### ISSUE TITLE
[Feature] Add a toggle to expand all sidebar listings

### ISSUE THREAD

**Issue by zaydek** [evanw/esbuild#1002]
I love the docs but I‘ve also wondered why it can feel frustrating at times to find something. I realized that the sidebar is not expanded by default, and by adding this functionality, the docs would be able to better serve power users without needing to implement something like search.

It would be nice if there was a button somewhere to enable the sidebar to be auto-expanded. By auto-expanded, I just mean showing all sublistings rather than only relying on scroll events to trigger a listing to expand. This would definitely be overwhelming for new users but for power users I think this is a missed feature.

The button could be at the bottom of the sidebar and when clicked, saves to localStorage so returning users don’t need to expand all options for subsequent visits.

For example:

Default:

```
**API**
- Transform API
- Build API
- Simple options
- Advanced options
- JS-specific details
```

When enabled (sidebar options, not only **API**, are always expanded):

```
**API**
- Transform API
- Build API
- Simple options
  - Bundle
  - Define
  - External
  - Format
  - Inject
  - Loader
  - Minify
  - Outdir
  - Outfile
  - Platform
  - Serve
  - Sourcemap
  - Splitting
  - Target
  - Watch
  - Write
- Advanced options
  - Asset names
  - Banner
  - Charset
  - Chunk names
  - Color
  - Conditions
  - Footer
  - Global name
  - Incremental
  - JSX factory
  - JSX fragment
  - Keep names
  - Log level
  - Log limit
  - Main fields
  - Metafile
  - Node paths
  - Out extension
  - Outbase
  - Preserve symlinks
  - Public path
  - Pure
  - Resolve extensions
  - Sourcefile
  - Sources Content
  - Stdin
  - Tree shaking
  - Tsconfig
  - Tsconfig raw
  - Working Directory
- JS-specific details
  - Running in the browser
```

I know you have landing pages like https://esbuild.github.io/api/#build-api to help with this but it’d be nice to have something like this be globally accessible from the sidebar. That, or a table of contents page with all options enumerated for all APIs (like https://esbuild.github.io/api/#build-api but for all APIs, not just build).

I think I prefer something like the expanded sidebar idea vs. a table of contents page just because it’s more immediate and requires no navigation.

**Comment by evanw** [comment]
I think I'd prefer to try just having the current page always be expanded. I'll try that.

**Comment by evanw** [comment]
This has been changed: https://esbuild.github.io/api/. Closing, although feel free to comment with follow-up thoughts if you'd like.

**Comment by zaydek** [comment]
@evanw Thank you, this is a welcome change!

There’s a certain coolness factor to having things expand on scroll but it also makes the site slightly less useful. I think this change will also help address some of the concerns in #824.
