### ISSUE TITLE
`unicode-13.0.0` npm package has been deprecated

### ISSUE THREAD

**Issue by Zuckjet** [evanw/esbuild#1003]
https://github.com/evanw/esbuild/blob/ab7e61ced8ff00ee171c9fee7ab8a1314ae674a7/scripts/package.json#L10

`unicode-13.0.0` npm package has been deprecated, see [details](https://www.npmjs.com/package/unicode-13.0.0).

 Recommend to use `@unicode/unicode-13.0.0`

**Comment by evanw** [comment]
I think this package is unused. I will try removing it.

**Comment by Zuckjet** [comment]
> I think this package is unused. I will try removing it.

One more question, I see this comment in unicode.go: https://github.com/evanw/esbuild/blob/5acc012756fe9e221e816f4ec489a495ad1f1ff6/internal/js_lexer/unicode.go#L1

In gen-unicode-table.js: https://github.com/evanw/esbuild/blob/7d987a220c396a44eea3e2765d28d6d3465063fb/scripts/gen-unicode-table.js#L4-L5

You mean unicode.go will not be changed any more ?

**Comment by evanw** [comment]
Ah that's where it was. I searched for `unicode-13.0.0` and it came up blank.

**Comment by Zuckjet** [comment]
Sorry for bothering, it seems I should send a PR for this small changes, but I think you may more like someone send a issue not a direct PR.

**Comment by evanw** [comment]
No worries. I don't mind either way. I'll fix it soon. Thanks for following up.
