### ISSUE TITLE
Can I specify chunk name when use code splitting?

### ISSUE THREAD

**Issue by Shigma** [evanw/esbuild#1008]
```js
// supposing there be a ./foo/index.js
// esbuild will generate an "index.xxxxxxxx.js" for it, which is quite confusing
// in this case, "foo.xxxxxxxx.js" will be better
import(/* chunkName: 'foo' */ './foo')
```

**Comment by mikecann** [comment]
@Shigma This was released just today: https://esbuild.github.io/api/#chunk-names

**Comment by evanw** [comment]
I agree that this isn't great, and I can try to make this better. However, I would like to know why you are asking for this. The name of the chunk (whatever it is) should automatically be substituted into the final output so it should continue to work. Are you trying to compute the name of the chunk to access it outside of esbuild somehow? Or is this just about aesthetics?

> @Shigma This was released just today: https://esbuild.github.io/api/#chunk-names

The chunk names feature wasn't released today (that was the entry names feature) and the chunk names feature doesn't help with this case.

**Comment by Shigma** [comment]
> I agree that this isn't great, and I can try to make this better. However, I would like to know why you are asking for this. The name of the chunk (whatever it is) should automatically be substituted into the final output so it should continue to work. Are you trying to compute the name of the chunk to access it outside of esbuild somehow? Or is this just about aesthetics?

Thanks for your quick response. Specifying chunk name will help me locate the original file of the generated chunk, so that I can plan a better code splitting. Currently there are so many `index.xxxx.js` in my dist folder. 🤣 

Also this is [a feature from webpack v4](https://v4.webpack.js.org/guides/code-splitting/#dynamic-imports). It seems thats webpack v5 [dropped it](https://webpack.js.org/blog/2020-10-10-webpack-5-release/#named-chunk-ids), but I have moved to esbuild before then.

**Comment by evanw** [comment]
With the latest release, chunk names should now be the name of the parent folder if the imported file is called `index`:

https://github.com/evanw/esbuild/blob/6cbfaca883cc61f709f726cb29037459bb31cfc0/internal/bundler/linker.go#L854-L865

So I believe this issue should now be resolved.

**Comment by bschlenk** [comment]
Just to add another use case, I'd like to be able to feature flag dynamic imports and have the backend throw an error if the user requesting the chunk isn't in the feature flag. The only way to do that would be to know the name of the chunk to be flagged.

**Comment by FirstWhack** [comment]
> With the latest release, chunk names should now be the name of the parent folder if the imported file is called `index`:
> 
> https://github.com/evanw/esbuild/blob/6cbfaca883cc61f709f726cb29037459bb31cfc0/internal/bundler/linker.go#L854-L865
> 
> So I believe this issue should now be resolved.

I apologize for bringing up this old issue... This behaviour does not exist anymore right? Is there any other way to influence chunk names now or always `chunk-XXX?`?
