### ISSUE TITLE
Dead code elimination on `--define` objects

### ISSUE THREAD

**Issue by davej** [evanw/esbuild#1011]
I realised that this is intentional but it would be nice to have an option to freeze any deep objects in `--define`.

This could be done using `Object.freeze()` and a `--freeze-define` option perhaps?

Something like this would be eliminated to an empty string:

```js
require("esbuild").transformSync(
  "if (foo.bar) { console.log('hi') }",
  {
    define: {
      foo: JSON.stringify({
        bar: false,
      }),
    },
    freezeDefine: true,
    minify: true,
  }
);
```

**Comment by zaydek** [comment]
I don’t know the backstory about frozen defines and how that effects dead-code elimination, but there’s JS API `Object.isFrozen` for detecting when an object is already frozen. Would it not make sense to just check that in Node? So you just use `define: Object.freeze({ ... }) ... Object.isFrozen(options.define)`.

That being said, that wouldn’t work for Go.

**Comment by evanw** [comment]
If you want `foo.bar` to be `false` you would do this instead:

```js
require("esbuild").transformSync(
  "if (foo.bar) { console.log('hi') }",
  {
    define: {
      'foo.bar': JSON.stringify(false),
    },
    minify: true,
  }
);
```

**Comment by davej** [comment]
@evanw Perfect. Thanks!

**Comment by davej** [comment]
@evanw Quick follow up, is there a way of doing something like this?

require("esbuild").transformSync(
  "if (foo[0]) { console.log('hi') }",
  {
    define: {
      'foo[0]': JSON.stringify(false),
    },
    minify: true,
  }
);

**Comment by evanw** [comment]
No, there isn't currently a way to do that. What's the real-world use case you are trying to accomplish? What is `foo`?
