### ISSUE TITLE
entryNames [dir] placeholder not replaced

### ISSUE THREAD

**Issue by joelmoss** [evanw/esbuild#1013]
Just playing with the new `entrynames` option:

`{ entryNames: '[dir]/[name]-[hash]' }`

And when built, I end up with `'public/froxy/build/[dir]/development-47KRCRWQ.js'`, which as you can see is literally using `[dir]`, instead of replacing it with the directory.

**Comment by evanw** [comment]
Whoops. This happened because I was extracting this feature from a larger rewrite. Looks like I somehow ported everything except the parser. Will fix.

**Comment by evanw** [comment]
A fix for this has been published in esbuild version 0.9.5.

**Comment by joelmoss** [comment]
thx for the quick turn around 👌
