### ISSUE TITLE
a `servedir` equivalent for watch mode - maybe `watchdir`?

### ISSUE THREAD

**Issue by osdevisnot** [evanw/esbuild#1014]
👋 @evanw - currently we can use esbuild as a standalone server with `servedir` option. I wish there was an equivalent (maybe `watchdir`?) option for watch mode to be able to use esbuild as standalone watcher.

This given us an ability to use esbuild's watcher to trigger rebuilds for our application (which might use external build system). 

Here is an example repository demonstrating such usage with next.js - https://github.com/osdevisnot/nextjs-custom-server-esbuild

In this repository, when one edits `pages/*.js` - we want `esbuild` to rebuild the `server/index.ts` so that next.js can rebuild those changes.

**Comment by zaydek** [comment]
@osdevisnot Checkout the new `watchFile` and `watchDirs` features just released for 0.10.0.

From the [changelog](https://github.com/evanw/esbuild/releases/tag/v0.10.0):

> * Allow plugins to return custom file watcher paths
> 
>     Currently esbuild's watch mode automatically watches all file system paths that are handled by esbuild itself, and also automatically watches the paths of files loaded by plugins when the paths are in the `file` namespace. The paths of files that plugins load in namespaces other than the `file` namespace are not automatically watched.
> 
>     Also, esbuild never automatically watches any file system paths that are consulted by the plugin during its processing, since esbuild is not aware of those paths. For example, this means that if a plugin calls `require.resolve()`, all of the various "does this file exist" checks that it does will not be watched automatically. So if one of those files is created in the future, esbuild's watch mode will not rebuild automatically even though the build is now outdated.
> 
>     To fix this problem, this release introduces the `watchFiles` and `watchDirs` properties on plugin return values. Plugins can specify these to add additional custom file system paths to esbuild's internal watch list. Paths in the `watchFiles` array cause esbuild to rebuild if the file contents change, and paths in the `watchDirs` array cause esbuild to rebuild if the set of directory entry names changes for that directory path.
> 
>     Note that `watchDirs` does not cause esbuild to rebuild if any of the contents of files inside that directory are changed. It also does not recursively traverse through subdirectories. It only watches the set of directory entry names (i.e. the output of the Unix `ls` command).

It’s not exactly what you’re asking for but does seem relevant.

**Comment by osdevisnot** [comment]
I changed the way builds work after opening this issue. So this is no longer needed.
