### ISSUE TITLE
Question: Embedding esbuild

### ISSUE THREAD

**Issue by sourcec0de** [evanw/esbuild#1015]
Hi all, amazing work everyone has done here!
I'm curious about leveraging some of esbuilds internals for another project.

1. Is it possible to access the parser and its resulting Typescript AST in Go?
2. Is it possible to supply `io.Reader` and `io.Writer` interfaces to the public [Go API][1]?
    1. Seems to be centralized around interacting with files or stdio.
    2. Is there a lower level public API that you would recommend?

Any insight would be greatly appreciated. 🙏

[1]: https://github.com/evanw/esbuild/blob/master/pkg/api/api.go

**Comment by evanw** [comment]
No, this is not possible. The parser and AST are deliberately internal implementation details of esbuild and are not intended for reuse. Sorry about that. Building a whole bundler is enough work without also building an extremely big API like this, so it's out of scope. Doing this would also heavily constrain potential future modifications to the parser and AST that could be necessary to improve the bundler, and the bundler is the primary goal of this project.

**Comment by sourcec0de** [comment]
@evanw thank you, this makes perfect sense!
I was actually just checking swc. Found my way there from deno.
