### ISSUE TITLE
class static getters service transform incorrect if set loader to 'ts'

### ISSUE THREAD

**Issue by aelbore** [evanw/esbuild#102]
I set the target to esnext should the static get props transform to function?
If you notice if I set the loader to 'js' it will output as expected but if i set loader to 'ts' the static get props turns to function.
The input code is valid typescript and javascript

```javascript
      const result = await service.transform(code, { 
        loader:  'ts', 
        sourcemap: true,
        target: 'esnext'
      })
```
Input Code
```typescript
export class HelloWorld {
  static get props() {
    return {
      name: {
        type: String
      }
    }
  }
} 
```
Actual Output
```js
class HelloWorld {  }

HelloWorld.props = function() {
   return {
      name: {
        type: String
      }
    }
}
```

Expected Output
```typescript
class HelloWorld {
  static get props() {
    return {
      name: {
        type: String
      }
    }
  }
} 
```

**Comment by evanw** [comment]
Thanks for the report! Sorry about that. I think the full scope of the bug is that static methods shouldn't ever be transformed, since they were in ES6 from the start. Will fix.
