### ISSUE TITLE
Logger writes to stderr not stdout?

### ISSUE THREAD

**Issue by zaydek** [evanw/esbuild#1024]
Not sure if this is intentional but the behavior slightly surprised me when I was working on something else. Here’s a minimal repro screenshot.

<img width="1083" alt="Screen Shot 2021-03-20 at 11 01 53 PM" src="https://user-images.githubusercontent.com/58870766/111872018-83100480-89d0-11eb-89a5-baef8579adcf.png">

**Comment by kzc** [comment]
Logging to stdout would interfere with pipes between processes.

```
$ echo 'console.log({a: 0, a: 1 ? 2 : 3})' | esbuild --minify | node
 > <stdin>:1:19: warning: Duplicate key "a" in object literal
    1 │ console.log({a: 0, a: 1 ? 2 : 3})
      ╵                    ^
   <stdin>:1:13: note: The original "a" is here
    1 │ console.log({a: 0, a: 1 ? 2 : 3})
      ╵              ^

1 warning
{ a: 2 }
```
```
$ echo 'console.log({a: 0, a: 1 ? 2 : 3})' | esbuild --minify 2>/dev/null | node
{ a: 2 }
```

**Comment by zaydek** [comment]
That makes sense. This is probably intentional behavior then. Thank you -- closing.

**Comment by hardfist** [comment]
It causes problems when esbuild is used in rushjs, which detect stderr output as warning, and it will terminate build if the build process generates warning info in CI environment.

**Comment by evanw** [comment]
This is what the [log level setting](https://esbuild.github.io/api/#log-level) is for:

> * `silent`
> Do not show any log output.
>
> * `error`
> Only show errors.
>
> * `warning`
> Only show warnings and errors.
>
> * `info`
> Show warnings, errors, and an output file summary. This is the default log level.
