### ISSUE TITLE
Could not resolve "vscode"

### ISSUE THREAD

**Issue by susiwen8** [evanw/esbuild#103]
Thanks for this great project, I want to use `esbuild` to build my vscode extension, but it throw `Could not resolve "vscode"`

Here is my option

```js
const options = {
    stdio: 'inherit',
    entryPoints: ['./src/extension.ts'],
    outfile: './dist/main.js',
    platform: 'node',
    minify: true,
    bundle: true,
    external: ['@microsoft/typescript-etw']
};
```

**Comment by evanw** [comment]
Your webpack config has this:

```js
externals: {
  vscode: 'commonjs vscode' // the vscode-module is created on-the-fly and must be excluded. Add other modules that cannot be webpack'ed, 📖 -> https://webpack.js.org/configuration/externals/
},
```

I assume that means you'll also have to make the `vscode` module an external module for esbuild too (by adding it to the `external` array).

**Comment by susiwen8** [comment]
You were right, Thanks!
