### ISSUE TITLE
ReferenceError: __name is not defined

### ISSUE THREAD

**Issue by sto3psl** [evanw/esbuild#1031]
Hi there, first of all, thanks for all the hard work you put into esbuild, it's awesome!

I have an issue with the `keepNames` option of esbuild. First of all some info about versions. I'm using esbuild through Vite.

* Vite Version: 2.1.2
* `esbuild` version: 0.9.6

What's happening is, that esbuild is bundling a file, where it renames the functions and then adds a `__name` function like so:

```js
// source
function init () {}

// output
function init3 () {}
__name(init3, 'init')
```

The problem is, that the `__name` function never gets defined in my module, which is causing the error `ReferenceError: __name is not defined` in the browser.

The actual input and output files are in this Gist: https://gist.github.com/sto3psl/8bca4562096050559ec51544483edc33

Here are the references with the above mentioned `init` function:

* Source: https://gist.github.com/sto3psl/8bca4562096050559ec51544483edc33#file-av-surface-ts-L238-L263
* `esbuild` output: https://gist.github.com/sto3psl/8bca4562096050559ec51544483edc33#file-after-esbuild-js-L35-L58

There are a bunch of `__name` references in the `esbuild` output but no definition of said function. I'm not sure what's happening but if it helps, this file does run in a Worker. If for some optimization reasons `__name` is defined on `window` or in the main thread in general, it isn't accessible in the Worker.

I'd appreciate any help and am not sure if this is a Vite or `esbuild` problem.

This is the Vite commit that introduced the `keepNames` behaviour: https://github.com/vitejs/vite/commit/b5cd8c8dc33e920a301ef03c097147d841d08200

**Comment by flunderpero** [comment]
This comes up in other places too, like #607

**Comment by evanw** [comment]
> The actual input and output files are in this Gist: https://gist.github.com/sto3psl/8bca4562096050559ec51544483edc33

This doesn't look like output from esbuild. The code generator doesn't generate blank lines like that. So I assume something else is happening after esbuild runs that is messing this up.

Another thing to note is that esbuild is not designed to preserve the value of `Function.prototype.toString()`. It assumes that the JavaScript it builds follows the normal scoping rules. So the `__name` helper (along with all of the other helpers that esbuild uses) is defined once at the top-level scope instead of being re-defined in every single function scope.

This means you can't just call `.toString()` on a function and eval it somewhere else to relocate it. Just disabling the `keepNames` option is not a robust approach because other helpers such as `__publicField` for class fields will also behave similarly. Although you could potentially ask Vite to provide the option to disable this to unblock you.

So if you're using code inside a worker make sure you're not calling `.toString()` on a function. Instead you should be bundling the code for the worker into another entry point and either including that bundled code as a string in your final output, or referencing the bundled file via URL in the worker constructor.

**Comment by sto3psl** [comment]
Do you have an idea what the actual problem is and if it's an issue with Vite? I don't call `.toString()` anywhere but looking at my project the worker code is loaded as a `Blob` from Vite. 

The output I pasted came out of the sources panel of Firefox DevTools, so that might explain the blank lines.

After running `esbuild` isolated over the specified file, the first two lines are
```js
var __defProp = Object.defineProperty;
var __name = (target, value) => __defProp(target, "name", {value, configurable: true});
```

This is what I'd expect and maybe Vite removes them for some reason?

I'm a little lost here but I guess I'm going to open an issue with Vite.

**Comment by sto3psl** [comment]
I just checked the library I'm using and how it creates the Worker. Turns out this is the code:

```js
export function makeWorkerBlob(func: Function, deps: Function[]) {
  let str = "'use strict';\n\n" + makeWorkerString(deps);
  str += "\n\n\nself.func = " + func.toString() + ";";
  str += "\n\n\nself.onmessage = " + onmessage.toString() + ";";
  // console.log(str);
  return new Blob([str], { type: "application/javascript" });
}
```

To summarize `esbuild` does the correct thing and deduplicates `__name` and because of the `.toString()` this of course won't end up in the worker scope. 

Now I need to figure out, how I can fix this in the library. 

Thanks anyway @evanw, you pointed me in the right direction.

**Comment by flunderpero** [comment]
I really support @evanw point of view on this. 
But there seem to be some libraries out there ([canvas-confetti](https://github.com/catdad/canvas-confetti) being another one) that generally use workers that way and those libraries fail with esbuild. As @evanw pointed out it is not only `keepNames` that could potentially break the code.
I don't have an idea on how to fix this or if it's even worth fixing it. Not being able to bundle (quite popular) libraries is at least surprising.

**Comment by evanw** [comment]
I think the most straightforward solution here is that Vite should not have this option force-enabled. I left a comment about this here: https://github.com/vitejs/vite/pull/2376#issuecomment-805285480.

**Comment by sto3psl** [comment]
Thanks for your help with this @evanw!

**Comment by itsthekeming** [comment]
So it's probably an issue with Vite? I am encountering this issue using Vite and [@react-three/drei](https://github.com/pmndrs/drei)'s `useGLTF` hook.

The hook loads a [draco](https://github.com/google/draco) decompressor from a static url that I think uses a worker. I have similar code in my browser dev-tools as @sto3psl, and the same `__name is not defined` error for each node from my loaded GLTF file that draco tries to decompress.

I'm not super familiar with the intricacies of web workers. I did set `keepNames` in my Vite config to `false` but the issue persists.

**Comment by itsthekeming** [comment]
Vite just merged pull request [#2742](https://github.com/vitejs/vite/pull/2742) that fixes this issue, so this can probably be closed.

**Comment by evanw** [comment]
Thanks for the update. Closing as this will be fixed in the next Vite release.

**Comment by Fuphoenixes** [comment]
> @evanw @sto3psl 你解决了吗？我也遇到这个问题，在CICD中。本地就可以了。https://github.com/lixiaofa/fast-plus/actions/runs/5443372337/jobs/9900013548 ![图像](https://user-images.githubusercontent.com/23230215/250937962-9bbfa7ab-0a3f-4ee9-a97a-7c3afbbd3d98.png) [](https://github.com/lixiaofa/fast-plus/actions/runs/5443372337/jobs/9900013548)

你解决了吗？我和遇到了一样的问题

**Comment by Mike-Bell** [comment]
another place where this comes up (currently): https://github.com/microsoft/onnxruntime/issues/18673

**Comment by Maxim-Mazurok** [comment]
I'm having this error inside of `await page.evaluate(async () => {...}` code for puppeteer. It adds `__name` to my arrow function for some reason

**Comment by ArcherGu** [comment]
@Maxim-Mazurok I encountered the same issue when using puppeteer. This code actually executes in the page context, but auxiliary functions like __name aren't brought into the page context, resulting in an error.

Currently, I've had no choice but to avoid using named functions in this code or simply pass them in as function strings.

Do you have a better way to deal with this problem? Thank you very much

**Comment by Maxim-Mazurok** [comment]
@ArcherGu I just switched back to [ts-node](https://www.npmjs.com/package/ts-node) from tsx.

I was migrating my personal nx monorepo from ts-node to tsx, but IIRC many things didn't work, so I just switched back. To make ts-node work in my setup I use `node -r ts-node/register -r tsconfig-paths/register {your_script_here}`, I guess it's a bit slower than tsx, but still fairly solid option if you need a fast and easy solution here...

Also here's another workaround: https://github.com/evanw/esbuild/issues/2605#issuecomment-2785610064

Hope this helps, cheers!

**Comment by qq1012827513** [comment]
got it! 
``` js
await page.evaluate(`(() => {
  window.__name = (fn) => fn;
})()`)
