### ISSUE TITLE
Strict Mode and File Name Comments

### ISSUE THREAD

**Issue by moonglum** [evanw/esbuild#1032]
First of all: Thanks for this awesome tool ❤️ 

I noticed two things when building files with esbuild with the following configuration:

```js
esbuild.buildSync({
  entryPoints: [entryPoint],
  bundle: true,
  write: false,
  charset: "utf8"
});
```

# Missing "use strict" in the IIFE

The generated IIFE does not contain the `"use strict"` that most bundlers inject to activate strict mode. Is this on purpose? I could not find a way to activate it (the `banner` is inserted before the IIFE).

# Source file names as comments

The generated source contains the file names as comments:

```js
(() => {
  // src/util.js
  var util_default = "UTIL";

  // src/index.js
  console.log(`[…] ${util_default}`);
})();
```

Is there a way to deactivate it? The only way I found was to run it with `minifyWhitespace: true`.

**Comment by evanw** [comment]
Both of these are by design. Strict mode can be enabled by setting a banner with `"use strict";` in it. It shouldn't matter whether it's outside or inside the IIFE since strict mode applies to all nested scopes. It is also by design that the way to remove comments is with `minifyWhitespace: true`.

**Comment by moonglum** [comment]
Ok, thank you 🙇
