### ISSUE TITLE
With splitting on, outdir nests all output deeply in subfolders when dependencies async import

### ISSUE THREAD

**Issue by dzearing** [evanw/esbuild#1041]
I have an app which imports a utility `log` from a utility library. Bundling/splitting/esm is on, outdir is `dist` and my entry is `src/index.ts`.

When I build and look at the outdir, I see a single `index.js` bundle with the log utility. So far so good.

Now, the utility library exports a function (which I'm not using) with async import:

```js
export { log } from './log';

export async function foo() {
  (await import(''./bar")).bar();
}
```

Even though my app does not care about the new `foo` export, the app's dist folder structure becomes completely munged.

Before the `foo` export (Expected!)
```bash
dist/
  index.js
```

After the export (Not expected):

```bash
dist/
  apps/
    app/
      src/
         index.js
  packages/
    utilities/
      /lib/
        otherThing.js
```

I did not expect the library to alter the output folder structure so significantly. It becomes completely unpredictable to know where your bundle gets dropped if dependencies can simply make a small code change to move around unrelated bundles. The output folder should remain stable and not be influenced by libraries adding async imports.

I have created an isolated repro here with steps in the readme:

https://github.com/dzearing/esbuild-split-repro

**Comment by lukeed** [comment]
This was recently solved – mention of it in the [`0.9.4` release notes](https://github.com/evanw/esbuild/releases/tag/v0.9.4)

**Comment by dzearing** [comment]
I am using `0.9.6`.

**Comment by lukeed** [comment]
Right, but you have to use the entry names option to flatten output tree.

**Comment by dzearing** [comment]
@lukeed you're right! adding `entryNames` to the config did the trick. Thank you!
