### ISSUE TITLE
Changed files in `onRebuild` result when using watch mode

### ISSUE THREAD

**Issue by Zertz** [evanw/esbuild#1047]
Would it be possible to get a list of changed files in `onRebuild` result when using watch mode? This would be useful to run code based on files changes. For example, if there are only CSS files, we could tell the client to only reload those and not do a full page reload.

I'm not familiar with internals so I'm not sure if this is feasible?

**Comment by zaydek** [comment]
I like this idea. Having access to the files changes would make logs, etc. more descriptive / actionable.

**Comment by lukeed** [comment]
Not at my desk, but I think you get this if you have `write: false`? That's just to say that I assume it should be possible to include a list of the same files' paths (imo) when `write` is enabled

**Comment by Zertz** [comment]
> Not at my desk, but I think you get this if you have `write: false`? That's just to say that I assume it should be possible to include a list of the same files' paths (imo) when `write` is enabled

I haven't tested this but it seems like `outputFiles` would contain the entire build result and not just changed files?

**Comment by evanw** [comment]
You can determine which output files have changed by comparing them with their previous contents. That can either be done with `write: false` or with `write: true, metafile: true` and then going through the paths in the returned metadata.
