### ISSUE TITLE
[Feature] onRebuild result should contain metafile if options ask for it

### ISSUE THREAD

**Issue by dzearing** [evanw/esbuild#1057]
When using watch mode, the metafile is returned from the initial build result, but not in the results from `onRebuild`when things change. I'd like to access the bundle metadata if possible when rebuilding (assuming `metafile: true` is set in options.) This would enable some interesting scenarios such as live updates on dev tools for monitoring bundle size, chunk changes over time, etc.

**Comment by evanw** [comment]
Thanks for the report. This was not intentional, and was just an oversight. Will fix.
