### ISSUE TITLE
[Request] Expose `Message.details` formatter

### ISSUE THREAD

**Issue by lukeed** [evanw/esbuild#1058]
There's quite a bit of logic going into logging the messages, specifically [the details](https://github.com/evanw/esbuild/blob/master/internal/logger/logger.go#L1051).

Would it be possible to expose this function on the `Message` interface itself? Perhaps it only appears when `logLevel` is silent. 

Specifically, I'd like to customize the "text" portion of each message & then use esbuild's formatted details.

***Current***
<img width="471" alt="Screen Shot 2021-03-25 at 11 42 41 AM" src="https://user-images.githubusercontent.com/5855893/112526603-5efd4c00-8d5f-11eb-816d-49f15e7574aa.png">

***Customized***
<img width="429" alt="Screen Shot 2021-03-25 at 11 42 48 AM" src="https://user-images.githubusercontent.com/5855893/112526611-60c70f80-8d5f-11eb-88fa-98e0ef59c658.png">

AFAIK, there's no way to catch-n-rewrite the stdout since this is `build` & esbuild writes it directly. 
I can (and was) reimplement the output in the JS wrapper layer, but this feels a little silly given that the code is already included.

Perhaps the usage could look something like this:

```js
// errors (or warnings)
let output = `Build failed with ${err.errors.length} error(s):`;
err.errors.forEach(msg => {
  output += '\n  ' + colors.inverse(msg.location.file) + ' ' + msg.text;
  output += '\n  ' + msg.details(); // or msg.frame() --> esbuild's code formatter
});
console.error(output);
```

**Comment by zaydek** [comment]
@lukeed Check this out https://github.com/evanw/esbuild/issues/920. May help answer some of your questions.

You should be able to disable logs with `logLevel: "silent"` and then inspect `result.warnings`. I’m doing something like this currently, although with my new approach I don’t think I need to anymore:

```js
const response = {
  warnings: [],
  errors: [],
}

try {
  result = await esbuild.build({
    // ...
  })
  if (result?.warnings?.length > 0) {
    response.warnings = result.warnings
  }
} catch (error) {
  if (error?.errors?.length > 0) {
    response.errors = error.errors
  }
  if (error?.warnings?.length > 0) {
    response.warnings = error.warnings
  }
}

// ...
```

**Comment by lukeed** [comment]
@zaydek thank you -- I'm aware I can do this. I'm in agreement with the other thread. My point here is that _because_ esbuild's formatting is so good & covers so many edge cases, that I don't even want to attempt to reimplement the same coverage in my JS layer. Instead, I'm hoping esbuild's formatting is available as a new method on the Message object.

**Comment by evanw** [comment]
I think the way to solve this would be to expose a top-level API to format a message object. I want to keep message objects serializable so I don't want to put a method on the messages themselves. And splitting off the detail part seems unnecessary when you can easily just remove the first line.

**Comment by lukeed** [comment]
Sounds good to me!

**Comment by lukeed** [comment]
Amazing 🙌 thanks!

**Comment by zaydek** [comment]
Nice work Evan. This actually solves a problem I didn’t know I had. I can defer to esbuild now for logging aesthetics, which is amazing.

@lukeed Does this solve your problem? This look almost like a solution to a different problem if I’m not mistaken -- I thought what you were asking for is the ability to customize message UI before logging it. If this does solve your problem, do you mind sharing an example of how you’re using this feature?

**Comment by lukeed** [comment]
Nope, this is exactly what I was after. I wanted to access esbuild's existing formatting so that I could call it programmatically. 

I was hesitant to suggest a top-level API change, but this is definitely the better option.

**Comment by zaydek** [comment]
If you don’t mind, could you show how you plan on using the API with your original example?

> ```js
> // errors (or warnings)
> let output = `Build failed with ${err.errors.length} error(s):`;
> err.errors.forEach(msg => {
>   output += '\n  ' + colors.inverse(msg.location.file) + ' ' + msg.text;
>   output += '\n  ' + msg.details(); // or msg.frame() --> esbuild's code formatter
> });
> console.error(output);
> ```

**Comment by lukeed** [comment]
@zaydek No problem. Yes, multiple times _or_ once with all messages & then iterate thru the returned array:

```js
// errors (or warnings)
let output = `Build failed with ${err.errors.length} error(s):`;
let formatted = await esbuild.formatMessages(err.errors, { kind: 'error' });

formatted.forEach(str => {
  // optionally modify the output esbuild gave me
  // for example, remove the 1st line.. whatever
  
  output += '\n  ' + str;
});
console.error(output);
```

**Comment by zaydek** [comment]
@lukeed Thank you! Nice work getting this implemented so quickly.

**Comment by lukeed** [comment]
I contributed nothing 😂
