### ISSUE TITLE
esbuild minifySyntax shouldn't convert string with \n into template literals in target es6

### ISSUE THREAD

**Issue by ycjcl868** [evanw/esbuild#1060]
I use esbuild mainly to use the compression feature, i.e. [src/index.ts#L17-L29.](https://github.com/umijs/plugins/blob/master/packages/plugin-esbuild/src/index.ts#L17-L29.)

When my source code is `var a = 'Hello\nWorld'`, the compiled result is actually 
```js
var a=`Hello\nWorld`;
```

**template strings**(the backtick syntax) will not work under IE 11

<img src="https://user-images.githubusercontent.com/13595509/112563198-1dd45e80-8d96-11eb-9609-7272fc113d38.png" width="150" />

The minimum reproduction code is as follows:

```js
(async () => {
  const { transform } = require('esbuild');

  const result = await transform(
    "var a = 'Hello\\nWorld';var b = 'Hello World';",
    {
      minify: true,
      // minifySyntax: true,
    },
  );
  console.log('result', result.code);
  // expect: var a = "Hello\nWorld,b="Hello World""
  // result: var a=`Hello\nWorld`,b="Hello World";
})();

```

**Comment by evanw** [comment]
Template literal syntax is part of ES6+. If you cannot use ES6, then you should use `target: 'es5'`.

**Comment by ycjcl868** [comment]
> Template literal syntax is part of ES6+. If you cannot use ES6, then you should use `target: 'es5'`. More information about the target feature is here: https://esbuild.github.io/api/#target.

I hope the string syntax can be as backward compatible as possible, I don't want to convert the es5 string to the es6 template string.

https://github.com/evanw/esbuild/blob/ff2db90dd58e7f0a1d223648d8a4de604c2445f5/internal/js_printer/js_printer.go#L1197-L1206

**Comment by evanw** [comment]
This happens because the target defaults to `esnext`, which means template literals are supported. If template literals are not supported, you need to pass `target: 'es5'`.

**Comment by ycjcl868** [comment]
> This happens because the target defaults to `esnext`, which means template literals are supported. If template literals are not supported, you need to pass `target: 'es5'`.

ok, maybe it should be noted in the documentation, I can help it.

**Comment by ycjcl868** [comment]
> This happens because the target defaults to `esnext`, which means template literals are supported. If template literals are not supported, you need to pass `target: 'es5'`.
> 
> 

I need to decide whether the target is `es5` through browserList.
