### ISSUE TITLE
Loader option appear to match any part of the filename

### ISSUE THREAD

**Issue by parkertomatoes** [evanw/esbuild#1061]
I tried to use the work-around from this issue, which adds a plugin for ".node", to load a native extension:
https://github.com/evanw/esbuild/issues/1051

This worked great, but failed after I tried to add the "threads" npm package and build my application:
```
 > node-file:<PATH>\node_modules\threads\dist\master\implementation.node.js:2:25: error: Could not resolve "<PATH>\\node_modules\\threads\\dist\\master\\implementation.node.js" (the plugin "native-node-modules" didn't set a resolve directory)
    2 │         import path from "<PATH>\\node_modules\\threads\\dist\\master\\implementation.node.js"
```

This line which sets the default loader appears to have matched a file in that library named `implementation.node.js`:
```js
    opts.loader['.node'] = 'file'
```

Meanwhile the plug-in API allows regular expressions and appears to have not matched it, causing an error:
```js
    build.onResolve({ filter: /\.node$/, namespace: 'file' }, args => ({
```

Removing the `$` from the regular expressions prevents the error (but still breaks my application because that file is not assigned to the correct loader)

Is there a way to make the "loader" option only match files _ending_ with that extension?

I'm using version 0.10.0

**Comment by evanw** [comment]
I think there might be something else going on. Doing what you described above works fine for me on both macOS and Windows. Here's what I tried (install `esbuild` and `threads` before running):

```js
const nativeNodeModulesPlugin = {
  name: 'native-node-modules',
  setup(build) {
    // If a ".node" file is imported within a module in the "file" namespace, resolve
    // it to an absolute path and put it into the "node-file" virtual namespace.
    build.onResolve({ filter: /\.node$/, namespace: 'file' }, args => ({
      path: require.resolve(args.path, { paths: [args.resolveDir] }),
      namespace: 'node-file',
    }))

    // Files in the "node-file" virtual namespace call "require()" on the
    // path from esbuild of the ".node" file in the output directory.
    build.onLoad({ filter: /.*/, namespace: 'node-file' }, args => ({
      contents: `
        import path from ${JSON.stringify(args.path)}
        try { module.exports = require(path) }
        catch {}
      `,
    }))

    // If a ".node" file is imported within a module in the "node-file" namespace, put
    // it in the "file" namespace where esbuild's default loading behavior will handle
    // it. It is already an absolute path since we resolved it to one above.
    build.onResolve({ filter: /\.node$/, namespace: 'node-file' }, args => ({
      path: args.path,
      namespace: 'file',
    }))

    // Tell esbuild's default loading behavior to use the "file" loader for
    // these ".node" files.
    let opts = build.initialOptions
    opts.loader = opts.loader || {}
    opts.loader['.node'] = 'file'
  },
}

require('esbuild').build({
  entryPoints: ['threads'],
  bundle: true,
  outdir: 'out',
  plugins: [nativeNodeModulesPlugin],
})
```

The plugin code was copied verbatim from https://github.com/evanw/esbuild/issues/1051#issuecomment-806325487. Is there anything about this code that is different from what you're doing? Or can you provide code code to reproduce the issue?

**Comment by parkertomatoes** [comment]
You're right that it's probably something else. I can consistently reproduce inside the project I found it in, but your code works for me and I couldn't reproduce it outside.

**Comment by ibilux** [comment]
@evanw how to use this code with vite and js to load .node file ?

**Comment by evanw** [comment]
I don’t use Vite at all. You are welcome to ask that question on their forum yourself.
