### ISSUE TITLE
Question: How to build React components for distribution on npm

### ISSUE THREAD

**Issue by gkjohnson** [evanw/esbuild#1062]
Hello! I'm building some packages with reusable React Components that I expect to be installed as dependencies by some internal applications and I am trying to build the dist files with esbuild. I'm building the files as an installable package so I don't want all node_modules dependencies inlined which is why I'm not using `--bundle`. Instead I'm listing all the files to be included in the package in the command line arguments (in practice I'm using globs or the js API):

```
esbuild index.jsx TestComponent.jsx --outdir=./dist/
```

In this example `index.jsx` imports `./TestComponent.jsx`. However after running the above command the dist folder includes `index.js` and `TestComponent.js` but `index.js` still imports `./TestComponent.jsx` causing it to fail to build when installed and bundled as a dependency.

Is there a way to achieved what I'm trying to do? Either bundle all non-node_module dependencies in my package as a single file or have `index.js` adjusted to import `./TestComponent.js` after build?

Here's zip with the above-mentioned example case. Just run "npm install" then "npm run build" to get the invalid files in ./dist.

[example.zip](https://github.com/evanw/esbuild/files/6208769/example.zip)

Thanks in advance for your help! And sorry if I'd missed something when looking through the docs.

**Comment by evanw** [comment]
Import paths are only transformed when bundling. You could potentially bundle each file individually but with a plugin that marks all import paths other than the entry point as external, and changes their paths as appropriate. Plugin documentation is here: https://esbuild.github.io/plugins/#resolve-callbacks.

**Comment by jridgewell** [comment]
Can you just mark each of the node modules external? Something like `esbuild index.jsx --bundle --external:react-dom --external:react --outdir=./dist/ ` would work for your case.

> Import paths are only transformed when bundling

@evanw: Is there a reason the outdir changes the file extensions when transforming?

**Comment by evanw** [comment]
> @evanw: Is there a reason the outdir changes the file extensions when transforming?

Yes. The output file extension defaults to `.js` because preserving the file extension is often not a good idea. For example, compiling `.ts` or `.jsx` to JavaScript but keeping the extension will break imports with implicit extensions in node because node does not (by default) implicitly add extensions other than `.js`, `.json`, or `.node` (see [node's documentation about this](https://nodejs.org/api/modules.html#modules_all_together)). If you want esbuild to output files with a different extension, you can use this feature: https://esbuild.github.io/api/#out-extension.

**Comment by gkjohnson** [comment]
Thanks after trying a few things I landed on reading all the dependencies from my package.json and adding them to the "externals" array while setting "splitting" and "bundle" to true. Coming from rollup it might be nice if "externals" could be a function that takes the resolved and / or unresolved path and returns whether it should be treated as an external dependency to handle cases like this.

And FWIW I want files to be changed to ".js" for distribution so end users don't have to concern themselves with setting up their build process for dealing with file formats I've chosen to use in my library.

Thank you again!

**Comment by Adam-Collier** [comment]
@gkjohnson could you share how you did this please? Does this capture peer dependencies too?

**Comment by gkjohnson** [comment]
> could you share how you did this please? Does this capture peer dependencies too?

I don't have the code in front of me but it's pretty simple. Just read the names of the dependencies from the package.json and add them to the "externals" array. If you want to include peerDependencies you can just add those, as well:

```js
const packagejson = require( './path/to/package.json' );
const external = Object.keys( packagejson.dependencies );

// ...

buildSync( {
  // ...
  splitting: true,
  bundle: true,
  external,
} );
```
