### ISSUE TITLE
[mvp]: Esbuild starter app

### ISSUE THREAD

**Issue by gopal-virtual** [evanw/esbuild#1068]
Hello folks, I've created an Esbuild starter app, to help people get started with the same quickly. You can try it out here https://www.npmjs.com/package/@gvirtual/create-esbuild-starter

A couple of pointers
- Currently, it can be bootstrapped only with React with Styled Components
- I've intentionally kept out CSS bundling due to this open issue #465 
- I'm planning to add other standard templates, based on community demand

Any feedback or contribution is highly appreciated. Thank you.

**Comment by evanw** [comment]
This is a cool package. However, this is not an issue with esbuild, so I'm going to close this issue.
