### ISSUE TITLE
Unexpected minify result

### ISSUE THREAD

**Issue by forehalo** [evanw/esbuild#108]
esbuild version: 0.2.11

reproduce link: https://codesandbox.io/s/elastic-frost-kbiwh?file=/routes/index.js

### Description
I was trying to use esbuild to uglify my bundles, but the result esbuild outputs has unexpected content cause errors.

### Way to reproduce
Open the reproduce link, searching for definition of `getQueryVariable` function after the result shown. You will see:

![image](https://user-images.githubusercontent.com/8281226/81777108-be28e800-9522-11ea-9d60-4f3cbabcf32f.png)

after prettier:

```js
function getQueryVariable(a) {
  for (var b = d.split("&"), c = 0; c < b.length; c++) {
    var d = b[c].split("="); // #line 3
    if (decodeURIComponent(d[0]) == a) return decodeURIComponent(d[1]);
  }
}
var standalone = "__[STANDALONE]__",
  animationData = "__[ANIMATIONDATA]__",
  renderer = "";
if (standalone) {
  var a = document.getElementsByTagName("script"),
    b = a.length - 1,
    c = a[b] || { src: "" },
    d = c.src.replace(/^[^\?]+\??/, ""); // #line 14
  renderer = getQueryVariable("renderer");
}
```

Check the function `getQueryVariable`. there is a for loop that defined a variable `d` internally(`line 3`) which will cover the one defined at `line 14`. The one at `line 3` will be hoisted to the very first of `getQueryVariable` and given value `undefined`. this will cause the initial statement of for loop `var b = d.split("&")` throws `Cannot read property 'split' of undefined`

The minimization results of `terser` and `uglify-js` are provided as well for comparison, seems they both didn't touch closure variables:

```js
// terser
function getQueryVariable(t) {
  for (var e = queryString.split("&"), r = 0; r < e.length; r++) {
    var i = e[r].split("=");
    if (decodeURIComponent(i[0]) == t) return decodeURIComponent(i[1]);
  }
}

// uglify-js
function getQueryVariable(t) {
  for (var e = queryString.split("&"), i = 0; i < e.length; i++) {
    var r = e[i].split("=");
    if (decodeURIComponent(r[0]) == t) return decodeURIComponent(r[1]);
  }
}

```

**Comment by evanw** [comment]
Thanks for the report. It looks like the way to reproduce this is to minify the file https://unpkg.com/lottie-web@5.6.10/build/player/lottie.js. It appears to be a bad interaction between the use of direct eval and a hoisted variable declared in a separate branch of the scope tree.
