### ISSUE TITLE
Code splitting is more broken with esbuild 0.10.1

### ISSUE THREAD

**Issue by iamakulov** [evanw/esbuild#1081]
Likely related to #399.

This is JFYI. I remember that code splitting is not fully supported, but with ~~0.11.0~~ 0.10.1, it seems to be even more broken. On the Framer codebase, it generates

**a) cyclic dependencies between chunks** that lead to `undefined is not a function` errors

<details>

   <summary>Example</summary>

   If I upgrade to esbuild 0.11.0 and try to run Framer, I’ll get the following error:

   <img width="1012" alt="Screen Shot 2021-03-29 at 16 52 05 1" src="https://user-images.githubusercontent.com/2953267/112839323-1c18dc80-90af-11eb-98b0-a84684003191.png">

   The error happens because, in `chunk-PLL4RMKF.js`, Sentry tries to call `__extends` from `tslib`, and `__extends` is undefined:

   <img width="1012" alt="Screen Shot 2021-03-29 at 16 52 35" src="https://user-images.githubusercontent.com/2953267/112839389-3652ba80-90af-11eb-99e7-dc0a752ed3b4.png">

   But why is it undefined? If we search by `__extends`, we’ll find that it’s imported from another chunk called `chunk-EZ2R6UVJ.js`:

   <img width="1012" alt="Screen Shot 2021-03-29 at 16 55 35" src="https://user-images.githubusercontent.com/2953267/112839761-977a8e00-90af-11eb-9534-00993e57e9fc.png">

   That chunk exports `__extends` absolutely correctly:

   <img width="1012" alt="Screen Shot 2021-03-29 at 16 56 19" src="https://user-images.githubusercontent.com/2953267/112839871-bd079780-90af-11eb-8bb5-f60c5c86a41e.png">
   <img width="1012" alt="Screen Shot 2021-03-29 at 16 56 24" src="https://user-images.githubusercontent.com/2953267/112839864-ba0ca700-90af-11eb-9d09-57de87090d9b.png">

   but what it also does is it imports a few symbols from the first chunk (`chunk-PLL4RMKF.js`):

   <img width="1012" alt="Screen Shot 2021-03-29 at 16 58 28" src="https://user-images.githubusercontent.com/2953267/112840115-ff30d900-90af-11eb-8e74-3564fc84637f.png">

   So, ultimately, the following happens:
   * some code imports `chunk-EZ2R6UVJ.js`
   * that chunk imports `chunk-PLL4RMKF.js`
   * `chunk-PLL4RMKF.js` initializes and tries to call `__extends` from `chunk-EZ2R6UVJ.js`
   * because `chunk-EZ2R6UVJ.js` haven’t initialized yet, `__extends` is undefined.

Here’s the contents of chunk `chunk-EZ2R6UVJ.js`:

```
// ../../../node_modules/tslib/tslib.js
// ../../../node_modules/tslib/modules/index.js
// ../../shared/src/assert.ts
// ../../shared/src/warnOnce.ts
// ../../shared/src/deprecation.ts
// ../../shared/src/errors.ts
// ../../shared/src/lazy.ts
// ../../shared/src/logger.ts
// ../../shared/src/ServiceMap.ts
// ../../shared/src/moduleIdentifiers.ts
// ../../shared/src/ResolvablePromise.ts
// ../../services/src/runtime/typescript/ServiceChannel.ts
// ../../services/src/runtime/typescript/ServiceDebugging.ts
// ../../services/src/runtime/typescript/streams/private.ts
// ../../services/src/runtime/typescript/private.ts
// ../../services/src/runtime/typescript/ServiceErrors.ts
// ../../services/src/runtime/typescript/environment.ts
// ../../services/src/runtime/typescript/ServiceManager.ts
// ../../services/src/runtime/typescript/streams/ServiceEventEmitter.ts
// ../../services/src/runtime/typescript/channels/LocalChannel.ts
// ../../services/src/runtime/typescript/channels/MessagePortChannel.ts
// ../../services/src/runtime/typescript/channels/PostMessageChannel.ts
// ../../services/src/runtime/typescript/channels/SocketClientChannel.ts
// ../../services/src/generated/typescript/index.ts
// src/environment/index.ts
```

Here’s the contents of chunk `chunk-PLL4RMKF.js`:

```
// ../../../node_modules/@sentry/utils/esm/is.js
// ../../../node_modules/@sentry/utils/esm/browser.js
// ../../../node_modules/@sentry/utils/esm/polyfill.js
// ../../../node_modules/@sentry/utils/esm/error.js
// ../../../node_modules/@sentry/utils/esm/dsn.js
// ../../../node_modules/@sentry/utils/esm/node.js
// ../../../node_modules/@sentry/utils/esm/string.js
// ../../../node_modules/@sentry/utils/esm/misc.js
// ../../../node_modules/@sentry/utils/esm/logger.js
// ../../../node_modules/@sentry/utils/esm/memo.js
// ../../../node_modules/@sentry/utils/esm/stacktrace.js
// ../../../node_modules/@sentry/utils/esm/object.js
// ../../../node_modules/@sentry/utils/esm/supports.js
// ../../../node_modules/@sentry/utils/esm/instrument.js
// ../../../node_modules/@sentry/utils/esm/path.js
// ../../../node_modules/@sentry/utils/esm/syncpromise.js
// ../../../node_modules/@sentry/utils/esm/promisebuffer.js
// ../../../node_modules/@sentry/utils/esm/time.js
// ../../../node_modules/@sentry/hub/esm/scope.js
// ../../../node_modules/@sentry/types/esm/session.js
// ../../../node_modules/@sentry/types/esm/severity.js
// ../../../node_modules/@sentry/types/esm/status.js
// ../../../node_modules/@sentry/hub/esm/session.js
// ../../../node_modules/@sentry/hub/esm/hub.js
// ../../../node_modules/@sentry/minimal/esm/index.js
// ../../../node_modules/@sentry/core/esm/api.js
// ../../../node_modules/@sentry/core/esm/integration.js
// ../../../node_modules/@sentry/core/esm/baseclient.js
// ../../../node_modules/@sentry/core/esm/transports/noop.js
// ../../../node_modules/@sentry/core/esm/basebackend.js
// ../../../node_modules/@sentry/core/esm/request.js
// ../../../node_modules/@sentry/core/esm/sdk.js
// ../../../node_modules/@sentry/core/esm/version.js
// ../../../node_modules/@sentry/core/esm/integrations/index.js
// ../../../node_modules/@sentry/core/esm/integrations/functiontostring.js
// ../../../node_modules/@sentry/core/esm/integrations/inboundfilters.js
// ../../../node_modules/@sentry/browser/esm/tracekit.js
// ../../../node_modules/@sentry/browser/esm/parsers.js
// ../../../node_modules/@sentry/browser/esm/eventbuilder.js
// ../../../node_modules/@sentry/browser/esm/transports/base.js
// ../../../node_modules/@sentry/browser/esm/transports/fetch.js
// ../../../node_modules/@sentry/browser/esm/transports/xhr.js
// ../../../node_modules/@sentry/browser/esm/backend.js
// ../../../node_modules/@sentry/browser/esm/helpers.js
// ../../../node_modules/@sentry/browser/esm/integrations/globalhandlers.js
// ../../../node_modules/@sentry/browser/esm/integrations/trycatch.js
// ../../../node_modules/@sentry/browser/esm/integrations/breadcrumbs.js
// ../../../node_modules/@sentry/browser/esm/integrations/linkederrors.js
// ../../../node_modules/@sentry/browser/esm/integrations/useragent.js
// ../../../node_modules/@sentry/browser/esm/client.js
// ../../../node_modules/@sentry/browser/esm/sdk.js
// ../../../node_modules/@sentry/integrations/esm/rewriteframes.js
```

In `chunk-EZ2R6UVJ.js`, `src/environment/index.ts` depends on Sentry from `chunk-PLL4RMKF.js`. In `chunk-PLL4RMKF.js`, Sentry depends on tslib from `chunk-EZ2R6UVJ.js`.

If `src/environment/index.ts` was bundled separately from other modules in `chunk-EZ2R6UVJ.js`, this issue wouldn’t happen.

</details>

**b) dependencies between chunks and _other entrypoints_**

This one feels very incorrect – chunks should never import other entrypoints.

<details>

<summary>Example</summary>

If I work around the following error (by tuning/reshuffling a few imports), I’ll get a different error:

<img width="1012" alt="Screen Shot 2021-03-29 at 17 10 36" src="https://user-images.githubusercontent.com/2953267/112841568-b24e0200-90b1-11eb-9fd7-c00b3217e556.png">

If I set a breakpoint inside that React function, I’ll see that the function is called from `projects.debug.js`:

<img width="1012" alt="Screen Shot 2021-03-29 at 17 11 10" src="https://user-images.githubusercontent.com/2953267/112841856-0ce75e00-90b2-11eb-8f01-73864f0494b9.png">

This is super weird. `projects.debug.js` is an entrypoint, and it’s a _different_ entrypoint. This file shouldn’t be loaded on this page at all.

Then why is it loaded? This is why:

![Screen Shot 2021-03-29 at 17 14 28](https://user-images.githubusercontent.com/2953267/112842077-3bfdcf80-90b2-11eb-87a2-91027c1b4e4d.png)

(`format` is a function from `date-fns/esm/format/index.js`)

This feels very incorrect. Entrypoints include top-level code with concrete side effects. That code should be called only when it’s supposed to be called.

In our case, `projects.debug.js` calls `ReactDOM.render(..., document.querySelector('#root'))` – and `#root` doesn’t exist on the page because it’s not the right page!

</details>

Sorry for no repro! I’m not working with Framer this week so this is the best I can come up with in a limited time. I’ll be able to invest more time in a proper repro in a couple weeks if it’s needed.

**Comment by iamakulov** [comment]
Wait, sorry – this has actually started happening even earlier, with 0.10.1. 0.10.0 works correctly.

**Comment by evanw** [comment]
I'm guessing this is the [removal of the file splitting optimization](https://github.com/evanw/esbuild/commit/fad7f47170ca2c452833c031f96133ff149a90d5), which is sort of a fundamental shift to how the bundler works. It's a bummer that I won't have a way to reproduce this. Unfortunately I don't think I'll be able to fix this without one. I've looked over that code a few times now and nothing stands out. And it doesn't seem to be an issue for any of the projects in my test set. I'll keep trying.

**Comment by iamakulov** [comment]
Got it, thank you for checking this on your side! Added this to my to-do list; if all goes as planned, will get back with a repro later this month.

**Comment by zandaqo** [comment]
I'm having the same issue and no luck making a minimum reproduction. I suspect in my case it has to do with chunks depending on entry points since I have a bunch of libraries loading their own versions of tslib.

**Comment by evanw** [comment]
> Made a reproducation here: https://github.com/zandaqo/esbuild_chunk

That's amazing! Thank you so much. I can reproduce it too, so I should be able to fix this.

**Comment by zandaqo** [comment]
> That's amazing! Thank you so much. I can reproduce it too, so I should be able to fix this.
No, thank you for the great tool, support, and overall experience here, the least we can do is complain about the inevitable bugs.

**Comment by evanw** [comment]
A fully-reduced test case for the repo above is as follows:

* `entry.js`: `import('./a'); import('./b')`
* `a.js`: `import { bar } from './shared'; bar()`
* `b.js`: `import './shared'`
* `shared.js`: `import { foo } from './foo'; export let bar = foo`
* `foo/index.js`: `export function foo() {}`
* `foo/package.json`: `{ "sideEffects": false }`

When you build this with `--bundle --splitting --format=esm`, the output files `a-...js` and `chunk-...js` both import symbols from each other, which is unexpected.

This bug is caused by `"sideEffects": false` somehow (not sure how yet) which means that you can work around the bug for now by using `--tree-shaking=ignore-annotations` until this bug is fixed.

**Comment by evanw** [comment]
Can you verify that version 0.11.5 fixes this issue?

**Comment by zandaqo** [comment]
@evanw All good here, 0.11.5 fixes it.
