### ISSUE TITLE
Provide an option to transform dynamic import to Promise.resolve(() => require(...))

### ISSUE THREAD

**Issue by SamChou19815** [evanw/esbuild#1084]
ESBuild fixes #1029 by always transform `import(...)` to `Promise.resolve(() => require(...))`. However, this is not always desired.

## Old Node Versions

Dynamic import is not supported in earlier node version (<13).
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#browser_compatibility. 
Therefore, it should at least emit using Promise.resolve when having something like `--target=node12`.

## Static Site Generation

During static site generation, we might want to produce a single bundled js that contains all the async imported modules.

e.g. Suppose we have the following source

```js
// a.js
// some react code

// b.js
// some react code

// entry-point.js
const LazyA = import('./a');
const LazyB = import('./b');
// ...
```

If dynamic import syntax is preserved, then webpack will create a chunk for both `a` and `b`. However, this is not what we want for static site generation, since there is no concern for bundle size during build time, and we only want one single js for convenience.

If the dynamic import syntax is transformed into `Promise.resolve(() => require(...))`, then we won't have the problem anymore.

I encountered this problem when I am trying to adopt esbuild for docusaurus: https://github.com/facebook/docusaurus/pull/4532

**Comment by marvinhagemeister** [comment]
The data on MDN is incorrect. Just had to test the support level for that for a project at work last week and can confirm that node 12 does indeed support dynamic imports.

| Node version | [Release Date](https://nodejs.org/en/download/releases/) | Dynamic import support |
|---|---|---|
| `12.16.3` | 2020-05-26 | Not supported |
| `12.17.0` | 2020-05-26 | Supported, but marked as experimental |
| `>=12.20.0` | 2020-11-24 | Fully supported (https://github.com/nodejs/node/pull/31974) |
| `13.0.0` | 2019-10-22 | Not supported |
| `>=13.2.0` | 2019-11-21 | Fully supported |

I recall there at the time being a huge discussion on twitter about the LTS version not supporting ESM and thereby blocking the transition away from CommonJS. The decision was made to backport ESM from newer release lines to `12.x`.

So node `>=12.20.0` does support dynamic imports completely and the data on MDN is wrong. Submitted and issue on their end: https://github.com/mdn/content/issues/3665

cc @evanw

**Comment by evanw** [comment]
The current environment version mechanism doesn't support a feature becoming unsupported and re-supported as the version number increases. So I'm planning to keep the supported version at node 13.2 for esbuild. Hopefully that's ok because node version 12 is no longer active anyway.

**Comment by marvinhagemeister** [comment]
Fair enough 👍
