### ISSUE TITLE
Inject not working with code splitting anymore

### ISSUE THREAD

**Issue by Jarred-Sumner** [evanw/esbuild#1086]
Reproducible example: https://github.com/Jarred-Sumner/inject-repro

Run this:
```bash
rm -rf out; ./node_modules/.bin/esbuild 1.jsx 2.jsx  --outdir=out  --format=esm  --inject:inject.js  --bundle --define:"process.env.NODE_ENV=\"production\"" --splitting
```

Given > 1 similar file like this:
```tsx
export function Greet() {
  return <div>hi</div>;
}

Greet();
```

It outputs a file like this:
```tsx
import {
  React
} from "./chunk-ELFW36T7.js";

// 2.jsx
init_inject();
function Greet() {
  return /* @__PURE__ */ React.createElement("div", null, "hi");
}
Greet();
export {
  Greet
};
```

Notice how it's calling `init_inject()` but that function is not defined in the module? It's defined in the chunk being imported.

This is with `inject.js` set to the auto-import jsx example copy-pasted from the docs:
```jsx
import * as React from 'react'
export { React }
```

Similar behavior occurs with variations of `inject` like:
```ts
export * from 'react';
```
```ts
export {default as React} from 'react';
```

If I had to guess, the problem is that React is being treated as a CJS module instead of an ESM, since it doesn't actually export ESM (UMD or CJS only)

**Comment by evanw** [comment]
Thanks for the report. I'm currently investigating and working on a fix.
