### ISSUE TITLE
Is it possible to run transformations to JSX / TS in the browser using esbuild via wasm?

### ISSUE THREAD

**Issue by YarivGilad** [evanw/esbuild#1087]
Hi all,
I'm after creating an online code editor using Monaco / Ace as the editor component, and in order to support compilation/transformation of JSX or TS, I was wondering if there is a way to use esbuild in the browser using web assembly rather than the node.js process.
I'd very much appreciate your inputs.
Also, if you know of an existing editor that achieved this goal, I'll be happy to know about it.
Thank you!
Yariv

**Comment by kzc** [comment]
See https://github.com/evanw/esbuild/blob/master/scripts/try.html

If you're on a unix like platform, clone this repo and run:
```
make platform-wasm
esbuild --servedir=.
```
and open http://127.0.0.1:8000/try.html

Alternatively, run `npm i esbuild-wasm` and change the script src accordingly:

https://github.com/evanw/esbuild/blob/5cf95a6aab419c2ebe3dfd58a10cd14763a5e712/scripts/try.html#L214

**Comment by hyrious** [comment]
My recent [repo](https://github.com/hyrious/esbuild-repl): https://hyrious.me/esbuild-repl

**Comment by evanw** [comment]
> I was wondering if there is a way to use esbuild in the browser using web assembly rather than the node.js process.

This already is documented on the website: https://esbuild.github.io/api/#running-in-the-browser. You don't need to build esbuild yourself to do this. Closing this issue as this was just a documentation request.
