### ISSUE TITLE
How to copy assets to output dir?

### ISSUE THREAD

**Issue by rejas** [evanw/esbuild#1089]
I have a simple web frontend (no react/vue, just some simple js stuff) and scss styles. Running those through esbuild works fine. 

But I cant get esbuild to copy my assets (svg and other images) to the output dir because those dont have references in the js/scss (unlike the woff2 fonts that get picked up by esbuild through their refrence in the font-face declarations)

Any hints on how to do that? Or do I have to copy those assets by myself after esbuild finished?

For reference, here is my config:
```

  // actually build the code
    await esbuild.build({
      entryPoints: ["src/js/index.js"],
      format: "iife",
      bundle: true,
      minify: isProd,
      sourcemap: !isProd,
      plugins: [sassPlugin()],
      outfile: `${buildDir}/bundle.js`,
      loader: {
        ".svg": "file",
        ".woff2": "file",
      },
    });
```

**Comment by Ventajou** [comment]
I can't speak to CSS because I don't use the it with esbuild. But for JS, it will only copy assets that you explicitly import and use because assets are considered to have no side effects.

So this will not copy the file:
```
import 'foo.svg';
```
While this will, because you use the imported value:
```
import foo from 'foo.svg';
console.log(foo);
```

If you want the first statement to work, you can write a custom plugin that will handle the copying. I've done that, it works. The advantage of this approach is you still are explicit in your code about which assets get copied.

Otherwise you can blanket copy all assets after the build like you mentioned.

**Comment by rejas** [comment]
Thanks for the info @Ventajou Are you refereing to this: https://github.com/Ventajou/esbuild-import ?

**Comment by Ventajou** [comment]
no, sorry my version is part of a larger build tool for work and it's not public. 

But a simple plugin should be easy to put together, what I did was let my plugin do the copying (and caching) of my assets and return a JS comment to esbuild as pseudo file content.

**Comment by zaydek** [comment]
In my case I have a folder called `www` which hosts static assets. That always gets copied to my build folder `out` manually (some code in Go) and therefore I don’t lean on esbuild for this step. This has been talked about previously here FWIW: #982.

**Comment by rejas** [comment]
Thanks all for the hint, I ended up copying the assets with a few lines of js after the buid has finished. Since the project isnt large, this is sufficient for now. Keep up the good work and thanks for this quick bundler.

**Comment by jasonwilliams** [comment]
I came across this use case also, is there a plugin for this? I can imagine this would be a popular requirement for many frontend projects where static assets need to be moved into the dist folder.

**Comment by wesgladwell** [comment]
> import foo from 'foo.svg';



> I came across this use case also, is there a plugin for this? I can imagine this would be a popular requirement for many frontend projects where static assets need to be moved into the dist folder.

Same issue here 👻

**Comment by mtomov** [comment]
> > import foo from 'foo.svg';
> 
> > I came across this use case also, is there a plugin for this? I can imagine this would be a popular requirement for many frontend projects where static assets need to be moved into the dist folder.
> 
> Same issue here 👻

Yeah, same. For a Bridgetown esbuild setup. Thanks!

**Comment by fregante** [comment]
This plugin works for me: https://www.npmjs.com/package/esbuild-plugin-copy

**Comment by speich** [comment]
If you use the esbuld cli, you can this by specifying a copy loader for each file type:

`esbuild ./myFolder/**/* --loader:.css=copy --loader:.js=copy --loader:.svg=copy --outdir=/myFolder`
