### ISSUE TITLE
"Could not read from file" errors using basic alias plugin

### ISSUE THREAD

**Issue by RwwL** [evanw/esbuild#1090]
Sorry, this almost certainly isn't really an issue but just a gap in me understanding the [resolve callbacks example](https://esbuild.github.io/plugins/#resolve-callbacks).

Based on that link, I have a tiny resolver plugin intended to replace a resolver alias I'd been using with webpack: `import 'components/*` from wherever would resolve to `[projectRoot]/client/components/`:
```
const aliasPlugin = {
  name: 'resolver',
  setup(build) {
    // Redirect all paths starting with "components/" to "[projectRoot]/client/components"
    build.onResolve({ filter: /^components\// }, (args) => ({ path: path.join(__dirname, 'client', args.path) }));
  },
};
```

I pass this option into my build like the example as well:
``` 
plugins: [aliasPlugin],
```

But when I run the build, I get "could not read file" errors for what looks like all of them, even though the path immediately following the error message looks correct:

```
client/router.js:12:23: error: Could not read from file: /[full project path]/client/components/Subsection
    12 │ import Subsection from 'components/Subsection';
client/pages/Subscriptions.js:2:30: error: Could not read from file: /[full project path]/client/components/SubscriptionsPage
    2 │ import SubscriptionsPage from 'components/SubscriptionsPage';
...[dozens more]
```

I also have some things organized in subfolders in `components` and could previously resolve their index.js files just by pointing the import at the directory, but with `esbuild` and this resolver I'm getting `Cannot read file "client/components/[subfolder]": is a directory ` errors, and I'm searching for an option to configure that if possible, but no luck yet, so any advice there is appreciated as well.

**Comment by evanw** [comment]
It's the resolver's job to resolve an import path to a file path. If you use your own resolver, you are then responsible for doing path resolution. You can potentially use something like `require.resolve(args.path, {paths: [args.resolveDir]})` or the [`resolve`](https://www.npmjs.com/package/resolve) package.

**Comment by RwwL** [comment]
Thanks. If I'm understanding you correctly, then using the exact example I referenced ([this one](https://esbuild.github.io/plugins/#resolve-callbacks)) would result in the same errors?

**Comment by evanw** [comment]
In that example the paths looked like `images/header.png` which would then be redirected to `./public/images/header.png`. If you have more complex path resolution needs, you many need more code to handle those needs. It was only an example.
