### ISSUE TITLE
esbuild does not tree shake implicit type import

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#1092]
It seems that esbuild shake the explicit  `import type { Draft} from 'immer'` , but does not shake `import { Draft } from 'immer'` even though Draft is type only and I configure `"importsNotUsedAsValues": "remove"` in tsconfig.json. you can see the problem here https://github.com/reduxjs/redux-toolkit/pull/957#issuecomment-810725314

**Comment by evanw** [comment]
When bundling is disabled, TypeScript files are compiled one-at-a-time so it's not possible to determine whether this is a type or not. You need to enable `"isolatedModules": true` in your `tsconfig.json` file: https://esbuild.github.io/content-types/#isolated-modules.

This is the case regardless of whether you use esbuild, Babel, or TypeScript's own compiler API:

```js
const ts = require('typescript')
const es = require('esbuild')
const bc = require('@babel/core')

const code = `
  export { Draft } from 'immer'
  import { someType, someValue } from 'example'
  var someVar: someType = someValue
`

console.log('// TypeScript:\n' + ts.transpileModule(code, {
  compilerOptions: {
    module: ts.ModuleKind.ESNext,
    importsNotUsedAsValues: ts.ImportsNotUsedAsValues.Remove,
  }
}).outputText)

console.log('// esbuild:\n' + es.transformSync(code, {
  loader: 'tsx',
  tsconfigRaw: `{
    "compilerOptions": {
      "importsNotUsedAsValues": "remove",
    },
  }`,
}).code)

console.log('// Babel:\n' + bc.transform(code, {
  plugins: [['@babel/plugin-transform-typescript', {
    onlyRemoveTypeImports: false,
  }]]
}).code)
```

The code above prints the following:

```js
// TypeScript:
export { Draft } from 'immer';
import { someValue } from 'example';
var someVar = someValue;

// esbuild:
export {Draft} from "immer";
import {someValue} from "example";
var someVar = someValue;

// Babel:
export { Draft } from 'immer';
import { someValue } from 'example';
var someVar = someValue;
```

**Comment by hardfist** [comment]
but this happens when bundling is enabled

**Comment by hardfist** [comment]
i dont know whether the shake could be done even when immer is external here
