### ISSUE TITLE
Support global instance of a WASM binary vs wasmURL reference (for say Cloudflare Worker environments)

### ISSUE THREAD

**Issue by whatnickcodes** [evanw/esbuild#1093]
I apologize in advance will be a noob. Love this project.

**Currently:**

`esbuild.initialize({
  wasmURL: `

**Would be nice to have this option or similar:**

`const esbuild = new WebAssembly.Instance(
    ESBUILD_WASM`

Where ESBUILD_WASM is a global variable.

**Why?**
Beside achieving a REPL, some environments like Cloudflare Workers require the WASM binary to be created this way due to needing to be a Resource Binding.

**For fun / experiment...**
Have an idea for a brand new way to build apps as fun experiment. If a person can get esbuild jammed in a Cloudflare worker through the WASM binary, you could on each request render a bunch of code, combine a bunch of virtual esmodules (ideally tree shaked, minified, uglified) and output the result. Would be trivial to cache the output, but by leveraging WASM and esbuild, it might be so quick a normal user wouldn’t even know even for complex pages. 

Almost like a single simple PHP template file but the output of the JS, HTML, CSS is stripped to absolute nakedness form. Would also allow remote/db driven components on the fly for a route.

**Comment by whatnickcodes** [comment]
Well looks like this was done

https://esbuild.developers.workers.dev/

https://blog.cloudflare.com/workers-now-even-more-unbound/

https://twitter.com/threepointone/status/1461361034732572682

No code though

**Comment by okikio** [comment]
@whatnickcodes The fetching, bundling, treeshaking, minifing, etc... can be done locally in browser via https://bundle.js.org
