### ISSUE TITLE
custom install registry or download cdn path

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#1094]
npm registry is too slow for some country which will cause CI|CD timeout sometimes. so it will be helpful if download registry or download cdn path can be customized like puppeteer| node-sass.

**Comment by evanw** [comment]
I believe you should be able to configure a custom registry with [`npm config set registry`](https://docs.npmjs.com/cli/v7/using-npm/registry) or [`.npmrc`](https://docs.npmjs.com/cli/v7/configuring-npm/npmrc).

**Comment by hardfist** [comment]
the npm install in postinstall will be effected by this ？

**Comment by evanw** [comment]
It should be, yes. Did you try it? The inner call to npm should pick up on the environment variables set by the outer call to npm.

**Comment by hardfist** [comment]
I will try again to verify this
