### ISSUE TITLE
Help with .env file and "define" property of esbuild configuration file

### ISSUE THREAD

**Issue by jrafaaael** [evanw/esbuild#1095]
Hello everyone! How can I use the .env files in esbuild? There I would like to place KEYS that were assigned to me from a web service to make requests to an API and I would not want anyone else to see those KEYS. I know I can set "variables" with the "define" property in the esbuild config file, but wouldn't this make that config file have to be in a .gitignore?
Hope someone can help me. Thanks in advance!

**Comment by evanw** [comment]
> I know I can set "variables" with the "define" property in the esbuild config file, but wouldn't this make that config file have to be in a .gitignore?

You can read from the `.env` file and then pass the values in the file to esbuild.

**Comment by jrafaaael** [comment]
> You can read from the `.env` file and then pass the values in the file to esbuild.

Hi there! Thanks for your prompt response! Could you explain a little more about what you tell me? I have sincerely tried everything I can think of and can not find a solution

**Comment by Jarred-Sumner** [comment]
@jrafaaael the code is something like this:
```ts
const dotenv = require("dotenv");
const esbuild = require("esbuild");
dotenv.load();

esbuild.build({

   define: {
      ...(Object.fromEntries(Object.entries(process.env).map([key, value] => [`process.env.${key}`, JSON.stringify(value)]])))
   }

   // rest of your esbuild config
})
```

Untested, that might be the wrong number of parentheses. also it might not be `dotenv.load` it might be something else

**Comment by gopal-virtual** [comment]
@Jarred-Sumner the example you've given will also populate the env variable that's coming from `bashrc` (which might be unexpected sometimes)

**Comment by evanw** [comment]
Closing since this is a help question, not an issue with esbuild. The information above sounds like a sufficient start to be able to address the problem.
