### ISSUE TITLE
rfc: no comment purge

### ISSUE THREAD

**Issue by cdaringe** [evanw/esbuild#1098]
# Problem

JavaScript/TypeScript users use comments for a variety of reasons, including the `PURE` tree shaking case.

A key usage I use them for is `istanbul ...` comments, which is critical for testing & coverage. Stripping these comments makes using esbuild for testing + coverage infeasible in large codebases, where such comment flags are actually critical.

# Discussion

This project has a strong philosophy of keeping features low. Love it.

Is _not deleting content_ in or out of scope for feature support? I would like to have a flag for never deleting comments. I'd advocate that we should consider this, because at the core, the current compiler is lossy. This feature isn't about supporting some new fancy language feature--it's just keeping existing content in place, especially content that is already understood and handled by the parser and printer.

**Comment by evanw** [comment]
> Is _not deleting content_ in or out of scope for feature support?

Comments are by definition not part of the content. From [the JavaScript standard](https://tc39.es/ecma262/#sec-lexical-and-regexp-grammars) itself:

> Simple white space and single-line comments are discarded and do not appear in the stream of input elements for the syntactic grammar. A _MultiLineComment_ (that is, a comment of the form `/*...*/` regardless of whether it spans more than one line) is likewise simply discarded if it contains no line terminator; but if a _MultiLineComment_ contains one or more line terminators, then it is replaced by a single line terminator, which becomes part of the stream of input elements for the syntactic grammar.

What you are actually asking for is for esbuild to assign specific semantics to certain comments for a specific tool that you want to use, to attach those annotations to the AST according to those semantics, and then for esbuild to preserve those semantics as it compiles and transforms your code. Doing that would add a lot of work and ongoing maintenance burden and I have decided that it's out of scope. You can read more about this here: https://github.com/evanw/esbuild/issues/578#issuecomment-739787682.

**Comment by revelt** [comment]
In theory, if we had a plugin like `rollup-plugin-cleanup` (which respects `istanbul`, when called like `cleanup({ comments: "istanbul", extensions: ["js", "ts"] }),`), then another for `console.*` removal (alternative of `@rollup/plugin-strip`), then another plugin to mildly minify (no touching of comment lines or comments), then disabled `esbuild`'s built-in minification, that would be a possible solution? What do you think? A plugins approach...

I'm also struggling with `console.log` and comments stripping challenge.

**Comment by evanw** [comment]
I'm going to close this for the reason described above: I consider this to be out of scope.
