### ISSUE TITLE
[Bug?] entryPoints type conflicts with doc description

### ISSUE THREAD

**Issue by jessuni** [evanw/esbuild#1108]
In the [documentation](https://esbuild.github.io/api/#entry-points), the following code snippet is given:

```javascript
require('esbuild').buildSync({
  entryPoints: {
    out1: 'home.js',
    out2: 'settings.js',
  },
  bundle: true,
  write: true,
  outdir: 'out',
})
```

When I tried building with individual outputs, esbuild throws an error:
`Error: "entryPoints" must be an array`

In `main.d.ts`, entryPoints only has `string[]` type. I wonder if this feature is not supported?

**Comment by evanw** [comment]
From [the published contents of `main.d.ts`](https://unpkg.com/esbuild@0.11.4/lib/main.d.ts):

```ts
export interface BuildOptions extends CommonOptions {
  ...
  entryPoints?: string[] | Record<string, string>;
  ...
}
```

**Comment by jessuni** [comment]
Found out I was using v0.9.2. Esbuild is rolling out new versions super fast! Thanks for the hard work.
