### ISSUE TITLE
Incorrect tree-shaking of module with "sideEffects: true"

### ISSUE THREAD

**Issue by aleclarson** [evanw/esbuild#1109]
```ts
import { SomeType } from 'foo/bar'
```

- The `foo/bar` module exists in a package with `sideEffects: true`.
- The importer is importing a type alias, but also expects the module to execute its side effects.
- Esbuild is removing this import, presumably because it thinks it's only there for the type import, when in fact, it's also there for the module's side effects.

**Comment by evanw** [comment]
The import is removed because that's also how the TypeScript compiler itself behaves:

```
$ cat example.ts
import { SomeType } from 'foo/bar'
import { someValue } from 'foo/bar'
export let value: SomeType = someValue
```

```
$ esbuild example.ts
import {someValue} from "foo/bar";
export let value = someValue;
```

```
$ tsc example.ts -module esnext ; cat example.js
import { someValue } from 'foo/bar';
export var value = someValue;
```

**Comment by aleclarson** [comment]
That's unfortunate. Thanks!
