### ISSUE TITLE
how to ignore the warning  "Define "process.env.NODE_ENV" when bundling for the browser"

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#1112]
sometimes we want to leave the process.env.NODE_ENV to other bundler even thou we use esbuild to bundle our code, but it seems no way to turn off the warning except turn off  the warn logLevel, which may ignore other important warning, something like rollup's onwarn handler would be helpful to handle this.

**Comment by evanw** [comment]
This warning has already been removed, and the behavior around `process.env.NODE_ENV` has changed. See the [release notes for version 0.11.3](https://github.com/evanw/esbuild/releases/tag/v0.11.3) for more information.

**Comment by evanw** [comment]
Closing for the reason described above. This code no longer exists.
