### ISSUE TITLE
[bug?] when using --watch, it continuously rebuild even though entry file is not modified

### ISSUE THREAD

**Issue by MD-IS** [evanw/esbuild#1113]
I am using esbuild native executable, in Termux in Android, when i do
```sh
esbuild App.tsx --outfile=App.js --watch
```
it continuously rebuild even though App.tsx is not modified. like in [this video](https://user-images.githubusercontent.com/71170546/113513395-bb4c4100-9593-11eb-815a-9ef25c6efcdc.mp4) Idk why it says change in '../../..', sometimes it was '../../../..'
../../../.. is /data
../../.. is /data/data

i got esbuild from https://registry.npmjs.org/esbuild-linux-arm/-/esbuild-linux-arm-0.11.5.tgz

my device is Android 5.1 Lolipop
armv7 architecture
Termux version is 0.73

**Comment by evanw** [comment]
This is saying that directory's entry list (i.e. what `ls` gives you) was changed and that esbuild is depending on the entry list for that directory. So the rebuild was triggered since dependent information was changed. It's possible that esbuild's path resolution algorithm could be changed to avoid triggering this by being less eager about caching directory contents.

**Comment by geoffharcourt** [comment]
We're experiencing the same thing. An `ignoreFiles` parameter for the `watch` argument might help here, or maybe only watch `entryPoints`? We're working around this with our own file watch wrapper, but this is the only thing blocking us from using the built-in watch functionality.

**Comment by jeregrine** [comment]
Hrm I get this as well and can reproduce it simply:

term1: esbuild app.js --watch
term2: cd .. && touch hello

term1: [watch] build started (change: "..")
...

term2: cd .. && touch hello

term1: [watch] build started (change: "../..")


m1 macbook air
esbuild 0.12.15

**Comment by josevalim** [comment]
I am not familiar with everything that esbuild can import but, if all of your dependencies need to be explicitly imported, could you build a tree of all files that need to be watched and watch those files exclusively? 🤔

**Comment by jeregrine** [comment]
> m1 macbook air
> esbuild 0.12.15
I also confirmed this on AMD/Linux, same test.

**Comment by jeregrine** [comment]
Just to confirm: this bug remains in 0.12.17

**Comment by thepeoplesbourgeois** [comment]
Experiencing this bug as well

MacOS 11.5.2
esbuild 0.12.18
