### ISSUE TITLE
onResolve not detecting imports when bundling is off

### ISSUE THREAD

**Issue by hmak-me** [evanw/esbuild#1114]
I am trying to build an npm project without bundling it to a single output file since it is an npm package. 
I used alias paths everywhere and need to convert them into relative paths in the build like the following example:

```javascript
// The following import statement:
import rule from 'src/validator/rule';

// Should be something like:
const import_rule = __toModule(require('../../validator/rule.ts'));
```

I've tried to provide a custom plugin to the build script to resolve those paths there:

```javascript
const alias = {
    name: 'alias',
    setup(build) {
        build.onResolve({ filter: /src/ }, args => {
            console.log(JSON.stringify(args));

            // ...
        });
    },
}
```

When it is bundling the project, everything is working, all of the import statements will be passed to the plugin and the output file works fine. The problem happens when I turn off the bundling. It only fires when it receives an `entry-point`. Here is my test config file for a smaller similar project:

```javascript
esbuild.build({
    entryPoints: [
        'src/bootstrap/index.ts'
    ],
    outdir: 'dist',
    outbase: 'src',
    format: 'cjs',
    platform: 'node',
    plugins: [
        alias,
    ],
}).then(() => {
    console.log('Build Finished!');
}).catch((err) => {
    console.log('Error', err);
});
```

**Comment by evanw** [comment]
This is by design. You need bundling enabled to cause esbuild to try to import other files. You can still mark all imports as external though to stop bundling from including them. Do that by returning `external: true` from the `onResolve` callback.

**Comment by hmak-me** [comment]
Thanks for your helpful response. I've managed to mark my import statements as externals to prevent them from bundling. But still got some problems getting plugins to work. I didn't see any explanation in docs about handling imports with multiple plugins. Please take a look a the configuration below:

**Build Script:**
```javascript
await esbuild.build({
    entryPoints: await fastGlob('src/**/*.(js|ts)'),
    external: [...Object.keys(pkg.dependencies || {})],
    outbase: 'src',
    outdir: 'lib',
    platform: 'node',
    bundle: true,
    keepNames: true,
    plugins: [
        wildcardImport(),
        aliasImport({
            src: './src',
        }),
        graphqlImport(),
        makeExternal(),
    ],
});
```

**Description:**
1. The first plugin will be responsible for wildcard imports and adds an import statement for every possible file matching the wildcard pattern.
2. The second plugin will resolve the absolute path of the import statements that started with the `src` alias.
3. The third plugin will load `.gql` and `.graphql` files.
4. The last plugin does what you said earlier. It will mark all files that are loaded from the `src` directory as external modules to prevent them from bundling. It also provides a relative path to the imported module calculated from the location of the importer module.

**Problem:**
The `aliasImport` plugin does its job pretty well, but it will end just right there. The modules processed in this plugin, will not be visible for the next plugins. 

I think there must be a way to let other plugins access the previously processed files.
