### ISSUE TITLE
Is there an C/FFI interface?

### ISSUE THREAD

**Issue by deeprobin** [evanw/esbuild#1116]
I want to run esbuild out of an rust application without invoking an binary esbuild file.
Is there built-in FFI support?

**Comment by evanw** [comment]
I consider it out of scope, and it's not officially supported. But someone has attempted one here: https://github.com/wilsonzlin/esbuild-rs. I have not tried it myself.

**Comment by evanw** [comment]
Closing this as I believe this question has been answered.
