### ISSUE TITLE
When a dynamically imported module includes CSS, code splitting results in an invalid CSS import

### ISSUE THREAD

**Issue by nihalgonsalves** [evanw/esbuild#1125]
`import('./module-name.css')` appears in the output, in place of the actual `.js` file.

There's a reproduction here: https://codesandbox.io/s/interesting-mayer-uvouc?file=/out/parent.js, but I'm inlining the code here for clarity:

### esbuild options

`esbuild src/parent.js --bundle --outdir=./out --splitting --format=esm --platform=browser`

 ### Input

**`src/parent.js`**
```js
import('./child')
```

**`src/child.js`**

```js
import './foo.css'
```

**`src/foo.css`**

```css
body {
  color: black;
}
```

### Output

**`out/parent.js`**

```js
// src/parent.js
import("./child.css");
```

^ `child.js` should be imported here

**`out/child.js`**

Empty (this is ok)

**`out/child.css`**

```css
/* src/foo.css */
body {
  color: black;
}
```

**Comment by evanw** [comment]
Thanks for the report and the clear repro. A fix for this will be in the next release.
