### ISSUE TITLE
[Feature Request] Option to control output js code's indention

### ISSUE THREAD

**Issue by runminlook** [evanw/esbuild#1126]
two spaces indention
four spaces indention
one tab indention

**Comment by evanw** [comment]
I do not intend for esbuild to be a code formatter. The non-minified output is intended to be human-readable in case it needs to be debugged, but it's not intended to be consumed as a primary source file. You could consider using a real code formatting tool such as [Prettier](https://prettier.io/) instead.

**Comment by evanw** [comment]
I'm going to close this since I consider options relating to code formatting to be out of scope.
