### ISSUE TITLE
styled-components do not work

### ISSUE THREAD

**Issue by gajus** [evanw/esbuild#1133]
The order of imported style is different than what we are getting in our webpack build.

<img width="385" alt="Screen Shot 2021-04-09 at 6 08 32 PM" src="https://user-images.githubusercontent.com/973543/114248922-e812a680-994d-11eb-89fb-15f73398f675.png">

<img width="340" alt="Screen Shot 2021-04-09 at 6 08 45 PM" src="https://user-images.githubusercontent.com/973543/114248918-e648e300-994d-11eb-8d93-7287742f0241.png">

As the order is different, it messes up styles too:

<img width="586" alt="Screen Shot 2021-04-09 at 6 09 39 PM" src="https://user-images.githubusercontent.com/973543/114248959-08dafc00-994e-11eb-9966-1a1d1038664a.png">
<img width="580" alt="Screen Shot 2021-04-09 at 6 09 43 PM" src="https://user-images.githubusercontent.com/973543/114248960-08dafc00-994e-11eb-93c1-4225704048bb.png">

**Comment by gajus** [comment]
Hm. This doesn't seem to be order problem.

esbuild has styles that do not exist at all in styled-components case.

**Comment by evanw** [comment]
Do you have a way for me to reproduce this issue myself?

**Comment by stolinski** [comment]
fwiw, we use Styled components and have had no issues.

**Comment by gajus** [comment]
Sorry, do not have a replica. Team deprioritized esbuild / this issue.

For what it is worth, we are using a combination of styled components and styled system.

**Comment by subhendukundu** [comment]
I have an open source project which has the same issue. And using styled components and styled system.
