### ISSUE TITLE
"require" statement is still attempting to load module even when code block shouldn't run 

### ISSUE THREAD

**Issue by sortofsleepy** [evanw/esbuild#114]
👋 

Not sure if this is an actual bug or not or if things are as intended but I ran into the oddest issue. 

I am using a library that uses the following function to check if the current environment is a Node environment or not. 

```javascript
export const isNode = () => {
    if (typeof process === "object") {
        if (typeof process.versions === "object") {
            if (typeof process.versions.node !== "undefined") {
                return true;
            }
        }
    }
    return false;
};
```
It correctly returns false as expected. 

That said, given the following code

```javascript

const inspect = isNode() ? require("util").inspect : null;
```

I would expect that `inspect` would end up null and that there is no attempt to load the util module. 

However, I am still getting an error saying "Could not resolve "util", suggesting there was some kind of attempt. 

Is this expected?

Thank you!

**Comment by evanw** [comment]
Yes, this is expected.

Bundling happens at build time, not run time. There's no way for esbuild to know at build time whether `isNode()` returns true or false, so the `util` package must be bundled in case that code branch is evaluated at run time.

You should be able to get around this with `--external:util` to tell esbuild to not try to bundle the `util` module. This means it will crash at run time if `isNode()` ever returns true.

**Comment by sortofsleepy** [comment]
👍 Got it! Thanks for responding so quickly!
