### ISSUE TITLE
Would love a way to silence the "indirect calls to require" warnings for 3rd party dependencies

### ISSUE THREAD

**Issue by lgandecki** [evanw/esbuild#1142]
I understand that I can silent the warnings with try catch around a require, but that's not really a solution when the require is in node_modules and it's a dependency of one of my dependencies. I guess I can try to require my dependency instead of import it, but then I'm losing TypeScript types and all in all it is a bit silly :) 
I would love to be able to "acknowledge" warnings, if I see a new one, I'd investigate and check whether it might be an issue or not, if it's not an issue, I want to silence it (an array of packages to silence is one option that comes to mind).

Did anyone find a nice way to deal with that? 

BTW: great job on this package, the speed improvement and the different workflow that this enables is mind-blowing. Thanks!

**Comment by evanw** [comment]
You can disable the printing of warnings by setting the [`logLevel`](https://esbuild.github.io/api/#log-level) setting to `error` in esbuild's API. If you would still like to see certain warnings, you can print them yourself by iterating over the [`warnings`](https://github.com/evanw/esbuild/blob/d616dac2ca7cb0f9bd918b96fa44ece3578ee9b3/lib/types.ts#L120) array returned from esbuild's API. If you would like to pretty-print the warnings using esbuild's log style, you can call the [`formatMessages`](https://github.com/evanw/esbuild/blob/d616dac2ca7cb0f9bd918b96fa44ece3578ee9b3/lib/types.ts#L334-L340) API.

**Comment by evanw** [comment]
Closing this issue as I have now completely removed the warning in #1155.

**Comment by lgandecki** [comment]
ok, interesting approach. but is there a chance to SEE those warning? One of the warnings did help me to fix my build, it would be super hard to figure out without that.

**Comment by evanw** [comment]
With the latest release, you can now opt-in to seeing some of these messages that you could have seen previously (along with some additional ones) with `--log-level=debug`.
