### ISSUE TITLE
(dynamic import) `transform` should probably respect `format: esm`

### ISSUE THREAD

**Issue by egoist** [evanw/esbuild#1146]
When using with options `{ target: 'node12', format: 'esm' }`, dynamic import is transformed to `require`:

```bash
> require('esbuild').transformSync(`import('foo')`,{target:'node12',format:'esm'})
{
  warnings: [],
  code: '...omitted...
    'Promise.resolve().then(() => __toModule(require("foo")));\n',
  map: ''
}
```

this would break `rollup-plugin-esbuild` since rollup only recognizes es module by default.

esbuild: `0.11.10`

**Comment by evanw** [comment]
Well dynamic import doesn't work in node 12, so this transformation is correct. Someone explicitly asked for this transformation to be added in #1084. Node 12 is [no longer actively maintained](https://nodejs.org/en/about/releases/) and is now in maintenance mode. If you don't actually need to support node 12, the easiest solution here could just be to use `target: 'node13.2'` instead, which is the earliest version of node that supports this feature according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import).

Technically node shipped a back-ported version of node 12.x that does work with dynamic import, node 12.20+. So in theory this could be made to work by using `target: 'node12.20'` and then changing esbuild to mark `node12.20` as supporting dynamic import. However, esbuild currently doesn't support a feature becoming unsupported and re-supported as the version number increases, so support for discontiguous version ranges would have to be added to esbuild first. See #1084 for more context.

**Comment by lukeed** [comment]
It could be agreeable to pretend like all of Node 13.x didn't exist, though. For example, it included a different/incomplete `"exports"` resolution algorithm.

It's been a mess, tbh. Fun stuff.

**Comment by egoist** [comment]
👍 Sounds fair.
