### ISSUE TITLE
The version of the downloaded binary is incorrect:

### ISSUE THREAD

**Issue by xiangyuisabatman** [evanw/esbuild#1151]
when i Run `node ./node_modules/esbuild/install.js` is error

$ node ./node_modules/esbuild/install.js
The version of the downloaded binary is incorrect: spawnSync E:\apiDoc2.0\fronte
nd\node_modules\esbuild\esbuild.exe EPERM
Install unsuccessful

**Comment by evanw** [comment]
> when i Run `node ./node_modules/esbuild/install.js` is error

You are never supposed to run that. It's only supposed to be run by npm automatically when you install the package.

**Comment by xiangyuisabatman** [comment]
but when i occur to happen this same problem, is answer[issues](https://github.com/vitejs/vite/issues/1361)

**Comment by evanw** [comment]
The solution to that npm bug is to delete and re-create your `package-lock.json` file, not to manually call esbuild's internal scripts: https://github.com/vitejs/vite/issues/1361#issuecomment-773720137.

**Comment by xiangyuisabatman** [comment]
after i delete node_modules and package-lock.json, i run `npm install`, then error
```
$ npm i

> esbuild@0.9.7 postinstall E:\apidoc-cms\node_modules\esbuild
> node install.js

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.3.1 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN apidoc-cms@0.0.0 No repository field.
npm WARN apidoc-cms@0.0.0 No license field.

added 146 packages from 186 contributors and audited 147 packages in 35.836s

7 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


Administrator@DESKTOP-KA7EPLR MINGW64 /e/apidoc-cms (1.0.0-dev-dxy)
$ The version of the downloaded binary is incorrect: spawnSync E:\apidoc-cms\node_modules\esbuild\esbuild.exe EPERM
Install unsuccessful

```

what can i do? T_T

**Comment by rizkyramadhan** [comment]
Maybe remove esbuild from package.json, run `npm i`, and then `npm i esbuild`

**Comment by evanw** [comment]
I’m closing this issue because it’s unactionable (it’s not something you are supposed to do in the first place) and there have been no recent updates. To solve this problem, the issue would need more information and/or specific instructions saying how to reproduce the problem.

**Comment by QiJieH** [comment]
i have a test , in windows use node binary package may be cause this issue, node install program don't have this issue.

**Comment by minijus** [comment]
@xiangyuisabatman, what would happen if you would try to launch `node_modules/esbuild/esbuild.exe` manually? In my case this executable is blocked by corporate group policy and I see exactly same error as you.
