### ISSUE TITLE
[bug] equality check upon -0 and 0

### ISSUE THREAD

**Issue by INCHMAN1900** [evanw/esbuild#1159]
## Reproduction

code like this:
```js
var isTrue = document.body.innerHTML === '';

console.log(isTrue ? -0 : 0)
```
after compiled with `--minify-syntax` option enabled, code becomes:
```js
var isTrue = document.body.innerHTML === "";
console.log(-0);
```

The ternary operator is removed, which may cause bugs in math operations. In our case, we use `Decimal.js`，and the `isNegative` function produces completely wrong answer when the value is negative zero.

## intended behavior

These two numbers are basically the same, like if your are not familiar with JavsScript, you would even know that -0 actually exists in this language. But they are different:
```js
Object.is(-0 , 0); // false

1 / 0; // Infinity

1 / -0; // Infinity
```

esbuild should be able to tell the difference between these different types of zero.

## What I found so far

`checkEqualityIfNoSideEffects` is the function for comparing two numbers. The number section is:
```go
r, ok := right.(*js_ast.ENumber)
return ok && l.Value == r.Value, ok
```
When the two parameters are numbers,`==` is used. Are they transformed to numbers in go first?

**Comment by rtsao** [comment]
It appears Terser correctly handles this (i.e. using SameValue equality for collapsing ternary branches and Strict Equality Comparison for mangling equality checks) whereas esbuild currently uses Strict Equality Comparison for both.

For example, using Terser:
```js
// input
console.log(x ? 0 : -0);
console.log(x ? 0 : +0);
console.log(0 === -0);

// output
console.log(x?0:-0);
console.log((x,0));
console.log(true);
```
