### ISSUE TITLE
Remove unicode char to the code

### ISSUE THREAD

**Issue by aelbore** [evanw/esbuild#116]
- having unicode in the code transform or build stops and have exceptions. 
sample of code with unicode (Please see attached file)
- is this scope of esbuild? or this could be done in the one who will use the esbuild?
- i did some string replace to my code `str.replace(/[^\0-~]/g, ' ')`

<img width="761" alt="Screenshot 2020-05-17 at 11 30 03 AM" src="https://user-images.githubusercontent.com/18069807/82135585-f1c38500-9836-11ea-959f-89b9e0ff48d6.png">

**Comment by evanw** [comment]
Thanks for the report. This is a bug in esbuild. It looks like I need to handle these unusual whitespace characters as whitespace. In the meantime you should be able to do something like `str.replace(/[^\S\r\n]/g,' ')`.
