### ISSUE TITLE
Simplify constant object access

### ISSUE THREAD

**Issue by adamburgess** [evanw/esbuild#1166]
Note: I opened this issue with a higher level question, which was how `{foo: 'bar'}.foo === 'bar'` should be minified to `!0`, but this is due to the property accessor not simplifying. If this issue is fixed, then that statement should be minified for free (there is already constant string equality checking). The original issue is at the bottom.

`{ foo: 'bar' }.foo` should be minified to `"bar"`.
This should work with a fair amount of depth:
`{ foo: { bar: 'baz' } }.foo.bar` should be minified to `"baz"`.

Would modifying js_parser maybeRewritePropertyAccess be the place for this to go?

<details>
  <summary>Original issue is here. Click to expand.</summary>
  
`console.log({foo: 'bar'}.foo === 'bar')` is not minified to `console.log(!0)`
esbuild does minify some other simple statements like this:
`console.log('foo' === 'foo')` _is_ minified to `console.log(!0)`

Terser minifies both statements.

---

My story: I was using Snowpack which uses `import.meta.env` to access the environment, e.g. `import.meta.env.NODE_ENV`. (instead of process.env.) I added support for this in rollup using the resolveMetaImport plugin hook.

My input:

```js
if (import.meta.env.NODE_ENV === 'development') {
    console.log('dev');
} else {
    console.log('prod');
}
```
Output from rollup which inlines the `import.meta.env` access:
```js
if ({"NODE_ENV":"production"}.NODE_ENV === "development") {
  console.log("dev");
} else {
  console.log("prod");
}
```
with esbuild's minification:
```js
{NODE_ENV:"production"}.NODE_ENV==="development"?console.log("dev"):console.log("prod");
```

I was hoping that esbuild would recognise this pattern and remove the dead code. Terser's output in this case:
```js
console.log("prod");
```

---

</details>

I understand that esbuild's minifier doesn't aim to support everything, so if that's the case here, all good!

**Comment by evanw** [comment]
I believe that minifying this should be fine provided that the expression is guaranteed to have no side effects. Some edge cases to think about off the top of my head:

* Anything with computed property names should disable this
* The property must not be a getter, setter, or method
* This must do the right thing in the case of duplicate keys
* This should be disabled if one of the properties is `__proto__`
* This should probably also never minify to `undefined` if the key is missing because it may be on the `Object` prototype

**Comment by adamburgess** [comment]
If it never minifies to undefined, the existance of `__proto__` shouldn't be a problem, right? If the key you're looking for is in the object, take it (as it has precedence), otherwise don't replace the access.

My first version using maybeRewritePropertyAccess is quite simple and seems to work. It only handles property access, index access must use something else.

> * Anything with computed property names should disable this
> * This must do the right thing in the case of duplicate keys

ooh, terser does the wrong thing:
```js
export const computed = {
    a: 'bad',
    [String.fromCharCode(97)]: 'good' // equiv. ['a']: 'good'
}.a; // should be 'good'
```
```js
export const computed=["bad",String.fromCharCode(97)][0]; // 'bad'
```

**Comment by evanw** [comment]
Good catch about terser! I see you have already filed this as https://github.com/terser/terser/issues/980.

> If it never minifies to undefined, the existance of `__proto__` shouldn't be a problem, right?

I believe you are correct. I was thinking of those rules in order and didn't realize the next rule eclipses that rule.

**Comment by evanw** [comment]
I just thought of another case:

```js
console.log({
  foo: function() { return this.bar },
  bar: true,
}.foo())
```

It would be bad if that was changed to this:

```js
console.log(function() { return this.bar }())
```
