### ISSUE TITLE
silent flag

### ISSUE THREAD

**Issue by scorredoira** [evanw/esbuild#117]
Would you consider adding a --silent or --verbose flag to allow output only errors?

**Comment by evanw** [comment]
Yes. Although I'm thinking the setting could maybe more of a log level. Then you could set it to several levels without needing to add additional settings (errors/warnings/status/verbose).

**Comment by scorredoira** [comment]
Any option that allows to make it silent unless there is a problem would be great.

Anyway, thanks a lot for the project. It's a pleasure to use it.
