### ISSUE TITLE
Implicit `sideEffects: false` for node builtins

### ISSUE THREAD

**Issue by mjackson** [evanw/esbuild#1173]
It looks like `import` of node builtins are not removed from the output bundle when they aren't used.

I made a test repo here: https://github.com/mjackson/esbuild-node-builtins-sideeffects

If you change the `import` in `input.js` to use `./local-fs` instead of `fs`, esbuild removes the `import` from the output bundle because there is a `sideEffects: false` in `package.json`, so `./local-fs` is considered free from side effects.

It'd be great if esbuild could do the same for all node builtins since AFAICT none of them actually have side effects.

**Comment by evanw** [comment]
Closing as a duplicate of #705.
