### ISSUE TITLE
Sideeffects array doesn't work with globbing

### ISSUE THREAD

**Issue by benaadams** [evanw/esbuild#1184]
If `"sideEffects"` is an array it should act as marking everything as `sideffects: false` except the files that match the items in the array.

However the warnings suggest is working the otherway around?

```
warning: Ignoring this import because "....ts" was marked as having no side effects
12 │ import "./...";
   ╵        ~~~~~~~~~~~~~
package.json:15:2: note: It was excluded from the "sideEffects" array in the enclosing "package.json" file
15 │   "sideEffects": [
   ╵   ~~~~~~~~~~~~~
```

Marking everything as `sideffects: true` except the files listed in the `sideEffects` array?

**Comment by benaadams** [comment]
From webpack docs https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free

> If your code did have some side effects though, an array can be provided instead:
```
{
  "name": "your-project",
  "sideEffects": ["./src/some-side-effectful-file.js"]
}
```

**Comment by benaadams** [comment]
I included it in the array to mark it as having side effects whereas every other file has no side effects; so its inclusion should mean its not marked as having no side effects.

i.e. there are 3 states

1. `"sideEffects": true` every file potentially has side effects
2. `"sideEffects": false` no side effects in any files
3. `"sideEffects": [ "file.*", "file1.ts" ]` no side effects in any files; except `file1.ts` and any matching pattern `file.*` which have side effects

**Comment by benaadams** [comment]
More specifically in my example the `package.json` has
```json
  "sideEffects": [
    "polyfills.*"
  ],
```
And esbuild outputs
```
$ esbuild src/AoA/Avatar.ts --minify --bundle --outfile=../../Servers/AoA.Portal/wwwroot/assets/js/aoa.avatar.js
 > src/AoA/Windows.ts:12:7: warning: Ignoring this import because "src/AoA/polyfills.ts" was marked as having no side effects
    12 │ import "./polyfills";
       ╵        ~~~~~~~~~~~~~
   package.json:15:2: note: It was excluded from the "sideEffects" array in the enclosing "package.json" file
    15 │   "sideEffects": [
       ╵   ~~~~~~~~~~~~~

1 warning
```
And the output `.js` there is none of the `prototype` modifying calls from the `polyfills.ts` as they  haven't been included, which is the opposite behaviour of webpack

**Comment by evanw** [comment]
Thanks for the additional detail. It looks like you are relying on some undocumented Webpack-specific behavior that I wasn't aware of. The path `src/AoA/polyfills.ts` can be marked as having side effects using `"src/AoA/polyfills.ts"` or `"src/AoA/polyfills.*"`, but it can apparently also be done using `"polyfills.*"`.

I wasn't aware of the last behavior (matching on file names instead of package subpaths). After experimenting with Webpack it looks like it's specific to file names (e.g. `"AoA/polyfills.*"` doesn't work). I really wish the Webpack documentation actually documentated how the feature works.

I can add this feature to esbuild as well.

**Comment by benaadams** [comment]
Ah, yes using the full (relative) path does look to work as expected. Thank you 💜

**Comment by benaadams** [comment]
>  After experimenting with Webpack it looks like it's specific to file names (e.g. "AoA/polyfills.*" doesn't work)

I assume you'd need to glob it? 

> A "side effect" is defined as code that performs a special behavior when imported, other than exposing one > or more exports. An example of this are polyfills, which affect the global scope and usually do not provide an export.
>
> ...
> 
> The array accepts simple glob patterns to the relevant files. It uses glob-to-regexp under the hood (Supports: *, **, {a,b}, [a-z]). Patterns like *.css, which do not include a /, will be treated like **/*.css.

So would need to be `**/AoA/polyfills.*`

Also the match applies to any imported files (including and overriding any setting in `node_modules` etc)

> Note that any imported file is subject to tree shaking. This means if you use something like css-loader in your project and import a CSS file, it needs to be added to the side effect list so it will not be unintentionally dropped in production mode:

**Comment by evanw** [comment]
Ah you're right, it is documented. My mistake. Thanks for the reference.

**Comment by benaadams** [comment]
Updated title to more correctly represent the issue (is less dramatic than I thought)

Regards the usefulness of the pattern matching; it can be helpful when the package contains many modes of module packaging and the files are repeated many times in different places (typescript, usm, CommonJS, es6 etc), rather than specifying each path and filetype specifically (e.g. `*.ts`,`*.mjs`,`*.js`)
