### ISSUE TITLE
how can I config the sourcemap file name with API?

### ISSUE THREAD

**Issue by wenyanqi** [evanw/esbuild#119]
![image](https://user-images.githubusercontent.com/5893714/82222913-87086b80-9954-11ea-84f3-07cfc42180e6.png)

I want to use esbuild through API. But I find the sourcemap file attribute 'source' is always "/input.jsx".

**Comment by wenyanqi** [comment]
With command, it's ok .
![image](https://user-images.githubusercontent.com/5893714/82223596-6ee51c00-9955-11ea-8c16-cd713f2a1367.png)

**Comment by evanw** [comment]
This is what the `sourcefile` option in the API is for:

https://github.com/evanw/esbuild/blob/13ed883e49772804ce5cc393242e5c9450c507e9/npm/esbuild/lib/main.d.ts#L8

**Comment by wenyanqi** [comment]
> This is what the `sourcefile` option in the API is for:
> 
> https://github.com/evanw/esbuild/blob/13ed883e49772804ce5cc393242e5c9450c507e9/npm/esbuild/lib/main.d.ts#L8

thank you for your reply. it's seems ok in the map file. 
![image](https://user-images.githubusercontent.com/5893714/82282006-63c9d480-99c5-11ea-88e7-375d9c672b6f.png)

But the source file seems loss 'sourceMappingURL'.
![image](https://user-images.githubusercontent.com/5893714/82282020-6b897900-99c5-11ea-943f-fdfbe297cd0c.png)

which supposed to be 
![image](https://user-images.githubusercontent.com/5893714/82282537-a3dd8700-99c6-11ea-8de7-3e77f972db15.png)

**Comment by evanw** [comment]
I made it so the API doesn't add the `sourceMappingURL` comment because esbuild doesn't know where the output will end up being written to or served from. I figured that since your code that uses the esbuild API knows this, it'd be straightforward to just append a comment to the JavaScript you get back from the API yourself if you want a source map comment.

Here's an example of how to do this if you want to write the output to a file:

```js
const { js, jsSourceMap } = await service.transform(input, {
  loader: 'tsx',
  sourcemap: true,
  sourcefile: 'example/pages/index.tsx',
})

const outfile = 'out.js'
fs.writeFileSync(outfile, `${js}//# sourceMappingURL=${outfile}.map\n`)
fs.writeFileSync(`${outfile}.map`, jsSourceMap)
```

**Comment by wenyanqi** [comment]
> ```js
> `${js}//# sourceMappingURL=${outfile}.map\n`)
> ```

Ok, thank you.
