### ISSUE TITLE
[Bug] Duplicated identifier for multiple entries using minify

### ISSUE THREAD

**Issue by elv1n** [evanw/esbuild#1201]
It's easier to understand the issue by taking a look at the [reproducible example](https://github.com/elv1n/esbuild-duplicated-identifier-issue/blob/master/dist/entry1.js)

There are two identical identifiers `sameName` that will cause an app crash.
```
import{a as sameName,b as sameName}from"./chunk-XVEQLNW5.js";
```

I found the problem only using multiple entries with `--splitting` and `--minify` options

Manual steps
Files:
```
// test1.js
export const sameName = {}
// test2.js
export const sameName = {}
// entry2.js
import { sameName } from './test1';
import { sameName as renameVar } from './test2';

export {
  sameName,
  renameVar
}
// entry1.js
export * from './entry2'
```

```shell
esbuild --bundle --outdir=dist --minify --format=esm --splitting entry1.js entry2.js
```

**Comment by evanw** [comment]
Thanks for the report. It looks like names imported from other chunks are currently not being considered for renaming when minification is enabled, which is an oversight. I'll fix this in the next release.
