### ISSUE TITLE
Support the `:-ms-lang()` CSS pseudo-class

### ISSUE THREAD

**Issue by kaksmet** [evanw/esbuild#1205]
The `_:-ms-lang(x)` selector has been used for targeting IE 10+ and Edge, as documented [here ](https://jeffclayton.wordpress.com/2015/04/07/css-hacks-for-windows-10-and-spartan-browser-preview/)and [here](https://blog.trigent.com/css-browser-specific-hacks/).

esbuild 0.11.15 prints the following warning:
```
warning: Unexpected "("
    1 │ _:-ms-lang(x), .selector {
      ╵           ^
```

**Comment by evanw** [comment]
Thanks for the report. It turns out this was a bug in the lexer. Tokens that start with `-` are ident-like but are sometimes `<function-token>` instead of `<ident-token>` ([reference](https://drafts.csswg.org/css-syntax-3/#consume-token)).
