### ISSUE TITLE
add file to bundle from plugin

### ISSUE THREAD

**Issue by Arcath** [evanw/esbuild#1206]
I'm going around in circles at the moment trying to figure out how to add a file to the bundle.

Bascially after markdown parses the file and returns the files contents I'd like to take the _local_ images and add them to the bundle. 

What do I return from an onLoad callback to get it to then queue up more files?

**Comment by evanw** [comment]
You can cause them to be imported using `import` statements in the file returned from the onLoad callback.

**Comment by Arcath** [comment]
Awesome thanks!
