### ISSUE TITLE
how to support less

### ISSUE THREAD

**Issue by Dolov** [evanw/esbuild#1207]
when i build my app 
throw error
app.tsx:3:7: error: No loader is configured for ".less" files: style.less
thanks your me

**Comment by evanw** [comment]
You will need a plugin. There are some here: https://github.com/esbuild/community-plugins. Or you can write your own: https://esbuild.github.io/plugins/#load-callbacks.

**Comment by Dolov** [comment]
> You will need a plugin. There are some here: https://github.com/esbuild/community-plugins. Or you can write your own: https://esbuild.github.io/plugins/#load-callbacks.

thanks it  work for me
