### ISSUE TITLE
Returning Object from constructor minification

### ISSUE THREAD

**Issue by MatthewAnstey** [evanw/esbuild#1208]
Hello, thanks for creating such a great tool!

Was having a play around with proxies and noticed this issue with the minified code.

```
class A {
  constructor(opts: any) {
    console.log(opts);
  }
}

export class B extends A {
  version = 5;
  hello = () => {
    alert("Hello");
  };
  constructor(opts: any) {
    super(opts);
    return new Proxy(this, {
      set() {
        return true;
      },
    });
  }
}
```

When I run 

```esbuild foo.ts --outfile=bar.js --target=es2019 --minify```

Super is not called at the top of the constructor resulting in "Uncaught ReferenceError: must call super constructor before using 'this' in derived class constructor." error.  TBH I'm really not sure if this is the correct use of proxy in a constructor, but thought I'd flag. 

```
class o {
  constructor(e) {
    console.log(e);
  }
}
export class B extends o {
  constructor(e) {
    this.version = 5;
    this.hello = () => {
      alert("Hello");
    };
    return (
      super(e),
      new Proxy(this, {
        set() {
          return !0;
        },
      })
    );
  }
}
```

**Comment by evanw** [comment]
Thanks for the report. This should definitely work. The minifier bug will be fixed in the next release.
