### ISSUE TITLE
Image Entrypoints

### ISSUE THREAD

**Issue by braddunbar** [evanw/esbuild#1213]
We just started using esbuild recently, and it's great for building our JS and CSS files. We would also like to use it to hash our images and write them to the output directory. We use the meta file to map js and css entrypoints to their output and using `example.png` as an entrypoint almost works already, but it also generates a `.js` file which gets the `entryPoint` in the meta file.

Is there any reason that images and, more generally, any entrypoint that uses the file loader can't have its own output annotated with `entryPoint` in the meta file? This change would allow us to use esbuild for all our static assets instead of using a separate solution for images.

*Note: I would only expect this for images included as **entrypoints**. I don't have any issues with images loaded as imports from javascript or css files.*

For example, this command:

```
esbuild example.png --outdir=out --loader:.png=file --metafile=meta.json
```

…produces this output in the metafile:

```
{
  "inputs": {
    "example.png": {
      "bytes": 372320,
      "imports": []
    }
  },
  "outputs": {
    "out/example-HWRBZE4Q.png": {
      "imports": [],
      "exports": [],
      "inputs": {
        "example.png": {
          "bytesInOutput": 372320
        }
      },
      "bytes": 372320
    },
    "out/example.js": {
      "imports": [],
      "exports": [],
      "entryPoint": "example.png",
      "inputs": {
        "example.png": {
          "bytesInOutput": 43
        }
      },
      "bytes": 43
    }
  }
}

```

…but I would expect this output:

```
{
  "inputs": {
    "example.png": {
      "bytes": 372320,
      "imports": []
    }
  },
  "outputs": {
    "out/example-HWRBZE4Q.png": {
      "imports": [],
      "exports": [],
      "entryPoint": "example.png",
      "inputs": {
        "example.png": {
          "bytesInOutput": 372320
        }
      },
      "bytes": 372320
    }
  }
}
```

**Comment by evanw** [comment]
Right now there are only two main content types: JS and CSS. All loaders must ultimately convert to one of those two types. I have thought about adding additional content types so you could e.g. use esbuild to minify or pretty-print JSON, but that doesn't currently work. The reason why you get a JS file when you do this is that the `file` loader generates a JS file that exports the file path as a string. The implications of doing this in all of the various cases would need to be thought through together. For now I'd recommend just copying files over to the output file yourself.

**Comment by evanw** [comment]
You can now do this with the `copy` loader, which was added in [version 0.14.44](https://github.com/evanw/esbuild/releases/v0.14.44).
