### ISSUE TITLE
[Deno] dead loop with huge stdin input of css

### ISSUE THREAD

**Issue by evanw** [evanw/esbuild#1219]
This was originally filed by @ije over at https://github.com/esbuild/deno-esbuild/issues/1, but that repo is only for deployments. Transferring here instead:

> When i try to build a large css file (3.6mb, tailwind.css) as **stdin** input, the build falls into an infinite loop:
> 
> ```js
>  const ret = await esbuild({
>     stdin: {
>       loader: 'css',
>       sourcefile: url,
>       contents: css // 3.6mb, tailwind.css
>     },
>     minify: true,
>     write: false,
>     sourcemap: false,
>   })
> ```
> 
> use filepath works fine: 
> 
> ```js
>  const ret = await esbuild({
>     entryPoints: ['./tailwind.css'],
>     minify: true,
>     write: false,
>     sourcemap: false,
>   })
> ```
> 
> __
> 
> deno 1.9.2 (release, x86_64-apple-darwin)

**Comment by evanw** [comment]
Thanks for the report. It looks like in Deno, `write(bytes)` doesn't actually write the provided bytes. It may only write some of those bytes and you need to try again later. This is why the code I had ported over from node was failing. I'll need to build a write queue to handle this.

**Comment by ije** [comment]
thanks, you are super fast as esbuild!
