### ISSUE TITLE
Exclude files from sourcemaps

### ISSUE THREAD

**Issue by edoardocavazza** [evanw/esbuild#1227]
Hello! I would like to exclude some files from the sourcemaps while keeping them in the bundle. Is it possible? In my use case I would like to exclude injected files.

**Comment by evanw** [comment]
You can remove a file from the generated source map by adding the following comment to the file:

```js
//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbIiJdLCJtYXBwaW5ncyI6IkEifQ==
```

**Comment by edoardocavazza** [comment]
Thank you!
