### ISSUE TITLE
OpenBSD support / other OSs in general?

### ISSUE THREAD

**Issue by falsifian** [evanw/esbuild#1235]
On OpenBSD (recent snapshot, amd64), `npm install esbuild` gives the below output indicating it's unsupported.

I had no trouble with the [build from source](https://esbuild.github.io/getting-started/#build-from-source) instluctions: `go build ./cmd/esbuild` just worked.

Would it be possible to make `npm install` just work on OpenBSD, or in general on any platform where `go build ./cmd/esbuild` works without modification?

I don't know much about `npm install`. Is it only for installing pre-built binaries? Is it not able to run commands to build things?

(Context: This came up when I tried to install [beancount-import](https://github.com/jbms/beancount-import/) from the master branch. `python3 -m pip install .` is close to "just working"; support for `esbuild` was one of just two little hiccups.)

```
falsifian moth ~ $ npm install esbuild

> esbuild@0.11.17 postinstall /home/falsifian/node_modules/esbuild
> node install.js

Unsupported platform: openbsd x64 LE
npm WARN enoent ENOENT: no such file or directory, open '/home/falsifian/package.json'
npm WARN falsifian No description
npm WARN falsifian No repository field.
npm WARN falsifian No README data
npm WARN falsifian No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! esbuild@0.11.17 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the esbuild@0.11.17 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/falsifian/.npm/_logs/2021-05-01T18_03_01_002Z-debug.log
```

**Comment by evanw** [comment]
I have been adding other OSs as people ask for them and can confirm that they actually work. I can add OpenBSD.

**Comment by falsifian** [comment]
Thank you! If you give me a prod when it's released, I'm happy to check whether it works (at least in the context of beancount-import).
