### ISSUE TITLE
TypeScript declared fields not correctly ignored when useDefineForClassFields is set

### ISSUE THREAD

**Issue by MattiasBuelens** [evanw/esbuild#1242]
When `useDefineForClassFields` is set in `tsconfig.json`, esbuild incorrectly emits code in the class constructor for fields that are marked with `declare`.

### Input
```typescript
export class Example {
    field1: string;
    declare field2: string;

    constructor(arg1: string) {
        this.field1 = arg1;
    }
}
```

tsconfig:
```json
{
  "compilerOptions": {
    "target": "es2015",
    "module": "es2015",
    "strict": true,
    "esModuleInterop": true,
    "useDefineForClassFields": true
  }
}
```

### Output with TypeScript 4.2
```javascript
export class Example {
    constructor(arg1) {
        Object.defineProperty(this, "field1", {
            enumerable: true,
            configurable: true,
            writable: true,
            value: void 0
        });
        this.field1 = arg1;
    }
}
```
[Playground](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=2#code/KYDwDg9gTgLgBAYwDYEMDOa4FEQoLZhLBwDeAsAFBzVwBmAlsEgCYCMAXHGjFPQHYBzANyUacZsGQooxBk2YAmTt16CRFUTQQQ+KgK4IY0ABTSBHLj34CAlKU1jqMABb00AOjktWcALxwzVnUxAF9KEKA)

### Output with esbuild
```javascript
var __defProp = Object.defineProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, {enumerable: true, configurable: true, writable: true, value}) : obj[key] = value;
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};

// src/index.ts
var Example = class {
  constructor(arg1) {
    __publicField(this, "field1");
    __publicField(this, "field2");
    this.field1 = arg1;
  }
};
export {
  Example
};
```

### Expected results
The line `__publicField(this, "field2");` should **not** be in the generated code, since `field2` has a `declare` modifier. I expect the correct output to be:
```javascript
var Example = class {
  constructor(arg1) {
    __publicField(this, "field1");
    this.field1 = arg1;
  }
};
```

Note that setting `useDefineForClassFields` to `false` (the default value) does correctly ignore the declared field:
```javascript
var Example = class {
  constructor(arg1) {
    this.field1 = arg1;
  }
};
```

[Repository with full reproduction case](https://github.com/MattiasBuelens/esbuild-bug-declare-field)

* OS: Windows 10 2004
* Node version: 14.16.0
* npm version: 6.14.12
* esbuild version: 0.11.18

**Comment by evanw** [comment]
Thanks for the report! The fix for this will be in the next release.
