### ISSUE TITLE
What is the official version for  esbuild-darwin-64

### ISSUE THREAD

**Issue by amitrai99** [evanw/esbuild#1245]
Searching for esbuild-darwin-64 on Google throws up a lot of versions. Can we document which is the official version?

NPM seems to have the official version on top.

https://www.npmjs.com/search?q=esbuild-darwin-64

**Comment by evanw** [comment]
Docs are here: https://esbuild.github.io/getting-started/.

**Comment by evanw** [comment]
Closing because this is already documented.
