### ISSUE TITLE
Dynamic import polyfill

### ISSUE THREAD

**Issue by Mokshit06** [evanw/esbuild#1246]
Since the native ESM dynamic imports support landed later than ESM via script tags, some browsers still don't support it.

It would be great if esbuild had an option to rename the dynamic import function so that polyfills like [this one](https://github.com/GoogleChromeLabs/dynamic-import-polyfill) can be used.

Rollup has a [similar option](https://rollupjs.org/guide/en/#renderdynamicimport) to handle this use case.

**Comment by aminya** [comment]
Duplicate of #16?

**Comment by ludofischer** [comment]
What browsers are you interested in supporting? According to caniuse.com, there is very little difference between the percentage of active browsers that support ESM ([92.65%](https://caniuse.com/es6-module)) and those that also support ESM dynamic imports ([92.34%](https://caniuse.com/es6-module-dynamic-import)). It's true their geographical coverage is likely biased.

**Comment by Mokshit06** [comment]
@ludofischer I was going through Vite's documentation and there they had a [section on dynamic import polyfill](https://vitejs.dev/guide/features.html#dynamic-import-polyfill) that Vite includes by default.

It mentioned that there is a browser support discrepancy between the two so I thought it would be by a larger percentage, but since almost all the browsers that support esm via script tags support dynamic imports, I don't think this option is required.
