### ISSUE TITLE
`class extends Array` seems to be transpiled wrong.

### ISSUE THREAD

**Issue by phryneas** [evanw/esbuild#1247]
We have this class that `extends Array`:
https://github.com/reduxjs/redux-toolkit/blob/3256ffd51b1b766026f7b0e27fe2620a0562aea9/src/utils.ts#L28-L57

```js
export class MiddlewareArray extends Array {
   concat(...arr {
    return new MiddlewareArray(...super.concat(...arr))
  }

  prepend(...arr) {
    if (arr.length === 1 && Array.isArray(arr[0])) {
      return new MiddlewareArray(...arr[0].concat(this))
    }
    return new MiddlewareArray(...arr.concat(this))
  }
}
```

esbuild transpiles that to:
```js
var MiddlewareArray = /** @class */ (function (_super) {
    __extends(MiddlewareArray, _super);
    function MiddlewareArray() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    MiddlewareArray.prototype.concat = function () {
        var arr = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            arr[_i] = arguments[_i];
        }
        return new (MiddlewareArray.bind.apply(MiddlewareArray, __spreadArray([void 0], _super.prototype.concat.apply(this, arr))))();
    };
    MiddlewareArray.prototype.prepend = function () {
        var arr = [];
        for (var _i = 0; _i < arguments.length; _i++) {
            arr[_i] = arguments[_i];
        }
        if (arr.length === 1 && Array.isArray(arr[0])) {
            return new (MiddlewareArray.bind.apply(MiddlewareArray, __spreadArray([void 0], arr[0].concat(this))))();
        }
        return new (MiddlewareArray.bind.apply(MiddlewareArray, __spreadArray([void 0], arr.concat(this))))();
    };
    return MiddlewareArray;
}(Array));
```

Now, the transpiled constructor function
```js
    function MiddlewareArray() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
```

returns an object of type `Array` and not `MiddlewareArray`.

We had this code working fine with `tsdx`, which uses `rollup` before, so I assume that this is some kind of edge case that `esbuild` does not handle correctly.

Could you please look into this?

PS:
experimenting with   
```js
static get [Symbol.species]() {
    return MiddlewareArray;
  }
```
did unfortunately not change anything for the better.

PPS: you can see our build script at https://github.com/reduxjs/redux-toolkit/blob/feature/v1.6-integration/scripts/build.ts

PPPS: you can see our current build output for comparison at https://unpkg.com/browse/@reduxjs/toolkit@1.5.1/dist/redux-toolkit.umd.js starting at lint 1009

**Comment by evanw** [comment]
> esbuild transpiles that to:

There is no code in this repo that transforms `class` statements into `function` statements. You must be confusing esbuild with another tool. Closing this issue as invalid.

FWIW this looks like the output of the official TypeScript compiler, so my guess is that you're compiling your code with `tsc` instead of or in addition to esbuild.

**Comment by phryneas** [comment]
Damn, I'm terribly sorry - I did not set that transpilation setup up, we had a PR for that incoming and someone else reviewed it - i am just fighting this bug right now, so I probably missed that part. Thank you for the quick feedback!
