### ISSUE TITLE
Stripped object property quotes cause unwanted obfuscation

### ISSUE THREAD

**Issue by DerGernTod** [evanw/esbuild#1251]
esbuild automatically strips quotes from object properties if it's able to:
```
echo let x = {"foo":true}; | npx esbuild
// let x = {foo: true};
echo let x = {"fo-o":true}; | npx esbuild
// let x = {"fo-o": true};
```
this imposes issues when processing the code further on: closure compiler distinguishes between quoted and non-quoted property definitions. quoted ones don't get obfuscated. this is a quick and easy way to prevent obfuscation for public apis. since esbuild strips the quotes, closure can't distinguish those anymore and will obfuscate everything, causing api functions to be mangled. this even happens without `minify`.

is there a way this can be prevented? it doesn't seem to be possible via plugins (i didn't invest too much time in developing one though, so in case it _is_ possible, some guidance would be nice). 

btw i love this project!

**Comment by evanw** [comment]
Sorry, esbuild is not designed to work with the language that Google Closure Compiler’s advanced mode uses. This is deliberate because it operates on a different language from JavaScript with different semantics (although they do share the same syntax, so it is confusing). 

AFAIK Google Closure Compiler is a complete tool chain including a type checker, bundler, minifier, and code optimizer. I suspect you will get the best results if you just use it for everything without using other tools. What do you need esbuild for that Google Closure Compiler can’t do?

**Comment by jridgewell** [comment]
This also applies to minifying with terser. It has a `keep_quoted` config that allows you to mangle properties except quoted ones.

We pass our esbuild output to terser for a final compression to save a few extra bytes (terser still achieves smaller sizes than esbuild's `--minify`), and would like to see this implemented as well.

**Comment by DerGernTod** [comment]
To be honest, we just use closure compiler for its advanced optimizations. Bundling with closure is simply a pain. I already run out with 58 chunks because I simply have that many bundles. I would have to provide it around 800 files because afaik is not able to resolve esm modules and include the required files automatically in the bundle. Either that, or the documentation is really bad. So we use ts for types, want to use esbuild for bundling (each of our 58 entry points to 58 output bundles) and use closure compiler for advanced optimizations.

**Comment by kzc** [comment]
> This also applies to minifying with terser.

fwiw, in addition to the `mangle.properties` option `keep_quoted`, uglify-js and its forks can preserve the input's quoted properties with the output option `keep_quoted_props`, but whether the upstream transpiler(s) and bundler(s) also preserve them is a different matter.

```
$ echo 'console.log({"foo":1, bar: 2});' | uglify-js -mc -b keep_quoted_props,beautify=0  --mangle-props keep_quoted
console.log({"foo":1,o:2});
```
```
$ echo 'console.log({"foo":1, bar: 2});' | terser -mc -b keep_quoted_props,beautify=0  --mangle-props keep_quoted
console.log({"foo":1,o:2});
```

A name cache can also be produced or used to specify the mangled property names so they can be stable across builds:

```
$ echo 'console.log({"foo":1, bar: 2});' | uglify-js --name-cache cache.json -mc -b keep_quoted_props,beautify=0  --mangle-props keep_quoted,debug
console.log({"foo":1,_$bar$_:2});

$ cat cache.json && echo
{"vars":{"props":{}},"props":{"props":{"$bar":"_$bar$_"}}}
```

Notice the unquoted property `bar` above was mangled in debug mode to `_$bar$_`.

**Comment by evanw** [comment]
Properties will be quoted when minification is disabled in the next release of esbuild. This isn't saying that esbuild being a preprocessor for Google Closure Compiler is now officially supported (it's not). I won't be testing esbuild in this scenario and there may be other things that are currently broken about this workflow, or that may break in the future. But preserving property quotes was easy to add and should be easy to maintain so I think it's fine to add this feature for its own sake.
