### ISSUE TITLE
[REPO] split esbuild repo

### ISSUE THREAD

**Issue by danny007in** [evanw/esbuild#1255]
Like
- evanw/esbuild (For bundle JS/TS OR JSX/JSX)
- evanw/esbuild-js-minifier (To minify js)
- evanw/esbuild-css-minifier (To minify css)

Yes, i know it will become breaking changes,
This will help to choose required packages

**Comment by evanw** [comment]
I do not plan on splitting this repo. The current setup is working well for me. Closing.
