### ISSUE TITLE
Watch mode: run code before rebuild starts?

### ISSUE THREAD

**Issue by Hallot** [evanw/esbuild#1258]
I am building with watch mode on, and would like to print how much time it took to rebuild the bundle.  
Potentially, I would also like to clear the TTY so I only have the latest errors displayed.

To do this, I would need an event similar to `onRebuild`, like `onRebuildStarted`. Am I correct in assuming this does not exist?  
Something similar to:
```
let buildStart
const buildConfig = {
    ..., // standard build arguments
    watch: {
        onRebuildStarted() {
            buildStart = Date.now()
        },
        onRebuild(error, result) {
            const buildEnd = Date.now()
            console.log(`Built in ${buildEnd - buildStart} ms.`)
        }
    }
}
esbuild.build(buildConfig).catch(() => process.exit(1))
```

Is there a way to achieve what I want without using an external watcher?  
Finally, if the answer to both questions is no, could this be a potential future feature?

Thanks.

**Comment by Hallot** [comment]
> I was also hoping there might be an `onComplete` function for when the initial build completes, ie. before any rebuild, but I couldn't find anything for that, either.

Can't you do `esbuild.build(buildConfig).then(doStuff).catch(() => process.exit(1))` or am I missing something?

**Comment by evanw** [comment]
I think you should be able to use these:

* https://esbuild.github.io/plugins/#start-callbacks
* https://esbuild.github.io/plugins/#end-callbacks

**Comment by Hallot** [comment]
Thanks, that's exactly what I was looking for.
