### ISSUE TITLE
Supported TypeScript version and changelog?

### ISSUE THREAD

**Issue by elektronik2k5** [evanw/esbuild#126]
Hello and thanks for creating this awesome project! :smiley: 

I searched the docs and issues but found no relevant information for a simple question: which version of TypeScript is currently supported? The readme has an overview of JS features, but unlike JS (referring to TC39 stages 3-4), TS evolves faster with several releases a year. A good example is TypeScript's [previous release, `typescript@3.8`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html), which introduced [new syntax](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-exports).

Related: I didn't find a changelog or release notes. Without those it is very difficult to consider `esbuild` for non toy projects.

Specifically, [esbuild was suggested](https://github.com/denoland/deno/issues/5432#issuecomment-631876142) for use in [deno](deno.land), but I can't evaluate the feasibility of using `esbuild` without knowing what's currently supported (specifically in TS) and what's the project roadmap.

**Comment by evanw** [comment]
> which version of TypeScript is currently supported?

That's a good question. I should add a compatibility table for TypeScript in addition to JavaScript. Just like esbuild doesn't support a single version of JavaScript, esbuild also doesn't support a single version of TypeScript. It supports some features from later versions without supporting some features from earlier versions.

For example, it supports the new type-only import/export syntax you linked to but it doesn't yet support [private fields](https://github.com/evanw/esbuild/issues/47) or [experimental decorators](https://github.com/evanw/esbuild/issues/104). I want to do a push to implement those at some point but right now I'm focusing on a rewrite of the core bundler to support tree shaking and code splitting.

> I didn't find a changelog or release notes. Without those it is very difficult to consider esbuild for non toy projects.

I should get a changelog together. That said, keep in mind that I'm not aware of anyone using this in production yet, so it may still be difficult to consider esbuild for non-toy projects even with a changelog.

**Comment by evanw** [comment]
I just got both of those started, and they can be improved over time. So I consider this issue fixed.

FWIW the only TypeScript-specific feature that I'm aware of that I don't support is experimental decorators. Most of the work to improve compatibility with TypeScript is just filling out support for newer JavaScript features.

**Comment by elektronik2k5** [comment]
Thank you for the detailed additions, they are clear and helpful. :smiley:
