### ISSUE TITLE
Allow global updates with Object.assign instead of normal assignment

### ISSUE THREAD

**Issue by erikbrinkman** [evanw/esbuild#1264]
Currently using the `global-name` option assigns to the global name like
```
var xyz = (() => {
```
You can assigns to sub fields without overwriting by specifying sub fields to generate
```
var xyz = xyz || {};
xyz.abc = (() => {
```
However, there's no way to append to a global variable like
```
var xyz = Object.assign(xyz || {}, (() => {
```

This seems like a generally useful ability, and is handled by rollup in certain instances. I'm not sure exactly what the api should look like. Making it default would be a breaking change, and seems maybe unnecessary. I could see a boolean flag, but maybe that's also complicated given that it only applies to `global-name`. I'm happy to put up a PR if this makes sense. I'm also open to the idea that this fits better in a plugin.

**Comment by evanw** [comment]
You can inject whatever wrapping code you need to using the [banner](https://esbuild.github.io/api/#banner) and [footer](https://esbuild.github.io/api/#footer) features. Specifically a banner of `var xyz = Object.assign(xyz || {}, (() => {` and a footer of `return xyz })())` might do the trick.

**Comment by erikbrinkman** [comment]
This does indeed work, although seems a little inelegant, or too elegant depending on how you look at it. Still given that it's not hard to replicate and I'm not certain an extra api would be more elegant, this seems good enough.

Thanks for the quick response!
