### ISSUE TITLE
Question about hashing output JS file

### ISSUE THREAD

**Issue by ivanduka** [evanw/esbuild#1265]
Hi,

Thank you for this awesome project!

Question: is it possible to set the output file to NAME-HASH.js as opposed to NAME.js?

My current script in package.json is very simple: `"build-js": "esbuild src/ts/main.tsx --bundle --minify --target=es2015 --outfile=dist/js/main.js",`

However, after bundling and minifying the project into a single `main.js` file, I want to:

1. Calculate `main.js` hash
2. Make it a part of the filename, like in `main-82da7f60280662901d4732c6c3c88a695449f777d708089760798adb81519ff5.js` for aggressive caching and then 
3. change my `<script defer src="/js/main.js" type="text/javascript"></script>` to `<script defer src="/js/main-82da7f60280662901d4732c6c3c88a695449f777d708089760798adb81519ff5.js" type="text/javascript"></script>` in my`index.html` 

Can I do any of those steps with esbuild? If not, can you advise me which tools can help me with that?

Thanks!

**Comment by geoffharcourt** [comment]
You can do this with the `entry_names` parameter: https://esbuild.github.io/api/#entry-names

**Comment by ivanduka** [comment]
Thanks, it's exactly what I was looking for! :)
