### ISSUE TITLE
Possible performance improvement via reducing calls to getting file stats

### ISSUE THREAD

**Issue by Jarred-Sumner** [evanw/esbuild#1276]
Caveating this with: I haven't benchmarked this suggestion.

If we look at the source for [`os.ReadFile` in Go](https://github.com/golang/go/blob/master/src/os/file.go#L669-L685), we can see that it calls `f.Stat()` to get the file size:

```go
func ReadFile(name string) ([]byte, error) {
	f, err := Open(name)
	if err != nil {
		return nil, err
	}
	defer f.Close()


	var size int
	if info, err := f.Stat(); err == nil {
		size64 := info.Size()
		if int64(int(size64)) == size64 {
			size = int(size64)
		}
	}
	size++ // one byte for final read at EOF


	// If a file claims a small size, read at least 512 bytes.
```

If we look at `cache_fs.go`, we can see that immediately before reading a file, it calls `fs.ModKey`:
```go
// If the file's modification key hasn't changed since it was cached, assume
// the contents of the file are also the same and skip reading the file.
modKey, modKeyErr := fs.ModKey(path)
if entry != nil && entry.isModKeyUsable && modKeyErr == nil && entry.modKey == modKey {
  return entry.contents, nil, nil
}

contents, err, originalError := fs.ReadFile(path)
if err != nil {
  return "", err, originalError
}
```

If we look at the source of `modKey()` (called by `fs.ModKey`), we can see that it calls `unix.Stat`:
```go
func modKey(path string) (ModKey, error) {
	stat := unix.Stat_t{}
	if err := unix.Stat(path, &stat); err != nil {
		return ModKey{}, err
	}

	// We can't detect changes if the file system zeros out the modification time
	if stat.Mtim.Sec == 0 && stat.Mtim.Nsec == 0 {
		return ModKey{}, modKeyUnusable
	}
```

Suggestion: pass the file size from `unix.Stat` when reading the file

Could also make it only open/close the file once instead of opening/closing for ModKey, and then opening/closing for reading

**Comment by evanw** [comment]
This is an interesting observation. However, I tried doing this (both using the stat size and single open/close) and it unfortunately didn't change the benchmark time at all, at least on macOS. Presumably the file metadata is already in the file system's cache when it's observed the second time.

**Comment by evanw** [comment]
I've deciding to close this since it doesn't appear that this is a performance win. I'm definitely open to such a change if it is a performance win but otherwise the current interface is cleaner, so I'd prefer to leave the code the way it is if this change would make no difference.
