### ISSUE TITLE
How to build on the fly without `entryPoints` and `outfile` ?

### ISSUE THREAD

**Issue by yaquawa** [evanw/esbuild#1279]
Is it possible to build on the fly(in memory) without `entryPoints` and `outfile` in the js API?

**Comment by evanw** [comment]
You can use [`write: false`](https://esbuild.github.io/api/#write) to have esbuild provide output files in memory, and you can use [plugins](https://esbuild.github.io/plugins/#using-plugins) to provide input files to esbuild in memory.

**Comment by ggoodman** [comment]
@yaquawa you may also like the [stdin](https://esbuild.github.io/api/#stdin) option to inject a custom, single entrypoint, if you are looking to reduce plugin complexity.

**Comment by yaquawa** [comment]
Hey, thanks for the answers!!  I'll give it a try later on.
