### ISSUE TITLE
Allow working-dir be set via a flag?

### ISSUE THREAD

**Issue by Aghassi** [evanw/esbuild#1287]
My use case is probably highly specific, but I figured I'd ask. My team is using ESBuild under Bazel and pulling in the published go binary as a workspace dependency (mainly to avoid doing an npm cache bust and reinstall when we upgrade ESBuild). This binary is able to be run just fine, but the main issue is that Bazel always invokes binaries relative to the root of the monorepo, meaning relative path imports don't work nicely out of the box. I assume this would be fixed by using `--working-dir` but this is currently only configurable through the node API and not through a flag on the binary. Are you open to allowing that be a binary flag? Alternatively, is there a better way to handle relative path resolutions in this situation that you think is better shaped for ESBuild?

**Comment by evanw** [comment]
The way to set the current working directory via the CLI is to use `cd`. This not being supported seems like a limitation of Bazel, not of esbuild. I know nothing about Bazel but I assume [this file](https://github.com/bazelbuild/rules_nodejs/blob/c61fc57e74081d5f8f504d80be36aed71b55b255/packages/esbuild/launcher.js#L25) inside Bazel would have to change. The call to node's `spawn` function can pass the `cwd` argument to set the current working directory (docs are [here](https://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options)).

**Comment by Aghassi** [comment]
Thanks for the clarity @evanw ! I will work with the rules_nodejs team to improve support. I appreciate your responsive feedback and attentiveness to my questions. I will close this for now.
