### ISSUE TITLE
BuildResult.OutputFiles differs between JS and Go

### ISSUE THREAD

**Issue by jwilsson** [evanw/esbuild#1288]
Hey!
When using the `onEnd` callback from a JS plugin the `result.outputFiles` is undefined unless `write: false` is passed in the `build` call, for example:

```js
import { build }  from 'esbuild';

const plugin = {
  name: 'my-plugin',
  setup: (build) => {
    build.onEnd((result) => {
      console.log(result.outputFiles); // Will be undefined
    })
  }
};

build({
  entryPoints: ['./src/app.jsx'],
  outdir: './dist',
  write: true,
  plugins: [plugin],
});
```

This seems to be expected, given [this comment](https://github.com/evanw/esbuild/blob/269ef769ff621bd9ff94d31188f3205f5079a9ee/lib/shared/types.ts#L125) in the type declarations.

However, when using the Go API, `BuildResult.OutputFiles` is always set. No matter the value of `write`, for example:

```go
package main

import (
  "fmt"

  "github.com/evanw/esbuild/pkg/api"
)

func main() {
  plugin := api.Plugin{
    Name: "my-plugin",
    Setup: func(build api.PluginBuild) {
      build.OnEnd(func(result *api.BuildResult) {
        for _, f := range result.OutputFiles {
          fmt.Printf("%s\n", f.Path) // Will always print "/path/to/my/file"
        }
      })
    },
  }

  api.Build(api.BuildOptions{
    EntryPoints: []string{"src/app.jsx"},
    Outdir:      "./dist",
    Write:       true,
    Plugins:     []api.Plugin{plugin},
  })
}
```

So this more of a question than an issue, which is the expected behaviour? Or is the difference in behaviour expected?

**Comment by evanw** [comment]
This is intentional. It's free to return the output files in Go since they are already in memory, but it's expensive to return them in JS because they must be copied between separate processes. So you only want to return them in JS if it's absolutely necessary but in Go you might as well return them even when they aren't necessary in case they are helpful.

**Comment by jwilsson** [comment]
Cool, makes sense. Thanks for the explanation!
