### ISSUE TITLE
[docs] I contribute Chinese docs to esbuild.

### ISSUE THREAD

**Issue by 92hackers** [evanw/esbuild#129]
I translated the esbuild docs into Chinese:  http://docs.breword.com/evanw-esbuild

And i posted the docs on some frontend community websites which are popular in China，many developers view it and know esbuild.

@evanw , If possible, i want to write a PR to add the Chinese docs link in readme.md to make esbuild spread more widely, or push the Chinese docs into esbuild repo.

Thanks.

**Comment by evanw** [comment]
Thank you for doing this. I'm concerned that translated documentation will become more and more out of date as time goes on, so I don't think it makes sense to add it to the esbuild repo itself. But I think it'd be fine to link to it from the readme as long as the link says what version of the documentation it represents to avoid confusion.

**Comment by 92hackers** [comment]
@evanw, Thanks for your reply.

I'm watching  esbuild project and when you release an new version, i will fetch the new repo content and check if docs content updated, if so, i will translate updated content.

also, the  docs highlight the current version of code:

<img width="1054" alt="Screen Shot 2020-05-25 at 11 23 50" src="https://user-images.githubusercontent.com/5372618/82788053-4cde2300-9e9a-11ea-82bf-efbcd778af74.png">

laster, i will create a PR and add the Chinese docs link into readme.md.
