### ISSUE TITLE
esbuild cannot resolve node built-in modules starting with `_`

### ISSUE THREAD

**Issue by Mokshit06** [evanw/esbuild#1294]
When I try to bundle a file that imports `_http_common`, which is a Node built-in module, esbuild throws an error `Could not resolve "_http_common" (mark it as external to exclude it from the bundle)`. The same thing also happens with other Node built-in modules that start with `_` (`_http_client`, `_http_agent`).

**Reproduction**

`echo "export * from '_http_common'" | esbuild --bundle --platform=node`

**Comment by evanw** [comment]
It looks like esbuild's internal list of built-in modules that come with node is outdated. I'll update the list. In the meantime you can use `--external:_http_common` as a workaround.
