### ISSUE TITLE
Option 'Metafile' in API documentation only handles cli

### ISSUE THREAD

**Issue by BePo65** [evanw/esbuild#1299]
According to the documentation, the option 'metafile' using the esbuild cli requires a filepath argument (e.g. `--metafile=meta.json`).

Trying to use this option via the script api results in
```
error: "metafile" must be a boolean
```

So perhaps the documentation should be completed with something like

```
in a script, `metafile` is a boolean that, if true, adds a property `metafile` to the result of the `build` method.
```

**Comment by BePo65** [comment]
Sorry, I missed the 'js' button.

**Comment by hinell** [comment]
@BePo65 I think we have to reopen this issues cause it's better to have a direct path specified in the JS api.
