### ISSUE TITLE
Unexpected identifier using NODE_ENV for react in define

### ISSUE THREAD

**Issue by zephyrus21** [evanw/esbuild#1306]
Getting an error like `Uncaught SyntaxError: Unexpected identifier` while using the code snippet below.

I have imported react package from unpkg.com using a custom plugin unpkgPathPlugin.
Also I am using esbuild-wasm version `0.8.27`

``` js
const result = await ref.current.build({
      entryPoints: ['index.js'],
      bundle: true,
      write: false,
      plugins: [unpkgPathPlugin()],
      define: {
        'process.env.NODE_ENV': '"production"',
        global: 'window',
      },
    });
```

**Comment by evanw** [comment]
There unfortunately isn't enough information here to be able to say what's wrong. Can you provide instructions for reproducing the issue? What does the generated code that causes the error look like? Also 0.8.27 is really old (almost 70 versions ago). Does the problem still happen with the latest version?

**Comment by zephyrus21** [comment]
I upgraded to the latest version and the problem ins now gone. My bad should have upgraded earlier. Thanks.
