### ISSUE TITLE
Uncaught SyntaxError: Export 'import_types' is not defined in module

### ISSUE THREAD

**Issue by PEDx** [evanw/esbuild#1307]
some chunk file have not declare `import_types`, but export it
If I can find some way to know which file is the introduction of this variable
In the link phase, do I have a chance to log something
[https://github.com/evanw/esbuild/blob/master/internal/bundler/linker.go#L209](https://github.com/evanw/esbuild/blob/master/internal/bundler/linker.go#L209)

![img](https://img9.doubanio.com/view/photo/l/public/p2651321905.webp)

**Comment by evanw** [comment]
Is it possible to provide a way for me to reproduce this issue? Also, does this issue reproduce in the latest version of esbuild?

**Comment by blechatellier** [comment]
I'm running into the same issue using vite (2.3.4) with the latest version (1.6.2) of "@chakra-ui/react", it works ok with the previous version (1.6.1).

**Comment by PEDx** [comment]
> I'm running into the same issue using vite (2.3.4) with the latest version (1.6.2) of @chakra-ui/react, it works ok with the previous version (1.6.1).

 go back to 1.6.1 , it fine for me. 👍  thank you

**Comment by PEDx** [comment]
> Is it possible to provide a way for me to reproduce this issue? Also, does this issue reproduce in the latest version of esbuild?

From now on, I am not sure whether it is caused by esbuild, it may be caused by other libraries after upgrading. I will continue to see where is the problem.
