### ISSUE TITLE
sourcefile ignored in TransformFailure

### ISSUE THREAD

**Issue by hgl** [evanw/esbuild#131]
When there is a compilation error, it seem the the thrown `TransformFailure` error's `file` property is always `/input.js`, even if the `sourcefile` option was passed.

It'd be great if that property could also reflect the `sourcefile` value

**Comment by evanw** [comment]
Yes, this is a good point. I'm planning to unify the `transform` API with stdin/stdout support since they both are a way to do file-less input. This would be good to fix as a part of that unification.
