### ISSUE TITLE
@__PURE__ comments dropped when `bundle: true`

### ISSUE THREAD

**Issue by phryneas** [evanw/esbuild#1319]
According to https://github.com/evanw/esbuild/issues/653, `@__PURE__` comments should only be dropped when `minify: true` is specified - and that also seems to be the case from looking at the source code ( https://github.com/evanw/esbuild/blob/34a27b20765629ecce212e029764c0c5a911255d/internal/js_printer/js_printer.go#L1643 ).

But it seems that those comments are also dropped when `bundle: true` is specified:
```bash
% echo '/*@__PURE__*/fn()' | yarn esbuild --bundle                                                                                                                                               size-limit
yarn run v1.22.10
$ /home/weber/tmp/redux-starter-kit/node_modules/.bin/esbuild --bundle
(() => {
})();
Done in 0.08s.
```

This is very unfortunate, as we are trying to use this for library bundling - and having these comments in there is very valuable for tree splitting. Is there anything that could be done to prevent this?

**Comment by phryneas** [comment]
It does, however not seem to be the reason.

`echo 'export const x = /*@__PURE__*/ fn()' | yarn esbuild --bundle`

I'm sorry for the wrong report. I'm just banging my head against the wall here and had hoped I had finally found the reason :(

Have a good day!

**Comment by evanw** [comment]
Adding a `/* @__PURE__ */` annotation means "remove this if the result is unused" so it will be removed if the result is unused.
