### ISSUE TITLE
Option to not remove unused functions

### ISSUE THREAD

**Issue by ChildishGiant** [evanw/esbuild#1321]
I'm using esbuild to bundle dependencies into a script for a game engine. This script needs to have a function of a set name that the engine will call each frame. Currently even with `--tree-shaking=ignore-annotations` and `"sideEffects": true` esbuild removes the function. Maybe a comment to show that the next line is actually used, just not in this file?

**Comment by evanw** [comment]
The bundler only supports three output formats right now: IIFE, CommonJS, and ESM. In all three formats, unused functions are local to the module's scope and cannot be observed externally, so removing them is valid and should have no visible effect. It sounds like maybe you are trying to use esbuild with an unsupported (possibly custom) output format? If that's the case then it might not work, and you may need to use another build tool instead. I'm not currently looking to expand the number of output formats that esbuild supports.

**Comment by ChildishGiant** [comment]
Ah okay, yea that's what I'm looking for. Thanks for the pointers 😃
