### ISSUE TITLE
\x3c within strings is replaced with <, causing script tags to be closed preemptively by the browser

### ISSUE THREAD

**Issue by DerGernTod** [evanw/esbuild#1322]
I have some code that renders a popup window including script tags, somewhat like this:
```
const POPUP_CONTENT = `<html><body><script>var foo = "bar"\x3c/script><div>something</div></body>`;
```

The \x3c is required because otherwise, when the browser parses the script that contains this string, it will close the script tag and the rest of the script will simply be rendered (in this case, `<div>something</div></body>`).

Unfortunately esbuild replaces `\x3c` with `<`:

```
echo "var foo = \"\x3c\";" | npx esbuild // outputs 'var foo = "<";';
```

This of course breaks everything for us since all code that comes after `\x3c/script>` is simply not executed. I also tried to split the string into a concatenated version that the browser doesn't recognize, but of course esbuild optimizes this and transforms it back into a single string.

It seems like this can be worked around by building a string array and joining it, but since this has to be done during runtime it's rather uncanny:
```
const POPUP_CONTENT = [`<html><body><script>var foo = "bar"<`, `/script><div>something</div></body>`].join("");
```

Is this expected or just an unhandled problem?

**Comment by jridgewell** [comment]
Parsing of `<script>` node contents, and parsing of JS files are different. I don't believe it's possible to just inject a script file into a `<script>` node and have it behave the same.

I think whatever system you're using to inject the `<script>` node contents should be fixed to scan for `</script` and correct it back to `\x3c`.

**Comment by evanw** [comment]
> Is this expected or just an unhandled problem?

This is just unhandled. I'm actually surprised I haven't handled it yet since I'm already aware of the problem.

> I think whatever system you're using to inject the `<script>` node contents should be fixed to scan for `</script` and correct it back to `\x3c`.

I think it's reasonable for esbuild to handle this case. Other JavaScript tools such as Terser already handle this.

**Comment by jridgewell** [comment]
> I think it's reasonable for esbuild to handle this case. Other JavaScript tools such as Terser already handle this.

This leaves a weird edge case with tagged template literals:

```js
function printRaw(strings) {
  console.log(strings.raw);
}

printRaw`</script>`;
```

It's not possible to transform the `</script` in a way that will preserve the runtime meaning without down leveling the entire expression.

**Comment by evanw** [comment]
> It's not possible to transform the `</script` in a way that will preserve the runtime meaning without down leveling the entire expression.

Good point. I just added down-leveling for tagged template literals in this case.
