### ISSUE TITLE
without __esModule property when format esm module cause load module error 

### ISSUE THREAD

**Issue by zhangyuang** [evanw/esbuild#1323]
from vite [issue](https://github.com/vitejs/vite/issues/3399) i think it's esbuild problem

### Describe the bug

when the thirdparty module is esm format, esbuild manage it without add `__esModule` property. but webpack will add `__esModule` property.

for examle, the source code is

```js
// swiper.esm.js
export { default as Swiper, default } from './esm/components/core/core-class';
export { default as Virtual } from './esm/components/virtual/virtual';
//...
```

After esbuild format ,will output

```js
import {default as default2, default as default3} from "./esm/components/core/core-class";
import {default as default4} from "./esm/components/virtual/virtual";
export {
  default14 as A11y,
  default3 as default
};

```

without `__esModule` property.

it will be cause an error. if a module build by webpack, the source code as below

```js
//  react-id-swiper sourceCode
import Swiper from 'swiper';
new Swiper()
```
after webpack build , output code will add helper function `__importDefault`
```js
// react-id-swiper
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
var swiper_1 = __importDefault(require("swiper"));
new swiper_1.default(swiperNodeRef.current, object_assign_1.default({}, props))
```

but because of `__esModule` is undefined, `__importDefault` function will add default property once again cause the return value `__importDefault(require("swiper")).default` is not the current object will be error

![image](https://user-images.githubusercontent.com/17424434/118099685-25180000-b408-11eb-9367-ab30c7ce14fb.png)
![image](https://user-images.githubusercontent.com/17424434/118099722-33feb280-b408-11eb-8e38-6ed8b0028b3d.png)
 

### Reproduction

https://github.com/zhangyuang/vite-react-swiper-error

### System Info

vite/2.3.2 darwin-x64 node-v12.18.3

### additional

when i add `__esModule` property in source code manually, it can be executed succeed like

```js
export { default as Swiper, default } from './esm/components/core/core-class';
export { default as Virtual } from './esm/components/virtual/virtual';
export const __esModule = true 
```

In this case，maybe vite can add `__esModule` in esbuild plugin . for example

```js
build.onLoad({ filter: /.*/, namespace: 'swiper' }, ({ path: id }) => {
        return {
          loader: 'js',
          resolveDir: root,
          contents: `export * from "filepath"
          export {default} from "filePath"
          export const __esModule = true 
          `
        }
      })
```

**Comment by dravenww** [comment]
I am also experiencing the same problem

**Comment by Rainmen-xia** [comment]
Looking forward esbuild to solving this problem。

**Comment by daniel100097** [comment]
Any workaround ?

**Comment by lbwa** [comment]
Maybe this isn't esbuild bug. No matter TypeScript compiler or babel compiler,  any **esm output** wouldn't create `__esModule` flag in JS community practices.

**Comment by zhangyuang** [comment]
Babel and tsc will generate `__esModule` from `esm` to `commonjs` tell bundler tools which is a esm module。
Most of bundler tools will add `_interopRequireDefault` methods to load this obj。

```js
function _interopRequireDefault(obj) {
  // 判断传入的对象是 ESModule 还是 CommonJS 模块
  return obj && obj.__esModule  // 这里就是之前说的为什么要加上 `__esModule` 属性
    ? obj                       // 如果是 ESModule，就直接返回传入的模块对象
    : { 'default': obj };       // 如果不是 ESModule，则将传入的 `module.exports` 放置在一个新对象 `default` 上，来模拟 ESModule
}
```
It cause an error, after vite use esbuild optimize `vue@2.0` will output below code

```js
 var _vue = (init_vue_runtime_esm(), vue_runtime_esm_exports);
    var _vue2 = _interopRequireDefault(_vue);
    function _interopRequireDefault(obj) {
      return obj && obj.__esModule ? obj : {default: obj};
    }
```

![image](https://user-images.githubusercontent.com/17424434/120151740-368e4400-c21f-11eb-8553-0408584b26ff.png)

**Comment by lbwa** [comment]
@zhangyuang 
![image](https://user-images.githubusercontent.com/32980314/120153036-d13b5280-c220-11eb-8675-b36e6207de43.png)

I said **output syntax** is es module, __esModule should be in commonjs product, not es module product. Your product is esm product, not commonjs. So __esModule isn't in it.

should: 
```js
exports.default = function foo() {}

exports.__esModule = true
```

shouldn't:

```js
export { default } from 'abc'

export const __esModule = true
```

**Comment by lbwa** [comment]
> Babel and tsc will generate `__esModule` from `esm` to `commonjs` tell bundler tools which is an esm module。
> Most of bundler tools will add `_interopRequireDefault` methods to load this obj。
> 
> ```js
> function _interopRequireDefault(obj) {
>   // 判断传入的对象是 ESModule 还是 CommonJS 模块
>   return obj && obj.__esModule  // 这里就是之前说的为什么要加上 `__esModule` 属性
>     ? obj                       // 如果是 ESModule，就直接返回传入的模块对象
>     : { 'default': obj };       // 如果不是 ESModule，则将传入的 `module.exports` 放置在一个新对象 `default` 上，来模拟 ESModule
> }
> ```
> 
> It cause an error, after vite use esbuild optimize `vue@2.0` will output below code
> 
> ```js
>  var _vue = (init_vue_runtime_esm(), vue_runtime_esm_exports);
>     var _vue2 = _interopRequireDefault(_vue);
>     function _interopRequireDefault(obj) {
>       return obj && obj.__esModule ? obj : {default: obj};
>     }
> ```
> 
> ![image](https://user-images.githubusercontent.com/17424434/120151740-368e4400-c21f-11eb-8553-0408584b26ff.png)

Those code has __esModule because those code is commonjs syntax product, not esm product.

**Comment by zhangyuang** [comment]
`__esModule` generated for compatible cjs and esm。In fact, in `esbuild@0.9.7` will generate `__esModule` property
With `esbuild@0.9.7` format `vue2.0` to `esm` will output below code which is true.

```js
var __markAsModule = (target) => __defProp(target, "__esModule", {value: true});

var require_vue_runtime_esm = __commonJS((exports) => {
  __markAsModule(exports);
  __export(exports, {
    default: () => vue_runtime_esm_default
  });
```

**Comment by lbwa** [comment]
1. I knew what __esModule and _interopRequireDefault done.
2. We have a misunderstanding between you and me. I said your js product format is esm syntax, so it never has __esModule flag, unless commonjs synatx.

I have use the latest version esbuild(v0.12.5). It works very well if output format is cjs and esm, and it has an expected behavior you want.

![image](https://user-images.githubusercontent.com/32980314/120157454-a273ab00-c225-11eb-979d-9408132a480b.png)

**Comment by zhangyuang** [comment]
-.- yes, i know `__esModule` only be generated in commonjs module in the persent.

here is the issue [repo](https://github.com/zhangyuang/vite-elemnt-error-repo)
when lock vite version in 2.2.4 which use esbuild version 0.9.7 can output the true code in `node_modules/.vite` directory

**Comment by zhangyuang** [comment]
@lbwa see #1333

**Comment by sodatea** [comment]
FYI, the `__importDefault` helper is from TypeScript.

**Comment by dravenww** [comment]
demo：https://github.com/tnfe/vite-vue2-pro
use vite and esbuild-plugin-vite-element-ui is running ok.
