### ISSUE TITLE
[Docs]Suggestions on refactoring documents to support multiple languages and multiple versions

### ISSUE THREAD

**Issue by misitebao** [evanw/esbuild#1337]
Hello, @evanw ☺
The current document only supports English (although I have seen other people submit Chinese document links in the issue), and if you want to add internationalization or multi-version functions based on the current document warehouse, it may not Convenience, so I have an idea. I want to use docusaurus to reconstruct the document. While keeping the English document unchanged, add support for other languages so that more developers can read it.

Because I’m not sure if you have any other ideas about the document, I would like to consult your opinion before doing it.

**Comment by evanw** [comment]
I can link to 3rd-party translations but I'm not planning on integrating them into the site. I want the documentation on the site to be up-to-date and 3rd-party translations are always out of date.

I'm also not planning on publishing documentation for different esbuild versions as it's a lot of work for me and esbuild is still before version 1.0.0.

**Comment by misitebao** [comment]
Okay, I get it, thank you for replying to me.
