### ISSUE TITLE
(suggestion) Make "Supported by" text in API docs more readable when both Build & Transform are present

### ISSUE THREAD

**Issue by rpivo** [evanw/esbuild#1340]
<img width="286" alt="Screen Shot 2021-06-01 at 9 09 32 PM" src="https://user-images.githubusercontent.com/28677706/120408847-d631fc00-c31d-11eb-8748-a01344622934.png">

The italic text for "Supported by: Transform | Build" looks like it says "Transform I Build" instead of a pipe character. A comma might appear more readable.

This is more of a low-priority suggestion. Please feel free to close if not desired.

**Comment by evanw** [comment]
What happened to the underlines? The links look like this for me:

![](https://user-images.githubusercontent.com/406394/120539939-f8b72a00-c39c-11eb-91bd-dd9d7122622d.png)

It's pretty clear that these are links with the underlines. Are you perhaps using some browser or browser extension that removes underlines? And if so, is there a workaround I can apply to bring the underlines back?

**Comment by rpivo** [comment]
That's odd -- I see the underlines now, and I'm unable to reproduce without the underlines. The underlines help a lot. I've been checking on Chrome on a Mac.

I'll close this.
