### ISSUE TITLE
What is the order of execution of esbuild's plugins and loaders, and is there any relevant documentation address?

### ISSUE THREAD

**Issue by stoneyallen** [evanw/esbuild#1347]

**Comment by evanw** [comment]
It should be documented on https://esbuild.github.io/plugins/ but basically it's `onResolve` → `onLoad`. Given an import path you need to figure out what file to load (`onResolve`), and given a file to load you need to figure out how to load it (`onLoad`).

Then that file may itself contain import paths which go back through the plugin system again. So if there's a chain of imports you get `onResolve` → `onLoad` → `onResolve` → `onLoad` → ...

**Comment by stoneyallen** [comment]
Maybe I didn't describe it clearly, it's all my fault. What I'm asking is, when my original file is typescript, what I understand is that esbuild will use ts-loader to process it, and if my plugin is babel, at this point I want to get code that is ts-processed, because babel may not recognize this ts format. So, what I want to ask is what is the order of execution of ts-loader with my custom plugin and can I control the plugin execution timing?

For example, I need to solve the automatic import problem of antd, I use @babel/plugin-import directly in webpack, but in esbuild I need to introduce @babel/plugin-import based on esbuild-plugin-babel, when I compile I find that the code containing ts syntax will report an error, because babel can't recognize it, and when I remove ts syntax I can successfully compile the expected jie

**Comment by evanw** [comment]
FYI this project has nothing to do with Webpack. I also don't know how Webpack works so I won't be able to help.

If you want to transform TypeScript syntax to JavaScript from within a plugin, you could consider calling esbuild again for that. The easiest way to do that is to use the [transform API](https://esbuild.github.io/api/#transform-api). If you're running Babel you could also consider running Babel's TypeScript plugin instead.

**Comment by arpitBhalla** [comment]
Hey @evanw do esbuild uses `tsc` under the hood to convert ts to js, if not, can you please explain me how it works,

**Comment by evanw** [comment]
No. If I did, everything would be horribly slow. Some info: #101. You are also welcome to read the source code since esbuild’s is open source. For example there is [`ts_parser.go`](https://github.com/evanw/esbuild/blob/537195ae84bee1510fac14235906d588084c39cd/internal/js_parser/ts_parser.go):

https://github.com/evanw/esbuild/blob/537195ae84bee1510fac14235906d588084c39cd/internal/js_parser/ts_parser.go#L1-L3

**Comment by stoneyallen** [comment]
> FYI this project has nothing to do with Webpack. I also don't know how Webpack works so I won't be able to help.
> 
> If you want to transform TypeScript syntax to JavaScript from within a plugin, you could consider calling esbuild again for that. The easiest way to do that is to use the [transform API](https://esbuild.github.io/api/#transform-api). If you're running Babel you could also consider running Babel's TypeScript plugin instead.

**Comment by stoneyallen** [comment]
At that time I already thought I could use babel's typescript, but I thought it might be slower because I believe esbuild's original typescript processing is faster, so I first tried to study the transfer api

**Comment by evanw** [comment]
Do you have any more questions? If not, I'd like to close this.
