### ISSUE TITLE
minify cause error on iOS10

### ISSUE THREAD

**Issue by SilentTiger** [evanw/esbuild#1349]
Such as `e["Ⅰ"] = "I"` will transform to `e.Ⅰ = "I"` after minify by esbuild, but `e.Ⅰ = "I"` is not valid on iOS 10.

Can someone tell me how to solve this kinds of problem?

**Comment by evanw** [comment]
I'm using https://kangax.github.io/compat-table/ for my source of browser compatibility data. It looks like I need to be handling the `Updated identifier syntax` section, which I am not currently handling.

**Comment by evanw** [comment]
Actually that's not right.

The character `Ⅰ` is U+2160 ROMAN NUMERAL ONE which is in the "letter number" Unicode category and was added in Unicode 1.1. [The ES5 specification](https://es5.github.io/#x7.6), which predates the "Updated identifier syntax" part of ES6, says an identifier can start with something in the "letter number" category from Unicode 3.0. So this character should be a valid identifier here.

There must be something else going on here. Unfortunately I don't have access to an iOS 10 platform to test on. Xcode doesn't let you install the iOS simulator for something that old (it only goes back to iOS 11.4, which works fine with this syntax).

**Comment by evanw** [comment]
Thanks. With that information I can reproduce it in the simulator on iOS 11.4 now. It looks like Safari doesn't implement ES5 correctly in this case. Specifically this part:

> _IdentifierStart_ ::
> &nbsp; &nbsp; &nbsp; &nbsp; UnicodeLetter
> &nbsp; &nbsp; &nbsp; &nbsp; `$`
> &nbsp; &nbsp; &nbsp; &nbsp; `_`
> &nbsp; &nbsp; &nbsp; &nbsp; `\` _UnicodeEscapeSequence_
>
> _UnicodeLetter_
> &nbsp; &nbsp; &nbsp; &nbsp; any character in the Unicode categories “Uppercase letter (Lu)”, “Lowercase letter (Ll)”, “Titlecase letter (Lt)”, “Modifier letter (Lm)”, “Other letter (Lo)”, or “Letter number (Nl)”.

The source code from JavaScript core from a while ago looks like this:

```c++
static NEVER_INLINE bool isNonLatin1IdentStart(UChar c)
{
    return U_GET_GC_MASK(c) & U_GC_L_MASK;
}
```

which is wrong because `U_GC_L_MASK` is defined as this:

```c++
/** Mask constant for multiple UCharCategory bits (L Letters). @stable ICU 2.1 */
#define U_GC_L_MASK \
            (U_GC_LU_MASK|U_GC_LL_MASK|U_GC_LT_MASK|U_GC_LM_MASK|U_GC_LO_MASK)
```

This omits the "letter number" category. So it looks like this is specifically a problem only with letter number characters such as the character U+2160 ROMAN NUMERAL ONE.
