### ISSUE TITLE
Minify "constant" template strings to reduce visible whitespace

### ISSUE THREAD

**Issue by eamodio** [evanw/esbuild#1351]
In one of my projects I'm using a lot of GraphQL querys, which in the code are just large \` quoted constant strings.

Terser minifies these by converting them to `'` quoted and converting the newlines and whitespace accordingly. This would make these query not stand out in the minified code as a large block of easily readable text.

**Comment by evanw** [comment]
It sounds like you’re suggesting for esbuild to replace newline characters with a `\n` escape sequence when minifying. But that would make the file size larger since two bytes are bigger than one. So that would not be a good thing to do when minification is enabled.

**Comment by eamodio** [comment]
Right, right -- man it's been a long day. Given then I guess I'll just close this -- it was just jarring opening up the minified file and seeing all my queries standing out so strongly. :smile:

**Comment by Vanilagy** [comment]
@eamodio I get you, but then at the end of the day, that file is only meant for computers anyway!
