### ISSUE TITLE
How to enable debug logging for path resolution

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#1353]
I sometimes met something like `Could not resolve xxx` problems, which is kind of hard to debug
![image](https://user-images.githubusercontent.com/8898718/120911146-4c848480-c6b7-11eb-8c22-085324ba01f1.png)

Typescript has something like --explainFiles to debug problem like this, it would be helpful to print the the default resolve process to debug problem like this.

**Comment by evanw** [comment]
Did you try `logLevel: 'debug'`?

**Comment by hardfist** [comment]
`logLevel: 'debug'` not working, but `logLevel: 'verbose'` works
