### ISSUE TITLE
0.12.4 breaks build for echarts-gl (error: Transforming const to the configured target environment ("ES5") is not supported yet)

### ISSUE THREAD

**Issue by gunters63** [evanw/esbuild#1355]
Probably related to #1332

Steps to reproduce:

1. Scaffold a new Vite project with the react-ts template (other templates will likely work too)
2. Add packages echarts, echarts-for-react and echarts-gl
3. Add the following lines at the top of App.tsx:
````
import 'echarts-gl';
import * as echarts from 'echarts';
import ReactECharts from 'echarts-for-react';
````
4. Run the dev server

Result: vitejs/esbuild run into errors like this:

````
 > node_modules/.pnpm/echarts-gl@2.0.4_echarts@5.1.1/node_modules/echarts-gl/lib/component/grid3D/install.js:22:4: error: Transforming const to the configured target environment ("ES5") is not supported yet
    22 │     const AxisView = registers.ComponentView.extend({
       ╵     ~~~~~
   node_modules/.pnpm/echarts-gl@2.0.4_echarts@5.1.1/node_modules/echarts-gl/jsconfig.json:3:18: note: The target environment was set to "ES5" here
     3 │         "target": "ES5"
````

Esbuild versions prio to 0.12.4 work fine.

**Comment by evanw** [comment]
This has already been addressed. From the [release notes of the latest release](https://github.com/evanw/esbuild/releases/tag/v0.12.6):

> * Only respect `target` in `tsconfig.json` when esbuild's target is not configured ([#1332](https://github.com/evanw/esbuild/issues/1332))
>
>     In version 0.12.4, esbuild began respecting the `target` setting in `tsconfig.json`. However, sometimes `tsconfig.json` contains target values that should not be used. With this release, esbuild will now only use the `target` value in `tsconfig.json` as the language level when esbuild's `target` setting is not configured. If esbuild's `target` setting is configured then the `target` value in `tsconfig.json` is now ignored.

**Comment by gunters63** [comment]
Yes, that worked when i esbuild a file importing echarts-gl on the command line with `esbuild --target=esnext ...`

For Vite i tried:
````
  build: {
    target: 'esnext'
}
````
and 
````
  esbuild: {
    target: 'esnext'
}
````

but neither worked. How to tell it Vite?

**Comment by gunters63** [comment]
> This has already been addressed. From the [release notes of the latest release](https://github.com/evanw/esbuild/releases/tag/v0.12.6):
> 
> > * Only respect `target` in `tsconfig.json` when esbuild's target is not configured ([#1332](https://github.com/evanw/esbuild/issues/1332))
> >   In version 0.12.4, esbuild began respecting the `target` setting in `tsconfig.json`. However, sometimes `tsconfig.json` contains target values that should not be used. With this release, esbuild will now only use the `target` value in `tsconfig.json` as the language level when esbuild's `target` setting is not configured. If esbuild's `target` setting is configured then the `target` value in `tsconfig.json` is now ignored.

What I don't understand here:

As per Typescript definition, every subdirectory in the source tree can have its local tsconfig.json which overrides the parents settings. That is why echart breaks because there is a local tsconfig in the node module folder.
But I think local tsconfigs should not be considered inside the node_modules folder because those tsconfigs there are only valid for the modules own build configurations.

**Comment by gunters63** [comment]
Thanks for the quick fix :)

**Comment by akshayjai1** [comment]
https://stackoverflow.com/questions/73277461/transforming-const-to-the-configured-target-environment-es5-is-not-supported/73277462#73277462
