### ISSUE TITLE
Consider using import assertions to specify loader

### ISSUE THREAD

**Issue by jed** [evanw/esbuild#1356]
Now that [import assertions](https://2ality.com/2021/01/import-assertions.html) have landed in Chrome, I wonder if this might be an elegant way to specify a loader from within a file. For example, consider the case in which I have `server.js` file for a server that serves an `app.js` file, and want to import (and not evaluate) the file as text, without renaming the file extension to suit the build script. Something like this would make that possible without a build configuration:

```js
import appjs from './app.js' assert {type: 'text'};
```

**Comment by evanw** [comment]
I have considered this. However, this goes against the design of import assertions. From [the import assertion specification](https://tc39.es/proposal-import-assertions/#sec-hostresolveimportedmodule):

> _moduleRequest_.[[Assertions]] must not influence the interpretation of the module or the module specifier; instead, it may be used to determine whether the algorithm completes normally or with an [abrupt completion](https://tc39.es/ecma262/#sec-completion-record-specification-type).

So the specification itself says they must not be used for something such as specifying the loader. If it is to be used by esbuild, it's purpose could be only to cause a build error if the loader ended up being different than the one determined by esbuild's path resolution process. But that seems pretty useless, so I haven't introduced something like that.

**Comment by jed** [comment]
Ah, shame that assertion scope is so limited. Thanks for giving it a thought!

**Comment by hardfist** [comment]
@evanw  webpack already support using import assertions to specify loader, which is super convenient 
https://github.com/webpack-contrib/css-loader#exporttype

**webpack.config.js**
```ts
const webpack = require('webpack')
/**
 * @type {import('webpack').Configuration}
 */
module.exports = {
  mode: 'development',
  entry: {
    main: './src/index.js',
  },
  module: {
    rules: [
      {
        assert: {type: 'text'},
        type: 'asset/source'
      }
    ]
  }
}
```
**src/index.js**
```ts
import dict from './test.json' assert { type: 'text'}
console.log({
  dict
})
```
**src/test.json**
```
{
  "answer": 42,
  "secret": 43
}
```
could you reconsider support it in esbuild, which would be really nice.

**Comment by ggoodman** [comment]
Perhaps instead of allowing it to specify loader directly, it might be helpful to pass the assertion metadata to plugins. That being said, the static matching for plugins on file names could also be extended to have some simple form of declarative KV matching for assertions (like k8s matchers).

**Comment by evanw** [comment]
The specification forbids this, and I don't think it's a good idea to have esbuild deviate from the specification here. There was a recent Twitter thread about this: https://twitter.com/bradleymeck/status/1506646993325772802. It looks like the way to do this in the future may be to use another proposed language feature instead: https://github.com/tc39/proposal-import-reflection.
