### ISSUE TITLE
Unsupported source map comment for compiled TypeScript

### ISSUE THREAD

**Issue by AlCalzone** [evanw/esbuild#1358]
I originally opened this issue at https://github.com/egoist/esbuild-register/issues/11, but it looks like the warnings come from `esbuild` itself.

When running scripts with `esbuild-register`, I'm getting a ton of these warnings in the stdout:
```
{
  column: 21,
  file: 'C:\\Repositories\\node-zwave-js\\packages\\core\\build\\index.js',
  length: 12,
  line: 32,
  lineText: '//# sourceMappingURL=index.js.map',
  namespace: ''
}
Unsupported source map comment
{
  column: 21,
  file: 'C:\\Repositories\\node-zwave-js\\packages\\core\\build\\capabilities\\CommandClasses.js',
  length: 21,
  line: 245,
  lineText: '//# sourceMappingURL=CommandClasses.js.map',
  namespace: ''
}
Unsupported source map comment
{
  column: 21,
  file: 'C:\\Repositories\\node-zwave-js\\packages\\shared\\build\\index.js',
  length: 12,
  line: 21,
  lineText: '//# sourceMappingURL=index.js.map',
  namespace: ''
}
```
These are the default source map comments that TS outputs and I believe they match the comment here
https://github.com/evanw/esbuild/blob/3a4546039a10e24627fd6e2e2897a8f247224ad5/internal/bundler/bundler.go#L560

**Comment by evanw** [comment]
The warning happens because source maps are enabled but esbuild doesn't have enough information to respect the source map comment. I can turn off the warning. Source maps still won't work, however.

**Comment by AlCalzone** [comment]
Turning off the warning would be nice.

Just out of curiosity: Which information is missing there?
The referenced files are already compiled by TS, they are next to the sourcemaps and the source paths in the sourcemaps seem fine to me.

**Comment by evanw** [comment]
That library uses the `transformSync` API which is designed to work in situations without a file system. So it doesn't have the ability to pass in the path resolution directory. The `buildSync` API is more general and could be used to respect the source map comment here.

**Comment by AlCalzone** [comment]
I see - thanks for the explanation!
