### ISSUE TITLE
Implement mangling for css classes and ids across html css javascript

### ISSUE THREAD

**Issue by joelmo** [evanw/esbuild#1363]
I want to attempt to implement this feature as a minification option. This means that class and id names will be shortened to a couple of characters. I started doing this in javascript but it would be neat to do this in go code for better speeds, also esbuild have all parsers and ast trees thats needed.
If possible, I want the implementation to start by walking all css asts to collect classes and ids while at same time replacing them with shorter names. This name mapping is saved and passed to the js and html minifiers. Replacing names in html is easy. But in javascript it can be difficult to distinguish if a literal is meant to be a selector or something else. For this reason it should be possible to skip certain selectors from being renamed.
Assuming the average name length is 10 chars, can be renamed to 1-2 chars. The possible saving should be about ~80% of all class/id selectors across html js and css.

**Comment by bryanjtc** [comment]
@joelmo Did you found a solution?
