### ISSUE TITLE
Error of missing dependencies when platform is set to neutral

### ISSUE THREAD

**Issue by ricardomatias** [evanw/esbuild#1367]
When I try to create a ESM bundle with the platform set to `neutral`, it errors with the following:

`error: Could not resolve "mitt" (mark it as external to exclude it from the bundle)`

Works fine if the target is `browser` or `node`

esbuild.config

```js
import { buildSync } from 'esbuild';

buildSync({
	entryPoints: [ 'lib/index.ts' ],
	outfile: 'build/esm/index.mjs',
	bundle: true,
	minify: true,
	target: 'es6',
	format: 'esm',
	platform: 'neutral',
	external: ['crypto'],
});
```

**Comment by evanw** [comment]
This is because that setting disables all of esbuild's built-in defaults. From [the documentation](https://esbuild.github.io/api/#platform):

> When the platform is set to `neutral`:
>
> * The [main fields](https://esbuild.github.io/api/#main-fields) setting is empty by default. If you want to use npm-style packages, you will likely have to configure this to be something else such as `main` for the standard main field used by node.

If you want the defaults, then don't use `neutral`. Or if you want `neutral`, then you'll have to set up some other things too.

**Comment by ricardomatias** [comment]
> This is because that setting disables all of esbuild's built-in defaults.

Thanks, this makes more sense. I think adding this sentence to the documentation would make the consequences of this option clear.
