### ISSUE TITLE
Uncaught Error: Dynamic require of "overlayscrollbars" is not supported

### ISSUE THREAD

**Issue by danny007in** [evanw/esbuild#1368]
my ts code

```ts

import OverlayScrollbars from 'overlayscrollbars'

if (typeof OverlayScrollbars !== 'undefined') {
  OverlayScrollbars(document.querySelectorAll(SELECTOR_SIDEBAR), {
	/* code */
  })
}

```

error

```console
Uncaught Error: Dynamic require of "overlayscrollbars" is not supported
```

because i exculde 

```js
    external: ['@types/overlayscrollbars', 'overlayscrollbars'],
```

i have also added  `typeof ` with `undefined`
```ts
  if (typeof OverlayScrollbars !== 'undefined') {
```

**Comment by evanw** [comment]
That code example works fine for me, at least with `overlayscrollbars@1.13.1`. Are you sure there isn't any other code involved?

> Uncaught Error: Dynamic require of "overlayscrollbars" is not supported

What does the error message look like for this error? What code does the error message point to?

**Comment by danny007in** [comment]
Probably issue might be
beacuse in `import OverlayScrollbars from 'overlayscrollbars' after excluding also it is appeared in code

**Comment by evanw** [comment]
I'm closing this issue due to age and lack of sufficient information.
