### ISSUE TITLE
async/await with ES6/ES2015 target

### ISSUE THREAD

**Issue by floydspace** [evanw/esbuild#137]
Hi @evanw, could you please explain how can I use async/await when compiling TypeScript to target ES6/ES2015?
I expect that it will compile replacing async/await with Promise, but instead I see it as it is and the following warning:
```
warning: This syntax is from ES2017 and is not available in ES2015
            async function toModel(item) {
```
Thank you.

**Comment by evanw** [comment]
The transforms for all syntax features haven't been written yet. There is not yet code to transform `async` functions into older JavaScript. That is what this warning is about, and why async functions are [documented as unsupported below ES2017](https://github.com/evanw/esbuild/blob/9bdc08dbe37f62be20002fe51fd036e212177aa9/README.md#javascript-syntax-support). I plan to add support for transforming pretty much all of the syntax that's currently supported at some point in the future.

**Comment by floydspace** [comment]
oh didn't catch this in the readme, thank you

**Comment by evanw** [comment]
This should work as of esbuild version 0.5.8.
