### ISSUE TITLE
tree shaking const variables when combined

### ISSUE THREAD

**Issue by s-cork** [evanw/esbuild#1371]
Simple example

```typescript
const a = 'a';
const b = 'b';
export const c = 'c';
```
output
```javascript
var c = "c";
export {
  c
};
```

---

But combining a and b

```typescript
const a = 'a';
const b = 'b';
a + b;
export const c = 'c';
```

results in 

```javascript
var a = "a";
var b = "b";
a + b;
var c = "c";
export {
  c
};
```

I guess esbuild is being conservative about side effects here?

I have a larger file of strings for Unicode categories.
Only some of which I use in the final bundle.
I was hoping that the unused constants would be tree shaken in the final bundle.

Is there something I'm missing?

**Comment by evanw** [comment]
You're correct. The `+` operator is currently considered a side effect since it can call `toString` and/or `valueOf` on the operands.

You are welcome to run another JavaScript optimizer on the output of esbuild such as [Terser](https://terser.org/) that can do this kind of complex analysis.

**Comment by s-cork** [comment]
Thanks for the response - makes sense.
