### ISSUE TITLE
Broken sourcemap with CommonJS format

### ISSUE THREAD

**Issue by aleclarson** [evanw/esbuild#1373]
**Repro:** https://github.com/aleclarson/repro/tree/esbuild-sourcemap#readme

```
git clone https://github.com/aleclarson/repro -b esbuild-sourcemap esbuild-sourcemap-bug
cd esbuild-sourcemap-bug
less README.md
```

**Expected:** A breakpoint in `index.js` should cause VS Code to open `index.js` when debugging

**Actual:** It opens `bundle.js` instead

The reproduction uses `vm.runInNewContext`, <s>so that may have something to do with it.</s> (Actually, that's unlikely to matter, since Sucrase sourcemaps work fine)

**Comment by evanw** [comment]
This looks like a bug in VSCode to me. There's no breakpoint where it decides to break, so I'm not sure why it does. Anyway you just have to click the continue button to get to `index.js`:

https://user-images.githubusercontent.com/406394/123441599-e342b380-d588-11eb-921e-b0bae4c17808.mov

For the record, here are the relevant files and their source maps. They can be visualized by uploading them to https://evanw.github.io/source-map-visualization/:

* **esbuild**

    ```js
    var __defProp = Object.defineProperty;
    var __markAsModule = (target) => __defProp(target, "__esModule", { value: true });
    var __export = (target, all) => {
      __markAsModule(target);
      for (var name in all)
        __defProp(target, name, { get: all[name], enumerable: true });
    };
    __export(exports, {
      x: () => x,
      y: () => y
    });
    let y = 1;
    let x = 1;

    //# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJtYXBwaW5ncyI6Ijs7Ozs7OztBQUFHO0FBQUE7QUFBQTtBQUFBO0FBQUEsSUFBQyxJQUFJO0FDQUwsSUFBQyxJQUFJOyIsIm5hbWVzIjpbXSwic291cmNlcyI6WyJmb28uanMiLCJpbmRleC5qcyJdfQ==
    ```

* **sucrase**

    ```js
    "use strict";Object.defineProperty(exports, "__esModule", {value: true});let y = 1;

    let x = 1;

    exports.x = x; exports.y = y;


    //# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiYnVuZGxlLmpzIiwibWFwcGluZ3MiOiJBQUFHOztBQ0FBOzs7OyIsIm5hbWVzIjpbXSwic291cmNlcyI6WyJmb28uanMiLCJpbmRleC5qcyJdfQ==
    ```

**Comment by softboy99** [comment]
Hi,
i have same problem

**Comment by evanw** [comment]
Closing this issue as it's not a problem with esbuild.
