### ISSUE TITLE
Want esbuild to output as a function not an iife

### ISSUE THREAD

**Issue by navanshu** [evanw/esbuild#1376]
I am bundling typescript for spyder monkey and want the output in this format
```javascript
function (item) {
// doing some operation with item
}
```
I still want to utilise importing some modules into the build.
My source looks like this
```javascript
export default functions(item: SomeType) {
}
```
If i don't import any module then the out has ```  export default ``` which I can just remove from the code but
If I import any another module in it then the problem begins. It then transform the bundle into IIFE. is this some typescript thing or esbuild thins?

**Comment by evanw** [comment]
Well that's a syntax error in JavaScript, so esbuild wouldn't ever output that. You should be able to get that using the [banner](https://esbuild.github.io/api/#banner) and [footer](https://esbuild.github.io/api/#footer) options like this:

```sh
esbuild "--banner:js=function (item) {" "--footer:js=}"
```

If you want to return something in particular, you can use that in combination with the IIFE format like this:

```sh
esbuild --format=iife --global-name=valToReturn "--banner:js=function (item) {" "--footer:js=return valToReturn}"
```

**Comment by navanshu** [comment]
Will try kind of above my head.
