### ISSUE TITLE
Replace import with identifier, in Transform API

### ISSUE THREAD

**Issue by donmccurdy** [evanw/esbuild#1377]
I'm using esbuild's Transform API in a browser-based editor, allowing users to write a script using ES Modules. The script executes in the browser, without access to any filesystem or npm, and allows only a set of npm packages known in advance. Example input:

```typescript
import A, {B, C as D} from 'my-package';
...
```

Because there isn't really a filesystem, I'd like to compile this to something like:

```typescript
const A = dependencies['my-package'];
const {B, C: D} = dependencies['my-package'];
```

I've tried a few things now and have hit some kind of dead end with each of them:

1. Use a [plugin](https://www.npmjs.com/package/@fal-works/esbuild-plugin-global-externals).
    - ERROR: Plugins appear to work only with the Build API, not the Transform API.
2. Compile to CommonJS, such string find/replace is trivial.
    - ERROR: I need top-level await, which doesn't work in CJS mode.
3. Use regular expressions to manually process the imports after compilation.
    - 😕: I suppose this could still work, but I'm hoping to avoid it given the range of the [import syntax options](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import).

Do you know of any options I've missed here? I realize what I'm asking to do isn't really robust for all imports, but to run a script with known packages in a REPL-like environment it would be sufficient.

**Comment by evanw** [comment]
The transform API is basically a limited subset of the build API that only exists to make simple transformation tasks easy. I would try the build API and plugins to do this since what you want to do is more complex than what the transform API is designed for.

**Comment by donmccurdy** [comment]
Have I understood right that the build API requires access to a filesystem, and won't take a string as input? My app is client-side only so that may be a non-starter for me. But I have found some options (e.g. https://www.npmjs.com/package/parse-imports) that would help with processing imports after esbuild completes, so I may go with that option instead.

**Comment by evanw** [comment]
> Have I understood right that the build API requires access to a filesystem, and won't take an in-memory string as input?

That's incorrect. The build API has an explicit API for providing an in-memory string as input: https://esbuild.github.io/api/#stdin. For example:

```js
esbuild.build({
  stdin: {
    contents: 'console.log(true)',
  },
}).then(result => {
  console.log(result.outputFiles[0].text)
})
```

And plugins can be used to provide a file system. For example:

```js
esbuild.build({
  entryPoints: ['some file'],
  plugins: [{
    name: 'example',
    setup(build) {
      build.onResolve({ filter: /.*/ }, args => {
        if (args.path === 'some file')
          return { path: args.path, namespace: 'some namespace' }
      })
      build.onLoad({ filter: /.*/ }, args => {
        if (args.path === 'some file')
          return { contents: 'console.log(true)' }
      })
    },
  }],
}).then(result => {
  console.log(result.outputFiles[0].text)
})
```

**Comment by donmccurdy** [comment]
Oh, thank you! Sounds like I have some good options here then, I'll work with this.

**Comment by cvlmtg** [comment]
@evanw your comment about the use of `stdin` helped me resolving another problem with esbuild, but probably you should update your example with `write: false` so that other people coming here to solve the same problem don't get crazy trying to understand why the promise doesn't resolve with the correct value :D

```js
esbuild.build({
  write: false,
  stdin: {
    contents: 'console.log(true)',
  },
}).then(result => {
  console.log(result.outputFiles[0].text)
})
```

**Comment by donmccurdy** [comment]
Thanks again @evanw  and @cvlmtg! In case it helps someone else, I ended up with this code:

```typescript
import * as esbuild from 'esbuild-wasm';
import esbuildWASM from '../../node_modules/esbuild-wasm/esbuild.wasm';

esbuild.initialize({wasmURL: esbuildWASM});

export interface CompileResult {
	code: string,
	map: string,
	warnings: esbuild.Message[],
	errors: esbuild.Message[],
}

export const compileScript = async (contents: string): Promise<CompileResult> => {
	const buildResult = await esbuild.build({
		stdin: {contents, loader: 'ts'},
		format: 'esm',
		plugins: [localImports()],
		outfile: 'compiled.js',
		sourcemap: 'external',
		write: false,
		bundle: true,
	});

	const codeFile = buildResult.outputFiles.find((file) => file.path === '/compiled.js');
	const mapFile = buildResult.outputFiles.find((file) => file.path === '/compiled.js.map');

	return {
		code: codeFile.text,
		map: mapFile.text,
		warnings: buildResult.warnings,
		errors: buildResult.errors,
	};
};

// Replace ES Imports with in-memory implementations.
const localImports = (): esbuild.Plugin => ({
	name: 'local-imports',
	setup(build: esbuild.PluginBuild) {
		build.onResolve({filter: /.*/}, (args) => ({
			path: args.path,
			namespace: 'local-imports',
		}));
		build.onLoad({filter: /.*/, namespace: 'local-imports'}, (args) => ({
			contents: `module.exports = packages['${args.path}']`
		}));
	}
});
```
