### ISSUE TITLE
Importless Javascript

### ISSUE THREAD

**Issue by iamfrntdv** [evanw/esbuild#1378]
One the biggest advantages of programming languages like go, java, swift, etc. is that there are no imports for local code. One of the biggest disadvantages of modern javascript is that sometimes imports can be more than any developer can ever imagine for example 50+ 80+ lines which is absolutely useless from any point of view. There are a lot of things that can be automated and imports are one of them. 

Esbuild really great tool, and I'm really glad that there is tool that can build js not in js. And this can be one of the killer features of esbuild.

Of course there might be some developers who won't like this...

**Comment by evanw** [comment]
They aren’t useless. For example, one point of imports and exports is encapsulation (modules can have local state inaccessible to other modules). 

It sounds like you are talking about file concatenation, not bundling. File concatenation is just string concatenation which is trivial to implement yourself. It’s not something you need a complex tool like esbuild for.

**Comment by iamfrntdv** [comment]
Good point! 
But should imports determine encapsulation? Isn't it possible to make encapsulation without imports? Of course there may be some module's private parts of code and some that can be public and in this case exports can be used..

**Comment by evanw** [comment]
That's not how JavaScript works. The JavaScript specification does not have a mode with implicit `import` and explicit `export`.

The scope of this project is just to be bundler for standard JavaScript. It's not a playground to experiment with non-standard language ideas. The [Babel ecosystem](https://babeljs.io/) does more experimentation with potential directions to take the JavaScript language in. You'll probably have better luck doing something like this with Babel.

Closing this as "out of scope" for esbuild.
