### ISSUE TITLE
Fail to install last version on windows 64 behind proxy

### ISSUE THREAD

**Issue by botteroxom** [evanw/esbuild#1382]
last version
```
npm install esbuild
npm ERR! code 1
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node install.js
npm ERR! Trying to install "esbuild-windows-64" using npm
npm ERR! Failed to install "esbuild-windows-64" using npm: Command failed: npm install --loglevel=error --prefer-offline --no-audit --progress=false esbuild-windows-64@0.12.9
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for esbuild-windows-64@0.12.9.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR!
npm ERR!
npm ERR! Trying to download "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.12.9.tgz"
npm ERR! Failed to download "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.12.9.tgz": unable to get local issuer certificate
npm ERR! Install unsuccessful
```
previous one
```
npm install esbuild@0.12.8
4 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```

**Comment by evanw** [comment]
Successfully-downloaded versions are cached locally, so it's not surprising if a previously-installed version can be installed successfully even if the network isn't working. That just means it's already cached.

You can find the cached versions in `%LocalAppData%\Cache\esbuild\bin` and you can delete these cached versions if you want to test re-downloading those versions over the network.

I don't think I can help you debug your proxy setup, however.

**Comment by botteroxom** [comment]
Thanks for he tip.
I deleted the cached version, but the outcome didn't changed. 😅

**Comment by mc-petry** [comment]
Have the same problem with proxy when running postinstall script:

![image](https://user-images.githubusercontent.com/8122711/127834277-7453a514-1da8-4fb0-92b1-93a207cb5deb.png)

**Comment by mc-petry** [comment]
I've checked. Version 0.12.15 works well:
![image](https://user-images.githubusercontent.com/8122711/127847228-21ff31ed-773b-4160-a76a-26a17dba58dc.png)

**Comment by woppa684** [comment]
Probably related issue here:

```
> esbuild@0.12.17 postinstall C:\Repos\myrepo\node_modules\esbuild
> node install.js

Trying to install "esbuild-windows-64" using npm
Failed to install "esbuild-windows-64" using npm: Command failed: npm install --loglevel=error --prefer-offline --no-audit --progress=false esbuild-windows-64@0.12.17
npm ERR! code E401
npm ERR! Unable to authenticate, need: Basic realm="http://ourcorporateregistry", Negotiate, NTLM

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\myuser\AppData\Roaming\npm-cache\_logs\2021-08-09T05_52_58_429Z-debug.log

Trying to download "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.12.17.tgz"
Failed to download "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.12.17.tgz": connect ECONNREFUSED 104.16.22.35:443
```

Our company uses a private registry that acts as a proxy that uses the NPM registry as an upstream source. The postinstall script doesn't respect my local .npmrc file that configures this proxy and token.

**Comment by ChristophRSG** [comment]
@evanw We have the same problem as @woppa684 ; we have a private registry that uses the NPM registry as upstream source and the postinstall script doesn't respect the .npmrc file.

So the "unactionable" tag would not be correct IMHO.

**Comment by bodrick** [comment]
So I created a powershell script to download and save to cache.
Here is the [Gist](https://gist.github.com/bodrick/7d5b65fdc8e7ec1bc6ed9f4b93cd31df)

**Comment by evanw** [comment]
> So the "unactionable" tag would not be correct IMHO.

Unactionable doesn't mean it's not a bug. It just means it doesn't have a self-contained way for me to reproduce this (code to run and/or instructions to follow), so it's not currently possible to investigate and fix. Once we have that it's likely possible to fix the problem.

**Comment by nickmartin1ee7** [comment]
I am also having this issue. The install.js seems to have a hardcoded dependency on the npmjs repository, rather than using .npmrc's custom repository.

**Comment by ChristophRSG** [comment]
@evanw It should be possible to reproduce this by adding any address as the registry in the .npmrc file since the setting is not respected by `esbuild`.

e.g.:

```
registry=https://www.example.com
```

**Comment by mc-petry** [comment]
For me helped to set npm proxy in that way:

npm config set registry http://registry.npmjs.org/
**npm config set http-proxy http://address:port**
npm config set https-proxy http://address:port
npm config set proxy http://address:port
npm set strict-ssl false

Maybe some of this is unnecessary

**Comment by marcotaubmann** [comment]
Got the error when running `npm install` on a newly initialized SvelteKit app. `yarn install` worked.

Maybe this helps someone.
