### ISSUE TITLE
Standard node builtins in browser

### ISSUE THREAD

**Issue by dy** [evanw/esbuild#1383]
Trying to use with [yt-player](https://www.npmjs.com/package/yt-player):

```
esbuild assets/main.js --outfile=_site/assets/main.js --bundle --watch

 > node_modules/yt-player/index.js:2:29: error: Could not resolve "events" (use "--platform=node" when building for node)
    2 │ const EventEmitter = require('events').EventEmitter
```

I wonder if browserify packages better be supported out of box.
Sorry for lacking research, please close if duplicate.

**Comment by evanw** [comment]
Emulating node in the browser is out of scope for esbuild. But you can do this yourself if you'd like by substituting node's built-in packages for packages of your choosing. One way to do this is with a plugin: https://esbuild.github.io/plugins/#resolve-callbacks.
