### ISSUE TITLE
Option to ignore files/path

### ISSUE THREAD

**Issue by alvarlagerlof** [evanw/esbuild#1393]
I need to make esbuild skip over my storybook files in src/stories. Is there a way to do that?

**Comment by evanw** [comment]
I'm not sure what you mean. If skip over means "leave the import there but don't include it in the bundle" you can use the "external" feature: https://esbuild.github.io/api/#external. If skip over means "replace the imported file with something else" you can use a plugin: https://esbuild.github.io/plugins/#load-callbacks.

**Comment by alvarlagerlof** [comment]
> I'm not sure what you mean.

I am using `@vanilla-extract/esbuild-plugin` for my library, and it seems to go over `src/stories`, which I don't want, since I don't use it there. I want to stop going trough that folder.

**Comment by alvarlagerlof** [comment]
![image](https://user-images.githubusercontent.com/14835120/123160418-776c2800-d46e-11eb-9e60-a9a1c06dcfbb.png)

It touches parts of code that I don't want it to. I've tried adding "./src/stories/*" and various other similar ones like this, but it still seems to not be working.

![image](https://user-images.githubusercontent.com/14835120/123160562-a2567c00-d46e-11eb-901a-19c949cc3658.png)

**Comment by evanw** [comment]
It seems to work fine for me without the plugin:

```
$ cat entry.js 
import './src/stories/foo'

$ cat src/stories/foo.js 
console.log('foo.js')

$ cat build.js 
require('esbuild').build({
  entryPoints: ['entry.js'],
  bundle: true,
  format: 'esm',
  external: ['./src/stories/*'],
})

$ node build.js 
// entry.js
import "./src/stories/foo";
```

There might be something about the way the plugin works that prevents this from working. In that case you could try asking the plugin author. I'm sure they could add a way to include/exclude files to the plugin itself if there isn't one already. I believe the plugin repo is here: https://github.com/seek-oss/vanilla-extract/tree/master/packages/esbuild-plugin.

**Comment by evanw** [comment]
I'm closing this issue as this is a problem with a plugin, not a problem with esbuild itself.
