### ISSUE TITLE
Getting "Invalid loader: cjs" error

### ISSUE THREAD

**Issue by taschmidt** [evanw/esbuild#1396]
I'm getting a confusing error and I'm not sure how to get around it. I have a TypeScript project that pulls in the "nanoid" library and compiles just fine. I just pulled in another library and IT uses nanoid and now my build is broken with the following error:

```
 > node_modules/@dj/video-common/dist/lib/clients/video-playlist.js:9:25: error: [plugin: JavaScript plugins] Invalid loader: "cjs" (valid: js, jsx, ts, tsx, css, json, text, base64, dataurl, file, binary)
    9 │ const nanoid_1 = require("nanoid");
      ╵                          ~~~~~~~~
```

Looking at the package.json for nanoid:
```
  "exports": {
    ".": {
      "browser": {
        "development": "./index.dev.js",
        "production": "./index.prod.js",
        "default": "./index.prod.js"
      },
      "require": "./index.cjs",
      "import": "./index.js",
      "default": "./index.js",
      "types": "./index.d.ts"
    },
    ...
  }
```

I can see WHY this situation is a little different: from my TypeScript project, it uses nanoid with `import { nanoid } from 'nanoid';` so it uses `index.js` but the dependent library is compiled down to JS where it becomes a require and uses `index.cjs`. But it looks like esbuild should support cjs so why is this a problem? And how can I fix it?

**Comment by taschmidt** [comment]
I did confirm that if I manually modify the require line in the nanoid package.json from "./index.cjs" to "./index.js" it does indeed work. But obviously this isn't really an option. So how can I fix this? I tried adding `{loader: {'.cjs': 'js'}}` but that didn't appear to make a difference.

**Comment by taschmidt** [comment]
Ok, I don't quite understand why, but this fixed it. The library I was pulling in that used nanoid had `"module": "commonjs"` in its tsconfig.json. I removed that and it now works. although I'm not entirely sure what other implications that would have.

**Comment by evanw** [comment]
It looks to me like you are using esbuild with plugins and one of those plugins is returning nonsense. Ideally the name of the plugin would show up here instead of `JavaScript plugins` so you'd know which plugin was at fault. That's a bug in esbuild that I can fix. But the underlying problem is with the plugin, not with esbuild.

> ```
> Invalid loader: "cjs" (valid: js, jsx, ts, tsx, css, json, text, base64, dataurl, file, binary)
> ```

Your problem is described in the error message you posted. The string `cjs` is not a valid esbuild loader. A valid esbuild loader is one of `js, jsx, ts, tsx, css, json, text, base64, dataurl, file, binary`. See https://esbuild.github.io/content-types/ for more information.

**Comment by taschmidt** [comment]
Ah, thank you! That was indeed the problem! Yeah, adding the name of the plugin to the error message would've saved me some time. I wasn't even thinking about the plugin (although in hindsight that's probably something I should've looked at).

If anyone else is wondering, my problem was the esbuild lodash plugin. Simply commenting it out fixed the problem. But for a more permanent fix, I added a filter like this:

```
module.exports = [
    new lodashPlugin({ filter: /\.(t|j)s$/ })
];
```
