### ISSUE TITLE
Warns incorrectly on CSS attribute selector case sensitivity flag

### ISSUE THREAD

**Issue by adamwathan** [evanw/esbuild#1397]
Given this CSS:

```css
[type="A" s] {
  color:  black;
}
```

esbuild warns with:

```
 > in.css:1:10: warning: Expected "]" but found "s"
    1 │ [type="A" s] {
      ╵           ^

 > in.css:1:11: warning: Unexpected "]"
    1 │ [type="A" s] {
```

This is actually valid, and is a newer flag similar to the existing `i` flag which esbuild seems to handle and does not warn about:

https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors#html_ordered_lists

Thanks so much for your work on this amazing tool, and for Figma! 😍

**Comment by evanw** [comment]
Huh. It looks like this is some weird Firefox-only syntax. I can add support for this.

**Comment by neupauer** [comment]
> Huh. It looks like this is some weird Firefox-only syntax. I can add support for this.

@evanw Hi, I'm not sure, but this is not a Firefox-only syntax (all browsers except Safari and IE :) support it).

There was a bug in Chrome (Edge, Opera), but it's already resolved see https://bugs.chromium.org/p/chromium/issues/detail?id=1041095

<img width="1002" alt="Screen Shot 2021-06-27 at 17 53 40" src="https://user-images.githubusercontent.com/6411116/123551108-acc78d00-d770-11eb-9c1d-7ac1446133f1.png">
