### ISSUE TITLE
[css] `shortColorName` can include 4 or 7 length names

### ISSUE THREAD

**Issue by hyrious** [evanw/esbuild#1400]
I found that `--minify` converts `color: blue` to `color: #00f`, even though `#00f` is not shorter than `blue`.

```bash
echo 'body{color:blue}' | esbuild --loader=css --minify
body{color:#00f}
```

This is because [shortColorName](https://github.com/evanw/esbuild/blob/97416e7cc7b27529d508e3807830b8969de5ef39/internal/css_parser/css_decls_color.go#L15) does not include these color names which have equal length to thier hex code.

FYI, I've found them for you:

```go
0x0000ffff: "blue",
0x00ff00ff: "lime",
0x00ffffff: "cyan",
0x00ffffff: "aqua",
0x696969ff: "dimgrey",
0x696969ff: "dimgray",
0x808080ff: "grey",
0x87ceebff: "skyblue",
0x8b0000ff: "darkred",
0xd8bfd8ff: "thistle",
0xdc143cff: "crimson",
0xfdf5e6ff: "oldlace",
0xff69b4ff: "hotpink",
```

**Comment by evanw** [comment]
But this doesn’t matter because the size isn’t different. Minified code is for computers to consume, not for humans. So this is working as intended.
