### ISSUE TITLE
Not Handle absolute imports when not bundling

### ISSUE THREAD

**Issue by fschwalm** [evanw/esbuild#1403]
Hello.

I'm using multiple entryPoints and using bundle: false.
The baseUrl is defined on tsconfig.json and when i use bundle:true it works.

This is a expected behavior or a bug?

Thx

**Comment by evanw** [comment]
This is expected. Import paths are only transformed when bundling. This is documented here: https://esbuild.github.io/content-types/#tsconfig-json.

**Comment by fschwalm** [comment]
ok!
Do you have some suggestions that i could deal with it?

Thank you so much!

**Comment by Naoto-Ida** [comment]
I know this is an older issue, but thought I'd share some tips.

We've recently encountered this as well. Our lib in question is not meant to be directly consumed, so we don't bundle.

What we do now is run `tsc-alias` AFTER running ESBuild. I haven't had issues so far with this setup. We don't have anything complex though; each alias points to the `src` directory of the packages under a monorepo.

I'm not super knowledgeable in the art of bundling, but @evanw, could you help us understand why this is a feature limited to when bundling is enabled?

**Comment by fschwalm** [comment]
Nice! Thanks for sharing!
I will try it.

**Comment by evanw** [comment]
> could you help us understand why this is a feature limited to when bundling is enabled?

This is because esbuild is a bundler, and has been primarily designed for bundling.

**Comment by evanw** [comment]
Closing this issue due to age.
