### ISSUE TITLE
My entry `index.html` is modified after upgrading to `v0.12.12`

### ISSUE THREAD

**Issue by JounQin** [evanw/esbuild#1404]
I'm just starting to write a html entry plugin for esbuild at https://github.com/rx-ts/esbuilder/tree/main/packages/html

It was working just fine before `v0.12.12` yesterday.

However, after upgrading to `v0.12.12` today and run build step, my source `src/index.html` is modified, and no `dist/index.html` generated anymore.

```diff
diff --git a/src/index.html b/src/index.html
index 738fe6d..a54052d 100644
--- a/src/index.html
+++ b/src/index.html
@@ -1,12 +1,11 @@
-<!DOCTYPE html>
-<html>
-  <head>
-    <meta charset="UTF-8" />
-    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
-    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
+<!DOCTYPE html><html><head>
+    <meta charset="UTF-8">
+    <meta http-equiv="X-UA-Compatible" content="IE=edge">
+    <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <title>esbuilder</title>
   </head>
-  <div id="app"></div>
-  <script src="index.ts"></script>
-  <body></body>
-</html>
+  <body><div id="app"></div>
+  <script src="index.HVGXJNEZ.js"></script>
+  
+
+</body></html>
\ No newline at end of file
```

Reproduce: simply run `yarn upgrade esbuild && yarn build:app`

**Comment by evanw** [comment]
Thanks for the report. I can reproduce the issue. It looks like code changes in 0.12.12 are incorrectly handling the case of paths loaded with the `file` loader that are in a custom namespace.
