### ISSUE TITLE
Does esbuild plan to support the Compression such as gzip and brotli?

### ISSUE THREAD

**Issue by Awen-hub** [evanw/esbuild#1408]
The Compression module zlib in nodejs in written by js. I think it may not as fast as written by go.

**Comment by evanw** [comment]
No. Compression is out of scope and there are no plans to add support for it to esbuild. Compression tools already exist and you can just run those tools separately after doing a build. Compression happens at the end of the build pipeline and doesn't need any special integration with esbuild for performance, so it doesn't make sense for it to be a part of esbuild itself.

Also I believe the performance-sensitive parts of the compression module zlib in nodejs is mainly [written in C++](https://github.com/nodejs/node/blob/f179eb01afc9d2ca136a80bcf5d5533c9115107b/src/node_zlib.cc#L1271-L1284), not in JS.

**Comment by evanw** [comment]
I'm closing this issue since the question has been answered.

**Comment by StokeMasterJack** [comment]
It would be nice to have an example in the docs of how one might integrate compression into an ESBuild pipeline.

**Comment by clshortfuse** [comment]
@StokeMasterJack 

````js

import { brotliCompressSync, gzipSync } from 'node:zlib';

/** snip **/

    build.onEnd(({ metafile, outputFiles }) => {
        const info = {
          timestamp: new Date().toLocaleString(),
        };
        for (const file of outputFiles) {
          writeFileSync(file.path, file.contents);
          info[relative('', file.path)] = {
            raw: file.contents.length,
            brotli: brotliCompressSync(file.contents).length,
            gzip: gzipSync(file.contents).length,
          };
        }
        if (metafile) {
          writeFileSync('meta.json', JSON.stringify(metafile));
        }
        console.log(info);
      });
````

I only use it for analysis right now, but just tap into [build.onEnd](https://esbuild.github.io/plugins/#on-end) with `write:false` in config.
