### ISSUE TITLE
Array.prototype.at()

### ISSUE THREAD

**Issue by lgarron** [evanw/esbuild#1415]
Firefox and Chrome are shipping `Array.prototype.at()`
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

I would love to be able to start using this in my code. For polyfilling, it's possible to use do the following with moderate efficieny:

```
// Index -1
arr.at(-1) → arr.slice(-1)[0]
// Any other index:
arr.at(-2) → arr.slice(-2, -1)[0]
arr.at(3) → arr.slice(3, 4)[0]
// etc.
```

**Comment by evanw** [comment]
You will have to polyfill this yourself. The transformations that esbuild does are purely syntactical and this is not a syntax feature, so supporting this is outside of esbuild’s scope. Trying to implement this feature as a syntax transform the way you suggested would break legitimate code since it’s impossible to always know if a variable is an array or not. You instead need to mutate the array prototype. A polyfill is already linked from the documentation page you referenced: https://github.com/tc39/proposal-relative-indexing-method#polyfill. Just paste it into your code. 

Closing this issue as “out of scope.”

**Comment by lgarron** [comment]
> You will have to polyfill this yourself. The transformations that esbuild does are purely syntactical and this is not a syntax feature, so supporting this is outside of esbuild’s scope. Trying to implement this feature as a syntax transform the way you suggested would break legitimate code since it’s impossible to always know if a variable is an array or not. You instead need to mutate the array prototype. A polyfill is already linked from the documentation page you referenced: https://github.com/tc39/proposal-relative-indexing-method#polyfill. Just paste it into your code.
> 
> Closing this issue as “out of scope.”

Alright, that makes sense, thanks!

Just need to wait for other tooling to catch up now. ⏳😓

**Comment by yulodl** [comment]
> You will have to polyfill this yourself. The transformations that esbuild does are purely syntactical and this is not a syntax feature, so supporting this is outside of esbuild’s scope. Trying to implement this feature as a syntax transform the way you suggested would break legitimate code since it’s impossible to always know if a variable is an array or not. You instead need to mutate the array prototype. A polyfill is already linked from the documentation page you referenced: https://github.com/tc39/proposal-relative-indexing-method#polyfill. Just paste it into your code.
> 
> Closing this issue as “out of scope.”

It's a syntax feature now. https://tc39.es/ecma262/#sec-array.prototype.at

**Comment by evanw** [comment]
> It's a syntax feature now.

That's not a syntax feature. This is just an addition to JavaScript's standard library. There are no new grammar rules that were added to JavaScript's syntax grammar that are necessary to be able to call `.at()` on something, so there are no changes needed to any JavaScript syntax parser to be able to parse `.at()`.

**Comment by yulodl** [comment]
> > It's a syntax feature now.
> 
> That's not a syntax feature. This is just an addition to JavaScript's standard library. There are no new grammar rules that were added to JavaScript's syntax grammar that are necessary to be able to call `.at()` on something, so there are no changes needed to any JavaScript syntax parser to be able to parse `.at()`.

Ok，got it. Thanks for answering.
