### ISSUE TITLE
"no emit" option for validating bundle without generating files

### ISSUE THREAD

**Issue by mitranim** [evanw/esbuild#1416]
First off, thanks for `esbuild`. It's an incredible upgrade from `webpack`. As for the issue itself...

Example scenario for no-emit:

* For staging or production, bundle using `esbuild`.
* In development, run the application 100% from source, using native JS modules.
* In development, run `esbuild` in watch mode, continuously validating the codebase, without writing files. Because the app runs from source, generated files would be unused, and could interfere with the development environment, for example by triggering unnecessary FS events.

Why: `esbuild` validates the existence of dependencies and all exports/imports between modules. This is extremely useful to have on a glance, _especially_ for apps that heavily use on-demand async imports. This is not redundant with linters; for example, `eslint` doesn't support this out of the box.

**Comment by dalcib** [comment]
Is the [write](https://esbuild.github.io/api/#write) option what are you looking for?

**Comment by mitranim** [comment]
Yes, exactly! Just failed to find it. Thanks! 👍
