### ISSUE TITLE
How to build minified and uncompressed bundles on a single compile run

### ISSUE THREAD

**Issue by tyroneneill** [evanw/esbuild#1428]
At present in order to bundle our final package with both an uncompressed and minified distribution we are calling build twice, I suspect some performance gains could be had if this could be done in the same pass?

**Comment by evanw** [comment]
This isn’t supported. Due to how esbuild works, the AST is actually minified during parsing for maximum speed so the AST would have to be re-parsed anyway to do this. You might as well just call esbuild twice.

**Comment by tyroneneill** [comment]
@evanw thanks for the explanation.
