### ISSUE TITLE
Install script failing with yarn workspaces

### ISSUE THREAD

**Issue by MixMasterMitch** [evanw/esbuild#1434]
I am getting the following error in my yarn workspace when I disable all [hoisting](https://classic.yarnpkg.com/blog/2018/02/15/nohoist/) (e.g. `nohoist: ['**/**']`)

```
error /Users/username/Github/repo/packages/A/node_modules/esbuild, /Users/username/Github/repo/packages/B/node_modules/esbuild, /Users/username/Github/repo/packages/C/node_modules/A/node_modules/esbuild: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /Users/username/Github/repo/packages/A/node_modules/esbuild
Output:
/Users/username/Github/repo/packages/A/node_modules/esbuild/install.js:198
      throw e;
      ^

Error: ENOENT: no such file or directory, rename '/Users/username/Github/repo/packages/A/node_modules/esbuild/bin/esbuild__' -> '/Users/username/Github/repo/packages/A/node_modules/esbuild/bin/esbuild'
    at Object.renameSync (fs.js:772:3)
    at /Users/username/Github/repo/packages/A/node_modules/esbuild/install.js:197:78
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  errno: -2,
  syscall: 'rename',
  code: 'ENOENT',
```

As a workaround, I have refined my hoisting so that esbuild is hoisted, but it still seems like esbuild install script should function in either case.

**Comment by evanw** [comment]
Could you provide a simple self-contained code sample that demonstrates the problem? I don't use Yarn and don't know what hoisting is or how to set it up myself.

It also seems strange that hoisting would break esbuild's install script since esbuild doesn't have any dependencies and hoisting seems to be about dependencies. The call to `renameSync(A, ...)` should follow a call to either `copyFileSync(..., A)` or `writeFileSync(A, ...)` so it's not clear to me why that file doesn't exist.

**Comment by MixMasterMitch** [comment]
I attempted to replicate the issue with a minimal repo example and ... there was no issue. 

Back in the repo exhibiting the issue, I realized that I hadn't tried deleting the `yarn.lock` file. Deleting it resolved the issue for me. So for any future person stumbling across this issue: 

```
Delete the yarn.lock file
```

**Comment by MixMasterMitch** [comment]
I ran into the same issue again and this time deleting the yarn.lock file didn't work. When the failure happens it looks like yarn is installing esbuild multiple times in parallel right before failing. There is a similar issue with node-gyp here: https://github.com/yarnpkg/yarn/issues/1874

I ran `yarn global add esbuild` and then my subsequent `yarn install` in my repo was successful (but maybe I just got lucky).

Could the esbuild install script be made more idempotent / thread safe?

**Comment by MixMasterMitch** [comment]
Ah I also just discovered that I was using different versions of esbuild across packages. I just upgraded them all to the latest version. I suspect that was a major contributor to the problem. Feel free to close unless you want to try to take further action.

**Comment by evanw** [comment]
I'm going to close this since this is no longer a problem for you and since the installation strategy is about to change: #1621.
