### ISSUE TITLE
How to keep all my comments code?

### ISSUE THREAD

**Issue by anchengjian** [evanw/esbuild#1439]
How to keep all my comments code, not just the LegalComments ???

**Comment by evanw** [comment]
This is not supported. You should use another tool instead.

**Comment by anchengjian** [comment]
why ?

**Comment by heyheyhello** [comment]
@anchengjian It's not part of the AST (kinda; I mean legal comments and `__PURE__` comments are...). Evan explains why here https://github.com/evanw/esbuild/issues/221#issuecomment-653804184 

It's a bummer I know, but handling comments is hard logic to code correctly.

I'd like them to stay too. Not sure if this is your use case at all but: my team publishes npm packages that other internal teams use. It's common for people to ctrl+click an import to want to see the node_modules code. With webpack, we'd see close-to-sourcecode code that had comments. After moving to esbuild we lost that. Our workaround was to use `--banner` to put a comment linking to the GitLab source code so people can read the comments in their browser. It's not ideal but might work if you want to at least redirect people to commented code...
