### ISSUE TITLE
Identifier "Link " has already been declared

### ISSUE THREAD

**Issue by sumitmukharjeeeeee** [evanw/esbuild#1452]
//import pages in app.js
//all the requred paths and components of react
import { BrowserRouter, Route, Link, Switch } from "react-router-dom";
import Home from "./booking/Home";
import Login from "./auth/Login";
import Register from "./auth/Register";
import Link from "react-router-dom";

//Creating Navigation bar
const TopNav = () => (
  <div className="nav bg-light d-flex justify-content-between">
    <Link className="nav-link" to="/">
      Home
    </Link>
    <Link className="nav-link" to="/login">
      Login
    </Link>
    <Link className="nav-link" to="/register">
      Register
    </Link>
  </div>
);

function App() {
  return (
    <BrowserRouter>
      <Switch>
        <Route exact path="/" component={Home} />
        <Route exact path="/login" component={Login} />
        <Route exact path="/register" component={Register} />
      </Switch>
    </BrowserRouter>
  );
}

export default App;

I am trying to import Link for my code but it throws error showing Identifier 'Link' has already been declared. (7:7)
![Screenshot (81)](https://user-images.githubusercontent.com/59107641/126041357-bdf632f6-a3c9-426a-a2da-ce1f4f46e4ec.png)

**Comment by heyheyhello** [comment]
This is not an issue with esbuild

```
import { BrowserRouter, Route, Link, Switch } from "react-router-dom";
//                             ^^^^ First
...
import Link from "react-router-dom";
//     ^^^^ Second

The error makes sense.
```
