### ISSUE TITLE
Keep \n in template strings

### ISSUE THREAD

**Issue by retorquere** [evanw/esbuild#1461]
I know it's semantically the same, but is it possible/easy to have 

```
`\nx`
```

stay that way rather than it being expanded to

```
`
x`
```

I have [a post-processing codemod](https://github.com/coderaiser/estrace/issues/3) that breaks on this.

**Comment by evanw** [comment]
This syntax is equivalent so it's valid to substitute one for the other, and I don't think this needs a configuration option. I don't plan to build workarounds for buggy JavaScript code transformation tools into esbuild itself. Also it looks like the linked issue was closed as fixed. Closing this issue as nothing will be done about it.
