### ISSUE TITLE
Using the WASM module's API from other languages

### ISSUE THREAD

**Issue by GavinRay97** [evanw/esbuild#1465]
Heya, I was curious if there is any reference or tips on using the WASM module's API outside of a browser context?

I am interested in getting the WASM module running on GraalVM, so that in-process transpilation + bundling of JS/TS is possible for Graal to then evaluate as JS scripts.

For C, the process is something generally like:
```c
// Compile with: $ emcc -o example.wasm example.c
// Test with : $ wasm --Builtins=wasi_snapshot_preview1 example.wasm
#include <stdio.h>

int main() {
  print("hello");
  return 0;
}
```
```java
import org.graalvm.polyglot.*;
import org.graalvm.polyglot.io.ByteSequence;

//Load the WASM contents into a byte array
byte[] binary = readBytes("example.wasm");

Context.Builder contextBuilder = Context.newBuilder("wasm");
Source.Builder sourceBuilder = Source.newBuilder("wasm", ByteSequence.create(binary), "example");

Source source = sourceBuilder.build();
Context context = contextBuilder.build();

context.eval(source);

Value mainFunction = context.getBindings("wasm").getMember("main").getMember("_start");
mainFunction.execute();
```

Is the API identical for using the WASM module?
I tried using `wasm-objdump` to look at the exports:
```
$ ./wasm-objdump.exe -s --section=Export ./node_modules/esbuild-wasm/esbuild.wasm
esbuild.wasm:	file format wasm 0x1

Contents of section Export:
00011e4: 0403 7275 6e00 dc07 0672 6573 756d 6500  ..run....resume.
00011f4: dd07 0567 6574 7370 00df 0703 6d65 6d02  ...getsp....mem.
0001204: 00                                       .
```

These exports don't look like the JS API so I'm not sure exactly what they are/what the arg object is meant to look like if that is the right exports.

Is this `run` export maybe this method?
https://github.com/evanw/esbuild/blob/a3d25dd6c2c7c75388c0e4d35dfb487d27c905b4/pkg/cli/cli.go#L24-L31

Any advice would be super appreciated. Thank you!

**Comment by evanw** [comment]
Short answer: No, this is not possible. The WebAssembly module is an implementation detail and is only designed to be used from the published JS API. Running esbuild using Java is not supported.

Long answer: It is technically possible to do this (everything is possible) but doing so would be extremely complicated and brittle, and is very unsupported and could break at any time. The interface between JavaScript and WebAssembly is not part of esbuild. It's instead an internal implementation detail of the Go WebAssembly compiler that esbuild takes verbatim. All esbuild does is run Go's [JavaScript stub for WebAssembly](https://github.com/golang/go/blob/0914646ab91a3157666d845d74d8d9a4a2831e1e/misc/wasm/wasm_exec.js) in a child process and talk to it over stdin/stdout, so you'd have to replicate the functionality of Go's JS stub including JS reflection and file system emulation. Then once you have that working, you'd also have to replicate esbuild's internal-only custom binary IPC protocol and likely also replicate a lot of the internals of esbuild's JS API. Both esbuild's internal binary stdin/stdout protocol and the Go compiler's internal WebAssembly JS<=>Go messages could change in a breaking fashion at any time in which case your custom reimplementation would break. I do not recommend doing this at all.

**Comment by GavinRay97** [comment]
Ouch, I'd be inclined to agree that every bit of that sounds absurdly difficult to implement.
Oh well, appreciate you taking time out of your day to answer regardless. Thank you!
