### ISSUE TITLE
Failed to build core modules with 'node:' prefix

### ISSUE THREAD

**Issue by dolfbarr** [evanw/esbuild#1466]
# Esbuild fails to build core modules with `node:` prefix.
Core modules can be required with `node:` prefix according to [docs](https://nodejs.org/api/modules.html):

> Core modules can also be identified using the node: prefix, in which case it bypasses the require cache. For instance, require('node:http') will always return the built in HTTP module, even if there is require.cache entry by that name.

Possible behavior: instead trying to require a core module, esbuild tries to find an external lib.

## Details 
index.js:
```
const path = require('path')
const pathNode = require('node:path')

console.log('success!')
```

Error:
```
> esbuild ./index.js --bundle --outfile=out/index.js --platform=node --external:node:path && node out/index.js


  out/index.js  102b

⚡ Done in 8ms
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'node:path'
```

## Expected Behavior

Esbuild correctly builds core modules with `node:` prefix and `--platform=node` flag.

## Actual Behavior

Esbuild fails to build core modules with `node:` prefix and `--platform=node` flag.

## Steps to Reproduce the Problem
I've prepared a repo to reproduce the problem: https://github.com/dolfbarr/esbuild-require-issue

`npm start` will build `index.js` file and run the output file via node to raise the error.

## Specifications
  - Version: 0.12.15
  - Node: v14.17.3

**Comment by hyrious** [comment]
`node:*` is not available in `require()`. [SPEC](https://nodejs.org/api/esm.html#esm_node_imports).
You can test it in your node repl:
```js
import("node:fs").then(console.log) // ok
require("node:fs") // fail
```

**Comment by hyrious** [comment]
However, it should work if we bundle it to ESM format.
```bash
echo 'import fs from "node:fs"' | esbuild --bundle --platform=node --format=esm
```
<samp>error: Could not resolve "node:fs"</samp>

A workaround is adding `--external:node:fs`.

**Comment by evanw** [comment]
> A workaround is adding `--external:node:fs`.

A better workaround is just adding `--external:node:*` which will handle all paths with a `node:` prefix. I can make that behavior happen by default (all `node:` paths will be considered external).

I don't think it's a good idea to try to translate `node:fs` to `fs` for old node versions since they aren't semantically equivalent, so I won't build that behavior in by default. If you need to work with old node versions that don't support `node:`, then you can just write `fs` instead or write a custom plugin that changes `node:` paths into whatever you need them to be.

**Comment by jimmywarting** [comment]
> `node:*` is not available in `require()` until node16. [SPEC](https://nodejs.org/api/esm.html#esm_node_imports).
> 
> You can test it in your node repl:
> 
> ```js
> import("node:fs").then(console.log) // ok
> require("node:fs") // fail in node14, ok in node16
> ```

i read the docs and it says it's supported in v14.18.0
