### ISSUE TITLE
v0.12.15 Atomics.wait fn freeezes the transformSync operation

### ISSUE THREAD

**Issue by kolodziejczak-sz** [evanw/esbuild#1471]
Hello,
I faced this exact issue on v0.12.15 https://github.com/evanw/esbuild/issues/595#issuecomment-744735746, had to install 0.12.14

simple file
```typescript
// index.ts
console.log('hello world');
```

then 

`node -r esbuild-register index.ts`

I found out that it freezes on that code of line `let status = Atomics.wait(sharedBufferView, 0, 0);`

tried on windows & (node 16.4.1 & 14.17.3)

**Comment by evanw** [comment]
I'm going to disable this on all node versions <v0.12.17 in the next release of esbuild anyway to fix another bug: #1462. So it's possible this will fix your bug as well. However, I don't currently have access to a Windows machine for testing so I'll be unable to verify the fix at the moment. I'll have to test this later instead when I get access to a Windows machine again.

**Comment by evanw** [comment]
This has now been disabled on node v0.12.15 so I assume it has been fixed. Can you confirm?

**Comment by kolodziejczak-sz** [comment]
It works now. Great job 👍
