### ISSUE TITLE
Is there a way to determine the dependencies between modules in the resulting bundle?

### ISSUE THREAD

**Issue by photonstorm** [evanw/esbuild#1473]
I'm trying to debug an issue I have where various modules are not being tree-shaken from my bundle, even though they are never (seemingly) used by my app.

I'd love to know if there is a way / API feature that will allow me to determine _what_ has requested the inclusion of a module in the bundle?

**Comment by hyrious** [comment]
You can turn on [metafile](https://esbuild.github.io/api/#metafile) to see which file imports them.

**Comment by photonstorm** [comment]
Ah! That's perfect, thank you.
