### ISSUE TITLE
internal/modules/cjs/loader.js throws out error

### ISSUE THREAD

**Issue by GopherJ** [evanw/esbuild#1476]
<img width="501" alt="image" src="https://user-images.githubusercontent.com/33961674/127257632-5663f92d-4967-4940-a061-f1817cd96b18.png">

**Comment by GopherJ** [comment]
any idea on this? I'm trying to bundle a polkadotjs typescript project

**Comment by evanw** [comment]
There isn't enough information here to be able to understand what's happening. The error message says the module `./combine.js` doesn't exist. You'll need to figure out how to provide enough information.

**Comment by evanw** [comment]
Closing due to lack of a response.
