### ISSUE TITLE
esbuild cant bundle correctly

### ISSUE THREAD

**Issue by sqlProvider** [evanw/esbuild#1479]
i have one app and one lib.

**Folder Structure**
```
apps
    mobile
        src
            index.tsx
            asd.ts

packages
    core
        index.ts
        src
            index.ts
        ...
```

**BUILD file in core**
```
ts_library(
    name = "core",
    module_name = '@app/core',
    srcs = glob(["**/*.ts"]),
    deps = [
        "@npm//reflect-metadata",
        "@npm//rxjs",
        "@npm//axios",
    ]
)
```

**BUILD file in mobile app**
```
ts_library(
    name = "mobile",
    module_name = '@app/mobile',
    srcs = glob(["**/*.ts", "**/*.tsx"]),
    deps = [
        "@npm//react",
        "@npm//@types/react",
        "@npm//react-router-dom",
        "@npm//@types/react-router-dom",
        "@npm//rxjs",
        "@npm//moment",

        "//packages/core:core",
    ]
)

esbuild(
    name = "bundler",
    entry_point = "src/index.tsx",
    minify = False,
    link_workspace_root = True,
    # setting node as the platform will default us to CJS
    platform = "browser",
    format = "esm",
    tool = select({
        "@bazel_tools//src/conditions:darwin": "@esbuild_darwin//:bin/esbuild",
        "@bazel_tools//src/conditions:linux_x86_64": "@esbuild_linux//:bin/esbuild",
        "@bazel_tools//src/conditions:windows": "@esbuild_windows//:esbuild.exe",
    }),
    deps = [
        ":mobile",
    ],
    external = [],
    args = [
        "--bundle"
    ]
)
```

I importing package like this. `import { UseInjectionService } from '@core';` 
Bundle including definations but not real code.

```
var require_core = __commonJS({
  "bazel-out/k8-fastbuild/bin/packages/core/src/core.js"(exports, module) {
    (function(factory) {
      if (typeof module === "object" && typeof module.exports === "object") {
        var v = factory(__require, exports);
        if (v !== void 0)
          module.exports = v;
      } else if (typeof define === "function" && define.amd) {
        define("@core/src/core", ["require", "exports", "@core/src/decorator", "@core/src/di", "@core/src/error", "@core/src/util", "@core/src/storage", "@core/src/validation", "@core/src/referance"], factory);
      }
    })(function(require2, exports2) {
      "use strict";
      Object.defineProperty(exports2, "__esModule", { value: true });
      var decorator_1 = require2("@tuttur/core/src/decorator");
      Object.defineProperty(exports2, "ClassDecorator", { enumerable: true, get: function() {
        return decorator_1.ClassDecorator;
      } });
      Object.defineProperty(exports2, "DecoratorProcessor", { enumerable: true, get: function() {
        return decorator_1.DecoratorProcessor;
      } });
    });
  }
});
```

but when I import like this `import { SmartBanner } from '@mobile/src/components/smartBanner';`. esbuild puting all code in bundle.

Can anyone explain this?

**Comment by evanw** [comment]
It looks like the file `bazel-out/k8-fastbuild/bin/packages/core/src/core.js` uses dynamic `require` (saving the value of `require` to a variable and calling it later instead of calling `require(…)` directly). Bundling with dynamic require is not supported by esbuild. You will have to either rewrite your code to not use dynamic require or use another bundler instead.

**Comment by sqlProvider** [comment]
@evanw i am just exporting public_api of core in core.ts. esbuild cannot bundle internals.

```
/**
 * @publicAPI packages/core/src decorator
 */
export {
	ClassDecorator,
	DecoratorProcessor
} from 'packages/core/src/decorator';
.
.
.

```

**Comment by hyrious** [comment]
Esbuild don't actually read your sources code in `packages/core/src`, instead, it read `bazel-out/k8-fastbuild/bin/packages/core/src/core.js`. I think this path-resolution (resolve `@core` to `bazel-out/k8-fastbuild/bin/packages/core`) is defined by your build tool. There're 2 problems here:

1. The `ts_library( name = "core",` converts all files in `packages/core` to umd format and uses dynamic require (as evan said), which prevents esbuild to correctly analyse your code's dependencies.

   ```js
   // correct code:
   // use CJS, directly use `require`
   exports.xxx = require("dep") // <- "dep" will be treated as dependency and be bundled
   // use ESM
   import { xxx } from "dep"

   // wrong code:
   // indirectly use `require`
   var r = require; r("dep") // <- esbuild: i don't think "dep" is a dependency
   ```

2. > esbuild puting all code in bundle.

   Even though you are correctly using the CJS format, esbuild's [tree-shaking](https://esbuild.github.io/api/#tree-shaking) only works for ESM.

**Comment by sqlProvider** [comment]
@hyrious what is the correct way to bundle code like that?

**Comment by sqlProvider** [comment]
after tons of hours i find the solution. ts_library rule have `devmode_target` and `devmode_module`. if you building under devmode, tslibrary doesn't read confs in tsconfig. it looks to `devmode_target` and `devmode_module`. when i setted correctly(`es2015`) those params, i got build.
