### ISSUE TITLE
Lowercase @charset "utf-8" is warned as unsupported

### ISSUE THREAD

**Issue by jeffpeterson** [evanw/esbuild#1483]
Specifying `@charset "utf-8";` in a CSS file causes a warning.
Uppercase `"UTF-8"` works fine, but it's imported from another package:

```
node_modules/mocha/mocha.css:1:9: warning: "UTF-8" will be used instead of unsupported charset "utf-8"
    1 │ @charset "utf-8";
      ╵          ~~~~~~~
```

**Comment by evanw** [comment]
There's nothing that says that `utf-8` is valid in [the CSS specification for `@charset`](https://drafts.csswg.org/css2/#charset). It only says `UTF-8` is valid.

However, I did find a reference that says the `Charset` HTTP header is case-insensitive: https://datatracker.ietf.org/doc/html/rfc7231#section-3.1.1.2. So perhaps that's the reason why this is ok?

I will change this to a case-insensitive check.
