### ISSUE TITLE
esbuild bundle incorrectly

### ISSUE THREAD

**Issue by Ronbb** [evanw/esbuild#1488]
repo: 
[output.zip](https://github.com/evanw/esbuild/files/6914664/output.zip)

When I used [@antv/x6 ](https://github.com/antvis/x6) with vite, I met the problem https://github.com/vitejs/vite/issues/3413. And I reproduce the bug by using esbuild directly.

It seems that `class ToolsView` is used before definition:

```javascript
/* ... */
var Button = class extends ToolsView.ToolItem // ...

/* ... */

var ToolsView = class extends View // ...

/* ... */
```

**Comment by hyrious** [comment]
I didn't reproduce your problem using your output.zip. Everything works fine.

**Comment by hyrious** [comment]
@Ronbb Reproduced. It also seems to be an issue with **yarn2**. After removing .yarn and .yarnrc.yml (so that we are using yarn1 or npm), it works fine.

**Comment by Ronbb** [comment]
@hyrious I try yarn2 with `yarn config set nodeLinker node-modules` and it works. Maybe this is a  ***pnp*** bug.

**Comment by hyrious** [comment]
@Ronbb I checked the out/x6.js produced by the broken example, looks like through the `@yarnpkg/esbuild-plugin-pnp` plugin esbuild can only load commonjs files instead of esm ones. Maybe **missing package.json's `module` info** leads to esbuild can not load the esm files.

If you can bundle once instead of two steps, the it will also be fine:

1. change your first line of app.js to
   ```js
   import { Graph, Node, Edge, Shape, ToolsView, NodeView, EdgeView } from '@antv/x6';
   ```
2. bundle.js:
   ```js
   require('esbuild').build({
     entryPoints: ['app.js'],
     plugins: [require('@yarnpkg/esbuild-plugin-pnp').pnpPlugin()],
     bundle: true,
     outfile: 'out/out.js',
     sourcemap: true
   }).catch(() => process.exit(1))
   ```

**Comment by Ronbb** [comment]
@hyrious Thanks for your advice. However I'm using `vite` in my project. `vite` bundles deps firstly for optimization in dev mode, which causes this problem. 

QAQ

**Comment by hyrious** [comment]
You can track the esm support in yarnpkg/berry#3185.

However I doubt it requires some virtual file system api in esbuild itself.

We can wait for evan's reply to see if it makes sense to support that.
