### ISSUE TITLE
Multiple imports from different files from one file are imported wrong with esm module

### ISSUE THREAD

**Issue by a-gerescher** [evanw/esbuild#149]
At first, let me sincerely thank for your efforts. What an extraordinary speed in a bundler, and i have tried all of them.

Unfortunately i have found a bug. 

If you define esm as output format, and are importing from different files the same method, i believe something is not like it should be.

First file app.js:
```javascript
import { p as Part, h, render } from './import';
import { Internal } from './in2';
const App = () => <Part> <Internal /> T </Part>;
render(<App />, document.getElementById('app'));
```
Second file in2.js:
```javascript
import { p as Part, h } from './import';
export const Internal = () => <Part> Test 2 </Part>;
```
Third file import.js:
```javascript
import { h, render } from 'preact';
export const p = "p";
export { h, render }
```
output:
```javascript
// src/import.js
import {h, render} from "preact";
const p = "p";

// src/in2.js
const Internal = () => h3(p, null, " Test 2 ");

// src/in.js
const App = () => h2(p, null, h2(Internal, null), " T ");
render2(h2(App, null), document.getElementById("app"));
```

Note the broken h2, render2, h3 functions.

Preact is marked as external file, output format esm. Yes i know this is an uncommon way of doing it. But, in other bundlers, output bundle is smaller, because the reexported function is only referenced once, and i am able to reuse it, and its possible to reexport it with the same name. What is important, with h and render in react/preact ...

Thank you.

**Comment by evanw** [comment]
Thank you for the clear description of what's wrong and for the minimal test case. It looks like I'm not binding imports to re-exports. I'm surprised I haven't run into this issue yet with all of my testing. This will be fixed soon.

**Comment by a-gerescher** [comment]
Thanks a lot!
