### ISSUE TITLE
 esbuild runs very slowly on the company's private network

### ISSUE THREAD

**Issue by RicholeYu** [evanw/esbuild#1491]

**Comment by RicholeYu** [comment]
![Uploading image.jpg…]()

**Comment by RicholeYu** [comment]
![0BBFC83B-FB91-409B-B4B9-27E02F3C0581](https://user-images.githubusercontent.com/25808811/127988244-b03009c6-de38-459a-9ac5-42c5f46c2273.jpeg)

**Comment by evanw** [comment]
I don’t understand what this means. The network is not involved when esbuild runs. Results are computed locally, not downloaded over the network.
