### ISSUE TITLE
Minification resulting in use of "this" before super()

### ISSUE THREAD

**Issue by MixMasterMitch** [evanw/esbuild#1497]
I think this issue is similar to https://github.com/evanw/esbuild/issues/242

[This class](https://github.com/software-mansion/react-native-reanimated/blob/30dcac7cb5a2fc4b22ea9651d93be7ca729f0286/src/reanimated1/core/AnimatedBlock.js) is being converted into the following minified output:
```javascript
var yJ = class extends X {
    constructor(t) {
        le(this, "_array");
        (0, gJ.default)(t.every(r => r instanceof X), "Reanimated: Animated.block node argument should be an array with elements of type AnimatedNode. One or more of them are not AnimatedNodes"), super({
            type: "block",
            block: t
        }, t), this._array = t
    }
    toString() {
        return `AnimatedBlock, id: ${this.__nodeID}`
    }
    __onEvaluate() {
        let t;
        return this._array.forEach(r => {
            t = Le(r)
        }), t
    }
};
```

Executing this results in the following browser error:
```
ReferenceError: 'super()' must be called in derived constructor before accessing |this| or returning non-object.
```

I am using an esbuild target of `es6`. I tried other values and all had the same problem.

**Comment by hyrious** [comment]
Minimal reproduction (it's an issue with `--minify-syntax`):
```js
class A extends B {
  x;
  constructor() {
    f(); // "Side Effect before super()", try comment this line
    super();
  }
}
// produces:
class A extends B {
  constructor() {
    __publicField(this, "x");
    f(), super();
  }
}
```
> When used in a constructor, the `super` keyword appears alone and must be used before the `this` keyword is used.

**Comment by nielsvanvelzen** [comment]
I'm running in this same issue after b589476. A minimal reproduction based on the previous comment:

```js
class A extends B {
	x;
	constructor() {
		super(), (this.x = 'z');
	}
}
```

Produces
```js
class A extends B {
  constructor() {
    __publicField(this, "x");
    super(), this.x = "z";
  }
}
```

With `esbuild a.js --minify-syntax --outfile=b.js --target=es6`
