### ISSUE TITLE
There is no way to bundle the package.json

### ISSUE THREAD

**Issue by aruizca** [evanw/esbuild#1502]
My use case is that I need to retrieve the name and version of my module dynamically from the `package.json file`. Eg:

```javascript
import { name, version } from '../../package.json';
```
Is there any way to workaround this scenario?

Thanks!

**Comment by hyrious** [comment]
It is able to **bundle** [json](https://esbuild.github.io/content-types/#json) files, make sure `--bundle` is present.

Also checkout https://github.com/evanw/esbuild/issues/1486#issuecomment-890980681.

BTW, `import ... from` is not really _dynamic_, instead `import()` is.

**Comment by evanw** [comment]
If by dynamically you mean `package.json` should not be bundled, then you should mark the file as [external](https://esbuild.github.io/api/#external) to exclude it from the bundle.

**Comment by aruizca** [comment]
I need to package.json to be part of the output as a separate file

**Comment by retorquere** [comment]
Do you mean you want the package.json copied alongside the output? You can do that in the script that calls esbuild.

**Comment by aruizca** [comment]
Problem I have is that I am using AWS CDK NodejsFunction
***@***.***_aws-lambda-nodejs.NodejsFunction.html>
and I don't have much control on the bundling process.

**Comment by evanw** [comment]
I'm closing this since it sounds like this isn't a problem with esbuild. The lack of a post-build callback in the AWS CDK is not something that can be addressed by an esbuild API change.
