### ISSUE TITLE
Esbuild and firebase-cli issue. Triggers rebuild of every file

### ISSUE THREAD

**Issue by navanshu** [evanw/esbuild#1503]
I have a custom application and have esbuild as my transpiler for typescript code with watch mode on.  
I run firebase emulator alondside my app.

First I run my application that has esBuild then I run the firebase-tools to get the emulators running, as soon as firebase changes some json / logs files (not packages.json obviously, firebase.json and some log files)

Esbuild goes into a nasty restart type of mode and start to transpile each file it is watching, its quite nasty for me as my application communicates on threads and I have terser to minimize the code. It would be good if esbuild (❤️) doesn't get affected by this change. I don't know for sure what causes this. But only happens if I run the firebase-cli after running my application.

**Comment by evanw** [comment]
Closing as I believe this should be fixed as of [version 0.13.5](https://github.com/evanw/esbuild/releases/tag/v0.13.5), specifically by #1676.
