### ISSUE TITLE
Need to change var to globalThis.

### ISSUE THREAD

**Issue by navanshu** [evanw/esbuild#1504]
I have an app and I genereate IIFE using esbuild and then i do some changes to produced bundle 
1. Convert IIFE into a function 
```javascript
(() => someCode)(); // produced by esbuild
() => someCode // convert into this
```
2. Store IIFE into a variable
```javascript
() => someCode // old
var Code = () => someCode // new
```
3. Run this function based on event listeners. It gets the job done

But this make var variable scoped into local execution context and are only available in the context.
Fix I think is to convert top level vars into globalThis. Is this possible with esbuild?
If there is any other way think that may improve this kindly tell.

**Comment by hyrious** [comment]
You can make use of [footer](https://esbuild.github.io/api/#footer) and `--global-name`:
```js
// a.js
export default function main() {
    console.log("hello, world!")
}
```
```bash
esbuild a.js --bundle --global-name=code --footer:js="globalThis.Code = code.default;"
```
```js
// output
var Code = (() => { ... })();
globalThis.Code = Code.default;
```

**Comment by navanshu** [comment]
Okay that actually works thanks for the fix.
