### ISSUE TITLE
Case-insensitive script and style closing tags are not escaped

### ISSUE THREAD

**Issue by wilsonzlin** [evanw/esbuild#1509]
5e749a2 fixed #1322 by escaping `</script` substrings to avoid being interpreted as a closing tag when embedded within an HTML `script` tag, but it didn't escape other case forms. The [spec](https://html.spec.whatwg.org/multipage/scripting.html#restrictions-for-contents-of-script-elements) states that the contents of a `<script>` end at a case-insensitive `</script`.

I tested with the following code:

```js
window.x = `</ScRIpt>`;
```

When run through esbuild, the result is:

```js
window.x="</ScRIpt>";
```

Which when embedded within an HTML page:

```html
<script>window.x="</ScRIpt>";</script>
```

Results in:

```
Uncaught SyntaxError: "" literal not terminated before end of script
```

Also, I noticed the same issue with CSS. With the following code:

```css
div {
  background: url("</style>");
}
```

The esbuild output is:

```css
div{background:url(</style>)}
```

Which when embedded within an HTML page causes the ending `)}` to leak out as HTML text.

I tested with version 0.12.19; feel free to close if this has already been fixed since.

**Comment by evanw** [comment]
What code uses `</ScRIpt>`? Is that a realistic concern? I have only ever seen `</script>`. Point taken about `</style>` though.

**Comment by wilsonzlin** [comment]
Thanks for the `</style>` fix. 👍 

Regarding the script tag, it's probably never done, although `</SCRIPT>` may be used somewhat. I'm using esbuild as a library within an HTML minifier I'm writing, so it's more about guaranteeing the output can't be invalid, and a simple search-and-replace for `</script` (case insensitive) isn't as accurate (and esbuild already has this feature anyway).
