### ISSUE TITLE
[Question] Error with shelljs module

### ISSUE THREAD

**Issue by kameshsampath** [evanw/esbuild#1510]
I am trying to us esbuild to build a vscode extension. The build works well but then I am seeing an error with `shelljs` module. 

I tried reproducing the same error with my demo project https://github.com/kameshsampath/esbuild-demo:

Once the build is complete and I run the script `yarn run echo` I get the following error:

```
$ node out/index.js
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module './src/cat'
Require stack:
- /tmp/js/esbuild-demo/out/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at /Users/kameshs/MyLabs/js/esbuild-demo/out/index.js:2766:7
    at Array.forEach (<anonymous>)
    at node_modules/shelljs/shell.js (/tmp/js/esbuild-demo/out/index.js:2765:24)
    at __require (/tmp/js/esbuild-demo/out/index.js:9:44)
    at Object.<anonymous> (/tmp/esbuild-demo/out/index.js:2777:26)
    at Module._compile (internal/modules/cjs/loader.js:1085:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/tmp/js/esbuild-demo/out/index.js' ]
}
error Command failed with exit code 1.
info Visit https://yarnpkg.
```

I read similar issue https://github.com/shelljs/shelljs/issues/754.

Any thoughts how to build a app with `shelljs`

**Comment by hyrious** [comment]
This is because shelljs uses dynamic require (`require(expression)`), which prevents bundlers to correctly analyse the dependencies. In short, `require('./a')` works but `require('./' + 'a')` doesn't.

It is usually ok to put your package `dependencies` in `external` when targetting vscode extensions. Simply try `esbuild entry.ts --bundle --platform=node --external:shelljs`.

**Comment by kameshsampath** [comment]
thank @hyrious  moving `shelljs` to external helped moving ahead.

**Comment by 7PH** [comment]
Hi @hyrious @kameshsampath  , I've opened [a PR on shelljs](https://github.com/shelljs/shelljs/pull/1161) to fix the issue on their side

> This is because shelljs uses dynamic require (require(expression)), which prevents bundlers to correctly analyse the dependencies. In short, require('./a') works but require('./' + 'a') doesn't.

Yes, and `require('./' + 'a.js')` works in the case of shelljs because the js files are present in the bundle
