### ISSUE TITLE
Docs: default JS format and transformSync

### ISSUE THREAD

**Issue by plmrry** [evanw/esbuild#1517]
According to [the docs](https://esbuild.github.io/api/#format-iife):

>  The iife format is the default format unless you set platform to node

However, with `transformSync`, this isn't true, as shown [in this test](https://github.com/evanw/esbuild/blob/bb4ae37d675ca0e5153b55f21ba1b76fdbcca67e/scripts/js-api-tests.js#L4042-L4043):

```js
      const { code } = esbuild.transformSync(`console.log(1+${i})`, {})
      assert.strictEqual(code, `console.log(1 + ${i});\n`)
```

I know that `transformSync` doesn't have a `platform` option, but the wording in the docs still makes it sound like `iife` will be the default format for `transformSync`

**Comment by evanw** [comment]
Thanks for pointing this out. The docs need to be updated. The default format is pass-through when bundling is disabled, but `iife` when bundling is enabled.

**Comment by evanw** [comment]
Docs have been updated: https://esbuild.github.io/api/#format.

**Comment by plmrry** [comment]
@evanw thanks! Although, at the end of the `iife` section, you have:

> Specifying the *esm* format looks like this:

I think that should be "iife" not "esm"?
