### ISSUE TITLE
How can I use esbuild to replace tsc when developing backend code

### ISSUE THREAD

**Issue by ZYinMD** [evanw/esbuild#1519]
This is probably a stupid question, and probably not the intended use of esbuild, but I have a very simple goal:

1. Build an express server, write my code in `src`, which includes many .ts files and sub folders.
2. Mirror `src` into `dist`, turning all .ts files into .js, but retaining folder structures and filenames, without any bundling.
3. Turn on watch mode during development, run the express server from the `dist` folder. 

This is exactly what tsc does, but I want to use esbuild instead of tsc for speed. I might run `tsc --noEmit` once before deploy, but that's all.

Since this goal is very common and very simple, I wonder what the "standard recommendation" is to achieve it. I didn't find it in the docs. Thanks!

**Comment by evanw** [comment]
You didn’t find it in the docs because esbuild doesn’t do this. It’s a bundler, not a tsc replacement. It’s probably possible to use esbuild to build someone like a tsc replacement but it’s not built in.

**Comment by gozmanyoni** [comment]
You can use estrella - https://github.com/rsms/estrella, which uses esbuild and provides the functionality you require.

Or build your own FS listener that run esbuild on changed files outputting them to dist and re-running your process.

**Comment by ZYinMD** [comment]
To people who found this issue:

I don't know why I had some previous memory that `tsc --watch` was slow, but the reality is it's very fast. If you're developing server code and don't need bundling, just use `tsc --watch`. The proposed use of esbuild in OP was really unnecessary.

**Comment by osdevisnot** [comment]
👋 @ZYinMD I don't think `tsc --watch` meets your third requirement.

> 3\. Turn on watch mode during development, run the express server from the `dist` folder.

FWIW, I've been doing it [this way](https://twitter.com/osdevisnot/status/1357822454027018240)

![Etf0THvVkAIk9XA](https://user-images.githubusercontent.com/802242/129491090-84246063-49a1-47b0-a362-38d6abc5d654.jpeg)

This works with bundling enabled, unless no-bundle is a hard requirement.

**Comment by gozmanyoni** [comment]
> To people who found this issue:
> 
> I don't know why I had some previous memory that `tsc --watch` was slow, but the reality is it's very fast. If you're developing server code and don't need bundling, just use `tsc --watch`. The proposed use of esbuild in OP was really unnecessary.

That is not true for large codebases.
esbuild does provide a significant benefits.

swc is another interesting option.

**Comment by ianmuninio** [comment]
For AWS Lambda deployment, we tried to make the cold start faster and esbuild made it possible for us. It's true that you don't need this most of the time but not for lambda. We only use it for some of our critical lambda like custom API Gateway Lambda Authorizer.

**Comment by khokm** [comment]
I want to use esbuild for transpiling not for speed in first case, but to be sure that generated code will be same - esbuild and tsc output may differ sometimes. Also i can't use bundling, because some modules are [importing dynamically ](https://github.com/fastify/fastify-autoload).
