### ISSUE TITLE
How can I use more than one plugin?

### ISSUE THREAD

**Issue by Ty3uK** [evanw/esbuild#1520]
Hello!

First of all, thank you for your amazing project!

I have some weird issue: in my project I have two plugins with onLoad callback. First - replaces `@` to relative path, second - runs `@emotion/babel-plugin` on files that have `@emotion/styled` in code.

Then, if I include both of this plugins in `plugins` array, `onLoad` will be fired only in topmost plugin. After some investigation I've found that in `handleRequest` function `request.key` always have `0` value.

Does this mean that esbuild doesn't support (yet?) plugins chaining? Or am I doing something wrong?

Repo with example: https://github.com/Ty3uK/esbuild-plugin-chaing-reproduce

**Comment by hyrious** [comment]
> Does this mean that esbuild doesn't support (yet?) plugins chaining?

In general, yes.
In the long term, the `onResolve` and `onLoad` does not behave like `transform`. The former resolves paths and the latter produces contents. The contents is produced **once** for a resolved path.

If you'd like to transform a file twice, it's better to put them inside one `onLoad` callback.

About your first plugin, transforming `@` to relative path, you may use tsconfig's [paths](https://www.typescriptlang.org/tsconfig#paths) to do so.

About chaining plugins, there's a plugin called [pipe](https://github.com/nativew/esbuild-plugin-pipe) providing a custom `transform` callback to enable such things.

**Comment by Ty3uK** [comment]
Thank you!
