### ISSUE TITLE
[Bug?] hash not stable with same files

### ISSUE THREAD

**Issue by indooorsman** [evanw/esbuild#1530]
see attachment. hash changes every build without any file changed. It may be a bug or by design or I missed some configuration？

<img width="663" alt="WX20210818-083532@2x" src="https://user-images.githubusercontent.com/4919405/129819669-41c3ed5b-d4ee-43e8-9ec8-568ba790e17f.png">

```js
esbuild.build({
  entryPoints: [entry],
  inject: ['./plugins/react-shim.js'],
  write: true,
  bundle: true,
  minify: false,
  watch: false,
  define: {
    APP_ADVERTISING_VERSION: JSON.stringify({
      version: packageJson.version,
      sparkUIVersion: packageJson.dependencies['spark-ui'],
      buildAt: new Date().toString(),
      buildPlatform: process.platform,
      env: mode
    })
  },
  outdir,
  target: ['chrome80', 'firefox78'],
  sourcemap: 'external',
  splitting: false,
  chunkNames: '[name]-[hash]',
  entryNames: '[name]-[hash]',
  assetNames: '[name]-[hash]',
  publicPath: '/static/advertising',
  logLevel: 'info',
  metafile: false,
  plugins: [aliasPlugin(alias), CssModulesPlugin({ v2: true })],
  loader: {
    '.svg': 'dataurl',
    '.png': 'file'
  }
});
```

**Comment by hyrious** [comment]
```js
buildAt: new Date().toString(),
```
It changed.

**Comment by indooorsman** [comment]
@hyrious 😢 thanks. but why css files change ?

**Comment by indooorsman** [comment]
> ```js
> buildAt: new Date().toString(),
> ```
> 
> It changed.

I removed it but no luck

**Comment by evanw** [comment]
I can take a look if you can provide self-contained sample code that reproduces the issue. It could potentially be an esbuild bug. Also make sure that the file contents and file paths (including virtual files generated by plugins) are the same between builds.

**Comment by indooorsman** [comment]
@evanw oh that's it... my plugin generate virtual files in random path ... 😭
