### ISSUE TITLE
globally accessible vendor chunk 

### ISSUE THREAD

**Issue by alexsoin** [evanw/esbuild#1532]
Please tell me how to create a vendor.js file with global access dependencies (collected from imports located in the node_modules) through the esbuild during assembly, by analogy with the work of webpack chunks:

```js
// webpack.config.js
...
optimization: {
  splitChunks: {
    chunks: 'all',
    maxInitialRequests: Infinity,
    minSize: 0,
    cacheGroups: {
    vendor: {
      test: /[\\/]node_modules[\\/]/,
      name: "vendor"
    },
    },
  },
}
...
```

How can I also collect two files of main.js and vendor.js in esbuild? I read the documentation and looked at the plugins, I could not find a solution for this problem.

**Comment by evanw** [comment]
This is not currently possible, and is an active feature request. Closing this duplicate issue in favor of #207.
