### ISSUE TITLE
process.env.NODE_ENV process is not defined

### ISSUE THREAD

**Issue by qballer** [evanw/esbuild#1533]
esbuild:0.12.21
node:14.17.3

When trying to provide the environment variable NODE_ENV it seems to not work with a specific library "[react-unleash-flags](https://github.com/fvoordeckers/react-unleash-flags)". 
I've created a small repo that reconstructs [the issue](https://github.com/qballer/esbuild-bug). To see the issue please do the following
```bash
npm run esbuild
npm run serve
```
after that got to http://localhost:8000/www/
You will be able to see something like this
![Screen Shot 2021-08-19 at 16 58 55](https://user-images.githubusercontent.com/1002622/130081904-eab757a3-cf1e-41ee-8b13-3f1ac78791e8.png)

if you comment out the feature flag you will see that everything works
![Screen Shot 2021-08-19 at 16 59 16](https://user-images.githubusercontent.com/1002622/130081970-67a52fa3-8fad-420d-aca4-a3d2675640b6.png)

Everything works on webpack but I would love to use this tool instead

**Comment by qballer** [comment]
Well it looks like this solves it:
adding the following defines:
```
      'process.env.NODE_ENV': '\"development\"',
      'process.env.REACT_APP_FLAGS_CTX_APP_NAME': '\"\"',
      'process.env.REACT_APP_FLAGS_CTX_INSTANCE_ID': '\"\"',
      'process.env.REACT_APP_FLAGS_CTX_HOST': '\"\"',
      'process.env.REACT_APP_FLAGS_CTX_URL' :'\"\"',
      'process.env.REACT_APP_FLAGS_CTX_URI':'\"\"'
```

react unleash seems to be using them internally. I wonder if there could be a proxied object created which by default will provide falsy values to all calls to process.env

**Comment by evanw** [comment]
> I wonder if there could be a proxied object created which by default will provide falsy values to all calls to process.env

Yes. See https://github.com/evanw/esbuild/issues/1374#issuecomment-861801905.
