### ISSUE TITLE
Is there a way to explicitly preserve a name when minifying?

### ISSUE THREAD

**Issue by aaboyd** [evanw/esbuild#1549]
I've recently tried to move our minification from Terser to esbuild and we've run into some problems while bundling three.js .

The issue we ran into in the past is described here https://github.com/mrdoob/three.js/issues/18540 . The solution is to add the `keep_fnames: /Float32Array/` option to our Terser configuration.  After moving to esbuild, I am not aware of a way to prevent the minifier from modifying `Float32Array` name.

Is there some way to do this that I am no seeing?  Thanks in advance for the help.

**Comment by evanw** [comment]
Closing this since there wasn't a reply. It sounds like the "keep names" option is appropriate from the issue description.
