### ISSUE TITLE
Unused top-level code is not removed with format:esm but is removed with format:iife

### ISSUE THREAD

**Issue by marc136** [evanw/esbuild#1551]
Hello, 

If I use an IIFE as output format, the dead top-level code is removed. I would expect the same behavior for ESM (as the global definitions also cannot leak outside the module).

This seems to be an unintended bug, as @evanw wrote on https://github.com/evanw/esbuild/issues/1518#issuecomment-899065935
>  ESM or IIFE. Neither of these formats allow module-level variables to leak into the global scope, so it’s ok for esbuild to remove unused code as it cannot possibly be referenced.

Or is there maybe a technical reason why I need to use the `build` API to get DCE when using ESM as an output format? But I think it would still be inconsistent behavior.

I have this code to check for the behavior

```js
const esbuild = require('esbuild');
const fs = require('fs');
const os = require('os');

function print(caption, code) {
    console.log(caption, '\n```js\n', code.toString().trim(), '\n```\n');
}

const esm = `// as ESM
function unusedFn(a) {
    return a + 1;
}

const a = 5;
let b = 7;

export const c = 2;
`;

const iife = `// as IIFE
function unusedFn(a) {
    return a + 1;
}

const a = 5;
let b = 7;

window.c = 2;
`;

const options = {
    target: "es2020",
    format: "esm",
};

let result = esbuild.transformSync(iife, Object.assign({}, options, { format: "iife" }));
print('Unused code is removed with format:iife', result.code);

result = esbuild.transformSync(esm, options);
print('Unused code is kept with format:esm', result.code);

const tmpFile = `${os.tmpdir()}/esbuild-test-${Date.now()}.js`
fs.writeFileSync(tmpFile, esm, { encoding: 'utf8' });
esbuild.buildSync(Object.assign(options, {
    entryPoints: [tmpFile],
    outfile: tmpFile,
    allowOverwrite: true,
    bundle: true,
}));
result = fs.readFileSync(tmpFile, { encoding: 'utf8' });
fs.rmSync(tmpFile);
print('Unused code is removed with format:esm and bundle:true', result);
```
---

Which yields with esbuild 0.12.22:

`❯ node esbuild-bug.js`

Unused code is removed with format:iife 
```js
(() => {
  window.c = 2;
})();
```

Unused code is kept with format:esm 
```js
function unusedFn(a2) {
  return a2 + 1;
}
const a = 5;
let b = 7;
const c = 2;
export {
  c
};
```

Unused code is removed with format:esm and bundle:true 
```js
 // ../../../../../tmp/esbuild-test-1629875946567.js
var c = 2;
export {
  c
};
```

**Comment by evanw** [comment]
You should now be able to use `treeShaking: true` with `format: 'esm'` to do this. This was added in [version 0.13.0](https://github.com/evanw/esbuild/releases/tag/v0.13.0) last September. Closing as fixed.
