### ISSUE TITLE
Also provide binaries for Android arm

### ISSUE THREAD

**Issue by thunder-coding** [evanw/esbuild#1556]
Currently esbuild only has prebuilt binaries for Android aarch64/arm64. It would be great to also have it for arm devices.

**Comment by hez** [comment]
Rasbian 32bit is also armv7 I believe.  Would be nice to be able to target/build for that.

**Comment by evanw** [comment]
_Cross-posting from https://github.com/evanw/esbuild/pull/1578#issuecomment-1019021979_

I'm closing this as I don't want to complicate esbuild's deploy process by having to install the entire Android build toolchain for this one platform. All of the other 18 platforms I already support can be built fine by Go on any platform without installing anything. I still don't understand why Go doesn't support cross-platform builds for this platform in particular (Go and Android are even both Google projects!) but that's up to them I guess. If you want to run esbuild on 32-bit Android ARM, you'll have to build it yourself. Sorry.

**Comment by rayfoss** [comment]
Linux arm (32bit ARM) and Android amd64 do cross compile just fine... The only relevant ones that don't are iOS arm64 and Android amd64

For 32bit Raspberry PI @hez `GOOS=linux GOARCH=arm go build ./cmd/esbuild`
For Android 64bit ARM @thunder-coding `GOOS=android GOARCH=arm64 go build ./cmd/esbuild`

Both of those do cross compile as expected in my testing, but also based on the documentation:

https://gist.github.com/asukakenji/f15ba7e588ac42795f421b48b8aede63#support-grid-1
