### ISSUE TITLE
Support class static blocks

### ISSUE THREAD

**Issue by Hawmex** [evanw/esbuild#1558]
[This](https://github.com/tc39/proposal-class-static-block) is currently at stage 3 and is supported by [Chrome](https://v8.dev/features/class-static-initializer-blocks#support) and [Typescript 4.4](https://github.com/microsoft/TypeScript/pull/43370).

**Comment by evanw** [comment]
Thanks for calling this out. I have been watching this feature and I'm aware of it. The issue is mainly that the current class transform is really complicated and has some shortcomings that need to be addressed such as #1328 (also #1524, #1360, #1480). So these should probably be reworked together.

**Comment by Hawmex** [comment]
### Update:

This proposal reached stage 4!
