### ISSUE TITLE
Browser compat table: Optional Chaining is available from Chrome 80

### ISSUE THREAD

**Issue by eugene1g** [evanw/esbuild#1559]
Recently, the browser compatibility table was updated to mark `OptionalChain` as available in Chrome91 instead of Chrome 80
https://github.com/evanw/esbuild/commit/d945c75c6ce0e7c6211a8a6acda885b049bc92b4 and it was released with `0.12.20`

MDN still shows this as [available in Chrome >=80](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining) 

Was this change intentional?

**Comment by jridgewell** [comment]
There is a bug in Chome's implementation of optional calls: https://github.com/kangax/compat-table/pull/1708

This is present from v80-v90, with v91 shipping the fix.

**Comment by eugene1g** [comment]
Fascinating. More details from here https://github.com/babel/babel/issues/13001

Good enough for me - this change _was_ intentional. Thanks!
