### ISSUE TITLE
optional chaining grouping bug

### ISSUE THREAD

**Issue by kzc** [evanw/esbuild#156]
An obscure corner of the spec as gleaned from https://github.com/estree/estree/pull/204 ...

Given:
```
$ esbuild --version
0.4.2
```
```
$ cat optchain.js
let o=null;try{o=(o?.a).b||"FAIL";}catch(x){}console.log(o||"PASS");
```
Expected:
```
$ cat optchain.js | node-v14.3.0
PASS
```
Actual:
```
$ cat optchain.js | esbuild --minify | node-v14.3.0
FAIL
```
```
$ cat optchain.js | esbuild --minify
let o=null;try{o=o?.a.b||"FAIL"}catch(a){}console.log(o||"PASS");
```
Down-levelling will preserve the intent of the original parentheses however:
```
$ cat optchain.js | esbuild --target=es2019 --minify | node-v14.3.0
PASS
```
```
$ cat optchain.js | esbuild --target=es2019 --minify
let o=null;try{o=(o==null?void 0:o.a).b||"FAIL"}catch(a){}console.log(o||"PASS");
```

**Comment by evanw** [comment]
Ah crap. Thanks so much for calling this out. I made sure the lowering worked in that case but forgot about pass-through. I like the idea in that thread of thinking of `?.` as a normal infix operator, as well as `.` belonging to an optional chain. I'll figure out how to fix this.

**Comment by kzc** [comment]
It's interesting that there are as many ways to model optional chaining as there are estree contributors. No one would likely ever use parentheses in this context in real life code. Hmm... maybe it could be used as a sort of mid-expression assert.
