### ISSUE TITLE
React bundling error: Invalid hook call

### ISSUE THREAD

**Issue by davegomez** [evanw/esbuild#1567]
> **Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:**
> 1. You might have mismatching versions of React and the renderer (such as React DOM)
> 2. You might be breaking the Rules of Hooks
> 3. You might have more than one copy of React in the same app
> See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

This is the error I'm finding when trying to bundle my React component library using esbuild.

I have tested many configuration and both format `esm` and `cjs`, but even when I successfully create the package and export my component, I get this error every time I try to use React hooks inside my components.

I created an [example repository using the minimal esbuild configuration](https://github.com/davegomez/esbuild-react-hooks-error) needed to create a React component library, which works only if I don't use hooks.

The stack trace shows the following:

> **resolveDispatcher**
>   node_modules/react/cjs/react.development.js:1476
> **useRef**
>   node_modules/react/cjs/react.development.js:1515
> **App**
>   /Users/davidg/Development/esbuild-react-hooks-error/lib/index.js:46

```js
  43 | });
  44 | var import_react = __toModule(require("react"));
  45 | function App(props) {
> 46 |   const ref = import_react.default.useRef();
  47 |   return /* @__PURE__ */ import_react.default.createElement("div", __spreadProps(__spreadValues({}, props), {
  48 |     ref
  49 |   }));
```

**Comment by hyrious** [comment]
You forgot to [_externalize_](https://esbuild.github.io/api/#external) react, which results in **more than one copy of React in the same app**.

**Comment by davegomez** [comment]
Thank you for the swift response @hyrious.

That was my first guess, but it's not working adding the `exrternal` option or even putting React as a `devDependency`.

**Comment by piersolenski** [comment]
Having the same issue, regardless of whether React is externalised or not 👍

**Comment by evanw** [comment]
Your instructions in the repo https://github.com/davegomez/esbuild-react-hooks-error resulted in code that works fine for me. The instructions were incomplete so I added some additional steps to get something that runs in the browser. Here's what I did:

```
$ git clone git@github.com:davegomez/esbuild-react-hooks-error.git
$ cd esbuild-react-hooks-error
$ npm ci
$ npm run build
$ npm pack
$ mkdir temp
$ cd temp
$ npm init -y
$ npm i esbuild react react-dom ../esbuild-react-hooks-error-1.0.0.tgz
$ cat example.jsx

    import React from 'react';
    import ReactDOM from 'react-dom';
    import Comp from 'esbuild-react-hooks-error';
    function App() {
      return <Comp>Testing</Comp>
    }
    ReactDOM.render(<App />, document.getElementById('foo'))

$ cat index.html

    <body><div id="foo"></div></body>
    <script src="out.js"></script>

$ npx esbuild --bundle example.jsx --outfile=out.js --servedir=.
```

At this point you can open http://127.0.0.1:8000/ in the browser. It says `Testing` in my browser with no errors thrown. So everything appears to be working fine.

What are you doing differently that is causing the error? Are you running the resulting component through some additional tool other than esbuild?

**Comment by davegomez** [comment]
Thank you @evanw 

Your example works, the only difference would be that I used two different fresh projects to test it using **create-react-app** and a custom one using **snowpack**, and both showed the same error.

I'm using only **esbuild** but now I'm sure I'm doing something wrong just don't know what.

Gonna keep looking and thank you for your help.

**Comment by max-sym** [comment]
I have the same issue now. @davegomez how did you solve it?

**Comment by max-sym** [comment]
@davegomez Thanks for quick reply!
Hmmm weird. Anyway, I ditched CRA and used vite instead, as I said in my previous comment, and it worked. Let's see if something happens again. Thanks :)
