### ISSUE TITLE
transform() API -  "name" option

### ISSUE THREAD

**Issue by FredKSchott** [evanw/esbuild#157]
Currently, the "name" option is hardcoded as "input.xxx"  in the JS API's `transform()` function:

https://github.com/evanw/esbuild/blob/master/npm/esbuild/lib/main.js#L283-L285

Normally this doesn't matter, but when inline sourcemaps are enabled every file is given the same "input.ts" filename as the "source" file. Could we add support for an `options.name` or `options.filename` option? Happy to add a PR if it helps.

fwiw, I know that Babel uses a `filename` option even when transforming from source/stdin.

**Comment by evanw** [comment]
The option is called `sourcefile`, not `filename`:

https://github.com/evanw/esbuild/blob/6a6ee4ea7b6c83d0f3f5b94fdffe575845b3c244/npm/esbuild/lib/main.d.ts#L9

I should probably make the API throw an error when you use `transform()` with `sourcemap` but not `sourcefile`. But that's a breaking change so I think I'll wait on that until the next round of breaking changes.

**Comment by FredKSchott** [comment]
that works, thank you!
