### ISSUE TITLE
Grouped destructuring expressions are "ungrouped" incorrectly.

### ISSUE THREAD

**Issue by SidOfc** [evanw/esbuild#1570]
Hello! First, thanks for building this tool, it is very simple to use and very fast, kudos!

Now for the issue, when running the following:
```sh
echo '[...(maybe.array || [])]' | esbuild
```

The result is:
```js
[...maybe.array || []];
```

However, I believe the result should be:
```js
[...(maybe.array || [])];
```

The parentheses should not be removed here since the compiler can't be certain that the left-hand side of the `||` will be an array (this would also make the `|| []` part redundant). Currently, this fails with the following exception if `maybe.array` is `undefined`:

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
```

I've confirmed this behavior on:
- version `0.12.24` running `esbuild --bundle --platform="node" --target="es2018"`
- version `0.12.24` running `esbuild`
- version `0.12.25` running `esbuild`

Finally, apologies if the issue name is a bit weird, if you have a better description in mind feel free to improve!

**Comment by jridgewell** [comment]
The current transformation is correct, both `[...maybe.array || []];` and `[...(maybe.array || [])];` are parsed the same way.

Try running this in your browser:
```js
const maybe = {};

// These both print [1]
console.log([...maybe.array || [1]]);
console.log([...(maybe.array || [1])]);

maybe.array = [2];
// These both print [2]
console.log([...maybe.array || [1]]);
console.log([...(maybe.array || [1])]);

**Comment by SidOfc** [comment]
Ah I see, I checked again and saw my rookie mistake, the `maybe` I'm calling `.array` on has a function with the same name :facepalm: . I was effectively trying to do `[...(function() {} || [])]` which of course is not the compiler's fault.

Cheers for the insanely quick reply, closing, feel free to delete if this is just a garbage issue that adds no real value.
