### ISSUE TITLE
How to handle esbuild tree shaking in author library

### ISSUE THREAD

**Issue by straker** [evanw/esbuild#1573]
I am the author of https://github.com/straker/kontra/ and would like to know what I need to change in my library in order for esbuild to properly tree shake it. Tree shaking works as expected when using Rollup, but when using esbuild it doesn't tree shake very well.

For example, If I only import the [degToRad](https://github.com/straker/kontra/blob/main/src/helpers.js#L20-L22) helper, Rollup gives me the expected output:

```js
// index.js
import { degToRad } from './kontra.mjs';

const rad = degToRad(180);
console.log('rad:', rad);
```

```terminal
npx rollup index.js --format iife --file out.js 
```

```js
(function () {
  'use strict';

  function degToRad(deg) {
    return deg * Math.PI / 180;
  }

  const rad = degToRad(180);
  console.log('rad:', rad);

}());
```

However, when trying to compile the same file with esbuild, it produces a file that contains almost the entire library (1280 lines long).

```terminal
npx esbuild index.js --bundle --format=iife --outfile=out.js
```

I have `"sideEffects": false` set in the package.json, and I've tried putting `/*@__PURE__*/` in various places around functions but that doesn't seem to work. So I'm not sure what else I should do in order to support esbuild tree shaking.

A little more info on the library. It follows the underscore.js pattern of [exporting all modules](https://github.com/jashkenas/underscore/blob/master/modules/index.js) and [exporting the `_` namespace](https://github.com/jashkenas/underscore/blob/master/modules/index-default.js) so that it can be used as both a global variable with all modules or just importing the specific module needed.

I thought maybe that was the issue but a small test file that did the same pattern was able to tree shake the unused code

```js
// module.mjs
function radToDeg(rad) {
  return rad * 180 / Math.PI;
}

function degToRad(deg) {
  return deg * Math.PI / 180;
}

const namespace = {
  degToRad,
  radToDeg
};

export default namespace;
export { degToRad, radToDeg };
```

```js
// index.js
import { degToRad } from './module.mjs';

const rad = degToRad(180);
console.log('rad:', rad);
```

```terminal
npx esbuild index.js --bundle --format=iife --outfile=out.js
```

```js
(() => {
  // module.mjs
  function degToRad(deg) {
    return deg * Math.PI / 180;
  }

  // index.js
  var rad = degToRad(180);
  console.log("rad:", rad);
})();
```

**Comment by hyrious** [comment]
The thing that prevents your library to be tree-shaked is some _assignments_ are being treated as side effects, here a shorter example:
```js
// b.js
export const f = 1
export const g = {}
g.a = 42                 // <- side effects
export const h = 2       // <- no side effects

// a.js
import { f } from "./b.js"
console.log(f)

// esbuild a.js --bundle
(() => {
  // b.js
  var f = 1;
  var g = {};
  g.a = 42;

  // a.js
  console.log(f);
})();
```
Why could `g.a = 42` has side effects? Because someone can write:
```js
g = { set a(x) { /* !!! */ } }
```
esbuild's tree-shaking is somewhat conservative for the correctness. It tries to do the same as Node.js's built-in es modules (like these side effects are always preserved).

Therefore, there's no luck for your library to get rid of it (unless Evan has decided to analyze the code as much as rollup does).

**Comment by straker** [comment]
Gotcha. Thank you for your answer.
