### ISSUE TITLE
esbuild postinstall scripts hangs randomly on WSL

### ISSUE THREAD

**Issue by UltraCakeBakery** [evanw/esbuild#1574]
When doing a `npm install` inside my devcontainer (`FROM mcr.microsoft.com/vscode/devcontainers/javascript-node:14`/`:16` esbuild always causes the entire terminal to freeze.

Nothing changes when I clear the npm cache, restart WSL, restart/reset docker.

This is all logs I have available:

```
node ➜ /app/backend (02ed521 ✗) $ npm cache clean --force
npm WARN using --force I sure hope you know what you are doing.
node ➜ /app/backend (02ed521 ✗) $ npm ci
npm WARN prepare removing existing node_modules/ before installation

> esbuild@0.12.25 postinstall /app/backend/node_modules/esbuild
> node install.js
```

After this I have to manually stop the script again as it simply never ends.

How could I debug this properly?

**Comment by Gelio** [comment]
I'm encountering a similar problem on Ubuntu 18.04.5 LTS and using yarn v2.4.1. I was able to install esbuild v0.12.25 initially, but then after removing `node_modules`, it gets stuck at the postinstall script.

Downgrading to v0.12.24 allowed me to install it, but again, reinstalling after cleaning `node_modules` is stuck at `postinstall`.

**Comment by senritsu** [comment]
Having a similar issue with the `mcr.microsoft.com/vscode/devcontainers/typescript-node` image. `esbuild` hangs on `npm install` or `yarn install`. Interrupting the hanging install with `ctrl-c` led to an error message. 

After restarting the container `install` worked, but still needed `node ./node_modules/esbuild/install.js` before the (vite) project was able to actually start.
