### ISSUE TITLE
splitting chunk

### ISSUE THREAD

**Issue by yisar** [evanw/esbuild#1575]
This is very important. At present, esbuild does not support it, so almost all my projects cannot be migrated from webpack to esbuild, because there are too many common chunk references in webpack, and esbuild only supports a little.

**Comment by hyrious** [comment]
[There are many likewise issues asking for the same thing.](https://github.com/evanw/esbuild/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+splitting)

If your project is a library, then rollup (vite) is maybe a better choice.

If your target is a site, and you don't like the current esm-only splitting strategy, then vite is maybe a better choice. If you just want something simple & stupid, [here is a dead-simple iife way to do manual chunks.](https://github.com/hyrious/esbuild-split-vendors-example)

**Comment by yisar** [comment]
@hyrious We are mini programs, not web projects. Vite is useless. I'll try to solve the problem manually for the time being, but esbuild had better improve it because it's really important.
