### ISSUE TITLE
the transform API can not remove unused variables

### ISSUE THREAD

**Issue by jerryYuX** [evanw/esbuild#1576]
code example:
```js
const res = transformSync(chunk.code, { minify: true, treeShaking: true, format:'esm', target:'es2015', loader: 'js' })
```
The result still contains unused variables

**Comment by hyrious** [comment]
tree-shaking in `transform` only exists when `--format=iife`.

**Comment by jerryYuX** [comment]
> tree-shaking in `transform` only exists when `--format=iife`.
I want to use esbuild to replace terser, and terser supports configuration `compress:{unused:true}` in transform.so Is there a way for the esbuild to remove unused variables？

**Comment by hyrious** [comment]
You can. Just use the `bundle` api and mark all imports as external with a simple plugin:
```js
{
  name: 'external-all',
  setup({ onResolve }) {
    onResolve({ filter: /()/ }, args => {
      if (args.kind !== 'entry-point')
        return { path: args.path, external: true }
    })
  }
}
```

**Comment by jerryYuX** [comment]
> Just use the `bundle` api and mark all imports as external with a simple plugin:
> 
> ```js
> {
>   name: 'external-all',
>   setup({ onResolve }) {
>     onResolve({ filter: /()/ }, args => {
>       if (args.kind !== 'entry-point')
>         return { path: args.path, external: true }
>     })
>   }
> }
> ```

OK, thanks,I will try to do it.

**Comment by jerryYuX** [comment]
It seems to work normally,but  I still hope that the tree-shaking of the es module can be turned on directly through the option of `transfrom` API.Thank you!
