### ISSUE TITLE
Only write files when the checksum of the result has changed

### ISSUE THREAD

**Issue by whitepaperclip** [evanw/esbuild#1577]
@evanw I can submit a PR for this, but wanted to see if this is even desirable first. 

I currently have some dev tools that reload my browser during development if certain watched files change, but mtime changes also trigger these browser updates. It would be nice if esbuild only wrote the bundled files when the result would have different contents than currently exist.

**Comment by evanw** [comment]
I'm not sure if this is desirable.

Some build tools work by checking the outputs of the build and rebuilding if the inputs are newer than the outputs. Right now this is never the case after a build so you should never get unnecessary rebuilds in this case, but if esbuild works the way you suggested then it would appear to these tools that the build is stale even after a successful build. So this may not be a good default behavior.

You should be able to do this yourself by using the API with [`write: false`](https://esbuild.github.io/api/#write) and then writing the files with your own code that does this.

**Comment by whitepaperclip** [comment]
Got it, thanks @evanw !
