### ISSUE TITLE
Wrong output generated for NullishCoalescing (`??` operator)

### ISSUE THREAD

**Issue by forehalo** [evanw/esbuild#1592]
version: latest master(https://github.com/evanw/esbuild/commit/6a3d3a67661378c36ab0f8f450feffc191ec9b52)

input:
```js
const a = b ?? "1";

b ??= "1";
```

output:
```js
const a = b != null ? b : "1";

b != null ? b : b = "1";
```

expected output ([how TypeScript does it](https://www.typescriptlang.org/play?#code/MYewdgzgLgBAhjAvDARjA-OmAiAjNgbgFgAoUtTZPQ0oA)):
```js
const a = b !== null && b !== void 0 ? b : "1";

b !== null && b !== void 0 ? b : (b = "1");
```

As described in [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator):
> The nullish coalescing operator (`??`) is a logical operator that returns its right-hand side operand when its left-hand side operand is `null` or `undefined`, and otherwise returns its left-hand side operand.

The thing happened when esbuild parser trying to lower the nullish coalescing operator into conditional expression(`x ? x : x`)
CHECK [lowerNullishCoalescing](https://github.com/evanw/esbuild/blob/6a3d3a67661378c36ab0f8f450feffc191ec9b52/internal/js_parser/js_parser_lower.go#L916-L916)

```go
func (p *parser) lowerNullishCoalescing(loc logger.Loc, left js_ast.Expr, right js_ast.Expr) js_ast.Expr {
	// "x ?? y" => "x != null ? x : y"
	// "x() ?? y()" => "_a = x(), _a != null ? _a : y"
	leftFunc, wrapFunc := p.captureValueWithPossibleSideEffects(loc, 2, left, valueDefinitelyNotMutated)
	return wrapFunc(js_ast.Expr{Loc: loc, Data: &js_ast.EIf{
		Test: js_ast.Expr{Loc: loc, Data: &js_ast.EBinary{
			Op:    js_ast.BinOpLooseNe,
			Left:  leftFunc(),
			Right: js_ast.Expr{Loc: loc, Data: js_ast.ENullShared},
		}},
		Yes: leftFunc(),
		No:  right,
	}})
}
```

**Comment by hyrious** [comment]
It is correct, because `something == null` returns true if and only if `something` is `null` or `undefined`, which satisfies spec. BTW, it's shorter.

**Comment by forehalo** [comment]
> It is correct, because `something == null` returns true if and only if `something` is `null` or `undefined`, which satisfies spec. BTW, it's shorter.

oh, you are right, I've taken it wrong
