### ISSUE TITLE
Top-level await error on supported browsers

### ISSUE THREAD

**Issue by NickGeek** [evanw/esbuild#1594]
Hi, I'm getting the following error when trying to build a project with TLA:

```
Top-level await is not available in the configured target environment ("chrome89", "firefox91", "safari15")
```

That is incorrect because Chrome 89, FF 91, and Safari 15 all support TLA.

**Comment by evanw** [comment]
Thanks for calling this out. The issue is that the data source I'm using for this is lacking contributions, and top-level await (along with a lot of other features) hasn't been added yet: https://github.com/kangax/compat-table/issues/1034. I will add it to esbuild manually.

**Comment by NickGeek** [comment]
Thanks!

**Comment by NickGeek** [comment]
@evanw You may need to add `ios15` to the list too.
