### ISSUE TITLE
Possible bug in the sourcemap generation

### ISSUE THREAD

**Issue by djalbat** [evanw/esbuild#1595]
I have put together a small project on GitHub to show the bug in action:

https://github.com/djalbat/sourcemaps-bug

For the sake of brevity I will not repeat the bug description here.

One thing I would add is that I am not entirely sure that the problem is with esbuild, but I am not sure.

**Comment by djalbat** [comment]
I've looked into this some more. If I build with Browserify rather than ESBuild then the problem persists. In fact Browserify does cannot even match ESBuild in that the `example.js` file does not even appear in the browser's developer tools. So it is a case of garbage in, garbage out from the point of view of the bundler. Further comments can be found in the issue raised for on SWC here:

https://github.com/swc-project/swc/issues/2236

I think it might be wise to keep this issue open until what appears to be a bug with SWC is fixed. As of writing, I am now pretty sure that the problem is not with ESBuild.

**Comment by evanw** [comment]
Ok. I will keep this open but mark it as "unactionable" because it's blocked by a problem with another project and cannot currently be verified.

**Comment by djalbat** [comment]
No worries, I'll close it. The information is here now for Google to find.
