### ISSUE TITLE
Difference between Javascript code generated from Typescript between esbuild and tsc

### ISSUE THREAD

**Issue by sloonz** [evanw/esbuild#1596]
Typescript : 

```js
class Test {
    id?: number;
}
```

Code generated by tsc : 

```js
class Test {
}
```

Code generated by esbuild : 

```js
class Test {
    id;
}
```

This results in an observable difference for `console.log({...new Test()})` : tsc version results in `{}`, esbuild version in `{id: undefined}`. This difference breaks, for example, the `.patch()` method of Objection, because `patch()` does something like this : `initialObject.$set(partialUpdate)`, which overrides non-patched fields to undefined (instead of preserving previous values).

**Comment by hyrious** [comment]
This behavior is controlled by tsconfig: useDefineForClassFields, which is enabled by default in esbuild if:
- bundle
- there is target: esnext in tsconfig
In other words, it is disabled if
- transform --target=esnext

If you need this behavior in transform, you have to append tsconfig like this:
`--tsconfig-raw={"compilerOptions":{"useDefineForClassFields":true}}`.

**Comment by sloonz** [comment]
Awesome, thanks for the answer !
