### ISSUE TITLE
JSON loader outputs invalid ESM code when a JSON file contains top-level properties like `"dashed-key": ""`

### ISSUE THREAD

**Issue by sodatea** [evanw/esbuild#1598]
## Reproduction

https://replit.com/@sodatea/esbuild-json-esm

## Suggested solution

Top-level JSON properties whose keys are illegal identifiers should not be exported as named exports.

**Comment by evanw** [comment]
This isn't invalid ESM. It's valid JavaScript, but it uses the ESNext feature known as [arbitrary module namespace identifier names](https://github.com/bmeck/proposal-arbitrary-module-namespace-identifiers) which is supported in recent versions of Chrome, Firefox, and Node. If you need the output to run in old JavaScript VMs that don't support certain ESNext features, make sure to specify the [target](https://esbuild.github.io/api/#target) setting such as `--target=node12.22.4` (the target defaults to `--target=esnext` if it's not explicitly specified).
