### ISSUE TITLE
Unsafe ++/-- transforms with private fields (number vs bigint)

### ISSUE THREAD

**Issue by bathos** [evanw/esbuild#1600]
In
```js
(class {
  static #a = 0n;
  static #b = this.#a++;
});
```
Out
```js
// (__accessCheck, etc here)
var _a, _b, _a2, _b2;
_b = class {
}, _a2 = new WeakMap(), _b2 = new WeakMap(), __privateAdd(_b, _a2, 0n), __privateAdd(_b, _b2, (__privateSet(_b, _a2, (_a = +__privateGet(_b, _a2)) + 1), _a)), _b;
```

In `+__privateGet(_b, _a2)) + 1`, the unary `+`  will throw a TypeError (and if it were absent, the binary `+ 1` would throw instead).

AFAIK, esbuild currently outputs the WeakMap-based transforms for static private fields unilaterally even if you want private fields to pass through as-is. (I’m hopeful that this will change eventually: I only noticed this one because I’d accidentally forgotten I can’t use public or private fields with esbuild safely for reasons unrelated to this specific issue.)

**Comment by evanw** [comment]
Thanks for calling this out. I believe I copied Babel's transform for this and so have inherited the same bug. I'll fix this in the next release.
