### ISSUE TITLE
minify: provide an option to enable treeshaking in single-file transform

### ISSUE THREAD

**Issue by yyx990803** [evanw/esbuild#1610]
In 4d32f7ccf41bf877bb5cf8e42944007acf7bfcb7 it was explained that treeshaking is disabled in single file transform due to esbuild not seeing the entire bundle. However, there are use cases where:

1. We know the file is a single ES module that won't be concatenated with other files;
2. We do NOT want to use `build --bundle` because we want to minify the file in isolation.
3. We also do NOT want to use `--format iife` because we don't want to change the format of the file.

A real world example is where Vite using `esbuild` as a minifier to minify ESM chunks produced by Rollup.

Currently there seems to be no way to force esbuild to enable top-level treeshaking when using the `transform` API - this creates some issues when some tools' codegen leaves unused declarations expecting them to be removed by minifiers.

I think it'd be nice to have an option to force enable this. Maybe just respect `treeShaking: true` when calling the `transform` API.

**Comment by yyx990803** [comment]
Actually this is why I've found a somewhat unpredictable 10%~20% difference compared to Terser when I tested using esbuild as the minifier for Vite in real world cases - in some cases it's Rollup's treeshaking failing, in some cases it's plugins leaving unused code expecting the minifier to remove them.

**Comment by hyrious** [comment]
It is also possible to do what you said in `bundle` api with a plugin that externalizes everything except the entry point: https://github.com/evanw/esbuild/issues/1576#issuecomment-913356103. But I do think it is valuable to do tree-shaking in `transform` too.

However, as I know vite uses rollup to build the dist, which does tree-shaking a lot (at least more than esbuild). Therefore I don't think applying esbuild on rollup's result could make dist smaller.

**Comment by yyx990803** [comment]
Our use case is a bit niche, since we rely on disabling Rollup's treeshaking for certain modules for module graph analysis in bundle generation phase, and instead rely on the minifier to remove those forced-included modules.
