### ISSUE TITLE
Another __require breaks on 0.12.26

### ISSUE THREAD

**Issue by Khachatour** [evanw/esbuild#1614]
Hello fellow contributors and @evanw, Thank you for this work you all are doing.

I want to state that by build is breaking after updating from `0.12.24` -> `0.12.26` and above.

I am getting `Dynamic require of "react" is not supported` this is an `iife` format build for browser target.

Before this error, I had an entry file with this content

```js
const keyModule = {
  react: 'React',
  'react-dom': 'ReactDOM',
  'react-dom/server': 'ReactDOMServer',
  'styled-components': 'styled',
};

(window as any).require = (key: string) => {
  if (Object.hasOwnProperty.call(keyModule, key)) {
    const name = keyModule[key];
    if (Object.hasOwnProperty.call(window, name)) {
      return window[name];
    }
    // eslint-disable-next-line no-console
    console.log(`Cannot find umd script for ${key}`);
  }
  return undefined;
};
```
As a workaround for external dependencies (which are marked as `external` in build API). 
I am testing this on plain HTML with react and other dependencies linked with a script tag.

Now I am getting this error, but what's strange is that I go to the final bundled file and just put this snippet which is also bundled just at the top of the file. It works. I think there is some possible race condition-ish stuff for wrapping the require.

Reverting and doing this with `0.12.24` seems completely fine.

For cross reference: #1579

**Comment by hyrious** [comment]
Yet another reference: #1604
