### ISSUE TITLE
Question: pass content string to `esbuild.build`?

### ISSUE THREAD

**Issue by loynoir** [evanw/esbuild#1620]
Currently, `esbuild.build` seems only accept filename.

```js
esbuild.build({entryPoints})
```

Is it possible to pass `content` and `filename` to `esbuild.build`?
Something like
```js
esbuild.build(preprocessed_source_code_by_other, {filename: vinyl.path})
```
```js
esbuild.build(vinyl.contents, {filename: vinyl.path})
```

Similar design also exists
```js
babel.transformSync(content, {filename})
```

```js
prettier.format(content, {filepath})
```

**Comment by hyrious** [comment]
You can use the [stdin](https://esbuild.github.io/api/#stdin) option. A `resolveDir` is required if you want to import other files in that content.

**Comment by loynoir** [comment]
@hyrious Wow, awesome! Thanks a lot! 😘
