### ISSUE TITLE
value-less props probably should not be emitted

### ISSUE THREAD

**Issue by cztomsik** [evanw/esbuild#1623]
I am not 100% sure what's correct behaviour regarding the class fields in ES but I know TS compiler results in a different code and unfortunately, it causes some bugs in my project. I also believe this is a new thing because it worked fine with older version of esbuild.

Example:
```
abstract class X {
  abstract readonly nodeType: number
}
```

Results in empty `class X {}` in [TS playground page](https://www.typescriptlang.org/play?#code/IYIwzgLgTsDGEAJYBthjAgsgTwHIHsATAUwQG8BYAKAQVEhngSmOEPwDtlsEOjiAKtgAOxAFy8ArgFsQxKNQC+1IA)

To be precise, TS compiler does not do it even for this case as you can [see here](https://www.typescriptlang.org/play?#code/MYGwhgzhAEAa0G8CwAoa0IHsC2BTACgE6YAOAXNGAHYCeqAvqkA):
```
class X {
  someProp
}
```

This is unfortunately problem for codebases with inheritance, because that `abstract readonly nodeType: number` is going to define property with value `undefined` and if you define getter `get nodeType() { return XXX }` on a subclass it will be ignored (not installed on the object instance)

```
class Y extends X {
  get nodeType() {
    return 1
  }
}
new Y().nodeType // should be 1 but is undefined
```

**Comment by evanw** [comment]
After some investigation, I believe the case where esbuild's output differs from the TypeScript compiler is where TypeScript's [`useDefineForClassFields`](https://www.typescriptlang.org/tsconfig#useDefineForClassFields) setting is set to `true` and the field is marked as `abstract`. In that case the TypeScript compiler is omitting it while esbuild isn't. That's an esbuild bug that needs to be fixed.

**Comment by cztomsik** [comment]
Thanks a lot, setting it to `false` resolved my issue and I can use the latest version. Feel free to close this if you don't care about the abstract case.
