### ISSUE TITLE
Uncaught ReferenceError: Buffer is not defined

### ISSUE THREAD

**Issue by oboxodo** [evanw/esbuild#1626]
Trying to bundle a project which includes https://solana-labs.github.io/wallet-adapter. 

First, I had a problem with `global` not being defined which I was able to solve using `define` as explained in https://github.com/evanw/esbuild/issues/73.

But now I'm getting this:
```
Uncaught ReferenceError: Buffer is not defined
    at node_modules/@ledgerhq/devices/lib/hid-framing.js (application-4e75002f3581f8a7fba234807c6daba3464e2fe671a1aeab139bc09d6e9fe1b7.js:55405)
    at __require2 (application-4e75002f3581f8a7fba234807c6daba3464e2fe671a1aeab139bc09d6e9fe1b7.js:45)
    at application-4e75002f3581f8a7fba234807c6daba3464e2fe671a1aeab139bc09d6e9fe1b7.js:93507
    at application-4e75002f3581f8a7fba234807c6daba3464e2fe671a1aeab139bc09d6e9fe1b7.js:95920
```

The error happens in [this line of code](https://github.com/LedgerHQ/ledgerjs/blob/915a59d53f8e5fbc705ee122ad51b39c4fedc00c/packages/devices/src/hid-framing.ts#L19).

Any ideas how to solve that, without depending on that package's maintainers to change their code?

**Comment by evanw** [comment]
`Buffer` is a node API. Are you running the code somewhere outside of node? If so, you'll have to provide an implementation of `Buffer` yourself such as https://www.npmjs.com/package/buffer. One way to do this might be to use esbuild's [inject](https://esbuild.github.io/api/#inject) feature with a file containing something like `export let Buffer = require('buffer').Buffer`.

**Comment by oboxodo** [comment]
@evanw yes, you were right.

This is the full set of changes I had to make in order to be able to build an app including https://solana-labs.github.io/wallet-adapter with esbuild:

* Install packages `buffer`, `process`, `crypto-browserify`, and `stream-browserify`.
* Add `--define:global=window --inject:config/esbuild.inject.js` options when calling `esbuild`.
* Add file `config/esbuild.inject.js` with the following contents:
    ```js
    export let Buffer = require("buffer").Buffer
    export let process = require("process/browser")
    ```
* Add the following `browser` entry to the `package.json` file:
    ```json
    "browser": {
      "crypto": "crypto-browserify",
      "stream": "stream-browserify"
    }
    ```

That seems to have worked. Now I need to figure out why it's generating a 4.5 MB bundle 😅

**Comment by niksy** [comment]
If someone is looking for unified solution to aliasing Node libraries and global variables such as `Buffer` or `process`, official support for `esbuild` has been added in [`node-stdlib-browser`](https://github.com/niksy/node-stdlib-browser#esbuild).

**Comment by data-miner00** [comment]
> If someone is looking for unified solution to aliasing Node libraries and global variables such as `Buffer` or `process`, official support for `esbuild` has been added in [`node-stdlib-browser`](https://github.com/niksy/node-stdlib-browser#esbuild).

Oh my god can't believe this actually worked, flawlessly! Thank you so much!!!

**Comment by anshuomomo** [comment]
Add these code in your index.html maybe work.

```
<script type="module">
    import { Buffer } from "buffer";
    window.Buffer = Buffer;
  </script>
```
This works for me.

**Comment by Srr233** [comment]
Hello there, I was faced same issue, but I found worked example: 
`<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <meta name="theme-color" content="#000000" />
    <meta name="description" content="C2C" />
    <link rel="apple-touch-icon" href="%PUBLIC_URL%/tonb.svg" />
    <link rel="manifest" href="%PUBLIC_URL%/manifest.json" crossorigin="use-credentials" />
    <link href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" rel="stylesheet" />
    <title>C2C</title>
    <script src="https://bundle.run/buffer@6.0.3"></script>
    <script>
      window.Buffer = window.buffer.Buffer;
    </script>
    <script
      src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
      integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8="
      crossorigin="anonymous"
    ></script>
  </head>
  <body>
    <div id="root"></div>
  </body>
</html>
`
2 important things:
 `  <script src="https://bundle.run/buffer@6.0.3"></script>
    <script>
      window.Buffer = window.buffer.Buffer;
    </script>`
And DONT USE IT WITH ASYNC.

**Comment by harissatti** [comment]
> Hello there, I was faced same issue, but I found worked example:
> 
> ```
> <html lang="en">
>   <head>
>     <meta charset="utf-8" />
>     <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
>     <meta name="viewport" content="width=device-width, initial-scale=1" />
>     <meta name="theme-color" content="#000000" />
>     <meta name="description" content="C2C" />
>     <link rel="apple-touch-icon" href="%PUBLIC_URL%/tonb.svg" />
>     <link rel="manifest" href="%PUBLIC_URL%/manifest.json" crossorigin="use-credentials" />
>     <link href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" rel="stylesheet" />
>     <title>C2C</title>
>     <script src="https://bundle.run/buffer@6.0.3"></script>
>     <script>
>       window.Buffer = window.buffer.Buffer;
>     </script>
>     <script
>       src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
>       integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8="
>       crossorigin="anonymous"
>     ></script>
>   </head>
>   <body>
>     <div id="root"></div>
>   </body>
> </html>
> ```
> 
> 2 important things: ` <script src="https://bundle.run/buffer@6.0.3"></script>` `<script>window.Buffer = window.buffer.Buffer;</script>` And DONT USE IT WITH ASYNC.

that work for me thanks for this solution. :)

**Comment by work-naveenbasyal** [comment]
> Hello there, I was faced same issue, but I found worked example:
> 
> ```
> <html lang="en">
>   <head>
>     <meta charset="utf-8" />
>     <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
>     <meta name="viewport" content="width=device-width, initial-scale=1" />
>     <meta name="theme-color" content="#000000" />
>     <meta name="description" content="C2C" />
>     <link rel="apple-touch-icon" href="%PUBLIC_URL%/tonb.svg" />
>     <link rel="manifest" href="%PUBLIC_URL%/manifest.json" crossorigin="use-credentials" />
>     <link href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" rel="stylesheet" />
>     <title>C2C</title>
>     <script src="https://bundle.run/buffer@6.0.3"></script>
>     <script>
>       window.Buffer = window.buffer.Buffer;
>     </script>
>     <script
>       src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
>       integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8="
>       crossorigin="anonymous"
>     ></script>
>   </head>
>   <body>
>     <div id="root"></div>
>   </body>
> </html>
> ```
> 
> 2 important things: ` <script src="https://bundle.run/buffer@6.0.3"></script>` `<script>window.Buffer = window.buffer.Buffer;</script>` And DONT USE IT WITH ASYNC.

Thank u , worked for me
