### ISSUE TITLE
0.13 --minify --tree-shaking=true drops ES exports without --format

### ISSUE THREAD

**Issue by yyx990803** [evanw/esbuild#1628]
**In**
```js
// input.js
const a = {}
export { a }
```

**Out**
```js
// esbuild input.js --minify -tree-shaking=true
const o={};
```

```js
// esbuild input.js --minify -tree-shaking=true --format=esm
const o={};export{o as a};
```

Probably should not alter exports when no format is specified.

**Comment by evanw** [comment]
Thanks for the report. Tree shaking has never been enabled in this context before, so this case was not previously considered. The cause of this is that with the `esm` output format a single `export {}` statement with all exports is appended to the end so the other `export {}` statements are removed when tree shaking is active, but this single `export {}` statement isn't added to the end without a configured output format. I'll fix this in the next release.
