### ISSUE TITLE
how to reslove json auto module.exports = affix

### ISSUE THREAD

**Issue by dongjinc** [evanw/esbuild#1639]
hello，look a little code
```json
{
  "name": "esbuild",
  "version": "0.7.22",
  "description": "An extremely fast JavaScript bundler and minifier.",
  "repository": "https://github.com/evanw/esbuild",
  "scripts": {
    "postinstall": "node install.js"
  },
  "main": "lib/main.js",
  "types": "lib/main.d.ts",
  "bin": "bin/esbuild",
  "license": "MIT"
}
```
through esbuild ..
```json
module.exports={name:"esbuild",version:"0.7.22",description:"An extremely fast JavaScript bundler and minifier.",repository:"https://github.com/evanw/esbuild",scripts:{postinstall:"node install.js"},main:"lib/main.js",types:"lib/main.d.ts",bin:"bin/esbuild",license:"MIT"}

```
how to delete module.exports ?

**Comment by dongjinc** [comment]
> This is how json file actually work as a module to be imported by other files. Why do you want a bare js object string? If you want to assign it to some variable, you can bundle it with another file importing the json like `var a = require('./a.json')`.

I think you are Chinese，Let's speak chinese 
是这样的，如果你有一个区域选择json文件，难道要在json文件内这样写吗
```json
module.exports = {
    '10001': '北京'
}
```
不应该这样写吗
```json
{
    '10001': '北京'
}
```
如果第一种写法 vscode会报错的哈，你觉得呢

**Comment by evanw** [comment]
If you want it to be valid JSON, you don't need esbuild. Just use the input file unmodified. Or use `JSON.stringify(JSON.parse(x))` if you want it minified.

**Comment by dongjinc** [comment]
> If you want it to be valid JSON, you don't need esbuild. Just use the input file unmodified. Or use `JSON.stringify(JSON.parse(x))` if you want it minified.

thanks,  I see the document contains json content . Did it for a long time . always auto affix.
i suggest can support this feature。eg: Affix(module.exports) can be customized

**Comment by hyrious** [comment]
`{ '10001': '北京' }` is not a valid JSON, you can not apply JSON.parse on it.
esbuild supports **import** JSON in js since it is common, and it will eventually output valid javascript code.
You'd better just use the original json file, or minify it with a little script like Evan said, or bundle it into your final code.

**Comment by dongjinc** [comment]
considering esbuild include minify json file Function. so try it minify the original json file. 
I might understand esbuild minify json It does not really compress the original json file and output json file/code. only pass though import json or the origin json output valid javascript code.
thank you very much

**Comment by dongjinc** [comment]
> `{ '10001': '北京' }` is not a valid JSON, you can not apply JSON.parse on it. esbuild supports **import** JSON in js since it is common, and it will eventually output valid javascript code. You'd better just use the original json file, or minify it with a little script like Evan said, or bundle it into your final code.

considering esbuild include minify json file Function. so try it minify the original json file.
I might understand esbuild minify json It does not really compress the original json file and output json file/code. only pass though import json or the origin json output valid javascript code.
thank you very much

**Comment by dongjinc** [comment]
thanks yours 。close with comment~
