### ISSUE TITLE
ENOENT when installing even when manually running install.sh

### ISSUE THREAD

**Issue by clavierpaul** [evanw/esbuild#1642]
Installing esbuild, I get the following error:

```
error /afs/userfolder/Projects/Web/project/node_modules/esbuild: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /afs/userfolder/Projects/Web/project/node_modules/esbuild
Output:
child_process.js:830
    throw err;
    ^

<ref *1> Error: spawnSync /afs/userfolder/Projects/Web/project/node_modules/esbuild/bin/esbuild ENOENT
    at Object.spawnSync (internal/child_process.js:1077:20)
    at spawnSync (child_process.js:776:24)
    at Object.execFileSync (child_process.js:822:15)
    at validateBinaryVersion (/afs/userfolder/Projects/Web/project/node_modules/esbuild/install.js:64:32)
    at Object.<anonymous> (/afs/userfolder/Projects/Web/project/node_modules/esbuild/install.js:96:3)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync /afs/userfolder/Projects/Web/project/node_modules/esbuild/bin/esbuild',
  path: '/afs/userfolder/Projects/Web/project/node_modules/esbuild/bin/esbuild',
  spawnargs: [ '--version' ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 1470830,
  stdout: null,
  stderr: null
}
```

I had read online that running `node node_modules/esbuild/install.sh` can fix the problem, however I get the exact same error running the script. I'm on node version v14.18.0.

**Comment by evanw** [comment]
Which OS version, esbuild version, package manager version, and installation command (including any custom package manager configuration files)? And does this happen every time?

**Comment by clavierpaul** [comment]
Ubuntu 20.04, esbuild@latest, nvm 2.2.6, `npm install esbuild` or `npm install esbuild@latest`.

**Comment by david-massey** [comment]
I see the same issue on Android11/Termux. I tried updating node and my package manager.
Node 14.4.0 and 16.10.0
pnpm 6.14.6 and 7.24.1
`pnpm install esbuild` or manually running `node node_modules/esbuild/install.sh`.
Yes, it happens every time. Just make a new project and run `pnpm i esbuild`.

**Comment by david-massey** [comment]
For me, the error occurs in `install.js#100`:
```fs2.unlinkSync(toPath)```
This is caught, but then it never tries to `linkSync` on the next line. ENOENT then occurs on validation

`esbuild@0.13.3/node_modules/esbuild/bin/` is empty, which generates the error in `unlinkSync`. Wrapping that with a `fs2.existsSync(toPath)` gets past that error.

However, `linkSync` generates an EACCES (permission) error on when linking `esbuild-android-arm64@0.13.3/node_modules/esbuild-android-arm64/bin/esbuild` to `esbuild@0.13.3/node_modules/esbuild/bin/esbuild`. The source exists but cannot write to the destination. All `bin/` directories and the `esbuild-android-arm64/bin/esbuild` have permissions 700.

**Comment by evanw** [comment]
Thanks for the details. I guess I didn't anticipate the scenario where `unlinkSync` succeeds but `linkSync` fails. I can rework the install script to be atomic on failure (i.e. `linkSync` followed by `renameSync`).

**Comment by david-massey** [comment]
Just to be clear, the initial situation is `unlinkSync` fails, is caught by the try/catch, never even attempts to `linkSync`, and then the script tries to validate a file that doesn't exist. When I guarded `unlinkSync` by an `existsSync`, `linkSync` fails due to permissions.

**Comment by evanw** [comment]
If `unlinkSync` had failed then the file it attempts to unlink should still be there and validation should still succeed. The file `node_modules/esbuild/bin/esbuild` should exist after the package is installed but before the installation script is run, since it's present in the package archive: https://unpkg.com/browse/esbuild@0.13.3/bin/esbuild.

**Comment by david-massey** [comment]
Thank you for the explanation there. Sorry, I did not unpack the package, and I just inspected it after the very first ENOENT failure on install. I now understand this to mean on the initial installation `unlinkSync` works, `linkSync` failed, is caught, and validate produces ENOENT. Any subsequent attempts to run `install.js` then cause `unlinkSync` to fail, as now there is no file to unlink.
