### ISSUE TITLE
bundle with esm: http imports not compiled and inlined

### ISSUE THREAD

**Issue by linux-china** [evanw/esbuild#1643]
I have a simple  TypeScript file with Deno library,    `demo.ts` file with following code: 

```typescript
import {sprintf} from "https://deno.land/std@0.109.0/fmt/printf.ts"

export function formatNumber(num: number): string {
    return sprintf("%9.8f", num);
}
```

Then I use `esbuild workers/function1.ts --bundle --platform=browser --format=iife`  to bundle this file, and http imports will be inlined into the bundle file with **format iife**. 

Then I switch to **esm format**, `esbuild workers/function1.ts --bundle --platform=browser --format=esm`  to bundle this file, and http imports will not be inlined and just keep same as following: 

```
// workers/function1.ts
import { sprintf } from "https://deno.land/std@0.109.0/fmt/printf.ts";

function formatNumber(num) {
  return sprintf("%9.8f", num);
}
export {
  formatNumber
};
```

Any idea to inline the http imports with format esm?

**Comment by hyrious** [comment]
> Then I use `esbuild workers/function1.ts --bundle --platform=browser --format=iife` to bundle this file, and http imports will be inlined into the bundle file with **format iife**.

No, it doesn't. You'd have to use a plugin to fetch http resources, for example the [HTTP plugin](https://esbuild.github.io/plugins/#http-plugin) from the docs.

**Comment by linux-china** [comment]
@hyrious  Got. thanks for your answer.

**Comment by linux-china** [comment]
@hyrious  I found this plugin https://deno.land/x/esbuild_plugin_http_fetch    Thanks for your remind, and I should check the plugins first :)

**Comment by Xeevis** [comment]
Why repeatedly fetch something that is most likely already cached on the FS? Deno caches everything. Just hit the Deno Graph and retrieve it from cache, Deno can still download if missing.

```ts
import { createCache } from "https://deno.land/x/deno_cache/mod.ts";
import { createGraph } from "https://deno.land/x/deno_graph/mod.ts";

const denoPlugin = {
  name: "deno-import",
  setup(build: esbuild.PluginBuild) {
    build.onResolve({ filter: /^https?:\/\// }, (args) => ({ path: args.path, namespace: "deno-url" }));
    build.onResolve({ filter: /.*/, namespace: "deno-url" }, (args) => ({
      path: new URL(args.path, args.importer).toString(),
      namespace: "deno-url",
    }));
    build.onLoad({ filter: /.*/, namespace: "deno-url" }, async (args) => {
      const { cacheInfo, load } = createCache();
      const graph = await createGraph(args.path, { cacheInfo, load });

      const module = graph.get(args.path);
      return { contents: module?.source };
    });
  },
};
```
