### ISSUE TITLE
Warning in the console

### ISSUE THREAD

**Issue by marcofugaro** [evanw/esbuild#1648]
I updated esbuild to version 0.13.x, and now I get a ton of this kind of warnings in the console.

Everything still works fine tough.

![image](https://user-images.githubusercontent.com/7217420/135674894-0269b481-dcd2-42c4-9002-c16311a5bf7f.png)

For context, I own a MacBook Air with an M1 processor.

**Comment by geoffharcourt** [comment]
This is because esbuild now has optional dependencies for every potential platform. These are harmless, but are a workaround for some behaviors in Yarn 2 that broke installation on some platforms.

**Comment by evanw** [comment]
These log messages are irrelevant and useless and can be ignored. Up-to-date versions of npm won't print these useless log messages, so you can update npm to avoid these if you don't want to see them. You may also be able to keep using the same version of npm but adjust the `loglevel` setting to not see these useless log messages, although I haven't ever tried that myself so I'm not sure about that. Anyway this is a problem with your package manager, not with esbuild.

**Comment by marcofugaro** [comment]
Indeed, I am using Yarn classic v1

Thanks for the info!
