### ISSUE TITLE
Example of using `external` with a filepath?

### ISSUE THREAD

**Issue by Pomax** [evanw/esbuild#1649]
The documentation for `external` currently reads:

> You can mark a file or a package as external to exclude it from your build. Instead of being bundled, the import will be preserved (using require for the iife and cjs formats and using import for the esm format) and will be evaluated at run time instead.

But this does not cover how to use it in combination with a filename. For example, I have a dependency with a dynamic import that relies on `path` and `fs`, but will never actually load when running in the browser. Without externals, esbuild throws the following error:

```
> esbuild ./src/game-client/app.js --bundle --loader:.js=jsx --format=esm --jsx-factory=h --outfile=./public/mahjong-client.js --watch --sourcemap

 > node_modules/js-schema-tools/lib/models/store/filesystem-store.js: error: Could not resolve "fs" (set platform to "node" when building for node)
    1 │ import fs from "fs";
      ╵                ~~~~

 > node_modules/js-schema-tools/lib/models/store/filesystem-store.js: error: Could not resolve "path" (set platform to "node" when building for node)
    2 │ import path from "path";
      ╵                  ~~~~~~
```

Since `external` can take a filepath, I figured I'd add the full path for this file:

```
> esbuild ./src/game-client/app.js --bundle --loader:.js=jsx --format=esm --jsx-factory=h --outfile=./public/mahjong-client.js --external:node_modules/js-schema-tools/lib/models/store/filesystem-store.js
```

However, this does not seem to exclude the file from the bundle, with the same error as before. Can the docs be amended to show an example of excluding an import by path?

**Comment by Pomax** [comment]
Looking at the code for that file, the dynamic import is effected by `const { FileSystemStore } = await import("./store/filesystem-store.js");` so marking it as external on a module name wouldn't work (as far as I know?)

**Comment by Pomax** [comment]
On a whim I tried `--external:*/filesystem-store.js`, and that works, but that feels like now I'm abusing the wildcard, what would be the "correct" path according to esbuild?

**Comment by hyrious** [comment]
```
--external:./node_modules/js-schema-tools/lib/models/store/filesystem-store.js
```
Relative paths starting with `.`, absolute paths starting with `/`, libraries starting with `[_@a-z]`.

A more common way to deactivate some library in browser should be manually replace them with no-op ones. You can use the [`browser`](https://esbuild.github.io/api/#platform) field in package.json, like so:

```js
"browser": {
    "js-schema-tools": false // or "./some-polyfill.js"
}
```

**Comment by Pomax** [comment]
Nice: can that be added to the documentation for `external`? Because it does not explain or link to the rules for paths at the moment.

**Comment by evanw** [comment]
The documentation has been updated to explain the specific rules regarding how external paths are interpreted and applied: https://esbuild.github.io/api/#external. Closing since this is now documented and has an example.
