### ISSUE TITLE
Question: way to have external suspicion alert ?

### ISSUE THREAD

**Issue by olup** [evanw/esbuild#1651]
I am just asking that for my general culture: is there a way for a bundler like esbuild to detect when an import will not be bundlable, and warn it's user about it ? Using esbuild to package lambda functions, my main fear all the time is to miss an external and discover it only at runtime when the code fails. Thanks.

**Comment by hyrious** [comment]
I suppose you are asking a general problem: how to know code would fail before it run? In general, it's impossible. You should provide more information about what code failed and what's the same of them. For example, indirectly require (e.g. `require('a' + 'b')`) won't be bundled correctly because esbuild can not analyze this expression.

**Comment by olup** [comment]
Not really, I am asking if esbuild will or can warn when esbuild cannot analyze an expression, or could warn when the resolving tree ends up in places it can't bundle. So it may be not possible, but it has nothing to do with the general impossibility of knowing if code will simply fail before running. Do you bundle backend code ? If so you know that libraries that have a native side (like bcrypt or UUID) needs to be set as external as part of their requires is not only JavaScript and thus cannot be bundled.

**Comment by evanw** [comment]
There used to be a warning for this but I have removed the warning since people kept asking for it to be removed. It has been moved to a debug-level log so you will need to pass `--log-level=debug` to see it:

```
$ echo "require(x)" | esbuild --bundle --log-level=debug
 > <stdin>:1:0: debug: This call to "require" will not be bundled because the argument is not a string literal
    1 │ require(x)
      ╵ ~~~~~~~
```

**Comment by evanw** [comment]
With the [latest release](https://github.com/evanw/esbuild/releases/v0.14.42), there is now an additional way to do this. You can use `--log-override:unsupported-require-call=warning` to make this a warning (which will continue with the build), or `--log-override:unsupported-require-call=error` to make this an error (which will fail the build).
