### ISSUE TITLE
Option to disable the require shim

### ISSUE THREAD

**Issue by edoardocavazza** [evanw/esbuild#1653]
Hi! I am looking for an option to disable the new require shim, because it seems that there are esm module that use `typeof require === 'function'` to actually require an umd module. 

Example:
```
import 'module.umd.js';
import 'plugin.umd.js';

if (typeof require === 'function') {
  require('module.umd.js').use('plugin.umd.js');
}
```

I think this is a common way to fallback to commonjs when not running in a browser. In the example above, the plugin auto injects itself in the browser because it found the global library, while it needs to be injected in commonjs like environments.

But if you bundle this script externalizing the umd module, the code breaks at runtime :(

Thanks!

**Comment by evanw** [comment]
What code does this specifically? Does it have `"type": "module"` and/or use the `.mjs` file extension? I'm asking because I believe Webpack has behavior that actually does expose `require` to ESM code unless one of those things is true.

**Comment by evanw** [comment]
Closing due to lack of a reply.
