### ISSUE TITLE
the default `logLevel` for JS Api and CLI is not the same

### ISSUE THREAD

**Issue by talks2much** [evanw/esbuild#1659]
I think this should be either stated in the docs or be made the same.

https://github.com/esbuild/esbuild.github.io/blob/main/src/content/api.yml#L4176

This might not be easy to figure out why watch in JS API does output errors, but not successful build messages by default.

**Comment by evanw** [comment]
Thanks for pointing this out. Documentation has been updated: https://esbuild.github.io/api/#log-level. Closing.
