### ISSUE TITLE
Named default export statements result in non-working bundle with ReferenceErrors

### ISSUE THREAD

**Issue by jessewmc** [evanw/esbuild#166]
Importing something like this:
```
export default function test2(){...}
```
results in a non-working bundle with ReferenceErrors.
This (among others):
```
function test2(){...}
export default test2;
```
works as expected.

Default exports appear to be included in bundled output with a numbered constant along the lines of
```
function test2(){ ... }
const default2 = test2;
```
And all references to the `test2` function are replaced with `default2`.

In the case of named default export statements like
```
export default function test() {}
```
these `const defaultX` variable declarations are not included in the bundle, but references to `test` are still replaced with `defaultX` resulting in a non-working bundle with ReferenceErrors, like so:
```
    // export-named-default-class.js
    class Test {
      test() {
        console.log("export default class Test {");
      }
    }

    // export-named-default-fn.js
    function test2() {
      console.log("export default function test2()");
    }

    // index.js
    const test = new default2();
    test.test();
    default3();
```

It looks like this might be an unintentional mixing of behaviour between default exports which need a name defined, and named exports which already have one exposed.

Anonymous function and class exports work correctly, and so do `export {name as default}` and `export default expression`.

Hope this is clear, let me know if I can provide more detail.

Here's a quick repo to reproduce, tested on 0.4.3:
[https://github.com/jessewmc/esbuild-default-exports](https://github.com/jessewmc/esbuild-default-exports)

**Comment by evanw** [comment]
Thank you for reporting this. However, it doesn't appear to me like this was tested using esbuild 0.4.3. The file https://github.com/jessewmc/esbuild-default-exports/blob/master/index-built.js is using the old bundling strategy that was used before version 0.4.0. This is what I get if I install esbuild 0.4.3 and run `esbuild --bundle index.js --outfile=index-built.js`:

```js
(() => {
  // export-named-default-class.js
  class Test {
    test() {
      console.log("export default class Test {");
    }
  }

  // export-named-default-fn.js
  function test2() {
    console.log("export default function test2()");
  }

  // index.js
  const test = new Test();
  test.test();
  test2();
})();
```

That file runs fine without any ReferenceErrors.

**Comment by jessewmc** [comment]
That's odd. I just checked, npm is reporting 0.4.3.

I tried building locally off the head of master, and using that version I get the same result I reported above.

Is there something else that could be causing the discrepancy?

**Comment by jessewmc** [comment]
Sorry, my mistake, it looks like I cloned the repo earlier than I thought and it was out of date.

If I run with esbuild built from head of master, it seems to be working correctly.

The version on npm does not seem to be correct though.

**Comment by jessewmc** [comment]
Oddly, the version I installed on npm this morning was out of date. I removed and reinstalled and now the version on npm matches as well. Sorry for the confusion.
