### ISSUE TITLE
entry-names=[dir] always adds an implicit / at the end

### ISSUE THREAD

**Issue by danielbodart** [evanw/esbuild#1661]
I have a folder structure like:

`src/app1/main.ts`
`src/app2/main.ts`

and I want the result to be:

`dist/app1.js`
`dist/app2.js`

I tried to do this with the following command:
`esbuild src/**/main.ts --outdir=dist --entry-names=[dir] --bundle`

But you end up with this instead:

`dist/app1/.js`
`dist/app2/.js`

This feels unintended as a lot of the examples in the docs say `--entry-names=[dir]/[name]` but this would produce a `//` if done literally.

**Comment by evanw** [comment]
Yes, that's true. Right now `[dir]` is treated as a directory. IIRC I did this because there was some problem with doing it the other way. But unfortunately I forget what that problem was at the moment and don't have time to look into it right now. I'll have to investigate.

**Comment by danielbodart** [comment]
Awesome thank you!
