### ISSUE TITLE
Importing a .d.ts file without the .d breaks

### ISSUE THREAD

**Issue by ghostdevv** [evanw/esbuild#1663]
If I have `X.d.ts` in my project, typescript is ok with me doing:

```js
import {} from './X'
```

But esbuild fails with a unable to resolve error, while I personally try and do `X.d` as it makes sense, typescript and Visual Studio Code does it without the `.d` on the end so I feel as if esbuild should be able too if possible

**Comment by hyrious** [comment]
`tsc` doesn't do bundle, it just do type checking and transform each non-`d.ts`-file to js.

For a bundler like esbuild, it has to _link_ files into one, but a `d.ts` file actually does not contribute any js code.
If you only use types from that file, use `import type {} from "./X"`.\
  Read more about that in the docs: https://esbuild.github.io/content-types/#typescript-caveats

**Comment by hyrious** [comment]
`tsc` doesn't do bundle, it just do type checking and transform each non-`d.ts`-file to js.

For a bundler like esbuild, it has to _link_ files into one, but a `d.ts` file actually does not contribute any js code.
If you only use types from that file, use `import type {} from "./X"`.\
  Read more about that in the docs: https://esbuild.github.io/content-types/#typescript-caveats

**Comment by ghostdevv** [comment]
This makes sense thank you, but I believe the issue might still apply? In my particular case I was using a enum from the file which I believe isn't able to be imported with `import type`. But you can export a enum from a `.d.ts` and typescript is fine with it if you don't include the `.d` in your import but esbuild fails

**Comment by ghostdevv** [comment]
@evanw esbuild supports enums? because they are also runtime objects - but it doesn't assume that a ts import for a dts doesn't have to have the `.d` on the end (both `./x` and `./x.d` are valid) - isn't that in scope?
