### ISSUE TITLE
js-cookie export not detected

### ISSUE THREAD

**Issue by Minnozz** [evanw/esbuild#1668]
[js-cookie](https://github.com/js-cookie/js-cookie) starts with the following code:
```js
/*! js-cookie v3.0.1 | MIT */
;
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
  typeof define === 'function' && define.amd ? define(factory) :
  (global = global || self, (function () {
    var current = global.Cookies;
    var exports = global.Cookies = factory();
    exports.noConflict = function () { global.Cookies = current; return exports; };
  }()));
}(this, (function () { 'use strict';
```

When I try to create bindings in ReScript, the following code is generated:
```js
// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsCookie from "js-cookie";
//(...)
JsCookie.Cookies.get("cookie-name")
```

This causes the following esbuild warning:
```
 > <path:file:line>: warning: Import "Cookies" will always be undefined because there is no matching export
    9 │   return JsCookie.Cookies.get("cookie-name");
      ╵                   ~~~~~~~
```

Is this because of something I do wrong, or js-cookie does wrong, or esbuild?

**Comment by Minnozz** [comment]
Thanks, that indeed fixes the problem. However, the code that you quoted is generated by the ReScript compiler, so I can't edit it directly.

ReScript always uses this import style (`import * as Foo from ...`) and it works for other libraries, so is there a weird interaction here? Because if I understand correctly, that syntax should be valid: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#syntax

**Comment by hyrious** [comment]
Well then you may have to write this:
```js
import * as JsCookie from "js-cookie"; // generated

const Cookies = JsCookie.default; // your code
```
