### ISSUE TITLE
incremental builds: rebuild() metafile does not include newly created files

### ISSUE THREAD

**Issue by millsp** [evanw/esbuild#1670]
I'm currently experimenting with incremental builds and the `rebuild` method.

It seems like `rebuild` does not update the files described in the `Metafile` object. If a file is added, or deleted between two rebuilds (and was imported in an already-known file (eg. `index.ts`)), that is not included in the resulting `rebuild()` metafile.

This feels like a bug when I read:

> The information shows which input files ended up in each output file

In my case, if I delete such a file esbuild fails by telling that the file that I just deleted does not exist:
```
error: Could not resolve "./src/get-generators/utils/check-feature-flags/test2.ts"
```

Similarly, if I add a file between two rebuilds, then it also does not appear in the `metafile.inputs` after the rebuild. That file is properly imported by a previously-known file, it's not just an isolated file.

**Comment by millsp** [comment]
This happens on custom rebuilds as well as when we provide the `watch` option.

**Comment by millsp** [comment]
@evanw thoughts? Am I doing something wrong? And would you need a repro?

**Comment by evanw** [comment]
Closing due to lack of a reply.
