### ISSUE TITLE
Wrong grouping in optional chaining with --loader=ts

### ISSUE THREAD

**Issue by AngusFu** [evanw/esbuild#168]
I get some code like

```ts
declare var el: HTMLElement | undefined;
const div = el?.querySelector<HTMLDivElement>('div');
const div2 = el?.querySelector('div');
```

which would be transformed  to the following code by `esbuild@0.4.3`:

```js
const div = (el == null ? void 0 : el.querySelector)("div");
const div2 = el == null ? void 0 : el.querySelector("div");
```

The script is 

```shell
echo -e "
  declare var el: HTMLElement | undefined;
  const div = el?.querySelector<HTMLDivElement>('div');
  const div2 = el?.querySelector('div');
" | npx esbuild --target=es2019 --loader=ts
```
> Note: the target `es2019`  can be changed to any one in `es2015 es2016 es2017 es2018 es2019 es2020`

![image](https://user-images.githubusercontent.com/8180186/83598618-c366d900-a59c-11ea-954e-3d994de837f5.png)

However, the first statement `const div = (el == null ? void 0 : el.querySelector)("div")` would cause a `Illegal invocation` error in browsers.

Seems that the result is not consistent with the [proposal](https://github.com/tc39/proposal-optional-chaining), since there is NO **grouping** in `el?.querySelector<HTMLDivElement>('div')`).

Then I paste the same inputs to  [TypeScript Playground](https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=6&pc=1#code/CYUwxgNghgTiAEA3W8QQFzwBIBUCyAMgKIQgC2IAdgC7wA+8ArpaAGYCWlIwA3ALAAoQWAD2lAM61g7RPAC8qCAH4AdAEdGIGAE8AymnDURMADy5CAERklyVagD4AFAHJpiZwEp+QgaIlSZACZ5RVUNLT0DMCMYFzdPbyA), the result seems to be correct: 

![image](https://user-images.githubusercontent.com/8180186/83599513-f4480d80-a59e-11ea-9e66-38f3a38e34b8.png)

> Note: the target `es2019`  can be changed to any one in `es2015 es2016 es2017 es2018 es2019 es2020`
![image](https://user-images.githubusercontent.com/8180186/83599557-12157280-a59f-11ea-8292-eaff8eaf6e26.png)

**Comment by evanw** [comment]
Thanks for reporting this. This was an unintentional regression due to the work for #156. I will fix this soon.
