### ISSUE TITLE
How to import jquery ($) and use it from other files ?

### ISSUE THREAD

**Issue by leoplct** [evanw/esbuild#1681]
I want to include jquery in my app/javascripts/application.js

```
import $ from 'jquery';
import './utility/direct_upload'
import './utility/custom'
import './utility/modals'
import './utility/init'
```

and use it from other file such as ./utility/custom.js etc..

**./utility/custom.js**

```
$("[data-toggle='dropdown']").dropdown();
$('[data-toggle="popover"]').popover({container: 'body'})
$('[data-toggle="tooltip"]').tooltip()
```

How can I do? Instead of re-imported in every file I use the $ var.

**/esbuild.config.js**
```
const path = require('path')
const rails = require('esbuild-rails')

require("esbuild").build({
  entryPoints: ["application.js"],
  bundle: true,
  outdir: path.join(process.cwd(), "app/assets/builds"),
  absWorkingDir: path.join(process.cwd(), "app/javascript"),
  watch: process.argv.includes("--watch"),
  plugins: [rails()],
}).catch(() => process.exit(1))
```

**package.json**
```
  "scripts": {
    "build": "node esbuild.config.js"
  }
```

**Comment by leoplct** [comment]
Try this but I got  _ReferenceError: $ is not defined_

app/javascripts/application.js
```
import $ from 'jquery';
window.$ = $
import './utility/init'
```

**./utility/init.js**
```
$(document).on('ready', function(){
    console.log("ok")
})



```

**Comment by hyrious** [comment]
> I am not running before, import './utility/init' is the last line.

Yeah it is at the last line, but it will be run at the top. You can try that in your  node.js:

```js
// a.mjs
console.log('a')
import './b.mjs'

// b.mjs
console.log('b')
```

It will output:

```
b
a
```

esbuild follows this behavior of node.js, so that's what happens.

**Comment by leoplct** [comment]
Tried, still same error. The strange thing is that _console.log('before')_ is not printed in dev console.

**application.js**
```
import $ from 'jquery';
console.log('before') <-- This is not printed in console
import './utility/init'
window.$ = $
```

**/utility/init.js**

```
console.log('init') <-- This is printed correctly in console
$(document).on('ready', function(){
    console.log("ok")
})
```

**Comment by kktos** [comment]
you didn't pay enough attention to the answer given.
there are 2 imports. Two.

one without any parenthesis.
`import something from somefile;`

one with parenthesis.
`import(somefile);`

this is why hyrious told you to solve your order problem to use import() WITH parenthesis for the second import
```
import $ from 'jquery'
window.$ = $
import('./utility/init') // it is guaranteed to be run after codes above.
```

**Comment by leoplct** [comment]
I've added this

**/esbuild.config.js**

```
const path = require('path')
const rails = require('esbuild-rails')

require("esbuild").build({
  entryPoints: ["application.js"],
  bundle: true,
  outdir: path.join(process.cwd(), "app/assets/builds"),
  absWorkingDir: path.join(process.cwd(), "app/javascript"),
  watch: process.argv.includes("--watch"),
  inject: ["inject-jquery.js"], <-----   ADDED HERE
  plugins: [rails()],
}).catch(() => process.exit(1))
```

**app/javascripts/inject-jquery.js**
`export { default as $ } from 'jquery'`

**app/javascripts/custom/init.js**
```
$(document).on("turbo:load ajax:success cable-ready:after-morph", function() { // 
    console.log("Loaded")
    $("[data-toggle='dropdown']").dropdown();
...
})
```
**app/javascripts/application.js**
```
...
import './custom/init'
```


but now I got this error in **dev console**

`Uncaught TypeError: (0 , import_jquery.default)(...).dropdown is not a function`
```
// custom/init.js
  init_jquery();
  var import_vanilla_lazyload = __toModule(require_lazyload_min());
  (0, import_jquery.default)(document).on("turbo:load ajax:success cable-ready:after-morph", function() {
    console.log("Loaded");
    (0, import_jquery.default)("[data-toggle='dropdown']").dropdown();

```

**Comment by evanw** [comment]
I'm not familiar with jQuery but `.dropdown()` doesn't appear to be part of jQuery's API: https://api.jquery.com/. I assume that means your code is providing `.dropdown()` with a plugin. In that case, it likely expects to find jQuery on the window. You could try changing your injected shim to something like this:

```js
import $ from 'jquery'
window.jQuery = window.$ = $
export { $ }
```

**Comment by leoplct** [comment]
Solved. I had to to this. I think it makes sense to add it to documentation.

```
import('popper.js/dist/popper.js')
import('bootstrap')
import('datatables.net')
import dataTable from 'datatables.net-bs4'
dataTable(window, $)
```

https://gist.github.com/bodrick/75ba7fe4d12aa3153883ae2cb866b46e

**Comment by Font-awesome-4** [comment]
@kktos https://jqcode.space/questions/guide-on-moving-an-item-from-one-form-and-including-it-as-an-option-in-a-dropdown-menu-in-another-form-using
