### ISSUE TITLE
Running postbuild script using `watch` in the JavaScript API

### ISSUE THREAD

**Issue by banagale** [evanw/esbuild#1688]
I'm able to get the build behavior I want with the `package.json` scripts section looking like this:

```
  "scripts": {
    "build": "esbuild ./briefings/frontend/src/briefings.ts --bundle --target=es2017 --minify --outfile=./briefings/frontend/build/briefings-fe.js --analyze",
    "postbuild": "./postbuild.sh"
  }
```

When I run `yarn run build`, esbuild bundles and outputs the file where I want. Yarn also runs the `postbuild` script, `postbuild.sh` which is a bash script that moves this file into place and does a few other things.

I'm trying to make esbuild run my postbuild each time it builds while in watch mode.

I have a working watch CLI command that looks like this:

`esbuild ./briefings/frontend/src/briefings.ts --bundle --target=es2017 --minify --outfile=./briefings/frontend/build/briefings-fe.js --analyze --watch`

This is basically the `build` line from above with the `--watch` flag, and it works well. If I edit any dependency of `briefings.ts` the watch rebuilds.

However, if I understand correctly, there's no way to perform any additional actions after each watch-triggered change using the CLI.

So I am trying to use the javascript API example, with 

`build.js`
```
require('esbuild').build({
  entryPoints: ['./briefings/frontend/src/briefings.ts'],
  outfile: './briefings/frontend/build/briefings-fe.js',
  bundle: true,
  minify: true,
  target: 'es2017',
  watch: {
    onRebuild(error, result) {
      console.log('rebuilding');
      if (error) console.error('watch build failed:', error);
      else console.log('watch build succeeded:', result);
    },
  },
}).then(result => {
  // Call "stop" on the result when you're done
  console.log('All done!');
  result.stop();
});

```

When I run this using `node build.js` it does the initial build but then exits, outputting "All done!"

I'm expecting this to run persistently, just like the watch in the CLI. Am I not executing `build.js` correctly? I'm new to node.

Once I have that, where is the best place to add a call to my `postbuild.sh` bash script? At the end of `onRebuild`?

**Comment by banagale** [comment]
Thank you for having a look, @evanw.

I misunderstood the intent of that sample code in the context of that section.

I have some minor docs changes that might make this clearer. I'd make edits to the [Build Scripts](https://esbuild.github.io/getting-started/#build-scripts) section and the [Watch section](https://esbuild.github.io/api/#target).

Do you take PRs for docs updates? I did not see the repo for `esbuild.github.io` 

Separate from the above, is there a way to get the output generated by the `--analyze` CLI flag via the JS API? 

I guessed at adding `analyze: 'verbose'` to `require('esbuild').build()` and saw that is not the way.

The default analysis and formatting provided by the CLI's `--watch` would be nice to optionally show during watch-triggered reloads.

----

In case someone else happens upon this issue and wants something similar:

Here's [a gist of the js api watch script implementation](https://gist.github.com/banagale/dbad61a74b654b8c77dd69f1d8a0482d) of what I was after. 

It offers some output flourishes to build upon:

<img width="745" alt="image" src="https://user-images.githubusercontent.com/1409710/137615547-7e1cc555-9e88-4129-92a5-09677a425f39.png">

**Comment by evanw** [comment]
> Separate from the above, is there a way to get the output generated by the `--analyze` CLI flag via the JS API?

Yes. See the documentation for details: https://esbuild.github.io/api/#analyze. You can see how to use the API from the CLI, from JS, and from Go by clicking on the "CLI | JS | Go" buttons next to each code example.

> Do you take PRs for docs updates? I did not see the repo for `esbuild.github.io`

The repo is here: https://github.com/esbuild/esbuild.github.io. In case you're curious: the content of any `https://example.github.io` page can be found at `https://github.com/example/example.github.io`, as documented here: https://docs.github.com/en/pages/getting-started-with-github-pages/about-github-pages#types-of-github-pages-sites.

I take some PRs but generally prefer to document things myself, so keep in mind I may end up editing/rewriting submitted content myself. I just tried making a small change to the documentation about `stop()` to be more specific. Hopefully that helps.

**Comment by banagale** [comment]
Been a minute but I was able to review [changes related](https://github.com/esbuild/esbuild.github.io/commit/50cd4f83f475fd2be83b56a16a0aee17e9fb1fcb) to this.

Looks more approachable and helpful. My only feedback would be to succinctly clarify the most common or likely reasons one might want to "to stop watch mode at some point in the future."
