### ISSUE TITLE
Invalid conversion from typescript to js in Express library

### ISSUE THREAD

**Issue by akiosTerr** [evanw/esbuild#169]
### I am trying to make a minified build from typescript to js

here is the build code:
```javascript
import { build } from 'esbuild';

build({
	stdio: 'inherit',
	entryPoints: ['./src/index.ts'],
	outfile: './dist/index.js',
	platform: 'node',
	minify: true,
	bundle: true,
}).catch(() => process.exit(1));
``` 
the command gives a error from **express** lib
error: 
```
node_modules\express\lib\view.js:81:21: error: The argument to require() must be a string literal
    var fn = require(mod).__express
```
PS: when I use "browser" as a platform, it gives lots of errors telling that "Could not resolve" multiple inbuilt libraries like "HTTP","PATH" and "FS".

I also tried the CLI command:
```
esbuild --bundle --minify --loader=ts --platform=node <src/index.ts> dist/index.js
```
it gives the same error

the same code works normally with sucrase-node and TSC.
the source code (typescript) I am trying to bundle:
```javascript
import express from 'express';

const app = express();
const port = 3333;
let a: number;

app.use(express.json());

app.get('/', (req, res) => {
	res.json({
		SYNC: 'life',
	});
});

app.listen(port, () => {
	a = 10;
	console.log(a);

	console.log('====================================');
	console.log(`Server Running on port ${port}`);
	console.log('====================================');
});

```

**Comment by evanw** [comment]
You likely don't need to bundle in the express library itself, since you're running this with node. Your example should work fine if you exclude express from the bundle with `--external:express`. Does that solve your issue?

**Comment by akiosTerr** [comment]
@evanw it does, thank you. 

well actually now that I am thinking its not actually necessary to minify node.js code
or even bundle it, but correct me if I am wrong.
