### ISSUE TITLE
Proposal : allow to use an 'io/fs.FS' as an input file system

### ISSUE THREAD

**Issue by LeGEC** [evanw/esbuild#1704]
When calling esbuild from the API, it would be a nice addition to be able to load code from something else than an actual mounted file system.

Two example usage :

* have the content of `node_modules/` read from a single `.zip` or `.tar.gz` archive, rather than from actual files on disk
* run `esbuild` on a server, from buffers in RAM presented as a `fs.FS`

**Comment by progrium** [comment]
Do you have any idea how obnoxious it is to have this in Go and not follow Go idioms and interfaces?

**Comment by LeGEC** [comment]
@progrium : hi there

Although I do see something that looks like sympathy towards the suggestion I made, I must say I'm not very fond of the tone in which you "promote" that suggestion.

Perhaps you could reword your sentence, either by saying you would like to see this implemented (for that, a simple "+1" on the original message is already an indication), or by giving your own example of how this would serve your purposes ?

Cheers

**Comment by progrium** [comment]
It was my intention to communicate my extreme frustration with the general decision to de-prioritize making the Go code of this project more useful to the Go ecosystem. It was with more restraint than you think.
