### ISSUE TITLE
ESBuild package breaks on Angular when optimization is on

### ISSUE THREAD

**Issue by Khachatour** [evanw/esbuild#1710]
Hey there folks!

I know it might not be the best place to fire an issue. We are shipping an NPM package that is bundled with ESBuild. One of our customers filed an issue when they are bundling with optimization there is an error. and when they bundle without optimization it seems everything is working. 

I have stumbled upon https://github.com/angular/angular-cli/issues/21654 
Where you folks fix it and suggest upgrading to `0.12.24` our version is `0.12.25` and with the NPM package that is bundled with `0.12.25` issue still persists. 

Additional information:
The error is `g is not defined`
The error happens for this call: pe=g("brushTool","config")

When comparing this to the actual code from the NPM package in node modules I can see that the actual line is "QX=ie("brushTool","config")".

And apparently, the "ie" function gets defined with a different name after the Angular optimization.

Thanks!

**Comment by evanw** [comment]
Closing due to age and lack of information.
