### ISSUE TITLE
[Question]: Is there support for file based entryNames?

### ISSUE THREAD

**Issue by ctrl-wstrueber** [evanw/esbuild#1713]
Hello, I am trying to figure out if there is a way to specify `entryNames` based on the file extension.
I would like to bundle files like:

**js:**
`static/js/[name]-[hash]`

 **css:**
`static/css/[name]-[hash]`

Is there a way to set `entryNames` as `static/[ext]/[name]-[hash]` or could this be achieved in a plugin?

Thanks for any feedback

**Comment by markskayff** [comment]
I'm facing the same issue. 
It's a rather simple request, I mean at least in what we want to accomplish.
We want to have our bundled .js under let's say a **public/js** 
and the resulting bundled css's under say **public/css**

The same goes for assets, more specifically for "file" loaded assets. These end up all below the **outdir**. But what if we want them somewhere else?

I have the bundle outputting to **public/js/** but want my assets into **public/assets/**
If in the config I do: assetNames: "../assets/<blah>" ... then the bundler routes these assets with "..assets ..." in the source name and things break. And publicPath doesn't seem to help here.

**Comment by evanw** [comment]
> Is there a way to set `entryNames` as `static/[ext]/[name]-[hash]` or could this be achieved in a plugin?

This has already been implemented in [version 0.14.2](https://github.com/evanw/esbuild/releases/tag/v0.14.2), which was released late last year. See also #1799. Closing this issue as "fixed."
