### ISSUE TITLE
Any chance to make building failed when comes across a specific warning?

### ISSUE THREAD

**Issue by WendellLiu** [evanw/esbuild#1721]
We got a case-insensitive issue on CI env. However, some of our env is deployed on MacOS which is case-insensitive file system. I find there is a warning [logging here](https://github.com/evanw/esbuild/blob/master/internal/bundler/bundler.go#L764). 

Could we make the building failed when we got a warning(it is even better if we can pick the warning for this feature)

**Comment by evanw** [comment]
With the [latest release](https://github.com/evanw/esbuild/releases/v0.14.42), there is now an easier way. You can now use `--log-override:different-path-case=error` to do this.
