### ISSUE TITLE
Error when attempting to use source map

### ISSUE THREAD

**Issue by danny519** [evanw/esbuild#1724]
When I try to view the source map for a file inside a library (@ material) then I get this error: `Could not load content for http://localhost:3000/node_modules/@material/animation/util.ts (HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE)`

Here is my esbuild config:
```js
 bundle: true,
    outdir: dist,
    sourcemap: true,
    outbase: assetsFolder,
    absWorkingDir: assetsFolder

```

**Comment by danny519** [comment]
Hmm I would assume esbuild would create source maps for it?

**Comment by clawoflight** [comment]
How do you think it should? It doesn't know how the source code looked. esbuild is not a decompiler :)
