### ISSUE TITLE
Re-`define` variables during watch mode

### ISSUE THREAD

**Issue by qpwo** [evanw/esbuild#1725]
I want to give some client/browser javascript the build time and current git branch. Sometimes I leave watch mode running a long time while I change branches and so on. Is there any way to update 'define' variables in watch mode?

**Comment by qpwo** [comment]
The fresh build does seem a bit slower than the reload build so would still be nice if i could update substitutions in reload one day. Works pretty darn well as is though.

**Comment by evanw** [comment]
If esbuild implemented it natively, it would just be doing the exact same thing. The result of using the `define` setting is baked into the cached ASTs for speed so if that is changed, esbuild would have to start over anyway and it wouldn't be any faster.
