### ISSUE TITLE
Specify loader inside import URL

### ISSUE THREAD

**Issue by fregante** [evanw/esbuild#1727]
Webpack lets you specify its loaders inline: https://webpack.js.org/concepts/loaders/#inline

Via config you can also specify a [custom URL parameter](https://webpack.js.org/configuration/module/#ruleresourcequery) to change the load type, e.g.:

```js
import x from './file.css?inline' // webpack with custom config

const style = document.createElement('style')
style.src = x
document.head.append(style)
```

I know this is somewhat possible via extension in esbuild:

```sh
esbuild --bundle source.js --loader:.css=dataurl
```

but that appears to only work per file extension, so it's _every css file or nothing._ Sometimes I want to bundle the CSS, sometimes I'd like to use its URL, in the same codebase.

Probably esbuild could support:

```js
import x from 'dataurl:./file.css' // wish

const style = document.createElement('style')
style.src = x
document.head.append(style)
```

**Comment by evanw** [comment]
Closing as out of scope. This can be added with plugins as described above (thanks for posting that comment).

**Comment by mhsdesign** [comment]
As simple solution i added `.dataurl` in the file like `import dummyImage from './resource/dummy-image.dataurl.svg';`  and adjusted my loaders:

```js
loader: {
        '.dataurl.svg': 'dataurl',
        '.svg': 'text',
}
```

But that has the flaw obviously that you would have to duplicate your sources if you need them in one place as data url and another time as text ... or if you cannot control the file name.
