### ISSUE TITLE
I lost some css rules when I use rem and vw in the same time

### ISSUE THREAD

**Issue by ben-lau** [evanw/esbuild#1732]
### Bug description

my css stylesheet has some `rem` and `vw` in the same time by using postcss plugin, then I found some property will lost the `rem` rule but kept the `vw` rule.
![image](https://user-images.githubusercontent.com/16952163/139418168-5b39a87e-ac97-488f-8abf-06fe87b307a5.png)

### Reproduction

part of my webpack config:
```javascript
{
  optimization: {
    minimize: true,
    splitChunks: {
      cacheGroups: {
        defaultVendors: {
          name: 'vendors',
          test: {},
          priority: -10,
          chunks: 'initial',
          reuseExistingChunk: true,
        },
        default: {
          minChunks: 2,
          priority: -20,
          chunks: 'initial',
          reuseExistingChunk: true,
        },
      },
    },
    minimizer: [
      new ESBuildMinifyPlugin({
        css: true,
      }),
    ],
  },
  module: {
    rules: [
      {
        test: /.css$/,
        use: [
          {
            loader: MiniCssExtractPlugin.loader,
            options: { publicPath: '../' },
          },
          {
            loader: 'css-loader',
            options: { importLoaders: 2, sourceMap: false },
          },
          {
            loader: 'esbuild-loader',
            options: { loader: 'css', minify: true },
          },
          {
            loader: 'postcss-loader',
            options: {
              sourceMap: false,
              postcssOptions: { plugins: ['postcss-pixel-to-remvw'] },
            },
          },
        ],
      },
    ],
  },
  plugins: [
    new MiniCssExtractPlugin({
      filename: 'css/[name].[contenthash:8].css',
      chunkFilename: 'css/[name].chunk.[contenthash:8].css',
    }),
  ],
};

```

### Node.js package manager

npm

### Environment

```shell
System:
    OS: macOS 11.5.1
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
    Memory: 989.15 MB / 8.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.17.6 - /usr/local/bin/node
    Yarn: 1.22.15 - /usr/local/bin/yarn
    npm: 6.14.15 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  npmPackages:
    esbuild: ^0.13.4 => 0.13.12 
    esbuild-loader: ^2.16.0 => 2.16.0 
    webpack: ^5.58.1 => 5.60.0
```
### From
https://github.com/privatenumber/esbuild-loader/issues/217

**Comment by ben-lau** [comment]
https://github.com/privatenumber/esbuild-loader/issues/217

**Comment by evanw** [comment]
Just so I understand fully: what is the problem with doing this? According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/length#browser_compatibility), both `rem` and `vw` have been supported for a very long time. For example, the earliest version of Chrome that supports both is Chrome 20, which was released in 2012. And both `rem` and `vw` are supported in IE starting with version 9, so this transformation shouldn't affect IE. Which browser(s) do you need to support that are problematic with this transformation?

**Comment by ben-lau** [comment]
> Just so I understand fully: what is the problem with doing this? According to [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/length#browser_compatibility), both `rem` and `vw` have been supported for a very long time. For example, the earliest version of Chrome that supports both is Chrome 20, which was released in 2012. And both `rem` and `vw` are supported in IE starting with version 9, so this transformation shouldn't affect IE. Which browser(s) do you need to support that are problematic with this transformation?

emm..., it's hard tot explain why I need both rem and vw in my stylesheet, but there is indeed a problem here, What's even stranger is some properties are normal, I just dont want to lost any style rules by using esbuild. Can you fix this issue?

**Comment by evanw** [comment]
Well you can just tell esbuild to not minify syntax if you don't want esbuild to change the CSS syntax. Instead of `minify: true`, which applies all minification transforms, you can just use `minifyWhitespace: true` to only minify whitespace.

> it's hard tot explain why I need both rem and vw in my stylesheet

I would need to know the full reason to determine if this is something that should be fixed by esbuild and, if so, what the correct fix should be.

**Comment by ben-lau** [comment]
In short, my product have to be compatible with Android 4, which is not support vw, but rem will be a downgrade plan, so my stylesheet will both exist rem and vw in the same time.
What I am curious about is why the rule loss only appears in some attributes, I think it’s either all lost or all saved will be right.

**Comment by ben-lau** [comment]
@evanw is it be solved?

**Comment by evanw** [comment]
Yes, it should be.
