### ISSUE TITLE
lch color notation is not converted

### ISSUE THREAD

**Issue by jameshfisher** [evanw/esbuild#1735]
[The docs](https://esbuild.github.io/content-types/#css) say

> Note that by default, esbuild's output will take advantage of all modern CSS features. For example, `color: rgba(255, 0, 0, 0.4)` will become `color: #f006` when minifying is enabled which makes use of syntax from CSS Color Module Level 4. 

This works with, say, `hsl()`:
```
$ echo "div { color: hsl(50,50%,50%); }" | npx esbuild --minify --loader=css
div{color:#bfaa40}
```

But it does not work with `lch()`:

```
$ echo "div { color: lch(29.2345% 44.2 27); }" | npx esbuild --minify --loader=css
div{color:lch(29.2345% 44.2 27)}
```

Setting the `target` doesn't seem to make any difference; it's always just passed through unmodified. Am I doing something wrong? Or does esbuild not support this notation?

**Comment by jameshfisher** [comment]
(Note: `lch()`, and a bunch of other color spaces, seem to be part of [CSS Color Module Level 4](https://drafts.csswg.org/css-color-4/#color-syntax))

**Comment by jameshfisher** [comment]
I'm guessing from https://github.com/evanw/esbuild/blob/b32360dc4f00f1a509641aadf41638481c60cdc7/internal/css_parser/css_decls_color.go#L325 that the answer is "Only `rgb, `rgba`, `hsl`, and `hsla` are supported"?

**Comment by evanw** [comment]
> Only `rgb`, `rgba`, `hsl`, and `hsla` are supported

Yes, that's correct. The `lch()` syntax is not supported. However, even if `lch()` was supported by esbuild, I'm not sure what esbuild would be able to do with it beside just passing it through unmodified. CIELAB uses a wider gamut than sRGB so converting `lch()` to hexadecimal would lose information, and would be an incorrect transformation to perform. Minification only applies shortening substitutions when it is safe to do so.

**Comment by evanw** [comment]
I'm going to close this because I think what esbuild is doing here is correct. CIELAB should not be converted to sRGB because they are different color spaces.
