### ISSUE TITLE
.nmprc and .yarnrc not work when install 

### ISSUE THREAD

**Issue by hellojukay** [evanw/esbuild#1738]
https://github.com/evanw/esbuild/blob/master/lib/npm/node-install.ts#L84

install script chdir to tmp dir and run npm command , so npm command will not use .npmrc in project root dir, so yarn --registry and npm --registry and .npmrc not work for install esbuild package in ci pipeline.

![image](https://user-images.githubusercontent.com/10371891/140034688-ecc11232-de6c-4dfe-9690-9722be5e713d.png)

**Comment by evanw** [comment]
The version you are using is from last July. Use a new version of esbuild instead: `npm i esbuild@0.13.12`. The problem you are mentioning was fixed in September.

Closing as this has already been fixed.

**Comment by Lonli-Lokli** [comment]
@evanw Seems like it's again an issue with the 0.17.19 - in case of enterprise system direct internet access is not allowed and package cannot be installed
