### ISSUE TITLE
Variable named 'exports' is removed which breaks the bundle

### ISSUE THREAD

**Issue by JRoseDev** [evanw/esbuild#1739]
We depend on the [adal-node](https://www.npmjs.com/package/adal-node) package which contains a module that ends with:

```js
// stuff...

var exports = {
  AuthenticationContext : AuthenticationContext,
  setGlobalADALOptions : function(options) {
    globalADALOptions = options;
  },
  getGlobalADALOptions : function() {
    return globalADALOptions;
  }
};

util.adalInit();
module.exports = exports;
```

When we bundle with esbuild the corresponding output is:

```js
	// stuff...

    util.adalInit();
    module2.exports = exports2;
  }
});
```

Which leaves `exports2` and `module2.exports` undefined and means accessing `AuthenticationContext` fails.

[This repo](https://github.com/BenedictHawthorn/esbuild-bug) has a minimal repro. We built `out.js` with `.\node_modules\.bin\esbuild index.js --bundle --outfile=out.js --platform=node`

It seems odd to have a variable named `exports` but we don't have any control over adal-node, is this a bug or is there any way of working around this in esbuild?

**Comment by hyrious** [comment]
Workaround: `--tree-shaking=false`.

**Comment by JRoseDev** [comment]
Thanks for the quick fix, and a workaround too, much appreciated! 🎉
