### ISSUE TITLE
Dependencies licenses bundling ?

### ISSUE THREAD

**Issue by aleks-ivanov** [evanw/esbuild#1740]
Is there a way/plugin for `esbuild` to generate a licenses compilation text file, when bundling a Javascript app ?

**Comment by evanw** [comment]
Documentation is here: https://esbuild.github.io/api/#legal-comments

**Comment by aleks-ivanov** [comment]
Yes and as I understand `legal comments` refer to comments inside the source code only and not licenses in a separate file. Correct ?

**Comment by evanw** [comment]
Yes, the license has to be in the source code. So a comment like `// @license MIT` will work.

If you want to do something different yourself, I recommend using the [metafile](https://esbuild.github.io/api/#metafile), which tells you which files were included in the bundle. Then you can do whatever you like with that information (e.g. looking in each package for `LICENSE.md` files). This can be done either as an esbuild plugin or just after calling `build()`.
