### ISSUE TITLE
Support input sourcemaps

### ISSUE THREAD

**Issue by rixtox** [evanw/esbuild#1742]
As I understand, esbuild doesn't plan to support any customiized AST transformation use cases because of keeing the speed optimization of the tool.

Then the alternative would be apply the custom AST transformation using some other tools, then use esbuild just for bundling.

In that case, the input to esbuild would include the sourcemaps generated from the previous tool, and esbuild need to support that and generate final sourcemaps that map to the original code.

This specific feature has been implemented for rollup by the [rollup-plugin-sourcemaps](https://github.com/maxdavidson/rollup-plugin-sourcemaps) plugin.

**Comment by hyrious** [comment]
Just append `//# sourceMappingURL=` after the result from other tools. See the [svelte plugin](https://esbuild.github.io/plugins/#svelte-plugin) for example.
