### ISSUE TITLE
Does not shake unused class with static property

### ISSUE THREAD

**Issue by kurkle** [evanw/esbuild#175]
model.js
```js
export class Test {
    test() {
        console.log('test');
    }
}

Test.id = 'A';

export function foo() {
  console.log('foo');
}
```

index.js
```js
import {foo} from './model';
foo();
```

```bash
npx esbuild --bundle --format=esm --outfile=bundle.js index.js
```

expected:
```js
// model.js
function foo() {
  console.log('foo');
}

// index.js
foo();
```

actual:
```js
// model.js
class Test {
  test() {
    console.log("test");
  }
}
Test.id = "A";
function foo() {
  console.log("foo");
}

// index.js
foo();
```

**Comment by kurkle** [comment]
It does shake, if the property is defined inside the class:

```js
export class Test {
    static id = 'A';
    test() {
        console.log('test');
    }
}

export function foo() {
  console.log('foo');
}
```

**Comment by evanw** [comment]
Thanks for calling out this limitation. This is because esbuild's tree shaking is conservative for correctness and doesn't make the unsafe assumption that `Test` doesn't have a setter called `id` that could potentially cause side effects.

**Comment by kurkle** [comment]
Shouldn't it be possible to know if there is a setter defined? Or could there be an option for "aggressive" tree shaking.
I'm not at all familiar with the code base here, so just guessing.

**Comment by kurkle** [comment]
Not sure if it makes any difference, but terser did decide to shake these: https://github.com/terser/terser/issues/724
Also rollup is shaking those (and even `Test.prototype.id = 'A'` case)

**Comment by evanw** [comment]
Rollup has known tree shaking bugs where code is incorrectly removed that actually does have side effects. See https://github.com/rollup/rollup/issues/2219 for some cases where this happens.

Since JavaScript is a dynamic language, it's impossible even with static analysis to determine whether a statement like that has externally-visible side effects or not. As an example, the code in the original post will have side effects if this code is evaluated before it runs:

```js
Object.defineProperty(Object.prototype, 'id', {
  set() {
    console.log('important side effects');
  }
});
```

```js
class Test {
  test() {
    console.log("test");
  }
}
Test.id = "A";
```

Running these two code snippets should print `important side effects`. It would be a correctness bug if that code was removed due to tree shaking, since that would change the externally-visible side effects. I'd like for esbuild to not contain correctness bugs like this.

I could see potentially adding an opt-in "unsafe mode" that may cause otherwise-valid code to break if it makes use of setters like this. That way by default you can be sure that tree shaking is not going to break your code. This mode would be something to opt-in to only if you have very comprehensive test coverage or you have audited all code in your bundle to make sure it's not going to break any of the assumptions made by the unsafe mode (whatever those end up being).

**Comment by bathos** [comment]
@evanw I’m not sure if maybe you’re referencing TypeScript semantics here, which may differ, but as the relevant proposals stand right now, a static (or instance) property is initialized with [CreateDataPropertyOrThrow](https://tc39.es/ecma262/#sec-createdatapropertyorthrow), meaning that a setter in the example above would not be invoked — it’s a define-own-property op, not a set op.

See step 34.a. of [ClassDefinitionEvaluation](https://tc39.es/proposal-static-class-features/#runtime-semantics-class-definition-evaluation) as modified by the [static class features proposal](https://tc39.es/proposal-static-class-features) and step 9 of [DefineField](https://tc39.es/proposal-class-fields/#sec-define-field) as introduced by the [class fields proposal](https://github.com/tc39/proposal-class-fields).

As the name `CreateDataPropertyOrThrow` indicates, it’s may throw, and this is a side effect in its own right (as is the evaluation of the initializer expression potentially), so the conclusion is correct regardless, but illustrating why it can throw requires weirder shenanigans than inherited setters, e.g.:

```js
class Foo {
  static bar = (Object.freeze(Foo), true);
}
```

**Comment by kurkle** [comment]
If aiming for correctness, it should not shake anything, right?

```js
export class Test {
    test() {
        console.log('test');
    }
}

eval("Test.id = 'A'");

export function foo() {
  console.log('foo');
}
```

```js
import {foo} from './model';
foo();
```

results to
```js
// model.js
eval("Test.id = 'A'");
function foo() {
  console.log("foo");
}

// index.js
foo();
```

**Comment by fabiosantoscode** [comment]
@evanw I'm with you, in principle, regarding avoiding every possible side effect.

However, it's often safe to assume some things. For example, Terser now assumes that `a == null` is only true when `a` is null or undefined. You can't turn this off.

And if you're setting a property on a fresh object or class, it's also pretty safe to assume that's not going to have a side effect even though that's technically possible.

**Comment by evanw** [comment]
> If aiming for correctness, it should not shake anything, right?

I'm fixing the bug with direct `eval()` in the next release. Direct `eval()` will disable all tree shaking and wrap the module in a CommonJS closure.

**Comment by hardfist** [comment]
> > If aiming for correctness, it should not shake anything, right?
> 
> I'm fixing the bug with direct `eval()` in the next release. Direct `eval()` will disable all tree shaking and wrap the module in a CommonJS closure.

@evanw  It seems that direct `eval` still disable  treeshaking in latest version?

**Comment by marcofugaro** [comment]
Thanks @evanw for adressing this! 🙏

Does this work for the `Foo.prototype.bar = ...` as well? Libraries such as [three.js use this pattern](https://github.com/mrdoob/three.js/blob/d10d1be864f5e08c9d13dc098dd07af61c39de53/src/math/Vector3.js#L740).

Currently it's the only thing preventing three.js from being tree-shaken by esbuild, it would be great if this was looked into.

**Comment by evanw** [comment]
No that’s something completely different. This change doesn’t do that. Doing that is very different, and also complicated. It requires object shape tracking which is a partial evaluation technique that esbuild doesn’t do.

**Comment by tank0317** [comment]
@evanw Static property shaking is still not working in typescript，is there any plan to support it ?
