### ISSUE TITLE
[bug] define plugin replaced as a variable rather than string

### ISSUE THREAD

**Issue by Jareechang** [evanw/esbuild#1751]
Hey there,

First of all, really enjoy using esbuild. It has been great, thanks for all your work.

## Summary

I am not sure if this is intended or not but I ran into an issue when using the `define` option. It might even be the documentation is outdated (happy to update if that is the case). 

Full example can be found here - https://github.com/Jareechang/esbuild-examples/tree/master/examples/tree-shaking-env

Basically, using the following build configuration yields two different results: 

### Option 1: What is shown on the documentation 
**Source:**
```ts
import * as utils from './utils';

console.log(utils.add(2, 3));

(process.env.NODE_ENV !== 'production') && console.log(utils.subtract(6, 3));
```
**config:**
```ts
const esbuild = require('esbuild');

esbuild.build({
  entryPoints: ['./src/index.ts'],
  bundle: true,
  define: {
    'process.env.NODE_ENV': 'production'
  },
  outfile: './dist/index.js',
  tsconfig: './tsconfig.json',
});
```

**yields:**

Note the `production` this will lead to an error when running. 

```js
(() => {
  // src/utils.ts
  var add = (a, b) => {
    return a + b;
  };
  var subtract = (a, b) => {
    return a + b;
  };

  // src/index.ts
  console.log(add(2, 3));
  production !== "production" && console.log(subtract(6, 3));
})();
```

### Option 2: quote the environment var

using same source code

**config:**
```ts
const esbuild = require('esbuild');

esbuild.build({
  entryPoints: ['./src/index.ts'],
  bundle: true,
  define: {
    'process.env.NODE_ENV': '"production"'
  },
  outfile: './dist/index.js',
  tsconfig: './tsconfig.json',
});
```

**yields:**

This seems to work and it is what I’d expect the result to be. 

```js
(() => {
  // src/utils.ts
  var add = (a, b) => {
    return a + b;
  };

  // src/index.ts
  console.log(add(2, 3));
})();
```

Maybe the documentation is outdated ? I just want to confirm this is the case. Thanks!

**Comment by evanw** [comment]
> Maybe the documentation is outdated ?

The documentation explicitly mentions this:

> If you want to replace something with a string literal, keep in mind that the replacement value passed to esbuild must itself contain quotes. Omitting the quotes means the replacement value is an identifier instead:
>
> ```js
> > require('esbuild').transformSync('id, str', {
>     define: { id: 'text', str: '"text"' },
>   })
> {
>   code: 'text, "text";\n',
>   map: '',
>   warnings: []
> }
> ```

See the full documentation here: https://esbuild.github.io/api/#define.

**Comment by Jareechang** [comment]
yikes, I should really read the documentation more carefully. 

Thanks!
