### ISSUE TITLE
Adding a new module system

### ISSUE THREAD

**Issue by retorquere** [evanw/esbuild#1752]
I'm bundling for a pretty peculiar environment -- Firefox XPCOM extensions. In this environment there is a sort-of-esm module system, but any exported entities must be listed in `EXPORTED_SYMBOLS` like so:

```
const EXPORTED_SYMBOLS = ["Services"];
```

and instead of

```
import { Services } from './Services.jsm'
```

there would be 

```
const { Services } = ChromeUtils.import("./Services.jsm")
```

how would I go about adding this module system to esbuild?

**Comment by evanw** [comment]
I don't think it makes sense to add support for rarely-used module systems like that to esbuild, sorry. Some ideas:

1. Why not just write your code like that in the first place?

2. Right now the `exports` field in the `metafile` is only populated when the output format is `esm`, but if I changed that to always be populated even for other formats such as `cjs` then you should be able to add support for this format using a plugin. My idea was to have the plugin generate output in the `cjs` format and then use the plugin to wrap the output file with something like this after the build finishes:

```js
// Step 1: Evaluate the CommonJS module
var module = { exports: {} };
((exports, module, require) => {
  /* esbuild output here */
})(module.exports, module, ChromeUtils.import);

// Step 2: Export the relevant symbols
const EXPORTED_SYMBOLS = [/* exports here */];
const [/* exports here */] =
  EXPORTED_SYMBOLS.map(x => module.exports[x]);
```

**Comment by retorquere** [comment]
> I don't think it makes sense to add support for rarely-used module systems like that to esbuild, sorry. Some ideas:
> 
>     1. Why not just write your code like that in the first place?

I like the tree-shaking that esbuild does, but it would remove the `EXPORTED_SYMBOLS`, and if I don't use `import` but rather `ChromeUtils.import` I lose out on the typescript typechecking across modules.

>     2. Right now the `exports` field in the `metafile` is only populated when the output format is `esm`, but if I changed that to always be populated even for other formats such as `cjs` then you should be able to add support for this format using a plugin. My idea was to have the plugin generate output in the `cjs` format and then use the plugin to wrap the output file with something like this after the build finishes:

That sounds awesome! I could just declare all my own code to be external, have esbuild bundle up everything from node_modules, wrap the results using such a plugin... that would be fantastic.

How could a plugin like this get access to the metafile?

**Comment by rizkyramadhan** [comment]
> How could a plugin like this get access to the metafile?

https://esbuild.github.io/api/#metafile

**Comment by retorquere** [comment]
But assuming the plugin is in a variableif a plugin is added to the build like so:

```
const xpcom = {
  name: 'xpcom',
  setup(build) {
    build.onLoad({ filter: /.*\.js$/ }, (args) => {
      let contents = await fs.promises.readFile(args.path, 'utf-8')

      // add the wrapping code here

      return {
        contents,
        loader: 'js'
      }
    })
  }
}

const result = require('esbuild').buildSync({
  entryPoints: ['app.js'],
  bundle: true,
  metafile: true,
  outfile: 'out.js',
  plugin: xpcom
})
require('fs').writeFileSync('meta.json', JSON.stringify(result.metafile))
```

how would the `xpcom` module get access to the metafile data?

**Comment by retorquere** [comment]
I suppose I could just run esbuild for `esm` format, grab the exports from the metafile, and then run esbuild again in `cjs` mode to apply the wrapper outlined above, right?

**Comment by evanw** [comment]
Yeah. Something like this:

```js
const xpcomPlugin = {
  name: 'xpcom',
  setup(build) {
    // Do another parallel ESM build to get the exported symbol list
    const esmBuild = esbuild.build({
      ...build.initialOptions,
      logLevel: 'silent',
      format: 'esm',
      metafile: true,
      write: false,
      plugins: [],
    })

    // Do a CommonJS build with a metafile
    build.initialOptions.format = 'cjs'
    build.initialOptions.metafile = true

    // When the build ends, wait for the other build
    build.onEnd(async cjsResult => {
      const esmResult = await esmBuild.catch(() => ({}))

      // If both builds succeeded, rewrite each entry point output file
      if (cjsResult.metafile && esmResult.metafile) {
        for (const output in cjsResult.metafile.outputs) {
          const cjs = cjsResult.metafile.outputs[output]
          if (!cjs.entryPoint) continue
          const esm = esmResult.metafile.outputs[output]

          // Wrap the CommonJS module
          const EXPORTED_SYMBOLS = esm.exports
          let js = fs.readFileSync(output, 'utf8')
          js = `
            var EXPORTED_SYMBOLS = ${JSON.stringify(EXPORTED_SYMBOLS)};
            var [${EXPORTED_SYMBOLS}] = (() => {
              var exports = {};
              var module = { exports };
              var require = ChromeUtils.import;
              ${js}
              return [${EXPORTED_SYMBOLS}];
            })();
          `
          fs.writeFileSync(output, js)
        }
      }
    })
  },
}
```

**Comment by retorquere** [comment]
Sweet! So no changes needed to esbuild; I suppose adding the exported symbols list would save one compilation stef, but with esbuild, that won't amount to much.

**Comment by retorquere** [comment]
Follow-up question if I may -- I have my typescript sources, and a bunch of libraries in `node_modules` -- how do I set up esbuild to make each individual .ts file a xpcom module with the code above, and create one large vendor bundle xpcom module for the libraries in `node_modules`? Should I list all my sources in `entryPoints`?

**Comment by retorquere** [comment]
Or even wrapping every js/ts file this way and not bundle anything, but just write out the wrapped js files from the node_modules to the outdir. If they're not bundled but are all xpcom'ed, that's fine too.

**Comment by evanw** [comment]
This is not something esbuild is designed to do, sorry. The easiest way to do this is to just bundle everything into one file and use source maps for debugging (which may not work in your unusual environment of course).

I'm sure you could figure something out yourself with enough hacking. If each module in node_modules has a single entry point, you could potentially use a plugin to generate a virtual entry point that imports and re-exports all packages and then bundle that (and then also a plugin to rewrite the import paths in your code).

Otherwise if you need to be able to import individual files within node_modules you could try writing a plugin that rewrites import paths of files inside packages into plain relative paths that work in your custom environment, and then keep building imported files into the output directory in a loop until all files have been built. Getting all of that right would depend on the specifics of your situation.

**Comment by retorquere** [comment]
It's not so much that I need separate files for things on node_modules, I thought that would make things easier. A single-file vendor bundle would be preferred actually. I just don't know how to cause that... but come to think of it, this might be code-splitting, and that's not yet supported for anything but esm, right?

**Comment by retorquere** [comment]
Would it work if I used a two-pass approach where the first pass would use esm as the target format with code splitting where I declared all my own typescript source files as endpoints (leaving the node_modules bundled in a tree-shaked vendor bundle), and the 2nd pass would convert all esm output (including the vendor bundle) to xpcom modules with the plugin above?

**Comment by retorquere** [comment]
Where is this part used?

```
              var exports = {};
              var module = { exports };
              var require = ChromeUtils.import;
```

I can't find this aliased `require` call in the generated sources.

**Comment by evanw** [comment]
Closing this issue due to age, and because it's not a goal of esbuild to support more obscure module formats.
