### ISSUE TITLE
Strip `node:` prefix when converting to CJS and `target < node14.18`

### ISSUE THREAD

**Issue by mattfysh** [evanw/esbuild#1760]
A recent release of `node-fetch` exposed an issue where `node:*` prefix imports compiled into `require()` calls are not supported if < node v14.18

https://github.com/node-fetch/node-fetch/issues/1367

Is there a way to check the compile target, and if the target is CJS without `node:*` prefix support, strip away the prefix?

Thanks Evan! :)

**Comment by mattfysh** [comment]
Relevant links:

1. https://github.com/evanw/esbuild/issues/1466
2. https://github.com/evanw/esbuild/commit/025d64eb807dd62fd4ec0cfa335d8d4cc131ae03

**Comment by hyrious** [comment]
I'm trying to solve it with a plugin:
```js
var stripNodeColonPlugin = {
  name: 'strip-node-colon',
  setup({ onResolve, onLoad }) {
    onResolve({ filter: /^node:/ }, args => {
      return { path: args.path.slice('node:'.length), namespace: 'strip-node-colon' }
    })
    onLoad({ filter: /()/, namespace: 'strip-node-colon' }, args => {
      return { contents: `
        export * from "${args.path}"
        export { default } from "${args.path}"
      ` }
    })
  }
}
```

**Comment by jimmywarting** [comment]
i was just thinking... what if you transpile: 
```js
import fs from 'node:fs'
export const foo = 'bar'
```
into something like:
```js
(async () => {
  const { default: fs } = await import('node:fs')
  return { foo: 'bar' }
})()
```

Everything about ESM is async from the ground up. All imports, top-level await.
This is valid cjs. And cjs can load esm modules too, this node prefix works from 12.20 as long as you use dynamic import
