### ISSUE TITLE
How can i use esbuild with `babel-plugin-import` feature

### ISSUE THREAD

**Issue by imcuttle** [evanw/esbuild#1763]
![image](https://user-images.githubusercontent.com/13509258/141101933-5f291058-d3ce-4a94-a7c6-c65e8395fe6a.png)
[babel-plugin-import](https://github.com/umijs/babel-plugin-import)

I don't want to use [esbuild-dynamic-import-plugin](https://www.npmjs.com/package/esbuild-dynamic-import-plugin) which is implemented by babel-parser (with low performance)

**Comment by evanw** [comment]
This is custom behavior that should be implemented in a plugin, not in esbuild itself. It's not a problem with esbuild if a plugin is implemented inefficiently. You are welcome to write your own more efficient plugin if you'd like.

One potential option is to use the library https://www.npmjs.com/package/es-module-lexer, which is designed for speed and gives you the imports in the source code without parsing anything else in the file.

Closing this issue as this is out of scope for esbuild itself.

**Comment by evanw** [comment]
Yes it's technically possible to do that, but it's definitely out of scope for what esbuild is supposed to do. So it's not going to be part of esbuild. Making this:

```js
import { Button } from 'antd';
```

actually mean this:

```js
var _button = require('antd/lib/button');
require('antd/lib/button/style');
```

is a very custom behavior that doesn't belong in a general-purpose tool like esbuild. You are welcome to deviate from how JavaScript normally works and make `import` mean something unusual like this, but it means you will be on your own as far as tooling for this custom behavior. You will have to either find a tool that does this, write your own, or write your own plugin to get an existing tool to do what you want.

**Comment by badrylin** [comment]
This is custom behavior that should be implemented in the plugin. However, the Transform API does not have a plugin option. I want to manipulate AST in Transform Api.
