### ISSUE TITLE
[Question/Bug?] The [dir] placeholder seems to be misbehaving

### ISSUE THREAD

**Issue by bognarlaszlo** [evanw/esbuild#1769]
Hi @evanw 

I'm creating a plugin for image optimisation that would run when images are resolved/loaded.

If I'm intercepting only in the Resolve phase - without a namespace and with loaders in config - the [dir] gets replaced as expected.
However it seem like when I retrun in Load phase it gets ignored/disappears.

My onResolve callback looks something like this:
```js
const ResolveCB = async ({resolveDir, path}) => {
    const file = resolve(resolveDir, path)
    const extension = extname(file).slice(1).toLowerCase()

    return {
        path: file,
        namespace: NAMESPACE,
        pluginData: {
            extension
        }
    }
}
```

The onLoad callback:
```js
const LoadCB = async ({path, pluginData: {extension}}) => {
    /* Encoding happens here */

    return {
        contents,
        loader: 'file'
    }
}
```

And my config:
```js
esbuild.build({
    bundle: true,
    logLevel: 'verbose',
    minify: production,
    sourcemap: !production,
    watch: watch,
    assetNames: '[dir]/[name]-[hash]',
    metafile: true
    entryPoints: [
        'resources/css/main.scss',
        'resources/js/main.js'
    ],
    outdir: 'public',
    plugins: [
        MYPLUGIN()
    ],
    loader: {
        '.jpg': 'file',
        '.jpeg': 'file',
        '.png': 'file',
        '.svg': 'file'
    }
})
.catch(() => process.exit(1));
```

Is this intentional, or am I missing something? My first intuition was that esbuild doesn't know about the initial path because the `OnLoadResult` doesn't contain that information and I tried to pass that data in pluginOptions but it didn't work.

Can you put me in direction?
TIA

**Comment by bognarlaszlo** [comment]
@evanw Any idea on this one? This is the plugin in question: https://github.com/bognarlaszlo/esbuild-squoosh
Thank you if you can look into this.

**Comment by evanw** [comment]
I took a look and I can reproduce the behavior you're talking about. The namespace feature lets you introduce a custom path format that isn't a file path. For example, a data URL plugin might use `namespace: "data-url'` and then the `onLoad` callback could extract the file contents from the path itself.

When you set a namespace other than `file`, esbuild tries to not make any assumptions about the data inside the path. In this case the custom namespace is disabling the interpretation of the path as existing in a directory on the file system, which means that the `[dir]` placeholder is not filled out.

You should use the `file` namespace (which is also the default namespace if you omit the namespace entirely) if your paths represent file system paths.

**Comment by evanw** [comment]
Does that mean this issue can be closed?

**Comment by bognarlaszlo** [comment]
Sure. I forgot to close.
