### ISSUE TITLE
Plugin seemingly not resolving external imports when using bundle: false

### ISSUE THREAD

**Issue by cristiano-belloni** [evanw/esbuild#1774]
Hi, I'm testing the plugin system. My aim is using a plugin to rewrite external imports for es modules (for example, I would like `import React from 'react'` to become `import React from 'https://mycustomurl/react'`.

It seems that if the `bundle` flag is `false`, then the external imports are never resolved and my console.log statement below never gets printed. If, instead, `bundle` is `true`, they are resolved (but I don't really want to bundle the files). Why is that?

```javascript
export const importPlugin = {
  name: "import-plugin",
  setup: (build) => {
    build.onResolve({ filter: /^[^\.]/ }, (args) => {
       return {
        path: `https://mycustomurl/${args.path}`,
        external: true,
        namespace: "custom-import",
      };
    });
  },
};
```

**Comment by evanw** [comment]
Yes, imports are only resolved when bundling is enabled. If you don't want an imported file to be included in the bundle, you can mark them as external. If you only want one file in the bundle, all exports must then be marked as external.

**Comment by melink14** [comment]
Just for future readers:

The solution of marking imports as external if you don't want them in the bundle doesn't work if the imports are also entry points. You'll receive an error that entry points can't be marked external. This is common when passing a list of ts files to esbuild which import each other.
