### ISSUE TITLE
[Bug]  'super' keyword outside a method

### ISSUE THREAD

**Issue by sean-esper** [evanw/esbuild#1777]
Trying to move a `CRA` project over to ESBuild using `craco` and `esbuild-loader`. I realize this is a complicated setup and apologize, but I hope the error is clear enough.

Development `yarn start` works fine. `yarn build` succeeds, however browser reports `Uncaught SyntaxError: 'super' keyword unexpected here` in console when trying to load the built version. It refers to one of my dependencies in node_modules, although its pretty hard to pull out the exact spot bc its minified.

I explicitly included the file in the esbuild path to see what would happen and this is the error it reports (similar to what the browser complains about):

```
./node_modules/_/dist/lib/index.js 16942:73
Module parse failed: 'super' keyword outside a method (16942:73)
File was processed with these loaders:
 * ./node_modules/esbuild-loader/dist/index.js
You may need an additional loader to handle the result of these loaders.
|           if (this.getIndex(n3.id) === -1) {
|             const t4 = { id: n3.id, role: n3.role };
|>            n3.userId && (t4.user = yield s.default.get(e2, n3.userId)), super.add(t4);
|           }
|         })), this._addHandler(this._channel, u.default.TYPE, (e3) => {
```

I noticed that something similar to this was fixed in `v0.13.8` for async functions, but I'm unsure if it handled this case.
I added a resolution to `esbuild-loader` to pull in `esbuild v0.13.13` and it still occurs.

Using babel we do not have this issue. We really want to move to ESLint because its /so much faster/!

Sorry if this is not 100% relevant to esbuild, wasnt really sure where to start.

**Comment by hyrious** [comment]
Can you provide a reproduction? We can find some clue from codes.

**Comment by sean-esper** [comment]
Its pretty hard for me to pull out a simple reproduction because I only have the minified library. I created this repository that is a basic create-react-app, then uses craco to use ESBuild.

https://github.com/sean-esper/testing-esbuild-ckeditor

craco-esbuild uses "esbuild-loader": "^2.15.1",
esbuild-loader uses "esbuild": "^0.13.4",

yarn start works fine showing the placeholder react page, yarn build/serve and trying to load in browser results in the error
![image](https://user-images.githubusercontent.com/54278988/142022498-214707db-e317-4de1-b3e0-8007b22c8204.png)

**Comment by evanw** [comment]
Thanks for the report. I was able to reproduce this. Here's a reduced reproduction:

```js
class Foo extends Bar {
  foo() {
    return async () => super.foo();
  }
  bar = async () => super.foo();
}
```

The problem is the use of `super` inside of an `async` arrow function inside of a derived class, and only happens with `--target=es2015` or `--target=es2016`.

**Comment by sean-esper** [comment]
Confirmed that I was able to build on --target=es2017

**Comment by evanw** [comment]
It turns out TypeScript (which esbuild's transform is modeled after) doesn't implement this case either. I filed this bug with TypeScript as well: https://github.com/microsoft/TypeScript/issues/46828.
