### ISSUE TITLE
Could esbuild provides some built-in features(like `babel-plugin-import`)?

### ISSUE THREAD

**Issue by imcuttle** [evanw/esbuild#1779]
Hi, @evanw 
Is it possible that esbuild provides some built-in features(like `babel-plugin-import`)?
And esbuild implements the feature by golang which has high performance. because esbuild had parsed the ast that it's no need to parse the ast(by javascript or es-module-lexer(c)) again.

```js
esbuild.transform(code, {
  features: [
    {name: 'import', options: {} },
  ]
})
```

_Originally posted by @imcuttle in https://github.com/evanw/esbuild/issues/1763#issuecomment-965935499_

**Comment by evanw** [comment]
Closing this since there is already a thread for this discussion.
