### ISSUE TITLE
[Feature]: support disable some entry  included in code splitting

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#1780]
```
{
 entryPoints: {
    pageA: 'src/pageA.ts',
    pageB: 'src/pageB.ts',
    worker: 'src/worker.ts
  }
}
```
We want to do code splitting for all pages but do not want to worker to participate in code splitting, because page and worker run in different environment, and worker runs in an environment that not supports code splitting.

**Comment by hyrious** [comment]
Just build twice, one for pages with code splitting enabled, another for worker with code splitting disabled.

**Comment by hardfist** [comment]
> Just build twice, one for pages with code splitting enabled, another for worker with code splitting disabled.

we also need to deal with HMR,  bundle analyze, sourcemap upload and so on , two compiler instance carrys lots of bundle

**Comment by evanw** [comment]
I'm closing this issue because I'm not planning on doing this. Building twice is the solution I would recommend as well.
