### ISSUE TITLE
feat: remove node: protocol

### ISSUE THREAD

**Issue by privatenumber** [evanw/esbuild#1784]
## Description
Request to strip the [`node:` protocol](https://nodejs.org/api/esm.html#:~:text=data%3Aapplication%2Fjson%2C%22world!%22'%3B-,node%3A%20imports) when converting `import` to `require` and the target is below Node v14.18.0.

## Motivation

The transform API converts `import` to `require`, which converts:
```js
import fs from 'node:fs';
```

to something like:

```js
const fs = __toModule(require("node:fs"))
```

This code cannot run in Node v12 because the `node:` protocol was backported to `require()` from Node v14.18.0

<img src="https://user-images.githubusercontent.com/1075694/140888149-3e70b3cf-1013-4d6f-ba10-0ab255024fd4.png">

### Reproduction
```sh
$ echo 'import fs from "node:fs"; console.log(fs)' | npx esbuild --format=cjs --target=node12 | node

Error: Cannot find module 'node:fs'
```

## Other info

The use of the `node:` protocol is becoming increasing prevalent due to Sindre Sorhus adopting them in his packages: https://github.com/nodejs/node/issues/38343

**Comment by hyrious** [comment]
Also see #1760.

**Comment by privatenumber** [comment]
Didn't find that in the search 😳. Thanks @hyrious!
