### ISSUE TITLE
[Question] run plugin after build

### ISSUE THREAD

**Issue by stell** [evanw/esbuild#1787]
When using Rollup I replaced a string after transpiling and bundling was finished, but before minification like this:

```
plugins: [
    modify({
        'original': 'replaced',
    }),
]
```

When using `esbuild-plugin-replace` like this

```
plugins: [
    replace({
         'original': 'replaced',
    })
]
```

the strings get replaced before bundling and transpiling. 

Can this be done in the onEnd Callback? Can this be done before minification?

**Comment by evanw** [comment]
There is no such phase in esbuild's system. For performance reasons, minification happens before converting the in-memory AST into a string. You could potentially have a plugin that disables minification and then has an `onEnd` callback that does the replacement and that then runs esbuild again a second time to do the minification. This would have a performance cost of course but it does what you're looking for.

**Comment by stell** [comment]
OK. Thanks for answering.
