### ISSUE TITLE
Reuse AST for multiple build.

### ISSUE THREAD

**Issue by zeakd** [evanw/esbuild#1788]
Hi. I'm building libraries in multiple formats like minify, cjs, esm, and run `build` multiple times.
``` js
esbuild.build({ format: 'cjs', ... });
esbuild.build({ format: 'esm', ... });
esbuild.build({ format: 'esm', minify: true, ... });
```
esbuild is fast enough to me, but i just wonder if there is any way to reuse AST cache like rebuild. Does build use cache internally? 

if not, how about add api like prebuild? like,
``` js
const prebuilt = esbuild.prebuild({ ...config });

prebuilt.build({ format: 'esm' })
prebuilt.build({ format: 'esm', minify: true })
prebuilt.build({ format: 'cjs' })
```

Thanks!

**Comment by hyrious** [comment]
AFAIK it is not possible.
Only incremental builds (same build options) can reuse AST.

**Comment by evanw** [comment]
No, there is fundamentally no way to do this. The parsed ASTs in esbuild are specific to the current build settings as the ASTs coming from the parser already have many aspects of the build settings "baked in" for performance reasons. Closing as this is not possible.
