### ISSUE TITLE
Asset imports in metafile

### ISSUE THREAD

**Issue by intrnl** [evanw/esbuild#1789]
The `imports` section can be extended to also list the assets loaded through the `file` or `css` loader, this can hopefully go towards plugins manually adding the ability to load code-split stylesheets, and preload module assets and dependencies.

```jsx
{
	"outputs": {
		"/_assets/app.js": {
			"imports": [
				{
					"path": "/_assets/app.css",
					"kind": "asset"
				},
				{
					"path": "/_assets/MainLayout-LFFXDZBS.js",
					"kind": "dynamic-import"
				}
			],
			"exports": [],
			"entryPoint": "src/app.jsx",
			"inputs": {}
		}
	},
	"/_assets/MainLayout-LFFXDZBS.js": {
		"imports": [
			{
				"path": "/_assets/MainLayout-CYAD42TH.css",
				"kind": "asset"
			},
			{
				"path": "/_assets/icon-QE33JS7D.svg",
				"kind": "asset"
			}
		],
		"exports": ["default"],
		"entryPoint": "src/layouts/MainLayout.jsx"
	}
}
```

**Comment by intrnl** [comment]
OT: can there be a way, at user's own risk, to prevent dynamically imported styles from being concatenated to the entrypoint's CSS?

**Comment by evanw** [comment]
I believe it should now be possible to do this given the information in the metafile. Closing.
