### ISSUE TITLE
Consider adding esbuild's `build` function to plugin `setup` callback

### ISSUE THREAD

**Issue by jed** [evanw/esbuild#1790]
I recently created [this plugin](https://github.com/jed/esbuild-plugin-eval) to eagerly evaluate a module. It requires access to esbuild's underlying `build` function, and instead of making plugin consumers pass it in, I'd love esbuild to provide it in the `setup` callback.

ie, instead of requiring users to do this:

```js
await build({
   entryPoints: ['app.js'],
   plugins: [myPlugin(build)]
})
```

I could have them do this:

```js
await build({
   entryPoints: ['app.js'],
   plugins: [myPlugin]
})
```

**Comment by hyrious** [comment]
You can access [`initialOptions`](https://esbuild.github.io/plugins/#build-options) in a plugin and change it before the setup callback end.

**Comment by jed** [comment]
i don't know what version the consumer of the plugin is running, and don't want to import two versions of esbuild.
