### ISSUE TITLE
[Tree Shaking] Automatically mark known globals as pure.

### ISSUE THREAD

**Issue by hyrious** [evanw/esbuild#1791]
Maybe tree-shaking can do more with this feature:
```js
var a = new Map() // same as..
var a = /*@__PURE__*/new Map()
```
There's [a list in rollup](https://github.com/rollup/rollup/blob/master/src/ast/nodes/shared/knownGlobals.ts) describing the info.

**Comment by evanw** [comment]
Treating `Map` as pure is incorrect when map takes an argument. Rollup generates incorrect code by following the rules you linked to. For example, the following code is incorrectly deleted by Rollup even though it has side effects:

```js
const x = new Map({
  [Symbol.iterator]() {
    return {
      next() {
        console.log('side effect')
        return { done: true }
      }
    }
  }
})
```

Here's a [link to this code in Rollup's REPL](https://rollupjs.org/repl/?version=2.60.1&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmNvbnN0JTIweCUyMCUzRCUyMG5ldyUyME1hcCglN0IlNUNuJTIwJTIwJTVCU3ltYm9sLml0ZXJhdG9yJTVEKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwcmV0dXJuJTIwJTdCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMG5leHQoKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjAlMjAlMjBjb25zb2xlLmxvZygnc2lkZSUyMGVmZmVjdCcpJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCUyMCUyMHJldHVybiUyMCU3QiUyMGRvbmUlM0ElMjB0cnVlJTIwJTdEJTVDbiUyMCUyMCUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlMjAlMjAlN0QlNUNuJTIwJTIwJTdEJTVDbiU3RCklNUNuJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlNUQlMkMlMjJvcHRpb25zJTIyJTNBJTdCJTIyZm9ybWF0JTIyJTNBJTIyZXMlMjIlMkMlMjJuYW1lJTIyJTNBJTIybXlCdW5kbGUlMjIlMkMlMjJhbWQlMjIlM0ElN0IlMjJpZCUyMiUzQSUyMiUyMiU3RCUyQyUyMmdsb2JhbHMlMjIlM0ElN0IlN0QlN0QlMkMlMjJleGFtcGxlJTIyJTNBbnVsbCU3RA==).
