### ISSUE TITLE
Support for node applications using Typescript and vanilla ESM w/ absolute paths

### ISSUE THREAD

**Issue by richwatts0** [evanw/esbuild#1795]
I can't seem to find a definitive & straight forward answer to whether or not esbuild is compatible with the above?

tl;dr I want absolute path aliases using my tsconfig paths setup.

I have a fresh node application where I have set package.json "type" to _module_, I am using Typescript where I am of course ensuring the .js file extension is included in my application imports.

Can I please just get some clarification that what I am trying to actually achieve is possible using esbuild before I sink anymore time into this rabbit hole?

**Comment by evanw** [comment]
I'd expect absolute paths inside `tsconfig.json` to work with esbuild as long as it works with TypeScript. If something about paths in `tsconfig.json` works with TypeScript and doesn't work with esbuild, feel free to file an esbuild bug about it.

**Comment by evanw** [comment]
Closing this issue due to age.
