### ISSUE TITLE
esbuild 0.13.15 fails with labeled tuple containing keyword `function`

### ISSUE THREAD

**Issue by eddyw** [evanw/esbuild#1797]
Hi,

`esbuild` fails to build if it encounters a labeled tuple that contains label `function`.

## Actual

```ts
// esbuild 0.13.15
type NamedArrayParams = [function: string]
```

`esbuild` fails with:
```ts
<stdin>:2:29: error: Unexpected "function"
```

## Expected

It shouldn't fail if the label name is `function`. It's perfectly valid label in TypeScript.
For instance, this works:
```ts
type LabeledArrayParams = [yadaYada: string]
```

## Workaround

Global search and replace of all tuple labels containing `function` to `functionName` or `callback` (whatever makes sense)

## Other info

**esbuild version:** 0.13.15
**OS:** macOS Monterey 12.0.1 (21A559)
**test script:**
```ts
const esbuild = require('esbuild');

console.log('ESBUILD VERSION: %s \n', esbuild.version); // 0.13.15
esbuild
	.transform(
		`
		type LabeledArrayParams = [yadaYada: string]
`,
		{ loader: 'ts', target: 'esnext' },
	)
	.then(value => {
		console.log(value?.code);
	});
```

**Comment by evanw** [comment]
How strange. Typically when JavaScript lets you use keywords as identifiers it's all or nothing. But doing this with TypeScript only lets you use these keywords:

* `false`
* `function`
* `import`
* `new`
* `null`
* `this`
* `true`
* `typeof`
* `void`

These keywords cannot be used:

* `break`
* `case`
* `catch`
* `class`
* `const`
* `continue`
* `debugger`
* `default`
* `delete`
* `do`
* `else`
* `enum`
* `export`
* `extends`
* `finally`
* `for`
* `if`
* `in`
* `instanceof`
* `return`
* `super`
* `switch`
* `throw`
* `try`
* `var`
* `while`
* `with`

I assume this is a bug in TypeScript. I replicated this behavior in esbuild as well.
