### ISSUE TITLE
esbuild is outputting invalid JS code that isn't compatible with targets

### ISSUE THREAD

**Issue by kaiyoma** [evanw/esbuild#1798]
I recently converted about 15 internal packages from Rollup to esbuild and the process has been excellent so far, but I'm running into some issues when trying to import these packages into my webpack-built app. For instance, here's one error I'm getting:

```
ERROR in ./node_modules/.pnpm/@arista+check-prop-types@16.0.0/node_modules/@arista/check-prop-types/dist/index.js 1:1161
Module parse failed: Unexpected token (1:1161)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

When I look at `1:1161` of the built file, I see that it's the `??` (logical nullish assignment) operator, but this shouldn't be appearing in my esbuild output because these are my esbuild targets:

```
['chrome80', 'edge80', 'firefox80']
```

If you look up this operator on [Can I Use](https://caniuse.com/?search=%3F%3F), you can see that it isn't supported in Edge and Chrome until version 85. Since I'm building for version 80 of both browsers, this operator should not be appearing in the output.

**Comment by kaiyoma** [comment]
Here's another example from the same packages and webpack build:

```
var c=class{host;constructor(e){this.host ...
//              ^-- webpack fails here
```

webpack points to the semicolon after `host` as being an unexpected character. I'm not exactly familiar with this notation, but it seems that esbuild is outputting some kind of unusual `class` notation that isn't natively understood by the targets.

**Comment by kaiyoma** [comment]
Ah, I just realized that my original post contains a few errors, as I'm confusing `??` with `??=`. The issue still stands that my targets for esbuild match up with my webpack targets, and yet the output from esbuild is not being accepted by webpack. Will keep digging...

**Comment by evanw** [comment]
> If you look up this operator on [Can I Use](https://caniuse.com/?search=%3F%3F), you can see that it isn't supported in Edge and Chrome until version 85. Since I'm building for version 80 of both browsers, this operator should not be appearing in the output.

The data source that I use for esbuild says that `??` works in Chrome 80+: https://github.com/kangax/compat-table/blob/adad233f401a32ff4232935c19caec9e4603c170/data-es2016plus.js#L4824.

> Ah, I just realized that my original post contains a few errors, as I'm confusing `??` with `??=`.

Yes, `??=` only works on Chrome 85+: https://github.com/kangax/compat-table/blob/adad233f401a32ff4232935c19caec9e4603c170/data-es2016plus.js#L5242.

> webpack points to the semicolon after `host` as being an unexpected character

I'm not familiar with Webpack but I assume the problem is that some JavaScript parser inside either Webpack or whatever plugin you're using is old and doesn't support new syntax. In that case it doesn't matter what browsers you target because the problem isn't with a browser; it's with the JavaScript parser in your build pipeline.

It's not clear what version of JavaScript is supported by that problematic parser but you could try setting the target to `es6` to get past this problem.

**Comment by kaiyoma** [comment]
Thanks for the quick reply! Yes, I just came to the same conclusion myself. Adding some notes here in case anyone else runs into this too...

For our app, we have a `browserslist` configuration in our package.json, which I _thought_ webpack was using, but that turned out to be an incorrect assumption. Support for using `browserslist` as the target didn't land until webpack 5, and we're still using webpack 4, which has a more simplistic "web" target. It would appear that this target is older than Chrome/Edge 80 and doesn't recognize newer JS syntax. References:

- `target` option for webpack 4: https://v4.webpack.js.org/configuration/target/
- `target` option for webpack 5: https://webpack.js.org/configuration/target/

As a workaround for now, I can augment my webpack configuration to run these specific packages through Babel. One day, when we either upgrade to webpack 5 or ditch webpack entirely for something else (my personal preference), we should be able to use the esbuild output directly with transpiling.
