### ISSUE TITLE
Question: Possibility of partial replacement of npm / yarn CLI

### ISSUE THREAD

**Issue by kesuskim** [evanw/esbuild#18]
Hello.
Gorgeous project, I'm deeply impressed 😄

As this project is written in Go, I assume later we can embed functionality into Go application, which we can fully care for Web project in Go! (and I assume you are already doing it partially)

For that purpose as this project already parsing `node_modules/` directory, I assume why not just add more features like this;

- initialize `package.json`
- fetch npm modules and store into `node_modules/` directory
- add [dev] dependencies and update `package.json`

Then we can use Go for full stack web development ! (maybe for the complex one we still need to separate frontend with backend, but we have an option)

As this project parse only for web modules, it would not that be easy task; but I think it is worth it. Any thoughts?

**Comment by evanw** [comment]
It's possible to write a npm replacement in Go. However, that's not the goal of this project. This project's purpose is limited to being a fast JavaScript bundler. I'm closing this issue because replacing npm is out of scope.
