### ISSUE TITLE
change some file caused infinite watch change loop

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#1805]
I change some file(which is not in the module graph) in project root directory, and it caused infinite loop.
![image](https://user-images.githubusercontent.com/8898718/143586562-7aa3716f-1e05-4b51-8e79-b8b3e83f646e.png)

And I don't know what `changed "."` means, does it mean esbuild watch the root directory by default, even some unrelated file will cause rebuild happen.

**Comment by evanw** [comment]
What version of esbuild is it? This was recently improved in [version 0.13.5](https://github.com/evanw/esbuild/releases/tag/v0.13.5). Also, are there any plugins that might be causing this?

**Comment by hardfist** [comment]
`0.13.4`, and It seems fixed in `0.13.5`, thanks
