### ISSUE TITLE
Cannot start service: Host version "0.14.0" does not match binary version "0.13.8"

### ISSUE THREAD

**Issue by KrysKruk** [evanw/esbuild#1806]
Hi!

After updating from version `0.13.15` to version `0.14.0` I no longer can use esbuild.

When trying to build I got an error:
```
Cannot start service: Host version "0.14.0" does not match binary version "0.13.8"
```

I removed `package-lock.json` and the whole `node_modules` folder to be sure and tried to run `npm rebuild esbuild`, but the same error is logged (also this commands hangs because of `UnhandledPromiseRejectionWarning`).

Killing the running `esbuild` process doesn't help either.

I couldn't find any informations in changelog nor documentation about updating steps.

... and a big **thank you** for running this project. Love it! ❤️ It's a huge boost in my productivity. Thank you again!

**Comment by KrysKruk** [comment]
My bad. I was accidentally copying files from different place with `node_modules` folder where the older `esbuild` version was installed. Sorry.

**Comment by Vijay410** [comment]
what is the solution if we get same . now facing same issue

**Comment by KrysKruk** [comment]
> what is the solution if we get same . now facing same issue

I explain what I did wrong in https://github.com/evanw/esbuild/issues/1806#issuecomment-980444438 . Make sure you removed all installed dependencies (e.g. `node_modules` folder) and install your dependencies again.

**Comment by jacobthesheep** [comment]
I have the same issue and deleted the repo on my local machine and redownloaded it and the error still persists

**Comment by L422Y** [comment]
For anyone looking, I was experiencing this with a Nuxt project and had explicitly added `esbuild` into my `package.json`, there was a conflict somewhere, so I just removed it from my `package.json` and reset my `node_modules` and the error went away.

**Comment by hellomrbigshot** [comment]
The problem for  me is     Host version "0.25.8" does not match binary version "0.25.5"
I use pnpm, and i try to delete node_modules and remove pnpm cache with ```pnpm store prune --force```
then re-install packages, it works.
