### ISSUE TITLE
feature request: allow to mark debugger as pure

### ISSUE THREAD

**Issue by ankurk91** [evanw/esbuild#1809]
Hi,

I could not find a way to remove `debugger` from output JS during minification

I was able to remove `console.log` using [pure](https://esbuild.github.io/api/#pure) option but not the [debugger](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/debugger)

Related Issue
https://github.com/evanw/esbuild/issues/28

**Comment by evanw** [comment]
The way to do this with esbuild is to use general-purpose code-removal mechanisms like this:

```js
if (!window.REMOVE_DEBUGGER) debugger;
```

If you pass `--define:window.REMOVE_DEBUGGER=true --minify` to esbuild, this code will be removed.

**Comment by ankurk91** [comment]
The `debugger` should be removed by default during minification.

Or allow us to mark it as `pure`
