### ISSUE TITLE
Cannot access <ClassName> before initialization

### ISSUE THREAD

**Issue by soadzoor** [evanw/esbuild#181]
Hey,

First of all, thank you for this tool, it's awesome!

About the error:
Today I replaced webpack with this tool in one of my older projects, and it went pretty smoothly, although I get a js error when I try to run my webapp: `Uncaught ReferenceError: Cannot access 'Constants2' before initialization`

The code is quite complex, but the related parts look (roughly) like this:
Main.ts:
```
export class Main
{
  private readonly _appMode: number = Constants.MODE;
}

new Main();
```

Constants.ts:
```
export class Constants
{
  public static readonly MODE: number = 2;
}
```

I believe the "Constants" class is not yet created when I try to access it from "Main", that's why it gives me the error. Interestingly, I also created a brand new project with similar structure, and I can access static functions / properties from other classes in the Main's constructor, no problem. I don't understand why it works in one case, but it doesn't in another..?

I use Main.ts as my only entry point while building (in both projects).

As a workaround, I did this in Main.ts in my original project:
```
requestAnimationFrame(() =>
{
  new Main();
});
```

which works fine, but I'm wondering if we could do something about this anyway.

Thanks!

**Comment by evanw** [comment]
In my experience this usually happens because of a cycle in the import dependency graph. Do you know if that's the case for you? With ES6 imports, the module evaluation order is arbitrary if there's a cycle in the import graph. This can also cause problems with other bundlers too. I can take a deeper look if you could provide a complete code sample that reproduces the issue.

**Comment by soadzoor** [comment]
@evanw That explains it! I'm pretty sure that my original project has some cycles in the import dependency graph! So, I guess there's not much we can do about it (except trying to avoid cycles in the import dependency graph), I guess. Thanks for the heads up!
