### ISSUE TITLE
Is it possible to know the final hashed asset path in the plugin context?

### ISSUE THREAD

**Issue by johnnybenson** [evanw/esbuild#1813]
The end goal is to generate a short list of `<Link preload>`  tags for a few critical assets injected into a static `index.html` created at build time.

It's not possible to assemble this list by hand because we want to continue leveraging the asset `[hash]` to avoid naming collisions.

I have the plumbing in place to render a list of link tags if I can collect the data, but it looks like I don't have this info in `onResolve`, `onLoad`, and `onEnd`.

Hoping someone out there has a suggestion or cool thing to try 😎.

Anyway, esbuild is a joy to work with. Thank you for making it.

**Comment by maisano** [comment]
If you enable the `metafile` flag ([docs](https://esbuild.github.io/api/#metafile)), you can access build metadata—which includes hashed paths—in the `onEnd` callback of a plugin.

**Comment by johnnybenson** [comment]
Ah brilliant, thank you.
