### ISSUE TITLE
Question: does esbuild support the browser field in package.json?

### ISSUE THREAD

**Issue by lkrugertogetr** [evanw/esbuild#1820]
I know for a fact we can specify a [target](https://esbuild.github.io/api/#target), but does this differentiate between [target specific exports](https://github.com/defunctzombie/package-browser-field-spec) defined in a package.json? 

[For example](https://github.com/solidjs/solid/blob/main/packages/solid/web/package.json): solid.js exports contents from a server.js by default, but for browsers it will export web.js. One export for example is a boolean `isServer` that can be used to minify out server or client specific sections.

Does esbuild provide for this in bundling?

Edit: tried it out and it doesn't seem to:
```typescript
//src/test.ts
import { isServer } from "solid-js/web";

console.log(isServer);
```
`pnpm esbuild src/test.ts --minify --target=node14 --bundle` and `pnpm esbuild src/test.ts --minify --target=chrome58 --bundle` both output:
```javascript
...
var e = !1;
console.log(e);
```

Anything planned on this, or should I create a workaround for this?

**Comment by hyrious** [comment]
[<samp>--platform=node</samp>](https://esbuild.github.io/api/#platform). `--target` actually does not change platform.

**Comment by lkrugertogetr** [comment]
> [--platform=node](https://esbuild.github.io/api/#platform). `--target` actually does not change platform.

That works, thanks!
