### ISSUE TITLE
Bundling loses formatting

### ISSUE THREAD

**Issue by dy** [evanw/esbuild#1823]
One unpleasant thing I noticed on attempt to bundle [subscript](https://github.com/spectjs/subscript) - bundling disregards formatting, comments and creates excessive variable definitions. 

[Before](https://github.com/spectjs/subscript/blob/e93fc0e0dba3976d49334c22d88f5ee08d17cc18/src/subscript.js)
[After](https://github.com/spectjs/subscript/blob/e93fc0e0dba3976d49334c22d88f5ee08d17cc18/subscript.js#L68)

Is that intentional effect, or just automation carelessness? 
I had an expectation that bundled code is still friendly and familiar, but it seems that it's not as careful as "manual" bundling. 
Honestly I can't see much purpose in unminified bundling if that's the case.
Is there some option to enable careful formatting-aware bundling (we just need imports exposed, right?)
Or - would that be considered a valuable feature?

I mean, [microjs](https://github.com/microjs/microjs.com/), as well as any developer, expect non-minified source to be nice and readable, as we used to do before modules era.

**Comment by evanw** [comment]
Sorry but esbuild is deliberately not a code formatter. No attempt is made to preserve the original formatting. If code formatting is important to you, you should use another tool instead. 

Closing as out of scope.

**Comment by dy** [comment]
Ok, I guess you disliked the tone or I didn't convey an argument.

Esbuild is the best bundler within others, but not absolutely. Perfect bundling implies minimal needed change to perform the task, and reformatting original code doesn't seem to be related to bundling, does that?

I'm not sure I can see arguments for its necessity, and for me as proponent of esbuild it's a bit unusual to see that disregard of a use-case. If that's the case, I guess my impression about the project was wrong and you're right.

Thank you for your reply.
