### ISSUE TITLE
bug in watch mode?

### ISSUE THREAD

**Issue by mreinstein** [evanw/esbuild#1824]
esbuild.js:

```javascript
import esbuild from 'esbuild'

esbuild.build({
    outbase: 'scripts',
    outdir: 'build',
    entryPoints: [ 'scripts/a.js', 'scripts/b.js', 'scripts/c.js' ],
    watch: true,
    bundle: true,
    format: 'esm',
    target: 'es6',
})
```

I run this with:
```bash
node esbuild.js
```

`a.js`, `b.js`, `c.js` are very simple modules that don't `import` anything (no dependencies.)
if I modify ONLY `a.js` and do `ls -l build/`, I see that all 3 files have been re-built and have new modification times.

Is this intentional? It seems like a bug that watch is just blanket re-building everything.

**Comment by mreinstein** [comment]
I'm on esbuild@0.14.1 btw

**Comment by evanw** [comment]
This is intentional. Not doing this means build results could appear to be stale. See this issue for context: #1577.

**Comment by mreinstein** [comment]
That's disapointing. If it's just going to blindly re-build on every single input file whenever one of them changes, it's going to result in a lot of over-building.  At that point one is better off just shutting off esbuild's watch capability and rolling their own.

**Comment by hyrious** [comment]
I don't think there are too much <q>over-building</q>, since esbuild would cache file ast in watch mode, the only downside here is it will eat some more IO of your disk. The browser still needs to refresh all files. The overall rebuild is still very quick.

If you are looking for a solution that the browser does not need to refresh (i.e. hot module reload), try [vite](https://vitejs.dev/).

**Comment by mreinstein** [comment]
> I don't think there are too much over-building

Well that doesn't match reality.  If you have enough entry points and a couple plugins then yes, there is over-building, evidenced by noticeable delays between file change and bundle completion.  Other watch systems (webpack, rollup, others) don't do this.
