### ISSUE TITLE
[Feature]: keep query in resolved path

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#1827]
```ts
const esbuild = require('esbuild');
const path = require('path')
async function main(){
  esbuild.build({
    entryPoints: {
      main: path.resolve('./src/index.js?entry')
    },
    plugins:[{
      name: 'xxx',
      setup(build){
        build.onLoad({filter:/.*/}, xxx => {
          console.log('resolvedId',xxx)
        })
      }
    }]
  })
}
main();
```
the result is 
```ts
resolvedId {
  path: '/Users/yj/project/ts-demo/src/index.js', // entry query is ignored
  namespace: 'file',
  pluginData: undefined
}
```
if we use query to specify an virtual module which the lost query will cause an problem(like when handle vue compile)

**Comment by hardfist** [comment]
Thanks for the fix, but there's still an problem
```ts
let examplePlugin = {
  name: 'example',
  setup(build) {
    build.onResolve({ filter: /.*/ }, args => {
      return { path: args.path, suffix: '?#iefix' }
    })

    build.onLoad({ filter: /.*/ }, args => {
      console.log({ path: args.path, suffix: args.suffix })
    })
  },
}
```
since onLoad relys on onResolve plugin to add suffix, so we had to implement onResolve plugin ourself, which is not a trivial problem(since build.internal_resolve is not supported yet), even we may implement internal_resolve ourself, it's not efficient

**Comment by evanw** [comment]
> since onLoad relys on onResolve plugin to add suffix

That's not true. The built-in onResolve behavior also fills in the suffix, so your plugin does not need an onResolve callback at all to get the suffix.

**Comment by hardfist** [comment]
That's great, and `Previously plugins had to add their own onResolve handler if they wanted to use the query suffix` this sentence might be kind of misleading.
