### ISSUE TITLE
Is it possible to ignore node_modules folder when using go pkg/api?

### ISSUE THREAD

**Issue by pavel-blagodov** [evanw/esbuild#1830]
Hi All,

I have noticed that you have left the following comment:
https://github.com/evanw/esbuild/blob/ab92f873a897587ccfc51abb59ba3d732434c4a1/internal/resolver/resolver.go#L1718

And I have the following issue. I want to resolve my es module bare specifier from my custom NodePaths folder but node_modules take precedence over my custom NodePaths folder. My custom NodePaths folder has few modules that have exactly the same relative path and name (aka 'bare specifier') as node_modules modules.

IMHO, it would be great to be able to force "NODE_PATH" to take precedence over "node_modules" paths.

P.S. Many thanks for esbuild

**Comment by hyrious** [comment]
The resolver behavior is aligned to [Node.js'](https://nodejs.org/api/esm.html#resolution-algorithm), that is to say, you'd better make your code able to run in vanilla Node.js environment. Otherwise you can always go use [plugins](https://esbuild.github.io/plugins/#resolve-callbacks) to redirect imports.

The best solution I can tell is creating symlinks of your special modules to node_modules, through [`npm link`](https://docs.npmjs.com/cli/v8/commands/npm-link) or `ln -s`. Monorepo (the `workspace` function in npm/pnpm/yarn) can also help you doing this stuff.

**Comment by pavel-blagodov** [comment]
Hi @hyrious,

I don't have npm as depency during actual build of the project. I use npm for development purpose only e.g. for downloading deps and things like eslint. Then, I prepare my deps and put them into another folder (e.g. my_modules). This issue forces me to make sure that I don't have node_modules folder in my project and in my home dir before I run api.Build command from esbuild golang api.

Do you believe that people that use golang esbuild pkg should also depend on Node.js/npm?
In any case, thanks for your reply I will have a look at [plugins](https://esbuild.github.io/plugins/#resolve-callbacks).

**Comment by pavel-blagodov** [comment]
BTW, in future, you may want to align the resolver behavior to import-maps specs. It's unofficial draft for now but it has all the chances to be approved. https://wicg.github.io/import-maps/#resolving
Cheers!

**Comment by evanw** [comment]
> IMHO, it would be great to be able to force "NODE_PATH" to take precedence over "node_modules" paths.

`NODE_PATH` is only there for compatibility with node, so it doesn't make sense to do something different than what node does.

You are welcome to customize path resolution to work however you like with plugins. The plugin API is basically identical between JS and Go so you are welcome to use either API (although of course the JS API gives you access to JS libraries, which you may want to use).

So the answer to "Is it possible to ignore node_modules folder when using go pkg/api?" is "yes" but you have to do it yourself, as described above. Closing this issue as I don't think `NODE_PATH` should be changed and the intended way to customize path resolution behavior in esbuild is through plugins.

**Comment by pavel-blagodov** [comment]
I don't think that "plugins" can help since you can't detect is bare specifier going to be resolved in "node_modules" folder or  in folder provided by **NodePaths**.
`{
   Path:angular
   Importer:/public//ui/app/main.js 
   Namespace:file ResolveDir:/public/ui/app 
   Kind:1 
   PluginData:<nil>}`

> NODE_PATH is only there for compatibility with node, so it doesn't make sense to do something different than what node does.
This statement is incorrect.

Resolving of "bare specifer" (e.g. "@angular/common/http") is not node feature. It is ES.next feature (see [import-map](https://github.com/WICG/import-maps)). Almost all modern browsers already support it. node_modules is just one of the folder that should be listed in **NodePaths** field (btw, NodePaths is not right name). With all respect to your work, you should allow us to decide where we should resolve our modules and do not override it by some default folders.

**Comment by pavel-blagodov** [comment]
So as you can see **NodePaths** has more use cases than just compatibility with node. You can use it in order to pass root folder of your custom import-maps

**Comment by evanw** [comment]
> I don't think that "plugins" can help since you can't detect is bare specifier going to be resolved in "node_modules" folder or  in folder provided by **NodePaths** in case you have more than one **NodePaths**

I don't understand. Your plugin can resolve the path using whatever custom logic you want. If the path can't be resolved, you can either fall back to esbuild's path resolution, or you can report an error to fail the build in which case esbuild's path resolution won't run. You don't have to use esbuild's built-in path resolution at all if you don't want to.

> you should allow us to decide where we should resolve our modules

That's why there's a plugin API for custom path resolution. You should be able to write some code to resolve paths however you want.

**Comment by jpike88** [comment]
>I don't understand. Your plugin can resolve the path using whatever custom logic you want. If the path can't be resolved, you can either fall back to esbuild's path resolution, or you can report an error to fail the build in which case esbuild's path resolution won't run. You don't have to use esbuild's built-in path resolution at all if you don't want to.

What about a third option: telling esbuild to ignore the resolution check and move on?
