### ISSUE TITLE
Transform es modules to commonjs -- in a shorter way?

### ISSUE THREAD

**Issue by hyrious** [evanw/esbuild#1831]
Consider this input:
```js
import { readFile } from "fs"
console.log(readFile)
```
It will be transformed to about 1kb output when the target format is `cjs`, just because of using `__toModule`. [see it live](https://hyrious.me/esbuild-repl/?version=0.14.2&shareable=JTdCJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHJlYWRGaWxlJTIwJTdEJTIwZnJvbSUyMCU1QyUyMmZzJTVDJTIyJTVDbmNvbnNvbGUubG9nKHJlYWRGaWxlKSUyMiUyQyUyMmNvbmZpZyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiU3RCU3RA%3D%3D).

This is rollup ([see it live (along with import_default and import_star)](https://rollupjs.org/repl/?version=2.60.2&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMHJlYWRGaWxlJTIwJTdEJTIwZnJvbSUyMCU1QyUyMmZzJTVDJTIyJTVDbmNvbnNvbGUubG9nKHJlYWRGaWxlKSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1vZHVsZV8xLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMGZzJTIwZnJvbSUyMCU1QyUyMmZzJTVDJTIyJTVDbmNvbnNvbGUubG9nKGZzKSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMm1vZHVsZV8yLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMColMjBhcyUyMGZzJTIwZnJvbSUyMCU1QyUyMmZzJTVDJTIyJTVDbmNvbnNvbGUubG9nKGZzKSUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmNqcyUyMiUyQyUyMm5hbWUlMjIlM0ElMjJteUJ1bmRsZSUyMiUyQyUyMmFtZCUyMiUzQSU3QiUyMmlkJTIyJTNBJTIyJTIyJTdEJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMmV4YW1wbGUlMjIlM0FudWxsJTdE)):
```js
'use strict';
var fs = require('fs');
console.log(fs.readFile);
```

This is tsc ([see it live (along with import_default and import_star)](https://www.typescriptlang.org/play?strict=false&noImplicitAny=false&strictNullChecks=false&strictFunctionTypes=false&strictPropertyInitialization=false&strictBindCallApply=false&noImplicitThis=false&noImplicitReturns=false&alwaysStrict=false&declaration=false&experimentalDecorators=false&emitDecoratorMetadata=false&target=99&jsx=0&module=1&allowSyntheticDefaultImports=false#code/PQgEB4CcFMDNpgOwMbVAFwJ4AdoGcBeAIkQHsATaI0YAPgFgAoASwFttTJ1QBvUGAIbkAYswA2aAL6hYkUq1BFYeIk2SlEeUhIB0Y0gHMAFIJHjoASiZM2HLjLwy5CpSrUatu-ceVXGN9k5uACpQAUdSR1l5RUjVRnVNbWg9QyNIvyA)):

```js
'use strict';
const fs_1 = require("fs");
console.log(fs_1.readFile);
```

I know the reason: because we have to be compatible with some old code style introduced by TypeScript without `esModuleInterop`. However, can it be trimmed down a bit? Since we know the import style (import name/default/star).

**Comment by evanw** [comment]
I'm not totally sure if this is safe, although of course it sounds safe when thinking about it quickly. The main edge cases are around `default` property access and arbitrary element access. I'd want to think more deeply about this and other edge cases such as `__esModule` and non-enumerable or non-owned properties to see if this could cause some behavior differences between this and the import-star code for arbitrary element access. It could be ok to do this transformation even with behavior differences but it'd be good to at least be aware of them going in.

**Comment by evanw** [comment]
After looking into this a bit, I think it's pretty safe to do this if all of the following are true:

* The namespace object must not be captured (i.e. stored somewhere that can't easily be analyzed):

    ```js
    // These are safe
    import 'fs'
    import {readFile} from 'fs'; readFile()
    import * as fs from 'fs'; console.log(fs.readFile)

    // These are unsafe
    import * as fs from 'fs'; console.log(fs) // Captured directly
    import * as fs from 'fs'; fs.readFile() // Captured via "this"
    import * as fs from 'fs'; fs.readFile`` // Captured via "this"
    ```

* The `default` and `__esModule` exports must not be accessed:

    ```js
    // These are safe
    import {readFile} from 'fs'; readFile()

    // These are unsafe
    import fs from 'fs'; console.log(fs.readFile)
    import {default as fs} from 'fs'; console.log(fs.readFile)
    import * as fs from 'fs'; console.log(fs.__esModule)
    import * as fs from 'fs'; console.log(fs[x]) // Could potentially access any export
    ```

There is a difference in behavior when doing this in that getters defined on `exports` potentially won't be accessed, but surely no one is crazy enough to rely on something like that?

**Comment by aminya** [comment]
Upgrading Esbuild from 0.14.3 to 0.14.5 breaks my code. It seems some new change optimizes the code in an unsafe way. Unfortunately, I cannot pinpoint the issue.
