### ISSUE TITLE
Using external flag but getting 'Dynamic require of "babylonjs" is not supported'

### ISSUE THREAD

**Issue by homanchou** [evanw/esbuild#1833]
In my entrypoint code I have at the top
```
import { Mesh, Scene, Vector3, FreeCamera, Engine, HemisphericLight } from 'babylonjs'
```
And I have babylonjs in my local node_modules folder since I have npm installed babylonjs.

However when I bundle my typescript I do not want the entirety of the babylonjs library included in the final bundle because that code is huge and doesn't change when I'm modifying just my code, so I would rather have my bundled code somehow reference the babylonjs from their cdn.

Using the 'external' flag with value 'babylonjs', esbuild correctly prevents babylonjs' code from being bundled in the output js.  On my index page I have placed a script tag to the babylonjs cdn:

```
<script src="https://preview.babylonjs.com/babylon.js"></script>
```

However when loading the page I get the error:

```
Uncaught Error: Dynamic require of "babylonjs" is not supported
```
It seems the bundled code can't find the library.  How do I tell it that it is already loaded as 'BABYLON' on the window object?

**Comment by hyrious** [comment]
Try this plugin: https://github.com/fal-works/esbuild-plugin-global-externals

**Comment by homanchou** [comment]
That didn't seem to work for babylonjs.  Maybe that only works if the package has one default export?  Whereas babylonjs has a ton of exports.

This approach does work: https://github.com/evanw/esbuild/issues/283 however it's annoying because I have to modify package.json and also create shim files.  But appears to do what I want.  I wish esbuild had a configuration to reference globals.

**Comment by hyrious** [comment]
If you don't want to write named exports, use that library in [this way](https://github.com/fal-works/esbuild-plugin-global-externals#module-type):

```js
globalExternals({
  babylonjs: {
    varName: 'BABYLON',
    type: "cjs",
  },
})
```

This way the plugin will generate a fake module like this:

```js
// fake babylonjs
module.exports = BABYLON
```

Read the docs.

**Comment by evanw** [comment]
The plugin approach described above works. Something like this could also work without any plugins (assuming `--external:babylonjs`):

```html
<script>
window.require = name => {
  if (name === 'babylonjs') return window.BABYLON
  throw new Error(`Could not require "${name}"`)
}
</script>
```

Marking something as external excludes it from the bundle, in which case you can provide your own `require` function at run-time to describe how external module names map to modules.

**Comment by homanchou** [comment]
@hyrious  thanks for the proper example!
> 
> Read the docs.

😓 I read them quickly... but I'm also new to bundling, didn't fully understand ... your example makes it concrete.

**Comment by homanchou** [comment]
>  can provide your own `require` function at run-time to describe how external module names map to modules.

Ah... I see!  Thanks for this as well!
