### ISSUE TITLE
Is it possible to build typescript entered in a form in the browser?

### ISSUE THREAD

**Issue by homanchou** [evanw/esbuild#1838]
Per the docs: https://esbuild.github.io/api/#running-in-the-browser

It seems it is possible to run esbuild in a browser.  The part I'm struggling with are the options to pass to:

```
esbuild.build(options)
```
normally `entryPoints` wants filenames, but in this case my content is already in the browser.

I tried converting the text submitted in a form to a `Blob` and then converting the blob to a url via createObjectURL, but that gets some errors.

I also tried setting `{ entryPoints: ["http://localhost:4000/assets/myfile.ts"] }`, to a file on the server side but that doesn't seem to take either.

What am I missing?  Thanks in advance.

**Comment by evanw** [comment]
If you're trying to bundle URLs: There's no code in esbuild that tries to download stuff from URLs, either inside or outside a browser. You need to provide that ability through a plugin regardless of what environment you're running in. The plugin would have to a) capture the URLs to avoid esbuild's default behavior and b) provide the content for those URLs. A simple and incomplete example of how you might do this is here: https://esbuild.github.io/plugins/#http-plugin (this is for node but of course in the browser you could just use the browser's `fetch`). Other people have probably written more complete plugins elsewhere.

If you aren't trying to bundle: The easiest way of transforming TypeScript into JavaScript a single file at a time is to use the transform API, not the build API. That's optimized for this use case. You can also use the stdin feature to provide a string as input to the build API without needing to write a plugin: https://esbuild.github.io/api/#stdin. Or you can write a plugin to provide the content for full control.

**Comment by hyrious** [comment]
You have to write plugins to redirect filenames appeared in the bundle to some virtual file or just external. [Here's an example implement](https://github.com/hyrious/esbuild-repl/blob/main/src/helpers/fs.ts). [See it live](https://hyrious.me/esbuild-repl/?shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLnRzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGElMjAlN0QlMjBmcm9tJTIwJTVDJTIyLiUyRmEudHMlNUMlMjIlNUNuQSUyMCUzRCUyMGNsYXNzJTIwJTdCJTVDbiUyMCUyMGZvbyUyMCUzRCUyMGElNUNuJTdEJTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlN0QlMkMlN0IlMjJuYW1lJTIyJTNBJTIyYS50cyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjBjb25zdCUyMGElMjAlM0QlMjAxJTIyJTJDJTIyaXNFbnRyeSUyMiUzQWZhbHNlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmJ1bmRsZSUyMiUzQXRydWUlMkMlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJzcGxpdHRpbmclMjIlM0F0cnVlJTdEJTdE).

**Comment by homanchou** [comment]
I just want to transform, not bundle.  The transform API works for me, thanks!
