### ISSUE TITLE
esbuild serve over https

### ISSUE THREAD

**Issue by YuriGal** [evanw/esbuild#1845]
Not an issue, but rather question: Is there a set of instructions or guide how to enable HTTPS support for esbuild `serve` command?

**Comment by evanw** [comment]
Sorry, I don't have any instructions or guide for this. I have never needed this myself. But any guide that helps you set up a HTTPS reverse proxy should be sufficient. You could try searching for `nginx https reverse proxy`.

**Comment by evanw** [comment]
Closing this as this question has been answered and this feature is out of scope.

**Comment by RiZKiT** [comment]
If someone stumbles upon this issue, see my suggestions here: https://stackoverflow.com/a/72951082/2590616
