### ISSUE TITLE
esbuild 0.14.4 failing to install

### ISSUE THREAD

**Issue by andyjones** [evanw/esbuild#1851]
I'm getting the following error trying to install esbuild 0.14.4 that was released to npm:

```
#14 8.279 npm ERR! /usr/src/app/node_modules/esbuild/install.js:96
#14 8.281 npm ERR!     throw new Error(`Expected ${JSON.stringify("0.14.4")} but got ${JSON.stringify(stdout)}`);
#14 8.281 npm ERR!           ^
#14 8.281 npm ERR! 
#14 8.281 npm ERR! Error: Expected "0.14.4" but got "0.14.3"
```

Does [cmd/esbuild/version.go](https://github.com/evanw/esbuild/blob/master/cmd/esbuild/version.go#L3) also need the version bumping from 0.14.3 to 0.14.4?

**Comment by evanleck** [comment]
FWIW I just reported the same thing https://github.com/evanw/esbuild/issues/1852

**Comment by evanw** [comment]
Working on it. Closing in favor of #1852.
