### ISSUE TITLE
A report about Safari's WebAssembly implementation being broken

### ISSUE THREAD

**Issue by ianberdin** [evanw/esbuild#1860]
Hi,
I'm on integration esbuild in PlayCode.io.

First of all, thank you very much for the amazing work. Figma and esbuild are incredible.

I came across the fact that in Safari web worker esbuild-wasm does not work. After few runs of build/transform, it throws the an error: `Maximum call stack size exceeded`.
[Sandbox](https://codesandbox.io/s/web-worker-example-forked-7r3sl?file=/public/test.worker.js) (open using Safari with opened Safari console).

Code:
```javascript
// test.worker.js
import {
  initialize,
  transform
} from 'https://cdn.jsdelivr.net/npm/esbuild-wasm@0.14.5/esm/browser.min.js'

  ;(async function () {
  await initialize({
    worker: false,
    wasmURL: 'https://cdn.jsdelivr.net/npm/esbuild-wasm@0.14.5/esbuild.wasm'
  })

  const r = await fetch(
    'https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.js'
  )
  const lib = await r.text()

  let i = 0
  setInterval(async () => {
    await transform(lib, { loader: 'js' })
    self.postMessage(`Build times ${i++}`)
  }, 1500)
})()
```
```javascript
// index.js
const worker = new Worker('/test.worker.js', { type: 'module' })

worker.addEventListener('message', ({ data }) => {
  console.log(data)
})
```

 A bit better stack trace: 

>  Error: Transform failed with 1 error:
    error: Maximum call stack size exceeded.
    failureErrorWithLog
    (anonymous function)
    (anonymous function)
    handleIncomingPacket
    readFromStdout
    (anonymous function)
    write
    syscall/js.valueCall
    wasm-stub
    <?>.wasm-function[1348]
    <?>.wasm-function[1331]
    <?>.wasm-function[1389]
    <?>.wasm-function[1386]
    <?>.wasm-function[1471]
    <?>.wasm-function[1486]
    <?>.wasm-function[3496]
    <?>.wasm-function[1007]
    <?>.wasm-function[1006]
    wasm-stub
    _resume
    (anonymous function)
    (anonymous function)
    resumeStdin
    onmessage
    (anonymous function)
    writeToStdin
    sendRequest
    start
    transform2
    Promise
    transform
    (anonymous function)

**Comment by brynshanahan** [comment]
Just came across this issue as well. Sandbox https://codesandbox.io/s/github/lukedxvxes/esbuild-in-browser/tree/master/?file=/src/bundler/plugins/unpkg-path-plugin.tsx

**Comment by evanw** [comment]
Maybe Safari's WebAssembly implementation is just buggy? I get really weird crashes for this in Safari when I run this on the main thread (no web worker involved). Doing that runs fine in Chrome and Firefox.

**Comment by ianberdin** [comment]
@evanw,
I have great news!
Both bugs (Safari does not know how to create a worker inside a worker yet) are closed in Safari technology preview.

But Safari is not Chrome and it won't be updated for at least a year...

Can we find some kind of intermediate solution, hot to catch the instance falling in order to restart and continue?

**Comment by evanw** [comment]
I agree that the way Apple handles Safari updates is very unfortunate. There’s nothing we can do about that though, although I hope that they one day change their minds. 

You could try to catch errors and reinstantiate esbuild’s library (which you should be able to do without esbuild’s help) but I wouldn’t recommend it. Running esbuild in a buggy VM is also likely to hang forever or to silently produce the wrong output. 

I can think of the following workarounds:

* If the client is Safari, run esbuild on the server in a controlled environment and send the results back to the client. 

* (Not serious) If the client is Safari, run esbuild’s WebAssembly code through an interpreter: https://github.com/emscripten-core/emscripten/wiki/Emterpreter. 

Realistically I’d probably just put up a banner that says something like “Safari’s WebAssembly implementation is known to be broken. Please use another browser.”

**Comment by ianberdin** [comment]
Thank you for the detailed answer and advice!
I agree, there is logic in this.

**Comment by softmarshmallow** [comment]
<img width="623" alt="Screen Shot 2022-04-09 at 12 41 13 PM" src="https://user-images.githubusercontent.com/16307013/162554984-03c5c044-1ebf-4e32-a6a6-b7c4ffa1640a.png">

I don't know if this is related, I have webworker + esbuild-wasm implementation works on chrome, doesn't work on safari (including technology preview build)
