### ISSUE TITLE
css outputs missing entryPoint in metafile

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#1861]
![image](https://user-images.githubusercontent.com/8898718/146488070-df1c8511-4407-480c-938c-25b07cd44aeb.png)

It seems the css output missing entryPoint info , which is inconvenient to group css file according to entryPoint, which is important for html-plugin supporting multi page application.

**Comment by danprince** [comment]
As far as I can tell with multiple entry points and [`EntryNames`](https://esbuild.github.io/api/#entry-names) set to `[hash]`, it's impossible to tell which entry point a CSS file belongs to.

There's a good chance that I've just missed something considering how few people have interacted with this issue, but I'm struggling with the same problem. I'm bundling multiple entrypoints, then injecting the appropriate script/link tags into their associated html files.

From the comment below, it sounds like this was a deliberate decision not to give CSS files an entrypoint property.

https://github.com/evanw/esbuild/blob/72088462ae161b452ec896462baa882863689d87/internal/bundler/linker.go#L5371-L5379

My current workaround is to ensure that each entry point has a (generated) unique ID that is included in the output file name.

```go
entryPoints = append(entryPoints, api.EntryPoint{
	InputPath:  fmt.Sprintf("page:%s", page.id),
	OutputPath: page.id,
})
```

Then I piece those entrypoints back together using those IDs when I need to inject scripts.

```go
for _, file := range result.OutputFiles {
	if strings.Contains(file.Path, page.id) {
		switch path.Ext(file.Path) {
		case ".js":
			scripts = append(scripts, file.Path)
		case ".css":
			styles = append(styles, file.Path)
		}
	}
}
```

@evanw Is there a better solution here and if not, would you accept a PR that added a `parentEntryPoint` (or similar) to the non-JS assets in the metafile, to help with recombining these bundles?
