### ISSUE TITLE
How to migrate from a large webpack project that relies on `resolve.modules`?

### ISSUE THREAD

**Issue by ghiculescu** [evanw/esbuild#1865]
(Sorry if there's a better place to ask this.)

We have a big wepback project with many entrypoints, the folder structure looks like this

```
webpack/
  feature_a/
    index.jsx // entrypoint
    views/ // lots of stuff in here
  feature_b/
    index.jsx // entrypoint
    views/ // lots of stuff in here
  helpers/
    time.js
```

Inside of any particular view, we then have lots of imports like this:

```js
import Time from "helpers/time"
```

I have not been able to get `esbuild` to resolve this import. When I run esbuild I get lots of errors of this form

```
✘ [ERROR] Could not resolve "helpers/time"

    app/webpack/feature_a/views/view.jsx:4:20:
      4 │ import Time from "helpers/time"
        ╵                     ~~~~~~~~~~~~~~~

  You can mark the path "helpers/time" as external to exclude it from the bundle, which will
  remove this error.
```

In webpack, we use [`resolve.modules`](https://webpack.js.org/configuration/resolve/#resolvemodules) to make this work. I can't find an equivalent setting in esbuild.

The only thing I've been able to do to make this work is to edit the line to look like

```js
import Time from "../../helpers/time"
```

Doing this across our whole project would take a really long time by hand, and I haven't found any good automations for doing it. Before I try and write a script for this, I want to confirm if there's any way to have esbuild understand our code as currently written?

**Comment by geoffharcourt** [comment]
If you do:

```es6
import Time from 'webpack/helpers/time';
```

does it work? This is how we've phrased all of our imports.

**Comment by ghiculescu** [comment]
This is my esbuild script

```js
esbuild
  .build({
    entryPoints: {
      feature_a: 'app/assets/webpack/feature_a/index.jsx',
      feature_b: 'app/assets/webpack/feature_b/index.jsx',
    },
    entryNames: '[dir]/[name]-[hash]',
    outdir: 'dist',
    bundle: true,
    format: 'esm',
    splitting: true,
    logLevel: 'debug',
  })
  .catch(() => process.exit(1))
```

I tried your suggestion but I still get errors. Debug logs:

```
● [DEBUG] Resolving import "webpack/airbrake" in directory "~/app/assets/webpack/feature_a/views" of type "import-statement"

  Read 3 entries for directory
  "~/app/assets/webpack/feature_a/views"
  No "browser" map found in directory
  "~/app/assets/webpack/feature_a/views"
  Searching for "webpack/airbrake" in "node_modules" directories starting from
  "~/app/assets/webpack/feature_a/views"
    Parsed package name "webpack" and package subpath "./airbrake"
    [..]

✘ [ERROR] Could not resolve "webpack/airbrake"

    app/assets/webpack/feature_a/views/index.jsx:5:23:
      5 │ import { notify } from "webpack/airbrake"
        ╵                        ~~~~~~~~~~~~~~~~~~

  You can mark the path "webpack/airbrake" as external to exclude it from the bundle, which will
  remove this error.
```

Seems like it is treating that as if it's a node module.

**Comment by evanw** [comment]
`resolve.modules` is not really a feature that esbuild has. You may be able to get esbuild to do this using the `tsconfig.json` paths feature, which esbuild does support: https://www.typescriptlang.org/tsconfig#paths.

You also are welcome to override esbuild's path resolution and substitute your own if you'd like. But you'll have to write an esbuild plugin: https://esbuild.github.io/plugins/#resolve-callbacks.

**Comment by ghiculescu** [comment]
Okay, thanks for that. I'll look into the plugin, since we don't use Typescript. Or would just having a `tsconfig.json` file work if there's no typescript files?

**Comment by evanw** [comment]
> Or would just having a `tsconfig.json` file work if there's no typescript files?

Yeah it should. TypeScript actually lets you type check JavaScript files with JSDoc annotations, so I believe `tsconfig.json` files are still relevant even in a JavaScript-only code base. I mention it because it's faster and easier, although less flexible. If you can't get `tsconfig.json` to work then a plugin should give you the power you need to do whatever you want.

**Comment by ghiculescu** [comment]
Thanks, I'll give that a try. We use flow 😭

**Comment by ghiculescu** [comment]
This worked!!

```json
{
  "compilerOptions": {
    "baseUrl": "app/assets/webpack"
  }
}
```

It didn't work with https://github.com/Csszabi98/es-pack/tree/main/plugins/esbuild-sass-plugin so I'll report an issue there.

Thanks so much for your help 😍

**Comment by geoffharcourt** [comment]
Ack, I forgot about our `baseUrl` setting, sorry for the incomplete idea earlier.
