### ISSUE TITLE
tsc fails but esbuild works

### ISSUE THREAD

**Issue by danechitoaie** [evanw/esbuild#1867]
If I run `tsc -b` I get a compilation error 
```
src/completion/completionDocumentProvider.ts:52:96 - error TS7030: Not all code paths return a value.

52     public provideCodeLenses(document: vscode.TextDocument, _token: vscode.CancellationToken): vscode.ProviderResult<vscode.CodeLens[]> {
```

while if I run esbuild the code is built without any problems.

And idea why esbuild does not see the same errors as tsc? Any way that I can make esbuild see the same errors and work the same as tsc?

**Comment by evanw** [comment]
You still have to use tsc for type checking because esbuild is not a type checker. See the docs: https://esbuild.github.io/content-types/#typescript. Closing as out of scope.
