### ISSUE TITLE
Support `exports` syntax in package.json

### ISSUE THREAD

**Issue by matthiasg** [evanw/esbuild#187]
More modern ESM node modules are supposed to use `exports` syntax to control visibility of exports. 

https://nodejs.org/api/esm.html#esm_main_entry_point_export

In case this is something that could be done an issue should track any progress

**Comment by evanw** [comment]
I've been following along with discussions about this on the issue trackers for other bundlers. As far as I know the `exports` syntax doesn't interact well with other bundler features that are already widely in use, namely the `module` and `browser` fields in `package.json`. Here is an example thread: https://github.com/webpack/webpack/issues/11014. I think it's premature to add support for this before other bundlers figure this out and the community settles on a way to work around these issues.

**Comment by matthiasg** [comment]
I think that is a prudent approach, but should at least be documented in a section about the module resolution strategy. Node 14 is advocating its use [export takes precendence over main](https://nodejs.org/docs/latest/api/esm.html#esm_package_entry_points) which will lead to some surprises.

**Comment by developit** [comment]
Just wanted to re-up this issue to get it back on your radar. The `"exports"` field is now supported in every major bundler except Parcel and ESbuild. Some examples to look at:

[Webpack](https://webpack.js.org/guides/package-exports)
[Rollup](https://github.com/rollup/plugins/pull/693)
[Vite](https://github.com/vitejs/vite/issues/1418#issuecomment-756349726)
[Snowpack](https://github.com/snowpackjs/snowpack/issues/2203)
[WMR](https://github.com/snowpackjs/snowpack/issues/2203)

**Comment by evanw** [comment]
Thanks for the links. However, it looks like decisions on how this stuff is supposed to work are still settling. See for example [this long Twitter thread](https://twitter.com/FredKSchott/status/1347352979154767873). Big +1 from me to what Devon is advocating for. I'd like to wait until y'all figure it out first so I don't end up implementing something that doesn't follow the community conventions.

**Comment by developit** [comment]
@evanw Shouldn't it be safe to implement Node's algorithm at this point though? It has been shipped as stable for 3 major versions, which makes it pretty locked in at this point. The additional community-proposed fields can certainly be subject to change, but that may always be the case, and they're only ever going to be a layer atop the base 3 fields.

**Comment by Tobbe** [comment]
How about using this [https://github.com/lukeed/resolve.exports](https://github.com/lukeed/resolve.exports)?

**Comment by lukeed** [comment]
Thanks! Yes that package follows the Node.js implementation and supports all `exports` map variants. It comes with shortcuts to toggle on/off require-vs-import and browser-vs-node, but you can use any custom conditions you want too (like webpack's production-vs-development).

> The nice thing about `exports` is that the package author determines the condition priority. When resolving, you just have to know which conditions you care about.

This makes it able to support all existing bundlers & whatever conditions they may choose to invent. Vite is already using it, wmr and yarn are WIP, and Rollup has stated that they're open to swapping too.

**Comment by airhorns** [comment]
In the meantime, we could probably write a plugin that used `resolve.exports` for now, right? You'd take a major performance hit because each resolution would have to jump back into JS land but that seems like an ok fix until things are stable enough to meet Evan's threshold?

**Comment by evanw** [comment]
> In the meantime, we could probably write a plugin that used `resolve.exports` for now, right?

If you're looking at writing a plugin, you may find this recently-released feature helpful for the import vs. require distinction: #879.

> that seems like an ok fix until things are stable enough to meet Evan's threshold?

Right now my main reason for not doing this right now (at least a node-compatible version) is that doing this is a breaking change. This change is on my list of potential things to bundle together in the next upcoming breaking change release.

**Comment by matthiasg** [comment]
@evanw appreciate your great work ! You do not have to make this a breaking change though if you hide it behind a feature flag. Do you think that would add too much complexity ?

**Comment by evanw** [comment]
This feature has been released in version 0.9.0 by the way. Please try it out and let me know if anything seems off. I tried to follow node's specification as close as I could but I don't use this feature myself so it's possible that something might not be working exactly right on the first try.

**Comment by Lcfvs** [comment]
Hi @evanw,

I think I have an unsupported case, into the project of my clients:

```js
  "exports": {
    "./*": "./src/*"
  },
```

**Comment by evanw** [comment]
> Hi @evanw,
> 
> I think I have an unsupported case, into the project of my clients:
> 
> ```js
>   "exports": {
>     "./*": "./src/*"
>   },
> ```

That already works:

https://esbuild.github.io/try/#YgAwLjIxLjQALS1idW5kbGUAZQBlbnRyeS5qcwBpbXBvcnQgInBrZy9mb28uanMiAAAvbm9kZV9tb2R1bGVzL3BrZy9wYWNrYWdlLmpzb24AewogICJleHBvcnRzIjogewogICAgIi4vKiI6ICIuL3NyYy8qIgogIH0KfQAAL25vZGVfbW9kdWxlcy9wa2cvc3JjL2Zvby5qcwBjb25zb2xlLmxvZygnd29ya3MnKQ

**Comment by Lcfvs** [comment]
Hi @evanw,

Thanks a lot for your reply & sorry for the delay, I was investigating... but even if it works within your playground... the bundling fails for my client project files.

I tried to make a very minimal sample for you, available here: https://github.com/Lcfvs/esbuild-attempt

After the download:
```sh
cd client
npm i
npm run build
```
Produces:
![image](https://github.com/evanw/esbuild/assets/2665124/d54f2b12-776b-410c-9834-be3ea5f231d6)

**Comment by evanw** [comment]
The failing import is in the `components-generics` package, not the `client` package. So you also need to do this to get it to build:

```
cd components-generics
npm i
```

That doesn't seem like a problem with esbuild to me.

**Comment by Lcfvs** [comment]
Oh, I see... thanks a lot and sorry for that, then 🫣

**Comment by Lcfvs** [comment]
I'm curious about that line: `No "browser" map found in directory "./esbuild-attempt/components-generics/src/js"`

Is it something like an importmap? Is it a way to resolve the problem without installing the subdependencies? And in that case, is there any writing to read about how to be used, please?

Because for the project, we can't really install them since the dependencies are symlinked, from a same dependencies directory, into several client clones, not replicated.

Thanks in advance. :)
