### ISSUE TITLE
"analyze" seems to be an invalid option

### ISSUE THREAD

**Issue by alexandernst** [evanw/esbuild#1870]
I'm building my project using the API and `analyze` doesn't seem to be a valid option (contrary to what the docs state). My conf:

```
esbuild.build({
  ...
  analyze: true, // <-- also tried "analyzeVerbose": true   and "analyze": "verbose"
});
```

**Comment by evanw** [comment]
You should read the docs again. They don’t say anything like that: https://esbuild.github.io/api/#analyze.

**Comment by alexandernst** [comment]
Indeed, I got totally confused!
