### ISSUE TITLE
Question: target awareness

### ISSUE THREAD

**Issue by chrisandrewca** [evanw/esbuild#1875]
Hello, thank you so much for producing esbuild.

I've been thinking.

> Note that if you use a syntax feature that esbuild doesn't yet have support for transforming to your current language target, esbuild will generate an error where the unsupported syntax is used. This is often the case when targeting the es5 language version, for example, since esbuild only supports transforming most newer JavaScript syntax features to es6.

Therefore; is it not possible to produce an .html page on each build which states
1. each js/css/html feature used
2. a checkmark or list of supported targets (a la caniuse.com)

Then, one would invoke the build using nodemon.

Such that, on each invocation of Ctrl+S; an application specific 'caniuse.com' dashboard is produced letting you know if the features you've chosen to use meet your target requirements.

No more having to keep track of every single proposal detail in your head.
No more manual lookups.
Automatic development. Instead of a manual car.

**Comment by evanw** [comment]
I'm confused. You don't have to track anything in your head. You just give esbuild your target browsers and then esbuild will immediately generate an error if you ever do anything that can't be made to work with those browsers. For example, you might set `--target=chrome58,firefox57,safari11,edge16`. Usually a given web application commits to supporting a specific set of target browser versions and communicates that to users (e.g. [this](https://help.figma.com/hc/en-us/articles/360039827194-Figma-Browser-Requirements)). That's the set of browsers that should be passed to esbuild.

**Comment by chrisandrewca** [comment]
Thank you so much for responding. Conceptually, let us back up a moment and create some idea space. I'm proposing a completely new and external workflow primarily driven by the data esbuild has access to. Precisely, "[the immediately generated error] if you ever do anything that can't be made to work with those browsers".

esbuild is saying. I can't use this feature. exit.

esbuild could say. I'm using these 14 features and thus support targets [x, y, z].

This FLIPS the discovery process. From manually looking up a feature on caniuse.com (and adjusting targets), to just coding!! It let's you drive discovery of possible targets from the code you introduce over time.

This makes coding an incredible learning experience. Associating targets with features as you use them. As you learn of new features and try using them in your code, different targets can show as (un)supported.

So esbuild could continue breaking the build. And possibly consider an additional use case, continuing the build, and displaying compatible platforms.

**Comment by evanw** [comment]
That's a nice idea but it doesn't fit esbuild's current architecture well and it's not easy to add, so I'm not planning on doing this. You should be able to do something like that yourself by doing multiple builds with different browser versions to discover which builds work and which don't. You can use binary search to find the boundary. You can also browse esbuild's internal mapping of which features are supported in which browsers here: https://github.com/evanw/esbuild/blob/86e6278fea0b4907147b35855af06104255fc313/internal/compat/js_table.go. I'm closing this issue because I'm not planning on including this in esbuild.
