### ISSUE TITLE
Sourcemap generated on windows includes \\ for paths. Should be /

### ISSUE THREAD

**Issue by matthiasg** [evanw/esbuild#188]
In order for Chrome to resolve sourcemaps correctly (especially when using workspaces) the `sources` property in the sourcemap should specify forward slashes not escaped backward slashes. 

E.g.

```
"sources": ["node_modules\\test\\src\\test2.js", "node_modules\\test\\src\\index.js", "src\\test\\index.ts", "src\\index.ts"]
```

should be

```
 "sources": ["node_modules/test/src/test2.js", "node_modules/test/src/index.js", "src/test/index.ts", "src/index.ts"]
```

**Comment by evanw** [comment]
Thanks for reporting. I'm guessing this is because these are really URLs, not paths, and should be treated as such. It's also not great that esbuild's output is different depending on the platform it's running on even independent of this issue. I'll fix this sometime soon.

**Comment by matthiasg** [comment]
Thanks. Great ! we always build on windows, linux, and mac to ensure consistency.
