### ISSUE TITLE
Question: Can esbuild output an abstract syntax tree (AST) as a result or be input an AST?

### ISSUE THREAD

**Issue by ashleydavis** [evanw/esbuild#1880]
This might be a slightly weird question, but first, thanks so much  for this amazing tool, it's really incredible.

I'd like to use to use esbuild to do something crazy with abstract syntax tree (AST) manipulation in my build pipeline.  It looks a bit like this what follows.

I take some JavaScript code and pass it through esbuild to produce an AST (say in JSON format):

\<javascript-code> --> **esbuild** --> \<AST>

I then process and augment the AST (I need to inject code at certain locations).

Finally I input the AST back to esbuild to produce the final compiled/bundled code:

\<AST> --> **esbuild** --> \<compiled-code>

So the full pipeline looks like this:

\<javascript-code> --> **esbuild** --> \<AST> (augment the AST) --> **esbuild** --> \<compiled-code>

So my question is, can esbuild output an AST?

And, can esbuild be input an AST?

If the answer is no (I imagine the answer is no because this is pretty weird use case), would it be difficult for me to contribute such a feature to esbuild? And, would you accept such a feature?

**Comment by evanw** [comment]
Sorry but AST manipulation is out of scope: https://esbuild.github.io/faq/#upcoming-roadmap. It's not a level of complexity that I think esbuild should reach and it's not something I want to maintain. There are other tools that do this kind of thing, but esbuild is not one of them. You'll need to use another tool instead, either to preprocess the input to esbuild, post-process the output from esbuild, or to replace esbuild entirely. Closing as out of scope.

**Comment by ashleydavis** [comment]
Thank you @evanw for your consideration and quick reply.
