### ISSUE TITLE
Feature request: Define env variables, and drop unused ones

### ISSUE THREAD

**Issue by Richard87** [evanw/esbuild#1882]
Hi!

I'm working on a plugin to include esbuild in caddy, and would love to enable env variables...

But, it seems all variables are included, and none are removed, even unused... That wont work for my naive implementation (including all available variables+all found in .env files).

I would love to be able to define `"process.env.NODE_ENV" = "production"`, and that esbuild would replace `process.env.NODE_ENV` this variable in any code with `"production"`, or a way to "treeshake" unused variables..

Alternative a plugin to resolve undefined variables in the code, but I suspect that would be almost impossible.

In the meantime, I'm only including `NODE_ENV`, and all variables starting with `REACT_APP_`

**Comment by evanw** [comment]
> I would love to be able to define `"process.env.NODE_ENV" = "production"`, and that esbuild would replace `process.env.NODE_ENV` this variable in any code with `"production"`

I'm confused. That's exactly what the "define" feature does: https://esbuild.github.io/api/#define. You can use `'--define:process.env.NODE_ENV="production"'` to do this.

> Alternative a plugin to resolve undefined variables in the code

Sorry, I don't fully understand what you're saying. But maybe you mean `'--define:process.env={}'` to turn all property accesses that weren't replaced unto `undefined`?

**Comment by Richard87** [comment]
Awesome! My bad, I must have done something wrong, and definitly forgot \" around the variable it works perfectly now :)  Thanks for the quick response!
