### ISSUE TITLE
Esbuild fails to properly parse some initialization wrappers

### ISSUE THREAD

**Issue by TikiTDO** [evanw/esbuild#1884]
The [flow-parser](https://www.npmjs.com/package/flow-parser) package exports a dist file of the following form:

```js
console.log(this);
(function (ctx) {
  /* Their Code */
})(
  (function () {
    return this;
  })()
);
```

When esbuild parses it with `--format=cjs` enabled it becomes something like this:

```js
console.log(exports);
(function(ctx) {
})(function() {
  return this;
}());
```

In the above case the `this` reference in the function meant to fetch the context can end up as undefined.

It works when using an arrow function as the wrapper, but I imagine the flow folks might be hard to persuade to change this.

 While I can understand that technically the value for `this` in the function may change with `bind`, in this particular case where it's immediately called perhaps some special handling is called for.

**Comment by evanw** [comment]
I'm confused. It looks like esbuild is working correctly. The first `this` references the module exports and the second `this` references the global object. You can see this for yourself:

```js
console.log(this === exports, this === global);
(function (ctx) {
  /* Their Code */
})(
  (function () {
    console.log(this === exports, this === global);
    return this;
  })()
);
```

This code prints the same thing both when it's run natively and after it's been transformed by esbuild:

```sh
$ node example.js
true false
false true

$ esbuild example.js --format=cjs > out.js

$ node out.js
true false
false true
```

This means esbuild is working correctly.

**Comment by TikiTDO** [comment]
I'm still not entirely sure while your example works if I try it in a fresh repo, it seems that to fail in one particular use case (`vscode-sortier`, which [imports](https://github.com/snowcoders/sortier-vscode/blob/main/src/extension.ts#L8) `sortier`, which [imports](https://github.com/snowcoders/sortier/blob/beta/src/language-js/parsers/flow/index.ts#L4) `flow-parser`). 

I thought it might be a vscode issue, but I can even reproduce it in normal node.

To reproduce I do the following.

1. Clone `https://github.com/snowcoders/sortier-vscode`
2. Run `npm i` to install deps
3. Edit `node_modules/flow-parser/flow_parser.js` with the following code:

```js
console.log(this === exports, this === global);

(function (ctx) {
  /* Their Code */
})(
  (function () {
    console.log(this === exports, this === global);
    return this;
  })()
);
```

4. Run `npm run build:base` which runs: ` esbuild ./src/extension.ts --bundle --outfile=dist/extension.js --external:vscode --external:typescript --format=cjs --platform=node`
5. Run `sed -i 's/__toESM(require("vscode"))/{}/' dist/extension.js` to avoid dealing with the global
6. Run `node dist/extension.js`

I get the following results:

```
true false
false false
```

I still can't quite reproduce it at will, but there seems to be an issue hiding somewhere that I can't quite pin down.

**Comment by TikiTDO** [comment]
Oh, it seems the very top level component has a `"use strict";` which then breaks the rest of the imports.

**Comment by evanw** [comment]
Ah I see. This seems like a problem with the package, not with esbuild. It's impossible to "undo" strict mode for code contained in strict mode code by design. There are [more robust ways of referencing the global object](https://mathiasbynens.be/notes/globalthis) in a cross-platform way that this library could use instead. Or they could just use `window`/`global` directly since they say they support browsers and node.

**Comment by TikiTDO** [comment]
I've asked the author of the consuming lib to just remove strict mode in this case. It doesn't look like it's particularly necessary. I'm not sure I'm ready to dive into the can of worms that is getting the flow folks to change their templates.
