### ISSUE TITLE
Mixing module.export with export behavior broke in 0.14.4

### ISSUE THREAD

**Issue by aminya** [evanw/esbuild#1887]
After upgrading from 0.14.3, the previous behaviour regarding mixing `module.export` with `export` is broken. Here is a minimal reproduction:

```ts
export enum Something {
	a,
	b,
}
const SomethingElse = { a: 1, b: 2}

module.exports = SomethingElse 
```

My fix was to not mix these together, but I think this is a bug in esbuild.

**Comment by evanw** [comment]
This is not supposed to work. You can either use ES module exports or CommonJS module exports but not both. I do not consider this to be a bug in esbuild.

**Comment by aminya** [comment]
Then, this should be a compiler error. Silently creating incorrect code is dangerous. I did not notice the issue until I ran the unit tests.

**Comment by evanw** [comment]
This shouldn't be a compiler error because it's valid code. Referencing `module` inside an ES module just references the global variable called `module`. I can try making it a warning though.
