### ISSUE TITLE
jsx support in js

### ISSUE THREAD

**Issue by Eshicagupta3** [evanw/esbuild#1888]
i am getting this error **The JSX syntax extension is not currently enabled** while using esbuild-register

**Comment by hyrious** [comment]
Maybe you are right that JSX _is_ a superset of JS. But as a bundler assuming all .js files are in JSX format may be wrong. You can just tell esbuild-register about your need to let him enable JSX for JS files.

**Comment by evanw** [comment]
This is an issue for esbuild-register, not for esbuild. They are separate projects. Closing since this issue was filed with the wrong project.
