### ISSUE TITLE
Import behavior changed in esbuild 0.14.0

### ISSUE THREAD

**Issue by DavidZbarsky-at** [evanw/esbuild#1890]
It looks like 0.14 had some behavior changes for reexports of default exports.

See https://github.com/DavidZbarsky-at/esbuild-imports-repro for a repro:
- `npm install && ./test.sh` shows that both `a.ts` and `a2.ts` behave the same way.
- try upgrading esbuild to 0.14.0 and rerunning that command
- you should see that the exports from `a.ts` are undefined, while `a2.ts` works as expected.

I took a look at [the release notes](https://github.com/evanw/esbuild/releases/tag/v0.14.0) but it wasn't clear to me that this behavior change was described there. I'm reporting this because I wasn't sure if this change was expected?

**Comment by evanw** [comment]
Thanks for the report. It looks like a regression. The `export {} from` syntax is not calling `__toESM` when it should be.

**Comment by DavidZbarsky-at** [comment]
Thanks for the speedy response! Our internal codebase hit some other issues during the upgrade that I haven't isolated yet, but if you're planning to fix this one soon I'll hold off on minimizing those (it might be the same issue)
