### ISSUE TITLE
Compiling for browsers 

### ISSUE THREAD

**Issue by pyladune** [evanw/esbuild#1893]
Hi,

Maybe this is something that I did not compute, but my app compiles fine with esbuild and node. However when running it inside browser, issues like 'require' one are showing up.

Since i solved them for compilation, i wonder why they still appear in browser.

Thanks

**Comment by FlorianLouvetRN** [comment]
This is already possible. Could you paste your build config? @pyladune

**Comment by pyladune** [comment]
config :esbuild,
  version: "0.14.7",
  default: [
    args:
    [
      "js/app.js",
      "--bundle",
      "--loader:.js=jsx",
      "--loader:.po=file",
      "--format=cjs",
      "--target=es2017",
      "--platform=node",
      "--define:global=window",
      "--outdir=../priv/static/assets",
      "--banner:js='import { createRequire as topLevelCreateRequire } from \"module\";\n const require = topLevelCreateRequire(import.meta.url);'",
      "--external:/images/*",
      "--external:/fonts/*",
      "--define:process.env.NODE_ENV='development'"
    ],
    cd: Path.expand("../assets", __DIR__),
    env: %{"NODE_PATH" => Path.expand("../deps", __DIR__)}
  ]

  config :dart_sass,
  version: "1.43.4",
  default: [
    args: [
      "js/app.scss",
      "../priv/static/assets/from_scss.css"
    ],
    cd: Path.expand("../assets", __DIR__)
  ]

**Comment by geoffharcourt** [comment]
Your platform here is `node`, does it need to be `browser`?

**Comment by pyladune** [comment]
yes, we target exclusively use in browser. we specified node to overpass the compilation error with require, etc... should we have set something else instead ?

**Comment by evanw** [comment]
Telling esbuild that the output will be running in node when it will be running in the browser instead is a bad idea and could cause lots of problems, so I don't recommend doing that.

I assume that the library you're talking about is https://nodejs.org/api/domain.html. So it sounds like you are attempting to run code that is intended for node in the browser. The typical way to do this with esbuild is to write an esbuild plugin to intercept the problematic package and substitute a browser-friendly version: https://esbuild.github.io/plugins/#on-resolve.

However, it looks like you may be running esbuild in a way that prevents you from using plugins. Plugins require using esbuild's JavaScript API. So instead you could try overriding this from within the browser. To do that, mark `domain` as external when building with esbuild and then add a `window.require` function to your HTML that returns a shim for the `domain` library when called. It'll be up to you what you want the shim to do.

**Comment by evanw** [comment]
Closing due to age.
