### ISSUE TITLE
Tree shaking not working, regardless of every module being marked as side effect free

### ISSUE THREAD

**Issue by Mwni** [evanw/esbuild#1895]
Simple snippet to reproduce:

```
import esbuild from 'esbuild'

await esbuild.build({
	stdin: {
		contents: `import fs from 'fs'`
	},
	plugins: [
		{
			name: 'no-side-effects',
			setup(build){
				build.onResolve({ filter: /.*/ }, async args => ({
					sideEffects: false
				}))
			}
		}
	],
	treeShaking: true,
	bundle: true
})
```

esbuild v0.14.9 - node v17

**Comment by Mwni** [comment]
Conversely, tree shaking takes place, when explicitly asked not to.

build.js
```
import esbuild from 'esbuild'

await esbuild.build({
	stdin: {
		contents: `import something from './something.js';`,
		resolveDir: process.cwd()
	},
	treeShaking: false,
	bundle: true
})
```

something.js
```
export default console.log('x')
```

output:
```
(() => {
})();
```

**Comment by Mwni** [comment]
Okay, I see now. Not passing back a definite path will invoke the esbuild default resolver, which will just override the `sideEffects` property to true. The problem is, I don't want to reimplement the whole package.json lookup logic to translate imports to their entry modules. And one is effectively locked out of using the default resolver, because of the infinite recursion

https://esbuild.github.io/plugins/#resolve

> There is currently no attempt made to detect infinite path resolution loops. Calling resolve from within onResolve with the same parameters is almost certainly a bad idea.

**Comment by evanw** [comment]
I said "almost" because you can do it if you know what you're doing:

```js
import esbuild from 'esbuild'

await esbuild.build({
    stdin: {
        resolveDir: '.',
        contents: `import fs from 'fs'`
    },
    plugins: [
        {
            name: 'no-side-effects',
            setup(build){
                build.onResolve({ filter: /.*/ }, async args => {
                    if (args.pluginData) return // Ignore this if we called ourselves

                    const { path, ...rest } = args
                    rest.pluginData = true // Avoid infinite recursion
                    const result = await build.resolve(path, rest)

                    result.sideEffects = false
                    return result
                })
            }
        }
    ],
    platform: 'node',
    format: 'esm',
    bundle: true
})
```

However, I believe this still could potentially cause two plugins to call each other infinitely if they both attempt recursion in different ways, so it's still something to be careful about.

**Comment by Mwni** [comment]
Spot on! The packages still get looked up, which was unusal when coming from a Rollup background, but they eventually do not end up in the bundle. So all good. It does makes sense that esbuild has to evaluate the state of side effects before shaking.

**Comment by mhsdesign** [comment]
Using `namespace` seems to be faster ;)

Thanks for solving this!!!

```js
onResolve({ filter: /.*/, namespace: "file" }, async ({ path, ...options }) => {
  const result = await resolve(path, { ...options, namespace: "noRecurse"})
  result.sideEffects = false
  return result
})
```
