### ISSUE TITLE
Compression Example

### ISSUE THREAD

**Issue by StokeMasterJack** [evanw/esbuild#1896]
I know you said compression is out of scope for ESBuild. But it would be helpful if there was an example (in the docs) of how to add this to an ESBuild pipeline. If you something readily available, that would be nice.

**Comment by evanw** [comment]
You mean compressing the output files of esbuild? That has nothing to do with esbuild, and depends completely on what tool you use. You'd just do that however the tool your using for compression works. For example I think you can do `gzip -r your-output-dir` if you're using gzip. But IMO that information belongs in the documentation for the compression tool, not in esbuild's documentation.

**Comment by evanw** [comment]
Closing as out of scope.
