### ISSUE TITLE
[MVP] Parse TypeScript syntax

### ISSUE THREAD

**Issue by evanw** [evanw/esbuild#19]
I want esbuild to demonstrate that it's possible for a normal web development workflow to have high-performance tools. I consider converting TypeScript to JavaScript a part of my initial MVP feature set for esbuild since I use TypeScript for all of my web development projects. This issue tracks the TypeScript syntax part of my MVP.

This task is tricky because TypeScript is a constantly moving target without a spec. My current plan is to get esbuild's output as close as reasonably possible to tsc's and then run every TypeScript source file I can find through esbuild and tsc and compare the output.

This is currently a work in progress on the [ts](https://github.com/evanw/esbuild/commits/ts) branch. I will close this issue when I can parse the vast majority of TypeScript files, even though I might not be able to parse every single TypeScript file. For example, I may close this issue before being able to parse TypeScript decorator syntax, since I don't use that in any of my projects.

**Comment by joseluisq** [comment]
This would be interesting feature but huge!

> I consider converting TypeScript to JavaScript a part of my initial MVP feature set for esbuild since I use TypeScript for all of my web development projects. This issue tracks the TypeScript syntax part of my MVP.

That's because I'm using Fuse-Box on production (among other things).

> I may close this issue before being able to parse TypeScript decorator syntax, since I don't use that in any of my projects.

Me neither use them. I dislike decorators particularly. 
But I don't think that you need to add support for an [experimental feature](https://github.com/Microsoft/TypeScript-Handbook/blob/master/pages/Decorators.md). 
We can live without decorators.

**Comment by mohamedmansour** [comment]
Instead of supporting TypeScript in the ESbuild grammar, the user can just run "tsc" and then "esbuild". Obviously the benefits of hooking it up to the grammar would be fastest, but that would be tricky for an open source project that moves really quickly.

**Comment by evanw** [comment]
I just landed my branch in master so I'm going to close this out. TypeScript support is now relatively complete. I can parse the source code from the TypeScript compiler itself, most of the official TypeScript compiler test files, and some public and private TypeScript projects that I've been using as test cases. It still could use some more features (e.g. decorators) but as I said above, I consider the MVP stage of TypeScript support complete without these features.
