### ISSUE TITLE
rename default with error 

### ISSUE THREAD

**Issue by underfin** [evanw/esbuild#190]
### Description
```
export {default as TestTs} from './TestTs.vue'
export {default as TestTs2} from './TestTs.vue'
```
The code will compiled to the blew code.

```
export {default2 as TestTs} from "/ts/TestTs.vue";
export {default3 as TestTs2} from "/ts/TestTs.vue";
```

### Enviorment
version: 0.5.5
Maybe caused by this commit. https://github.com/evanw/esbuild/commit/b6e98c3f2a3d2a3994ac8ce911367e4f92f4276b

**Comment by evanw** [comment]
Many thanks for reporting this. I'm surprised this doesn't have test coverage and was able to regress. This will be fixed momentarily.
