### ISSUE TITLE
How to find the path trace of a bad import?

### ISSUE THREAD

**Issue by qpwo** [evanw/esbuild#1904]
I have a browser [package](https://github.com/solana-labs/wallet-adapter) installed which is somewhere downstream doing a `require("assert")` and `require('stream')` -- or at least esbuild thinks it is. The error message shows the file doing the bad import (`cipher-base@1.0.4`) but the rest of the stack trace is within esbuild's files.

Anyone know how I can find out how this package is included in the first place? **I want like 'A imports B which imports C which imports cipher-base',** so I can intervene with a different version of B or C that doesn't rely on cipher-base.

Maybe this is an npm/yarn question and not an esbuild question? If so I can move the issue

Some text for future googlers:

> The package "stream" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.

> Could not resolve "stream"

> Could not resolve "assert"

> esbuild import node dependency into browser bundle

**Comment by qpwo** [comment]
For now I'm just installing the browser wrappers for `stream` and `assert` from npm but would rather replace the bad deps

**Comment by evanw** [comment]
Build metadata is only available for successful builds. But you should be able to "snoop" on dependency information using a plugin: https://esbuild.github.io/plugins/#on-resolve. Just don't return anything (i.e. return `undefined`) to fall back to esbuild's built-in resolution behavior.
