### ISSUE TITLE
"Illegal Module Name" for external URL

### ISSUE THREAD

**Issue by chowey** [evanw/esbuild#191]
I have a source file with an external import, like so:

```js
// source.js
import config from "/api/config?a=1&b=2";
// do some stuff with config
```

I try to build it with the `--bundle` and `--external:"/api/config?a=1&b=2"` flags. I get the following error:

> error: Invalid module name: "/api/config?a=1&b=2"

This does work with other build systems (e.g. TypeScript or Babel). The external module is supposed to be resolved by the browser at runtime.

Am I doing something wrong? Is this not supported?

**Comment by evanw** [comment]
Right now the `--external` flag is only for excluding modules, not arbitrary paths. There is already an open feature request for having `--external` support relative paths: #127. It looks like this request is similar but slightly different because it's for absolute paths, not relative paths.
