### ISSUE TITLE
[bug] Tree-shaking unexpected behaviour

### ISSUE THREAD

**Issue by recallfx** [evanw/esbuild#1912]
I found a few cases when tree shaking is not working (checked version `0.14.10`) .

1. Using `prototype` on declared classes;
2. Creating Class instances;
3. Using non existing class in extends;

When format is `esm`, it also pollutes global scope with those leftovers unless using `--minify-identifiers`.

Are there any plans to improve tree shaking so these cases would be covered?

Example:
```
// foo.js
const CONSTANT = '1';

// these gets removed
const REMOVE = '2';
const OTHER_REMOVE = '3';
class SomeClass {
  constructor() {
    this.test = OTHER_REMOVE;
  }
}
function someFunction() {}

// gets renamed
const console = 'console';

// variables used in any of left classes
const Math = 1;
const location = () => {};

// gets included because prototype is used
class ClassWithPrototype {
  constructor() {
    this.test = Math;
  }
}

ClassWithPrototype.prototype.test = true;

// gets included because new instance
class ClassInstance {
  constructor() {
    this.test = console;
  }
}

const classInstance = new ClassInstance();

// gets included because of non existent class in extends
class ClassExtendsNonExistent extends SomeNonExistingClass {
  constructor() {
    this.test = location;
  }
}

export { CONSTANT };
```

```
// index.js
import { CONSTANT } from './foo';
console.log(CONSTANT);
```

Output of `esbuild index.js --tree-shaking=true --format=esm --bundle`: 
```
// foo.js
var CONSTANT = "1";
var console2 = "console";
var Math = 1;
var location = () => {
};
var ClassWithPrototype = class {
  constructor() {
    this.test = Math;
  }
};
ClassWithPrototype.prototype.test = true;
var ClassInstance = class {
  constructor() {
    this.test = console2;
  }
};
var classInstance = new ClassInstance();
var ClassExtendsNonExistent = class extends SomeNonExistingClass {
  constructor() {
    this.test = location;
  }
};

// index.js
console.log(CONSTANT);
```

**Comment by evanw** [comment]
> I found a few cases when tree shaking is not working

This is not a bug, just not implemented. Evaluated code means the code is considered to be used, which means it isn't tree shaken.

> When format is `esm`, it also pollutes global scope with those leftovers unless using `--minify-identifiers`.

This is not true. That's not how JavaScript works. If you run JavaScript as ESM (i.e. with `<script type="module">` or `.mjs`), the runtime puts the code into its own module scope. Variables declared there do not affect the global scope.

> Are there any plans to improve tree shaking so these cases would be covered?

No plans at the moment.

**Comment by recallfx** [comment]
Thank you!
