### ISSUE TITLE
Suggetion: allow to specify external's type (esm or commonjs)

### ISSUE THREAD

**Issue by hronro** [evanw/esbuild#1915]
Say we are trying bundle a module write in commonjs:

```sh
echo 'module.exports = require("bar").default + 100;' > foo.js
esbuild foo.js --bundle --format=esm --external:bar --platform=browser
```

The format of `bar` module is ESM and eventually we will made the `bar` module available in the browser using [import-maps](https://github.com/WICG/import-maps) like this: 
 
```html
<script type="importmap">
{
	"imports": {
		"bar": "https://example.com/bar.js"
	}
}
</script>
```

However, currently esbuild will output something like `__require("bar").default`, which will cause a runtime error.

I guess esbuild is treating `bar` as a commonjs module, so using `__require` make sense.

So I wonder if we can specify the external's type, so esbuild will finally generate proper imports for the ESM externals.

If it's in a config file, it should be something like this:

```js
{
    externals: ["foo", { name: "bar", type: "esm" }]
}
```

But I'm not sure how it could be done with a CLI argument.

**Comment by watsonsong** [comment]
Is this suggestion has any solution?
I want to use esm but import some external with commonjs.
