### ISSUE TITLE
 ReferenceError: require is not defined

### ISSUE THREAD

**Issue by zejunking** [evanw/esbuild#1916]
description: 
I want to build a cjs file and use it in Chrome， but I get an error when I open html  in Chrome。
Did I configure it wrong? Still need to translate require?

version:  "^0.14.10"

```
build({
  entryPoints: ['src/index.ts'],
  target: ['es6', 'chrome58'],
  format: 'cjs',
  platform: 'browser',
  outfile: 'oader.js',
  watch: true,
})
```

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <script type="text/javascript" async="" src="test.js"></script>
  </head>
  <body>
    test
  </body>
</html>
```

![image](https://user-images.githubusercontent.com/21262401/148413560-235388d5-5834-4f5b-b545-c091e65818b5.png)

**Comment by evanw** [comment]
I’m confused. Browsers don’t support CommonJS at all, so there’s no way this would work. You need to use one of the other output formats instead.

**Comment by zejunking** [comment]
Sorry，I read the document carefully and found that I misunderstood the usage of the cjs file
