### ISSUE TITLE
esm vs cjs - import oddity/clarification

### ISSUE THREAD

**Issue by bradleygore** [evanw/esbuild#1917]
Hey - sorry to bother, just had a really strange situation and want to make sure I understand properly.

Say we have a project we're publishing to npm as a reusable lib. This lib contains files `a.ts`, `b.ts`. If `b.ts` defines an enum, which `a.ts` imports as `import { TheEnum } from './b.ts';`. This all builds properly (following the docs and using `isolatedModules` and such for TS).

The oddity (maybe just lack of understanding on my part) is that if I build that project w/ esbuild as a `cjs` output, it then breaks if downstream web app imports `upstream/a.ts` b/c `a.ts` tries to import `./b.ts` and the enum it tries to import is just `undefined`. Downstream project builds fine (also w/ esbuild) but it fails in runtime.

If I change upstream to output as `esm`, then it works in downstream (just breaks in `jest` tests but I know how to work that one out).

The main thing that is odd is that this doesn't happen if the upstream files import classes and such from files in the upstream pkg, only seems to happen on enums from what I can tell. So if `b.ts` had a class, and `export { TheClass };` then `a.ts` can `import {TheClass} from './b.ts';` just fine, and it still works in `cjs` output from what I can tell.

I'm pretty convinced that exporting reusable libs for browser as `esm` output is the right solution based on trial/error - is that correct? Is there some specific reasoning/guidance why `cjs` doesn't work (after all - aren't both versions still getting bundled by the downstream build process?). Sorry if it's a dumb question - I've used [other bundler that is much slower] for a long time so still learning my way around esbuild 😄 

Really slick build tool btw - the speed is 🔥 🔥 🔥

**Comment by evanw** [comment]
Can you provide an example of the problematic output? I can't reproduce the problem. Here's what I tried:

```
$ cat a.ts
import { TheEnum } from './b.js'
import { TheClass } from './b.js'
console.log(TheEnum, TheClass)

$ cat b.ts
enum TheEnum { TheValue }
class TheClass {}
export { TheEnum, TheClass }

$ esbuild a.ts b.ts --format=esm --outdir=esm
$ echo '{"type":"module"}' > esm/package.json
$ node esm/a.js
{ '0': 'TheValue', TheValue: 0 } [class TheClass]

$ esbuild a.ts b.ts --format=cjs --outdir=cjs
$ echo '{"type":"commonjs"}' > cjs/package.json
$ node cjs/a.js
{ '0': 'TheValue', TheValue: 0 } [class TheClass]
```

**Comment by bradleygore** [comment]
Sure thing - I'll try to create a small reproduction example over the weekend as the example I have right now is for work.

**Comment by bradleygore** [comment]
I was not able to write a small reproduction - though I tried. I couldn't reproduce what I'm seeing in a larger project. I'll close this until I can make a reproduction.
