### ISSUE TITLE
Unused code is not being tree shaken

### ISSUE THREAD

**Issue by domoritz** [evanw/esbuild#1922]
I am comparing bundles produced by esbuild with rollup and webpack. I noticed that the bundles with esbuild don't seem to be tree shaken. For different includes, the file size with esbuild is almost the same while it differs dramatically for other bundlers. I do have `minify: true` and `treeShaking: true`. 

Here is my config file: https://github.com/apache/arrow/blob/4e7bbd9c23065c5001d37fd8be398cb7de899fb2/js/test/bundle/esbuild/esbuild.js

To reproduce, clone https://github.com/apache/arrow/tree/4e7bbd9c23065c5001d37fd8be398cb7de899fb2 and run

```
cd js
yarn
yarn build -t apache-arrow
yarn test:bundle
```

Here are the file sizes (with ` ll test/bundle/**/`).

```
test/bundle/esbuild/:
199k -I deserialize-bundle.js
198k -I field-bundle.js
199k -I makeTable-bundle.js
199k -I makeVector-bundle.js
198k -I schema-bundle.js
198k -I table-bundle.js
200k -I tableFromArrays-bundle.js
198k -I vector-bundle.js
200k -I vectorFromArray-bundle.js

test/bundle/rollup/:
162k -I deserialize-bundle.js
 755 -I field-bundle.js
 70k -I makeTable-bundle.js
 56k -I makeVector-bundle.js
 13k -I schema-bundle.js
 68k -I table-bundle.js
 79k -I tableFromArrays-bundle.js
 51k -I vector-bundle.js
 65k -I vectorFromArray-bundle.js

test/bundle/webpack/:
161k -I deserialize-bundle.js
 13k -I field-bundle.js
 70k -I makeTable-bundle.js
 56k -I makeVector-bundle.js
 13k -I schema-bundle.js
 68k -I table-bundle.js
 78k -I tableFromArrays-bundle.js
 51k -I vector-bundle.js
 64k -I vectorFromArray-bundle.js
```

You can also just run `yarn gulp bundle:esbuild`

```
test/bundle/esbuild/deserialize-bundle.js: 194 Kb
test/bundle/esbuild/field-bundle.js: 193 Kb
test/bundle/esbuild/makeTable-bundle.js: 194 Kb
test/bundle/esbuild/makeVector-bundle.js: 194 Kb
test/bundle/esbuild/schema-bundle.js: 193 Kb
test/bundle/esbuild/table-bundle.js: 193 Kb
test/bundle/esbuild/tableFromArrays-bundle.js: 195 Kb
test/bundle/esbuild/vector-bundle.js: 193 Kb
test/bundle/esbuild/vectorFromArray-bundle.js: 195 Kb
```

**Comment by hyrious** [comment]
Bundle multiple files may not work as you expected, the output files are not "linked" to each other ([see it live](https://hyrious.me/esbuild-repl/?version=0.14.10&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGElMjAlN0QlMjBmcm9tJTIwJy4lMkZhLmpzJyUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwbGV0JTIwYSUyMCUzRCUyMDElMkMlMjBiJTIwJTNEJTIwMiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmJ1bmRsZSUyMiUzQXRydWUlMkMlMjJzcGxpdHRpbmclMjIlM0FmYWxzZSU3RCU3RA%3D%3D)), unless you are targetting esm with [splitting](https://esbuild.github.io/api/#splitting) enabled.

Besides, esbuild's minifier is not as redical as rollup or terser(webpack). For example it will treat all object prop access (a.b) as having side-effect since there may defined get handler, therefore these codes are not erased.

**Comment by domoritz** [comment]
It [I enable tree shaking in your example](https://hyrious.me/esbuild-repl/?version=0.14.10&shareable=JTdCJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmV4cG9ydCUyMCU3QiUyMGElMjAlN0QlMjBmcm9tJTIwJy4lMkZhLmpzJyUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmEuanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwbGV0JTIwYSUyMCUzRCUyMDElMkMlMjBiJTIwJTNEJTIwMiUyMiUyQyUyMmlzRW50cnklMjIlM0F0cnVlJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmJ1bmRsZSUyMiUzQXRydWUlMkMlMjJmb3JtYXQlMjIlM0ElMjJlc20lMjIlMkMlMjJzcGxpdHRpbmclMjIlM0FmYWxzZSUyQyUyMnNvdXJjZXNDb250ZW50JTIyJTNBZmFsc2UlMkMlMjJ0cmVlU2hha2luZyUyMiUzQXRydWUlN0QlN0Q%3D), I do see that `b` gets removed even without splitting.

**Comment by hyrious** [comment]
In that simple case, yes tree-shaking works. It actually means top level variables (including functions) that are pure (no side effect in its initializing expression) with no other expression using its value will be erased. `var a = 1` is pure, but `var a = {}; a.b = 1` is not. (similar code in your repo).

The correct way to mark some initializing code as pure in esbuild, is manually wrap them in a closure and call it with pure notation:

```js
var a = /* @__PURE__ */ (() =>
  var a = {}; a.b = 1
  return a
)()

// then, if no code uses a, the var a = ... expression will be removed.
```

**Comment by evanw** [comment]
Closing this issue since it sounds like it has been resolved. Using `/* @__PURE__ */ (() => { ... })()` is the correct way to mark arbitrary code as side-effect free in a way that works with all modern bundlers (including esbuild).

**Comment by domoritz** [comment]
Is it reasonable for ESBuild to detect which functions are pure in the future or is the current level of tree shaking the goal?

**Comment by evanw** [comment]
I wouldn't plan on esbuild automatically detecting this. I also recommend using the annotation as that makes your code portable across tools instead of depending on the implementation details of a specific version of a specific tool.
