### ISSUE TITLE
[Feature Request]: Option to not minify some parts of the code

### ISSUE THREAD

**Issue by loxator** [evanw/esbuild#1923]
Hi,

I would like to implement the following solution https://github.com/bitcoinjs/bitcoinjs-lib/issues/959#issuecomment-351040758 in ESBuildMinifyPlugin, so as to not minify some parts of the code. Is this something that is in the roadmap for esbuild? Thanks!

Reference - https://github.com/privatenumber/esbuild-loader/discussions/237

**Comment by evanw** [comment]
No, it's not on the roadmap. But all esbuild does to preserve the names is to assign the name to the `.name` property. You can easily do that yourself:

```
$ cat before.js
function foo() {}
console.log(foo.name)

$ esbuild before.js --bundle --minify | node
o

$ cat after.js
function foo() {}
Object.defineProperty(foo, 'name', { value: 'foo' })
console.log(foo.name)

$ esbuild before.js --bundle --minify | node
foo
```

**Comment by loxator** [comment]
Thanks for the tip! I will try it out, but a bit confused as to how to go about it with an external NPM package? I will probably have to make the change in the `bitcoin-js` package and link it locally to my project, right? Or is there a way I can tell esbuild to not change names for a specific package? Thanks again!
