### ISSUE TITLE
How to override default conditions

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#1924]
If we set `platform` to `browser`, which will set `conditions` contains `browser`, can we override the default conditions without changing `platform` field(we try to set `conditions`, but it seems only append custom field other than override `conditions`).

**Comment by evanw** [comment]
There isn't a built-in way to do this. Two options I can think of:

* Set the platform to `neutral` instead, which disables all custom configuration, and then add back whatever configuration you want. This will also disable interpretation of the `browser` field in `package.json`, which could be desired if you're not actually bundling for the browser.

* If you only want to disable it for a single problematic package, you could use a plugin to intercept imports for that package and substitute your own custom path resolution behavior instead.

**Comment by hardfist** [comment]
Actually I want to build for node and browser(an ssr framework on top of esbuild), if I set platform to `neurtral`(then it seems that I can't enable browser interpretation), but if I set platform to `browser` I can't override default conditions.  I currently use plugin to solve this problem and I wonder is there an better way to do this.

**Comment by evanw** [comment]
It sounds like you are trying to do something pretty custom (have a build with the browser version of some packages and the non-browser version of other packages), so I think using a plugin makes the most sense.

**Comment by hardfist** [comment]
Ok, then I will continue with plugin, thanks for your response
