### ISSUE TITLE
"top:0; bottom:0; left: 0; right:0;" is transformed to "inset:0;" but "inset" is not supported by many browsers

### ISSUE THREAD

**Issue by gabrielhpugliese** [evanw/esbuild#1925]
Version:
```
# ./node_modules/.bin/esbuild --version
0.14.11
```

Without minify:
```
# ./node_modules/.bin/esbuild test.css
body {
  top: 0;
  bottom: 0;
  left: 0;
  right: 0;
}
```

With minify:
```
# ./node_modules/.bin/esbuild --minify test.css
body{inset:0}
```

But many browsers do not support it (We have lots of users with Safari 13 and 14 still):
https://caniuse.com/?search=inset

Using only `minifyWhitespace` without `minify` flag makes the bundle pretty big.
Is there any other way to circumvent this?

**Comment by evanw** [comment]
From [the docs](https://esbuild.github.io/content-types/#css):

> Note that by default, esbuild's output will take advantage of all modern CSS features. For example, <code>color: rgba(255, 0, 0, 0.4)</code> will become <code>color: <wbr>#f006</code> when minifying is enabled which makes use of syntax from [CSS Color Module Level 4](https://drafts.csswg.org/css-color-4/#changes-from-3). If this is undesired, you must specify esbuild's [target](https://esbuild.github.io/api/#target) setting to say in which browsers you need the output to work correctly. Then esbuild will avoid using CSS features that are too modern for those browsers.

**Comment by gabrielhpugliese** [comment]
Thanks @evanw, I missed that one.

**Comment by jardicc** [comment]
For people who need to disable "inset" only. https://github.com/evanw/esbuild/blob/main/CHANGELOG-2022.md#01446

```
		supported: {
			"inset-property": false,
		},
```
