### ISSUE TITLE
Include .trie in Bundle without copy plugin?

### ISSUE THREAD

**Issue by HiveSolution** [evanw/esbuild#1926]
Hey there, I'm using fontkit in one of my projects. This requires a couple of `.trie` files.
I'm currently resolving the problem of those files missing by using a copy plugin and just including the required files in the dist folder. Works like a charm but would be awesome if I didn't have to do that.
Is there a way to include those directly in the bundle or should i just keep the copy plugin to include them in dist?

**Comment by evanw** [comment]
> Is there a way to include those directly in the bundle

Yes:

* https://esbuild.github.io/content-types/#text
* https://esbuild.github.io/content-types/#binary

**Comment by HiveSolution** [comment]
Thanks for the response, looked a bit deeper into what's requiring those files. `fontkit` is using them via `require("fs").readFileSync(__dirname+"/use.trie")` and not as an `import` statement so I'm guessing there's no way around copying the files into dist.
Or would you know of a workaround in that case?
