### ISSUE TITLE
esm + bundle + p-queue + exclude node_modules = not working

### ISSUE THREAD

**Issue by jpike88** [evanw/esbuild#1929]
```import pQueue from 'p-queue';```

Using this plugin code to exclude node_modules:
[```https://github.com/evanw/esbuild/issues/619#issuecomment-751769812```](https://github.com/evanw/esbuild/issues/619#issuecomment-751769812)

This results in p-queue still being included in the app.js, and breaks the app when it's run with this error:

```
internal/process/esm_loader.js:74
    internalBinding('errors').triggerUncaughtException(
                              ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/joshpike/Projects/aquipa/server/dist/priority-queue.js' imported from /Users/joshpike/Projects/aquipa/server/dist/app.js
```

Workaround: modify the node_modules like so to force the whole ```p-queue``` module to be pulled in as an internal lib.

```
if (
						resolved.includes('node_modules') &&
						!resolved.includes('p-queue')
					) {
						return {
							external: true,
						};
					}
```

This is obviously far from ideal. The fact that esbuild doesn't have an easy way to handle cases like this is incredibly frustrating and makes it not suitable for proper use in node.js environments.

**Comment by jpike88** [comment]
After much pain I can't go vanilla esbuild, it's just not mature enough for bundling nodejs applications. moving to vite.

**Comment by hardfist** [comment]
so you just want to exclude node_modules except p-queue？
