### ISSUE TITLE
Build fails when requring('fs')

### ISSUE THREAD

**Issue by metalmatze** [evanw/esbuild#193]
Hey, 

first of all, thank you for this project. Exactly what I need building an entirely Go based application :100: 

Now, I use OpenAPI to generate both Go client and server and for the web UI I also generate a JavaScript client. That is then used in the JavaScript app itself.
Sadly the build for that currently fails, as the OpenAPI client actually has this snippet (which should probably never evaluate for my situation) but not it's there anyway...

```javascript
// fs.ReadStream in Node.js and Electron (but not in runtime like browserify)
if (typeof require === 'function') {
    let fs;
    try {
        fs = require('fs');
    } catch (err) {}
    if (fs && fs.ReadStream && param instanceof fs.ReadStream) {
        return true;
    }
}
```
I build  using: `node_modules/esbuild/bin/esbuild --bundle ui/index.js --outfile=ui/bundle.js --sourcemap`
and see this error.
```
api/client/javascript/src/ApiClient.js:185:29: error: Could not resolve "fs"
```

For now I have commented out the lines above to at least be able to build, however, in the long term I would love to not patch the generated files every time I regenerated the API :man_shrugging: 

Thanks!

**Comment by evanw** [comment]
By default esbuild attempts to bundle all module dependencies. If you want to exclude a module dependency, you can use the `--external` flag like this:

```
node_modules/esbuild/bin/esbuild --external:fs --bundle ui/index.js --outfile=ui/bundle.js --sourcemap
```

That will cause the call to `require('fs')` to be passed through to the output file unmodified.

**Comment by metalmatze** [comment]
That works like a charm! Thank you so much and thank you again for the project! :100:
