### ISSUE TITLE
Exposing require() from IIFE bundle for browser to reexport some modules like React

### ISSUE THREAD

**Issue by shestakov** [evanw/esbuild#1931]
Hello Evan! Thank you and all the contributors for your work!

I would be grateful if you could help me to clear up one thing.

Currently I use Browserify for bundling. It uses node-way CJS module model, and it could _expose_ select modules to be required in _another bundle_  _in browser_ via require(). It is _the first sample_ [here in docs](https://github.com/browserify/browserify#more-examples).

Is it possible to do the same thing with esbuild? The actual problem is that I have _two_ bundles: the main bundle, which contains react, mobx, etc., and the _lightweight_ plugin bundle, which uses react, mobx and so on, but _does not_ contain those modules itself. They are just peer dependencies.

Could you please make it more clear?

**Comment by evanw** [comment]
Do you mean something like this?

```js
window.exposed = Object.create(null);
window.expose = function(name, module) {
  window.exposed[name] = module;
};
window.require = function(name) {
  if (name in window.exposed) return window.exposed[name];
  throw new Error('Module not found: ' + name);
};
```

**Comment by shestakov** [comment]
> Do you mean something like this?

Yep, I believe, it's something like this. Guess, this undoes tree-shaking, yet can be crucial in some cases.

**Comment by shestakov** [comment]
> Do you mean something like this?

I guess, this means `no` for both CJS and ESM, right?

**Comment by evanw** [comment]
Closing this issue due to age.
