### ISSUE TITLE
Invalid JS code when `minify-syntax` is enabled.

### ISSUE THREAD

**Issue by ooflorent** [evanw/esbuild#1936]
Given the following code:
```js
function debug_assert(expr) {
  if (DEBUG) {
    assert(expr);
  }
}

function f() {
  if (some_test) {
    let a = 0;
  } else {
    debug_assert(false);
  }
}
```
When it is compiled using:
```
esbuild minify_else.ts --define:DEBUG=false --minify-syntax
```
An invalid JS output is produced:
```js
function debug_assert(expr) {
}
function f() {
  if (some_test) {
    let a = 0;
  } else     // This is not
    ;        // valid
}
```

**Comment by evanw** [comment]
Sorry, I don't understand. How is that not valid? The semicolon by itself is an [EmptyStatement](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/Empty) in JavaScript.

What JS engine are you using that doesn't support that syntax? Or are you potentially using this with a buggy JavaScript parser? As far as I know that syntax is supported at least as far back as ES3, which was published way back in the year 2000. If a JavaScript parser or runtime can't understand this syntax, then that's a problem with that parser, not with esbuild (and is probably also severely broken on a lot of real-world code).

I can potentially improve the output here to make it shorter, but I can't fix bugs in other parsers. This kind of statement may also be generated by esbuild in other cases such as when minifying `while(foo()){}` into `for(;foo(););`. I'm not going to change esbuild to work around parser bugs like this.

**Comment by ooflorent** [comment]
> How is that not valid? The semicolon by itself is an EmptyStatement in JavaScript.

I completely forgot that empty statements could be in an `else` block.

> What JS engine are you using that doesn't support that syntax? Or are you potentially using this with a buggy JavaScript parser?

None. I was scanning the generated output of the project I'm working on when this caught my attention.

> I can potentially improve the output here to make it shorter […]. I'm not going to change esbuild to work around parser bugs like this.

Sure, that is not my intention! However, removing empty statements could be a good addition to the minifier.
