### ISSUE TITLE
[Question] Imports being pushed to the start of the file

### ISSUE THREAD

**Issue by itschip** [evanw/esbuild#1937]
As far as I have understood, esbuild pushes all the imports to the top of the file. I've encountered a little challenge regarding this.

```ts
import { ResourceConfig } from '../../typings/config';
import { RewriteFrames } from '@sentry/integrations';
// Setup and export config loaded at runtime
export const config: ResourceConfig = JSON.parse(
  LoadResourceFile(GetCurrentResourceName(), 'config.json'),
);

// Setup controllers
import './db/pool';
import './players/player.controller'
```

This is an example of how our main file looks like. We need the `config` to be exported before the rest of the files are imported. However, as mentioned above, esbuild does not seem to respect this sort of setup. 

So my question is, would it be feasible to use something like a resolve callback, on-start, or some other plugin api to export `config` before? And is this something that will ever be introduced internally?

**Comment by hyrious** [comment]
Believe it or not, the ESM spec said import statements are re-ordered to the top. Esbuild matches the behavior and prevents you write some buggy code.

If you need to ensure some code's order, you should write their dependency down by `import` statements:

```js
// config.js
import { ResourceConfig } from '../../typings/config';
import { RewriteFrames } from '@sentry/integrations';
export const config: ResourceConfig = JSON.parse(
  LoadResourceFile(GetCurrentResourceName(), 'config.json'),
);

// main.js
import { config } from './config.js';
// if you need "config" as a global variable:
// globalThis.config = config
import './db/pool';
import './players/player.controller'
```

**Comment by itschip** [comment]
Yeah, I've done that. Just had to get some clarity :)
