### ISSUE TITLE
Marking external, and also ignoring resolution check of node_modules packages

### ISSUE THREAD

**Issue by jpike88** [evanw/esbuild#1938]
I may choose to bundle my node_modules application WITHOUT node_modules present during the build. Problem is that rebuild seems to have no obvious way to skip the resolution check (which is done in our test CI, but not our deploy CI as it builds in another architecture to the production server).

The only way it seems to workaround this limitation is to dump the dependencies in package.json and insert them into ```externals``` arguments as an array.

Is there a better way to handle this?

**Comment by jpike88** [comment]
Also asking the maintainer of a plugin I use if the esbuild API allows him to do this.

https://github.com/remorses/esbuild-plugins/issues/13


In the meantime I have to do a wasteful ```npm ci```, then after build ```rm -rf node_modules```. This step shouldn't be necessary when building the app bundle.

**Comment by evanw** [comment]
> The only way it seems to workaround this limitation is to dump the dependencies in package.json and insert them into externals arguments as an array.

Yes, that would work. Another way to do this would be with a plugin: https://esbuild.github.io/plugins/#on-resolve. The specifics of the plugin behavior are up to you.

Closing this as a plugin is the intended way to customize path resolution behavior like this.
