### ISSUE TITLE
Files with extension mts should be transformed to mjs

### ISSUE THREAD

**Issue by bogusfocused** [evanw/esbuild#1942]
I use ```esbuild *.mts --bundle --platform=node --outdir=dist  --format=esm``` to build.
The files in outdir is *.js. The code is fine and I can use it with node if I rename them to mjs using ```for f in `dir dist`; do mv dist/$f dist/${f%.js}.mjs ; done```

esbuild should emit files with mjs extension, given ```--format=esm``` and ```--platform=node```, since node accepts esm modules only with extension mjs or flags ```--input-type=module``` or package.json ```type=module``` . I cannot pass flags since I use npm run. I can neither set package.json as I use files directly. It would not break or hurt other platforms if esbuild emits .mjs . It's all about extension.

**Comment by hyrious** [comment]
Have you tried `--out-extension:.js=.mjs`

**Comment by bogusfocused** [comment]
> Have you tried `--out-extension:.js=.mjs`

Thanks. works!
