### ISSUE TITLE
Eset internet security deletes esbuild.exe 0.14.11

### ISSUE THREAD

**Issue by ocombe** [evanw/esbuild#1943]
I updated my node modules and had weird issues about missing `esbuild.exe`, it turns out that Eset Internet Security marks the file as suspicious and deletes it from my node modules when it's created...
I submitted the file as a false positive, but you might want to contact them and see what's going on there...

**Comment by evanw** [comment]
I’m going to close this because it’s not a problem with esbuild and there’s nothing I can change about esbuild that will fix this. If you install a program on your computer that deletes esbuild, then that’s something you have to fix yourself.

**Comment by ocombe** [comment]
It depends why it detects this as a threat, is this something in the new version? A part of code that is unsafe? Or just a few people reported it as a threat and that's all?

**Comment by evanw** [comment]
Dealing with false positives is a reality of using antivirus software. I have no idea why this happened. The only people who would know why are the people who made that software. Nothing significant about esbuild was changed recently: https://github.com/evanw/esbuild/releases.
