### ISSUE TITLE
Spread in object literals is not support in "lt iOS 11.3"

### ISSUE THREAD

**Issue by lizy0329** [evanw/esbuild#1949]
[Can I use Spread?](https://caniuse.com/?search=spread)

[AplineJS](https://github.com/alpinejs/alpine) is build from esbuild, but it‘s not support "lt iOS 11.3" because the production code contain ...obj(spread in object) for any esbuild target.

This is a feature or bug? I can't do anything but use babel translate, no polyfill here.

**Comment by evanw** [comment]
I'm using a different data source for JavaScript feature compatibility data: https://kangax.github.io/compat-table/. My data source says that it's supported in Safari 11.1 and up: https://github.com/kangax/compat-table/blob/f156b2f5c2cb14e4d79cfaa04c3b746a5b781b32/data-es2016plus.js#L2977. I've had other cases in the past where https://caniuse.com was incorrect while https://kangax.github.io/compat-table/ was correct: https://github.com/evanw/esbuild/issues/1930#issuecomment-1011194183. So it could just be that Can I use is incorrect about this.

**Comment by lizy0329** [comment]
But in my case, "lte iOS 11.3" will throw error: "SyntaxError: Unexpected token '...'. Expected a property name." 😂😂😂

We also have a large number of IOS 11.1 11.2 machines in our company for testing

**Comment by ljharb** [comment]
Object spread/rest should be supported in iOS 11.3+, *not* 11.1 and 11.2.

**Comment by evanw** [comment]
Ah ok. So it sounds like esbuild is working correctly here. The feature support information in esbuild is correct for Safari but if you have an iOS version instead of a Safari version, then you currently need to map it to a Safari version yourself before you give it to esbuild.

**Comment by ljharb** [comment]
(fwiw, compat-table provides enough info for esbuild to be able to map iOS versions to Safari versions)

**Comment by evanw** [comment]
Yeah, sorry I was confused. I forgot that esbuild actually does support iOS versions. So this all works fine:

```
$ echo 'x = { ...y }' | ./esbuild --target=safari11.3
x = { ...y };

$ echo 'x = { ...y }' | ./esbuild --target=safari11.2
x = { ...y };

$ echo 'x = { ...y }' | ./esbuild --target=ios11.3
x = { ...y };

$ echo 'x = { ...y }' | ./esbuild --target=ios11.2
var __defProp = Object.defineProperty;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a, b) => {
  for (var prop in b || (b = {}))
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
x = __spreadValues({}, y);
```

You just have to use `--target=ios` instead of `--target=safari`, which I assume you are using.
