### ISSUE TITLE
Removing whitespace unnecessarily

### ISSUE THREAD

**Issue by kvey** [evanw/esbuild#195]
Trying esbuild out I ran into the following on a tsx file:
This space between `{text}` and `<` was removed which doesn't appear to happen in our existing webpack build.
```
 {text} <Button color={colors.blue}>Browse files</Button>
```

Also: this project is awesome!

**Comment by evanw** [comment]
Thank you very much for reporting this. Sorry about the behavior difference. I'll fix this soon.
