### ISSUE TITLE
[BUG] dead code elimination not working on false condition branch when set `treeShaking` as true

### ISSUE THREAD

**Issue by Amour1688** [evanw/esbuild#1955]
###  source code
```
// src/a.js

if (process.env.NODE_ENV === 'production') {
  console.log(1);
} else {
  console.log(2);
}
```

### build script

```js
const { buildSync } = require('esbuild');

buildSync({
  entryPoints: ['./src/a.js'],
  treeShaking: true
});
```

### output

```js
if (false) {
  console.log(1);
} else {
  console.log(2);
}
```

### expected result

```js
if (false) {
} else {
  console.log(2);
}
```

or

```js
{
  console.log(2);
}
```

**Comment by evanw** [comment]
You need to use `--minify-syntax` to enable syntax transformations like this.

**Comment by Amour1688** [comment]
It works in webpack when `mode` equals `development`.


```js
if (process.browser) {
  console.log(1)
} else {
  const http = require('http');
}
```

I set `platform` as `browser`


![image](https://user-images.githubusercontent.com/31695475/150901682-3a9076f7-58a8-4e50-a461-222ae574c141.png)


The code of else condition branch should not be bundled.

**Comment by evanw** [comment]
There is no special behavior associated with `process.browser` in esbuild. You can see everything that esbuild does when you apply `--process=browser` here: https://esbuild.github.io/api/#platform. You can `--define:process.browser=true` yourself if you'd like:

```
$ esbuild --bundle example.js
✘ [ERROR] Could not resolve "http"

    example.js:4:23:
      4 │   const http = require('http');
        ╵                        ~~~~~~

  The package "http" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.
```

```
$ esbuild --bundle example.js --define:process.browser=true
(() => {
  // example.js
  if (true) {
    console.log(1);
  } else {
    const http = null;
  }
})();
```

You can then use `--minify-syntax` to drop false branches (among other things) if you want to:

```
$ esbuild --bundle example.js --define:process.browser=true --minify-syntax
(() => {
  // example.js
  console.log(1);
})();
```
