### ISSUE TITLE
Prevent esbuild from removing an unused function when platform="node"

### ISSUE THREAD

**Issue by FlafyDev** [evanw/esbuild#1961]
I'm building my typescript file with `platform` equals to `node`.
I also have an unused function in that file that esbuild removes. If I reference this function somewhere(making it used), esbuild doesn't remove it.
So my question is: How can I make esbuild not remove the unused function without making it used?

**Comment by EMH333** [comment]
This happens because of "tree shaking" which is enabled by default in most cases (https://esbuild.github.io/api/#tree-shaking).

Set `treeShaking: false` in the esbuild options to disable this functionality (as shown in the docs).

**Comment by FlafyDev** [comment]
Thanks, that fixed it!
