### ISSUE TITLE
esbuild runtime introduces `exports` and `modules` which is not match with default browser env

### ISSUE THREAD

**Issue by atetubou** [evanw/esbuild#1964]
esbuild version: 0.14.12

When I apply esbuild to following code (derived from [CodeMirror](https://github.com/codemirror/CodeMirror/blob/b9e6190b3edf16fe959055c45807e06f833f9d1f/addon/runmode/runmode.js#L5-L10))
```js
(function() {
    if (typeof exports == "object" && typeof module == "object") // CommonJS
    { console.log("CommonJS"); }
    else if (typeof define == "function" && define.amd) // AMD
    { console.log("AMD"); }
    else // Plain browser env
    { console.log("browser") ;}
}());
```
like `esbuild --bundle a.js`, then esbuild generates following code
```js
(() => {
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __commonJS = (cb, mod) => function __require() {
    return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
  };

  // a.js
  var require_a = __commonJS({
    "a.js"(exports, module) {
      (function() {
        if (typeof exports == "object" && typeof module == "object") {
          console.log("CommonJS");
        } else if (typeof define == "function" && define.amd) {
          console.log("AMD");
        } else {
          console.log("browser");
        }
      })();
    }
  });
  require_a();
})();
```

In browser, original code shows `browser` while generated code shows `CommonJS`.

And I'm wondering whether esbuild can make `exports`/`module` variables match with browser env.

**Comment by hyrious** [comment]
I think what esbuild did is correct since it only accepts commonjs or es modules input. If you really want to detect browser env, use `typeof window !== undefined`.

**Comment by TimvdLippe** [comment]
@hyrious Unfortunately, this is third-party code (e.g. CodeMirror) that we include from NPM. Therefore, we are unable to change the implementation itself. We can file an upstream bug to CodeMirror to request them to change their implementation, but as far as I know, the snippet is not unique to CodeMirror. That is to say, the snippet is a common way of implementing UMD modules and I would reckon that CodeMirror is not the only NPM package that would become problematic. Would it be feasible to update esbuild to account for these configurations or do you think that is not possible?

For context: we are working on integrating esbuild in Chrome DevTools (WIP CL at https://crrev.com/c/3401984) and this is one of the blockers we identified.

**Comment by hyrious** [comment]
I see, maybe you are expecting the code in `console.log('browser')` take effects? Normally it is registering a global variable, then you can do that manually by re-ordering your entry files:

```js
// load-codemirror.js
import CodeMirror from 'codemirror'
(global || self).CodeMirror = CodeMirror

// code that depends on a global 'CodeMirror' variable
import 'load-codemirror.js'
CodeMirror.from(...)
```

**Comment by atetubou** [comment]
@hyrious Thank you for your advice.

I'll check whether we can apply [your suggestion](https://github.com/evanw/esbuild/issues/1964#issuecomment-1022132119) to our code.

**Comment by evanw** [comment]
This happens because esbuild's bundler only supports modules in either the CommonJS module format or in the ES module format. The CommonJS format has the following invariants:

* `require` is always a function
* `exports` is always an object
* `module` is always an object
* `module.exports` always starts off being equal to `exports`

Code in the CommonJS format should be able to rely on the invariants that come with the CommonJS format, so esbuild ensures those invariants are upheld. The module format that code comes in is independent from what that code does. A CommonJS module can contain code meant for the browser and an ES module can contain code meant for node.

What esbuild does here is not specific to esbuild. All other bundlers (Webpack, Parcel, and Rollup) do exactly the same thing (albeit in slightly different ways):

* Webpack

    ```js
    (function () {
      if (true) // CommonJS
      { console.log("CommonJS"); }
      else { }
    }());
    ```

* Parcel

    ```js
    "object" == typeof {} ? console.log("CommonJS") : 
      "function" == typeof define && define.amd ? console.log("AMD") : 
        console.log("browser");
    ```

* Rollup

    ```js
    var a$1 = {exports: {}};
    
    (function (module, exports) {
    (function () {
      { console.log("CommonJS"); }
    }());
    }());
    
    var a = a$1.exports;
    
    export { a as default };
    ```

All bundlers take the CommonJS path in your code example. So esbuild's behavior here is correct.

**Comment by atetubou** [comment]
We currently uses rollup with ES module mode, but rollup doesn't generate code having `function (module, exports)` like in your comment.

How do you apply rollup to the snippet?

If I run `rollup a.js --format esm`, it shows code like
```js
(function() {
    if (typeof exports == "object" && typeof module == "object") // CommonJS
    { console.log("CommonJS"); }
    else if (typeof define == "function" && define.amd) // AMD
    { console.log("AMD"); }
    else // Plain browser env
    { console.log("browser") ;}
}());
```

**Comment by hyrious** [comment]
@atetubou Rollup always treats input format as esm, unless you're using [@rollup/plugin-commonjs](https://github.com/rollup/plugins/blob/master/packages/commonjs).

**Comment by evanw** [comment]
Yeah sorry my test was done assuming `@rollup/plugin-commonjs` is active, which from what I understand is typically the case when people are using lots of npm packages (along with `@rollup/plugin-node-resolve`).

**Comment by atetubou** [comment]
Hmm, I see. We don't use `@rollup/plugin-commonjs` so we don't see this issue with rollup.

@hyrious can I ask you to elaborate [your suggestion](https://github.com/evanw/esbuild/issues/1964#issuecomment-1022132119)?

Currently our code can be simplified like
```js
// third_party.js
(function() {
    if (typeof exports == "object" && typeof module == "object") // CommonJS
    { console.log("CommonJS"); }
    else if (typeof define == "function" && define.amd) // AMD
    { console.log("AMD"); }
    else // Plain browser env
    { console.log("browser") ;}
}());
```
and
```js
// our_code.js
import './third_party.js';
```

Then bundle those with `esbuild --bundle our_code.js`. But I don't understand how I can apply your suggestion to this case.

**Comment by TimvdLippe** [comment]
You probably already know this, so forgive me if this is common knowledge, but the format used by CodeMirror (and various other popular NPM packages) is the UMD format: https://github.com/umdjs/umd This format is designed to work in all environments, regardless of the module format that imports the bundle. That is to say, if you were to use CommonJS in a Node environment, it would export itself as CommonJS. In our case, we use ES modules with the side-effect import listed in @atetubou comment above. In this case, the UMD module defines itself on the global, which would be equivalent to the `console.log("browser")`.

For CodeMirror, you can see its UMD definition in https://source.chromium.org/chromium/chromium/src/+/main:third_party/devtools-frontend/src/front_end/third_party/codemirror/package/addon/runmode/runmode-standalone.js;l=261-268;drc=e804c593423c50942b7d00793ca72f9254b116db which is generated by Rollup as its UMD module format: https://github.com/codemirror/CodeMirror/blob/b9e6190b3edf16fe959055c45807e06f833f9d1f/rollup.config.js#L16 (listed at https://rollupjs.org/guide/en/#outputformat and generated by https://github.com/rollup/rollup/blob/master/src/finalisers/umd.ts)

Another dependency of ours, Acorn, has the same setup: https://github.com/acornjs/acorn/blob/9899904395d67776a78702fe5640ea4bc12b9ec6/acorn/rollup.config.js#L9 and the format is relatively commonly used in libraries: https://github.com/search?l=&q=format%3A+%22umd%22+filename%3Arollup.config.js&type=code

Given the prevalence of the UMD format and given that Rollup by default (e.g. without any plugins) can handle imports to the format, would it be possible for esbuild to do the same?

**Comment by hyrious** [comment]
@atetubou You have to look at what happens in your `third_party.js`'s `browser` part, and then doing that manually by yourself. Normally it is assigning a global variable in common UMD format:

```js
import What './third_party.js'; // you have to checkout what `What` is
global.What = What
```

@TimvdLippe Although UMD is well-known, but this code pattern isn't obvious to be recognized by a js parser. Rollup can do this only because it never know any format other than ESM (without plugins). But detecting CJS is easy: just see if it is referencing global names like `module`, `exports` or even `this` in some aged packages.

**Comment by atetubou** [comment]
@hyrious ah, you are suggesting to copy [this part](https://github.com/codemirror/CodeMirror/blob/b9e6190b3edf16fe959055c45807e06f833f9d1f/addon/runmode/runmode.js#L12-L74) to our code?
I think we can do that, but I prefer to have local patch using `window` (and upstreaming that) following [your first suggestion](https://github.com/evanw/esbuild/issues/1964#issuecomment-1022007863).

**Comment by TimvdLippe** [comment]
@hyrious I understand detection might be possible. In that case, would it be possible to update esbuild to add a configuration that specifies "always assume all code is ESM"? E.g. do not try to emulate the CommonJS behavior, which would then get rid of the CommonJS snippet in the UMD definition and workaround the issue.

**Comment by evanw** [comment]
> would it be possible to update esbuild to add a configuration that specifies "always assume all code is ESM"?

This is already possible. One way to do that is use the `.mjs` extension on a per-file basis to indicate that a given file is ESM. Another way to do this more broadly is to put `"type": "module"` in `package.json` which indicates that all `.js` files are ESM. This is not something specific to esbuild. It's a standard convention from node: https://nodejs.org/dist/latest/docs/api/esm.html#enabling.

**Comment by TimvdLippe** [comment]
Thanks @evanw for the pointers. I am aware of these, but naively assumed they were Node-only and not specific to the browser (since browsers don't look at either the file extension or the `package.json`)

@atetubou That might be worth a try then. Renaming files is relatively more maintainable than having to maintain git patches of third-party content.

**Comment by evanw** [comment]
> I am aware of these, but naively assumed they were Node-only and not specific to the browser

It's not about whether the code is intended for node or not. Instead it's specific to the npm package format, which can contain code intended for both node and the browser.

**Comment by atetubou** [comment]
By changing file extention from `.js` to `.mjs`, we were able to avoid this issue. Although there is one pitfall that we also need to change `.d.ts` to `.mjs.d.ts` (@TimvdLippe knew this) in our case.

Thank you everyone discussing in this issue. I also greatly appreciate author of this tool as we see a lot faster build now.
