### ISSUE TITLE
Remove dynamic requires for externals from bundle entirely

### ISSUE THREAD

**Issue by noomly** [evanw/esbuild#1968]
My case is the following: I am using esbuild to bundle a small typescript project into a single file. This file will then be evaluated by some other program as a plugin. This other program injects into the bundle file the definition of a few functions/variables (that I am going to refer to as externals), which are used in the plugin.

I could just declare the externals in a `externals.d.ts` (as illustrated below) and then declare them in `.eslintrc.json` as globals so I can use them in my code without any errors and Typescript would be able to recognize them and provide typing.

```typescript
declare global {
    const SpecialError: ErrorConstructor;
    const specialFunction: (arg1: number, arg2: string) => void;
}
```

This is the solution I am currently using but I'm not satisfied with it because it means that Typescript will recognize them in other places in the project where they have no meaning and shouldn't be used.

The ideal way to introduce these externals would be locally, via an import, without introducing them into typescript's global scope and setting globals in eslint's config. So `externals.d.ts` would look like this:

```typescript
declare const SpecialError: ErrorConstructor;
declare specialFunction: (arg1: number, arg2: string) => void;
```

I would then be able to import the functions in the files that make use them like so:

```typescript
import { SpecialFunction } from "./externals";

specialFunction(0, "a dummy string");
```

However now esbuild will fail: `[ERROR] Could not resolve "./externals"`". I saw this suggestion below the error in the esbuild output: `You can mark the path "./externals"`. So in my build options I added the parameter `external; ["./externals"]` and esbuild was now bundling without complaining. Except that now, the bundled file was including the following snippets of code:

```javascript
  var __require = /* @__PURE__ */ ((x) => typeof require !== "undefined" ? require : typeof Proxy !== "undefined" ? new Proxy(x, {
    get: (a, b) => (typeof require !== "undefined" ? require : a)[b]
  }) : x)(function(x) {
    if (typeof require !== "undefined")
      return require.apply(this, arguments);
    throw new Error('Dynamic require of "' + x + '" is not supported');
  });

  // src/file1.ts
  var import_externals2 = __require("./externals");

  // src/file2.ts
  var import_externals = __require("./externals");

  // [...]
  
  (0, import_externals2.specialFunction)(0, "a dummy string"); 

  // [...]
```

Which breaks the plugin as esbuild seems to think that it has to import the functions from another file, while these externals are supposed to be directly injected into the code later. Instead, the behavior I am looking for is that esbuild would ignore the import to "./externals" and call `specialFunction` directly like so, without requiring any external files (as this is prohibited in the plugin system I'm using):

```javascript
specialFunction(0, "a dummy string"); 
```

Is there a way to tell esbuild to ignore the import to the externals and leave the calls as-is in the bundle?

**Comment by hyrious** [comment]
The use case you described is not a typical module system -- that's said, the _injecting_ behavior of the host program is breaking what modules be like. Thus you can not treat it as normal modules (regardless of the `external` config). While esbuild is expecting all input things are normal modules (cjs or esm), there's no such case for you to alter that.

Since the injected methods are in the global scope, I think what you tried first is correct since it _behaves_ in this way.

As an alternative choice, what you expected is silently removing those import statements when bundling with esbuild. In that case, you can just remove them in the esbuild [plugins](https://esbuild.github.io/plugins/#on-load)' onLoad callback:

```js
name: 'silently-remove-special-imports',
setup({ onLoad }) {
  const fs = require('fs')
  onLoad({ filter: /\.ts$/ }, async args => {
    let code = await fs.promises.readFile(args.path, 'utf8')
    code = code.replace(/^import .*"./externals"/gm, '/* erased */')
    return { contents: code, loader: 'default' }
  })
}
```

**Comment by noomly** [comment]
The solution you suggested is actually perfect for my case. Thank you!
