### ISSUE TITLE
Specify package.json engines.node (version compat) field

### ISSUE THREAD

**Issue by webketje** [evanw/esbuild#1970]
Hi there, great work on esbuild.
For [Metalsmith](https://github.com/metalsmith/metalsmith) I want to provide a generic JS compiling plugin and ESbuild fits better than other alternatives. However I need to make sure that the core plugins have a specific NodeJS compatibility.
In order to do so, I ran `npm info esbuild@latest engines.node` but this returns nothing.

Could you add to package.json
```js
"engines": {
  "node": ">=8.17.0"
}
```
I tested a dev mode build (no minification, no edge cases) with nvm on Node 8.17.0 and it worked. ESbuild might even support earlier versions.

**Comment by evanw** [comment]
I'm surprised that esbuild works with node 8. That reached end of life in 2019. I think it would be a bad policy for esbuild to spend resources supporting a dead platform.

The earliest node version that I'd consider officially supporting is node 12, which is currently in maintenance mode: https://nodejs.org/en/about/releases/. And it looks like node 12 will reach end of life in April of this year.

I could add `engines.node` and have that just be equal to node's current maintenance LTS version. Is that what you're looking for?

**Comment by webketje** [comment]
@evanw I just let you know that the current version does work with Node 8.17.0 (this probably depends on the options passed to the compiler you're using to convert the Go code). It's good practice to add an `engines.node` field, not sure whether it should reflect the *incidentally* or *actually* supported version, but following the LTS EOL is definitely good
