### ISSUE TITLE
Unexpected newline in string behaviour during minification.

### ISSUE THREAD

**Issue by JJMeijer** [evanw/esbuild#1972]
The following code does a split on `"\r\n"`. During minification the newline is changed to an actual newline in the code instead of the string. It's probably better to do the split with regex anyways, but as it only happens during minification I think it's unexpected behaviour.

Source
```ts
const str = '';
console.log(str.split("\r\n"));
```

Esbuild output
```js
(() => {
  // test.ts
  var str = "";
  console.log(str.split("\r\n"));
})();
```

Esbuild output minified
```js
(()=>{var o="";console.log(o.split(`\r
`));})();
```

**Comment by evanw** [comment]
That's expected. `\n` is two bytes and an actual newline is one byte. You asked esbuild to minify your code to make it shorter and that's what it's doing.

**Comment by JJMeijer** [comment]
I see. I now see that in this example this is indeed the correct result. 

In my actual project the eventual result is `\r ` with a space, and not a newline.

```js
onMessage(t){t.data.trim().split(`\r `).forEach(
```

**Comment by evanw** [comment]
How did the space get there? Are you perhaps running the output of esbuild through some other tool that handles JavaScript syntax incorrectly? Or is esbuild generating the space? If esbuild is generating the space, then please provide the problematic input to demonstrate the problem.

**Comment by JJMeijer** [comment]
Sorry for wasting your time. I was using a plugin ([esbuild-minify-templates](https://www.npmjs.com/package/esbuild-minify-templates)) which generated the space in their writing process. Thx for the help!
