### ISSUE TITLE
Finantial support

### ISSUE THREAD

**Issue by mixtur** [evanw/esbuild#1988]
Hello. Quite an amazing project you have there. Speedy bundler-minifier is indeed something that community was lacking for a while.

Also have my sincere kudos for the highly detailed changelog. This is the best I've ever seen in an open source project.

So the question is. Is there a way to support you financially? I am sure people will be happy to throw some money in your direction. I know I would.

**Comment by evanw** [comment]
That's thoughtful of you to offer, but there is deliberately no way to support the project financially. I understand that this is what a lot of open source project maintainers look for but it's not what I'm looking for.
