### ISSUE TITLE
Minify whitespaces removing `/* @__PURE__ */`

### ISSUE THREAD

**Issue by Xenfo** [evanw/esbuild#1990]
How do I prevent this behaviour? I need the comment to be there but the file to also be minified.

**Comment by hyrious** [comment]
As I know there's no way to keep it with `--minify-whitespace` currently. I'd recommend you to turn off minifying when exporting an esm library.

**Comment by Xenfo** [comment]
The other minify options are fine though?

**Comment by evanw** [comment]
Whitespace removal is intended for distribution to end users, in which case pure annotations are meaningless.

**Comment by evanw** [comment]
Closing as by design.
