### ISSUE TITLE
What is the recommended pattern to achieve the same behavior as the HtmlWebpackPlugin ? Add hash named assets to the index.html file

### ISSUE THREAD

**Issue by cbdeveloper** [evanw/esbuild#1995]
I'm just starting a new project and `esbuild` looks like a really good alternative to `webpack + babel`.

This is for a browser SPA React app.

I started configuring my project, but I still don't understand how I'm supposed to achieve the following behavior:

- I need to add a hash to my JS files, so I can long-term cache them on the browser and also be able to "invalidate" them, when their hash changes. That seems to be accomplished by configuring the [chunk names](https://esbuild.github.io/api/#chunk-names)

![image](https://user-images.githubusercontent.com/43407798/152749555-e7c98f32-3fc8-4aba-8727-843356a4775c.png)

- But I also need a way to insert those hash named assets into my `index.html` file. Something very similar to what the [HtmlWebpackPlugin](https://webpack.js.org/plugins/html-webpack-plugin/) does.

![image](https://user-images.githubusercontent.com/43407798/152749506-eb719e68-d769-40c4-9a8e-c8a39efd7e81.png)

Is it possible out of the box with some configuration?

I found this related issue https://github.com/evanw/esbuild/issues/96 but it seems that the current solution is to write custom script code to achieve the desired behavior.

Are you planning to support this feature?

**Comment by evanw** [comment]
> Is it possible out of the box with some configuration?

No.

> I found this related issue https://github.com/evanw/esbuild/issues/96 but it seems that the current solution is to write custom script code to achieve the desired behavior.

Yes you'll have to write some code to do this. Information about output files can be found using the `metafile` API: https://esbuild.github.io/api/#metafile.

> Are you planning to support this feature?

No plans at the moment.

**Comment by cbdeveloper** [comment]
Hey @evanw , thank you so much for your reply. I'll close the issue now.

Just out of curiosity, why aren't you considering to support this?

I'm not tryting to convince you otherwise, I would like to just hear your opinion on long-term caching for the generated JS bundles (especially for web apps), given the fact that `esbuild` outputs code for the browser by default. Maybe long-term caching for JS bundles is not as necessary as I think it is. What do you think?

**Comment by evanw** [comment]
It would be nice to have built in of course, but so would many other things. Every thing I add to esbuild takes work to build and work to maintain over time. I think it makes sense to round out esbuild's support for JS and CSS before adding yet another language target. The original issue for HTML support in esbuild is still open: #31.
