### ISSUE TITLE
How to suppress warnings when they are handled in the code?

### ISSUE THREAD

**Issue by vladmandic** [evanw/esbuild#1997]
I've updated `ESBuild` from **0.14.11** to **0.14.19** and noticed it added additional warnings such as:

    Import "node" will always be undefined because there is no matching export in "dist/tfjs.esm.js"
        src/warmup.ts:83:20:
          83 │     const data = tf['node'].decodeJpeg(img);

Which would be great except in cases where I have explicit handler and ignore directive for that in my code, but `ESBuild` does not follow ignore rules.

My code:

```js
  if ('node' in tf) {
    // @ts-ignore tf.node is undefined if target is browser
    const data = tf['node'].decodeJpeg(img);
    ....
  }
```

I don't want to reduce `logLevel` from *warning* to *error*, but I do want to suppress warnings for code where it's explicitly handled in the code.

I know `ESBuild` is not (and not intended to be) a full-blown linter, but if its throwing a non-critical (and in this case false) warning, I should be able to suppress it somehow.

Suggestions?

**Comment by vladmandic** [comment]
Tried that and it works, but that was I can suppress entire warning type which may not be desired as it's a good warning if it happens anywhere else. Or I can have a custom string parser in the JS build script for each file/line which would be horrible.

IMO, if neither ESLint nor TypeScripts are not complaining about this (since it has @ts-ignore), ESBuild shouldn't either.

**Comment by evanw** [comment]
Ok. I will remove the warning.

**Comment by mitranim** [comment]
I'd really like this warning back. Esbuild's ability to validate matching exports/imports is very useful when using plain JS rather than TypeScript.

**Comment by mitranim** [comment]
Clarification: I want it back as a warning, rather than debug. Warnings can be used to `exit 1` in a build.

**Comment by vladmandic** [comment]
> I'd really like this warning back. Esbuild's ability to validate matching exports/imports is very useful when using plain JS rather than TypeScript.

that's what `eslint` is for. and unlike pure build system like `esbuild`, it can be configured as user wishes and obeys inline overrides.

**Comment by mitranim** [comment]
I disagree. `esbuild` already has this functionality. It can easily expose it, without requiring another external tool. In addition, imports depend on module resolution rules. For an external tool like `eslint`, you have to duplicate the configuration, which may be incompatible. Also last time I checked, `eslint` didn't support import validation at all.

**Comment by vladmandic** [comment]
> Also last time I checked, eslint didn't support import validation at all.

Yes, it does. And works like a charm in realtime combined with VSCode.

> It can easily expose it, without requiring another external tool

Enabling this without the way to suppress it is a deal-breaker. And since there is no way to suppress such warnings (as ESLint does not follow conventions such as `// @ts-ignore` in the code), author decided to disable it by default. Yes, its a nice extra feature - but without means to use it properly, its a no-go. You want to have fully opinionated build tool that forces specific coding standard even if it works fine otherwise? This is not it.

**Comment by mitranim** [comment]
> Yes, it does. And works like a charm in realtime combined with VSCode.

Eslint doesn't have built-in import validation. [eslint-plugin-import](https://github.com/import-js/eslint-plugin-import) seems to be very unreliable. I've been unable to make it actually work, by which I mean the `named` rule actually validating that all imports and exports match. If there's something else, please let me know.

**Comment by vladmandic** [comment]
@mitranim if `eslint-plugin-import` is unreliable for you, why not report it and get it fixed there? it is actively maintained.

**Comment by mitranim** [comment]
Esbuild already has the import validation feature, which works well, is useful to many people, and doesn't require external tooling. Why would you force the user to resort to an external tool which, in turn, requires _another_ external tool, with additional configuration, and also doesn't work reliably and needs fixing? I fail to see why you would do this to Esbuild users.

**Comment by vladmandic** [comment]
i'm all for it *if* it can be configured by user - that's why tsc and eslint follow `//@...` code comment blocks.  
it cannot be forced on all users without any considerations.

**Comment by evanw** [comment]
As of [the latest release](https://github.com/evanw/esbuild/releases/tag/v0.14.42), you can now bring back this warning with `--log-override:import-is-undefined=warning`. You can also make it an error with `--log-override:import-is-undefined=error`.

**Comment by mitranim** [comment]
Thank you, that's a nice improvement. IMO it would be better to treat them as warnings or errors by default, and make suppression opt-in, because users may never discover the feature.
