### ISSUE TITLE
Dynamic require for css and svg files

### ISSUE THREAD

**Issue by ahmedAdel202090** [evanw/esbuild#1999]
if i am using dynamic require to upload css files dynamically for example: ``import(`./${variable}.css`)`` or ``let photo = require(`./${variable}.svg`)``
after bundling. it will show errors

=> Uncaught (in promise) TypeError: Failed to fetch dynamically imported module:
=> Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/css". Strict MIME type checking is enforced for module scripts per HTML spec.

**Comment by evanw** [comment]
Bundling dynamic imports is not supported by esbuild. This is documented: https://esbuild.github.io/api/#non-analyzable-imports.

**Comment by evanw** [comment]
Closing as out of scope.
