### ISSUE TITLE
What version ECMAScript esbuild can consume as input source?

### ISSUE THREAD

**Issue by scott1028** [evanw/esbuild#2003]
I try to find out what latest syntax I can use as a input source code for esbuild.
In babel I can use `preset-env`, but in esbuild I check the document Ref: https://esbuild.github.io/content-types/#javascript

I only can setup target(output) es version. I don't know what version ECMAScript esbuild can consume. How can I know it?

**Comment by hyrious** [comment]
🤣 Any version. Just without proposals that are not stable (e.g. the [decorators](https://github.com/tc39/proposal-decorators) in js).

**Comment by scott1028** [comment]
@hyrious 
I don't need to take care of `core-js` or other polyfill situation, right?

**Comment by hyrious** [comment]
Note that esbuild can only lowering your code to ES6 at most, and it won't polyfill the API (like <samp>Array.at</samp>). If you need these, you still have to post-process your final code with:

- To get ES6+ &rarr; ES5, use babel.
- To polyfill (or [ponyfill](https://github.com/sindresorhus/ponyfill)) global API, use core-js and/or other libraries (a good example here is [resize-observer](https://github.com/juggle/resize-observer)).

**Comment by evanw** [comment]
That's correct. Specifically, esbuild consumes "esnext" as input which to me means both:

* The [latest work-in-progress specification](https://tc39.es/ecma262/), which includes syntax-related [ECMAScript proposals](https://github.com/tc39/proposals) that have [reached stage 4](https://github.com/tc39/proposals/blob/main/finished-proposals.md).

* All relevant other new JavaScript syntax features that have been shipped by a major browser, by node, or by TypeScript. This includes some syntax-related ECMAScript proposals that have only reached stage 3, which is a decision I make on a case-by-case basis. This also includes random syntax features like [this one](https://github.com/tc39/ecma262/pull/2154) that are done outside of the proposal process.

As mentioned above esbuild only handles new JavaScript syntax, not new APIs. There is also the caveat that esbuild can only support the subset of TypeScript syntax features that [don't require a type system to implement](https://esbuild.github.io/content-types/#no-type-system).

**Comment by evanw** [comment]
Feel free to continue to discuss here, but I'm closing this because this isn't an open issue with esbuild and this question has been answered.
