### ISSUE TITLE
how to handle globals defined in non-modular files

### ISSUE THREAD

**Issue by CodeWithOz** [evanw/esbuild#2005]
I'm working on a webpage that has js files that don't provide esm exports, and they define global variables that other files depend on. Something like this:
```html
<!-- index.html -->
...
<script src="first.js"></script>
<script src="second.js"></script>
...
```

```js
/* first.js */
var someGlobalVariable = 'value';

/* second.js */
function anImportantFunc() {
  doSomethingWith(someGlobalVariable);
}
...
anImportantFunc();
```

The webpage does not use any UI framework.

I'm trying to minify these js files but the minifier understandably changes the names of the global variables without updating the other files that depend on them, so those other files throw errors when they hit undefined variables. Is there a way to make the minifier aware of this, possibly by specifying variables to ignore in some/all files? Similar to how eslint allows you to specify globals that shouldn't be marked as undefined. I understand this may be difficult because the files don't have clear dependency tree relationships in the way that modules have. Thanks.

**Comment by hyrious** [comment]
You can simply **concat** them first then let esbuild minify the all-in-one file.

**Comment by CodeWithOz** [comment]
@hyrious do you mean that I can use esbuild to concatenate the files? I can't seem to find docs or examples of that. The closest I've seen is [`inject`](https://esbuild.github.io/api/#inject) but it still relies on exports/imports, which my files do not use.

**Comment by hyrious** [comment]
No, you have to write some script to do that.

**Comment by evanw** [comment]
> I'm trying to minify these js files but the minifier understandably changes the names of the global variables without updating the other files that depend on them

That shouldn’t happen. Can you provide an example (code and esbuild command) that demonstrates this? The minifier is careful to preserve global variable names when no output format is selected. When an output format is selected then esbuild does minify global variable names, but that’s only because all supported output formats imply a local scope. And make sure you don’t have bundling enabled as that implicitly picks an output format.

**Comment by evanw** [comment]
Closing since this should already work, and there was no response to the question above. Format conversion and bundling both require modular files as input by design. You can only minify non-modular files with esbuild if you are not using format conversion or bundling.
