### ISSUE TITLE
Feature Request: Specify where to find an import file

### ISSUE THREAD

**Issue by mangelozzi** [evanw/esbuild#2008]
Firstly, what an awesome powerful tool. I have just been reading the documentation and it can do so much!

A handy feature when bundling, say you have a module that imports settings:

```
import { settings } from './settings.js';
```

Now say you build for DEV and for PROD, if DEV, then it must import from `./settings_dev.js`, and if prod from `./settings_prod.js`

Would be great if from the command line one could specify the logic of:
`find ./settings.js at: ./setting_dev.js`

Not within the settings file is the setting that tells it whether it is dev or prod, so one can't use dynamic imports (also not really  supported with service workers).

**Comment by davezuko** [comment]
Seems like you might be looking for https://esbuild.github.io/plugins/#on-resolve

> A callback added using onResolve will be run on each import path in each module that esbuild builds. The callback can customize how esbuild does path resolution. For example, it can intercept import paths and redirect them somewhere else.

**Comment by evanw** [comment]
You could also probably do this without a plugin using a custom condition and `package.json` imports: https://esbuild.github.io/api/#conditions.

**Comment by mangelozzi** [comment]
> You could also probably do this without a plugin using a custom condition and `package.json` imports: https://esbuild.github.io/api/#conditions.

That is perfect thank you!
