### ISSUE TITLE
expose profile flags  to js api

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#2013]
esbuild contains many debug flags for performance | memory profiler(like --timings, --cpuprofile), but it seems that these flags are only supported in cli, when integreate esbuild using js api in complex js tools, it is not easy to profile the esbuild parts.

**Comment by evanw** [comment]
Closing since I am deliberately not planning to expose these.

**Comment by hardfist** [comment]
can these flags be exposed by environment like ESBUILD_PROFILE、ESBUILD_TIMING ?
