### ISSUE TITLE
Detect when a source tree has been completed

### ISSUE THREAD

**Issue by Mwni** [evanw/esbuild#2017]
I have the following problem:

```
import App from './app.js'
import Extensions from 'internal:extensions'

new App([...], Extensions)
```

The `internal:extensions` code is generated by extracing specific "custom markup" code somewhere in the `app.js` source tree. These snippets are then transformed, composed and injected back via the `internal:extenions` import. 

**The issue:** I cannot tell when every import of the `app.js` tree has been resolved before resolving the extensions. I hack around this by waiting 1 second before resolving `internal:extensions` and hoping the app tree has resolved entirely.

Is there a way to tap into the internal workings of esbuild to know this?

**Comment by evanw** [comment]
> Is there a way to tap into the internal workings of esbuild to know this?

No. Even if you waited forever, the source tree won't be completed because your plugin is holding up the source tree from being completed.

**Comment by evanw** [comment]
Not really, although you could do two builds in succession. The first one would have `internal:extensions` as external or empty or something, and the second one could use the list of files from the first build.

**Comment by Mwni** [comment]
I was afraid of this. Nevertheless, thank you for your time and the library, Evan.

**Comment by hyrious** [comment]
I mentioned similar request in #1902. I'm not sure how your magic module works, but my situation is I have to scan files to get enough data to make a virtual module. It turns out that I could just add an option `glob` to search files instead of hacking into esbuild on-load callbacks.
