### ISSUE TITLE
Insecure runtime references in bundled code

### ISSUE THREAD

**Issue by eligrey** [evanw/esbuild#2024]
I've noticed code such as the following included in the bundles for [Transcend Consent](https://transcend.io/consent) built with esbuild. We target Edge 18, Safari 12.1, Chrome latest, and Firefox ESR latest for our builds.

<details><summary><strong>current esbuild output</strong></summary>
<p>

```ts
var __defProp = Object.defineProperty;
var __defProps = Object.defineProperties;
var __getOwnPropDescs = Object.getOwnPropertyDescriptors;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a, b) => {
  for (var prop in b || (b = {}))
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
var __spreadProps = (a, b) => __defProps(a, __getOwnPropDescs(b));
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};
var __accessCheck = (obj, member, msg) => {
  if (!member.has(obj))
    throw TypeError("Cannot " + msg);
};
var __privateGet = (obj, member, getter) => {
  __accessCheck(obj, member, "read from private field");
  return getter ? getter.call(obj) : member.get(obj);
};
var __privateAdd = (obj, member, value) => {
  if (member.has(obj))
    throw TypeError("Cannot add the same private member more than once");
  member instanceof WeakSet ? member.add(obj) : member.set(obj, value);
};
var __privateSet = (obj, member, value, setter) => {
  __accessCheck(obj, member, "write to private field");
  setter ? setter.call(obj, value) : member.set(obj, value);
  return value;
};
```

</p>
</details>

The following references are being used insecurely (i.e. are dynamically resolved) at runtime post-bundle execution:

- `WeakSet.prototype.{has, add}`
- `WeakMap.prototype.{has, get, set}`
- `WeakMap[Symbol.hasInstance]` / `Symbol[Symbol.hasInstance]`
- `Function.prototype.call`

Due to these insecure references, I've resorted to an [active intervention where our secure utils library freezes these properties by default](https://www.notion.so/transcend/Security-architecture-b7474ad00e7b4a828e84b3a9493c4e17#e3d6f659e0404f52bd1db95484a6e337), with an option to turn off the intervention in case it causes interference with a site. I would prefer if the code emitted by esbuild used secure runtime reference caching so that I wouldn't have to resort to active interventions.

If the emitted code looked like the following I could remove these specific anti-tamper interventions from Transcend Consent:

<details><summary><strong>expected esbuild output</strong></summary>
<p>

```ts
var call = Function.prototype.call.bind(Function.prototype.call);
var hasInstance = Symbol[Symbol.hasInstance];
var isInstance = (constructor, instance) => call(hasInstance, constructor, instance);
var { WeakSet, TypeError } = typeof globalThis !== 'undefined' ? globalThis : self;
var { has, get, set } = WeakMap.prototype;
var { add } = WeakSet.prototype;
var __defProp = Object.defineProperty;
var __defProps = Object.defineProperties;
var __getOwnPropDescs = Object.getOwnPropertyDescriptors;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a, b) => {
  for (var prop in b || (b = {}))
    if (call(__hasOwnProp, b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (call(__propIsEnum, b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
var __spreadProps = (a, b) => __defProps(a, __getOwnPropDescs(b));
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};
var __accessCheck = (obj, member, msg) => {
  if (!call(has, member, obj))
    throw TypeError("Cannot " + msg);
};
var __privateGet = (obj, member, getter) => {
  __accessCheck(obj, member, "read from private field");
  return getter ? call(getter, obj) : call(get, member, obj);
};
var __privateAdd = (obj, member, value) => {
  if (call(has, member, obj))
    throw TypeError("Cannot add the same private member more than once");
  isInstance(WeakSet, member) ? call(add, member, obj) : call(set, member, obj, value);
};
var __privateSet = (obj, member, value, setter) => {
  __accessCheck(obj, member, "write to private field");
  setter ? call(setter, obj, value) : call(set, member, obj, value);
  return value;
};
```

</p>
</details>

**Comment by evanw** [comment]
I'm not sure what you mean by "security" exactly (i.e. what the threat model is) but securing JavaScript evaluation against a hostile host environment is extremely difficult, is not something esbuild even remotely attempts to do, and is firmly out of scope for this project. The caching of references to built-in functions that esbuild currently does is only for better performance and improved minification. The changes you proposed would likely have negative performance consequences, so I don't think it makes sense to add them to esbuild even disregarding the security aspect.

**Comment by eligrey** [comment]
I don't think my changes would negatively affect performance at all, and to the contrary it may even improve performance. These methods are being implicitly called already; I'm just caching them better.

**Comment by eligrey** [comment]
All of the new references that I added to the example were the following lines:

```ts
var call = Function.prototype.call.bind(Function.prototype.call);
var hasInstance = Symbol[Symbol.hasInstance];
var isInstance = (constructor, instance) => call(hasInstance, constructor, instance);
var { WeakSet, TypeError } = typeof globalThis !== 'undefined' ? globalThis : self;
var { has, get, set } = WeakMap.prototype;
var { add } = WeakSet.prototype;
```

I updated the rest of the code in that example to use these methods together. It's not that significant of a paradigm shift and I think it should be encouraged to cache all runtime references even if only for performance. In my opinion this change does belong in esbuild as otherwise you are introducing *new* behavior by using dynamic runtime references like `.{call, has, get, set, etc}` instead of cached references.

**Comment by hyrious** [comment]
I don't think esbuild can avoid problems in insecure runtime by doing this, since there may be any codes run before/after the bundled result. For example, you may just hack to replace `Function.prototype.call` before the bundle.

Insecure runtime should be avoided by enforcing HTTPS or other works in similar layers. There's no way for a bundler to do this kind of work.

**Comment by evanw** [comment]
> I don't think my changes would negatively affect performance at all, and to the contrary it may even improve performance.

Here's a quick benchmark:

| | Current approach | Proposed approach |
|---|---|---|
| Benchmark time | 283ms | 601ms (2.1x slower) |

<details>
<summary>Click to show benchmark code</summary>
<p>

```js
// The current approach
function demoOld() {
  var __accessCheck = (obj, member, msg) => {
    if (!member.has(obj))
      throw TypeError('Cannot ' + msg);
  };
  var __privateGet = (obj, member, getter) => {
    __accessCheck(obj, member, 'read from private field')
    return getter ? getter.call(obj) : member.get(obj);
  };
  var __privateAdd = (obj, member, value) => {
    if (member.has(obj))
      throw TypeError('Cannot add the same private member more than once');
    member instanceof WeakSet ? member.add(obj) : member.set(obj, value);
  };
  var __privateSet = (obj, member, value, setter) => {
    __accessCheck(obj, member, 'write to private field');
    setter ? setter.call(obj, value) : member.set(obj, value);
    return value;
  };

  var total = 0;
  for (var i = 0; i < 1_000_000; i++) {
    var o = {};
    var member = new WeakMap();
    __privateAdd(o, member, 0);
    for (var j = 0; j < 5; j++)
      __privateSet(o, member, __privateGet(o, member) + 1);
    total += __privateGet(o, member);
  }
  return total;
}

// The proposed approach
function demoNew() {
  var call = Function.prototype.call.bind(Function.prototype.call);
  var hasInstance = Symbol[Symbol.hasInstance];
  var isInstance = (constructor, instance) => call(hasInstance, constructor, instance);
  var { WeakSet, TypeError } = typeof globalThis !== 'undefined' ? globalThis : self;
  var { has, get, set } = WeakMap.prototype;
  var { add } = WeakSet.prototype;

  var __accessCheck = (obj, member, msg) => {
    if (!call(has, member, obj))
      throw TypeError("Cannot " + msg);
  };
  var __privateGet = (obj, member, getter) => {
    __accessCheck(obj, member, "read from private field");
    return getter ? call(getter, obj) : call(get, member, obj);
  };
  var __privateAdd = (obj, member, value) => {
    if (call(has, member, obj))
      throw TypeError("Cannot add the same private member more than once");
    isInstance(WeakSet, member) ? call(add, member, obj) : call(set, member, obj, value);
  };
  var __privateSet = (obj, member, value, setter) => {
    __accessCheck(obj, member, "write to private field");
    setter ? call(setter, obj, value) : call(set, member, obj, value);
    return value;
  };

  var total = 0;
  for (var i = 0; i < 1_000_000; i++) {
    var o = {};
    var member = new WeakMap();
    __privateAdd(o, member, 0);
    for (var j = 0; j < 5; j++)
      __privateSet(o, member, __privateGet(o, member) + 1);
    total += __privateGet(o, member);
  }
  return total;
}

function time(fn) {
  let before = Date.now()
  fn()
  let after = Date.now()
  return after - before
}

// Warmup
demoOld()
demoNew()

// Benchmark
console.log(`demoOld: ${time(demoOld)}ms`)
console.log(`demoNew: ${time(demoNew)}ms`)
```

</p>
</details>

**Comment by eligrey** [comment]
We have a pretty large project written on top of a 2K+ SLOC utils library that was written "differently" as you say. The abstractions make the rest of our code look normal to us, and I would implore you to explore the JIT performance results more thoroughly. Perhaps even the order of those tests could affect the JIT as they aren't being run in complete isolation

**Comment by eligrey** [comment]
@evanw If it ends up being clear that this will noticeably slow down any performance-critical projects, would you accept pull requests that create an optional flag for a 'more secure but slower' mode?

**Comment by eligrey** [comment]
@evanw Having a 'do something more securely' lever isn't a guarantee, and I wasn't asking for you to make any security guarantees. You may be overthinking the implications here.

We're going to keep freezing the properties that are being dynamically resolved at runtime for now as that does mitigate our security concerns (at the cost of potential interference with other code).
