### ISSUE TITLE
Android binaries

### ISSUE THREAD

**Issue by guiprav** [evanw/esbuild#204]
I sometimes like using Termux to code on-the-go on my Android phone, but there are no binaries available for that platform.

Considering we have linux-arm64, how hard would it be to get it working on android-arm64 as well?

I wanted to try myself, but my phone is short on storage space and golang/ndk stuff take almost 600 MiB, so I couldn't.

But would be interesting knowing what you think about this :)

**Comment by evanw** [comment]
It should be easy to get esbuild working on other platforms, but I don't want to start shipping a binary without someone at least verifying that it works it on the platform in question first. I used to have an Android device but the hardware died, so I can't test it myself at the moment. If you or someone else does get the chance to test it and can verify that it works, I'm happy to start shipping the binary. See #146 for an example of how to add support for a new platform to esbuild.

**Comment by guiprav** [comment]
Thanks, Evan. I'll see if I can free some space up and give it a shot. I'll let you know.

**Comment by egoist** [comment]
Since Android requires NDK for cross compiling and currently new releases are published manually, I'm not sure if it's a good idea to add Android binary build in the core repo. Alternatively you can use gobinaries.com by @tj to build it on the fly for Termux:

```bash
curl -sf https://gobinaries.com/evanw/esbuild/cmd/esbuild | PREFIX=/data/data/com.termux/files/usr/bin/ sh
# then run `esbuild`
```

**Comment by evanw** [comment]
Ah ok. Yeah if the compilation process isn't straightforward then I don't think it belongs in esbuild core. Glad to know there's an easy workaround.

**Comment by sayantan300** [comment]
Hello, can I actually give it a short? I use android with termux and luckily got a lot of storage here, I might want to build this if you all guys want to 😁

**Comment by sayantan300** [comment]
> 

Lemme quickly try that out ;)

**Comment by sayantan300** [comment]
ah so, ran that, esbuild runs now :+1:
