### ISSUE TITLE
Procedure to fix old code

### ISSUE THREAD

**Issue by resistorsoftware** [evanw/esbuild#2040]
I have some older code that runs out of node_modules. This older code throws an exception when esbuild does its thing.

The offending line is:

    import { Controller } from 'stimulus';

And hat causes the build to fail.

    node_modules/stimulus-flatpickr/dist/index.m.js:1:27:
    13:59:49 js.1 | 1 │ import { Controller } from 'stimulus';

The message is to "make it external" and the problem will go away. The thing that fixed this for me was, I had to change the line of code to be 

    import { Controller } from '@hotwired/stimulus';

And voila... all my problems go away. Obviously that is easy for me to do in the node_modules on my machine, but when I push to the cloud, I lose that edit, and the old code is pulled in and used in the build there. How do people function so that when a node_module is updated locally, the build in the cloud will also be updated the same way? 

Can esbuild help me with this problem? Is that one of things it is good at? If so, is there a simple explanation as how I might accomplish the task.

**Comment by evanw** [comment]
Maybe that's what https://www.npmjs.com/package/patch-package does? You could also do this with an esbuild plugin at build time: https://esbuild.github.io/plugins/.

**Comment by resistorsoftware** [comment]
That is a couple of days of reading right there, but it sounds promising. So much work for a one-line swap! Thanks for the links.

**Comment by evanw** [comment]
A plugin is pretty simple. Might look something like this (not tested):

```js
let examplePlugin = {
  name: 'example',
  setup(build) {
    build.onResolve({ filter: /^stimulus$/ }, args =>
      ({ path: '@hotwired/stimulus', external: true }))
  },
}
```

**Comment by resistorsoftware** [comment]
My package.json has a build line:
    "build": "esbuild app/javascript/*.* --bundle --outdir=app/assets/builds",

So I am assuming I would not use that anymore. I would instead execute some JS file? I wrote a quick and dirty one, a build.js in my project root.

```// "build": "esbuild app/javascript/*.* --bundle --outdir=app/assets/builds",

let stimulusPlugin = {
  name: 'fix stimulus',
  setup(build) {
    build.onResolve({ filter: /^stimulus$/ }, args =>
      ({ path: '@hotwired/stimulus', external: true }))
  },
}

require('esbuild').build({
  entryPoints: ['app/javascript/*.*'],
  bundle: true,
  outdir: 'app/assets/builds',
  outfile: 'application.js',
  plugins: [stimulusPlugin],
}).catch(() => process.exit(1))
```

When I run my Procfile.dev the build happens, no errors get spit out... 
    js: yarn build --watch

My package.json build statement is now:

    "build": "build.js",

But I am noticing that as I edit my JS files, the build is not happening. The --watch is not triggering a rebuild. I guess I am doing something really dumb.

**Comment by strobilomyces** [comment]
Not to detract from this discussion, but if you only want to do this for stimulus-flatpickr, there's already a pre-release with a fix: https://github.com/adrienpoly/stimulus-flatpickr/issues/83

**Comment by resistorsoftware** [comment]
@strobilomyces I appreciate that now! You are correct. I dug into their issues, and that issue was solved some time ago with a release to a version 3.0 from 1.4 of that code!! Cow-a-bunga! 

But this just once again reminds me of how poor JS tooling is, as the yarn add command just gave me the old version and not the new one. What a bunch of malarky. One assumes a command gives you the latest greatest when it mostly does, but when it does not, that sucks!! 

Anyway, I am all good now, and I have no need for a plugin adventure now.
