### ISSUE TITLE
Add more options to serve

### ISSUE THREAD

**Issue by majidsajadi** [evanw/esbuild#2053]
I know 

> esbuild is not meant to be an all-in-one solution for all frontend needs

but since the serve is suppose to be used as a simple dev server, is there any plan for adding some essential features such as proxy?

**Comment by evanw** [comment]
I don't have any plans for building this into esbuild itself. It's already straightforward to use esbuild with a proxy, as is documented here: https://esbuild.github.io/api/#customizing-server-behavior.
