### ISSUE TITLE
vite 启动

### ISSUE THREAD

**Issue by darkcityX** [evanw/esbuild#2055]
![image](https://user-images.githubusercontent.com/36305044/155646534-61a4351d-490c-45e9-b981-494b8c513f33.png)

**Comment by hardfist** [comment]
maybe you should raise issue in vite

**Comment by evanw** [comment]
That error comes from the file system, not from esbuild. You will have to debug for yourself why you are getting `Access is denied`. For example, you may have set file system permissions incorrectly.

**Comment by evanw** [comment]
Closing as unactionable.
