### ISSUE TITLE
CSS minifier transforms `translate3d(0,0,0)` to `translate(0)`, breaking layouts in Safari 

### ISSUE THREAD

**Issue by stephband** [evanw/esbuild#2057]
ESBuild's CSS minifier transforms `translate3d(0,0,0)` to `translate(0)`. Unfortunately in Safari `translate3d(0,0,0)` is a useful hack, forcing it to respect `z-index` layering correctly, where `translate(0)` does not have the same effect.

**Comment by stephband** [comment]
Looking at the code I notice the minifier is doing a whole bunch of things to 3d transforms. The problem with this is as CSS authors we use 3d transforms to deliberately trigger hardware acceleration, as well as to solve rendering problems in Safari. I would really rather ESBuild was not messing with these:

https://github.com/evanw/esbuild/blob/2734bbf97b4bc5951d49ebb4193c41277d83a301/internal/css_parser/css_parser_test.go#L1585-L1595

**Comment by evanw** [comment]
Please provide a small test case that demonstrates a rendering difference.

**Comment by yisibl** [comment]
Indeed, this conversion is not safe.
For related background take a look at: https://developpaper.com/what-you-need-to-know-about-the-css-will-change-property/

**Comment by stephband** [comment]
Here is a test case:

https://stephen.band/test/css-transform.html

And here is a screenshot of that page, scrolled to half-way down in Safari:

<img width="611" alt="Screenshot 2022-03-03 at 00 10 31" src="https://user-images.githubusercontent.com/69022/156465491-73ea3476-1693-4862-a7e2-72708409b4a4.png">

The orange and yellow blocks both have 100% height, relative position, and a greater z-index than the red block. Yet here we see the red block over the top of the yellow. This never happens to the orange block. The yellow block has `transform: translate(0)` while the orange block has `transform: translate3d(0, 0, 0)`.

**Comment by evanw** [comment]
Thanks for the test case. I was able to reproduce the bug. I verified that the following transforms trigger the bug in Safari:

- `matrix3d`
- `perspective`
- `rotate3d`
- `rotateX`
- `rotateY`
- `scale3d`
- `scaleZ`
- `translate3d`
- `translateZ`

and the following transforms do not:

- `matrix`
- `rotate`
- `rotateZ`
- `scale`
- `scaleX`
- `scaleY`
- `skew`
- `skewX`
- `skewY`
- `translate`
- `translateX`
- `translateY`

**Comment by Primajin** [comment]
I think this is good (that we no longer transform 3D into 2D) as one can use a 3D transform (often with 0,0,0) to just force the rendering being made by the GPU.

**Comment by stephband** [comment]
@evanw Hi. I have now been able to deploy these changes to production and can confirm it fixes all our woes. Thank you very much for your help, and for ESBuild, which rocks.
