### ISSUE TITLE
Object spread is supported in Node >= 8.3 but polyfilled by esbuild

### ISSUE THREAD

**Issue by tinovyatkin** [evanw/esbuild#2060]
Object spread syntax is supported in Node starting 8.3 (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax#browser_compatibility) but esbuild currently outputs `__spreadValues` polyfill for anything higher than `--target=node8.3.0` (I've checked with `node16` also) - see [repl](https://hyrious.me/esbuild-repl/?version=0.14.23&mode=transform&input=const+a+%3D+%7B+F%3A+%27ee%27+%7D%0Aconst+b+%3D+%7B+...a%2C+E%3A+%27eee%27+%7D&options=--target%3Dnode8.3.0)

Compare the output with `--target=es2018` that is what we should get for the Node target.

**Comment by evanw** [comment]
This is deliberate. V8's native implementation of object spread is being avoided because it has performance issues. See also: #951, #1365, #1583.
