### ISSUE TITLE
Cross-module dead code elimination of constant doesn't work with defines

### ISSUE THREAD

**Issue by vlovich** [evanw/esbuild#2061]
Hmm.... I think I must be doing something wrong. I'm trying to take advantage of #1981 in 0.14.19. have a `constants.ts` file like this:
```
declare global {
  const __IS_PRODUCTION_BUILD__: boolean
}
export const isProductionBuild = __IS_PRODUCTION_BUILD__
```

In build.mjs I have:
```
...
define: {
  __IS_PRODUCTION_BUILD__: process.env.NODE_ENV === 'production'
}
...
```

I've used `isProductionBuild` in my code like so:
```
// Workaround for https://github.com/cloudflare/miniflare/issues/191
import { isProductionBuild } from './constants'

function isDateInstance(value: any): value is Date {
  if (!isProductionBuild) {
    return value instanceof Date || (typeof value === 'object' && value.constructor.name === 'Date')
  }
  return value instanceof Date
}

function someFunction(value: any) {
   if (isDateInstance(value)) {
     ...
   }
}
```

I would expect that the conditional `if (isDateInstance(value))` gets minified to `if(value instanceof Date)` in a production build. Instead I see:
```
function KA(e){return!0?e instanceof Date:e instanceof Date||e instanceof Object&&e.constructor.name==="Date"}
```
and later
```
if(KA(t))
```

**Comment by evanw** [comment]
General function inlining like this is not an optimization that esbuild does. This is documented here: https://esbuild.github.io/api/#minify-considerations. You are welcome to use another tool instead if you need this optimization.

**Comment by vlovich** [comment]
Fine, but it's still not inlining the constant as intended right?.
```
function isWorkaroundDateInstance(value: any): value is Date {
   return value instanceof Date || (typeof value === 'object' && value.constructor.name === 'Date')
}

if (value instanceof Date || (!isProductionBuild && isWorkaroundDateInstance(value) {
}
```

becomes
```
if(t instanceof Date||!!0&&KA(t))
```
rather than
```
if(t instanceof Date)
```

It's failing to recognize that `!!0&&anything` can be stripped because it will never evaluate to true.

**Comment by evanw** [comment]
This is also in the documentation. What you are referring to is the "Cross-statement constant propagation" bullet point. You can read more about why this limitation exists here: https://github.com/evanw/esbuild/issues/2006#issuecomment-1034076043.

**Comment by evanw** [comment]
This is a known design limitation. The best way to do this is to avoid indirection through another variable, as described above. Closing as "won't fix."
