### ISSUE TITLE
define and boolean elimination

### ISSUE THREAD

**Issue by Conaclos** [evanw/esbuild#2063]
Hi!

I would like to thank you again for esbuild and its excellent documentation (including the CHANGELOG).

I use esbuild as the main tool to build my libraries. Usually I have two builds:
- a debug/test build
- a production build (the published one)

In my code I generally extensively use assertions (pre- and post- conditions). I would like to remove these assertions in the production build. The only way I know to achieve it with esbuild is to use a constant such as DEBUG:

```js
// @filename index.js
import { assert } from "assert-mod"
export function sqrt(x) {
  DEBUG && assert(x >= 0);
  return Math.sqrt(x);
}
```

and set DEBUG to false (or 0) for the production build:

```sh
esbuild --bundle index.js --define:DEBUG=false --format=esm --external:assert-mod
```

However, esbuild emits the following code:

```js
import { assert } from "assert-mod";
function sqrt(x) {
  false;
  return Math.sqrt(x);
}
export {
  sqrt
};
```

Note the apparition of an expression-statement `false;`.

Do you think it could be possible to improve a bit the dead-code elimination in order to remove also the boolean constant? The emitted code could be:

```js
function sqrt(x) {
  return Math.sqrt(x);
}
export {
  sqrt
};
```

Note that I would like to **avoid minification** to keep a readable code.

## Alternative solution

Another solution could be to add a `--drop:assert`.

**Comment by evanw** [comment]
> The emitted code could be:
>
> ```js
> function sqrt(x) {
>   return Math.sqrt(x);
> }
> export {
>   sqrt
> };
> ```

No. The external import of `assert-mod` must be kept because it may have side effects. Dropping that import would be incorrect.

**Comment by Conaclos** [comment]
Ah yes I forgot to add the import. However, it is not the proposal of the issue: the proposal is to remove the useless boolean constant.

In other words, instead of emitting:

```js
import { assert } from "assert-mod";
function sqrt(x) {
  false;
  return Math.sqrt(x);
}
export {
  sqrt
};
```

esbuild could emit:

```js
import { assert } from "assert-mod";
function sqrt(x) {
  return Math.sqrt(x);
}
export {
  sqrt
};
```

Diff between the two versions:

```diff
import { assert } from "assert-mod";
function sqrt(x) {
-  false;
  return Math.sqrt(x);
}
export {
  sqrt
};
```

**Comment by Conaclos** [comment]
Thanks!
