### ISSUE TITLE
Subpath import uses Node.js version of sources when bundling for web

### ISSUE THREAD

**Issue by ottokruse** [evanw/esbuild#2065]
I'm using subpath imports (https://nodejs.org/api/packages.html#subpath-imports) to make a code base work in both browser and Node.js. This is in my package.json:

```
    "imports": {
        "#node-web-compat": {
            "browser": "./node-web-compat-web.js",
            "import": "./node-web-compat-node.js"
        }
    }
```

My source files import `"#node-web-compat"`, which should then dynamically use either `"./node-web-compat-web.js"` or `"./node-web-compat-node.js"`.

This work in Node.js and also in webpack (a quick web app I launched with CreateReactApp works) but bundling with esbuild seems to always use the Node.js version, even when bundling for browser:

`npx esbuild dist/esm/index.js --bundle --format=esm`

Throws:
```
✘ [ERROR] Could not resolve "crypto"

    src/node-web-compat-node.ts:6:57:
      6 │ import { createPublicKey, createVerify, KeyObject } from "crypto";
        ╵                                                          ~~~~~~~~

  The package "crypto" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

✘ [ERROR] Could not resolve "stream"

    src/https-node.ts:8:25:
      8 │ import { pipeline } from "stream";
        ╵                          ~~~~~~~~

  The package "stream" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

✘ [ERROR] Could not resolve "util"

    src/https-node.ts:9:28:
      9 │ import { TextDecoder } from "util";
        ╵                             ~~~~~~

  The package "util" wasn't found on the file system but is built into node. Are you trying to
  bundle for node? You can use "--platform=node" to do that, which will remove this error.

3 errors
```

The files mentioned in the error are in my `/src` dir, but I was esbuilding `/dist/esm/index.js` which is also curious. (Same result if I do `npx esbuild src/index.ts --bundle` by the way)

**Comment by evanw** [comment]
I can't reproduce this myself. You'll need to provide the source code for this to be actionable.

You could try debugging this for yourself using `--log-level=verbose`, which will hopefully print enough information to explain what's happening.

**Comment by ottokruse** [comment]
Thanks, verbose logging did reveal good insights.

Was able to make it work by adding this to the package.json:

```
  "browser": {
    "#node-web-compat": "./dist/esm/node-web-compat-web.js"
  },
```

Would have been great if it had already worked with the subpath imports (https://nodejs.org/api/packages.html#subpath-imports) that I had in my package.json. It looks like `esbuild` outright ignores that field in package.json -- is this something you'd ever wanna support? (Do not wish to annoy you but apparently webpack supports it)

Anyway thanks for your help and for your effort building and maintaining `esbuild`.

**Comment by evanw** [comment]
They should already work:

```
$ cat package.json 
{
  "imports": {
    "#node-web-compat": {
      "browser": "./node-web-compat-web.js",
      "import": "./node-web-compat-node.js"
    }
  }
}

$ cat node-web-compat-web.js 
console.log('web')

$ cat node-web-compat-node.js 
console.log('node')

$ cat index.mjs 
import "#node-web-compat"

$ esbuild --bundle index.mjs | node
web
```

This was added in version 0.13.9 (see #1691). If it's not working as expected, I'm going to need the source code of an example demonstrating the problem to be able to fix it.

**Comment by ottokruse** [comment]
I have a minimal reproduce sample here: https://github.com/ottokruse/esbuild-subpath-imports

I'll do my own digging too. Maybe the reason is I'm adding TypeScript to the mix. Maybe the tsconfig file `paths` overrides the package.json imports?

Appreciate your help

**Comment by ottokruse** [comment]
After some more playing I can confirm the issue goes away if I remove the tsconfig file, or remove `baseUrl` and `paths` from it (but in the latter case my IDE starts showing errors and `npx tsc` no longer works).

Which actually solves my issue ... because I was just `esbuild`ing to see if my npm package would be `esbuild`able by it's users, and I just verified it will, since the tsconfig.json and ts sources are not included in the npm package.

**Comment by ottokruse** [comment]
Since TS doesn’t properly support subpath imports, it will probably be impossible to make this work more robustly in esbuild.
https://github.com/microsoft/TypeScript/issues/44848
