### ISSUE TITLE
Emitting multiple "file" results in a loader

### ISSUE THREAD

**Issue by EmielM** [evanw/esbuild#2072]
Apologies if this is too much of a question, but I've searched quite extensively and it seems a common use case -- to me at least :). If this is out of scope here, feel free to close -- at least I hope this post could help others wondering off in this direction.

My use case is supporting an asset loader of the form `import a from 'asset:myImage?100x200`. I'd like this to generate code to contain metadata (`{height: 100, width: 200, hashes: ["xxx", "yyy", "zzz]}`), where the hashes refer to emitted assets (included in the out/ dir) in different resolutions.

What would be a reasonable/idiomatic approach? It seems I can't emit (extra) output files programmatically from the loader. The `UniqueKeyForFileLoader` is accessible from go only, and ostensibly only using the 'file' loader.

I prototyped with creating a larger dependency tree: the plugin initially resolves+loads code for`/^asset:/` that would then generate `import 'realasset:...` code for each file that needs to be emitted (included in out/). A second resolve+load handler would handle these import urls and translate to the correct 'file' loader.

Protocode:
```js
build.onResolve({filter: /^asset:/}, async (args) => {
  const [file, ops] = args.path.slice(6).split('?');
  return {
    path: file,
    namespace: 'asset',
    pluginData: { ops, origInclude: args.path },
  };
});

build.onLoad({filter: /.*/, namespace: 'asset'}, async (args) => {
  // TODO: generate asset from args.path, and args.pluginData.ops,
  // save payload in data & determine proper metadata
  const data = "myAssetPayload", width = 100, height = 200;
  const metadata = {
    path: args.path,
    width,
    height,
  };
  return {
    contents: `import file from 'real${args.pluginData.origInclude}'; export default {...${JSON.stringify(metadata)}, hashes: [file]};`,
    pluginData: {data},
  };
});

build.onResolve({filter: /^realasset:/}, (args) => {
  console.log("realasset resolve", args);
  const [file] = args.path.slice(11).split('?');
  return {
    path: file,
    namespace: 'realasset',
    pluginData: args.pluginData,
  }
});

build.onLoad({filter: /.*/, namespace: 'realasset'}, (args) => {
  console.log("realasset load", args);
  return {
    contents: args.pluginData.assetData,
    loader: 'file',
  };
});
```

This feels unnecessarily complex and also inefficient, because we already (need to) build the different resolutions in the initial "asset" loader to generate the metadata. Also passing the asset data around as pluginData to the realasset handler.... well. Finally I have a nagging a feeling this breaks some serious cache assumptions (eg when doing incremental bundling).

Any insights :)? Thanks!

**Comment by evanw** [comment]
> I prototyped with creating a larger dependency tree

This is the intended way to do this.

> I have a nagging a feeling this breaks some serious cache assumptions

That's not true. Making these assumptions about plugin behavior would break plugins like this, which is why esbuild does not make such assumptions. Doing so would be incorrect. Plugins are always run and have to take care of all caching by themselves, since only they know how to do that correctly: https://esbuild.github.io/plugins/#caching-your-plugin.

**Comment by EmielM** [comment]
Thank you!
