### ISSUE TITLE
Ignore type-only entries in `paths` TypeScript compiler option

### ISSUE THREAD

**Issue by shroudedcode** [evanw/esbuild#2074]
_Based on https://github.com/evanw/esbuild/issues/2070#issuecomment-1057028107_

Currently, ESBuild uses TypeScript's `paths` compiler option to resolve source files which can lead to problems if the said option is only used to fix typing-related issues. That's because in those cases the destination paths will be `.d.ts` files which either [result in parsing issues](https://github.com/evanw/esbuild/issues/2070) or the package not being imported (because the file is handled like an empty file).

### Reproduction

The issue can be reproduced by cloning [this repo](https://github.com/shroudedcode/esbuild-tsconfig-paths-issue-repro), installing the dependencies, and then running the `bundle` and `bundle:paths` scripts. Right now the latter will fail because [this fix](https://github.com/evanw/esbuild/commit/50dc6ae99a7e055eeb41ec9e06cb8ba8c28ec71d) isn't released yet. Once it is released it will no longer fail, but produce incorrect output as the bundle will no longer include the imported package (just `void 0`).

### Possible fix

This could be fixed by ignoring all `types` entries ending in `.d.ts` as developers will never expect those to actually resolve to a source file at build time.

/cc @magic-akari

**Comment by magic-akari** [comment]
I am willing to fix it.
