### ISSUE TITLE
Function arguments do not match local inspect options

### ISSUE THREAD

**Issue by brianmhunt** [evanw/esbuild#2076]
It seems that in some circumstances function arguments use the global variable names.  For example:

```ts
// one file
const r: number = 1

// another file
function x (r: number) {
  // r transpiles as `function (r2) { ... }`
}
```

I _presume_ the reproduction/cause is trivial here, but I can elaborate if needed.

This exhibits as a problem when debugging.  Specifically, if one tries to access `r` or add breakpoints/logpoint based on `r` it'll use the global, rather than the local function argument.  This is not the expected/desirable behaviour.  The workaround is for developers to look into the `Scope => Local` in DevTools to see what the variable actually is named, which is not obvious/intuitive and adds cycles.

It would be better if the transpiled output honoured the function argument names.  For example:

```ts
// Given:
function x (r) { console.log(r) }

// Current
function x (r2) { console.log(r2) }

// Desirable example
function x (params) { const { r } = params; console.log(r) }
```

There are other options e.g.
1. a globals object so the global is accessed as `g.r` 
2. a prefix `g_r` for the global

Thank you, esbuild is looking amazing!

**Comment by brianmhunt** [comment]
@evanw I wonder if this is resolved with https://github.com/evanw/esbuild/issues/1296.

When I get a chance I'll check it out and if it is I'll close this issue, but if you feel it's definitely resolved please feel free to close this.

**Comment by privatenumber** [comment]
Sounds like your request is actually about the transpiled code, but if you're using source-maps, then yes https://github.com/evanw/esbuild/issues/1296 fixes it:

- [REPL](https://hyrious.me/esbuild-repl/?version=0.15.5&mode=transform&input=%2F%2F+one+file%0Aconst+r%3A+number+%3D+1%0A%0A%2F%2F+another+file%0Afunction+x+%28r%3A+number%29+%7B%0A++%2F%2F+r+transpiles+as+%60function+%28r2%29+%7B+...+%7D%60%0A%7D&options=--loader%3Dts+--sourcemap)

- [Source Map Visualization](https://evanw.github.io/source-map-visualization/#MzIAY29uc3QgciA9IDE7CmZ1bmN0aW9uIHgocjIpIHsKfQoyNzYAewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsiPHN0ZGluPiJdLAogICJzb3VyY2VzQ29udGVudCI6IFsiLy8gb25lIGZpbGVcbmNvbnN0IHI6IG51bWJlciA9IDFcblxuLy8gYW5vdGhlciBmaWxlXG5mdW5jdGlvbiB4IChyOiBudW1iZXIpIHtcbiAgLy8gciB0cmFuc3BpbGVzIGFzIGBmdW5jdGlvbiAocjIpIHsgLi4uIH1gXG59Il0sCiAgIm1hcHBpbmdzIjogIkFBQ0EsTUFBTSxJQUFZO0FBR2xCLFNBQVMsRUFBR0EsSUFBVztBQUV2QjsiLAogICJuYW1lcyI6IFsiciJdCn0K) (Hover over `r2`)

**Comment by brianmhunt** [comment]
Thanks @privatenumber I didn't know about that replication system.  We're seeing bugs in the sourcemap name and that looks like the perfect place to replicate (and then I'll report here / in a new issue).

**Comment by privatenumber** [comment]
I think what you're describing is more of a limitation with Chrome's console not being able to map variables to the ones in the source map:

https://github.com/esbuild-kit/tsx/issues/98#issuecomment-1254625677

**Comment by evanw** [comment]
I'm closing this issue because this is a known limitation of source maps, and I don't want to expand esbuild's scope to try to add hacks like this to the generated code to try to improve debugger support. The source maps that esbuild generates now include `names` mappings, so arguably this is something that the debugger could now implement itself if they chose to do this.

**Comment by brianmhunt** [comment]
Thanks @evanw .

For ease of reference / future readers, this has been a bug/omission in Chromium for what looks to be around 7 years, but looks to be down to only one blocker. [1]

There doesn't seem to be an issue for Bugzilla / Mozilla, that I could find. [2]

[1] https://bugs.chromium.org/p/chromium/issues/detail?id=327092
[2] https://bugzilla.mozilla.org/buglist.cgi?quicksearch=names+sourcemap yields no results.
