### ISSUE TITLE
Using es-style import in a commonjs module leads to runtime error 

### ISSUE THREAD

**Issue by janlent1** [evanw/esbuild#2078]
Hi,
Our company is using webpack with babel for js(x) and ts-loader for ts(x). Since the author of ts-loader advertised for migrating at least to the esbuild-loader, I am trying to migrate the logic to there. Most seems to work except one problem that I encounter, and since this is a large codebase, encounter quite often. Currently the build is stuck without any error message because it is swallowed somewhere. Since this sounds fixable and a requirement for porting larger codestacks to esbuild/esbuild-loader, I am opening this issue:
We have a lot of legacy code and the module style is sometimes mixed. When we have a `module.exports` at the end, but an es-style `import` at the top, the esbuild-loader will run without throwing an error but during runtime this error is thrown:
`Uncaught (in promise) Error: ES Modules may not assign module.exports or exports.*, Use ESM export syntax`
When I rewrite the code and use a `require` instead of the `import`, the module works. 
Is it possible to accept imports in commonjs modules as well? 
That would make our code migrateable. 
Thanks!

**Comment by hyrious** [comment]
The error comes from babel, where if you set [`sourceType: "module"`](https://babeljs.io/docs/en/options#sourcetype), it disallows mixed code style.

esbuild-loader, on the other hand, does not do anything to your input code (mixed module) if you don't specify a target format, i.e. if you give it mixed module, it will output mixed module:

```js
// input
import a from "./a"
module.exports = a

// output of "esbuild.transform(input)", not change anything
import a from "./a"
module.exports = a
```

You can try setting `format: 'cjs'` to the esbuild-loader to force esbuild generating commonjs style code.

**Comment by janlent1** [comment]
Thanks @hyrious will try it out!
