### ISSUE TITLE
Remove type reexport

### ISSUE THREAD

**Issue by EnderShadow8** [evanw/esbuild#2079]
I'm reexporting a type using the `export {} from` syntax.

a.ts:
```ts
export type T = 0
export const v = 0
```

b.ts:
```ts
export {T, v} from "./a"
```

The output b.js:

tsc output:
```js
export {v} from "./a";
```

esbuild output:
```js
import {T, v} from "./a";
export {
  T,
  v
};
```

As you can see, the esbuild output includes the type `T` even though it should be removed.

**Comment by hyrious** [comment]
esbuild cannot know the `T` is a type or real value, see [the doc](https://esbuild.github.io/content-types/#typescript-caveats).

Instead, write this:

```ts
export type {T} from "./a"
export {v} from "./a"
```
