### ISSUE TITLE
esbuild calling jsx-factory function inconsistently

### ISSUE THREAD

**Issue by ianmobbs** [evanw/esbuild#2083]
Hi,

I'm trying to use esbuild with a new [SolidJS](https://www.solidjs.com/) project. When building the project, the default JSX factory used by esbuild is `React.createElement` - since I'm not currently using/bundling React, this fails. [This issue](https://github.com/solidjs/solid/issues/102) in SolidJS indicates that the alternative to `React.createElement` here should be `document.createElement`. However, when passing `--jsx-factory=document.createElement` to `esbuild`, it calls the function inconsistently. 

I have created a sample repository reproducing this issue, [which you can view here](https://github.com/ianmobbs/esbuild-solidjs-test-repro). When attempting to serve a build using `esbuild index.tsx --bundle --outfile=public/app.js --servedir=public --target=chrome58,firefox57,safari11,edge18 --jsx-factory=document.createElement` (or just `yarn build-with-document` in the sample repo), I am greeted with the following error:
```
Uncaught DOMException: Failed to execute 'createElement' on 'Document': The tag name provided ('() => {
    return /* @__PURE__ */ document.createElement("p", {
      class: "text-center"
    }, "Hello, world!");
  }') is not a valid name.
    at http://127.0.0.1:8000/app.js:799:41
    at http://127.0.0.1:8000/app.js:648:55
    at http://127.0.0.1:8000/app.js:41:31
    at runUpdates (http://127.0.0.1:8000/app.js:384:14)
    at createRoot (http://127.0.0.1:8000/app.js:41:14)
    at render (http://127.0.0.1:8000/app.js:646:5)
    at http://127.0.0.1:8000/app.js:799:3
    at http://127.0.0.1:8000/app.js:800:3
```
as `esbuild` generates the following code:
```
  // index.tsx
  var App = () => {
    return /* @__PURE__ */ document.createElement("p", {
      class: "text-center"
    }, "Hello, world!");
  };
  render(() => /* @__PURE__ */ document.createElement(App, null), document.getElementById("root"));
```

We can see esbuild is calling `createElement` correctly in `App()` (passing tag name `"p"`, CSS options `class: "text-center"`, and content `"Hello, world!"`), but not in `render()` (passing the `App()` element as the tag). 

Do you have any suggestions here on using `esbuild` with non-React projects? I would also be happy to contribute here, if you could point me in the right direction.

Thanks!

**Comment by ianmobbs** [comment]
Update: I was able to resolve this issue using the create element function in [this article](https://betterprogramming.pub/how-to-use-jsx-without-react-21d23346e5dc). I will leave this issue open in case there's something that can be done on the esbuild side here!
```
const customCreateElement = (tag, props, ...children) => {
    if (typeof tag === "function") return tag(props, ...children);
    const element = document.createElement(tag);

    Object.entries(props || {}).forEach(([name, value]) => {
        if (name.startsWith("on") && name.toLowerCase() in window)
            element.addEventListener(name.toLowerCase().substr(2), value);
        else element.setAttribute(name, value.toString());
    });

    children.forEach(child => {
        appendChild(element, child);
    });

    return element;
};

const appendChild = (parent, child) => {
    if (Array.isArray(child))
        child.forEach(nestedChild => appendChild(parent, nestedChild));
    else
        parent.appendChild(child.nodeType ? child : document.createTextNode(child));
};
```

**Comment by evanw** [comment]
This doesn't work because `document.createElement` is not a substitute for `React.createElement`, as you have discovered. One takes a string as an argument while the other takes either a string or a component. There's nothing to fix in esbuild because there is nothing wrong.

Closing this issue as invalid.
