### ISSUE TITLE
force loader in require/import

### ISSUE THREAD

**Issue by retorquere** [evanw/esbuild#2084]
Is there a way to force a specific loader in the source code itself, the way you can with `!!` in webpack? I have json files that I sometimes want to pack as json, and sometimes as a compiled JSON-schema validator using `ajv`, preferably without marking it with a file extension.

**Comment by evanw** [comment]
It's possible to implement this feature yourself with a plugin: https://esbuild.github.io/plugins/#on-resolve

**Comment by retorquere** [comment]
I should absolutely have thought of that.
