### ISSUE TITLE
A way to get individual chunks

### ISSUE THREAD

**Issue by nujarum** [evanw/esbuild#2086]
This is a question or maybe a feature request about the `bundle` option of the Build API.

Is there any way to get the individual chunks to be bundled?

The `outputs.inputs[<path>].bytesInOutput` in the `result.metafile` seems to give us the byte length of the chunks, but it seems difficult to split them exactly because the starting position is unclear.

So, is it possible to return information like `startInOutput` in addition to `bytesInOutput`?

Or, if you have an alternative, I would be happy to hear about it.

Example of `metafile`:
```js
{
  inputs: { ... },
  outputs: {
    ...,
    'dist/index.js': {
      ...,
      entryPoint: 'src/index.ts',
      inputs: {
        'src/lib1.ts': { bytesInOutput: 84 },
        'src/index.ts': { bytesInOutput: 0 },
        'src/lib2.ts': { bytesInOutput: 152 } // <-- How can I identify the starting byte position?
      },
    }
  }
}
```

**Comment by evanw** [comment]
It's not that straightforward because files may be discontiguous in the output file (i.e. in multiple places). You can reconstruct some of this information using source maps, although it depends on what you're looking for. What are you trying to do?

**Comment by nujarum** [comment]
Thanks for your reply, @evanw.

I see, one source file may be output to multiple locations in some cases.

I was looking into the possibility of creating a tool or plugin that could take advantage of esbuild's great transformations, but allow for a little more flexibility in customizing the bundling.

Of course, I recognize that the Transform API can be used to get individual outputs.
However, [Cross-module inlining of TypeScript enum only works when `bundle` is enabled](https://github.com/evanw/esbuild/issues/128#issuecomment-1002341244), so I was hoping to use the output from the Build API if possible.

Now that I understand my question, I will close this isssue after a while.
