### ISSUE TITLE
Plugin API Feature Request: detecting if a module is ESM or CJS in advance?

### ISSUE THREAD

**Issue by Alloyed** [evanw/esbuild#2087]
Background: I'd like to write a plugin that does something special to all third party commonJS modules, like so:
```js
        build.onResolve({ filter: /.*/ }, (args) => {
            if (...detect cjs...) {
                return { path: args.path, namespace: 'wrap-cjs' };
            }
        });
```
As far as I know, there are a few pieces of information I could use to do this, without impacting modules in ESM format.

* use `build.resolve()` and if the filename is .cjs or .cts, then it's commonJS. This is unfortunately not too common.
* use the same metadata esbuild uses to resolve the file in the first place. this would mean the "main"/"module"/"type" fields in the package.json for the resolved file.
* parse the file and look for import/export statements. I'm not actually sure if the grammar is unambiguous here, but if it is, I could do this in `build.onLoad()` as a workaround.

Could the `build.resolve()` API be augmented to include any of the above information?

**Comment by hyrious** [comment]
What about _mixed style_ modules?

```js
import A from 'a'
module.exports = A
```

**Comment by evanw** [comment]
I'm closing this issue because this is not something that I'm planning to expose as part of the plugin API. There are already ways of determining this with existing libraries, and this could also mean different things in different cases (as described by the previous comment).
