### ISSUE TITLE
Sourcemap `sources` field not rewritten for aliased files

### ISSUE THREAD

**Issue by marvinhagemeister** [evanw/esbuild#2094]
When a file is resolved via a namespace by a plugin and the file contains an existing sourcemap, the `sources` field is not updated for that specific file. This only happens when the value in `sources` is relative.

In this example the first file is namespaced via a plugin:

Actual:
```js
// index.js.map
{
  "version": 3,
  "sources": ["lib.js", "../src/other/other.js", "../src/index.js"],
  // ...
}
```
Expected:

```js
// index.js.map
{
  "version": 3,
  "sources": ["../src/lib.js", "../src/other/other.js", "../src/index.js"],
  // ...
}
```

Reproduction: https://github.com/marvinhagemeister/esbuild-sourcemap-bug

**Comment by evanw** [comment]
Namespaces were intended to support paths that don't necessarily behave like file system paths. The only namespace that esbuild treats as having file system paths is the `file` namespace.

**Comment by marvinhagemeister** [comment]
Makes sense, I should be able to get rid of the namespace 👍
