### ISSUE TITLE
Combining stdin + incremental with the javascript build API

### ISSUE THREAD

**Issue by collin** [evanw/esbuild#2100]
I'm poking around with the javascript API. I am using the stdin option to pass source as a string.

I've omitted the full source here, but my actual code is importing node modules. And I am running multiple builds where the source changes a bit. So I think I would get some advantage from doing incremental builds.

However it doesn't seem possible to combine these two features. Even with a weird hack defining the stdin contents as a getter like this:

```ts
let buildSource = `console.log("HELLO")`;
const result = await build({
  bundle: true,
  incremental: true,
  write: false,
  stdin: {
    resolveDir: rootDir,
    get contents() {
      console.log("stdin contents were accessed");
      return buildSource;
    }
  }
});
buildSource = console.log("NEW SOURCE")`;
const result2 = result.rebuild();
```
It appears the std content isn't getting accessed twice twice when I do this.

Is there any particular reason why I shouldn't want to use the stdin option + incremental builds?

**Comment by collin** [comment]
I've gone ahead with a tempfile instead, does seem to be quite a bit faster to be able to use the incremental builds. I'm pretty happy with it.

**Comment by ashtonmeuser** [comment]
@collin I'm a little late to this one but I'd love to see how you solved this.
