### ISSUE TITLE
esbuild changes code even without minifications

### ISSUE THREAD

**Issue by spapas** [evanw/esbuild#2109]
Hello friends, 
I'm creating a bundle without any minifications from a file that contains the following line:

```
var $toFixed = 1.0.toFixed;
```

this line is converted to 

```
var $toFixed = 1 .toFixed
```

in my bundle; i.e it eats the zero. Could you clarify if this is intentional? Is there a way to disable this behavior ? 

TIA

**Comment by evanw** [comment]
These two things are the same code. The JavaScript language does not have separate floating point and integer number types like this, so esbuild does not distinguish between them either. There is no way to disable this behavior.

**Comment by spapas** [comment]
Makes sense thank you!

**Comment by velichkin** [comment]
@evanw I've saw your explanation above, but is there any chance this behaviour will be changed? It breaks code in IE11 and Safari 10. 
`1.0.toString` works fine, but `1 .toString` doesn't. Now I have to run `.replace(' .toString', '.0.toString')` after running esbuild.

**Comment by evanw** [comment]
I just tried this out in IE11 and it works fine:

<img height="140" src="https://user-images.githubusercontent.com/406394/168600776-13978c41-4687-4858-bab4-162a793e82f2.png">

**Comment by spapas** [comment]
@velichkin we had *exactly* the same problem. We ended up disabling the js cloudflare optimisations:/

**Comment by evanw** [comment]
Sounds like a Cloudflare bug then, not an esbuild bug. Ideally the bug would be reported to them so they can fix it. If you want your files minified, you're also welcome to use esbuild's minifier instead.
