### ISSUE TITLE
How to make css inject in javaScript 

### ISSUE THREAD

**Issue by zheyaoa** [evanw/esbuild#2110]
In esbuild , when I bundle a javascript file . 
![image](https://user-images.githubusercontent.com/31647991/159010318-6b29a362-8831-47a4-8e85-d559b4e8e3b0.png)
The output will depart the javascript code and css code . 
![image](https://user-images.githubusercontent.com/31647991/159010252-156d66f2-323a-4fa3-b0a5-30cc9345c63e.png)
How to  make css inject in the output javascript like rollup's rollup-postcss-plugin. 
In rollup-postcss-plugin, The css code will be injected to <head> by default

**Comment by hyrious** [comment]
If you're meant to replicate the "inject" option of rollup-postcss-plugin like what style-loader for webpack does -- inserting a `<style>` tag in your document, then you could write a [plugin](https://esbuild.github.io/plugins/#on-load) to load the css file in the form of:

```js
// if the css file has "body { color: red }", load it as:
document.head.appendChild(document.createElement('style'))
             .appendChild(document.createTextNode("body { color: red }"))
```

The plugin turns out to be like this:

```js
var StyleLoader = {
  name: 'inline-style',
  setup({ onLoad }) {
    var fs = require('fs')
    var template = css =>
      `typeof document<'u'&&` +
      `document.head.appendChild(document.createElement('style'))` +
      `.appendChild(document.createTextNode(${JSON.stringify(css)}))`
    onLoad({ filter: /\.css$/ }, async args => {
      let css = await fs.promises.readFile(args.path, 'utf8')
      return { contents: template(css) }
    })
  }
}
```

Here's a more complex example [plugin](https://github.com/hyrious/esbuild-plugin-style/tree/v0.3.4) of using namespaces to create virtual modules.

**Comment by phoenisx** [comment]
This is just an open question since I couldn't find any thread or discussion regarding this!

How do you recommend injecting CSS `<link />` in HTML files? I see for each CSS import in a JS module, a CSS chunk is generated, and also, if the Module is imported in other places, a common CSS chunk is generated, which contains some duplicate CSS.

The concern is that I cannot figure out what `assetPath` or `publicPath` to use to inject the CSS in HTML in`onEnd` hook using the metafile.
Is there a simple way to get CSS output path for each `entry` in ESBuild?

E.g.

```
entryPoints: [
  'page/x.js', // imports 'a.css', 'b.css'
  'page/foo/y.js' // imports 'b.css', 'c.css'
  'page/foo/bar/z.js' // imports 'a.css', 'c.css'
]
```

Generated CSS output paths keep on changing depending on which module they were imported, so it becomes difficult to track for `page/x.js` where `a.css` and `b.css` were generated or would they be merged into single `abc.css`.

Also, thanks for creating such a great tool. 🙇🏾

**Comment by zheyaoa** [comment]
> 



> If you're meant to replicate the "inject" option of rollup-postcss-plugin like what style-loader for webpack does -- inserting a `<style>` tag in your document, then you could write a [plugin](https://esbuild.github.io/plugins/#on-load) to load the css file in the form of:
> 
> ```js
> // if the css file has "body { color: red }", load it as:
> document.head.appendChild(document.createElement('style'))
>              .appendChild(document.createTextNode("body { color: red }"))
> ```
> 
> The plugin turns out to be like this:
> 
> ```js
> var StyleLoader = {
>   name: 'inline-style',
>   setup({ onLoad }) {
>     var fs = require('fs')
>     var template = css =>
>       `typeof document<'u'&&` +
>       `document.head.appendChild(document.createElement('style'))` +
>       `.appendChild(document.createTextNode(${JSON.stringify(css)}))`
>     onLoad({ filter: /\.css$/ }, async args => {
>       let css = await fs.promises.readFile(args.path, 'utf8')
>       return { contents: template(css) }
>     })
>   }
> }
> ```
> 
> Here's a more complex example [plugin](https://github.com/hyrious/esbuild-plugin-style/tree/v0.3.4) of using namespaces to create virtual modules.

**Comment by zheyaoa** [comment]
> If you're meant to replicate the "inject" option of rollup-postcss-plugin like what style-loader for webpack does -- inserting a `<style>` tag in your document, then you could write a [plugin](https://esbuild.github.io/plugins/#on-load) to load the css file in the form of:
> 
> ```js
> // if the css file has "body { color: red }", load it as:
> document.head.appendChild(document.createElement('style'))
>              .appendChild(document.createTextNode("body { color: red }"))
> ```
> 
> The plugin turns out to be like this:
> 
> ```js
> var StyleLoader = {
>   name: 'inline-style',
>   setup({ onLoad }) {
>     var fs = require('fs')
>     var template = css =>
>       `typeof document<'u'&&` +
>       `document.head.appendChild(document.createElement('style'))` +
>       `.appendChild(document.createTextNode(${JSON.stringify(css)}))`
>     onLoad({ filter: /\.css$/ }, async args => {
>       let css = await fs.promises.readFile(args.path, 'utf8')
>       return { contents: template(css) }
>     })
>   }
> }
> ```
> 
> Here's a more complex example [plugin](https://github.com/hyrious/esbuild-plugin-style/tree/v0.3.4) of using namespaces to create virtual modules.

Thx , I have a good idea to resolve it  depend on your example plugins .

**Comment by rgembalik** [comment]
> If you're meant to replicate the "inject" option of rollup-postcss-plugin like what style-loader for webpack does -- inserting a `<style>` tag in your document, then you could write a [plugin](https://esbuild.github.io/plugins/#on-load) to load the css file in the form of:
> 
> ```js
> // if the css file has "body { color: red }", load it as:
> document.head.appendChild(document.createElement('style'))
>              .appendChild(document.createTextNode("body { color: red }"))
> ```
> 
> The plugin turns out to be like this:
> 
> ```js
> var StyleLoader = {
>   name: 'inline-style',
>   setup({ onLoad }) {
>     var fs = require('fs')
>     var template = css =>
>       `typeof document<'u'&&` +
>       `document.head.appendChild(document.createElement('style'))` +
>       `.appendChild(document.createTextNode(${JSON.stringify(css)}))`
>     onLoad({ filter: /\.css$/ }, async args => {
>       let css = await fs.promises.readFile(args.path, 'utf8')
>       return { contents: template(css) }
>     })
>   }
> }
> ```
> 
> Here's a more complex example [plugin](https://github.com/hyrious/esbuild-plugin-style/tree/v0.3.4) of using namespaces to create virtual modules.

Any idea how to add loader processing here? I have an example in which my css file has `url()` and I'd love to inject it as dataurl, but even if I use `await esbuild.transform(css, { loader: 'css' })`, it doesn't inject data urls as it would without the plugin.
