### ISSUE TITLE
write: false - splitting: true - possible?

### ISSUE THREAD

**Issue by Mwni** [evanw/esbuild#2118]
What prevents this from being possible?
Currently you get the error `Must use "outdir" when code splitting is enabled` when trying to do this.

**Comment by hyrious** [comment]
It **is** possible, the error message means chunks (generated by splitting) need a place to render. Just give it '/' or somewhere.

FYI, I did this in my repl:

https://github.com/hyrious/esbuild-repl/blob/e7fed7875dfcaebe64c99f1c2f2d593428f9bc37/src/stores/build.ts#L71-L73

**Comment by Mwni** [comment]
Thank you!
