### ISSUE TITLE
Incorrect warning about missing `baseUrl` in extended `tsconfig.json`

### ISSUE THREAD

**Issue by JounQin** [evanw/esbuild#2119]
context: https://github.com/vitejs/vite/issues/3758

**Comment by evanw** [comment]
You will have to provide more information than this. I don't know what you're talking about. What is wrong, and what is the desired behavior? Why is the warning incorrect? Is `baseUrl` present in the same file that esbuild says it is missing in? Do you have example code that reproduces the issue? Note that I know nothing about Vite.

**Comment by JounQin** [comment]
### Describe the bug





`baseUrl` is already set in the project level `tsconfig.json`: https://github.com/JounQin/test/blob/vite/tsconfig.json#L4

The warning means vite is consuming the original tsconfig from node_modules, this is incorrect.

### Reproduction



https://github.com/JounQin/test/tree/vite

### System Info

Output of `npx envinfo --system --npmPackages vite,@vitejs/plugin-vue --binaries --browsers`:

```log
  System:
    OS: macOS 12.0
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 23.45 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.22.1 - ~/.nvm/versions/node/v12.22.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 6.14.12 - ~/.nvm/versions/node/v12.22.1/bin/npm
  npmPackages:
    @vitejs/plugin-vue: ^1.2.3 => 1.2.3 
    vite: ^2.3.7 => 2.3.7
```

Used package manager:  yarn

### Logs 



```
node_modules/@1stg/tsconfig/app.json:12:8: warning: Non-relative path "src/*" is not allowed when "baseUrl" is not set (did you forget a leading "./"?)
    12 │         "src/*"
```

---

### Before submitting the issue, please make sure you do the following

- [x] Read the [Contributing Guidelines](https://github.com/vitejs/vite/blob/main/.github/contributing.md).
- [x] Read the [docs](https://vitejs.dev/guide).
- [x] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [x] Provide a description in this issue that describes the bug.
- [x] Make sure this is a Vite issue and not a framework-specific issue. For example, if it's a Vue SFC related bug, it should likely be reported to https://github.com/vuejs/vue-next instead.
- [x] Check that this is a concrete bug. For Q&A open a [GitHub Discussion](https://github.com/vitejs/vite/discussions) or join our [Discord Chat Server](https://chat.vitejs.dev/).

**Comment by JounQin** [comment]
@evanw Just copied the original context from the original issue.

**Comment by evanw** [comment]
Yes, I read the link. That's just the same information. You still aren't describing what's wrong or what the desired behavior is. It also links to a readme with a single word "test" that has no information about how to demonstrate the problem.

**Comment by JounQin** [comment]
@evanw 

> baseUrl is already set in the project level tsconfig.json: https://github.com/JounQin/test/blob/vite/tsconfig.json#L4
>
> The warning means vite is consuming the original tsconfig from node_modules, this is incorrect.

Didn't I? For the reproduction, you can simply run `yarn dev` to show the incorrect warning.

**Comment by evanw** [comment]
> you can simply run `yarn dev` to show the incorrect warning

Thanks. That was not evident.
