### ISSUE TITLE
API: Allow input from memory for building

### ISSUE THREAD

**Issue by remko** [evanw/esbuild#212]
The build CLI allows to take input from stdin and dump the output to stdout. This doesn't seem to be possible using the (Go) API? 

Possibly related to #139

**Comment by evanw** [comment]
The esbuild CLI is [literally implemented using the public Go API](https://github.com/evanw/esbuild/blob/57d6f87e089f44404df5040d2b8a0a12815b6d60/pkg/cli/cli_impl.go#L418-L433), so if you want to do something that the CLI does you should be able to just reference that. Here's the part where it takes input from stdin and dumps the output to stdout:

```go
// Read the input from stdin
bytes, err := ioutil.ReadAll(os.Stdin)
if err != nil {
  logging.PrintErrorToStderr(osArgs, fmt.Sprintf(
    "Could not read from stdin: %s", err.Error()))
  return 1
}

// Run the transform and stop if there were errors
result := api.Transform(string(bytes), *transformOptions)
if len(result.Errors) > 0 {
  return 1
}

// Write the output to stdout
os.Stdout.Write(result.JS)
```

Where the input comes from is intentionally not part of the API. There are many different potential sources of input (stdin, file, network, output of another command, etc.) and I don't think it makes sense to encode all of that in the API itself. It's trivial to read the input string from stdin first, as shown in the code example above.

**Comment by remko** [comment]
Seems I was wrong: you can’t pass a file for bundling (not transforming) via stdin via the CLI. I guess you’ll also need an option to specify the file name. Or am I missing something?

**Comment by evanw** [comment]
Ah, I see. What's the use case? I'm asking because bundling usually involves multiple files, but you could only really pass one file via stdin.

I could see wanting an API where you could pass an array of multiple in-memory files to bundle. Perhaps that's what you meant by saying it's related to #139. The way I plan to address both of those requests is with the future plugin API.

**Comment by remko** [comment]
I'm looking at [using ESBuild as a Hugo pipe stage](https://github.com/gohugoio/hugo/issues/7321).
This particular case always takes 1 (in-memory) file as input.

**Comment by remko** [comment]
@evanw Given that #139 is closed, but didn't solve this issue, can this one be reopened? Or is there another issue for tracking allowing input from memory?

**Comment by evanw** [comment]
Let's reopen this one.

**Comment by CEbbinghaus** [comment]
Does this work with module resolution? Is it possible to provide all the files in memory and build them out into a single bundle?
