### ISSUE TITLE
Failed to import sucrase

### ISSUE THREAD

**Issue by nihgwu** [evanw/esbuild#2128]
It works before but not sure since which version it's broken, so the case is, sucrase has a flattened folder structure as below
![image](https://user-images.githubusercontent.com/2595058/160115935-67de254a-fd12-47f1-ba73-07a13d8b3e0f.png)

esbuild will import `NameManager.js` instead of `NameManager.mjs` from `index.mjs`, then I'll get the following error
```
TypeError: import_NameManager.default is not a constructor
    at getSucraseContext (index.mjs:93:23)
    at transform (index.mjs:40:28)
```

what should I do for this case? For Vite I can alias `sucrase` to `sucrase/dist/index.js` to force importing the cjs version https://github.com/vitejs/vite/issues/7112#issuecomment-1065150062, but for Remix I have no idea yet as I can't find a way to config the module resolution https://github.com/nihgwu/react-runner/issues/108#issuecomment-1078785440

**Comment by evanw** [comment]
If you want to import `./NameManager.mjs` you should import `./NameManager.mjs`, not `./NameManager`. Node doesn't automatically apply the `.mjs` extension, so esbuild doesn't either (the extension `.mjs` is deliberately not included in the [set of automatically-applied extensions](https://esbuild.github.io/api/#resolve-extensions)). You could also add `.mjs` to esbuild's set of automatically-applied extensions to get this to work although that may cause you more pain later as it may diverge from the way the current ecosystem works.

**Comment by nihgwu** [comment]
regarding the `.mjs` extension, I understand we should specify the extension explicitly when importing, but as you know there are still tons of packages are not following the standard fulling, that's why for `webpack` we can use `resolve.fullySpecified: false` as a workaround, the current problem is that I Remix doesn't support override `esbuild` config, and `sucrase` won't change the importing style in a short time I think
But you pointed out a better solution for Vite, I'll try it out, my concern is that it worked before, but doesn't work then

**Comment by evanw** [comment]
> the current problem is that I Remix doesn't support override `esbuild` config

That's an issue with Remix, not with esbuild. There is already a setting for this in esbuild so I'm closing this issue because there's nothing further to do here.
