### ISSUE TITLE
Errors with function named `readonly`

### ISSUE THREAD

**Issue by MarvinRudolph** [evanw/esbuild#213]
Hey!

I'm using [Vite](https://github.com/vitejs/vite) with Vue 3. Vue exports a function named `readonly` which returns a wrapped `Readonly` type. Using it as a return-type with `ReturnType<typeof readonly>` throws an error `Unexpected ">"`.

I think the problem here is the *reserved* `readonly` keyword in interfaces for example because it works when I rename it in the import (`import { readonly as readOnly } from 'vue'`).

Is this a problem with esbuild or maybe a bug in Vite itself?

**Comment by evanw** [comment]
Thanks for reporting this. It's definitely a bug with esbuild. The problem is that for `typeof readonly`, the `readonly` identifier is incorrectly treated as a type operator. I'll fix this shortly.

**Comment by evanw** [comment]
This should be fixed in version 0.5.19.
