### ISSUE TITLE
Reloading Chunks in case of Inconsistent Network Connection

### ISSUE THREAD

**Issue by jhirshman** [evanw/esbuild#2130]
Hi, we're trying to support users who have inconsistent network connections.  We're finding that sometimes a chunk will fail to load due to a network issue which ends up breaking our whole site for that user.

Webpack has an extension like this one for retrying chunk loads: https://github.com/mattlewis92/webpack-retry-chunk-load-plugin/blob/master/src/index.ts.

In an ideal world, we would be able to wrap the imports of the chunks so that we could add a few retries if the chunk fails to load.  Possibly making network new requests after a short interval.

Is there a solution like this that esbuild supports or a way for us to write an extension to esbuild for this?

The failure model we're working with to simulate our customer's problems is we're having our local development server fail to respond to 1/50 requests to serve .js files and want to be robust to that.

**Comment by hyrious** [comment]
I don't think this kind of work should be done in the bundler side. (e.g. Can you find similar approach in rollup or webpack?)

If you have some important resources to be load at the first place, don't split them into another chunk. This is still working where not all server/client supports HTTP2.

If you are worrying that `import()` throws error, wrap it in your custom retry function. For example react users may just write: `React.lazy(() => retry(() => import('./component.js')))`.

**Comment by jhirshman** [comment]
I'm not sure what you mean by not splitting important resources into chunks.  I don't believe there is a mechanism to control what gets put into chunks and what doesn't.

Note, this does not concern the lazy or dynamic imports.  We're able to issue retries for them by wrapping the dynamic import.  This only concerns the chunks that are loaded after the initial bundle that imports them is loaded.

**Comment by evanw** [comment]
This is outside of the scope of what esbuild does. You'll have to figure out how to handle this yourself. It sounds pretty difficult to handle this in all of the various cases (e.g. what do you do about a URL directly embedded in the HTML). My first thought would be to use a service worker but those don't work on the initial page load. If I had this problem myself and I wanted to solve it, I would probably inline the entire app into a single HTML page without any additional chunks. That way it would either all load or all fail. Anyway I'm going to close this because this is out of the scope of what esbuild does.

**Comment by 111Rick111** [comment]
Hey @jhirshman have you found a solution?

**Comment by simeyla** [comment]
**Every single website** with chunks, particularly on a mobile device is susceptible to network connection issues - especially when you're loading dozens of chunks with zero auto-retry functionality.

Frankly I'm sort of amazed (like genuinely surprised) there isn't a better solution to this. Or maybe there is by now? Every developer (whether application / framework / bundler / browser) ends up pointing fingers but not finding a good solution. It has to be someone's responsibility surely? Perhaps ultimately the browser should be doing this?

With frameworks such as Angular increasingly making it easier to lazy load components the problem will only get greater. I don't want to sound 'complainy' - I'm more puzzled than anything.

When I implemented the 'retry' plugin for my Angular app it dramatically reduced the number of errors in my logs from missing chunks. Does nothing similar exist that can be plugged in here somehow?
