### ISSUE TITLE
Allow not external child path of a package

### ISSUE THREAD

**Issue by linonetwo** [evanw/esbuild#2131]
I have `external: ['react', 'react-dom'],` in my config, but I don't want `react/jsx-runtime` to be excluded.

In the doc:

> This means that --external:@foo/bar implicitly also means --external:@foo/bar/* which matches the import path @foo/bar/baz. So it marks all paths inside the @foo/bar package as external too. 

Can you make this assumption optional?

Or can there be a way to re-inject `react/jsx-runtime` by my self?

**Comment by evanw** [comment]
> Can you make this assumption optional?

No. The `external` option is provided for convenience but doesn't have fine-grained control. More complex use cases are served by plugins instead.

> Or can there be a way to re-inject `react/jsx-runtime` by my self?

Yes. You can customize path resolution logic with a plugin: https://esbuild.github.io/plugins/#on-resolve. You can use that to intercept `react/jsx-runtime` and resolve it yourself, which will override esbuild's behavior.

Closing this issue as out of scope. The intended workaround is to write a plugin for this.
