### ISSUE TITLE
Generated constructor uses `this` before calling `super` when the constructor has a spread argument and the super call is in an `if`/`else` block.

### ISSUE THREAD

**Issue by Lakuna** [evanw/esbuild#2134]
This issue is almost identical to #678.

When processing a class similar to this:

```js
export class Foo extends Array {
	constructor(...data) {
		if (true) {
			super(...data);
		} else {
			super(...data);
		}
	}

	bar = "bar";
}
```

Using the following command:

```
esbuild test.js --target=es2015
```

The returned code is as follows:

```js
var __defProp = Object.defineProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};
export class Foo extends Array {
  constructor(...data) {
    __publicField(this, "bar", "bar");
    if (true) {
      super(...data);
    } else {
      super(...data);
    }
  }
}
```

The call to `__publicField(this, "bar", "bar");` occurs before either instance of `super(...data);`. The issue appears to occur for the same reason as #678, but only when there are multiple possible `super` calls.

The esbuild version is `0.14.28`.

**Comment by evanw** [comment]
Thanks for the report. I've been meaning to fix this for a while. TypeScript typically doesn't allow this so I never hit this myself, but of course people still want to be able to do this in JavaScript. Here's the TypeScript compile error for this:

> A 'super' call must be a root-level statement within a constructor of a derived class that contains initialized properties, parameter properties, or private identifiers.

**Comment by Lakuna** [comment]
Ignore that, sorry.
