### ISSUE TITLE
Preserving seemingly superfluous parentheses

### ISSUE THREAD

**Issue by SheetJSDev** [evanw/esbuild#2136]
```js
	var storage: TileStorageType = (pb?.[7]?.[0]) ? ((varint_to_i32(pb[7][0].data)>>>0) > 0 ? 1 : 0 ) : -1;
```

With flags `--platform=browser --target=es5` esbuild generates

```js
  var storage = ((_a = pb == null ? void 0 : pb[7]) == null ? void 0 : _a[0]) ? varint_to_i32(pb[7][0].data) >>> 0 > 0 ? 1 : 0 : -1;
```

This is technically equivalent for compliant ES5 engines.  However, Adobe ExtendScript (the engine that ships with Photoshop and friends) has a number of strange associativity rules.  If the original parentheses were preserved, the output would have been compliant.

Is there a way to indicate that parentheses should be preserved?

**Comment by evanw** [comment]
No, there isn't a way to do this. It's out of scope for esbuild to support weird non-compliant JavaScript implementations. You are welcome to work around these problems yourself if you'd like by e.g. splitting things into separate variable declarations. But I don't intend to add support for this to esbuild itself. Closing as out of scope.
