### ISSUE TITLE
Execute complied code

### ISSUE THREAD

**Issue by mbrevda** [evanw/esbuild#2145]
I have a react component that I use as a template to generate a `index.html` file. This component takes the name of outputs (e.g. `app-NU43JK4C.js`) and inserts it as a script tag. The issue is that being in jsx, I need to compile this script before it can be executed. Ideally, I'd prefer not writing it to disk at all. 

I'm aware of transpile, but that wont import all the dependencies.

Is there some way to compile and run code in a single go?

Here is a simplified version of the component:

```jsx
import {renderToStaticMarkup} from 'react-dom/server'
import appleTouchIcon180 from 'icons/apple-touch-icon-180x180.png'
import faviconSvg from 'packages/frontend/src/static/favicon.svg'

const Index = ({app}) => {

  return (
    <html>
      <head>
        <link rel="icon" type="image/svg+xml" href={faviconSvg} />
        <link rel="apple-touch-icon" href={appleTouchIcon180} />
      </head>
      <body>
        <script src={app} />
      </body>
    </html>
  )
}

export default params => {
  return '<!DOCTYPE html>' + renderToStaticMarkup(<Index params={params} />)
}

**Comment by evanw** [comment]
Do you mean like these?

* https://github.com/egoist/esbuild-register
* https://github.com/folke/esbuild-runner
* https://github.com/antfu/esno

I'm not affiliated with these projects and have not tried them, but I believe they do what you're asking for.

**Comment by hyrious** [comment]
Writing to disk isn't that harmful. But if you want to execute code written in ESM, there is a way -- [via import(dataurl)](https://2ality.com/2019/10/eval-via-import.html).

**Comment by mbrevda** [comment]
> Writing to disk isn't that harmful. But if you want to execute code written in ESM, there is a way -- [via import(dataurl)](https://2ality.com/2019/10/eval-via-import.html).

Exactly! Would be great if the API allowed for this directly. At the very least it might be worth documenting.

Thanks!

**Comment by mbrevda** [comment]
Also, while using `import` is quite clean it doesn't seem to have good ergonomics around error handling (see screenshot, not much to see here!), which would be one more vote for a built in way to do this

<img width="1058" alt="Screen Shot 2022-03-31 at 7 24 54 AM" src="https://user-images.githubusercontent.com/293004/160976228-6499fc46-c4d0-4c22-9d92-c8c6c30e9f84.png">

**Comment by hyrious** [comment]
That's true. So I still recommend you to really write it to disk, in which case you can use sourcemaps to point back to the real file.

**Comment by privatenumber** [comment]
There is a request to allow passing in a virtual (in-memory) file-system here: https://github.com/evanw/esbuild/issues/690

It looks like the use-cases described there are similar to this.
