### ISSUE TITLE
Something wrong when compiling file assets

### ISSUE THREAD

**Issue by markskayff** [evanw/esbuild#2146]
I'm still testing esbuild and found something it's not working out of the box.
I'm trying to compile file assets like jpg, png, etc... using the loader.
Thing is where this files end up living. 
I have the outdir set to **public/js** but I want the assets (even it'd be cool to control the css's locations) under **public/assets**.
This is my current config and my tree struct.

`require('esbuild').build({
  entryPoints: ['src/app.jsx'],
  assetNames: "assets/[name]-[hash]",
  bundle: true,
  sourcemap: true,
  loader: {
    '.png': 'dataurl',
    '.jpg': 'file',
    '.svg': 'text'
  },
  logLevel: 'info',
  //watch: true,
  outdir: 'public/js',
})`
![tree-struct](https://user-images.githubusercontent.com/22687247/161126909-e76042c0-7926-4625-af7c-c829908f00d5.png)

So, when I run this build, thing is the assets end up below the **public/js**, so there is no control as to where this assets are gonna live in my final tree struct. To make it worse, the final react code references the asset with ./assets/<blah> so it's not even finding the assets which are living under "js/"

You can even try to hack this and say let's do: **../assets/<blah>** ... but that breaks as the src in the compiled code now points to "../assets/<blah>" and the path is lost once again.

So, seems there's missing some control over where your file assets are actually living and how they are referenced.
It'd be cool to have control over CSS's in the same way, and probably other asset types.
The publicPath didn't help to solve the issue either, as the src path are stil missing the point.

**Comment by evanw** [comment]
The `outdir` is the root directory for the output. All outputs are written somewhere inside the `outdir`. From there, you can further place things in subdirectories within `outdir` if you'd like.

So in your case it sounds like you want `outdir: 'public'` since `public` is the root and then `assetNames: "assets/[name]-[hash]"` and `entryNames: "js/[name]"` or something.

**Comment by markskayff** [comment]
Ah, maybe that pattern would work. I was missing the entryNames one. I'll let you know how it goes.

**Comment by markskayff** [comment]
Ok, the entryNames worked to separate the **outdir** from the entry point dir.
And the publicPath seemed to start working now after I have this configuration of "outdir", "assetNames" and "entryNames".
It feels a bit hacky, and still feeling like want more control over where assets go, even place. For example to have the css files under its own directory. Feels weird (in my example) to have the css under the js/ folder. 

But anyways, thanks for the response. I have the project test now where I wanted it to be.

**Comment by evanw** [comment]
>  It feels a bit hacky, and still feeling like want more control over where assets go, even place. For example to have the css files under its own directory. Feels weird (in my example) to have the css under the js/ folder.

You can use `entryNames: "[ext]/[name]"` for that. This is all in the documentation: https://esbuild.github.io/api/#entry-names.
