### ISSUE TITLE
Loader: support files with multiple extensions

### ISSUE THREAD

**Issue by iamakulov** [evanw/esbuild#215]
Right now, the `loader` option doesn’t support matching by multiple extensions. For example:

```js
// index.js
import moduleAsText from "./module.raw.js"
console.log(moduleAsText)
```

```sh
# Shell
$ esbuild --bundle index.js --outfile=out.js --loader:.raw.js=text
error: Invalid file extension: ".raw.js"
1 error
```

Would it be possible to support this? 

**Practical use-case:** for me, this is needed for interop with webpack.

A team I’m working with is trying to switch to ESBuild for development, keeping webpack in production. In the codebase, there’re a few cases where a `.js` file is being loaded with `raw-loader`. In webpack, it’s possible to match these files with `test: /\.raw\.js$/` and apply the loader selectively; but ESBuild throws an error.

**Comment by evanw** [comment]
Yes, I've been planning to do this. A use case I have in mind for later is `.css` vs `.module.css`. The behavior that makes the most sense to me is for it to pick the loader with the longest match.

**Comment by anubra266** [comment]
@evanw I'm working on a project, where I'll like to import some of my `.tsx` components with the `text` loader in some cases. How could I go about this?
