### ISSUE TITLE
When I run `npx esbuild index.js --banner:js=//comment --banner:css=/*comment*/ --outfile=bundle.js`, I always get a single slash

### ISSUE THREAD

**Issue by zhengyimeng** [evanw/esbuild#2150]
My environment is Windows
When I execute this command
I got this
![image](https://user-images.githubusercontent.com/20783425/161434057-4bb9dd1d-190e-4359-b4e1-799d5ee209ec.png)
I tried adding \ before /, but it didn't help
Like this: `npx esbuild index.js --banner:js=\/\/comment --banner:css=/*comment*/ --outfile=bundle.js`

**Comment by evanw** [comment]
I assume you're hitting some problem either with Windows shell escape logic or with `npx`. In either case, this is not a problem with esbuild (esbuild doesn't contain any code that rewrites command line arguments like this). I'm unfamiliar with Windows Command Prompt and I don't have a Windows machine handy so I won't be able to help you. You'll have to look elsewhere for help regarding how to escape command-line arguments correctly on Windows. Another option is to use esbuild's JavaScript API instead to bypass this issue.

**Comment by hyrious** [comment]
I cannot reproduce this behavior on my Windows machine. Here is what I did:

```cmd
C:\Users\hyrious\Desktop\test>type a.js
console.log("index.js");

C:\Users\hyrious\Desktop\test>type package.json | findstr esbuild
    "esbuild": "^0.14.30",

C:\Users\hyrious\Desktop\test>npx esbuild a.js --banner:js=//comment --banner:css=/*comment*/ --outfile=b.js

  b.js  35b

Done in 5ms

C:\Users\hyrious\Desktop\test>type b.js
//comment
console.log("index.js");
```

To be clear: CMD/PowerShell doesn't have to escape `/`, most of the case it is needed by some other programs like npx. You can read more escaping rule [here](https://ss64.com/nt/syntax-esc.html).

Also try: (yes, single `"`, it means quoting to the end)

```cmd
npx esbuild index.js --banner:js="//comment
```

**Comment by evanw** [comment]
Thanks for the verification. I suppose it could also hypothetically be a specific buggy version of `npx` as it has had some [command line escaping bugs](https://github.com/evanw/esbuild/issues/965) in the past (which is why I have removed all mention of `npx` from esbuild's documentation).

**Comment by zhengyimeng** [comment]
Ok, thank you.
I got this error when running on 'Git Bash'
The result is correct when I run it on 'Powershell' or 'CMD'
This should be an error on 'git bash', not on 'esbuild 'itself
