### ISSUE TITLE
Regression in 0.14.30, tree shaking removing used code

### ISSUE THREAD

**Issue by leafo** [evanw/esbuild#2151]
I'm still trying to extract a minimum reproducible test case, as the issue is showing up in a larger project, but maybe this might point someone in the right direction.

I've tested building on 0.14.29 and it works as expected, 0.14.30 creates a broken bundle. Disabling tree shaking with 0.14.30 prevents the used code from disappearing, which makes me believe it's related to the tree shaking functionality.

Build command: 

```
NODE_PATH=../static/js ../node_modules/.bin/esbuild js/st/main.jsx --log-level=warning --bundle --sourcemap --outfile=main.js
```

I feel like screenshot is easiest way to demonstrate what's going on, tell me if you want me to format it differently.

![image](https://user-images.githubusercontent.com/15198/161447483-0fc99245-9200-4fb2-893c-877e65a07afd.png)

The build completes successfully, all the imports resolve. Yet some of the classes ([`MelodyRecognitionExercise`](https://github.com/leafo/sightreading.training/blob/master/static/js/st/components/ear_training/melody_recognition_exercise.jsx)) are completely stripped out via the tree shaking causing an error when attempting to reference them.

Here's the the section from the output js file where the code should be (it's finding the correct file but removing all the code inside of it):

![image](https://user-images.githubusercontent.com/15198/161447581-53ba8af7-dd14-4e7b-a3f3-3ca9d0b98731.png)

Disabling tree shaking (`--tree-shaking=false`), or moving back to 14.29 will produce a bundle that includes the missing code:

![image](https://user-images.githubusercontent.com/15198/161447622-2dd9abdd-f471-449d-b346-07606b984319.png)

**Comment by evanw** [comment]
It would be helpful to have a reproducible test case since all of my tests passed with the last release, but I understand that it can be hard to extract one. Despite the lack of an example I have a hunch as to what it might be and I'm going to try making a change in the next release anyway. Hopefully it will fix your problem.

**Comment by leafo** [comment]
I just tested with v0.14.31 and it's producing the expected output again. Thanks for taking a look so quickly.
