### ISSUE TITLE
es2016 + minify outputs illegal import alias

### ISSUE THREAD

**Issue by colemars** [evanw/esbuild#2154]
output:
```
import{createElement as V1,forwardRef as os,memo as as}from"react"
```

working on getting specific input

**Comment by evanw** [comment]
Which one is illegal, and in what environment? It appears to work fine for me. Here's a quick test:

```
$ cat test.mjs
import{readFile as V1,writeFile as os,exists as as}from"fs"
console.log(V1,os,as)

$ node test.mjs
[Function: readFile] [Function: writeFile] [Function: exists]
```

**Comment by colemars** [comment]
Yup, sorry. I assumed that was bad syntax. Got a webpack/babel-loader error and it pointed me to that character, but it seems more of an issue with this version of babel-loader than anything else.

Apologies for false report.
