### ISSUE TITLE
Raspberry Pi Availability

### ISSUE THREAD

**Issue by willpuckett** [evanw/esbuild#2156]
Appending "aarch64-unknown-linux-gnu": "esbuild-linux-arm64" to knownUnixlikePackages (line 147-151 of lib/deno/mod.ts) gets things working for me on raspberry pi. Would this be a prudent addition?

**Comment by evanw** [comment]
Sounds good to me. I don't use Deno myself and don't have a Raspberry Pi either so I'm taking your word for it. It's a simple addition in any case.

**Comment by evanw** [comment]
I copied the content of your PR here: https://github.com/esbuild/deno-esbuild/pull/2. This will go out with the next release of esbuild.

**Comment by willpuckett** [comment]
awesome thanks!
