### ISSUE TITLE
`build.onEnd()` hook replace error

### ISSUE THREAD

**Issue by Valexr** [evanw/esbuild#2157]
`npm run build` -> `open public/index.html` - error in inlined `<script>`

This [method](https://github.com/Valexr/optimade-esbuild/blob/bbec2cbf6bb02eec54ca6319b55f36c6664dcb30/html.js#L23) solved issue 🤓 but why in replaced script string have unused `<body />&` tags...?

**Comment by evanw** [comment]
I don't know. That's something you'll have to debug for yourself. Your problem is in code you wrote that runs after esbuild runs so the behavior of that code is entirely up to you.

By the way you can do this:

```js
js = js.text;
css = css.text;
```

instead of this:

```js
js = decode(js.contents);
css = decode(css.contents);
```

**Comment by Valexr** [comment]
> I don't know. That's something you'll have to debug for yourself. Your problem is in code you wrote that runs after esbuild runs so the behavior of that code is entirely up to you.
> 
> By the way you can do this:
> 
> ```js
> js = js.text;
> css = css.text;
> ```
> 
> instead of this:
> 
> ```js
> js = decode(js.contents);
> css = decode(css.contents);
> ```

Tx 🚀 @evanw 
Good hint 👍🏻 with `output.text` represents in output🤓
You are right - my replace() method call after esbuild... but i don't understand it's behavior🤔

**Comment by evanw** [comment]
Documentation for `replace` is here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace

**Comment by Valexr** [comment]
With replacer() function same `replacement` string works...🤷🏻‍♂️
May be it's bug in method for long strings...?! 🤔

```js
html.replace('</body>', replacer)

function replacer() {
  return `<script>\n${js.text}</script>\n</body>`;
}
```

**Comment by evanw** [comment]
I'm closing this issue because this is a general question about how JavaScript works, which is not appropriate for this issue tracker. This is not a problem with esbuild.
