### ISSUE TITLE
Error `The service was stopped: spawn ... ENOENT` when calling `build` within Jest 27 Test

### ISSUE THREAD

**Issue by mxro** [evanw/esbuild#2165]
I've recently upgraded a project to use Jest 27 and a few unit tests involing esbuild stopped working. These unit tests essentially call the async esbuild `build` operation to bundle a few sample files:

Here the call to esbuild:

```typescript
 await build({
      plugins: [pnpPlugin()],
      bundle: true,
      entryPoints: [`${routesDir}/${config.relativeFilePath}`],
      external: ['aws-sdk'],
      minify: true,
      format: 'cjs',
      target: 'node12.0',
      sourcemap: true,
      outfile: getOutFileForLambda(config),
      ...esbuildConfig,
      ...localEsbuildConfig,
    });
``` 

https://github.com/goldstack/goldstack/blob/issue-148-upgrade-to-jest-27/workspaces/templates-lib/packages/template-lambda-api/src/templateLambdaApiBuild.ts#L31

And here the related Jest test:

```
  it('Should build lambda', async () => {
    const fileToBuild = path.resolve('./testData/build-test/index.ts');
    expect(fs.existsSync(fileToBuild)).toEqual(true);
    await buildLambdas('./testData/build-test', [
      {
        path: '/index',
        relativeFilePath: 'index.ts',
        name: 'test-lambda-index',
        absoluteFilePath: fileToBuild,
        route: 'ANY /',
        type: RouteType.FUNCTION,
      },
    ]);
    const generated = read('./distLambda/index/lambda.js');
    expect(generated.length).toBeGreaterThan(100);
  });
```

https://github.com/goldstack/goldstack/blob/issue-148-upgrade-to-jest-27/workspaces/templates-lib/packages/template-lambda-api/src/templateLambdaApiBuild.spec.ts#L10

When running this test in Jest, the following error is reported:

```
   The service was stopped: spawn C:\Users\Max\repos\goldstack-mega\.yarn\cache\esbuild-windows-64-npm-0.14.34-461e67de52-44e1b69008.zip\node_modules\esbuild-windows-64\esbuild.exe ENOENT

      at ../../../../.yarn/unplugged/esbuild-npm-0.14.34-72a5e72c78/node_modules/esbuild/lib/main.js:1335:25
      at ../../../../.yarn/unplugged/esbuild-npm-0.14.34-72a5e72c78/node_modules/esbuild/lib/main.js:666:9 
      at ChildProcess.afterClose (../../../../.yarn/unplugged/esbuild-npm-0.14.34-72a5e72c78/node_modules/esbuild/lib/main.js:644:7)
```

Here a few things I've tried so far to investigate this:

- Running the same command (that is run in the Jest test) outside of Jest works, see here: https://github.com/goldstack/goldstack/blob/issue-148-upgrade-to-jest-27/workspaces/templates-lib/packages/template-lambda-api/scripts/buildTestLambdas.ts
- Tested on both Windows and Linux ([see GitHub Actions build](https://github.com/goldstack/goldstack/runs/5876552739?check_suite_focus=true#step:6:62))
- Upgraded esbuild to latest version `0.14.34`

I assume there is something going on here with the context in which Jest executes the tests that conflicts with how esbuild wants to spawn the process.

Environment:

```
node 14.19.1
yarn 3.0.2
```

**Comment by evanw** [comment]
Yarn’s PnP mode can break stuff because it hijacks normal npm package resolution. It looks like that might be happening here. Somehow is trying to spawn something inside a zip file, which is of course impossible. What happens if you disable Yarn PnP mode, or just use npm instead?

**Comment by evanw** [comment]
Here's some more detail. You can see esbuild's hack to try to prevent Yarn PnP from breaking things here:

https://github.com/evanw/esbuild/blob/8534ad397573f100f2108b928266e2db17b6f921/lib/npm/node-platform.ts#L177-L195

If we can `require('pnpapi')` then we know Yarn PnP is active. In that case we know that attempting to spawn a child process from within the package for the current platform will fail because Yarn PnP has put the child process in a zip file. The workaround is to instead spawn a copy of the executable that we copy out of the zip file, which turns it into a real file that the OS can spawn.

I assume your problem is that Jest breaks `require('pnpapi')`. This looks like a bug in Jest: https://github.com/facebook/jest/issues/11604. Without this, esbuild can't tell that it's running inside Yarn PnP and so can't it apply this workaround. So I'm going to close this issue because it's a bug in Jest, not in esbuild. From [this comment](https://github.com/facebook/jest/issues/11604#issuecomment-944888383) it sounds like you can maybe change some Jest configuration to re-enable `require('pnpapi')` to get this to work. Or you can just not use Yarn, which will avoid this entire class of problems altogether.

**Comment by mxro** [comment]
Thanks for your quick and detailled response. Sad that yarn pnp requires that workaround (e.g extracting the files) but thanks for supporting this since that enables usage of the esbuild in this template for packaging Lambda deployment packages.

For anyone's future reference, this is how I was able to resolve the issue (as [suggested in the comment linked above](https://github.com/facebook/jest/issues/11604#issuecomment-944888383)):

Add [jest-pnp-resolver](https://www.npmjs.com/package/jest-pnp-resolver) package

```
yarn add -D jest-pnp-resolver
```

Add `resolver` to [`jest.config.js`](https://github.com/goldstack/goldstack/blob/master/workspaces/templates-lib/packages/template-lambda-api/jest.config.js#L6):

```
module.exports = {
  ...base,
  resolver: require.resolve('jest-pnp-resolver'),
  globals: {
    'ts-jest': {
      tsconfig: 'tsconfig.json',
    },
  },
};
```

**Comment by kvz** [comment]
We recently encountered a related but different issue where esbuild was failing with `spawn EACCES` errors, but only when run from cron jobs. The error message was: `Error: The service is no longer running: spawn /path/to/esbuild EACCES`.

In our case, the issue wasn't with the long-lived service or permissions on esbuild. Our cron jobs were running with `PWD=/home/ubuntu`, and a non priviliged app user didn't have permission to access that directory. When tsx tried to spawn esbuild, it failed with EACCES. The solution was to ensure cron jobs changed to an accessible directory before running (e.g. `cd /non-priviliged-user-owned/dir && sudo -u non-privliged-user tsx file.ts` <-- without `cd`-ing to a safe place first, the `Error: The service is no longer running: spawn /srv/recent/16126460956/api2/node_modules/@esbuild/linux-arm64/bin/esbuild EACCES` error). 

In the hopes this might help others googling for this mysterious error. Sometimes it's not about the service lifecycle, nor permissions on the esbuild file itself, but rather about the PWD environment in which esbuild is being spawned.

**Comment by ashnazg** [comment]
To semi-echo @kvz , I beat my head against the wall on the same error.  In my case, the issue was the combination of:
* `jenkins` workspace on `/var`
* `/var` mounted with `noexec` flag

This is why every _other shell account_ **could** run the same commands and configs just fine.
