### ISSUE TITLE
Granular keepNames?

### ISSUE THREAD

**Issue by IanBellomy** [evanw/esbuild#2167]
Short:
I'm looking for a way to preserve the names for a few methods without having to invoke keepNames for the whole build.

Something like (handwaves)
````
//@es-build-keepname
methodXYZ(){...}
````

Context:
I'm trying to refactor a nest of async calls into a kind of stack so I can save and restore execution state. This would be easiest if I could just rely on a small subset of methods having consistent names in perpetuity (even if minified). Because this naming need only applies to a small slice of a large project, enabling keepNames for the whole build feels like overkill.

There are other ways around the refactoring problem of course but I thought I'd sniff around for a quick solution first /  note a possible use case for such a feature.

**Comment by hyrious** [comment]
If you don't care about writing one more line, why not just manually keep the name by yourself? Like such:

```js
function keepMe() {}
Object.defineProperty(keepMe, "name", { value: "keepMe", configurable: true })
```

**Comment by IanBellomy** [comment]
> If you don't care about writing one more line, why not just manually keep the name by yourself? Like such:
> 
> ```js
> function keepMe() {}
> Object.defineProperty(keepMe, "name", { value: "keepMe", configurable: true })
> ```

An option for sure but because I'm working with class expressions and methods defined in the class body I'd _prefer_ any name-preserving expressions to be co-located with the method(s) in question.

**Comment by hyrious** [comment]
class members (props) won't be renamed unless you used [mangle props](https://esbuild.github.io/api/#mangle-props) to tell esbuild which members are safe to rename, and `--keep-names` won't keep these props' names. ([see it live](https://hyrious.me/esbuild-repl/?version=0.14.34&mode=transform&input=class+KeepMe+%7B+dropMe_%28%29%7B%7D+keepMe%28%29%7B%7D+%7D&options=--mangle-props%3D.*_+--keep-names))

**Comment by IanBellomy** [comment]
> class members (props) won't be renamed unless you used [mangle props](https://esbuild.github.io/api/#mangle-props) to tell esbuild which members are safe to rename, and `--keep-names` won't keep these props' names. ([see it live](https://hyrious.me/esbuild-repl/?version=0.14.34&mode=transform&input=class+KeepMe+%7B+dropMe_%28%29%7B%7D+keepMe%28%29%7B%7D+%7D&options=--mangle-props%3D.*_+--keep-names))

Fantastic!

**Comment by vzakharov-rxnt** [comment]
@IanBellomy Is it possible to keep names by a regular expression? We have a development standard in an Angular 16 app, where only <1% of components need to be kept, others can be shortened. Keeping all has a build impact of 3.3%.

**Comment by vzakharov-rxnt** [comment]
@hyrious Is it possible to keep names by a regular expression? We have a development standard in an Angular 16 app, where only <1% of components need to be kept, others can be shortened. Keeping all has a build impact of 3.3%.
