### ISSUE TITLE
Remix, react-three/fiber, and react-three/drei have conflicting import

### ISSUE THREAD

**Issue by dalelotts** [evanw/esbuild#2168]
I'm still learning about remix and react-three, so I got some help identifying this as an esbuild issue. See https://github.com/remix-run/remix/issues/2692 for the original remix issue.

Steps to Reproduce

1. Clone this repo: https://github.com/dalelotts/r3f
2. Uncomment use of OrbitControls in this file https://github.com/dalelotts/r3f/blob/main/app/pano/canvas-wrapper.client.tsx#L10
3. Run `npm run dev`
4. Visit `http://localhost:3000/r3f` - TypeError: Cannot read properties of undefined (reading 'root') is displayed

The following codesandbox uses patch-package to patch the imports for @react-three/fiber and @react-three/drei packages to rename the React import so they don't conflict: https://codesandbox.io/s/remix-three-drei-r8lkg6

**Comment by dalelotts** [comment]
Upon further research, @killiman patched the Remix compiler to minify the code, even on DEV. It looks like the bug does not appear in the minified version. 

Here's the patch:

```diff
diff --git a/node_modules/@remix-run/dev/compiler.js b/node_modules/@remix-run/dev/compiler.js
index 606e429..0dd6229 100644
--- a/node_modules/@remix-run/dev/compiler.js
+++ b/node_modules/@remix-run/dev/compiler.js
@@ -333,7 +333,7 @@ async function createBrowserBuild(config, options) {
     incremental: options.incremental,
     mainFields: ["browser", "module", "main"],
     treeShaking: true,
-    minify: options.mode === build$1.BuildMode.Production,
+    minify: true,
     entryNames: "[dir]/[name]-[hash]",
     chunkNames: "_shared/[name]-[hash]",
     assetNames: "_assets/[name]-[hash]",
```

Here is the discussion on discord: https://discord.com/channels/770287896669978684/771068344320786452/962097799359508521

**Comment by dalelotts** [comment]
Possibly not a esbuild issue based on this PR https://github.com/remix-run/remix/pull/2694

**Comment by evanw** [comment]
This issue doesn't describe what's wrong with esbuild or what the desired behavior is. The provided bug demonstration is using esbuild in combination with other tools and untangling what esbuild is doing vs. what other tools are doing is likely going to take some time (and that may be wasted effort if it's indeed not an esbuild issue). I don't have context on this and I don't have the time to look into this myself. Marking this as `unactionable` until the problem has been narrowed down to something esbuild-specific. And if you don't need this investigated anymore or if this wasn't a problem with esbuild after all, please close this issue.

**Comment by dalelotts** [comment]
Understood. I'll try to narrow it down some.

**Comment by agcty** [comment]
I believe this issue is actually related to https://github.com/evanw/esbuild/issues/475.

**Comment by evanw** [comment]
Closing due to lack of a reply.

**Comment by juddydev** [comment]
Hello, I have an issue implement 3d model viewer using r3f in remix and shopify
r3f is working in remix?

**Comment by dalelotts** [comment]
It is working with the latest versions of Remix et al.

**Comment by juddydev** [comment]
Thank you
