### ISSUE TITLE
Not able to treeshake library bundled with esbuild

### ISSUE THREAD

**Issue by raviteja83** [evanw/esbuild#2171]
Awesome work on the esbuild library. It has saved us lot of time with deployments. 

```
// src/Checkbox.ts
export const Checkbox = {
  Root: CheckboxRoot, // this is a component defined above
  Indicator: CheckboxIndicator,  // this is a component defined above
};

// src/index.ts
export * from './Checkbox';
```
The above is the format I export the components. I have several such components. When I am only using one of the component in the app, all the components are present in the final bundle.

The following is esbuild config: 
```
esbuild.buildSync({
      entryPoints: ['src/index.tsx'],
      outfile: 'dist/index.js',
      minify: true,
      bundle: true,
      format: 'esm',
      target: 'es6',
      tsconfig: 'tsconfig.json',
      external: [Object.keys(pkg.dependencies)],
      metafile: true,
    });
```
Am I missing something? How do I make it treeshakeable? 

>Note:When I simply compile with tsc, the output is treeshakeable.

**Comment by hyrious** [comment]
You may be using some language features that having side-effects (i.e. not pure) when esbuild is generating es6 compatible code. For example, private fields. [see it live](https://hyrious.me/esbuild-repl/?version=0.14.34&mode=build&modules=%5B%5B%22main.js%22%2C%22import+%7B+A+%7D+from+%27.%2Fcheckbox%27%5Cn%5Cnconsole.log%28A%29%22%2C1%5D%2C%5B%22checkbox.tsx%22%2C%22import+%7B+Component+%7D+from+%27react%27%5Cn%5Cnexport+class+A+extends+Component+%7B%7D+%2F%2F+A+is+pure%5Cn%5Cnexport+class+B+extends+Component+%7B+%2F%2F+B+is+pure%2C+but%5Cn%5Ct%23p+%3D+1+%2F%2F+cannot+be+tree-shaked+when+targeting+es6%5Cn%7D%5Cn%5Cnexport+const+C+%3D+%7B+A%2C+B+%7D+%2F%2F+C+is+pure%22%2C0%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22target%22%3A%22es6%22%7D).

Besides, you said that tsc does generate tree-shakeable code. So what does the code look like? Which language feature you're using? Which bundler you're using to test the tree-shaking? Rollup and esbuild work differently here.

No matter what kind of code you're writting, you can always mark a variable to pure (i.e. tree-shakeable) by this way:

```js
var CheckboxRoot = /* @__PURE__ */ (() => {
  // use any side effect in this block
  var a = {}; a.x = 42; f(a); return a
})();
```

**Comment by raviteja83** [comment]
Thanks for the quick response. The components are based on styled components. only features like destructuing, default args are mostly used. 
I was checking the output with webpack build. Will check with target esnext once.

**Comment by hyrious** [comment]
> I have tried adding `/* @__PURE__ */`

Just want to mention that `minify: true` will strip these magic comments, which will invalidate the pure notation. You can instead use:

```
minifySyntax: true,
minifyIdentifiers: true,
minifyWhitespace: false, // comments are seen as whitespace in esbuild
```

**Comment by raviteja83** [comment]
I have also tried this with a simpler library that just exports svg's as React components. Same issue there as well. Even though I import a single Icon, everything is getting loaded. Also tried it with nextjs.

**Comment by raviteja83** [comment]
I tried the icons library with parcel. It seems to work. could be an issue with my webpack config. 
If a component has /* @__PURE__ */ in the output bundle after running through esbuild, can I expect it to be treeshaken with any bundler? Also, can you suggest a way to narrow down on the side effects for a component/function.

**Comment by hyrious** [comment]
> Also, can you suggest a way to narrow down on the side effects for a component/function.

1. Literals are pure (no side effects, can be tree-shaked if no other code uses it):

   ```js
   42, "hello", [{ world }], function(){ anything_here }

   // after tree shaking
   // nothing left
   ```

2. Function callings can be marked as pure (by `/* @__PURE__ */ f(anything)`) to tell the bundler the value returned by the calling can be safely removed if no other code uses it. See [the doc](https://esbuild.github.io/api/#pure).

   ```js
   /* @__PURE__ */ f(g(42))

   // after tree shaking (enable --minify-syntax in esbuild)
   g(42) // because we didn't mark `g()` as pure, so this side effect is kept
   ```

These rules are basically every bundler supporting tree-shaking would follow. Rollup and parcel may do something more (like constant-expression-folding) but esbuild is doing the fewest things here.

Let's see some code in action:

```jsx
// the variable `App` is pure because it equals to
// var App = function(){ whatever }
// before being used, the function can always be shaked
function App() {
  return <div>{(console.log(1), 42)}</div>
}

// oh no, `X.p = ...` triggers a setter, which may has unexpected side effects
// so this statement will make the variable `App` not pure as before
App.defaultProps = { a: 42 }

// Let's apply the technique mentioned above:
var App = /* @__PURE__ */ (() => {
  function App() { ... }
  App.defaultProps = { a: 42 }
  return App
})();
// Now the variable `App` is pure, it can be shaked.
```

**Comment by raviteja83** [comment]
const config = new A();
export const { styled } = config;

const Button = styled('button', { display: 'flex' }); 

This is how the components are created. The components using styled are not pure in the esbuild output. Instead of adding pure to every component, is there way all components using this can be made pure?

**Comment by evanw** [comment]
> Instead of adding pure to every component, is there way all components using this can be made pure?

No. If you want `Button` and `Checkbox` to be able to be tree-shaken, you'll have to do this:

```js
const config = new A();
export const { styled } = config;

const Button = /* @__PURE__ */ styled('button', { display: 'flex' });
const Checkbox = /* @__PURE__ */ styled('input', {});
```

The `/* @__PURE__ */` annotation is a convention that has arisen in the community (e.g. [UglifyJS](https://github.com/mishoo/uglifyjs) and [Terser](github.com/terser/terser)) and I believe is the most portable way to do this. But it must be added to function calls, not functions. That's just how it works.

**Comment by evanw** [comment]
There's good information in this thread that I believe wasn't captured in the docs yet. I've published some updated docs for this here: https://esbuild.github.io/api/#tree-shaking-and-side-effects. I'm closing this issue because this is now documented.
