### ISSUE TITLE
the result of resolve tslib is diffrent from webpack

### ISSUE THREAD

**Issue by underfin** [evanw/esbuild#2173]
### Description

The `tslib` package.json condition exports has a `module` filed. 
```.json
"exports": {
      ".": {
          "module": "./tslib.es6.js",
          "import": "./modules/index.js",
          "default": "./tslib.js"
      },
      "./": "./"
  }
```
It can be webpack used and keep bundle result correctly, but esbuild is not (esbuild use `import`).

### Reproduction

https://github.com/underfin/bug-reporter/tree/master/esbuild-tslib

- pnpm i && npm run build

esbuild output https://github.com/underfin/bug-reporter/blob/master/esbuild-tslib/esbuild-output.js#L454

webpack output https://github.com/underfin/bug-reporter/blob/master/esbuild-tslib/webpack-output/main.js#L23

### Maybe helpers issue

- https://github.com/microsoft/tslib/pull/129
- https://github.com/webpack/webpack/issues/11613

**Comment by hyrious** [comment]
`module` is not a formal field of node's `exports`, see [Conditional exports](https://nodejs.org/api/packages.html#conditional-exports) in the doc. esbuild won't support that.

I'll suggest that they use this pattern to force bundling the same file when targetting browser:

```js
"exports": {
  ".": {
    "node": {
      "import": "./modules/index.js",
      "require": "./tslib.js"
    },
    "default": "./tslib.es6.js"
  }
}
```

**Comment by evanw** [comment]
The name `module` is meaningless here. The standard doesn’t specify any special behavior for it. You can give it meaning using `--conditions=module` if you’d like: https://esbuild.github.io/api/#conditions.
