### ISSUE TITLE
Esbuild with uWebSockets.js

### ISSUE THREAD

**Issue by Jaikant** [evanw/esbuild#2179]
Trying esbuild with [uWebSockets.js](https://github.com/uNetworking/)

The resultant file, fails to execute, with the error - `Error: Cannot find module './uws_darwin_x64_93.node'`

The said module is available in `node_modules/uWebSockets.js/`

```
$ ls node_modules/uWebSockets.js/
LICENSE				uws_darwin_arm64_83.node	uws_linux_arm64_102.node	uws_linux_x64_93.node
README.md			uws_darwin_arm64_88.node	uws_linux_arm64_83.node		uws_win32_x64_102.node
index.d.ts			uws_darwin_arm64_93.node	uws_linux_arm64_88.node		uws_win32_x64_83.node
package.json			uws_darwin_x64_102.node		uws_linux_arm64_93.node		uws_win32_x64_88.node
source_commit			uws_darwin_x64_83.node		uws_linux_x64_102.node		uws_win32_x64_93.node
uws.js				uws_darwin_x64_88.node		uws_linux_x64_83.node
uws_darwin_arm64_102.node	uws_darwin_x64_93.node		uws_linux_x64_88.node
```

The esbuild options, I am using are:
```
esbuild.build({
      absWorkingDir: process.cwd(),
      entryPoints: {
        server: 'server.js'
      },
      outfile: process.cwd() + "/build/index.js",
      platform: "node",
      format: "cjs",
      target: "node14",
      bundle: true,
      write: false,
      bundle: true,
    })
    .then(async (build) => {
      console.log('Server build successful ')
      await writeServerBuildResult(build.outputFiles);
      return build;
    });
```

If copy the file `uws_darwin_x64_93.node` from `node_modules/uWebSockets.js/` to `./build`, all is well.
Why isn't esbuild being able to resolve `uws_darwin_x64_93.node`.

Not sure, if it is relevant, but the error message on execution is being thrown from this [line](https://github.com/uNetworking/uWebSockets.js/blob/797286515a9df9890c56803deaadd40c2c82dfc9/src/uws.js#L22).

**Comment by hyrious** [comment]
> Why isn't esbuild being able to resolve `uws_darwin_x64_93.node`.

Because esbuild cannot analyze a dynamic `require(a + b + c)` expression to know what files will be used.

**Comment by Jaikant** [comment]
@hyrious thanks that's useful to know. Thanks for the response.

**Comment by eudaimos** [comment]
For anyone coming here, the trick is to add `uWebSockets.js` as an [`external`](https://esbuild.github.io/api/#external) to the build and it'll work for watching/rebuild as well.

For command line example:
```sh
$ esbuild app.js --platform=node --external:uWebSockets.js
```
