### ISSUE TITLE
dyld: Symbol not found: _SecTrustEvaluateWithError

### ISSUE THREAD

**Issue by mwang0** [evanw/esbuild#2183]
env
os:   mac 10.12.6
node: v14.19.1
npm:  6.14.16
pnpm: 6.32.7

```sh
pnpm dev


> admin-web@1.0.0 dev /Users/meimei/workspace/admin-web
> vite --host

dyld: Symbol not found: _SecTrustEvaluateWithError
  Referenced from: /Users/meimei/workspace/admin-web/node_modules/.pnpm/esbuild-darwin-64@0.14.29/node_modules/esbuild-darwin-64/bin/esbuild
  Expected in: flat namespace

failed to load config from /Users/meimei/workspace/admin-web/vite.config.ts
error when starting dev server:
Error: The service was stopped
    at /Users/meimei/workspace/admin-web/node_modules/.pnpm/esbuild@0.14.29/node_modules/esbuild/lib/main.js:1332:25
    at /Users/meimei/workspace/admin-web/node_modules/.pnpm/esbuild@0.14.29/node_modules/esbuild/lib/main.js:663:9
    at Socket.afterClose (/Users/meimei/workspace/admin-web/node_modules/.pnpm/esbuild@0.14.29/node_modules/esbuild/lib/main.js:641:7)
    at Socket.emit (events.js:412:35)
    at endReadableNT (internal/streams/readable.js:1334:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
 ELIFECYCLE  Command failed with exit code 1.

```

**Comment by evanw** [comment]
[Go's official website](https://go.dev/dl/) says that Go requires macOS 10.13 or later, and you are using macOS 10.12. So you are using an unsupported platform. Your options are to either update your OS, try to build esbuild for yourself using an older version of the Go compiler, use the WebAssembly version of esbuild, or to use another tool instead.

**Comment by evanw** [comment]
I'm closing this because there's nothing to do here on esbuild's end. You'll have to use one of the workarounds described in my previous comment.

**Comment by siliushi** [comment]
i have resolved this porbloms
mac: 10.12.6

**Comment by XuBin63** [comment]
Unhandled Rejection (Error): register failed, invalid key getInitialState from plugin

这个报错是啥情况也搜不到解决方案。

**Comment by murongGitHub** [comment]
env
os: win11
node: v16.20.2
npm: 8.19.4

`
node:internal/modules/cjs/loader:1028
  const err = new Error(message);
              ^

Error: Cannot find module '78815644744557'
Require stack:

`

**Comment by tresorama** [comment]
## Workaround for macOS 11

The max version you can use is `esbuild` @ `0.26.0`

### If you use esbuild directly

This is your case if `esbuild` is a `devDependency` in your `package.json`.  
You must set fixed version in `package.json`.

```json
// package.json
{
  "devDependecies": {
    "esbuild": "0.26.0"
  }
}
```

### If you use esbuild indirectly (as dep of your deps)

This is your case if `esbuild` is not declared in your `package.json`, but a dep you have depends on esbuild (Vite is a strong candidate).  
You must use `overrides` in `package.json`.

**npm**  

```json
// package.json
{
  "overrides": {
    "esbuild": "0.26.0"
  }
}
```


**pnpm**  

```json
// package.json
{
  "pnpm": {
    "overrides": {
      "esbuild": "0.26.0"
    }
  }
}
```

**Comment by raihan71** [comment]
> "overrides": {
>     "esbuild": "0.26.0"
>   }

this works like a charm
