### ISSUE TITLE
Case-sensitive warning doesn't work with folders in windows

### ISSUE THREAD

**Issue by xxshady** [evanw/esbuild#2187]
### File structure
![image](https://user-images.githubusercontent.com/54737754/163732966-e64e76bf-5768-461d-b1cf-491bb20bd412.png)

#### main.ts
```js
import "./FOLDER" // *BUG* nothing in console output of esbuild on windows
import "./FILE" // esbuild case-sensitive warning 
```
#### file.ts
empty

#### folder/index.ts
empty

### Build command
```
esbuild main.ts --bundle --outfile=dist.js
```

**Comment by evanw** [comment]
This is not a bug. These warnings are meant to be helpful when they do happen, but they aren't meant to catch all problems. The presence of a warning should indicate a problem bu the absence of a warning shouldn't indicate the absence of a problem. In this case the structure of the code isn't set up to provide the type of warning you're asking for so I don't think it's reasonable to add this warning to esbuild.

**Comment by xxshady** [comment]
So the only proper way now to detect such problems is to run esbuild on case-sensitive OS?

**Comment by xxshady** [comment]
and i think there may already be a plugin that strictly checks file casing in imports

**Comment by hyrious** [comment]
Will this [tsconfig option](https://www.typescriptlang.org/tsconfig#forceConsistentCasingInFileNames) work?

**Comment by xxshady** [comment]
nope

**Comment by xxshady** [comment]
yes, but then we need to use tsc for this

**Comment by hyrious** [comment]
We obviously need ts for type checking, you can just install VSCode or other editors with typescript lsp to help you find these things when editing. While still use esbuild to bundle project quickly.

esbuild itself does not do type-checking at all, that's (one of the reason of) why it is fast.
