### ISSUE TITLE
Relative asset paths and client side routing

### ISSUE THREAD

**Issue by mattkauffman23** [evanw/esbuild#2189]
I'm working on a project that uses `react-router` to provide client side routing. So I have urls like: `/users/foo` that actually end up using `/index.html` as their html document. I also have components set up like this in my project:

```
- src
- - common
- - - SharedComponent.tsx
- - -  asset.png
```

Where `SharedComponent.tsx` imports `asset.png` relatively like `import asset from './asset.png;`. After doing a build using a file loader for `png`s the built js references the image as `./asset.png`. While this is correct from the perspective of `SharedComponent.tsx` when the browser is loading `/users/foo` it attempts to load the image from `/users/foo/asset.png` producing a 404.

What approach can I use to address this? Is there an options that lets me define where assets loaded via a file loader are copied to and then get the built js to reference those files absolutely? So rather than creating a path like `./asset.png` create one like `/assets/asset.png`.

**Comment by mbrevda** [comment]
[`publicPath='/'`](https://esbuild.github.io/api/#public-path)

**Comment by mattkauffman23** [comment]
Well that was easy... thank you! Not sure how I missed that option. Closing.
