### ISSUE TITLE
Build-in support to create aliases to import or require modules would be very helpful

### ISSUE THREAD

**Issue by doberkofler** [evanw/esbuild#2191]
I currently evaluating the migration of a very very lange and complex webpack configuration to esbuild.
I have found some esbuild plugins but was not able to get things working and believe that build-in support for aliases similar to [resolve.alias](https://webpack.js.org/configuration/resolve/#resolvealias) in webpack or [paths](https://www.typescriptlang.org/tsconfig#paths) in TypeScript would be a very helpful addition.

**Comment by evanw** [comment]
Yes, I agree. However, esbuild actually does support `paths` in `tsconfig.json`. It's respected in both TypeScript and JavaScript files while bundling.

**Comment by doberkofler** [comment]
@evanw Interesting, but I'm not sure I fully understand. I would prefer to just rely use the build-in features but noticed, that esbuild did automatically resolve the TypeScript modules but not the css modules. Is this this the expected behavior or should also the css modules be resolved? Please also note, that I created a separate SR #2192 that specifically focuses on the module resolution when chaining plugins. Thank you for your awesome work.

**Comment by doberkofler** [comment]
I also noticed that for example the `dataurl` loader needed to import image resources does not resolve accordingto the `paths` in `tsconfig.json` and does also not observe the alias set in the plugin `esbuild-plugin-alias`.

**Comment by maor-benami77** [comment]
It it supported only when bundling?
What about using esm without bundling?
The paths stay the same

**Comment by jsejcksn** [comment]
I just saw this mentioned in the latest [release notes](https://github.com/evanw/esbuild/releases/tag/v0.15.16).

How is it different from / advantageous over supporting standard [import maps](https://github.com/WICG/import-maps)?
