### ISSUE TITLE
Watch generating different output

### ISSUE THREAD

**Issue by bakura10** [evanw/esbuild#2194]
Hi :),

I am trying to use the watch mode with the following script:

```
esbuild js/common.js --outfile=dist/assets/common.js --bundle --format=esm --target=safari12 --watch
```

When the command is launched the first time, the proper file is generated and contains all my exports at the end of the bundled files:

<img width="400" alt="image" src="https://user-images.githubusercontent.com/1198915/164019257-c02efdde-ba27-4185-bab8-a399835e4a7b.png">

However, as soon as I change any file, they are properly detected by ESbuild and the file is re-generated, but the output is completely different. No exports are outputted at all. The first few lines of the file are also different, on watch it wraps everything around a self invocating function.

On initial build:

<img width="592" alt="image" src="https://user-images.githubusercontent.com/1198915/164019522-c0631086-460e-4b0c-9152-638561cc28a0.png">

On subsequent watch builds:

<img width="456" alt="image" src="https://user-images.githubusercontent.com/1198915/164019672-a3eb0c42-1581-4c0e-a0a2-213c2637c559.png">

Am I missing something here?

Thanks!

**Comment by hyrious** [comment]
It looks like the `format` was changed to `iife` on subsequent watch builds. However I cannot reproduce it on my local machine.

**Comment by bakura10** [comment]
Hi !

I have been able to reproduce the problem with a minimal example. The command is still this one:

```
js-common": "esbuild js/common.js --outfile=dist/assets/common.js --bundle --format=esm --target=safari12 --watch
```

The content of the "common.js":

```
/* Third party exports */
export * as FocusTrap from 'focus-trap';
```

Where focus-trap is this library: https://github.com/focus-trap/focus-trap (I am using version 6.7.3 of FocusTrap and 0.14.36 for ESBuild).

On initial launch of the command, the generated file starts as follows:

<img width="607" alt="image" src="https://user-images.githubusercontent.com/1198915/164156421-69728e97-903e-4f79-a998-0eff0475ae3a.png">

With the module properly exported at the end:

<img width="424" alt="image" src="https://user-images.githubusercontent.com/1198915/164156456-c60acb4f-2086-4c35-9290-792828e30c35.png">

If I change the comment (for instance) in the common.js, ESBuild recompile the file, but this time the start of the file looks like this:

<img width="699" alt="image" src="https://user-images.githubusercontent.com/1198915/164156556-92d51321-9b1b-43e2-9e65-a533e66e3c21.png">

With nothing being exported at the end:

<img width="536" alt="image" src="https://user-images.githubusercontent.com/1198915/164156590-4bce6767-c706-4683-95d2-861c80ea7d32.png">

If I do any further changes, this does not fix it. I have to shut down the terminal and relaunch it, then the initial load generates properly the code.

Hope this will give some hints!

**Comment by bakura10** [comment]
Hi,

I tried again and can definitely reproduce it. It seems to be completely random. I can edit the file 3 or 4 times and ESbuild will properly use ESM, and on the 5th changes then it will render incorrectly, then on the 6th time back to ESM.

The changes I am doing is trying to remove, add, remove, add, remove... the last ";". About once every 3-4 tries, it renders incorrectly.

**Comment by evanw** [comment]
I still can't reproduce this unfortunately. I have this going in one terminal:

```
while sleep 1; do (head -n 1 dist/assets/common.js) && (echo ';' >> js/common.js); done
```

and this going in the other terminal:

```
node_modules/.bin/esbuild js/common.js --outfile=dist/assets/common.js --bundle --format=esm --target=safari12 --watch
```

It's rebuilding every second but every time generates the same ESM code without an IIFE around it. Marking this as `unactionable` since there's nothing I can currently fix with esbuild using the content of this issue so far. I'd like to help but I'm not sure what else to do.

**Comment by bakura10** [comment]
No problem, i understand. I will try to check further on my end if I find something that may help reproduce it :)

**Comment by bakura10** [comment]
There is really something strange. I have tried to remove several flags into the command I run. I'm using this command instead (so no bundle, and no Safari 12 requirement)

```esbuild js/common.js --outfile=dist/assets/common.js --format=esm --watch```

I took a video showing what is happening: https://www.loom.com/share/17357e4dd9e94adb8dd2607c1bec88d9

As you can see, it seems to generate completely different output depending on the run, and I am completely unable to understand why :/

**Comment by hyrious** [comment]
I still cannot reproduce your behavior with exactly the same options (build without bundle). I'm guessing your JetBrains IDE does something on opened files&hellip;

**Comment by bakura10** [comment]
I'm reproducing it with Visual Studio Code as well :/.

**Comment by bakura10** [comment]
I have been unable to reproduce the issue those last few days... Closing this for now. Thanks everyone for inspecting it :)
