### ISSUE TITLE
--define remove line-breaks?

### ISSUE THREAD

**Issue by tmikaeld** [evanw/esbuild#22]
I tried using --define to remove line breaks, but it didn't work - maybe add it as an option?

**Comment by evanw** [comment]
I don’t understand what you mean. Can you provide a small example JavaScript file and esbuild command line? What are you trying to accomplish?

**Comment by tmikaeld** [comment]
I'm trying to use it with Cloudflare Workers, which often have troubles if there's line-breaks in the source.

However, this time it was due to this issue:
https://github.com/evanw/esbuild/issues/17#issuecomment-587522309

Still, Webpack has an option to remove line-breaks, maybe we can have that in esbuild too?

**Comment by evanw** [comment]
Are you saying that Cloudflare Workers won’t run JavaScript files that are more than one line long? Are you trying to use esbuild’s minification to put everything on one line?

The minified code that esbuild generates currently has some newlines in it due to the way parallel compilation happens with source map concatenation, since source maps are line based. I can potentially see if there’s a way to remove those newlines if it’s an important feature.

**Comment by tmikaeld** [comment]
They normallt do, I'm not always sure why they don't and I didnt have time to spend days digging into webpack. So line breaks are not a priority, more like a nice add-on.

The export default is more important, I could get a bundled and minified script to work on Workers when I tried on a script that don't use export default.

**Comment by evanw** [comment]
Can you give an example file (or files) where export default does not work as expected? That way I can reproduce and fix the issue.

**Comment by tmikaeld** [comment]
I'm unable to test it myself where I am right now, but here's some clues.

In a module:
```
export default async function something () {
   console.log('hello world');
}
```

And on import I had used conditionals:
```
const { default: something } = await import('./something');
```

Using conditional import is not very common, but handy when used in serverless context.

**Comment by tmikaeld** [comment]
By the way, I tried to get Cloudflare officially involved, but it didn't work ;-)

https://github.com/cloudflare/wrangler/issues/1089
