### ISSUE TITLE
Possible regression with 0.14.37 and new ASI behavior

### ISSUE THREAD

**Issue by edoardocavazza** [evanw/esbuild#2201]
Consider the following sample (I know it is not a meaningful piece of code, but it's the easiest case to reproduce):

**index.ts**
```js
export function check(value: number) {
    return 3 < value >>> 0;
}
```

```
esbuild index.ts
```

Output with 0.14.36
```js
export function check(value) {
  return 3 < value >>> 0;
}
```

Output with 0.14.37
```js
export function check(value) {
  return 3 >> 0;
}
```

**Comment by evanw** [comment]
Thanks for the report. I'll work on figuring out what to do here.
