### ISSUE TITLE
 esbuild-android-64 not accessible from esbuild

### ISSUE THREAD

**Issue by hgschwibbe** [evanw/esbuild#2202]
We try to execute `npm ci` from the [cypress/included:8.5.0](https://hub.docker.com/layers/included/cypress/included/8.5.0/images/sha256-a5560b974ceceb89fdd9c08930515ca412d3f5f8d415f03d5be27805a2018a96?context=explore) Docker image, and we got the following error message:

```
Executing "step_script" stage of the job script 00:01
$ npm ci
npm ERR! esbuild-android-64 not accessible from esbuild
npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-04-22T09_56_06_247Z-debug.log
Uploading artifacts for failed job
```

From the `package-lock.json` it looks like `jest-preset-angular` is the only dependency that requires `esbuild`:
```  
   "jest-preset-angular": {
      "version": "11.1.1",
      "dev": true,
      "requires": {
        "bs-logger": "^0.2.6",
        "esbuild": "0.14.11",
        "esbuild-wasm": "0.14.11",
        "jest-environment-jsdom": "^27.0.0",
        "pretty-format": "^27.0.0",
        "ts-jest": "^27.0.0"
      },
      "dependencies": {
        "esbuild-wasm": {
          "version": "0.14.11",
          "dev": true
        }
      }
    },
```

Its an Angular Web App where we try to run Cypress tests for and we don't understand why optional Android dependencies are required in a non Android environment.

**Comment by hgschwibbe** [comment]
[cypress/included:8.5.0](https://hub.docker.com/layers/included/cypress/included/8.5.0/images/sha256-a5560b974ceceb89fdd9c08930515ca412d3f5f8d415f03d5be27805a2018a96?context=explore) contains Node 14,
using [cypress/included:9.5.4](https://hub.docker.com/layers/included/cypress/included/9.5.4/images/sha256-31774246df793fdde7762e2452df288cc6f8d1f5e4ccc34cb8a76337fe402e43?context=explore) fixed the problem, this container uses Node 16.

**Comment by MCOfficer** [comment]
Voting to reopen this. Node 14 or 16, this smells a lot like a bug.

**Comment by Castier** [comment]
" npm i esbuild-android-arm64 --save-optional " resolve the problem for me :)

**Comment by haikyuu** [comment]
It wasn't happening before. So it's definitely a regression.

It only happens in CI environment in my case

**Comment by haikyuu** [comment]
Here is the log from npm install 
```
notsup Unsupported platform for esbuild-linux-mips64le@0.14.49: wanted {"os":"linux","arch":"mips64el"} (current: {"os":"linux","arch":"x64"})
```

**Comment by Castier** [comment]
Your log said the version is wanted is mips64el and you are in arch 64. 
try to install esbuild-linux-x64 in optionnal

**Comment by haikyuu** [comment]
> Your log said the version is wanted is mips64el and you are in arch 64. try to install esbuild-linux-x64 in optionnal or maybe if you want install esbuild-linux-mips64le@0.14.49, you need to install in optionnal

I only have esbuild in my dependencies. There is something off going on with node 14 I guess

**Comment by Castier** [comment]
you can have esbuild in your optionalDepencies like this :
 "optionalDependencies": {
    "esbuild-android-arm64": "^0.15.5",
    "fsevents": "^2.3.2"
  }
