### ISSUE TITLE
There is a compilation error

### ISSUE THREAD

**Issue by dongj0316** [evanw/esbuild#2203]
There is a compilation error, which seems to be the problem of esbuild. Is there any solution?

<img width="1927" alt="image" src="https://user-images.githubusercontent.com/18900209/164689668-18c3e9ac-328d-4a57-9c75-41668fde164e.png">

**Comment by dongj0316** [comment]
System info:
```
 System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 317.63 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.19.0 - ~/.nvm/versions/node/v14.19.0/bin/node
    Yarn: 1.22.17 - ~/.nvm/versions/node/v12.13.1/bin/yarn
    npm: 8.7.0 - ~/.nvm/versions/node/v14.19.0/bin/npm
  npmPackages:
    @vitejs/plugin-legacy: ^1.2.2 => 1.7.1 
    vite: ^2.4.2 => 2.9.1 
```

**Comment by hyrious** [comment]
It seems the `()` of a function iife expression will always be stripped, however the code will be invalid when it is after `export default`.

```js
const a = function(){}()      // valid
export default function(){}() // invalid
```

**Comment by dongj0316** [comment]
@hyrious Yes, this is a syntax error `'uncaught syntax error: unexpected token ')'`

<img width="568" alt="image" src="https://user-images.githubusercontent.com/18900209/164706711-166bef6c-23f7-4916-b5b6-89ab3d2a2107.png">

**Comment by dongj0316** [comment]
I did it temporarily

<img width="400" alt="image" src="https://user-images.githubusercontent.com/18900209/164706945-ac2e9a34-9fe0-417a-9700-067e7958c102.png">

**Comment by evanw** [comment]
Thanks for the report. This is a bug in esbuild. I will fix this in the next release. In the meantime, you should be able to work around this by changing `export default ...` into `let someVar = ...` followed by `export { someVar as default }`.
