### ISSUE TITLE
String.replaceAll function is not transformed successfully in chrome84

### ISSUE THREAD

**Issue by guguji5** [evanw/esbuild#2204]
I have the original javascript code include the function `replaceAll`,which is not support by chrome84. I try to esbuild it with target chrome84, but there is no difference after command `esbuild test.js --bundle --outfile=test.bundle.js --target=chrome84`

source code
`
var a ='slkdhfjkashjkfa2222'
var b = a.replaceAll('j', 9)
console.log(b)
`

transformed code
`
(() => {
  // test.js
  var a = "slkdhfjkashjkfa2222";
  var b = a.replaceAll("j", 9);
  console.log(b);
})();
`
But the replaceAll could not work at chrome 84

I am new to esbuild, so I am not sure whether it is  by desire or not, It is appreciate to any explanation  for that

**Comment by guguji5** [comment]
<img width="1460" alt="7C6316F1-9C8D-46B0-AF46-C4F4678B0E03" src="https://user-images.githubusercontent.com/17986248/164708202-74da4127-6beb-44da-8505-a22c45d8031f.png">

**Comment by hyrious** [comment]
esbuild doesn't do polyfill, you have to do it manually with (for example) core-js.

**Comment by zloirock** [comment]
So maybe already makes sense to add option for automatic `core-js` injection for remove [Babel](https://babeljs.io/docs/en/babel-preset-env#usebuiltins) or [SWC](https://swc.rs/docs/configuration/supported-browsers) from the build step in cases where they used only for that? -) It can be done enough simple.

**Comment by guguji5** [comment]
@hyrious Thanks for your reply. I don't know the polyfill and the so-called new language features clearly. 
new chrome can execute the more function, just like replaceAll. If esbuild don't transform it ,what esbuild do?

**Comment by guguji5** [comment]
@zloirock Is there any suggestion to support outdated browser in project, or it is not the scope of esbuild?

**Comment by zloirock** [comment]
`esbuild` can transpile modern syntax features, like exponentiation operator (`**`), to old versions of syntax. [`core-js`](https://github.com/zloirock/core-js) provide modern standard library features, like `String#replaceAll`.

You can load `core-js/actual` for get all required standard library.

You can load only required parts of standard library, like `core-js/actual/string/replace-all`.

You can use Babel or SWC for optimization or automatic injection of required `core-js` features, see the links above.

**Comment by evanw** [comment]
Thanks for the replies. Yes, automatic polyfill injection is outside of esbuild's scope. I have updated the documentation for `target` to mention this (including linking to `core-js`): https://esbuild.github.io/api/#target.

Closing as out of scope.
