### ISSUE TITLE
ClamAV: node_modules/esbuild-windows-64/esbuild.exe: Win.Malware.GrimPlanet-9946924-0 FOUND

### ISSUE THREAD

**Issue by candrews** [evanw/esbuild#2210]
Using ClamAV version 0.104.2 updated today, scanning `esbuild@0.13.8` results in:
```
/node_modules/esbuild-windows-64/esbuild.exe: Win.Malware.GrimPlanet-9946924-0 FOUND
```

I submitted a false positive report to ClamAV using the form at https://www.clamav.net/reports/fp

I'm reporting this issue so you're aware that virus scanners are reporting findings in this software in case there's any action you'd like to take.

**Comment by evanw** [comment]
Sorry, but there’s nothing I can do with these reports. Closing as invalid. I am already aware of this:  https://esbuild.github.io/faq/#anti-virus-software.
