### ISSUE TITLE
Can't convert RegExp:Unicode property escapes

### ISSUE THREAD

**Issue by YOOYY** [evanw/esbuild#2215]
There is a new feature in es2018, RegExp: Unicode property escapes; I tried converting it to es2015 but nothing changed in the code.

for example:
```
const regexGreekSymbol = /\p{Script_Extensions=Greek}/u;
console.log(regexGreekSymbol.test('π'));
```

output:
```
var regexGreekSymbol = /\p{Script_Extensions=Greek}/u;
console.log(regexGreekSymbol.test("\u03C0"));
```

this is my configuration:
```
{
  entryPoints: ['./demo.js'],
  outfile: 'outfile.js',
  target: ['es2015']
}
```

version: 0.14.38

**Comment by YOOYY** [comment]
> As far as I know there're some other new regex flags added recently. I wonder how could we polyfill/convert them correctly to lower environments. At least is there a reference implementation?

Babel seems to support converting RegExp.
I had this problem when using vite, so I had to add vite's babel plugin, I also saw esbuild's babel plugin on npm

**Comment by evanw** [comment]
> Babel seems to support converting RegExp.

Not always. It looks like Babel just converts `/./y` into `new RegExp(".", "y")` for example. I assume that will crash in older browsers. Here's the relevant Babel thread: https://github.com/babel/babel/issues/904. They are deliberately leaving this up to the polyfill to handle.

**Comment by jridgewell** [comment]
Babel can't implement sticky behavior without implementing a full matcher, so it's left to runtime. However, it's possible to support unicode, unicode properties escapes, unicode sets, named capture groups, and dotall through [`regexpu`](https://www.npmjs.com/package/regexpu-core). For named capture groups, it requires a [runtime wrapper](https://github.com/babel/babel/blob/b6d8434d17af056c860882efe7c670b9c6e0ec72/packages/babel-helpers/src/helpers/wrapRegExp.js).

**Comment by evanw** [comment]
Thanks very much for the context about what Babel does handle. However, despite that I decided to fix this by converting unsupported regular expression literals to `new RegExp()`. One reason is that lowering regular expressions looks like a significant increase in complexity and this conversion is a much simpler way to solve this problem. Another reason is that a pure syntax conversion isn't totally correct, and you may still want/need a polyfill anyway (e.g. if you need the `flags` property to represent the original source code).
