### ISSUE TITLE
Discrepancy between esbuild command and buildfile watch

### ISSUE THREAD

**Issue by hphu3** [evanw/esbuild#2222]
When running esbuild without a build file with the following options: 
`esbuild app/javascript/*.* --bundle --sourcemap --outdir=app/assets/builds`
The following log is emitted with a file changed:
```
[watch] build started (change: "app/assets/javascripts/sample_file.jsx")
[watch] build finished
```

I switched to using the build api with `watch: true` and there is nothing logged. Shouldn't these two be consistent?

I can add a plugin to log build start/finishes similar to https://github.com/evanw/esbuild/issues/1409 but according to that issue, it seems like there's no way to get the changed file `(change: "app/assets/javascripts/sample_file.jsx")`?

**Comment by susiwen8** [comment]
You need to add [`logLevel`](https://esbuild.github.io/api/#log-level)
`logLevel: 'info' | 'debug'`

**Comment by hphu3** [comment]
Thanks @susiwen8 that was it!
