### ISSUE TITLE
Can esbuild combine multiple js files into a single js file?

### ISSUE THREAD

**Issue by Jieiku** [evanw/esbuild#2224]
I am trying to combine two files, they work on [my site](https://jieiku.github.io/abridge-demo/) if loaded separately.

https://raw.githubusercontent.com/Jieiku/abridge-demo/main/search.min.js
https://raw.githubusercontent.com/Jieiku/abridge-demo/main/search_index.en.js

When I combine them (`cat search.min.js search_index.en.js > out.js`) they no longer work and throw an error:

`Uncaught TypeError: d is undefined`

I assume it is because the two js files have conflicting function or variable names.

I am wondering how to combine these files using esbuild. I appreciate any help, thank you.

**Comment by hyrious** [comment]
You can put them in different blocks:

```js
{ content of first file }
{ content of the second }
```

**Comment by Jieiku** [comment]
Thanks @hyrious I gave that a shot but the error persists.

```
cat search.min.js > out.js
echo -n "{ " | cat - search_index.en.js >> out.js
echo -n " }" >> out.js
```

**Comment by hyrious** [comment]
I just tried your repo locally and it may turns out to be the order -- `search_index` should be placed before `search.min.js`. Here's what I did:

```bash
> cat search_index.en.js > out.js
> cat search.min.js >> out.js
> git diff
```

```diff
diff --git a/index.html b/index.html
index e9ed2c1..b6153ba 100644
--- a/index.html
+++ b/index.html
@@ -36,8 +36,7 @@
     <meta name="twitter:card" content="summary_large_image" />
     <meta name="twitter:image" content="https://jieiku.github.io/abridge-demo/banner.png" />
     <meta property="og:image" content="https://jieiku.github.io/abridge-demo/banner.png" />
-    <script type="text/javascript" src="https://jieiku.github.io/abridge-demo/search_index.en.js?h=32dea888cd65b26a72ba054637175e8b28dbd40aa577993e21bff47e2ef44e0e" defer></script>
-    <script type="text/javascript" src="https://jieiku.github.io/abridge-demo/search.min.js?h=2fff7b6be8254a63d52589b6d83a03b2b0222a53591ac7a4f610437a7c2e7e74" defer></script>
+    <script type="text/javascript" src="out.js" defer></script>
   </head>
   <body>
     <header>
```

```bash
> npx @hyrious/w7
serving http://localhost:5000
```

There's no error.

**Comment by Jieiku** [comment]
WOW! I never would have guessed that the order mattered.

Thank you so much for taking the time to help me out!
