### ISSUE TITLE
`loader: 'tsx'` + `jsx: 'preserve'` doesn't work

### ISSUE THREAD

**Issue by hipstersmoothie** [evanw/esbuild#2229]
It seem like preserve is only implement for `jsx`. When I try to use it with `tsx` I get this error

```
 error: Invalid option in transform() call: "jsx"
```

**Comment by hyrious** [comment]
I didn't reproduce your error, here's what I did:

```js
> esbuild.transformSync('<div />', { jsx: 'preserve', loader: 'tsx' })
{ warnings: [], code: '<div />;\n', map: '' }
```

**Comment by evanw** [comment]
Marking as `unactionable` because there isn't enough information here to reproduce the problem.

**Comment by evanw** [comment]
Closing due to lack of a reply.
