### ISSUE TITLE
one more non-analyzable import

### ISSUE THREAD

**Issue by sergeysedoy97** [evanw/esbuild#2231]
e.g.
```
...
// Prevent React Native packager from seeing modules required with this
const nodeRequire = require;

function getRealmConstructor(environment) {
  switch (environment) {
    case "node.js":
    case "electron":
      return nodeRequire("bindings")("realm.node").Realm;
...
```
the `binding` module will not be bundled in this case.

**Comment by evanw** [comment]
If you obfuscate `require` like this to prevent it from being detected, then it will not be detected. This is not a bug with esbuild.

**Comment by sergeysedoy97** [comment]
Is it possible to detect such assignments and replace them?

**Comment by evanw** [comment]
I have added a way to detect code like this, which will be in the next release.
