### ISSUE TITLE
PluginName not working

### ISSUE THREAD

**Issue by xihangzhou** [evanw/esbuild#2236]
How to transfer the result of path resolution in a plugin to another plugin? For example, plugin1 resolve '/src/a'  to '/src/b', and then plugin1 need to transfer '/src/b'  to plugin2.  
I found that perhaps the property of pluginName can do this, but I failed. 
Thanks for replying

**Comment by evanw** [comment]
You can probably do this by calling [`resolve()`](https://esbuild.github.io/plugins/#resolve) and setting `pluginData`. This is what `pluginData` is intended to be used for.

**Comment by evanw** [comment]
Closing this as `pluginName` is not supposed to be used for this. Please use `pluginData` instead.
