### ISSUE TITLE
replace `private` with `#`

### ISSUE THREAD

**Issue by jimmywarting** [evanw/esbuild#2237]
could you maybe stop using the private keyword and use real private class properties/methods instead?

`private` is only soft private and isn't really truly private...
a minifier is able to mangle private class method into single letters for much smaller bundle sizes

**Comment by evanw** [comment]
The TypeScript team decides how TypeScript works, not me. TypeScript is deliberately transformed the same way as the official TypeScript compiler for compatibility. The change you are proposing would break many things including introspection of private properties. If you don't like how TypeScript works then you should ask the TypeScript team instead: https://github.com/microsoft/typescript.

Closing as invalid.

**Comment by jimmywarting** [comment]
fyi, i didn't mean that the TS compiler would change how typescript works. i just meant that you should be using `#` in your own codebase... 
like here for instance: https://github.com/evanw/esbuild/blob/02894dc765c333542b5727bed91cc9f882054ede/lib/shared/stdio_protocol.ts#L344

**Comment by evanw** [comment]
I see. Using `#` has performance overhead, so using `private` makes more sense here.
