### ISSUE TITLE
cjs file importing a default export from esm results is broken

### ISSUE THREAD

**Issue by shresthabijay** [evanw/esbuild#2238]
# Description of issue

If an cjs file imports an esm file with an default export, the resulting esbuild output is buggy.

## Steps to reproduce

[Minimal reproduction example repository](https://github.com/shresthabijay/esbuild-esm-to-cjs-issue)

- `yarn build`
- `node out.js` 

You will see that the code doesn't execute and complains that `esmPackageExport2` is not a function.

## Cause of the issue

Let's say we have these files.

```javascript
// esm-package.js

const esmPackageExport = () => 7
export default esmPackageExport
```

```javascript
// cjs-package.js

const esmPackageExport = require('./esm-package')

const cjsPacakgeExport = () => esmPackageExport() + 7
module.exports = cjsPacakgeExport
```

```javascript
// index.js

const test = require('./cjs-package')

console.log(test())
```

In this example if we build index.js, esbuild outputs following for the cjs package and esm package.

```javascript
// esm-package.js
var esm_package_exports = {};
__export(esm_package_exports, {
  default: () => esm_package_default
});

// cjs-package.js
var require_cjs_package = __commonJS({
  "cjs-package.js"(exports, module) {
    var esmPackageExport2 = (init_esm_package(), __toCommonJS(esm_package_exports));
    /**
     * Note: The code below won't execute because esmPackageExport2 is not function but an object.
     * 
     *  {
     *    default: actualExport
     *  }
     * 
     * This was causing the issue.
     */
    var cjsPacakgeExport = () => esmPackageExport2() + 7;
    module.exports = cjsPacakgeExport;
  }
});
```

**Comment by hyrious** [comment]
This is a known limitation of cjs-esm interop, as described in the [docs](https://esbuild.github.io/content-types/#default-interop).

In practice, when you read an esm module in cjs context --

```js
// esm.js
export let a = 1;
export default 2;

// cjs
require('./esm.js') => { default: 2, a: 1 }
```

**Comment by shresthabijay** [comment]
@hyrious Thanks! This makes sense.
