### ISSUE TITLE
Cannot serve without build options

### ISSUE THREAD

**Issue by Gohryt** [evanw/esbuild#2241]
If call serve without build options it gives _ERROR: Cannot read properties of undefined (reading 'color')_ error.
If call serve as serve(so, { color: false }) it works.

I think it should work without build options as if there is color: false.

**Comment by susiwen8** [comment]
```ts
export declare function serve(serveOptions: ServeOptions, buildOptions: BuildOptions): Promise<ServeResult>;
```

`buildOptions` is required

**Comment by evanw** [comment]
The build options are required. This is documented in the type definitions and is also documented here: https://esbuild.github.io/api/#serve-arguments. The intended use case for this API is to expose an esbuild build command over the network. I do not recommend using esbuild as a server without a build command. It wasn't designed for this and is not well suited for it, so I don't think it makes sense to encourage this.

Closing this issue as this requirement is already documented.

**Comment by charlag** [comment]
If I may suggest validating that two the number of arguments matches at all? I've blindly changed `.build()` for `.watch()` and was very confused by the error.
