### ISSUE TITLE
get list of imported chunks for each entrypoint

### ISSUE THREAD

**Issue by nitsky** [evanw/esbuild#225]
The initial load of a web app can be sped up by preloading all javascript chunks it needs using `<link>` tags. This could be done with the esbuild JS or Go API like it is done with Rollup, where each output chunk has `imports` and `dynamicImports` keys specifying paths to the corresponding output files. Rollup's CLI doesn't currently support outputting this information, but perhaps esbuild could optionally emit a manifest file with metadata on all emitted entrypoints, chunks, and assets.

Below is a link to the relevant Rollup docs section:

http://rollupjs.org/guide/en/#rolluprollup

**Comment by evanw** [comment]
Thanks for logging this. I agree that this would be good to do.

There actually already is a way to emit a metadata file (the `--metafile` flag) but it probably doesn't yet output all of the information it needs to for code splitting.

**Comment by evanw** [comment]
This information has been added to the metafile output starting in version 0.6.0. See [the release notes](https://github.com/evanw/esbuild/blob/6d0c49058a473194e19bcde662644cdeb6908e45/CHANGELOG.md#060) for more information.
