### ISSUE TITLE
Allow custom source-map location

### ISSUE THREAD

**Issue by icedtoast** [evanw/esbuild#2254]
Can an option(s) be added to:
 a) Place sourcemaps in a separate folder in the output directory? (e.g. output/dist.js , output/sourcemaps/dist.js.map )
 b) Customize the url used to refer to sourcemaps? So that they can be served from an internal-only host.

**Comment by evanw** [comment]
I believe this should already be straightforward to do. Use `write: false` to return an array of output files along with `sourcemap: 'external'` so `sourceMappingURL` comments are not already added. Then write some code to place the `.map` files wherever you want and to append `sourceMappingURL` comments to the corresponding source files with the correct location. This approach is not that much code and should already more flexible than providing an option within esbuild itself, so I'm not currently planning on adding this to esbuild's official API.

**Comment by EloB** [comment]
Is there a simple way to only output the same name as the file itself? I have multiple entrypoints and using entryNames with object (in/out).

<img width="236" alt="image" src="https://github.com/evanw/esbuild/assets/476567/2cbfbf33-b2d6-4794-946c-610321b9145c">

Current behaviour
```js
//# sourceMappingURL=/EndpointGet/app.mjs.map
```

Wanted behaviour
```js
//# sourceMappingURL=app.mjs.map
```
