### ISSUE TITLE
No loader is configured for ".node" files

### ISSUE THREAD

**Issue by alherd-by** [evanw/esbuild#2256]
I have case, when I need to use external library to hash passwords (argon2) in my netlify functions.
On netlify servers it's works fine. But when I'm trying to use `netlify functions:serve` on local machine I get this error:

```
No loader is configured for ".node" files: node_modules/argon2/lib/binding/napi-v3/argon2.node

    node_modules/argon2/argon2.js:12:12:
      12 │ } = require("./lib/binding/napi-v3/argon2.node");
```

Steps to reproduce:
- create function with importing dependency `argon2`

**Comment by hyrious** [comment]
See https://github.com/evanw/esbuild/issues/1051#issuecomment-806325487 and a working one in [tsup](https://github.com/egoist/tsup/blob/dev/src/esbuild/native-node-module.ts).
