### ISSUE TITLE
It's not possible to use `analyze` in a JS build script

### ISSUE THREAD

**Issue by kidroca** [evanw/esbuild#2257]
> Using the command-line interface can become unwieldy if you need to pass many options to esbuild. For more sophisticated uses you will likely want to write a build script in JavaScript using esbuild's JavaScript API

Indeed my build command became a bit to long and I switched to the JavaScript API
It's seems for whatever reason `analyze` is not accepted as a valid option, because I get the following error

```log
X [ERROR] Invalid option in build() call: "analyze"
```

<details>
<summary><h4>Sample build script<h4></summary>

```js
const esbuild = require('esbuild');
const svgrPlugin = require('esbuild-plugin-svgr');

esbuild
  .build({
    entryPoints: ['../modules/pdf/generatePdf.js'],
    analyze: true, // or analyze: 'verbose'
    bundle: true,
    platform: 'node',
    target: 'node16.13',
    loader: {
      '.js': 'jsx',
      '.png': 'dataurl',
      '.jpg': 'dataurl',
    },
    outfile: 'pdf-source.js',
    plugins: [svgrPlugin()],
  })
  .catch(() => process.exit(1));
```
</details>

Looks like `analyze` can be used only through the CLI.
Is there some way to make `esbuild` output analysis using the JS API?

**Comment by kidroca** [comment]
Thanks, I didn't notice source samples could be switched

**Comment by JoernBerkefeld** [comment]
tbh - i just stumbled over the same thing. the documentation is missing the example you gave here, @hyrious. would be great if you could copy paste it into the docs.

(use const instead of let though ;-))

**Comment by kidroca** [comment]
@JoernBerkefeld 
It's this thing (the tab) here:
![image](https://user-images.githubusercontent.com/12156624/201894539-6cc44cd0-2bb2-4ad5-8b55-85e1832d09e0.png)

https://esbuild.github.io/api/#analyze

**Comment by JoernBerkefeld** [comment]
shame on me. i overlooked those completely!
