### ISSUE TITLE
Support for custom TSConfig path

### ISSUE THREAD

**Issue by iamakulov** [evanw/esbuild#226]
Hey,

Is there a chance ESBuild would support specifying a custom path to `tsconfig.json`/`jsconfig.json`?

### Prior art

TypeScript supports passing a custom path to `tsconfig.json` using the `-p` (or `--project`) CLI parameter:

```
tsc -p tsconfig.tests.json
```

### Use cases

**My use-case:** the project I’m working on uses ESBuild for development and webpack for production. To run ESBuild, we have to replace one package with a custom mock. We do this through `tsconfig.json`’s `paths`:

```json
{
    "compilerOptions": {
        "paths": {
            ...
            "linaria": ["./environment/linaria-esbuild-mock.ts"]
        },
    }
}
```

However, putting this into the primary `tsconfig.json` results in a bad DX. (E.g., Ctrl+clicking `linaria` imports now leads to the mock instead of the original file.) It would be great if we had `tsconfig.esbuild.json` with necessary overrides – and were able to point ESBuild to use it.

**Other use-cases:** A few projects I saw used `tsconfig.test.json` for custom test configs (e.g., for custom `include`/`exclude` configuration).

**Comment by shcca** [comment]
I've just come across a need for this as well.

The project I'm working on has a setup where the entry point and its `tsconfig.json` exist in different dirs, which means `esbuild` can't read the associated `tsconfig.json`. Within `tsconfig.json`, I'm defining `compilerOptions.baseUrl` (similar to OP's `compilerOptions.paths`).

In my case, I'm using the `build()` API, so I need to the ability to set a `tsconfig.json` path programmatically.

So something like:

```
build({
  entryPoints: ['index.ts'],
  outfile: './dist/index.js',
  tsConfig: './some-other-path/tsconfig.json'
}).catch(() => process.exit(1))
```

This would provide a ton of flexibility for project organization and build setups. Thanks!

**Comment by evanw** [comment]
I see why this would be useful, but I'm having trouble figuring out what the right implementation would be. There can be many tsconfig.json files spread throughout a directory tree. Does this force-override all of them? Just one of them? Is it only a fallback if no tsconfig.json file is found? Does there need to be some way of configuring different overrides for different directories?

**Comment by shcca** [comment]
Good questions. I'm not sure. Here's what I'm doing.

I have a dir of serverless functions:

```
/lambda
  /group1
    func1.ts
  /group2
    func2.ts
  /modules
    package.json
  tsconfig.json
```

`modules` holds common npm packages. `func1` and `func2` can import them.

`tsconfig.json` contains `compilerOptions.baseUrl` with a value of `./modules/node_modules`.

When triggered, one or more functions are *independently* bundled in parallel using `Webpack`.

I set `tsconfig.json`'s absolute path using `ts-loader`'s `configFile` option: [https://github.com/TypeStrong/ts-loader#configfile](https://github.com/TypeStrong/ts-loader#configfile)

```
configFile: resolvePath('./lambda/tsconfig.json')
```

A key distinction here might be *independently*? `Webpack` takes one entry. Of course, I can only speak on my use case and not OP's, but maybe what's required is an optional `esbuild` 1:1 entry:tsconfig path relationship? It would eliminate having to juggle more than one `tsconfig.json` but still provide flexibility?

**Comment by iamakulov** [comment]
> I see why this would be useful, but I'm having trouble figuring out what the right implementation would be. There can be many tsconfig.json files spread throughout a directory tree. Does this force-override all of them? Just one of them? Is it only a fallback if no tsconfig.json file is found? Does there need to be some way of configuring different overrides for different directories?

I’d follow the TS implementation:

> **Using `tsconfig.json` or `jsconfig.json`**
> * By invoking `tsc` with no input files, in which case the compiler searches for the `tsconfig.json` file starting in the current directory and continuing up the parent directory chain.
> * By invoking `tsc` with no input files and a `--project` (or just `-p`) command line option that specifies the path of a directory containing a `tsconfig.json` file, or a path to a valid `.json` file containing the configurations.
— [Source](https://www.staging-typescript.org/docs/handbook/tsconfig-json.html)

Which means:

* `tsconfig.json`s in child directories are ignored. (E.g., in [this test project](https://github.com/evanw/esbuild/files/4884416/tsconfig.zip), both `root.ts` and `a/a.ts` are compiled to ES5 – even though `a/tsconfig.json` specifies `"target": "ESNext"`.)
* Specifying the explicit `tsconfig.json` path overrides any automatically detected `tsconfig.json`

**Comment by evanw** [comment]
Thanks for finding this information! After reading that, I agree that following the TypeScript implementation does sound like the right thing to do.

**Comment by seriouscoderone** [comment]
I have a related issue, where I want to bundle the tsconfig compilerOptions.paths as "nodeModules", but it only looks at the package.json https://github.com/aws/aws-cdk/blob/b2037d3b1a63715f71587681c84a5fd34be939a7/packages/%40aws-cdk/aws-lambda-nodejs/lib/util.ts#L91

**Comment by uglycoyote** [comment]
I'm not clear on whether this issue was closed because it was implemented, or denied?  Is there currently a way to esbuild to set a custom tsconfig path?  I could not find anything in the command line options list.

I'm in this situation becuase I'm combining esbuild and another bundler on the same repo.  Currently i have tsconfig's `target` property set to es5, but my esbuild doesn't know how to transform a bunch of the features used in the codebase to es5, forcing me to switch it to es6.  But using es6 breaks my existing build with the other bundler, so I would like to keep using what works (es5) when building with that bundler, and use es6 for esbuild.
