### ISSUE TITLE
DeprecationWarning: Invalid 'main' field in ... Please either fix that or report it to the module author

### ISSUE THREAD

**Issue by TuiMao233** [evanw/esbuild#2260]
Hi, I am developing a project using pnpm workspace and typescript and I want to utilize esbuild as packaging system.

In esbuild compilation, for example, @xxx/aaa refers to the package of @xxx/bbb. Since it is limited to runtime, the main: index.js of @xxx/bbb cannot be used as the final reference, but after compilation, dist/package .json is correct.

What should I do, or how can I ignore the error

~~~
(node:182616) [DEP0128] DeprecationWarning: Invalid 'main' field in 'F:\xxxx\packages\aaa\node_modules\bbb\package.json' of 'index.js'. Please either fix that or report it to the module author
(Use `node --trace-deprecation ...` to show where the warning was created)
~~~

**Comment by hyrious** [comment]
You can use this trick if you're using typescript monorepo like me: `"main": "src/index.ts"`. So that bundlers resolve to source code directly, which is super convenient for debugging. Then use [pnpm#publishConfig](https://pnpm.io/package_json#publishconfig) to change the main field on publishing.

**Comment by TuiMao233** [comment]
> 如果你像我一样使用 typescript monorepo，你可以使用这个技巧`"main": "src/index.ts"`：让打包器直接解析为源代码，调试起来超级方便。然后使用[pnpm#publishConfig](https://pnpm.io/package_json#publishconfig)更改发布时的主字段。

wow this is awesome he solved my problem and looks natural
