### ISSUE TITLE
Bug: sourcemap seems incorrect, which leads to mysterious coverage reports

### ISSUE THREAD

**Issue by shigma** [evanw/esbuild#2263]
- **reproduction**: https://github.com/shigma/cordis

Tests for this repo showed all fine expect for *service.ts*:

<img width="1154" alt="image" src="https://user-images.githubusercontent.com/33423008/170090665-f47bbda7-4a80-4037-9752-06e855bab414.png">

Even if the code fragment is obviously to be covered, the coverage still behaved abnormal:

![image](https://user-images.githubusercontent.com/33423008/170091218-1ceff843-cb7b-4eea-836d-b3277ae72bc9.png)

![image](https://user-images.githubusercontent.com/33423008/170091239-9f29eafe-77fe-4a1d-9758-bfd514e38e7f.png)

I think this may be caused by incorrect sourcemap, but I'm not sure.

**Comment by evanw** [comment]
There have been a few reports about problematic code coverage tools in the past too. The fault doesn't necessarily lie with esbuild; some code coverage tools are just bad at interpreting source maps. You can check out the source map in detail by uploading it here: https://evanw.github.io/source-map-visualization/. Here is an example: [(link)](https://evanw.github.io/source-map-visualization/#NTM3AC8vIHNyYy9zZXJ2aWNlLnRzCnZhciBTZXJ2aWNlID0gY2xhc3MgewogIGNvbnN0cnVjdG9yKGN0eCwgbmFtZSwgaW1tZWRpYXRlKSB7CiAgICB0aGlzLmN0eCA9IGN0eDsKICAgIENvbnRleHQuc2VydmljZShuYW1lKTsKICAgIGlmIChpbW1lZGlhdGUpIHsKICAgICAgdGhpc1tDb250ZXh0LmltbWVkaWF0ZV0gPSBuYW1lOwogICAgfQogICAgY3R4Lm9uKCJyZWFkeSIsIGFzeW5jICgpID0+IHsKICAgICAgYXdhaXQgdGhpcy5zdGFydCgpOwogICAgICBjdHhbbmFtZV0gPSB0aGlzOwogICAgfSk7CiAgICBjdHgub24oImRpc3Bvc2UiLCBhc3luYyAoKSA9PiB7CiAgICAgIGN0eFtuYW1lXSA9IG51bGw7CiAgICAgIGF3YWl0IHRoaXMuc3RvcCgpOwogICAgfSk7CiAgfQogIHN0YXJ0KCkgewogIH0KICBzdG9wKCkgewogIH0KICBnZXQgY2FsbGVyKCkgewogICAgcmV0dXJuIHRoaXNbQ29udGV4dC5jdXJyZW50XSB8fCB0aGlzLmN0eDsKICB9Cn07CmV4cG9ydCB7CiAgU2VydmljZQp9OwovLyMgc291cmNlTWFwcGluZ1VSTD1pbmRleC5lanMubWFwCjExNTQAewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsiLi4vc3JjL3NlcnZpY2UudHMiXSwKICAic291cmNlc0NvbnRlbnQiOiBbImltcG9ydCB7IEF3YWl0YWJsZSB9IGZyb20gJ2Nvc21va2l0J1xuLy8gaW1wb3J0IHsgQ29udGV4dCB9IGZyb20gJy4vY29udGV4dCdcblxuZXhwb3J0IGNsYXNzIFNlcnZpY2Uge1xuICBwcm90ZWN0ZWQgc3RhcnQoKTogQXdhaXRhYmxlPHZvaWQ+IHt9XG4gIHByb3RlY3RlZCBzdG9wKCk6IEF3YWl0YWJsZTx2b2lkPiB7fVxuXG4gIGNvbnN0cnVjdG9yKHByb3RlY3RlZCBjdHg6IENvbnRleHQsIG5hbWU6IHN0cmluZywgaW1tZWRpYXRlPzogYm9vbGVhbikge1xuICAgIENvbnRleHQuc2VydmljZShuYW1lKVxuXG4gICAgaWYgKGltbWVkaWF0ZSkge1xuICAgICAgdGhpc1tDb250ZXh0LmltbWVkaWF0ZV0gPSBuYW1lXG4gICAgfVxuXG4gICAgY3R4Lm9uKCdyZWFkeScsIGFzeW5jICgpID0+IHtcbiAgICAgIGF3YWl0IHRoaXMuc3RhcnQoKVxuICAgICAgY3R4W25hbWVdID0gdGhpc1xuICAgIH0pXG5cbiAgICBjdHgub24oJ2Rpc3Bvc2UnLCBhc3luYyAoKSA9PiB7XG4gICAgICBjdHhbbmFtZV0gPSBudWxsXG4gICAgICBhd2FpdCB0aGlzLnN0b3AoKVxuICAgIH0pXG4gIH1cblxuICBnZXQgY2FsbGVyKCk6IENvbnRleHQge1xuICAgIHJldHVybiB0aGlzW0NvbnRleHQuY3VycmVudF0gfHwgdGhpcy5jdHhcbiAgfVxufVxuIl0sCiAgIm1hcHBpbmdzIjogIjtBQUdPLG9CQUFjO0FBQUEsRUFJbkIsWUFBc0IsS0FBYyxNQUFjLFdBQXFCO0FBQWpEO0FBQ3BCLFlBQVEsUUFBUSxJQUFJO0FBRXBCLFFBQUksV0FBVztBQUNiLFdBQUssUUFBUSxhQUFhO0FBQUEsSUFDNUI7QUFFQSxRQUFJLEdBQUcsU0FBUyxZQUFZO0FBQzFCLFlBQU0sS0FBSyxNQUFNO0FBQ2pCLFVBQUksUUFBUTtBQUFBLElBQ2QsQ0FBQztBQUVELFFBQUksR0FBRyxXQUFXLFlBQVk7QUFDNUIsVUFBSSxRQUFRO0FBQ1osWUFBTSxLQUFLLEtBQUs7QUFBQSxJQUNsQixDQUFDO0FBQUEsRUFDSDtBQUFBLEVBbkJVLFFBQXlCO0FBQUEsRUFBQztBQUFBLEVBQzFCLE9BQXdCO0FBQUEsRUFBQztBQUFBLE1Bb0IvQixTQUFrQjtBQUNwQixXQUFPLEtBQUssUUFBUSxZQUFZLEtBQUs7QUFBQSxFQUN2QztBQUNGOyIsCiAgIm5hbWVzIjogW10KfQo=). The source map looks ok to me so you'll have to be more specific about what you mean by "incorrect" and what you'd like to see changed.

**Comment by evanw** [comment]
By the way I landed some minor source map improvements with this latest release regarding the range of class members. I noticed that the `get` keyword wasn't being covered, for example. You can compare the [previous source map](https://evanw.github.io/source-map-visualization/#NTM3AC8vIHNyYy9zZXJ2aWNlLnRzCnZhciBTZXJ2aWNlID0gY2xhc3MgewogIGNvbnN0cnVjdG9yKGN0eCwgbmFtZSwgaW1tZWRpYXRlKSB7CiAgICB0aGlzLmN0eCA9IGN0eDsKICAgIENvbnRleHQuc2VydmljZShuYW1lKTsKICAgIGlmIChpbW1lZGlhdGUpIHsKICAgICAgdGhpc1tDb250ZXh0LmltbWVkaWF0ZV0gPSBuYW1lOwogICAgfQogICAgY3R4Lm9uKCJyZWFkeSIsIGFzeW5jICgpID0+IHsKICAgICAgYXdhaXQgdGhpcy5zdGFydCgpOwogICAgICBjdHhbbmFtZV0gPSB0aGlzOwogICAgfSk7CiAgICBjdHgub24oImRpc3Bvc2UiLCBhc3luYyAoKSA9PiB7CiAgICAgIGN0eFtuYW1lXSA9IG51bGw7CiAgICAgIGF3YWl0IHRoaXMuc3RvcCgpOwogICAgfSk7CiAgfQogIHN0YXJ0KCkgewogIH0KICBzdG9wKCkgewogIH0KICBnZXQgY2FsbGVyKCkgewogICAgcmV0dXJuIHRoaXNbQ29udGV4dC5jdXJyZW50XSB8fCB0aGlzLmN0eDsKICB9Cn07CmV4cG9ydCB7CiAgU2VydmljZQp9OwovLyMgc291cmNlTWFwcGluZ1VSTD1pbmRleC5lanMubWFwCjExNTQAewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsiLi4vc3JjL3NlcnZpY2UudHMiXSwKICAic291cmNlc0NvbnRlbnQiOiBbImltcG9ydCB7IEF3YWl0YWJsZSB9IGZyb20gJ2Nvc21va2l0J1xuLy8gaW1wb3J0IHsgQ29udGV4dCB9IGZyb20gJy4vY29udGV4dCdcblxuZXhwb3J0IGNsYXNzIFNlcnZpY2Uge1xuICBwcm90ZWN0ZWQgc3RhcnQoKTogQXdhaXRhYmxlPHZvaWQ+IHt9XG4gIHByb3RlY3RlZCBzdG9wKCk6IEF3YWl0YWJsZTx2b2lkPiB7fVxuXG4gIGNvbnN0cnVjdG9yKHByb3RlY3RlZCBjdHg6IENvbnRleHQsIG5hbWU6IHN0cmluZywgaW1tZWRpYXRlPzogYm9vbGVhbikge1xuICAgIENvbnRleHQuc2VydmljZShuYW1lKVxuXG4gICAgaWYgKGltbWVkaWF0ZSkge1xuICAgICAgdGhpc1tDb250ZXh0LmltbWVkaWF0ZV0gPSBuYW1lXG4gICAgfVxuXG4gICAgY3R4Lm9uKCdyZWFkeScsIGFzeW5jICgpID0+IHtcbiAgICAgIGF3YWl0IHRoaXMuc3RhcnQoKVxuICAgICAgY3R4W25hbWVdID0gdGhpc1xuICAgIH0pXG5cbiAgICBjdHgub24oJ2Rpc3Bvc2UnLCBhc3luYyAoKSA9PiB7XG4gICAgICBjdHhbbmFtZV0gPSBudWxsXG4gICAgICBhd2FpdCB0aGlzLnN0b3AoKVxuICAgIH0pXG4gIH1cblxuICBnZXQgY2FsbGVyKCk6IENvbnRleHQge1xuICAgIHJldHVybiB0aGlzW0NvbnRleHQuY3VycmVudF0gfHwgdGhpcy5jdHhcbiAgfVxufVxuIl0sCiAgIm1hcHBpbmdzIjogIjtBQUdPLG9CQUFjO0FBQUEsRUFJbkIsWUFBc0IsS0FBYyxNQUFjLFdBQXFCO0FBQWpEO0FBQ3BCLFlBQVEsUUFBUSxJQUFJO0FBRXBCLFFBQUksV0FBVztBQUNiLFdBQUssUUFBUSxhQUFhO0FBQUEsSUFDNUI7QUFFQSxRQUFJLEdBQUcsU0FBUyxZQUFZO0FBQzFCLFlBQU0sS0FBSyxNQUFNO0FBQ2pCLFVBQUksUUFBUTtBQUFBLElBQ2QsQ0FBQztBQUVELFFBQUksR0FBRyxXQUFXLFlBQVk7QUFDNUIsVUFBSSxRQUFRO0FBQ1osWUFBTSxLQUFLLEtBQUs7QUFBQSxJQUNsQixDQUFDO0FBQUEsRUFDSDtBQUFBLEVBbkJVLFFBQXlCO0FBQUEsRUFBQztBQUFBLEVBQzFCLE9BQXdCO0FBQUEsRUFBQztBQUFBLE1Bb0IvQixTQUFrQjtBQUNwQixXQUFPLEtBQUssUUFBUSxZQUFZLEtBQUs7QUFBQSxFQUN2QztBQUNGOyIsCiAgIm5hbWVzIjogW10KfQo=) to the [latest source map](https://evanw.github.io/source-map-visualization/#NTMzAC8vIHNlcnZpY2UudHMKdmFyIFNlcnZpY2UgPSBjbGFzcyB7CiAgY29uc3RydWN0b3IoY3R4LCBuYW1lLCBpbW1lZGlhdGUpIHsKICAgIHRoaXMuY3R4ID0gY3R4OwogICAgQ29udGV4dC5zZXJ2aWNlKG5hbWUpOwogICAgaWYgKGltbWVkaWF0ZSkgewogICAgICB0aGlzW0NvbnRleHQuaW1tZWRpYXRlXSA9IG5hbWU7CiAgICB9CiAgICBjdHgub24oInJlYWR5IiwgYXN5bmMgKCkgPT4gewogICAgICBhd2FpdCB0aGlzLnN0YXJ0KCk7CiAgICAgIGN0eFtuYW1lXSA9IHRoaXM7CiAgICB9KTsKICAgIGN0eC5vbigiZGlzcG9zZSIsIGFzeW5jICgpID0+IHsKICAgICAgY3R4W25hbWVdID0gbnVsbDsKICAgICAgYXdhaXQgdGhpcy5zdG9wKCk7CiAgICB9KTsKICB9CiAgc3RhcnQoKSB7CiAgfQogIHN0b3AoKSB7CiAgfQogIGdldCBjYWxsZXIoKSB7CiAgICByZXR1cm4gdGhpc1tDb250ZXh0LmN1cnJlbnRdIHx8IHRoaXMuY3R4OwogIH0KfTsKZXhwb3J0IHsKICBTZXJ2aWNlCn07Ci8vIyBzb3VyY2VNYXBwaW5nVVJMPWluZGV4LmVqcy5tYXAKMTE3MQB7CiAgInZlcnNpb24iOiAzLAogICJzb3VyY2VzIjogWyJzZXJ2aWNlLnRzIl0sCiAgInNvdXJjZXNDb250ZW50IjogWyJpbXBvcnQgeyBBd2FpdGFibGUgfSBmcm9tICdjb3Ntb2tpdCdcbi8vIGltcG9ydCB7IENvbnRleHQgfSBmcm9tICcuL2NvbnRleHQnXG5cbmV4cG9ydCBjbGFzcyBTZXJ2aWNlIHtcbiAgcHJvdGVjdGVkIHN0YXJ0KCk6IEF3YWl0YWJsZTx2b2lkPiB7fVxuICBwcm90ZWN0ZWQgc3RvcCgpOiBBd2FpdGFibGU8dm9pZD4ge31cblxuICBjb25zdHJ1Y3Rvcihwcm90ZWN0ZWQgY3R4OiBDb250ZXh0LCBuYW1lOiBzdHJpbmcsIGltbWVkaWF0ZT86IGJvb2xlYW4pIHtcbiAgICBDb250ZXh0LnNlcnZpY2UobmFtZSlcblxuICAgIGlmIChpbW1lZGlhdGUpIHtcbiAgICAgIHRoaXNbQ29udGV4dC5pbW1lZGlhdGVdID0gbmFtZVxuICAgIH1cblxuICAgIGN0eC5vbigncmVhZHknLCBhc3luYyAoKSA9PiB7XG4gICAgICBhd2FpdCB0aGlzLnN0YXJ0KClcbiAgICAgIGN0eFtuYW1lXSA9IHRoaXNcbiAgICB9KVxuXG4gICAgY3R4Lm9uKCdkaXNwb3NlJywgYXN5bmMgKCkgPT4ge1xuICAgICAgY3R4W25hbWVdID0gbnVsbFxuICAgICAgYXdhaXQgdGhpcy5zdG9wKClcbiAgICB9KVxuICB9XG5cbiAgZ2V0IGNhbGxlcigpOiBDb250ZXh0IHtcbiAgICByZXR1cm4gdGhpc1tDb250ZXh0LmN1cnJlbnRdIHx8IHRoaXMuY3R4XG4gIH1cbn1cbiJdLAogICJtYXBwaW5ncyI6ICI7QUFHTyxJQUFNLFVBQU4sTUFBYztBQUFBLEVBSW5CLFlBQXNCLEtBQWMsTUFBYyxXQUFxQjtBQUFqRDtBQUNwQixZQUFRLFFBQVEsSUFBSTtBQUVwQixRQUFJLFdBQVc7QUFDYixXQUFLLFFBQVEsYUFBYTtBQUFBLElBQzVCO0FBRUEsUUFBSSxHQUFHLFNBQVMsWUFBWTtBQUMxQixZQUFNLEtBQUssTUFBTTtBQUNqQixVQUFJLFFBQVE7QUFBQSxJQUNkLENBQUM7QUFFRCxRQUFJLEdBQUcsV0FBVyxZQUFZO0FBQzVCLFVBQUksUUFBUTtBQUNaLFlBQU0sS0FBSyxLQUFLO0FBQUEsSUFDbEIsQ0FBQztBQUFBLEVBQ0g7QUFBQSxFQW5CQSxBQUFVLFFBQXlCO0FBQUEsRUFBQztBQUFBLEVBQ3BDLEFBQVUsT0FBd0I7QUFBQSxFQUFDO0FBQUEsRUFvQm5DLElBQUksU0FBa0I7QUFDcEIsV0FBTyxLQUFLLFFBQVEsWUFBWSxLQUFLO0FBQUEsRUFDdkM7QUFDRjsiLAogICJuYW1lcyI6IFtdCn0K) to see the difference. I don't know what's wrong in your case but if you want, you could try again with the latest release to see if that was the issue.

**Comment by shigma** [comment]
In fact, tests for a commit I pushed yesterday suddenly showed that the mysterious file had been covered normally. But the commit did not involve changes to that file. Anyway, I prefer to believe it's not an esbuild problem, so I've filed an issue with c8.

I will test my past commits with the new esbuild version. Thanks for your work!

**Comment by evanw** [comment]
Ok. Closing as an external issue then. We can always reopen this if there is something to fix in esbuild.
