### ISSUE TITLE
Discrepancy with TS compiler in import elision with preserveValueImports:true

### ISSUE THREAD

**Issue by AlexandreBonaventure** [evanw/esbuild#2268]
Hello,

I'm copying the comment from @sapphi-red found in this vite issue: https://github.com/vitejs/vite/issues/8339#issuecomment-1138269925

----

## Repro

```ts
import { type Map } from 'mapbox-gl';

let MyMap:Map
```

When `preserveValueImports` is `true`, the output behavior differs from TypeScript compiler. I thought a bit strange about the TS compiler's behavior at first, but [it seems intended](https://github.com/microsoft/TypeScript/pull/45998#:~:text=from%20%22./component%22-,Emit%20behavior,-Adding%20the%20type).

**Esbuild**
```ts
import {} from "mapbox-gl";
let MyMap;
```
**TS compiler remove the import line** 
```ts
let MyMap;
```

[`"preserveValueImports":true` (esbuild repl)](https://hyrious.me/esbuild-repl/?version=0.14.39&mode=transform&input=import+%7B+type+Map+%7D+from+%27mapbox-gl%27%3B%0A%0Alet+MyMap%3AMap%0A&options=--loader%3Dts+--tsconfig-raw%3D%27%7B%22compilerOptions%22%3A%7B%22preserveValueImports%22%3Atrue%7D%7D%27) [`"preserveValueImports":true` (ts playground)](https://www.typescriptlang.org/play?preserveValueImports=true#code/JYWwDg9gTgLgBAbzjAnmApnAsgQzHAXzgDMoIQ4ByEPAIwgA8BaAcwBtKBuAWACg+26eFhS4wALmx4+QA)

## Expected behaviour
Esbuild should probably behave like TS compiler in this case and remove the whole unused import line, otherwise it is keeping an empty import line which breaks tree-shaking/code-splitting in bundlers using esbuild like vite

--- 

When `preserveValueImports` is `false`, no discrepancies, it becomes:

```ts
let MyMap;
```

[`"preserveValueImports":false` (esbuild repl)](https://hyrious.me/esbuild-repl/?version=0.14.39&mode=transform&input=import+%7B+type+Map+%7D+from+%27mapbox-gl%27%3B%0A%0Alet+MyMap%3AMap%0A&options=--loader%3Dts+--tsconfig-raw%3D%27%7B%22compilerOptions%22%3A%7B%22preserveValueImports%22%3Afalse%7D%7D%27) [`"preserveValueImports":false` (ts playground)](https://www.typescriptlang.org/play?preserveValueImports=false#code/JYWwDg9gTgLgBAbzjAnmApnAsgQzHAXzgDMoIQ4ByEPAIwgA8BaAcwBtKBuAWACg+26eFhS4wALmx4+QA)

**Comment by evanw** [comment]
Thanks for the report. I can confirm the issue, and will fix this in the next release.
