### ISSUE TITLE
Eliminate dead code

### ISSUE THREAD

**Issue by jalal246** [evanw/esbuild#2269]
false condition is not eliminated even when `tree-shaking=true`.  Is this the expected behavior? 

```js
// index.js
class Foo {
  constructor(bar) {
    this.bar = bar;
  }

  getBar() {
    if (false) {
      console.log("Eliminate me");
    }
    return this.bar;
  }
}

export default Foo;
```

output file after executing `esbuild index.js --tree-shaking --format cjs --bundle --outfile=esbuild-index.js`

```js
var Foo = class {
  constructor(bar) {
    this.bar = bar;
  }
  getBar() {
    if (false) {
      console.log("Eliminate me");
    }
    return this.bar;
  }
};
var test_default = Foo;
```

I tried this with rollup: `rollup index.js --format cjs --bundle --file rollup-index.js`
 ```js
 'use strict';

class Foo {
  constructor(bar) {
    this.bar = bar;
  }

  getBar() {
    return this.bar;
  }
}

module.exports = Foo;
 ```
 
 EDIT: I added some code for more clarity.

**Comment by sidwebworks** [comment]
@jalal246 is foo a method on a class?

**Comment by jalal246** [comment]
@sidwebworks Yes.

**Comment by sidwebworks** [comment]
From what I understand most bundlers like Rollup and even Esbuild can only tree shake dead import/exports, top level variables etc, because it's easier to statically analyse them. 

The dynamic nature of the language makes it really hard to tree shake things like classes methods etc.

**Comment by sidwebworks** [comment]
That being said, I think that's what's happening. It might be possible in future where tree shaking these things will become much more possible but not sure if it's common as of now in the JS/TS tooling ecosystem.

@jalal246

**Comment by sidwebworks** [comment]
You can read more about the Why's and How's from this issue in Rollup
 https://github.com/rollup/rollup/issues/349

**Comment by sidwebworks** [comment]
Yeah, not a bug by any means. It's just a current limitation or more specifically something too complicated to tame right now.

**Comment by jalal246** [comment]
@sidwebworks maybe potential solution for rollup (https://github.com/ampproject/rollup-plugin-closure-compiler) I don't know if we can implement it for esbuild.

**Comment by jalal246** [comment]
Reopening it because I am not expecting `foo` to be eliminated. I am expecting the code inside the if statement to be so which is to my understanding it's not related to object properties.

**Comment by jalal246** [comment]
okay, thanks.
