### ISSUE TITLE
Feature request: transform tagged template literals (e.g. strip tabs in emotion css)

### ISSUE THREAD

**Issue by fr-an-k** [evanw/esbuild#2275]
Thanks for a great build system which eases our jobs!

However, I was wondering if there was a good way to for instance handle transformation of tagged template literals, such as emotion css, without resorting to regular expressions and reading/writing files in a separate pass.

To keep the code readable, whitespace is added to the string constants by the IDE/prettier, but is not automatically removed; I had this issue back in the rollup days as well.

Would be nice if you could pass an object like this:

```
await esbuild.build({
	...
	taggedTemplateLiteralTransforms: {
		css: str => str.replace(...)
	}
}
```

I expect the answer to be a reasonable "no", but perhaps this could be part of a future version.

**Comment by evanw** [comment]
I'm not going to do this, sorry. I understand why you would want this but I want esbuild to be a reasonably-scoped tool that just works the way JavaScript works. I don't think esbuild should become a way to experiment with alternate JavaScript semantics like this. That's what tools like Babel are designed for, and they are much better suited for this kind of thing. You could also consider [turning this feature of Prettier off](https://prettier.io/docs/en/options.html#embedded-language-formatting).
