### ISSUE TITLE
How to return value from an iife bundle?

### ISSUE THREAD

**Issue by chuanqisun** [evanw/esbuild#2277]
## Context

I'm using esbuild to generate a bundle that can be used as "content script" for a chrome extension. `iife` is the only compatible format as content script cannot be an es module.

```javascript
/* running from background thread */
chrome.scripting.executeScript(
    {
      target: {tabId: tabId},
      files: ['content-script-bundle.js'],
    },
    (results) => { ... }
);
```
[API Reference](https://developer.chrome.com/docs/extensions/reference/scripting/#injection-targets)

## The problem
The API exposes the return value of `content-script-bundle.js` via the callback. This is only possible if the generated `iife` return the value like this:

```javascript
/* in content-script-bundle.js */
(() => {
  return "some value"
})()

/* in background thread */
chrome.scripting.executeScript(
    {
      target: {tabId: tabId},
      files: ['content-script-bundle.js'],
    },
    (results) => {
      console.log(results[0].result); // output: "some value"
    }
);
```
[API Reference](https://developer.chrome.com/docs/extensions/reference/scripting/#handling-results)

However, the `iife` output from esbuild does not expose the return value. The closest I can get is:
```typescript
/* esbuild input */
async function main() {
  return "some value";
}

export default main();
```
```javascript
/* esbuild output */
(() => {
  async function main() {
    return "some value";
  }
  var demo_default = main();
})();
```

Do you see ways I can make the `iife` return a value like this?
```javascript
/* proposed output */
(() => {
  async function main() {
    return "some value";
  }
  var demo_default = main();
  return demo_default;
})();
```

## Appendix

My current work-around involves using globalName + footer. But I'd be thrilled to have a cleaner way to return from within `iife`.
```javascript
  esbuild
    .build({
      entryPoints: contentScriptEntries,
      bundle: true,
      format: "iife",
      globalName: "_contentScriptReturn",
      footer: { js: "_contentScriptReturn.default" }, // this allows the default export to be returned to global scope
    })
```

As you can see, the output is more bloated now due to the use of `globalName`
```javascript
var _contentScriptReturn = (() => {
  var __defProp = Object.defineProperty;
  var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
  var __getOwnPropNames = Object.getOwnPropertyNames;
  var __hasOwnProp = Object.prototype.hasOwnProperty;
  var __export = (target, all) => {
    for (var name in all)
      __defProp(target, name, { get: all[name], enumerable: true });
  };
  var __copyProps = (to, from, except, desc) => {
    if (from && typeof from === "object" || typeof from === "function") {
      for (let key of __getOwnPropNames(from))
        if (!__hasOwnProp.call(to, key) && key !== except)
          __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
    }
    return to;
  };
  var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

  // src/content-script-demo.ts
  var dom_reader_exports = {};
  __export(dom_reader_exports, {
    default: () => dom_reader_default
  });
  async function main() {
    return "some value";
  }
  var dom_reader_default = main();
  return __toCommonJS(dom_reader_exports);
})();
_contentScriptReturn.default // <------------ This is the hack
```

**Comment by evanw** [comment]
You're correct that there's no way to do this. The IIFE output is intended to be used in a `<script>` tag in HTML, for which there's no return value. Your approach of `globalName` + `footer` is indeed the most straightforward way to do this. Chrome's script format seems pretty esoteric so I don't think it makes sense to build support for that into esbuild itself. Instead I would recommend using the workaround that you have already found. FWIW using CommonJS export (i.e. `exports.default = main()`) instead of ESM export (i.e. `export default main()`) reduces the output size because esbuild needs to enforce the immutability of exports for ESM but not for CommonJS.

**Comment by eligrey** [comment]
@evanw This is a fundamental JS feature, not just a Chrome script oddity. I think support for not dropping the final return value should be reconsidered. There are many areas where final return values would be useful:

- JS execution sandboxes implemented through message-passing & JS string evaluation, including:
  - ShadowRealm evaluation input
  - Worker-based JS isolation systems
- Piping JS console input over the Chrome DevTools Protocol
- Piping JS input to node or deno REPLs

This seems worth of a `keepFinalReturn` build option.

**Comment by hyrious** [comment]
Have you tried `format: 'cjs'` with manual return statement?

[live example](https://hyrious.me/esbuild-repl/?version=0.14.41&mode=build&modules=%5B%5B%22main.js%22%2C%22return+require%28%27.%2Flib%27%29%22%2C1%5D%2C%5B%22lib.js%22%2C%22exports.a+%3D+1%22%2C0%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22cjs%22%7D)

**Comment by eligrey** [comment]
@hyrious Oh yeah, I completely forgot about that format. That probably solves the OP's issue.

**Comment by evanw** [comment]
Yes, that's a good point. I also forgot. If you don't need the nested scope that's part of the IIFE format, using `format: 'cjs'` might be what you're looking for.

**Comment by chuanqisun** [comment]
Thank you all for the suggestions! `format: 'cjs'` looks promising though I don't want to blend esm and cjs module syntax in one code base, especially when tsconfig is involved. 

I'll stay with the work-around for now.

**Comment by jsejcksn** [comment]
Is there any downside to supporting this configuration option: using the default export as the optional return value?

For example:

If no default export is present in the entrypoint module, then there'd be no change in the current behavior (no return statement in the IIFE), but if there is a default export, then it is used as the return value (`module.exports` in CJS and `export default` in ESM).

```js
// Input (ESM)

const someValue = 'hello world';

export default someValue;
```

```js
// Input (CJS)

const someValue = 'hello world';

module.exports = someValue;
```

```js
// Output (IIFE)

(() => {
  const someValue = 'hello world';
  return someValue;
})();
```

**Comment by hyrious** [comment]
https://esbuild.github.io/api/#global-name

**Comment by jsejcksn** [comment]
> https://esbuild.github.io/api/#global-name

@hyrious I think that's a different use case. Does it allow for non-object values? (important to the described option)

**Comment by hyrious** [comment]
It does, see [REPL](https://hyrious.me/esbuild-repl/?version=0.15.12&mode=transform&input=const+someValue+%3D+%27hello+world%27%3B%0A%0Amodule.exports+%3D+someValue&options=--format%3Diife+--global-name%3DA)

```js
// Input
module.exports = 'hello'

// --format=iife, result equals to
(() => { ... return 'hello' })()
```

It does not work for ESM default export because that value cannot be treat as **the whole module**.

**Comment by jsejcksn** [comment]
> It does not work for ESM default export because that value cannot be treat as **the whole module**.

I see — in that case, it's not a substitute: use with non-object values in ESM is just as important.

**Comment by AlttiRi** [comment]
`--global-name=xyz` generates ~30 extra  lines of the code (`__toCommonJS` and etc), while only `--format=iife` just wraps the result code in IIFE without adding something else.

Is it possible to get the same result as with Rollup?

I need to wrap a code into IIFE with minimum of an extra code (without `__toCommonJS` and etc) as Rollup does it.

**Comment by dhowe** [comment]
Does this have a good solution, besides the return/footer hack. I need to generate output as suggested above:
```js
var MyClass = (function (exports) {
    'use strict';

    class MyClass {}

    exports.MyClass = MyClass;

    return exports;

})({});
```
