### ISSUE TITLE
Include the pathname of file importing a module to plugin API

### ISSUE THREAD

**Issue by whaaaley** [evanw/esbuild#2278]
I'm trying to implement a glob import plugin that resolves to an object tree that matches the file structure. The issue I'm having is that the plugin doesn't really know where it is in the project so it can't output an object for the specific file importing the glob path. Every object that is output starts at a user's home directory.

Is getting the current file doing the import outside the scope of esbuild?

Thanks! 🙏

**Comment by hyrious** [comment]
You can actually know where it is in `onLoad`'s `args.resolveDir`.

**Comment by evanw** [comment]
The `onResolve` callback has a `resolveDir` argument for this: https://esbuild.github.io/plugins/#on-resolve-arguments. If you are writing an `onLoad` callback as well, you can return `resolveDir` which will then be passed to any future `onResolve` callbacks for imports inside the loaded file: https://esbuild.github.io/plugins/#on-load-results.

**Comment by whaaaley** [comment]
Oooooh. Gotcha! I think I got something working. 👍
