### ISSUE TITLE
property access inside `/* @__PURE__ */` makes an object not removed when minifying

### ISSUE THREAD

**Issue by sapphi-red** [evanw/esbuild#2279]
For example, `BaseTransitionImpl` is not removed from the output.
```js
const TransitionHookValidator = [Function, Array];
const BaseTransitionImpl = {
  props: {
    mode: String,
    appear: Boolean,
    persisted: Boolean,
    onBeforeEnter: TransitionHookValidator,
    onEnter: TransitionHookValidator,
    onAfterEnter: TransitionHookValidator,
    onEnterCancelled: TransitionHookValidator,
    onBeforeLeave: TransitionHookValidator,
    onLeave: TransitionHookValidator,
    onAfterLeave: TransitionHookValidator,
    onLeaveCancelled: TransitionHookValidator,
    onBeforeAppear: TransitionHookValidator,
    onAppear: TransitionHookValidator,
    onAfterAppear: TransitionHookValidator,
    onAppearCancelled: TransitionHookValidator
  }
};
/* @__PURE__ */ Object.assign({}, BaseTransitionImpl.props);
```
[esbuild repl](https://hyrious.me/esbuild-repl/?version=0.14.42&mode=transform&input=const+TransitionHookValidator+%3D+%5BFunction%2C+Array%5D%3B%0Aconst+BaseTransitionImpl+%3D+%7B%0A++props%3A+%7B%0A++++mode%3A+String%2C%0A++++appear%3A+Boolean%2C%0A++++persisted%3A+Boolean%2C%0A++++onBeforeEnter%3A+TransitionHookValidator%2C%0A++++onEnter%3A+TransitionHookValidator%2C%0A++++onAfterEnter%3A+TransitionHookValidator%2C%0A++++onEnterCancelled%3A+TransitionHookValidator%2C%0A++++onBeforeLeave%3A+TransitionHookValidator%2C%0A++++onLeave%3A+TransitionHookValidator%2C%0A++++onAfterLeave%3A+TransitionHookValidator%2C%0A++++onLeaveCancelled%3A+TransitionHookValidator%2C%0A++++onBeforeAppear%3A+TransitionHookValidator%2C%0A++++onAppear%3A+TransitionHookValidator%2C%0A++++onAfterAppear%3A+TransitionHookValidator%2C%0A++++onAppearCancelled%3A+TransitionHookValidator%0A++%7D%0A%7D%3B%0A%2F*+%40__PURE__+*%2F+Object.assign%28%7B%7D%2C+BaseTransitionImpl.props%29%3B&options=--minify+--tree-shaking%3Dtrue+--format%3Desm)

`terser` outputs the following code.
```js
const o=[Function,Array];Boolean,Boolean;
```

Is this is not supported because it is difficult to support this without performance degration?

refs: https://github.com/vuejs/core/blob/dddbd96dfe69292cee401f72d2703e8fb3708a14/packages/runtime-dom/src/components/Transition.ts#L72-L77

**Comment by hyrious** [comment]
Yes, AFAIK property accessing is always treated as having side effects in esbuild since there might defined a custom getter. Tracking the pureness of an object prop is not in esbuild's goal.

There's still some way to hack around this, for example:

```js
// as pure as "var a = 1"
var pure_value = /* @__PURE__ */ (() => obj.prop)()
```

**Comment by sapphi-red** [comment]
I found a weird behavior.

- `BaseTransitionImpl` gets removed.
  ```js
  const a = /* @__PURE__ */ (() => BaseTransitionImpl.props)();
  ```
- `BaseTransitionImpl` doesn't get removed.
  ```js
  /* @__PURE__ */ (() => BaseTransitionImpl.props)();
  ```
  ```js
  const a = /* @__PURE__ */ Object.assign({}, BaseTransitionImpl.props);
  ```
  ```js
  /* @__PURE__ */ Object.assign({}, BaseTransitionImpl.props);
  ```

Is there any difference between these?

**Comment by hyrious** [comment]
There's a weird case to use `--tree-shaking` and `--minify` togather:

In:

```js
/* @__PURE__ */ (() => a.b)();
var c = /* @__PURE__ */ (() => d.e)();
```

Out:

```js
a.b; // won't be here if removed --minify-syntax
```

[see in repl](https://hyrious.me/esbuild-repl/?version=0.14.42&mode=transform&input=%2F*+%40__PURE__+*%2F+%28%28%29+%3D%3E+a.b%29%28%29%3B+%2F%2F+try+remove+--minify%0Avar+c+%3D+%2F*+%40__PURE__+*%2F+%28%28%29+%3D%3E+d.e%29%28%29%3B&options=--tree-shaking+--minify).

So this might be a hidden bug in esbuild.

**Comment by hyrious** [comment]
> Is there any difference between these?

The first 2 cases should be tree-shaked. This is because `/* @__PURE__ */` is marking **the function call** to return a pure value. Which means:

<pre>
var a = /* @__PURE__ */ <ins>foo(</ins>whatever<ins>)</ins>
</pre>

The annotation does nothing about the things in braces. So if they have side effects, they are kept.

**Comment by sapphi-red** [comment]
That makes sense.

So here it should be `/* @__PURE__ */ (() => Object.assign({}, BaseTransitionImpl.props))();`? (though it does not work currently as you pointed out https://github.com/evanw/esbuild/issues/2279#issuecomment-1140449282)

**Comment by evanw** [comment]
Thanks for the report. This is just an oversight. Looks like I missed a `break` in https://github.com/evanw/esbuild/commit/fccd1c4e34281b86596f7f08b469db8966e7f310 when I added the additional case for minifying unused IIFEs. That caused the code that minifies `/* @__PURE__ */ (() => x)()` into nothing to be overridden by the code that minifies `(() => x)()` into `x`.

I'll fix this in the next release. If you want to work around this in the meantime, you can use `/* @__PURE__ */ (() => x)(0)` instead of `/* @__PURE__ */ (() => x)()` since this optimization currently only applies if there are zero arguments.

**Comment by sapphi-red** [comment]
Thank you!
