### ISSUE TITLE
ENOBUFS failure with write: false

### ISSUE THREAD

**Issue by alexey-detr** [evanw/esbuild#228]
Thanks for your amazing job! I'm really inspired with esbuild and trying to integrate it into a jest transform to optimize our unit-testing pipeline.

If you'll try to build an in-memory `write: false` bundle synchronously esbuild fails with

```
spawnSync .../node_modules/esbuild/bin/esbuild ENOBUFS
```

Unfortunately jest supports only sync transformers so it's not an option to switch to an async API (which acutally works just fine).
My build config:

```js
const { buildSync } = require('esbuild');

module.exports = {
  process(content, filename) {
    const { outputFiles } = buildSync({
      entryPoints: [filename],
      bundle: true,
      loader: {
        '.js': 'jsx',
        '.tsx': 'tsx',
        '.scss': 'text',
      },
      platform: 'node',
      format: 'cjs',
      target: 'es2019',
      write: false,
    });
    // ...
  },
};
```

**Comment by evanw** [comment]
This should be fixed in version 0.5.23.
