### ISSUE TITLE
an error occurs when first build with incremental is true, and can't get the build instance

### ISSUE THREAD

**Issue by xiaoboost** [evanw/esbuild#2280]
When I use build method with config `incremental: true`，such as：

```js
const esbuild = require('esbuild');
const path = require('path');

async function main() {
  try {
    const instance = await esbuild.build({
      incremental: true,
      bundle: true,
      minify: false,
      watch: true,
      entryPoints: [path.join(__dirname, './index.ts')],
    });

    console.log(`重编译实例：${!!instance}`);
  } catch (e) {
    console.log(e);
  }
}

main();
```

If the first build occurs a error, for example, the code in `index.ts`：

```ts
let let
```

I can't get result of `esbuild.build`, it will be into `catch` statement.

I think do not throw errors here and set errors to `errors` property of result, it can be better.

**Comment by susiwen8** [comment]
I think it's better not throwing error under `watch` mode at first build.
