### ISSUE TITLE
Package LICENSE in NPM registry

### ISSUE THREAD

**Issue by jodyheavener** [evanw/esbuild#2285]
Hi there! In a couple projects I'm using [license-checker-rseidelsohn](https://github.com/RSeidelsohn/license-checker-rseidelsohn) to be able to automate packaging all the licenses of my projects' dependencies in their distributed packages. I would like to include esbuild's [LICENSE](https://github.com/evanw/esbuild/blob/master/LICENSE.md) but it looks like esbuild doesn't ship that file to the [NPM registry](https://www.npmjs.com/package/esbuild). Would there be a possibility of including it?

**Comment by evanw** [comment]
Sure, I can do that.

One thing to point out is that the esbuild package [already indicates what license it uses](https://github.com/evanw/esbuild/blob/43b8e152b7af75bbdbafe6e6ef794f15a226301f/npm/esbuild/package.json#L39). You could consider updating your software to check for the `license` field in the package's `package.json` file.
