### ISSUE TITLE
Size value in build summary (logLevel: info) is wrong

### ISSUE THREAD

**Issue by lukeed** [evanw/esbuild#2286]
Hey~!

I consistently see a resulting bundle size that's incorrect when using `logLevel: info` (JS API). Here are two examples I have:

```txt
  path/to/foo/index.js  8.0kb
  path/to/bar/index.js  16.4kb
```

But when I use `write: false` and look at the `result.result.outputFiles` to print my own build summary, I'm getting different values when looking at the `file.content` and/or `file.text` value. The previous two examples are shown here:

```js
// snip
result.outputFiles!.map(o => {
  console.log('~>>> text.length', o.text.length);
  console.log('~>>> contents.byteLength', o.contents.byteLength);
});
// snip
```

```
~>>> text.length 8151
~>>> contents.byteLength 8151
~>>> text.length 16769
~>>> contents.byteLength 16769
```

Similarly, when I `Get Info` using macOS Finder on the output files, the value macOS shows is the same as logged in Node.js:

<img width="198" alt="Screen Shot 2022-05-30 at 10 18 48 PM" src="https://user-images.githubusercontent.com/5855893/171098290-74f6c2f5-90ec-40ed-b0f5-eede4339eeb8.png">

TBH, I wouldn't really mind that the size values were off except that I'm looking to print my own summary _while also_ passing thru an `--analyze` flag that logs `esbuild.analyzeMetafile` output directly. This is problematic because the analysis also shows the `16.4kb` and `8.0kb` values, so the _true values_ that I show won't align with the analysis underneath that esbuild is providing.

**Comment by wolffc** [comment]
a kilo byte are 1024 bytes if you devide by 1024 you get the following results:
8151 / 1024 = 8.0 (rounded from 7.9599609375)
16769 / 1024 = 16.4 (rounded from 16.3759765625) 

so to mee it seems the calucation is correct. 
the "on disk part" refers to the space a file use on the disk. and this can be vastly different depending on the "bock size" of your storage device / filesystem. a a block is allways fully used even if just one byte is written to it. but for network transfer only the the content lenght is important not the size on disk)

**Comment by lukeed** [comment]
Derp, oversight 🙈 Thanks for the patient explanation!
