### ISSUE TITLE
Print warning or onwarn callback for those external libs that doesnt resolve

### ISSUE THREAD

**Issue by aelbore** [evanw/esbuild#229]
- instead throw an error because of external not able to resolve, print warnings or have onwarn callback 
- rollup has onwarn callback by default it prints warning for un-resolvable external libs
- if has onwarn callback developer can decide what will do for the warnings produce by the build
- maybe this is only for external libs which is in the node_modules or any node built-in modules.

main.ts
```javascript
import * as fs from 'fs'

export async function readFile(filename: string) {
  return fs.promises.readFile(filename, 'utf-8')
}
```

build script
```javascript
  const outFiles = buildSync({   
    entryPoints: [ 'main.ts' ],
    outfile: './dist/main.js',
    minify: false,
    bundle: true, 
    write: false,
    target: 'esnext',
    sourcemap: true
  })
```

**Comment by evanw** [comment]
Why do you need this? Why not just add those external modules to the build script?

Also, in case it's helpful: if you're building for node and want to use the `fs` library you can set `platform: 'node'` to automatically configure all builtin node modules as external modules.

**Comment by aelbore** [comment]
@evanw i think your right get all pkg.dependences, pkg.devDependencies and pkg.peerDepedendecies as external.
but i think it would be good like instead of throwing exceptions or failed the build, it will treat external dependencies that libs that doesnt resolve and print warnings.

**Comment by aelbore** [comment]
@evanw i think we can close this, many thanks for your work
