### ISSUE TITLE
keep dynamic import when target set to es5

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#2290]
Currently esbuild will transform dynamic import to require when target set to es5, which will cause problem when we want to further transpile the transpiled code to systemjs format(commonjs is not supported to systemjs).

**Comment by evanw** [comment]
I'm adding the ability to configure syntax feature support at the individual feature level in the next release. So you will be able to do `--supported:dynamic-import=true` to do this. I'm closing this issue because I believe this should now be fixed.
