### ISSUE TITLE
Tree shaking for slices of imported json files

### ISSUE THREAD

**Issue by ggoodman** [evanw/esbuild#230]
It appears that esbuild could benefit from a size reduction in produced assets by treating imported `.json` as a module record itself so that unused portions of the imported json structure can be pruned off.

As you can see below, the explicit graph from `index.ts` only touches the `name` property of the imported json. In theory, the rest could be shaved off. This is a contrived example, but as the module graph increases in size, this could produce quite a bit of cumulative space saving.

**index.ts**:
```ts
export { name } from './package.json';
```

**package.json**:
```json
{
  "name": "test",
  "version": "0.0.0",
  "lots_of_other_crap": "..."
}
```

**`esbuild --bundle --outfile=index.js --minify index.ts --format=esm`**:
```js
let d=Object.defineProperty,f=Object.prototype.hasOwnProperty,h=(a,b)=>()=>(b||(b={exports:{}},a(b.exports,b)),b.exports),i=a=>d(a,"__esModule",{value:!0}),j=(a,b)=>{i(a);if(typeof b==="object"||typeof b==="function")for(let c in b)f.call(b,c)&&!f.call(a,c)&&c!=="default"&&d(a,c,{get:()=>b[c],enumerable:!0});return a},k=a=>a&&a.__esModule?a:j(d({},"default",{value:a,enumerable:!0}),a);var e=h((a,b)=>{b.exports={name:"test",version:"0.0.0",lots_of_other_crap:"..."}});const m=k(e());const p=m.name;export{p as name};
```

**Comment by evanw** [comment]
I’ve been thinking about doing this. It’s good to hear that it’d make a significant difference for you. I’ll look into it.

**Comment by ggoodman** [comment]
I haven't actually measured the impact but did notice this in the bundled / minified output when kicking the tires with `esbuild`.

Not knowing the complexity of implementing such a feature in your current architecture, it seemed like a 'quick win' that might be worth suggesting.

**Comment by ggoodman** [comment]
EPIC.

**Comment by cscheffauer** [comment]
@evanw i know this has been closed already - wanted to check if there are any plans to improve this tree shaking mechanism further to allow for nested properties in JSON files as well, not only top level entries (similar to this: https://github.com/privatenumber/webpack-json-access-optimizer)

**Comment by jlukic** [comment]
Tree shaking for nested properties would be huge for me as well, working on a web component framework that defines web components from a very verbose "specification" json file, that only uses a portion of nested properties.
