### ISSUE TITLE
Get a map of entryPoints to final entryNames?

### ISSUE THREAD

**Issue by bcomnes** [evanw/esbuild#2301]
When building a series of `entryPoints`, and customizing the final `entryNames` by adding a hash or whatnot (e.g. `[dir]/[name]-[hash]`), is there a way to get a map the input entryNames to the final `entryNames` that contain the final hash?

**Comment by mbrevda** [comment]
You can try this as a plugin:

```js
const mapOutputToEntry = {
  name: 'mapOutputToEntry',
  setup(build) {
    build.onEnd(result => {
      const ob = {}
      Object.keys(result?.metafile?.outputs || {}).forEach(file => {
        const {entryPoint} = result.metafile.outputs[file]
        if (entryPoint) ob[entryPoint] = file
      })

      result.outputMap = ob
    })
  }
}
```

**Comment by bcomnes** [comment]
Thanks! I'll try it out.
