### ISSUE TITLE
Import .tsx as text

### ISSUE THREAD

**Issue by anubra266** [evanw/esbuild#2305]
Is it possible to import a `.tsx` file as text. (With text loader)

**Comment by evanw** [comment]
Yes? You can use `--loader:.tsx=text`. Docs are here: https://esbuild.github.io/api/#loader.

**Comment by evanw** [comment]
You can use an `onLoad` plugin for ultimate flexibility: https://esbuild.github.io/plugins/#on-load. Or you could potentially add an additional suffix like `.text.tsx` and then use `--loader:.text.tsx=text`.

**Comment by anubra266** [comment]
I don't fully understand how the first can be used conditionally, but for the second, won't I have to rename all my `.tsx` files to `.text.tsx`?

**Comment by evanw** [comment]
> I don't fully understand how the first can be used conditionally

Plugins are code you write, so you can write a conditional branch in your plugin to change behavior in certain cases.

> won't I have to rename all my `.tsx` files to `.text.tsx`?

If you want all `.tsx` files to be loaded as text then just use `--loader:.tsx=text`. If you want file `a.tsx` to be loaded as TSX and file `b.tsx` to be loaded as text (but didn't want to use plugins for some reason), you could use `--loader:.text.tsx=text` and rename `b.tsx` to `b.text.tsx`.
