### ISSUE TITLE
Parsing errors when dealing with TypeScript Generics in a type parameter.

### ISSUE THREAD

**Issue by TylorS** [evanw/esbuild#2306]
Hello there! 

I'm running into an edge case that seems to be regarding the way esbuild is parsing TypeScript syntax. Here's the real example I was attempting to utilize.

## The Code in Question
<img width="615" alt="Screen Shot 2022-06-07 at 10 40 31 AM" src="https://user-images.githubusercontent.com/6282473/172410856-37626343-7741-4a82-aa64-ac4fc63ea9cd.png">

## The conditions required to trip on this error
The error seems to arise under 2 specific conditions. 1.) The function being called must be an accessed method call on a Namespaced Import or Object/Class in the form of `Foo.bar()` and 2.) The first type parameter provided to that method must also have its own generics defined for it.

<img width="621" alt="Screen Shot 2022-06-07 at 10 40 43 AM" src="https://user-images.githubusercontent.com/6282473/172411618-40751da1-b440-4ed6-ae0c-89e5dfe3be6f.png">

## The Error
<img width="536" alt="Screen Shot 2022-06-07 at 10 55 59 AM" src="https://user-images.githubusercontent.com/6282473/172412531-da60107c-a813-4a2c-aa36-8a17fc885250.png">

## The Workaround
Changing the code to the following will allow things to continue working, which I've gone ahead to use as a workaround for this issue.
<img width="461" alt="Screen Shot 2022-06-07 at 10 52 32 AM" src="https://user-images.githubusercontent.com/6282473/172411713-4e8a6541-f7c8-424f-bf5e-40f68573d1ea.png">

## The Reproduction case

I've tried to boil this down to a smaller reproduction case, and this appears to trip up the same exact error.

```ts
export declare const Test: {
  readonly service: <F>() => <T extends string>(tag: T) => { service: F; tag: T }
}

export const Foo = Test.service<<A>() => A>()('Foo')
```

**Comment by evanw** [comment]
Thanks for the report. I haven't investigated yet but I bet it's due to the `<<` token, which needs to sometimes be interpreted as two `<` tokens instead. Here's a quick workaround that's simpler if you'd like to use it instead:

```diff
 export declare const Test: {
   readonly service: <F>() => <T extends string>(tag: T) => { service: F; tag: T }
 }
 
-export const Foo = Test.service<<A>() => A>()('Foo')
+export const Foo = Test.service</**/<A>() => A>()('Foo')
```

**Comment by mnassabain** [comment]
Recently had a similar problem. Rewriting my functions with the "function" syntax instead of the arrow syntax solved the problem for me.
