### ISSUE TITLE
Deduplicate imports in bundle output

### ISSUE THREAD

**Issue by polRk** [evanw/esbuild#2309]
I see in my bundle 3 equal imports
```
var p = require('ydb-sdk')
...
var g = require('ydb-sdk')
var e = require('ydb-sdk')
```
Is it good?

**Comment by evanw** [comment]
This is a known issue. This is a minor issue in that it increases the size of the output slightly but does not impact correctness since calling `require()` multiple times just returns the same object (well, unless you mess with node's internals, but esbuild doesn't generate code which does that).

**Comment by polRk** [comment]
@evanw Thank for your answer!
