### ISSUE TITLE
Support package self-referencing using its name

### ISSUE THREAD

**Issue by PaperStrike** [evanw/esbuild#2312]
Node.js allows one to self-reference the package by the package's name:
https://nodejs.org/api/packages.html#self-referencing-a-package-using-its-name

This is helpful for writing tests that reference the package instead of directly to the files, by that we can avoid import paths like `../../../src/xxx`, and test if the `exports` field is in the correct format to be consumed.

Thank you!

**Comment by evanw** [comment]
I was wondering if/when someone was going to ask for this. You are the first! I can look into it.
