### ISSUE TITLE
target node14.6.0 emits unsupported code

### ISSUE THREAD

**Issue by Shinigami92** [evanw/esbuild#2315]
https://github.com/faker-js/faker/pull/1052

We set out target to `['es2020', 'node14.6.0']` as node v14.6 is the lowest version we want to support based on https://kangax.github.io/compat-table/es2016plus/#node14_6

In the issue you can see that everything below node 14.13 is failing in the build step
(I assume) related to that, we got multiple issue reports about that Webpack and Cypress now fails when using FakerJS

---

This can be somewhat also be relevant for Vite and other Vue/Vite ecosystem packages 👀

**Comment by hyrious** [comment]
I believe this is because node's support for **simulating esm named exports** [was just added in node14.13](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V14.md#14.13.0), which causes your `@esbuild-kit/esm-loader` failed to work. To make it clear, I'll take the following code for example:

```js
// lib.js (commonjs)
exports.a = 42

// index.mjs (esm)
import { a } from "./lib.js" // only works in >= node14.13
```

Before 14.13 you could only do `import all from "./lib.js"; let { a } = all`.

**Comment by hyrious** [comment]
> Do I need to switch to `tsx` instead of using `esno`, because `esno` uses some "`with automated CJS/ESM mode and caching.`"?

Have you read its [source code](https://github.com/esbuild-kit/esno/blob/master/esno.js)? 🤣

> Or do I need to use `node` and transpile our `bunlde.ts` to `bundle.js` before I run `node ./scripts/bundle.js`?

This is exactly a workaround to pass your CI check! If all your need is that, go for it.

**Comment by Shinigami92** [comment]
Uhm... I now compared the dist from main branch and the dist from the PR (that now uses plain node and normal js, not ts or anything like that) ... and the result is the exact same :eyes: 

So I'm not sure if this was the issue :thinking: 
IMO it's sadly not solved yet

**Comment by Shinigami92** [comment]
The funny thing is, that if I switch target to node12, it definitely emit at least one file differently

![image](https://user-images.githubusercontent.com/7195563/173636145-6a014f8b-054d-4ffb-a1ce-351b4a59afad.png)

Seems like to transform some nullish coalescing or so :thinking: 

So could it be that prior to node v14.13 something needs to be adjusted here? I'm not sure how esbuild maps which feature is allowed for which target.
