### ISSUE TITLE
Customizable chunk splitting behavior

### ISSUE THREAD

**Issue by fabiospampinato** [evanw/esbuild#2317]
WebPack has some options for customizing how chunks will be generated (https://webpack.js.org/plugins/split-chunks-plugin/#optimizationsplitchunks) and I think it'd be useful to port (some?) of them over.

In particular I miss the "minSize" option, which tells the bundler to not make chunks below the set size threshold basically. That's pretty useful because for example for my use case I'd rather always pay 0.5kb of bundle size for something rather than pay a network request for it in the future.

**Comment by petterek** [comment]
👍 
Maybe being able to mark an import as 'do not do code splitting on this'.  
Could use a comment, but sounds kinda funky.. 

`import { LitElement, html, nothing } from "lit";
import { customElement, property } from 'lit/decorators.js';

import {ViewModel } from './ViewModel'; //no-code-split
import { ActiveKeysFromIndexTypeRESTApi } from './PanelDataFromRESTApi'; //no-code-split
`
or something like that..

**Comment by petterek** [comment]
Another idea.. 
Set a threshold to the number of times a file needs to be referred before splitting it out.. 

```
splitting: true, 2
```

**Comment by joker-777** [comment]
I really would like to support this idea. We just tried out esbuild by replacing webpack in our project with esbuild. The build time is way faster but the loading time of the website is a lot slower because it has to load 60 different js files instas of 20 with webpack.

**Comment by dzearing** [comment]
Dupe of https://github.com/evanw/esbuild/issues/1128

**Comment by fabiospampinato** [comment]
Closing in favor of #1128
