### ISSUE TITLE
JSX transform: add the debug source information

### ISSUE THREAD

**Issue by kirillrogovoy** [evanw/esbuild#2318]
Most other compilers, namely Typescript and Babel, support a "dev" mode when the compiled code would include the 5th argument of the `react/jsx-dev-runtime` function call which provides the data on the original source file.

```diff
return jsx(
  'div',
  {
    children: [
      jsx(
        'h1',
        { children: 'Hello, world!' },
        void 0,
        false,
+       { fileName: _jsxFileName, lineNumber: 14, columnNumber: 5 },
        this,
      ),
      'text text',
    ],
  },
  void 0,
  true,
+ { fileName: _jsxFileName, lineNumber: 13, columnNumber: 9 },
  this,
)
```

Reference:
- https://github.com/reactjs/rfcs/blob/createlement-rfc/text/0000-create-element-changes.md#dev-only-transforms= for more details
- https://babeljs.io/docs/en/babel-plugin-transform-react-jsx-source

Some tools, such as [impulse](https://github.com/kirillrogovoy/impulse), leverage that data in dev runtime.

Once there's support for the new runtime API, it should be trivial to implement.

I'm ready to contribute, but I need help with higher-level design decisions.

Related to https://github.com/evanw/esbuild/issues/334

**Comment by alexgorbatchev** [comment]
Also, https://github.com/ericclemmons/click-to-component relies on this, which is an amazing tool for large multi-team projects.
