### ISSUE TITLE
CLI does not recognize --sourcefile=

### ISSUE THREAD

**Issue by tv42** [evanw/esbuild#232]
Using esbuild v0.5.23

```
$ esbuild --help
...
  --sourcefile=...          Set the source file for the source map (for stdin)
...
$ touch bar.js
$ esbuild --sourcefile=foo bar.js
error: Invalid build flag: "--sourcefile=foo"
1 error
```

**Comment by evanw** [comment]
The `--sourcefile` flag is only for stdin, since stdin doesn't have a file name. It doesn't apply to files that already have a file name. It will apply if you pass the file over stdin instead:

```
esbuild --sourcefile=foo < bar.js
```

**Comment by tv42** [comment]
In that case, let's make this issue a request for a better error message? My take is that it's not an "invalid build flag", but what might be true is "flag --sourcefile= is pointless when processing named files".
