### ISSUE TITLE
No matching export in "browser-external:fs" for import "existsSync"

### ISSUE THREAD

**Issue by softboy99** [evanw/esbuild#2325]
[vite] error while updating dependencies:
Error: Build failed with 17 errors:
node_modules/.pnpm/local-pkg@0.4.1/node_modules/local-pkg/dist/shared.mjs:54:9: ERROR: No matching export in "browser-external:fs" for import "existsSync"
node_modules/.pnpm/local-pkg@0.4.1/node_modules/local-pkg/dist/shared.mjs:54:21: ERROR: No matching export in "browser-external:fs" for import "promises"
node_modules/.pnpm/local-pkg@0.4.1/node_modules/local-pkg/dist/shared.mjs:62:13: ERROR: No matching export in "browser-external:node:fs" for import "promises"
node_modules/.pnpm/local-pkg@0.4.1/node_modules/local-pkg/dist/shared.mjs:235:14: ERROR: No matching export in "browser-external:node:fs" for import "promises"
node_modules/.pnpm/local-pkg@0.4.1/node_modules/local-pkg/index.mjs:1:9: ERROR: No matching export in "browser-external:path" for import "join"
...
    at failureErrorWithLog (D:\Software\Develop\Vue\iLabClient3\node_modules\.pnpm\esbuild@0.14.45\node_modules\esbuild\lib\main.js:1612:15)
    at D:\Software\Develop\Vue\iLabClient3\node_modules\.pnpm\esbuild@0.14.45\node_modules\esbuild\lib\main.js:1258:28
    at runOnEndCallbacks (D:\Software\Develop\Vue\iLabClient3\node_modules\.pnpm\esbuild@0.14.45\node_modules\esbuild\lib\main.js:1043:63)
    at buildResponseToResult (D:\Software\Develop\Vue\iLabClient3\node_modules\.pnpm\esbuild@0.14.45\node_modules\esbuild\lib\main.js:1256:7)
    at D:\Software\Develop\Vue\iLabClient3\node_modules\.pnpm\esbuild@0.14.45\node_modules\esbuild\lib\main.js:1365:14
    at D:\Software\Develop\Vue\iLabClient3\node_modules\.pnpm\esbuild@0.14.45\node_modules\esbuild\lib\main.js:675:9
    at handleIncomingPacket (D:\Software\Develop\Vue\iLabClient3\node_modules\.pnpm\esbuild@0.14.45\node_modules\esbuild\lib\main.js:772:9)
    at Socket.readFromStdout (D:\Software\Develop\Vue\iLabClient3\node_modules\.pnpm\esbuild@0.14.45\node_modules\esbuild\lib\main.js:641:7)
    at Socket.emit (node:events:527:28)
    at addChunk (node:internal/streams/readable:315:12)

**Comment by hyrious** [comment]
FYI, the `browser-external:` is generated by vite via plugins:
https://github.com/vitejs/vite/blob/a32c4bad5fd937874dc721fbcfb96ba1d4de4122/packages/vite/src/node/optimizer/esbuildDepPlugin.ts#L224-L225
where vite is wrapping node modules as empty objects/proxies to prevent it being bundled in browser context. You can see that it uses commonjs style `module.exports` to prevent esbuild from checking named exports.

But the error looks like some plugin/config is generating esm code that causes the error message, here's a [minimal example](https://hyrious.me/esbuild-repl/?version=0.14.45&mode=build&modules=%5B%5B%22main.js%22%2C%22import+%7B+existsSync+%7D+from+%5C%22.%2Ffs%5C%22%22%2C1%5D%2C%5B%22fs.js%22%2C%22export+%7B%7D%22%2C0%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22splitting%22%3Atrue%7D) to trigger that:

```js
// main.js
import { existsSync } from "./fs"

// fs.js
export {}
```

No matter how this issue could happen, you're still not supposed to use node-only packages ([local-pkg](https://www.npmjs.com/package/local-pkg)) in the browser. Vite and esbuild are not designed to support that.

**Comment by evanw** [comment]
This sounds like a bug in something else other than esbuild, so I'm going to close this issue. Refusing to compile code with a mismatched export is an important part of the JavaScript specification and won't be changed. If you want to be able to compile code like this anyway, you can do something like this instead:

```js
import * as fs from "browser-external:fs"
let { existsSync } = fs
```

That turns a compile error into a run-time error, which will still fail at run-time but only if `existsSync` is actually called.
