### ISSUE TITLE
esbuild-wasm seems to create mutliple React instances in final bundle text

### ISSUE THREAD

**Issue by AyloSrd** [evanw/esbuild#2327]
Hello! I am using`esbuild-wasm` to compile and bundle React code directly in the browser, and inject it in an `iframe` (the project is an online React REPL). 
React and third party libraries are imported dynamically using **UNPKG**. 
The other files (e.g. App.jsx) are dynamically generated and imported from a virtual file system.

While `esbuild` is working fine and it's very fast, I believe it creates several instances of React in the final bundle, causing some libraries to fail working, because of [this problem](https://reactjs.org/warnings/invalid-hook-call-warning.html) (Invalid Hook Call Warning). 
In the final bundle I have, in fact, a `require_react` a `require_react_production_min` and an `import_react` variable.
This is how I generate the bundle :
```jsx
const bundle = await esbuildRef.current.build({
    bundle: true,
    define: {
        'process.env.NODE_ENV': '"production"',
        global: 'window',
    },
    entryPoints: [ENTRY_POINT_JSX],
    format: 'esm',
    plugins: [myPlugin(virtualFileSystem)],
    write: false,
})
```
Is it bug, am I doing something wrong, or is it normal `esbuild-wasm` behaviour ? 
If so, is there any workaround to that for having a unique React instance in the bundle?
Thx in advance

**Comment by evanw** [comment]
I assume the problem is with `myPlugin`. What does that look like? Is there any way you can provide a self-contained demonstration of the problem?

**Comment by evanw** [comment]
I can't reproduce this. I had to modify your code slightly to get it to run, since the code you posted is not self-contained. Here's what I ran:

<details>

```js
const myPlugin = (vfs) => {
  return {
    name: 'unpkg-path-plugin',
    setup(build) {
      const fileCache = new Map

      build.onResolve({ filter: /.*/ }, async (args) => {

        if (args.path === ENTRY_POINT_JSX) {
          return { path: args.path, namespace: 'a' }
        }

        if (args.path.startsWith('./') && vfs[args.path.substring(2)]) {
          return {
            namespace: 'a',
            path: args.path.substring(2)
          }
        }

        if (args.path.startsWith('./') && vfs[`${args.path.substring(2)}.js`]) {
          return {
            namespace: 'a',
            path: `${args.path.substring(2)}.js`
          }
        }

        if (args.path.includes('./') || args.path.includes('../')) {
          return {
            namespace: 'a',
            path: new URL(
              args.path,
              'https://unpkg.com' + args.resolveDir + '/'
            ).href,
          }
        }

        return {
          namespace: 'a',
          path: `https://unpkg.com/${args.path}`,
        }
      })

      build.onLoad({ filter: /.*/ }, async (args) => {
        if (args.path === ENTRY_POINT_JSX) {
          return {
            loader: 'jsx',
            contents: vfs[ENTRY_POINT_JSX],
          }
        }

        if (vfs[args.path]) {
          return {
            loader: 'jsx',
            contents: vfs[args.path],
          }
        }

        const cached = await fileCache.get(args.path)

        if (cached) {
          return cached
        }

        const { data, request } = await require('axios').get(args.path)

        const result = {
          loader: 'jsx',
          contents: data,
          resolveDir: new URL('./', request.res.responseUrl).pathname,
        }

        await fileCache.set(args.path, result)

        return result
      })
    },
  }
}

const virtualFileSystem = {
  'App.js': `import HelloWorld from './HelloWorld'
import React from 'react'
import { createRoot } from 'react-dom/client'

function App() {
	return <HelloWorld />
}

const container = document.getElementById('root')
const root = createRoot(container)
root.render(<App />)`,
  'HelloWorld.js': `import React from 'react'

export default function HelloWorld() {
	return <p>Yo</p>
}`
}

const ENTRY_POINT_JSX = 'App.js'

require('esbuild-wasm').build({
  bundle: true,
  define: {
    'process.env.NODE_ENV': '"production"',
    global: 'window',
  },
  entryPoints: [ENTRY_POINT_JSX],
  format: 'esm',
  plugins: [myPlugin(virtualFileSystem)],
  outfile: 'out.js',
})
```

</details>

The generated code seems to work fine. I only see one copy of React. What makes you think there is more than one copy?

> In the final bundle I have, in fact, a `require_react` a `require_react_production_min` and an `import_react` variable.

That's totally normal:

```js
// a:https://unpkg.com/react@18.2.0/cjs/react.production.min.js
var require_react_production_min = __commonJS({
  "a:https://unpkg.com/react@18.2.0/cjs/react.production.min.js"(exports) {
    "use strict";
    ...
  }
});

// a:https://unpkg.com/react
var require_react = __commonJS({
  "a:https://unpkg.com/react"(exports, module) {
    "use strict";
    module.exports = require_react_production_min();
  }
});

// a:HelloWorld.js
var import_react = __toESM(require_react());
```

This is what having one copy of React looks like.

**Comment by AyloSrd** [comment]
> the code you posted is not self-contained.

I am sorry, I am not a native speaker I don't know what self-contined means.: I should have checked, my bad. 
Thanks for having taken the time to make it work out though.

> What makes you think there is more than one copy?

I mean, yes there is just one copy of the React code, but there are multiple instances of React. 
```js
// a:https://unpkg.com/react-dom@18.2.0/cjs/react-dom.production.min.js
var require_react_dom_production_min = __commonJS({
  "a:https://unpkg.com/react-dom@18.2.0/cjs/react-dom.production.min.js"(exports) {
    "use strict";
    var aa = require_react(); // <== first instance

// a:HelloWorld.js
var import_react = __toESM(require_react()); // <== second instance
return /* @__PURE__ */ import_react.default.createElement("p", null, "Yo");
...

// a:App.js
var import_react2 = __toESM(require_react()); // <== third instance
...
return /* @__PURE__ */ import_react2.default.createElement(HelloWorld, null);
```
`require_react()` is called 3 times here, creating 3 instances (`aa`, `import_react` and `import_react2`), and each of the instances it is used in different parts of the bundle, so that each instance will refer only to a part of the bundle.  `aa` will be responsible for ReactDOM,  `import_react` for `<HelloWorld />` , and  `import_react2` for `<App /> `.
This causes some libreries to fail working. When I console.log `React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner.current` from inside a component I should be getting the current fiber referring to that specific component; but since the React instance logged is not the same that has generated the current fiber (probably is the ReactDOM one), I always get `null` logged.

I believe that `require_react()` shoud be called just once in the bundle to create one instance of React used everywhere in the bundle. Something like this : 
```js
// a:https://unpkg.com/react-dom@18.2.0/cjs/react-dom.production.min.js
var require_react_dom_production_min = __commonJS({
  "a:https://unpkg.com/react-dom@18.2.0/cjs/react-dom.production.min.js"(exports) {
    "use strict";
    var global_react = require_react(); // <== here we declare global react

// a:HelloWorld.js
return /* @__PURE__ */ global_react.default.createElement("p", null, "Yo");
...

// a:App.js
...
return /* @__PURE__ */ global_react.default.createElement(HelloWorld, null);
```
I don't know if I what I am saying is clear.
Why for instance  there is a `import_react`  in `HelloWorld.js`  and `import_react2` in `App.js` ? 
Shouldn't  it be the first `import_react` to be reused in both components?

**Comment by evanw** [comment]
The way `require()` works in node (and therefore in esbuild) is that if you call it multiple times, it just returns the same result as before. So there shouldn't be multiple instances.

To implement this in esbuild, the function returned by `__commonJS` stores its result after the first call and just returns the stored result when called again. The function is optimized for size, so it's unfortunately hard to read as-is:

```js
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
```

If you were to rewrite it for readability, it would look like this:

```js
var __commonJS = (callback) => {
  var module;

  return () => {
    if (!module) {
      var fileNameForDebugger = Object.getOwnPropertyNames(callback)[0];
      module = { exports: {} };
      callback[fileNameForDebugger](module.exports, module);
    }

    return module.exports;
  }
};
```

As you can see, the returned function always returns the same value after the first call.

Anyway, I can't reproduce the problem you're describing. Here's what I tried:

```
$ npm init -y
$ npm i react react-dom esbuild

$ cat index.jsx 
import React from 'react'
import { createRoot } from 'react-dom/client'
import A from './a.jsx'
import B from './b.jsx'
createRoot(document.getElementById('root')).render(<><A/><B/></>)

$ cat a.jsx 
import React from 'react'
export default () => {
  var current = React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner.current
  return <div>A{JSON.stringify(current && Object.keys(current))}</div>
}

$ cat b.jsx 
import React from 'react'
export default () => {
  var current = React.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner.current
  return <div>B{JSON.stringify(current && Object.keys(current))}</div>
}

$ cat index.html 
<!DOCTYPE html>
<body>
  <div id="root"></div>
  <script src="out.js"></script>
</body>

$ node_modules/esbuild-wasm/bin/esbuild --bundle index.jsx --outfile=out.js
```

The output in the browser looks like this, so the values aren't null:

```
A["tag","key","elementType","type","stateNode","return","child","sibling","index","ref","pendingProps","memoizedProps","updateQueue","memoizedState","dependencies","mode","flags","subtreeFlags","deletions","lanes","childLanes","alternate","actualDuration","actualStartTime","selfBaseDuration","treeBaseDuration","_debugSource","_debugOwner","_debugNeedsRemount","_debugHookTypes"]
B["tag","key","elementType","type","stateNode","return","child","sibling","index","ref","pendingProps","memoizedProps","updateQueue","memoizedState","dependencies","mode","flags","subtreeFlags","deletions","lanes","childLanes","alternate","actualDuration","actualStartTime","selfBaseDuration","treeBaseDuration","_debugSource","_debugOwner","_debugNeedsRemount","_debugHookTypes"]
```

despite the source code having the pattern you are describing:

```js
// index.jsx
var import_react3 = __toESM(require_react());
var import_client = __toESM(require_client());

// a.jsx
var import_react = __toESM(require_react());
var a_default = () => {
  var current = import_react.default.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner.current;
  return /* @__PURE__ */ import_react.default.createElement("div", null, "A", JSON.stringify(current && Object.keys(current)));
};

// b.jsx
var import_react2 = __toESM(require_react());
var b_default = () => {
  var current = import_react2.default.__SECRET_INTERNALS_DO_NOT_USE_OR_YOU_WILL_BE_FIRED.ReactCurrentOwner.current;
  return /* @__PURE__ */ import_react2.default.createElement("div", null, "B", JSON.stringify(current && Object.keys(current)));
};
```

**Comment by AyloSrd** [comment]
> To implement this in esbuild, the function returned by __commonJS stores its result after the first call and just returns the stored result when called again.

Oh I see! That makes sense. As you said then, there's just one instance of React.

> The output in the browser looks like this, so the values aren't null:

I tried the same code, to me the result is :
```
Anull
Bnull
```
There must be something else causing it, I'll investigate further.

Since the problem doesn't seem to come from `esbuild-wasm`, I'll close this issue.
I appreciate very much you taking the time to test it out and reply in depth and in perfect clarity, to all of my questions.
Thx a lot!
