### ISSUE TITLE
How should I import the ts file so that it can be actually read(.ts)

### ISSUE THREAD

**Issue by songwuk** [evanw/esbuild#2332]
hi
example：
` 

      setup(build){

         const filter = /\.ts$/;

          build.onResolve({ filter }, async (resolve) => {

                 return {

                    path: resolve.path,

                    namespace: 'ts',

                  }
          })
      }
`

How do I recognize the ts file in onResolve 
🙏🙏🙏🙏🙏

**Comment by evanw** [comment]
Sorry but I have no idea what you’re asking.

**Comment by songwuk** [comment]
> Sorry but I have no idea what you’re asking.

Sorry , I didn't express clearly.
I can omit the suffix of the import path in typescript by configuring the `tsconfig.json` file, 
but I can't detect the correct import path in the `onResolve` API in esbuild, I don't know if I do it effectively

**Comment by hyrious** [comment]
I guess you're misunderstanding the usage of plugin api? Let me give you an overview of it:

```js
`import "./path"` -->
  resolve("./path") => "/path/to/path.ts" (absolute path) -->
  load("/path/to/path.ts") => "source code" -->
(now esbuild bundles all source code)
```

Each source file in esbuild will be loaded in 2 phases as above -- `resolve` and `load`. You can use plugins to **replace** the default behavior in esbuild by `onResolve` and `onLoad` callbacks.

- `resolve`: find absolute path to some file as specified in the source code, like `./file` -> `/path/to/file.ts`.

- `load`: read file content from absolute path, you can think of it as `fs.readFile`.

**Comment by songwuk** [comment]
ok I understand, thanks for your reply

**Comment by evanw** [comment]
I'm still not sure what you're asking for but from the above response it sounds like your question was answered, so I'm going to close this issue.

In case you're asking how to know if an import needs to add `.ts` at the end or not: It's your code so you can write that check however you want. For example, you can check the file system for both without `.ts` and with `.ts` and go with whichever exists on the file system. Or you can use node's `require.resolve()` algorithm via [the `resolve` package](https://www.npmjs.com/package/resolve) and then put `.ts` in the `extensions` option.
