### ISSUE TITLE
Tree-shaking broken. Erroneous `[ignored-bare-import]` warning. `import type` statements possible culprit.

### ISSUE THREAD

**Issue by mikestopcontinues** [evanw/esbuild#2334]
I'm using esbuild in a monorepo to bundle a library, then rebundle it in a second package (specifically, a serverless func). However, I'm getting a series of errors that completely breaks tree-shaking, resulting in a 5MB bundle instead of about 300kb.

The problem seems to be that during the initial bundling process, many of the imports are tree-shaken, but the bare import statements remain:

```ts
import './chunk-TFQ3YM4A.mjs';
import './chunk-7TSMCAJT.mjs';
import './chunk-7W62PHEE.mjs';
```

Those files shouldn't be included at all. The package is marked `"sideEffects": false`. For reference, I'm not directly importing these files into this entry point. They're within an `import type {}` statement. The types get dropped, but the web of imports remain. (This seems to be a known issue. #1794 #1435).

Some of the apps in this monorepo still use webpack, which shakes away those useless imports just fine. The problem arises when using `esbuild` to bundle a package that depends on the library with the bunk imports.

When I do that, I get this warning, 44 times:

```
▲ [WARNING] Ignoring this import because "libs/arc-model/dist/chunk-TFQ3YM4A.mjs" was marked as having no side effects [ignored-bare-import]

    libs/arc-model/dist/index.mjs:1:2430:
      1 │ ...rt{a as wo}from"./chunk-IOOPTIQW.mjs";import"./chunk-TFQ3YM4A.mjs";import"./chunk-7TSMCAJT.mjs";import"./chun...
        ╵                                                ~~~~~~~~~~~~~~~~~~~~~~

  "sideEffects" is false in the enclosing "package.json" file

    libs/arc-model/package.json:4:2:
      4 │   "sideEffects": false,
        ╵   ~~~~~~~~~~~~~
```

Is there workaround for handling this issue? For this particular use-case, the size difference has a big impact on performance.

Thanks.

**Comment by evanw** [comment]
I have read your post several times but I can't figure out what your problem is exactly. Can you provide a code example that demonstrates the problem?

If `"sideEffects": false` is authored incorrectly and the incorrect annotation can't be changed, you can [disable annotations](https://esbuild.github.io/api/#ignore-annotations) to pretend the `"sideEffects": false` isn't there. Or if the warning is correct but you would like to not see the warning, you can disable it with `--log-override:ignored-bare-import=silent`.

**Comment by mikestopcontinues** [comment]
Closing the issue for now. I was able to prevent the library bundle from sprouting those bare imports. Tree shaking in the app is still not working, but it may be due to args passed in by the AWS CDK.
