### ISSUE TITLE
Android ARM binaries

### ISSUE THREAD

**Issue by ravener** [evanw/esbuild#2335]
issue #803 included support for android arm64 builds. I'd like to suggest arm 32-bits as well.

I can build esbuild from source no problems and this is not a big deal for me but for completeness sake I believe ARM should be supported too.

**Comment by evanw** [comment]
_Cross-posting from https://github.com/evanw/esbuild/pull/1578#issuecomment-1019021979_

I'm closing this as I don't want to complicate esbuild's deploy process by having to install the entire Android build toolchain for this one platform. All of the other 18 platforms I already support can be built fine by Go on any platform without installing anything. I still don't understand why Go doesn't support cross-platform builds for this platform in particular (Go and Android are even both Google projects!) but that's up to them I guess. If you want to run esbuild on 32-bit Android ARM, you'll have to build it yourself. Sorry.

**Comment by ravener** [comment]
@evanw it seems like go enforces CGO_ENABLED for android and the generated binaries are dynamically linked, pointing to /system/bin/linker(64) instead of statically linked.

to be fair since the linux binaries are statically linked they do run fine on Android it's just that platform resolves to 'android' rather than 'linux' so another option would also be to just alias those and publish the linux binaries as android, it would atleast suffice for use in Termux.

otherwise, completely understandable, I respect your decision and I'm completely fine with building from source.

**Comment by HUGEORGAniSM** [comment]
> @evanw it seems like go enforces CGO_ENABLED for android and the generated binaries are dynamically linked, pointing to /system/bin/linker(64) instead of statically linked.
> 
> to be fair since the linux binaries are statically linked they do run fine on Android it's just that platform resolves to 'android' rather than 'linux' so another option would also be to just alias those and publish the linux binaries as android, it would atleast suffice for use in Termux.
> 
> otherwise, completely understandable, I respect your decision and I'm completely fine with building from source.

This would be really nice, as installing esbuild (or tools that depend on it, like Vite!!) in Termux on ARMv7 (32-bit Android) is impossible unless building it from source, which I have not tried yet.. and in the case of Vite, it appears to install (for example, pnpm add -g vite) fine but then fails in postinstall due to unsupported architecture.

**Comment by Freed-Wu** [comment]
Android termux has supported esbuild https://github.com/termux/termux-packages/issues/11873

Can we:

1. If user doesn't have esbuild in Android termux, when they `npm install esbuild`, give a warning and let them `pkg install esbuild`
2. If user has esbuild in Android termux, use it and give an information about it, not give an error

**Comment by ravener** [comment]
> Android termux has supported esbuild [termux/termux-packages#11873](https://github.com/termux/termux-packages/issues/11873)
> 
> Can we:
> 
>     1. If user doesn't have esbuild in Android termux, when they `npm install esbuild`, give a warning and let them `pkg install esbuild`
> 
>     2. If user has esbuild in Android termux, use it and give an information about it, not give an error

Unfortunately, that wouldn't be simple, the npm package was made for that reason to make it OS-independent so it can't make use of your package manager, and your package manager (at least how Termux packages them) can't guarantee a specific version either like the npm package could.

**Comment by Freed-Wu** [comment]
At least we can ignore the error to ensure esbuild node package can be installed. Then user can `ln -s $(which esbuild) node_modules/.bin` to use it. For a specific version, user should ensure it by themselves, if them meet any problem because they use system's esbuild not npm's, they should take the duty by themselves.

**Comment by Amarknmar** [comment]
Eshv_'chin
