### ISSUE TITLE
deno-esbuild: Deno Deploy support

### ISSUE THREAD

**Issue by ayoreis** [evanw/esbuild#2336]
[Deno Deploy](https://deno.com/deploy) is an edge runtime by Deno. And it would be awesome to use esbuild  with it, but when I try to run this code:

```typescript
import * as esbuild from "https://deno.land/x/esbuild@v0.14.45/mod.js";
const ts = 'let test: boolean = true'
const result = await esbuild.transform(ts, { loader: 'ts' })
console.log('result:', result)
esbuild.stop()
```

It gives me this error:
```
Error: Failed to find cache directory
    at getCachePath (https://deno.land/x/esbuild@v0.14.45/mod.js:1759:11)
    at installFromNPM (https://deno.land/x/esbuild@v0.14.45/mod.js:1713:35)
    at install (https://deno.land/x/esbuild@v0.14.45/mod.js:1802:18)
    at https://deno.land/x/esbuild@v0.14.45/mod.js:1813:29
    at ensureServiceIsRunning (https://deno.land/x/esbuild@v0.14.45/mod.js:1941:7)
    at Module.transform (https://deno.land/x/esbuild@v0.14.45/mod.js:1679:37)
    at file:///src/main.tsx:8:30
```

I don't get the error right now, but I can try to find the problem and then propose a fix.

**Comment by evanw** [comment]
You can read the source code here:

https://github.com/evanw/esbuild/blob/20f4b459c9de5473eb6bac712c98d0b010e9959c/lib/deno/mod.ts#L83-L117

This will fail on Linux if certain environment variables aren't set. I don't use Deno and know nothing about it so I can't help you, sorry.

**Comment by evanw** [comment]
BTW if you are ok with using WebAssembly instead of native, then you can try that when the next version of esbuild is released soon. See #2323 which was just fixed.

**Comment by evanw** [comment]
Marking as `unactionable` until more information is provided.

**Comment by ayoreis** [comment]
**Update:** So Deno Deploy does not support `Deno.writeFile` nor `Deno.run` (at least yet). That's what's causing the errors, the best option right now is using WebAssembly as you sugested, though its not enough for my use case where I need building.

So my proposal is that we make `build `available in the WebAssembly version and get files with `fetch(new URL('./path/to.file'))` / the user being required to write a plugin that would resolve all the files by itself.

This would allow building in Deno Deploy, and in the browser! You mentioned in #2323 that to get this working it would require additional work, so I am not expecting this to happen and just proposing it. Maybe I could even learn Go and do it myself.

And maybe esbuild switching automatically to WebAssembly in Deno Deploy, but I don't think that's necessary since you can just check for the existence of `Deno.run` and fallback to WebAssembly.

What do you think? Do I write a new issue for this?

**Comment by evanw** [comment]
I'm confused. The `build` API already works. Here's an example:

```js
import * as esbuild from 'https://deno.land/x/esbuild@v0.14.48/wasm.js'
const result = await esbuild.build({
  stdin: {
    contents: `
      import x from 'fib(10)'
      console.log('fib(10) is', x)
    `,
  },
  bundle: true,
  plugins: [{
    name: 'some-plugin',
    setup(build) {
      build.onResolve({ filter: /^fib\((\d+)\)/ }, args => {
        return { path: args.path, namespace: 'fib' }
      })
      build.onLoad({ filter: /^fib\((\d+)\)/, namespace: 'fib' }, args => {
        let match = /^fib\((\d+)\)/.exec(args.path), n = +match[1]
        let contents = n < 2 ? `export default ${n}` : `
          import n1 from 'fib(${n - 1}) ${args.path}'
          import n2 from 'fib(${n - 2}) ${args.path}'
          export default n1 + n2`
        return { contents }
      })
    },
  }],
})
eval(result.outputFiles[0].text)
Deno.exit(0)
```

That should print this:

```
fib(10) is 55
```

You'll need to use an esbuild plugin to avoid the file system if Deno Deploy doesn't have a file system, but there should be nothing preventing you from using esbuild in that case. I'm not planning on testing esbuild with Deno Deploy myself because it's a closed service so it'll be up to you to figure out how to write the plugin you need for this. I'm closing this issue since esbuild's current WebAssembly implementation should be sufficient for this.
