### ISSUE TITLE
The built-in hardcoded mime types does not handle webfont file extensions correctly

### ISSUE THREAD

**Issue by sean220** [evanw/esbuild#2337]
When using data-url loader to bundle webfont files in css，it failed to identify correct content-type.
**actually:**
`url(data:text/plain;charset=utf-8;base64,ZGF0YTpmb250L3dvZm...`
**expected:**
`url(data:font/woff;charset=utf-8;base64,ZGF0YTpmb250L3dvZm...`

After implementing my own onLoad plugin and returning the correct dataurl content, 
it will eventually be modified to the wrong mime type.

**Comment by evanw** [comment]
Hopefully the internal list should be easy to update. Do you just need `.woff` => `font/woff`? Anything else?

**Comment by evanw** [comment]
Ah, I see. If you specify `dataurl` in `onLoad`, you are telling esbuild "here is a string that should be encoded as a data URL." So it's being wrapped in a data URL twice. It doesn't mean "here is a string that is already encoded as a data URL." Here's the URL in your example:

```
 url(data:text/plain;charset=utf-8;base64,ZGF0YTpmb250L3dvZm...
```

That's actually just the base64 encoding of your input:

```
> atob('ZGF0YTpmb250L3dvZm')
"data:font/wof"
```

I'm not sure quite what the best way to handle this is from within a plugin off the top of my head. Maybe having the URL be marked as external and for the external text to be the data URL? That way esbuild will leave it alone. But the easiest solution is for esbuild to just do it for you once the MIME types are updated.

**Comment by sean220** [comment]
I understand, this defect is that I return the encoded content of dataurl in onLoad, which causes it to be recognized as text/plain in esbuild. After change to return rawdata,although not recognized by hardcoded mimetypes,but it is correctly handled by `http.DetectContentType([]byte(contents))`
But webfonts are common import type in css, adding built-in mimeTypes should improve some performance, thanks again.
