### ISSUE TITLE
Esbuild doesn't respect the order of import statement in multiple entries

### ISSUE THREAD

**Issue by iheyunfei** [evanw/esbuild#2340]
It's the same as https://github.com/rollup/rollup/issues/4539.

# input

![image](https://user-images.githubusercontent.com/49502170/175234650-ea960e71-f559-4477-9dd7-4bda11a4dcaf.png)

# output

![image](https://user-images.githubusercontent.com/49502170/175234485-9b573af0-7756-4b10-90b9-349a7d94a6ae.png)

### Expected Behaviour

If I run `otherEntry.js`, I expect the output of the console would be 
```
b
a
```

### Actual Behaviour

the output of the console is

```
a
b
```

**Comment by hyrious** [comment]
#399
