### ISSUE TITLE
Polyfill `Array.prototype.flat/flatMap` when target is `node10`

### ISSUE THREAD

**Issue by vanyauhalin** [evanw/esbuild#2341]
`Array.prototype.flat/flatMap` has been [added](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap#browser_compatibility) in NodeJS v11.0.0, but esbuild does not process these methods if the target is `node10`.

```js
// index.js
import { build } from 'esbuild';
await build({
  entryPoints: ['src.js'],
  outfile: 'dist.js',
  platform: 'node',
  target: 'node10'
});
```

```js
// src.js
console.log([].flat());
```

```js
// dist.js
console.log([].flat());
```

Not sure if there is a real need to add a [polyfill](https://github.com/jonathantneal/array-flat-polyfill), but maybe someone needs it.

**Comment by susiwen8** [comment]
https://esbuild.github.io/api/#target
<img width="1024" alt="Screen Shot 2022-06-23 at 5 37 27 PM" src="https://user-images.githubusercontent.com/20318608/175268412-38509b0d-c161-429b-b76c-f61ac88f5e47.png">

**Comment by vanyauhalin** [comment]
Oops, didn't notice. Thanks.
