### ISSUE TITLE
Inconsistent builds when running in parallel on same service

### ISSUE THREAD

**Issue by SamyPesse** [evanw/esbuild#235]
I'm running into a weird issue, and I'm still investigating the origin: I'm building a code base with multiple bundles, and use `esbuild` as a Node library to build all of them, but when building the bundles in parallel I'm getting inconsistent result:

- 💥  Running 7 builds in parallel using the same esbuild service => one of them is missing a defined variable (passed in `define`)
- ✅  Running the same builds in serie using the same esbuild service => all good
- ✅  Running the same builds in parallel using different esbuild service for each build => all good

I've investigated if it was coming from a mutation of options on my code, but it's not the case.
I've took a look at the implementation of the Node API, but couldn't find any code that is not "async safe".

To validate both, I've logged the [`length`](https://github.com/evanw/esbuild/blob/2b3bba042518b389dc7af18a1960c5a2791fc7cb/lib/api-common.ts#L169) being sent to the esbuild binary, and I'm getting consistent lengths (whatever the method being used).

From my current understanding it looks like an issue in the Go binary when receiving multiple commands. Is it a known limitation ?

I can reproduce the issue, but cannot really share the codebase as it's private.

**Comment by evanw** [comment]
Really sorry about that. I fixed a bug like this in version 0.5.22. What version are you using?

**Comment by SamyPesse** [comment]
Thanks @evanw I was using the 0.5.21, upgrading to 0.5.24 fixes the issue.
