### ISSUE TITLE
Cant read sourcemaps for created from tsc

### ISSUE THREAD

**Issue by stoivo** [evanw/esbuild#2351]
I use pnpm workspaces and one workspace uses tsc to compile the package. I tried to enable source maps in tsc and it did output source maps but it seems like esbuild has some problems picking up the source maps. It could be that I am using it wrong. 

I managed to work my way around it by switching the build process over to esbuild. Seam like esbuild likes to parse its source maps better.

To demonstrate my issue I created a repo https://github.com/stoivo/example-esbuild-missing-sourcemap-from-package. It contains a root project and two projects in workspaces. fbutil is built with tsc and fbutilesbuild es build with esbuild. I have written a bit more on my diagnoses in the readme.

The source map produced doesn't include sourcesContent for "../pkgs/fbutil/src/main.ts".
```json
{
  "version": 3,
  "sources": ["../pkgs/fbutil/src/main.ts", "../pkgs/fbutilesbuild/src/main.ts", "../src/main.ts"],
  "sourcesContent": [null, "export default function hello() {\n  console.log(`Asdasd`);\n}\n", "import print from \"fbutil/dist/main\"\nimport print2 from \"fbutilesbuild/dist/main\"\n\nexport default function lol(): void {\n  console.log(`I love you`);\n  print()\n  print2()\n}\n"],
  "mappings": ";;;AAAc,iBAAe;AAC3B,UAAQ,IAAI,QAAQ;AACtB;;;ACFe,kBAAiB;AAC9B,UAAQ,IAAI,QAAQ;AACtB;;;ACCe,eAAqB;AAClC,UAAQ,IAAI,YAAY;AACxB,QAAM;AACN,SAAO;AACT;",
  "names": []
}
````

So I managed to work my way around the issue by switching package build tool to esbuild. I would like if esbuild at least told me that it did not find the source

BTW love esbuild❤️

**Comment by stoivo** [comment]
I was preatty sure I tested it, but apparently not. Thanks that did the trick.

**Comment by stoivo** [comment]
More of an open question: should esbuild warn or error when the source code isn't included?

**Comment by evanw** [comment]
No, I don’t think so. That’s a perfectly valid use case. You may just want to map over stack traces for logging purposes in production, for example.

**Comment by stoivo** [comment]
ah, I didn't think of that. Thats what sourceContent is for.  It's even written why. https://esbuild.github.io/api/#sources-content
