### ISSUE TITLE
Should I call esbuilg.build in the plugin?

### ISSUE THREAD

**Issue by magiskboy** [evanw/esbuild#2352]
When I write a plugin for esbuild, I try to call `esbuild.build` when `onResolve` is fired. Is it a problem? So should I do this?

```typescript
const externalsPlugin: (options?: {
  builtPaths?: PathTree;
}) => esbuild.Plugin = ({ builtPaths } = {}) => {
  return {
    name: 'externals',
    setup(build) {
      const {
        entryPoints = [],
        external = [],
        outbase = '',
        outdir = '',
      } = build.initialOptions;

      if (!builtPaths) {
        builtPaths = new Map<string, PathTree>();

        (entryPoints as string[]).forEach((entryPoint) => {
          buildPathTree(path.relative(outbase, entryPoint), builtPaths);
        });
      }

      build.onResolve({ filter: /.*/ }, async (args) => {
        const isExternal = external.some((externalPrefix) =>
          args.path.startsWith(externalPrefix),
        );

        const isTs = !/\w+\.\w+$/.test(args.path);

        if (isTs && !isExternal) {
          const tsSuffixes = ['.ts', '.tsx', '/index.ts', '/index.tsx'];
          const absolutePath = path.resolve(args.resolveDir, args.path);

          const existIndex = (
            await Promise.allSettled(
              tsSuffixes.map((suffix) => fs.stat(`${absolutePath}${suffix}`)),
            )
          ).findIndex(({ status }) => status === 'fulfilled');

          if (existIndex >= 0) {
            const absolutePathWithExt = `${absolutePath}${tsSuffixes[existIndex]}`;

            const isBuilt = buildPathTree(
              path.relative(outbase, absolutePathWithExt),
              builtPaths,
            );

            if (!isBuilt) {
              await esbuild.build({
                ...build.initialOptions,
                entryPoints: [absolutePathWithExt],
                plugins: getEsbuildPlugins({
                  externalsPluginOptions: { builtPaths },
                  copyAssetsPluginOptions: { rootDir: outdir },
                }),
              });
            }
          }
        }

        return {
          external: isExternal || isTs,
        };
      });
    },
  };
};

esbuild.build({plugins: [externalsPlugin()]})
```

**Comment by evanw** [comment]
I'm guessing probably not, but you didn't describe why you are doing that so I don't know. There isn't any fundamental reason why you can't do this. Keep in mind that `onResolve` is run for every import in every file. So if the same import is imported several times, then you will end up rebuilding the same file several times and wasting effort if you do this. Also keep in mind that while esbuild should work fine with multiple parallel builds, any plugins you are using may not work fine when run in parallel for separate builds if they weren't written with that in mind.

**Comment by magiskboy** [comment]
I want to keep output structure same source structure (like `preserveModules` in rollup) so I have two options:
- build each source file. For this solution, I use `onResolve` as a visitor on the codebase graph. My concern it can conflict with other plugins.
- pass multiple entry points to build function (**prefered**)

**Comment by evanw** [comment]
You probably want to use `onLoad`, not `onResolve`. `onResolve` determines what file each import maps to, and is run once for every import in every file. `onLoad` determines what each file contains and is run once per file. So for example if A and B both import C, `onResolve` will be called for C twice (once for the import in A and once for the import in B) while `onLoad` will only be called once (for the contents of C).

**Comment by magiskboy** [comment]
I see, thanks @evanw
