### ISSUE TITLE
MainFields: `exports`

### ISSUE THREAD

**Issue by coderaiser** [evanw/esbuild#2355]
Would be great to have [`exports`](https://nodejs.org/api/packages.html#exports) field support, so modules like [support-color](https://github.com/chalk/supports-color/blob/v9.2.2/package.json#L14-L17) can be used with `platform: 'neutral'`.

I have such config:

```js
const esbuild = require('esbuild');
const alias = require('esbuild-plugin-alias');

esbuild.build({
    entryPoints: ['lib/putout.js'],
    bundle: true,
    outfile: 'out.mjs',
    platform: 'neutral',
    mainFields: [
        'main',
        'module',
        'browser',
        'exports'
    ],
    plugins: [
        alias({
            'path': require.resolve('path-browserify'),
            'tty': require.resolve('tty-browserify'),
        }),
    ],
     external: [
     'acorn',
     'espree',
     'esprima',
     'hermes-parser',
     'os',
     'assert',
     'fs',
     'supports-color',
     '@putout/engine-loader'
    ],
})
```

And such error:

```js
file:///Users/coderaiser/putout/packages/putout/out.mjs:8
  throw new Error('Dynamic require of "' + x + '" is not supported');
        ^

Error: Dynamic require of "supports-color" is not supported
    at file:///Users/coderaiser/putout/packages/putout/out.mjs:8:9
    at ../../node_modules/@babel/highlight/node_modules/chalk/index.js (file:///Users/coderaiser/putout/packages/putout/out.mjs:28580:23)
    at __require2 (file:///Users/coderaiser/putout/packages/putout/out.mjs:11:50)
    at ../../node_modules/@babel/highlight/lib/index.js (file:///Users/coderaiser/putout/packages/putout/out.mjs:28753:18)
    at __require2 (file:///Users/coderaiser/putout/packages/putout/out.mjs:11:50)
    at ../../node_modules/@babel/code-frame/lib/index.js (file:///Users/coderaiser/putout/packages/putout/out.mjs:28849:22)
    at __require2 (file:///Users/coderaiser/putout/packages/putout/out.mjs:11:50)
    at ../../node_modules/@babel/traverse/lib/path/replacement.js (file:///Users/coderaiser/putout/packages/putout/out.mjs:43041:22)
    at __require2 (file:///Users/coderaiser/putout/packages/putout/out.mjs:11:50)
    at ../../node_modules/@babel/traverse/lib/path/index.js (file:///Users/coderaiser/putout/packages/putout/out.mjs:46442:32)
```

When create a file `build.js` in 🐊[**Putout**](https://github.com/coderaiser/putout) repository in directory [`packages/putout`](https://github.com/coderaiser/putout/tree/master/packages/putout).

**Comment by evanw** [comment]
You are talking about esbuild's support for the `exports` field but that's irrelevant here because you have marked `support-color` as external, which means it isn't bundled (so esbuild doesn't even try to find out what file it corresponds to). The error `Dynamic require of "supports-color" is not supported` happens at run-time, not bundle-time, and just means that your code is trying to use `require` to load the `supports-color` package in an environment that doesn't have a `require` API available at run-time. You haven't provided any information about why you are using `neutral`, how you are running the code, or why you have excluded `supports-color` from the bundle in the first place, so it's unclear what you should be doing here instead.

**Comment by coderaiser** [comment]
Thank you for a quick response!

I want to make an **ESM** bundle of 🐊**Putout** for **Deno** and **Browsers**, the thing is some dependencies uses `process.env`, some of them uses `fs` or `os`. All of them not required for transformations.

Here is a bundle I made with **Rollup**: [`@putout/bundle`](https://github.com/putoutjs/bundle#putoutbundle-), I run it with:

```js
import putout from 'https://esm.sh/@putout/bundle';

putout('const a = 5');
// transform results
```

I don't quite understand how to make a similar thing with **ESBuild**. I would be glad for help, since **ESBuild** works much faster :)!

**Comment by hyrious** [comment]
I guess you're asking for an esbuild config acting as the same as [the rollup config](https://github.com/putoutjs/bundle/blob/master/rollup.config.mjs)? Most of them are not hard with a single option or some little plugins. Them main burden here is you have to replicate [`rollup-plugin-polyfill-node`](https://github.com/FredKSchott/rollup-plugin-polyfill-node) in esbuild. I did a quick search and found [one plugin](https://github.com/geut/brode/tree/main/packages/esbuild-plugin-brode) do the same work. So you could give it a try.

Note: set platform to `browser`.

**Comment by evanw** [comment]
Closing because esbuild already supports `exports`.
