### ISSUE TITLE
Esbuild imports of ./nested/file.ext fail in CI run (but work locally)?

### ISSUE THREAD

**Issue by webketje** [evanw/esbuild#2358]
###  Environment
- ESbuild version: 0.14.43-45
- OS: ubuntu-latest
- Distribution: esbuild-linux-64
- Node version: any supported
- Particularity: mocha unit testing (so `process.cwd() !== absWorkingDir`, and multiple esbuild runs are done in a single test file)
- Using the build API (not CLI)

### Description
Under certain conditions (CI), esbuild  imports to files that are not siblings of the importing file, fail

### Use case
Given all entry points and imports reside in the `src` folder, and following config: 

```js
{
  bundle: true,
  minify: true,
  sourcemap: false,
  platform: 'browser',
  target: 'es6',
  assetNames: '[dir]/[name]',
  drop: ['console', 'debugger'],
  loader: {
    '.png': 'dataurl',
    '.svg': 'text',
    '.jpg': 'file',
  },
  entryPoints: {
    index: './src/index.js'
  },
  absWorkingDir: '/home/user/repo/test/fixtures/in-source',
  outdir: 'build',
  write: false,
  metafile: true,
  outbase: 'home/user/repo/test/fixtures/in-source/src'
}
```

Using a JS file 
```js
import logo from './lib/logo-compact.png'
import svg from './lib/logo-compact.svg'
import { key } from './lib/data.json'
import style from './lib/style.css'
import square from './lib/square.jpg'
import test, { param } from './lib/imported'

test(param)

export {
  logo,
  svg,
  key,
  style,
  square
}
```
Locally the build works fine, but in CI all imports fail. 

```
index.js:1:17: ERROR: Could not resolve "./lib/logo-compact.png"
index.js:2:16: ERROR: Could not resolve "./lib/logo-compact.svg"
index.js:3:20: ERROR: Could not resolve "./lib/data.json"
index.js:4:18: ERROR: Could not resolve "./lib/style.css"
index.js:5:19: ERROR: Could not resolve "./lib/square.jpg"
index.js:5:19: ERROR: Could not resolve "./lib/imported"
```
Weirdly, "flattening" the imports (making them siblings of the importing file and importing './logo-compact.png' instead of './lib/logo-compact.png') works as expected. I've been unable to reproduce this issue on my local machine

**Comment by evanw** [comment]
Does setting the [log level](https://esbuild.github.io/api/#log-level) to `debug` or even `verbose` tell you anything more about the problem? 

Also: the errors you posted don’t look like how esbuild prints errors, so you may have some other tool filtering your error messages. You may want to look at esbuild’s original error messages instead of the filtered ones in case important information has been removed.

**Comment by webketje** [comment]
Thx, not sure what causes the reformatting of error messages but they are definitely ESbuild's.
So I re-ran the CI with debugLevel: verbose: and thanks to that noticed the issue that has nothing to do with ESbuild:
I specified "lib" in .gitignore without root slash, which made it ignore the "lib" folders under test :man_facepalming: 
Sorry for taking your time
