### ISSUE TITLE
Import scss / svg

### ISSUE THREAD

**Issue by munrocket** [evanw/esbuild#236]
FYI
```
import './index.css';
       ~~~~~~~~~~~~~
src/components/UploadsExtContainer/UploadsExtContainer.tsx:10:16: error: File extension not supported: src/components/UploadsExtContainer/UploadsExtContainer.module.scss
import stl from './UploadsExtContainer.module.scss';
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/components/UploadsExtContainer/UploadsExtContainer.tsx:6:22: error: File extension not supported: src/ui/icons/thinArrow.svg
import arrowIcon from '@/ui/icons/thinArrow.svg';
                      ~~~~~~~~~~~~~~~~~~~~~~~~~~
```
🚀

**Comment by evanw** [comment]
CSS support is tracked by #20. I believe it should be possible to use SCSS once that and #111 are implemented.

SVG may already work depending on what you need the bundler to do for you. For example, `--loader:.svg=text`. will cause `import arrowIcon from '@/ui/icons/thinArrow.svg'` to populate `arrowIcon` with the SVG file as a string.

**Comment by evanw** [comment]
Documentation for the plugin API has now been released: https://esbuild.github.io/plugins/. Closing this because you should be able to build these integrations yourself.
