### ISSUE TITLE
Add `platform` option to `transform` js api

### ISSUE THREAD

**Issue by remorses** [evanw/esbuild#2362]
Currently transform is missing the [`platform`](https://esbuild.github.io/api/#platform) option

This option is useful to annotate commonjs named exports so that node can statically analyze them and let you use named imports on commonjs files

**Comment by privatenumber** [comment]
Duplicate of https://github.com/evanw/esbuild/issues/2248, which was closed because Node.js actually directly reads the file from disk (bypassing any transformers like esbuild) to statically analyze the exports.
