### ISSUE TITLE
Inlined const enums add comments that aren't escaped

### ISSUE THREAD

**Issue by pushkine** [evanw/esbuild#2369]
### 🕗 Version

latest 0.14.48

### 💻 Code

```ts
// bar.ts
export const enum PRCD {
	"*/%" = 14,
}

// foo.ts
import { PRCD } from "./bar";

console.log(PRCD["*/%"]);
```
```
esbuild foo.ts --bundle --outfile=foo.js
```

### 🙁 Actual behavior

```ts
"use strict";
(() => {
  // foo.ts
  console.log(14 /* */% */);
})();

```
```ts
  console.log(14 /* */% */);
//                      ^^ ERROR: Unterminated regular expression literal. ts(1161)
```

### 🙂 Expected behavior

No errors

**Comment by hyrious** [comment]
Interesting, I haven't seen this behavior in transform mode because it removes comments. TypeScript used to have this issue too but they have fixed it in 4.7 with a simple string-replacement: `*/` &rarr; `*_/`. (see more about that at https://github.com/microsoft/TypeScript/pull/47990)
