### ISSUE TITLE
incorrect parse of parenthesized array literal

### ISSUE THREAD

**Issue by SheetJSDev** [evanw/esbuild#2375]
Shortest test case:

```ts
0?([]):1; 
```

Test:

```zsh
% npx esbuild@latest test.ts --outfile=test.js --platform=browser --target=es5
✘ [ERROR] Transforming destructuring to the configured target environment ("es5") is not supported yet

   test.ts:1:3:
      1 │ 0?([]):1; 
        ╵    ^
```

The carat is pointing to the open square bracket

The error is elicited by the ternary expression when the truthy part is a parenthesized array, irrespective of the number of elements.

**Comment by susiwen8** [comment]
https://github.com/evanw/esbuild/blob/master/internal/js_parser/js_parser.go#L2655
Esubild might take `([]):` or`({}):` is arrow function
