### ISSUE TITLE
React 'development' and 'production' libraries included in bundle

### ISSUE THREAD

**Issue by mxro** [evanw/esbuild#2377]
As initially reported in https://github.com/facebook/react/issues/24841

When bundling code that uses the `renderToString` method, multiple versions of react-dom are included in the bundle.

Here the file used as entrypoint ([index.jsx](https://github.com/mxro/react-server-side-bundling/blob/master/esbuild/index.jsx))

```javascript
import React from 'react';
import { renderToString } from 'react-dom/server';

console.log('rendered: ', renderToString(<div>Test</div>));
```

Using this build operation ([bundle.js](https://github.com/mxro/react-server-side-bundling/blob/master/esbuild/bundle.js)):

```javascript
  const res = await esbuild.build({
    entryPoints: ['./index.jsx'],
    bundle: true,
    minify: true,
    platform: 'node',
    format: 'cjs',
    treeShaking: true,
    target: 'node16.0',
    metafile: true,
    outfile: './dist/bundle.js',
    write: true,
  });
```

The following files are included in the bundle assembled by `esbuild`:

- `react-dom-server-legacy.node.production.min.js`
- `react-dom-server.node.production.min.js`
- `react-dom-server.node.development.js`
- `react-dom-server-legacy.node.development.js`
- `react-dom.production.min.js`
- `react-dom.development.js`
 
Here a sample project demonstrating the same: [react-server-side-bundling](https://github.com/mxro/react-server-side-bundling)

Note that when bundling the same `index.jsx` with [`webpack`](https://webpack.js.org/) there is no duplication in included React libraries. In result, the bundle generated with esbuild comes to 284 kb while the bundle generated by webpack is only 75 kb.

**Comment by hyrious** [comment]
You can add a `define` to enable constant folding with `minify: true`:

```js
define: {
	'process.env.NODE_ENV': '"production"',
}
```

Webpack automatically adds that config with respecting its running [mode](https://webpack.js.org/configuration/mode), however esbuild doesn't have that concept.

esbuild has one similar behavior that it adds the config automatically only when `platform: 'browser'`.

**Comment by mxro** [comment]
Sorry I don't think I quite understand. I thought I had enabled tree shaking in the example I've put together, see

https://github.com/mxro/react-server-side-bundling/blob/master/esbuild/bundle.js#L11

Is there anything else I need to configure in addition to setting `treeShaking: true,` when calling `build`?

**Comment by hyrious** [comment]
> Is there anything else I need to configure in addition to setting `treeShaking: true,` when calling `build`?

Add `define: { 'process.env.NODE_ENV': '"production"' }`.

**Comment by mxro** [comment]
Oh I see! Thank you, I tried that and it works great. I changed the `build` operation call to:

```javascript
  const res = await esbuild.build({
    entryPoints: ['./index.jsx'],
    bundle: true,
    minify: true,
    platform: 'node',
    format: 'cjs',
    treeShaking: true,
    define: {
      'process.env.NODE_ENV': '"production"'
    },
    target: 'node16.0',
    metafile: true,
    outfile: './dist/bundle.js',
    write: true,
  });
```

And esbuild now compiles a bundle with the size of 84 kb and no extra libraries.
