### ISSUE TITLE
TS: Class fields that use `declare` cannot be initialized

### ISSUE THREAD

**Issue by marvinhagemeister** [evanw/esbuild#2380]
Came across this pattern in the wild which throws an error with `esbuild` but passes compilation with `tsc`:

```ts
declare const isOptional: unique symbol;

class Foo {
  public declare readonly [isOptional] = true;
}

// TSC detects "a" as being true
const a = new Foo()[isOptional]
```

The error thrown by esbuild:

```sh
✘ [ERROR] Class fields that use "declare" cannot be initialized

    src/parser/v2/test2.ts:4:42:
      4 │   public declare readonly [isOptional] = true;
```

**Comment by evanw** [comment]
Huh weird, TIL. It looks like this is a very narrow special case (you can't even set it to `null`). I'll just allow anything here and let the type checker enforce the special cases.
