### ISSUE TITLE
Prevent entry files to be marked as externals

### ISSUE THREAD

**Issue by Gin-Quin** [evanw/esbuild#2382]
Presently, if an entry file matches of the `external` rules, the following error is raised:

`[ERROR] The entry point "y.ts" cannot be marked as external`

I created [esrun](https://github.com/digital-loukoum/esrun), which is a Typescript runner that uses esbuild under the hood. For the sake of esm/cjs compatibility, dependencies are not bundled into the final executable. To achieve this, I mark the following files as externals:

- "./node_modules/*"
- "../node_modules/*"
- "../../node_modules/*"
- "../../../node_modules/*"
- "../../../../node_modules/*"

> btw, a better way to mark "all parent node_modules" would be great, but that's not the point of the issue

This works fine, until an `esrun` user tried to execute a file that is already inside a `node_modules`. The error is described in [this issue](https://github.com/digital-loukoum/esrun/issues/18). Then the entry file is **also** matching one of the `external` string so it raises the forementioned bug.

Two solutions come to me:

- preventing one of the entry files to be marked as external even if they match (because it makes no sense to have an external entry file),
- or add an "internal" parameter that takes strings / regexps / globs to describe files that should be treated as externals (even if they match).

**Comment by evanw** [comment]
You're right, I should prevent entry files from being marked as external. I will do that in a future release.

**Comment by evanw** [comment]
A fix for this has landed in master, so I'm closing this issue as fixed.

**Comment by Gin-Quin** [comment]
Great! Thank you for the fix and the answer 💪
