### ISSUE TITLE
typeof generics allowed in TypeScript 4.7, but esbuild complains about angle brackets

### ISSUE THREAD

**Issue by bmaycc** [evanw/esbuild#2387]
Hi, 

In TS 4.7, the typeof keyword now allows generic values to be handled, which can be very handy in a number of situations.

For example ([playground](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABCAzgUwGJqhAFmgJwB4AVAPgAoAPALkRIEpEBvAKEQ8QOxAKSoDcrAL5CICFFEQBPOgCUefEtIAOaIlFVo4wZOiw58xSQRhgA5mTKIAvIgBEARgBMAZntDWAei+IUMAFsVABtCRDQqAEMg0LpI4JQ4RBVIlHQURDN6AGVWcTBJRAAvOk01HT1MbDxCIhMzS1tECmkmG2tpAURWIA)):
```ts
function useFetcher<T>(x: T) {
    return x;
};
const y: ReturnType<typeof useFetcher<string>> = "123";
```

Unfortunately, when sent thru ESBuild, you get a syntax error: 
```txt
error: Expected ">" but found "<"
  const y: ReturnType<typeof useFetcher<string>> = "123";
```

It looks like it's related to typeof handling in general, because the following also fails;
```ts
const z: typeof useFetcher<string>;
```
Error:
```
error: Expected ";" but found "<"
    const z: typeof useFetcher<string>;
```

Thanks in advance for the help!

**Comment by evanw** [comment]
I'm confused. It works fine:

```
$ echo 'const y: ReturnType<typeof useFetcher<string>> = "123"' | esbuild --loader=ts
const y = "123";
```

I assume you're using an old version of esbuild. In that case, you should update esbuild.
