### ISSUE TITLE
Cannot find namespace 'WebAssembly'

### ISSUE THREAD

**Issue by doteric** [evanw/esbuild#2388]
During the compilation using `tsc` with the esbuild API I encountered following error:
```
node_modules/esbuild/lib/main.d.ts:584:16 - error TS2503: Cannot find namespace 'WebAssembly'.
```

I had to `skipLibCheck` in TypeScript so that I can compile without any errors.

![image](https://user-images.githubusercontent.com/33552134/178841470-bc79a5f2-2ecc-4574-b2af-60157654fa59.png)

**Comment by evanw** [comment]
It's defined by TypeScript itself in [`typescript/lib/lib.dom.d.ts`](https://unpkg.com/typescript@4.7.4/lib/lib.dom.d.ts):

```ts
declare namespace WebAssembly {
    interface Module {
    }

    var Module: {
        prototype: Module;
        new(bytes: BufferSource): Module;
        customSections(moduleObject: Module, sectionName: string): ArrayBuffer[];
        exports(moduleObject: Module): ModuleExportDescriptor[];
        imports(moduleObject: Module): ModuleImportDescriptor[];
    };

    ...
}
```

Maybe you're using an old version of TypeScript?

**Comment by doteric** [comment]
Hey @evanw 
I use `typescript` `4.7.3`. I see that the `WebAssembly` namespace is there in `node_modules\typescript\lib\lib.dom.d.ts` indeed, but TypeScript doesn't pick that up. 🤔 

Here is the project that the problem exists if you'd like to know that: https://github.com/doteric/funpack

**Comment by hyrious** [comment]
This is because you have `"lib": ["es2021"]`, while `WebAssembly` is in `"dom"`.

**Comment by doteric** [comment]
Thanks for looking into this @hyrious 
Pretty interesting, and yeah `dom` wouldn't really fit into the package as it's only used on `node`.  
For now I'm fine with going with `skipLibCheck`, but just reported this issue for the awareness :smile:

**Comment by evanw** [comment]
Ok. I'm going to close this since the `dom` library is how TypeScript has chosen to ship type annotations for the `WebAssembly` API. This is a problem with TypeScript, not with esbuild. See also https://github.com/microsoft/TypeScript/issues/47381 and https://github.com/microsoft/TypeScript-DOM-lib-generator/issues/826.
