### ISSUE TITLE
Comparisons of heterogenous primitive types are not considered for dead code elimination

### ISSUE THREAD

**Issue by hamish-milne** [evanw/esbuild#2394]
`echo "if ('foo'=='bar') foo(); else bar();" | yarn esbuild --minify` outputs `bar();` as expected.

`echo "if ('foo'==null) foo(); else bar();" | yarn esbuild --minify` outputs `"foo"==null?foo():bar();` when we expect it to output `bar();`, because `'foo'==null` is always `false`.

This occurs when the LHS and RHS of an equality operator are different types, or arrays, or objects. Additionally, only `==`, `===`, the logical and ternary operators, and property accessors of new object expressions seem to be considered; arithmetic and comparison operators are excluded. While some of these are probably out of scope, it would be helpful to understand which constructs are eliminated and which are not.

**Comment by Conaclos** [comment]
Loose equality is often discouraged except for null/undefined checks. It seems fine to implement loose equality for these cases. It is pretty straightforward since null/undefined are only loosely equal to null/undefined.
