### ISSUE TITLE
Do not ignore imports

### ISSUE THREAD

**Issue by FlxAlbroscheit** [evanw/esbuild#2405]
For some reason, esbuild prevents me from importing images. Instead, it throws this warning...

```Ignoring this import because "src/img/icon_404.png" was marked as having no side effects [ignored-bare-import]```

...when trying to import a file in ```main.js``` like this:
```import '../img/icon_404.png';```

There is no "sideEffects" flag or whatsoever in the current module nor other imported modules. How can I instruct esbuild not to ignore this file?

My ```build.js```:
```
esbuild.build({
  entryPoints: {
    app: './src/js/main.js'
  },
  outdir: './dist',
  target: 'esnext',
  entryNames: '[name]-[hash]',
  publicPath: '',
  bundle: true,
  metafile: true,
  loader: { 
    '.png': 'file'
  },
  plugins: [
    sassPlugin(),
    assetsManifest({
      // ....
      }
    })
  ]
});
```

**Comment by evanw** [comment]
A file loaded with the `file` loader results in a single default export with the resulting file name as a string. You are supposed to use that string in your code to load the file. If that string is unused then tree shaking reasons that the file is unreachable and removes the file from the bundle. 

If you want to use the `file` loader then you should make sure the default export is used in your code to load the file. If you are trying to just copy the file to the output directory, then the `file` loader is the wrong tool for the job.

**Comment by evanw** [comment]
Closing due to lack of a reply. Also note that the [`copy` loader](https://esbuild.github.io/content-types/#copy) may be what you're looking for instead of the `file` loader.
