### ISSUE TITLE
Generic functions with default parameters in TSX error out

### ISSUE THREAD

**Issue by thatsmydoing** [evanw/esbuild#2410]
In esbuild 0.14.49, the following code in a tsx file
```
const foo = <T = unknown>(t: T) => null;
```
throws the following error
```
✘ [ERROR] Expected ">" but found "="

    index.tsx:1:15:
      1 │ const foo = <T = unknown>(t: T) => null;
        │                ^
        ╵                >

1 error
```

In typescript 4.7.4, the above compiles just fine.

For our particular case, we can workaround it by using the alternative generics in TSX workaround of using a comma but that doesn't apply to all cases.

```
const foo = <T,>(t: T) => null;
```

**Comment by evanw** [comment]
Thanks for the report. It looks like this changed relatively recently: https://github.com/microsoft/TypeScript/issues/47062. This will need to be changed in esbuild as well to match.
