### ISSUE TITLE
`tsconfig.json` extends with colliding directory name

### ISSUE THREAD

**Issue by JounQin** [evanw/esbuild#2411]
https://github.com/privatenumber/get-tsconfig/blob/adedf571e375e56d60b7b472e2ac8a356f14cff6/tests/specs/get-tsconfig/extends/extends.spec.ts#L367-L388

**Comment by JounQin** [comment]
Reproduction https://github.com/evanw/esbuild/pull/2412

**Comment by evanw** [comment]
You have only posted a link and a single word of text. Please use words to describe what the problem is. Are you saying that esbuild is missing test coverage for this and you just want to add a test? Or are you saying esbuild's behavior in this edge case is incorrect?

**Comment by JounQin** [comment]
OK, when I extends `config-package/lib`, there is a `config-package/lib.json` file and also `config-package/lib/` directory, `lib.json` should be preferred. (That's how TypeScript works).

My PR is trying to add a failing test case.

**Comment by JounQin** [comment]
I was going to fix it on my own machine, but I don't understand why whenever I started the test progress, I can never stop it but can restart my machine... So I can not working on a fix for it.
