### ISSUE TITLE
Modifying buffer output in onEnd callback doesn't update text output

### ISSUE THREAD

**Issue by ArnaudBarre** [evanw/esbuild#2423]
Following #1792

## Repro

version: `0.14.51`

```js
const { build } = require("esbuild");

build({
  write: false,
  stdin: { contents: "const a = 1;" },
  plugins: [
    {
      name: "updateOutput",
      setup: (build) => {
        build.onEnd((result) => {
          const file = result.outputFiles[0];
          const transformed = file.text.replace("1", "2");
          file.contents = Buffer.from(transformed);
          // Object.defineProperty(file, "text", { value: transformed });
        });
      },
    },
  ],
}).then((result) => {
  const file = result.outputFiles[0];
  console.log(file.contents.toString().trim(), file.text.trim());
});
```

## Result

Logs `const a = 2; const a = 1;`

## Expected result

Logs `const a = 2; const a = 2;`

## Workaround

Uncommenting the defineProperty line gives the expected result.

**Comment by evanw** [comment]
This is not a feature. There is nothing in the documentation that says this is supposed to work. I recommend calling `Object.defineProperty` as you suggested.

**Comment by ArnaudBarre** [comment]
I agree this not documented that it should work as simply as this, but this is what I expected when reading `It can modify the build result` in [this section](https://esbuild.github.io/plugins/#on-end) and seeing that text was a getter.

Would you accept a PR for:
1. Adding a small paragraph to document how to modify build result (i.e. setting both text and contents like above)
2. Update [convertOutputFiles](https://github.com/evanw/esbuild/blob/master/lib/shared/common.ts#L1691) to 

```ts
function convertOutputFiles({ path, contents }: protocol.BuildOutputFile): types.OutputFile {
  let text: string | null = null;
  let mutableContents = contents;
  return {
    path,
    get contents() {
      return mutableContents;
    },
    set contents(value) {
      mutableContents = value;
      text = null
    },
    get text() {
      if (text === null) text = protocol.decodeUTF8(contents);
      return text;
    },
    set text(value) {
      text = value;
      mutableContents = protocol.encodeUTF8(text)
    },
  }
}
```

**Comment by ArnaudBarre** [comment]
Thanks for the change. I understand the performance reason for not having a setter for text, but this not obvious at first that this is only a getter. This could be made clearer by adding a small precision in the doc like: ```It can modify the build result (by mutating `contents`)``` and adding a readonly modifier for `text` on the TS types.

**Comment by evanw** [comment]
Changing the type of `text` on the TS types makes sense to do, but people would likely complain if I did that because it's a backwards-incompatible type change. I'll try to remember to do that with the next breaking change release.

**Comment by ArnaudBarre** [comment]
Having a TS error because some part of your code didn't make sense is not a breaking change IMO because it doesn't break you code (.i.e nothing change at runtime) and you can just add an ts-ignore comment. But I understand that for a project of that size there is always people complaining
