### ISSUE TITLE
[Question] react lazy loading support? 

### ISSUE THREAD

**Issue by davidrenne** [evanw/esbuild#2427]
Can this bundle parse es6 imports like how webpack does it?

`import(/* webpackChunkName: 'lazyloadedfilename' */ filename.js)`

In which it knows to run a promise to fetch the js output that esbuild makes when react suspense renders that component child?

**Comment by davidrenne** [comment]
Or also webpack allows you to split chunks under certain patterns or callbacks using the below kind of configs

```
optimization: {
    moduleIds: 'named',
    splitChunks: {
      cacheGroups: {
        vendor: {
          chunks: 'all',
          name: 'vendor',
          test(mod) {
```

What would be a similar approach in this tool to attack loading your app into different js outputs.

**Comment by hyrious** [comment]
1. Manual chunks is still on the road.
2. esbuild can already split chunks that are dynamically imported through `format: 'esm'` and `splitting: true`. [repl link](https://hyrious.me/esbuild-repl/?version=0.14.51&mode=build&modules=%5B%5B%22main.jsx%22%2C%22export+default+function+App%28%29+%7B%5Cn++useEffect%28%28%29+%3D%3E+%7B%5Cn++++import%28%27.%2Fbtn%27%29.then%28setButton%29%5Cn++%7D%2C+%5B%5D%29%5Cn%7D%22%2C1%5D%2C%5B%22btn.jsx%22%2C%22export+default+function+Button%28%7Bchildren%7D%29+%7B%5Cn++return+%3Cbutton%3E%7Bchildren%7D%3C%2Fbutton%3E%5Cn%7D%22%2C0%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22splitting%22%3Atrue%7D)

**Comment by davidrenne** [comment]
Thanks!
