### ISSUE TITLE
Comma operator can change flow of execution

### ISSUE THREAD

**Issue by caffeinating** [evanw/esbuild#2434]
When minifying, multiple statements are sometimes joined together by the comma operator.   This can alter the semantics and/or the flow of execution imperatively set by the source code.

For example, in this source:
```javascript
function foo( a ) { 
  return someState.value( a );
}
class SomeClass extends BaseClass {
  // ...
  bar( b ) {
    this.record( 'got something', b );
    this.process( foo( b ) );
  }
}
```
the bar method has two statements, which are reproduced something like the following in minified output:
```javascript
function f( a ) { 
  return s.v( a );
}
class _r extends ue { 
  // ...
  ba( b ) {
      this.record( 'got something', b ),  this.process( f( b ) );
  }
}
```
In the original source, `this.record` will run before `this.process` begins, which means also before the call to `foo` is executed.   In the minified version, `this.record` will NOT run until after the call to function `f(b)` completes, because as a single statement any arguments must be resolved before it is executed.   i.e. the semantics of the `bar` method have changed.

In the case from which the above example is taken, when `SomeClass.bar()` was called, the `foo( a )` call was failing with an exception... ok.  But the `this.record()` statement did not run before that failure (not at all, actually).   I can imagine much worse, such as the standalone `foo` function being dependent on a side effect of `SomeClass.record`, which could mean `SomeClass.bar` might cause `foo( b )` to silently fail with incorrect values since `record` now runs after `foo` completes.

Finally, I'm unclear why this technique (comma operator) is being used anyway, since a semi-colon (instead of the comma) would result in the same source size, while incurring no change to source semantics.

**Comment by evanw** [comment]
> as a single statement any arguments must be resolved before it is executed

What? [The JavaScript specification itself](https://tc39.es/ecma262/#sec-comma-operator-runtime-semantics-evaluation) says that `a , b` means "evaluate `a`, then evaluate `b`". I encourage you to produce a working counterexample.

> I'm unclear why this technique (comma operator) is being used anyway, since a semi-colon (instead of the comma) would result in the same source size, while incurring no change to source semantics.

It's because `for(;x;)y(),z()` is shorter than `for(;x;){y();z()}`. All other JavaScript minifiers have been doing this same thing for years without any problems.

I'm assuming something else is going on that you'll need to debug in your code. Either that or your JavaScript environment is very broken. So I'm going to close this issue as invalid.

**Comment by caffeinating** [comment]
Dang, you beat me to the punch.   
I was returning to remove and/or close this issue myself, since 30 seconds after making the post I had a thought about what else might be happening, and sure enough, further investigation proved it... record() was not being enabled by a config.
My apologies.
And thanks for the explanation (and quick response!)
