### ISSUE TITLE
Escaping quotations in string concatanation/adding

### ISSUE THREAD

**Issue by thepirateraccoon** [evanw/esbuild#2436]
Hi I just stumbled upon the following minor problem:

`let name= "Bob"`
`let txt = "Hello '" + name + "' how are you?";`

Normally this should just turn into the following text: _Hello 'Bob' how are you_ however string escaping seems to be an issue even when excaping backslash \' is applied.
I don't know if I am missing something, if there exist a fix for it or it is a bug/missing feature.

Just noticed it, and thought I might put it in here.

**Comment by evanw** [comment]
I don't understand what you are saying. Please provide the esbuild command you used, the generated output, and the expected output.

**Comment by thepirateraccoon** [comment]
Apologies, when looking over how we used the minify tool I realized there was a script calling the tool and th same script was at fault, since it was manipulating the minified js, to make it compatible with some other part of our code.

**Comment by evanw** [comment]
Ok. Sounds like esbuild is working as expected then. Closing.
