### ISSUE TITLE
How to specific multiple external module by command arguments?

### ISSUE THREAD

**Issue by tjx666** [evanw/esbuild#2438]
After I google and read documents, I can't find any infomation about it.

**Comment by evanw** [comment]
This is documented here: https://esbuild.github.io/api/

> If you are using the command-line API, it may be helpful to know that the flags come in one of three forms: `--foo`, `--foo=bar`, or `--foo:bar`. The form `--foo` is used for enabling boolean flags such as [`--minify`](https://esbuild.github.io/api/#minify), the form `--foo=bar` is used for flags that have a single value and are only specified once such as [`--platform=`](https://esbuild.github.io/api/#platform), and the form `--foo:bar` is used for flags that have multiple values and can be re-specified multiple times such as [`--external:`](https://esbuild.github.io/api/#external).

so you do `--external:a --external:b`

**Comment by tjx666** [comment]
I read here https://esbuild.github.io/api/#external, maybe add an example of mutiple externals to here is better.
