### ISSUE TITLE
feature req: pass through Webpack "magic comments" inside Worker constructor

### ISSUE THREAD

**Issue by benjamind** [evanw/esbuild#2439]
# Feature Request

In https://github.com/evanw/esbuild/issues/309 support was added to pass through Webpack "magic comments" in `import(/* webpackChunkName: "foo" */ './foo.js')` style statements. Webpack also supports these chunk name comments in the `new Worker` constructor syntax:

```js
new Worker(
        /* webpackChunkName: "foo-worker" */ new URL(
            "../foo-worker.ts",
            import.meta.url
        ),
        { type: "module" }
    );
```
It would be great if this was supported in ESbuild for the same reasons, allowing the [esbuild-loader](https://github.com/privatenumber/esbuild-loader) project to work correctly for workers.

**Comment by evanw** [comment]
Is this behavior documented anywhere? I don't see it on https://webpack.js.org/api/module-methods/#magic-comments or https://webpack.js.org/guides/web-workers/. If it's indeed not documented, then it'd be good for someone to document it so people can find out about them.

**Comment by privatenumber** [comment]
Best I could find was a StackOverflow post referencing the magic comments doc:
https://stackoverflow.com/questions/70985414/how-to-handle-sharedworker-code-upgrades-with-webpack-5

At least it's in the code:
https://github.com/webpack/webpack/blob/8241da7f1e75c5581ba535d127fa66aeb9eb2ac8/lib/dependencies/WorkerPlugin.js

**Comment by benjamind** [comment]
Thanks for the fix!

**Comment by privatenumber** [comment]
@benjamind Where did you learn about Webpack's magic comments support in Workers?

**Comment by benjamind** [comment]
We only encountered it after trying to adopt esbuild in our workflow for TS stripping. I dug into the webpack source to confirm the behavior should have worked. Agree they should publicly document this feature.

**Comment by privatenumber** [comment]
Would you mind opening an issue with Webpack to document the behavior?
