### ISSUE TITLE
Imported typescript enums with numeric values can break

### ISSUE THREAD

**Issue by geoffharcourt** [evanw/esbuild#2443]
First off, thank you so much for your work on esbuild, it's made a massive difference in our organization's work.

We produced this issue in 0.14.51. This is a contrived example, but we had something similar break our app in production today. If the solution here is not to do this, we can try to avoid it!

We have a TS enum with numeric values

```typescript
/* enum.ts */
export enum HelloEnum {
  you = 0,
  say = 1,
  goodbye = 2,
  but = 3,
  i = 4,
  say = 5,
  hello = 6,
}
```

If the enum imported (this does not happen if the enum is defined in the file within which it's used), and we call `toString()` on an enum value, it gets output in a way that is invalid syntax.

```typescript
import { HelloEnum } from './enum.ts';

const items = ["a", "b", "c", "1", "2", "3", "4", "5"];
const item = items[Math.floor(Math.random()*items.length)];

const wasntEqual = item !== WorkInEnum.say.toString();

console.log(wasntEqual);
```

The result here is that the second to last line is output as:

```js
const wasntEqual = item !== HelloEnum.say.toString();
```

which to our astonishment breaks because you can't call `5.toString()`? If there's a space such as:

```js
HelloEnum.say .toString()
``` 

then this output would work. If the enum is defined in the file then the space is provided. The different behavior for an import vs. inline use makes us think this is a bug, but we're not sure!

**Comment by evanw** [comment]
I had to fix that code to get it to run. I changed `WorkInEnum` to `HelloEnum` and removed the duplicate definition of `say`. But once I do that, bundling with `esbuild --bundle --minify` produces valid code that runs fine:

```js
(()=>{var t=["a","b","c","1","2","3","4","5"],a=t[Math.floor(Math.random()*t.length)],s=a!==1 .toString();console.log(s);})();
```

So what's the problem? Sorry, I don't understand. Can you provide working sample code, the esbuild command used, and the complete broken output that you're getting?

**Comment by geoffharcourt** [comment]
Thanks for your response and apologies for the sloppy reproduction extraction. I've reproduced the issue more correctly here: https://github.com/geoffharcourt/esbuild_2443

I installed esbuild (only package) with `yarn install` and then ran `$(yarn bin)/esbuild test.ts` and got this output:

```
import { HelloEnum } from "./enum";
const items = ["a", "b", "c", "1", "2", "3", "4", "5"];
const item = items[Math.floor(Math.random() * items.length)];
const wasntEqual = item !== HelloEnum.say.toString();
console.log(wasntEqual);
```

It appears that running with `--bundle` here results in the space being added:

```
(() => {
  // test.ts
  var items = ["a", "b", "c", "1", "2", "3", "4", "5"];
  var item = items[Math.floor(Math.random() * items.length)];
  var wasntEqual = item !== 1 /* say */.toString();
  console.log(wasntEqual);
})();
```

Is this correct in the un-bundled case to not have the space? (Our application where we originally saw this issue did have `bundle: true` set, so I'm trying to determine if there's other circumstances that can reproduce this same problem.)

**Comment by evanw** [comment]
Ok, sounds good. I'll mark this as `unactionable` until you figure out how to provide a reproduction.

I went over the release notes and I didn't see anything that sounds like this. I also looked through the code for printing enums and didn't see anything obvious that could be used to cause this. So I'm still not sure how this would be possible on esbuild's end.

**Comment by geoffharcourt** [comment]
I can't reproduce this in a smaller case than our entire application's codebase, and I don't want to clog the issues list. If we can generate a smaller reproduction I'll reopen. Sorry for the use of your time for something unactionable!
