### ISSUE TITLE
Can I create my own export format?

### ISSUE THREAD

**Issue by dipakw** [evanw/esbuild#2444]
Hi,

I want to have my own export format. For example, below is my bundle code in `esm` format:

```js
function App() {
   // app code
}

function Other() {
  // other code
}

export {
  Other,
  App as default
}
```

Here, I want to implement my own export format, something like, `register({ _default: App, Other })`. I know I can do this easily by replacing the code, but just wanted ask if there's any better way to do this. I went through the documentation but couldn't find anything to achieve this.

**Comment by evanw** [comment]
No, esbuild only supports three standard export formats: https://esbuild.github.io/api/#format. You could do something like this in ESM using a self-import though:

```js
// some-file.js
function App() {
   // app code
}

function Other() {
  // other code
}

export {
  Other,
  App as default
}

import * as ourselves from './some-file.js'
register(ourselves);
```

**Comment by dipakw** [comment]
Thanks @evanw
