### ISSUE TITLE
yarn pnp transpile issue - (@cloudflare wrangler + mime types)

### ISSUE THREAD

**Issue by zerdos** [evanw/esbuild#2455]

**Comment by zerdos** [comment]
https://github.com/zerdos/spike.land/commit/b497a40f2feb299ec2421244054206948270ea12#r80882280

**Comment by evanw** [comment]
Sorry but I have no idea what you're trying to say. It looks like you're saying esbuild is now using Yarn PnP resolution rules, which is expected. This was recently announced: https://github.com/evanw/esbuild/releases/tag/v0.15.0. Marking this issue as `unactionable` because I don't know what to do with this issue.

**Comment by zerdos** [comment]
Sorry if I was unclear - here is a better example:


```
const mime = require('mime');

console.log(mime.getType('txt'));                       // ⇨ 'text/plain'             
console.log(mime.getExtension('text/plain'));   // ⇨ 'txt'
```

With  **nodeLinker: node-modules** esbuild produces the expected bundle, but with  **nodeLinker: pnp** the bundle will have a type error.

Also during the bundling now I got a warning, which say:
▲ [WARNING] Use "../../.yarn/global/cache/mime-npm-3.0.0-8d911e4c06-9.zip/node_modules/mime/Mime.js" instead of "../../.yarn/global/cache/mime-npm-3.0.0-8d911e4c06-9.zip/node_modules/mime/mime.js" to avoid issues with case-sensitive file systems [different-path-case]

    example.js:1:21:
      1 │ const mime = require('mime');

**Comment by evanw** [comment]
Thanks. I can reproduce the issue now. I think that the cause is probably the trailing `/` that Yarn adds to the end of its paths. That's not how esbuild works internally so esbuild's internals aren't expecting the slash, and that means it fails to search for `index.js` correctly. I'll fix this.
