### ISSUE TITLE
bug(v0.14.51): TSConfig JSX settings override API arguments for `--bundle` mode

### ISSUE THREAD

**Issue by ctjlewis** [evanw/esbuild#2460]
The recent TSConfig inference seems to have introduced a small bug where, in bundle mode, the provided `{ jsx, jsxFactory }` args will be overridden by the local TSConfig.

I have a project where we have `{ jsx: "preserve" }` in TSConfig, and I am telling ESBuild to `build({ bundle: true, jsx: "transform", jsxFactory: "React.createElement" })`, but it is emitting the JSX syntax in the output rather than transforming it (i.e. `tsconfig.json`s `preserve` setting is taking precedence). The untransformed output is not a valid program, and Node throws "unexpected character `<`". Building with `{ bundle: false }` does not reproduce this issue.

**Comment by evanw** [comment]
This isn't a bug. This is just how `tsconfig.json` handling works in esbuild. Since esbuild potentially reads multiple `tsconfig.json` files during a build, this behavior lets you have separate settings for separate parts of your build, which API arguments don't let you do.

**Comment by ctjlewis** [comment]
I assume it's a bug as nobody 

I want to force JSX settings for the build and cannot do that in bundle mode any longer, the build process is overriding my options with whatever is in the TSConfig it finds when `{ bundle: true }`. I have a TS-ESM spec that uses Esbuild for transforms and 0.14.51 breaks it. I am the guy calling the build process and telling it how it should configure itself so it should never be telling me what the config will be; it's fine to read defaults from TSConfig but my runtime settings would override under the logic of every other build process, and under the previous logic for this tool up until this version.

I would like to upgrade but I cannot if I can no tell Esbuild what the JSX settings will be. It reading from a TSConfig optimized for a Next build (a totally different optimization context), where `"jsx": "preserve"`, and not accepting my override *only* in bundle mode is extremely confusing behavior and assuming it was a bug was the charitable assumption.

**Comment by ctjlewis** [comment]
To stop short of a repro, it's very simple: My tool calls Esbuild to bundle a Next.js project. Currently tsmodule is held back to 0.14.50 and it bundles everything without issue using JSX settings I provide it (`React.createElement` factory etc.). The bundles are valid ES, not JSX, and don't throw when you run `node dist/pages/index.js`.

Upgrade Esbuild to ^0.14.51 and the build process will now stick you with the Next project's TSConfig settings, ignoring your overrides in the call itself. The emitted bundles now contain JSX because they read `preserve` from TSConfig and ignored your settings, and `node dist/pages/index.js` will now throw "unexpected character `<`", and are not valid ES programs.

So I don't know man. It certainly walks like a bug and quacks like a bug. Either way I just want to raise the issue.

**Comment by evanw** [comment]
You can pass an esbuild-specific tsconfig file if you don't want esbuild to use that `tsconfig.json` file: https://esbuild.github.io/api/#tsconfig. The file can be empty, or it can include whatever custom settings you want.

I could change how `tsconfig.json` works in esbuild but that would be a breaking change, and would have to be done in a new breaking change release.

**Comment by ctjlewis** [comment]
Hm, OK - I can just create internal tsconfigs and set JSX settings by configuring those, though this basically means that the `{ jsx, jsxFactory }` build parameters don't do anything when `{ bundle: true }, which is why I figured I'd raise it. 

But I see how to work around now.

**Comment by ctjlewis** [comment]
Ah, since `BuildOptions` does not take `tsconfigRaw` (only `TransformOptions`), I could only work around by totally unplugging from the project tsconfig entirely - if I could pass `tsconfigRaw`, I could just read `${process.cwd()}/tsconfig.json`, override some values, `JSON.stringify()` it and pass it in.

Normally, it would pick the config up, but my jsx settings would override (and those are really the only overrides I need); here I would need to standardize the tsconfig entirely to work around, and e.g. force `{ "strict": boolean }` with no escape hatch. I will probably just stay on 0.14.50 for now.

**Comment by spencewood** [comment]
I'm also experiencing this issue with a similar setup: Nextjs with the `bundle: true` parameter on the esbuild api. With the changes to how jsx is handled with the latest releases, I expected to be able to override the typescript configuration using the new `jsx: "transform"`, but it just doesn't work. And considering how Nextjs manages the tsconfig.json, changing the config file isn't really an option other than maintaining another esbuild specific config file.

**Comment by ctjlewis** [comment]
Nice, a fellow Next project bundler. See tsmodule in that linked commit above @spencewood: It’s just a configuration wrapper around esbuild, and has it held back until this is unblocked. 

There’s a section in the README about Next component libraries—just touch up the conditional exports field in package.json to export everything if you want page bundles etc downstream as well.

It requires going 100% ESM though.

**Comment by spencewood** [comment]
Thanks, I'll look into it! Not sure I can go 100% ESM right now. Might just be stuck on 0.14.50 for the time being.

**Comment by ctjlewis** [comment]
@evanw This issue still persists, and I cannot tell the `esbuild({ ... })` call to override the local `tsconfig.json`, it will always defer to what's on the filesystem.

**Comment by ctjlewis** [comment]
This is working again, thank you @evanw!
