### ISSUE TITLE
`esbuild@0.15.3` inserts the `"use strict";` directive before the configured `banner`

### ISSUE THREAD

**Issue by merceyz** [evanw/esbuild#2467]
**Describe the bug**

Starting in `esbuild@0.14.44`, esbuild inserts the `"use strict";` directive before the configured `banner`.

Ref https://github.com/yarnpkg/berry/pull/4732

**To Reproduce**

```sh
docker run --rm -it node:16.16.0 bash
cd $(mktemp -d)
yarn init -2
yarn set version 3.2.2
yarn add esbuild@0.15.3
printf '{"compilerOptions": {"strict": true}}' > tsconfig.json
printf "console.log(42)" > foo.js
yarn esbuild --banner:js='#!/usr/bin/env node' ./foo.js | node
```

**Comment by evanw** [comment]
Ah ok, I can make this work. FWIW the current way to use a hashbang is to put it in the entry point source file.
