### ISSUE TITLE
pnp: `esbuild@0.15.3` unable to resolve esm packages

### ISSUE THREAD

**Issue by YXL76** [evanw/esbuild#2473]
## To Reproduce

```bash
yarn init -2
yarn add strtok3 esbuild
echo "import * as strtok3 from 'strtok3';" > index.js
yarn esbuild index.js --bundle
```

## Result

```log
✘ [ERROR] Could not resolve "strtok3"

    index.js:1:25:
      1 │ import * as strtok3 from 'strtok3';
        ╵                          ~~~~~~~~~

  You can mark the path "strtok3" as external to exclude it from the bundle, which will remove this
  error.
```

**Comment by arcanis** [comment]
The way we handle this is that we make the "is it a package import" check on the specifier, not the resolution / unqualified path (if it's a package import, we then use the unqualified path to read the `package.json` and its `exports` field, like in Node). This is handled [here](https://github.com/yarnpkg/berry/blob/cf67f3a15052cf809cefcc0df58937874ad3c34d/packages/yarnpkg-pnp/sources/loader/makeApi.ts#L797-L798).

**Comment by merceyz** [comment]
The fix for this issue seems to have broken importing workspaces. The logs also show it doing a lot of file IO trying to locate stuff in `node_modules` which it will never find.

**Comment by evanw** [comment]
Can you provide an example test case? I’m building up a suite of Yarn PnP tests for CI and that would be very helpful to have.

**Comment by merceyz** [comment]
Sure, opened https://github.com/evanw/esbuild/issues/2476 with a reproduction to track the new issue.

**Comment by YXL76** [comment]
[strtok3](https://github.com/Borewit/strtok3/blob/91791f8f2ef80f905bdc0bc1088fd96ff2076ae9/package.json#L42) has subpath exports. `esbuild@0.15.4` still cannot resolve it.

```javascript
import * as strtok3 from 'strtok3/core';
```

**Comment by evanw** [comment]
> [strtok3](https://github.com/Borewit/strtok3/blob/91791f8f2ef80f905bdc0bc1088fd96ff2076ae9/package.json#L42) has subpath exports. `esbuild@0.15.4` still cannot resolve it.

Thanks for calling this out. I have realized this as well, and already have a fix. I'm currently working on getting it to be released.

**Comment by merceyz** [comment]
> the verbose logs also show it doing a lot of file IO trying to locate stuff in node_modules which it will never find.
https://github.com/evanw/esbuild/issues/2473#issuecomment-1217106596

Was able to track this down, opened https://github.com/evanw/esbuild/issues/2481.
