### ISSUE TITLE
Q: Css modules are present in {outdir} but somehow the js files won't load them

### ISSUE THREAD

**Issue by ThiagoFacchini** [evanw/esbuild#2479]
Like the title said,
I can see that the .css modules from my react components are available and transpiled inside my outdir.
Also, inspecting my dom, I can see the classNames were properly applied.

The problem I'm having is that none my css get's loaded into my application.

Here is my esbuild configs:
```
esBuildDevServer.start(
    build({
        entryPoints: ['./index.tsx'],
        bundle: true,
        minify: false,
        sourcemap: true,
        incremental: true,
        metafile: true,
        format: 'esm',
        loader: { '.png' : "dataurl" },
        // target: ['chrome58', 'safari11'],
        plugins: [
            stylePlugin({
                postcss: {
                    plugins: [
                        postcssImport,
                        postcssNesting,
                        autoprefixer                        
                    ]
                }
            }),
            copyFilePlugin({
                source: ['../../public/client/reset.css'],
                target: ['../../public/client/dist'],
                copyWithFolder: false
            }),
            svgPlugin()
        ],
        outdir: '../../public/client/dist',
    }),
    // To run the dev server a permission change is necessary:
    // chmod u+x node_modules/esbuild-dev-server-darwin-x64/devserver
    {
        port: '8080',
        watchDir: './',
        index: '../../public/client/index.html',
        staticDir: '../../public/client/',
        onBeforeRebuild: {},
        onAfterRebuild: {}
    }
)
```

Here is a very basic example of a React component:

```
import React from 'react';
import styles from './styles.module.css'

const NotFound = () => {

    return (
        <div className={styles.container}>
            NOT FOUND
        </div>
    )
}

export default NotFound
```

Here is the css file imported in the react component:
```
.container {
    background-color: salmon;
    font-size: 20px;
    display: flex;
    flex-direction: column;
    flex: 1;
}
```

Below a screenshot of my outdir (dist):
<img width="488" alt="Screen Shot 2022-08-17 at 9 40 37 pm" src="https://user-images.githubusercontent.com/6634582/185149088-105227d1-b02c-4e8d-afaa-629c3835393e.png">
FYI: Please disregard reset.css since it's been simply copied and is imported via <link rel...>  in index.html

Note that I have a index.css file outdir, and this is the content:
```
/* temp_stylePlugin:ni:sha-256;aV��<�B$[����4Z ���
rP����8 */
._container_1dtej_1 {
  background-color: lime;
  font-size: 20px;
}

/* temp_stylePlugin:ni:sha-256;�����T��.}r�j�&J�~[b�'���� */
._container_17tus_1 {
  background-color: salmon;
  font-size: 20px;
  display: flex;
  flex-direction: column;
  flex: 1;
}

/* temp_stylePlugin:ni:sha-256;�y�c�89T��!4�r5�ItWEy���w�	�� */
._appContainer_oriht_1 {
  background-color: #333;
  font-size: 20px;
  height: 100vh;
  width: 100vh;
}
/*# sourceMappingURL=index.css.map */
```

As you can see, looks like the esbuild-style-plugin is working...

Now when you look to the dom using chrome inspector, this is the result:
<img width="1481" alt="Screen Shot 2022-08-17 at 9 45 20 pm" src="https://user-images.githubusercontent.com/6634582/185150043-c57169c2-1e94-4bc5-95ad-f993448a7551.png">

The className seems to be right, although there's absolutely none of my style (refer to the transpiled css) related to the class container_17tus_1.

I tried several different things (including change the style plugin) but end of the day, all the other plugins generated the very same result.

Does anybody know what am I doing wrong?

Thanks in advance.

**Comment by ThiagoFacchini** [comment]
Just to add on top...

I had a look on the transpiled JS file, and I found reference for the imported css:

```
  // stylePlugin:/Volumes/External Storag/Projects/Squirkle/src/client/views/home/styles.module.css
  var styles_module_default = {
    "container": "_container_17tus_1",
    "threeContainer": "_threeContainer_17tus_8"
  };
```

Also, looking at the sources tab of the inspector, I found this:
<img width="1166" alt="Screen Shot 2022-08-18 at 8 55 08 am" src="https://user-images.githubusercontent.com/6634582/185268958-ea727787-a452-4abc-82e0-ca28dbf118a0.png">

I'm not what other bit of information may be relevant...

Anybody has any idea on what's going on?
Thanks!

**Comment by evanw** [comment]
I have no idea how the plugin you are using is supposed to be used. But if you were to use CSS in esbuild without a plugin, you would have to import the CSS into your HTML yourself. This is documented here: https://esbuild.github.io/content-types/#css-from-js. I'm mentioning this because it may be similar with the plugin you're using.

**Comment by ThiagoFacchini** [comment]
Thanks for your reply @evanw, really appreciate.
If I do that, it definitely works...
 
That said, what I am after are css modules, so I can avoid css namespace collisions... 
So end of the day I'm looking for css modules with postcss capabilities... as you can see from my post, everything looks right, but somehow the content of the classes don't reach the browser... I'm not sure what do, to be honest... I kinda exhausted all my options...

I was hoping to somebody had similar requirements, I mean, what I'm trying to do is pretty common in react projects, so I'm kinda surprised nobody run into it, which leads me to believe I'm the one doing something silly.

**Comment by evanw** [comment]
If the plugin isn't working then this is probably a problem with the plugin, not with esbuild. It'd be best to ask the author of the plugin instead.

**Comment by evanw** [comment]
Closing since this is not a problem with esbuild.
