### ISSUE TITLE
Does esbuild works with sequelize?

### ISSUE THREAD

**Issue by jodev7** [evanw/esbuild#2484]
here is error img
![image](https://user-images.githubusercontent.com/80722162/185539368-9bb037a6-5c43-47da-9de4-cf6ac95fc50b.png)

**Comment by evanw** [comment]
I guess not, sorry.

**Comment by evanw** [comment]
Closing as out of scope. This is documented here: https://esbuild.github.io/api/#non-analyzable-imports. You can mark the module as external if it doesn't work with bundlers.
