### ISSUE TITLE
Feature request: A way to bundle CJS files in a directory with type: module in package.json

### ISSUE THREAD

**Issue by tabarra** [evanw/esbuild#2488]
Scenario/issue:
- `package.json` at root of the project has `type: module`;
- The project first passes through `tsc` which transpiles to CJS (this step is required);
- When I run esbuild at the transpiled version (CJS), i get a bunch of `commonjs-variable-in-esm` errors.

The workaround for now is literally to write `{"type": "commonjs"}` to `./temp_tsc_output/package.json` to force esbuild to recognize the files as CJS, but this is hacky/fragile and I bet will likely break when I'm most in a hurry trying to fix prod or something.

Is there any less hacky way of doing that that i couldn't find on the docs?

**Comment by evanw** [comment]
This is the way node-style packages work, as decided by node itself. For example, if you run a file containing `module.exports = require('fs')` within a `{ "type": "module" }` scope using node, you'll get this:

```
ReferenceError: module is not defined in ES module scope

This file is being treated as an ES module because it has a '.js' file 
extension and 'package.json' contains "type": "module". To treat it as 
a CommonJS script, rename it to use the '.cjs' file extension.
```

You're supposed to use the `.cjs` file extension for CommonJS files inside a default-ESM package.

**Comment by tabarra** [comment]
Thanks.
