### ISSUE TITLE
ESM Code Splitting Imports

### ISSUE THREAD

**Issue by GravlLift** [evanw/esbuild#2489]
Apologies if this is a very obvious question, but I couldn't find anything in the docs to explain this:

I'm looking to use esbuild to generate `esm` formatted output _without_ bundling. As a simple case, I tried this.

a.ts
```ts
import { writeBLog } from "./b";
console.log("a.ts");
writeBLog();
```

b.ts
```ts
export function writeBLog() {
  console.log("b.js")
}
```

`esbuild a.ts --outdir=out --format=esm`

I was expecting to see both a `a.js` and `b.js` file in my `out` dir. Instead I only get `a.js`

a.js
```ts
import { writeLog } from "./b";
console.log("a.ts");
writeLog();
```

And of course, that import now refers to a non-existent b.js file.

It seems like esbuild is treating all files as external by default. What setting do I need to set to get esbuild to ouput a `b.js` file (and any other imports) as well?

EsBuild version 0.15.5

**Comment by evanw** [comment]
There’s nothing in the docs about this because this isn’t something esbuild does. 

Can you say more about your use case? Why do you want to do this instead of bundling?

**Comment by GravlLift** [comment]
I'm looking to share a module in memory across multiple entry points, and also make use of asynchronous loading of said modules. So in the above example, I'd like to have a third file, `c.ts`, that also imports `b.ts`. I'd list a and c and entry points, and then all three files would be output to the out directory as `a.js`, `b.js`, and `c.js`. Rather than duplicating the b module code in both `a.js` and `c.js`, the b module would sit in its own file.

Sounds like I'll need to declare all my files as entry points in order to accomplish what I'm trying to do? Might need to get creative with files that import a node_module...

**Comment by hyrious** [comment]
Maybe you're looking for the [splitting](https://esbuild.github.io/api/#splitting) feature.

If you want esbuild to preserve folder structure (preserveModules) #708, or manually control what files it will emit (manualChunks) #207, these are not supported yet.

**Comment by GravlLift** [comment]
Yeah, I guess #708 is indeed what I'm looking for. Thank you.
