### ISSUE TITLE
Support dynamic entrypoints.

### ISSUE THREAD

**Issue by avin-kavish** [evanw/esbuild#2492]
I would like to use some code as the entry point for a bundle, like maybe a function. is that possible?

Like,
```tsx
function foo() {
}

require('esbuild').buildSync({
  entryPoints: [foo],
  outfile: 'out.js',
})
```

**Comment by evanw** [comment]
No. You need to pass it as a string, either in a file or using the stdin feature.

**Comment by avin-kavish** [comment]
Maybe you can suggest a way to implement this. At runtime I have a reference to a function that I want to use as the entry point. I can emit some code to use as the input to esbuild. Just not sure how to get the path to the file so I can emit an import.

**Comment by avin-kavish** [comment]
Solved in a different way.

**Comment by evanw** [comment]
You’ll have to give it a name somehow and not use the stdin feature. Either put it in a file or use a plugin that matches and loads a specific arbitrary name. That name would go in the `entryPoints` array and also in the `export` statement.
