### ISSUE TITLE
Worker target/platform?

### ISSUE THREAD

**Issue by terpimost** [evanw/esbuild#2507]
I'm a bit confused if there is such feature/config in esbuild to produce worker with actual target of worker.
The problem is that some libraries do provide versions for browser and for a worker, [like his](https://github.com/orgs/remarkjs/discussions/1037#discussioncomment-3504130). 

So how should I configure the build process with esbuild to produce worker for a browser which would not think that is just a browser, so it will pick up version of libraries which don't call `document.`?

**Comment by evanw** [comment]
Are you looking for this? https://esbuild.github.io/api/#conditions

**Comment by terpimost** [comment]
Thank you @evanw for the fast reply. I think redirecting import path to different file locations is only a part of a solution.

For example I have `app.js` and `worker.js` entry points. 
I thought I should build them with different targets/platforms, shouldn't I?

I understand that there is `esbuild app.js --bundle --platform=browser` but what should I use for the worker?
Should I use node platform to bundle the worker.js like `esbuild worker.js --bundle --platform=node`?

esbuild doesn't have `worker` platform or `worker` target. Should I use `browser` platform but provide `node` target?

I want proper dependencies be pulled for the worker and I also want to avoid compiling worker.js with a code which calls for `document.something` (I guess this partly should be handled by the typescript config somehow)

**Comment by evanw** [comment]
> esbuild doesn't have `worker` platform or `worker` target. Should I use `browser` platform but provide `node` target?

I'm not sure. You should probably learn about the libraries you're using to see how they expect to be used.

**Comment by evanw** [comment]
Closing because there isn't a clear path forward for this. There are many kinds of workers and a single target for all of them doesn't seem appropriate to me. One way to do this is to use `--platform=neutral` to reset esbuild's environment defaults and then add in all of the behavior you want (such as `--conditions=worker`) depending on what your libraries are expecting.
