### ISSUE TITLE
Odd output for circular reference code splitting

### ISSUE THREAD

**Issue by guybedford** [evanw/esbuild#251]
a.js
```js
export * from './b.js';
export var p = 5;
```

b.js
```js
export * from './a.js';
export var q = 6;
```

when bundling with:

```
./esbuild --splitting a.js b.js --outdir=out --format=esm --bundle
```

I'm getting an output for a looking like:

```js
// a.js
export {
  p,
  q
};
```

with no definition of `p` or `q`.

**Comment by evanw** [comment]
That's strange. There is indeed a bug here, but I'm getting a different output. Here's what I see:

```js
import {
  p
} from "./chunk.js";

// a.js
export {
  p,
  q
};
```

So `p` is defined at least (esbuild version 0.6.1). The missing import for `q` is still a bug of course. I'll work on fixing that. Thanks so much for reporting this.
