### ISSUE TITLE
esbuild fails on optimization step `ERROR: Expected identifier but found "="`

### ISSUE THREAD

**Issue by janniks** [evanw/esbuild#2511]
**tl;dr** the esbuild optimization fails with the following error in the @angular/cli:
```
Error: Optimization error [main.108cfaa997006c95.js]: Error: Transform failed with 1 error:
main.108cfaa997006c95.js:51652:5: ERROR: Expected identifier but found "="
```

> More information and reproduction project in this issue: https://github.com/angular/angular-cli/issues/23842

**Comment by evanw** [comment]
What does the line with the problematic `=` look like?

**Comment by alan-agius4** [comment]
Esbuild is doing the right thing here, see: https://github.com/angular/angular-cli/issues/23842#issuecomment-1234202896

**Comment by evanw** [comment]
Yes this is not a problem with esbuild. Closing.

Also: esbuild’s error messages deliberately include the relevant line of source code to avoid confusion like this. If Angular is not including the line of source code as context for the error, they may want to reconsider that decision.
