### ISSUE TITLE
Darwin ARM64 exits and returns 137 while Darwin 64 works fine

### ISSUE THREAD

**Issue by tozz** [evanw/esbuild#2512]
After 1.5.1 (and every release thereafter) I see `esbuild` failing with error 137 on a M1 Mac, while it works without a problem on an Intel Mac. The exact same code base, same dependencies etc.
Worth mentioning is that this happens with the Phoenix `esbuild` (Elixir) installer and not when running `esbuild` via yarn, but I don't see why this would matter, the Phoenix one downloads https://registry.npmjs.org/esbuild-darwin-arm64/-/esbuild-darwin-arm64-0.15.6.tgz

I get that this isn't a very helpful bug report, but I can't get `esbuild` to give me any more error information.

**Comment by evanw** [comment]
Please provide instructions for how to reproduce the issue. Specifically the command line arguments and/or input files that are causing esbuild to exit abnormally.

**Comment by tozz** [comment]
Terribly sorry for the bad report, I figured out that it had nothing to do with any input source or similar, see attached crash dump. This happens by just running the binary, I don't know if this helps.

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: 0097EC85-B891-45A4-8395-7C80D733118A
CrashReporter Key:   79EB255E-F531-ED5C-AC25-25D6243871C4
Hardware Model:      Mac13,1
Process:             esbuild-darwin-arm64 [61911]
Path:                /Users/USER/*/esbuild-darwin-arm64
Identifier:          esbuild-darwin-arm64
Version:             ???
Code Type:           ARM-64 (Native)
Role:                Unspecified
Parent Process:      erl_child_setup [61909]
Coalition:           com.googlecode.iterm2 [2230]
Responsible Process: iTerm2 [3623]

Date/Time:           2022-08-31 21:29:19.9579 +0200
Launch Time:         2022-08-31 21:29:19.9562 +0200
OS Version:          macOS 12.5.1 (21G83)
Release Type:        User
Report Version:      104

Exception Type:  EXC_BAD_ACCESS (SIGKILL (Code Signature Invalid))
Exception Subtype: UNKNOWN_0x32 at 0x0000000104fa8000
Exception Codes: 0x0000000000000032, 0x0000000104fa8000
VM Region Info: 0x104fa8000 is in 0x104fa8000-0x105450000;  bytes after start: 0  bytes before end: 4882431
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  mapped file                 104fa8000-105450000    [ 4768K] r-x/rwx SM=COW  ...t_id=5e30a78b
      mapped file                 105450000-1056ec000    [ 2672K] rw-/rw- SM=COW  ...t_id=5e30a78b
Exception Note:  EXC_CORPSE_NOTIFY
Termination Reason: CODESIGNING 2 

Highlighted by Thread:  0

Backtrace not available

No thread state (register information) available

Binary Images:
               0x0 - 0xffffffffffffffff ??? (*) <00000000-0000-0000-0000-000000000000> ???

Error Formulating Crash Report:
_dyld_process_info_create failed with 6
dyld_process_snapshot_get_shared_cache failed
Failed to create CSSymbolicatorRef - corpse still valid ¯\_(ツ)_/¯

EOF

-----------
Full Report
-----------

{"app_name":"esbuild-darwin-arm64","timestamp":"2022-08-31 21:29:24.00 +0200","app_version":"","slice_uuid":"00000000-0000-0000-0000-000000000000","build_version":"","platform":0,"share_with_app_devs":0,"is_first_party":1,"bug_type":"309","os_version":"macOS 12.5.1 (21G83)","incident_id":"0097EC85-B891-45A4-8395-7C80D733118A","name":"esbuild-darwin-arm64"}
{
  "uptime" : 1100000,
  "procLaunch" : "2022-08-31 21:29:19.9562 +0200",
  "procRole" : "Unspecified",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac13,1",
  "procStartAbsTime" : 27646941931131,
  "coalitionID" : 2230,
  "osVersion" : {
    "train" : "macOS 12.5.1",
    "build" : "21G83",
    "releaseType" : "User"
  },
  "captureTime" : "2022-08-31 21:29:19.9579 +0200",
  "incident" : "0097EC85-B891-45A4-8395-7C80D733118A",
  "bug_type" : "309",
  "pid" : 61911,
  "procExitAbsTime" : 27646941968062,
  "translated" : false,
  "cpuType" : "ARM-64",
  "procName" : "esbuild-darwin-arm64",
  "procPath" : "\/Users\/USER\/*\/esbuild-darwin-arm64",
  "parentProc" : "erl_child_setup",
  "parentPid" : 61909,
  "coalitionName" : "com.googlecode.iterm2",
  "crashReporterKey" : "79EB255E-F531-ED5C-AC25-25D6243871C4",
  "responsiblePid" : 3623,
  "responsibleProc" : "iTerm2",
  "sip" : "enabled",
  "vmRegionInfo" : "0x104fa8000 is in 0x104fa8000-0x105450000;  bytes after start: 0  bytes before end: 4882431\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  mapped file                 104fa8000-105450000    [ 4768K] r-x\/rwx SM=COW  ...t_id=5e30a78b\n      mapped file                 105450000-1056ec000    [ 2672K] rw-\/rw- SM=COW  ...t_id=5e30a78b",
  "isCorpse" : 1,
  "exception" : {"codes":"0x0000000000000032, 0x0000000104fa8000","rawCodes":[50,4378492928],"type":"EXC_BAD_ACCESS","signal":"SIGKILL (Code Signature Invalid)","subtype":"UNKNOWN_0x32 at 0x0000000104fa8000"},
  "termination" : {"namespace":"CODESIGNING","flags":0,"code":2},
  "vmregioninfo" : "0x104fa8000 is in 0x104fa8000-0x105450000;  bytes after start: 0  bytes before end: 4882431\n      REGION TYPE                    START - END         [ VSIZE] PRT\/MAX SHRMOD  REGION DETAIL\n      UNUSED SPACE AT START\n--->  mapped file                 104fa8000-105450000    [ 4768K] r-x\/rwx SM=COW  ...t_id=5e30a78b\n      mapped file                 105450000-1056ec000    [ 2672K] rw-\/rw- SM=COW  ...t_id=5e30a78b",
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "usedImages" : [
  {
    "size" : 0,
    "source" : "A",
    "base" : 0,
    "uuid" : "00000000-0000-0000-0000-000000000000"
  }
],
  "legacyInfo" : {
  "threadHighlighted" : 0
},
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "60356660bbe37970735c5624",
      "factorPackIds" : {

      },
      "deploymentId" : 240000027
    },
    {
      "rolloutId" : "60da5e84ab0ca017dace9abf",
      "factorPackIds" : {

      },
      "deploymentId" : 240000008
    }
  ],
  "experiments" : [

  ]
},
  "reportNotes" : [
  "_dyld_process_info_create failed with 6",
  "dyld_process_snapshot_get_shared_cache failed",
  "Failed to create CSSymbolicatorRef - corpse still valid ¯\\_(ツ)_\/¯"
]
}

```

**Comment by tozz** [comment]
Just downloaded the archive and ran it separately, and it's not signed (as the error log shows).

**Comment by evanw** [comment]
Yes it’s not signed; the Go compiler does not generate signed binaries. But it’s strange that you are the only one with an M1 and this problem. 

Some ideas: Is the binary that Yarn downloads bitwise-identical to the one that Phoenix downloads (e.g. is `shasum` the same)? Are you doing anything unusual on your end to run the binary? Is your OS up to date? Does it work when you run it with Terminal.app instead of iTerm2.app?

**Comment by evanw** [comment]
Wait what does the “while Darwin 64 works fine” part in the title mean? Are you perhaps running Phoenix via x64 and Rosetta and you’re saying you need the x64 binary instead of the arm64 binary? If so and if downloading the x64 binary would fix things, you could talk to the Phoenix team about downloading a different architecture in this case. You could also try running Phoenix natively without Rosetta if that also fixes the problem.

**Comment by tozz** [comment]
SHA is identical between Yarn and Phoenix. 1.5.1 works with Phoenix, any version after doesn't. 1.5.1 and later all works with Yarn.
As for the ARM/Non-arm stuff, it was mostly to make sure I didn't have issues with the code base, I've seen rare occurrences where `esbuild` has crashed due to configuration settings so I wanted to make sure that wasn't the case (I tested it on an Intel machine).

My only guess here is that something changed between 1.5.1 and later in the compile-step somehow breaking it being run with Phoenix wrapping it, everything else is the same. Then again, if this only happens to me I guess I'm out of luck.

**Comment by evanw** [comment]
Ok well if it’s something Phoenix-specific then I’m not sure what to do about this issue report. Making this as `unactionable` for now.

**Comment by tozz** [comment]
Ok, this was weird, restarting the machine solved it, going to guess this was some weird macOS issue. Considering this closed.

**Comment by chrismccord** [comment]
I too am hitting this now and it unfortunately breaks *all* versions going back to the 0.12.x line which definitely worked for me prior. Restarting did not fix, so I don't know if this is an obscure issue or an OS update, but I'm hoping it's not widespread. It appears to be osx killing it because of an invalid signature, but I'm not sure what changed to start doing this.

**Comment by chrismccord** [comment]
If I sign it myself it runs just fine, but it will be wiped out the next time a new binary is fetched – which for Phoenix users would be the next time they ran `phx.new`.

**Comment by chrismccord** [comment]
Having Phoenix force the x64 binary instead makes it work, which I now realize is what @tozz was reporting. I guess because Rosetta? This is something we can do in the Phoenix esbuild package which is probably fine. I'll make that change for now at least. Thanks folks!

**Comment by tozz** [comment]
> Having Phoenix force the x64 binary instead makes it work, which I now realize is what @tozz was reporting. I guess because Rosetta? This is something we can do in the Phoenix esbuild package which is probably fine. I'll make that change for now at least. Thanks folks!
I haven't tested it yet, but won't this fail silently for those of us who doesn't have Rosetta installed? I don't think I've ever seen a CLI tool trigger Rosetta installation.

I just installed `0.16.4` for arm64 and it works as it should, so I think your change is too extreme @chrismccord , it's something local on your machine (as it were mine), not a general problem with unsigned binaries for Apple Silicon.

**Comment by chrismccord** [comment]
Upgrading from osx 12.5 to 13.x fixed the problem for me, so we can point folks towards that solution if this comes up elsewhere in the wild. Thanks!

**Comment by tozz** [comment]
Great to hear that you got it working :)

**Comment by AndrewDryga** [comment]
Reboot worked for me.
