### ISSUE TITLE
CSP Issue with new Function("return this")

### ISSUE THREAD

**Issue by jhirshman** [evanw/esbuild#2514]
Several of our libraries have distributed code that looks like this
```
try{n=n||new Function("return this")()}catch(e){"object"==typeof window&&(n=window)}e.exports=n},function(e,t,n){"use strict";var r=n(27),o=n(50)
```

the problem is that this code will trigger a CSP error because "new Function" is blocked unless you allow unsafe-eval

when we were using webpack, we weren't seeing any CSP errors.  This issue explains that you can set node options in webpack to override the "global" behavior https://github.com/webpack/webpack/issues/5627

Is there something we can do with esbuild to either strip out this code during esbuild bundling or another solution to avoid the csp errors?

**Comment by evanw** [comment]
It’s not esbuild’s responsibility to rewrite code for you like this. You are welcome to use an esbuild plugin to modify the problematic source code if you want. If it were me I would file an issue with the problematic libraries to get them changed, which would fix this problem for everyone. There are shims that don’t have CSP issues such as this one: https://mathiasbynens.be/notes/globalthis. Closing as out of scope.
