### ISSUE TITLE
Bundle glob-based dynamic imports

### ISSUE THREAD

**Issue by Cephyric-gh** [evanw/esbuild#2515]
In 1 of our projects we dynamically import files at runtime based on what the user has requested. Previously when we were using webpack to build the project it would automatically detect those import lines and include all the files that matched the base of the import in the bundle out of the box, however I cannot get this to work with esbuild. An example of 1 of the import lines is as follows:

```typescript
let ctor: {default: {new(event: IdentifiedEvent, ides: Record<string, string>): Bases}};

switch (method) {
    case HttpMethod.GET:
        ctor = await import(`../actions/native/${provider}/get/${version}/${path}`);
        break;
    case HttpMethod.POST:
        ctor = await import(`../actions/native/${provider}/post/${version}/${path}`);
        break;
    case HttpMethod.PUT:
        ctor = await import(`../actions/native/${provider}/put/${version}/${path}`);
        break;
    case HttpMethod.PATCH:
        ctor = await import(`../actions/native/${provider}/patch/${version}/${path}`);
        break;
    case HttpMethod.DELETE:
        ctor = await import(`../actions/native/${provider}/delete/${version}/${path}`);
        break;
}
```

Is there a way I can make esbuild detect these imports and include the files in the bundle similarly to webpack?

**Comment by Cephyric-gh** [comment]
Further digging lead me to https://github.com/evanw/esbuild/issues/56, which shows that it's in fact a limitation of esbuild that is not intended to be resolved. Unfortunate, but will look at the workarounds suggested in that issue.

**Comment by evanw** [comment]
That's a very old issue. I'm now working on doing a form of this: #2508

**Comment by Cephyric-gh** [comment]
Oh that's really good to hear (and very useful timing!), I will subscribe to that PR and await for a version to be released with this change for now then and continue with other things (still got a whole bunch of other things to migrate over for this specific project anyway, so the old webpack builder will suffice until that new change is released)
