### ISSUE TITLE
Sourcemaps points to incorrect line in Safari Web Inspector

### ISSUE THREAD

**Issue by chicoxyzzy** [evanw/esbuild#2522]
I have [a minimal example app](https://github.com/chicoxyzzy/esbuild-sourcemaps-safari) which could be built with either Rollup (using `npm run build:rollup`) or esbuild (using `npm run build:esbuild`).

<img width="419" alt="image" src="https://user-images.githubusercontent.com/1507086/188482076-ac464229-6090-41e4-abb9-3404a888c377.png">

When I build the app with Rollup and then run the server (`npm start`), I can see that line of `console.error` points to correct line (line 7) in Safari Web Inspector
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1507086/188482269-a12d33b2-b594-433d-8caa-372da76d344c.png">

When I build the app with esbuild, it points to the wrong line (the last line of the module — line 15) in Safari Web Inspector

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1507086/188482412-4ca24df1-77ed-4f09-8b08-fbb93324a639.png">

The line is correct for Chrome and Firefox

Chrome:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1507086/188482607-1ce3b388-194d-4a92-95e8-e8b1a65783e3.png">

Firefox:
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/1507086/188482674-288b0af1-c309-4005-b0b7-f4da6167974b.png">

**Comment by chicoxyzzy** [comment]
Thank you. I'm going to file the issue on WebKit Bugzilla

**Comment by chicoxyzzy** [comment]
https://bugs.webkit.org/show_bug.cgi?id=244814

**Comment by evanw** [comment]
Thanks! Closing as this is not a problem with esbuild.
