### ISSUE TITLE
Bundling individual npm packages based on package.json fields?

### ISSUE THREAD

**Issue by lewisl9029** [evanw/esbuild#2524]
Hi there!

I'm looking to use esbuild to bundle npm packages into independent es modules that can be imported and used by the browser directly.

I managed to get something working, but I've had to hack together a bunch of things in userland that esbuild already supports, namely:

- Determining the entry points to the package based on package.json `main` `module` `exports` fields and conditions
- Applying files substitutions based on package.json `browser` field

I was wondering if there's any way to make use of esbuild's built-in logic for handling these special fields in package.json for packages so I can get rid of the brittle code I wrote for handling this stuff myself that's probably missing a bunch of edge cases?

If not, I'd love to brainstorm how we might go about supporting this use case. One approach could be to accept a packageJson option (as file path or data) as an alternative to entryPoints to have esbuild handle everything automatically? Open to other ideas too, of course.

I'm not very proficient with Go, but happy to draft up a PR as a starting point once we settle on an API!

Thanks!

**Comment by evanw** [comment]
I’m not sure. Perhaps you might find the [resolve](https://esbuild.github.io/plugins/#resolve) API to be useful. 

It sounds like you want to determine all possible import paths for a given npm package. This is a pretty custom use case and is not something I’m interested in building into esbuild itself, as this is not something esbuild needs. It’s also something that I expect others in the community would be interested in, and something that would be independently useful as a separate module unrelated to esbuild. So I’m closing this issue as out of scope.

**Comment by lewisl9029** [comment]
Understood, on a second look, I realized esbuild only needs to resolve identifiers that are actually used, and doesn't need to enumerate all possible entry points for every package to do so. Definitely out of scope in that case!
