### ISSUE TITLE
Identifier directly after number

### ISSUE THREAD

**Issue by Thy3634** [evanw/esbuild#2528]
I got this in a vite lib project.

I got an error when use the lib

This is the source code:
```js
(0.0).toPrecision(d)
```

build result:
```js
0.toPrecision(d)
```
it's illegal.

I believe it's a bug.

**Comment by hyrious** [comment]
I don't think it is caused by esbuild: [see it in REPL](https://hyrious.me/esbuild-repl/?version=0.15.7&mode=transform&input=%280.0%29.toPrecision%28d%29)

As you can see esbuild generates valid code: `0 .toPrecision(d)`, there must be some other tools mis-printed the code.

**Comment by Sidarta85** [comment]
> Eu não acho que seja causado por esbuild: [veja no REPL](https://hyrious.me/esbuild-repl/?version=0.15.7&mode=transform&input=%280.0%29.toPrecision%28d%29)
> 
> Como você pode ver, o esbuild gera um código válido: `0 .toPrecision(d)`, deve haver algumas outras ferramentas que imprimiram incorretamente o código.

**Comment by Thy3634** [comment]
OK 
I found the reason, the code formatter deleted the space.
I think it's not a bug, but a bad feature, because it's should be direct and simple.

**Comment by evanw** [comment]
Which code formatter does this? Ideally this bug in that code formatted would be fixed so this doesn’t keep happening.

**Comment by evanw** [comment]
Well VSCode's formatter is at least one formatter that has this problem. I reported this bug to them here: https://github.com/microsoft/TypeScript/issues/50686
