### ISSUE TITLE
Having an Issue Resolving/Working With Font Files .woff and .woff2

### ISSUE THREAD

**Issue by ChrispyChris** [evanw/esbuild#2531]
Hello there,
I've been struggling to figure out what I'm doing wrong as I'm new to esbuild. I'm hoping that I'm close to getting things working and that I'm just making a silly mistake. Hopefully someone that is a part of the project can help me out here :)!

Here is my esbuild file:

```
#!/usr/bin/env node

const esbuild = require("esbuild");
const sassPlugin = require("esbuild-plugin-sass");

let onResolvePlugin = {
  name: "onResolvePlugin",
  setup(build) {
    let path = require("path")

    build.onResolve({ filter: /$\.woff2?/ }, args => {
      return { path: path.join(args.resolveDir, "build" , args.path) }
    })
  },
}

esbuild.build({
  logLevel: "info",
  entryPoints: ["src/index.tsx"],
  bundle: true,
  minify: true,
  sourcemap: true,
  plugins: [sassPlugin(), onResolvePlugin],
  loader: {
    ".woff": "file",
    ".woff2": "file",
  },
  outfile: "build/app.js",
}).catch(() => process.exit(1));
```

Off the bat, I'm wondering if my build.onResolve callback is causing this issue or not. You can see in my loader I have included both woff and woff2. I'll also post the errors I'm experiencing.

```> chriswoodtech@0.1.0 build
> ./build.js

✘ [ERROR] Could not resolve "../../../../../home/chris/Development/Websites/chriswoodtech/assets/fonts/Helvetica-Neue/HelveticaNeueLTW05-57Cond.woff2"

    ../../../../../tmp/tmp-1908091-YFN1AglmPfJE/chriswoodtech/src/index.css:1:289:
      1 │ ...W05-57Cond"),url("../../../../../home/chris/Development/Websites/chriswoodtech/assets/fonts/Hel...
        ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not resolve "../../../../../home/chris/Development/Websites/chriswoodtech/assets/fonts/Helvetica-Neue/HelveticaNeueLTW05-57Cond.woff"

    ../../../../../tmp/tmp-1908091-YFN1AglmPfJE/chriswoodtech/src/index.css:1:433:
      1 │ ...mat("woff2"),url("../../../../../home/chris/Development/Websites/chriswoodtech/assets/fonts/Hel...
        ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2 errors
```

If any other information is needed to help you understand what I have going on, I'd be more than happy to give any information you need!

**Comment by evanw** [comment]
> `/$\.woff2?/`

In a regular expression, `$` means “end of string” so I don’t think this regular expression will match anything. Is that your problem?

**Comment by ChrispyChris** [comment]
> > `/$\.woff2?/`
> 
> In a regular expression, `$` means “end of string” so I don’t think this regular expression will match anything. Is that your problem?

I'm not sure. I figured I would use that to target the font files specifically, as they both end in .woff. Am I wrong in my approach? It wouldn't surprise me, as I've tried finding any documentation on woff files and esbuild and am just struggling terribly haha.

**Comment by evanw** [comment]
`/$\.woff2?/` => `/\.woff2?$/`

**Comment by ChrispyChris** [comment]
> `/$\.woff2?/` => `/\.woff2?$/`

Still no luck :(, before your comment I also tried something similar, /.*\.woff2?/ and my thinking was that the .* covers everything up until the .woff extension. This actually changed my error to this:
```
> chriswoodtech@0.1.0 build
> ./build.js

✘ [ERROR] Could not read from file: /home/chris/Development/Websites/chriswoodtech/assets/fonts/Helvetica-Neue/HelveticaNeueLTW05-57Cond.woff

    ../../../../../tmp/tmp-1917759-Uld45k954i6M/chriswoodtech/src/index.css:1:433:
      1 │ ...mat("woff2"),url("../../../../../home/chris/Development/Websites/chriswoodtech/assets/fonts/Hel...
        ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

✘ [ERROR] Could not read from file: /home/chris/Development/Websites/chriswoodtech/assets/fonts/Helvetica-Neue/HelveticaNeueLTW05-57Cond.woff2

    ../../../../../tmp/tmp-1917759-Uld45k954i6M/chriswoodtech/src/index.css:1:289:
      1 │ ...W05-57Cond"),url("../../../../../home/chris/Development/Websites/chriswoodtech/assets/fonts/Hel...
        ╵                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

2 errors
```

You can see it is slightly different, Could no resolve changed to Could not read from file. That looks like progress, maybe? I'm still confused as to the issue overall, so don't take my word on any of this haha. 

Also I really appreciate you trying to help. You're the first person to tackle this so far!

**Comment by evanw** [comment]
Does the file `/home/chris/Development/Websites/chriswoodtech/assets/fonts/Helvetica-Neue/HelveticaNeueLTW05-57Cond.woff` exist? That is the path given to esbuild by the `onResolvePlugin` code you wrote. The error is saying that it does not exist (or is not readable). If this is the case, you will need to have your code give a different path to esbuild to a file that does actually exist.

**Comment by ChrispyChris** [comment]
Shoot, it exists but it's in my src folder, so /home/chris/Development/Websites/chriswoodtech/src/assets/fonts/Helvetica-Neue/HelveticaNeueLTW05-57Cond.woff

Is it skipping the src directory because of the return part of this?
```/home/chris/Development/Websites/chriswoodtech/assets/fonts/Helvetica-Neue/HelveticaNeueLTW05-57Cond.woff```

Again thanks, this is the closest I've gotten so far. I still don't quite understand the path part when it joins. I've tried looking at the docs for that, but path.join(args.resolveDir, "/build", args.path) is still pretty much gibberish to me. I can't figure out if that's where it's going to move the files when it actually finds them or what. I almost thought it was messing up my search, but I don't know.

**Comment by evanw** [comment]
You should be able to debug this yourself. For example, you can use `console.log` to print the value of a variable to the terminal in JavaScript. You can also read the documentation for `path.join` yourself: https://nodejs.org/api/path.html#pathjoinpaths.

One thing to know here is that you are using a plugin written by someone else (`esbuild-plugin-sass`) that is probably generating files in a temporary directory (in this case `/tmp/tmp-1917759-Uld45k954i6M/chriswoodtech/src/`). Inside `onResolve` for any import in one of those generated files, `args.resolveDir` will be that temporary directory. This is because import paths in a given file are resolved relative to the directory of that file. So you may not be able to use `args.resolveDir` like you wanted to here. It’s possible for a plugin to provide the correct `resolveDir` to esbuild to make this work but the plugin you’re using hasn’t done this. So you can either work around this yourself, work with the plugin author to enable this use case, or for the plugin and change it to your liking. 

In any case, I’m closing this issue because this is not a problem with esbuild itself.
