### ISSUE TITLE
[Question] Could not resolve 'xyz' Importing the directory is not supported

### ISSUE THREAD

**Issue by morsmodr** [evanw/esbuild#2535]
I am facing a build issue on a Remix app with the following error

![Screen Shot 2022-09-08 at 6 18 34 PM](https://user-images.githubusercontent.com/7231256/189252887-72d5725d-8ad3-476a-a29b-d99e4c94821d.png)

As Remix uses esbuild under the hood, this seems like a bug with it?

**Comment by evanw** [comment]
This is happening because [the ESM specification](https://nodejs.org/api/esm.html#resolver-algorithm) forbids importing a directory when `package.json` uses `exports`:

> Unsupported Directory Import: The resolved path corresponds to a directory, which is not a supported target for module imports.

This is not a problem with esbuild. Instead, you are importing from the wrong place.

**Comment by evanw** [comment]
This error message is the same thing that you get when you try to run code that does this in node itself. However, node's language for this could be considered confusing. I will add additional information. Here's the old error message:

```
✘ [ERROR] Could not resolve "example/dist/components/icon-badge"

    example.mjs:1:7:
      1 │ import 'example/dist/components/icon-badge'
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Importing the directory "./dist/components/icon-badge" is not supported:

    node_modules/example/package.json:3:16:
      3 │     "./dist/*": "./dist/*"
        ╵                 ~~~~~~~~~~

  You can mark the path "example/dist/components/icon-badge" as external to exclude it from the
  bundle, which will remove this error.
```

And here's the new error message:

```
✘ [ERROR] Could not resolve "example/dist/components/icon-badge"

    example.mjs:1:7:
      1 │ import 'example/dist/components/icon-badge'
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  Importing the directory "./dist/components/icon-badge" is forbidden by this package:

    node_modules/example/package.json:3:16:
      3 │     "./dist/*": "./dist/*"
        ╵                 ~~~~~~~~~~

  The presence of "exports" here makes importing a directory forbidden:

    node_modules/example/package.json:2:2:
      2 │   "exports": {
        ╵   ~~~~~~~~~

  Import from "example/dist/components/icon-badge/index.js" to get the file
  "node_modules/example/dist/components/icon-badge/index.js":

    example.mjs:1:42:
      1 │ import 'example/dist/components/icon-badge'
        │                                           ^
        ╵                                           /index.js

  You can mark the path "example/dist/components/icon-badge" as external to exclude it from the
  bundle, which will remove this error.
```

**Comment by morsmodr** [comment]
Thanks! I understand more now :)

The package in question has exports like so

```
  "exports": {
    ".": "./dist/index.js",
    "./dist/*": "./dist/*",
    "./package.json": "./package.json"
  },
```

As node doesn't do extension checks, we need to update above package that has this from `"./dist/*": "./dist/*",` to `"./dist/*": "./dist/*.js",` and that should cover any subpaths as well right? Like `./dist/components/icon-badge/index.js` `./dist/components/listbox/index.js` - Correct?

**Comment by morsmodr** [comment]
Was able to resolve this issue by fixing our internal package which had direct imports within dist folder. Switched to pure ESM exports and esbuild worked like a charm
