### ISSUE TITLE
Minifier ignore transformation on some conditions

### ISSUE THREAD

**Issue by Inqnuam** [evanw/esbuild#2538]
Hello,
is there any way to tell to the minifer to not transform for example:
```js
if(true) {
console.log("this is true")
}
```
to:

```js
console.log("this is true")
```

an easy workaround when minifier is disabled is:

```js
if(true == true) {
console.log("this is true")
}
```
it will be converted to 
```js
if(true) {
console.log("this is true")
}
```

**Comment by evanw** [comment]
No there isn’t. Why do you want to do this?

**Comment by evanw** [comment]
Maybe your question is about how to minify whitespace and/or minify identifiers but not minify syntax? There are settings for this. Everything is described in the documentation: https://esbuild.github.io/api/#minify.

Closing this issue due to lack of a reply.
