### ISSUE TITLE
Misunderstandings with Tree-shaking & Types

### ISSUE THREAD

**Issue by helloimalastair** [evanw/esbuild#2540]
Just want to clarify because I'm not 100% sure. If I import **ONLY** types from a package(`import types { something } from "somepackage";`), then said package should not have any impact on my bundle size, right? I'm using the `discord-api-types` package, and for some reason, it seems the entire thing is bundled, even if I don't actually import any non-types. It would be fine if it were lighter, but currently, it makes up more than half of my bundle, with helper functions I do not use.

For reference: [metafile.](https://nopaste.ml/?l=json#XQAAAQAIlwAAAAAAAAA9iIknJB4biI7G2OxBU1VlYuyRGgVmSPzJkb9LQGpL/6ORnlHn8TkXkTIIXncPzpa6xrI4Jo735+fDDA7ZU+Kpps3i8qH8weBbcKFqg9p9BpdV9Zy9qeiSCpOGG/TfWSanM/1+ey62WgVe9o0+jSMhun94SmXWOWfKiuNjw9FJjBwCMx/wPWNVeJ4JuYgdLQAlaFSTak5SamypKaEScRqTByr5Qr+w6XgSyV3IfCNW/U2/Sg9UKwgS3GD4TansU90oRdgE2Sg3LzuyZ58dwHMMfenjvacdeXzJ/+R2OJD/kg9z2jVQeedIFP/ZX9DO/movt+Q3cwAiVu/w8ElWI2anuUiVBuDjAhffGspyCoc7DAs6jvqN+VFJ4s6wFm8awyIdYgGTkE7Pp1VuHi3xcjh932hRuFQzRhuArSpshm7jtIu9cfpgws3iPt/3xb5UOA6Att0qTqMJkGRZNCObu3rl24sccM60L3KyNOKGAC50+cvzm5xwZtZ4O7uWFW3lzGGZc8YB9Bjgdph2SEuwivfRRdg8/9AoTNUHqe/d/PBBkMwHviiFpRCaXHsmJnQDkFYNHxEECo9afZSXYb0WwygjR58JIK1aZkX6aLJx24L4yuMrxE+D1aU2E9NMQNi8mMVnvPJgd67rP/b/X8VC48tNJeYHfHzyzkG5cOF9bvhyMa9iHSNHmBkR3YsDh+OMhBvXPtlHfvo7djatvekGZn2SIAX6ccZPwBFm95sak6rVWn9pvWd3GvMxhUakhefph9I/96jpd1hB4483AJ56kmAgHU7+1RpGR4eRhC4cfl2pgPsUodvuVwbylVYkyk8eLkTTawupOYgDftzpVXvKQxnaYMx9s0bzvrCEXJspS45qn7zifnTUIA2sQR1dFJoRASIqQvKkH/2jTt+5vJ4ZCxGFcf1As2rDylfopiLneic+QLYZnsVNCcQZujtueTFGsTiGgkKjsXeVwTbpsGpNKcamHoTD6lRlz+sNcLQvd7YZ2+TaHLiwLo5bWMZQN+MYlGJg1CGvsxxhDddA+Ag6wkf2HxnsV8dZXe2e/i6zNpOVpYX5lNYaBmbBGgTkfORVmYOFH+cc8cpZjR4JcNFx3DlPbfNjwn1XbllT23ktcar3j5e6CikbUZCc8E7sP9UrCQfviyvlbFYqK3rVMgCI8WxQ8D/bVJdUlyYurH6kOt4kpo6FuAImgj4aI2RWnXPrHhVfjvS0b5/NmsE/dFRVUyQSppuFJVrR/vA1fEV0SH5ybqnSkyu1iEdO4CxGoIWNho25oq81tJoeEyJnx2pyTAiz7MWOySBCUfq117FCQLq4m7s0CnGTsvV8zC1Wxjx2MqQzA8UMCq4P1SZ55tFJOu0BvL58idHKBwxLQk/G0fbBQIHGXq/wcm3S4kTS3ZV4po9vuRQfyBA3nWshl8dSROvP9bTGNbYrtGfh7ZxjVwjhm1j5obTcXRbKFStxb/BdRmBNstOvqvazyzWmv3G378sveAd8+BEX9IGWkkc84sj10kOWpPoJ7yU3sLpRxr9eRNtG8S6mekwAWCQKvdqMJu2MLCOvSlvtI19lbmMkJkg0IWtbGEM5iRuwIGBNFtIC+3YH04IjJ9XSA16QDnXaBPUg1gkOe6tA4kcpWkHT+uDaiUz28HCKayxX3J7vDAFuIILGZR4+aK5Fy7D5Xh60toKv537QUU09tiia3R9pFPwLqlqwr3NbEw/hOG3qHhdxJV4agMsHKQdTtvQZJvCXZ96ZTQQnRoVJGim0+3fQQQhDDIZmIWTgvEU82I9zE+QL2eLVgfwQHQZWQ/e8lyZ/nc7JQkGAxPI2nl/hWFXxWCm1+Qfcdv6ouX3lVOh4h2xfh0kcovKsFsCWSd/Qm53j0HVcjgwnAIr3bCTBhJHSDcWYK55ZGk7qNb7atXKsOnSMramT2QqFmHI2vwkpJ80eVAqIcFhBj1qPct7vXj3qKdb8J0peuqmy4DwazNmKsUqzYGNBo2E89Rfgf/nRVE6h1pidq012w3A5jMkiVadXVx8mvi0TuOnTt5XzJJXr2GQLAZ8fMxaU6yEe2iN94psNLCgDXtBh9mktJpmQmbck5wnYvemTRT/Sok/bZQE0t9ZooPdKzU5JodtK+RqH6RBR1ownfA8z/WIzYhfgE4QMHVoJA7svdX8pn+VF+YIc0Aovj3wBVXVimED1KRiEJBcEpgX0N32Zeky6hYLWsuAjwsou7sXJHKqQQQv9az3CsBjTkErpGmKAhsF5353kAoOt864ipwkHjpkWD3Wg7Cy/yWpL9H51gAwIVuggbSBhLxdG7XryFA/TRKyoM/mOd6DGeWI1y71bUOQqA7emwuJGCuVX1v/58HlNtu0RLO5VGR0Axe21aa+W7AweAgfWPkGOK2E5pZcVPkPPjbSlqjDPNpXrhHjRZJlbkDi/uPCNv5iUzO/Nz0bKAtnd2+p5OJuTZ4GdWO1jIuPwjmJ8Hbn2KQxBmzmy0cZucKL4GY+XKXCxdB+apMHrymbH/64fCwPLQbXgdj3RxTP1HQEZy4VZO0qIqz3mbatgOV+uPBeO/Qm71Z7Gsz4aZbGN0DhWscY8rAc3/q/mpdno1ILVoRQO+XieShkPaGbxfEtFHGdL1Nd/FYLcrqAedfmG9R1mj74Gsn/EQB0wgNoSwyEjNfGO6ERIvQECvcH5SM1/DB2mfg6a3xiAkEFA3gelCSPyB0YOM4vslfeT35kgwG4dxuFuL0l1qkOGMV3iwQU9pTuM7oT4cr4hGGhDZEcwcyV6o4/m6j+nKlYBpvdTGT9PvNCzVI+1FwnD2CvMRW8HCsbzC7F4t+KxTVcMG6wvwAzU39EwEpmtCBaBnvTXOSOL8Yqj2xErwhjDShvZsjOw0JLFrs4nRIc2IvHRhriaiAStRyXUXTxBpgdueO+0Q5yTDNXKeIiML5j0sAWhNV/q9xgRwkA7HOrZN2ImSE14P6RwwIS6f0ijqW4Sv5bcKqP/YQYmlVPdlhBJe0bTLiNotbAbfuYKBeX1SmP395zchb8ueBSN6HoZjb/oihb74egAOplRoVrEW6VdgtmCXbr0lGSjZWefBvKodHc7OSt28K0wUpg5xSPukJWog7RfeIVMTUUPcpfR/TRzYJA++mMWPL9QL9BmI4un6QmZFhklh5KYklnJ72LfGvIq4T8jJ+SUujHWOduId+BKj67kH2Ba9RWfCASyfwPmw6jom2n9mRP2zHiyO8KOK8p9gcOyI9/aL1f0aKlAZ6ZH0/FSRKQWG4rCeyZTWpLO2oTXJ9gan2SflrdaNrQ0flZvP64cwNKKKg+2H3tNPDwGJbLZuIQhSXbV1uK30f0xgBjEQUlxyx1bMttzOXKpAef5y2SNFQxCr9OrFkyPhAK8uRsMIzC8PKBL07Ndb4YUkW8POwZmCuD56X8EzrXgDUl5lLvY7cyGR4fF1rCtv1iMzqfO536yGH5IsonjWLpKJl1sCLkMEJzreTm1XojpIy6PSYwxgydBzzohGXdnJ9IomMtWEqKyLl0b1eNHcO5e2qzFTIsCHuolufYpkRBdEH6FzKw5eF2eSqS7qXrxvisLiLQpTwZKp4Xraif/rEYV8g==)
79% of assets calculated are from the types-only package.

**Comment by evanw** [comment]
The TypeScript syntax is `import type { something } from "somepackage";` (no `s`) but yea type-only imports have no effect on bundle size. In case it’s helpful: you can use [`--analyze=verbose`](https://esbuild.github.io/api/#analyze) with esbuild to see where something is imported from.

**Comment by helloimalastair** [comment]
@evanw 

Sorry, it was a typo(I wrote it out correctly in my code). Got it working now and removed about 110 KB of dead code. Thanks for your help!
