### ISSUE TITLE
Building code to a variable

### ISSUE THREAD

**Issue by Kycermann** [evanw/esbuild#2549]
Hi, I'm using esbuild progammatically like this:

```js
esbuild.build({
   plugins: [],
   entryPoints: [input],
   outfile: output,
   bundle: true,
   minify: false,
})
```

Is it possible to return the results to a variable instead of outputting to a file?

If not, is it intentional?

**Comment by evanw** [comment]
Closing as there is nothing to be done here. Hopefully the documentation in the above link is sufficient.

**Comment by GeoffreyBooth** [comment]
I came looking to open an issue requesting this and fortunately found this issue. I would have expected this to be mentioned in either https://esbuild.github.io/getting-started/#build-scripts or https://esbuild.github.io/api/#build-api or under the various `out*` options. I would appreciate some part of the docs where the JavaScript API is fully documented in one place, including the possible return values of `build()`.
