### ISSUE TITLE
Bundle doesn't include external module

### ISSUE THREAD

**Issue by grenierdev** [evanw/esbuild#2559]
I'm studying esbuild for a new project and I'm encountering an odd issue.

**Version**
```txt
$ node --version
v18.8.0
$ esbuild --version
0.15.8
```

**index.jsx**
```jsx
import { h, render } from "https://esm.sh/preact@10.11.0";

const App = <h1>Hello World</h1>;

render(App, document.getElementById('app')!);
```
**Bundlng**
```sh
esbuild --bundle --minify --outfile=index.js --jsx-factory=h --jsx-fragment=Fragment --format=esm --target=esnext ./index.jsx
```

**Output**
```js
import{h as e,render as o}from"https://esm.sh/preact@10.11.0";var p=e("h1",null,"Hello World");o(p,document.getElementById("app"));
```

**Expected behaviour**
Since the preact import is not defined as an [external package](https://esbuild.github.io/api/#external), I expect it to be bundled in my `index.js`.

Am I missing something or is it the expected behaviour of external import?

**Comment by hyrious** [comment]
`https://` paths are external by default (https://github.com/evanw/esbuild/blob/master/internal/resolver/resolver.go#L310), you may want to use a [plugin](https://esbuild.github.io/plugins/#http-plugin) to bundle them.

**Comment by grenierdev** [comment]
Thanks @hyrious !
