### ISSUE TITLE
Support JSON output format?

### ISSUE THREAD

**Issue by timiyay** [evanw/esbuild#2560]
I have a use case where I'd like to create an esbuild plugin that transforms a JS module into a JSON file, but I'm currently unable to achieve this since the formats of `iife | esm | cjs` always add a module export or other wrapping code.

Is there an appetite for a `json` or `bare` output format?

**Comment by hyrious** [comment]
What kind of JSON value do you expect from a JS module?

**Comment by timiyay** [comment]
We have a 2-part build.

Part 1 uses esbuild to bundle JS code as normal.

Part 2 transforms some JS files to JSON, by executing them. This allows us some dynamism when composing asset manifests (it's for building interactive games).

Part 2 is undergoing some review, and I'm experimenting with whether esbuild's plugin system would allow us to wrap our custom logic in a great, existing build tool.

It's possible esbuild is not the right tool for this, since it's aiming to be a JS bundler, not a generic build tool.

Nonetheless, I was blocked in my experiments by the requirement to use `iife | cjs | esm`. Though, I could add some extra build step to snip off the `module.exports =` prefix and have some JSON.

**Comment by evanw** [comment]
This sounds out of esbuild's scope. Nothing esbuild currently does involves running the code that it processes. I recommend just using `fs.writeFile` and `JSON.stringify` if you want to convert a JS object to JSON and save it to a file. You don't need esbuild for that.
