### ISSUE TITLE
Integration with core-js to replace import based on target?

### ISSUE THREAD

**Issue by adrienharnay** [evanw/esbuild#2561]
Hi,

I was wondering if you would consider implementing an integration with `core-js` to replace `import 'core-js/stable';` with only the imports needed for the `target` given to esbuild?

Like [babel](https://github.com/zloirock/core-js#babel) and [swc](https://github.com/zloirock/core-js#swc) do.

Thanks in advance!

**Comment by zloirock** [comment]
All required for the implementation of this mode data is available [here](https://www.npmjs.com/package/core-js-compat).

**Comment by evanw** [comment]
It's deliberate that esbuild doesn't try to automatically inject polyfills. This avoids unnecessary overhead if the polyfills aren't needed, and also lets you choose which polyfills to use. This is already [described in esbuild's documentation](https://esbuild.github.io/api/#target):

> Note that this is only concerned with syntax features, not APIs. It does *not* automatically add [polyfills](https://developer.mozilla.org/en-US/docs/Glossary/Polyfill) for new APIs that are not used by these environments. You will have to explicitly import polyfills for the APIs you need (e.g. by importing [`core-js`](https://www.npmjs.com/package/core-js)). Automatic polyfill injection is outside of esbuild's scope.

You are welcome to create such an integration as an esbuild plugin if you'd like. I'm closing this issue as out of scope.

**Comment by adrienharnay** [comment]
Thank you for the answer! What would be the recommended approach when used with webpack / `esbuild-loader`, which doesn't support plugins?

**Comment by evanw** [comment]
I'm not sure because I don't have anything to do with `esbuild-loader`. But Webpack supports plugins so I assume you'd just write a Webpack plugin?
