### ISSUE TITLE
Use WASM service on multiple files

### ISSUE THREAD

**Issue by UPL123** [evanw/esbuild#2563]
I am making a server that serves modules compiled with esbuild. For that, I am using a Deno server with this code

```ts
const service = await esbuild.initialize({
    wasmURL: "https://deno.land/x/esbuild@v0.14.51/esbuild.wasm",
    worker: false,
});

http.serve(async req => {
    return handler(service)
});
```

But when I compile, I get this error

```ssh
ReferenceError: Worker is not defined
    at startRunningService (https://deno.land/x/esbuild@v0.14.51/wasm.js:1749:5)
    at async npmHandler (file:///src/src/npm/mod.ts:116:34)
    at async Server.#respond (https://deno.land/std@0.156.0/http/server.ts:219:24)
```

This maybe means the service isn't getting imported. I would like to use a function to get the service, like in this code

https://github.com/esbuild/deno-esbuild/blob/f422aa98a8533060a4d60bd1947980cc74706027/wasm.js#L1644

Thanks, UPL

**Comment by evanw** [comment]
I'm not sure what you're saying because you haven't provided a way to reproduce the issue. But I'm guessing you're confused about the `initialize` function. It returns `void` as you can see [here](https://github.com/esbuild/deno-esbuild/blob/f422aa98a8533060a4d60bd1947980cc74706027/wasm.d.ts#L577):

```ts
export declare function initialize(options: InitializeOptions): Promise<void>;
```

So it doesn't make sense to try to make use of the return value of `initialize` like you are doing here. If you aren't already, you may want to consider using TypeScript with Deno so that the type checker can tell you this.

**Comment by UPL123** [comment]
I want to start the service on a file and use it on other files.

**Comment by evanw** [comment]
I'm not sure what you're saying because you haven't provided a way to reproduce the issue. Please provide a code sample that reproduces the problem as well as instructions for how to run the code sample.

**Comment by UPL123** [comment]
Server file
```ts
// Initialize esbuild
await esbuild.initialize({
  wasmURL: "https://deno.land/x/esbuild@v0.14.51/esbuild.wasm",
  worker: false,
});
http.serve(async (req) => {
  return handler()
}, { port: 8000 })
```

Handler file
```ts
function handler() {
  // Use esbuild
  const result = esbuild.build({
    // Options
  })
  // Using this returns: Worker is not defined
}
```

**Comment by evanw** [comment]
That code doesn't run:

```
$ cat foo.js 
// Initialize esbuild
await esbuild.initialize({
  wasmURL: "https://deno.land/x/esbuild@v0.14.51/esbuild.wasm",
  worker: false,
});
http.serve(async (req) => {
  return handler()
}, { port: 8000 })

$ deno run foo.js 
error: Uncaught ReferenceError: esbuild is not defined
await esbuild.initialize({
^
    at file://./foo.js:2:1
```

**Comment by UPL123** [comment]
Hi, Im closing this because I fixed the issue. Now I use a function to start the service and return it and then use it on the function. Sorry for the errors and thanks!

UPL
