### ISSUE TITLE
`--tsconfig-raw='{"compilerOptions": { "target": "ES5" }}'` has same effect with `--target es5` since 0.15.8

### ISSUE THREAD

**Issue by sapphi-red** [evanw/esbuild#2564]
```js
const a = 7
```
When transforming the code above with `--tsconfig-raw='{"compilerOptions": { "target": "ES5" }}'`, with esbuild 0.15.7 no errors happen, but with esbuild 0.15.8 "Transforming const to the configured target environment" error happened.

[esbuild repl 0.15.7](https://hyrious.me/esbuild-repl/?version=0.15.7&mode=transform&input=const+a+%3D+7&options=--tsconfig-raw%3D%27%7B%22compilerOptions%22%3A+%7B+%22target%22%3A+%22ES5%22+%7D%7D%27)
[esbuild repl 0.15.8](https://hyrious.me/esbuild-repl/?version=0.15.8&mode=transform&input=const+a+%3D+7&options=--tsconfig-raw%3D%27%7B%22compilerOptions%22%3A+%7B+%22target%22%3A+%22ES5%22+%7D%7D%27)

I've checked the changelog but didn't find a related change. Is this an intended change?
If so, is there any difference between using `--tsconfig-raw='{"compilerOptions": { "target": "ES5" }}'` of `tsconfig` and `--target es5`?

refs https://github.com/vitejs/vite/issues/10167

**Comment by evanw** [comment]
Looks like this behavior change comes from https://github.com/evanw/esbuild/commit/3e2374cb011a47482b415f84716afa13ea88f3ce. However, this new behavior feels like the correct behavior to me. The `target` setting in `tsconfig.json` is supposed to be respected by esbuild unless it's overridden at the esbuild level. This has been the case for a while: https://github.com/evanw/esbuild/issues/277. Arguably the previous behavior of esbuild you're describing was a bug that was fixed.

**Comment by sapphi-red** [comment]
I agree this is a correct behavior. Thank you for the explaination!
