### ISSUE TITLE
Subpath patterns are not supported

### ISSUE THREAD

**Issue by sybereal** [evanw/esbuild#2569]
Subpath patterns, as documented [here](https://nodejs.org/docs/latest/api/packages.html#subpath-patterns), allow specifying patterns of files that can be imported in other packages. This is especially useful for packaging TypeScript. The exports object could look like this, for example:

```json
{
  "./*.js": {
    "types": "out/*.d.ts",
    "import": "out/*.js"
    }
}
```

If I import `foo/bar.js` in a package depending on this one, TypeScript will correctly look up the type information in `out/bar.d.ts`. esbuild, however, fails to resolve the import and exits with a message along the lines of `"foo/bar.js" is not exported`.

I've created a hopefully understandable minimal reproduction of this issue at https://github.com/sybereal/esbuild-export-pattern-repro.

**Comment by evanw** [comment]
I think this issue is a request for this feature: https://github.com/nodejs/node/pull/39635. That PR changed node's path resolution algorithm after esbuild implemented it, and esbuild's implementation now needs to be updated.

**Comment by sybereal** [comment]
Thank you for the amazingly quick resolution, much appreciated. esbuild has been a pleasure to work with.
