### ISSUE TITLE
Feature Request: onEnd return the time that the build took

### ISSUE THREAD

**Issue by danielperez9430** [evanw/esbuild#2572]
Hi good morning,

I was trying to see if it was possible to get the build time from a plugin, but it seems that if I do it with date objects in the `build.onStart` and `build.onEnd`, what I get back is the time it took for the plugin to execute.

In my case, I'm interested in knowing the total build time when I use the watch option.

**Comment by evanw** [comment]
Using `onStart` and `onEnd` seems to work fine. Here's an example:

```js
require('esbuild').build({
  entryPoints: ['index.js'],
  bundle: true,
  watch: true,
  plugins: [
    // Add a timer plugin
    {
      name: 'timer',
      setup(build) {
        let start
        build.onStart(() => { start = Date.now() })
        build.onEnd(() => { console.log(`Build took ${Date.now() - start}ms`) })
      },
    },

    // Slow down builds so that the delay is noticeable
    {
      name: 'slow',
      setup(build) {
        build.onLoad({ filter: /.*/ }, () => {
          return new Promise(r => setTimeout(() => r(), 100))
        })
      },
    },
  ],
})
```

If there are 2 files in the build then the log says it took around 200ms. Why isn't that working for you? Can you describe your problem in more detail?

**Comment by danielperez9430** [comment]
In my case when I do a build the terminal say "Done in 0.19s"
<img width="551" alt="image" src="https://user-images.githubusercontent.com/10388515/192096972-9a29008e-3537-4619-9dbe-d6ff00007e50.png">

But in watch mode with the extension using onStart and onEnd is 6ms

<img width="1136" alt="image" src="https://user-images.githubusercontent.com/10388515/192097171-0776d5bf-0691-423b-9ad0-789949221586.png">

That's why I'm not sure the time is right. Because I did exactly the same as you but with the new Date().getTime(). Am I get the same result at all

**Comment by evanw** [comment]
They are measuring different things. The first message is printed by Yarn and includes Yarn's overhead (which can be pretty sizable). The second message is measuring just the time taken by the build without Yarn's overhead, so it makes sense that it's smaller.

**Comment by danielperez9430** [comment]
Oh, that makes sense. Thanks for the clarification, because I didn't fully understand that difference of the time include yarn.

Thanks for the clarification!!!
