### ISSUE TITLE
How can I avoid the emission of __PURE__ annotations?

### ISSUE THREAD

**Issue by snuup** [evanw/esbuild#2578]
Cannot find any hint on how to configure esbuild such that those annotation do NOT occur in the output.

**Comment by evanw** [comment]
There are two ways:

* `--ignore-annotations`: https://esbuild.github.io/api/#ignore-annotations
* `--minify-whitespace`: https://esbuild.github.io/api/#minify

**Comment by snuup** [comment]
perfect, i use it with vite and this solved it:

    import { defineConfig } from "vite";
    export default defineConfig({
        esbuild: {
            ignoreAnnotations: true,
        }
    });
