### ISSUE TITLE
Missing Transform option: `mangle.eval`

### ISSUE THREAD

**Issue by masx200** [evanw/esbuild#2582]
Missing Transform option: `mangle.eval`

https://terser.org/docs/api-reference#mangle-options

```
Mangle options
eval (default false) -- Pass true to mangle names visible in scopes where eval or with are used.
```

**Comment by evanw** [comment]
If you want to run `eval` but not have it deoptimize the surrounding scope, you need to change it from a direct eval to an indirect eval. More information about this is here: https://esbuild.github.io/content-types/#direct-eval. Typically you just need to change `eval(x)` to `(0, eval)(x)` or similar.

**Comment by evanw** [comment]
I'm not planning on adding this feature. Instead, direct eval should be avoided (as described in the documentation).
