### ISSUE TITLE
tsconfig resolution mechanism

### ISSUE THREAD

**Issue by steabert** [evanw/esbuild#2583]
I had a question regarding how esbuild resolves the tsconfig file assiciated with an imported file. I ran into an issue with another tool https://github.com/esbuild-kit/tsx/issues/96, discovering that esbuild properly handles multiple TypeScript projects.

We wondered how esbuild does this. Does it look for a new `tsconfig.json` when a new file is imported that is not part of the files already included by the current `tsconfig.json` file, and then cache that?

**Comment by evanw** [comment]
For a given file, esbuild looks for the closest `tsconfig.json` file in a parent directories of that file. This behavior is similar to how npm locates the relevant `package.json` file.

**Comment by evanw** [comment]
I'm closing this issue because this question was answered.
