### ISSUE TITLE
Possibility to ignore `root package.json`s sideEffects field

### ISSUE THREAD

**Issue by KingSora** [evanw/esbuild#2587]
Good day!

I switched from rollup to esbuild for my e2e tests and its working really well. The only problem which came up was to ignore the `sideEffects` field in the projects root directory `package.json`. Currently esbuild will remove, "unused imports" because it thinks they are sideEffect free because of the `sideEffects` field in the package.json. 

I want to keep the `sideEffects` field there, because when I'm publishing my package (its a library) its needed, it should only be respected then though, and not for my "internal" code.

Previously I've been using rollups `rollup-node-resolve` plugin which implements the node resolve algo for it. Conveniently it has the option [`ignoreSideEffectsForRoot`](https://github.com/rollup/plugins/tree/master/packages/node-resolve/#ignoresideeffectsforroot) which does just that. - So I've been woundering whether esbuild also wants to add support for that. 

I'm aware of the `ignoreAnnotations` option, but I definitely wanna keep the `sideEffects` hint for external libraries.
I could also add a dummy `package.json` with `sideEffects: true` in my e2e tests folder, but that feels like a weird hacky workaround for my specific case. - Whats your opinion about this?

**Comment by evanw** [comment]
Any `sideEffects` annotations present in `package.json` are supposed to be correct. The `ignoreAnnotations` feature of esbuild is supposed to be a temporary measure to get things to build while the incorrect `sideEffects` annotations are fixed. If there are certain files that do have side effects, you can used the [more advanced form](https://webpack.js.org/guides/tree-shaking/#mark-the-file-as-side-effect-free) of the `sideEffects` annotation to list out those files that do have side effects.

**Comment by KingSora** [comment]
Thanks for the response @evanw! The files with sideEffects are only internal test files, which are never exposed. Thats why I wouldn't like them to be added to the sideEffects array.

I'll just use another `package.json` file to reflect the sideEffects in my e2e tests.. I just thought it might be a handy option for others where the usecase might be different.
