### ISSUE TITLE
Bundling creates random unused variables that throw syntax errors.

### ISSUE THREAD

**Issue by mqxf** [evanw/esbuild#2590]
I used esbuild by running this command on my backend:
`esbuild --bundle --minify --platform=node --outfile=main.js src/main.ts`
the output of which I would just put onto my backend server.
However, when running the compiled code it throws an error saying "SyntaxError: Identifier 'e' has already been declared"
After searching through the compiled code. I found randomly on the last line in the middle that there is a `let e;` statement
This e is unused, and removing it fixed the issue. But why was it there in the first place, it was placed when e was already defined, and threw errors, yet was never used after it was 'declared'
I don't know if this is a bug or what, but I don't want to have to find all the random variables that are created every single time I compile my program.

**Comment by mqxf** [comment]
Ok, here is the src folder, and the package.json
If you install the dependencies and run
`esbuild --bundle --minify --platform=node --outfile=main.js src/main.ts`
then try running main.js through 
`node main.js`
it should throw the syntax error. Not sure what exactly causes it so I don't know what a way of reproducing it is other than this
Also just running it when the variable is removed will throw an error since this is tagged as module instead, ignore that, its only the syntax error that matters

[source.zip](https://github.com/evanw/esbuild/files/9699276/source.zip)

**Comment by evanw** [comment]
Sorry, I couldn't reproduce this. I tried with the latest versions of all of those packages, which results in the following `package.json` file:

```json
{
  "dependencies": {
    "cookie-parser": "1.4.6",
    "email-validator": "2.0.4",
    "esbuild": "0.15.10",
    "express": "4.18.1",
    "jose": "4.10.0",
    "nodemailer": "6.8.0",
    "password-validator": "5.3.0",
    "salted-sha512": "1.0.2",
    "surrealdb.js": "0.5.0",
    "uuid": "9.0.0",
    "validator": "13.7.0"
  }
}
```

After unpacking the zip file, creating a `package.json` file with the above contents, running `npm install`, and then running `node_modules/.bin/esbuild --bundle --minify --platform=node --outfile=main.js src/main.ts`, the resulting `main.js` file appears to be fine. What versions of those packages are necessary to reproduce the issue?

**Comment by mqxf** [comment]
It seems correct, and I don't understand what the issue is or how it is produced. I'll try reinstalling a few things, and see if that fixes it.
