### ISSUE TITLE
"No native build was found" for `node-gyp-build`

### ISSUE THREAD

**Issue by r-token** [evanw/esbuild#2592]
I can successfully bundle my code, but some of my dependencies use [node-gyp-build](https://github.com/prebuild/node-gyp-build). At runtime, the code that uses that throws an error that says: `Error: No native build was found for platform=linux arch=x64 runtime=node abi=93 uv=1 libc=glibc node=16.16.0`. You can find that line of code [here](https://github.com/prebuild/node-gyp-build/blob/0078d7884dfeb0e708477b3e20bfc4f520c1e2f8/index.js#L60).

The error stack also references dependencies including [sodium-native](https://github.com/sodium-friends/sodium-native), [sodium-universal](https://github.com/sodium-friends/sodium-universal) and others. But I believe the problem lies with "node-gyp-build".

Is this something that can be addressed here within esbuild? Or does this necessitate a fix on node-gyp-build's side? I don't understand the actual issue here, and can't find much help online for it. So any clarity on this would be wonderful.

esbuild settings:
* platform: node
* target: node16
* bundle: true

**Comment by evanw** [comment]
Sorry, I don’t know what to say. I don’t know anything about `node-gyp-build` other than that it’s completely unrelated to esbuild. So I assume the solution to your problem has nothing to do with esbuild. Marking this issue as `unactionable` because there’s nothing I can do with it.

**Comment by r-token** [comment]
Totally acceptable. What brought me here was that marking the dependencies that use `node-gyp-build` as "external" and leaving them out of the bundling process resolves the issue. No worries though. Feel free to close this if you'd prefer.

**Comment by evanw** [comment]
Ok. I'm going to close this issue then.
