### ISSUE TITLE
Real life example for prod and dev?

### ISSUE THREAD

**Issue by arrowcircle** [evanw/esbuild#2599]
Hi! I am struggling to setup real life dev environment with esbuild.
For dev I want to have:
- live reload
- react routing crutch with dev server
- index HTML with proper links to js and css
For prod I am looking for:
- index HTML with proper digested links to js and CSS.

I was trying to implement this with @chialab/esbuild-plugin-html, but it makes index.html file with digest. 

Could someone please show an example with working solution of something like I want to implement?

**Comment by ludofischer** [comment]
You could take a look at [Vite](https://github.com/vitejs/vite), it uses ESbuild under the hood. I think what you are asking for is more complicated to build on your own than it looks.

**Comment by arrowcircle** [comment]
@ludofischer Thanks for the suggestion. What I am looking for is simple dev stack for SPA with esbuild. Maybe there are standard solutions, that just works out of the box for both dev and prod?

**Comment by evanw** [comment]
The things you are asking for are not things that esbuild does, so it's not possible to provide an example of how to do that with esbuild. I also recommend looking at Vite since it tries to do these things from what I understand. Closing this issue as out of scope.
