### ISSUE TITLE
Include .hbs files into a different folder

### ISSUE THREAD

**Issue by kaykhan** [evanw/esbuild#2601]
Hi, we use this in one of our projects however the final output does not contain the `src/templates/*.hbs` files and folder we need. 

In our webpack version we do someothing like this 

```
  plugins: [
        new CopyPlugin({
            patterns: [
                { from: 'src/templates', to: 'templates' },
            ],
        }),
```

Is it possible to replicate this functionality in esbuild? Unfortuantly ive not found anything in the doucmentation which looks like this. an example would be nice

**Comment by evanw** [comment]
I assume this would work: https://nodejs.org/api/fs.html#fscpsyncsrc-dest-options.

**Comment by kaykhan** [comment]
The problem is when i use esbuild to build my project i need that template folder to be in the root along with the minimified js.

if the fscpsync is still appropriate here, how could i include that in the esbuild config?

**Comment by evanw** [comment]
I was thinking something like this:

```js
esbuild.buildSync({ ... })
fs.cpSync(...)
```

**Comment by evanw** [comment]
Closing this issue because copying files into a folder is not something you need esbuild for. Node already provides a function to copy files into a folder.

**Comment by kaykhan** [comment]
I tihnk you misunderstood my question, esbuild does not package files like images or .hbs files  that are needed in a function. My problem was if a function is referencing an image or a .hbs file and it does not exist in the output folder /dist, /build how do we copy during build time those needed files that are not (.ts/.js etc)

**Comment by evanw** [comment]
If you want to copy `*.hbs` files from `src/templates` to `templates` as described in the original post, you can just do something like `cp src/templates/*.hbs templates` (or the equivalent JavaScript code).
