### ISSUE TITLE
Different classes names order on Windows and Linux

### ISSUE THREAD

**Issue by noneex** [evanw/esbuild#2603]
Hello, I'm using vite with esbuild. 
When I build on linux and windows the same project, I get different hashes in index.[hash].css file.
I compared those files and find out that some classes placed in different order.

Any idea why it happens? And is it possible to fix this?

**Comment by evanw** [comment]
That's probably a question for Vite, since they add a lot of stuff on top of esbuild. Unless you can provide an esbuild-only example that does this without Vite involved.

**Comment by evanw** [comment]
Closing this issue as it has remained unactionable with no follow-up.
