### ISSUE TITLE
minify functions under namespaces?

### ISSUE THREAD

**Issue by ash-hashtag** [evanw/esbuild#2606]
or is it a bad idea? I see that functions under a namespace doesn't minify even private ones(not exported out, just helper functions), is there any reason to it? and what about minifying private functions of classes too?

close this if it's dumb, I'm just using very long function names with namespaces

**Comment by hyrious** [comment]
`--minify-identifiers` should do the trick. [REPL Link](https://hyrious.me/esbuild-repl/?version=0.15.10&mode=transform&input=namespace+A+%7B%0A++function+a_very_long_long_long_long_long_long_func%28%29+%7B%7D%0A%7D&options=--loader%3Dts+--minify-identifiers)

**Comment by evanw** [comment]
You need to turn on minification for the output to be minified. Documentation for how to do that is here: https://esbuild.github.io/api/#minify. It's expected that function names are not minified if minification is disabled. Closing this issue as there is nothing to do here.
