### ISSUE TITLE
CJK characters are unnecessarily escaped

### ISSUE THREAD

**Issue by intrnl** [evanw/esbuild#2608]
It seems that esbuild always escapes CJK characters causing the output to become extremely verbose

[REPL](https://hyrious.me/esbuild-repl/?version=0.15.10&mode=transform&input=const+str+%3D+%27%E3%81%93%E3%81%93%E3%81%AF%E3%80%81%E3%82%A2%E3%83%BC%E3%82%AF%E3%82%B9%E5%90%84%E4%BA%BA%E3%81%AE%E8%B7%B3%E8%BA%8D%E8%83%BD%E5%8A%9B%E3%82%92%E8%A9%A6%E3%81%99%E3%83%88%E3%83%AC%E3%82%A4%E3%83%8B%E3%82%A2%E3%81%A7%E3%81%82%E3%82%8B%E3%80%82%E2%80%9C%E3%82%B8%E3%83%A3%E3%83%B3%E3%83%97%E2%80%9D%E3%80%81%E2%80%9C2%E6%AE%B5%E3%82%B8%E3%83%A3%E3%83%B3%E3%83%97%E2%80%9D%E3%82%92%E7%94%A8%E3%81%84%E3%81%A6%E3%80%81%E7%9B%AE%E6%A8%99%E5%9C%B0%E7%82%B9%E3%81%AB%E5%88%B0%E9%81%94%E3%81%9B%E3%82%88%E3%80%82%27%3B)

Input:
```
const str = 'ここは、アークス各人の跳躍能力を試すトレイニアである。“ジャンプ”、“2段ジャンプ”を用いて、目標地点に到達せよ。';
```

Output:
```
const str = "\u3053\u3053\u306F\u3001\u30A2\u30FC\u30AF\u30B9\u5404\u4EBA\u306E\u8DF3\u8E8D\u80FD\u529B\u3092\u8A66\u3059\u30C8\u30EC\u30A4\u30CB\u30A2\u3067\u3042\u308B\u3002\u201C\u30B8\u30E3\u30F3\u30D7\u201D\u3001\u201C2\u6BB5\u30B8\u30E3\u30F3\u30D7\u201D\u3092\u7528\u3044\u3066\u3001\u76EE\u6A19\u5730\u70B9\u306B\u5230\u9054\u305B\u3088\u3002";
```

**Comment by evanw** [comment]
https://esbuild.github.io/api/#charset

**Comment by intrnl** [comment]
Gotcha, I somehow missed that, sorry!
