### ISSUE TITLE
Feature request: Support minify with loader

### ISSUE THREAD

**Issue by matatk** [evanw/esbuild#2609]
I'm including some HTML files inside my bundled JS code as strings, by using the `text` loader. I would like to have the HTML minified, but it doesn't seem possible to combine a loader with a minifier. Someone on StackOverflow asked the [same question, but with CSS files instead](https://stackoverflow.com/q/69088135/1485308).

Please could you make it possible to perform minification whilst loading?

Thank you for this tool; I'm really enjoying the speed boost!

**Comment by evanw** [comment]
Sorry, I'm confused. HTML is not a [content type](https://esbuild.github.io/content-types/) that esbuild currently supports. There isn't a way to minify HTML with esbuild because esbuild is not a HTML minifier.

**Comment by matatk** [comment]
That's a good point! I'd forgotten that I'd put in an override to load HTML as plain text, sorry. Thanks for your quick reply.

However, CSS is a recognised content type—seeing as the person on SO made the same request for CSS, perhaps you could consider changing this issue to reflect that request instead? If not, I don't mind if you close this, of course.

**Comment by evanw** [comment]
You can do this with a plugin that uses a nested call to esbuild from within the plugin. Something like this (untested):

```js
let yourPlugin = {
  name: 'your-plugin',
  setup(build) {
    build.onLoad({ ... }, async (args) => {
      let css = await fs.promises.readFile(args.path)
      css = await esbuild.transform(css, { loader: 'css', minify: true })
      return { loader: 'text', contents: css }
    })
  },
}
```

Doing things this way gives you the flexibility of saying exactly what should happen in the nested call. For example, depending on your use case you may want the CSS to be bundled as well as minified.

**Comment by matatk** [comment]
@evanw this is very cool, thank you for the example code. If I hook this up to an external library, it may help me address my use case too. Either way, this neatly answers the CSS question, so I think this can be closed; I'll do that now, and will update the thread on StackOverflow. Cheers!
