### ISSUE TITLE
[Question] why do we need js and ts loaders when jsx and tsx loaders can parse js and ts respectively?

### ISSUE THREAD

**Issue by vijaybritto** [evanw/esbuild#261]
Sorry if I'm missing something pretty obvious but I don't understand why we need js and ts loaders when jsx and tsx can parse the same. 
Is it for speed?

**Comment by evanw** [comment]
No it's for correctness, not for speed. They don't have compatible syntax. `<a>b` is a legacy type cast for `ts` but is the start of a JSX element for `tsx`.

It's not something you can distinguish by trying both (`ts` and `tsx`) in this case and only picking the one that works out in the end. For example, `<a>1</a>/g` is something that's valid syntax for both loaders and means something different for each one. For the `ts` loader it should be `1 < /a>/g` and for the `tsx` loader it should be `<a>1</a> / g`. These may seem like edge cases but I want esbuild to be a robust tool that you can count on to work correctly.

**Comment by evanw** [comment]
I'm going to close this because I believe my post above answers this question.

**Comment by vijaybritto** [comment]
Thanks a lot for the explanation! I was not thinking about these at all

Thanks,
Vijay

________________________________
