### ISSUE TITLE
The `onLoad` `filter` should always filter fully resolved path to a file

### ISSUE THREAD

**Issue by KingSora** [evanw/esbuild#2616]
Good day!

Recently I've encountered a weird behvior regarding the `filter` for a `onLoad` callback. (https://github.com/remix-run/remix/pull/4130)
My code looks like this:
```js
build.onLoad({ filter: /\.css$/ }, () => {}); 
```
With this I would expect that each and every `.css` file will go through this `onLoad` callback. This is also the case unless its the entry point of a package. Packages like [`@fontsource/aguafina-script`](https://cdn.jsdelivr.net/npm/@fontsource/aguafina-script@4.5.10/package.json) have its entry point set as `main: "index.css"`. 

I'm not sure what causes this, and its possible that this behavior is implemented on purpose, but I would expect that the `filter` for the `onLoad` callback always filters the fully resolved path to a file.

**Comment by evanw** [comment]
I can't reproduce this. Here's what I tried:

```js
require('esbuild').build({
  stdin: {
    contents: `import '@fontsource/aguafina-script'`,
    resolveDir: __dirname,
  },
  bundle: true,
  plugins: [{
    name: 'demo',
    setup(build) {
      build.onLoad({ filter: /\.css$/ }, args => {
        return { contents: `console.log(${JSON.stringify('this is ' + args.path)})` }
      });
    },
  }],
})
```

That works fine, and produces output that looks like this:

```js
(() => {
  // node_modules/@fontsource/aguafina-script/index.css
  console.log("this is ./node_modules/@fontsource/aguafina-script/index.css");
})();
```

This is expected because what you are asking for should already be how esbuild works. You'll have to investigate more deeply on your end to figure out what's going on. I suspect it may have something to do with whatever you're using that's layered on top of esbuild.

**Comment by KingSora** [comment]
@evanw as always, thanks for the quick reply. I've communicated your answer to the remix team, I guess they're doing something with the path in another plugin.
