### ISSUE TITLE
BUG: Escape character classes escaped inside single quotes do not retain escaping

### ISSUE THREAD

**Issue by cristobal** [evanw/esbuild#2618]
After some debugging at work it came to my attention that character classes that are escaped inside a RegExp constructor with single quotes e.g. `new RegExp('\\d+')` loose context because the double backslash is removed and now it's only interpreted as `new RegExp('d+')`.

One of the reasons we use single quotes is due that we are using [prettier](message) as formatter 😂 

## Reproducing the problem
![Screenshot 2022-10-19 at 14 47 47](https://user-images.githubusercontent.com/155505/196695015-a6a7ac95-d95f-4736-bcba-369e2fcc77ef.png)

### Node
![Screenshot 2022-10-19 at 14 51 31](https://user-images.githubusercontent.com/155505/196695829-9f63604e-324b-4ced-8b70-5ecb41c1be98.png)

### Browsers
*Chrome*
![Screenshot 2022-10-19 at 14 51 56](https://user-images.githubusercontent.com/155505/196695902-bfd8983f-664b-4721-951c-5642e8198f68.png)

*Firefox*
<img width="233" alt="Screenshot 2022-10-19 at 14 52 47" src="https://user-images.githubusercontent.com/155505/196696118-3f410f5a-96f4-4853-9af7-96dbecc6e3fc.png">

*Safari*
![Screenshot 2022-10-19 at 14 51 02](https://user-images.githubusercontent.com/155505/196695692-347046a2-6dbf-4c34-b5c5-4d08f02380b1.png)

## Expected behaviour
Well the expected behaviour would be for esbuild to leave the regexp pattern inside the RegExp constructor untouched.

## Solution
If this is difficult to fix perhaps a note in the FAQ would be sufficient.

**Comment by hyrious** [comment]
This is not true, it should be caused by [shell escaping](https://www.gnu.org/software/bash/manual/html_node/Escape-Character.html), i.e. `\\` is interpreted as one `\` character, and `"\d"` in javascript is equal to `"d"`.

[REPL demo](https://hyrious.me/esbuild-repl/?version=0.15.11&mode=transform&input=new+RegExp%28%27%5C%5Cd%2B%27%29) of passing `'\\d'` to esbuild.
