### ISSUE TITLE
Array.isArray not be tree-shaking

### ISSUE THREAD

**Issue by Aimer-Fan** [evanw/esbuild#2620]
For example, the code like:
```js
// test/types.js
export const isArray = Array.isArray
export const isNumber = value => typeof value === 'number'

// test/index.js
import { isNumber } from  './types'
console.log(isNumber)
```

use `esbuild test/index.js --bundle --format=esm --outfile=out.js` the source code will be bundled to this:
```js
// out.js

// test/types.js
var isArray = Array.isArray;
var isNumber = (value) => typeof value === "number";

// test/index.js
console.log(isNumber);
```
the `isArray` is not be used, but still be bundled in result.

I try to use rollup and it returned this:

```js
const isNumber = value => typeof value === 'number';

console.log(isNumber);
```

I am not sure if this is a bug.

**Comment by lukeed** [comment]
https://esbuild.github.io/api/#pure

**Comment by hyrious** [comment]
`--pure` only automatically adds `/* @__PURE__ */` to **function-calls**, it [does not shake](https://hyrious.me/esbuild-repl/?version=0.15.11&mode=transform&input=const+isArray+%3D+Array.isArray%0Aconst+isNumber+%3D+value+%3D%3E+typeof+value+%3D%3D%3D+%27number%27&options=--tree-shaking+--pure%3AArray.isArray) assignments like above.

The known-pure-globals are here: https://github.com/evanw/esbuild/blob/master/internal/config/globals.go

> Rollup's known globals:
> https://github.com/rollup/rollup/blob/master/src/ast/nodes/shared/knownGlobals.ts

As a result, you can either

- Replace all `isArray()` in your code with `Array.isArray()` and add esbuild option `--pure:Array.isArray`
- Rewrite `isArray`'s difinition to `isArray = (a) => Array.isArray(a)`

**Comment by lukeed** [comment]
Linked for the comment syntax. If added, should do the trick. Haven’t used with Array.isArray specifically but many others. esbuild holding onto the code because there “may be side effects”

**Comment by Aimer-Fan** [comment]
> 

thanks, the second one is works for me.

**Comment by Aimer-Fan** [comment]
> Linked for the comment syntax. If added, should do the trick. Haven’t used with Array.isArray specifically but many others. esbuild holding onto the code because there “may be side effects”
> 
> ```js
> export const isArray = /* @__PURE__ */ Array.isArray;
> ```

I've tried it, but it still doesn't work.

`/* @__PURE__ */` is to comment function-calls, but `Array.isArray` is just a function.

**Comment by Aimer-Fan** [comment]
> `--pure` only automatically adds `/* @__PURE__ */` to **function-calls**, it [does not shake](https://hyrious.me/esbuild-repl/?version=0.15.11&mode=transform&input=const+isArray+%3D+Array.isArray%0Aconst+isNumber+%3D+value+%3D%3E+typeof+value+%3D%3D%3D+%27number%27&options=--tree-shaking+--pure%3AArray.isArray) assignments like above.
> 
> The known-pure-globals are here: https://github.com/evanw/esbuild/blob/master/internal/config/globals.go
> 
> > Rollup's known globals:
> > https://github.com/rollup/rollup/blob/master/src/ast/nodes/shared/knownGlobals.ts
> 
> As a result, you can either
> 
> * Replace all `isArray()` in your code with `Array.isArray()` and add esbuild option `--pure:Array.isArray`
> * Rewrite `isArray`'s difinition to `isArray = (a) => Array.isArray(a)`
> * Let esbuild add more things to the list

thanks, the second one is works for me.
