### ISSUE TITLE
tree shaking breaks function dependencies

### ISSUE THREAD

**Issue by ethangclark** [evanw/esbuild#2622]
Seeing this with `0.15.12` and `0.14.53`:

```ts
import { z } from 'zod';

const wrappedParse = (v: any) => z.string().parse(v);
wrappedParse('foo'); // no problem

const rawParse = z.string().parse;
rawParse('foo'); // TypeError: Cannot read properties of undefined (reading 'safeParse')

// (safeParse is another function from the zod library)
```

This works fine when I build using vite, which leads me to believe that this is being caused by esbuild.

Zod uses star imports and exports extensively, so perhaps this has something to do with those.

**Comment by evanw** [comment]
I can't reproduce this. Here's what I tried:

```ts
import { z } from 'zod'; // zod@3.19.1

const wrappedParse = (v: any) => z.string().parse(v);
console.log('wrappedParse', wrappedParse('foo')); // no problem

const rawParse = z.string().parse;
console.log('rawParse', rawParse('foo')); // TypeError: Cannot read properties of undefined (reading 'safeParse')
```

Bundling that with `esbuild --bundle` and running it with node gives the following output:

```js
wrappedParse foo
rawParse foo
```

What additional instructions are necessary to reproduce this problem?

**Comment by ethangclark** [comment]
Drat, sorry for the bad instructions. I'll try to get a better example.

**Comment by ethangclark** [comment]
Was using `zod@3.11.6`. Upgraded to `zod@3.19.1` and the problem disappeared.

Sorry for the trouble! (And thanks for your awesome work.)

**Comment by mattfysh** [comment]
@ethangclark this was due to you calling `parse` with no context, ie. these two snippets call the same function with different context:

```
myObj.fn()
```

```
const fn = myObj.fn
fn()
```

The reason your code was breaking is because the parse method was losing its context when being invoked without dot notation.

And the reason upgrading zod fixed it is because they now bind the methods automatically in the newer version
