### ISSUE TITLE
Use default loader if plugin onLoad does not specify

### ISSUE THREAD

**Issue by joshuakb2** [evanw/esbuild#2624]
Currently, when a plugin contains an `onLoad` callback and returns contents, if it does not specify a loader, esbuild defaults to JS. I suggest that the default loader should be used instead if the plugin does not specify. Here is my reasoning:

If the plugin knows what type of code it is producing, it should be able to explicitly specify the appropriate loader. However, plugins like `esbuild-plugin-replace` don't actually change the type of code, they just modify the code slightly before handing it off to esbuild. These plugins would rather allow esbuild to make the determination based on the file path, but because it will always default to JS, presently that plugin is forced to make a guess as to what loader is appropriate.

In my case, the replace plugin was choosing the "js" loader because my files have a "js" extension, even though my esbuild configuration contains `loader: { '.js': 'jsx' }`. This makes it impossible for me to use the plugin and use JSX in ".js" files at the same time.

This change appears to be a one-liner, but I would be happy to submit a pull request if you agree. Otherwise I'd love to know your thoughts about this.

**Comment by evanw** [comment]
Have you tried returning `loader: "default"` from your plugin?

**Comment by joshuakb2** [comment]
No I didn't! I'm having trouble finding any mention of that in the docs. But that does fix my problem, so I'll give `esbuild-plugin-replace` a pull request instead.

Thank you!
