### ISSUE TITLE
Esbuild loader problems.

### ISSUE THREAD

**Issue by ThiagoFacchini** [evanw/esbuild#2627]
Hi I'm writing a React / ThreeJS application, pretty simple in fact and I bumped into a weird issue with the loader configuration of ESBuild.

I'm basically trying to import mesh files to my application (.glb) and I'm getting what at first glance looks like it's an issue with the file, but after a little investigation I believe is has to do with the loader or it's configurations.

The error I get is:
![Screen Shot 2022-10-24 at 4 22 48 pm](https://user-images.githubusercontent.com/6634582/197481858-c37cceeb-ac04-46a9-980e-7522dca634c3.png)

So I initially thought it was something with the file, so I checked my network tab on dev tools and I found:
1 - The file apparently is loaded;
2 - The content of the file is simply wrong
![Screen Shot 2022-10-24 at 4 27 50 pm](https://user-images.githubusercontent.com/6634582/197482475-dbcd53fc-5bc6-42da-9f18-fe82eb3d9abf.png)

Additionally I check on my dist folder, and the file that is in there (head-X7LAW4TI.glb) looks correct.

Esbuild configurations:

```
esBuildDevServer.start(
    build({
        entryPoints: ['./index.tsx'],
        bundle: true,
        minify: false,
        sourcemap: true,
        incremental: true,
        // format: 'esm',
        platform: 'browser',
        target: ['chrome58', 'safari11'],
        loader: { 
            '.png': "dataurl", 
            '.hdr': 'dataurl', 
            '.jpg': 'dataurl',
            '.otf': 'dataurl',
            '.ttf': 'dataurl',
            '.glb': 'file'
        },
        plugins: [
            stylePlugin({
                postcss: {
                    plugins: [
                        postcssImport,
                        postcssNesting,
                        autoprefixer                        
                    ]
                }
            }),
            copyFilePlugin({
                source: ['../../public/client/reset.css'],
                target: ['../../public/client/dist'],
                copyWithFolder: false
            }),
            svgPlugin()
        ],
        outdir: '../../public/client/dist'
        // external: ["three/examples/jsm/controls/OrbitControls"]
    }),
    // To run the dev server a permission change is necessary:
    // chmod u+x node_modules/esbuild-dev-server-darwin-x64/devserver
    {
        port: '8080',
        watchDir: './',
        index: '../../public/client/index.html',
        staticDir: '../../public/client/',
        onBeforeRebuild: {},
        onAfterRebuild: {}
    }
)
```

Lastly, that's how I'm importing the file:
```
import headGLBURL from './head.glb']
...
...
...
const head = useLoader(GLTFLoader, headGLBURL)
```

I'm not really sure of what is happening but definitely the correct file isn't been loaded, neither I'm sure how to solve it.

Would appreciate any help and or support to solve it.
Thanks!

**Comment by evanw** [comment]
I agree that it looks like your web server is serving the wrong file. You'd probably have to reach out to whoever wrote the code for `esBuildDevServer.start()` to figure out what's wrong here. That code didn't come from this repo, so it's likely not possible for a change in this repo to be able to fix this problem. Maybe you're looking for this repo instead? https://github.com/Falldot/esbuild-dev-server

**Comment by ThiagoFacchini** [comment]
Thanks @evanw you are absolutely right. Please feel free to delete this thread.
