### ISSUE TITLE
`target` in tsconfig doesn't affect esbuild's runtime library

### ISSUE THREAD

**Issue by mengxinssfd** [evanw/esbuild#2628]
I found that after building the code, there is an extra `__spreadValues` function, which is written inside `var prop in b ||= {}`

```javascript
var __spreadValues = (a, b) => {
  for (var prop in b ||= {})
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a, prop, b[prop]);
    }
  return a;
};
```
It's using the `ECMAScript 2021 - (ES12)` feature, when I set the `target` to a version before ES12, it doesn't work

**Comment by mengxinssfd** [comment]
> Can you provide a self-contained code sample and esbuild configuration that will reproduce the problem?


You can look at this repository <https://github.com/mengxinssfd/esbuild-isuue--2628>.

Sorry, what I said earlier was not correct. `esbuild.build({target:'ES 2017'})` is useful.

It is accurate to use the `target` inside `tsconfig.json` without specifying `target:'ES version'`.

**Comment by heyheyhello** [comment]
@evanw I ran into this just now, the issue is that `||=` is used despite the tsconfig target asking for ES6. Here's a repro:

```
$ echo 'var a = { a:1 }; export default { b:2, ...a }' | npx esbuild --loader=ts --tsconfig-raw='{"compilerOptions": { "target": "es6" }}'

var __defProp = Object.defineProperty;
var __getOwnPropSymbols = Object.getOwnPropertySymbols;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __propIsEnum = Object.prototype.propertyIsEnumerable;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __spreadValues = (a2, b) => {
  for (var prop in b ||= {})
    if (__hasOwnProp.call(b, prop))
      __defNormalProp(a2, prop, b[prop]);
  if (__getOwnPropSymbols)
    for (var prop of __getOwnPropSymbols(b)) {
      if (__propIsEnum.call(b, prop))
        __defNormalProp(a2, prop, b[prop]);
    }
  return a2;
};
var a = { a: 1 };
export default __spreadValues({ b: 2 }, a);
```

Here's the docs that says tsconfig `target` will be respected: https://esbuild.github.io/content-types/#tsconfig-json

Using `--target=es6` will correctly transform `||=`

```
$ echo 'var a = { a:1 }; export default { b:2, ...a }' | npx esbuild --loader=ts --tsconfig-raw='{"compilerOptions": { "target": "es6" }}' --target=es6

...
for (var prop in b || (b = {}))
...
```

**Comment by heyheyhello** [comment]
This was tricky to debug because the docs say the default target is "esnext" if not specified, and we weren't specifying a target, so I expected that adding an explicit `target: "esnext"` to esbuild's config would do nothing.

There actually is a difference between implicit target esnext and explicit target esnext. Not sure if that's a bug or if that should be documented.

I did various combos of esbuild target vs tsconfig target to figure it out.

<img width="1391" alt="image" src="https://user-images.githubusercontent.com/44614862/202028812-1799c2f1-5a0d-4ce5-b640-74db9dd5d07c.png">

**Comment by evanw** [comment]
FYI I'm changing this so `target` in `tsconfig.json` doesn't affect any file, including esbuild's runtime library. You'll now have to use esbuild's `--target=es2021` setting for this.
