### ISSUE TITLE
How to translate the entire project directory?

### ISSUE THREAD

**Issue by makoven** [evanw/esbuild#263]
Sorry for the stupid question. Is it possible to use your utility to translate ALL project files from one format (ts/tsx), recursively, to a directory of js files with a similar structure,  as does the typescript or babel?

**Comment by evanw** [comment]
This is a bundler, and it's intended use case is for bundling. So what you're asking for is not the intended use case. But I believe it should basically be possible. If you need to do that you could either:

* Pass all of the files to esbuild explicitly. You can either list them out yourself like this:

    ```
    esbuild [file1] [file2] ... --outdir=out
    ```

    or use another command to generate the list:

    ```
    esbuild `find . \( -name '*.ts' -o -name '*.tsx' \)` --outdir=out
    ```

* Build something yourself that does this using esbuild's [JavaScript API](https://github.com/evanw/esbuild/blob/4093e1853aa7911559a6337cc9e889800f80e8e9/docs/js-api.md) or [Go API](https://pkg.go.dev/github.com/evanw/esbuild@v0.6.3/pkg/api?tab=doc).

* Use an existing solution that's designed for this such as the TypeScript compiler. I've also heard that [swc](https://github.com/swc-project/swc) is designed for this exact use case and is intended to be high performance (e.g. written in Rust) so it could be a good tool to check out.

**Comment by makoven** [comment]
@evanw Thank you, I thought so. Just confused by the slogan "Similar tools: Babel or TypeScript for transpiling"

**Comment by evanw** [comment]
Makes sense. Sorry about the confusion. Looks like this is a request for #109 then, so I'll close this as a duplicate.

**Comment by Hebilicious** [comment]
@evanw Referencing this community projects here : https://github.com/egoist/tsup as it seems to do what @makoven wanted and is built on top of esbuild and rollup.

**Comment by roelandmoors** [comment]
Just for reference. I use this to build my express server typescript files:
```
  "scripts": {
    "watch": "nodemon --watch server --ext ts --exec 'npm run build && npm run start'",
    "build": "esbuild `find server \\( -name '*.ts' \\)` --platform=node --outdir=build/server",
    "start": "node build/server/index.js",
    "clean": "rimraf build"
  },
```
(server is an npm workspace/folder for the express server)

**Comment by justingolden21** [comment]
`Invalid build flag: "-name"` when I try roelandmoors's build command

**Comment by izakfilmalter** [comment]
If you are using yarn you will need to change to the following:
```
    "buld": "esbuild $(find . \( -name '*.ts' -o -name '*.tsx' \)) --outdir=out",
```
