### ISSUE TITLE
External notation via colon: inconsistency?

### ISSUE THREAD

**Issue by dy** [evanw/esbuild#2635]
Just curious why `esbuild app.js --bundle --external:fsevents --platform=node` has `=` for platform and `:` for external?

**Comment by evanw** [comment]
This is already explained at the top of [esbuild's API documentation](https://esbuild.github.io/api/):

> If you are using the command-line API, it may be helpful to know that the flags come in one of three forms: `--foo`, `--foo=bar`, or `--foo:bar`. The form `--foo` is used for enabling boolean flags such as [`--minify`](https://esbuild.github.io/api/#minify), the form `--foo=bar` is used for flags that have a single value and are only specified once such as [`--platform=`](https://esbuild.github.io/api/#platform), and the form `--foo:bar` is used for flags that have multiple values and can be re-specified multiple times such as [`--external:`](https://esbuild.github.io/api/#external).

**Comment by evanw** [comment]
Closing this issue as this question is already answered in the documentation.
