### ISSUE TITLE
Stdin API with bundle option

### ISSUE THREAD

**Issue by ym-project** [evanw/esbuild#2638]
Hi!

I use esbuild with gulp. Gulp works with virtual files and passes changes through nodejs streams. Esbuild read files from file system by default so I use stdin api to receive changes from another stream (not from file system).

It works fine until I use `bundle` option. As I understand esbuild reads file content via stdin option. But when esbuild sees `import` or `require` statements, it starts to read files from file system to include imported file to bundle.

Can I prevent this behavior? For example esbuild can improve stdin api and pass list of files. And when esbuild search files, he will look for imported file from stdin list and then (if not found) from file system.

Thank you!

**Comment by evanw** [comment]
The way to customize path resolution in esbuild is to write a plugin.

**Comment by ym-project** [comment]
Hm... It's a good advice. Thank you!
