### ISSUE TITLE
Resolve tsconfig aliases when not bundling

### ISSUE THREAD

**Issue by SimTheFool** [evanw/esbuild#2639]
Hello !

I'm trying to use esbuild without bundling my entrypoints. I'm only compiling every source file of my project. My dev/build workflow is heavily relying on tsconfig path aliases. But those are not resolved when not bundling.

Is there a way to resolve them at compilation without bundle ? How should I proceed to write a plugin that override them in this context ?

I though I should go with `onResolve`, but only resolution of `entry-point` type are supplied if not bundling. What I need is to change resolution of '`import-statement` types. So should I rather go by `onLoad` callback and use node `fs` native module to parse and write my file import lines ? This seems a bit overkilled and prone to performance issue.

Thx for any insight about the way to go here ;)

**Comment by evanw** [comment]
Why not enable bundling and have your plugin return paths with `external: true`?

**Comment by SimTheFool** [comment]
@evanw  oh that's clever ! I'm glad I've ask, I'm turning around for hours -_- Thank you very much, I'll try that tomorrow

**Comment by SimTheFool** [comment]
It could work even if it's a bit painful to manage every cases. Though, the resulted bundled-not-really-bundled file is a bit bloated.
Here is what a none bundled file looks like:
```
"use strict";
import { readService } from "@adapters/readService";
import { getAllCharacters as getAllCharactersApplicative } from "@applicative/queries/getAllCharacters";
const getAllCharacters = () => {
  const get = () => getAllCharactersApplicative(readService);
  return {
    get
  };
};
export const queries = {
  getAllCharacters
};
```


And here is the bundles-not-really-bundled file:
```

**Comment by evanw** [comment]
Are you looking for `format: 'esm'`?

**Comment by evanw** [comment]
Closing this issue due to lack of a reply. I believe `format: 'esm'` should avoid the compatibility shim in this case.
