### ISSUE TITLE
Bundled express api increased in memory consumption by 150MB after bundle

### ISSUE THREAD

**Issue by Terkea** [evanw/esbuild#2642]
I have an express API written in typescript which used to be compiled with `tsc`. I wanted to move away from that as the output of the `tsc` still relied on the `node_modules` to be installed on the host machine.

This is where esbuild comes into place, with it I managed to reduce the size of the build by hundreds.

Now after I profiled both builds, the one using `tsc` and the one using esbuild I noticed that the esbuild version has a higher memory consumption than the `tsc` one.

I was wondering why is this happening and how could I possibly minimise the memory consumption of the project using esbuild.

This is the config that I am currently using to bundle the API

```js
    .build({
        entryPoints: [
            "server/start.ts"
        ],
        platform: "node",
        bundle: true,
        minify: false,
        platform: "node",
        logLevel: "info",
        sourcemap: false,
        target: "node12",
        loader: {
            ".html": "text",
            ".png": "file",
        },
        outdir: OUTDIR,
        plugins: [envPlugin],
        })
```

**Comment by evanw** [comment]
I have no idea, sorry. The best way for you to figure this out is probably to use a heap profiler to see what is taking up more memory. I’m marking this as `unactionable` because this is a request for debugging help, which is not what this issue tracker is for.

**Comment by markusbkk** [comment]
> I have an express API written in typescript which used to be compiled with `tsc`. I wanted to move away from that as the output of the `tsc` still relied on the `node_modules` to be installed on the host machine.
> 
> This is where esbuild comes into place, with it I managed to reduce the size of the build by hundreds.
> 
> Now after I profiled both builds, the one using `tsc` and the one using esbuild I noticed that the esbuild version has a higher memory consumption than the `tsc` one.
> 
> I was wondering why is this happening and how could I possibly minimise the memory consumption of the project using esbuild.
> 
> This is the config that I am currently using to bundle the API
> 
> ```js
>     .build({
>         entryPoints: [
>             "server/start.ts"
>         ],
>         platform: "node",
>         bundle: true,
>         minify: false,
>         platform: "node",
>         logLevel: "info",
>         sourcemap: false,
>         target: "node12",
>         loader: {
>             ".html": "text",
>             ".png": "file",
>         },
>         outdir: OUTDIR,
>         plugins: [envPlugin],
>         })
> ```

Sounds like a code splitting issue.
Is your tsc build maybe lazy loading whereas your esbuild one isn't?

**Comment by evanw** [comment]
Closing this because it has remained unactionable.
