### ISSUE TITLE
Using as a Go Library

### ISSUE THREAD

**Issue by phillvancejr** [evanw/esbuild#2643]
Hello, is it possible and if so how difficult is it to just use this as a Go library? For example if I wanted to be able to compile JSX from a go program, would it be simple to just import this and then call some functions? I've looked at the cmd src and it seems easy to follow so I could just rebuild myself from there, but I'm wondering if this was a planned feature and if there is some documentation on doing this. If not I'll just reverse engineer from the cmd/esbuild main.go and service.go files but I'm just checking if there is a simpler solution before I jump in. Thanks

**Comment by evanw** [comment]
There is already very extensive documentation about esbuild’s entire API: https://esbuild.github.io/api/. No reverse engineering is necessary.

**Comment by phillvancejr** [comment]
> There is already very extensive documentation about esbuild’s entire API: https://esbuild.github.io/api/. No reverse engineering is necessary.

Awesome, thanks a lot!
