### ISSUE TITLE
.pnp.js file in home directory turn on pnp mode in project

### ISSUE THREAD

**Issue by Reon90** [evanw/esbuild#2647]
~ .pnp.js project-folder

**Comment by evanw** [comment]
This is how Yarn is supposed to work. Here's a comment from someone who works on Yarn: https://github.com/evanw/esbuild/issues/2495#issuecomment-1227269139

**Comment by evanw** [comment]
Closing as by design.

**Comment by sverrejoh** [comment]
Right now esbuild breaks if the user by mistake has a `pnp.cjs/pnp.js` file in the home directory, which can happen easily by doing `yarn add something` in the wrong terminal window.

I wonder if esbuild could stop looking for pnp config files after finding a yarn.lock file, or if there could be an esbuild config flag to explicitly disable pnp (for projects not compatible with pnp).

**Comment by jlipsky14167** [comment]
> Right now esbuild breaks if the user by mistake has a `pnp.cjs/pnp.js` file in the home directory, which can happen easily by doing `yarn add something` in the wrong terminal window.
> 
> I wonder if esbuild could stop looking for pnp config files after finding a yarn.lock file, or if there could be an esbuild config flag to explicitly disable pnp (for projects not compatible with pnp).

Thank you @sverrejoh!!! I wasted hours finding the problem in a project untouched for months. I almost reinstalled the OS. Thank God I remembered this in a conversation with a partner.
