### ISSUE TITLE
Serverless incorrectly importing .js files when .mjs output is specified. 

### ISSUE THREAD

**Issue by jtoronto** [evanw/esbuild#2648]
Following the advice here: https://github.com/oieduardorabelo/top-level-await-in-aws-lamba-with-typescript

I added the following to my esbuild config. 
```
    format: 'esm'
    outputFileExtension: '.mjs'
    platform: 'node'
    target: 'esnext'   
```

The deployed function errors when invoked because it's unable to find it. 
```ERROR	Error: Cannot find module './lib/utility/error_throwing_function.js'```

If I just run `sls package`  and inspect the contents, this is what I find. 

`s_v1SNSErrorReporterTester.js`: 
```

var serverlessSDK = require('./serverless_sdk/index.js');
serverlessSDK = new serverlessSDK({
  orgId: 'REDACTED',
  applicationName: 'api',
  appUid: 'REDACTED',
  orgUid: 'REDACTED',
  deploymentUid: 'REDACTED',
  serviceName: 'api',
  shouldLogMeta: true,
  shouldCompressLogs: true,
  disableAwsSpans: false,
  disableHttpSpans: false,
  stageName: 'dev',
  serverlessPlatformStage: 'prod',
  devModeEnabled: false,
  accessKey: null,
  pluginVersion: '6.2.2',
  disableFrameworksInstrumentation: false
});

const handlerWrapperArgs = { functionName: 'api-dev-v1SNSErrorReporterTester', timeout: 6 };

try {
  const userHandler = require('./lib/utility/error_throwing_function.js');
  module.exports.handler = serverlessSDK.handler(userHandler.handler, handlerWrapperArgs);
} catch (error) {
  module.exports.handler = serverlessSDK.handler(() => { throw error }, handlerWrapperArgs);
}
```

Note that it's still trying to `require` it from its former `.js` extension, however if you do look in ./lib/utility of the package, `error_throwing_function` is indeed named `.mjs`. 

Is there another config option I'm missing or is this a bug?

**Comment by evanw** [comment]
I'm not sure? There is no esbuild setting called `outputFileExtension`. It looks like you are using some kind of esbuild wrapper, so you may want to ask this question of the people who made that wrapper instead.

In case it helps: even if you could get this to work, node doesn't allow you to `require()` a file ending in `.mjs` because CommonJS files aren't allowed to synchronously import ESM files. You would have to use `import()` instead of `require()` to do that.

**Comment by jtoronto** [comment]
Ahh yes you're right. I'm using the serverless-esbuild extension serverless plugin, so this is an issue I should raise with them. My mistake.
