### ISSUE TITLE
Option to turn off lowering for script inlining

### ISSUE THREAD

**Issue by jdanyow** [evanw/esbuild#2649]
Code like the following is lowered due to 58ac420581421b36c03649c0018286e5a8e58ffd *always lower template literals containing "</script>"*.

```js
const page = html`
<!DOCTYPE html>
<html>
  <head>
    <script>
      // script in tagged template literal introduces lowering...
    </script>
  </head>
  <body>
    ... lots of html ...
   </body>
</html>
```

This breaks compatibility with libs like [minify-html-literals](https://www.npmjs.com/package/minify-html-literals) because esbuild has lowered the template string to plain string syntax, making it impossible for minify-html-literals to find the tagged template literal.

Would it make sense to have an option to disable script inlining compatibility?

**Comment by hyrious** [comment]
What about enable [`--supported:template-literal=true`](https://esbuild.github.io/api/#supported)?

**Comment by jdanyow** [comment]
The lowering occurs despite template-literal being supported at line 12600.

https://github.com/evanw/esbuild/blob/97d6dbaff48210589f339dd80c2c372896dadf92/internal/js_parser/js_parser.go#L12594-L12609

**Comment by lydell** [comment]
Leaving this link here in case it helps: https://html.spec.whatwg.org/multipage/scripting.html#restrictions-for-contents-of-script-elements

**Comment by jdanyow** [comment]
@lydell right- esbuild is lowering to ensure the output can be the contents of a`<script>` element but this is not necessary when the output is not inlined, eg `<script src="/path/to/esbuild/output.js">`.

**Comment by evanw** [comment]
In the next release, esbuild will only do this if the `platform` setting is set to `browser` (the default value). Setting `platform` to `node` or `neutral` will disable this behavior. You will also be able to disable this behavior with `--supported:inline-script=false` (for JS) and `--supported:inline-style=false` (for CSS).

**Comment by jdanyow** [comment]
thank you @evanw!

**Comment by jdanyow** [comment]
thanks @evanw!
