### ISSUE TITLE
Runner to replace ts-node?

### ISSUE THREAD

**Issue by jeremiahlangner** [evanw/esbuild#2652]
I prefer ESBuild in favor of ts-node; can you work to add a runner to this repo with some default options, or with the options configured for ESBuild? Would love to have all this in one repo.

See folke's implementation: https://github.com/folke/esbuild-runner

**Comment by evanw** [comment]
Sorry but something like that is currently out of scope. There are also other projects that do this already that are based on esbuild. For example:

* https://github.com/esbuild-kit/tsx
* https://github.com/egoist/esbuild-register

You may want to consider using one of those instead.

**Comment by jeremiahlangner** [comment]
Cool. Still want one in the same repo.

**Comment by evanw** [comment]
Closing as out of scope.
