### ISSUE TITLE
short-circuit return not minifying properly

### ISSUE THREAD

**Issue by clshortfuse** [evanw/esbuild#2653]
Given:

````js
function set(foo) {
  if (foo === 1) return;
  let bar = foo;
  if (bar == null) return;
  if (bar === -1) return;
  let baz;
  if (foo === 2) return;
  const bux = foo;
  if (bux) return;
  if (foo === 2) {
    bar = 1;
  } else {
    bar = 0
  }
}
````

Minifies as: `function set(t){if(t===1)return;let e=t;if(e==null||e===-1)return;let n;t===2||t||(t===2?e=1:e=0)}`

````js
function set(r) {
    if (r === 1) return;
    let e = r;
    if (e == null || e === -1) return;
    let t;
    r === 2 || r || (r === 2 ? e = 1 : e = 0)
}
````

Should be: `function set(l){if(l!==1){let e=l;if(e!=null&&e!==-1){let f;l===2||l||(l===2?e=1:e=0)}}}`

````js
function set(t) {
    if (t !== 1) {
        let e = t;
        if (e != null && e !== -1) {
            let l;
            t === 2 || t || (t === 2 ? e = 1 : e = 0)
        }
    }
}
````

Is this a mistake, or is it because of `let` and brace scoping? Am I missing an option? (Just using `--minify`). I would rather use short-circuit returns in real code because I prefer less indentation.

**Comment by evanw** [comment]
> is it because of `let` and brace scoping?

Yes. This is why esbuild does the transformation you're looking for with `var` but not with `let`.

**Comment by clshortfuse** [comment]
I wonder if there's a way to safe way to implement this without side-effects. In most cases you can't because code could always do `typeof foo === 'undefined'` which could change code if you were to inverse it. But `return;` is different because there's no actual work being done in there. It's somewhat different.

I couldn't figure out a side-effect, but maybe I could be wrong. Still, I minified with author-side `{ }` instead of return and while shorter in plaintext, it came out larger with `gzip` and `brotli`. Compression library probably provide a dictionary key for `return;` since it comes up so often.

It could be explored if `return;` is unique enough to not cause side effects, but personally, it's lower priority for me with the gzip conclusion. Feel free to close this, if you want.

**Comment by evanw** [comment]
Thanks for investigating. I'm going to close this issue then given that it's a regression when the result is gzipped.
