### ISSUE TITLE
Expose default logger to JS API

### ISSUE THREAD

**Issue by hinell** [evanw/esbuild#2655]
```js
// esbuild.js
let esbuild = require("esbuild");
let logger  = esbuild.logger;
 
      esbuild.build({
          plugins: [ ... , Logger ]
      })
     .then()
```

**Comment by hyrious** [comment]
You can already do that with:

```js
const result = await esbuild.build({ … })
if (result.warnings)
	const output = await esbuild.formatMessages(result.warnings, { kind: 'warning', color: true })
	console.log(output)
}
if (result.errors)
	const output = await esbuild.formatMessages(result.errors, { kind: 'error', color: true })
	console.log(output)
}
```

**Comment by hinell** [comment]
Closing now, thanks. Probably need a separate issue to document this. Currently only described by the API here: 
https://github.com/evanw/esbuild/blob/ba4771032805f950982ab81cc099783bc6cd90c7/lib/shared/types.ts#L305-L318

**Comment by hinell** [comment]
@hyrious Thanks, but these don't report what output files were build. These functions also need to be documented:
https://github.com/evanw/esbuild/blob/ba4771032805f950982ab81cc099783bc6cd90c7/lib/shared/types.ts#L305-L318

**Comment by evanw** [comment]
This is now documented here: https://esbuild.github.io/api/#format-messages-api.
