### ISSUE TITLE
Invalid option on plugin, OOP

### ISSUE THREAD

**Issue by hinell** [evanw/esbuild#2656]
```js
// esbuild.js
class Foo {
    fieldFoo = "foo"
    name = "esbuild-foo-plugin"
    setup(){}
}

esbuild.build({ ..., plugins: [ new Foo() ] })


```
```bash
# in terminal
$ node esbuild.js
✘ [ERROR] [plugin esbuild-foo-plugin] Invalid option on plugin "esbuild-foo-plugin": "fieldFoo"
```
Esbuild is efying OOP paradigm. I'm creating a class that has basic Plugin methods compatible with esbuild and yet it complains that there are extra-fields (they obviously don't interfere with the plugin lifecycle).

I request to expose basic `Plugin` class in the JS api and check incoming pluings against it and supress this error. The workaround currently is to make these props private or non-enumerable:
```js
    #fieldFoo = "foo"
```

**Comment by evanw** [comment]
An esbuild plugin is an object with a `name` and a `setup` function. Unexpected property names on the plugin object are not permitted by esbuild, which allows for the possibility of safely expanding esbuild's plugin API in the future without conflicting with existing plugins.

If you need to adapt an object with more properties to work with this, you can do something like this:

```js
function adaptObjectToPlugin(obj) {
  return {
    name: obj.name,
    setup: obj.setup.bind(obj)
  }
}
```

**Comment by hinell** [comment]
@evanw It's a bad pattern for future plugin extension. I've used this already. It creates extra instance when we don't need it.

**Comment by hinell** [comment]
@evanw It's a bad pattern for future plugin extension. I've used this already. It creates an extra instance when we don't need it. Additionally, there is basically only one sensetive API provided by the context in the `setup(context){ ... }` where it matters and where one would expect changes. The rest has little to do with it unless you plan some grand extensions.

**Comment by hinell** [comment]
We have to follow basic [Liskov substitution principle
](https://en.wikipedia.org/wiki/Liskov_substitution_principle)

**Comment by hesxenon** [comment]
@hinell JS is a multi paradigm language; you don't have to use expensive and tricky classes to instantiate an object.

The point here is rather clear: unknown properties in plugin objects may interfere with esbuilds own future plans.

If you are hellbent on classes in a multi-paradigm prototype based language though you could probably use private fields since they are not enumerated.

**Comment by hinell** [comment]
> you could probably use private

Read the the issue, it already have said that.

> unknown properties in plugin objects may interfere with esbuilds own future plans.

This is unlikely to happen. Method `setup()` is called on undefined instance so it makes zero sense to enforce this protection.

**Comment by hinell** [comment]
> you could probably use private

Read the issue, I suggested the same thing.

> unknown properties in plugin objects may interfere with esbuilds own future plans.

This is unlikely to happen. Method `setup()` is called on undefined instance so it makes zero sense to enforce this protection.

**Comment by hesxenon** [comment]
> I suggestede the same thing

then there's your solution

> This is unlikely to happen

You're not the one deciding where esbuild goes in the future, are you?

Imagine `fieldFoo` is added to the esbuild plugin API a year from now. Suddenly your plugin would break, even though esbuild didn't make a breaking change.

So it's only sensible to make sure the objects esbuild receives look _exactly_ as expected, _without_ additional properties.

**Comment by hinell** [comment]
@hesxenon Well every major `esbuild` version may bring breaking changes.

**Comment by hinell** [comment]
@hesxenon Well every major esbuild version may bring breaking changes. Plugin writers should expect that. I'm personally writing few plugins that are compatible with `0.x.x` versions only. Othewise users are warned. Esbuild can ensure that plugins work by introducing versioned plugin api.

**Comment by hinell** [comment]
Will close it for now. If anyone find this proposal worth to follow - please comment and thumb up so Evan sees it.
