### ISSUE TITLE
[bug] Inaccessible methods from default exports in CJS

### ISSUE THREAD

**Issue by revelt** [evanw/esbuild#2657]
The ESLint is still in CJS so I decided to write plugin in TS and bundle it to CJS using `esbuild`. It didn't work outright! I had to resort to manually tweaking the `esbuild` produced files, specifically to replace `module.exports` line so that ESLint could access the methods from a default export:

![Screenshot 2022-11-04 at 19 00 56](https://user-images.githubusercontent.com/8344688/200056385-d71548bc-0fa2-4343-9f8b-e68018bdcb84.png)

## Minimal repro

Here's a minimal repo git: https://github.com/revelt/esbuild-bug — just follow the instructions.

I got [a real ESLint plugin](https://www.npmjs.com/package/eslint-plugin-test-num) on npm and it's been built from TS and ESM imports to CJS using `esbuild` and was [patched](https://github.com/codsen/codsen/blob/main/ops/scripts/fix-cjs.js) this way.

Thank you.

**Comment by hyrious** [comment]
Are you expecting esbuild to convert `export default a` in ESM to `module.exports = a` in CJS? This is not supported in esbuild. [Read more about default interop in the docs.](https://esbuild.github.io/content-types/#default-interop)

A workaround is you can create a wrapper that manually does `modules.exports = a`: [see it live](https://hyrious.me/esbuild-repl/?version=0.15.13&mode=build&modules=%5B%5B%22cjs.js%22%2C%22import+a+from+%27.%2Fesm%27%5Cn%5Cnmodule.exports+%3D+a%22%2C1%5D%2C%5B%22esm.js%22%2C%22export+default+%7B+a%3A+1+%7D%22%2C0%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22cjs%22%7D)

```js
import plugin from './plugin'
module.exports = plugin
```

Note: eslint 8 introduces a new config file that loads plugins in native ESM way,
https://eslint.org/docs/latest/user-guide/configuring/configuration-files-new
which should just work with your original plugin.

**Comment by revelt** [comment]
good point! thank you, closing
