### ISSUE TITLE
Minify: insert newlines instead of semicolons

### ISSUE THREAD

**Issue by wmertens** [evanw/esbuild#2659]
It would be nice to have an option to emit `\n` instead of `;` at the end of JS statements (except when followed by `[` or `(`).
The resulting code is just as small, and it is way easier to debug when you don't have access to the sourcemap.

**Comment by evanw** [comment]
Sorry but code formatting is out of esbuild's scope. If you want your output formatted with code formatting options like this, then you should run a real code formatter on your output after running esbuild.
