### ISSUE TITLE
Allow to set module alias via Node.js API

### ISSUE THREAD

**Issue by egoist** [evanw/esbuild#266]
## Use Case

I made a [library](https://github.com/egoist/maho) that uses esbuild as the bundler and I need to set alias to some generated files (whose output path is based on user configuration), that would make it easier to access in the library itself:

```js
// Instead of:
import { routes } from './some/path/to/.cache/generated-routes.js'
// I can do:
import { routes } from '@cache/generated-routes.js'
```

Frameworks can also use this option to define some built-in aliases like `@` to current directory so users won't have to do that in `tsconfig.json` or `jsconfig.json`

**Comment by evanw** [comment]
This sounds like a good use case for plugins. I believe the work-in-progress plugin API described in #111 should be able to address this need.

**Comment by ImedAdel** [comment]
Hey @evanw, I hope you're doing well :) Can `--define:K=V` be used to substitute `react` with `preact/compat` during parsing? (and therefore it can be used to substitute `./some/path/to/.cache` with `@cache` too) I tried doing that but it didn't work. I guess it's only for boolean values then?

**Comment by evanw** [comment]
Closing this because you should be able to do this with the plugin API. The API is documented here: https://esbuild.github.io/plugins/.

**Comment by PaulBGD** [comment]
Hello! This Issue comes up when Googling for making preact compat work, I wrote a little plugin if anyone wants an idea of how to make this work:

```js
const preactCompatPlugin = {
    name: "preact-compat",
    setup(build) {
        const path = require("path");
        const preact = path.join(process.cwd(), "node_modules", "preact", "compat", "dist", "compat.module.js");

        build.onResolve({filter: /^(react-dom|react)$/}, args => {
            return {path: preact};
        });
    }
}
```

If there was a way to just replace the dependency name I couldn't find one, but these seems to work _fine_ for now.

**Comment by osdevisnot** [comment]
I wonder if you can use NPM alias technique like below with esbuild:

https://github.com/developit/nextjs-preact-demo/blob/master/package.json#L18

cc: @PaulBGD

**Comment by iamtekeste** [comment]
Thank you for your help @PaulBGD and you are right that exactly how I ended up finding your solution 😄
