### ISSUE TITLE
New error when processing with closure compiler

### ISSUE THREAD

**Issue by DVLP** [evanw/esbuild#2660]
When bundling with closure compiler with a newer version of esbuild getting this error.
"Parse error. primary expression expected  for (var prop in b ||= {})"

This shorthand in the context of a for...in loop seems to be the problem `b ||= {}`

Newer esbuild generates this causing an error in closure compiler
```
  var __spreadValues = (a, b) => {
    for (var prop in b ||= {})
```

Older esbuild used to generate this - no error
```
var __spreadValues = (a, b) => {
    for (var prop in b || (b = {}))
```

**Comment by evanw** [comment]
This can happen if you don't use the `target` setting: https://esbuild.github.io/api/#target. Is that the problem here?

**Comment by DVLP** [comment]
Adding target es2020 helped, thanks!
