### ISSUE TITLE
How to transform "webpack.external" config in Esbuild?

### ISSUE THREAD

**Issue by tangzixuan** [evanw/esbuild#2662]
In webpack config, we may use config like:
```js
  externals: {
    react: 'React',
 }
```
How to config it  with esbuild,  who can give some help, thanks!

**Comment by hyrious** [comment]
You can do that with a plugin: https://github.com/fal-works/esbuild-plugin-global-externals

**Comment by tangzixuan** [comment]
Thank you very much!
