### ISSUE TITLE
after run esbuild, some class name is changed(add a number behind the class name)

### ISSUE THREAD

**Issue by xtutu** [evanw/esbuild#2664]
AAA  ===> AAA2
BBB ===> BBB3

How to keep the class name?

----
esbuild version:  0.15.13

----

build config:
```bash
async function buildWithBundle() {
    let result = await esbuild.build({
        entryPoints: ['./src/init.ts'],
        outfile: jsGameDir + "/init.mjs",
        bundle: true,
        sourcemap: true,
        minifyWhitespace: false,
        keepNames: true,
        preserveSymlinks: true,
        format: "esm",
        target: [
            "es2020",
        ],
        tsconfig: "./tsconfig.json", // default
        external: ['puerts', 'csharp', 'fs', 'path'],
        metafile: true,
    })
    // let text = await esbuild.analyzeMetafile(result.metafile)
    // console.log(text)
}
```

package.json
```json
{
    "name": "ts",
    "version": "1.0.0",
    "description": "ts project",
    "keywords": [],
    "type": "commonjs",
    "repository": {
        "type": "git",
        "url": ""
    },
    "license": "MIT",
    "scripts": {
        "build": "node ./run_esbuild.js"
    },
    "devDependencies": {
        "esbuild": "^0.15.13",
        "typescript": "^4.8.3"
    },
    "dependencies": {
        "long": "^5.2.0"
    }
}
```

**Comment by evanw** [comment]
Sometimes esbuild renames identifiers to avoid name collisions. Preserving the original names is not a guarantee that esbuild makes, nor is it even possible to do that in all cases. The only guarantee that esbuild makes is that `keepNames` preserves the value of the `.name` property.

If you are using direct `eval` and hitting a problem with name renaming, I recommend [not using direct `eval`](https://esbuild.github.io/content-types/#direct-eval). If you are running into problems with debuggers not respecting esbuild's renaming decision, then you should make sure that the source maps are being loaded into your debugger correctly (and if the debugger is ignoring the `names` field in the source map, then this is a bug with the debugger, not with esbuild).

Closing this as out of scope.
