### ISSUE TITLE
[ERROR] Invalid option in build() call: "tsconfigRaw" on Gitpod

### ISSUE THREAD

**Issue by zhyd1997** [evanw/esbuild#2666]
Open Storybook codebase on Gitpod:

```bash
git clone https://github.com/storybookjs/storybook.git # current commit hash: 02e4a69c9edcb563f0b8424584532771feab8597

yarn task --task compile --start-from=install 

yarn task --task sandbox --template react-vite/default-ts --start-from=install
```

and then you will see the error:

<details>
  <summary>Error Log</summary>
<pre>
 <code language="shell">
Error: Command failed with exit code 1: yarn build-storybook --quiet
✘ [ERROR] Invalid option in build() call: "tsconfigRaw"

    /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:244:12:
      244 │       throw new Error(`Invalid option ${where}: "${key}"`);
          ╵             ^

    at checkForInvalidFlags (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:244:13)
    at flagsForBuildOptions (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:435:3)
    at buildOrServeContinue (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1228:9)
    at Object.buildOrServe (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1173:9)
    at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2110:17
    at new Promise (<anonymous>)
    at Object.build (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2109:14)
    at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2284:67
    at MessagePort.<anonymous> (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2303:9)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)

✘ [ERROR] Invalid option in build() call: "tsconfigRaw"

    /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:244:12:
      244 │       throw new Error(`Invalid option ${where}: "${key}"`);
          ╵             ^

    at checkForInvalidFlags (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:244:13)
    at flagsForBuildOptions (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:435:3)
    at buildOrServeContinue (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1228:9)
    at Object.buildOrServe (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1173:9)
    at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2110:17
    at new Promise (<anonymous>)
    at Object.build (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2109:14)
    at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2284:67
    at MessagePort.<anonymous> (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2303:9)
    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)

@storybook/cli v7.0.0-alpha.48

info => Cleaning outputDir: /storybook-static
ERR! Error: Build failed with 1 error:
ERR! /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:244:12: ERROR: Invalid option in build() call: "tsconfigRaw"
ERR!     at failureErrorWithLog (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1624:15)
ERR!     at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1143:18
ERR!     at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1138:9
ERR!     at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:678:9
ERR!     at handleIncomingPacket (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:775:9)
ERR!     at Socket.readFromStdout (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:644:7)
ERR!     at Socket.emit (node:events:513:28)
ERR!     at addChunk (node:internal/streams/readable:315:12)
ERR!     at readableAddChunk (node:internal/streams/readable:289:9)
ERR!     at Socket.Readable.push (node:internal/streams/readable:228:10)
ERR!  Error: Build failed with 1 error:
ERR! /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:244:12: ERROR: Invalid option in build() call: "tsconfigRaw"
ERR!     at failureErrorWithLog (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1624:15)
ERR!     at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1143:18
ERR!     at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1138:9
ERR!     at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:678:9
ERR!     at handleIncomingPacket (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:775:9)
ERR!     at Socket.readFromStdout (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:644:7)
ERR!     at Socket.emit (node:events:513:28)
ERR!     at addChunk (node:internal/streams/readable:315:12)
ERR!     at readableAddChunk (node:internal/streams/readable:289:9)
ERR!     at Socket.Readable.push (node:internal/streams/readable:228:10) {
ERR!   errors: [
ERR!     {
ERR!       id: '',
ERR!       pluginName: '',
ERR!       text: 'Invalid option in build() call: "tsconfigRaw"',
ERR!       location: [Object],
ERR!       notes: [],
ERR!       detail: Error: Invalid option in build() call: "tsconfigRaw"
ERR!           at checkForInvalidFlags (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:244:13)
ERR!           at flagsForBuildOptions (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:435:3)
ERR!           at buildOrServeContinue (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1228:9)
ERR!           at Object.buildOrServe (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1173:9)
ERR!           at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2110:17
ERR!           at new Promise (<anonymous>)
ERR!           at Object.build (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2109:14)
ERR!           at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2284:67
ERR!           at MessagePort.<anonymous> (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2303:9)
ERR!           at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)
ERR!     }
ERR!   ],
ERR!   warnings: []
ERR! }
    at makeError (/workspace/storybook/scripts/node_modules/execa/lib/error.js:60:11)
    at handlePromise (/workspace/storybook/scripts/node_modules/execa/index.js:118:26)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async exec (/workspace/storybook/scripts/utils/exec.ts:45:7)
    at async runTask (/workspace/storybook/scripts/task.ts:283:24)
    at async run (/workspace/storybook/scripts/task.ts:417:28) {
  shortMessage: 'Command failed with exit code 1: yarn build-storybook --quiet',
  command: 'yarn build-storybook --quiet',
  escapedCommand: 'yarn build-storybook --quiet',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '@storybook/cli v7.0.0-alpha.48\n' +
    '\n' +
    'info => Cleaning outputDir: /storybook-static\n' +
    'ERR! Error: Build failed with 1 error:\n' +
    'ERR! /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:244:12: ERROR: Invalid option in build() call: "tsconfigRaw"\n' +
    'ERR!     at failureErrorWithLog (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1624:15)\n' +
    'ERR!     at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1143:18\n' +
    'ERR!     at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1138:9\n' +
    'ERR!     at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:678:9\n' +
    'ERR!     at handleIncomingPacket (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:775:9)\n' +
    'ERR!     at Socket.readFromStdout (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:644:7)\n' +
    'ERR!     at Socket.emit (node:events:513:28)\n' +
    'ERR!     at addChunk (node:internal/streams/readable:315:12)\n' +
    'ERR!     at readableAddChunk (node:internal/streams/readable:289:9)\n' +
    'ERR!     at Socket.Readable.push (node:internal/streams/readable:228:10)\n' +
    'ERR!  Error: Build failed with 1 error:\n' +
    'ERR! /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:244:12: ERROR: Invalid option in build() call: "tsconfigRaw"\n' +
    'ERR!     at failureErrorWithLog (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1624:15)\n' +
    'ERR!     at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1143:18\n' +
    'ERR!     at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1138:9\n' +
    'ERR!     at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:678:9\n' +
    'ERR!     at handleIncomingPacket (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:775:9)\n' +
    'ERR!     at Socket.readFromStdout (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:644:7)\n' +
    'ERR!     at Socket.emit (node:events:513:28)\n' +
    'ERR!     at addChunk (node:internal/streams/readable:315:12)\n' +
    'ERR!     at readableAddChunk (node:internal/streams/readable:289:9)\n' +
    'ERR!     at Socket.Readable.push (node:internal/streams/readable:228:10) {\n' +
    'ERR!   errors: [\n' +
    'ERR!     {\n' +
    "ERR!       id: '',\n" +
    "ERR!       pluginName: '',\n" +
    `ERR!       text: 'Invalid option in build() call: "tsconfigRaw"',\n` +
    'ERR!       location: [Object],\n' +
    'ERR!       notes: [],\n' +
    'ERR!       detail: Error: Invalid option in build() call: "tsconfigRaw"\n' +
    'ERR!           at checkForInvalidFlags (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:244:13)\n' +
    'ERR!           at flagsForBuildOptions (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:435:3)\n' +
    'ERR!           at buildOrServeContinue (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1228:9)\n' +
    'ERR!           at Object.buildOrServe (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1173:9)\n' +
    'ERR!           at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2110:17\n' +
    'ERR!           at new Promise (<anonymous>)\n' +
    'ERR!           at Object.build (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2109:14)\n' +
    'ERR!           at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2284:67\n' +
    'ERR!           at MessagePort.<anonymous> (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2303:9)\n' +
    'ERR!           at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)\n' +
    'ERR!     }\n' +
    'ERR!   ],\n' +
    'ERR!   warnings: []\n' +
    'ERR! }',
  stderr: '✘ [ERROR] Invalid option in build() call: "tsconfigRaw"\n' +
    '\n' +
    '    /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:244:12:\n' +
    '      244 │       throw new Error(`Invalid option ${where}: "${key}"`);\n' +
    '          ╵             ^\n' +
    '\n' +
    '    at checkForInvalidFlags (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:244:13)\n' +
    '    at flagsForBuildOptions (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:435:3)\n' +
    '    at buildOrServeContinue (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1228:9)\n' +
    '    at Object.buildOrServe (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1173:9)\n' +
    '    at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2110:17\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at Object.build (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2109:14)\n' +
    '    at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2284:67\n' +
    '    at MessagePort.<anonymous> (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2303:9)\n' +
    '    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)\n' +
    '\n' +
    '✘ [ERROR] Invalid option in build() call: "tsconfigRaw"\n' +
    '\n' +
    '    /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:244:12:\n' +
    '      244 │       throw new Error(`Invalid option ${where}: "${key}"`);\n' +
    '          ╵             ^\n' +
    '\n' +
    '    at checkForInvalidFlags (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:244:13)\n' +
    '    at flagsForBuildOptions (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:435:3)\n' +
    '    at buildOrServeContinue (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1228:9)\n' +
    '    at Object.buildOrServe (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:1173:9)\n' +
    '    at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2110:17\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at Object.build (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2109:14)\n' +
    '    at /workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2284:67\n' +
    '    at MessagePort.<anonymous> (/workspace/storybook/sandbox/cra-default-ts/node_modules/esbuild/lib/main.js:2303:9)\n' +
    '    at MessagePort.[nodejs.internal.kHybridDispatch] (node:internal/event_target:736:20)\n',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
</code>
</pre>
</details>

**Comment by hyrious** [comment]
This might be caused by [esbuild-register recently published a version that uses esbuild `build()` api](https://github.com/egoist/esbuild-register/commit/4d83bae16838a231fa830cfa14d77f92944700e2) while the storybook [is passing `tsconfigRaw` to that](https://github.com/storybookjs/storybook/blob/HEAD/code/lib/core-common/src/utils/interpret-require.ts), which is [not supported](https://esbuild.github.io/api/#tsconfig-raw) apparently. This issue has been fixed in the latest esbuild-register.

**Comment by zhyd1997** [comment]
@hyrious Thanks for your quick reply, I will check it later!

**Comment by zhyd1997** [comment]
Thanks @hyrious 

https://github.com/storybookjs/storybook/pull/19796
