### ISSUE TITLE
Using globally defined external dependencies with named and default exports

### ISSUE THREAD

**Issue by tim-hilt** [evanw/esbuild#2668]
Kind of related to #337 - We used Rollup before but I'm currently busy porting everything over to use esbuild.

One thing I struggeled with is the use of external dependencies, that are present on the `window`-object like so:

``` typescript
import * as Styled from "styled-components";
import * as React from "react";
import * as ReactDOM from "react-dom";

window["Styled"] = Styled;
window["React"] = React;
window["ReactDOM"] = ReactDOM;
```

I have prepared my esbuild-config.js to account for the global-externals like so:

``` js
  build({
    define: {
      global: "window",
    },
    external: ["styled-components", "react", "react-dom"],
    // ...
  }).catch(() => process.exit(1));
```

Now I need a plugin to tell esbuild to include the variables on `window` in the build. I tried out [fal-works/esbuild-plugin-global-externals](https://github.com/fal-works/esbuild-plugin-global-externals) and [a-b-r-o-w-n/esbuild-plugin-globals](https://github.com/a-b-r-o-w-n/esbuild-plugin-globals). The former is more configurable and seems to be better suited for esm-builds which I intend to use like so:

``` js
import { build } from "esbuild";
import { globalExternals } from "@fal-works/esbuild-plugin-global-externals";
import * as React from "react";
import * as Styled from "styled-components";
import * as ReactDOM from "react-dom";

  const globals = {
    "styled-components": {
      varName: "Styled",
      namedExports: Object.keys(Styled).filter((key) => key !== "default"),
    },
    react: {
      varName: "React",
      namedExports: Object.keys(React).filter((key) => key !== "default"),
    },
    "react-dom": {
      varName: "ReactDOM",
      namedExports: Object.keys(ReactDOM).filter((key) => key !== "default"),
    },
  };

  build({
    // ...
    define: {
      global: "window",
    },
    /// ...
    format: "esm",
    external: ["styled-components", "react", "react-dom"],
    plugins: [globalExternals(globals)],
  }).catch(() => process.exit(1));
};
```

The application builds successfully, but now when I try to open one part of the application that relies on the global externals being available, I see this in the browsers console:

```
Uncaught TypeError: import_styled_components2.default.div is not a function
```

When I take a look at it in the debugger, I see that `div` is actually inside of `import_styled_components2.default.default`. So the plugin didn't resolve the `default` export correctly. Both of the libraries suffer from this problem; default exports are not usable for me.

From my point of view this question would be better handled in a community forum or on the repos of the plugins themselves, but it's been more than a year that they received new commits. An issue that I created there didn't receive any answers.

Can you help me get this to work or point me to a place that's better suited, if this doesn't fit the issues here?

**Comment by evanw** [comment]
> Do you know if star-imports are tree-shakable?

Usually, yes. Caveats:

* Both files must be in the bundle
* Both files must use ESM
* The importing file must not access properties using any kind of indirection

If those conditions are met, then esbuild's bundler will automatically convert this:

```js
import * as foo from 'foo'
foo.bar()
```

into this during the bundling operation:

```js
import { bar } from 'foo'
bar()
```

**Comment by tim-hilt** [comment]
Thanks for the response! We might have some stuff in our codebase, that we can optimize then.

**Comment by evanw** [comment]
Closing this issue as this conversation did not receive additional replies.
