### ISSUE TITLE
Enum values are undefined instead of being incremented

### ISSUE THREAD

**Issue by JakubekWeg** [evanw/esbuild#2669]
I have a code:
```ts
const enum First {
    A,
}

const enum Second {
    B = First.A,
    C,
}

console.log(First.A, Second.B, Second.C);
```
It prints `0 0 1` which is fine, but as soon as I export `First` into `First.ts` so it is 
```ts
export const enum First {
    A,
}
```
And main.ts is 
```ts
import { First } from "First";

const enum Second {
    B = First.A,
    C,
}

console.log(First.A, Second.B, Second.C);
```
Now when I run it I'm getting `0 0 undefined`, but expected to get same results as above

**Comment by JakubekWeg** [comment]
Yeaaah, I understand, so I need to come up with a different way. 
Thank you

**Comment by visj** [comment]
In terms of correctness it should probably still be considered a bug, since it does not conform to the Typescript compiled output. @evanw
