### ISSUE TITLE
[esbuild-wasm] Unable to use `esbuild.initialize` in node environment even when wasmModule is provided

### ISSUE THREAD

**Issue by cytommi** [evanw/esbuild#2670]
Hi! I am attempting to use `esbuild-wasm` in node16.
  
I have the following code snippet 
```javascript 
    const wasmPath = path.join(
      path.dirname(require.resolve('esbuild-wasm')),
      '..',
      'esbuild.wasm'
    );

    try {
      const wasmModule = new WebAssembly.Module(readFileSync(wasmPath));
      await new Promise((resolve) => {
        esbuild
          .initialize({
            wasmModule,
            worker: false,
          })
          .then(() => {
            esbuild.transform("console.log('hello')").then((res) => {
              console.log(res);
              resolve(res);
            });
          });
      });
    } catch (err) {
      console.log(err);
    }
```
I was expecting this to work because per the documentation for `esbuild.initialize`, it seemed like providing a `wasmModule` should work for non-browser environments such as Node: 

```
The result of calling "new WebAssembly.Module(buffer)" where "buffer"
is a typed array or ArrayBuffer containing the binary code of the
"esbuild.wasm" file.

You can use this as an alternative to "wasmURL" for environments where it's
not possible to download the WebAssembly module.
```

However, I got the following error when running the above code: 
```
Error: The "wasmModule" option only works in the browser
```

Please let me know how I can resolve this so that I can use esbuild-wasm in node. Thank you!

**Comment by cytommi** [comment]
Seems like esbuild-wasm is not supported in node yet... https://github.com/evanw/esbuild/blob/4bd03f3d1426acd58db7bed999c34687825d4251/lib/npm/node.ts#L226-L235
Are there plans to support esbuild-wasm in Node? 
It would be nice to support this. Has great utility for bundling untrusted code leveraging Wasm's sandboxing capabilities

**Comment by evanw** [comment]
The `initialize` call is not necessary in node. Have you tried doing `require('esbuild-wasm').transform(...)` instead?

**Comment by evanw** [comment]
I'm closing this issue due to lack of a reply, and because I believe it's not a problem. The `esbuild-wasm` package already works in node (indeed it has always worked, since that's how esbuild's WebAssembly tests are run). You only need to call `initialize` in the browser though, not in node.
