### ISSUE TITLE
How to modify the output path?

### ISSUE THREAD

**Issue by takegine** [evanw/esbuild#2678]
How to modify the output path?
 I want to ` a/index.tsx ` output to ` dist/scripts/a.Js ` and ` a/index.less ` output to ` dist/styles/a.css`,
 I tried `outdir: 'dist',entryNames: 'scripts/[dir]' `, but the css directory is wrong.

If it needs a plugin to run, how should I write it？

**Comment by hyrious** [comment]
What about build twice?

**Comment by takegine** [comment]
> What about build twice?
> 
> * build({ entryPoints: ['a/index.tsx'], outfile: 'dist/scripts/a.js' })
> * build({ entryPoints: ['a/index.less'], outfile: 'dist/styles/a.css' })

`a/index.less` is import in  `a/index.tsx`, like this:
```typescript
// a/index.tsx
import React from 'react';
import './index.less';
export default ()=><div />

```

**Comment by takegine** [comment]
I hope to like this

```
├── src
│   └── a
│       ├── index.html
│       ├── index.tsx
│       └── index.less
├── dist
│   ├── layout
│       └── a.html
│   ├── scripts
│       └── a.js
│   ├── styles
│       └── a.css

```

**Comment by evanw** [comment]
One easy way to modify output paths is to use [`write: false`](https://esbuild.github.io/api/#write), which will return an array of files and their contents in memory. Then you can write those files wherever you choose.

**Comment by evanw** [comment]
Closing because this is already possible (via `write`).
