### ISSUE TITLE
Persistent disk cache to speed up rebuilds

### ISSUE THREAD

**Issue by jpike88** [evanw/esbuild#2679]
As per this comment by a member of the angular team (https://github.com/angular/angular-cli/issues/24240#issuecomment-1316889203), 

`There is about 25% improvement on cold builds for an ng new application. However, the 2nd build in Webpack is warm unlike esbuild which is cold. In this case the improvement is between 0~2% on a ng new application. This is because Webpack builder has persistant disk which is not yet implemented in the esbuild builder`

Is there an issue tracking this, and is this something you intend on trying to solve for?

**Comment by clydin** [comment]
`esbuild builder` in the above quote is the Angular CLI's experimental esbuild-based build system and was not meant to indicate esbuild itself. The Angular build system is comprised of both esbuild and non-esbuild related actions. In the context of caching, several of the actions that are performed during a build only need to occur once per an install of certain npm packages. Those type of actions are primary candidates for on-disk caching.  However, this does not currently require any changes to esbuild to implement.

**Comment by jpike88** [comment]
got it, thank you. obviously it's good news that the angular team is implementing it, angular is notable for having longest build times out of all the things I know of. if it can be esbuild-ified then that will be heaven
