### ISSUE TITLE
Add support for import assertions and non-JS module types

### ISSUE THREAD

**Issue by anil9973** [evanw/esbuild#2682]
**Feature Use Case**
Importing JSON, CSS, and HTML according to upcoming JavaScript and HTML standards.

CSS modules are standardized (In the HTML spec [here](https://html.spec.whatwg.org/multipage/webappapis.html#css-module-script)) and shipping in Chrome and Edge since v93. Firefox and Webkit were involved in the development of import assertions as a result of working out CSS modules, and are both currently implementing the prerequisites for CSS modules (constructible stylesheets and adopedStyleSheets).

This means that we'll be able to import JSON, CSS and HTML into JavaScript natively, and ideally in bundlers without any specific loaders (or perhaps a "web standard loader" that implements all web-native module types?):

```
import styles from './styles.css' assert {type: 'css'};

// or

const styles = await import('./styles.css', {assert: {type: 'css'}});
```

It is very helpful for **shadowDOM** web custom elements.

know more at
[web.dev/css-module-scripts](https://web.dev/css-module-scripts/)

**Comment by anil9973** [comment]
Rollup v3.3.0 add support for import assertions.

[ [v3.0] Basic support for import assertions #4646 ](https://github.com/rollup/rollup/pull/4646)

**Comment by evanw** [comment]
Import assertions are already supported. They are passed through to the output unmodified so that the browser can interpret them (unless you tell esbuild that they are unsupported, in which case esbuild will remove them):

```js
$ echo "import {default as foo} from './foo.json' assert {type: 'json'}" | esbuild
import { default as foo } from "./foo.json" assert { type: "json" };

$ echo "import {default as foo} from './foo.json' assert {type: 'json'}" | esbuild --supported:import-assertions=false
import { default as foo } from "./foo.json";
```

**Comment by anilkumarum** [comment]
Thanks for reply.
I issue is solved and it work perfect.
please close this issue.
