### ISSUE TITLE
`esbuild-wasm@0.15.14` closes with no output and exit code 130 with Node.js v19

### ISSUE THREAD

**Issue by merceyz** [evanw/esbuild#2683]
**Describe the bug**

Running `esbuild-wasm@0.15.14` with Node.js v19 closes without any output and exit code 130.

Ref https://github.com/nodejs/citgm/pull/905#issuecomment-1318883988

**To Reproduce**

```sh
docker run --rm -it node:19.1.0 bash
cd $(mktemp -d)
yarn init -2
yarn config set nodeLinker node-modules
yarn add esbuild-wasm@0.15.14
yarn esbuild --help
echo $?
```

**Comment by evanw** [comment]
Thanks for the report. I can reproduce this. Here is the specific error that happens:

```
globalThis.crypto = {
                  ^

TypeError: Cannot set property crypto of #<Object> which has only a getter
```

This problem doesn't happen in esbuild's code. It looks like this error is an unfortunate interaction between Go's WebAssembly shim code and some recent changes made by Node v19:

* The relevant Go code: https://github.com/golang/go/blob/cf93b25366aa418dea3eea49a7b85447631c2a1d/misc/wasm/wasm_exec_node.js#L25
* I'm assuming this is the problematic change in Node: https://github.com/nodejs/node/pull/44897

I'll see what I can do about this.
