### ISSUE TITLE
Feature request: Add escape hatch to mark everything exc. named packages as externs

### ISSUE THREAD

**Issue by ctjlewis** [evanw/esbuild#2684]
There is currently no way to make this happen, because `./*` will always include the entry-point, and there is no way to say "except the entry-point".

The reason this is needed is to bundle several entry-points and not bother inlining any `./` relative imports, but *do* inline stuff that's imported as a named package so it can ship with no dependencies.

Without a way to do this, we can only create huge standalone bundles, which is not logically consistent at runtime e.g. via `import.meta.url`:

```ts
// a.ts
import "./b"

// b.ts
console.log(import.meta.url)
```

The log will change if `a` is bundled without marking relative imports external and bundling `b` separately. 

If we can find a way to say, "only bundle the entry-point and inline named packages," we can have all of the good stuff without any logical issues. We are very close already, even just a way to hack in `external: ["!./myEntryPoint", "./*"]` to let esbuild know we area still asking it to bundle the entry-point would be amazing.

**Comment by evanw** [comment]
The plugin API is intended to be used when you want to customize path resolution beyond the built-in behavior: https://esbuild.github.io/plugins/#on-resolve. You can return `external: true` or `external: false` for a given path to set whether it should be considered external or not. Is that what you are looking for?
