### ISSUE TITLE
feature request: support target for deno

### ISSUE THREAD

**Issue by idanran** [evanw/esbuild#2686]
https://deno.land/manual@v1.28.1/node/npm_specifiers

"Deno 1.28 stabilizes support for npm specifiers, which allow you to use npm modules directly in Deno with a higher chance of compatibility than importing from CDN's, particularly if the modules depend on artifact files in their package."

**Comment by evanw** [comment]
Sorry, I'm not sure I understand what you're proposing. You just linked to some documentation but didn't actually say anything yourself.

Are you asking for esbuild to implement a clone of Deno's npm package installer inside esbuild itself? That's something that isn't in scope for esbuild. Being a package manager is out of scope. If you want to augment esbuild's path resolution so that packages are automatically installed for you, then you should write your own plugin to do that: https://esbuild.github.io/plugins/

**Comment by idanran** [comment]
> Sorry, I'm not sure I understand what you're proposing. You just linked to some documentation but didn't actually say anything yourself.
> 
> Are you asking for esbuild to implement a clone of Deno's npm package installer inside esbuild itself? That's something that isn't in scope for esbuild. Being a package manager is out of scope. If you want to augment esbuild's path resolution so that packages are automatically installed for you, then you should write your own plugin to do that: https://esbuild.github.io/plugins/
> 

Well, thanks.

**Comment by evanw** [comment]
Adding `deno` as a valid value for `target` could make sense. I can do that.

However, keep in mind that the purpose of the `target` setting is to enable or disable JavaScript syntax features for the target JavaScript VM. For example, versions of Deno older than v1.2 don't support the new `||=` operator, so adding e.g. `--target=deno1.0` to esbuild would let you tell esbuild to transpile `||=` to older JavaScript. The `target` setting doesn't have any effect on path resolution. Adding `--target=deno1.0` to esbuild wouldn't do anything about Deno-specific npm specifiers at all.

**Comment by idanran** [comment]
> Adding `deno` as a valid value for `target` could make sense. I can do that.
> 
> However, keep in mind that the purpose of the `target` setting is to enable or disable JavaScript syntax features for the target JavaScript VM. For example, versions of Deno older than v1.2 don't support the new `||=` operator, so adding e.g. `--target=deno1.0` to esbuild would let you tell esbuild to transpile `||=` to older JavaScript. The `target` setting doesn't have any effect on path resolution. Adding `--target=deno1.0` to esbuild wouldn't do anything about Deno-specific npm specifiers at all.

I see. Thank you.
