### ISSUE TITLE
Configure `.node` Loader for Vite

### ISSUE THREAD

**Issue by gyenabubakar** [evanw/esbuild#2691]
I am using Storybook with Svelte and Vite and I'm getting this error when I run the Storybook dev server:

<img width="1398" alt="Screenshot 2022-11-21 at 2 27 29 PM" src="https://user-images.githubusercontent.com/26672526/203080729-87db260e-992c-4f20-ba0c-5340dae6fa7e.png">

I think @evanw's [reply here](https://github.com/evanw/esbuild/issues/1051#issuecomment-806325487) can solve this but I'm not sure how to add this plugin to my Vite config.

**Comment by evanw** [comment]
It probably doesn’t make sense to include the `fsevents` package in a bundle meant for a browser, since it does file system events and the browser doesn’t have a file system. I would mark `fsevents` as external in that case: https://esbuild.github.io/api/#external.

**Comment by evanw** [comment]
I don't know anything about Vite, sorry. This is the esbuild repo. The Vite repo is here: https://github.com/vitejs/vite.
