### ISSUE TITLE
[Feature request] Variable blacklist for `minify`

### ISSUE THREAD

**Issue by hyoretsu** [evanw/esbuild#2693]
Add a variable name blacklist for `minify` option.

Reasoning? Normally you wouldn't need this. But I'm minifying a mod for Cookie Clicker, and its dumb developer created a function called `l()`, so it breaks things.

**Comment by evanw** [comment]
This shouldn't be necessary. When minifying, esbuild automatically avoids the names of global variables that your code uses. So if your code contains `l()` and there is no local variable called `l` (i.e. `l` is a reference to the global variable called `l`), esbuild's minifier will automatically avoid minifying something to the name `l`. If your code doesn't contain `l()` (or if `l` is a local variable), then esbuild's minifier is free to safely use the name `l` for things when minifying because it can't possibly conflict with your code.

**Comment by hyoretsu** [comment]
I have no reference to the `l()` function, but the game my mod is for uses it.

It won't conflict with my code, but it will with the game's source code.

**Comment by evanw** [comment]
Each of esbuild's [three supported output formats](https://esbuild.github.io/api/#format) runs in a local scope, so any minified identifiers that esbuild generates will not conflict with any global identifiers (as long as you are using the generated output correctly):

* `iife`: This wraps all code in a closure, which creates a local scope.
* `cjs`: The code must be run as CommonJS. All CommonJS loaders wrap the code in a closure at run-time, which creates a local scope.
* `esm`: The code must be run as ESM. In the browser that is done with `<script type="module">`. Other environments have different ways of doing this.

If you are using esbuild's output incorrectly (e.g. running `esm` without `type="module"`) then things will likely break. That's not a problem with esbuild though, and I'm not going to add features to esbuild to try to get that to work. Instead you need to make sure you are using esbuild's output correctly.

If you are running the generated code in a JavaScript environment that uses some other type of module format that esbuild doesn't support, then you should probably use esbuild's `iife` output format to make sure there's a local scope that prevents minified identifiers from conflicting with other things.

**Comment by hyrious** [comment]
Sounds like the game mod works by inlining others code directly in the source code? Then you may try using the 'iife' format to avoid variable leaks.

**Comment by hyoretsu** [comment]
That same situation could happen in the future, but that wasn't the problem that made my mod crash. Minifying with `platform: 'browser'` works just fine.
