### ISSUE TITLE
Typescript variables inaccessible in dev-tools console when built with --minify 

### ISSUE THREAD

**Issue by ryanlinnane** [evanw/esbuild#2699]
If you build with --minify and --sourcemap, you can find and place breakpoints on the respective `.ts` files in chrome devtools, and you can highlight variables in scope and get some information. However, if you open up the console on a breakpoint and try to act on a variable in scope or log it, it will be undefined. Instead you can only access the compiled .js scoped variables from within console.

Hope this helps. Let me know if you need any more information. Without the minify flag, I can log the typescript variables that are inscope by name.

**Comment by evanw** [comment]
Does any other JavaScript bundler make this work? This sounds like a problem with your JavaScript debugger, not with esbuild. All esbuild can do is provide source maps and it's already doing that.

**Comment by ryanlinnane** [comment]
Just tested with rollup (terser plugin) for minification and I get the same issue. Terser seems a bit more heavy handed ripping out some code even for optimizations, but you're absolutely correct. I'll close this, thank you!
