### ISSUE TITLE
Suppor for vue ?

### ISSUE THREAD

**Issue by Tazeg** [evanw/esbuild#27]
In a VueJS project I did : 

```bash
esbuild --bundle . --outdir=dist --minify
```
I got : 

```bash
src/main.js:3:16: error: File extension not supported: /home/jeff/gitclones/vuejs-project/src/App.vue
import App from './App.vue'
...
```

**Comment by evanw** [comment]
Since Vue has a custom syntax and compiler specific to their project, I consider replicating it inside esbuild to be out of scope for the goals of this project. This is the same reason that esbuild won't support Svelte (see #8).
