### ISSUE TITLE
Download dependencies

### ISSUE THREAD

**Issue by jakajancar** [evanw/esbuild#270]
It would be nice if esbuild could download “http(s)://...” imports (and probably cache them in ~/.cache/esbuild/) while bundling. Then it could be used completely on its own for building projects without external tooling, as long as you just use web-compatible imports and not require() or other node/npm stuff.

**Comment by evanw** [comment]
This will soon be possible by writing an esbuild plugin. You can follow issue #111 to get updates about the upcoming plugin API.

**Comment by evanw** [comment]
Plugin documentation has been released: https://esbuild.github.io/plugins/. You should be able to do this yourself now. There is even an example HTTP plugin as a starting point: https://esbuild.github.io/plugins/#http-plugin.
