### ISSUE TITLE
Exclude a function to be bundled

### ISSUE THREAD

**Issue by marvelbark2** [evanw/esbuild#2701]
How to use esbuild to bundle a specific function?
For example 
import { useEffect } from "react";
import { fetchContacts } from "../lib/contacts";

```js
export const data = /* @__PURE__ */ {
    runner: async () => {
        const contacts = await fetchContacts();
        return {
            contacts
        };
    }
}
export function X {...}
export default function index({ data }) {
    useEffect(() => {
        const term = process.env.TERM;

        console.log(term);
    }, [])
    return (
        <div className="w-screen h-screen flex items-center justify-center bg-gray-50">
            <div className="flex flex-col w-full p-10 mx-24 border border-dashed border-gray-500 space-y-6 items-center">

                <a href="/fes">Data</a>
                <a href="/api">TEST</a>
            </div>
        </div>
    )
}
```
I need only to bundle index function and X function, I tried to do this:

```js
const fs = require('fs');
const { join } = require('path');
const esbuild = require('esbuild');


const { default: DynamicImport } = require("@rtvision/esbuild-dynamic-import");

const fetchParams = (pageName) => {
    if (pageName.includes(':')) {
        return `window.fetchParams = () => {
            const pageName = '${pageName}'.split('/')
            const currentPage = window.location.pathname.split('/');
            const params = {};
            const searchParams = new URLSearchParams(window.location.search);
            for(let [key, value] of searchParams.entries()) {
                params[key] = value;
            }
            for(let i = 0; i < pageName.length; i++) {
                if(pageName[i].includes(':')) {
                    params[pageName[i].replace(':', '')] = currentPage[i + 1]
                }
            }
            return params;
          }`;
    } else return `
    window.fetchParams = () => {
        const currentPage = window.location.pathname;
        const searchParams = new URLSearchParams(window.location.search);
        const params = {};
        for(let [key, value] of searchParams.entries()) {
            params[key] = value;
        }
        return params;
      }`;
}


const getWSDataReload = (data, pageName) => {
    if (data && data.invalidate)
        return `const ws = new WebSocket('ws://'+ window.location.host + '/${pageName}.data')
        ws.onopen = () => {
        ws.onmessage = (e) => {
            const data = JSON.parse(e.data)
            if(data.type === 'change') {
                const deserializedData = new window.framework.DESERIALIZE(data.payload);
                const newElement = createElement(Component, {data: deserializedData.fromJSON()})
                hydrate(newElement, document.getElementById("${pageName}"))
            }
        }
        }`
}


const getHydrationScript = (filePath, pageName, data) => `
${process.env.NODE_ENV === "development" ? 'import "preact/debug";' : ""}
  import {hydrate, createElement, h} from "preact"
  import Module from "${filePath}"
   const Component = Module.default;
   const Parent = Module.Parent;
  document.getElementById("${pageName}").innerHTML = "";

  if(window.getData) {
    const data = window.getData();
    const deserializedData = new window.framework.DESERIALIZE(data);
    const Element = createElement( Component, { data: deserializedData.fromJSON() } );
    const W = h("span", {id: "${pageName}"}, Element);
    if(Parent) {
        const ParentElement = createElement(Parent, {}, W);
        hydrate(ParentElement, document.getElementById("root"))
    } else {
        hydrate(Element, document.getElementById("${pageName}"))
    }
    ${getWSDataReload(data, pageName)}
  } else {
    if(Parent) {
        const Element = createElement(Component)
        const ParentElement = createElement(Parent, {id: '${pageName}'}, Element);
        hydrate(ParentElement, document.getElementById("root"))
    } else {
        const Element = createElement(Component);
        hydrate(Element, document.getElementById("${pageName}"));
    }
   
  }

  ${fetchParams(pageName)}
`;

const file = join(process.cwd(), "src/test.jsx");
const configFileName = join(process.cwd(), "tsconfig.json");



function bundle() {
    (async () => {
        const subCode = getHydrationScript(file, "contacts", { invalidate: 1222 });
        const result = await esbuild.build({
            stdin: {
                contents: subCode,
                resolveDir: process.cwd(),
            },
            bundle: true,
            allowOverwrite: true,
            treeShaking: true,
            minify: false,
            keepNames: true,
            loader: { ".ts": "ts", ".tsx": "tsx", ".js": "jsx", ".jsx": "jsx" },
            jsx: "automatic",
            platform: "browser",
            plugins: [DynamicImport({ transformExtensions: ['.js'], changeRelativeToAbsolute: true, loader: "ts", filter: /lib\/.*\.ts$/ })],
            outdir: join(process.cwd(), "dist"),
            tsconfig: configFileName,
            metafile: true,
        })

        fs.writeFileSync(join(process.cwd(), "contacts.js"), subCode);

        if (result.metafile) {
            let text = await esbuild.analyzeMetafile(result.metafile, {
                verbose: true,
            })
            console.log(text)
        }
    })()
}
bundle()

```

Can you help me to fix this?

**Comment by evanw** [comment]
If you only want to export part of a file’s exports, you could try splitting it up into two files and then just bundle one of them. 

You could also create another file that does something like `export {X, default} from './the-file.js'` and bundle that file instead to select just a few exports from `the-file.js`.

**Comment by marvelbark2** [comment]
Thank you for your answer but this is the problem how to split this dynamically where "the-file.js" is dynamic str?

**Comment by marvelbark2** [comment]
> If you only want to export part of a file’s exports, you could try splitting it up into two files and then just bundle one of them.
> 
> You could also create another file that does something like `export {X, default} from './the-file.js'` and bundle that file instead to select just a few exports from `the-file.js`.

I tried to do that:
```js
export { Parent, default } from "./src/contacts/index.tsx";
```

But it does bundle everything, but when I comment the data doesn't not bundle it then the imports used on it wasn't included and this is exactly what I need to not bundle global import used on data function (Server function not supposed to be executed on browser also its module dep/imports even they're global imports)

**Comment by marvelbark2** [comment]
> > But it does bundle everything
> 
> Here is an example:
> 
> * **index.jsx:**
>   ```js
>   export const data = /* @__PURE__ */ {
>       runner: async () => {
>           const contacts = await fetchContacts();
>           return {
>               contacts
>           };
>       }
>   }
>   export function X() {/*...*/}
>   export default function index({ data }) {
>       useEffect(() => {
>           const term = process.env.TERM;
>   
>           console.log(term);
>       }, [])
>       return (
>           <div className="w-screen h-screen flex items-center justify-center bg-gray-50">
>               <div className="flex flex-col w-full p-10 mx-24 border border-dashed border-gray-500 space-y-6 items-center">
>   
>                   <a href="/fes">Data</a>
>                   <a href="/api">TEST</a>
>               </div>
>           </div>
>       )
>   }
>   ```
> * **entry.js:**
>   ```js
>   export {X, default} from './index.jsx'
>   ```
> 
> Run `esbuild entry.js --bundle --format=esm` on the above files and you get this:
> 
> ```js
> // index.jsx
> function X() {
> }
> function index({ data }) {
>   useEffect(() => {
>     const term = process.env.TERM;
>     console.log(term);
>   }, []);
>   return /* @__PURE__ */ React.createElement("div", { className: "w-screen h-screen flex items-center justify-center bg-gray-50" }, /* @__PURE__ */ React.createElement("div", { className: "flex flex-col w-full p-10 mx-24 border border-dashed border-gray-500 space-y-6 items-center" }, /* @__PURE__ */ React.createElement("a", { href: "/fes" }, "Data"), /* @__PURE__ */ React.createElement("a", { href: "/api" }, "TEST")));
> }
> export {
>   X,
>   index as default
> };
> ```
> 
> As you can see, `data` is not present in the bundle.

Thank you @evanw It's working, now I need Esbuild to exclude unused imports, Thanks 👍

**Comment by evanw** [comment]
Excluding unused imports would be invalid in general because imports are not lazily evaluated in JavaScript, so this is not something that esbuild does. The only way an imported file will be excluded is if all of its exports are unused and it can be detected to have no side effects (which is nothing special about excluding imports, it’s just normal dead code removal).

**Comment by marvelbark2** [comment]
Yes I see this is why I built a small import deps analyzer, for specific script to delete import line

**Comment by evanw** [comment]
Running something to modify the source code during the build before the source is processed by esbuild is possible. You could look into using an [`onLoad` plugin](https://esbuild.github.io/plugins/#on-load) to do this.

**Comment by marvelbark2** [comment]
Thank you so much @evanw
