### ISSUE TITLE
how to replace react because of global ?

### ISSUE THREAD

**Issue by takegine** [evanw/esbuild#2702]
I have separately inculcated react (umd) in html, and react has been linked to the global. However, when you write code in `src`, you will automatically import react if you use `useState` or somthing else. So that the output ESM contains the sentence `import {use state} from 'react'`. How can I replace all the `import * from 'react'` in the output file with `this. React`.
Declaring that `react` `global`  in `dts` is not a solution, because some dependency packages downloaded from npm also import react

**Comment by evanw** [comment]
You can write a plugin that swaps the `react` package for a module that does `module.exports = window.React`. An example plugin is in this thread: https://github.com/evanw/esbuild/issues/337#issuecomment-754840414

**Comment by takegine** [comment]
https://github.com/evanw/esbuild/issues/337#issuecomment-754840414 it is helpful, thanks
