### ISSUE TITLE
Exclude all devDependencies from the bundle

### ISSUE THREAD

**Issue by mustela** [evanw/esbuild#2713]
Hello there! Is there any way to exclude all the devDependencies from the final bundle? It seems they are all being added into it. 

Thanks!

**Comment by evanw** [comment]
The `devDependencies` property is not inspected by esbuild when bundling. Any dependency that is used will be bundled. If you want something to be excluded from the bundle, you should mark it as external: https://esbuild.github.io/api/#external. If you want all `devDependencies` to be external, you can read the value from `package.json` yourself like this: https://github.com/evanw/esbuild/issues/346#issuecomment-687116197.

**Comment by evanw** [comment]
I'm closing this issue because the question has been answered, and I do not intend to add a special feature to esbuild that does exactly this for you.
