### ISSUE TITLE
Do not replace this to (void 0)

### ISSUE THREAD

**Issue by yisar** [evanw/esbuild#2714]
This troubles me. Why should I replace `this` keyword, or is there any way I can keep `this` keyword.

**Comment by hyrious** [comment]
I guess you're using `this` in esm context? In es modules top level `this` is undefined by spec.

**Comment by bathos** [comment]
If curious to see where that “happens”: [GetThisBinding of Module Environment Records](https://tc39.es/ecma262/#sec-module-environment-records-getthisbinding).

(Though the transformation is sound, I’m not sure what motivates it — minification at least would seem to favor `this`.)
