### ISSUE TITLE
ESBuild doesn't handle MUI imports properly

### ISSUE THREAD

**Issue by eyalben** [evanw/esbuild#2716]
### Description 

The code within `@mui/icons-material` contains unresolvable imports.

It looks like the build works find, but internal imports sometimes resolves as `undefined` values instead of their original, which breaks the entire project.

See the equivalent MUI Open issue here:
https://github.com/mui/material-ui/issues/31835

### Steps to reproduce

You can use Vite (which uses ESBuild) to reproduce this issue easily.

1. Create a new React Typescript Vite project
2. Install `@mui/material` and `@mui/icons-material`
3. Import a material icon using: `import EmailIcon from "@mui/icons-material/Email"` and render it using `<EmailIcon />`
4. Run `yarn run dev`

### Current Behaviour

The `yarn run dev` works properly but when trying to browse to the website there's the following runtime exception:
`Uncaught TypeError: createTheme_default is not a function`

Debugging `mui` code using the borwser shows that the `createTheme` function resolved after the build is set to `undefined` instead of the exported function.

### Expected Behavior

`createTheme` function should be imported properly as part of the build process

### Temporary Fix

It looks like that the following import line doesn't resolves properly and breaks the build:
`import EmailIcon from "@mui/icons-material/Email"`

Importing the icons through the following line, solves the issue:
`import { Email as EmailIcon } from "@mui/icons-material"`

**Comment by eyalben** [comment]
Yep, in your example it looks like it resolves fine, I'll try to report that on Vite, thanks!

**Comment by stoplion** [comment]
Using Vite / esbuild with MUI. Getting these errors ALOT..
```
Uncaught TypeError: createTheme_default is not a function
    at Box.js:5:22
```
