### ISSUE TITLE
The package "x" wasn't found on the file system but is built into node.

### ISSUE THREAD

**Issue by jcolladokuri** [evanw/esbuild#2717]
We are using ESBUILD to bundle our NodeJs/TS project, I recently added a new package to our project(https://www.npmjs.com/package/applicationinsights). After this, a previously working build stopped working throwing the following error on a ton packages when running `npm run build`

![image](https://user-images.githubusercontent.com/20448042/206053737-221d0088-7df2-49f7-bf49-d7961efb1720.png)

Here is what I am using to bundle:
```
esbuild cli/index.ts lib/index.ts --bundle --minify --platform=node --outdir=dist --external:./node_modules/*
```

Here is what I am using to build after bundling:

```
esbuild.buildSync({
  entryPoints: ["./dist/file.js"],
  bundle: true,
  outfile: "./dist/file.js",
  allowOverwrite: true,
  format: "iife",
  globalName: "package_name",
  minify: true
});
```

I have been trying to figure out what is going on with these errors but have not gotten anywhere. IF it helps, the packages it is having trouble with are peerDependencies of peerDependencies:

```
$ npm why events
npm ERR! No dependencies found matching events

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2022-12-07T00_17_56_029Z-debug-0.log
```
```
npm why xml2js
xml2js@0.4.23 dev
node_modules/xml2js
  xml2js@"^0.4.19" from @azure/core-http@2.3.1
  node_modules/@azure/core-http
    @azure/core-http@"^2.2.3" from applicationinsights@2.3.6
    node_modules/applicationinsights
      dev applicationinsights@"^2.3.6" from the root project
```

In the above case, xml2js is what is pulling in events

Any pointers would be greatly appreciated.

**Comment by evanw** [comment]
You have already pasted the answer to your own question in your post:

> The package "util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "util" to do that, which will remove this error.

Following the text of the error message would give you this:

```diff
 esbuild.buildSync({
+  platform: "node",
   entryPoints: ["./dist/file.js"],
   bundle: true,
   outfile: "./dist/file.js",
   allowOverwrite: true,
   format: "iife",
   globalName: "package_name",
   minify: true
 });
```

That's for if you're bundling for node. If you aren't trying to bundle for node (e.g. you are bundling for the browser), then this isn't going to work. The `util` module is something that comes with node: https://nodejs.org/api/util.html. It's not part of the web API.

If this is the case, you'll have to swap out the import of the `util` module with some other package that is similar enough and works in the browser. How to do that is up to you. That's not something that esbuild does for you.

**Comment by jcolladokuri** [comment]
Thank you, this solved the issue. I initially thought I only needed to set the flag in my bundle command.
