### ISSUE TITLE
esbuild 0.16.0+ always replaces `process.env.NODE_ENV`

### ISSUE THREAD

**Issue by sapphi-red** [evanw/esbuild#2718]
```js
process.env.NODE_ENV = 'test'
const foo = process.env.NODE_ENV
```
is tranformed to
```js
"development" = "test"; // invalid syntax here
const foo = "development";
```
from esbuild 0.16.0. ([esbuild repl with 0.16.1](https://hyrious.me/esbuild-repl/?version=0.16.1&mode=transform&input=process.env.NODE_ENV+%3D+%27test%27%0Aconst+foo+%3D+process.env.NODE_ENV))

This was not happening in esbuild 0.15.18.

Using `--define:process.env.NODE_ENV=process.env.NODE_ENV` ([repl](https://hyrious.me/esbuild-repl/?version=0.16.1&mode=transform&input=process.env.NODE_ENV+%3D+%27test%27%0Aconst+foo+%3D+process.env.NODE_ENV%0A&options=--define%3Aprocess.env.NODE_ENV%3Dprocess.env.NODE_ENV)) seems to work.

**Comment by evanw** [comment]
Thanks for the report. This might be due to the `transform` API call now defaulting to the `browser` platform instead of the `neutral` platform. If I'm right, then setting `platform: 'neutral'` should be a quick way to get back to the old behavior. I'll look into this and #2719.
