### ISSUE TITLE
Allow arbitrary comments within dynamic imports and constructor calls

### ISSUE THREAD

**Issue by bluwy** [evanw/esbuild#2721]
## Background

`esbuild` currently supports special webpack comments within `import()` and `new Worker()` ([recently supported](https://github.com/evanw/esbuild/issues/2439)). Vite also supports special `/* @vite-ignore */` comments but esbuild currently strips them out, causing Vite warnings in ts, jsx, tsx files.

We're also experimenting with using esbuild for define replacements only which we found this issue: https://github.com/vitejs/vite/pull/11151

## Feature request

It would be nice to allow arbitrary comments within `import()` and `new Worker()`, or perhaps simply `/* @vite-ignore */` for now if it has performance implications.

## Testing

Here's a [stackblitz](https://stackblitz.com/edit/node-bkijwj?file=index.js) showing the current issue. Run `node index.js` in the terminal to execute the code.

## Related links

https://github.com/evanw/esbuild/issues/221

**Comment by evanw** [comment]
What are the specific syntax and semantics of `@vite-ignore`? Is this documented anywhere?

For example, Webpack comments follow the regular expression `/(^|\W)webpack[A-Z]{1,}[A-Za-z]{1,}:/` and are allowed anywhere in the token stream within the outer opening and closing parentheses. Webpack doesn't care if they get moved around inside that span so esbuild doesn't need to be precise about where the comments end up. Webpack comments are currently collected by esbuild and placed at the front inside the opening parentheses. This isn't a general-purpose mechanism both because tools may care where the comments end up (keeping them but moving them around might actually break things) and humans may be confused if the comments are moved away from the things they are commenting.

**Comment by bluwy** [comment]
We currently don't have them documented unfortunately but only from warnings generated because of something Vite can't analyze. They can be used like in these examples:

```ts
// comment should appear anywhere within the parentheses:
import(/* @vite-ignore */ dynamicVar)
import(dynamicVar /* @vite-ignore */) // it's rare someone does this, but works

// comment should appear within the second parameter, between `,` and `)`
new Worker(new URL('./path', import.meta.url), /* @vite-ignore */ dynamicOptions)
new Worker(new URL('./path', import.meta.url), dynamicOptions /* @vite-ignore */) // also rare someone does this, but works
```

We're using this regex: `/\/\*\s*@vite-ignore\s*\*\//`. The checks are done [here for dynamic imports](https://github.com/vitejs/vite/blob/a08ca078515b1f8b33eeb193d0c18eca05811271/packages/vite/src/node/plugins/importAnalysis.ts#L591-L595) and [here for worker options](https://github.com/vitejs/vite/blob/a08ca078515b1f8b33eeb193d0c18eca05811271/packages/vite/src/node/plugins/workerImportMetaUrl.ts#L74-L82).

**Comment by evanw** [comment]
Based on your comment, it sounds like a simple single rule to handle the `/* @vite-ignore */` comment would be for esbuild to always place it right before the closing `)`.

**Comment by bluwy** [comment]
I think to be accurate, it should be anywhere within the parameter boundary, so for cases like:

```js
import(/* @vite-ignore */ dynamicVar, { assert: { type: "json" } })
``` 

You could move it till the comma only:

```js
import(dynamicVar /* @vite-ignore */, { assert: { type: "json" } })
```

**Comment by bluwy** [comment]
It also looks like before https://github.com/evanw/esbuild/issues/2439, `/* @vite-ignore */` in `import()` used to work in Vite. Now the comment isn't preserved since v0.15.17 ([repro](https://stackblitz.com/edit/node-7y2jar?file=index.js)).

**Comment by ArnaudBarre** [comment]
This was changed in https://github.com/evanw/esbuild/commit/fdf184e63912e83f4d4efd80516e5d929e61cfe6

What is the benefice of preserving only Webpack comments when minify is off?

**Comment by evanw** [comment]
That commit was added to fix a bug where Webpack comments were not being preserved if they weren't in the leading position.

> What is the benefice of preserving only Webpack comments when minify is off?

This behavior only exists to support Webpack-specific comments in `import()` expressions (see #309).

**Comment by ArnaudBarre** [comment]
Would it be possible to keep other leading comments inside imports or add `@vite-ignore` to the regex?

**Comment by evanw** [comment]
Yes, that's what this issue is about (making this work for Vite's magic comments as well).
