### ISSUE TITLE
Provide ability to cancel build

### ISSUE THREAD

**Issue by benmccann** [evanw/esbuild#2725]
We wanted Vite to be able to cancel a build. We came up with a workaround for being able to do it that I'm sharing here, but we felt it was a bit too hacky to merge it at the moment and are going to hold off until the functionality is hopefully supported here

![Screenshot from 2022-12-07 13-37-11](https://user-images.githubusercontent.com/322311/206302015-8f9131d1-5ab2-4a16-a787-5883f9fb5dcc.png)

**Comment by evanw** [comment]
Hmm, this could get complicated with incremental builds. I'll have to think about the right API for this so heads up that this might not be added super quickly. Thanks for the report.

**Comment by evanw** [comment]
The new context object makes this straightforward, so I'm going to add this API there. The context object is primarily meant for incremental builds but you can use it even if you are only building once. That might look like this:

```js
let ctx = esbuild.context({
  // ...
})
try {
  setTimeout(() => ctx.cancel(), 500)
  return await ctx.rebuild()
} finally {
  // Remember to dispose of the context when you're done
  await ctx.dispose()
}
```
