### ISSUE TITLE
Path not found when importing from node_modules into project

### ISSUE THREAD

**Issue by srconklin** [evanw/esbuild#2726]
the require of normalize.css from within suitcss-base is looking for the dependency it the suitcss-base path INSTEAD of the root of node_modules. Can you advise on how to get past this? 

X [ERROR] [plugin postcss] ENOENT: no such file or directory, open 'C:\Users\scott\Projects\cbi\node_modules\suitcss-base\normalize.css\normalize.css'

    node_modules/suitcss-base/index.js:1:8:
      1 │ require('normalize.css/normalize.css');
        ╵         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/@deanc/esbuild-plugin-postcss/index.js:16:10:
      16 │     build.onResolve(
         ╵           ~~~~~~~~~

**Comment by evanw** [comment]
No. This error was produced by `esbuild-plugin-postcss`. You need to ask whoever wrote that code. I’m closing this issue as it’s from a plugin, not from esbuild.
