### ISSUE TITLE
JSON imports fail because transpiled files still import .json instead of .js

### ISSUE THREAD

**Issue by pierre-aurele-martin** [evanw/esbuild#2728]
Hello,

I'm implementing esbuild in our project and so far, this is great. The speed is on point ! I just have an issue with json import. 
Here is how to reproduce.

`src/test.ts`
```typescript
import * as tj from './testjson.json';

console.log('ok');
console.log(tj.a);
```

`src/testjson.json`
```json
{"a": 123, "b": "thisib"}
```

`esbuild.js`
```javascript
require('esbuild').build({
    entryPoints: ['src/test.ts', 'src/testjson.json'],
    bundle: false,
    outdir: 'build',
    format: 'cjs',
    plugins: [],
    incremental: true,
  }).then((result) => {
    console.log('then');
    result.rebuild.dispose()
    process.exit(0);
  }).catch(() => process.exit(1))
```

Then `node esbuild.js`. Ad you will see:
- `testjson.json` is transpile to `testjson.js` - (BTW, I can't call it test.json otherwise there is a name conflict...
- `test.ts`is transpile to `test.js` BUT with this code: `var tj = __toESM(require("./testjson.json"));`

And this file doesn't exist anymore...

My only solution so far is to convert json into .ts files but that seems a little strange to not be able to use json in our code.

I didn't find a lot of issues related to this in here so I'm opening an issue. Thanks for your help and the great tool !

EDIT1: One fix I just found is to set json loader as 'copy' in `esbuild.js`... But It just pop up new errors on json file. I still believe there is something wrong here :)

**Comment by evanw** [comment]
This isn’t really how esbuild is intended to be used. Import paths aren’t transformed at all when bundling is disabled. The easiest way to fix this is to enable bundling (`bundle: true`). That will produce a single file containing the TypeScript and the JSON.

**Comment by pierre-aurele-martin** [comment]
I don't want to bundle because that would make esbuild unusable for what I want to do... 

We have a mono repo with around ~10 services and ~30 libraries (packages). Bundling with esbuild on a single service generate a /build folder of around ~300mb (no assets, just code...). Versus 500kb w/o bundling.

Which make the latest Mac very slow when nodemon is watching this /build and doesn't make any sense overall. I don't want to bundle something I already got two paths away.

TSC was super slow so I try to have an implementation of esbuild where we can also us it to rebuild faster in dev mode. I understand that's not the first intended use for esbuild, but still the behaviour seem stranged to me.

**Comment by Inqnuam** [comment]
@pierre-aurele-martin what about "externals" ?

**Comment by pierre-aurele-martin** [comment]
I tried after seeing the size of my bundles but it was causing a load of issues... 

I can't remember if the issue was with esbuild and / or when I tried to run the result. I do remember it was struggling on nestjs and was packages.

I did managed to accomplish what I wanted with changing the json loader to copy. My point was that esbuild generate some code that's not valid. And I would be surprise to be the only one to use it with multiple entryPoints w/o bundling.

But I might be wrong :)

**Comment by evanw** [comment]
The easiest way to do it would be to just copy the file yourself. But if you really want to use esbuild to do this (transform JSON into JS and then rewrite the import from .json to .js), you'll need to enable bundling and then writing a plugin that specifies the behavior you want: https://esbuild.github.io/plugins/#on-resolve. Enabling bundling is still required for plugins to be able to intercept import paths, but you can have the plugin return `external: true` for your rewritten path so that esbuild doesn't bundle it.

**Comment by pierre-aurele-martin** [comment]
Thanks for the answer :) As stated, I made it work by simply copying the JSON files. 

Now I'm down the road and most of our services, that uses nestjs doesn't transpile properly through our CI/CD using Docker... There is something wrong between generating commonjs, docker and nestjs circular dependencies...

I got the exact same problem with swc so that's reassuring 👍  - I didn't figure out yet what's wrong or what should I do differently...

**Comment by evanw** [comment]
I'm closing this because esbuild is not intended to solve this use case.
