### ISSUE TITLE
Deno module attempts to download npm package from the wrong URL since 0.16.0

### ISSUE THREAD

**Issue by 0f-0b** [evanw/esbuild#2729]
https://github.com/evanw/esbuild/blob/8ef19fefc9bfdd28fab95dec3783d3f100f25e3e/lib/deno/mod.ts#L70

Should be `` `https://registry.npmjs.org/${name}/-/${name.replace('@esbuild/', '')}-${version}.tgz` ``.

**Comment by unvented** [comment]
Same issue here!

**Comment by evanw** [comment]
Whoops, sorry. Will fix.
