### ISSUE TITLE
[feature] JavaScript Plugins API: expose more info about require / import statements

### ISSUE THREAD

**Issue by Inqnuam** [evanw/esbuild#2734]
Currently the Plugin API when `onResolve` is called exposes some info about the import context:
```javascript
{
  path: './style.scss',
  importer: '/Users/inqnuam/Documents/apps/test/my-project/src/handlers/commons.ts',
  namespace: 'file',
  resolveDir: '/Users/inqnuam/Documents/apps/test/my-project/src/handlers',
  kind: 'import-statement',
  pluginData: undefined
}
{
  path: '@types/style.css',
  importer: '/Users/inqnuam/Documents/apps/test/my-project/src/handlers/commons.ts',
  namespace: 'file',
  resolveDir: '/Users/inqnuam/Documents/apps/test/my-project/src/handlers',
  kind: 'require-call',
  pluginData: undefined
}
```
It would be nice to have more info about the import/require clause, like if it is imported as alias, as default or it is nameless.
I'm able to do that but it requires to read the importer file content then execute some functions like typescript complier api or with Regex.
I guess you already have that info in your esbuild AST.

In my context It is actually useful when we work with css to determine if css classe names should be considered as global or local scoped.

Ex:

`style.scss`:
```css
.myButton {
  color:red;
}
```
When we need it as global class
importer
```js
import "./style.scss"
``` 
css output:
```css
.myButton {
  color:red;
}
```

as local scoped
importer
```js
import styles from  "./style.scss"
``` 
css output:
```css
.myButton_hash_d8f1 {
  color:red;
}
```

**Comment by evanw** [comment]
What file a module resolves to is not supposed to depend on what imports the importer uses. That’s not how JavaScript’s module system works. I recommend that you come up with some other way of doing this if you want to do this with esbuild. For example, you could import from `./style.scss?global` for global styles and then use `?global` in your plugin. 

I’m closing this issue as I do not plan to do this.
