### ISSUE TITLE
Since version 0.16.0 binary executable is broken when executing on a github action

### ISSUE THREAD

**Issue by spartDev** [evanw/esbuild#2740]
Since version 0.16.0 when running **esbuild** in a **github action** who use **ubuntu latest**, the binary executable is broken.
I think he doesn't find the right one.

```
> esbuild lambda/index.ts --bundle --outdir=build --platform=node --minify --target=node16 --external:aws-sdk

sh: 1: esbuild: not found
npm ERR! Lifecycle script `bundle` failed with error: 
npm ERR! Error: command failed 
```

When running the same command on a mac book pro, everything work well.

**Comment by evanw** [comment]
You need to provide a way to reproduce the issue. This is not enough information.

**Comment by Inqnuam** [comment]
Hello @evanw 
I can confirme that sometimes esbuild execution crash on GitHub actions (ubuntu-latest) with an error something like "unexpected end of file".
Re-running jobs fixe the issue.
Happened 2h ago but can't find the log anymore. will save it next time.

**Comment by evanw** [comment]
Sorry but that's still not enough information. To make progress, this issue would need the specific steps required to reproduce the problem. In the meantime I'm going to close this issue as there's no action I can take with it.
