### ISSUE TITLE
[Feature Request][Deno]: Support "NPM_CONFIG_REGISTRY" env variable

### ISSUE THREAD

**Issue by felipechierice** [evanw/esbuild#2744]
I have to use an alternative NPM registry in my machine because my proxy blocks the public NPM's registry https://registry.npmjs.org/, so I'm basically checking whether the `NPM_CONFIG_REGISTRY` env variable exists before fallbacking to the public one. In case anyone else needs support, here it is.

PR: #2743

**Comment by evanw** [comment]
Closing since #2743 was landed.
