### ISSUE TITLE
`React.forwardRef` is not annotated as PURE

### ISSUE THREAD

**Issue by Itherael** [evanw/esbuild#2749]
Currently, all the `jsx` calls using React are marked as `/* @__PURE__ */`, but not when the function is with `forwardRef` or any other top-level React function calls.

This source code: 
```jsx
export const examplePure = () => <div>hello</div>;
export const exampleReactForwardPure = React.forwardRef(examplePure);
```
Is transformed to:
```js
var examplePure = () => /* @__PURE__ */ jsx("div", { children: "hello" });
var exampleReactForwardPure = React.forwardRef(examplePure);
```

Expected output:
```js
var examplePure = () => /* @__PURE__ */ jsx("div", { children: "hello" });
var exampleReactForwardPure = /* @__PURE__ */ React.forwardRef(examplePure);
```

**Comment by hyrious** [comment]
"any other top-level React function calls" has nothing to do with the default pureness of jsx expressions. In other words, the `/*@__PURE__*/` annotation is added not for React, but for JSX (which can be implemented by any other library).

If you want to add pure annotations to some pieces of your code, you can add the annotation manually.

**Comment by Itherael** [comment]
Is there any way to automate this process on my side? I can't use the [pure API](https://esbuild.github.io/api/#pure) because React is not global.

**Comment by hyrious** [comment]
Unfortunately not. The last time I saw a similar request is done by using [acorn](https://github.com/acornjs/acorn) to add this comment to all top-level function calls in https://github.com/codemirror/buildhelper

**Comment by evanw** [comment]
Sorry but this is not how `/* @__PURE__ */` works. You have to put it in your source code if you want it to be there. Closing this as “won’t fix.”
