### ISSUE TITLE
When I upgraded to 0.16.x there was a error in jest test environment, is work on 0.15.x

### ISSUE THREAD

**Issue by noyobo** [evanw/esbuild#2750]
```
● Test suite failed to run

    Invariant violation: "Buffer.from("") instanceof Uint8Array" is incorrectly false

    This indicates that your JavaScript environment is broken. You cannot use
    esbuild in this environment because esbuild relies on this invariant. This
    is not a problem with esbuild. You need to fix your environment instead.
```

**Comment by evanw** [comment]
This indicates that your JavaScript environment is broken. You cannot use esbuild in this environment because esbuild relies on this invariant. This is not a problem with esbuild. You need to fix your environment instead.

**Comment by evanw** [comment]
This is a known bug with Jest: https://github.com/facebook/jest/issues/13227. It's up to you to work around it, as described in the error message that you copied and pasted.

**Comment by PixeledCode** [comment]
@noyobo I know its very late but did you ever found a solution to this?

**Comment by noyobo** [comment]
> [@noyobo](https://github.com/noyobo) I know its very late but did you ever found a solution to this?

It's been a long time and I now use vitest instead of jest. I forget the details of that time.
