### ISSUE TITLE
Deno: programmable option to set pre-downloaded esbuild binary/cache path

### ISSUE THREAD

**Issue by xnuk** [evanw/esbuild#2759]
Let's say with some code:
```javascript
// foo.ts

import { build, stop } from 'https://deno.land/x/esbuild@v0.16.9/mod.js'

if (import.meta.main) build({}).finally(stop)
```

If I run this with `deno run foo.ts`, with no additional permission, lots of permissions are required without explaining reasons:
```
✅ Granted read access to <CWD>.
✅ Granted env access to "ESBUILD_BINARY_PATH".
✅ Granted env access to "XDG_CACHE_HOME".
✅ Granted env access to "HOME".
✅ Granted read access to "/home/xnuk/.cache/esbuild/bin/@esbuild-linux-x64@0.16.9".
✅ Granted env access to "NPM_CONFIG_REGISTRY".
✅ Granted net access to "registry.npmjs.org".
✅ Granted write access to "/home/xnuk/.cache/esbuild/bin".
✅ Granted run access to "/home/xnuk/.cache/esbuild/bin/@esbuild-linux-x64@0.16.9".
```

This happens by the function `install()` and `installFromNPM()`, required to get binary path. Since cached path seems hard to configurable, I downloaded the binary myself, and changed result of `Deno.env.get('ESBUILD_BINARY_PATH')`, for less permission prompts:
```javascript
// foo.ts

import { build, stop } from 'https://deno.land/x/esbuild@v0.16.9/mod.js'

const monkey = () => {
  const original = Deno.env.get.bind(Deno.env)
  Deno.env.get = key =>
    key === 'ESBUILD_BINARY_PATH' ? '/path/to/esbuild' : original(key)
}
monkey()

if (import.meta.main) build({}).finally(stop)
```

```
✅ Granted read access to <CWD>.
✅ Granted run access to "/path/to/esbuild".
```

Solutions could be:
- Add `binPath` option in `InitializeOptions` and run like `initialize({ binPath: ... })`
- Or put it in `CommonOptions`
- Export `install()` function and receive some options to it
- Make new `setBinPath()` or something

**Comment by evanw** [comment]
There is already a programmable option to set a pre-downloaded esbuild binary/cache path:

```
$ ESBUILD_BINARY_PATH=./esbuild deno run your-code.js
```

**Comment by evanw** [comment]
I'm closing this as there is already an API for this. The way to do this is the same way that it works for node, and I'm not planning on changing that. This is also a pretty custom use case and isn't something I want to encourage, so it's not something that I'm documenting on the website or in the type definitions.
