### ISSUE TITLE
Invalid version with prerelease version of node

### ISSUE THREAD

**Issue by theoparis** [evanw/esbuild#2760]
It seems like esbuild doesn't seem to like prerelease suffixes on engine versions... It seems to be related to line 340 in `pkg/api/api_impl.go` - the version regex might not support `-xyz` suffixes...?

Also, it would be nice if I can also byasss the strict engine version checking feature similar to yarn's `--ignore-engines`.

```
│ Error: Transform failed with 1 error:
│ error: Invalid version: "20.0.0-pre"
```

**Comment by evanw** [comment]
Yes esbuild appears to be working as intended here.

**Comment by theoparis** [comment]
Alright my bad, I'll close this issue then.
