### ISSUE TITLE
CSS formatting issue with tailwind

### ISSUE THREAD

**Issue by dy** [evanw/esbuild#2763]
```
// x.js
import x from 'x.css'

// x.css
.x {
@apply hover:tw-bg-[rgba(255,255,255,50%)];
}
```

esbuild compiles that into
```
// x.css
.x {
@apply hover:tw-bg-[rgba(255, 255, 255, 50%)];
}
```
but compiling resulting css with tailwind produces error:
```
`hover:tw-bg-[rgba(255,` class does not exist. If `hover:tw-bg-[rgba(255,` is a custom class, make sure it is defined within a `@layer` directive.
```

**Comment by evanw** [comment]
Shouldn’t you be running CSS preprocessors such as tailwind on your code first before running esbuild?

**Comment by dy** [comment]
We have zillions of components with own CSSs, and tailwinding each of them produces tons of tailwind utility overhead...

**Comment by evanw** [comment]
Isn’t that a problem with tailwind though, not esbuild?

The input to esbuild is supposed to be actual CSS. It’s not esbuild’s job to support the union of all of the world’s CSS meta-syntaxes as input.

**Comment by dy** [comment]
Yeah, I totally relate, we use esbuild as resort from one hellish place. I [reported](https://github.com/tailwindlabs/tailwindcss/issues/10138) the issue, but tailwind authors are not always open to changes unfortunately.

**Comment by adamwathan** [comment]
As @evanw mentioned you should definitely be processing your CSS with Tailwind _before_ passing it into esbuild. Not sure exactly what your project looks like or how it's all set up but it doesn't seem right or useful to me to run your CSS through esbuild and _then_ through Tailwind.

> and take a deep breath of fresh air

Try and be a bit more mature than this, you're not incentivizing anyone to help you.

**Comment by dy** [comment]
We have multiple components (from [this discussion](https://github.com/tailwindlabs/tailwindcss/discussions/6612#discussioncomment-4430041)) and running tailwind for all of them is problematic, besides it produces a lot of utility overhead for each individual component. So pre-bundling css and running one single tailwind after is more meaningful.

**Comment by adamwathan** [comment]
Why not use `postcss-import` to import all of the CSS into one main file, run Tailwind on that file, and then run that through esbuild (if you even still need esbuild for this part at all)? That's how I would recommend bundling CSS before feeding it into Tailwind.

**Comment by dy** [comment]
Because esbuild already does that, we hoped to avoid stuffing scripts with tooling. Besides postcss is not as fast.

**Comment by adamwathan** [comment]
I created a test project and confirmed that if you use the modern commaless `rgb` syntax, esbuild doesn't change the formatting:

```css
.x {
  @apply hover:tw-bg-[rgb(255_255_255/50%)];
}
```

If it were me I would just have written this CSS in the first place though, to me there's not really any benefit to using Tailwind in this way:

```css
.x:hover {
  background-color: rgb(255 255 255/ 50%);
}
```

**Comment by dy** [comment]
The issue relates to not just rgb format, but also `bg-[linear-gradient(a,b,c)]`, `shadow-[a,b,c]` etc, so there's no workarounds. Thank you @adamwathan, we're going to try to remove `@apply` rules from css.
