### ISSUE TITLE
Entry point for package with "browser" mapping is ignored

### ISSUE THREAD

**Issue by linasburneika** [evanw/esbuild#2765]
Hello, I found a specific package which has both nodejs and browser as an output, however esbuild latest version always takes nodejs even if platform:"browser" is configured.

@azure/storage-blob@12.12.1

https://github.com/Azure/azure-sdk-for-js/blob/main/sdk/storage/storage-blob/package.json

**Comment by evanw** [comment]
Can’t run the code right now but I’m assuming the problem is that you’re using the CommonJS version of this package (via `require`) and this package doesn’t configure a browser override for the `"./dist/index.js"` path. That’s problem with the package, not with esbuild.

**Comment by linasburneika** [comment]
I added mainFields: ["browser", "module", "main"] to esbuild configuration and now it bundles the browser version of storage-blob as expected.

I was using older version of esbuild and recently updated to the latest. I had `mainFields` not defined before (but platform set to browser), looks like there are changes in defaults of config and it doesn't correspond to the docs anymore: https://esbuild.github.io/api/#main-fields

**Comment by evanw** [comment]
This is documented in detail [here](https://esbuild.github.io/api/#platform):

> When the platform is set to `browser` (the default value):
>
> * The [main fields](https://esbuild.github.io/api/#main-fields) setting is set to `browser,module,main` but with some additional special behavior. If a package supports `module` and `main` but not `browser` then `main` is used instead of `module` if that package is ever imported using `require()`. This behavior improves compatibility with CommonJS modules that export a function by assigning it to `module.exports`.

The documentation also contains [this](https://esbuild.github.io/api/#main-fields), which describes what this package isn't doing:

> For package authors: If you want to author a package that uses the `browser` field in combination with the `module` field to fill out all four entries in the full CommonJS-vs-ESM and browser-vs-node compatibility matrix, you want to use the expanded form of the `browser` field that is a map instead of just a string:
>
> ```json
> {
>   "main": "./node-cjs.js",
>   "module": "./node-esm.js",
>   "browser": {
>     "./node-cjs.js": "./browser-cjs.js",
>     "./node-esm.js": "./browser-esm.js"
>   }
> }
> ```

I'll try to add more documentation to make this more clear.
