### ISSUE TITLE
Remove all `export` statements from bundle

### ISSUE THREAD

**Issue by WorriedArrow** [evanw/esbuild#2768]
Hi,
I was just wondering if there is any way to remove this kind of code at the end of builds with esbuild:
![image](https://user-images.githubusercontent.com/81983357/209261118-5d52de0c-f945-486c-b60b-766b0bf644f1.png)
I have exported it, but I only want to use it locally across source files, not export it in the build.

Thanks in advance!

**Comment by evanw** [comment]
If you don’t want it to be exported, then don’t export it. If you only want your bundle to have certain exports but don’t want to change your current code, then you can make another file to use as the entry point to your bundle that only re-exports the symbols you want to be exported, and bundle that file instead.

**Comment by WorriedArrow** [comment]
Sounds good.
One question: Is there any way to prevent TypeScript from freaking out because I didn't export it from my entry point, or would that not be possible?

**Comment by WorriedArrow** [comment]
Also, to clarify my original post, I want **no** exports, not just some of them.

**Comment by evanw** [comment]
Then just don’t put any exports in the entry point. The way to mark a TypeScript file as ESM without exporting anything is with an `export {}` statement (an empty export clause). The reason for this is that the TypeScript compiler still needs to see some ESM import/export syntax for it to consider the file an ES module.

**Comment by WorriedArrow** [comment]
This would work, except it still generates the export statements.
![image](https://user-images.githubusercontent.com/81983357/209279625-5d257f16-7b98-46b8-8b68-c8b0df9f850b.png)
Is there any way to totally eliminate the `export` statement from build?

(Context: I can't put my code in the module scope)

**Comment by evanw** [comment]
It might help to provide a code sample that demonstrates the problem. If you use esbuild to bundle a file without any exports, then you shouldn’t get any exports.

**Comment by WorriedArrow** [comment]
Here's my entry point code:
```js
import { fadeIn, fadeOut } from "./utils/animations";
import addContent from "./utils/pluginUI";
import def from "./api/def";
import { uploadPlugin } from "./utils/pluginUploading";
import defWP from "./utils/webpack";
import load from "./loader";
import addDecorations from "./utils/windowDecorations";

export const OpenLoader = def();
export const DiscordNative = window["DiscordNative"];
export const WebpackModules = defWP();

// Listen for Ctrl/Cmd + Shift + R for complete relaunch
...
```
Basically, I want to export those 3 things *just* to the rest of the source code and eliminate it from the build.

**Comment by evanw** [comment]
If that file is `my-entry-point-code.js`, you can create another file that looks like this and then bundle that instead:

```js
import "./my-entry-point-code.js"
```

The bundle won't have any exports because this file doesn't have any exports.

**Comment by WorriedArrow** [comment]
I'll try that and see how it goes.

**Comment by WorriedArrow** [comment]
It still adds this at the end...
![image](https://user-images.githubusercontent.com/81983357/209380039-4c1d807e-2781-41ee-adc6-bee121c49104.png)
Is there any way to *just* call `require_entrypoint` instead of calling and exporting it?

**Comment by evanw** [comment]
You still haven't said how you are invoking esbuild, so I don't have enough information to answer your question. But it's definitely possible to use esbuild to build code without exporting stuff. For example:

```
$ echo 'import "./my-entry-point-code.js"' | esbuild --bundle
(() => {
  ...

  // my-entry-point-code.js
  var OpenLoader = def();
  var DiscordNative = window["DiscordNative"];
  var WebpackModules = defWP();
})();
```

**Comment by WorriedArrow** [comment]
Sorry about that, here's my esbuild config:
![image](https://user-images.githubusercontent.com/81983357/209392056-b69ee09b-6c15-4ad3-a067-31eeb231117c.png)

**Comment by evanw** [comment]
what is `src/entrypoint.ts`

**Comment by WorriedArrow** [comment]
```js
import "./main";
```

**Comment by WorriedArrow** [comment]
https://github.com/evanw/esbuild/issues/2768#issuecomment-1364036214 This is main.ts

**Comment by evanw** [comment]
I can't reproduce this:

```
$ cat src/entrypoint.ts 
import "./main";

$ cat src/main.ts 
/*
import { fadeIn, fadeOut } from "./utils/animations";
import addContent from "./utils/pluginUI";
import def from "./api/def";
import { uploadPlugin } from "./utils/pluginUploading";
import defWP from "./utils/webpack";
import load from "./loader";
import addDecorations from "./utils/windowDecorations";
*/
export const OpenLoader = def();
export const DiscordNative = window["DiscordNative"];
export const WebpackModules = defWP();

$ cat build.js 
const { buildSync } = require('esbuild')
const { join } = require('path')
buildSync({
  entryPoints: [join(__dirname, 'src', 'entrypoint.ts')],
  bundle: true,
  minify: false,
  treeShaking: false,
  platform: 'neutral',
  format: 'esm',
  target: 'es2022',
  outfile: join(__dirname, 'dist', 'openloader.js'),
})

$ node build.js 

$ cat dist/openloader.js 
// src/main.ts
var OpenLoader = def();
var DiscordNative = window["DiscordNative"];
var WebpackModules = defWP();
```

Marking this issue as `unactionable`.

**Comment by WorriedArrow** [comment]
Huh, that's odd.
Copied your config and my full code, reproduced as you did. My existing build code reproduces my issue.

**Comment by evanw** [comment]
I have a guess for what the problem is. Do you have `"type": "commonjs"` in your `package.json` file? That tells esbuild that all files should default to being CommonJS, which would be a reason for the `__commonJS` wrapper.

One workaround for that could be to move `src/entrypoint.ts` to `src/entrypoint.mts` to make it explicit that the entry point is ESM, not CommonJS.

**Comment by WorriedArrow** [comment]
Exactly the issue.

**Comment by WorriedArrow** [comment]
Thanks!
