### ISSUE TITLE
actually some analyzable imports!

### ISSUE THREAD

**Issue by yousefelgoharyx** [evanw/esbuild#2769]
Now I have a list of imports that I want to dynamically import at runtime but esbuild marks them as non-analyzable. The imports are known ahead of time. Is there any way to work around this?

**Comment by evanw** [comment]
I have no idea what you’re saying. Please provide a code example.

**Comment by yousefelgoharyx** [comment]
```json
{
  "/about": {
    "layoutPath": "app\\routes\\about\\layout.tsx",
    "pagePath": "app\\routes\\about\\page.tsx"
  },
  "/about/test": {
    "layoutPath": "app\\routes\\about\\test\\layout.tsx",
    "pagePath": "app\\routes\\about\\test\\page.tsx"
  },
  "/contact": {
    "layoutPath": "",
    "pagePath": ""
  },
  "/": {
    "layoutPath": "app\\routes\\layout.tsx",
    "pagePath": "app\\routes\\page.tsx"
  }
}
```
```js
for (const routeKey in routesMap) {
    const Page = React.lazy(() => import(route.pagePath));
    const Layout = React.lazy(() => import(route.layoutPath));
    ReactDOM.hydrateRoot(
      document.getElementById('app')!,
      <Layout>
        <Page />
      </Layout>
    );
}
```
The problem is that esbuild marks these imports as `external`. The thing is that all imports could be known at compile-time and thus esbuild should be able to bundle them as well so I was just asking if there is some way I could achieve this.
Sorry if my English isn't expressive enough

**Comment by evanw** [comment]
I see. These imports are indeed non-analyzable. From [esbuild's documentation about bundling](https://esbuild.github.io/api/#non-analyzable-imports):

> Bundling with esbuild only works with statically-defined imports (i.e. when the import path is a string literal). Imports that are defined at run-time (i.e. imports that depend on run-time code evaluation) are not bundled, since bundling is a compile-time operation. For example:
>
> ```js
> // Analyzable imports (will be bundled by esbuild)
> import 'pkg';
> import('pkg');
> require('pkg');
>
> // Non-analyzable imports (will not be bundled by esbuild)
> import(`pkg/${foo}`);
> require(`pkg/${foo}`);
> ['pkg'].map(require);
> ```

One way to fix your non-analyzable imports for esbuild would be to do something like this instead:

```tsx
const routesMap = {
  "/about": {
    layoutPath: () => import("app\\routes\\about\\layout.tsx"),
    pagePath: () => import("app\\routes\\about\\page.tsx"),
  },
  "/about/test": {
    layoutPath: () => import("app\\routes\\about\\test\\layout.tsx"),
    pagePath: () => import("app\\routes\\about\\test\\page.tsx"),
  },
  "/contact": {
    layoutPath: () => import(""),
    pagePath: () => import(""),
  },
  "/": {
    layoutPath: () => import("app\\routes\\layout.tsx"),
    pagePath: () => import("app\\routes\\page.tsx"),
  },
};

for (const routeKey in routesMap) {
  const route = routesMap[routeKey];
  const Page = React.lazy(route.layoutPath);
  const Layout = React.lazy(route.pagePath);
  ReactDOM.hydrateRoot(
    document.getElementById('app')!,
    <Layout>
      <Page />
    </Layout>
  );
}
```

**Comment by hanayashiki** [comment]
> ```json
> {
>   "/about": {
>     "layoutPath": "app\\routes\\about\\layout.tsx",
>     "pagePath": "app\\routes\\about\\page.tsx"
>   },
>   "/about/test": {
>     "layoutPath": "app\\routes\\about\\test\\layout.tsx",
>     "pagePath": "app\\routes\\about\\test\\page.tsx"
>   },
>   "/contact": {
>     "layoutPath": "",
>     "pagePath": ""
>   },
>   "/": {
>     "layoutPath": "app\\routes\\layout.tsx",
>     "pagePath": "app\\routes\\page.tsx"
>   }
> }
> ```
> 
> ```js
> for (const routeKey in routesMap) {
>     const route = routesMap[routeKey];
>     const Page = React.lazy(() => import(route.pagePath));
>     const Layout = React.lazy(() => import(route.layoutPath));
>     ReactDOM.hydrateRoot(
>       document.getElementById('app')!,
>       <Layout>
>         <Page />
>       </Layout>
>     );
> }
> ```
> 
> The problem is that esbuild marks these imports as `external`. The thing is that all imports could be known at compile-time and thus esbuild should be able to bundle them as well so I was just asking if there is some way I could achieve this. Sorry if my English isn't expressive enough

You can generate a "import map" by yourself at compile time, or write a plugin for that.

**Comment by evanw** [comment]
I'm closing this issue because this behavior is a deliberate part of the bundle design, has already been documented, and has a straightforward workaround.
