### ISSUE TITLE
should follow tsconfig compilerOptions target when didn't pass target

### ISSUE THREAD

**Issue by bluelovers** [evanw/esbuild#277]
```ts
let b;
export let a = b ??= true;
```

```json
{
  "compilerOptions": {
    "target": "ES2019"
  }
}
```

---

this 2 should get same output
```
esbuild index.ts --tsconfig=./tsconfig.json --target=es2019
esbuild index.ts --tsconfig=./tsconfig.json
```

expected output

```ts
let b;
export let a = b !== null && b !== void 0 ? b : b = true;
```

**Comment by evanw** [comment]
I understand why this would be useful. However, different directories can take their settings from different tsconfig.json files with esbuild. In my opinion it would be confusing and error-prone for the language target (which really only makes sense as a global setting) to vary per-directory, especially by default. So I think the current esbuild behavior of having to specify a global language target is actually less error-prone and more correct.

**Comment by DylanVann** [comment]
The recently merged behavior can be an issue when there are `tsconfig.json` files in `node_modules`.

e.g.

I'm bundling some code that uses `subscriptions-transport-ws` which contains a `tsconfig.json` file that specifies `"target": "es5"`. This results in errors like `error: Transforming const to the configured target environment ("es5") is not supported yet`.

Ideally I would like to totally ignore `tsconfig.json` files, and bundle/compile everything to the target I specify.
