### ISSUE TITLE
JSX with Plugin API

### ISSUE THREAD

**Issue by WorriedArrow** [evanw/esbuild#2770]
Is it possible to have a callback in a plugin for when JSX is parsed?

If not, is it possible to just convert JSX to a specific function call, such as:
```js
function hello() {
    return <div><sup>Hello</sup> <sub>World!</sub></div>
}
```
would become:
```js
function hello() {
    return customFunction("<div><sup>Hello</sup> <sub>World!</sub></div>");
}
```

**Comment by evanw** [comment]
No, that's not possible. The JSX transform that esbuild implements looks like this:

```js
function hello() {
  return customFunction("div", null, customFunction("sup", null, "Hello"), " ", customFunction("sub", null, "World!"));
}
```

There is no way to customize the JSX transform that esbuild implements other than changing what `customFunction` is. If you want to have a different JSX transform then you'll have to implement it yourself.

I'm closing this issue as I consider it to be out of esbuild's scope.
