### ISSUE TITLE
Leave adoptedStyleSheets in its default state

### ISSUE THREAD

**Issue by anilkumarum** [evanw/esbuild#2779]
esbuild support import assertions but esbuild remove adoptedStyleSheets that is imported via import assertions.

This is my code:
```js
import myStyle from "./style.css" assert { type: "css" };
this.shadowRoot.adoptedStyleSheets = [myStyle]; // inside custom elements
//or,
document.adoptedStyleSheets = [myStyle];
```
Current behaviour:
Import css stylesheet via import assertions  is no longer available for use at `adoptedStyleSheets`. 
esbuild  removed import statement.
No style apply on shadowroot custom elements
```js
var e = {};
this.shadowRoot.adoptedStyleSheets = [e]
// or,
document.adoptedStyleSheets = [e];
```

Expected behaviour we want:
Just leave this at its original state.
```js
import myStyle from "./style.css" assert { type: "css" };
this.shadowRoot.adoptedStyleSheets = [myStyle]; // inside custom elements
//or,
document.adoptedStyleSheets = [myStyle];
```

Currently, we need to fix these lines manually on every shadow custom elements.

**Comment by evanw** [comment]
Are you looking for something like `--loader:.css=copy`? The default behavior for `.css` files is to use the `css` loader which bundles all CSS files imported into JS files together into a separate CSS bundle, but you can customize the loader that esbuild uses for `.css` files using the `--loader` flag. You can also mark all `.css` files as external using `--external:*.css` but then you'll have to copy the files over yourself somehow. Using the `copy` loader is a way to have esbuild do this copying for you.

**Comment by anilkumarum** [comment]
I tried both flag: `--loader:.css=copy` and `--external:*.css`;
my build command
`esbuild todo-list.js --bundle --minify --target=chrome105 --outfile=out.js --loader:.css=copy`

Browser throw this error:
`out.js:15 Uncaught Error: Dynamic require of "./style.css" is not supported`

Build code:
```js
var m = ((t) =>
		typeof require < "u"
			? require
			: typeof Proxy < "u"
			? new Proxy(t, { get: (e, o) => (typeof require < "u" ? require : e)[o] })
			: t)(function (t) {
		if (typeof require < "u") return require.apply(this, arguments);
		throw new Error('Dynamic require of "' + t + '" is not supported');
	});

	var y = (t, e, o) => (
		(o = t != null ? r(l(t)) : {}),
		u(e || !t || !t.__esModule ? i(o, "default", { value: t, enumerable: !0 }) : o, t)
	);
	var n = y(m("./style-2XXKDGFX.css"));
    this.shadowRoot.adoptedStyleSheets = [n.default]
```

Browser doesn't fetch css nodules until we add this code :
```js
{ assert: { type: 'css' } }
```

**Comment by evanw** [comment]
Import assertions are an ESM-only feature. You likely need `--format=esm` too.

**Comment by anilkumarum** [comment]
With `--format=esm `, esbuild leave adoptedStyleSheets in its default state.

I added build command for whose see this issue in future:

My build command:
`esbuild entry.js --bundle --minify --format=esm --target=chrome105  --outfile=out.js --loader:.css=copy`
