### ISSUE TITLE
Does the Transform API support the Platform option? 

### ISSUE THREAD

**Issue by OSpoon** [evanw/esbuild#2781]
Does the Transform API support the Platform option? Why can't I find a related prompt in the document.

**Comment by hyrious** [comment]
It does, see [doc](https://esbuild.github.io/api/#platform):

> ### Platform
> _Supported by: [Transform](https://esbuild.github.io/api/#transform-api) | [Build](https://esbuild.github.io/api/#build-api)_

**Comment by hyrious** [comment]
`platform` in transform mode currently only affects these behaviors:

- Whether to add `0 && (module.exports = { ... })` annotations in `cjs` format to tell node.js named exports, [repl](https://hyrious.me/esbuild-repl/?version=0.16.12&mode=transform&input=export+default+1&options=--platform%3Dnode+--format%3Dcjs)

  ```js
  // input.js
  export var foo = 1
  // output.js, truncated
  0 && (module.exports = { foo });
  ```

- Whether to use node.js `Buffer` to encode `binary` assets, [repl](https://hyrious.me/esbuild-repl/?version=0.16.12&mode=transform&input=hello&options=--platform%3Dnode+--loader%3Dbinary)

  ```js
  // input
  hello
  // output.js
  var __toBinaryNode = (base64) => new Uint8Array(Buffer.from(base64, "base64"));
  module.exports = __toBinaryNode("aGVsbG8=");
  ```

**Comment by evanw** [comment]
I'm closing this issue since the question has been answered: yes, the transform API does support the platform option.

Also thanks for the follow-up answer @hyrious. I have added these side effects to https://esbuild.github.io/api/#platform.
