### ISSUE TITLE
typing for esbuild

### ISSUE THREAD

**Issue by eng-dibo** [evanw/esbuild#2787]
support typing for esbuild, so type checking and auto-complete are supported

build.ts
```
import { build } from 'esbuild';

build({
  logLevel: 'info',
  entryPoints: ['src/index.js'],
  bundle: true,
  outfile: 'www/main.js',
}).catch(() => process.exit(1));
```

run: `ts-node build.ts`

**Comment by evanw** [comment]
I’m confused. Typings are already included: https://unpkg.com/esbuild@0.16.13/lib/main.d.ts. Is it an issue on your end?

**Comment by eng-dibo** [comment]
![screen](https://user-images.githubusercontent.com/57308531/210441012-3a55af95-42a3-4ccd-94f3-34c70f57d9df.jpg)
@evanw

**Comment by hyrious** [comment]
It seems your typescript was configured to resolve "esbuild" to "esbuild.ts" (this file) instead of something like "node_modules/esbuild/lib/main". This often happens when there's no [`"moduleResolution": "node"`](https://www.typescriptlang.org/tsconfig/moduleResolution.html) in tsconfig.json.

**Comment by evanw** [comment]
I'm closing this issue since it sounds like there's nothing wrong with esbuild's package. This is a local configuration issue instead.

**Comment by eng-dibo** [comment]
`"moduleResolution": "node"` already exists

![image](https://user-images.githubusercontent.com/57308531/211154918-ad528f62-4fd4-42dc-95d3-8892917e687a.png)

@hyrious @evanw

**Comment by hyrious** [comment]
Ok, another possible reason is you have set `baseUrl` to the folder of esbuild.ts, for example `"baseUrl": "."`. This setting is to tell typescript where to resolve non-relative paths (like `esbuild`).

You can find more info about module resolution details at https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url

**Comment by eng-dibo** [comment]
resolved by renaming `esbuild.ts` to `esbuild.config.ts` 
it seems that typescript translates  `import .. from "esbuild"` into `import .. from "esbuild.ts" 

this may be caused by setting baseUrl to the same directory that includes esbuild.ts, as you suggested
