### ISSUE TITLE
--packages=external does not work in conjunction with typescript path aliases

### ISSUE THREAD

**Issue by josias-r** [evanw/esbuild#2792]
tsConfig paths:
```
"paths": {
	"$lib": ["lib"],
	"$lib/*": ["lib/*"],
},
```

With `--packages=external`, esbuild results in files using the `$lib` alias to compile to the following:

```
import { smth } from "$lib/something";
```

Instead of bundling `$lib/something` which is a local file, not a file from `node_modules`

Here's the full command I'm using: 

```
esbuild index.ts --tsconfig=tsconfig.json --outfile=dist/index.js --bundle --format=esm --platform=node --packages=external
```

**Comment by evanw** [comment]
That's just what the `--packages=external` flag does, sorry. The flag means "make any import path external that looks like a package path in the source code."

The `--packages=external` flag only exists for convenience. You can accomplish what it does with more verbose means such as using `--external:` or writing a plugin. If you want to do something more custom than what it does, then you'll need to do something more verbose.

**Comment by josias-r** [comment]
> That's just what the --packages=external flag does, sorry. The flag means "make any import path external that looks like a package path in the source code."

I get that, but just like mentioned in the docs for esbuild alias:
> Also note that marking an import path as external happens after the import path is rewritten by any configured [aliases](https://esbuild.github.io/api/#alias), so the alias feature still has an effect when this setting is used.

Wouldn't it make sense to resolve typescript aliases before marking paths as imports?

Otherwise, is it possible to write a plugin that also runs after the paths are resolved?

**Comment by evanw** [comment]
> is it possible to write a plugin that also runs after the paths are resolved?

Yes. The current API for this is not that elegant but you can use the [`resolve()` function](https://esbuild.github.io/plugins/#resolve) in your plugin and then interpret the result. Note that if you are resolving a path that your own plugin will apply to, you can avoid an infinite loop by adding something in `pluginData` to tell your plugin not to resolve that path again.

**Comment by josias-r** [comment]
> Yes. The current API for this is not that elegant but you can use the [resolve() function](https://esbuild.github.io/plugins/#resolve) in your plugin 
I will try that, thank you.

Still I think this should be up for discussion:

> Wouldn't it make sense to resolve typescript aliases before marking paths as imports?


But I'll close the ticket and if it never gains traction I guess it's just my personal need

**Comment by djgrant** [comment]
My intuition was also that the the externalisation of packages would happen after tsconfig paths/baseUrl are resolved. I agree this would be a good feature; an option (packages: external) that overrides the functionality of a built-in feature (tsconfig resolution) seems likely to violate expectations.

Nonetheless, the advice above on creating a plugin was helpful, and this seems to work adequately:

```ts
import { Plugin } from "esbuild";

export function externalModulesPlugin(): Plugin {
  return {
    name: "external-modules",
    setup(build) {
      build.onResolve({ filter: /.*$/ }, async (args) => {
        if (!args.pluginData?.resolved) {
          const resolveResult = await build.resolve(args.path, {
            kind: "import-statement",
            resolveDir: args.resolveDir,
            pluginData: {
              resolved: true,
            },
          });
          if (resolveResult.path.includes("/node_modules/")) {
            resolveResult.external = true;
          }
          return resolveResult;
        }
        return undefined;
      });
    },
  };
}

```

**Comment by h-sifat** [comment]
@djgrant Thanks a lot for the solution :gift_heart:. I guess this issue should be addressed.
