### ISSUE TITLE
typescript error after next js build

### ISSUE THREAD

**Issue by afu-hive** [evanw/esbuild#2798]
Here error

<img width="598" alt="image" src="https://user-images.githubusercontent.com/107838484/210963090-7522655c-e819-4ea0-b2fe-216681c130f3.png">

I got this error after implement test feature with vitest

here my dependency version
```javascript
"react": "17.0.1",
"@types/react": "17.0.2",
"typescript": "4.1.2",
"vitest": "^0.26.3"
"@vitejs/plugin-react": "^3.0.1",
"@wojtekmaj/enzyme-adapter-react-17": "^0.8.0",
"enzyme": "^3.11.0",
```

I try to remove `get text(): string;` line it's work fine but when I build on CI `node_modules` will recreate and this error happen again

**Comment by evanw** [comment]
That error is not from esbuild. You have the wrong project.

**Comment by evanw** [comment]
Wait sorry, I missed that it was from esbuild’s type definitions. I’ll take a look.

**Comment by evanw** [comment]
It looks like you need to upgrade to [TypeScript 4.3+](https://devblogs.microsoft.com/typescript/announcing-typescript-4-3/#separate-write-types).

**Comment by evanw** [comment]
This type syntax seems to be the only thing that prevents these type declarations from being used in older TypeScript versions. So I can just remove this type syntax. That'll let the type declarations be used as far back as TypeScript 3.5. (before that version TypeScript doesn't include type declarations for the `WebAssembly` global variable). I'll also add a test to ensure that this doesn't accidentally regress in the future.
