### ISSUE TITLE
Preserving some `import()` statements in the output

### ISSUE THREAD

**Issue by vicary** [evanw/esbuild#2801]
We have a number of 3rd party pre-built ESM modules where we have to import at client-side in the browser.

Is it possible to skip module resolution for some of the `await import()` statements, preserving it as-is so we can run them in the browser?

**Comment by evanw** [comment]
See https://esbuild.github.io/api/#external

**Comment by vicary** [comment]
Thanks for the reply, and sorry for skipping some critical details on our use case.

We have a plugin system in place, which means we don't know the name of externals ahead of time. We are importing from a variable on the fly like so `await import(moduleName);`.

Is it still possible with the existing external API too?

**Comment by evanw** [comment]
I'm confused. Module resolution isn't ever run for dynamic imports where the import path isn't a string literal:

```js
$ echo 'await import(moduleName)' | esbuild --bundle --format=esm
// <stdin>
await import(moduleName);
```

So it seems like you are asking for a way to stop esbuild from doing something that it doesn't do in the first place?
