### ISSUE TITLE
Output multiple bundles for different directories

### ISSUE THREAD

**Issue by zachkirsch** [evanw/esbuild#2804]
I have a feeling this isn't possible but wanted to create an issue just to make sure.

I have source code that looks like this:
```
internal/
  internal-a.js
  internal-b.js
  internal-c.js
external/            <-- depends on internal/
  external-a.js
  external-b.js
  external-c.js
```

I'd like for my final bundled output to be
```
internal.js
external.js          <-- depends on internal.js
```

My package.json would look like:
```json
"exports": {
  ".": "./external.js",
  "./internal": "./internal.js",
```

Rationale: I want to keep the exports of `external.js` pretty small (so to not pollute the IDE autocomplete when consuming the package). But for advanced users, I'd like the internal utilities in `internal.js` to be import-able.

Is this possible?

**Comment by evanw** [comment]
Sure. Three ways off the top of my head:

1. Bundle your internal entry points into `internal.js`. Then bundle your external entry points into `external.js`. This is the simplest approach, but the code in `internal.js` would be duplicated into `external.js`. If you don't want to do this, then here are two other approaches:

2. Bundle your internal and external entry points together with [code splitting](https://esbuild.github.io/api/#splitting) enabled. The caveats there would be that esbuild's code splitting is still WIP and currently only works with the `esm` output format.

3. Bundle twice: once for `external.js` with `internal.js` marked as [external](https://esbuild.github.io/api/#external), then again for `internal.js`. This may or may not be challenging depending on whether your cross-directory imports reference the final bundle or the original sources.

**Comment by zachkirsch** [comment]
Awesome, thanks!
