### ISSUE TITLE
Outputs an invalid code when a comment exists inside parenthesis and before async function

### ISSUE THREAD

**Issue by sapphi-red** [evanw/esbuild#2805]
When the following code is input,
```js
(
  /* foo */
  async function () {
  console.log('async 1');
})()
```
the output is
```js
/* foo */ async function() {
  console.log("async 1");
}();
```
and this is not a valid js code. ([repl](https://hyrious.me/esbuild-repl/?version=0.16.15&mode=transform&input=%28%0A++%2F*+foo+*%2F%0A++async+function+%28%29+%7B%0A++console.log%28%27async+1%27%29%3B%0A%7D%29%28%29))

This happens from 0.16.14.

A real world reproduction: [stackblitz](https://stackblitz.com/edit/esbuild-template-wdwjee?file=src%2Fmain.js,dist%2Fmain.js%3AL15457,build.js) (firestore has the code above. you can find the code by searching `Loads a bundle and returns the list of affected collection groups.` in [firestore's code](https://cdn.jsdelivr.net/npm/@firebase/firestore@3.8.0/dist/index.esm2017.js))

Original issue: https://github.com/vitejs/vite/issues/11626

**Comment by evanw** [comment]
Crap. This is the danger with printing comments. I remembered about the ones after the `return` and `throw` keywords but I forgot about these ones. I’ll fix this in the next release.

**Comment by sapphi-red** [comment]
Thanks!
