### ISSUE TITLE
Tree-shaking is not happening for deps.ts

### ISSUE THREAD

**Issue by vicary** [evanw/esbuild#2806]
There are a few similar coding pattern that we found esbuild is failing to shake away, where we unfortunately found out by an insane amount of cold start time in AWS Lambda.

Such pattern being re-exporting scattered exports in one single file, sometimes `deps.ts`, more mature projects may use `index.ts` for each directory.

We have around 100 util functions in a project as `lib/utils/*.ts`, where we re-exports them in `lib/utils/index.ts`. If we import any one of them via `import { ... } from "lib/utils";`, all 100 functions get bundled.

Is this an expected behaviour, or did we misconfigured esbuild such as output format?

**Comment by evanw** [comment]
Can you provide a self-contained example with code and the esbuild command used that reproduces the problem?

**Comment by vicary** [comment]
We are using the Serverless Framework and its `serverless-esbuild` plugin, so it will takes some time for me to make a minimum reproducing repo.

When I tried setting up from scratch, it is tree-shaking properly. It must be related to options generated by `serverless-esbuild`, which internally use `import { build } from "esbuild";`

I'll try capturing the generated build options this few days.

**Comment by hyrious** [comment]
Decorators are meant to have side effects, this is by design.

If you're sure that `@Entity` won't affect any other place of your code, you can wrap your code like this:

```ts
const TestModel = /* @__PURE__ */ (() => {
	@Entity()
	class TestModel {}
	return TestModel
})()
```

**Comment by vicary** [comment]
@hyrious Thanks, it works to an extent.

Is it also by design that only importing decorators without using it will force the decorator itself into the bundle?

**Comment by hyrious** [comment]
Decorators are just functions, they follow the same rule as other side effects.

```js
function Entity() {} // this is pure, it will be removed if not used

function Entity2() {}
Entity2.a = 1 // oops, this line has side effect, it will not be removed if imported
```

**Comment by vicary** [comment]
I believe this should be done on TypeORM side, thanks for answering!
