### ISSUE TITLE
Format set to iife, bundle file still has `require`

### ISSUE THREAD

**Issue by zouhangwithsweet** [evanw/esbuild#2810]
![image](https://user-images.githubusercontent.com/21095710/211552224-c1bbde68-5765-4df6-861e-b80b595c9c00.png)

**Comment by hyrious** [comment]
https://esbuild.github.io/api/#bundle

**Comment by zouhangwithsweet** [comment]
> https://esbuild.github.io/api/#bundle

I don't want to build vue into bundle file，just use it from window.vue

**Comment by zouhangwithsweet** [comment]
except 

((vue) => { something })(vue)

**Comment by evanw** [comment]
Dependencies that aren't in the bundle are turned into `require` calls to let you load them dynamically. You could add something like this in your HTML, for example:

```js
window.require = path => {
  if (path === 'vue') return getVueFromSomewhere()
  else throw new Error('Cannot require ' + path)
}
```

Or if you want to get fancy you can write a plugin to transform `import` into code that loads the library from wherever you need to load it from. Here is an example of doing that: https://github.com/evanw/esbuild/issues/337#issuecomment-754840414.

**Comment by zouhangwithsweet** [comment]
I got it, thanks sir. :)
