### ISSUE TITLE
Maintaining Class Names for a library

### ISSUE THREAD

**Issue by joeworkman** [evanw/esbuild#2819]
I am using esbuild to bundle a library. There are certain classes within my code that I would like to expose for developers to be able to access and write their own code using the classes. I have spent hours going through docs, videos and blog posts. I don't think that this is possible. I hope that I am wrong.

**Comment by evanw** [comment]
There isn't enough information here to know what you're talking about, sorry. But from your description it sounds like you are looking for help learning how JavaScript works. There are many tutorials about this. Here's one example: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules.

TL;DR: You can do this with the `export` keyword:

```js
// my-library.js
export class MyClass {}
```

Developers could then use it like this:

```js
import { MyClass } from './my-library.js'
new MyClass
```

You may have to change esbuild's [`format`](https://esbuild.github.io/api/#format) setting to match the output module format that you intend to publish your library with.

**Comment by joeworkman** [comment]
You are correct in that I am new to using JS Modules. Your answer helped me get to the solution though. 

I was just running a simple test with inline script tags. I had...

```
<script type="module" src="/my-library.js"></script>
<script>
new MyClass;
</script>
```

However, what I needed was....

```
<script type="module">
import { MyClass } from './my-library.js'
new MyClass;
</script>
```

I appreciate you taking the time to help me out.
