### ISSUE TITLE
Event source introduction in 0.17

### ISSUE THREAD

**Issue by dmail** [evanw/esbuild#2824]
I just read the release changelog for 0.17 and noticed usage of event source to implement live reloading.
I have tried this approach in the past and it works but comes with big troubles you'll encounter for sure. 
I want to warn you about this:

These is a very annoying browser behavior regarding event source connections. They are limited (something like 5 max) PER BROWSER, not per tab. So as soon as you have 5 tab using event source the 6th tab will wait forever waiting to connect.
I have also noticed browser sometimes depriorize the event source connection or something like that and here again you won't be able to connect to the server.

Sorry for not having more precise information on the subject. I am on my phone so I can't properly find the resources on the subject.

**Comment by evanw** [comment]
Thanks. I’m aware. It’s documented here: https://esbuild.github.io/api/#live-reload-caveats. The workaround is to enable HTTPS: https://esbuild.github.io/api/#https.

**Comment by dmail** [comment]
Oh wonderful 😊👍
I was not aware https could fix this annoying stuff thanks

**Comment by mbrevda** [comment]
Is some way esbuild could expose if there are currently browser(s) connected?

The use case would be to open a new browser window conditionally, but only if there are no clients connected:

```js
const {port, /* hypothetical API -> */ clients} = await context.serve({port: 3000});

// open in browser if we don't already have an open browser
if (await clients().length === 0) open(`http://localhost:${port}`);
console.log(`frontend: server listening on port ${port}`);
```

This could, hypothetically, be extended to allow sending arbitrary messages to listening clients, enabling more advanced reload scenarios, error message overlays, etc:


```js
for (const client in await clients()) client.postMessage('hi!')
```

and even listen for messages from the client:

```js
const onMsg = data => console.log(data)
for (const client in await clients()) client.addEventListener('message', onMsg)
```

thoughts?
