### ISSUE TITLE
0.17.0 - where is the onRebuild in watch mode?

### ISSUE THREAD

**Issue by Den368** [evanw/esbuild#2826]
Previously, we could know when and why (error, result) "watch" rebuilt the project by adding a watch configuration object, for example:
```
watch: {
        onRebuild(error, result) {
            if (error) console.error(`Build failed at [${new Date()}]:`, error);
            else console.log(`Build succeeded at [${new Date()}]:`, result);
        }
}
```

Is there a way to do the same?

**Comment by hyrious** [comment]
Please see the [release note](https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#upgrade-guide-for-existing-code), you can use a plugin with the onEnd callback to simulate the same behavior:

> ```js
> const plugins = [{
>   name: 'my-plugin',
>   setup(build) {
>     let count = 0;
>     build.onEnd(result => {
>       if (count++ === 0) console.log('first build:', result);
>       else console.log('subsequent build:', result);
>     });
>   },
> }];
> const ctx = await esbuild.context({ ...buildOptions, plugins });
> await ctx.watch();
> ...
> await ctx.dispose(); // To free resources
> ```
