### ISSUE TITLE
Use of require to load externals

### ISSUE THREAD

**Issue by bep** [evanw/esbuild#283]
This is probably me not getting the API, but I

* Thought the `externals` options was (among other things) a way to define dependencies loaded some other way (e.g. CDN).
* The "hello world" JSX example from the README with the options below produces code on the form ` const React = __toModule(require("react"));`, which crashes in the browser.

```go
package main

import (
	"fmt"
	"log"

	"github.com/evanw/esbuild/pkg/api"
)

func main() {

	jsx := `import * as React from 'react'
import * as ReactDOM from 'react-dom'

ReactDOM.render(
  <h1>Hello, world!</h1>,
  document.getElementById('root')
);`

	buildOptions := api.BuildOptions{
		Bundle:    true,
		Target:    api.ESNext,
		Format:    api.FormatIIFE,
		Externals: []string{"react", "react-dom"},

		Stdin: &api.StdinOptions{
			Contents: jsx,
			Loader:   api.LoaderJSX,
		},
	}

	result := api.Build(buildOptions)
	if result.Errors != nil {
		log.Fatalf("Err: %v", result.Errors)
	}
	fmt.Println("Got:", len(result.OutputFiles), "files")
	fmt.Println(string(result.OutputFiles[0].Contents))

}
```

**Comment by evanw** [comment]
> Thought the externals options was (among other things) a way to define dependencies loaded some other way (e.g. CDN).

The option is mainly to be able to bundle something for node with external libraries (either ones built in to node or ones that can't be bundled such as native `.node` binary addons). It is not a general-purpose CDN redirection mechanism.

I think you can do something like that using the [`"browser"` field in package.json](https://github.com/defunctzombie/package-browser-field-spec/tree/4f296871cee64e60124841c06c06511885152f19#spec), which lets you redirect require/import paths to different sources when targeting the browser. You should be able to redirect a module to a small shim file that forwards to the CDN version using something like `module.exports = window.React`.

**Comment by bep** [comment]
OK, thanks, I will try that.

**Comment by benkoshy** [comment]
My thanks for all the work you've put in.

> You should be able to redirect a module to a small shim file that forwards to the CDN version using something like module.exports = window.React.

What should I put in the shim?

```js
// package.json
{
  "browser": {
    "abc": "./public/js/shims/abc.js"
  }
}
```

```js
// ./public/js/shims/abc.js

module.exports = window.google | require("https://www.gstatic.com/charts/loader.js") 

// How can I get an abc.js IIFE from a CDN?
// Just a brief pointer would more than suffice.
```

I can open a PR to document this if it would help.
