### ISSUE TITLE
context api: Get notified on file changes

### ISSUE THREAD

**Issue by shyim** [evanw/esbuild#2835]
In previous versions there was a `OnRebuild` function on WatchOptions. Is there something similar for the new api?

Use case:

When the css output changes, I want to say the browser reload only CSS not entire page

**Comment by evanw** [comment]
> In previous versions there was a `OnRebuild` function on WatchOptions. Is there something similar for the new api?

This is described in the release notes: https://github.com/evanw/esbuild/releases/v0.17.0

> When the css output changes, I want to say the browser reload only CSS not entire page

There are instructions for doing that here: https://esbuild.github.io/api/#live-reload and https://esbuild.github.io/api/#hot-reloading-css
