### ISSUE TITLE
Return type of 'watch' API (JS) doesn't match implementation

### ISSUE THREAD

**Issue by jgoz** [evanw/esbuild#2836]
The implementation of [`watch()`](https://github.com/evanw/esbuild/blob/002ef9522a4103132cefb075aee3e09b0e4fa3f1/lib/shared/common.ts#L1058) returns a Promise, but on BuildContext it is [typed as returning `void`](https://github.com/evanw/esbuild/blob/002ef9522a4103132cefb075aee3e09b0e4fa3f1/lib/shared/types.ts#L492).

I realize awaiting `watch` is probably unnecessary 99% of the time, but in the rare event that watch mode fails to start and the promise gets rejected, using `await` would prevent it from bubbling into `unhandledrejection` territory.

This is probably relevant only to JS API users who also use TypeScript and some kind of type-aware linting that points out missing or extraneous `await`s.

**Comment by evanw** [comment]
Thanks for catching this. This was an oversight. The return type definitely should be a promise. I’ll fix this type definition. I think the only case where watch mode currently fails is when you call it a second time or you call it after `dispose`, so this shouldn’t come up unless the API is misused.
