### ISSUE TITLE
New in/out entryPoint object does not write files

### ISSUE THREAD

**Issue by edoardocavazza** [evanw/esbuild#2837]
I have tried the new entryPoints format introduced in 0.17.1, but the output prints only to stdout and the dist file is not created.

```js
import esbuild from 'esbuild';

esbuild.build({
    entryPoints: [
        { in: './src/index.ts', out: './dist' },
    ],
});
```

**Comment by evanw** [comment]
This feature isn't new. It's just that the JS API now has a more flexible syntax for this that matches the existing CLI and Go API. You still need to specify an output directory to get this to work. I can work on improving this scenario (e.g. maybe this should imply `outdir: '.'` or maybe it shouldn't be allowed to do this without an `outdir`) but for now you should specify an `outdir`. Your specific example is probably better expressed like this anyway:

```js
esbuild.build({
    entryPoints: ['./src/index.ts'],
    outfile: './dist.js',
});
```

**Comment by edoardocavazza** [comment]
Oh ok, that makes sense! Thanks for the explanation!
