### ISSUE TITLE
CSS variables with same value defined in media query are minified incorrectly

### ISSUE THREAD

**Issue by CLDXiang** [evanw/esbuild#2838]
esbuild@0.17.0

When two different CSS variables with same value defined in media query, only one of these CSS variables will remain in the minified output.

Input:
```css
@media (prefers-color-scheme: dark) {
  body {
    --VAR-1: #000;
  }
}

@media (prefers-color-scheme: dark) {
  body {
    --VAR-2: #000;
  }
}
```

`esbuild --bundle style.css --outfile=out.css --minify-syntax` output:

```css
/* style.css */
@media (prefers-color-scheme: dark) {
  body {
    --VAR-2: #000;
  }
}
```

**Comment by evanw** [comment]
Thanks for the report. It looks like this is an old regression from [version 0.11.19](https://github.com/evanw/esbuild/releases/v0.11.19).
