### ISSUE TITLE
'packages' doesn't exist in type 'BuildOptions'

### ISSUE THREAD

**Issue by eng-dibo** [evanw/esbuild#2844]
as mentioned in the docs, we can use ` packages: 'external'`

![image](https://user-images.githubusercontent.com/57308531/213326588-253b0c8b-6690-43ec-b33f-0addd4e258d1.png)

but it seems that it is missing from the typing

```
import { BuildOptions, build } from 'esbuild';

let esbuildConfig: BuildOptions = {
 packages: 'external',
 .....
}
```
![jpg](https://user-images.githubusercontent.com/57308531/213327101-4e2ad20e-3972-4c62-858d-7a49f5175353.jpg)

**Comment by eng-dibo** [comment]
it seems that it exists in `CommonOptions`, but `bundle` is not exists there

**Comment by evanw** [comment]
It works fine for me:

```
$ npm i esbuild typescript
$ echo 'import {build} from "esbuild"; build({packages: "external"})' > example.ts
$ node_modules/.bin/tsc example.ts 
```

That doesn't produce any errors. I assume this means you're using an old version of esbuild without the `packages` feature and you just need to update esbuild. If not, then please provide steps to reproduce the issue.

**Comment by eng-dibo** [comment]
![jpg](https://user-images.githubusercontent.com/57308531/213337900-b378add7-a1a2-4504-966b-b2ae17d576f3.jpg)

**Comment by eng-dibo** [comment]
let me investigate tsconfig.json carefully and reply to you again to save your time

**Comment by hyrious** [comment]
<q>packages</q> was added in [0.16.5](https://github.com/evanw/esbuild/releases/tag/v0.16.5), could you check your node_modules/esbuild/package.json to see if it is greater than that?

**Comment by eng-dibo** [comment]
does this option totally replaces the package `esbuild-node-externals`?
@hyrious

**Comment by eng-dibo** [comment]
> packages was added in [0.16.5](https://github.com/evanw/esbuild/releases/tag/v0.16.5)

this solved the issue
