### ISSUE TITLE
[improvement] a clearer error reporting

### ISSUE THREAD

**Issue by its-dibo** [evanw/esbuild#2845]
I got this error `Could not resolve "./packages/cache"`, but the error doesn't show why it couldn't be resolved!.
the error occurs when I try to use the built-in `resolve()` method

```
build.onResolve({ filter: /.*/ }, async (args: OnResolveArgs) => {
 ...
 let result = await build.resolve(realPath, {
          pluginName: 'test',
          importer: args.importer,
          namespace: args.namespace,
          resolveDir: args.resolveDir,
          kind: args.kind,
          pluginData: args.pluginData,
        });
        if (result.errors.length > 0) {
          return { errors: result.errors };
        }
}
```

**Comment by eng-dibo** [comment]
however, I know the reason for the error, but the error message is still not clear
the error is solved by overriding the value of `args.resolveDir`

**Comment by evanw** [comment]
I'm closing this issue because I'm not planning on doing this. There are lots of reasons why something may not have resolved correctly and enumerating all of them whenever a path resolution failure occurs is too much detail for a log message in my opinion.
