### ISSUE TITLE
Support generating dependency graph

### ISSUE THREAD

**Issue by fabiospampinato** [evanw/esbuild#2850]
It'd be useful to be able to see who is importing what in a standalone graph.

Potentially it could be even more useful to be able to see that information in the bundle analyzer, so that hovering over a module shows up the import chain also.

---

Even chatGPT thinks this should be implemented: 😀

<img width="819" alt="Screen Shot 2023-01-19 at 15 07 27" src="https://user-images.githubusercontent.com/1812093/213478507-eaba441b-1774-42e3-b851-48a1124f2bbe.png">

**Comment by fabiospampinato** [comment]
It seems to show one of the import changes though, not all of them, so it becomes hard to judge whether something can be removed from the bundle easily or not.

Feel free to re-open if that feature could be in scope for esbuild.

**Comment by evanw** [comment]
Sorry about the gray boxes in the screenshot. They are supposed to be arrows but Chrome needs a special CSS vendor prefix. I just published a new build with a fix.
