### ISSUE TITLE
Top-level await detection doesn't take into account dead code elimination

### ISSUE THREAD

**Issue by fabiospampinato** [evanw/esbuild#2853]
Trying to bundle the following code throws:

```js
if ( false ) {
  await foo ();
}
```

But esbuild should realize that there's not actually any top-level await there, because the await is unreachable.

This detail not being supported makes it a bit more annoying to create a module that works in different environments but that top-level awaits in only one of them.

**Comment by evanw** [comment]
Interesting suggestion. I can't think of any negative consequences of doing this, so I think this sounds reasonable.
