### ISSUE TITLE
Working with TypeScript's EMS + nodeResolution: Node16

### ISSUE THREAD

**Issue by cometkim** [evanw/esbuild#2859]
in TypeScript ESM config with nodeResolution `Node16` or `NodeNext`, import paths should have a `.js` extension even if the source is *.ts.

 When I try to build it with esbuild I get errors for file resolution

```
✘ [ERROR] Could not read from file: /home/comet/Workspace/src/github.com/braneproject/dom/packages/dom/src/worker-thread/DOMTokenList.js

    src/index.ts:3:29:
      3 │ import { DOMTokenList } from './worker-thread/DOMTokenList.js';
        ╵                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

```

because the actual file path is `/home/comet/Workspace/src/github.com/braneproject/dom/packages/dom/src/worker-thread/DOMTokenList.ts`

**Comment by evanw** [comment]
I'm confused. The behavior you're asking for is already something esbuild does. Please provide a way to reproduce the issue (input code + esbuild command used).

**Comment by cometkim** [comment]
Sorry. That was my plugin behavior.

I wrote a plugin to resolve import maps like:

```
  "imports": {
    "#shared/*.js": "./src/shared/*.js",
    "#globals/*.js": {
      "custom": "./src/globals/*.custom.js",
      "default": "./src/globals/*.default.js"
    }
  },
```

I need to return an absolute path in `onResolve`, but the plugin can't guess whether the actual target path is `.ts` or `.js`.

**Comment by evanw** [comment]
Can’t it check the file system to see which one of those files exists? That’s all esbuild does. You can see esbuild’s logic for that here if it helps:

https://github.com/evanw/esbuild/blob/main/internal/resolver/resolver.go#L1535-L1561

**Comment by cometkim** [comment]
thank you. I wrote the same code. https://github.com/cometkim/nanobundle/blob/0b85f38/src/plugins/esbuildImportMapsPlugin.ts#L18-L26

I thought there must be a better workaround :sweat_smile:
