### ISSUE TITLE
Files with an initial `.` are copied incorrectly

### ISSUE THREAD

**Issue by arnog** [evanw/esbuild#2861]
Files that start with a `.`, e.g. `.htaccess`, seems to confuse the `copy` loader.

Using a relative path:

```js
build({
  entryPoints: ['./packages/website/assets/.htaccess'],
  outdir: './build/',
  loader: { '.htaccess': 'copy' },
}).catch(() => process.exit(1));
```
result in a file `assets.htaccess` copied into the `./build` directory.

Using an absolute path:

```js
build({
  entryPoints: ['/Users/arno/dev/packages/website/assets/.htaccess'],
  outdir: './build/',
  loader: { '.htaccess': 'copy' },
}).catch(() => process.exit(1));
```

result in a file `..htaccess` copied into the `./build` directory (note the double `.`).

I was expecting the file `.htaccess` to be copied into the `./build` directory.

**Comment by evanw** [comment]
Thanks for the report. I'll work on a fix.
