### ISSUE TITLE
Use esbuild-wasm in jest

### ISSUE THREAD

**Issue by Linkontoask** [evanw/esbuild#2862]
https://github.com/jsdom/jsdom/issues/2524#issuecomment-1399453859

I tried to introduce TextEncoder, TextDecoder in the jest setup, but found another error with it.

```js
var encodeUTF8;
var decodeUTF8;
var encodeInvariant;
if (typeof TextEncoder !== "undefined" && typeof TextDecoder !== "undefined") {
  let encoder = new TextEncoder();
  let decoder = new TextDecoder();
  encodeUTF8 = (text) => encoder.encode(text);
  decodeUTF8 = (bytes) => decoder.decode(bytes);
  encodeInvariant = 'new TextEncoder().encode("")';
} else if (typeof Buffer !== "undefined") {
  encodeUTF8 = (text) => Buffer.from(text);
  decodeUTF8 = (bytes) => {
    let { buffer, byteOffset, byteLength } = bytes;
    return Buffer.from(buffer, byteOffset, byteLength).toString();
  };
  encodeInvariant = 'Buffer.from("")';
} else {
  throw new Error("No UTF-8 codec found");
}
if (!(encodeUTF8("") instanceof Uint8Array))
  throw new Error(`Invariant violation: "${encodeInvariant} instanceof Uint8Array" is incorrectly false

This indicates that your JavaScript environment is broken. You cannot use
esbuild in this environment because esbuild relies on this invariant. This
is not a problem with esbuild. You need to fix your environment instead.
`);
```

```
Invariant violation: "new TextEncoder().encode("") instanceof Uint8Array" is incorrectly false
```

The key point is that my local validation using the agreed block of code `encodeUTF8("") instanceof Uint8Array` returns `true`, which makes me feel confused, and I have tried for a long time without being able to find out why. But the code as above is fine in the browser.

**Comment by evanw** [comment]
[The `encode` function is supposed to return a `Uint8Array`.](https://developer.mozilla.org/en-US/docs/Web/API/TextEncoder/encode) If it doesn’t, then that’s a problem with that JavaScript environment, not with esbuild. So the esbuild issue tracker is an inappropriate place for getting help with your issue.
