### ISSUE TITLE
[Live-Reload] Change event not triggered

### ISSUE THREAD

**Issue by benny00100** [evanw/esbuild#2864]
Hello,

I am trying to implement live-reloading using this example

https://esbuild.github.io/api/#live-reload

However, I never receive the `change` event.

The connection to the event source according the `onopen `listener was successful though? 

Adding an additional `onmessage` listener - it seems that no events are fired from the esbuild server?!

Can anyone point me in any direction - what's wrong?

Using latest esbuild version 0.17.4.

Thanks in advance!

**Comment by mbielanczuk** [comment]
I was just able to configure live-reload with this config (and also version 0.17.4):


```js

import esBuild from "esbuild";

const ctx = await esBuild.context({
    entryPoints: ["<your-entry-point>"],
    bundle: true,
    format: "cjs",
    outfile: "<your-bundle-file>",
    banner: {
        js: "(() => { (new EventSource(\"/esbuild\")).addEventListener('change', () => location.reload()); })();"
    }
});

await ctx.serve({ servedir: "<your-statics-and-index>", port: 3000 });
await ctx.watch();

```

Maybe that will be helpful.

**Comment by evanw** [comment]
> Adding an additional `onmessage` listener - it seems that no events are fired from the esbuild server?!

Did you follow the example code (copied below)?

```js
// This should work, and is what's in the documentation
new EventSource('/esbuild').addEventListener('change', () => location.reload())
```

You cannot use `onmessage` instead because the event is called `change`, not `message`:

```js
// This does not work, and is not what's in the documentation
new EventSource('/esbuild').onmessage = () => location.reload()
```

Also make sure you enable watch mode. Serving without watch mode does not give you live reload.

**Comment by benny00100** [comment]
> I was just able to configure live-reload with this config (and also version 0.17.4):
> 
> ```js
> import esBuild from "esbuild";
> 
> const ctx = await esBuild.context({
>     entryPoints: ["<your-entry-point>"],
>     bundle: true,
>     format: "cjs",
>     outfile: "<your-bundle-file>",
>     banner: {
>         js: "(() => { (new EventSource(\"/esbuild\")).addEventListener('change', () => location.reload()); })();"
>     }
> });
> 
> await ctx.serve({ servedir: "<dir-with-your-statics-and-bundle>", port: <port> });
> await ctx.watch();
> ```
> 
> Maybe it will be helpful.

Thanks a lot for sharing your code. The banner option did the trick. It seems that I added the `new EventSource` in my project incorrectly. Your version is much smarter. Thanks a lot!
