### ISSUE TITLE
Run nodejs application in watch mode

### ISSUE THREAD

**Issue by kirylvarykau** [evanw/esbuild#2868]
Hi! 

I like esbuild a lot and I have a question. 

I'd like to restart my nodejs server on change. I found a `watch` mode, but it doesn't return control to the console.

I know, that it's possible to run `watch` in one terminal and then run e.g. `nodemon` in another one, but then we don't have a synchronization between them (probably delay could solve it as well). 

Even `rebuild` doesn't return control back, so I can't do sequently `rebuild` -> `restart app`. 

So, I'm curious if there any pretty solutions without some strange workarounds or libs with 10 download per week?
Plugins aren't using a benefit of `watch` or `rebuild` API. They're based on complete build each time.
Maybe someone has a meaningful solution to this quite straightforward issue? 

Thank you a lot!

**Comment by hyrious** [comment]
There're at least 2 methods I know to implement your requirement.

1. Use [`node --watch`](https://nodejs.org/api/cli.html#--watch) along with a node [loader](https://nodejs.org/api/esm.html#transpiler-loader) that simply invokes esbuild. It's pretty simple solution that you can find many existing [tools](https://github.com/esbuild-kit/tsx). [Here](https://github.com/hyrious/esbuild-dev/blob/main/src/loader.ts)'s mine if you need some inspiration.
2. Use esbuild's context api along with a plugin's on-end callback to restart the server. This was described in the release note of 0.17.0 where you can find more code examples there. In addition, I also made one [tool](https://github.com/hyrious/esbuild-dev) that wraps this use case already.

**Comment by evanw** [comment]
I believe you are looking for this: https://esbuild.github.io/plugins/#on-end. This lets you do something after a build.

> Even `rebuild` doesn't return control back, so I can't do sequently `rebuild` -> `restart app`.

What do you mean? It sounds like you're saying `rebuild().then(() => restartApp())` isn't possible, but it is.

> Plugins aren't using a benefit of `watch` or `rebuild` API. They're based on complete build each time.

Adding a plugin doesn't disable incremental builds. All builds done on a build context are incremental builds, regardless of whether they use plugins or not.

**Comment by evanw** [comment]
Closing because this question has been answered.
