### ISSUE TITLE
Serve stopped working: now getting 426 Upgrade Required errors

### ISSUE THREAD

**Issue by cquillen2003** [evanw/esbuild#2873]
I am using esbuild's Serve api (esbuild v0.16.16) per the docs "Customizing server behavior" section.  It was working great until recently.  It no longer works.  I have made no changes to the code.

Requests to esbuild's dev server now fail with a `426 Upgrade Required` error.

Any help will be greatly appreciated.

**Comment by evanw** [comment]
You could check the value of the `Upgrade` header but my guess is that this is due to the introduction of HTTP/2. Perhaps your proxy doesn’t support HTTP/2? I can try to investigate later. Can you provide a self-contained demonstration of the problem here?

**Comment by cquillen2003** [comment]
I'm not sure about HTTP/2 support.  I had to use the "Customizing server behavior" example in the docs to figure this out.  Here is a self-contained, simple demo.

https://github.com/cquillen2003/esbuild-issue

I am seeing requests to the esbuild dev server at `localhost:8000` fail with 426 errors.

**Comment by evanw** [comment]
I can't reproduce this, sorry. When I load that page in the browser (Firefox, Chrome, and Safari) I see `Loading React root....` followed by `App` (after fixing `App.jsx` by adding `import React from 'react'`). Marking this issue as `unactionable` since the provided demo doesn't demonstrate the problem.

**Comment by cquillen2003** [comment]
I was just able to fix this by changing the port from 8000 to 8001 on the esbuild dev server.  Not sure why, but I will go ahead and close this.
