### ISSUE TITLE
[Question] Why does the export build by cjs have a prefix?

### ISSUE THREAD

**Issue by gwsbhqt** [evanw/esbuild#2874]
Why does this `0 &&` prefix exist? Won't a short-circuit operation occur due to false values?

Input
```tsx
export const aaa = xxx
```

Output
```js
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  aaa
});
```

**Comment by hyrious** [comment]
Yes, it has no side effects. But [cjs-module-lexer](https://github.com/nodejs/cjs-module-lexer) can parse this pattern and infer named exports when this CJS file being imported into ESM enviroment in nodejs.

**Comment by gwsbhqt** [comment]
> Yes, it has no side effects. But [cjs-module-lexer](https://github.com/nodejs/cjs-module-lexer) can parse this pattern and infer named exports when this CJS file being imported into ESM enviroment in nodejs.

My fault, I ignored the real code above.

Real export code

```js
var src_exports = {};
__export(src_exports, {
  version: () => version
});
module.exports = __toCommonJS(src_exports);
```

Fake analysis code

```js
// Annotate the CommonJS export names for ESM import in node:
0 && (module.exports = {
  aaa
});
```
