### ISSUE TITLE
How to make  esbuild converted code read process.env dynamic variables from files ?

### ISSUE THREAD

**Issue by polyphia** [evanw/esbuild#2876]
Hi guys, sorry bout the noob question am really new to ESBuild . 

I converted some .js file to .cjs in order to be able to compile it afterwards and was surprised to see all the variables set through process.env were assigned static values from the existing env files . 

I have about 6 files with dozens of variables set through process.env and they all are assigned static values upon compilation . 

How can I make ESBuild ignore the static values and fetch the env dynamic variables from the respective files ?

Is this related to injection parameter ?

Thanks

**Comment by hyrious** [comment]
First of all, esbuild does [not](https://hyrious.me/esbuild-repl/?version=0.17.5&mode=transform&input=process.env.NODE_ENV%0Aprocess.env.DEBUG%0Aprocess.env.DEV) replace all `process.env.*`, only `process.env.NODE_ENV` will be replaced [in bundle mode](https://hyrious.me/esbuild-repl/?version=0.17.5&mode=build&modules=%5B%5B%22main.js%22%2C%22%2Bprocess.env.NODE_ENV%5Cnprocess.env.DEBUG%5Cnprocess.env.DEV%22%2C1%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22splitting%22%3Atrue%7D) and it has a simple [workaround](https://hyrious.me/esbuild-repl/?version=0.17.5&mode=build&modules=%5B%5B%22main.js%22%2C%22%2Bprocess.env.NODE_ENV%5Cnprocess.env.DEBUG%5Cnprocess.env.DEV%22%2C1%5D%5D&buildOptions=%7B%22bundle%22%3Atrue%2C%22format%22%3A%22esm%22%2C%22splitting%22%3Atrue%2C%22define%22%3A%7B%22process.env.NODE_ENV%22%3A%22process.env.NODE_ENV%22%7D%7D).

> all the variables set through process.env were assigned static values from the existing env files.

It seems you're using some dotenv plugin to define env variables at compile time. But you want to make this happen at runtime? If that's the case, you can invoke [dotenv](https://github.com/motdotla/dotenv) in your source code directly .

**Comment by polyphia** [comment]
@hyrious thanks for the reply ! 

I am not using any plugin, I am just running a very streamlined esbuild command with barely any arguments :

esbuild ./app --bundle --outfile=app.cjs --format=cjs --platform=node 

The problem is that my dynamic variables which I usually set through multiple env files are being assigned static values corresponding to the vars defined values at the time of bundling . 

Example of my code: 

```
const mysettings = require("settings.json");
Object.assign(process.env, mysettings );

const MYVAR = process.env.MYVAR

```

After bundling, changing MYVAR in my env settings file does not change the variable value in the app, it always assumes the same static value it had when bundled .

**Comment by hyrious** [comment]
Oh, in that case maybe you need `--external:settings.json`.

To exclude all json files from bundle: `--external:*.json` (take care of shell escapeing then).

To exclude a local file: `--external:./settings.json`.

**Comment by polyphia** [comment]
Much much appreciated, that fixed it ! I had tried the --external argument but I think I had my relative path incorrectly set, works now and def saved me a lot of time . 

Thanks :)
