### ISSUE TITLE
[Feature Request]: context.build helper

### ISSUE THREAD

**Issue by rtpg** [evanw/esbuild#2877]
I have a script that currently looks like the following:

```
const ctx = await require('esbuild').context({...})
if (process.env.WATCH) {
    await ctx.watch()
} else {
    await ctx.rebuild()
    ctx.dispose()
}
```

the context dictionary of course being "big enough" such that having the context this way around is nice. Writing `ctx.rebuild()` when I'm going to do a single build doesn't look great though. Would be nice if `ctx.build` existed as the alias.

This is obviously super minor, but it does feel like the "re" of `rebuild` is pretty context dependent.

**Comment by evanw** [comment]
I believe the existing `build` function may already be the shortcut you are looking for.

```js
if (process.env.WATCH) {
    esbuild.context(opts).then(c => c.watch())
} else {
    esbuild.build(opts)
}
```

**Comment by rtpg** [comment]
Yeah... I guess it's more that I like the concept of using a context from top to bottom. Purely an aesthetics request as, like you said, I can call `esbuild.build`. I think I'll just opt for that.

(personal opinion time: If I were the only person on the planet I would definitely name `ctx.rebuild` as `ctx.build` outright)

**Comment by evanw** [comment]
Ok. Thanks for the suggestion. I'm not planning on changing the API at this time, so I'm going to close this issue.
