### ISSUE TITLE
Is it possible to set custom name for each entry

### ISSUE THREAD

**Issue by coderaiser** [evanw/esbuild#2878]
I see that there is [`entry-names`](https://esbuild.github.io/api/#entry-names), and I can set it to:

```js
import * as esbuild from 'esbuild'

await esbuild.build({
  entryPoints: ['src/main-app/app.js'],
  entryNames: '[dir]/[name]-[hash]',
  outbase: 'src',
  bundle: true,
  outdir: 'out',
})
```

Here is my config:

```js
import * as esbuild from 'esbuild'

const dir = './client';
const dirModules = './client/modules';

await esbuild.build({
  entryPoints: [
        `${dir}/cloudcmd.js`,
        `${dirModules}/edit.js`,
        `${dirModules}/edit-file.js`,
        `${dirModules}/edit-file-vim.js`,
        `${dirModules}/edit-names.js`,
        `${dirModules}/edit-names-vim.js`,
        `${dirModules}/menu.js`,
        `${dirModules}/view/index.js`,
        `${dirModules}/help.js`,
        `${dirModules}/markdown.js`,
        `${dirModules}/config/index.js`,
        `${dirModules}/contact.js`,
        `${dirModules}/upload.js`,
        `${dirModules}/operation/index.js`,
        `${dirModules}/konsole.js`,
        `${dirModules}/terminal.js`,
        `${dirModules}/terminal-run.js`,
        `${dirModules}/cloud.js`,
        `${dirModules}/user-menu/index.js`,
        `${dirModules}/polyfill.js`,
        `${dirModules}/command-line.js`,

        'css/columns/name-size-date.css',
        'css/columns/name-size.css',
  ],
  entryNames: '[dir]',
  bundle: true,
  minify: true,
  sourcemap: true,
  target: ['chrome100'],
  alias: {
    path: 'path-browserify',
  },
  outdir: 'dist',
    loader: {
      '.png': 'dataurl',
      '.gif': 'dataurl',
      '.woff': 'dataurl',
      '.woff2': 'dataurl',
      '.ttf': 'dataurl',
      '.eot': 'dataurl',
      '.svg': 'text',
    }
})


```

I want to have files `view.js` and `help.js` generated in my `outdir`. So I can use them without knowing whether it has `/index.js` or not.

I achieved this with [webpack](https://github.com/coderaiser/cloudcmd/blob/v16.13.0/.webpack/js.js#L75-L97) since it uses key-value pairs, but I cannot migrate to v5 because old plugins unsupported and new [do not supports what I need](https://github.com/webpack-contrib/mini-css-extract-plugin/issues/1013) while developing [Cloud Commander](https://cloudcmd.io).

So I think about migrating to `esbuild`, but I need to have ability to set custom names to my `entryPoints` to reuse existing loading process.

Maybe I missing something, could you please help me?

**Comment by evanw** [comment]
https://esbuild.github.io/api/#entry-points:

> In addition, you can also specify a fully custom output path for each individual entry point using an alternative entry point syntax

**Comment by evanw** [comment]
I'm closing this issue because the answer to this question is already in the documentation.
