### ISSUE TITLE
[Question/FeatureRequest] : Is it possible to programmatically resend the server esbuild event?

### ISSUE THREAD

**Issue by benny00100** [evanw/esbuild#2882]
Hi,

I have the following use case. My esbuild script watches my project using the live-reload logic with the proxy example from the documentation (`version 0.17.5`).

All runs fine. The projects reloads automatically when one of the entry-files changes.

In addition, I am watching some other files outside of the actual esbuild configuration using `fs.watchFile(externalFile)`. When this external file gets changed, I am forcing a rebuild with `await ctx.rebuild()`.

This workd fine, however the `esbuild` server event is not fired again.

Is there a command/workaround like for example `ctx.fireEsbuildEvent` ? Or could someone point me into the direction of implementing such behaviour by myself?

Thanks in advance!

**Comment by evanw** [comment]
The `change` event has nothing to do with watch mode. It can potentially be sent after every build, independent of whether watch mode is active or not. But the `change` event is only sent when the build outputs change. If the build outputs don't change then no `change` event is sent. If you want your server to send a separate signal to your code about something else other than a change in the build outputs, then you have to wire that up yourself.

**Comment by benny00100** [comment]
@evanw Thanks for explaining the behaviour. Pretty clever that the `change` event is only sent when the re-build process detects acutal changes. 
All fine. I will wire it up for myself for my project. Thanks again!
