### ISSUE TITLE
The service is no longer running on long running node.js process

### ISSUE THREAD

**Issue by fbuecklers** [evanw/esbuild#2884]
Hi,

we have a long-running esbuild process running in our Backend and are experience sometimes the following issue:
The service is no longer running

We know already that this can happen if the OOM is killing the esbuild child process or a bug is crashing the process etc.
Nevertheless, the crash process will not be restarted anymore until we are completely restarting the node.js process.

This seems to be coming from the following code part:
https://github.com/evanw/esbuild/blob/362cae86f435fd9dc823e6f355fcfa4ec92cb5b3/lib/npm/node.ts#L248

It looks like that we always get the same global `longLivedService` object even if the closed/error callbacks on the connection were called already. And since it is a module global variable, this can't be recovered anymore without restarting the node process. 

Is there any reason why this is implemented like that, since the fix for it sounds quite easy by just setting the global variable to null back, if the close/error handler is invoked. 

Thanks in advance

**Comment by evanw** [comment]
> Is there any reason why this is implemented like that, since the fix for it sounds quite easy by just setting the global variable to null back, if the close/error handler is invoked.

No thought has been given to making the library reentrant in that way. So doing this would also require auditing esbuild's various JS API implementations (node, Deno, WASM, browser) to make sure that doing this works and doesn't leak memory.

**Comment by evanw** [comment]
I'm closing this issue because I do not plan to do this.
