### ISSUE TITLE
Which is better, deno-esbuild or the Node version via Deno's npm shim?

### ISSUE THREAD

**Issue by callumlocke** [evanw/esbuild#2887]
I noticed there's an official Deno version of esbuild ([GitHub](https://github.com/esbuild/deno-esbuild), published to [Deno X](https://deno.land/x/esbuild@v0.17.5)), and it seems to use WebAssembly. But the readme is minimal.

As of Deno 1.25 (I think) it's also possible to use the Node version of esbuild in Deno, via `import esbuild from 'npm:esbuild'`.

Which is recommended for use in Deno? On the one hand it seems the official deno-esbuild must be preferable to using the Node version via Deno's npm shim, because it's 'official', and it avoids using the magic shim (which also still requires the `--unstable` flag, at least when it's used in remote modules). But on the other hand, I'm guessing it must be quite a bit slower as it uses WASM, while the Node version uses a native binary?

**Comment by evanw** [comment]
I’m not sure! I don’t use Deno myself. What do you think is better?

Both node and Deno have native and WASM versions. So I assume your Deno code can import from either `https://deno.land/x/esbuild/mod.js` or `npm:esbuild` for native and either `https://deno.land/x/esbuild/wasm.js` or `npm:esbuild-wasm` for WASM (I haven’t tested this myself). So the WASM or not question would then be independent of your original question. You generally should be using the native version unless you have specific requirements that force you to use the WASM version. Note that esbuild’s Deno implementation is documented on esbuild’s website: https://esbuild.github.io/getting-started/#deno.

**Comment by callumlocke** [comment]
> Deno code can import from either https://deno.land/x/esbuild/mod.js [...] for native

Ah ok, I thought the pure-Deno version was WASM-only? If not, that's great news!

But I'm confused... [deno-esbuild](https://github.com/esbuild/deno-esbuild) doesn't seem to include any binaries except the WASM one. Where/how does it get the appropriate native binary for the system? (I know the npm version uses a postinstall script to download the appropriate binary for your system, but AFAIK postinstall is not a thing in Deno.)

btw ESBuild is amazingly fast, correct, and well put together, thanks for making it. It's making life good for me.

**Comment by evanw** [comment]
> Where/how does it get the appropriate native binary for the system?

The source code is here:

https://github.com/evanw/esbuild/blob/bfe3ead93e3326bf708854a784b9e8b71d8978c2/lib/deno/mod.ts#L141-L168

The Deno code does the same thing as the node code, essentially.

**Comment by callumlocke** [comment]
Not sure how I missed that section when I skimmed it. So if I understand correctly, it does the same thing as Node, except I guess it does it at runtime (on first run only) rather than on postinstall. Please correct me if I'm wrong.

To your question from before:

> I don’t use Deno myself. What do you think is better?

Now that I understand the Deno version is not WASM-only, I'd say definitely your official deno.land/x package should be recommended over `npm:esbuild`. It's nice that importing `npm:esbuild` seems to work seamlessly, but I imagine Deno's Node-compat magic must add some overhead (and surface area for bugs, extra soucemapping steps etc).
