### ISSUE TITLE
Bug: incorrect re-export got empty module

### ISSUE THREAD

**Issue by shigma** [evanw/esbuild#2896]
<img width="869" alt="image" src="https://user-images.githubusercontent.com/33423008/217061697-74b06678-d04c-4fbd-885b-6bdfee14759a.png">

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/33423008/217061801-762cf423-f2f8-4dee-90dc-a645627ee8d1.png">

The source code is in the form of ESM.

The generated `__reExport` comes before the `import` statement, which leads to empty module `core_exports`.

**Comment by shigma** [comment]
<img width="843" alt="image" src="https://user-images.githubusercontent.com/33423008/217063239-dc6cdcaf-38df-4347-96ad-ad5c64225f3f.png">

Another output behaves right. I don't know what is the difference between them.

**Comment by evanw** [comment]
> The generated `__reExport` comes before the `import` statement, which leads to empty module `core_exports`.

JavaScript always evaluates all `import` statements before any other code in the file, so the ordering of `import` statements with other code is irrelevant. In the JavaScript specification, imports run during the "link" phase and other code runs during the "evaluate" phase.

**Comment by shigma** [comment]
> JavaScript always evaluates all `import` statements before any other code in the file, so the ordering of `import` statements with other code is irrelevant. In the JavaScript specification, imports run during the "link" phase and other code runs during the "evaluate" phase.

Thanks for your explanation. You are right. 🤣
