### ISSUE TITLE
Sourcemap option not supported by transform API, but docs say it is

### ISSUE THREAD

**Issue by callumlocke** [evanw/esbuild#2906]
I get a TypeScript error when I try to use the `sourcemap` option with `.transform()`. The option doesn't seem to exist on that API. But the docs say that it should be supported, [here](https://esbuild.github.io/api/#transform) and [here](https://esbuild.github.io/api/#sourcemap).

**Comment by daychongyang** [comment]
Can you provide additional information about this error？https://github.com/evanw/esbuild/blob/main/lib/shared/types.ts#L235

**Comment by evanw** [comment]
This works fine. Here's what I tried, which does not cause any TypeScript errors:

```ts
import esbuild from 'esbuild'
esbuild.transform('', { sourcemap: true })
```

Marking this as `unactionable` as there is nothing to be done here.

**Comment by evanw** [comment]
I'm closing this issue because it's currently unactionable (a way to reproduce the issue was not provided). We can reopen this issue later if enough additional information is provided.

**Comment by callumlocke** [comment]
Seems I didn't check my setup carefully enough before opening an issue, sorry for wasting your time.
