### ISSUE TITLE
Minifying JavaScript with Unicode identifiers next to keywords produces syntax error

### ISSUE THREAD

**Issue by satgo1546** [evanw/esbuild#2910]
```sh-session
$ esbuild --version
0.17.7
$ cat index.js
a.π in a
$ esbuild index.js --minify --charset=utf8
a.πin a;
$ node -e 'a.πin a;'
[eval]:1
a.πin a;
      ^

SyntaxError: Unexpected identifier 'a'
    at ...
```

The same goes for other keywords such as `of` and `instanceof`.

Meanwhile, the problem is mitigated by `--charset=ascii`.

```sh-session
$ esbuild index.js --minify
a.\u03C0 in a;
```

**Comment by evanw** [comment]
Thanks for the report. Looks like esbuild is only looking at the previous byte for this, which is incorrect for Unicode. I’ll fix this in the next release.
