### ISSUE TITLE
Swagger API documentation is broken in esbuild bundle

### ISSUE THREAD

**Issue by MatsG23** [evanw/esbuild#2915]
When I use [Fastify](https://www.fastify.io) in combination with Swagger, the API documentation can not be accessed when running the bundle file by esbuild.

When I run the bundle file, I can see this error in the console:
```
"root" path "[path to one level above the project folder]/static" must exist
```
Trying to access the API documentation at `http://localhost:3000/documentation` then fails with a 404 HTTP error. The documentation thing when I run the unbundled code project. 
My guess is that the code in the bundle somehow infers with the [`@fastify/swagger` dynamic documentation generation](https://github.com/fastify/fastify-swagger#dynamic) so that the output path for the Swagger documentation HTML page is incorrect.

You can easily reproduce the issue in this project (further instructions given): https://github.com/MatsG23/esbuild-issue

**Comment by evanw** [comment]
Here's what the first page of esbuild's documentation says about [bundling for node](https://esbuild.github.io/getting-started/#bundling-for-node):

> You also may not want to bundle your dependencies with esbuild. There are many node-specific features that esbuild doesn't support while bundling such as `__dirname`, `import.meta.url`, `fs.readFileSync`, and `*.node` native binary modules. You can exclude all of your dependencies from the bundle by setting [packages](https://esbuild.github.io/api/#packages) to external:
>
> ```
> esbuild app.jsx --bundle --platform=node --packages=external
> ```

I'm closing this issue because esbuild is already working as expected. The answer to your question is already in the documentation.

**Comment by evanw** [comment]
No, I don’t plan on doing this.
