### ISSUE TITLE
posibility of file replacement in build process

### ISSUE THREAD

**Issue by DerHerrGammler** [evanw/esbuild#2916]
I am new to esbuild and came from webpack.  
I try to find a way to do a file replacement in my configurations just like the webpack `fileReplacements` array. Is there currently a way of doing this?

If there is currently no way of doing this it would be a good feature for esbuild

**Comment by evanw** [comment]
You can write a plugin to do that: https://esbuild.github.io/plugins/

**Comment by evanw** [comment]
I'm closing this issue because this is not a bug with esbuild.
