### ISSUE TITLE
Error on trying to set `wasmModule` in `esbuild-wasm`

### ISSUE THREAD

**Issue by okikio** [evanw/esbuild#2918]
When trying to set a custom `wasmModule` in `esbuild-wasm` I get this new error 

<img width="971" alt="image" src="https://user-images.githubusercontent.com/17222836/218668684-b053525d-1a56-437c-a219-0b047ca2c3d9.png">

But in previous versions of `esbuild-wasm`, custom `wasmModule`'s worked on Deno, Bun, and Node.

Looking further into the code it doesn't seem like we ever even check to see if the user is on a browser, so this restrictions seems odd.

<img width="368" alt="image" src="https://user-images.githubusercontent.com/17222836/218669120-b3b2a70d-3941-4b08-a16d-869e87969f6d.png">

<img width="368" alt="image" src="https://user-images.githubusercontent.com/17222836/218669182-b76f5300-7f99-4435-88fb-970707e65a1d.png">

<img width="535" alt="image" src="https://user-images.githubusercontent.com/17222836/218669321-025167c0-6306-41b6-88a8-6f8f264108c4.png">

**Comment by evanw** [comment]
There is a completely separate entry point for the browser: https://github.com/evanw/esbuild/blob/d8b028fc62bb6a4115a841b9ba9d0c747a0d54d1/npm/esbuild-wasm/package.json. That’s why the code for node doesn’t need to do browser checks.

**Comment by okikio** [comment]
You may want to update the docs then 
<img width="900" alt="image" src="https://user-images.githubusercontent.com/17222836/218800227-c18f88ec-bb0b-414d-b84e-9f4cd996aa34.png">

**Comment by evanw** [comment]
This is assuming `--platform=browser` which is esbuild’s default behavior. It won’t work when you use `--platform=node`, but you also shouldn’t be using `--platform=node` to build code that will run in the browser.

**Comment by okikio** [comment]
Interesting, I'll take a look thanks for the support, I'll close this issue
