### ISSUE TITLE
Is there any examples using esbuild with configure react ssr app using `renderToPipeableStream` ? 

### ISSUE THREAD

**Issue by dante01yoon** [evanw/esbuild#2920]
it gives me hydration error in console.log
`Uncaught Error: Hydration failed because the initial UI does not match what was rendered on the server.`

I wonder esbuild can't be used to build ssr app.

**Comment by hyrious** [comment]
I guess you just have to follow the doc: https://beta.reactjs.org/reference/react-dom/server/renderToPipeableStream then let esbuild to compile your jsx server code into js so that node.js could run it.

**Comment by dante01yoon** [comment]
> 

thanks to your previous answer about [this issue](https://github.com/evanw/esbuild/issues/2893#issuecomment-1420083228), I could acquire build ssr app with renderToString, but seems not working with `renderToPipeableStream`.  I  wonder esbuild [can't support hydration](https://github.com/evanw/esbuild/issues/2893#issuecomment-1419395821) with `renderToPipeableStream` or not. 

> React hydration for SSR is not an intended use case for esbuild. You may need to use another tool instead that has been designed to do that.

**Comment by evanw** [comment]
To answer your original question: No, there are no examples of using esbuild to configure a React SSR app using `renderToPipeableStream` in esbuild’s documentation. You will have to debug this issue with your code yourself.

**Comment by dante01yoon** [comment]
> To answer your original question: No, there are no examples of using esbuild to configure a React SSR app using `renderToPipeableStream` in esbuild’s documentation. You will have to debug this issue with your code yourself.

I see. I'm confuse hydration should be worked or not  via esbuild.

**Comment by evanw** [comment]
I'm closing this issue because this isn't a bug report. Or at least, it seems like a question and it's not clear that esbuild is doing anything wrong here. If you believe this to be a bug with esbuild, then you'd need to provide a small self-contained example that demonstrates the bug.

**Comment by dante01yoon** [comment]
> I'm closing this issue because this isn't a bug report. Or at least, it seems like a question and it's not clear that esbuild is doing anything wrong here. If you believe this to be a bug with esbuild, then you'd need to provide a small self-contained example that demonstrates the bug.

sure. thanks a lot.
