### ISSUE TITLE
Bundle Size Analyzer - repository & project

### ISSUE THREAD

**Issue by akupiec** [evanw/esbuild#2926]
Main questions: 
1. Where can I find bundle analyzer sources?

Short explanation: 

I wanted to create single analyzer on steroids for both webpack & esbuild version, then I noticed that esbuild analyzer works almost as I initially intended ^_^ 
Therefore I basically wanted to steal(fork) it :) 

Side questions for the creator/maintainers:

1. Did you consider creating group(organization) for repositories related to esbuild? Like documentation/analyzer/esbuild/some plugins.  
I have noticed there are a few open issues just for an analyzer :)
3. Is there some community group/chat/mailing list - other then github issues? ^_^

**Comment by lydell** [comment]
I think it’s here: https://github.com/esbuild/esbuild.github.io/tree/main/src/analyze#bundle-size-analyzer

**Comment by evanw** [comment]
Yes, that's the source code for the website. Note that there's no license, however, and the website source code is not intended for reuse.

> 1. Did you consider creating group(organization) for repositories related to esbuild?

Yes. This is why https://github.com/esbuild exists.

> 2. Is there some community group/chat/mailing list - other then github issues?

No.

**Comment by akupiec** [comment]
1. > Yes. This is why https://github.com/esbuild exists.

Did you consider transferring evanw/esbuild to esbuild group ? [transferring-a-repository](https://docs.github.com/en/repositories/creating-and-managing-repositories/transferring-a-repository)

2. Ok I understand. I just feel uncomfortable creating such generic "issues" just to ask some questions.

3. > Note that there's no license, however, and the website source code is not intended for reuse.

Please reconsider adding licence at least for analyzer :)
