### ISSUE TITLE
Exposed 0.0.0.0:8000 network is not reachable

### ISSUE THREAD

**Issue by Valexr** [evanw/esbuild#2928]
Started esbuild serve() by default & `192.168.88.<some>:8000` on other devices in local network is not reachable🤷🏻‍♂️

**Comment by evanw** [comment]
I'm marking this as unactionable because this issue lacks reproduction instructions. I do this all the time myself (use esbuild as a server and access it from other devices) so your description is insufficient to reproduce the issue.

**Comment by Valexr** [comment]
repo for reprodaction https://github.com/Valexr/esbuild-svelte-ts

**Comment by evanw** [comment]
Sorry but I still don't think there's anything I can do with this issue report. Like I said, using esbuild as a web server between machines works for me.

I'm guessing you're having a local network configuration issue. You'll need to debug that on your end. Some options for debugging this include the `ping` command and also setting up a local non-esbuild server on the problematic machine.

**Comment by Valexr** [comment]
Vite, serve or http-server (for example) very well expose server to local network in my configuration 👌🏻

I think maybe needed firewall rules, but I’m turn it fully off with no results 🤔

**Comment by Valexr** [comment]
![Screenshot 2023-02-16 at 15 10 18](https://user-images.githubusercontent.com/5656366/219361273-a8577875-4075-4e5b-9878-23416251857a.jpg)

5555 - vite
8000 - esbuild

**Comment by Valexr** [comment]
My bad 😁 added esbuild to firewall rule 👌🏻
