### ISSUE TITLE
IIFE globalName does not support namespacing via '.'

### ISSUE THREAD

**Issue by ggoodman** [evanw/esbuild#293]
When using a namespced `globalName` invalid javascript is emitted:

```
esbuild --globalName=A.B --format=iife
```

Produces the following invalid JavaScript:
```js
var A.B = (() => {
 // ...
})();
```

The use-case for something like this is supporting suites of related libraries exporting their own exports within a partitioned, common namespace.

I've hacked around this for the time being with:

```
esbuild --globalName="A = A || {}; A.B" --format=iife
```

**Comment by evanw** [comment]
Just did a quick survey of other tools. It looks like Rollup is the only tool that supports this. Parcel exports to `this["A.B"]` instead and Webpack crashes in the minifier with invalid JavaScript.

Parcel's behavior seems the most correct to me. I also found this issue where someone is having problems with the way Rollup does it: https://github.com/rollup/rollup/issues/1473. I'll have to think about what to do here.

**Comment by ggoodman** [comment]
It would be neat if the ultimate solution continued to have an escape hatch so that this behaviour remains possible.

**Comment by ggoodman** [comment]
🙇  amazing!
