### ISSUE TITLE
The platform "darwin" is incompatible with this module

### ISSUE THREAD

**Issue by mrleblanc101** [evanw/esbuild#2932]
---
- Operating System: Darwin
- Node Version:  v16.14.0
- Package Manager:  yarn@1.22.15
---
Using yarn, I get hundred of info log from saying this in my Nuxt 3 project wan I run `yarn install`
> info @esbuild/android-arm@0.17.8: The platform "darwin" is incompatible with this module.
![image](https://user-images.githubusercontent.com/17392251/219574503-5b28c643-365e-48f3-bf52-c52d2e510fd4.png)

Related: https://github.com/nuxt/nuxt/issues/19104

**Comment by evanw** [comment]
This is because you’ve chosen to use a really old version of Yarn with lots of useless log messages. Newer versions of Yarn don’t have this problem. You should upgrade if you don’t want to see them. Otherwise you can ignore them. 

I’m closing this because it’s not a problem with esbuild.

**Comment by mrleblanc101** [comment]
Seems like it was using an old yarn version inside my `nvm` folder instead of the version installed via HomeBrew which was up to date.
