### ISSUE TITLE
Why does @tensorflow/tfjs-node now require node-pre-gyp with esbuild?

### ISSUE THREAD

**Issue by jambudipa** [evanw/esbuild#2935]
I had previously been using `tsc` to build my app, which uses `@tensorflow/tfjs-node`. No problems. Now, I have introduced `esbuild`, and suddenly `@tensorflow/tfjs-node` has decided it needs:

- aws-sdk
- nock
- mock-aws-s3

I installed these directly, but receive the following error on running:
>Error: @package/learn package.json is not node-pre-gyp ready:
package.json must declare these properties:
binary

It was all fine before: why does switching to `esbuild` now mean this library is needed, which it doesn't seem to like?

**Comment by evanw** [comment]
I don't know, sorry.

**Comment by evanw** [comment]
Yes, that’s me. But I’ve never used `node-pre-gyp` before and I don’t know anything about it.

**Comment by appocalypseltd** [comment]
Oh, well it is required by one of those three libraries; but they are unnecessary when building with tsc. Using esbuild, it falls over. Strange. I will dig around more tomorrow.

**Comment by evanw** [comment]
In case it helps: You can tell esbuild to omit a package from a bundle with the `external` feature: https://esbuild.github.io/api/#external

**Comment by Inqnuam** [comment]
@appocalypseltd is your NodeJS version compatible with all your dependencies ?

**Comment by jambudipa** [comment]
@Inqnuam Yes it is. As I say, it builds fine with `tsc`. @evanw I will look into the `external` option, thanks.

**Comment by evanw** [comment]
I'm marking this issue as `unactionable` because I don't think I can do anything with this report.

**Comment by evanw** [comment]
I'm closing this because it's been `unactionable` for a week without a follow-up reply.
