### ISSUE TITLE
watch mode aborts loop on plugin errors

### ISSUE THREAD

**Issue by martinpitt** [evanw/esbuild#2939]
We are trying to [port one of our projects to esbuild](https://github.com/cockpit-project/cockpit-podman/pull/1210) from webpack. We have eslint and styleint in our build chain, and CI should enforce that they pass, i.e. `node build.js` should fail if there are any stylelint/eslint errors. This would normally be done with something like

```js
build.onEnd(() => {
    if (/*... there are some errors ... */) 
        return {
            errors: [{ pluginName: 'stylelint', text: 'stylelint errors found' }]
        };
    else
       return null;
}
```

This works fine for single-shot build mode, `node build.js` exits with nonzero and a (annoyingly noisy, but readable) error:
```
/var/home/martin/upstream/kk-esbuild/src/ContainerLogs.jsx
  21:7  error  Multiple spaces found before 'PropTypes'  no-multi-spaces

✖ 1 problem (1 error, 0 warnings)
  1 error and 0 warnings potentially fixable with the `--fix` option.

✘ [ERROR] ESLint errors found [plugin eslintPlugin]

/var/home/martin/upstream/kk-esbuild/node_modules/esbuild/lib/main.js:1636
  let error = new Error(`${text}${summary}`);
              ^

Error: Build failed with 1 error:
error: ESLint errors found
    at failureErrorWithLog (/var/home/martin/upstream/kk-esbuild/node_modules/esbuild/lib/main.js:1636:15)
    at /var/home/martin/upstream/kk-esbuild/node_modules/esbuild/lib/main.js:1048:25
    at /var/home/martin/upstream/kk-esbuild/node_modules/esbuild/lib/main.js:1512:9
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    {
      id: '',
      pluginName: 'eslintPlugin',
      text: 'ESLint errors found',
      location: null,
      notes: [],
      detail: -1
    }
  ],
  warnings: []
}

Node.js v18.12.1
```

However, this breaks watch mode, i.e. with `await context.watch()`: As soon as there are any errors, the watch loop aborts with the same error as above. This is not intended -- of course during development you are going to make lots of linter and other errors, the point is to quickly rebuild them after code changes and saving.

So, can errors be shown with less noise, and not interrupt the watch loop?

A workaround report these in `warnings` -- that doesn't break the watch loop, but it will also make the build *not* fail. So I [added a hack](https://github.com/cockpit-project/cockpit-podman/pull/1210/commits/0619949df410aed49fcd66467b4ecf153d3dc05f) which uses "warnings" in watch mode and "errors" in single-shot build mode. But it depends on an environment variable (which we set in our `package.json`), so it's not a very localized fix. I didn't see a way to tell from within the plugin whether esbuild is in watch mode or not.

Thanks for considering!

**Comment by evanw** [comment]
> So, can errors be shown with less noise, 

I assume the noise you're talking about is the exception stack trace that node shows? That's not esbuild-specific. Any JavaScript code that throws an error will cause node to do that. If you don't want to see node's stack trace then you need to handle the exception yourself.

For example:

```js
esbuild.build(options).catch(() => process.exit(1))
```

> and not interrupt the watch loop?

I'm not able to reproduce this. Here's what I tried:

```js
const esbuild = require('esbuild')
const fs = require('fs')

let count = 0
setInterval(() => fs.writeFileSync('x.ts', ++count % 2 ? 'error' : 'success'), 250)

esbuild.context({
  entryPoints: ['x.ts'],
  bundle: true,
  write: false,
  logLevel: 'info',
  plugins: [{
    name: 'x',
    setup(build) {
      build.onEnd(result => {
        if (result.outputFiles[0]?.text.includes('error'))
          return {
            errors: [{ pluginName: 'stylelint', text: 'stylelint errors found' }]
          };
        else
          return null;
      })
    },
  }],
}).then(ctx => ctx.watch())
```

That prints the following in a loop forever:

```
[watch] build finished, watching for changes...
✘ [ERROR] Could not resolve "x.ts"

1 error
[watch] build started (change: "x.ts")
✘ [ERROR] stylelint errors found [plugin stylelint]

1 error
[watch] build finished
[watch] build started (change: "x.ts")
[watch] build finished
[watch] build started (change: "x.ts")
✘ [ERROR] stylelint errors found [plugin stylelint]

1 error
[watch] build finished
[watch] build started (change: "x.ts")
[watch] build finished
[watch] build started (change: "x.ts")
✘ [ERROR] stylelint errors found [plugin stylelint]

1 error
[watch] build finished
[watch] build started (change: "x.ts")
[watch] build finished
[watch] build started (change: "x.ts")
✘ [ERROR] stylelint errors found [plugin stylelint]

1 error
...
```

**Comment by martinpitt** [comment]
> I assume the noise you're talking about is the exception stack trace that node shows?

Right.

> That's not esbuild-specific. Any JavaScript code that throws an error will cause node to do that.

Sure, but the plugin isn't throwing an exception. Returning `{errors: [...], warnings: [...]}` is a (1) technically not an exception but a successful value, and (2) semantically, a statement about the processed code, not about esbuild/build.js/the plugin encountering a bad situation. I.e. that  `let error = new Error(`${text}${summary}`);` is a conscious decision in esbuild.ts to format these as an `Error` (with a traceback).

> Here's what I tried:

Interesting, thanks! Indeed that does not cause the `Error` traceback nor the stopping of the watch loop for me either.

This was a bug in our build.js, which called `context.rebuild()` even when in watch mode:

```diff
--- build.js
+++ build.js
@@ -61,10 +61,9 @@ const context = await esbuild.context({
     ]
 });
 
-// Manually do an incremental build
-await context.rebuild();
-
 if (watchMode)
     await context.watch();
-else
+else {
+    await context.rebuild();
     context.dispose();
+}
```

Now it works perfectly, thank you and sorry for the noise!
