### ISSUE TITLE
Async function get compiled with generators even when targetting es6

### ISSUE THREAD

**Issue by ninofiliu** [evanw/esbuild#2944]
# my issue

Inside a webpack + esbuild-loader + esbuild + vue + react stack I target es6 but my async functions still get transpiled into generators invoked by the `__async` helper, for example:

source code

```ts
export async function setViewAs(newViewAs?: ViewAs): Promise<void> {
  currentViewAs = newViewAs;
  await Promise.all(
    viewAsSubscribers.map((callback) => {
      callback(newViewAs);
    }),
  );
}
```

transpiled code

```ts
var __async = (__this, __arguments, generator) => {
  return new Promise((resolve, reject) => {
    // ...
    step((generator = generator.apply(__this, __arguments)).next());
  });
};
function setViewAs(newViewAs) {
  return __async(this, null, function* () {
    currentViewAs = newViewAs;
    yield Promise.all(viewAsSubscribers.map((callback) => {
      callback(newViewAs);
    }));
  });
}
```

I'm targetting an ES version which supports promises so I shouldn't be needing that, also this transpilation, while not buggy, complexifies debugging using the devtools because it adds a lot of scopes and functions in the call stack that don't exist in the source code.

# my question

Is there any configuration option to disable the use of `__async` and keep async functions as they are when being transpiled by esbuild?

# additional infos

- esbuild version: 0.14.19
- esbuild-loader version: 2.18.0
- relevant webpack config excerpt:
  ```ts
  module.exports = {
    module: {
      rules: [
        {
          test: /\.js$/,
          loader: 'esbuild-loader',
          options: {
            target: 'es2015',
          },
        },
        {
          test: /\.tsx?$/,
          loader: 'esbuild-loader',
          options: {
            loader: 'tsx',
            target: 'es2015',
          },
        },
      ],
    }
  };
  ```

# links

I'm not 100% sure what's adding these `__async` or if it's even esbuild, but here's a few links I don't fully understand that seem to be related:

- https://github.com/evanw/esbuild/blob/5d80704f1c64213da83c5f18d6f95255ccdff86e/CHANGELOG-2022.md#01432
- https://github.com/evanw/esbuild/blob/f22c5132e3116288ce2782759f4cbb039ef6a136/internal/runtime/runtime.go#L329
- https://github.com/evanw/esbuild/blob/5fe21253ee75fb4c5ea395a0877b2a5ab51c3575/internal/js_parser/js_parser_lower.go#L500
- https://github.com/Aliucord/AliucordRN/blob/2b8e2eca038b2551d89e0da771e248c0add20f65/src/utils/misc.ts#L8

**Comment by jridgewell** [comment]
ES6/ES2015 doesn't support native async await, it wasn't added until ES2017.

**Comment by ninofiliu** [comment]
Oh really? I always thought is was added in es2015. My bad. Let me target es2017 and see what is being transpiled

**Comment by ninofiliu** [comment]
Yessss that transpiles into native async/await. Thanks @jridgewell ! 

```ts
// transpiled code
async function setViewAs(newViewAs) {
  currentViewAs = newViewAs;
  await Promise.all(viewAsSubscribers.map((callback) => {
    callback(newViewAs);
  }));
}
```
