### ISSUE TITLE
transformSync prunes imports with treeShaking: false

### ISSUE THREAD

**Issue by 0x5424** [evanw/esbuild#2948]
On version 0.17.10, `transformSync` automatically prunes unused default/const imports, even with treeShaking set to false.

Perhaps this is moreso a question of expected behavior. According to the [docs](https://esbuild.github.io/api/#transform) the transform environment is isolated--so my assumption was disabling tree-shaking would keep unused dependencies in the output code...

I provided a small reproduction repo to clarify further:
https://github.com/0x5424/esbuild-repro

```
┌──────────┬─────────────────────────────────────────────────────────────────────────┐
│ (index)  │                                 Values                                  │
├──────────┼─────────────────────────────────────────────────────────────────────────┤
│  Actual  │              'export const TestFn = () => "Transpiled";\n'              │
│ Expected │ 'import React from "react";export const TestFn = () => "Transpiled";\n' │
└──────────┴─────────────────────────────────────────────────────────────────────────┘
```

**Comment by evanw** [comment]
The behavior you are observing is how TypeScript is supposed to work. [TypeScript automatically removes all unused imports during the conversion to JavaScript.](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4kAPSWONCAOwGd4AVJZgMXrgF44AKAJQAuOMyjB6Ac14A+AiygomYYABskAE3xA) This is the behavior that the TypeScript team picked out for their language, and is not something that is up to esbuild to change.

If you want TypeScript to not do that, then you have to explicitly tell it not to. TypeScript has several ways of doing that. One is the [`preserveValueImports` option](https://www.typescriptlang.org/tsconfig#preserveValueImports) and another one is the [`importsNotUsedAsValues` option](https://www.typescriptlang.org/tsconfig#importsNotUsedAsValues). You can pass TypeScript options to esbuild using a `tsconfig.json` file: https://esbuild.github.io/api/#tsconfig-raw.

The reason why esbuild's tree-shaking setting doesn't affect this is that first esbuild transforms TypeScript into JavaScript, then esbuild applies (or doesn't apply) tree shaking to the resulting JavaScript.

**Comment by 0x5424** [comment]
Thanks for the succinct explanation! I had assumed it was related to esbuild since I provided no tsconfig, but it's just the default TS behavior 😅
