### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by irhamputra** [evanw/esbuild#295]
Hi creator 👋🏼

I just wanna say thank you for build this cool project and I've been waiting for this project.
I've been playing around and I tried build with React TS and deploy to Vercel and this is extremely fast 🤯.
I put my playground here 
Source code: https://github.com/irhamputra/react-esbuild
Live: https://react-esbuild.vercel.app/

Sorry I can't contribute to your project or help you.

thanks a lot and have a great day

**Comment by evanw** [comment]
You're welcome! Thanks for stopping by and for giving a new tool a chance.
