### ISSUE TITLE
which file watcher does ESBuild use?

### ISSUE THREAD

**Issue by WagnerMoreira** [evanw/esbuild#2953]
title, I'm just curious, I checked the code I don't know go, so it's a bit hard to understand what's going on
I've seen people having issues with the file changes not being picked up, it doesn't seem like esbuild use watchman

**Comment by evanw** [comment]
https://esbuild.github.io/api/#watch

> Watch mode in esbuild is implemented using polling instead of OS-specific file system APIs for portability.

**Comment by evanw** [comment]
I'm closing this issue because this is a question, not a bug report, and the answer is already in the documentation.
