### ISSUE TITLE
Shimming (global)

### ISSUE THREAD

**Issue by ComLock** [evanw/esbuild#296]
I'm compiling for an environment where neither global, nor window exist. (So not node, nor the browser)

With webpack I'm able to shim
https://webpack.js.org/guides/shimming/

...my own global by using the ProvidePlugin
https://webpack.js.org/plugins/provide-plugin/

Here is an example myGlobal.es:
const global = (1, eval)('this');
global.crypto = { getRandomValues: require('polyfill-crypto.getrandomvalues') };
module.exports = global;

Is this something that will somehow be possible soon?

**Comment by evanw** [comment]
What's the environment? If `globalThis` is available, you could potentially use `--define:global=globalThis --define:window=globalThis`.

I think inserting a shim should be possible by just importing the shim at the top of the entry point file. Otherwise, this issue looks like a request for the same feature as #53.

**Comment by ComLock** [comment]
The environment is Java Nashorn (inside the product Enonic XP).

I had not heard about globalThis. I will look into it tomorrow.

**Comment by ComLock** [comment]
I couldn't wait. It turns out neither globalThis nor self is defined.

**Comment by ComLock** [comment]
BTW '--define:global=this' gives "Invalid define value".

Is a define that accepts for javascript code a good idea?

--define:global=(1, eval)('this')

**Comment by ComLock** [comment]
I was trying to write the shim code inside the entry file, but of course imports will get ordered first.
As soon as I put my shim in a separate file and imported it instead, things work :)

**Comment by ComLock** [comment]
In case someone else needs it, here is the shim that works for me:

`const global = (1, eval)('this'); // https://stackoverflow.com/questions/9107240/1-evalthis-vs-evalthis-in-javascript
global.global = global;
global.globalThis = global;
global.frames = global;
global.self = global;
global.window = global;
global.crypto = { getRandomValues: require('polyfill-crypto.getrandomvalues') };
`
