### ISSUE TITLE
Why does `--loader` in `ts` and `tsx` removes some of my imports

### ISSUE THREAD

**Issue by ShenQingchuan** [evanw/esbuild#2961]
## Reproduction in esbuild.repl

https://hyrious.me/esbuild-repl/?version=0.16.15&mode=transform&input=import+defaultImportExample+from+%27lib-1%27%0Aimport+%7B+namedImportExample+%7D+from+%27%40lib-2%2Fcore%27%3B%0Aimport+*+as+namespaceImportExample+from+%27lib-3%2Fdist%2Fsomething%27%0A%2F%2F+import+%7B+type+ITypeInnerImportExample+%7D+from+%27lib-ts-4%27%3B%0A%2F%2F+import+type+%7B+ITypeOuterImportExample+%7D+from+%27lib-ts-5%2Ftypes%27%0A%0Aconsole.log%28%27WHY+%3F%3F%3F%3F%27%29&options=--loader%3Dts+--target%3Desnext

**Comment by hyrious** [comment]
See https://github.com/evanw/esbuild/issues/2948#issuecomment-1442685493
