### ISSUE TITLE
tree-shaking don`t work in js files

### ISSUE THREAD

**Issue by le2022le** [evanw/esbuild#2969]
**app.js**

`import moment from "moment";`

When I use `esbuild app.js --outfile=out.js --bundle`, I found that the moment was also beaten into the end product.

![image](https://user-images.githubusercontent.com/119395626/223016914-980162a0-1aa0-484c-997a-dc46ae5e9b3a.png)

esbuild version: latest

**Comment by le2022le** [comment]
But when I change the filename to ts as `app.ts`，it work.
![image](https://user-images.githubusercontent.com/119395626/223015956-c469ee2d-caaa-41b8-9f9a-8f6b7bb35faa.png)

How do I get tree-shaking to work in js files?

**Comment by evanw** [comment]
That's not tree shaking. [TypeScript automatically removes unused import statements](https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBCCICmA7eAzKS4CJErq4DcQA) when converting TypeScript to JavaScript. That happens before bundling begins, so it has nothing to with esbuild's tree shaking analysis.

**Comment by le2022le** [comment]
Thanks for your help. But how can I achieve a similar effect In js source files
