### ISSUE TITLE
Warn users when omitting a bundle due to root package.json sideEffects config

### ISSUE THREAD

**Issue by eccentric-j** [evanw/esbuild#2971]
## Context

1. Used `npx create-remix` to create a reproduction repo for another issue on another library
2. The package.json it generated assumed `sideEffects: false`
3. The module I was using, that relied on side-effects was mysteriously omitted from all the bundles
4. 3 days of debugging, searching, and asking later I stumbled upon the mention of sideEffects in esbuild docs

## Proposal

Would it be possible to add a warning to esbuild so that if it's completely omitting a side-effectful module due to root package.json `sideEffects` key it could warn about that in the console?

## Why

Not realizing `sideEffects: false` was set by default on the package.json, I was extremely confused and frustrated that the code I was using was omitted from the bundle without any hints as to why. Through testing realized it was due to the side-effectful nature of it, but did not know of any levers to pull besides that.

## When

Given that there is control flow logic to omit modules with side-effects based on root package.json `sideEffect` key, I'm hoping adding a warning around there when that happens wouldn't be too much trouble. I have limited Go experience (read none so far) but willing to give it a shot if maintainers feel there's merit.

## Known Consequences

Given a user has a side-effectful module they are expecting to be omitted from a bundle, repeated warnings on build might be annoying. 

That said, I feel like in most cases, one should really change their approach to reduce side-effects or change their `sideEffects` key in their package.json. 

## Context Boundaries

I'm not advocating for warning on every side-effectful node_module omitted from their respective package.json, just root project code omitted from the root package.json.

Anyway, thanks for reading. Let me know your thoughts!

**Comment by evanw** [comment]
Can you provide a code sample here that demonstrates the issue? I just want to make sure I understand precisely what you're talking about.

**Comment by eccentric-j** [comment]
@evanw https://github.com/eccentric-j/esbuild-remix-sidefx-repro

To recap:

1. Remix CLI generated a package.json with `sideEffects: false`
2. I created a ./app/lib/sideEffect.ts file that performs some side-effects critical to the index page
3. esbuild will omit bundling sideEffect.ts completely
4. Viewing the page causes a runtime error due to globalThis.SIDE_EFFECT.message not existing in server-side or client-side bundles

I'm proposing that esbuild could warn users if root project modules are omitted due to a package.json setting so that if it's not intended, it can be more readily debugged\fixed.

**Comment by evanw** [comment]
It looks like esbuild already does warn about this. Here's what happens if you `esbuild --bundle app/routes/index.tsx` in that repo:

```
▲ [WARNING] Ignoring this import because "app/lib/sideEffect.ts" was marked as having no side effects [ignored-bare-import]

    app/routes/index.tsx:1:7:
      1 │ import "~/lib/sideEffect"
        ╵        ~~~~~~~~~~~~~~~~~~

  "sideEffects" is false in the enclosing "package.json" file

    package.json:3:2:
      3 │   "sideEffects": false,
        ╵   ~~~~~~~~~~~~~
```

This is a problem with Remix, not esbuild. Remix is [telling esbuild to not print any warnings](https://github.com/remix-run/remix/blob/4988875856ba4007d4e1e4219b117ce9c7012489/packages/remix-dev/compiler/compileBrowser.ts#L168), and then also [discarding the warnings that esbuild returns without printing them itself](https://github.com/remix-run/remix/blob/4988875856ba4007d4e1e4219b117ce9c7012489/packages/remix-dev/compiler/compileBrowser.ts#L225).

I'm closing this issue because esbuild already does what you are suggesting.

**Comment by eccentric-j** [comment]
Oh I'm really sorry about that! I'll sponsor you a bit to make up for taking your time. Anyway thanks for looking into it. I'll create a remix issue about that and link here.

**Comment by eccentric-j** [comment]
Looks like you don't have sponsorships or tips setup for your gh profile or this project. If you would like to enable it I'm happy to sponsor a bit. Otherwise, you could recommend another project to sponsor instead 🙂
