### ISSUE TITLE
Strange issue with css file being added into the output assets directory

### ISSUE THREAD

**Issue by josephdyer** [evanw/esbuild#2975]
I'm really sorry, this is hard to explain, so bear with me....

I was experimenting with a config option (outfile or out extension, can't remember which one sorry!) to see how I could change the filename for my CSS file. It generated a file, but I have since removed that option from the config file, but now when I save my `main.scss` file, esbuild keeps generating my experimental `main.hello-css` css file and adding it to assets.

Is there some sort of cache somewhere that's still seeing that file and creating it? Maybe with rebuild?

![Screenshot 2023-03-08 at 17 53 27](https://user-images.githubusercontent.com/7864396/223791588-cf14d628-133e-4455-9bcc-9d35d58017df.png)

Any help appreciated :) 

Again, sorry it's quite unusual but I'm not sure what to do, it's just annoying - I've uninstalled and reinstalled esbuild too :(

My config file:

```esbuild
    .context({
        entryPoints: ['resources/scss/*.scss'],
        entryNames: production ? '[name].min' : '[name]',
        bundle: true,
        outdir: 'assets/css',
        minify: production,
        sourcemap: !production,
        logLevel: production ? 'info' : 'debug',
        plugins: [
            globPlugin(),
            sassPlugin({
                async transform(source) {
                    const { css } = await postcss([
                        autoprefixer,
                        mqpacker
                    ])
                    .process(source, { from: undefined })
                    return css
                }
            })
        ]
    })
    .then(context => {
        if (!production)
        {
            context.watch()
            console.log('⚡ SCSS Compiled!')
        }
        else {
            context.rebuild().then(result => {
                console.log('⚡ CSS Minified!')
                 context.dispose()
            })
        }
    })
    .catch(() => process.exit(1))

**Comment by evanw** [comment]
Please provide a self-contained code sample that reproduces the problem along with instructions for how to reproduce it.
