### ISSUE TITLE
Make some examples for new-comer

### ISSUE THREAD

**Issue by creampnx-x** [evanw/esbuild#2977]
I wish there is an `example` dir to contain some useful examples for new comers like webpack: https://github.com/webpack/webpack/tree/main/examples. Vite is using esbuild, but when I check the repo, I still feel confused. 
and the esbuild document is huge.

**Comment by evanw** [comment]
There are various examples in the documentation: https://esbuild.github.io/getting-started/ as well as examples in the CLI (if you run `esbuild -h` or `esbuild` with no arguments):

```sh
Examples:
  # Produces dist/entry_point.js and dist/entry_point.js.map
  esbuild --bundle entry_point.js --outdir=dist --minify --sourcemap

  # Allow JSX syntax in .js files
  esbuild --bundle entry_point.js --outfile=out.js --loader:.js=jsx

  # Substitute the identifier RELEASE for the literal true
  esbuild example.js --outfile=out.js --define:RELEASE=true

  # Provide input via stdin, get output via stdout
  esbuild --minify --loader=ts < input.ts > output.js

  # Automatically rebuild when input files are changed
  esbuild app.ts --bundle --watch

  # Start a local HTTP server for everything in "www"
  esbuild app.ts --bundle --servedir=www --outdir=www/js
```

**Comment by mhsdesign** [comment]
I really like the docs and they did help a lot ;) Its worth reading every line (especially about the configuration options youre using) So big thanks!

I at first underestimated custom plugins and how easy the api is. When i refactored a big project from webpack to esbuild i wrote a few little 5 liner plugins that are in the webpack universe complete packages ^^
Also many webpack plugins will be replaced by esbuilds superior coverage of everything: Jsx, Css & Font bundling is already included ^^

Absolutely love it.

**Comment by Balu-Raut-Syngenta** [comment]
@creampnx-x that's good point but I do agree with @evanw there are bunch of examples in the https://esbuild.github.io/getting-started/
@evanw can I create example folder and add readme file for each example folder. Perhaps I can add codesnadbox link.

**Comment by evanw** [comment]
I'm closing this issue as esbuild already has lots of examples on its documentation website and help text.
