### ISSUE TITLE
OnRebuild is removed？！

### ISSUE THREAD

**Issue by lv-saharan** [evanw/esbuild#2978]
if watch.onRebuild is removed,when write option set to false,where to get the build result?

**Comment by evanw** [comment]
You can get it using an `onEnd` callback in a plugin. This was described in the release notes for the release that made this API change: https://github.com/evanw/esbuild/releases/tag/v0.17.0.

**Comment by chenjiahan** [comment]
Here is an example:

```ts
const onEndPlugin = {
  name: 'on-end',
  setup(build) {
    build.onEnd((result) => {
      console.log(`build ended with ${result.errors.length} errors`);
    });
  },
};

const ctx = await context({
  plugins: [onEndPlugin],
  // ...other options
});

await ctx.watch();
```

**Comment by evanw** [comment]
I'm closing this issue as this is not a problem with esbuild. This change was made deliberately and has already been documented.
