### ISSUE TITLE
Ponyfill/Polyfill/Shim Object.assign

### ISSUE THREAD

**Issue by ComLock** [evanw/esbuild#298]
When --target is below es2018 spread properties will be transformed to Object.assign, which is wonderful.

However since my environment (Java Nashorn) doesn't have Object.assign I need to shim it.

Here are some npm modules to do that:
- object-assign
- es6-object-assign

The problem is that my shim ends up after the transform `var __assign = Object.assign;` so it doesn't work.

**Comment by evanw** [comment]
Are you able to evaluate your shim script before you evaluate the file generated by esbuild? Alternatively, does joining the two files together with string concatenation work for you?

**Comment by ComLock** [comment]
I'm using --bundle

**Comment by ComLock** [comment]
Perhaps I could use. --bundle to bundle node modules, but make the shim an external.

**Comment by ComLock** [comment]
Neither external shim, nor concat of two transpiled files seem to work.

**Comment by evanw** [comment]
More specifically, imagine you have this source code:

```js
var test = {...{x: 1}};
```

That will be compiled into this file by esbuild:

```js
var __assign = Object.assign;
var test = __assign({}, {x: 1});
```

And imagine you have this shim file:

```js
Object.assign = Object.assign || shim;
```

If you join these two files together with string concatenation, you get this:

```js
Object.assign = Object.assign || shim;
var __assign = Object.assign;
var test = __assign({}, {x: 1});
```

This looks like it should do what you're asking for. If you're using the Nashorn Java API you could do the the file concatenation in Java with strings, or if you're using the command-line Nashorn API you could do the file concatenation using a command such as `cat`. Does that work for you?

**Comment by ComLock** [comment]
Got it working using concatenation
