### ISSUE TITLE
Not sequential execution of promises context.watch()

### ISSUE THREAD

**Issue by Valexr** [evanw/esbuild#2980]
I have a 2 contexts & `server` have less code & bundling more faster then `client`.
When started, it can't find needed client resources...
If "prebundling" with `rebuild` method - all 👌🏻, but  i think it's only delay before server started...

### ⚠️ Check without output folders - auto creating on `context.watch()`

How i can check if `await context.watch()` truly resolved?

Used  `top level await` in esbuild config file 🤓

```js
const server = await context(serverOptions);
const client = await context(clientOptions);

// await client.rebuild();
// await server.rebuild();

await client.watch();
await server.watch();
```

Same behavior with chain promises or scoped async iife ...🤔 
```js
const server = await context(serverOptions);
const client = await context(clientOptions);

client.watch().then(() => server.watch());
```

**Comment by hyrious** [comment]
What about using `onEnd()` in client plugins to notify server update.

```js
let onFirstBuild = () => server.watch()

clientOptions = {
  plugins: [{
    name: 'notify-build-end',
    setup({ onEnd }) {
      let first = true
      onEnd(() => {
        if (first) {
          onFirstBuild()
          first = false
        }
      })
    }
  })
}

await client.watch()
```

**Comment by evanw** [comment]
This should work:

```js
const server = await context(serverOptions);
const client = await context(clientOptions);

await client.watch();
await client.rebuild();

await server.watch();
await server.rebuild();
```

Calling `watch()` just enables watch mode but doesn't wait for a build. Calling `rebuild()` waits for a build and returns the result. This is likely what you want because if there is an error, `rebuild()` will throw an error and stop your build script. It sounds like you wouldn't want the build script to continue if the server build depends on the client build and the client build fails.

**Comment by Valexr** [comment]
> This should work:
> 
> ```js
> const server = await context(serverOptions);
> const client = await context(clientOptions);
> 
> await client.watch();
> await client.rebuild();
> 
> await server.watch();
> await server.rebuild();
> ```
> 
> Calling `watch()` just enables watch mode but doesn't wait for a build. Calling `rebuild()` waits for a build and returns the result. This is likely what you want because if there is an error, `rebuild()` will throw an error and stop your build script. It sounds like you wouldn't want the build script to continue if the server build depends on the client build and the client build fails.

Yep, it’s work fine👌🏻you can see commented code in my message. For separated env I’m use scoped variables:

```js
if(DEV) watch()
else build()
```

Tx for explanation ✌🏻
