### ISSUE TITLE
Failed to run esbuild through a task runner

### ISSUE THREAD

**Issue by fabiospampinato** [evanw/esbuild#2987]
I use a little program called [monex](https://github.com/fabiospampinato/monex) for running and re-running a bunch of arbitrary commands, but for whatever reason esbuild doesn't seem to work with it.

For example, I can run this in my shell just fine:

```sh
esbuild ./src/index.tsx --bundle --outfile=dist/client/index.js --watch --format=esm
```

But if I run it through monex now suddenly esbuild just exists with no output:

```sh
monex -x 'esbuild ./src/index.tsx --bundle --outfile=dist/client/index.js --watch --format=esm'
```

Monex executes the command [like this](https://github.com/fabiospampinato/monex/blob/e04486d6cab891b60f1f6a782b128f8989a014b5/src/interactive/controller_single.ts#L98-L103), so I'm not sure there's a problem in there.

Also I tried basically the same with sass, the following works as expected:

```sh
sass ./public/scss/index.scss ./public/css/index.css --watch --no-source-map
```

And it also works as expected through monex:

```sh
monex -x 'sass ./public/scss/index.scss ./public/css/index.css --watch --no-source-map'
```

So I can only reproduce this problem with esbuild, and I don't see what could be broken in `monex` to cause this issue, hence I opened this issue. Maybe there's a bug with esbuild somewhere? It's kind of a weird issue 🤔

**Comment by evanw** [comment]
You may need `--watch=forever` if you’re using a task runner that immediately closes stdin. This is mentioned in the documentation: https://esbuild.github.io/api/#watch. Note that this may cause esbuild to run forever, however.

**Comment by fabiospampinato** [comment]
`--watch=forever` does the trick, I didn't even think to check the docs as I thought explicitly telling it to watch ought to keep it alive.

The docs mention the reason for this, but the parent process in my case didn't exist, maybe the logic for this could be rewritten to be more reliable? Like whether stdin is wired in or not has nothing to do with it. As a first improvement maybe it can check if `stdin` was ever wired in? If it wasn't then maybe this isn't a reliable thing to watch for. Alternatively maybe the parent PID can be retrieved if there is one, and that could be prodded instead?
