### ISSUE TITLE
Is there a way to swap esbuild with esbuild-wasm without downstream projects explicitly supporting it?

### ISSUE THREAD

**Issue by josh-hemphill** [evanw/esbuild#2989]
Running into false-positive anti-virus blocking the esbuild binary, and ultimately trying to get Vite to work, but they haven't responded to the thread about it.
Our environment might take months to maybe never to get the binary approved and allowed, so I'm curious if they're 1:1 compatible such that we could just inject it into the dependency tree or something so we can continue working in the meantime.

**Comment by evanw** [comment]
> Is there a way to swap esbuild with esbuild-wasm without downstream projects explicitly supporting it?

You'd have to look at your package manager's documentation for how to do that. For example, [npm overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) might work (I haven't tried them myself so I don't know if this is the right answer for you).

> so I'm curious if they're 1:1 compatible such that we could just inject it into the dependency tree or something

No. Quoting [esbuild's documentation about the WASM build](https://esbuild.github.io/getting-started/#wasm):

> The WebAssembly version also excludes some features such as the local file server.
