### ISSUE TITLE
performance issue/deadlock with esbuild 0.6.10

### ISSUE THREAD

**Issue by ngbinh** [evanw/esbuild#299]
After upgrading from `0.6.7` to `0.6.10`, I saw the bundle time increases about 10 times and esbuild even froze my Linux dev machine while trying to build our big scala.js project at work. 

I have to switch back to `0.6.7` for now

**Comment by evanw** [comment]
Can you share more details about your setup? For example, are you using the command-line API, the JavaScript API, or the Go API?

**Comment by ngbinh** [comment]
I am using the command-line API. The command I am using is similar to what in https://github.com/ngbinh/esbuild-minify .

**Comment by evanw** [comment]
That's strange. I'm unable to reproduce the performance issue with that repo. Both esbuild 0.6.7 and esbuild 0.6.10 finish in 0.25 seconds on my machine (a MacBook Pro with macOS 10.15).

**Comment by ngbinh** [comment]
I will try to get a reproduce soon

**Comment by ngbinh** [comment]
looks like it was because my IntelliJ freezes after so many files change externally.
