### ISSUE TITLE
panic: Expected scope (7, 0) in index.ts, found scope (7, 2) (while parsing "index.ts")

### ISSUE THREAD

**Issue by jakebailey** [evanw/esbuild#2991]
I was futzing around with decorators and thought I'd throw a new-style decorator into esbuild to see what old-style decorators would have output (was too lazy to open a new TS playground and change settings).

I was surprised to see a panic:

```
Error: Build failed with 1 error:
error: panic: Expected scope (7, 0) in index.ts, found scope (7, 2) (while parsing "index.ts")
```

The code is just:

```ts
@((target, context) => {
  target.staticProp
  //      ^?
})
class Foo {
  static staticProp = 1234;
}
```

~Which, is not legal TS code for old-style decorators, but is for new-style.~ esbuild doesn't support new style decorators yet, but, the panicking seems unintentional.

[esbuild playground](https://jakebailey.github.io/esbuild-playground/#Ly8gQGZpbGVuYW1lOiBjb25maWcuanNvbgp7CiAgImVudHJ5UG9pbnRzIjogWyIvaW5kZXgudHMiXSwKICAiZm9ybWF0IjogImVzbSIKfQoKLy8gQGZpbGVuYW1lOiBpbmRleC50cwpAKCh0YXJnZXQsIGNvbnRleHQpID0+IHsKICB0YXJnZXQuc3RhdGljUHJvcAogIC8vICAgICAgXj8KfSkKY2xhc3MgRm9vIHsKICBzdGF0aWMgc3RhdGljUHJvcCA9IDEyMzQ7Cn0=)

**Comment by hyrious** [comment]
Except for the new decorator proposal, the <q>decorator expression</q> is also valid TypeScript.

[TypeScript Playground Link](https://www.typescriptlang.org/play?ts=4.9.5#code/AIChGMBsGcC4AICGA7AngSngXgHzytOgFBSLTTwBiA9tfAN4C+RQA)

**Comment by jakebailey** [comment]
Hm. With my exact code, I got errors. Maybe that's not right.

**Comment by jakebailey** [comment]
Ah, it's just because of that second parameter, apparently.

**Comment by evanw** [comment]
Sorry about that. Looks like I'm missing test coverage for decorators that are inline function expressions. Will fix.

**Comment by jakebailey** [comment]
Thanks for the fix!
