### ISSUE TITLE
Configurable memory limit

### ISSUE THREAD

**Issue by vmarinescu** [evanw/esbuild#2996]
Hello Evan,
first, thank you for the great tool !! 

for our use case, we are bundling ~100 files for our serverless stack, and we observed that 
our pipeline is sometimes running out of memory when trying to bundle. 

From my local testing, I saw esbuild use up to 3 GB RAM and our pipeline provides only 4 GB memory.

It's understandable that esbuild is trading space for time, but I wonder if it is even possible and if you would consider
having a configurable upper limit for the used memory ? 

Thank you

**Comment by vmarinescu** [comment]
Btw, already tried to limit the memory used by the node process, but actually a separate process is spawned for esbuild for which the limit is not considered.

**Comment by evanw** [comment]
I haven’t tried but you could try setting the `GOMEMLIMIT` environment variable for Go. It would be interesting to know if that does anything. Documentation is here: https://pkg.go.dev/runtime#hdr-Environment_Variables. 

Also if you are passing multiple entry points to esbuild, you could try passing fewer at a time.

**Comment by vmarinescu** [comment]
Thank you for your reply! 

I just tried GOMEMLIMIT, and it helps. Seems this is not a hard-cap for GO, but rather it would trigger the GC once above the configured limit. 
Configuring it to 1000MiB would still show a maximum RAM usage of 2.4 GiB for example. I guess some of the entry-points have a lot of dependencies, hence the GC can't clean up some of the memory.

Here is my test data:
```
no limit   -> 10 seconds   -> 3.6 GiB
1000MiB -> 20 seconds   -> 2.4 GiB
500MiB   -> 20 seconds   -> 2.4 GiB
```

For our use-case, we will go with 2500MiB as it seems the max usage is never above 3 GiB, while also not loosing any noticeable speed.

Should I open a PR to document this somewhere? Maybe in the FAQ section?

**Comment by evanw** [comment]
Hmm. I'm not sure if a FAQ is the correct place for this considering this question has only ever been asked once. Maybe I should change it into a "miscellaneous notes" section or something...

**Comment by znewsham** [comment]
I'd vote for this to be more obvious too - currently esbuild is using 16.4GB - which in fairness, is way higher than I've ever seen it go before - but it often uses around the 5GB mark

My use case is fairly specific - but it would be great to know more about how/when esbuild releases resources when there are multiple parallel builds.
