### ISSUE TITLE
IsPackagePath does not consider aliases from tsconfig.json

### ISSUE THREAD

**Issue by gorbak25** [evanw/esbuild#3003]
https://github.com/evanw/esbuild/blob/deb93e92267a96575a6e434ff18421f4ef0605e4/internal/resolver/resolver.go#L2460
 When bundling for nodejs with `--packages=external` enabled if there is an alias in tsconfig this function will classify such an import as an external module instead of an internal one.
Here is a minimal reproduction https://github.com/gorbak25/esbuild-bug-IsPackagePath

**Comment by oyed** [comment]
Also currently experiencing this myself.

**Comment by evanw** [comment]
Linking this issue to #3238.
