### ISSUE TITLE
Accepting multiple in-memory entrypoints?

### ISSUE THREAD

**Issue by lewisl9029** [evanw/esbuild#3011]
Looks like `stdin` can accept a single in-memory entry point right now. 

Wondering if you're open to an update to the api to accept more than 1 entry point though `stdin` (probably through an array of the same stdin input objects)? 

My use case requires supplying a large number of programmatically generated entry points, so ideally I don't want to be writing all of them to the fs if I can avoid it. Currently it takes several seconds to write out all of them, longer than it takes for esbuild to bundle 😅 .

Would be happy to work on a PR if this sounds like a reasonable thing to add. :)

**Comment by evanw** [comment]
If you're programmatically generating them than the most natural way to do this is probably with a plugin. Plugins can provide content for entry point files, so entry point files don't have to exist on the file system. You can write a plugin with an `onResolve` callback that maps the entry point name to a module path, and then an `onLoad` callback that intercepts the load for that module path and returns the content.

However, if you are concerned about performance, keep in mind that using file system is sometimes more efficient than using in-memory buffers as esbuild is run in a separate process and all in-memory buffers have to be sent over IPC. IPC is typically faster for small files while the file system is typically faster for large files.

**Comment by lewisl9029** [comment]
Ah thank you, I didn't realize plugins could provide content for entry points like that. Will give it a shot!

Appreciate the note on perf with large files vs small files too, in my case it's a whole bunch of really small files, which is why the fs writes ends up taking so long. Definitely will do some benchmarks to compare though.

Will close this one since the alternative sounds reasonable!
