### ISSUE TITLE
How do you clear old [hash] js file which used assetNames [hash] when building new ones?

### ISSUE THREAD

**Issue by zwcloud** [evanw/esbuild#3020]
build config:

      outdir: 'js',
      loader: {'.js': 'file'},
      assetNames: '[dir]/[name]-[hash]'

For example `src/index.js` is built into two files in js folder at `js/index.js` and `js/index-HASHVALUE0.js`.

then change the content of `src/index.js`, the hash value changed.

After rebuilding, `js/index-HASHVALUE0.js` still exists and a new `js/index-HASHVALUE1.js` file is generated.

Ho do you delete the old `js/index-HASHVALUE0.js` file with esbuild? Is there a builtin api? Or is there any plugin for this?

**Comment by evanw** [comment]
There's no built-in behavior around this. I didn't want to automatically delete people's files for them to avoid unintentional data loss. One easy approach could be to remove the output directory before each build.

**Comment by zwcloud** [comment]
Closed. If anyone know a plugin that can do this, please post here.

**Comment by axekan** [comment]
@zwcloud  There are plugins for this. I found [esbuild-plugin-clean](https://www.npmjs.com/package/esbuild-plugin-clean) which seems to work, but there are at least 2 more that do the same thing.

I have it set up like this:

```js
const fileEndings = ['js', 'css', 'woff', 'woff2'];
const plugins = [
	sassPlugin(),
	clean({
		patterns: fileEndings.map((f) => `../wwwroot/js/*.${f}`),
		options: {
			force: true,
		},
	}),
];
```
