### ISSUE TITLE
Support for new Typescript 5.0 const keywork with 'new' methods in interfaces

### ISSUE THREAD

**Issue by ecyrbe** [evanw/esbuild#3021]
Typescript 5.0 has released a new [const type parameter](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#const-type-parameters) in generic functions.

esbuild does not support it yet.

swc and eslint, and other tooling have catched up. we are just waiting for esbuild to also add support for it.

Awesome package tool, keep up the good work. it's impressive.

**Comment by evanw** [comment]
This was already added [two months ago](https://github.com/evanw/esbuild/releases/tag/v0.17.5). If you have a case that doesn’t work, then please provide it.

**Comment by ecyrbe** [comment]
sorry, more context of it not working:
![image](https://user-images.githubusercontent.com/633115/227741684-41638dd7-d1c7-41b9-b26e-617da05eb0e9.png)
![image](https://user-images.githubusercontent.com/633115/227741736-64c48b62-eff4-46ef-a17f-430424aab31a.png)

**Comment by ecyrbe** [comment]
So minimal setup to reproduce seems to be on overriding new keyword in interfaces. That use case works fine in TSC

**Comment by evanw** [comment]
Thanks for the test case. Sorry about the oversight. A fix for this will be in the next release.
