### ISSUE TITLE
can't figure out how to apply source maps with transforms

### ISSUE THREAD

**Issue by clshortfuse** [evanw/esbuild#3022]
Hi!

I'm have a working CSS Template Literal minifier, but I would like to have the unminified code in the source map. I've tried a couple of solutions, but I'm kinda stuck.

````js
import { readFile } from 'node:fs/promises';
import { relative } from 'node:path';

import * as acorn from 'acorn';
import * as walk from 'acorn-walk';
import esbuild from 'esbuild';
import { SourceMapGenerator } from 'source-map';

/** @type {import('esbuild').Plugin} */
export default {
  name: 'minify css templates',
  setup(build) {
    const cache = new Map();
    build.onLoad({ filter: /\.js$/ }, async (args) => {
      const input = await readFile(args.path, 'utf8');
      const key = args.path;
      let value = cache.get(key);

      if (!value || value.input !== input) {
        let contents = input;
        /** @type {[string,number,number][]} */
        const transforms = [];
        const file = relative(process.cwd(), args.path);
        const map = new SourceMapGenerator({
          file,
        });
        walk.simple(acorn.parse(contents, { ecmaVersion: 'latest', sourceType: 'module', locations: true }), {
          TaggedTemplateExpression(node) {
            if (node.quasi.expressions.length) return;
            if (node.quasi.quasis?.length !== 1) return;

            const { tag } = node;
            let name;
            switch (tag.type) {
              case 'Identifier':
                name = tag.name;
                break;
              case 'MemberExpression':
                name = tag.property.name;
                break;
              default:
                console.warn('Unknown TaggedTemplateExpression', tag);
                return;
            }

            if (name !== 'css') return;

            const [templateElement] = node.quasi.quasis;
            const { raw } = templateElement.value;
            const { start, end } = templateElement;
            const { code } = esbuild.transformSync(raw, {
              minify: build.initialOptions.minify,
              minifyWhitespace: build.initialOptions.minifyWhitespace,
              minifyIdentifiers: build.initialOptions.minifyIdentifiers,
              minifySyntax: build.initialOptions.minifySyntax,
              target: build.initialOptions.target,
              loader: 'css',
            });
            const { loc: { start: { line, column } } } = templateElement;

            map.addMapping({
              generated: {
                line,
                column,
              },
              source: file,
              original: {
                line,
                column,
              },
              name: raw,
            });
            transforms.push([code.trim(), start, end]);
            // console.log('Minified CSS', end - start, 'bytes to', code.trim().length);
          },
        });
        for (const [data, start, end] of transforms.reverse()) {
          contents = contents.slice(0, start) + data + contents.slice(end);
        }
        if (transforms.length) {
          map.setSourceContent(args.path, input);
          const sourceMapOutput = map.toString();

          const base64 = Buffer.from(sourceMapOutput).toString('base64');
          contents += `//# sourceMappingURL=data:application/json;charset=utf-8;base64,${base64}`;
        }
        value = { input, output: { contents } };
        cache.set(key, value);
      }

      return value.output;
    });
  },
};

````

The act of minifying the CSS template works just fine. From what I understand, the starting line and column should be the same since I'm just minifying a string. But I think I'm failing with the source file. Without a source map, esbuild shows the minified string in the  map file. With a source map, that file just completely disappears. 

Am I doing this wrong? Should I not be using `build.onLoad({ filter: /\.js$/ ` ? I was worried `esbuild` would skip over it, but it seems I'm just adding a pre-step before esbuild runs its JS minification.

Also, am I using an unstable code path? It minifies fine, but I don't want to break later because I'm tapping into something I shouldn't be.

**Comment by evanw** [comment]
Using `onLoad` to return code with a `//# sourceMappingURL` should work fine. That functionality has been around for a while, hasn't been changed recently, and has no known issues.

I'm guessing the problem is in your source map. You can use https://evanw.github.io/source-map-visualization/ to debug your source map generation code (upload the string in `contents`). If you believe this to be a problem with esbuild instead of with your source map generation code, then please provide a self-contained way to reproduce the issue.

**Comment by clshortfuse** [comment]
I do see now that I have to map out each piece of the JS, and not just the changes (where I change the string). Seems overly verbose, but it is what it is.

I haven't fully figured out the quirks of the onLoad system, since trying to create one plugin for CSS and one for HTML didn't work. I guess you can only have one loader per file type (JS). But I'll worry about that later.

Thanks!

**Comment by clshortfuse** [comment]
For posterity, you were right. It was the source-maps. I used [`magic-string`](https://github.com/Rich-Harris/magic-string) instead of trying to compile it myself and it solved my issues. Thanks, again!
