### ISSUE TITLE
Can not export the name-imported with default in transpiled cjs 

### ISSUE THREAD

**Issue by snowyu** [evanw/esbuild#3029]
The ESM js files to transpile:

```js
// fn.js
export function fn() {}
export default fn
```
```js
// fn1.js
export function fn1() {}
export default fn1
```

```js
// index.js
export * from './fn'
export * from './fn1'
```

```js
// package.json
{
  "name": "util-ex",
  "main": "./lib/index.js",
  "module": "./src/index.js",
  "type": "commonjs",
}
```

Used it in another esm package after transpiled, found no `cloneObject` exported.  exported only after commenting the `export default cloneObject`

```js
import { fn } from 'util-ex'
console.log(fn) // is undefined
```

**Comment by hyrious** [comment]
You mentioned "transpiled", what are the actual files in runtime? What runtime is it? It sounds like #2486 where esbuild currently does not emit any code for node.js to infer re-exports from cjs code. But you can provide a self-contained reproduction to make it clear.

In fact, the transform mode does not produce the "unbundled" result (or let's call it [preserve modules](https://rollupjs.org/configuration-options/#output-preservemodules) as in rollup, which is not supported yet: #708). Any try to use it like that will likely to fail.

**Comment by snowyu** [comment]
@evanw  0.17.15  Still Can not export the name-imported, report error now: `SyntaxError: Named export 'fn' not found. The requested module 'util-ex' is a CommonJS module, which may not support all module.exports as named exports.`

But can workaround:

```js
import util from 'util-ex';
const fn = util.fn;
```

If wanna named exported on node, do not overrite the `module.exports`.

**Comment by evanw** [comment]
I added a test case based on your incomplete reproduction: https://github.com/evanw/esbuild/commit/b86e58128d9c9281c92c3bca3b2f1a0a5131eaf8#diff-6058dc2cc79db56a46212b92b928329c09ac9f8a3f41c6ce8edbafb3d6050613R1990-R2023. That test case failed before 0.17.15 and passed with 0.17.15, which is why I considered this issue to be fixed.

If you still believe that there is a bug with esbuild, then please provide a complete reproduction. That would include at minimum all relevant files and all instructions necessary to reproduce the bug.

**Comment by snowyu** [comment]
https://replit.com/@snowyu/esbuild-node-interop

**Comment by hyrious** [comment]
Your repl has a mistake in package.json `"type": "module"`, which indicates that all .js files are in ESM. Node.js will try to load ./dist/lib.js with ESM loader and it cannot find any named exports apparently.

**Comment by snowyu** [comment]
@hyrious which means other package(esm) call the cjs pacakge!  The SWC has the same issue, but It fixed now since I've reported.

You can chagne the js to cjs in the lib dir is the same result.
