### ISSUE TITLE
How to get javascript version of code before being written to filesystem in a plugin when transpiling with esbuild?

### ISSUE THREAD

**Issue by BlackAsLight** [evanw/esbuild#3035]
So basically I'm writing .tsx files and using esbuild to transpile them to .js files, but I can't seem to figure out a way to get my hands on the javascript version that esbuild makes before it writes it to a file. At the moment I've had to settle for running esbuild twice. First to bundle it and transpile it from .tsx to .js then second to take that bundle file and overwrite it with itself but with esbuild running my plugin that second time. 
```ts
import { build, stop } from "https://deno.land/x/esbuild@v0.15.10/mod.js"
import { denoPlugin } from "https://deno.land/x/esbuild_deno_loader@0.6.0/mod.ts"
import plugin from "./plugin.ts"

await build({
	plugins: [ denoPlugin() ],
	entryPoints: [ "./sample.tsx" ],
	outfile: "./sample.js",
	bundle: true,
	format: "esm",
	jsxFactory: 'x',
	jsxFragment: 'y'
})
await build({
	plugins: [ plugin ],
	entryPoints: [ "./sample.js" ],
	outfile: "./sample.js",
	format: "esm",
	bundle: true,
	minify: true,
	allowOverwrite: true
})

stop()
```
```ts
import initSwc, { parse, print } from 'https://esm.sh/@swc/wasm-web@1.3.44'
import { type PluginBuild } from 'https://deno.land/x/esbuild@v0.15.10/mod.js'

await initSwc()
const AST = await parse('({ type: "div", props: null, children: [ ] })')

export default {
	name: 'basic_jsx',
	setup(build: PluginBuild) {
		build.onLoad({ filter: /\.js/ }, async ({ path }) => {
			let text = await Deno.readTextFile(path)
			// Mutates javascript version of code
			return { contents: text }
		})
	}
}
```
If you know of a way I could make this into one build function by not needing to do `Deno.readTextFile` and instead receiving the content before its written, then that would be great.

**Comment by hyrious** [comment]
You can set [`write: false`](https://esbuild.github.io/api/#write) to get js output from the return value of calling build, then mutate that string, then write it to disk by yourself.

**Comment by BlackAsLight** [comment]
I'd still have to call esbuild twice since in the second time I'm currently calling it I'm also minifying it. The mutation I want to do to the javascript won't work properly on an already minified version

**Comment by hyrious** [comment]
So you want to inject a mutation step between esbuild's TSX &rarr; [JS] &rarr; Minified JS steps. However as I know there's no such hook to do so. I'd recommend you to run the minifying in another step.

**Comment by evanw** [comment]
I'm closing this because running esbuild twice is the answer. What you're asking for is not possible since parsing, converting TS to JS, and minification all happen at the same time. There is no intermediate step even internally. This is intentional since converting the AST to a string and parsing it back into an AST would be unnecessary extra work.
