### ISSUE TITLE
Shadowed variable is minified incorrectly

### ISSUE THREAD

**Issue by dragonofdeath** [evanw/esbuild#3037]
Shadowed variable is initialized incorretly in this case:
```
echo  "const A = 0; function R() { const A = A; return A; }" | esbuild --minify
```
returns this:
```
const A=0;function R(){const n=n;return n}
```
when it should return something like this:
```
const A=0;function R(){const n=A;return n}
```
esbuild version 0.17.15

**Comment by hyrious** [comment]
No, your source code will cause ReferenceError at runtime. There's no such feature in JavaScript. Try run this yourself:

```js
const A = 0; function R() { const A = A; return A; }
R()
```

**Comment by evanw** [comment]
I'm closing this issue as invalid.

**Comment by dragonofdeath** [comment]
@hyrious true! thank you!
