### ISSUE TITLE
Help needed with new context format for dev server

### ISSUE THREAD

**Issue by HarikalarKutusu** [evanw/esbuild#3047]
I've been using esbuild under the hood from vite & rollup in my monorepo. I decided to convert the server side to microservices and get rid of the wrapper over wrapper structure, back to using esbuild directly (as a newby). But I could not make a simple live dev server with "watch" using the v0.17.x contexts, also misguided with many tutorials I read/followed. I also tried all plugins I could find for this purpose, but none worked did not satify my needs, and some of them even had old dependencies.

I created a simple (to-be-microservice) node server index.ts with console.log etc but it never fires with the following setup (removed irrelevant parts):

```js
// ./build.js
const isDev = process.env.NODE_ENV === "development";

const sharedOptions = {
  bundle: true,
  minify: !isDev,
  platform: "node",
  format: "esm",
  target: "ES2020",
  plugins: [environmentPlugin(envList), dtsPlugin(), nodeExternalsPlugin()],
};

const devOptions = {
  ...sharedOptions,
  entryPoints: ["./src/index.ts"],
  outfile: "dist/index.mjs",
};

// Runs when isDev is true
const esb_dev = () => {
  esbuild.context(devOptions).then((c) => {
    c.watch({}).then(() => console.log("Watching..."));
    c.serve({
      servedir: "dist",
      host: process.env.HOST,
      port: Number(process.env.PORT),
    })
      .then((res) => {
        console.log("================================================");
        console.log(`DevServer ${pjson.name} on ${res.host}:${res.port}`);
        console.log("================================================");
      })
      .catch((e) => {
        console.log("Error:", e);
        c.dispose();
      });
  });
};

```

It prints "Watching..." and the `DevServer appName host:port` part, but does not run the compiled `index.mjs` file. Currently I build and run it from script with node, nothing watching.

Help is very much appreciated.

**Comment by hyrious** [comment]
`watch` triggers rebuild on fs events, `serve` starts a http server for website to play locally. None of them would run node for you.

You can do that with a simple plugin that spawns child process on each [on-end](https://esbuild.github.io/plugins/#on-end) callback. See [examples in the changelog](https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#upgrade-guide-for-existing-code) (search for <q>Watch with `onRebuild`</q>).

```js
let child
devOptions.plugins.push({
	name: 'run-node-on-build',
	setup({ onEnd }) {
		onEnd(result => {
			if (result.errors.length === 0) {
				child && child.kill()
				child = spawn('node', ['dist/index.mjs'], { stdio: 'inherit' })
			}
		})
	}
})
```

Dev Hint: `child.kill()` does not succeed immediately, if the child process wants to listen a port and the old process does not release that port, it will fail.

**Comment by HarikalarKutusu** [comment]
Oh, thank you! I saw that construct before, but I was thinking the `context.serve` will actually do this thing. I'll try it right away...

**Comment by HarikalarKutusu** [comment]
It worked! It ran and it is watching. I really appreciate it @hyrious, thank you. I spent hours trying to figure this thing out...
