### ISSUE TITLE
Passing `build` an imports resolver function

### ISSUE THREAD

**Issue by terrablue** [evanw/esbuild#3048]
In my scenario, I have all the imports already loaded into an object in memory. While I understand it's possible to pass `stdin.contents` to `build`, I was wondering if there's an option to tell esbuild that whenever it encounters an import, it should execute a function with the import specifier as input instead of looking for the import somewhere in the filesystem. That function would return the contents of the import. In that way, it would be possible to use esbuild as a pure function that transforms the object in memory into another object in memory (provided it's used with `write: false`, which I'm already doing).

Is this something that's currently possible, planned or trivial to implement in esbuild?

My workaround consists of dumping my in-memory object into a special `build` directory that I destroy after invoking `build`.

**Comment by evanw** [comment]
It sounds like you are looking for this: https://esbuild.github.io/plugins/

**Comment by terrablue** [comment]
Great, thanks!
