### ISSUE TITLE
Already bundled modules are not being bundled

### ISSUE THREAD

**Issue by Sevi7** [evanw/esbuild#3054]
Hi, I don't know if what I'm asking is possible and I did not find any info, but we are using some modules that are published already bundled (aws-cdk-lib for example). And when we bundle our code with these libraries, they are not being bundled and full size of the libraries are introduced in the bundled code. So we have lambda functions of even 16 MB (and cold start is crazy high for them). Is there a way to solve this?

**Comment by evanw** [comment]
I'm not sure what you're saying, sorry. Please provide a self-contained code sample that demonstrates the issue.

**Comment by evanw** [comment]
I'm closing this issue because it has been unactionable for a while and no additional information was provided.
