### ISSUE TITLE
Bundle external web fonts?

### ISSUE THREAD

**Issue by tmm1** [evanw/esbuild#3055]
I have a CSS import in one of my dependencies like so:

```
@import url(https://fonts.googleapis.com/css?family=Material+Icons);
```

Is it possible to, via plugin or otherwise, tell esbuild to download a copy of this font and bundle it as a dataurl, instead of relying on the external server?

(I'm creating a self-hosted web app that needs to be able to run without internet access.)

**Comment by evanw** [comment]
Yes, that's what plugins are for. The first example plugin in the documentation is one that shows you how to download something via HTTP: https://esbuild.github.io/plugins/#http-plugin. You should be able to do what you want by modifying that example slightly.

**Comment by tmm1** [comment]
I tried that first but neither onLoad nor onResolve seemed to receive the url. Do I need to use a specific namespace other than file?

**Comment by tmm1** [comment]
I created an example here: https://gist.github.com/tmm1/f9c4c1e6def24eeff901de750a0f810d/revisions

I'm using the sass plugin, maybe that's part of the issue. But when I run `node build.js` I don't see any console.log output from my plugin looking for `/gstatic/`

I tried with regular css here, and there is still no `onLoad` or `onResolve` being triggered: https://gist.github.com/tmm1/92df1dd2d33b098da1307345842ee944

**Comment by tmm1** [comment]
I discovered if I change `type:"style"` to `type:"css"` in the `sassPlugin()` invocation, it will process the css text back through esbuild and let me run other plugins.

Now the httpPlugin example kicks in, however it seems to interpret the downloaded contents as JS instead of CSS:

```
Downloading: https://fonts.googleapis.com/css?family=Material+Icons
✘ [ERROR] JavaScript decorators are not currently supported

    http-url:https://fonts.googleapis.com/css?family=Material+Icons:1:0:
      1 │ @font-face {
        ╵ ^

✘ [ERROR] Expected "class" after decorator but found "-"

    http-url:https://fonts.googleapis.com/css?family=Material+Icons:1:5:
      1 │ @font-face {
        ╵      ^

  The preceding decorator is here:

    http-url:https://fonts.googleapis.com/css?family=Material+Icons:1:0:
      1 │ @font-face {
        ╵ ^

  Decorators can only be used with class declarations.

✘ [ERROR] Expected ";" but found "{"

    http-url:https://fonts.googleapis.com/css?family=Material+Icons:1:11:
      1 │ @font-face {
        │            ^
        ╵            ;
```

**Comment by tmm1** [comment]
If I embed the CSS directly into my project:

```
@font-face {
  font-family: 'Material Icons';
  font-style: normal;
  font-weight: 400;
  src: url(https://fonts.gstatic.com/s/materialicons/v140/flUhRq6tzZclQEJ-Vdg-IuiaDsNZ.ttf) format('truetype');
}
```

then the httpPlugin similarly fails downloading the TTF contents:

```
Downloading: https://fonts.gstatic.com/s/materialicons/v140/flUhRq6tzZclQEJ-Vdg-IuiaDsNZ.ttf                                                
✘ [ERROR] Unexpected "\x00"

    http-url:https://fonts.gstatic.com/s/materialicons/v140/flUhRq6tzZclQEJ-Vdg-IuiaDsNZ.ttf:1:0:
      1 │ �pGDEF SGPOS
        ╵ ^
```

**Comment by tmm1** [comment]
`httpPlugin` has to be modified such that `onLoad` returns not only `contents` but the appropriate `loader` as well. See https://esbuild.github.io/plugins/#on-load-results
