### ISSUE TITLE
esbuild would apply ext names twice if it is already given in the entry point config

### ISSUE THREAD

**Issue by yw662** [evanw/esbuild#3059]
If the config is like
```ts
{
// ...
entryPoints: [ {in: 'index.ts', out: 'index.js'} ]
// or entryPoints: { 'index.js': 'index.ts' }
}
```

It will end up as `index.js.js`.
Should it be just `index.js` if it already says `index.js` ?

**Comment by evanw** [comment]
No, that's not how it works. The [`entryPoints`](https://esbuild.github.io/api/#entry-points) field specifies the base name and the extension comes from the [`outExtension`](https://esbuild.github.io/api/#out-extension) setting.

**Comment by evanw** [comment]
I'm closing this issue because esbuild is working as intended.
