### ISSUE TITLE
Understanding IPC implementation

### ISSUE THREAD

**Issue by thetutlage** [evanw/esbuild#306]
This issue is not a bug. I am just curious to know how the IPC model works when using the Node API.

You mention, that the service `await startService()` shares the child process among multiple transform calls and is using `stdin/stdout` for the communication. Doesn't that cause race conditions for parallel `service.transform` calls? For example: The response for the 2nd call is written first to the `stdout`?

**Please consider this as a naive question and not something challenging the implementation details 🙂**

**Comment by evanw** [comment]
The IPC works using a message-based protocol (called "packets" in the code). Each message includes a flag that indicates whether it's a request or a response and a unique "id" which is a number that starts at zero and increments for every request sent. The id counters for each side of the IPC channel are independent.

Every response message uses the same id as the request message that it's responding to. This lets both sides match up incoming responses with the requests that generated them to avoid ordering issues.

**Comment by thetutlage** [comment]
@evanw That makes perfect sense. I thought the IPC channel itself guarantees the order of messages. But that's not the case and a custom id is used to map request and response together.

Thanks a ton for the response, and esbuild is a game changer when combined with custom ESM module loaders.
