### ISSUE TITLE
Add simple minification when using dataurl loader for svg

### ISSUE THREAD

**Issue by ArnaudBarre** [evanw/esbuild#3073]
This svg:

```svg
<svg viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">
    <path
            d="M9.25 4.25L6 7.75L2.75 4.25"
            stroke="#1C1C1E"
            stroke-linecap="round"
            stroke-linejoin="round"
    />
</svg>
```

currently bundles to something to this:

```js
var Tc='data:image/svg+xml,<svg viewBox="0 0 12 12" fill="none" xmlns="http://www.w3.org/2000/svg">%0A  <path%0A          d="M9.25 4.25L6 7.75L2.75 4.25"%0A          stroke="%231C1C1E"%0A          stroke-linecap="round"%0A          stroke-linejoin="round"%0A  />%0A</svg>%0A';
```

Would it be possible to replace all consecutive whitespaces by a simple space?

**Comment by evanw** [comment]
Yes, that’s possible. You can do that by writing a plugin: https://esbuild.github.io/plugins/

**Comment by ArnaudBarre** [comment]
Yep of course, my question was is it possible to include this in core as there is already some specific code for that, this very scoped improvement and can benefit everyone.

**Comment by evanw** [comment]
It sounds like you are asking for esbuild to add another content type: SVG. Currently esbuild only supports CSS and JS. That could make sense but it's a pretty sizable increase in esbuild's current scope. For now I recommend using other tools for this via a plugin. One example that comes to mind is [svgo](https://github.com/svg/svgo).

**Comment by ArnaudBarre** [comment]
No I don't expect esbuild to handle a new content type. I'm requesting a slight improvement in [this file](https://github.com/evanw/esbuild/blob/main/internal/helpers/dataurl.go) to replace all consecutive whitespaces by one space. In JS this would be something like `rawUrl.replaceAll(/\s+/, " ")`, but I don't know how to write this efficiently in go.

I'm not asking for all the minification that svgo does, I'm already doing it before committing files (and it's expensive to do it each time on load). But for keeping source code nice, I'm suing prettier on SVGs, that why I only need whitespace handling when using the data url loader

**Comment by evanw** [comment]
These two `text` elements are not equivalent:

```svg
<svg xmlns="http://www.w3.org/2000/svg" width="400" height="360">
  <text x="20" y="20" style="white-space:pre">Space test</text>
  <text x="20" y="40" style="white-space:pre">Space    test</text>
</svg>
```

What you're talking about requires XML parsing and SVG-specific minification rules to do safely. You are asking for esbuild to implement a new content type.

**Comment by ArnaudBarre** [comment]
I'm not using SVGs with text nodes so I didn't though of this case. I will use a plugin for that
