### ISSUE TITLE
 Flag for pure-functions seems broken

### ISSUE THREAD

**Issue by opvasger** [evanw/esbuild#308]
#### Problem
Hello! I can't figure out how to use the documented `--pure=N`-flag!

I have 18 pure-functions I'd like to optimize, as they're used a lot. Am I using the flag wrong? How do I specify multiple pure-functions?

the command
`esbuild --pure=F2 --minify --outfile=build/client.min.js build/client.js`
yields
`error: Invalid build flag: "--pure=F2"`

#### Version
esbuild 0.6.12
windows 10, bash-shell

**Comment by evanw** [comment]
Whoops, my bad. That's a problem with the documentation. The flag is `--pure:N` not `--pure=N`. Flags that can be re-specified multiple times use `:` not `=`. I'll update the documentation.

**Comment by opvasger** [comment]
thanks a lot - figured it was something along those lines 👍
