### ISSUE TITLE
Error while using abstract class

### ISSUE THREAD

**Issue by yasha-black** [evanw/esbuild#3080]
I'm using abstract classes in my Vite React project.

Example:
```typescript
export abstract class Foo {
  abstract readonly bar: string | number;
  abstract get baz(): number;
}
```

Output error:
```
[vite] Internal server error: Transform failed with 1 error:
ERROR: Expected ")" but found "class"
  Plugin: vite:esbuild
  File: /example.ts
  
  Expected ")" but found "class"
  17 |    }
  18 |  };
  19 |  export let Foo = (_class = abstract class Foo {
     |                                                ^
  20 |    abstract readonly bar:string | number;
  21 |    abstract get baz(): number;
```

Does `esbuild` support abstract classes, or am I doing something wrong?

**Comment by evanw** [comment]
I'm closing this issue as invalid. The code that Vite is generating in your case not valid TypeScript, so esbuild isn't doing anything wrong here. This is the error that the official TypeScript compiler gives for that code ([playground link](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBAG2PAYhCcC8cAUB9AYwQEMBnUrOYgI1JimIPiLIrQwG8AoOK2+xvCjBiAEwgA7BAE841YlABccOlACWEgOZwAPnAkBXALbVgUANw8+qwXE3I5xAF44AlMsMmzlgL6uuQA)):

```
example.ts:1:37 - error TS1005: ')' expected.

1 export let Foo = (_class = abstract class Foo {
                                      ~~~~~
```

You need to fix whatever part of Vite generated that invalid code. This is not a problem with esbuild.

**Comment by mesqueeb** [comment]
@yasha-black how did you end up solving it? I'm hitting the same trying to upgrade a craco react project to vite
