### ISSUE TITLE
Update the link to minification becnhmarks

### ISSUE THREAD

**Issue by prantlf** [evanw/esbuild#3083]
The link in the [esbuild documentation about minification](https://esbuild.github.io/api/#minify) is outdated. Although it shows esbuild better than other minifiers, like swc, today's situation has changed and the picture that is shows is different. You might want to change https://github.com/privatenumber/minification-benchmarks/tree/cd3e5acb8d38da5f86426d44ac95974812559683#readme to just https://github.com/privatenumber/minification-benchmarks#readme or to a newer commit.

I thought I'd send a PR, but I can't find where the website sources are. If you reveal it to me, I'll do it :-)

**Comment by hyrious** [comment]
https://github.com/esbuild/esbuild.github.io here it is.

**Comment by prantlf** [comment]
Thank you! Let's move this there.
