### ISSUE TITLE
Question: Correct method to handle workspace library dependency updates

### ISSUE THREAD

**Issue by HarikalarKutusu** [evanw/esbuild#3086]
I have this structure in my node-express microservices pnpm workspaces monorepo environment, all use esbuild:
```
@myapp/commonlib
@myapp/serverlib (dependencies: commonlib)
@myapp/microservice1 (dependencies: commonlib, serverlib)
@myapp/microservice2 (dependencies: commonlib, serverlib)
...
```
During development of microservices, I generalize & move some types/methods to libraries.
Every time I do that, I have to build the libraries so that I can use them, otherwise the microservices on watch mode or while building give lots of errors as expected - and I sometimes forget and spend time until I recognize that I need to build...

Nx, Turborepo etc have features to deal with these, but they are very restrictive and I don't like them.

How would you handle such situations automatically using esbuild?
Using context for each such dependency to watch them (the build scripts are getting larger than the microservice code :) )?
Using pnpm script to rebuild them before running each microservice build (unnecessary builds? )?

Any advice is very much appreciated...

**Comment by evanw** [comment]
Sorry, but this is out of scope for what esbuild does. The API provides a way to run a build. How and when you run it is up to you. You should look at other tools for build orchestration scenarios like yours.
