### ISSUE TITLE
Question: can a plugin choose which files to minify during bundling?

### ISSUE THREAD

**Issue by retorquere** [evanw/esbuild#3087]
I'm looking to minify things from node_modules, but leave my own code outside node_modules un-minified for easier debugging. Is his something a plugin can cause esbuild to do?

**Comment by hyrious** [comment]
AFAIK it is impossible for any bundler. However, you can manually create chunks using [this trick](https://github.com/hyrious/esbuild-split-vendors-example) and control the minification of each chunk.

**Comment by evanw** [comment]
If you want to only do symbol renaming and syntax compression for certain files, you could build with those features off and then use a plugin that runs esbuild again with those features on to preprocesses certain files during the build. There would still be a single whitespace setting across all files, however.

**Comment by retorquere** [comment]
That'd still be interesting to me.

**Comment by evanw** [comment]
I'm closing this because this question has been answered.

**Comment by retorquere** [comment]
I don't know how I would do that though. I've made esbuild plugins before, but I don't know how to do this one.
