### ISSUE TITLE
onLoad called only once for the same asset (bug?)

### ISSUE THREAD

**Issue by alexandernst** [evanw/esbuild#3092]
Lets say I have my esbuild script in the root folder of my project an a `src` folder that contains my code.

```
-  esbuild.mjs
-  src
|--- index.jsx
|--- index.scss
```

Lets say that my jsx looks like this:

**src/index.jsx**
```js
import "@src/index.scss";
import Logo from "@src/Logo.svg";
```

---

Lets also say that my scss looks like this:

**index.scss**
```scss
body {
  background-image: url(@src/Logo.svg);
}
```

---

Finally, let's say that I have a custom plugin that looks like this:

```js
import { transform } from "@svgr/core";

function handleSVG(options = {}) {
  return {
    name: 'handleSVG',
    setup(build) {
      build.onResolve({ filter: /\.svg$/ }, async (args) => {
        console.log("onresolve", args);
        return {
          path: args.path.replace(/^(.*?)@src\//, path.resolve(__dirname, "src") + "/"),
          pluginData: {
            importer: args.importer,
          },
        };
      });

      build.onLoad({ filter: /\.svg$/ }, async (args) => {
        console.log("onload", args);
        if (args.suffix === "?url" || /\.s?css/.test(args.pluginData.importer)) {
          return {
            contents: args.path,
            loader: 'file',
          };
        }

        const svg = fs.readFileSync(args.path, { encoding: 'utf8' });
        const contents = await transform(svg, { ...options }, { filePath: args.path });

        return {
          contents,
          loader: 'jsx',
        };
      });
    },
  };
};
```

---

This plugin allows me to use SVG files as React components, but also allows me to use SVG files as regular images, depending on the importer. Or that's the intention of the code.

What actually happens is that when I run the build script I get the following:

```
$ node esbuild.mjs
⚡ [esbuild] Building..
onresolve {
  path: '@src/Logo.svg',
  importer: '/Users/alexandernst/Downloads/esbuild-example/src/App.jsx',
  namespace: 'file',
  resolveDir: '/Users/alexandernst/Downloads/esbuild-example/src',
  kind: 'import-statement',
  pluginData: undefined
}
onload {
  path: '/Users/alexandernst/Downloads/esbuild-example/src/Logo.svg',
  namespace: 'file',
  suffix: '',
  pluginData: {
    importer: '/Users/alexandernst/Downloads/esbuild-example/src/App.jsx'
  }
}
onresolve {
  path: '@src/Logo.svg',
  importer: '/Users/alexandernst/Downloads/esbuild-example/src/index.scss',
  namespace: 'file',
  resolveDir: '/Users/alexandernst/Downloads/esbuild-example/src',
  kind: 'url-token',
  pluginData: undefined
}
✘ [ERROR] Cannot use "src/Logo.svg" as a URL

    src/index.scss:6:20:
      6 │   background-image: url(@src/Logo.svg);
        ╵                     ~~~~~~~~~~~~~~~~~~

  You can't use a "url()" token to reference the file "src/Logo.svg" because it was loaded with the
  "jsx" loader, which doesn't provide a URL to embed in the resulting CSS.
```

If I understand correct, the problem here is that the `onLoad` callback is being called only once. The second call is skipped because esbuild already knows how to load `/Users/alexandernst/Downloads/esbuild-example/src/Logo.svg` (it uses the result of the first `onLoad` call). This is actually problematic, since I'm using the same SVG file in my SCSS and in my JSX code, and I want to use it as an image in my SCSS file and as a React component in my JSX code.

I found a workaround; I can just do:

**index.scss**
```scss
body {
  background-image: url(@src/Logo.svg?url);
}
```

but I wonder if this is a bug in esbuild or if it is an intentional behavior.

**Comment by evanw** [comment]
That's intentional. That's how module resolution works in node, in browsers, and in esbuild. Each post-resolve module specifier is only loaded once. If you import a module in node using the same post-resolve module specifier from two separate files, you don't get two copies of that module. Instead you get two references to the same module. If you want to load two copies of a module, you have to use two different post-resolve module specifiers (as you noted at the end of your post).

**Comment by alexandernst** [comment]
Fair enough! Closing this :)
