### ISSUE TITLE
ResolveExtensions does not respect dotted extensions

### ISSUE THREAD

**Issue by demigor** [evanw/esbuild#3093]
Hi, 
I'm trying to migrate my webpack-bundled project to esbuild and stuck on the following problem.
The project supports several platforms: ios, windows, browser etc.
All platform-neutral components defined in *.js files and platform-specific implementations (if exist) in *.ios.js, *.windows.js etc.

I define ios build like this:

```js
await build({
...
  resolveExtensions: [".ios.js",".js",".less",".css",".json"],
...
})
```

and windows build like this:

```js
await build({
...
  resolveExtensions: [".windows.js",".js",".less",".css",".json"],
...
})
```

expecting that my ios or windows-specific components will be resolved first.

However, esbuild always resolves to *.js files instead, not respecting platform-specific extensions, as Webpack did.

**Comment by evanw** [comment]
I cannot reproduce this. Here's what I tried:

```
$ echo 'import "./bar"' > foo.js
$ echo 'bar.ios.js' > bar.ios.js
$ echo 'bar.js' > bar.js    

$ esbuild --bundle foo.js 
(() => {
  // bar.js
  bar.js;
})();

$ esbuild --bundle foo.js --resolve-extensions=.ios.js,.js
(() => {
  // bar.ios.js
  bar.ios.js;
})();
```

Please provide a self-contained way to demonstrate your problem.

**Comment by demigor** [comment]
Looks like error caused by esbuild-plugin-path-alias, which does poor job resolving ~ alias.

import aliasPlugin from 'esbuild-plugin-path-alias'

await build({
...  
plugins: [aliasPlugin({'~': path.resolve(__dirname, './src')
...
  })

So components references as '~/components/App' always resolve to js, not respecting ResolveExtensions. I'll open issue in esbuild-plugin-path-alias repo.

Thank you for prompt investigation!
