### ISSUE TITLE
`logLevel: 'info'` no longer prints summaries?

### ISSUE THREAD

**Issue by rgarner** [evanw/esbuild#3094]
Pre 0.17.x, if I ran `yarn build` — which is just calling `node esbuild.config.js` from an `esbuild.config.js` that looks a bit like 

```javascript
const SRCDIR = "app/javascript";
const OUTDIR = "app/assets/builds";
const PUBLIC_ASSETS = "public/assets"

require("esbuild").build({
  logLevel:      "info",
  entryPoints:   ["application.js", "flows.js", "forsa.js"],
  bundle:        true,
  minify:        process.env.NODE_ENV === "production",
  sourcemap:     true,
  outdir:        path.join(process.cwd(), OUTDIR),
  absWorkingDir: path.join(process.cwd(), SRCDIR),
  watch:         process.argv.includes("--watch"),
  plugins: [],
  define,
})
```

I got output with summaries:

```shell
➜  jt git:(main) yarn build
yarn run v1.22.19
$ node esbuild.config.js

  app/assets/builds/flows.js            437.2kb
  app/assets/builds/forsa.js            312.3kb
  app/assets/builds/application.js      294.0kb
  app/assets/builds/flows.js.map        642.7kb
  app/assets/builds/application.js.map  603.4kb
  app/assets/builds/forsa.js.map        546.1kb

✨  Done in 0.17s.
```

After upgrading to 0.17.18, the code now looks like:

```javascript
const SRCDIR = "app/javascript";
const OUTDIR = "app/assets/builds";
const PUBLIC_ASSETS = "public/assets"

const context = await esbuild.context({
  logLevel:      'info',
  entryPoints:   ["application.js", "flows.js", "forsa.js"],
  bundle:        true,
  minify:        process.env.NODE_ENV === "production",
  sourcemap:     true,
  outdir:        path.join(process.cwd(), OUTDIR),
  absWorkingDir: path.join(process.cwd(), SRCDIR),
  plugins: [],
  define,
})

await context.rebuild()
```

But running `yarn build` only gets me

```shell
➜  jt git:(esbuild-upgrade-017) yarn build
yarn run v1.22.19
$ node esbuild.config.js
✨  Done in 0.17s.
```

Is there something else I need to do to get summaries back? I've tried a small plugin to read the `results` from `onEnd`, but even though all my files are present and correct in the output dir, most of the `results` come back `undefined`:

```js
const plugins = [{
  name: 'my-plugin',
  setup(build) {
    build.onEnd(result => console.log(result));
  },
}];
```

gets me

```js
{
  errors: [],
  warnings: [],
  outputFiles: undefined,
  metafile: undefined,
  mangleCache: undefined
}
```

Is there something I missed in the upgrade [guide](https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#upgrade-guide-for-existing-code)?

PS Many thanks for this excellent tool. It got me off webpack, for which I will always be profoundly thankful.

**Comment by rgarner** [comment]
Can't tell from the CHANGELOG if we're supposed to implement our own build logging now, but managed to replicate the old functionality by using `metafile: true` and adding a custom plugin to use that data in the build results. It's not quite the same but it's pretty close (excuse the `filename.replace`, which is for my personal Rails working dir use case), if it helps anyone.

```js
import chalk from 'chalk';

const logOutputSize = {
  name: 'log-output-size',
  setup(build) {
    build.onEnd(result => {
      const summaries = Object.keys(result.metafile.outputs).map((filename) => {
        return {
          filename: filename.replace('..', 'app'),
          size: (result.metafile.outputs[filename].bytes / 1024).toFixed(1)
        }
      })

      if(summaries.length > 0) {
        const maxLength = Math.max(...summaries.map((s) => s.filename.length))

        console.log()
        summaries.forEach((s) => console.log("  " +  chalk.cyan(`${s.filename.padEnd(maxLength)} ${s.size}kb`)))
        console.log()
      }
    });
  },
};
```

**Comment by evanw** [comment]
The summary is printed by `build`, not by `rebuild`. So you can have esbuild print it for you by calling `build`.

**Comment by rgarner** [comment]
Ah, I'm an idiot, thank you. I knew it'd end up being something simple. Still, at least I learned how to make a plugin!

**Comment by rgarner** [comment]
Ah, I see it now, I just copied `rebuild` from the migration guide, assuming `build` was gone.
