### ISSUE TITLE
Log all onResolve or onLoad calls

### ISSUE THREAD

**Issue by espoal** [evanw/esbuild#3095]
**Problem:**

I would like to log all `onResolve` and or `onLoad` calls. I'm trying to follow [this](https://esbuild.github.io/plugins/#resolve) part of the doc, but I fall in the pitfall of having an infinite resolution loop. Here's roughly what I'm trying:

```js
export const logOnResolve = {
	name: 'logOnResolve',
	setup(build) {
		build.onResolve({ filter: /.*/ }, async (args) => {
			console.log({ args })
			const result = await build
				.resolve(/* I tried several different combinations here, 
                                without much success */)
			console.log({ result })
			return result
		})
	},
}
```

A similar problem happens with `onLoad` calls. How would you handle this @evanw ?

**Context:**

I'm trying to build a caching plugin for CI/CD. Don't think just building, but also testing, deploying, benchmarking, .... 
My idea is to build a Merkle tree of all the dependencies involved, store it in a format similar to `yarn.lock`, and then compare it against the `git diff` before pulling the branch. I would then conditionally re trigger building, testing, deploying... only against the changes.

Maybe you have a better approach in mind?

**Comment by evanw** [comment]
Here's an example of doing this without an infinite loop:

```js
const logOnResolve = {
  name: 'logOnResolve',
  setup(build) {
    build.onResolve({ filter: /.*/ }, async ({ path, ...args }) => {
      if (args.pluginData === 'logOnResolve') return
      console.log({ args })
      args.pluginData = 'logOnResolve'
      const result = await build.resolve(path, args)
      console.log({ result })
      return result
    })
  },
}
```

**Comment by evanw** [comment]
Closing because this question was answered, and there was no follow-up reply.
