### ISSUE TITLE
[feat] Ability to emit fullSpecified file extensions in imports

### ISSUE THREAD

**Issue by natew** [evanw/esbuild#3107]
Sorry to create another issue here, searching didn't return anything.

Any chance we could implemented a way to have esbuild automatically emit the fully specified file extensions?

Right now building for multiple environments gets a bit hairy as Metro and Webpack (depending on the version) both have different issues. It'd save quite a bit of time to be able to have esbuild handle adding the `.js` suffix, if possible.

**Comment by evanw** [comment]
You can do that yourself with a plugin: https://esbuild.github.io/plugins/#on-resolve. For example:

```js
import * as esbuild from 'esbuild'

let exampleAddJsPlugin = {
  name: 'add-js',
  setup(build) {
    build.onResolve({ filter: /.*/ }, args => {
      if (args.kind !== 'entry-point')
        return { path: args.path + '.js', external: true }
    })
  },
}

await esbuild.build({
  stdin: {
    contents: `
      import fn from './somewhere'
      fn()
    `,
  },
  bundle: true,
  plugins: [exampleAddJsPlugin],
  format: 'esm',
})
```

Running that code prints the following:

```js
// <stdin>
import fn from "./somewhere.js";
fn();
```

Using a plugin lets you build whatever custom path mangling logic you need. The logic likely isn't just "always append `.js`" and is likely case-specific to your project, which means it wouldn't be a good fit for something to build into esbuild itself. This behavior is better as a plugin so you have full control over what happens.

**Comment by natew** [comment]
Thank you, that’s perfect.
