### ISSUE TITLE
Issue with module federation and code splitting using es build

### ISSUE THREAD

**Issue by IdoMor** [evanw/esbuild#3108]
Hello,

I am encountering an issue when using es build with module federation and code splitting. It seems that if a remote and host use different versions of the same library built with es build, the chunks of that library would not be shared, even though they are specified as shared in the module federation configuration. This results in broken code.

I believe this issue could be resolved if names could be given to chunks, which would allow for shared chunks to be properly identified and shared across different versions of the same library.

Thank you for your attention to this matter. Please let me know if you need any additional information or if you have any questions.

Best regards,
Ido

**Comment by evanw** [comment]
Module federation is not something that esbuild supports, sorry. I consider it to be outside of esbuild's scope.

**Comment by IdoMor** [comment]
But this is not an issue with module federation, it is a request to allow for named chunks
I had only described the issue with module federation to elaborate the need for this feature

**Comment by evanw** [comment]
I'm closing this issue as a duplicate because the feature request for giving custom names to output files is already covered by #553.
