### ISSUE TITLE
get css inline

### ISSUE THREAD

**Issue by herrKlein** [evanw/esbuild#3109]
I am using esbuild to build a component library, and using css for each of the components.
I use Vite as a dev environment, In Vite I use ```css?inline```, and use the css string to construct styles in the component itself.
```js
import otherStyles from './bar.css?inline' // otherStyles will be available as a string
```
I know vite (dev env) is based on esbuild, so it should be possible , But can't seem to get this inline css to work in esbuild. Esbuild does parse the import but makes an external css. Does anyone know how to replicate this ```?inline``` behaviour in an esbuild? I Can't find a plugin and cannot find it in the docs.

**Is it possible in the default esbuild to get the processed css as a string?**

**Comment by herrKlein** [comment]
This plugin seems to have this feature by using type: "css-text", but it does not work..
I suspect the default behaviour of esbuild is ahead of this plugin..
https://www.npmjs.com/package/esbuild-sass-plugin

In the docs of esbuild this is mentioned
> This loader is enabled by default for .css files
https://esbuild.github.io/content-types/#css

How can we disable this default behaviour of esbuild and css, so that I can let the plugin do his work

**Comment by herrKlein** [comment]
Thanks for the effort, can't get it too work yet, it enters the onResolve, but not the onLoad. Reading into how onLoad should work now. 
I assume you also use esbuild to process the imported css file. ?

**Comment by hyrious** [comment]
How did you use that? It works for me. Here's what I did:

```js
// style.css
body { color: red }

// index.js
import style from './style.css?inline'
console.log(style)

// build.mjs
import { build } from "esbuild";
const InlineCSSPlugin = { ... };
build({
  entryPoints: ["index.js"],
  outfile: "bundle.js",
  bundle: true,
  plugins: [InlineCSSPlugin],
}).catch(() => process.exit(1));
```

Outputs:

```js
// bundle.js
(() => {
  // inline-css:/private/tmp/test/style.css
  var style_default = "/* style.css */\nbody {\n  color: red;\n}\n";

  // index.js
  console.log(style_default);
})();
```

**Comment by herrKlein** [comment]
Thanks, it looked like, although I had a breakpoint, the debugger did not stop when entering the onload, thanks for the complete example, seems to work now!
