### ISSUE TITLE
Emit "use client" directive for RSC builds

### ISSUE THREAD

**Issue by vicary** [evanw/esbuild#3115]
React Server Components require client-only components to be served with a module-level directive [`"use client"`](https://nextjs.org/docs/getting-started/react-essentials#the-use-client-directive), hook authors are now required to add them to stay forward compatible.

Is there a way to tell esbuild to keep them in the final ESM bundle?

**Comment by evanw** [comment]
Unknown directives are currently stripped by the minifier. I can change esbuild to preserve them instead. In the meantime, you can use the [banner feature](https://esbuild.github.io/api/#banner) to do this.

**Comment by milovangudelj** [comment]
Sorry to jump in here after all this time but I'll need this soon and just adding a banner to the entire bundle seems a bit excessive. It's been a while since I've used esbuild so I might have forgotten a few things that can circumvent this issue.

Let me know if the situation has changed or not and if there's some magic trickery I can use to keep the directive only for the components that actually need it.

**Comment by vicary** [comment]
Esbuild does it's job at the referenced commit, but my experience says that the whole toolchain is usually more than esbuild.

You may need to code split via something like `await import()`, such that `"use client"` has a separate file to stay, and make sure subsequent processors (if they exist) do not remove them again.

**Comment by clearly-outsane** [comment]
Did this get released? I can't find it in the docs

**Comment by Seojunhwan** [comment]
Hello everyone,

I wanted to follow up on this issue as I've developed a plugin that might help address this problem: https://github.com/Seojunhwan/esbuild-plugin-preserve-directives

This plugin is specifically designed to preserve directives like "use client" in esbuild output. I created it as a potential solution for those who need this functionality before it's natively implemented in esbuild.

Key features of the plugin:
1. Preserves "use client" and other directives in the output
2. Works with both JavaScript and TypeScript files
3. Configurable to preserve specific directives

I'd love to get your feedback on this approach. Has anyone else been working on similar solutions? Do you see any potential issues or improvements?

If you try it out, please let me know how it works for you. I'm open to suggestions and contributions to make it more robust and useful for the community.

This could serve as a temporary solution for users who need to preserve the "use client" directive in their RSC builds while we wait for native support in esbuild.

**Comment by oscarteg** [comment]
Any library that has client components and server components needs this.
