### ISSUE TITLE
Live reload not working

### ISSUE THREAD

**Issue by gusma296** [evanw/esbuild#3118]
can anyone help, this is my config, i've added event source but it still doesn't work, i think it's because i added createServer to handle routes and error 404, how can both of them work? please help me to solve this.

```
import * as esbuild from 'esbuild'
import open from "open"
import http from 'http';

const args = process.argv.slice(2)
const watch = args.includes('--watch')
const clients = [];

const watchPlugin = {
  name: 'watch-plugin',
  setup(build) {
    build.onStart(()=>{console.log(`Build Starting : ${new Date(Date.now()).toLocaleString()}`)})
    build.onEnd((result)=> {
      if (result.errors.length > 0) {
        console.log(`Build Finished, with errors: ${new Date(Date.now()).toLocaleString()}`);
      }else{
        console.log(`Build Finished successfully: ${new Date(Date.now()).toLocaleString()}`);
      }
    })
  }
}

const context = await esbuild.context({
    entryPoints: ['src/index.js'],
    bundle: true,
    // sourcemap: 'external',
    // minify: false,
    outdir: "public",
    plugins:[watchPlugin],
    // format: "esm",
    // splitting:true,
    // metafile:true,
    // treeShaking: true,
    // publicPath:'/',
    loader:{
      ".svg":"dataurl",
      ".js": "jsx",
      ".png": "dataurl"
    },
    banner: {
      js: "(() => { (new EventSource(\"/esbuild\")).addEventListener('change', () => location.reload()); })();"
  },
  
  })

if (watch) {
  await context.watch();
  await context.serve({
    host: 'localhost',
    port: 8000,
    servedir:'public',
  }).then((result)=>{
    const { host, port } = result;
    
    http.createServer((req, res) => {
      const { url, method, headers } = req;
      if (req.url === '/esbuild'){
        return clients.push(
          res.writeHead(200, {
            'Content-Type': 'text/event-stream',
            'Cache-Control': 'no-cache',
            Connection: 'keep-alive',
          }))
      }
    const path = ~url.split('/').pop().indexOf('.') ? url : `/index.html`
    req.pipe(
      http.request({ hostname: host, port: port, path, method, headers }, (prxRes) => {
        res.writeHead(prxRes.statusCode, prxRes.headers)
        prxRes.pipe(res, { end: true })
      }),
      { end: true }
    )}).listen(8000);

    open("http://localhost:8000/").then(()=>{
      console.log(`Local: http://localhost:8000/`,);
    })
    
  })
}else{
  await context.rebuild();
  context.dispose();
}
```

**Comment by Valexr** [comment]
Proxy server needs different port then ctx.serve()

**Comment by Valexr** [comment]
For example https://github.com/Valexr/esbuild-svelte-ts/blob/405fc1ca83b5f3aa4d72e0805589136bf81d0fb0/esbuild.js#L50w

**Comment by evanw** [comment]
I'm closing this because it looks like this question has been answered: two Unix sockets cannot share the same port. Thanks for answering the question by the way.

**Comment by hyrious** [comment]
1. You have to use different ports for esbuild server and your custom http server.
2. You have to forward '/esbuild' request to the esbuild server so that it can send SSE messages to the client. In your example you catched all /esbuild requests in your custom server but didn't do anything to the clients e.g. send update events on each rebuild.

Here's an example script to do so:

```js
import esbuild from "esbuild";
import http from "http";

const args = process.argv.slice(2);
const watch = args.includes("--watch");

const context = await esbuild.context({
  entryPoints: ["src/index.js"],
  bundle: true,
  outdir: "public",
  banner: {
    js: "(() => { (new EventSource(\"/esbuild\")).addEventListener('change', () => location.reload()); })();",
  },
});

if (watch) {
  await context.watch();
  const { host, port } = await context.serve({
    host: "localhost",
    port: 8000,
    servedir: "public",
  });
  const server = http.createServer((req, res) => {
    const { method, headers } = req;
    const url = new URL(req.url, `http://${req.headers.host}`);
    const path = url.pathname === "/" ? "/index.html" : url.pathname;
    const proxyReq = http.request(
      { hostname: host, port: port, path, method, headers },
      function handler(proxyRes) {
        res.writeHead(proxyRes.statusCode, proxyRes.headers);
        proxyRes.pipe(res, { end: true });
      }
    );
    req.pipe(proxyReq, { end: true });
  });
  server.listen(3000, () => {
    console.log(`Local: http://localhost:3000/`);
  });
} else {
  await context.rebuild();
  context.dispose();
}
```

**Comment by gusma296** [comment]
> 1. You have to use different ports for esbuild server and your custom http server.
> 2. You have to forward '/esbuild' request to the esbuild server so that it can send SSE messages to the client. In your example you catched all /esbuild requests in your custom server but didn't do anything to the clients e.g. send update events on each rebuild.
> 
> Here's an example script to do so:
> 
> ```js
> import esbuild from "esbuild";
> import http from "http";
> 
> const args = process.argv.slice(2);
> const watch = args.includes("--watch");
> 
> const context = await esbuild.context({
>   entryPoints: ["src/index.js"],
>   bundle: true,
>   outdir: "public",
>   banner: {
>     js: "(() => { (new EventSource(\"/esbuild\")).addEventListener('change', () => location.reload()); })();",
>   },
> });
> 
> if (watch) {
>   await context.watch();
>   const { host, port } = await context.serve({
>     host: "localhost",
>     port: 8000,
>     servedir: "public",
>   });
>   const server = http.createServer((req, res) => {
>     const { method, headers } = req;
>     const url = new URL(req.url, `http://${req.headers.host}`);
>     const path = url.pathname === "/" ? "/index.html" : url.pathname;
>     const proxyReq = http.request(
>       { hostname: host, port: port, path, method, headers },
>       function handler(proxyRes) {
>         res.writeHead(proxyRes.statusCode, proxyRes.headers);
>         proxyRes.pipe(res, { end: true });
>       }
>     );
>     req.pipe(proxyReq, { end: true });
>   });
>   server.listen(3000, () => {
>     console.log(`Local: http://localhost:3000/`);
>   });
> } else {
>   await context.rebuild();
>   context.dispose();
> }
> ```

thanks for answering, but
i have tried your code, but i still get error 404 when i move web page for example localhost:3000/about

![image](https://github.com/evanw/esbuild/assets/47033246/94f99a5b-e4f6-46fd-85ac-84cf6d5513e5)

**Comment by hyrious** [comment]
@gusma296 You have to implement the routing (e.g. redirect 404 to / like spa) by yourself.

For example, if path is not / and proxyRes.statusCode is 404, try again with path = /.

**Comment by gusma296** [comment]
@hyrious I got this, thanks.
