### ISSUE TITLE
Nested selectors with pseudo-elements result in invalid selectors

### ISSUE THREAD

**Issue by yusuke-omae** [evanw/esbuild#3119]
esbuild version: 0.17.19

Suppose you enter the following CSS:
```
.foo {
  position:relative;
  &::before, &::after {
    position: absolute;
    content:"";
  }
}
```

expected transform css
```
.foo {
  position: relative;
}
.foo::before,
.foo::after {
  position: absolute;
  content: "";
}
```

actual transform css
```
.foo {
  position: relative;
}
.foo:is(::before, ::after) {
  position: absolute;
  content: "";
}
```

Because of the [specification](https://drafts.csswg.org/selectors/#matches) that pseudo-elements cannot be placed in the `:is()` selector, it is treated as an invalid selector in the current implementation.

> Pseudo-elements cannot be represented by the matches-any pseudo-class; they are not valid within [:is()](https://drafts.csswg.org/selectors/#matches-pseudo).

**Comment by evanw** [comment]
As far as I can tell, pseudo-elements deliberately don't work with CSS nesting according to the CSS nesting specification (https://www.w3.org/TR/css-nesting-1/#ref-for-matches-pseudo%E2%91%A0):

> The [nesting selector](https://www.w3.org/TR/css-nesting-1/#nesting-selector) cannot represent pseudo-elements (identical to the behavior of the [:is()](https://www.w3.org/TR/selectors-4/#matches-pseudo) pseudo-class).

So I believe esbuild is working correctly here. Both `.foo { &::before {} }` and `.foo:is(::before) {}` are equivalent according to the specification, and are equally invalid. Transforming `.foo { &::before {} }` into `.foo::before {}` would be incorrect because it's not equivalent.

**Comment by evanw** [comment]
I'll ask for clarification on this behavior. Right now there is only one implementation of this (Chrome) so it's hard to say what's a bug and what isn't. The CSS nesting specification is also still being actively changed so it's hard to say what the eventual behavior of CSS nesting is going to end up being. We'll have to wait and see. I know the people on CSS nesting want to remove this restriction. It sounds like they want to fix this by changing `:is()` to work with pseudo-elements, at which point this will automatically start working.

**Comment by evanw** [comment]
I'm reopening this because it looks like you're right. That part of the specification only applies to pseudo-elements that come in through the `&` selector from the parent selector, but not to any of those that are joined with the `&` selector later.
