### ISSUE TITLE
esbuild doesn't work in nodejs v20

### ISSUE THREAD

**Issue by its-dibo** [evanw/esbuild#3123]
I upgraded my nodejs to v20, but I noticed that the generated output is not bundled, even not compiled, i.e the contents of output/index.mjs is almost the same as src/index.ts with minor changes.

when i revert back into nodejs v19 it worked correctly.

I tested it in windows x64 and ubunto

**Comment by hyrious** [comment]
I'm using node20 too and didn't notice this issue. Maybe you should provide a reproduction to make it clear.

**Comment by its-dibo** [comment]
so far, I think the problem occurs when importing from an alias path
