### ISSUE TITLE
Question: conditional (ternary) operator

### ISSUE THREAD

**Issue by winsycwen** [evanw/esbuild#3127]
When I configure minify at https://esbuild.github.io/try/ to compile the code that contains the ternary operation, why is the result of compilation different when using it in a function?

The Code:
 ```
String((val === null || val === undefined) ? '' : val)
```

When I put the above code into the function, I thought the compiled result would be the same, but it doesn't

```
function coerceToString(val) {
    return String((val === null || val === undefined) ? '' : val);
}
```

Result:
![image](https://github.com/evanw/esbuild/assets/4016739/a7f170c6-7e75-4085-9098-0d02168ce5e2)

**Comment by hyrious** [comment]
I think the difference is the `val` in function param is known as a variable name, while a global `val` is maybe a call to `window.val` which may have side effects. So in your first example, the call to `window.val` cannot be simplified to once.

**Comment by evanw** [comment]
Yes, this is correct. Every global variable access is a property access, which might be a call to an arbitrary getter function with important side effects. For example, the getter might count how many times it’s accessed. It would also be incorrect to apply that transformation to this equivalent code:

```js
String((obj.val === null || obj.val === undefined) ? '' : obj.val)
```

I’m closing this issue as esbuild is working correctly here.
