### ISSUE TITLE
Esbuild simplifies outputfile path when its not wanted

### ISSUE THREAD

**Issue by Patrick-clone** [evanw/esbuild#3128]
I have these entry points: (using [glob](https://www.npmjs.com/package/glob) `./src/*/index.{ts,css}`)
```
src/project1/index.ts
src/project1/index.css
```

But when I have 1 "project" the output is (using `--outdir=dist`):
```
dist/index.js
dist/index.css
```

I expect the output to be:
```
dist/project1/index.ts
dist/project1/index.css
```

This is the case when I add a second project like:
```
src/project1/index.ts
src/project1/index.css
src/project2/index.ts
src/project2/index.css
```
Then the output is what I expected:
```
dist/project1/index.ts
dist/project1/index.css
dist/project2/index.ts
dist/project2/index.css
```

I'm using esbuild version: `0.17.18`

**Comment by hyrious** [comment]
This is documented here: https://esbuild.github.io/api/#outbase

> If the outbase directory isn't specified, it defaults to the [lowest common ancestor](https://en.wikipedia.org/wiki/Lowest_common_ancestor) directory among all input entry point paths. This is `src/pages` in the example above, which means by default the output directory will contain `home/index.js` and `about/index.js` instead.

**Comment by Patrick-clone** [comment]
@hyrious Thank you very much for the (quick) answer. I was not aware of this option.
