### ISSUE TITLE
Treeshaking when using `esbuild-wasm` on the browser isn't as efficient as when running locally

### ISSUE THREAD

**Issue by okikio** [evanw/esbuild#3129]
In order to supprt npm packages I'm basically using a plugin to auto fetch the packages and their files from https://unpkg.com, I'm manually fetching the `package.json` as well and setting up the resolves all manually, but this method seems to cause issues with esbuilds treeshaking system.

e.g. https://github.com/okikio/bundlejs/issues/51
https://bundlejs.com/?q=date-fns&treeshake=%5B%7B+isAfter+%7D%5D

^ For this specific bundle of `date-fns` only `{ isAfter }` is exported, but the final resulting bundle for some reason brings in the parser, I can't find the reason why the parser is brought in

**Comment by okikio** [comment]
I've found that if I use esbuild as an import traversal system to fetch all the packages and files required, and then run esbuild again the treeshake then works, is there a better approach to get esbuild treeshaking to work better? https://bundle-git-treeshaking-fix-okikio-dev.vercel.app/

**Comment by evanw** [comment]
Can you be specific about what issues it causes? Why is tree shaking happening in some cases but not others? Sorry, I don't understand why this is happening from what you've written.

**Comment by okikio** [comment]
Hey there, sorry if my previous explanation was a bit muddled. Let's dive back into it.

## Case 1 - Fetch and Go

In this first scenario, I'm using just one plugin to sort out imports. So, when I come across something like `import react from "react"`, I fetch it straight from https://unpkg.com and pass it to the plugin loader. This gets us the bundle we're after, but the tree shaking is a bit rough around the edges. 

I've compared this fetch-and-go approach to running `esbuild-wasm` the usual way and noticed that `esbuild` seems to do a better job with tree shaking when it's not relying on plugins to do the heavy lifting. For some reason, it has a bit of a hard time when a plugin is involved in fetching packages from outside sources. 

## Case 2 - Fetch, Store, Reuse

This next scenario is like an upgrade from the first. This time, all the loaded files are stored in a temporary virtual file system, and we're using a plugin to pull files from there. 

Here's how it works: First, we fire up `esbuild`, but with specific instructions to only worry about loading the external files into the virtual file system for the first run. Think of `esbuild` here as a path-traversal assistant. 

After this initial run, we toss out `esbuild`'s results, then take it for another spin. But now, we're telling `esbuild` to only use the virtual file system plugin to find packages. The cool thing is, this actually results in a bundle that's properly tree shaken.

The puzzling part is why this issue pops up in the first place. It seems like `esbuild` is quick on its feet fetching files and modules when they're already in memory. That's why I'm guessing there could be some kind of race condition that's tripping up the tree shaking process.

Anyway, hope that clears things up a bit. Feel free to ping me if you've got more questions.

**Comment by evanw** [comment]
Is there any difference in the `metafile` for both builds? For example, is one build using that package's `main` field while another build is using that package's `module` field? That would explain a difference in tree shaking because tree shaking only works with ESM, not with CommonJS. What you described (downloading the files ahead of time vs. on the fly) sounds like it should should be providing the exact same inputs to esbuild, which should then result in the exact same outputs. If the inputs to esbuild are different in these two cases, then it sounds like it'd be due to some problem with the plugin you wrote, which you should be able to fix for yourself. In any case, providing a self-contained way to reproduce the problem you are describing would be helpful here.

**Comment by okikio** [comment]
I'll try to create a self-contained reproduction

**Comment by okikio** [comment]
@evanw Sorry for the delay it took me a couple days to get a clean repro https://github.com/okikio/esbuild-wasm-treeshake-repro
> Note: the approach taken in the repro doesn't cover edge cases to make things easier to understand

The result of using esbuild without on nodejs to bundle and treeshake `export { isAfter } from "date-fns";` is `1.5Kb` treeshaken and bundled, and `99.8Kb` when using the plugins, with treeshaking and bundling enabled

**Comment by hyrious** [comment]
Well I found something in the `logLevel: 'verbose'` log:

```
Marking this file as having no side effects due to "/node_modules/date-fns/esm/add/package.json"
```

That is to say when using plugins, esbuild won't know lines below has no side effects becasue it won't check package.json in without FS access.

```js
// date-fns@2.30.0/package/esm/index.js:2
export { default as add } from "./add/index.js";
// and other thousands of lines ...
```

**Comment by okikio** [comment]
OH!! OH my gosh, that explains a lot, what heuristics from the `package.json` does esbuild use to determine if something has `sideEffects`

**Comment by okikio** [comment]
@hyrious @evanw Is there a way to let `esbuild-wasm` know of a `package.json` file to use from a plugin?

**Comment by hyrious** [comment]
AFAIK there's no way to let a plugin provide such info. That's why https://esbuild.github.io/try/ needs the hacking way to provide FS in browser.

**Comment by okikio** [comment]
😭 :sad esbuild noises:

**Comment by jakebailey** [comment]
Technically, you can use WASI instead to run the CLI version in the browser, using a full VFS: https://github.com/jakebailey/esbuild-playground/blob/main/src/esbuild/wasiWorker.ts

But, you won't get the JS API, only the CLI.

**Comment by okikio** [comment]
That unfortunately wouldn't support npm packages

**Comment by jakebailey** [comment]
It's a VFS; you can mount whatever you want into it. I'm not sure how you're getting packages into `esbuild-wasm` in the browser as it is now; plugins?

**Comment by okikio** [comment]
Yep, plugins
