### ISSUE TITLE
Build and copy and entire directory of database migrations

### ISSUE THREAD

**Issue by pthieu** [evanw/esbuild#3130]
Not sure if this has already been covered, please close if it has.

I am using https://github.com/kysely-org/kysely and I have a list of database migration files ordered by filename. Something like:
```
db/migrations/yyymmdd_name.ts
```

To run the migrations, I have a function:
```
  const db = new Kysely<DB>({
    dialect: new PostgresDialect({
      pool: new Pool({ connectionString: config.DATABASE_URL }),
    }),
  });

  const migrator = new Migrator({
    db,
    provider: new FileMigrationProvider({
      fs,
      path,
      migrationFolder: path.join(__dirname, 'migrations'),
    }),
  });

  const { error, results } = await migrator.migrateToLatest();
```

This looks through the directory and runs the migrations. This works well if I use `tsx` and run a file with this:

```
import { migrateToLatest } from '../src/db/lib';
migrateToLatest();
```

It also works well in local dev if I import and run the function before server start.

I'm looking at how to deploy the service and because we currently use `esbuild` to bundle and minify to a single `index.js`, the `migrationFolder: path.join(__dirname, 'migrations')` line will not work.

Is there a way to transpile all the migration files into JS and copy them to a folder `/dist/yyymmhh_name.js`?

**Comment by hyrious** [comment]
Maybe you can just put all files in that folder (with a glob library, for example) to esbuild's [entryPoints](https://esbuild.github.io/api/#entry-points) option and set an [output folder](https://esbuild.github.io/api/#outdir).

In case you don't have shell expansion (`*`) on server, here's a possible script way to invoke esbuild:

```js
import fs from "fs"
import path from "path"
import esbuild from "esbuild"

const entryPoints = fs.readdirSync('db/migrations')
  .filter(e => e.endsWith('.ts'))
  .map(e => path.join('db/migrations', e))

esbuild.build({
  entryPoints,
  bundle: true,
  format: 'esm',
  outdir: 'dist',
  packages: 'external',
}).catch(() => process.exit(1))
```

**Comment by pthieu** [comment]
@hyrious thanks, this works. I was so fixated on making it work in 1 step, I didn't think to use a second.

Do you know if it's possible to combine entry points? In my CI/CD, I'm not planning to include the `node_modules` folder in the Docker container image, so if I don't set `packages: 'external'`, there will be a lot of repeated code.

Or maybe a way to automatically include compiled dependencies in another output file that are used by the migration files only and not the rest of the code?

**Comment by hyrious** [comment]
I'm not sure what dependencies it could depends on and what the impact will be if bundled twice (one in the main server, another one in the migration script). The [Kysely](https://github.com/kysely-org/kysely#mysql-migration-example) migration example seems only depends on the typings of the `db` variable, in which case nothing will get bundled in except the script itself.

I think it will also be okay to bundle the model definitions files, they are just schemas and are meant to be pure.

**Comment by pthieu** [comment]
In some of the migration files, to do a raw migration, Kysely allows for the `sql` template literal function to be imported via: `import { sql } from 'kysely';`

Should be ok for now, just wanted to know what my options are.
