### ISSUE TITLE
Add V8 as valid target environment?

### ISSUE THREAD

**Issue by eigilsagafos** [evanw/esbuild#3134]
I'm using esbuild to bundle functions that run on V8 (plv8 in postgres). Currently I'm using node as target. It would have made more sense if v8 was a valid target so that errors where thrown if I tried to use something from the node std library.

**Comment by hyrious** [comment]
Since you just want to get errors when importing node libraries, I think you can just set `platform` to `browser` and set `format` to `cjs`.

**Comment by eigilsagafos** [comment]
That would produce the same problem but with browser apis

**Comment by hyrious** [comment]
Note that `platfom: "node"` only passes cases when you're **importing** node builtin libraries. esbuild actually does not check a global name you're referencing is whether from browser or node.

For example, this code always passes no matter what option you passed:

```js
location.reload()
```

**Comment by evanw** [comment]
Adding V8 as a valid target environment would be relevant if you wanted to pass esbuild a specific V8 version (e.g. [V8 11.6.64](https://github.com/v8/v8/releases/tag/11.6.64)) and have esbuild limit its use of JavaScript syntax features to whatever that build of V8 supports. This would not change anything regarding path resolution, as that's not what esbuild's `target` setting does.

Unfortunately I don't think this is currently feasible. The target environments that I support are drawn from here: https://kangax.github.io/compat-table/. That data source has a lot of different environments including many based on V8, but it does not have V8 itself. So I'm going to close this issue as "won't fix" for that reason.

Note that if you want to turn off esbuild's platform-specific behaviors, you can set esbuild's platform to `neutral`, in which case it won't do anything specific to either `browser` or `node`.
