### ISSUE TITLE
wasm.js not working the same as mod.js in Deno.

### ISSUE THREAD

**Issue by BlackAsLight** [evanw/esbuild#3136]
So I have this small build script in Deno and it works as expected. It takes all the files in `./ts/` and converts a `.js` and `.min.js` version of each. However, when switching out the import from `mod.js` to `wasm.js`, it at first appears to work the same, but the files never actually get written to disk even though every call to the esbuild function has resolved and the console.log at the bottom has executed.
```ts
import { build, stop } from 'https://deno.land/x/esbuild@v0.17.19/mod.js'
import { denoPlugins } from 'https://deno.land/x/esbuild_deno_loader@0.7.0/mod.ts'

const startTime = performance.now()

const path = await Deno.realPath(`./`)
async function esbuild(inPath: string, outPath: string, minify: boolean) {
	console.log(`Compiling: .${inPath.slice(path.length)} -> .${outPath.slice(path.length) }`)
	const { errors, warnings } = await build({
		plugins: denoPlugins(),
		entryPoints: [ inPath ],
		outfile: outPath,
		format: 'esm',
		bundle: true,
		minify: minify
	})
	errors.forEach(error => console.error(error))
	warnings.forEach(warning => console.warn(warning))
}

try {
	await Deno.remove('./static/js/', { recursive: true })
}
// deno-lint-ignore no-empty
catch { }
finally {
	await Deno.mkdir('./static/js/', { recursive: true })
}

const promises: Promise<void>[] = []
for await (const dirEntry of Deno.readDir('./ts/')) {
	if (!dirEntry.isFile || !dirEntry.name.endsWith('.ts'))
		continue

	promises.push(esbuild(`${path}/ts/${dirEntry.name}`, `${path}/static/js/${dirEntry.name.slice(0, dirEntry.name.lastIndexOf('.'))}.min.js`, true))
	promises.push(esbuild(`${path}/ts/${dirEntry.name}`, `${path}/static/js/${dirEntry.name.slice(0, dirEntry.name.lastIndexOf('.'))}.js`, false))
}
await Promise.allSettled(promises)
stop()

console.log(`${(performance.now() - startTime).toLocaleString('en-US', { maximumFractionDigits: 2 })}ms`)
```
Is this a bug or am I meant to use the `wasm.js` version differently to the `mod.js` version?

**Comment by binyamin** [comment]
In general, WASM code must be initialized before running. Esbuild exports an `initialize()` function, which you should call as early as possible. Try it and report back. :smiley:

**Comment by BlackAsLight** [comment]
Doing `await initialize({})` did work thanks, but since I'm importing a .js file, I do wonder why said file doesn't just initialise itself.

**Comment by BlackAsLight** [comment]
I spoke too soon in my previous message. I just noticed now that although Deno does end itself after compiling instead of hanging, I am not getting the files written to disk like I am with the mod.js version. I am also noticing slower performance overall with the wasm.js build.

**Comment by hyrious** [comment]
I believe this is because the wasm.js does not have FS access:
https://github.com/evanw/esbuild/blob/e6a8169c3a574f4c67d4cdd5f31a938b53eb7421/lib/deno/wasm.ts#L123

Talking about performance, there's no multi-thread support in (one instance of) WebAssembly. So it must be slower than the native one.

**Comment by BlackAsLight** [comment]
I don't know how I'd set that to true, if I am even able to, but if its going to perform slower then I'll just stick with the mod.js version. Thanks anyway
