### ISSUE TITLE
Unexpected results with `{ in: ..., out: ... }` entry points 

### ISSUE THREAD

**Issue by musjj** [evanw/esbuild#3140]
```js
let result = await esbuild.build({
  entryPoints: [
    { in: 'foo.js', out: 'sub' },
    { in: 'bar.css', out: 'sub' },
  ],
  bundle: true,
  outdir: 'dist',
})
```

Expected output files:
```
dist/sub/foo.js
dist/sub/bar.css
```
What I got:
```
dist/sub.js
dist/sub.css
```

Am I doing something wrong here?

**Comment by hyrious** [comment]
The `out` config is for output file's basename (without extension). Other parts of the path are controlled by `outdir`, `outbase` and `outExtension`.

So it should be:

```js
let result = await esbuild.build({
  entryPoints: [
    { in: 'foo.js', out: 'foo' },
    { in: 'bar.css', out: 'bar' },
  ],
  bundle: true,
  outdir: 'dist/sub',
})
```

And since the `out` is the same as basename(`in`), esbuild already infers that when you just put entry files in this form:

```js
entryPoints: ['foo.js', 'bar.css']
```

**Comment by musjj** [comment]
Huh, I thought the `{ in: ..., out: ...}` structure was introduced so that you can output multiple files into the same folder? At least that's what the [CHANGELOG.md](https://github.com/evanw/esbuild/blob/main/CHANGELOG.md#0171) implied:
```js
// You can now specify duplicate output paths as an array of objects
let result = await esbuild.build({
  entryPoints: [
    { in: 'foo.js', out: 'dist' },
    { in: 'bar.css', out: 'dist' },
  ],
})
```
What I wanted to do is that I want to output paths into different directories.
I have something like:
```
src/index.html
src/main.js
assets/image.png
```
And I wanted to output it into this structure:
```
dist/index.html
dist/main.js
dist/assets/image.png
```
Is there any way to achieve this?

**Comment by hyrious** [comment]
Again, the `out` is not folder name. You can control the folder name with other options like outdir and xxxNames.

In your case, if the image.png is imported in main.js with loader = file, then you could make use of the [`assetNames`](https://esbuild.github.io/api/#asset-names) option:

```js
// src/main.js
import image from "../assets/image.png"
foo(image)

// esbuild config
assetNames: "assets/[name]",
outdir: "dist",
```

If you do not reference the image in the js and just want to copy, you can make use of the copy loader:

```js
// esbuild config
entryPoints: {
  "main": "src/main.js",
  "assets/image": "assets/image.png",
},
outdir: "dist",
loader: { ".png": "copy" },
```

**Comment by musjj** [comment]
Thanks for the clarification. I was misled by the "dist" naming scheme in the example.
