### ISSUE TITLE
bundle will rewrite target

### ISSUE THREAD

**Issue by 2239559319** [evanw/esbuild#3152]
![image](https://github.com/evanw/esbuild/assets/34960995/71474477-5be6-4cc5-9f54-3f635897e5ba)
![image](https://github.com/evanw/esbuild/assets/34960995/74416224-9568-486e-922c-b0097d587cae)
Target will not take effect when bundle set to true.

**Comment by hyrious** [comment]
If you assume `bundle: true` implies `target: 'es5'` then your `const` becomes `var`, then you're wrong. It becomes `var` because esbuild has an optimization in bundle mode where all top-level variable names are hoisted together to avoid some performance issues (#2889).
