### ISSUE TITLE
Crawl esbuild imports/require resolutions without bundling?

### ISSUE THREAD

**Issue by joshbrew** [evanw/esbuild#3155]
Hey guys, love esbuild. I'm working on my own little quality-of-life dev tool called tinybuild (like parcel or something) and I am stumped on one question. I'm doing some things where I am crawling import paths and collecting certain file extensions into their own file for bundling, namely css and related formats. However, I don't need to bundle all of the code, and bundle:false won't continue resolving imports as far as I can tell, while bundle:true will compile the code even though I just toss it out after. All I need is to run the import resolution step with the plugin, is there a setting I'm missing?

**Comment by evanw** [comment]
No, you're not missing anything. You need bundling to crawl esbuild imports/require resolutions.

**Comment by joshbrew** [comment]
Got it, I am just thinking if there's a way to skip a lot of the text in that case, just look for import/require. Keep up the amazing work!

**Comment by joshbrew** [comment]
I have a fine alternative for the specific thing I was working on (related to caching dependencies for hot swapping) so this is okay. I need to understand some of this bundling better but it's basically just reading text so it's not really gonna slow much down.

**Comment by evanw** [comment]
There isn't a way to crawl imports with esbuild without bundling. That's not something esbuild was designed for. If you don't have to deal with TypeScript and you need extreme speed (faster than esbuild's bundler), then you may find these libraries helpful instead:

* https://github.com/guybedford/es-module-lexer
* https://github.com/nodejs/cjs-module-lexer

These libraries exist to extract imports from JavaScript without even parsing the file. You would have to write your own path resolution though.

**Comment by joshbrew** [comment]
> There isn't a way to crawl imports with esbuild without bundling. That's not something esbuild was designed for. If you don't have to deal with TypeScript and you need extreme speed (faster than esbuild's bundler), then you may find these libraries helpful instead:
> 
> * https://github.com/guybedford/es-module-lexer
> * https://github.com/nodejs/cjs-module-lexer
> 
> These libraries exist to extract imports from JavaScript without even parsing the file. You would have to write your own path resolution though.

Thank you, I realized I was overdoing it anyway with my particular problem, got my sass hot swapping up in a huge app (takes about 5s to bundle first time) and now it's handling the css/scss for live dev in <200ms, yay! It's a plugin that lets me specify any extensions and apply rebuild rules to them for live dev, and otherwise I have to do a full rebundle when I change the js anyway so that takes care of updating the cached list of subdependencies. Very fast now!
