### ISSUE TITLE
How to set stdin.resolveDir in cli?

### ISSUE THREAD

**Issue by yang4515** [evanw/esbuild#3159]
```sh
echo 'export * from "./another-file"' | esbuild --bundle --resolve-dir=src
```

```js
import * as esbuild from 'esbuild'

await esbuild.build({
  stdin: {
    resolveDir: './src'
  }
})
```

**Comment by hyrious** [comment]
I believe the resolveDir is set to current working directory and there's no way to change that from command line.

https://github.com/evanw/esbuild/blob/a7a909605b1387b5c74d1bd0217af3fb4a843461/pkg/cli/cli_impl.go#L1113

**Comment by evanw** [comment]
You can use the `cd` command to change the current working directory when writing code for the command line:  https://manpages.org/cd (or https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/cd)

**Comment by yang4515** [comment]
Thank you for your response. I am using esbuild in a tauri project via tauri's sidecar method, so I cannot use the cd command to change the current directory. In the end, I was able to achieve the functionality by copying the file to the appropriate directory and then calling esbuild. The scenario in which I am using esbuild is that I have some built-in code in the tauri project, and the user's code will be bundled together with the built-in code. I need to move the user's code to the directory of the built-in code and then call esbuild.
