### ISSUE TITLE
Internal error causing panic when certain class static blocks are present

### ISSUE THREAD

**Issue by clydin** [evanw/esbuild#3161]
An [internal check](https://github.com/evanw/esbuild/blob/a7a909605b1387b5c74d1bd0217af3fb4a843461/internal/js_parser/js_parser.go#L11231) in 0.18.2 related to class downlevel info appears to be triggering and leading to a panic when `--minify-syntax` and `--bundle` are enabled with a static class block present that is empty or only contains certain expression statements. This does not occur in 0.18.1.

Minimal reproductions:
https://esbuild.github.io/try/#YgAwLjE4LjIALS1taW5pZnktc3ludGF4IC0tYnVuZGxlAGUAZW50cnkuanMAY2xhc3MgYSB7CiAgc3RhdGljIHt9Cn0
https://esbuild.github.io/try/#YgAwLjE4LjIALS1taW5pZnktc3ludGF4IC0tYnVuZGxlAGUAZW50cnkuanMAY2xhc3MgYSB7CiAgc3RhdGljIHsgYTsgfQp9
https://esbuild.github.io/try/#YgAwLjE4LjIALS1taW5pZnktc3ludGF4IC0tYnVuZGxlAGUAZW50cnkuanMAY2xhc3MgYSB7CiAgc3RhdGljIHsgU3ltYm9sLml0ZXJhdG9yOyB9Cn0

**Comment by evanw** [comment]
Really sorry about that. This case didn't have test coverage apparently. I'll push out a fix for this. Thank you very much for the report.

**Comment by alan-agius4** [comment]
Thanks for the swift action @evanw!
