### ISSUE TITLE
[bug] Upgrading from 0.17.x causes "Experimental decorators are not currently enabled" error

### ISSUE THREAD

**Issue by 0xAsimetriq** [evanw/esbuild#3163]
Just upgraded from `0.17.19` to `0.18.2` and started getting build error for "Experimental decorators are not currently enabled". It seems to be scoped only to `0.18.X` releases, and this feature is enabled like before in tsconfig.

**Comment by Leksat** [comment]
Facing the same issue. Not sure if it matters: in my case I got the error in a monorepo package.

(I also tried to pass `tsconfig: 'tsconfig.json'` to `rollup-plugin-esbuild`, but this makes no difference.)

**Comment by evanw** [comment]
This was a deliberate change. You now need to enable experimental decorators to use experimental decorators. I'm marking this issue as `unactionable` because it does not provide a way to reproduce the issue. It will later be closed if a way to reproduce the issue is not provided.

**Comment by 0xAsimetriq** [comment]
What's the correct way to enable them in v 0.18.x? At the moment we set `"experimentalDecorators": true` in our tsconfig, but seems it has no effect.

**Comment by evanw** [comment]
There's no way for me to tell if this is a bug with esbuild, or if esbuild is fine and the problem is somewhere else (e.g. with `rollup-plugin-esbuild`), because you still haven't provided a way for me reproduce the issue.

**Comment by Leksat** [comment]
Oh, `rollup-plugin-esbuild` does not send full tsconfig to `esbuild` and ignores `experimentalDecorators`:
https://github.com/egoist/rollup-plugin-esbuild/blob/c806163a584eb9ce95488e92d57933c1fc5b57df/src/options.ts#L44-L45

I'll open an issue in https://github.com/evanw/esbuild

**Comment by evanw** [comment]
@0xAsimetriq are you also using `rollup-plugin-esbuild` and have the same issue? If so, I'll close this issue in favor of https://github.com/egoist/rollup-plugin-esbuild/issues/365.

**Comment by 0xAsimetriq** [comment]
Yes, this is good to close
