### ISSUE TITLE
Bundling with declared unique symbol errors out

### ISSUE THREAD

**Issue by matray** [evanw/esbuild#3168]
Unfortunately this needed a slightly bigger reproduction case to show the error. Linked is a repo demonstrating it. 

https://github.com/matray/esbuild-repro

npm run build && npm run bundle to see the error output:

```
  matray ~/dev/esbuild-repro   main  npm run bundle

> esbuild-repro@1.0.0 bundle
> esbuild index.ts internal.ts internal2.ts internal3.ts --outdir=dist/ --bundle

✘ [ERROR] No matching export in "internal.ts" for import "CONCURRENCY_LIMITER"

    internal3.ts:1:9:
      1 │ import { CONCURRENCY_LIMITER } from "./internal"
        ╵          ~~~~~~~~~~~~~~~~~~~

✘ [ERROR] No matching export in "internal.ts" for import "CONCURRENCY_LIMITER"

    internal3.ts:1:9:
      1 │ import { CONCURRENCY_LIMITER } from "./internal"
        ╵          ~~~~~~~~~~~~~~~~~~~

2 errors
```

When not bundling, this works just fine for some reason 🤷 .

I would expect esbuild to simply ignore the imported `declare const x: unique symbol` when traversing through code and treat it as either a typescript type.

To avoid needing to navigate:
File 1:
```ts
import { CONCURRENCY_LIMITER } from "./internal";
export interface inner {
  _symbol: typeof CONCURRENCY_LIMITER
}
const breaking = 'BREAKING' as const
export type binner = inner | typeof breaking
```

File 2:
```ts
import { CONCURRENCY_LIMITER } from "./internal"
import { binner } from "./internal2"

export const getExample: () => binner = () => ({_symbol: CONCURRENCY_LIMITER})
```

File 3:
```ts
export declare const CONCURRENCY_LIMITER: unique symbol
```

Entrypoint:
```ts
import { getExample } from "./internal3"
console.log(getExample())
```

**Comment by evanw** [comment]
This behavior is inherent to how esbuild works, and is not a bug. See https://esbuild.github.io/content-types/#isolated-modules for more information.

**Comment by matray** [comment]
Ah my bad there then :) thanks for the prompt reply!
