### ISSUE TITLE
Regression: exception when compiling `a = {[-1]: 1}`

### ISSUE THREAD

**Issue by StephanHoyer** [evanw/esbuild#3169]
Worked in v0.17.19.
Does not work in 0.18.3

I fixed it in userland by converting it to a string first (which is done anyways by JS)

**Comment by hyrious** [comment]
This issue is saying `--minify` incorrectly removes the `[]` from `[-1]` from 0.18.0, which leads to a syntax error (`a = { -1: 1 }`). [playground link](https://esbuild.github.io/try/#dAAwLjE4LjMALS1taW5pZnktc3ludGF4AGEgPSB7Wy0xXTogMX0)

**Comment by StephanHoyer** [comment]
that was fast.... thanks @evanw 

And thanks for your awesome work in this wonderful piece of software!
