### ISSUE TITLE
`tsconfig` option only allowed for Build, but not for Transform

### ISSUE THREAD

**Issue by ghost** [evanw/esbuild#3171]
Currently, the `tsconfig` option is only allowed for Build: https://esbuild.github.io/api/#tsconfig
However, I'm using vite which only allows esbuild transform (`TransformOptions`); `tsconfig` is not usable.

esbuild (through vite) currently defaults to our "IDE-only" tsconfig.json with stricter checks. As a result, we get lots of warnings and errors due to stricter checks than our code can satisfy.
What it should be using instead, is our more lax `tsconfig.build.json` (which our code *does* satisfy).

This is also the original problem from https://github.com/evanw/esbuild/issues/226 which was solved by adding `tsconfig` to the Build options in https://github.com/evanw/esbuild/commit/9ac27fa7c572ce012a31faf3c724120e29aaaf6e

For that, I'd like to have this in our vite config:

```js
  [...]
  esbuild: {
    tsconfig: './tsconfig.build.json'
  },
  [...]
```

However, that's not allowed, because `esbuild`:
- in vite config is `esbuild?: ESBuildOptions | false;`..
- where `interface ESBuildOptions extends EsbuildTransformOptions`..
- where `import { TransformOptions as EsbuildTransformOptions } from 'esbuild';` which is..

https://github.com/evanw/esbuild/blob/73ee85abeb12a858bfbcd8d59c55974d5796e55c/lib/shared/types.ts#L255-L264

While `commonOptions` allows `tsconfigRaw`, it does not allow `tsconfig`.

---

For vite, there's also a discussion about specifying the tsconfig.json, and this is a suggested workaround: https://github.com/vitejs/vite/issues/10531#issuecomment-1285144991 
That basically loads `tsconfig.json` and plugs it into the `tsconfigRaw`.
I assume that esbuild still loads the actual "tsconfig.json" (which shouldn't be necessary) and then overwrites (or even merges?) the `tsconfigRaw`, which might lead to unexpected results.

**Comment by evanw** [comment]
The only way to pass `tsconfig.json` to the transform API is with `tsconfigRaw`: https://esbuild.github.io/api/#tsconfig-raw. The transform API is intended to be used without a file system, so it doesn’t make sense to pass it a file system path.

 If you want esbuild to search the file system when building (for at least both `tsconfig.json` and `package.json`), you can use the build API instead.
