### ISSUE TITLE
5 security vendors and no sandboxes flagged this file as malicious - esbuild.exe

### ISSUE THREAD

**Issue by KaptainKool** [evanw/esbuild#3172]
https://www.virustotal.com/gui/file/a7d8ee8b42ea0b0f99cc6137ec7b78a2a1e48b356fac02b9cfcc4291a4a3664a

Bkav Pro
McAfee-GW-Edition
SecureAge
McAfee
Rising

**Comment by evanw** [comment]
https://esbuild.github.io/faq/#anti-virus-software
