### ISSUE TITLE
Getting "Uncaught ReferenceError: module is not defined" when i make JS bundle from TSX project

### ISSUE THREAD

**Issue by Ajadli** [evanw/esbuild#3174]
// esbuild.config.js
```
const res = require('esbuild').buildSync({
    entryPoints: ['src/app.tsx'],
    bundle: true,
    minify: false,
    format: 'cjs',
    sourcemap: false,
    mainFields: ["browser", "main"], 
    platform: "browser",
    loader :{
        '.png' : 'binary'
    },
    outfile: 'dist/output.js',
  })
```

Bundle is breaking here :

![image](https://github.com/evanw/esbuild/assets/108657556/41ece074-5aa6-4c66-869f-41e09b32427a)

**Comment by hyrious** [comment]
`format: 'cjs'` means the runtime supports `module` `require`, etc. Browser is not a CJS runtime. Maybe you want to change that to [`format: 'iife'`](https://esbuild.github.io/api/#format-iife) instead.
