### ISSUE TITLE
How to switch between libraries for node and browser?

### ISSUE THREAD

**Issue by Alex134831** [evanw/esbuild#3176]
Hello. I want to use a Node.js built-in module (or a node library) in my project. But when bundling for browser, remove its import and inject another library. What is the best way for this? I use imports not require.

**Comment by hyrious** [comment]
There are many ways for library users (end users) to decide which package to be bundled during their build process. For example in esbuild you can use [aliases](https://esbuild.github.io/api/#alias) to substitute by package names, for more complex cases (like only swap one file) you can use plugins.

For library authors, the best way to do so is using the ["browser"](https://esbuild.github.io/api/#main-fields-for-package-authors) field to substitute files/libraries that only works in node with empty or something that works in browser. A real world example could be [axios](https://cdn.jsdelivr.net/npm/axios/package.json).

**Comment by Alex134831** [comment]
Thanks. Aliases is ok for me.
