### ISSUE TITLE
`mangleProps` combined with decorator leads to internal error

### ISSUE THREAD

**Issue by MuTsunTsai** [evanw/esbuild#3177]
Whenever I use TypeScript `experimentalDecorators` together with a property that I want to mangle, it shows and error like this:
```
error: panic: Internal error (while parsing "*****.ts")
```

Can't really reproduce it with esbuild-try as it doesn't support decorators, but the pattern of this is quite clear.

**Comment by evanw** [comment]
https://esbuild.github.io/try/#dAAwLjE4LjQALS1sb2FkZXI9dHMKLS1tYW5nbGUtcHJvcHM9XyQKLS10c2NvbmZpZy1yYXc9e1wiY29tcGlsZXJPcHRpb25zXCI6e1wiZXhwZXJpbWVudGFsRGVjb3JhdG9yc1wiOnRydWV9fQBjbGFzcyBGb28gewogIEB4IGZvbwogIEB5IGJhcl8KfQ

**Comment by MuTsunTsai** [comment]
Thanks for the fix. Hope to see it in the next release soon.

**Comment by MuTsunTsai** [comment]
Confirm issue fixed in v0.18.6.
