### ISSUE TITLE
Shared scan phase between multi-platform builds

### ISSUE THREAD

**Issue by rtsao** [evanw/esbuild#3186]
A common workflow involves generating multiple bundles for different targets, for example:

```js
Promise.all([
  // SSR
  esbuild.build({
    platform: 'node',
    entryPoints: ['entries/server.js'],
    bundle: true,
  }),
  // Evergreen browsers
  esbuild.build({
    platform: 'browser',
    entryPoints: ['entries/browser.js'],
    target: ['chrome114', 'safari16'],
    bundle: true,
  }),
  // Legacy browsers
  esbuild.build({
    platform: 'browser',
    entryPoints: ['entries/browser.js'],
    target: ['es5'],
    bundle: true,
  }),
])
```

While the entry points may differ, there is typically large overlap in bundled files. In this case, many files would be redundantly processed multiple times for each bundle (resolution, lexing, parsing, and scope analysis).

A potential optimization might be to support multiple builds using a shared module worklist to avoid repeating the first AST pass for the same file over and over. I suspect this could yield a meaningful performance improvement for the common use case of a large app that needs several bundles of (largely) the same input code.

Any thoughts on how feasible this might be?

Other bundlers, such as Parcel support similar functionality: https://parceljs.org/features/targets/#multiple-targets

Related: https://github.com/evanw/esbuild/issues/1726

**Comment by evanw** [comment]
This is not really possible with esbuild's current design. For speed, input files are partially processed during parsing in a way that is specific to the build options. So the AST from one build isn't necessarily safe to reuse for another build. In your example, the ASTs will undergo different syntax transforms during parsing due to the different target environments that you have selected.

**Comment by evanw** [comment]
I'm closing this issue as out of scope because it doesn't fit well with esbuild's architecture (as described above).
