### ISSUE TITLE
Loader for all image types

### ISSUE THREAD

**Issue by RailsCod3rFuture** [evanw/esbuild#3188]
I'm using the latest version of esbuild and the configuration is slightly different for this one, in comparison to the older approach. I am trying to load jpeg/png files using the command line argument. esbuild....--loader:.jpg=name but it doesn't quite work as expected. What must I do to get images to compile correctly for esbuild?

**Comment by evanw** [comment]
It's up to you. How you load is determined by what you want to do with them. For example, if you wanted to load each image into a `Uint8Array`, you could use the [`binary` loader](https://esbuild.github.io/content-types/#binary) like [this](https://esbuild.github.io/try/#YgAwLjE4LjYALS1idW5kbGUgLS1sb2FkZXI6LmpwZz1iaW5hcnkAZQBlbnRyeS5qcwBpbXBvcnQgY29udGVudHMgZnJvbSAnLi9maWxlLmpwZycKY29uc29sZS5sb2coY29udGVudHMpAABmaWxlLmpwZwAoanBlZyBjb250ZW50cyBoZXJlKQ). You could also use a different loader if you wanted to do something different instead.

**Comment by RailsCod3rFuture** [comment]
ok thanks -- I'll look into the binary loading config

**Comment by evanw** [comment]
I'm closing this issue because there's nothing to do here (the documentation for loaders already exists on the website).
