### ISSUE TITLE
[Deno] Use imports in the `deno.json` file.

### ISSUE THREAD

**Issue by long-woo** [evanw/esbuild#3193]
Could not find file location correctly.

`deno.json` file configuration:

<img width="344" alt="image" src="https://github.com/evanw/esbuild/assets/3394035/04f2c345-a0a7-4d25-8872-42acffb656a0">

```ts
await esbuild.build({
  entryPoints: ["./src/cli.ts"],
  bundle: true,
  outfile: "dist/index.js",
  target: "es2015",
  platform: "node",
});
```

result:

<img width="805" alt="image" src="https://github.com/evanw/esbuild/assets/3394035/d0648737-3a2b-489b-8dbe-b7391bea4af8">

**Comment by evanw** [comment]
I'm not sure what this is about and it doesn't include a way to reproduce the issue, so I'm going to close this. FWIW esbuild implements node's path resolution algorithm, not Deno's path resolution algorithm (which involves downloading things from the internet).
