### ISSUE TITLE
Setting `keepNames: true` in v0.18.4 and later causes used code to be dropped incorrectly.

### ISSUE THREAD

**Issue by alan-agius4** [evanw/esbuild#3195]
Esbuild version 0.18.4  introduced a bug where when using `keepNames: true` it causes used code to be dropped incorrectly.

Config
```js
{
  minify: true,
  keepNames: true,
}
```

Input
```js
(() => {
 function foo() {}
 console.log(foo());
})();
```

Actual Output
```js

```

Expected Output
```js
var f=Object.defineProperty;var n=(o,c)=>f(o,"name",{value:c,configurable:!0});(()=>{function o(){}n(o,"foo"),console.log(void 0)})();
```

**Reproduction** https://esbuild.github.io/try/#dAAwLjE4LjkAewogIG1pbmlmeTogdHJ1ZSwKICBrZWVwTmFtZXM6IHRydWUsCn0AKCgpID0+IHsKIGZ1bmN0aW9uIGZvbygpIHt9CiBjb25zb2xlLmxvZyhmb28oKSk7Cn0pKCk7Cg

**Comment by evanw** [comment]
Thanks for the report. I have a guess as to why this happens. Enabling `keepNames: true` generates this:

```js
function foo() {
}
__name(foo, "foo");
console.log(foo());
```

with the expression statement `__name(foo, "foo")` marked internally as "treat as having no side effects for tree shaking purposes". But then enabling `minify: true` turns that into this:

```js
function foo() {
}
__name(foo, "foo"), console.log(void 0);
```

However, that expression statement is still tagged as "treat as having no side effects for tree shaking purposes" which now masks the side effects from `console.log(void 0)`. This should be straightforward to fix.
