### ISSUE TITLE
css-minifier: An [unsupported-css-nesting] warning is displayed for @page margin-at-rules when the target doesn't support CSS nesting

### ISSUE THREAD

**Issue by PHoltom-Sequiter** [evanw/esbuild#3197]
With a css file containing a margin-at-rule, like so:

```css
@page {
	@top-left {
		content: "Anything";
	}
}
```

Attempting to minify with a target that doesn't support CSS nesting, for example `.\node_modules\.bin\esbuild .\test.css --minify --target=chrome87`

Results in a warning 

```
▲ [WARNING] CSS nesting syntax is not supported in the configured target environment ("chrome87") [unsupported-css-nesting]

    test.css:2:1:
      2 │   @top-left {
        ╵   ~~~~~~~~~
```

Support for this particular nesting predates CSS nesting by quite a bit: [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/@page#browser_compatibility)

The output generated appears to be fine, in the above example the result is `@page{@top-left{content:"Anything"}}` but is there anything that can be done about the warning?

**Comment by evanw** [comment]
I'll look into it. In the meantime, you can disable the warning with `--log-override:unsupported-css-nesting=silent`.
