### ISSUE TITLE
Getting `Error: The service was stopped` with 5000 entry points

### ISSUE THREAD

**Issue by ImedAdel** [evanw/esbuild#320]
Hi Evan 👋 I was trying to build a fast SSG for large sites using React and ESBuild, and one of the benchmarks includes building 5000 React files, twice, using ESBuild. Running the following gave me `Error: The service was stopped`.

# Code

```js
// ...
const mapped = files.map(f => ('./src/routes/' + f)).filter(f => f.endsWith('.js'))
const service = await startService()
await Promise.all([
	service.build({
		entryPoints: mapped,
		outdir: './tmp',
		minify: false,
		bundle: true,
		platform: 'node',
		format: 'cjs',
		loader: {
			'.js': 'jsx'
		},
		external: ['react', 'react-dom']
	}),
	service.build({
		entryPoints: mapped,
		outdir: './dist/assets',
		minify: true,
		bundle: true,
		platform: 'browser',
		format: 'esm',
		loader: {
			'.js': 'jsx'
		}
	}),
])
// ...
```

# Error
```
Error: The service was stopped
    at /root/dev/react-bench/node_modules/esbuild/lib/main.js:384:29
    at Socket.afterClose (/root/dev/react-bench/node_modules/esbuild/lib/main.js:331:7)
    at Socket.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

# Specs
I'm using an Ubuntu server from DigitalOcean (so that I don't freeze my pc :v) with 4GB of memory and 2 vCPUs. At the moment of the "accident" the CPU usage was at 50%, disk reads at 350 MB/s, and writes at 220 kB/s. Not sure if these stats might help but I included them anyways.

**Comment by evanw** [comment]
It looks like you're saying the Linux OOM killer may have killed the esbuild binary. Have you tried batching your requests to avoid running out of memory? For example, you could try chunking them 50 at a time or something.

**Comment by ImedAdel** [comment]
Yup. Apparently it's the Linux OOM Killer (sounds like a serial killer name). `/proc/sys/vm/overcommit_memory` is set to 0 so I guess there is nothing to do about it other than increasing memory or sending smaller batches (500 is already working great).

**Comment by Ireland999** [comment]
![Uploading image.png…]()
Jenkins automatic deployment always reports such errors, resulting in deployment failure. Is there a good solution?

**Comment by HNazmul** [comment]
same problem to me... but I used Sveltekit and Vitejs. How can I resolve it? Please any solution. I am new to vitejs.

**Comment by evanw** [comment]
Please read the above thread. You are likely running out of memory. How you check whether this is actually the case or not depends on your OS. If this is what's happening, then the fix also depends on your situation. You may need to add more memory to your VM or you may need to process your entry points in batches.

**Comment by djfwilkinson** [comment]
In my case the issue was esbuild running too many threads on a virtual machine on CI. Once I reduced the concurrency (via `serverless-esbuild` config as this was part of a serverless stack) the builds began completing again.

**Comment by shroomist** [comment]
@djfwilkinson what was the concurrency value that solved this for you?

**Comment by djfwilkinson** [comment]
@shroomist In my case `3` was acceptable. I looked up the number of virtual CPUs the CI machine was running. In my case I can configure the machine to different specs and the spec I was using had 3 virtual CPUs. The 'standard' machine would have had 2 vcpus so I would have chosen `2` as concurrency. I suspect `1` would work in any similar situation although I would also assume that it would take longer to complete it's jobs.

**Comment by Namtv2312** [comment]
![image](https://github.com/evanw/esbuild/assets/60953789/755a42fd-3388-4d24-845b-b0996dbf6e44)
`ps aux | grep  node`
`sudo kill -9` all process, worked for me

**Comment by unlocomqx** [comment]
rm -rf node_modules
then reinstall worked for me
