### ISSUE TITLE
MacOS Windows Defender detected esbuild binary as Trojan:MacOS/Wacatac.A!ml

### ISSUE THREAD

**Issue by jangelon** [evanw/esbuild#3200]
Hello, my work installs Microsoft Defender on our Macs, and today it popped up quarantining the esbuild binary as a trojan.

<img width="796" alt="MacOs Windows Defender Quarantine" src="https://github.com/evanw/esbuild/assets/833546/fbdaca68-a5d7-4b4b-82ed-4b5d23b0104f">

and here's the version information from Microsoft Defender
<img width="493" alt="Windows Defender Version" src="https://github.com/evanw/esbuild/assets/833546/be9b363e-2c35-40d7-a823-5f0d031501cf">

I'm on a mac running Ventura 13.2.1

**Comment by evanw** [comment]
See https://esbuild.github.io/faq/#anti-virus-software. If you install software on your computer that prevents you from using esbuild for whatever reason then that's your problem, not a problem with esbuild. What you do about that is up to you (see the link for some options).
