### ISSUE TITLE
Problems with `package.json` wildcard exports

### ISSUE THREAD

**Issue by yzrmn** [evanw/esbuild#3201]
Hi!

`redgeometry` is a hybrid ESM/CJS NPM package that also ships its source files. I realized that if the consuming application uses `"moduleResolution": "Node16"` the package also needs to specify the export in `package.json`. However, it looks like esbuild does not handle it correctly.

### `./node_modules/redgeometry/package.json` (exports altered)
```json
    ...
    "exports": {
        ".":{
            "import": "./dist/index.js",
            "require": "./dist/index.cjs"
        },
        "./src/*": {
            "default": "./src/*"
        }
    },
    ...
```

### `./src/index.ts`
```typescript
import { Vector2 } from "redgeometry/src/primitives/vector.js";

const v = new Vector2(1, 2);
console.log(v.length);
```

### `./package.json`
```json
{
    "name": "esbuild-exports",
    "version": "0.1.0",
    "type": "module",
    "dependencies": {
        "redgeometry": "0.3.0"
    },
    "devDependencies": {
        "esbuild": "^0.18.10",
        "typescript": "^5.1.4"
    },
    "scripts": {
        "init": "npm install",
        "check": "tsc",
        "serve": "esbuild ./src/index.ts --serve --bundle --outdir=./dist"
    }
}
```

### `./tsconfig.json`
```json
{
    "compilerOptions": {
        "esModuleInterop": true,
        "isolatedModules": true,
        "module": "ESNext",
        "moduleResolution": "Node16",
        "noEmit": true,
        "strict": true,
        "target": "ESNext",
        "verbatimModuleSyntax": true
    }
}
```

TSC behaves as expected with the export, but esbuild complains:
```
X [ERROR] Could not resolve "redgeometry/src/primitives/vector.js"

    src/index.ts:1:24:
      1 │ import { Vector2 } from "redgeometry/src/primitives/vector.js";
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The module "./src/primitives/vector.js" was not found on the file system:

    node_modules/redgeometry/package.json:23:23:
      23 │             "default": "./src/*"
         ╵                        ~~~~~~~~~
```

If we change:

* `"type": "commonjs"`
* `"moduleResolution": "Node"`
* `import { Vector2 } from "redgeometry/src/primitives/vector"` (extensionless)

Again, TSC is fine with that, but esbuild gives:

```
X [ERROR] Could not resolve "redgeometry/src/primitives/vector"

    src/index.ts:1:24:
      1 │ import { Vector2 } from "redgeometry/src/primitives/vector";
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The module "./src/primitives/vector" was not found on the file system:

    node_modules/redgeometry/package.json:23:23:
      23 │             "default": "./src/*"
         ╵                        ~~~~~~~~~

  Import from "redgeometry/src/primitives/vector.ts" to get the file
  "node_modules/redgeometry/src/primitives/vector.ts":

    src/index.ts:1:58:
      1 │ import { Vector2 } from "redgeometry/src/primitives/vector";
        │                                                           ^
        ╵                                                           .ts
```

Interestingly, changing the export to

```json
        "./src/*": {
            "default": "./src/*.ts"
        }
```
satisfies esbuild in this case.

But this obviously would not work for the original setup (`"moduleResolution": "Node16"`)...

TSC:
```
src/index.ts:1:25 - error TS2307: Cannot find module 'redgeometry/src/primitives/vector.js' or its corresponding type declarations.

1 import { Vector2 } from "redgeometry/src/primitives/vector.js";
                          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

esbuild:
```
X [ERROR] Could not resolve "redgeometry/src/primitives/vector.js"

    src/index.ts:1:24:
      1 │ import { Vector2 } from "redgeometry/src/primitives/vector.js";
        ╵                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  The module "./src/primitives/vector.js.ts" was not found on the file system:

    node_modules/redgeometry/package.json:23:23:
      23 │             "default": "./src/*.ts"
         ╵                        ~~~~~~~~~~~~
```

It looks to me that esbuild does not apply the same rules when resolving those import paths. Is it reasoanble to expect that esbuild behaves similar to TSC in this case? Or is there a different solution that I am missing?

**Comment by evanw** [comment]
> Or is there a different solution that I am missing?

Does [`allowImportingTsExtensions`](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0/#allowimportingtsextensions) allow you to import with `.ts` here?

> `redgeometry` is a hybrid ESM/CJS NPM package that also ships its source files.

Keep in mind that this is a use case that TypeScript is not designed for, and which is known to not work well. There's a [long thread](https://github.com/evanw/esbuild/issues/3019) with commentary from the TypeScript team which talks about this a bit if you're interested. Basically npm packages authored in TS are expected to publish generated JS code, not TS source code, because the behavior of that TS code depends on the TS compilation settings used at the time of authoring. To avoid behavior changes, these settings should be in control of the package author, not the package consumer. So the best solution here would probably be for this package to publish the generated JS files like it's supposed to be doing.

**Comment by evanw** [comment]
No I think it should be ok for esbuild to do this in this case, since there are no `.js` files. I can try to get esbuild to do that here. But if there are `.js` files present, I think esbuild should still prefer the `.js` files to the `.ts` files in this case.

**Comment by evanw** [comment]
I'm not sure exactly what you're saying by "ignores the exports" because you haven't provided a self-contained way to reproduce your issue. But I suspect that extensionless imports should not work if `exports` is present. I believe the `exports` field was deliberately designed to make extensionless imports not work (they are viewed as a mistake with node's original design). So extensionless imports wouldn't work with node's native ESM support, and shouldn't work in esbuild either. But I can look more into this if/when you provide a self-contained way to reproduce your issue.

**Comment by yzrmn** [comment]
Sorry for not being clearer :) I was just pointing out a case when esbuild respects package.json exports and TSC does not. In the table [Comparison with existing module resolution settings](https://github.com/microsoft/TypeScript/pull/51669) it is noted that the module resolutions `Classic` and `Node` do not support package.json exports.

So in [this example](https://esbuild.github.io/try/#YgAwLjE4LjEwAC0tYnVuZGxlAGUAc3JjL2luZGV4LnRzAGltcG9ydCB7IFNvbWVDbGFzcyB9IGZyb20gInNvbWUtcGFja2FnZS9kaXN0Igpjb25zb2xlLmxvZyhTb21lQ2xhc3MubmFtZSk7AAB0c2NvbmZpZy5qc29uAHsKICAgICJjb21waWxlck9wdGlvbnMiOiB7CiAgICAgICAgImVzTW9kdWxlSW50ZXJvcCI6IHRydWUsCiAgICAgICAgImlzb2xhdGVkTW9kdWxlcyI6IHRydWUsCiAgICAgICAgIm1vZHVsZSI6ICJFU05leHQiLAogICAgICAgICJtb2R1bGVSZXNvbHV0aW9uIjogIk5vZGUiLAogICAgICAgICJub0VtaXQiOiB0cnVlLAogICAgICAgICJzdHJpY3QiOiB0cnVlLAogICAgICAgICJ0YXJnZXQiOiAiRVNOZXh0IiwKICAgICAgICAidmVyYmF0aW1Nb2R1bGVTeW50YXgiOiB0cnVlCiAgICB9Cn0AAHBhY2thZ2UuanNvbgB7CiAgICAibmFtZSI6ICJ0aGlzLXBhY2thZ2UiLAogICAgInZlcnNpb24iOiAiMC4xLjAiLAogICAgInR5cGUiOiAibW9kdWxlIgp9CgAAbm9kZV9tb2R1bGVzL3NvbWUtcGFja2FnZS9wYWNrYWdlLmpzb24AewogICAgIm5hbWUiOiAic29tZS1wYWNrYWdlIiwKICAgICJ2ZXJzaW9uIjogIjAuMS4wIiwKICAgICJmaWxlcyI6IFsKICAgICAgICAiZGlzdCIKICAgIF0sCiAgICAiZXhwb3J0cyI6IHsKICAgICAgICAiLi9kaXN0LyoiOiAiLi9kaXN0LyoiCiAgICB9Cn0AAG5vZGVfbW9kdWxlcy9zb21lLXBhY2thZ2UvZGlzdC9pbmRleC5qcwBleHBvcnQgY2xhc3MgU29tZUNsYXNzIHt9AABub2RlX21vZHVsZXMvc29tZS1wYWNrYWdlL2Rpc3QvaW5kZXguZC50cwBleHBvcnQgY2xhc3MgU29tZUNsYXNzIHt9) it works with TSC but not with esbuild because TSC ignores the package.json export while esbuild, not knowing about the module resolution, respects it (if you delete the exports field from `node_modules/some-package/package.json` it works).

I'm actually fine with NOT supporting extensionless import paths for package.json exports but wanted to draw attention to this (slightly) related matter.

**Comment by evanw** [comment]
I think perhaps esbuild shouldn't respect `moduleResolution` even though it could. It seems like `moduleResolution` is a tool that helps you adapt TypeScript to the module system that is being used to run your code, not a tool that helps the module system that is being used to run your code adapt to TypeScript. For example, I believe that the intent of adding the [`bundler`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#--moduleresolution-bundler) module resolution mode is so that you can set `"moduleResolution": "bundler"` when using a bundler such as esbuild.

**Comment by yzrmn** [comment]
Fair point, I didn't think about it that way and I agree :)

**Comment by jedwards1211** [comment]
> I believe the exports field was deliberately designed to make extensionless imports not work

Extensionless imports are still possible.  For example `import pick from 'lodash-es/pick'` doesn't work because `lodash-es` doesn't declare an export map; you have to import `from 'lodash-es/pick.js'`.  But you'd be able to omit the extension if it declared the following export map:

```
  "exports": {
    "./*": "./*.js"
  }
```

Them importing `from 'lodash-es/pick'` would resolve via the export map to `node_modules/lodash-es/pick.js`.

**Comment by jedwards1211** [comment]
> Inlining, dead code elimination and conditional code (e.g. asserts)

Aren't all of these possible on JS files, at least if they're ESM?

**Comment by yzrmn** [comment]
@evanw: The fix works great, thanks! I have tested multiple configurations and esbuild lines up with TSC now :)

> Aren't all of these possible on JS files, at least if they're ESM?

Probably yes, but then the library would need to distribute the bundled files with defines (e.g. debug or trace) that would have been optimized away otherwise. In that case users of the library must take care of the optimizations themselves either way (if they don't want the performance penalty).

> Extensionless imports from packages are still possible.

Yes! I have found that out as well. In the example from the OP you could import `(...)/vector`, `(...)/vector.js` and `(...)/vector.ts` with:

```
    "./src/*": "./src/*.ts",
    "./src/*.ts": "./src/*.ts",
    "./src/*.js": "./src/*.ts"
```

With esbuild 0.18.12 the following would enable both imports `(...)/vector.js` and `(...)/vector.ts`:

```
    "./src/*": "./src/*"
```

**Comment by jedwards1211** [comment]
> Probably yes, but then the library would need to distribute the bundled files with defines (e.g. debug or trace) that would have been optimized away otherwise

I'm curious what you mean, do you have an example?

**Comment by yzrmn** [comment]
Sure, let's consider [this example](https://esbuild.github.io/try/#YgAwLjE4LjEzAHsKICAgIGRlZmluZTogeyAiRU5WX0RFQlVHIjogImZhbHNlIiB9LAogICAgbWluaWZ5U3ludGF4OiB0cnVlLAp9AGUAZW50cnkudHMAZGVjbGFyZSBjb25zdCBFTlZfREVCVUc6IGJvb2xlYW47CgpmdW5jdGlvbiB2YWxpZGF0ZU5vdE51bGwodmFsdWU6IG51bWJlcik6IGJvb2xlYW4gewogICAgcmV0dXJuIHZhbHVlICE9PSAwOwp9Cgpjb25zdCBhID0gTWF0aC5yYW5kb20oKTsKY29uc3QgYiA9IE1hdGgucm91bmQoYSkgKyAxOwoKaWYgKEVOVl9ERUJVRyAmJiB2YWxpZGF0ZU5vdE51bGwoYikpIHsKICAgIHRocm93IG5ldyBFcnJvcigiVmFsdWUgbXVzdCBub3QgYmUgMCIpOwp9Cgpjb25zb2xlLmxvZyhgVmFsdWUgJyR7Yn0gaXMgbm90IDAnYCk7Cg) which is set up for release. The validation function is completly removed because esbuild recognizes that the if-condition is always false. For debug builds we would use `define: { "ENV_DEBUG": "true" }` so that the validation function is always called. In both cases `ENV_DEBUG` vanishes from the resulting code.

Now we want users of this library to decide whether they want the runtime validation to happen or not. Then `ENV_DEBUG` needs to stay in the code ([like this](https://esbuild.github.io/try/#YgAwLjE4LjEzAHsKICAgIGRlZmluZToge30sCiAgICBtaW5pZnlTeW50YXg6IHRydWUsCn0AZQBlbnRyeS50cwBkZWNsYXJlIGNvbnN0IEVOVl9ERUJVRzogYm9vbGVhbjsKCmZ1bmN0aW9uIHZhbGlkYXRlTm90TnVsbCh2YWx1ZTogbnVtYmVyKTogYm9vbGVhbiB7CiAgICByZXR1cm4gdmFsdWUgIT09IDA7Cn0KCmNvbnN0IGEgPSBNYXRoLnJhbmRvbSgpOwpjb25zdCBiID0gTWF0aC5yb3VuZChhKSArIDE7CgppZiAoRU5WX0RFQlVHICYmIHZhbGlkYXRlTm90TnVsbChiKSkgewogICAgdGhyb3cgbmV3IEVycm9yKCJWYWx1ZSBtdXN0IG5vdCBiZSAwIik7Cn0KCmNvbnNvbGUubG9nKGBWYWx1ZSAnJHtifSBpcyBub3QgMCdgKTsK)) and be defined by the consuming application or its build process. But not all build tools possess the same level of optimizations as esbuild, so the application might end up checking `ENV_DEBUG` at runtime (which could affect performance in hot loops, especially if your code is drenched in checks).

Arguably, we could ship additional debug bundles and I have seen some libraries doing it. But maybe we want multiple `ENV_TRACE_FEATURE*` defines as well (more help to track down bugs in the context of the application). Distributing all those permutations would be silly of course.

So I think it's reasonable to publish libraries with full release optimizations and include the original source files for advanced debugging scenarios or fine grained access.
