### ISSUE TITLE
request: prefer ternary over if/else for minification

### ISSUE THREAD

**Issue by clshortfuse** [evanw/esbuild#3202]
Given:

````js
function set(value) {
  if (a) {
    window.location.href = value;
  } else {
    window.location.href = '#';
  }
}
````

`function set(o){a?window.location.href=o:window.location.href="#"}`

Following the [unicorn/prefer-ternary](https://github.com/sindresorhus/eslint-plugin-unicorn/blob/v47.0.0/docs/rules/prefer-ternary.md) method some evaluations are safe to minify into ternary format:

````js
function set(value) {
  window.location.href = a ? value : '#';
}
````

`function set(n){window.location.href=a?n:"#"}`

-----

Also, 

````js
function set(value) {
  if (value) {
    window.location.href = value;
  } else {
    window.location.href = '#';
  }
}
````

Is converted to ternary, and then flattened again allowing:

````js
function set(value) {
  window.location.href = value || '#';
}
````
`function set(n){window.location.href=n||"#"}`

-----------

There's a second instance I found but I'm not sure if it's completely safe:

````js
function set1(fn) {
  const usedLaterVar = first.dotted;
  const uselessVariable = second.dotted;
  if (uselessVariable) {
    fn(usedLaterVar);
  } else {
    fn('value');
  }
}
````

`function set1(e){const s=first.dotted,t=second.dotted;e(t?s:"value")}`

````js
function set2(fn) {
  const usedLaterVar = first.dotted;
  if (second.dotted) {
    fn(usedLaterVar);
  } else {
    fn('value');
  }
}
````

`function set2(e){const t=first.dotted;second.dotted?e(t):e("value")}`

set2 is one character shorter because it folds the variable into the if/then.

**Comment by evanw** [comment]
This is not a safe transformation. Getters can have important side effects. Compare this:

```js
let a = true;
let foo = window.foo = {};
Object.defineProperty(window, 'foo', {
  get: () => {
    a = false;
    return foo;
  },
});

function set(value) {
  if (a) {
    window.foo.href = value;
  } else {
    window.foo.href = '#';
  }
}

set('#works');
console.log('foo:', window.foo.href);
```

to this:

```js
let a = true;
let foo = window.foo = {};
Object.defineProperty(window, 'foo', {
  get: () => {
    a = false;
    return foo;
  },
});

function set(value) {
  window.foo.href = a ? value : '#';
}

set('#works');
console.log('foo:', window.foo.href);
```

They print different things, which means the transformation you suggested is an invalid minification.

**Comment by clshortfuse** [comment]
Thanks for the response. I see your point, with `a` being mutated, changing the order of evaluation.

Any thoughts on the second two? I not sure how `value` would change values since it's scoped to the function.

**Comment by evanw** [comment]
> I not sure how `value` would change values since it's scoped to the function.

Compare:

```js
function set(value) {
  let foo = window.foo = {};
  Object.defineProperty(window, 'foo', {
    get: () => {
      value = false;
      return foo;
    },
  });

  if (value) {
    window.foo.href = value;
  } else {
    window.foo.href = '#';
  }
}

set('#works');
console.log('foo:', window.foo.href);
```

to:

```js
function set(value) {
  let foo = window.foo = {};
  Object.defineProperty(window, 'foo', {
    get: () => {
      value = false;
      return foo;
    },
  });

  window.foo.href = value || '#';
}

set('#works');
console.log('foo:', window.foo.href);
```

I'm closing this issue because this transformation is invalid.

**Comment by clshortfuse** [comment]
Modifying the example to mutate a value isn't exactly the same, but you would know better about esbuild's limits in terms of tracing modified function arguments. But that wouldn't be the case with:

````js
function set1(fn) {
  const usedLaterVar = first.dotted;
  const uselessVariable = second.dotted;
  if (uselessVariable) {
    fn(usedLaterVar);
  } else {
    fn('value');
  }
}
````

````
function set2(fn) {
  const usedLaterVar = first.dotted;
  if (second.dotted) {
    fn(usedLaterVar);
  } else {
    fn('value');
  }
}
````js

But that's strictly because this would be using `const` which doesn't allow redefining of variables.  Essentially, that's just flattening two lines:

````js
const uselessVariable = second.dotted;
if (uselessVariable) {
````

Which would require a lookahead or sorts to see if `uselessVariable` is ever referenced again. Basically, if `uselessVariable` is used once and only once, it can be collapsed. I'm not sure if something the parsing engine can do.
