### ISSUE TITLE
Plugin callback as goroutine?

### ISSUE THREAD

**Issue by joelmoss** [evanw/esbuild#3203]
Apologies, but this is not an issue as such, but In the absence of GH discussions, this is my best option...

In the [plugin docs](https://esbuild.github.io/plugins/#on-load) it talks about running callbacks concurrently...

> In Go, each callback may be run on a separate goroutine. 

I have a bunch of plugins written in Go, so want to take advantage of its concurrency and use goroutines where possible. But it's not immediately obvious how I would do that for esbuild plugins.

As an example, the [HTTP plugin example](https://esbuild.github.io/plugins/#http-plugin) would be a good candidate to run concurrently. So of course I can make the `http.Get()` call a goroutine...

```go
build.OnLoad(api.OnLoadOptions{Filter: ".*", Namespace: "http-url"},
      func(args api.OnLoadArgs) (api.OnLoadResult, error) {
          res, err := go http.Get(args.Path)
          // ...
      }
)
```

but I would expect to need to run the actual callback functions as goroutines as well, or instead of, but how?

Could you please advise a Go noobie? thx 🙏

**Comment by evanw** [comment]
There's probably nothing you need to do. Just write code like you would normally. Each file that esbuild processes is already run in a separate goroutine, and your plugin's callback to load the file contents will be called from within that file processing goroutine, so all esbuild Go plugins are already run in parallel.

Just be aware that each callback will be run on a separate goroutine. For example, if you want to share data between different callbacks in your plugin (e.g. a shared in-memory cache), then you'll need to guard it with a mutex.

**Comment by joelmoss** [comment]
Just what I wanted to hear, thx 👍
