### ISSUE TITLE
Trojan warnning on 0.18.11 + MacOS + Microsoft Defender

### ISSUE THREAD

**Issue by bd82** [evanw/esbuild#3206]
I can install 0.18.10 successfully, however installing 0.18.11 **fails** with all (npm/yarn/pnpm).

It seems I am getting related popups from Microsoft Defender.
![image](https://github.com/evanw/esbuild/assets/4233843/202b3254-5bc3-4ac4-856f-46a6e8997cbd)

I don't know if this is a false positive or a real problem...

**Comment by lazarljubenovic** [comment]
It's a false positive. See https://esbuild.github.io/faq/#anti-virus-software.

**Comment by bd82** [comment]
Thanks.
