### ISSUE TITLE
[BUG] Typescript enum compilation lost reference  on version 0.18.9

### ISSUE THREAD

**Issue by noyobo** [evanw/esbuild#3210]
```ts
import { MyEnum } from './enums';
enum MyEnum2 {
  'A.A' = 'a',
  'aa' = 'aa',
}
console.log(MyEnum['A.A'], MyEnum2['A.A']);
console.log(MyEnum.aa, MyEnum2['aa']);
console.log(MyEnum['aa'], MyEnum2.aa);
```

output:

```js
// src/index.ts
console.log(MyEnum["A.A"], "a" /* A.A */);
console.log("aa" /* aa */, "aa" /* aa */);
console.log(MyEnum["aa"], "aa" /* aa */);

// error: MyEnum not defined
```
- [repl 0.18.9](https://esbuild.github.io/try/#YgAwLjE4LjkAe2J1bmRsZTogdHJ1ZX0AZQBlbnRyeS50cwBpbXBvcnQgeyBNeUVudW0gfSBmcm9tICcuL2VudW1zJzsKZW51bSBNeUVudW0yIHsKICAnQS5BJyA9ICdhJywKICAnYWEnID0gJ2FhJywKfQpjb25zb2xlLmxvZyhNeUVudW1bJ0EuQSddLCBNeUVudW0yWydBLkEnXSk7CmNvbnNvbGUubG9nKE15RW51bS5hYSwgTXlFbnVtMlsnYWEnXSk7CmNvbnNvbGUubG9nKE15RW51bVsnYWEnXSwgTXlFbnVtMi5hYSk7AABlbnVtcy50cwBleHBvcnQgZW51bSBNeUVudW0gewogICdBLkEnID0gJ2EnLAogICdhYScgPSAnYWEnLAp9)
- [repl 0.18.8](https://esbuild.github.io/try/#YgAwLjE4LjgAe2J1bmRsZTogdHJ1ZX0AZQBlbnRyeS50cwBpbXBvcnQgeyBNeUVudW0gfSBmcm9tICcuL2VudW1zJzsKZW51bSBNeUVudW0yIHsKICAnQS5BJyA9ICdhJywKICAnYWEnID0gJ2FhJywKfQpjb25zb2xlLmxvZyhNeUVudW1bJ0EuQSddLCBNeUVudW0yWydBLkEnXSk7CmNvbnNvbGUubG9nKE15RW51bS5hYSwgTXlFbnVtMlsnYWEnXSk7CmNvbnNvbGUubG9nKE15RW51bVsnYWEnXSwgTXlFbnVtMi5hYSk7AABlbnVtcy50cwBleHBvcnQgZW51bSBNeUVudW0gewogICdBLkEnID0gJ2EnLAogICdhYScgPSAnYWEnLAp9)

Conditions that trigger the bug:
1. Import from other files
2. Using string subscripts, like `enum['key']`

**Comment by ghiscoding** [comment]
seems related to #3184
