### ISSUE TITLE
Svelte plugin example deprecated with Svelte 4

### ISSUE THREAD

**Issue by Tazeg** [evanw/esbuild#3214]
The code for a svelte plugin given at <https://esbuild.github.io/plugins/#svelte-plugin> does not work with svelte 4. The error is : 

```
node:internal/errors:496
    ErrorCaptureStackTrace(err);
    ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './compiler.mjs' is not defined by "exports" in ~/myapp/node_modules/svelte/package.json imported from ~/myapp/esbuildPluginSvelte.mjs
```

I think that `import * as svelte from 'svelte/compiler.mjs'` is no longer available for Svelte 4.

**Comment by evanw** [comment]
Thanks for the report. It looks to me like this is the required change:

```diff
-import * as svelte from 'svelte/compiler.mjs'
+import * as svelte from 'svelte/compiler'
```
