### ISSUE TITLE
esbuild can't bundle @elastic/elasticsearch

### ISSUE THREAD

**Issue by PuAlbert** [evanw/esbuild#3220]
@elastic/elasticsearch: 6.X, 
some code in `@elastic/elasticsearch` like this 

`function lazyLoad (file, opts) {
  var fn = null
  return function _lazyLoad (params, options, callback) {
    if (fn === null) {
      fn = require(`./api/${file}.js`)(opts)
    }
    return fn(params, options, callback)
  }
}`
`

and be invoked like this

`const apis = {
    bulk: lazyLoad('bulk', opts),
    cat: {
      aliases: lazyLoad('cat.aliases', opts),
      allocation: lazyLoad('cat.allocation', opts),
....
`

for example , if using its bulk method, it will throw `Can not find module ./api/bulk.js`
anyone meet this error and how do you fix it

**Comment by hyrious** [comment]
This is so called [non-analyzable imports](https://esbuild.github.io/api/#non-analyzable-imports) where esbuild cannot bundle codes like `require(non-static-expression)`.

There're some ways to deal with it:

* Mark `@elastic/elasticsearch` as external: `--external:@elastic/elasticsearch` and let it find the dependent files at runtime.

* Write a [patch](https://github.com/ds300/patch-package) or [plugin](http://esbuild.github.io/plugins/) to manually edit that file to not use this kind of code. It seems they already did that: https://cdn.jsdelivr.net/npm/@elastic/elasticsearch@8.8.1/lib/api/index.js

**Comment by PuAlbert** [comment]
Great, Thanks, it works for me by adding external...
