### ISSUE TITLE
False positive: Unexpected newline after "type"

### ISSUE THREAD

**Issue by cowwoc** [evanw/esbuild#3225]
Testcase: https://esbuild.github.io/try/#dAAwLjE3LjYALS1wbGF0Zm9ybT1uZXV0cmFsIC0tZm9ybWF0PWVzbSAtLWxvYWRlcj10cwBpbXBvcnQgdHlwZSB0IGZyb20gInRzeCI7CgpleHBvcnQgdHlwZQp7CiAgdAp9Ow

Specifically, when compiling:

```ts
import type t from "tsx";

export type
{
  t
};
```

esbuild doesn't like the opening brace on the next line. If you move the brace up to the same line as "export type" the error disappears.

The testcase is legal Typescript, so I believe esbuild's behavior is a bug.

**Comment by evanw** [comment]
Thanks for the report. I think this is happening because the following is supposed to be invalid:

```ts
export type
T = t
```

So esbuild needs to distinguish between these two cases.
