### ISSUE TITLE
  text: 'Invalid option in build() call: "watch"'   macOs  m2     arm64??

### ISSUE THREAD

**Issue by keepresolve** [evanw/esbuild#3227]
Using the mac m2 chip, the watch cannot run using the api method。

 "esbuild": "^0.18.12",

![image](https://github.com/evanw/esbuild/assets/29271171/46240b4a-aba0-4323-b934-5c0baeb32424)

**Comment by hyrious** [comment]
There's no `watch` option since [0.17.0](https://github.com/evanw/esbuild/releases/tag/v0.17.0). Instead you should use the [context](https://esbuild.github.io/api/#watch) api to do so.

**Comment by evanw** [comment]
Closing this issue as invalid. Please read the documentation: https://esbuild.github.io/api/#watch.
