### ISSUE TITLE
how to modify the module names imported in “import” or “require”

### ISSUE THREAD

**Issue by lidenggao** [evanw/esbuild#3228]
I want to modify the module names imported in “import” or “require” statements through plugins, but I couldn't find a way to do it. Can support for modifying imported module names be added in onResolve? 

Example:
```
import moment from 'moment'
import m from 'moment'
```
Modify to:
```
import { vendor_moment as moment } from 'vendor'; 
import { vendor_moment as m } from 'vendor'; 
```

esbuild is awesome.

**Comment by evanw** [comment]
I'm closing this issue because doing this is already supported.
