### ISSUE TITLE
Import node_modules together with `--external` causes import renames

### ISSUE THREAD

**Issue by Patrick-clone** [evanw/esbuild#3231]
I'm using and importing a node module in multiple files like this `import { Foo } from '@foo';`. But when I build and say `--external:@foo` there are multiple import statements in the bundled out file like this: `import { Foo as Foo2} from '@foo'`. 

I've seen [this](https://github.com/evanw/esbuild/issues/1027) issue, but it does not make sense to me how this is the default behavior. This is a very common use case is it not? Importing node modules in multiple part of your code base and excluding them from the bundle because in production you load the node module through a `<script>` tag or something like that.

Is this something that is possible with esbuild?

**Comment by evanw** [comment]
I think this issue is a duplicate of #475. This is harmless except for a slight size increase in the resulting code.

**Comment by Patrick-clone** [comment]
Thank you for the quick response and the link. I could not find this issue.
I will close this issue.
