### ISSUE TITLE
setting `absWorkingDir` still resolve dependencies in current module

### ISSUE THREAD

**Issue by FlysoftBeta** [evanw/esbuild#3234]
I used Yarn 3 (with PnP enabled) to install esbuild and wrote a script under my module to build another script under another node module. But esbuild still tried to resolve dependencies in my module.

This is my code I used for bundling:
```js
build({
        target: "node18",
        bundle: true,
        platform: "node",
        entryPoints: ["/path/to/another_package/index.js"],
        absWorkingDir: "/path/to/another_package",
        write: true,
});
```

This is what esbuild says:
```
✘ [ERROR] Could not resolve "ws"

   /path/to/another_package/index.js:
      1 │ const WebSocket = require('ws');
        ╵                           ~~~~

  The Yarn Plug'n'Play manifest forbids importing "ws" here because it's not listed as a dependency
  of this package:

    ../../../../.pnp.cjs:2793:33:
      2793 │           "packageDependencies": [\
           ╵                                  ~~

  You can mark the path "ws" as external to exclude it from the bundle, which will remove this
  error. You can also surround this "require" call with a try/catch block to handle this failure at
  run-time instead of bundle-time.
```

**Comment by evanw** [comment]
Please reproduce the issue on [https://esbuild.github.io/try/](https://esbuild.github.io/try/#YgAwLjE4LjEzAHsKICB0YXJnZXQ6ICJub2RlMTgiLAogIGJ1bmRsZTogdHJ1ZSwKICBwbGF0Zm9ybTogIm5vZGUiLAogIGVudHJ5UG9pbnRzOiBbIi9wYXRoL3RvL2Fub3RoZXJfcGFja2FnZS9pbmRleC5qcyJdLAogIGFic1dvcmtpbmdEaXI6ICIvcGF0aC90by9hbm90aGVyX3BhY2thZ2UiLAp9AAAvcGF0aC90by9hbm90aGVyX3BhY2thZ2UvaW5kZXguanMAY29uc3QgV2ViU29ja2V0ID0gcmVxdWlyZSgnd3MnKTsAAC9wYXRoL3RvL2Fub3RoZXJfcGFja2FnZS9ub2RlX21vZHVsZXMvd3MvaW5kZXguanMA) and then paste the link here. Either that or provide explicit instructions for how to reproduce the issue. I'm marking this issue as `unactionable` as you didn't provide a way to reproduce the issue, so there's nothing I can do with your report.

**Comment by FlysoftBeta** [comment]
### Way to reproduce

1. Init a Yarn package named `test` and install `esbuild`:
```bash
mkdir test && cd test
corepack enable && corepack prepare --activate yarn@3.6.1
yarn init
yarn add esbuild --dev
```

2. Init another package using npm and install `ws`:
```bash
mkdir another_package && cd another_package
npm init -y
npm install ws --save
```

3. Create `index.js` in `another_package` folder:
```js
console.log(require("ws"));
```

4. Create `build.js` in `test` package:
```js
const { build } = require("esbuild");

const anotherPackageDir = `${__dirname}/another_package`;
build({
	target: "node18",
	bundle: true,
	platform: "node",
	entryPoints: [`${anotherPackageDir}/index.js`],
	absWorkingDir: anotherPackageDir,
	write: true,
});
```

5. Run the script:
```bash
yarn node ./build.js
```

6. The error shows up :(

**Comment by FlysoftBeta** [comment]
So is it possible to use esbuild installed in a Yarn PnP project to build a js file located in another npm project?

**Comment by evanw** [comment]
This is really a Yarn support question, not an esbuild one. I believe Yarn has a feature called [`pnpIgnorePatterns`](https://yarnpkg.com/configuration/yarnrc/#pnpIgnorePatterns) that you can use to tell Yarn to not apply Plug'n'Play to a subfolder.

**Comment by FlysoftBeta** [comment]
> This is really a Yarn support question, not an esbuild one. I believe Yarn has a feature called [`pnpIgnorePatterns`](https://yarnpkg.com/configuration/yarnrc/#pnpIgnorePatterns) that you can use to tell Yarn to not apply Plug'n'Play to a subfolder.

Thanks! I haven't noticed this feature before.
