### ISSUE TITLE
Node API that doesn't rely on stdio or the filesystem for output

### ISSUE THREAD

**Issue by romainmenke** [evanw/esbuild#3243]
I am not the typical user, so feel free to close this as unplanned.
I can fix this for myself by wrapping the esbuild in a child process.

----

What I want to do :
- call the node API
- assign the bundled CSS to a variable

```js
const result = await esbuild.build({
	entryPoints: ['style.css'],
	bundle: true,
})

// prints my bundled CSS
console.log(result.output);
```

What I don't want :
- CSS printed to `stdout`
- messages on `stdout`
- errors on `stderr`

-----

Currently esbuild pollutes everything by just writing to `stdout` and `stderr` as if it's the sole process.

Am I holding it wrong and can this be done today?

**Comment by hyrious** [comment]
1. You can set [log level](https://esbuild.github.io/api/#log-level) to `silent` to disable esbuild writing to stderr.
2. Set [write: false](https://esbuild.github.io/api/#write) to get the output in memory.

**Comment by romainmenke** [comment]
This works!

Thank you @hyrious 

```js
const esBundle = await esbuild.build({
	entryPoints: ['style.css'],
	bundle: true,
	logLevel: 'silent',
	write: false
})

console.log(esBundle.outputFiles[0].text)
```
