### ISSUE TITLE
Code splitting unstable?

### ISSUE THREAD

**Issue by ryb73** [evanw/esbuild#3259]
The docs for code splitting have a warning that says:

> Code splitting is still a work in progress. It currently only works with the esm output [format](https://esbuild.github.io/api/#format). There is also a known [ordering issue](https://github.com/evanw/esbuild/issues/399) with import statements across code splitting chunks. You can follow [the tracking issue](https://github.com/evanw/esbuild/issues/16) for updates about this feature.

This makes it sound like code splitting is unstable/not production-ready. I'm looking at migrating from Rollup but this may be a deal breaker.

Is code splitting ready for use in production?

**Comment by evanw** [comment]
Yes, the documentation means what it says. Code splitting is still a work in progress. I don't consider it to be ready for use in production yet.

**Comment by ryb73** [comment]
Thanks for the clarification. I wasn't sure because "work in progress", to
me, could mean many things, and it seems that the feature has been around
and in use for a long time.
