### ISSUE TITLE
Does esbuild support transforming regex lookbehind assertions?

### ISSUE THREAD

**Issue by MrHBS** [evanw/esbuild#3262]
Though it is mentioned in the website, however while testing it doesn’t seem to do any transformation.

**Comment by evanw** [comment]
No it does not. It only transforms regular expression literals  containing this feature into calls to the `RegExp` constructor. You’ll need to polyfill the `RegExp` constructor yourself to use this feature in older browsers.

**Comment by evanw** [comment]
I'm closing this issue because this question was answered.

**Comment by evanw** [comment]
The `regexp-lookbehind-assertions` flag in the `supported` setting controls the conversion of regular expression literals to the `RegExp` constructor. The `supported` setting is pretty low-level and contains other things not mentioned in the list you linked including `typeof-exotic-object-is-object` (a weird issue specific to IE) and `function-or-class-property-access` (a workaround for a Safari bug). It's supposed to be an internal esbuild implementation detail except that people requested it to be exposed. Anyway I can add a note to the JavaScript support table that regular expression transformation is not something that esbuild does.
