### ISSUE TITLE
Optimize a custom plugin

### ISSUE THREAD

**Issue by marvelbark2** [evanw/esbuild#3267]
Hey !
I want to optimize this plugin, esbuild takes longer while using it
import { PluginBuild } from "esbuild";

```
export default () => (
    {
        name: 'avoid-none-used',
        setup(build: PluginBuild) {
            build.onResolve({ filter: /.*/ }, async (args) => {
                try {
                    if (args.pluginData) return // Ignore this if we called ourselves


                    const { path, ...rest } = args
                    rest.pluginData = true // Avoid infinite recursion

                    const result = await build.resolve(path, rest)
                    result.sideEffects = path === 'preact/debug' || path === 'preact/devtools';

                    if (result.errors.length > 0) {
                        return { path: result.path, external: true }
                    }
                    return result
                } catch (e) {
                    console.error(e);
                    return { external: true };
                }
            });
        }
    }
)
```
---> await build.resolve(path, rest)  Takes a long time !

I want to make esbuild ignore server deps or something bug to resolve unused import, I use this plugin to avoid nodejs modules or server deps because script contains browser code and server code but I'm importing only browser code using stdin option.

How to optimize this or do you have any idea or solution for this case?

**Comment by evanw** [comment]
You can use `filter` to avoid processing every single import in your bundle. You could also consider caching imports so that you don’t resolve the same import all over again repeatedly (e.g. the same import path in the same directory with the same initial conditions). Or you could use esbuild’s Go API for better performance.

**Comment by marvelbark2** [comment]
Do
