### ISSUE TITLE
[Question] How to import ts file with `.js` extension from exports map

### ISSUE THREAD

**Issue by SettingDust** [evanw/esbuild#3268]
I'm working in a monorepo. 
I write export maps to package.json. After that, I can't import my ts file from another package in the monorepo. It's fine before added exports map.
Am I have to compile it before I using the packages?

**Comment by evanw** [comment]
Please provide a way to reproduce the issue. Marking this issue as `unactionable` because you didn’t do this.

**Comment by SettingDust** [comment]
It's causing by I try to using esbuild as a esm loader. MF
