### ISSUE TITLE
Bundling breaks tree-shaking when modules are reexported as namespaces

### ISSUE THREAD

**Issue by thetarnav** [evanw/esbuild#3278]
For my libraries I like to create entries like `array.ts`, `math.ts`, `color.ts` etc. that export functions normally, and then `index.ts` (a main entry) is reexporting them as namespaces.
e.g.
```ts
// array.ts
export function doSomething(): void {}

// index.ts
export * as array from "./array.ts"
```

then user can use it like this:
```ts
import { array } from "lib"
array.doSomething()

// or

import { doSomething } from "lib/array"
doSomething()
```
This works well when `bundle` is disabled, as the code is left as is.
And unused functions can be then safely tree-shaken by user's bundler. [for example using rollup](https://rollupjs.org/repl/?version=3.27.0&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMiUyRiUyRiUyMFRSRUUtU0hBS0lORyU1Q25pbXBvcnQlMjAlN0IlMjBtYXRoJTIwJTdEJTIwZnJvbSUyMCcuJTJGcmVleHBvcnQuanMnJTNCJTVDbiU1Q25jb25zb2xlLmxvZyhtYXRoLmN1YmUoNSkpJTNCJTIwJTJGJTJGJTIwMTI1JTIyJTJDJTIyaXNFbnRyeSUyMiUzQXRydWUlMkMlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjIlMkYlMkYlMjBtYXRocy5qcyU1Q24lNUNuJTJGJTJGJTIwVGhpcyUyMGZ1bmN0aW9uJTIwaXNuJ3QlMjB1c2VkJTIwYW55d2hlcmUlMkMlMjBzbyU1Q24lMkYlMkYlMjBSb2xsdXAlMjBleGNsdWRlcyUyMGl0JTIwZnJvbSUyMHRoZSUyMGJ1bmRsZS4uLiU1Q25leHBvcnQlMjBjb25zdCUyMHNxdWFyZSUyMCUzRCUyMHglMjAlM0QlM0UlMjB4JTIwKiUyMHglM0IlNUNuJTVDbiUyRiUyRiUyMFRoaXMlMjBmdW5jdGlvbiUyMGdldHMlMjBpbmNsdWRlZCU1Q24lMkYlMkYlMjByZXdyaXRlJTIwdGhpcyUyMGFzJTIwJTYwc3F1YXJlKHgpJTIwKiUyMHglNjAlNUNuJTJGJTJGJTIwYW5kJTIwc2VlJTIwd2hhdCUyMGhhcHBlbnMhJTVDbmV4cG9ydCUyMGNvbnN0JTIwY3ViZSUyMCUzRCUyMHglMjAlM0QlM0UlMjB4JTIwKiUyMHglMjAqJTIweCUzQiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiU3RCUyQyU3QiUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjAqJTIwYXMlMjBtYXRoJTIwZnJvbSUyMCU1QyUyMi4lMkZtYXRocy5qcyU1QyUyMiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJyZWV4cG9ydC5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiU3RCUyQyUyMnRyZWVzaGFrZSUyMiUzQXRydWUlN0QlN0Q=).

[ts-belt also uses the same pattern.](https://github.com/mobily/ts-belt/blob/master/src/index.js)

But enabling `bundle` (and/or `splitting`) options includes a `__export` helper for the namespace, which prevents tree-shaking, as it turns the namespace to a normal object then cannot be analyzed.
The output looks like this:
```ts
var __defProp = Object.defineProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};

var array_exports = {};
__export(array_exports, {
  doSomething: () => doSomething,
});

function doSomething() {
}

export { array_exports as array }
```

**Comment by lazarljubenovic** [comment]
https://github.com/evanw/esbuild/issues/1420

**Comment by thetarnav** [comment]
@lazarljubenovic thank you, somehow it didn't pop up when I searched...
