### ISSUE TITLE
Support Svelte

### ISSUE THREAD

**Issue by amursky** [evanw/esbuild#328]
It would be nice to have [Svelte](https://svelte.dev/) support.

**Comment by evanw** [comment]
Closing as a duplicate of #8, a previous request for Svelte support with more discussion. This won't be a native feature of esbuild but it will be possible to invoke the Svelte compiler from a plugin once esbuild's plugin API is released. You can follow #111 for updates about the work-in-progress plugin API.

**Comment by aral** [comment]
In case anyone else ends up here, here are links to the current state of Svelte support as far as I can see:

- https://esbuild.github.io/plugins/#svelte-plugin
- https://github.com/EMH333/esbuild-svelte
