### ISSUE TITLE
REPL: show the file size in bytes in the online playground

### ISSUE THREAD

**Issue by mrbrianevans** [evanw/esbuild#3296]
In the "try esbuild" online REPl, it would be useful to see the file size in bytes before and after minification.

Eg add up the total number of characters on the left hand size and show that converted to bytes, and then add up the number of characters in the output. 

This will be useful for seeing what difference minification makes. Could also show the percentage change.

With some guidance, I'm happy to try implement this on the weekend.

Quick mockup of what it could look like:
![image](https://github.com/evanw/esbuild/assets/53117772/e8f145aa-5ea8-47f7-bf70-497371cccb9a)

**Comment by evanw** [comment]
I added the size to the build output. I didn't add the percentage though because there isn't a one-to-one relationship between inputs and outputs in build mode.
