### ISSUE TITLE
esbuild References With Yarn Workspaces

### ISSUE THREAD

**Issue by sidpremkumar** [evanw/esbuild#3298]
I have a yarn workspace that setup as: 
```
packages/pkga
apps/app1
```

I want to use `pkga` in `app1`. So I've creates a tsconfig as follows in `apps/app1`
```
{
...
"references": [{ "path": "../../packages/pkga/tsconfig.json" }]
}
```

I have an esbuild config as: 
```
const { build } = require('esbuild');
const nodeVersion = require('fs').readFileSync('../../.nvmrc').toString().trim().split('v')[1];
const { nodeExternalsPlugin } = require('../../esbuildNodeModules');

esbuildBase = async () => {
  try {
    console.log('Building...');
    await build({
      entryPoints: ['src/main.ts'],
      outfile: 'dist/bin/main.js',
      bundle: true,
      platform: 'node',
      plugins: [nodeExternalsPlugin()],
      tsconfig: 'tsconfig.json',
      format: 'cjs',
      target: [`node${nodeVersion}`],
      minify: false, 
    });
    console.log('Finished Building 🍾');
  } catch (err) {
    console.error(`Failed to build`, err);
    process.exit(1);
  }
};

esbuildBase();
```

Its able to detect the imports fine: 
```
import { somethingrandom } from '@somename/pkga/src/test;
```

But then in `test` we import more: 
```
import { morethingsinpkg1 } from 'src/test1'
```
(*Note: The src/test1 is relative to pkg1*)

But then when building I get the following error: 
```
  text: 'Could not resolve "src/test1"'
````

It almost feels like its able to resolve the first file (`pkga/src/test`) but then it can't resolve anything inside that file (such as `src/test1`) 

Has anyone seen this before? I've been smacking my head against the wall forever trying to figure this out 😭 

Thanks!

**Comment by evanw** [comment]
Please provide a way to reproduce the issue. Marking this issue as `unactionable` because you didn’t do this.

**Comment by sidpremkumar** [comment]
Sorry about that, let me reopen this when I have time to add that 👍
