### ISSUE TITLE
Add a TODOs Badge to the README

### ISSUE THREAD

**Issue by patrickdevivo** [evanw/esbuild#33]
Hi there! I wanted to propose adding the following badge to the README to indicate how many `TODO` comments are in this codebase:

[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.comgithub.com/evanw/esbuild)](https://www.tickgit.com/browse?repo=github.com/evanw/esbuild)

The badge links to `tickgit.com` which is a free service that indexes and displays TODO comments in public github repos. It can help surface latent work and be a way for contributors to find areas of code to improve, that might not be otherwise documented.

The markdown is:

```
[![TODOs](https://badgen.net/https/api.tickgit.com/badgen/github.comgithub.com/evanw/esbuild)](https://www.tickgit.com/browse?repo=github.com/evanw/esbuild)
```

Thanks for considering, feel free to close this issue if it's not appropriate or you prefer not to!

**Comment by evanw** [comment]
Did you even look at my code? I don't use TODOs to track my work. Your bot is just picking up Mongolian letters in my Unicode table. Closing as irrelevant.
