### ISSUE TITLE
Is it possible to watch both css and js folders without using plugins?

### ISSUE THREAD

**Issue by smohadjer** [evanw/esbuild#3305]
I want to use esbuild in my npm scripts to bundle js and css files of my website, but when I run esbuild in watch mode on one folder, it stops running on another folder and vice versa. Why is that? Can't we run esbuild twice in watch mode? Here is how my build script in package.json looks like:

```
"scripts": {
  "bundle:js": "esbuild source.js --outfile=out.js --bundle --watch=forever",
  "bundle:css": "esbuild source.css --outfile=out.css --bundle --watch=forever",
  "build": "npm run bundle:js && npm run bundle:css"
}
```

**Comment by erwinheldy** [comment]
@smohadjer you need a tool for running multiple scripts in parallel. i usually use `jalankan`

```bash
npm install jalankan --save-dev
```

```json
"scripts": {
  "bundle:js": "esbuild source.js --outfile=out.js --bundle --watch=forever",
  "bundle:css": "esbuild source.css --outfile=out.css --bundle --watch=forever",
  "build": "jalankan bundle:* -p"
}
```

```bash
npm run build
```

**Comment by smohadjer** [comment]
> I think you are confused about how terminal commands work. The `&&` syntax waits for the first command to terminate before running the second command, so there’s no way this will work. You want to look into a parallel command runner utility instead.

I believe I had tried with `&` as well and it didn't work either.

**Comment by smohadjer** [comment]
Thanks @evanw, changing from `&&` to `&` fixed the problem.
