### ISSUE TITLE
how to build asset-manifest.json with esbuild

### ISSUE THREAD

**Issue by vladmandic** [evanw/esbuild#331]
as subject line says, how to build asset-manifest.json with esbuild?
i know there is a a --metafile flag, but i don't see how it can be used for automatic builds (e.g., i'm using esbuild.startService()).

**Comment by evanw** [comment]
Each command-line flag has an API property with the same name. So if you're using `startService()`, you can pass the `metafile` option to get the same behavior:

https://github.com/evanw/esbuild/blob/9a6bd6769b27a6c639ac452c4a5c1cfef9c066c9/lib/types.ts#L32

**Comment by vladmandic** [comment]
you're right. i didn't check the types, only docs - and it's not documented.
anyhow, this works just fine:

```js
async function compile(entryPoints) {
  const service = await esbuild.startService();
  try {
    await service.build({
      entryPoints,
      outdir: './dist',
      minify: true,
      bundle: true,
      sourcemap: true,
      external: ['fs', 'crypto', 'util'],
      logLevel: 'error',
      metafile: './asset-manifest.json',
    });
    log.state('Client application rebuild ready');
  } catch (err) {
    log.error('Client application build error', err.errors);
  }
}
```
