### ISSUE TITLE
dropLabels unexpected behaviour

### ISSUE THREAD

**Issue by Inqnuam** [evanw/esbuild#3311]
dropLabels + bundle + default export produces invalid output

```json
{
  dropLabels: ['DROP'],
  format: "esm",
  bundle: true,
}
```

```js
// original code
const myFunc = ()=> {
 DROP: {console.log("drop")}
 console.log("keep")
}
export default myFunc
```

```js
// esbuild output
export {
  entry_default as default
};
```

setting `bundle` to false

```js
// esbuild output
const myFunc = () => {
  console.log("keep");
};
var entry_default = myFunc;
export {
  entry_default as default
};
```

[online reproduction](https://esbuild.github.io/try/#YgAwLjE5LjEAewogIGRyb3BMYWJlbHM6IFsnRFJPUCddLAogIGZvcm1hdDogImVzbSIsCiAgYnVuZGxlOiB0cnVlLAp9AGUAZW50cnkuanMAY29uc3QgbXlGdW5jID0gKCk9PiB7CkRST1A6IHtjb25zb2xlLmxvZygiZHJvcCIpfQpjb25zb2xlLmxvZygia2VlcCIpCn0KCmV4cG9ydCBkZWZhdWx0IG15RnVuYwo)

**Comment by Inqnuam** [comment]
No issue with named export


```js
// original code
const myFunc = ()=> {
DROP: {console.log("drop")}
console.log("keep")
}

export {myFunc}
```

```js
// esbuild output with both bundle true and false
const myFunc = () => {
  console.log("keep");
};
export {
  myFunc
};
```

**Comment by evanw** [comment]
That sure is strange. Thanks for the report. Looks like I forgot a `popScope()` when dropping labels.
