### ISSUE TITLE
TsconfigRaw type missing valid tsconfig field `extends`

### ISSUE THREAD

**Issue by jacoobes** [evanw/esbuild#3314]
https://github.com/evanw/esbuild/blob/e330bde34251da78eb81be91e583fbfb8318944a/lib/shared/types.ts#L91

https://esbuild.github.io/content-types/#tsconfig-json
The type `TsConfigRaw` starting here doesn't include the valid `extends` top level field for tsconfig. I could easily pr this if this is unintended behavior

**Comment by mohamedmansour** [comment]
I would just use `tsconfig` not `tsconfigRaw` if you plan to point to a tsconfig file locally.

**Comment by evanw** [comment]
This is because `TsconfigRaw` is intended to be used with the transform API which does not have a concept of a file system, so `extends` does not make sense. As the previous comment says, you can (and should) use `tsconfig` instead of `tsconfigRaw` if you are working with files on the file system.
