### ISSUE TITLE
`Invalid command: on-resolve` happens when the context is disposed during bundling a large project

### ISSUE THREAD

**Issue by sapphi-red** [evanw/esbuild#3318]
```
X [ERROR] Invalid command: on-resolve [plugin JavaScript plugins]

    node_modules/esbuild/lib/main.js:734:12:
      734 │       throw new Error(`Invalid command: ` + request.command);
          ╵             ^

    at handleRequest (C:\Users\green\Downloads\wmaikmbpp.github\node_modules\esbuild\lib\main.js:734:13)
    at handleIncomingPacket (C:\Users\green\Downloads\wmaikmbpp.github\node_modules\esbuild\lib\main.js:755:7)
    at Socket.readFromStdout (C:\Users\green\Downloads\wmaikmbpp.github\node_modules\esbuild\lib\main.js:679:7)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at Pipe.onStreamRead (node:internal/stream_base_commons:190:23)
```
The error above happens when `context.cancel` + `context.dispose` gets called while esbuild is processing many files parallely (I guess).

It's not so important because I guess I can just ignore the error.

esbuild Version: 0.18.20

### How this happens (my guess)
1. the JS part send the `Dispose` packet to the Go part
2. JS part removes the handlers
3. Go part still calls the plugins  (https://github.com/evanw/esbuild/blob/e330bde34251da78eb81be91e583fbfb8318944a/internal/bundler/bundler.go#L121-L610)
4. the "JavaScript plugins" plugin sends the `OnResolve` packet to the JS part (https://github.com/evanw/esbuild/blob/e330bde34251da78eb81be91e583fbfb8318944a/cmd/esbuild/service.go#L887-L1119)
5. Since the handles are removed (2), the `Invalid command` error happens

If I change the "JavaScript plugins" to throw "The service was stopped" error after the context was disposed (https://github.com/sapphi-red/esbuild/commit/c6c401b9e67794e6358023676ea3191612161f86), the "The service was stopped" error happened.

### Reproduction (It's not minimal but is trimmed a bit)
1. Clone https://github.com/sapphi-red-repros/esbuild-invalid-command-dispose-during-highly-parallel-state
2. `npm i`
3. Run `node update.mjs` (This script will append an empty line to `.env` every 200ms)
4. Run `npm run storybook` in a different terminal
5. Wait 100ms
6. Open `http://localhost:6060` in browser
7. See the error in the terminal (the storybook one)

If it doesn't reproduce, changing the value of `node update.mjs` or the time in step 5 might work.

**Comment by evanw** [comment]
Thanks for the report. Note to self: I was able to reproduce this deterministically on pretty much any build with a plugin by adding `time.Sleep()` before the part of esbuild's code that sends `on-resolve`.
