### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ':' on esbuild 0.6.22

### ISSUE THREAD

**Issue by ngbinh** [evanw/esbuild#332]
esbuild 0.6.9 works fine but 0.6.22 fails. Reproduce (not minimized) can be found here https://github.com/ngbinh/esbuild-minify .

Please let me know if you have any question.

Thanks

**Comment by evanw** [comment]
Thanks so much for reporting this. Sorry about the breakage. This has been fixed in version 0.6.23.

**Comment by ngbinh** [comment]
Awesome! Will try it out

**Comment by ngbinh** [comment]
can confirm that `0.6.23` fixes the issue. Thanks
