### ISSUE TITLE
Dynamic import paths with wildcard doesn't work with typescript files

### ISSUE THREAD

**Issue by mattlewis92** [evanw/esbuild#3320]
The new wildcard matching for dynamic imports that was added in `0.19.0` is broken in typescript files, due to the glob helper not being emitted and it results in a runtime error of `globRequire_images_svg is undefined`.

Minimal repro [here](https://esbuild.github.io/try/#YgAwLjE5LjIAe2J1bmRsZTogdHJ1ZSwgb3V0ZGlyOiAnZGlzdCcsIGxvYWRlcjogeycuc3ZnJzogJ2ZpbGUnLH19AGUAZW50cnkudHMAaW1wb3J0IHtmaWxlfSBmcm9tICcuL2ZpbGUnCmNvbnN0IG5hbWUgPSAnZmlsZSc7Cgpjb25zb2xlLmxvZyhyZXF1aXJlKGAuL2ltYWdlcy8ke25hbWV9LnN2Z2ApKTsAAGltYWdlcy9maWxlLnN2ZwBzdmcxAABpbWFnZXMvZmlsZTIuc3ZnAHN2ZzIAAGZpbGUuanMAZXhwb3J0IGNvbnN0IGZpbGUgPSAnZmlsZSc7) and comparison against `.js` entry point [here](https://esbuild.github.io/try/#YgAwLjE5LjIAe2J1bmRsZTogdHJ1ZSwgb3V0ZGlyOiAnZGlzdCcsIGxvYWRlcjogeycuc3ZnJzogJ2ZpbGUnLH19AGUAZW50cnkuanMAaW1wb3J0IHtmaWxlfSBmcm9tICcuL2ZpbGUnCmNvbnN0IG5hbWUgPSAnZmlsZSc7Cgpjb25zb2xlLmxvZyhyZXF1aXJlKGAuL2ltYWdlcy8ke25hbWV9LnN2Z2ApKTsAAGltYWdlcy9maWxlLnN2ZwBzdmcxAABpbWFnZXMvZmlsZTIuc3ZnAHN2ZzIAAGZpbGUuanMAZXhwb3J0IGNvbnN0IGZpbGUgPSAnZmlsZSc7)

**Comment by gabrielf** [comment]
In my case I could work around this problem by using esbuild on the javascript output from tsc. I realize this may not be feasible for all use cases but it worked fine for our.

**Comment by slalomzacharyd** [comment]
I'm sticking to an older version of esbuild until there is a fix.  I'm definitely looking forward to this working more broadly however.

**Comment by jbreemhaar** [comment]
Encountered this problem myself today. Oof. Will downgrade for now.

**Comment by cutsoy** [comment]
For what it's worth, upgrading to v0.20.0 fixed it for us! So big thank you to whoever fixed this! 🎉

**Comment by mattlewis92** [comment]
Oh yes, this was fixed by https://github.com/evanw/esbuild/commit/e1b7050aa074da1a0a846a01b4a3c82857128944!
