### ISSUE TITLE
Object.values on an enum with template literal values

### ISSUE THREAD

**Issue by Hacksore** [evanw/esbuild#3329]
Repro: https://github.com/Hacksore/test-ts-objects-literals

This only happens with `esbuild` and when you use template literal values.

I can't repro on [tsplayground](https://tsplay.dev/WoM8LN)

**repro code**
```ts
const staticMember = "static";

enum TemplateLiteral {
  Minecraft = `minecraft_${staticMember}`,
  Lol = `lol_${staticMember}`,
}

console.log(Object.values(TemplateLiteral);
```

**expected**
```
[ 'minecraft_static', 'lol_static' ]
```

**actual**
```
[ 'minecraft_static', 'Minecraft', 'lol_static', 'Lol' ]
```

**Comment by typesafegh** [comment]
mhhh

**Comment by Hacksore** [comment]
My workaround for is migrating back to `ts-node` instead of using `tsx`.

@evanw if you do fix this let me know but at least this issue is here for others who encounter the behaviour.

Closing for now.

**Comment by evanw** [comment]
I plan to apply the fix that I described above.
