### ISSUE TITLE
Expose the resolution algorithm in the api package

### ISSUE THREAD

**Issue by paralin** [evanw/esbuild#3332]
Currently the resolution algorithm is located under `internal/resolver` and is therefore not exposed to external users.

I have a few cases where I need to resolve, for example: `import("react-dom/client")` to an absolute path like `import("react-dom/client.js")` in an OnResolve callback, transforming the import to the absolute path.

Since the information on which file was resolved is not exposed in OnResolve, I need some way to determine it at that point.

Adding an exposed API to `resolve("react-dom/client") -> "react-dom/client.js"` would be very useful.

**Comment by evanw** [comment]
Did you see https://esbuild.github.io/plugins/#resolve? That is the resolution algorithm located under `internal/resolver` exposed to external users.

**Comment by paralin** [comment]
@evanw is it exposed in the Go API? I just see:

OnResolve func(options OnResolveOptions, callback func(OnResolveArgs) (OnResolveResult, error))

Thanks for this incredible project.

**Comment by evanw** [comment]
The resolver is only available within the context of a build because the resolution behavior depends on the build's options.

**Comment by paralin** [comment]
@evanw Okay, I see. It would be possible to build a wrapper around the build API to do something like what I posted in the updated code snippet above, construct a temporary app.js file with `import("pkgname")` and call the builder on it with a plugin to catch the OnResolve and then resolve from there.

Seems like a little bit of a hack - but I'm okay with it! Thanks.
