### ISSUE TITLE
Live Reload Not Working

### ISSUE THREAD

**Issue by mcqj** [evanw/esbuild#3344]
Live reload does not appear to work for me. I've created a minimal React project to try to reduce the surface area in case the problem was being caused by some other software but to no avail. Watch is working and rebuilding. The EventSource seems to connect fine but no events flow to the browser. 

Here is a gist that demonstrates the issue. Maybe I'm missing something in my config?

https://gist.github.com/mcqj/c7c263cf68e9a7986d16cac7b430e8ff

**Comment by hyrious** [comment]
It's not `.onmessage`, i.e. not the `message` event, but `change` event. You have to listen that event like this:
```js
new EventSource('/esbuild').addEventListener('change', () => location.reload())
```

**Comment by evanw** [comment]
Thanks for the answer. This is correct; esbuild uses the `change` event. This is already in esbuild's documentation for live reload: https://esbuild.github.io/api/#live-reload. So I'm closing this issue as it's already documented and working correctly.

**Comment by mcqj** [comment]
Thanks - that was indeed the problem
