### ISSUE TITLE
Question: use function as entrypoint with programmatic usage, i.e. not reading entrypoint from file

### ISSUE THREAD

**Issue by ottokruse** [evanw/esbuild#3355]
I'd like to programmatically bundle a function with esbuild, without needing to save this function first on my disk.

```javascript
import * as esbuild from "esbuild";
import { foo } from "bar";
function test() {
  console.log("Hello!");
  foo();
}

const bundled = esbuild.buildSync({
  stdin: {
    contents: test,
  },
  bundle: true,
)
```

Is something like that possible?

(The above doesn't work as contents needs to be a `string` and just passing `test.toString()` doesn't cut it :))

**Comment by evanw** [comment]
Yes. You can use a plugin for that. Use an arbitrary entry point name and then use a plugin to intercept that name and provide the module contents dynamically.

**Comment by ottokruse** [comment]
Thanks I'll have a look. Might be a rabbit hole I'm stepping in, if you have any pointers on the easiest possible way to make this work I'd be much obliged.
