### ISSUE TITLE
Different export default output based on passing --format esm or nothing

### ISSUE THREAD

**Issue by switz** [evanw/esbuild#3363]
It's my understanding that `format` defaults to esm, so why the different output? This is relevant as it's breaking a library of mine that I'd like to output as `export default`, but it's being overridden.

Source:

```javascript
export default 1;
```

when `no flags`:

https://esbuild.github.io/try/#YgAwLjE5LjIAewoKfQBlAGVudHJ5LnRzAGV4cG9ydCBkZWZhdWx0IDE7

```javascript
export default 1;
```

when `--format esm`:

https://esbuild.github.io/try/#YgAwLjE5LjIAewogIGZvcm1hdDogJ2VzbScsCn0AZQBlbnRyeS50cwBleHBvcnQgZGVmYXVsdCAxOw

```javascript
var entry_default = 1;
export {
  entry_default as default
};
```

here's the relevant issue in my library: https://github.com/switz/driver/issues/6

edit:

I see that enabling bundling can affect this flag, but passing bundle true|false doesn't change this output

**Comment by evanw** [comment]
This is not a correctness issue with esbuild. These two syntax forms are equivalent in JavaScript. If this is breaking something in another tool then it's a bug with that tool, not with esbuild.

You should file a bug with whatever tool you're using for auto-imports that isn't working. For example, if this is about TypeScript's language service, then I'm guessing they'll probably need to change their implementation of `getLocalSymbolForExportDefault` [here](https://github.com/microsoft/TypeScript/blob/5d04803196899fab535103a5114bc9bf8d04dbd9/src/compiler/utilities.ts#L7266) to handle this case.

**Comment by switz** [comment]
Thanks Evan, I appreciate you taking a look at this as well as sending me in the proper direction. Apologies for the misdirected issue, I've opened an issue over at the typescript repo.

Cheers.
