### ISSUE TITLE
TS 5.0: Esbuild fails when `extends` field in tsconfig is set to Array

### ISSUE THREAD

**Issue by helmturner** [evanw/esbuild#3366]
As of 19.2 ESbuild does not appear to be fully compatible with TypeScript 5.0 features. Namely, [the following is valid in TS 5.0](https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-rc/#supporting-multiple-configuration-files-in-extends)

```jsonc
{
    "extends": ["a", "b", "c"],
    "compilerOptions": {
        // ...
    }
}
```
However using this syntax, ESBuild fails with the following:

> TypeError: The "path" argument must be of type string. Received an instance of Array
> \-\-
>   at __node_internal_captureLargerStackTrace (node:internal/errors:496:5)
>   at new NodeError (node:internal/errors:405:5)
>   at validateString (node:internal/validators:162:11)
>   at Object.join (node:path:1171:7)
>   at loadTsconfig (<...>/node_modules/esbuild-register/dist/node.js:4234:37)
>   at loadSyncDefault (<...>/node_modules/esbuild-register/dist/node.js:4178:18)
>   at tsConfigLoader (<...>/node_modules/esbuild-register/dist/node.js:4165:22)
>   at configLoader (<...>/node_modules/esbuild-register/dist/node.js:4497:22)
>   at loadConfig2 (<...>/node_modules/esbuild-register/dist/node.js:4480:12)
>   at registerTsconfigPaths (<...>/node_modules/esbuild-register/dist/node.js:4756:67)
>   at Object.register (<...>/node_modules/esbuild-register/dist/node.js:4888:35)

For context, my setup is using Tamagui which runs esbuild under the hood. Unfortunately, [I can't seem to reproduce it in the repl](https://esbuild.github.io/try/#YgAwLjE5LjIALS10c2NvbmZpZz10c2NvbmZpZy5qc29uIABlAGVudHJ5LnRzAGV4cG9ydCBkZWZhdWx0IGZ1bmN0aW9uIG1haW4oKSB7IGNvbnN0IG1lc3NhZ2UgPSAiaGVsbG8iOyBjb25zdCB0YXJnZXQgPSAid29ybGQiOyBjb25zb2xlLmxvZyhtZXNzYWdlICsgIiAiICsgdGFyZ2V0KSB9AAB0c2NvbmZpZy5vbmUuanNvbgB7CiAgIiRzY2hlbWEiOiAiaHR0cHM6Ly9qc29uLnNjaGVtYXN0b3JlLm9yZy90c2NvbmZpZyIsCiAgImNvbXBpbGVyT3B0aW9ucyI6IHsKICAgICJzdHJpY3QiOiB0cnVlLAogICAgImNoZWNrSnMiOiB0cnVlLAogICAgIm5vRXJyb3JUcnVuY2F0aW9uIjogdHJ1ZSwKICAgICJub0VtaXRPbkVycm9yIjogdHJ1ZSwKICAgICJ1c2VVbmtub3duSW5DYXRjaFZhcmlhYmxlcyI6IHRydWUsCiAgICAiZXhhY3RPcHRpb25hbFByb3BlcnR5VHlwZXMiOiBmYWxzZSwKICAgICJmb3JjZUNvbnNpc3RlbnRDYXNpbmdJbkZpbGVOYW1lcyI6IHRydWUsCiAgICAibm9VbmNoZWNrZWRJbmRleGVkQWNjZXNzIjogdHJ1ZSwKICAgICJub0ZhbGx0aHJvdWdoQ2FzZXNJblN3aXRjaCI6IHRydWUsCiAgfQp9AAB0c2NvbmZpZy5qc29uAHsKICAiZXh0ZW5kcyI6IFsiLi90c2NvbmZpZy5vbmUuanNvbiIsICIuL3RzY29uZmlnLnR3by5qc29uIl0sCiAgImNvbXBpbGVyT3B0aW9ucyI6IHsKICAgICJiYXNlVXJsIjogIi4iLAogICAgInJvb3REaXIiOiAiLiIsCiAgICAibGliIjogWwogICAgICAiZXNuZXh0IiwKICAgICAgIkRPTSIsCiAgICAgICJET00uSXRlcmFibGUiCiAgICBdLAogICAgInRhcmdldCI6ICJlczIwMjIiLAogICAgImltcG9ydEhlbHBlcnMiOiB0cnVlLAogICAgImFsbG93SnMiOiB0cnVlLAogICAgImNoZWNrSnMiOiB0cnVlLAogICAgInNraXBMaWJDaGVjayI6IHRydWUsCiAgICAiZXNNb2R1bGVJbnRlcm9wIjogdHJ1ZSwKICAgICJtb2R1bGUiOiAiZXNuZXh0IiwKICAgICJtb2R1bGVSZXNvbHV0aW9uIjogIkJ1bmRsZXIiLAogICAgInJlc29sdmVKc29uTW9kdWxlIjogdHJ1ZSwKICAgICJpc29sYXRlZE1vZHVsZXMiOiB0cnVlLAogICAgImpzeCI6ICJwcmVzZXJ2ZSIsCiAgICAiaW5jcmVtZW50YWwiOiB0cnVlLAogICAgIm5vRW1pdCI6IHRydWUKICB9LAp9AAB0c2NvbmZpZy50d28uanNvbgB7CiAgIiRzY2hlbWEiOiAiaHR0cHM6Ly9qc29uLnNjaGVtYXN0b3JlLm9yZy90c2NvbmZpZyIsCiAgImNvbXBpbGVyT3B0aW9ucyI6IHsKICAgICJub0ltcGxpY2l0UmV0dXJucyI6IHRydWUsCiAgICAibm9JbXBsaWNpdFRoaXMiOiB0cnVlLAogICAgIm5vSW1wbGljaXRBbnkiOiB0cnVlLAogICAgIm5vVW51c2VkTG9jYWxzIjogdHJ1ZSwKICAgICJub1VudXNlZFBhcmFtZXRlcnMiOiB0cnVlLAogICAgInN0cmljdE51bGxDaGVja3MiOiB0cnVlLAogICAgInN0cmljdEZ1bmN0aW9uVHlwZXMiOiB0cnVlLAogICAgInN0cmljdEJpbmRDYWxsQXBwbHkiOiB0cnVlLAogICAgInN0cmljdFByb3BlcnR5SW5pdGlhbGl6YXRpb24iOiB0cnVlLAogICAgIm5vSW1wbGljaXRPdmVycmlkZSI6IHRydWUsCiAgICAibm9Qcm9wZXJ0eUFjY2Vzc0Zyb21JbmRleFNpZ25hdHVyZSI6IHRydWUKICB9Cn0), so this might actually just be a Tamagui error, but I found the issue by applying the following patch to `esbuild-register@3.4.2`:

```diff
diff --git a/dist/node.js b/dist/node.js
index 274bb1d3c0c057ce3e2a52c4ec3c5a05ec40520d..bc9df80f5ba1aea207b7c92fdf3392ea0f18453e 100644
--- a/dist/node.js
+++ b/dist/node.js
@@ -4224,12 +4224,16 @@ var require_tsconfig_loader = __commonJS((exports) => {
     var cleanedJson = StripBom(configString);
     var config = JSON5.parse(cleanedJson);
     var extendedConfig = config.extends;
+    console.log("extendedConfig", extendedConfig);
     if (extendedConfig) {
       if (typeof extendedConfig === "string" && extendedConfig.indexOf(".json") === -1) {
         extendedConfig += ".json";
       }
       var currentDir = path.dirname(configFilePath);
       var extendedConfigPath = path.join(currentDir, extendedConfig);
       if (extendedConfig.indexOf("/") !== -1 && extendedConfig.indexOf(".") !== -1 && !existsSync(extendedConfigPath)) {
         extendedConfigPath = path.join(currentDir, "node_modules", extendedConfig);
       }
```

The result of the console log is the value of `extends` in my tsconfig, which is in fact an array. 

Alsog tagging @natew here, in case it's a Tamagui thing.

**Comment by evanw** [comment]
> modules/esbuild-register/dist/node.js

I believe you are looking for https://github.com/egoist/esbuild-register instead. The code you have a problem with does not come from esbuild.
