### ISSUE TITLE
esbuild should optimize `if (value !== -1)` to`if (~value)` and `if (value === -1)` to `if (!~value)`

### ISSUE THREAD

**Issue by eligrey** [evanw/esbuild#3369]
This is an easy win that can be hardcoded solely for !== -1 checks that aren't being used for their boolean result specifically (e.g. in an if statement like `if (value !== -1) { ... }`). When it is inferred that the types require a boolean (or just by default since it's easier to implement), esbuild could output `!!~value` but that is less performant and uses more bytes.

What are your thoughts on this potential optimization?

**Comment by evanw** [comment]
This optimization is invalid:

```js
var value = -1.5
console.log(value !== -1, !!~value)
```

That prints `true false`.

**Comment by eligrey** [comment]
Can this optimization be conditionally used when we know `value` isn't a number?

**Comment by eligrey** [comment]
Oh, I see the problem. Sorry for the invalid proposal.
