### ISSUE TITLE
allow assigning external modules to global variables

### ISSUE THREAD

**Issue by zanona** [evanw/esbuild#337]
It would be great if we could reference external modules to their global counterpart as I currently do on rollup like:
```js
export default {
	external: [
		'@wordpress/blocks',
		'@wordpress/block-editor',
		'@wordpress/components',
		'@wordpress/compose',
		'@wordpress/data',
		'@wordpress/date',
		'@wordpress/edit-post',
		'@wordpress/element',
		'@wordpress/plugins',
	],
	output: {
		format: 'iife',
		globals: {
			'@wordpress/blocks': 'wp.blocks',
			'@wordpress/block-editor': 'wp.blockEditor',
			'@wordpress/components': 'wp.components',
			'@wordpress/compose': 'wp.compose',
			'@wordpress/data': 'wp.data',
			'@wordpress/date': 'wp.date',
			'@wordpress/edit-post': 'wp.editPost',
			'@wordpress/element': 'wp.element',
			'@wordpress/plugins': 'wp.plugins',
		},
	},
	plugins,
};
```

a possible interface for this, could be something like:

```
esbuild --bundle foo.tsx --external:@wordpress/blocks=wp.blocks --external:@wordpress/plugins=wp.plugins
```

**Comment by rtsao** [comment]
This is already supported, see https://github.com/evanw/esbuild/pull/144

**Comment by evanw** [comment]
I think this feature would be most appropriately addressed by a plugin instead of adding it to esbuild's core. There is a plugin API in development that I believe should be able to implement this feature: #111.

**Comment by remorses** [comment]
@evanw the current plugin api cannot implement this feature without parsing the module 

I think this feature is necessary to inject polyfills that are not just primitive types (where you can use —define instead)

For example now you cannot replace the global process object without changing the window object at runtime or implementing a plugin that needs to parse the js file (Making the bundle process slow again)

A built-in way to inject objects in the global scope referencing them via modules paths would be perfect imho, this way you could polyfill the process object by implementing a module that exports a mocked process object and pass it to the esbuild configuration

The only alternative would be to inject process at runtime via window.process

**Comment by evanw** [comment]
> @evanw the current plugin api cannot implement this feature without parsing the module

I was thinking about a plugin like this:

```js
let examplePlugin = plugin => {
  plugin.setName('wp-global')
  plugin.addResolver({ filter: /^@wordpress\// }, args => ({
    path: args.path, namespace: 'wp-global',
  }))
  plugin.addLoader({ filter: /.*/, namespace: 'wp-global' }, args => {
    let name = args.path.slice(11).replace(/-(.)/g, (_, x) => x.toUpperCase())
    let contents = `export default wp[${JSON.stringify(name)}]`
    return { contents }
  })
}
```

When you build this file with that plugin:

```js
import blocks from '@wordpress/blocks'
console.log(blocks)
```

you get something like this:

```js
// wp-global:@wordpress/blocks
var blocks_default = wp["blocks"];

// <stdin>
console.log(blocks_default);
```

I'm not familiar with Rollup so I'm not sure what your use case is, but that's what I thought you were trying to do. Is that what you were looking for?

**Comment by remorses** [comment]
I want to do the opposite, replace global objects with external modules, this way you can for example replace the “process” global object with a polyfill


### Example

Building with a setting like `--globals=proces:process-polyfill.js`

The code below
```js
console.log(`This platform is ${process.platform}`);
```

Would become
```js
import process from './process-polyfill.js'
console.log(`This platform is ${process.platform}`);
```

**Comment by evanw** [comment]
> I think i misunderstood this feature request, i created #451 with my use case

#415 has now been implemented.

> It would be great if we could reference external modules to their global counterpart as I currently do on rollup

Actually this is already possible without plugins by using `paths` in `tsconfig.json` (or `jsconfig.json` if you prefer) and stub files for each global:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@wordpress/blocks": "file-that-exports-wp.blocks.js",
      "@wordpress/block-editor": "file-that-exports-wp.blockEditor.js",
      "@wordpress/components": "file-that-exports-wp.components.js",
      "@wordpress/compose": "file-that-exports-wp.compose.js",
      "@wordpress/data": "file-that-exports-wp.data.js",
      "@wordpress/date": "file-that-exports-wp.date.js",
      "@wordpress/edit-post": "file-that-exports-wp.editPost.js",
      "@wordpress/element": "file-that-exports-wp.element.js",
      "@wordpress/plugins": "file-that-exports-wp.plugins.js"
    }
  }
}
```

For example, `file-that-exports-wp.blocks.js` could look like this:

```js
export default wp.blocks
```

**Comment by zanona** [comment]
> Actually this is already possible without plugins by using `paths` in `tsconfig.json` (or `jsconfig.json` if you prefer) and stub files for each global:

Unfortunately I am afraid this isn't possible as those are usually not project dependencies but rather are already part of the global scope when the application starts, hence, there's no file to link to. 

It would be like referencing DOM methods...they are not dependencies and there are no files linked to it, they are just part of the environment. In TS we do have type helpers but those are just stubs and not real implementation which would be the same for `@wordpress/blocks` for example.

Perhaps I didn't fully understand your suggestion, though?

**Comment by evanw** [comment]
Closing this. It should now be possible to implement things like this using plugins and/or inject.

**Comment by a-b-r-o-w-n** [comment]
I am trying to implement something similar to webpack's external config but am not having any luck. This module will be executed in an iframe with some global variables in scope so I don't want to bundle those. In my source I have something like:

```ts
import { foo } from 'my-package';
```

In webpack I would do:

```js
{
  externals: {
    'my-package': 'MyPackage'
  }
}
```

Where `MyPackage` is the name of the global variable defined on `window`. When running esbuild, I get errors like

> No matching export for import "foo"

I have implemented the plugin as suggested above. Is this possible to do with esbuild?
