### ISSUE TITLE
Why doesn't esbuild process exit when building by script?

### ISSUE THREAD

**Issue by ooker777** [evanw/esbuild#3370]
I have this `build.ts` script:
```js
import * as esbuild from 'https://deno.land/x/esbuild@v0.19.0/mod.js'
await esbuild.build({
  entryPoints: ['main.ts'],
})
```
The command `deno run --allow-all --allow-env .\build.ts` runs fine, but it doesn't exit. Why is that?

**Comment by evanw** [comment]
Please read the documentation: https://esbuild.github.io/getting-started/#deno

> you need to call `stop()` when you're done because unlike node, Deno doesn't provide the necessary APIs to allow Deno to exit while esbuild's internal child process is still running.
