### ISSUE TITLE
[Feature Requirement][Plugin API] add import assertion type to On-resolve arguments

### ISSUE THREAD

**Issue by indooorsman** [evanw/esbuild#3372]
Hi @evanw ,
I'm trying to build a plugin which will generate different things according to the import assertion type, e.g.:
```js
import styles from './a.css' assert {type: 'css'}; 
```
if assert type is `css`, then `styles` would be a `CSSStyleSheet` 
```js
import styles from './a.css'; 
```
if no assert type, then styles would be a normal object which export all classnames.

The current on resolve arguments do not have information of import assertions: 
```
interface OnResolveArgs {
  path: string;
  importer: string;
  namespace: string;
  resolveDir: string;
  kind: ResolveKind;
  pluginData: any;
}

type ResolveKind =
  | 'entry-point'
  | 'import-statement'
  | 'require-call'
  | 'dynamic-import'
  | 'require-resolve'
  | 'import-rule'
  | 'composes-from'
  | 'url-token'
```
Could you consider to add it?
Thanks.

**Comment by evanw** [comment]
I have considered this. However, this goes against the design of import assertions. From the import assertion specification:

> _moduleRequest_.[[Assertions]] must not influence the interpretation of the module or the module specifier; instead, it may be used to determine whether the algorithm completes normally or with an [abrupt completion](https://tc39.es/ecma262/#sec-completion-record-specification-type).

So the specification itself says they must not be used for something such as importing something different when an assertion is present. If it is to be used by esbuild, it's purpose could be only to cause a build error if the loader ended up being different than the one determined by esbuild's path resolution process. 

Luckily the language designers eventually realized that this was a design mistake, and have decided to not add import assertions to the language after all. So import assertions are deprecated and will never be a part of JavaScript. Instead, they plan to add “import attributes” which are like import assertions except 1) they use the `with` keyword and 2) they are allowed to influence the interpretation of the imported module. Once they are added to the language, it will make sense for esbuild to add a plugin API like what you are suggesting here. But AFAIK no browser implements them yet so esbuild hasn’t yet added support for them.

**Comment by indooorsman** [comment]
@evanw Thanks for quick reply, and what you said does make sense. 
BTW I didn't know import assertion had been deprecated 🤣
