### ISSUE TITLE
Multiple `tsconfig`s used when building a workspace with aliases

### ISSUE THREAD

**Issue by ilijapuaca** [evanw/esbuild#3375]
This seems to be a regression (or a change in behavior) starting with `v0.19` - our builds started failing after the upgrade with errors indicating that paths for one of the aliases was not being resolved correctly. After spending some time going through the verbose log, it turned out that the issue happens because `tsconfig` of the aliased package seems to come into the play when previously that supposedly wasn't the case.

Putting a small repro in place seems difficult as yarn workspace setup may be involved as well at some point. We basically have a git submodule in our workspace that has a somewhat complicated setup by itself that we set up aliases to in our own codebase, hence the presence of `tsconfig` in the module itself.

Previously aliases were picked up just fine, but after upgrading to `v0.19` builds fail as wrong files (not the ones that `paths` points to) get picked up. After removing `tsconfig.json` out of the aliased package things seem to work fine again, so my assumption is that that the `tsconfig` that's present in the submodule is somehow taken into account now while transpiling its code (although it has nothing to do with the initial entry point) where it previously wasn't.

I've put together [this setup](https://esbuild.github.io/try/#YgAwLjE5LjIALS1idW5kbGUAZQBlbnRyeS5qcwBpbXBvcnQge3N1bX0gZnJvbSAnZm9vL21hdGgnOwoKc3VtKDEsIDIpAAB0c2NvbmZpZy5qc29uAHsKICAiY29tcGlsZXJPcHRpb25zIjogewogICAgInBhdGhzIjogewogICAgICAiZm9vLyoiOiBbIi4vbGliL2Zvby9zcmMvKiJdCiAgICB9CiAgfQp9AABsaWIvZm9vL3RzY29uZmlnLmpzb24AewogICJjb21waWxlck9wdGlvbnMiOiB7CiAgICAiYmFzZVVybCI6ICIuL3NyYyIsCiAgICAicGF0aHMiOiB7CiAgICAgICIqIjogWyIqIl0KICAgIH0KICB9Cn0AAGxpYi9mb28vc3JjL21hdGgvaW5kZXgudHMAZXhwb3J0IGZ1bmN0aW9uIHN1bShhOiBudW1iZXIsIGI6IG51bWJlcik6IG51bWJlciB7CiAgcmV0dXJuIGEgKyBiOwp9AABsaWIvZm9vL3BhY2thZ2UuanNvbgB7CiAgIm5hbWUiOiAiZm9vIiwKICAibWFpbiI6ICJkaXN0L2luZGV4LmpzIgp9AABsaWIvZm9vL21hdGgudHMAbW9kdWxlLmV4cG9ydHMgPSByZXF1aXJlKCcuL2Rpc3QvYWN0aW9ucycpOw) which is the closest I can get to modeling a similar setup without having to put together an entire repo with yarn, which I'll do if need be, but I thought it'd be worthwhile putting this up first as someone might have an idea what the regression/change might've been here.

**Comment by ZuBB** [comment]
It sounds similar to what is described in https://github.com/evanw/esbuild/issues/3354

**Comment by ilijapuaca** [comment]
Perhaps worth noting - the submodule which contains tsconfig that previously wasn't being taken into account has `paths` set to such:

```
  "paths": {
      "*": ["*"]
    }
```

Removing this makes things work the way they have < 0.19 🤷‍♂️

**Comment by evanw** [comment]
I just fixed #3354 and I'm closing this issue under the assumption that it's a duplicate.

I'm not sure what [the link](https://esbuild.github.io/try/#YgAwLjE5LjIALS1idW5kbGUAZQBlbnRyeS5qcwBpbXBvcnQge3N1bX0gZnJvbSAnZm9vL21hdGgnOwoKc3VtKDEsIDIpAAB0c2NvbmZpZy5qc29uAHsKICAiY29tcGlsZXJPcHRpb25zIjogewogICAgInBhdGhzIjogewogICAgICAiZm9vLyoiOiBbIi4vbGliL2Zvby9zcmMvKiJdCiAgICB9CiAgfQp9AABsaWIvZm9vL3RzY29uZmlnLmpzb24AewogICJjb21waWxlck9wdGlvbnMiOiB7CiAgICAiYmFzZVVybCI6ICIuL3NyYyIsCiAgICAicGF0aHMiOiB7CiAgICAgICIqIjogWyIqIl0KICAgIH0KICB9Cn0AAGxpYi9mb28vc3JjL21hdGgvaW5kZXgudHMAZXhwb3J0IGZ1bmN0aW9uIHN1bShhOiBudW1iZXIsIGI6IG51bWJlcik6IG51bWJlciB7CiAgcmV0dXJuIGEgKyBiOwp9AABsaWIvZm9vL3BhY2thZ2UuanNvbgB7CiAgIm5hbWUiOiAiZm9vIiwKICAibWFpbiI6ICJkaXN0L2luZGV4LmpzIgp9AABsaWIvZm9vL21hdGgudHMAbW9kdWxlLmV4cG9ydHMgPSByZXF1aXJlKCcuL2Rpc3QvYWN0aW9ucycpOw) in the original post is trying to demonstrate as everything appears to be working fine to me and esbuild's behavior is not different between 0.18.x and 0.19.x on that code. So I can't currently reproduce what this post is describing.
