### ISSUE TITLE
Invalid build flag: "--packages=external"

### ISSUE THREAD

**Issue by Zagorodnyi** [evanw/esbuild#3376]
Constantly getting an error` Invalid build flag: "--packages=external".`

My command `esbuild ./src/server/_runServer.ts --bundle --platform=node --packages=external`

Same thing with js implementation:

```js
import { buildSync } from 'esbuild';

buildSync({
  entryPoints: ['./src/server/_runServer.ts'],
  bundle: true,
  platform: 'node',
  packages: 'external',
  outfile: 'dist/out.js',
});

```

Resut: 

```
 errors: [
    {
      id: '',
      pluginName: '',
      text: 'Invalid option in build() call: "packages"',
      location:  //...,
      detail: Error: Invalid option in build() call: "packages"
          at checkForInvalidFlags (node_modules/esbuild/lib/main.js:244:13)
          at flagsForBuildOptions (node_modules/esbuild/lib/main.js:435:3)
          at buildOrServeContinue (node_modules/esbuild/lib/main.js:1228:9)
          at Object.buildOrServe (node_modules/esbuild/lib/main.js:1173:9)
          at node_modules/esbuild/lib/main.js:2110:17
          at new Promise (<anonymous>)
          at Object.build (node_modules/esbuild/lib/main.js:2109:14)
          at node_modules/esbuild/lib/main.js:2284:67
          at MessagePort.<anonymous> (node_modules/esbuild/lib/main.js:2303:9)
          at [nodejs.internal.kHybridDispatch] (node:internal/event_target:761:20)
    }
    }
];
```

The help command clearly shows this as possible flag as well as the esbuild official docs.

" --packages=...        Set to "external" to avoid bundling any package"

**Comment by Zagorodnyi** [comment]
> It seems your esbuild version is too low (< 0.16.5) to use this option.

I'm using the latest version  "esbuild": "^0.19.2"

**Comment by hyrious** [comment]
> I'm using the latest version "esbuild": "^0.19.2"

Yeah but your stacktrace is indicating you're using an old one:

<pre>at checkForInvalidFlags (node_modules/esbuild/lib/main.js:<ins>244</ins>:13)</pre>

This function [was at line 244](https://hyrious.me/npm-browser/?q=esbuild@0.15.18/package/lib/main.js:244) back into esbuild 0.15.18.

The most possible reasons can be:

- Some dependencies of your project is depending on an old esbuild, and they are hoisted to the top so you cannot access the new one easily.
- You're using your system's global esbuild which is an old one.
- Someone set a global env `ESBUILD_BINARY_PATH` which tells esbuild to use the binary from a specific location.

**Comment by Zagorodnyi** [comment]
Yes, npm why esbuild showed ts-jest depending on esbuild v0.14.0. Thanks!
