### ISSUE TITLE
CSS: Nested type selectors incorrectly allowed

### ISSUE THREAD

**Issue by Marcisbee** [evanw/esbuild#3382]
According to css nesting spec (https://www.w3.org/TR/css-nesting-1/#example-34e8e94f), type selectors are not allowed.
This should show warning (it did in v0.19.1, but not in v0.19.2):
```css
div {
  color: red;

  input {
    margin: 1em;
  }
}
```

Could this be some regression?

- **v0.19.2 latest**: https://esbuild.github.io/try/#YgAwLjE5LjIAAGUAZW50cnkuY3NzAGRpdiB7CiAgY29sb3I6IHJlZDsKCiAgaW5wdXQgewogICAgbWFyZ2luOiAxZW07CiAgfQp9
  - ❌ No warning (even tho it should warn)
- **v0.19.1**: https://esbuild.github.io/try/#YgAwLjE5LjEAAGUAZW50cnkuY3NzAGRpdiB7CiAgY29sb3I6IHJlZDsKCiAgaW5wdXQgewogICAgbWFyZ2luOiAxZW07CiAgfQp9
  - ✅ Warning

**Comment by evanw** [comment]
The specification you are referencing is unfortunately outdated. See also:
* https://drafts.csswg.org/css-nesting/#example-82c7d228
* https://github.com/w3c/csswg-drafts/issues/7961
* https://github.com/WebKit/WebKit/commit/2cfe184f6dbee766aefa51db1de3e613c185b0fb
* https://github.com/evanw/esbuild/releases/tag/v0.19.2

**Comment by Marcisbee** [comment]
Ah, makes sense. Thanks!
