### ISSUE TITLE
Ability to mark spread assignment as side-effect free

### ISSUE THREAD

**Issue by devversion** [evanw/esbuild#3392]
**Problem**

Consider a snippet like the following:

```js
const base = {
  someField: true,
};

export const sub = {
  // commenting this out will properly drop `sub` and `base`.
  ...base,
}
```

When ESBuild discovers such a file as part of bundling, where `sub` is not even _used_, ESBuild will preserve `sub` and `base` in the output bundle as it considers the **spread assignment** as a side-effect.

Terser on the other hand does not consider such as side-effect (as an additional note)

**Reproduction**

* [ESBuild Try Online](https://esbuild.github.io/try/#YgAwLjE5LjMALS1taW5pZnktc3ludGF4IC0tYnVuZGxlAGUAZW50cnkuanMAaW1wb3J0IHt9IGZyb20gJy4vb3RoZXInOwAAb3RoZXIuanMAY29uc3QgYmFzZSA9IHsKICBvazogdHJ1ZSwKfTsKCmV4cG9ydCBjb25zdCBzdWIgPSB7CiAgLi4uYmFzZSwKfQ)

**Request**

Provide a way to mark such assignments (`...base`) as side-effect free/pure. e.g. using the `@__PURE__` annotation.

**Comment by evanw** [comment]
You can mark anything as pure by putting it in an IIFE. This is because the pure annotation only applies to function calls. Example:

```js
const base = {
  someField: true,
};

export const sub = /* @__PURE__ */ (() => ({
  ...base,
}))()
```

**Comment by devversion** [comment]
Thanks @evanw. Yes, we've started doing that in https://github.com/angular/angular/commit/03127fc870f56cb05a542c9d4a25cc1f866a832e, but were wondering if there would be a way to only mark the individual spread assignment as "side-effect free"- instead of having to wrap the full constant.

**Comment by evanw** [comment]
Note that in the latest release, esbuild will now inline IIFEs that return an expression when minifying, so there should no longer be any size impact from wrapping this expression in an IIFE to annotate it.

**Comment by evanw** [comment]
I'm closing this issue as I do not plan on creating a special-cased annotation for this. The general way of doing this for any JavaScript expression is using an IIFE, and that should work perfectly fine in this case too.
