### ISSUE TITLE
Private name "#..." must be declared in an enclosing class when referencing from decorator

### ISSUE THREAD

**Issue by akcyp** [evanw/esbuild#3394]
esbuild version: 0.19.3

Context: Private class fields should be only available from inside of class declaration. We can move accessor to outside context but still we have to declare it "inside" class declaration, like in this example:
```ts
let x
class A {
    #test = 42;
    static {
        x = (obj) => obj.#test;
    }
}
console.log(x(new A)); // 42
// Works correctly in both typescript and esbuild compiler
```

The problem: When using decorators syntax we cannot reffer to private fields. Example:

```ts
type AttributeOptions<T> = {
  onChange?: (this: T, value: string, oldValue: string) => void;
};

const Attribute = <T, V>(options: AttributeOptions<T> = {}) => (
  value: ClassAccessorDecoratorTarget<T, V>,
  _: ClassAccessorDecoratorContext<T, V>,
): ClassAccessorDecoratorResult<T, V> => {
  const { get, set } = value;
  return {
    get() {
      return get.call(this);
    },
    set(value) {
      const oldValue = get.call(this);
      set.call(this, value);
      options.onChange?.call(this, value as string, oldValue as string);
    },
  };
};

class CustomHTMLElement {
  #test = 'test';
  @Attribute({
    onChange() {
      console.log(this.#test); // <- fails on esbuld
    }
  }) accessor field = '';
}

new CustomHTMLElement().field = '';
```

Typescript **working** example: [Playground Link](https://www.typescriptlang.org/play?lib=lib.dom.d.ts%2Clib.esnext.d.ts%2Clib.esnext.decorators.d.ts&ts=lib.dom.d.ts%2Clib.esnext.d.ts%2Clib.esnext.decorators.d.ts#code/C4TwDgpgBAgswCcCWAjArsCB5MwkHsA7AZwB4AVAPigF4oBvAKCiiIGEALAQ0IHMIA-AC4oACmAckxEeQA0UAG5cANmggjiiJH3n5lAEwBqKtRq18AlLWoL8SfQG5GAXyeMAxkU2x4ydJlooCnlDSlF8XAISETgtf2xIrwpqOnpnKxpqUWZFE3UoNmUuYmIYd3cIEvwEABEITwQuYGryLgR+YGCoUNkcgH0RQuLS8sriarqGpuq2IkwAD065bspei0GikrKKqtr66umEACVKtGUlkJTqJhZPEmAGKA75YggH50ClVQgnFgQ3tAIQgMHIsDqiKw3FjQ-7AQHAjoAOncKmU4kkxAsv2hzl60Kgr2Aoi+akhoOhd28eiMeUCSJRyjREikWPJLEJyNR6Kk8hJEFZ+JYETwXkR7G4fEEnMZ3OIvNpxQJ5l4ugMxm+UEVmmQlmxLFxOVcLjc7k2xAKaE0+AAtgAJcgAWQAMgBRZQQa0QQgPKEAYkw3joAHIA8Ag9iAAKxPwYCCiKFCwicHj8CEgwVQSl6CCI5T4XiyxH+yrAAU4w1WLijXZQABmSAgBkCQfDLkYjEIEAA7harXbHa73Z7vRDEfXG-pm62gA)

Esbuild **not working** example: [Playground Link](https://esbuild.github.io/try/#dAAwLjE5LjMALS1sb2FkZXI9dHMAdHlwZSBBdHRyaWJ1dGVPcHRpb25zPFQ+ID0gewogIG9uQ2hhbmdlPzogKHRoaXM6IFQsIHZhbHVlOiBzdHJpbmcsIG9sZFZhbHVlOiBzdHJpbmcpID0+IHZvaWQ7Cn07Cgpjb25zdCBBdHRyaWJ1dGUgPSA8VCwgVj4ob3B0aW9uczogQXR0cmlidXRlT3B0aW9uczxUPiA9IHt9KSA9PiAoCiAgdmFsdWU6IENsYXNzQWNjZXNzb3JEZWNvcmF0b3JUYXJnZXQ8VCwgVj4sCiAgXzogQ2xhc3NBY2Nlc3NvckRlY29yYXRvckNvbnRleHQ8VCwgVj4sCik6IENsYXNzQWNjZXNzb3JEZWNvcmF0b3JSZXN1bHQ8VCwgVj4gPT4gewogIGNvbnN0IHsgZ2V0LCBzZXQgfSA9IHZhbHVlOwogIHJldHVybiB7CiAgICBnZXQoKSB7CiAgICAgIHJldHVybiBnZXQuY2FsbCh0aGlzKTsKICAgIH0sCiAgICBzZXQodmFsdWUpIHsKICAgICAgY29uc3Qgb2xkVmFsdWUgPSBnZXQuY2FsbCh0aGlzKTsKICAgICAgc2V0LmNhbGwodGhpcywgdmFsdWUpOwogICAgICBvcHRpb25zLm9uQ2hhbmdlPy5jYWxsKHRoaXMsIHZhbHVlIGFzIHN0cmluZywgb2xkVmFsdWUgYXMgc3RyaW5nKTsKICAgIH0sCiAgfTsKfTsKCmNsYXNzIEN1c3RvbUhUTUxFbGVtZW50IHsKICAjdGVzdCA9ICd0ZXN0JzsKICBAQXR0cmlidXRlKHsKICAgIG9uQ2hhbmdlKCkgewogICAgICBjb25zb2xlLmxvZyh0aGlzLiN0ZXN0KTsKICAgIH0KICB9KSBhY2Nlc3NvciBmaWVsZCA9ICcnOwp9CgpuZXcgQ3VzdG9tSFRNTEVsZW1lbnQoKS5maWVsZCA9ICcnOw)

![image](https://github.com/evanw/esbuild/assets/67923777/1d6117d6-5a23-4e7c-8c56-253b2d344c00)

**Comment by evanw** [comment]
First of all, the code you wrote appears to be intended for [JavaScript decorators](https://github.com/tc39/proposal-decorators) and not for [TypeScript experimental decorators](https://www.typescriptlang.org/tsconfig#experimentalDecorators). They are two different features with almost-identical syntax but with different semantics. This is a problem because esbuild currently only implements TypeScript experimental decorators (see #104 for the open issue about esbuild adding support for JavaScript decorators). So your code wouldn't work even if this error didn't happen.

In case you are talking about how to run analogous code written for TypeScript experimental decorators: TypeScript has bugs and semantic inconsistencies in the design of this feature (specifically experimental decorators) that are causing this problem. See https://github.com/microsoft/TypeScript/issues/48515 for details. I'm still not sure what exactly to do about this.

**Comment by akcyp** [comment]
Yeah, you're right, I was trying to use stage 3 decorators syntax. The implementation of decorators has been taking a long time, I guess it is not an easy task, especially implementing them without full specifications. As I understand it, as long as the decorators are not in the final stage and typescript has syntax errors related to this feature, we should not expect basic support? Anyway, thank you for the explanation and quick reply, you can close this issue or keep it for reference.
