### ISSUE TITLE
Uncaught SyntaxError: export declarations may only appear at top level of a module

### ISSUE THREAD

**Issue by J-Cake** [evanw/esbuild#3395]
I'm using ESbuild to cut down on React compile times, and frankly I love it. To this day I haven't had a single issue, until I went to export a global object from my index file, and got an error from the browser:

```
Uncaught SyntaxError: export declarations may only appear at top level of a module
```

Looking at the bundled result, I don't understand the origins of this error. 

```javascript
...
// src/index.tsx
var import_jsx_runtime16 = __toESM(require_jsx_runtime(), 1);
var state = new StateManager({
  openFile: null
});
dom.createRoot(document.body.querySelector("section#root")).render(/* @__PURE__ */ (0, import_jsx_runtime16.jsxs)(FluentProvider, { theme: webLightTheme, children: [
  /* @__PURE__ */ (0, import_jsx_runtime16.jsx)("h1", { children: "Synovo Website" }),
  /* @__PURE__ */ (0, import_jsx_runtime16.jsxs)("section", { id: "ui", children: [
    /* @__PURE__ */ (0, import_jsx_runtime16.jsx)(Overview, {}),
    /* @__PURE__ */ (0, import_jsx_runtime16.jsx)(PageEditor, {})
  ] })
] }));
export {
  state
};
...
```

This seems to not be indented, and a quick bracket-count says it's 100% a top-level statement, but I'm not sure as to the origin of this issue. 

This is the file I wish to export from:

```typescript
import React from 'react';
import * as dom from 'react-dom/client';
import * as ui from '@fluentui/react-components';
import StateManager from '@j-cake/jcake-utils/state';

import Overview from './overview.js';
import PageEditor from './page-editor.js';

export interface GlobState {
    openFile: null | string
}
export const state = new StateManager<GlobState>({
    openFile: null
});

dom.createRoot(document.body.querySelector('section#root')!)
    .render(<ui.FluentProvider theme={ui.webLightTheme}>
    <h1>Synovo Website</h1>
    
    <section id="ui">
        <Overview />
        
        <PageEditor />
    </section>
</ui.FluentProvider>);
```

Something I've successfully done plenty of times.

ESBuild version: 0.19.2
Firefox Version: 117.0
MSEdge Version: 118.0.2060.1

**Comment by J-Cake** [comment]
I'm looking for guidance on how possibly to reproduce this issue. perhaps I wasn't clear in my question, granted, but as I'm not sure how to produce a reproducible, I was looking for assistance.

**Comment by evanw** [comment]
My only guess would be that you have some code that post-processes the output file somehow(either on the file system or at run-time) which changes the contents into something other than what you think they are. But it’s impossible to say what that would be without the full picture.
