### ISSUE TITLE
esbuild loader to handle everything

### ISSUE THREAD

**Issue by mkilpatrick** [evanw/esbuild#3403]
This is more of a question than anything. Is there a way to define a loader (apart from already existing loaders defined for certain filetypes) to ignore them? My use case is wanting to compile some files that might import an unknown filetype (say a font file or image type) that doesn't really matter. What I'm doing is using esbuild so I can import the module and use a specific exported const. If someone imports a filetype that isn't defined in the loaders then it will bomb out. For my purpose, the unknown types don't matter because they're not directly used by the const I'm ultimately trying to get.

Somehow Vite seems to handle all filetypes in its dev server, but I can't parse how they're doing that. Is there any way to have some fallback that will just treat all unknown imports as dataurl?

**Comment by evanw** [comment]
There isn't a built-in way to do this. The simplest way to do this is with a plugin: https://esbuild.github.io/plugins/. You can use `onResolve` to intercept all path resolution, call out to `resolve` inside your plugin to run esbuild's path resolution, then decide what to do if `resolve` fails. To avoid an infinite loop you can set `pluginData` to something when you call `resolve` and then check for that something in `onResolve` to avoid calling `resolve` again.

**Comment by mkilpatrick** [comment]
Hey Evan, I tried what you suggested. I'm trying to mark an unknown imported filetype (.bob) as external. I thought that the result of resolve would return errors, but it doesn't. Here are the arguments and return values, but you can see I still get a loader error at the end. Is there a way to try the default loaders _first_ instead of _last_?

build.onResolve's args
```
args {
  path: '../assets/images/bob.bob',
  importer: '/Users/mkilpatrick/Desktop/rp-test/src/templates/location.tsx',
  namespace: 'file',
  resolveDir: '/Users/mkilpatrick/Desktop/rp-test/src/templates',
  kind: 'import-statement',
  pluginData: true
}
```

build.resolve's response
```
result {
  errors: [],
  warnings: [],
  path: '/Users/mkilpatrick/Desktop/rp-test/src/assets/images/bob.bob',
  external: false,
  sideEffects: true,
  namespace: 'file',
  suffix: '',
  pluginData: undefined
}
```

build.onLoad's args
```
onLoad args {
  path: '/Users/mkilpatrick/Desktop/rp-test/src/assets/images/bob.bob',
  namespace: 'file',
  suffix: '',
  pluginData: undefined
}
```

✘ [ERROR] No loader is configured for ".bob" files: src/assets/images/bob.bob

    src/templates/location.tsx:40:16:
      40 │ import bob from "../assets/images/bob.bob";

**Comment by mkilpatrick** [comment]
Actually I found [this](https://github.com/chialab/rna/tree/main/packages/esbuild-plugin-any-file) plugin which works for my case.

**Comment by evanw** [comment]
I'm closing this issue because it sounds like it has been resolved.
