### ISSUE TITLE
Is there a way to detect syntax greater than or equal to es6?

### ISSUE THREAD

**Issue by someBrown** [evanw/esbuild#3411]
Is there a way to detect syntax greater than or equal to es6? Babel is slow to transform packages inside node_modules, so I want to use esbuild for syntax checking

**Comment by hyrious** [comment]
You can set esbuild `target` to `es5` and wait for its error out.

**Comment by someBrown** [comment]
> You can set esbuild `target` to `es5` and wait for its error out.
I've tried, but it doesn't work. The following output is normal 
``` 
import { transform } from "esbuild";
let ts = "test = {...{a:1}}";
let result = await transform(ts, {
  target: ["es5"],
});
console.log(result);
```

**Comment by someBrown** [comment]
> You can set esbuild `target` to `es5` and wait for its error out.

I've tried, but it doesn't work. The following output is normal.
```
import { transform } from "esbuild";
let ts = "test = {...{a:1}}";
let result = await transform(ts, {
  target: ["es5"],
});
console.log(result);

```

**Comment by hyrious** [comment]
Well, this is because the `...` is polyfilled by `__spreadValues` bu default, which results in valid es5 code. Maybe there're some [`--supported`](https://esbuild.github.io/api/#supported) options needing tweaked.

**Comment by someBrown** [comment]
> supported

I didn't set --supported, this object-rest-spread syntax doesn't report an error, it's transformed to es5, but I would expect it to report an error.

**Comment by evanw** [comment]
This is not something that esbuild does, sorry. You'll have to use some other tool for this. I'm closing this issue as out of scope.
