### ISSUE TITLE
Loader .svg: copy not exectuted when bundle: false

### ISSUE THREAD

**Issue by eatsjobs** [evanw/esbuild#3414]
When I build with "esbuild": "~0.19.4"
the loaders seems not been executed. in particular having
```
{
entryPoints: ["./src/**.ts"],
bundle: false,
loader: { ".svg": "copy" }
}
```
does not copy the file in the directory. also other options like base64 or dataurl are not executed
is this by design?

**Comment by eatsjobs** [comment]
Maybe I can handle it with a plugin or will not nork either?

**Comment by evanw** [comment]
Plugins also only get access to import paths when bundling is enabled. You need to enable bundling for the bundling functionality to work.

**Comment by eatsjobs** [comment]
Thanks for your answers @evanw I have another question but is indeed another topic. Gonna close this one.
