### ISSUE TITLE
how to force clear esbuild cache

### ISSUE THREAD

**Issue by mebest100** [evanw/esbuild#3429]
I notice the ouput is the same when re-run build even I changed build config.
But how to force clear esbuild cache. By add what param in config or just clear dir but what the dir?

**Comment by hyrious** [comment]
esbuild does not cache anything on your filesystem. It might be done by some of your plugins.

**Comment by evanw** [comment]
Marking this issue as `unactionable` because you didn't follow issue reporting instructions and didn't provide a way to reproduce the issue.

**Comment by evanw** [comment]
I'm closing this issue because no reproduction was provided.
