### ISSUE TITLE
Cannot start service: Host version

### ISSUE THREAD

**Issue by jacobthesheep** [evanw/esbuild#3431]
Not sure why this is happening but only when Vercel tries to build my website it gives this error:

```
[ERROR] Cannot start service: Host version "0.18.20" does not match binary version "0.19.4"
1 error
[vite:esbuild] The service was stopped: write EPIPE
file: /vercel/path0/src/pages/data.ts
 error   The service was stopped: write EPIPE
```
I removed package-lock.json and the whole node_modules folder to be sure but the error still shows up.

It's only happening with this [repo](https://github.com/jacobthesheep/torahcycle.info)

**Comment by hyrious** [comment]
This was because you have multiple versions of esbuild as dependencies of different packages, and `bun` wrongly hoisted them:

```
@astrojs/vercel 5.0.2
├─┬ astro 3.2.3 peer
│ ├── esbuild 0.19.4
│ ├─┬ vite 4.4.11
│ │ └── esbuild 0.18.20
│ └─┬ vitefu 0.2.4
│   └─┬ vite 4.4.11 peer
│     └── esbuild 0.18.20
└── esbuild 0.19.4
astro 3.2.3
├── esbuild 0.19.4
├─┬ vite 4.4.11
│ └── esbuild 0.18.20
└─┬ vitefu 0.2.4
  └─┬ vite 4.4.11 peer
    └── esbuild 0.18.20
```

It should be a bug of `bun`.

**Comment by jacobthesheep** [comment]
> This was because you have multiple versions of esbuild as dependencies of different packages, and `bun` wrongly hoisted them:
> 
> ```
> @astrojs/vercel 5.0.2
> ├─┬ astro 3.2.3 peer
> │ ├── esbuild 0.19.4
> │ ├─┬ vite 4.4.11
> │ │ └── esbuild 0.18.20
> │ └─┬ vitefu 0.2.4
> │   └─┬ vite 4.4.11 peer
> │     └── esbuild 0.18.20
> └── esbuild 0.19.4
> astro 3.2.3
> ├── esbuild 0.19.4
> ├─┬ vite 4.4.11
> │ └── esbuild 0.18.20
> └─┬ vitefu 0.2.4
>   └─┬ vite 4.4.11 peer
>     └── esbuild 0.18.20
> ```
> 
> It should be a bug of `bun`.

Thanks
