### ISSUE TITLE
Does config.define affects node_modules?

### ISSUE THREAD

**Issue by Neo-Ciber94** [evanw/esbuild#3432]
> Sorry if we are not suppose to make questions in the issues

I consume a library that defines a `process.env.VARIABLE` can I use define to replace that value?

```ts
build({
   define: {
       'process.env.VARIABLE': "'my_new_value'"
   }
})
```

I'm trying to do that but is not being replaced after build.

**Comment by hyrious** [comment]
Yes, `define` affects every bundled file. That's how esbuild could [handle](https://github.com/evanw/esbuild/blob/main/docs/architecture.md#constant-folding) libraries like React.

If you find your `define` not working, there might be several reasons:

- The library is not bundled in, i.e. it is externalized (`--external:lib`) or just not be references by your code.
- Some plugins doing something that affects your final bundle.

**Comment by Neo-Ciber94** [comment]
@hyrious Thanks, that will help me to identify the cause.
