### ISSUE TITLE
ESBuild used outdated GO Version

### ISSUE THREAD

**Issue by tintinInGitHub** [evanw/esbuild#3438]
I've used the Strapi (https://github.com/strapi/strapi) Which have also used Esbuild and after i've Scan the Image Vulnerabilites ,it got these GO issues.

![Screenshot 2566-10-10 at 14 45 04](https://github.com/evanw/esbuild/assets/72849666/e3e17442-3cdc-4b81-a715-7b65ea3c9019)

![Screenshot 2566-10-10 at 14 45 17](https://github.com/evanw/esbuild/assets/72849666/44c10beb-faa9-4907-ad76-6fbb3ad9ef8b)

and it also led to the ESBuild Path

![image](https://github.com/evanw/esbuild/assets/72849666/00bd2956-d687-4eeb-ad6d-3a6ddabddb59)

This might be generate unexpected code at build time when using cgo. And much more can happen.

The best way to fix this is to upgrade to recommend versions of GO : <1.20.5/<1.19.6

Thank you

**Comment by evanw** [comment]
This is incorrect. The latest published binaries for esbuild are [built with Go 1.20.7](https://github.com/evanw/esbuild/blob/48eda0981b4da7624c8bb7acd83dae43c5e9408f/Makefile#L22-L23). See https://esbuild.github.io/faq/#old-go-version for more information about irrelevant vulnerability reports.

Closing this issue as invalid.
