### ISSUE TITLE
JSON loader uses commonjs

### ISSUE THREAD

**Issue by LarsDenBakker** [evanw/esbuild#344]
When using the JSON loader to transform a single file, the output is commonjs format. Setting the `format` option has no effect, I think that's only used when bundling.

See https://repl.it/repls/SuburbanMediumblueLinuxkernel#index.js for a reproduction.

**Comment by evanw** [comment]
I think this looks like a duplicate of #109 to me.

**Comment by LarsDenBakker** [comment]
Being able to specify the format would solve this, but it seems like it will be some work still.

But I was expecting that loaders for non-js files would return an es module.

**Comment by evanw** [comment]
Closing as a duplicate of #109 (which was just implemented).
