### ISSUE TITLE
esbuild plugins show no output in the console

### ISSUE THREAD

**Issue by ThePlenkov** [evanw/esbuild#3440]
Hi!

I try to follow [plugins guide](https://esbuild.github.io/plugins/#using-plugins) and created a simple plugin.

What I notice - is that in this case console is empty and it doesn't look nice.

Is there any other way to declare plugins in the way, that's it's possible to use same output as CLI has?

Thanks!

**Comment by ThePlenkov** [comment]
i mean something like this:
![image](https://github.com/evanw/esbuild/assets/6381507/9c0d1771-de35-4e1b-bcd8-17509808d992)

**Comment by evanw** [comment]
Docs for this setting are here: https://esbuild.github.io/api/#log-level

**Comment by evanw** [comment]
I'm closing this issue because there is already a way to control this, and it's already documented.
