### ISSUE TITLE
should't string concatenation be minified?

### ISSUE THREAD

**Issue by lucafabbian** [evanw/esbuild#3444]
Consider this code:

```js
let a = "hello"
a+="world"

let b = "good"
b+="night"

export const c = a
export const d = b
```
Minified with `esbuild`, it becames:
```
let o="hello";o+="world";let t="good";t+="night";export const c=o,d=t;
```

but could become
```js
export const c = "helloworld",d="goodnight"
```

is there a way to force it? Would it ever be implemented?

**Comment by evanw** [comment]
Partial evaluation during compilation only supports a few limited constructs. The `+=` operator is not one of them as it involves tracking changing values for a variable over time, which is not something esbuild does (esbuild is not a JavaScript VM). You can get this to do what you want by using the `+` operator instead:

```js
let a = "hello"
+"world"

let b = "good"
+"night"

export const c = a
export const d = b
```

That minifies to this:

```js
let o="helloworld",t="goodnight";export const c=o,d=t;
```

**Comment by lucafabbian** [comment]
is there an official way to specify "run this at compile time"? Otherwise I'll try to do it writing a plugin myself

**Comment by evanw** [comment]
No, the JavaScript language unfortunately does not have a compile-time evaluation feature.

You can do anything in a plugin of course, so that will work. But you can also precompute the strings before calling esbuild's API and then pass them to esbuild as [define](https://esbuild.github.io/api/#define) values to inline them directly into your code, which may be simpler than writing a plugin depending on what you're doing.

**Comment by lucafabbian** [comment]
I've resolved by writing a simple plugin which parses every `.preprocess.js` file at compile time.
```js
const preprocessPlugin = {
  name: 'preprocess',
  setup(build) {
    build.onLoad({ filter: /\.preprocess(\.js|)$/ }, async (args) =>{
      const module = await import(args.path);
      let contents = ''
      for(let [key, value] of Object.entries(module)){
        contents+=`export ${key === 'default' ? 'default' : 'const ' + key + ' ='} ${JSON.stringify(value)}\n`
      }
      return { contents, loader: "js" };
    })
  },
}
```

**Comment by evanw** [comment]
I'm glad you were able to find a solution. I'm going to close this issue because I consider this kind of partial evaluation to be out of scope for esbuild.
