### ISSUE TITLE
Import maps not supported - can't build many projects

### ISSUE THREAD

**Issue by manake** [evanw/esbuild#3445]
Three.js library comes with three.module.js and also with plugins in /jsm/ folder that typically are accessible using import map using `three/addons/` prefix.

So, `esbuild` has no capability of building three.js projects because such projects require import maps.

It will set everything from /jsm/ folder to `undefined`:
```
WARNING] Import "OBJLoader" will always be undefined because there is no matching export in "node_modules/three/build/three.module.js" [import-is-undefined]
```

Adding support for import maps is important and most likely very easy, so I'm making such suggestion.

**Comment by manake** [comment]
I think I made a mistake, it actually seems to be able to find exports in /jsm/ automatically.

And even if not, it seems import maps could be specified with a plugin?

If so, please close this issue.

**Comment by evanw** [comment]
Ok, I'm closing this issue. There is already another open issue for import map support: #2230. Someone has posted a potential plugin starting point there.
