### ISSUE TITLE
force pure annotation to "well-known" dependencies functions 

### ISSUE THREAD

**Issue by Sarabadu** [evanw/esbuild#3446]
hope this is the right place to ask this. we are using esbuild for bundle service worker, and there is a common issue with react `createContext` calls, esbuild evaluate those context creation on every library as side effect, which make that call to appear on the final bundle.

if any library contains something like:

```js
import {createContext} from 'react'

export const context = createContext();
```

Will end up with this as an output:
```js
// file.js
var import_react = __toESM(require_react());
var context = (0, import_react.createContext)();
```

I understand that the way to solve it is adding the `/* #__PURE__ */` on the createContext call. but its difficult to solve that when the code comes from different dependencies. So i was wondering if there is any way to set those kind of thing on esbuild configuration. I was looking  at the `pure` option, but didn't manage to make that work.

if not I assume should instead managed by a plugin

**Comment by evanw** [comment]
There is no way to do this at the moment other than to add `/* __PURE__ */` at the call site, as described in esbuild's documentation: https://esbuild.github.io/api/#pure

**Comment by Sarabadu** [comment]
Great closing it then, thanks
