### ISSUE TITLE
Class instance fields compilation vs TypeScript

### ISSUE THREAD

**Issue by lxsmnsyc** [evanw/esbuild#3447]
Example code:
```ts
class Animal {
  name: string;
  constructor(theName: string) {
    this.name = theName;
  }
}
```

if the target is set to `es2017`, TypeScript compiles this to:

```js
class Animal {
    constructor(theName) {
        this.name = theName;
    }
}
```

However, ESBuild compiles this into:

```js
var __defProp = Object.defineProperty;
var __defNormalProp = (obj, key, value) => key in obj ? __defProp(obj, key, { enumerable: true, configurable: true, writable: true, value }) : obj[key] = value;
var __publicField = (obj, key, value) => {
  __defNormalProp(obj, typeof key !== "symbol" ? key + "" : key, value);
  return value;
};
class Animal {
  constructor(theName) {
    __publicField(this, "name");
    this.name = theName;
  }
}
```

Which, I would assume, is because ESBuild converts the TS code into ESNext code and then compiles it down to ES2017 for class instance fields?

ESBuild's output also negatively affects perf, so is it possible for ESBuild to just skip the instance field polyfill if the field declared only has a type annotation? It would've been understandable if the field has an initial value, or maybe is it possible to compile this such that the instance field w/ initial value would be just `this.field = initial`?

**Comment by hyrious** [comment]
See [the TypeScript section in the docs](https://esbuild.github.io/content-types/#tsconfig-json). If you want the legacy TypeScript class fields behavior, you only need to set this in tsconfig.json:

```json
"useDefineForClassFields": false
```

**Comment by lxsmnsyc** [comment]
ahh thanks! Somehow I missed that.
