### ISSUE TITLE
Watch doesn't work (copying and pasting exact code from docs) 

### ISSUE THREAD

**Issue by s1nistr4** [evanw/esbuild#3448]
So when trying to run esbuild in watch mode, the official docs as of today (10/13/2023) tell you do run this code 

```
import * as esbuild from 'esbuild'

let ctx = await esbuild.context({
  entryPoints: ['app.js'],
  outfile: 'out.js',
  bundle: true,
})

await ctx.watch()
console.log('watching...')
```

Source here: https://esbuild.github.io/api/#watch

However this doesn't work and instead returns the following error: 

```
Invalid option in context() call: "watch"
```

I heard there was a breaking change about this but if there is then the docs should be updated to reflect that. I haven't been able to find any info online about how to run esbuild in watch mode aside from the cli.

**Comment by evanw** [comment]
I'm confused. The exact source code you posted works fine:

```console
$ cat index.mjs 
import * as esbuild from 'esbuild'

let ctx = await esbuild.context({
  entryPoints: ['app.js'],
  outfile: 'out.js',
  bundle: true,
})

await ctx.watch()
console.log('watching...')

$ node index.mjs 
watching...
✘ [ERROR] Could not resolve "app.js"
```

The error you get that says `Invalid option in context() call: "watch"` would only happen if you provided an option called `watch` to the `context()` call. But there is no `watch` property in the object literal that your code passes to `context`, so that error does not occur.

**Comment by evanw** [comment]
I'm closing this issue as invalid. Copying and pasting the exact code from the docs does work, as demonstrated above. I'm guessing you probably have a stray `watch` property in your object literal from the old API that you didn't remove, and that you didn't actually copy and paste the exact code from the docs.
