### ISSUE TITLE
Does `context.watch()` take any options?

### ISSUE THREAD

**Issue by stupid-genius** [evanw/esbuild#3476]
I see, in multiple places, in the docs that `context.watch({})` takes an object, presumably to pass in options.  But in the docs/examples, the object is always empty.  Are the options documented anywhere?

**Comment by hyrious** [comment]
Currently there's no watch options, the interface is there for possible options in the future. Its type also indicates that the object is optional:

```ts
watch(options?: WatchOptions): Promise<void>
```

**Comment by QAComet** [comment]
Could there be something noted in the [watch section](https://esbuild.github.io/api/#watch) of the documentation? It's frustrating to see that option noted in the typescript helper popups in vscode, but then having to search through the source/issues here for the definition of WatchOptions (and it being an empty go struct).
