### ISSUE TITLE
esbuild `keepNames` use results in errors in older browsers

### ISSUE THREAD

**Issue by jahorton** [evanw/esbuild#3477]
From part of `esbuild`'s `keepNames` (https://esbuild.github.io/api/#keep-names) setup:

```javascript
var ae=Object.defineProperty;var v=function(r,e){return ae(r,\"name\",{value:e,configurable:!0})};
```

When that block of code is executed on certain notable older browsers, the following error will be thrown:

```
TypeError: Cannot redefine property: name 
```

My team has run into this issue in our support of Android 5.0 / API 21 devices, which (if not updated) defaults to Chrome for Android 35.  

This is fortunately rather easy to verify through Android Studio:
1. Via "Tools" > "Device Manager"...
2. The "Nexus S" and "Pixel 2 XL" simulation targets can be configured for use of API 21, which have images set to Chrome 35
3. From there, remote-device inspection can then be used to inspect inside the simulated app's webview.
4. Then, within the Chrome inspector window, via Console, enter the following lines commands in sequence:

```javascript
var temp = function() { console.log("hello") };
console.log(temp.name); // outputs "" on API 21 / Android 5.0
Object.defineProperty(temp, 'name', {value: 'temp', configurable: true}); // will throw the error on API 21 / Android 5.0.
```

I cannot guarantee that API 21 is either the earliest or the last Android API to have this issue; it's simply the earliest one my team supports and is the version for which we encountered the issue.

I suppose this is a case in which `keepNames` should simply be off... and that's probably fair.  Would be nice if there were an error clearly denoting that `keepNames` has failed in these cases, though - it took quite a bit of investigation to reach this conclusion.

**Comment by evanw** [comment]
I think this corresponds to this [`configurable: true`](https://caniuse.com/mdn-javascript_builtins_function_name_configurable_true) support matrix. I should be able to make esbuild generate an error if you attempt to configure it this way.
