### ISSUE TITLE
ignore-scripts flag is mentioned in comment but not in error

### ISSUE THREAD

**Issue by folmert** [evanw/esbuild#3478]
Running `npm run build` after installing packages with `npm install --ignore-scripts` will fail and esbuild won't tell exactly why. It mentions the `ignore-scripts` flag but only in a comment...

> // If that didn't work too, then maybe someone installed esbuild with
>         // both the "--no-optional" and the "--ignore-scripts" flags. The fix
>         // for this is to just not do that. We don't attempt to handle this
>         // case at all.

source: https://github.com/evanw/esbuild/blob/4e11b50fe3178ed0a78c077df78788d66304d379/lib/npm/node-platform.ts#L206C9-L207C69

Why the error mentions `--no-optional` but not `--ignore-scripts`? It should warn about both flags.

**Comment by evanw** [comment]
> Running `npm build` after installing packages with `npm install --ignore-scripts` will fail and esbuild won't tell exactly why.

Sorry but I don't understand what you're saying. This is what happens when I run `npm build` in an empty package with a dependency on `esbuild`:

```console
$ npm build
Unknown command: "build"

To see a list of supported npm commands, run:
  npm help
```

I'm marking this issue report as `unactionable` because you didn't follow the issue reporting instructions and didn't provide enough information to reproduce the issue. I will close this issue if sufficient information isn't provided.

**Comment by folmert** [comment]
@evanw Reproduction steps:

1. create a new Vite project with `npm create vite@latest` (Vite is using esbuild bundler)
2. run `npm install --ignore-scripts`
3. run `npm run build`
4. esbuild throws an error:

> `The package "${pkg}" could not be found, and is needed by esbuild.
> If you are installing esbuild with npm, make sure that you don't specify the
> "--no-optional" or "--omit=optional" flags. The "optionalDependencies" feature
> of "package.json" is used by esbuild to install the correct binary executable
> for your current platform.

My point is that this error is a bit misleading and inaccurate. `--no-optional` flag was **not** the reason it failed, `--ignore-scripts` was - it should have warned about using `--ignore-scripts` flag as well.

**Comment by evanw** [comment]
I still can't reproduce this. Here's what I did (in an empty folder on GitHub Codespaces), and it worked fine:

```console
$ npm create vite@latest
✔ Project name: … vite-project
✔ Select a framework: › Vanilla
✔ Select a variant: › TypeScript

Scaffolding project in /workspaces/codespaces-blank/vite-project...

Done. Now run:

  cd vite-project
  npm install
  npm run dev

$ cd vite-project/
$ npm install --ignore-scripts

added 11 packages, and audited 12 packages in 2s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
$ npm run build

> vite-project@0.0.0 build
> tsc && vite build

vite v5.0.0 building for production...
✓ 7 modules transformed.
dist/index.html                 0.46 kB │ gzip: 0.29 kB
dist/assets/index-s-MxoWxy.css  1.21 kB │ gzip: 0.63 kB
dist/assets/index-QFzqfbCu.js   3.05 kB │ gzip: 1.62 kB
✓ built in 124ms
```

The reason I'm not just throwing `--ignore-scripts` into the error message as you're suggesting is that esbuild is supposed to work fine with `--ignore-scripts` (as it does in the demonstration above). So what you're reporting seems like it might be a bug. But if I can't reproduce the bug then I can't fix it.

Make sure you don't have some global npm configuration that breaks package installation. For example if you run `npm config set omit optional` then `npm install` will break (including Rollup's new `@rollup/rollup-linux-x64-gnu` package, which Vite now also uses). But that would be an issue that you need to fix, not esbuild or Rollup.

**Comment by evanw** [comment]
Closing this issue due to lack of a follow-up reply.
