### ISSUE TITLE
Why are classes transformed to var x = class { when bundling?

### ISSUE THREAD

**Issue by joshbrew** [evanw/esbuild#3481]
Before
<img width="469" alt="Capture" src="https://github.com/evanw/esbuild/assets/18196383/833c3c45-7f1a-419d-b236-0447e1531b8f">

After
<img width="449" alt="Capture" src="https://github.com/evanw/esbuild/assets/18196383/a05b0f0f-c205-4f65-a3b1-69635cc984f5">

I only noticed because it broke a feature in a plugin I'm testing (ECMAScript for Godot) that expects the other syntax. I am just curious why as it looks a bit unorthodox, any way to disable it?

**Comment by intrnl** [comment]
See the changelog for [0.7.19](https://github.com/evanw/esbuild/blob/main/CHANGELOG-2020.md#0719) for details, but this was something that had been permanently enabled and can't be turned off since 0.8.13

**Comment by joshbrew** [comment]
"Weird compiler shit" got it :-)

**Comment by lxhzzy06** [comment]
+1
