### ISSUE TITLE
[Question] Copy HTML files

### ISSUE THREAD

**Issue by Mqxx** [evanw/esbuild#3483]
Hey is it possible that ESBuild just copies my HTML files from my `src` folder to my `dist` folder? I currently have a [very ugly script](https://github.com/DenoPlayground/CopyFiles) that does this task. Is there a flag in ESBuild with which I can achieve this?

Thanks. ~Mqx

**Comment by evanw** [comment]
I believe you can use the [`copy` loader](https://esbuild.github.io/content-types/#copy) for this. [Here is an example.](https://esbuild.github.io/try/#YgAwLjE5LjUALS1idW5kbGUgc3JjL2FwcC50cyBzcmMvaW5kZXguaHRtbCAtLWxvYWRlcjouaHRtbD1jb3B5IC0tb3V0ZGlyPWRpc3QAAHNyYy9pbmRleC5odG1sADxzY3JpcHQgc3JjPSJhcHAuanMiPjwvc2NyaXB0PgAAc3JjL2FwcC50cwBjb25zb2xlLmxvZygnaGVsbG8nKQ)

**Comment by Mqxx** [comment]
Nice that works perfectly!
