### ISSUE TITLE
[Feature Request] Provide a lazy CommonJS require option

### ISSUE THREAD

**Issue by SukkaW** [evanw/esbuild#3488]
Given the following input:

```js
import { a } from 'mod';
export default a(1);
```

esbuild will output the following code using `--format=cjs`:

```js
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);
var stdin_exports = {};
__export(stdin_exports, {
  default: () => stdin_default
});
module.exports = __toCommonJS(stdin_exports);
var import_mod = require("mod");
var stdin_default = (0, import_mod.a)(1);
```

The `require('mod')` is eagerly evaluated, which retains the correct behavior. However, it may adversely affect the initial load time as evaluating dependencies upfront can be unnecessary when implementing a library, see https://github.com/pnpm/pnpm/issues/6447#issuecomment-1523077211 and https://github.com/pnpm/pnpm/pull/6998.

Hence, I propose adding a new format option `--format=lazy-cjs` (or a new option `--lazy`). When specified, the `require()` should be lazily evaluated when their imported bindings are used for the first time.

Here is swc's output when `jsc.module.type` is set to `commonjs` and `jsc.module.lazy` is set to `true`:

```js
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "default", {
    enumerable: true,
    get: function() {
        return _default;
    }
});
function _mod() {
    const data = require("mod");
    _mod = function() {
        return data;
    };
    return data;
}
const _default = (0, _mod().a)(1);
```

**Comment by lydell** [comment]
Isn’t `require("mod")` executed immediately in swc’s output as well? 🤔 When that piece of code executes, one of the last things it does is calling `_mod()`, which calls `require("mod")`, which makes the `exports.default` getter useless?

**Comment by SukkaW** [comment]
> Isn’t `require("mod")` executed immediately in swc’s output as well? 🤔 When that piece of code executes, one of the last things it does is calling `_mod()`, which calls `require("mod")`, which makes the `exports.default` getter useless?

My original 2 LOC input is only for demonstration. A more real-world example would be like this:

```js
// input
import { a } from 'mod';
import { readFile } from 'fs/promises';

(async () => {
  const data = await readFile('data.txt', 'utf-8');
  a(JSON.parse(data));
})();
```

```js
// swc output
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
function _mod() {
    const data = require("mod");
    _mod = function() {
        return data;
    };
    return data;
}
function _promises() {
    const data = require("fs/promises");
    _promises = function() {
        return data;
    };
    return data;
}
(async ()=>{
    const data = await (0, _promises().readFile)('data.txt', 'utf-8');
    (0, _mod().a)(JSON.parse(data));
})();
```

Here, `_mod()` will not be executed until the `data.txt` is read from the filesystem, which means **`require("mod")` will not happen until the `data.txt` is read from the filesystem**, **hence the `lazy`**.

**Comment by lydell** [comment]
In that example you have `async` anyway, so you could just as well use `const { a } = await import("mod")`?

**Comment by SukkaW** [comment]
> In that example you have `async` anyway, so you could just as well use `const { a } = await import("mod")`?

`await import('mod')` is not an option if we are building a sync API:

```js
// input
import { a } from 'mod';
import { readFileSync } from 'fs';

export const someSyncAPI = () => {
  const data = readFileSync('data.txt', 'utf-8');
  if (data. length > 0) {
    a(JSON.parse(data));
  } else {
    console.log('data.txt is empty!');
  }
};
```

```js
// swc output
"use strict";
Object.defineProperty(exports, "__esModule", {
    value: true
});
Object.defineProperty(exports, "someSyncAPI", {
    enumerable: true,
    get: function() {
        return someSyncAPI;
    }
});
function _mod() {
    const data = require("mod");
    _mod = function() {
        return data;
    };
    return data;
}
function _fs() {
    const data = require("fs");
    _fs = function() {
        return data;
    };
    return data;
}
const someSyncAPI = ()=>{
    const data = (0, _fs().readFileSync)('data.txt', 'utf-8');
    if (data.length > 0) {
        (0, _mod().a)(JSON.parse(data));
    } else {
        console.log('data.txt is empty!');
    }
};
```

Only after `data.txt` is read from the filesystem and its content is not empty will `require("mod")` be executed.

Also, migrating large existing codebases (like pnpm in this case) to use `await import()` would be a lot of work.

**Comment by lydell** [comment]
Nice, I think your issue has a higher chance now that you’ve provided a motivating example.

**Comment by evanw** [comment]
I'm closing this issue as I do not intend to do this. Both CommonJS and ESM have well-defined standard semantics and I do not plan on having esbuild deviate from them.
