### ISSUE TITLE
CSS `mask-composite` is not being vendored prefixed

### ISSUE THREAD

**Issue by alan-agius4** [evanw/esbuild#3493]
The `mask-composite` CSS property is not being vendored prefixed.

Repro: https://esbuild.github.io/try/#dAAwLjE5LjUAewogIGxvYWRlcjogJ2NzcycsCiAgdGFyZ2V0OiBbJ2Nocm9tZTEyMiddCn0AKiB7Cm1hc2staW1hZ2U6IHJldmVydDsKbWFzay1jb21wb3NpdGU6IGV4Y2x1ZGU7Cn0

https://caniuse.com/?search=mask-composite

Esbuild version: 0.19.5

**Comment by evanw** [comment]
The mapping that you're supposed to do for this seems to be a little more complex than just a vendor prefix. From some initial research it looks like the following additional rewrites might be needed:

* `mask-composite: add` => `-webkit-mask-composite: source-over`
* `mask-composite: subtract` => `-webkit-mask-composite: source-out`
* `mask-composite: intersect` => `-webkit-mask-composite: source-in`
* `mask-composite: exclude` => `-webkit-mask-composite: xor`

I'm not familiar with this CSS property though.

**Comment by alan-agius4** [comment]
Yes, you are absolutely right, it’s far more examples than just adding a prefix.
