### ISSUE TITLE
[Feature request] Allow bundling typescript without compiling

### ISSUE THREAD

**Issue by dsblv** [evanw/esbuild#3494]
We use esbuild as a build step before another bundler. It seems wasteful to transform ts code twice, and I'd love keeping type info in place too.

I believe this is not out of scope for esbuild, because

a. It'd improve deno target output (deno supports ts natively)
b. It seems in line with "Think of esbuild as a "linker" for the web

If esbuild already intercepts tsc's module resolution, it's a matter of not running `tsc.transform` at all. As far as I can tell, it's not possible with current api/plugins.

Thank you!

**Comment by evanw** [comment]
Sorry, but I consider this to be [out of scope](https://esbuild.github.io/content-types/#no-type-system). Right now esbuild treats TypeScript types as whitespace. Parsing and interpreting TypeScript types would be a massive increase in complexity. From what I understand, interpreting the types would be necessary to do bundling and tree-shaking for TypeScript code, which would require duplicating most of the complexity of the TypeScript compiler.

**Comment by dsblv** [comment]
Interesting! I figured that you'd have to fully cover typescript ast to be able to parse it. Love that you could avoid that!

I am curious what kind of type information you're referring to? In my (limited) understanding, bundler mostly tracks identifiers, and types are identifiers in typescript's ast.

**Comment by evanw** [comment]
These two TypeScript files are both necessary for a successful type check even though there is no import between them and `CSSStyleDeclaration` is declared seemingly without being used:

```ts
document.body.style.foo = 'bar'
```

and

```ts
interface CSSStyleDeclaration {
  foo: 'bar' | 'baz'
}
```

You would need type checking to determine that `document.body.style` is a reference to `CSSStyleDeclaration`. I suppose you could argue that a property of `foo` should pull in every file with a `foo` identifier in it somewhere, but I suspect even that isn't sufficient for bundling TypeScript code correctly.

**Comment by dsblv** [comment]
I see what you mean, thank you! Didn't realise typescript could even do that.

Agreed, there's probably no point in doing it not 100% correct when it comes to types. I wonder if it's possible by running typescript language server and asking it proper questions though...

Anyway, gonna close the issue now, thank you so much for clarification!
