### ISSUE TITLE
[Feature request] Expose module graph API

### ISSUE THREAD

**Issue by dsblv** [evanw/esbuild#3495]
`bundle` mode offers two ways of opting a package out of the bundle: `packages: "external"` and `external: [...]`. In other words: bundle none or bundle some.

I needed a way to _include_ some packages while dropping others, and came up with a two step process:

- Bundle all, see what comes out in metafile
- Get the module list, exclude some, put all in `external`, bundle again

While working with metafiles, I found some more interesting ways to use the module graph info, like hoisting css imports for prefetch.

However, I'd appreciate a module graph API without the overhead of building twice. `esbuild.resolve(config)`, that outputs just the metadata?

Thank you!

**Comment by evanw** [comment]
> I needed a way to _include_ some packages while dropping others

Isn't this what [plugins](https://esbuild.github.io/plugins/) are for? You can write JavaScript code to make arbitrary external-or-not decisions on a case-by-case basis.

**Comment by dsblv** [comment]
That's right, that plugin is already written :)

My point was, that module graph is still useful on its own, and it'd make sense to use the same tool for bundling as well as for analysis.

I see that it's not what esbuild's intended purpose is, just wanted to highlight it's usefulness!
