### ISSUE TITLE
Tree shaking multilevel wildcard imports

### ISSUE THREAD

**Issue by ibrahimqasim** [evanw/esbuild#3499]
When doing multiple levels of wildcard imports using `index.js` files, esbuild seems to not remove some of the unused code correctly.

You can see an example [here](https://esbuild.github.io/try/#YgAwLjE5LjYALS1idW5kbGUAZQBlbnRyeS5qcwBpbXBvcnQgKiBhcyBmb28gZnJvbSAnLi9mb28nCmZvby5iYXouZmlyc3QuZnVuY3Rpb24xKCkAAGZvby9pbmRleC5qcwBleHBvcnQgKiBhcyBiYXIgZnJvbSAnLi9iYXInCmV4cG9ydCAqIGFzIGJheiBmcm9tICcuL2JheicKAABmb28vYmFyL2luZGV4LmpzAGV4cG9ydCAqIGFzIGZpcnN0IGZyb20gJy4vYW50ZWxvcGUnCmV4cG9ydCAqIGFzIHNlY29uZCBmcm9tICcuL2JhYm9vbicKAABmb28vYmFyL2FudGVsb3BlLmpzAGV4cG9ydCBjb25zdCBmdW5jdGlvbjEgPSAoKSA9PiB7CiAgICBjb25zb2xlLmxvZygnZnVuY3Rpb24xJykKfQpleHBvcnQgY29uc3QgZnVuY3Rpb24yID0gKCkgPT4gewogICAgY29uc29sZS5sb2coJ2Z1bmN0aW9uMicpCn0KAABmb28vYmFyL2JhYm9vbi5qcwBleHBvcnQgY29uc3QgZnVuY3Rpb24xID0gKCkgPT4gewogICAgY29uc29sZS5sb2coJ2Z1bmN0aW9uMycpCn0KZXhwb3J0IGNvbnN0IGZ1bmN0aW9uMiA9ICgpID0+IHsKICAgIGNvbnNvbGUubG9nKCdmdW5jdGlvbjQnKQp9CgAAZm9vL2Jhei9pbmRleC5qcwBleHBvcnQgKiBhcyBmaXJzdCBmcm9tICcuL2NvdycKZXhwb3J0ICogYXMgc2Vjb25kIGZyb20gJy4vZG9ua2V5JwoAAGZvby9iYXovY293LmpzAGV4cG9ydCBjb25zdCBmdW5jdGlvbjEgPSAoKSA9PiB7CiAgICBjb25zb2xlLmxvZygnZnVuY3Rpb241JykKfQpleHBvcnQgY29uc3QgZnVuY3Rpb24yID0gKCkgPT4gewogICAgY29uc29sZS5sb2coJ2Z1bmN0aW9uNicpCn0KAABmb28vYmF6L2RvbmtleS5qcwBleHBvcnQgY29uc3QgZnVuY3Rpb24xID0gKCkgPT4gewogICAgY29uc29sZS5sb2coJ2Z1bmN0aW9uNycpCn0KZXhwb3J0IGNvbnN0IGZ1bmN0aW9uMiA9ICgpID0+IHsKICAgIGNvbnNvbGUubG9nKCdmdW5jdGlvbjgnKQp9Cg).

When doing a wildcard import for `foo`, `bar` is correctly removed, but the whole of `baz` is included. I would expect only `function1` from `cow` to be included. However, it seems that a single level of wildcard import works (e.g. `import * as first from './foo/baz/cow'` then `first.function1()`).

My expectation would be that wildcard imports would be tree shaken to an arbitrary depth.

**Comment by evanw** [comment]
This issue has already been reported (see #1420 and #2636), so I'm closing this as a duplicate. You can read the comments in those other issues for more information.

**Comment by ibrahimqasim** [comment]
Apologies for the duplicate
