### ISSUE TITLE
Comparison with -0 using the "===" operator will also match 0

### ISSUE THREAD

**Issue by SangMinL96** [evanw/esbuild#3508]
**I got this warning while I was working on it**
[WARNING] Comparison with -0 using the "===" operator will also match 0 [equals-negative-zero]
    ../../.yarn/__virtual__/@encarpkg-design-virtual-46bb46c3f9/1/packages/design/dist/index.umd.js:38:99374:
      38 │ ...anslate=e.scrollWidth-e.offsetWidth-e.scrollLeft:t.translate=-e.scrollLeft:t.translate=-e.scrollTop,t.translate===-0&&(t.translate=0),t.updateActiveIndex(),t.updateSlidesClasses();var r,a=t.maxTranslate()-t.minTranslate();a===0?r=...
         ╵                                                                                                                      ~~
  Floating-point equality is defined such that 0 and -0 are equal, so "x === -0" returns true for
  both 0 and -0. You need to use "Object.is(x, -0)" instead to test for -0.

**I looked it up in the dist folder with esbuild compiling and corrected it.**
stopImmediatePropagation())))}function Ac(){var t=this,e=t.wrapperEl,i=t.rtlTranslate,n=t.enabled;if(n){t.previousTranslate=t.translate,t.isHorizontal()?i?t.translate=e.scrollWidth-e.offsetWidth-e.scrollLeft:t.translate=-e.scrollLeft:t.translate=-e.scrollTop,`t.translate===-0`&&(t.translate=0),t.updateActiveIndex(),t.updateSlidesClasses();var r,a=t.maxTranslate()-t.minTranslate();a===0?r=0:r=(t.translate-t.minTranslate())/a,r!==t.progress&&t.updateProgress(i?-t.translate:t.translate),t.emit("setTranslate",t.translate,!1)}}var Ir=!1;function Tc(){}function Oc(){var t=this,e=Ie(),i=t.params,n=t.touchEvents,r=t.el,a=t.wrapperEl,o=t.device,

**Modifying the displayed code**
`t.translate===Object.is(x, -0)`
When I checked the correction, the warning disappeared

**I'm sorry, but we couldn't implement the problem reproduction code.**
But let me tell you about my development environment.
Monorepo was configured using turbo po, and there are largely design packages in the Vite (react) environment and service packages in the nextjs environment.
I received a warning when I imported the design package of the vite environment from the nextjs package.
The vite design environment ran the vite config watch mode and both mjs and umd.js received the same warning.

**!!  I don't know if it will help, but I will copy and paste the suspect code below**

` useLayoutEffect(() => {
		const messageElement = messageElementRef.current;

		if (isBrowser && messageElement?.offsetTop && triggerElement) {
			const tooltipBackgroundColor = window
				.getComputedStyle(messageElement, null)
				.getPropertyValue('background-color');
			const messageWidth = messageElement.offsetWidth;
			const messageHeight = messageElement.offsetHeight;
			const triggerElementRect = triggerElement.getBoundingClientRect();
			const triggerOffset = triggerElementRect && {
				top: triggerElementRect.top + window.scrollY,
				left: triggerElementRect.left + window.scrollX,
				width: triggerElementRect.width,
				height: triggerElementRect.height,
			};
			const triggerTop = triggerOffset.top;
			const triggerLeft = triggerOffset.left;
			const triggerWidth = triggerOffset.width;
			const triggerHeight = triggerOffset.height;
			const rightEnd = Math.round(triggerLeft - messageWidth / 2 + triggerWidth / 2) + messageWidth;
			const isOverRight = rightEnd + ADJUSTMENT > window.innerWidth;
			const isOverTop = triggerElementRect.top - messageHeight - ADJUSTMENT < 0;
			const messageRight = window.innerWidth - ADJUSTMENT;
			const triggerRight = triggerLeft + triggerWidth;
			const tooltipLeft = calcLeft(triggerLeft, triggerWidth, messageWidth);
			const tooltipCalculatedStyle: CSSProperties = {};
			let tooltipArrowCalculatedStyle: CSSProperties;

			if (arrowPosition === 'TOP') {
				tooltipCalculatedStyle.top = calcTop(triggerTop, messageHeight);
				tooltipArrowCalculatedStyle = {
					bottom: -5,
					...getArrowBottomStyleWithColor(tooltipBackgroundColor),
				};
			} else if (arrowPosition === 'BOTTOM') {
				tooltipCalculatedStyle.top = calcBottom(triggerTop, triggerHeight);
				tooltipArrowCalculatedStyle = {
					top: -5,
					...getArrowTopStyleWithColor(tooltipBackgroundColor),
				};
			} else if (isOverTop) {
				tooltipCalculatedStyle.top = calcBottom(triggerTop, triggerHeight);
				tooltipArrowCalculatedStyle = {
					top: -5,
					...getArrowTopStyleWithColor(tooltipBackgroundColor),
				};
			} else {
				tooltipCalculatedStyle.top = calcTop(triggerTop, messageHeight);
				tooltipArrowCalculatedStyle = {
					bottom: -5,
					...getArrowBottomStyleWithColor(tooltipBackgroundColor),
				};
			}

			if (isOverRight) {
				tooltipCalculatedStyle.right = ADJUSTMENT;
				tooltipArrowCalculatedStyle.right = triggerOffset.width / 2 + (messageRight - triggerRight);
				tooltipArrowCalculatedStyle.transform = 'translateX(50%)';
			} else {
				tooltipCalculatedStyle.left = tooltipLeft;
				tooltipArrowCalculatedStyle.left = triggerOffset.width / 2
					+ triggerOffset.left - tooltipLeft;
				tooltipArrowCalculatedStyle.transform = 'translateX(-50%)';
			}

			setTooltipStyle(tooltipCalculatedStyle);
			setTooltipArrowStyle(tooltipArrowCalculatedStyle);
		} else {
			setTooltipStyle({ top: -9999, left: -9999 });
			setTooltipArrowStyle({ top: -9999, left: -9999 });
		}
	}, [triggerElement, arrowPosition]);`

**Comment by SangMinL96** [comment]
"vite": "^4.1.4",

**Comment by hyrious** [comment]
If you don't want to see this warning, you can use the [log override](https://esbuild.github.io/api/#log-override) option to suppress specific kinds of messages:

```js
import { defineConfig } from 'vite'

export default defineConfig({
  esbuild: {
    logOverride: {
      'equals-negative-zero': 'silent'
    }
  }
})
```

**Comment by evanw** [comment]
Sorry, I don't understand. What's the problem? You just posted a lot of code and log messages, but it looks like esbuild is working as expected. Warnings don't stop the build and you're welcome to ignore them if you want, or you can disable them if you don't want to look at them.

**Comment by SangMinL96** [comment]

