### ISSUE TITLE
Class `name` properties have a leading underscore added to them at runtime

### ISSUE THREAD

**Issue by mattlewis92** [evanw/esbuild#3516]
The latest esbuild versions rewrite class names to add a leading underscore [like so](https://esbuild.github.io/try/#YgAwLjE5LjgALS1idW5kbGUAZQBlbnRyeS5qcwBleHBvcnQgY2xhc3MgRm9vIHsKICB0eXBlID0gRm9vLm5hbWU7Cn0) (vs in [older versions](https://esbuild.github.io/try/#YgAwLjE3LjE5AC0tYnVuZGxlAGUAZW50cnkuanMAZXhwb3J0IGNsYXNzIEZvbyB7CiAgdHlwZSA9IEZvby5uYW1lOwp9) where this behaviour wasn't present)

Unfortunately this has a side effect where the class name at runtime then has a leading underscore which our application uses for DataDog metrics reporting, so our service names show up wrong after upgrading esbuild.

Is there a way that esbuild could account for this? Perhaps by inlining any class name references at compile time so they're correct? Or an option to disable this renaming of classes?

**Comment by evanw** [comment]
I assume you are looking for the “keep names” setting: https://esbuild.github.io/api/#keep-names

**Comment by mattlewis92** [comment]
Perfect, that's exactly what we were after, it works like a charm. Thank you so much! 🙌
