### ISSUE TITLE
Docs for live reload are seemingly incorrect

### ISSUE THREAD

**Issue by Mr4k** [evanw/esbuild#3519]
Hi I tried to implement live reload for my small project by following the docs [here](https://esbuild.github.io/api/#live-reload):
currently the command given there is:  
`esbuild app.ts --bundle --outdir=www --watch --servedir=www`   
which did not seem to work for me. I needed to specify that I was also using serve mode by appending the tag `--serve`   
`esbuild app.ts --bundle --outdir=www --watch --servedir=www --serve` which worked.    

If the top command is actually wrong I'm happy to submit a quick pr to fix.

esbuild version: `0.19.7`

**Comment by evanw** [comment]
I'm unable to reproduce this. Here's what I tried:

```console
$ cat www/index.html
<!DOCTYPE html>
<script>new EventSource('/esbuild').addEventListener('change', () => location.reload())</script>
<script src="app.js"></script>

$ cat app.ts
document.write('hello')

$ esbuild app.ts --bundle --outdir=www --watch --servedir=www
```

Load http://localhost:8000/ in a browser, which shows `hello`. Change `hello` to `world` in `app.ts` and save. The browser automatically reloads and shows `world`. No `--serve` is needed, which means esbuild's documentation is correct.

Let me know if there are any additional steps required to reproduce your issue.

**Comment by Mr4k** [comment]
You are absolutely right. I have no idea why my project was having trouble before.
