### ISSUE TITLE
Include Metadata as part of BuildResult

### ISSUE THREAD

**Issue by eulores** [evanw/esbuild#352]
Can you please expose `Metadata` as part of `BuildResult`, in particular if `write` is `false`.
That would be similar to exposing `outputFiles`.

Right now I have to write out that information to disk using `metafile`, only to then read it in and parse the JSON.
Thanks!

This is related to #15 and #140.

**Comment by evanw** [comment]
`Metadata` is included as part of `BuildResult` if `write` is `false`. It's included as one of the `outputFiles`. You do not need to read it from disk. This is verified by the above commit.

**Comment by eulores** [comment]
Thanks!

**Comment by lomadurov** [comment]
@evanw but `BuildResult` doesn't contain `imports`. How can I get a list of `imports` if `write` is `false`?

**Comment by evanw** [comment]
The imports should be contained in the `metafile`. This is the format of the data, which does include `imports`:

https://github.com/evanw/esbuild/blob/36343c2911c5baf79a641f88244fbe9011d5b58d/lib/types.ts#L100-L123
