### ISSUE TITLE
Setting a window/globalThis property causes a mangle conflict

### ISSUE THREAD

**Issue by knaccc** [evanw/esbuild#3533]
If a global variable is set using `globalThis.varname` or `window.varname` instead of as `let varname`, then functions will have a naming clash after mangling is performed.

In the example below, one.js successfully prints `hello` when mangled. However, two.js results in a global scope naming clash, causing the `sayHello` function to be overwritten by the number `4`, and causing the mangled version to fail with the error `Uncaught TypeError: l is not a function`

I assume the solution would be to consider anything set on `window/self/globalThis` to be in global scope.

Thanks for your incredible work, esbuild is great.

one.js:

```javascript
function sayHello() {
  console.log('hello')
}

let myvar = 4;

sayHello();
```

one.min.js:
```javascript
function l(){console.log("hello")}let o=4;l();
```

two.js:

```javascript
function sayHello() {
  console.log('hello')
}

window.myvar = 4;

sayHello();
```

two.min.js:
```javascript
function l(){console.log("hello")}window.l=4,l();
```

Both are mangled using the following command:

```bash
esbuild --minify --format=esm --mangle-props="myvar" one.js
```

**Comment by evanw** [comment]
From [the documentation about `--format=esm`](https://esbuild.github.io/api/#format-esm):

> The `esm` format can be used either in the browser or in node, but you have to explicitly load it as a module. This happens automatically if you `import` it from another module. Otherwise:
>
> * In the browser, you can load a module using `<script src="file.js" type="module"></script>`.
>
> * In node, you can load a module using `node --experimental-modules file.mjs`. Note that node requires the `.mjs` extension unless you have configured `"type": "module"` in your `package.json` file. You can use the [out extension](https://esbuild.github.io/api/#out-extension) setting in esbuild to customize the output extension for the files esbuild generates. You can read more about using ECMAScript modules in node [here](https://nodejs.org/api/esm.html).

It sounds like you aren't following the documentation because each ES module has its own local scope. If your code was run as an ES module then `window.l` wouldn't be able to overwrite `function l(){}` in another module.

**Comment by knaccc** [comment]
Aha, thanks, I understand now. I was using format=esm because I am not using modules and wanted my functions in global scope.

The easy workaround is to just declare the global variables using `let`.

Thanks again for your help.
