### ISSUE TITLE
Module dynamic imported from cjs output has unexpected exports.

### ISSUE THREAD

**Issue by chenjun1011** [evanw/esbuild#3544]
Minimal repro:

```js
// a.js
exports.createElement = function() {
  console.log('createElement')
}

// index.mjs
import { createElement } from './a';

export async function renderToHTML(requestContext) {
  createElement();
}
```

Esbuild config:

```js
import * as esbuild from 'esbuild'

await esbuild.build({
  entryPoints: ['index.mjs'],
  bundle: true,
  outfile: 'bundle.js',
  target: 'node12.20.0',
  format: 'cjs'
});
```

Outputted bundle.js:

```js
// ...

// a.js
var require_a = __commonJS({
  "a.js"(exports) {
    exports.createElement = function() {
      console.log("createElement");
    };
  }
});

// index.mjs
var esbuild_demo_exports = {};
__export(esbuild_demo_exports, {
  renderToHTML: () => renderToHTML
});
module.exports = __toCommonJS(esbuild_demo_exports);
var import_a = __toESM(require_a(), 1);
async function renderToHTML(requestContext) {
  (0, import_a.createElement)();
}
```

When use 'import()' to dynamic load bundle.js

```js
const mod = await import('./bundle.js');
console.log('mod=>', mod);
```

The module loaded has an unexpected export `createElement`.

<img width="330" alt="image" src="https://github.com/evanw/esbuild/assets/1303018/29f839b8-3acd-49ce-8034-c615059d948b">

It seems although the `exports` passed to the module `a` are not node.js's native `exports`, it still changed the native exports. This maybe a bug in dynamic import.(The problem only occurs in the case of dynamic import)

![image](https://github.com/evanw/esbuild/assets/1303018/252ba8ed-80f8-4b2a-88a9-dec4ca10f4ce)

If esbuild can avoid the keyword `exports`  in `__commonJS` function, or provide some overriding configuration
, may solved this problem.

**Comment by evanw** [comment]
This is a bug in node. Node is trying to guess at what exports the module has and it's guessing wrong. If I rename `exports` to `not_exports` then the bug isn't triggered. Node isn't doing the correct scope analysis to determine whether `exports` is from the top-level module or a nested module. It just makes up an export called `foo` if it finds an assignment to `exports.foo` anywhere in the source code, even if `exports` is a local variable. I can try to have esbuild avoid naming variables `exports` when targeting node to work around this bug in node.
