### ISSUE TITLE
Dynamic Import JSON not working

### ISSUE THREAD

**Issue by ad1992** [evanw/esbuild#3557]
Hi I am trying to using ESBuild for creating the ESM build of Excalidraw. However dynamic import json doesn't seem to work even though its mention in docs (The support for `with` was released in [0.19.7](https://github.com/evanw/esbuild/releases/tag/v0.19.7)

```
const  currentLangData = await import(`./locales/${currentLang.code}.json`, {
    with: { type: "json" },
  });
 ```
 This gets converted to 👇🏻 
 ```
  currentLangData = await globImport_locales_json(`./locales/${currentLang.code}.json`);
  ```

 This code throws error -> "chunk-EGAXOKDI.js:7443 Failed to load language en: globImport_locales_json is not defined" .
 
 **EDIT**
 
However, If I hardcode the string path then it works, so probably the root cause is the path is dynamic and that's why its not working.
 
 Is there anything I am missing to make Dynamic Import JSON work with dynamic paths ?
 
 Thank you!

**Comment by evanw** [comment]
Thank you for the report. I'm hoping that this was #3319, which was just fixed. Please update esbuild and try again.

If that didn't fix it, then I'm going to need a way to reproduce your issue as I unfortunately am not able to fix your issue without a way to reproduce it. Please provide a way for me to reproduce your issue.

**Comment by ad1992** [comment]
@evanw you are awesome, Thanks for releasing the fix so quickly. It works now 🚀
