### ISSUE TITLE
Classes with iterators are not tree-shaken

### ISSUE THREAD

**Issue by devongovett** [evanw/esbuild#3561]
When a class includes an iterator method using `Symbol.iterator`, it is no longer tree-shaken when unused.

```js
(() => {
  class Test {
    *[Symbol.iterator]() {
      // do nothing
    }
  }
})()
```

[Example](https://esbuild.github.io/try/#dAAwLjE5LjEwAC0tbWluaWZ5ACgoKSA9PiB7CiAgY2xhc3MgVGVzdCB7CiAgICAqW1N5bWJvbC5pdGVyYXRvcl0oKSB7CiAgICAgIC8vIGRvIG5vdGhpbmcKICAgIH0KICB9Cn0pKCk)

If you change this to `*foo` (still a generator function), or a non-generator with a static identifier as a name, it is tree-shaken. I believe this should be safe to tree shake with `Symbol.iterator` as well. SWC's minifier does so.

**Comment by evanw** [comment]
Thanks for pointing this out. That’s obviously not great, and should be safe to do.
