### ISSUE TITLE
I'm puzzled about the empty contents of on-load-results.

### ISSUE THREAD

**Issue by lidenggao** [evanw/esbuild#3564]
https://esbuild.github.io/plugins/#on-load-results
Set this to a string to specify the contents of the module. If this is set, no more on-load callbacks will be run for this resolved path. If this is not set, esbuild will continue to run on-load callbacks that were registered after the current one. Then, if the contents are still not set, esbuild will default to loading the contents from the file system if the resolved path is in the namespace. file

So, I wrote such a plugin. 
I think the console should output 1 and 2, and finally complete normally. 
```js
setup(build) {
        build.onResolve({
          filter: /.*/
        },async args=>{
          return {
            path: resolve(__dirname, args.path)+'.ts',
            namespace: 'xxx'
          }
        })
        build.onLoad({
          filter: /.*/,
          namespace: 'xxx'
        }, async args=>{
          console.log(1)
          return {}
        });
        build.onLoad({
          filter: /.*/,
          namespace: 'xxx'
        }, async args=>{
          console.log(2)
          return {}
        });
      }
```

But in fact, I get 1 and an error
 Do not know how to load path: xxx:E:\coding\@iuijs\specs\cli\data\file.ts

Am I wrong in my understanding?

esbuild version: 0.19.10

**Comment by evanw** [comment]
That's correct. Only modules in the `file` namespace will load from the file system if you are relying on esbuild's built-in loader.

I'm closing this issue as it's not a problem with esbuild.
