### ISSUE TITLE
Can esbuild bundle in fetch call responses?

### ISSUE THREAD

**Issue by Pomax** [evanw/esbuild#3565]
I may be missing it in the docs, but is it possible for `esbuild` to replace code like this:

```js
const response = await fetch(`./some/local/file`);
const fileContent = await response.text();
```
by just putting the file content "whatever it is when `esbuild` runs" as hardcoded string in the bundle?

**Comment by evanw** [comment]
It's not really possible. The only expression-level bundling entry points are `require(<string>)` and `import(<string>)`. You could do a hack such as bundling once with `fetch` substituted with a custom function that records its arguments somewhere, running the bundle and recording all of the fetches, and then bundling again with `fetch` substituted with another custom function that contains the hard-coded strings from the first step. But there's nothing built-in to handle something like that.

**Comment by Pomax** [comment]
no worries. I can always write a quick a dirty "replace this exact string that I know my code uses". Thanks (and merry christmas/happy new year)
