### ISSUE TITLE
Esbuild-wasm in NextJs Context (Client)

### ISSUE THREAD

**Issue by kaimou1357** [evanw/esbuild#3566]
I'm currently using esbuild-wasm in my React frontend app. I've been converting it to a Next.JS app and am having trouble getting esbuild-wasm working since it keeps complaining that

`Error: The "wasmURL" option only works in the browser
`
This used to work when I was on create-react-app but now with next-js I'm assuming it's in the Node context and no longer works.

I'd like to convert react code from jsx -> pure JS and I'm wondering if there is a better way to do so?

The basic context here is that I am looking to dynamically transform the code and render the transformed code in an iframe.

My setup is that I have a next_app where the esbuild.wasm is server under next_app/public.

Is there another way to do this?

**Comment by kaimou1357** [comment]
Things I've tried:

```
WebAssembly.instantiateStreaming(
    fetch('/esbuild.wasm')
  ).then((result) => esbuild.initialize({wasmModule: result}))
```

and

`esbuild.initialize(wasmUrl: "/esbuild.wasm")`

**Comment by hyrious** [comment]
This probably because Next.js has a server-side rendering (SSR) step where basically it just runs your react-components in Node.js to produce an HTML string.

To mark some piece of code that not able / necessary to run in SSR mode, you can test if a global `window` exists:

```js
if (typeof window !== 'undefined')
	esbuild.initialize({ wasmUrl: "/esbuild.wasm" })
```

**Comment by kaimou1357** [comment]
> This probably because Next.js has a server-side rendering (SSR) step where basically it just runs your react-components in Node.js to produce an HTML string.
> 
> To mark some piece of code that not able / necessary to run in SSR mode, you can test if a global `window` exists:
> 
> ```js
> if (typeof window !== 'undefined')
> 	esbuild.initialize({ wasmUrl: "/esbuild.wasm" })
> ```

So the problem is the code actually works but I cannot npm run build (build the nextjs production bundle) because of this problem.

**Comment by kaimou1357** [comment]
```
⨯ node_modules/esbuild-wasm/lib/main.js (1934:10) @ Object.initialize
 ⨯ Error: The "wasmURL" option only works in the browser
    at eval (./src/app/components/esbuildInitializer.js:8:73)
    at (ssr)/./src/app/components/esbuildInitializer.js (/Users/kaimou/Code/GenKode/next_app/.next/server/app/tool/page.js:446:1)
    at __webpack_require__ (/Users/kaimou/Code/GenKode/next_app/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/components/LiveCodeEditor.js:9:77)
    at (ssr)/./src/app/components/LiveCodeEditor.js (/Users/kaimou/Code/GenKode/next_app/.next/server/app/tool/page.js:369:1)
    at __webpack_require__ (/Users/kaimou/Code/GenKode/next_app/.next/server/webpack-runtime.js:33:42)
    at eval (./src/app/tool/page.tsx:12:84)
    at (ssr)/./src/app/tool/page.tsx (/Users/kaimou/Code/GenKode/next_app/.next/server/app/tool/page.js:512:1)
    at __webpack_require__ (/Users/kaimou/Code/GenKode/next_app/.next/server/webpack-runtime.js:33:42)
    at JSON.parse (<anonymous>)
```

**Comment by kaimou1357** [comment]
If it's no longer possible to transform code this way - are there any other suggested methods?

**Comment by hyrious** [comment]
Do you mean you cannot touch these components' code, or for other reason? Maybe Next.js has some configuration to opt-in/out server-side rendering but that needs you to dig into its document by yourself.

Anyway, this is not a problem with esbuild.

**Comment by evanw** [comment]
I'm marking this as `unactionable` because the issue reporting instructions were not followed. Specifically you did not provide a way to reproduce the issue.

**Comment by kaimou1357** [comment]
> This probably because Next.js has a server-side rendering (SSR) step where basically it just runs your react-components in Node.js to produce an HTML string.
> 
> To mark some piece of code that not able / necessary to run in SSR mode, you can test if a global `window` exists:
> 
> ```js
> if (typeof window !== 'undefined')
> 	esbuild.initialize({ wasmUrl: "/esbuild.wasm" })
> ```

So I tried this and this seemed to allow a build. I'll close this issue.
