### ISSUE TITLE
suggestion: add statistics output

### ISSUE THREAD

**Issue by vladmandic** [evanw/esbuild#357]
As title says, suggestion to add ESBuild stats output to `.build()` method output.
Currently it returns warnings and errors objects

For example, I use ESBuild in parallel with CleanCSS (https://www.npmjs.com/package/clean-css) which returns

```js
errors: [],
warnings: [],
stats: { efficiency: 0.1811044589564067, minifiedSize: 452059, originalSize: 552035, timeSpent: 3986 }
```

**Comment by evanw** [comment]
Statistics about the input and output files are available using the `metafile` option, which generates a JSON file containing all of the information. Usually code that is measuring run time for benchmark purposes will do its own measurements to make sure to capture end-to-end time. Including time information in the metafile could potentially be inaccurate.

**Comment by vladmandic** [comment]
thanks, works like a charm!

```js
async function buildStats() {
  const stats = { modules: 0, moduleBytes: 0, imports: 0, importBytes: 0, outputs: 0, outputBytes: 0, outputFiles: [] };
  if (!fs.existsSync(metafile)) return stats;
  const data = fs.readFileSync(metafile);
  const json = JSON.parse(data);
  if (json && json.inputs && json.outputs) {
    for (const [key, val] of Object.entries(json.inputs)) {
      if (key.startsWith('node_modules')) {
        stats.modules += 1;
        stats.moduleBytes += val.bytes;
      } else {
        stats.imports += 1;
        stats.importBytes += val.bytes;
      }
    }
    for (const [key, val] of Object.entries(json.outputs)) {
      if (!key.endsWith('.map')) {
        stats.outputs += 1;
        stats.outputFiles.push(key);
        stats.outputBytes += val.bytes;
      }
    }
  }
  return stats;
}
```

(plus a wrapper around build to measure time).
