### ISSUE TITLE
Allow modules resolve to multiple loaders

### ISSUE THREAD

**Issue by trapgar** [evanw/esbuild#3575]
I have a react app that references `.svg` files both in `.scss` and `.tsx` files.

```tsx
import { ReactComponent as ImgSupplier } from 'assets/images/my-image.svg';
```

```scss
.my-class {
    background-image: url('/assets/images/my-image.svg');
}
```

I created the below plugin that based on my understanding of the docs *should* work, but I get an error stating `ERROR: Could not resolve "/assets/images/my-image.svg"` for the SCSS file.

Setting breakpoints shows that the loader for the `{ namespace: 'svgr' }` is never called. I've tried all manner of tweaks to the plugin, but the root cause appears to be that the imported modules _always_ appear to be coded to a **single** loader, without any way of specifying that different loaders should be used based on how the module/resource is imported.

```js
{
        name: 'svg-resolver',
        setup(build) {
            build.onResolve({ filter: /\.svg$/ }, async args => {
                switch (args.kind) {
                    // these should be resolved like ES6 modules
                    case 'import-statement':
                    case 'require-call':
                    case 'dynamic-import':
                    case 'require-resolve':
                        return { external: true, namespace: 'svgr' };
                    // anything else falls back on the default (file) loader
                    default:
                        return;
                }
            });

            build.onLoad({ filter: /\.svg$/, namespace: 'svgr' }, async (args) => {
                const fn = args.path.split('\\').at(-1);
                const svg = await read(args.path, { encoding: 'utf8' });
                const sanitized = svg.match(/<svg[^]+?<\/svg>/)?.[0];

                if (!sanitized)
                    return { errors: [{ pluginName: 'svgr', location: args.path, text: `${fn} is not a valid svg.` }] };

                const fname = `Svg${getClassNameFromFileName(fn)}`;
                const base64 = btoa(sanitized);
                const contents =
`function ${fname}(props) {
    return (
        <img src="data:image/svg+xml;base64,${base64}" {...props} />
    );
}

export { ${fname} as ReactComponent };

export default \`data:image/svg+xml;base64,${base64}\`;
`;

                return {
                    contents,
                    loader: 'tsx'
                };
            });
        }
    }
```

If this is supported by esbuild, please update the docs with an example as it is not at all obvious.

**Comment by evanw** [comment]
It's definitely possible to allow modules to resolve to multiple loaders. That's exactly what the [WebAssembly example plugin](https://esbuild.github.io/plugins/#webassembly-plugin) does. Your problems are due to the way your code works.

> ```tsx
> import { ReactComponent as ImgSupplier } from 'assets/images/my-image.svg';
> ```

For this one, you are passing `external: true` to esbuild. That tells esbuild to exclude that import path from the bundle (i.e. it will be loaded at run-time, not at compile-time). That is already documented [here](https://esbuild.github.io/api/#external). That's why your `onLoad` callback isn't running at compile-time. If you wanted that path to be internal to the bundle then you shouldn't be setting `external: true` for that path.

> ```css-scss
> .my-class {
>     background-image: url('/assets/images/my-image.svg');
> }
> ```

For this one, your code is deliberately falling back to esbuild's default behavior (the part of your code that says `anything else falls back on the default (file) loader`). The default file loader takes the path and reads it from the file system. I'm guessing there is no file present at the absolute path `/assets/images/my-image.svg`, which is why esbuild is saying `Could not resolve "/assets/images/my-image.svg"`. That is not a problem with esbuild. Perhaps you meant to use a relative path instead? Relative paths start with `./` while absolute paths start with `/`.

**Comment by trapgar** [comment]
Thanks, that pointed me in the right direction. For posterity the final code looked like below:

```js
const { readFile: read } = require('node:fs/promises');
const path = require('node:path');

const JS_IMPORTS = ['import-statement', 'require-call', 'dynamic-import', 'require-resolve'];

/** Converts `my-image.svg` to `MyImage` */
const filename = fn => {
    return `${fn.split('-').map(s => `${s[0].toUpperCase()}${s.substring(1)}`).join('')}`.replace(/\.svg$/, '').replace(/^(\d)/, '_$1');
};

/**
 * esbuild plugin that converts SVG files to import-able ES modules.
 * @param {{}} options
 * @returns {import('esbuild').Plugin}
 */
module.exports = (options = {}) => {
    return {
        name: 'svg-resolver',
        setup(build) {
            build.onResolve({ filter: /\.svg$/ }, async args => {
                if (args.namespace !== 'svg-component' && JS_IMPORTS.includes(args.kind))
                    return { path: path.join(process.cwd(), 'src', args.path), namespace: 'svg-component' };
                else if (!args.path.startsWith(path.join(process.cwd(), 'src')))
                    return { path: path.join(process.cwd(), 'src', args.path), namespace: 'file' };
                else
                    return { path: args.path, namespace: 'file' };
            });

            build.onLoad({ filter: /.*/, namespace: 'svg-component' }, async (args) => {
                const fn = args.path.split('\\').at(-1);

                const fname = `Svg${filename(fn)}`;
                const contents =
`import React from 'react';
import contents from ${JSON.stringify(args.path)};

function ${fname}(props) {
    return (
        <img src={contents} {...props} />
    );
}

export { ${fname} as ReactComponent };

export default contents;
`;

                return {
                    contents,
                    loader: 'jsx',
                    resolveDir: process.cwd()
                };
            });

            build.onLoad({ filter: /.*/, namespace: 'svg-file' }, async (args) => {
                const fn = args.path;
                const svg = await read(args.path, { encoding: 'utf8' });
                const sanitized = svg.match(/<svg[^]+?<\/svg>/)?.[0];

                if (!sanitized)
                    return { errors: [{ pluginName: 'svgr', location: args.path, text: `${fn} is not a valid svg.` }] };

                return { contents: sanitized, loader: 'file' };
            });
        }
    };
};
```

My intention was to make this as close as possible to the `react-scripts` implementation, so it has an implicit root directory of `'src'`.
