### ISSUE TITLE
Do I really need Rollup and esbuild?

### ISSUE THREAD

**Issue by guest271314** [evanw/esbuild#3578]
I'm using esbuild to bundle a TypeScript file to JavaScript. I am using Rollup to generate a file. Can one or the other be used for both actions?

```
await esbuild.build({
  entryPoints: ["src/index.ts"],
  platform: "node",
  outfile: dynamicImport,
  format: "esm",
  packages: "external",
  legalComments: "inline",
  sourcemap: true,
  bundle: true,
  keepNames: true,
  allowOverwrite: true
});
```

```
const bundle = await rollup.rollup({
  input: "./src/script.js",
  plugins: [
    // ...
  ],
});
```

**Comment by evanw** [comment]
It's up to you? It really depends on what you're using Rollup for.

I'm closing this issue because it does not represent a work item for esbuild.

**Comment by guest271314** [comment]
FWIW I wound up dropping Rollup as a dependency, and using esbuild to bundle, once, or dynamically https://github.com/guest271314/webbundle.
