### ISSUE TITLE
warning: The "typeof" operator will never evaluate to "null"

### ISSUE THREAD

**Issue by ngbinh** [evanw/esbuild#358]
I updated esbuild to the `0.6.28` from `0.6.23` and it breaks my build on project that depends on https://www.npmjs.com/package/tabulator-tables with a warning:

```
 npx esbuild doctable-fastopt.js --bundle --strict --platform=browser --target=es2015 --outfile=doctable-fastopt-bundle.js --log-level=info --define:process.env.NODE_ENV="development" --define:process.cwd=String --define:process.platform=String --define:process=String --external:process
node_modules/tabulator-tables/dist/js/tabulator.js:13581:76: warning: The "typeof" operator will never evaluate to "null"
                headers[i] = typeof col.value == "undefined" || typeof col.value == "null" ? "" : col.value;
                                                                                    ~~~~~~

```

**Comment by evanw** [comment]
This is just a warning. Nothing is broken. Warnings just inform you about things but don't cause the build to fail. The build still succeeds as long as there are no errors.

This particular warning is warning you about nonsensical code in that library. If you don't want to see that warning, you could either reach out to the author of that package to tell them to fix their nonsensical code, or just pass `--log-level=error` to esbuild to disable the logging of warnings.

**Comment by ngbinh** [comment]
Yes. I think you are right. Close for now
