### ISSUE TITLE
IIFE Parameter Support?

### ISSUE THREAD

**Issue by joshstoik1** [evanw/esbuild#3591]
Does the esbuild CLI provide a way to specify parameters for its IIFE closures, like:

```js
((currentScript)=>{
    …
})(document.currentScript);
```

With terser, for example, this could be accomplished via:

```bash
terser --enclose currentScript:document.currentScript …
```

Thanks!

**Comment by evanw** [comment]
Sorry, I don't understand. You can trivially use a variable for this in your code instead:

```js
var currentScript = document.currentScript;
```

So this feature is not necessary.

**Comment by joshstoik1** [comment]
Thanks for clarifying @evanw!
