### ISSUE TITLE
settings / plugins for wrapped (lazyload) required in nodejs

### ISSUE THREAD

**Issue by xpr0gamers** [evanw/esbuild#3592]
Hello everyone, 

is there a way via settings or a custom plugin, to handle wrapped requires? 
I use a npm package who have this coding:
![image](https://github.com/evanw/esbuild/assets/25172624/8de605b5-41ad-4916-b165-9361db6c30fc)

The implemantation of the function "lazyload" looks like this:
![image](https://github.com/evanw/esbuild/assets/25172624/9198da67-8b6b-4dd0-94ee-d35ffc29b9f1)

Thanks.

**Comment by hyrious** [comment]
One possible way is to rewrite these `lazyLoad('path')` to `lazyLoad(() => require('path'))`. The later form can be statically analyzed by esbuild to make it able to bundle the file pointed by 'path'. You can do the rewrite using [plugins](https://esbuild.github.io/plugins/).

On the other hand, many Node.js packages are not written in a bundler-friendly way where they may use [non-analyzable imports](https://esbuild.github.io/api/#non-analyzable-imports) and other code patterns. In which case I would just recommend you to externalize them using [`--packages=external`](https://esbuild.github.io/api/#packages).
