### ISSUE TITLE
tsconfigRaw not available on JS `build` API as touted by the docs

### ISSUE THREAD

**Issue by gabrielmfern** [evanw/esbuild#3594]
I'm trying to get a few options to override certain values of the local tsconfig, but I'm not able to do it
through a file as I need to change it and the point of build and it would be more reliable to have the `tsconfigRaw` option.
I'm using `build` not `transform` though so I can't find it, I thought it might be a missing TS definition
but it errors if I try to force passing the option into it.

The docs for this https://esbuild.github.io/api/#tsconfig-raw touts that this can be used with `build` but I can't manage to use it. Is not supported by build or is this option missing from the JS API?

**Comment by evanw** [comment]
[It seems to work fine for me.](https://esbuild.github.io/try/#YgAwLjE5LjExAHsKICB0c2NvbmZpZ1JhdzogewogICAgY29tcGlsZXJPcHRpb25zOiB7CiAgICAgIGpzeEZhY3Rvcnk6ICd3b3JrcycKICAgIH0KICB9Cn0AZQBlbnRyeS50c3gAPGRpdi8+) Please provide a way to reproduce your issue. Marking this as `unactionable` for now.

**Comment by gabrielmfern** [comment]
@evanw Apparently I was using an older version that didn't have support for it, specifically `0.16.4`. Thanks for the quick response!
