### ISSUE TITLE
running JavaScript functions at bundle-time

### ISSUE THREAD

**Issue by sirenkovladd** [evanw/esbuild#3596]
Is there a way to execute a function at bundle time and write to some variable

get-version.macros.js
```js
export async fucntion getVersion() {
  const version = await readFile("./assert/version", "utf8")
  const versionX = await readFile("./assert/version-x", "utf8")
  return { version, versionX }
}
```

index.js
```js
import { getVersion } from './get-version.macros.js'

const v = await getVersion()
document.body.appendChild(`version ${v.version}, version X: ${v.versionX}`)
```

build.js
```js
const result = await build({
    entryPoints: templates.map(t => `./index.js`),
    bundle: true,
    // ?
  });
```

result
```js
const v = {version: '1', versionX: '2'}
document.body.appendChild(`version ${v.version}, version X: ${v.versionX}`)
```

**Comment by sirenkovladd** [comment]
I'm not sure what does the `Inject` but it seems to just copy the code (without execution)
`Define` looks like what I need but as far as I can see it is only used for string

I'm looking for a solution like https://bun.sh/docs/bundler/macros

**Comment by evanw** [comment]
> Is there a way to execute a function at bundle time and write to some variable

The way to do this with esbuild is with a plugin: https://esbuild.github.io/plugins/. The top of the documentation page for plugins has an example for how to do this very thing (importing from a path that runs some code at bundle-time to generate code): https://esbuild.github.io/plugins/#using-plugins.

> get-version.macros.js
> 
> ```js
> export async fucntion getVersion() {
>   const version = await readFile("./assert/version", "utf8")
>   const versionX = await readFile("./assert/version-x", "utf8")
>   return { version, versionX }
> }
> ```
> 
> index.js
> 
> ```js
> import { getVersion } from './get-version.macros.js'
> ```

In case it helps: this particular thing doesn't necessarily need any code at all if you can associate loaders with file extensions. I realize that this isn't exactly what you're asking for. But just so you know, esbuild has a built-in [`text` loader](https://esbuild.github.io/content-types/#text) that can load a file as a string. For example (you can also map file extensions other than `.txt` to the `text` loader):

```js
import version from './assert/version.txt'
import versionX from './assert/version-x.txt'
```

> I'm looking for a solution like https://bun.sh/docs/bundler/macros

If you want that exact solution, then why aren't you using it? AFAIK Bun is free to use and has a built-in bundler. Bun is also a JavaScript runtime which makes it much more natural for it to do this kind of thing. Becoming a JavaScript runtime is outside of esbuild's scope.

**Comment by sirenkovladd** [comment]
Got it thanks, just used a plugin to fix it, just had a feeling there was a built-in way to solve it.
thank you for the detailed answer
