### ISSUE TITLE
Please give me tips how to solve router plain javascript app

### ISSUE THREAD

**Issue by lukaszkaleta** [evanw/esbuild#3614]
Hi 
I am having issue with using router and page refresh (browser F5)

Application is server on:

http://0.0.0.0:8001

Withing app I have setup router (@vaadin/router) which has following routes:

http://0.0.0.0:8001/ -> F5 does work OK 
http://0.0.0.0:8001/unit -> F5 does work OK -> component i-unit-view is shown
http://0.0.0.0:8001/unit/dashboard -> F5 does NOT work -> empty page and error in console:

_Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec._

but then I use router programaticly:
`Router.go(/unit/dashboard)`
url changes to http://0.0.0.0:8001/unit/dashboard and i-dashboard-view page is shown

Here is router config:
`    {
      path: '/unit',
      children: [
        {
          path: '/',
          component: 'i-unit-view'
        },
        {
          path: '/dashboard',
          children: [
            {
              path: '/',
              component: 'i-dashboard-view',
            }
          ]
        }
      ]
    }`

Here is mine esbuild script:

`import * as esbuild from 'esbuild';

let ctx;

try {
  ctx = await esbuild.context({
    entryPoints: ['src/app.js'],
    bundle: true,
    minify: false,
    sourcemap: true,
    outfile: 'public/bundle.js',
    define: {
      'process.env.NODE_ENV': "'development'"
    }
  });

  await ctx.watch();
  console.log('Watching customer portal...');

  const { host, port } = await ctx.serve({
    servedir: 'public',
    fallback: 'public/index.html'
  });

  console.info(`Hot refresh at http://${host}:${port}`);
} catch (error) {
  console.error('An error occurred:', error);
  process.exit(1);
}
`

I will appreciate any help.

**Comment by hyrious** [comment]
How did you reference the bundle.js file in index.html? The correct one should be like this:

```html
<script src="/bundle.js"></script>
```

Notice the prefix `/`. When you're at `{domain}/unit/dashboard`, `bundle.js` or `./bundle.js` points to `{domain}/unit/bundle.js` which does not exist and esbuild fallbacks to return the index.html. That's probably why you get a `text/html` response for the script.

**Comment by lukaszkaleta** [comment]
@hyrious thank you .. it solves the issue
