### ISSUE TITLE
How to get final version of build.initialOptions inside a plugin?

### ISSUE THREAD

**Issue by koshic** [evanw/esbuild#3615]
My use case: I'm an author of `pluginA` and I have to rely on some esbuild options to provide consistent output (as an example, `absWorkingDir` value affects source maps generation, `entrypoints` style affects metafile analysis, etc.).

Obvious and well documented solution is to use https://esbuild.github.io/plugins/#build-options. But, those options can be mutated by other plugins, so in the following setup `build.initialOptions` available inside `pluginA` is... incorrect:
```js
plugins: [
  pluginA(),
  pluginB() // hahaha, absWorkingDir will be changed 👿 
]
```

Changing the order can help only in limited situations: what if plugin count > 2 (5, 10, 20...)? What if `pluginB` also need actual settings which can mutated by `pluginA`? It looks like a circular dependency. 

Is it possible to get actual options now? Or it's need to add something like `build.getFinalOptions()`to the API?

**Comment by evanw** [comment]
I'm confused. Can't you just access `build.initialOptions` in your plugin? Something like this:

```js
const esbuild = require('esbuild')

const pluginA = () => ({
  name: 'pluginA',
  setup(build) {
    build.onStart(() => {
      console.log(build.initialOptions)
    })
  }
})

const pluginB = () => ({
  name: 'pluginB',
  setup(build) {
    build.initialOptions.absWorkingDir = '/'
  }
})

esbuild.build({
  plugins: [
    pluginA(),
    pluginB() // hahaha, absWorkingDir will be changed 👿
  ]
})
```

You just need to wait until setup is complete. One way to do that is with [`onStart`](https://esbuild.github.io/plugins/#on-start). I suppose it could be a problem if some plugin continues to mutate `build.initialOptions` over time. But esbuild doesn't attempt to defend against plugins that are actively trying to break things.

**Comment by koshic** [comment]
> Can't you just access `build.initialOptions` in your plugin?

Yeah, it works. Sorry for such stupid issue, I though that 'build' object is not shared 'as is' for all plugins :-/

> I suppose it could be a problem if some plugin continues to mutate `build.initialOptions` over time.

For me it's a 'broken' plugin should be fixed / replaced so that's is not an issue.

And thank you for warm, prompt answer and such beautiful tool!
