### ISSUE TITLE
How to add success log to watch ?

### ISSUE THREAD

**Issue by lukaszkaleta** [evanw/esbuild#3617]
Hi

During development I can see some javascript errors in the console from esbuild, but when I finish feature and all is compiled correcrectly I would like to see some message that now essbuild finish sucessfully .. but I do see still old error which was fixed few minutes ago .. this is missleading for me as I not sure if this old error or new one

![image](https://github.com/evanw/esbuild/assets/8665009/f3207fb6-c3e9-4cf4-86bc-fbe318adecd8)

This is mine config script

`//
// Run this script during developing customer portal application
//
import * as esbuild from 'esbuild';

let ctx;

try {
  ctx = await esbuild.context({
    entryPoints: ['src/app.js'],
    bundle: true,
    minify: false,
    sourcemap: true,
    outfile: 'public/bundle.js',
    define: {
      'process.env.NODE_ENV': "'development'"
    }
  });

  await ctx.watch();
  console.log('Watching customer portal...');

  const { host, port } = await ctx.serve({
    servedir: 'public',
    fallback: 'public/index.html'
  });

  console.info(`Hot refresh at http://${host}:${port}`);

  console.info(`Hot refresh at http://localhost:${port}/unit/1221/projects/639146352/periodic-control/controls/dashboard`);
} catch (error) {
  console.error('An error occurred:', error);
  process.exit(1);
}
`

Any tips are appriacited.
Maybe I can add some callback to watch ?

**Comment by hyrious** [comment]
You can use the [on-end](https://esbuild.github.io/plugins/#on-end) callbacks and see if the `errors` field is an empty array.
Example:

https://github.com/hyrious/esbuild-repl/blob/56312a6/scripts/plugins/svelte-ssr.ts#L117-L141

**Comment by lukaszkaleta** [comment]
@hyrious Thank you .. I have solved it as you suggested :)

Here is mine config after applying changes:

`import * as esbuild from 'esbuild';

let ctx;

let watchPlugin = {
  name: 'watch-plugin',
  setup(build) {
    build.onEnd(result => {
      console.log(`build ended with ${result.errors.length} errors`)
    })
  },
}

try {
  ctx = await esbuild.context({
    entryPoints: ['src/app.js'],
    bundle: true,
    minify: false,
    sourcemap: true,
    outfile: 'public/bundle.js',
    define: {
      'process.env.NODE_ENV': "'development'"
    },
    plugins: [watchPlugin],
  });

  await ctx.watch();
  console.log('Watching customer portal...');

  const { host, port } = await ctx.serve({
    servedir: 'public',
    fallback: 'public/index.html'
  });

  console.info(`Hot refresh at http://${host}:${port}`);

  console.info(`Hot refresh at http://localhost:${port}/unit/1221/projects/639146352/periodic-control/controls/dashboard`);
} catch (error) {
  console.error('An error occurred:', error);
  process.exit(1);
}
`
