### ISSUE TITLE
Feature Request: Allow absolute paths for resolved chunks

### ISSUE THREAD

**Issue by EloB** [evanw/esbuild#3621]
I'm using esbuild for AWS lambda development. I'm trying to split chunks into a layer. I would like the `splitting: true` to put the chunk in a separate folder like  `chunkNames: "MyLayer/[name]"` but the problem is my bundle will resolve like this.
```js
require("./MyLayer/something.js");
```

I want it to resolve like this (necessary for AWS lambda layer).
```js
require("/opt/nodejs/something.js");
```

I've tried to make it possible with a plugin but wasn't able todo it.

# Example
```js
exports.handler = async () => {
  if (condition) {
    const { doSomething } = await import("./something");
    doSomething();
  }
  // ...
};
```

**Comment by evanw** [comment]
Did you try using the [public path](https://esbuild.github.io/api/#public-path) setting for that? Something like [this](https://esbuild.github.io/try/#YgAwLjIwLjAALS1zcGxpdHRpbmcgLS1mb3JtYXQ9ZXNtIC0tb3V0ZGlyPS4gLS1idW5kbGUgLS1wdWJsaWMtcGF0aD0vb3B0L25vZGVqcwBlAC9ob21lL3VzZXIvcHJvamVjdC9lbnRyeS5qcwBleHBvcnRzLmhhbmRsZXIgPSBhc3luYyAoKSA9PiB7CiAgaWYgKGNvbmRpdGlvbikgewogICAgY29uc3QgeyBkb1NvbWV0aGluZyB9ID0gYXdhaXQgaW1wb3J0KCIuL3NvbWV0aGluZyIpOwogICAgZG9Tb21ldGhpbmcoKTsKICB9CiAgLy8gLi4uCn07AAAvaG9tZS91c2VyL3Byb2plY3Qvc29tZXRoaW5nLmpzAA).

**Comment by EloB** [comment]
Thanks for your reply and that might work. I have to test it. :)

**Comment by EloB** [comment]
@evanw That worked. :)
