### ISSUE TITLE
Glob pattern for `copy` file loader

### ISSUE THREAD

**Issue by Mqxx** [evanw/esbuild#3624]
Hey, I currently use ESBuild as part as a way to copy specific files from my `src` to my `dist` folder. My current config looks like this:

```ts
const copyConfig : esbuild.BuildOptions = {
  allowOverwrite: true,
  logLevel: args.logLevel ?? 'info',
  color: true,
  outdir: './dist',
  loader: {
    '.html': 'copy',
    '.svg': 'copy',
    '.png': 'copy',
    '.ico': 'copy',
  },
  entryPoints: [
    './src/**/index.html',
    './src/**/_assets/**'
  ]
}
```

Is there a way to set a loader for all file types for this config? I would like to be able to copy entire contents of a directory reguardless of the file extension. Currently I need to specify every file extension in the loader object to `copy`.

**Comment by evanw** [comment]
Node already has an API to copy a directory tree: https://nodejs.org/api/fs.html#fscpsrc-dest-options-callback. I believe it's called `fs.cp` and it has a `recursive` flag. Maybe that helps?

You could also try using an esbuild plugin for that. Here is the API reference: https://esbuild.github.io/plugins/#on-load. You should be able to use a plugin to set the loader based on the directory.

**Comment by Mqxx** [comment]
Okay thanks for the response. 👍🏻
