### ISSUE TITLE
punycode should be 'external' but bundled ?

### ISSUE THREAD

**Issue by MarcWeber** [evanw/esbuild#3626]
See https://nodejs.org/api/punycode.html. It's deprecated and the recommended way to use it is using https://www.npmjs.com/package/punycode.

So looks like there should be 3 options in the future:
- use from node (eg the :true value from esbuild's list of node modules)
- use external but bundle (the new option which would fix this issue)
- use external and don't bundle (the existing --external:X flag)

So I see 2 ways to trigger such feature: --external-but-bundle:X  or the internal list BuiltInNodeModules allowing 'external-but-bundle' in addition to existing bool values ?

This could be ralted: https://github.com/evanw/esbuild/issues/346

So even if I am mistaken this issue will be found by Google and help future users to resolve this fast or stay up to date.

**Comment by evanw** [comment]
The intent behind esbuild's resolver is to behave the same way as node itself. Here is an example:

https://esbuild.github.io/try/#YgAwLjIwLjAALS1idW5kbGUgLS1wbGF0Zm9ybT1ub2RlAGUAL3Byb2plY3QvZW50cnkuanMAY29uc3Qgbm9kZVB1bnljb2RlID0gcmVxdWlyZSgncHVueWNvZGUnKTsKY29uc3QgaW50ZXJuYWxQdW55Y29kZSA9IHJlcXVpcmUoJ3B1bnljb2RlLycpOwAAL3Byb2plY3Qvbm9kZV9tb2R1bGVzL3B1bnljb2RlL2luZGV4LmpzAA

If you import from `punycode` then you get node's version, and if you import from `punycode/` then you get the version from `node_modules`. This is consistent with the instructions in the documentation you linked to:

> ⚠️ Note that userland modules don't hide core modules. For example, `require('punycode')` still imports the deprecated core module even if you executed `npm install punycode`. Use `require('punycode/')` to import userland modules rather than core modules.

So it looks to me like esbuild is already working as intended and no additional changes are needed. It's the responsibility of code that imports `punycode` to decide what version to use. If it wants to use the node version then it should import from `punycode`. If it wants to use some other version then it should add a dependency on that package and them import from `punycode/` instead.

**Comment by MarcWeber** [comment]
I agree lack of knowledge / RTFM issue on my side. Thank you very much.
