### ISSUE TITLE
Bundled image is broken on the production

### ISSUE THREAD

**Issue by karan1803** [evanw/esbuild#3644]
Images are broken in the production environment they shouldn't be broken and the network content type should be "image/svg" or something like that but its "text/html", I have attached the screenshot.

Here is my build config - This not for react app its react library...

Also attached image for the project structure below
![screenshot-nimbusweb me-2024 02 13-14_34_59](https://github.com/evanw/esbuild/assets/59016533/7baf69ab-fc96-48ff-8021-8dafe04b0a18)

const esbuild = require('esbuild');
const { nodeExternalsPlugin } = require('esbuild-node-externals');
const svgLoader = require('esbuild-plugin-svgr');
const inlineImage = require("esbuild-plugin-inline-image");

esbuild
  .build({
    entryPoints: ['./src/index.tsx'],
    outfile: 'dist/index.js',
    bundle: true,
    minify: true,
    sourcemap: true,
    treeShaking: true,
    platform: 'node',
    format: 'cjs',
    target: 'node18',
    plugins: [nodeExternalsPlugin(), svgLoader(), inlineImage()],
  })
  .catch(() => process.exit(1));

![screenshot-github com-2024 02 13-14_37_30](https://github.com/evanw/esbuild/assets/59016533/82490b3e-7447-4726-8460-dfa187e5ef41)

**Comment by evanw** [comment]
I’m confused. The content type in a HTTP response is provided to the browser by your web server. If your web server isn’t providing the correct content type for a given file, then nothing esbuild can do will help. You need to fix your web server instead. 

Also you’re talking about SVG but your screenshot shows PNG. There is no built-in behavior for either of these file types, so any behavior that you don’t like is coming from one of the plugins you’re using. You’ll need to fix those plugins instead. That has nothing to do with esbuild either.

**Comment by karan1803** [comment]
Thanks @evanw , but previously I have used tsdx previously and right now migrate the package to esbuild after that only i am facing the issue, have u got any idea why its happening...

**Comment by lazarljubenovic** [comment]
It has little to do with bundler and a lot with the server. You're barking up the wrong tree.
