### ISSUE TITLE
Cannot implement import attribute `with { type: "external" }`

### ISSUE THREAD

**Issue by brillout** [evanw/esbuild#3646]
I'm trying to implement this:

```js
// Not externalized
import { something } from 'some-package'
// Externalized
import { something } from 'some-package' with { type: "external" }
```

In other words:

```js
build.onResolve({filter: /.*/}, async (args) => {
  if (args.kind !== 'import-statement') return undefined
  if (args.with === 'external') {
    return { external: true, /*...*/ }
  }
  // ...
})
```

That would work but the issue is that `args.with` is missing at `onResolve()`. It seems to be provided only to `onLoad()`.

Is there a way to implement such import attribute?

**Comment by evanw** [comment]
This is not currently supported, but it's something to add to esbuild in the future. I think this issue is related to at least #3384 and #3639.

**Comment by magoniac** [comment]
It might turn out to be a really handy option. As for possible performance issues I saw someone had suggested to introduce extra filtering property, smth. like { filter: /.*/, withType: "external" }.
