### ISSUE TITLE
minify-syntax bug: conditional yields "??" in final source code

### ISSUE THREAD

**Issue by rsms** [evanw/esbuild#365]
Repro:

1. install esbuild 0.6.29 from npm
2. create file `main.js` (see below)
3. run `esbuild --platform=node --minify-syntax --outfile=out.js main.js`
4. Inspect and/or attempt to evaluate resulting `out.js`

main.js
```js
function f(x) {
  x = x != null
    ? x
    : 1
  if (!x) {
    this.z()
  }
}
f(self["x"])
```

out.js
```js
function f(x) {
  x = x ?? 1, x || this.z();
}
f(self.x);
```

evaluating the out.js file in nodejs:

```txt
$ node out.js
/Users/rsms/src/ext/esbuild/bug-chokidar-isDirectory/out.js:2
  x = x ?? 1, x || this.z();
         ^
SyntaxError: Unexpected token '?'
```

This repro was reduced from real code in the popular [chokidar](https://www.npmjs.com/package/chokidar) package (i.e. import that package and build with minification yields the same bug; grep for `isDirectory = isDirectory` in the chokidar source code.)

env:
- macOS 10.15
- nodejs 12.16.3
- esbuild 0.6.29

**Comment by evanw** [comment]
The default language target is `--target=esnext` which means the `??` operator is considered available in the target environment. If you're targeting node 12, you should set `--target=node12` to make sure esbuild only uses syntax that node 12 supports.

**Comment by rsms** [comment]
Thank you!
I wonder if there is an opportunity to produce a warning somehow when the invocation relies on default values and may be using cutting-edge features. Just an idea.
