### ISSUE TITLE
Injecting code into bundled dependency with iife format

### ISSUE THREAD

**Issue by commonuserlol** [evanw/esbuild#3668]
For example, module `X` uses `TextEncoder` but in my env there's no `TextEncoder` so external implementation will be used, but `X` code will be executed before my `index.ts`. Can I inject `globalThis.TextEncoder = TextEncoder` into `X` when bundling?

**Comment by evanw** [comment]
There is already a feature called [inject](https://esbuild.github.io/api/#inject) that is for this exact purpose. Are you asking how to use it? You can do something like [this](https://esbuild.github.io/try/#YgAwLjIwLjEALS1idW5kbGUgLS1pbmplY3Q6Li9zaGltcy5qcwBlAGVudHJ5LmpzAGNvbnNvbGUubG9nKG5ldyBUZXh0RW5jb2RlcigpLmVuY29kZSgnXHVBNjZFJykpAABzaGltcy5qcwBleHBvcnQgY2xhc3MgVGV4dEVuY29kZXIgewogIGVuY29kZSh4KSB7CiAgICByZXR1cm4gbmV3IFVpbnQ4QXJyYXkodW5lc2NhcGUoZW5jb2RlVVJJQ29tcG9uZW50KHgpKS5zcGxpdCgnJykubWFwKHggPT4geC5jaGFyQ29kZUF0KCkpKQogIH0KfQ).

**Comment by commonuserlol** [comment]
By external implementation I meant it inside `node_modules` and it used in my code. Should I pass inject flag to nodule_modules/textencodermodulename/impl.js ?

**Comment by evanw** [comment]
Ah, I see. You can also do something like [this](https://esbuild.github.io/try/#YgAwLjIwLjEALS1idW5kbGUgLS1pbmplY3Q6Li9zaGltcy5qcyAtLXBhY2thZ2VzPWV4dGVybmFsIC0tZm9ybWF0PWVzbQBlAGVudHJ5LmpzAGNvbnNvbGUubG9nKG5ldyBUZXh0RW5jb2RlcigpLmVuY29kZSgnXHVBNjZFJykpAABzaGltcy5qcwBleHBvcnQgeyBUZXh0RW5jb2RlciB9IGZyb20gJ3RleHRlbmNvZGVybW9kdWxlbmFtZS9pbXBsLmpzJw) instead if you'd like (import the package into your injected file). Another feature you can use for this is [banner](https://esbuild.github.io/api/#banner) which lets you put code at the top of your file that's guaranteed to come before anything else, but it's quite limited and may not be what you want here.
