### ISSUE TITLE
build() vs context().rebuild()

### ISSUE THREAD

**Issue by cowwoc** [evanw/esbuild#3677]
Question: Say I am not interested in incremental builds or watch mode, but I want to interact with esbuild's API using the context object, is invoking `esbuild.context().rebuild()` once equivalent to invoking `esbuild.build()`? If not, what is the difference between the two?

Justification: Ideally I'd like to use a common function to configure esbuild, and defer the decision of whether I want to `build()` or `watch()` until a later point in the code.

Thank you.

**Comment by evanw** [comment]
> is invoking `esbuild.context().rebuild()` once equivalent to invoking `esbuild.build()`? If not, what is the difference between the two?

Basically yes. The source code for `build` is [here](https://github.com/evanw/esbuild/blob/cc74e6042a9f573bf58e1e3f165ebda70af4ad3b/pkg/api/api.go#L376). The only differences are that a) `build` may also print a build summary and b) `build` also disposes of the context before returning to clean up. 

> Justification: Ideally I'd like to use a common function to configure esbuild, and defer the decision of whether I want to `build()` or `watch()` until a later point in the code.

This is one of the reasons behind having a `rebuild` method.

**Comment by cowwoc** [comment]
Perfect, thank you!
