### ISSUE TITLE
Decorator wrapped around declare or abstract fields are failing since 0.19.8

### ISSUE THREAD

**Issue by rodrigofuentes** [evanw/esbuild#3684]
The issue I'm facing is decorated declare or abstract fields are causing an `Error: Decorators are not valid here`. After some inspection it seems that `esbuild` supported this until version `0.19.8`

Is this no longer supported?

Code example:
```ts
function log(target: any, key: string): void {
  console.log(`Logging ${key} function`)
}

abstract class ExampleClass {
  @log
  abstract prop1: string

  @log
  prop2: boolean = true
}

class ExampleClass2 extends ExampleClass {
  prop1: string = "world"
}
```

Esbuild result:
```md
✘ [ERROR] Decorators are not valid here

    entry.ts:6:2:
      6 │   @log
        ╵   ^

```

Some playground links:

[Working esbuild-playground on version 0.19.7](https://esbuild.github.io/try/#dAAwLjE5LjcALS10YXJnZXQ9ZXNuZXh0Ci0tbG9hZGVyPXRzCi0tc291cmNlbWFwAGZ1bmN0aW9uIGxvZyh0YXJnZXQ6IGFueSwga2V5OiBzdHJpbmcpOiB2b2lkIHsKICBjb25zb2xlLmxvZyhgTG9nZ2luZyAke2tleX0gZnVuY3Rpb25gKQp9CgphYnN0cmFjdCBjbGFzcyBFeGFtcGxlQ2xhc3MgewogIEBsb2cKICBhYnN0cmFjdCBwcm9wMTogc3RyaW5nCgogIEBsb2cKICBwcm9wMjogYm9vbGVhbiA9IHRydWUKfQoKY2xhc3MgRXhhbXBsZUNsYXNzMiBleHRlbmRzIEV4YW1wbGVDbGFzcyB7CiAgcHJvcDE6IHN0cmluZyA9ICJ3b3JsZCIKfQoKY29uc3QgeCA9IG5ldyBFeGFtcGxlQ2xhc3MyKCkKeC5wcm9wMSA9ICJoZWxsbyIKCmNvbnNvbGUubG9nKHgp)

[typescript-playground](https://www.typescriptlang.org/play?useDefineForClassFields=true&experimentalDecorators=true&emitDecoratorMetadata=true&ssl=21&ssc=1&pln=1&pc=1#code/GYVwdgxgLglg9mABAGzgcwBRQIYCc0CmUAXItmAJ4A0iA1gRaQM5S4xhoCUpAbnDABNEAbwBQiRBARM4yAgDpUmAAYAZdGnZpEAEmH0KAX0ShIsBMs6jDo0dgBGLXNmiTk2Jk0QBRAB7YAWwAHOQBhd08RcUQAASVohycXKEQg3DgggEZmVi1bCTj0aLSMgCZSezhZAnJEAF5EVhACa1sICK8-QJCCcI8mUsQCXygCMAFO-2CwjqiJEqyctg56xAAiAHc4XGQBNdbRKTAWRF9VsAINnymevs9SjCtfeQXM1bWACwJkVH3D6WqinQGF8ViAA)

**Comment by evanw** [comment]
There are two problems here:

1. Using decorators like this is legacy TypeScript-specific behavior that requires you to set `"experimentalDecorators": true` in your `tsconfig.json` file. You can do this on esbuild's command line with `--tsconfig-raw='{"compilerOptions":{"experimentalDecorators":true}}'` like [this](https://esbuild.github.io/try/#dAAwLjIwLjEALS10YXJnZXQ9ZXNuZXh0Ci0tbG9hZGVyPXRzCi0tc291cmNlbWFwCi0tdHNjb25maWctcmF3PSd7ImNvbXBpbGVyT3B0aW9ucyI6eyJleHBlcmltZW50YWxEZWNvcmF0b3JzIjp0cnVlfX0nAGZ1bmN0aW9uIGxvZyh0YXJnZXQ6IGFueSwga2V5OiBzdHJpbmcpOiB2b2lkIHsKICBjb25zb2xlLmxvZyhgTG9nZ2luZyAke2tleX0gZnVuY3Rpb25gKQp9CgphYnN0cmFjdCBjbGFzcyBFeGFtcGxlQ2xhc3MgewogIEBsb2cKICBkZWNsYXJlIHByb3AxOiBzdHJpbmcKCiAgQGxvZwogIHByb3AyOiBib29sZWFuID0gdHJ1ZQp9CgpjbGFzcyBFeGFtcGxlQ2xhc3MyIGV4dGVuZHMgRXhhbXBsZUNsYXNzIHsKICBwcm9wMTogc3RyaW5nID0gIndvcmxkIgp9Cgpjb25zdCB4ID0gbmV3IEV4YW1wbGVDbGFzczIoKQp4LnByb3AxID0gImhlbGxvIgoKY29uc29sZS5sb2coeCk).

2. This currently only works for `declare` fields, not for `abstract` fields. This is an esbuild bug that I can fix (I didn't think about the `abstract` case).
