### ISSUE TITLE
The current esbuild does not support the platform I am currently using, and the CPU model is sw_64. Can this platform be supported in the source code?

### ISSUE THREAD

**Issue by 2morning** [evanw/esbuild#3688]
My project will download vite dependencies, and vite will automatically go https://registry.npmjs.org Download esbuild. As the esbuild in this path does not support the sw platform, an error message may appear. How can this be resolved?
<img width="807" alt="微信图片_20240309213001" src="https://github.com/evanw/esbuild/assets/57852159/2103d6f5-84d4-4451-aa5a-f2c63452e5a8">
<img width="575" alt="微信图片_20240309213100" src="https://github.com/evanw/esbuild/assets/57852159/8339465c-b037-45b5-9c2a-54d9552e0458">

**Comment by 2morning** [comment]
The dependency downloaded in the configuration file is vite and does not directly declare the download of esbuild. esbuild is downloaded as a dependency of vite. I manually modified the source code file of esbuild so that it can be installed normally on the sw platform. However, in the project, downloading this dependency is still done directly https://registry.npmjs.org Searching, not searching locally.

**Comment by evanw** [comment]
What is "sw_64"? I tried an Internet search but got https://en.wikipedia.org/wiki/Smith_%26_Wesson_Model_64, which I assume is not what you're talking about.

Adding `unactionable` because this issue doesn't have enough information.

**Comment by tombl** [comment]
I think this is the [Sunway](https://en.wikipedia.org/wiki/Sunway_(processor)) architecture. They have [a proprietary fork](https://developer.wxiat.com/understand/ecologial/8) of the go compiler.

**Comment by 2morning** [comment]
Thank you for your reply. I have resolved the issue by recompiling the binary code available on the SW64 architecture using the esbuild source code, and then using the global link to resolve it.

**Comment by evanw** [comment]
Ah, I see. In that case I'm closing this issue as I won't be doing this. Go doesn't support this platform so esbuild won't either. You are welcome to either build esbuild for yourself using a custom compiler (as it sounds like you've done) or to use the WASM build instead which should work on any platform that has a WASM engine.
