### ISSUE TITLE
Fails to resolve tsconfig.json `extends` by `exports` field when using yarn pnp

### ISSUE THREAD

**Issue by sapphi-red** [evanw/esbuild#3698]
When [a `tsconfig.json` has extends](https://github.com/sapphi-red-repros/esbuild-yarn-pnp-tsconfig-extends-exports-field-repro/blob/aec47f0293cedc4227785b5e5b30e3692a09b03e/packages/app/tsconfig.json#L2) and that [uses exports field](https://github.com/sapphi-red-repros/esbuild-yarn-pnp-tsconfig-extends-exports-field-repro/blob/aec47f0293cedc4227785b5e5b30e3692a09b03e/packages/tsconfigs/package.json#L5-L7) to be resolved and using yarn pnp, esbuild fails to resolve the base tsconfig file. The following warning is output.

```
▲ [WARNING] Cannot find base config file "D:\\path\\to\\project\\packages\\tsconfigs\\config" [tsconfig.json]

    tsconfig.json:2:13:
      2 │   "extends": "tsconfigs/config",
        ╵              ~~~~~~~~~~~~~~~~~~
```

By running `yarn show-config` in `packages/app`, I can see TypeScript resolving it without issue.

If I set `nodeLinker: pnpm` or `nodeLinker: node-modules`, esbuild does not output any warnings.

Reproduction: https://github.com/sapphi-red-repros/esbuild-yarn-pnp-tsconfig-extends-exports-field-repro
Original issue: https://github.com/vitejs/vite/issues/16156

**Comment by lewispham** [comment]
@evanw This issue still presents in TS version 5.6.3. Any idea why it is closed?
