### ISSUE TITLE
Can you create a docker image which can use for build?

### ISSUE THREAD

**Issue by sarkiroka** [evanw/esbuild#37]
I think use docker image for build javascript is a great idea. Not need a more type of esbuild anymore (win/mac/linux) Just only say: `docker run -v$(pwd):/usr/local/app esbuild:latest` and the magic happened...
What do you think about this idea

**Comment by evanw** [comment]
Thanks for the idea. However, I am planning to  solve this problem by instead making a single npm package for all platforms with a post install script that automatically downloads the correct binary (see #32).

**Comment by sarkiroka** [comment]
And what about the CI/CD servers? We need to install nodejs and npm instead of docker? Please think about docker container again. It has many many advantage. This is an important aspect in my devops hat.

**Comment by evanw** [comment]
I'm only using npm as a distribution mechanism. There's nothing about nodejs that's inherently necessary to run esbuild. For example, this is all it takes to get an esbuild binary on Linux:

```sh
$ curl -O https://registry.npmjs.org/esbuild-linux-64/-/esbuild-linux-64-0.0.9.tgz
$ tar xf ./esbuild-linux-64-0.0.9.tgz
$ file ./package/bin/esbuild
package/bin/esbuild: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, not stripped
$ ./package/bin/esbuild

Usage:
  esbuild [options] [entry points]

...
```

Given that it's this simple, it seems like overkill to me to use docker just to run esbuild. It also seems pretty simple to use these commands to create a docker image if you do need one, so it doesn't seem necessary to me to have an official docker image. That said, I don't use docker myself, so I could be misunderstanding something.

**Comment by icfantv** [comment]
@evanw I think the underlying issue will be that a lot of corporate CI systems are locked down to the Internet so using `npm install` or `yarn install` will fail.  Additionally, corporate ITSEC might need to be, ahem, persuaded, to allow a foreign binary into, say, an Artifactory server.

One of our product teams is evaluating this for their product to see how/if it's viable.  If it is, either us building a Docker image wrapping this or having the ability to build eslint locally the first time prior to use in a CI environment would be very useful.

If you don't want to mess with supporting the latter (and I'm still going through the existing issues so I don't know if you've already addressed this use-case elsewhere), I'm happy to investigate the Docker route if we decide that we want to use this internally and share that if it's useful.

Thoughts?

**Comment by evanw** [comment]
Running esbuild using Docker should work fine. I haven't tried it myself but I don't see why it wouldn't work. I don't intend for this to be the distribution method for esbuild but it should be trivial to do this yourself if you need it.

The instructions for installing a binary without needing to install node or npm are in my previous post. If you want to build from source because you don't trust the binary, you could do this:

```sh
$ git clone --depth 1 --branch v0.0.0 https://github.com/evanw/esbuild.git
$ cd esbuild
$ go build "-ldflags=-s -w" ./cmd/esbuild
```

except you would replace `0.0.0` with the version of esbuild you intend to build. These commands result in an executable file called `./esbuild` in the current working directory.

**Comment by icfantv** [comment]
Agreed.  We run all our Ansible and Helm stuff from containers to keep the versions stable and not have to deal with all the inherent versioning issues on dev computers.  A dev on one of our app teams is currently evaluating this.  I think Docker will be the way we decide to go if we decide to switch away from Webpack.  Thanks again.
