### ISSUE TITLE
esbuild@0.20.1 prototype setting when bundling json containing a `__proto__` key

### ISSUE THREAD

**Issue by lucacasonato** [evanw/esbuild#3700]
```js
const DATA = `{
  "hello": "world",
  "__proto__": {
    "sky": "universe"
  }
}
`;

import * as esbuild0_20_0 from "npm:esbuild@0.20.0";
console.log(esbuild0_20_0.version);
const res0_20_0 = await esbuild0_20_0.build({
  stdin: {
    contents: DATA,
    loader: "json",
  },
  format: "esm",
  write: false,
  absWorkingDir: Deno.cwd(),
});
console.log(res0_20_0.outputFiles[0].text);

import * as esbuild0_20_1 from "npm:esbuild@0.20.1";
console.log(esbuild0_20_1.version);
const res0_20_1 = await esbuild0_20_1.build({
  stdin: {
    contents: DATA,
    loader: "json",
  },
  format: "esm",
  write: false,
  absWorkingDir: Deno.cwd(),
});
console.log(res0_20_1.outputFiles[0].text);
```

```
>>> deno run -A test.ts
0.20.0
var hello = "world";
var __proto__ = {
  sky: "universe"
};
var stdin_default = {
  hello,
  __proto__
};
export {
  __proto__,
  stdin_default as default,
  hello
};

0.20.1
var hello = "world";
var __proto__ = {
  sky: "universe"
};
var stdin_default = {
  hello,
  __proto__: __proto__
};
export {
  __proto__,
  stdin_default as default,
  hello
};
```

In the 0.20.1 output, the `__proto__` field of the JSON is incorrectly written as `__proto__: __proto__`. This sets the prototype of `stdin_default` rather than a `__proto__` key, like was happening in 0.20.0 and below.

This may be a security issue if users bundle untrusted JSON files into their code (but probably not that bad).

**Comment by lucacasonato** [comment]
Was broken by https://github.com/evanw/esbuild/commit/ac365374f9054493aa07530ae1fe8524d26cb617. Discovered through tests in https://github.com/lucacasonato/esbuild_deno_loader

**Comment by evanw** [comment]
Hmm, I think this perhaps never really worked. Version 0.20.0 can [generate incorrect output as well](https://esbuild.github.io/try/#YgAwLjIwLjAALS1idW5kbGUAZQBlbnRyeS5tanMAaW1wb3J0IGltcG9ydGVkRGF0YSBmcm9tICcuL2RhdGEuanNvbicgYXNzZXJ0IHsgdHlwZTogJ2pzb24nIH0KCmNvbnN0IG5hdGl2ZURhdGEgPSBKU09OLnBhcnNlKGB7CiAgImhlbGxvIjogIndvcmxkIiwKICAiX19wcm90b19fIjogewogICAgInNreSI6ICJ1bml2ZXJzZSIKICB9Cn1gKQoKY29uc29sZS5sb2coewogIGltcG9ydGVkOiBPYmplY3QuZ2V0UHJvdG90eXBlT2YoaW1wb3J0ZWREYXRhKT8uc2t5ID8gJ1x1Mjc0QycgOiAnXHUyNzA1JywKICBuYXRpdmU6IE9iamVjdC5nZXRQcm90b3R5cGVPZihuYXRpdmVEYXRhKT8uc2t5ID8gJ1x1Mjc0QycgOiAnXHUyNzA1JywKfSkAAGRhdGEuanNvbgB7CiAgImhlbGxvIjogIndvcmxkIiwKICAiX19wcm90b19fIjogewogICAgInNreSI6ICJ1bml2ZXJzZSIKICB9Cn0). Thanks for the report! I'll fix this in the next release.

**Comment by lucacasonato** [comment]
Thanks @evanw for the quick fix!

**Comment by hai-x** [comment]
Sorry, I want to ask a question here. Is there some relevant spec indicated that we need compute property key in some case such as `__proto__`? Just for curiosity. I found that it behaves differently in `es5` and `es6`.

**Comment by evanw** [comment]
I believe the relevant part of the JavaScript specification is [here](https://tc39.es/ecma262/#:~:text=propKey%20is%20%22__proto__%22):

> _PropertyDefinition_ : _PropertyName_ : _AssignmentExpression_
>
> 1. Let _propKey_ be ? Evaluation of _PropertyName_.
> 2. If this _PropertyDefinition_ is contained within a _Script_ that is being evaluated for JSON.parse (see step 7 of JSON.parse), then
>        a. Let _isProtoSetter_ be **false**.
> 3. Else if propKey is "**\_\_proto\_\_**" and IsComputedPropertyKey of _PropertyName_ is **false**, then
>        a. Let _isProtoSetter_ be **true**.
> 4. Else,
>        a. Let _isProtoSetter_ be **false**.

**Comment by hai-x** [comment]
> I believe the relevant part of the JavaScript specification is [here](https://tc39.es/ecma262/#:~:text=propKey%20is%20%22__proto__%22):
> 
> > _PropertyDefinition_ : _PropertyName_ : _AssignmentExpression_
> > 
> > 1. Let _propKey_ be ? Evaluation of _PropertyName_.
> > 2. If this _PropertyDefinition_ is contained within a _Script_ that is being evaluated for JSON.parse (see step 7 of JSON.parse), then
> >    a. Let _isProtoSetter_ be **false**.
> > 3. Else if propKey is "**__proto__**" and IsComputedPropertyKey of _PropertyName_ is **false**, then
> >    a. Let _isProtoSetter_ be **true**.
> > 4. Else,
> >    a. Let _isProtoSetter_ be **false**.

Got it. Thank u.
