### ISSUE TITLE
Simple way to make an esbuild plugin that watches src directory recursively?

### ISSUE THREAD

**Issue by zaydek** [evanw/esbuild#3705]
As I understand, the `watchDirs` field for a plugin watches a directory but not in a recursive way. Is there a simple way to write a plugin so I can say _watch all files in `src` recursively_?

According to the docs:

> A rebuild will also be triggered if the list of directory entries for any directory in the watchDirs array has been changed since the last build. Note that this does not check anything about the contents of any file in these directories, and it also does not check any subdirectories. Think of this as checking the output of the Unix ls command.

Is it possible to say `src/**/*` or `src/*` so I can simply have everything considered 'source code' trigger a refresh? I am using esbuild as a custom dev server, combining the `watch` and `serve` commands, so ideally I would be able to tell esbuild instead of something that composes esbuild, like chokidar, which I've done in the past.

Thank you.

**Comment by evanw** [comment]
No, this is not possible. If you want something like chokidar then you should use chokidar. The watch mode that's built into esbuild is designed specifically for only triggering a rebuild when esbuild's build inputs are changed.

You could try to hack this by making every file that you want to serve into a build input. For example, this will watch all `.html` and `.svg` files recursively (and `copy` them into the `www` folder, which is then served with watch mode):

```
esbuild ./src/**/*.html ./src/**/*.svg --loader:.html=copy --loader:.svg=copy --outdir=www --watch --serve
```

But that's not a general solution. I recommend using another more general dev server if you want a dev server without using esbuild's bundling features (or augmenting esbuild with something like chokidar).

**Comment by zaydek** [comment]
Gotcha. OK fair enough, thank you. Closing this.
