### ISSUE TITLE
Run DCE without minify?

### ISSUE THREAD

**Issue by commonuserlol** [evanw/esbuild#3706]
Can esbuild run DCE (dead code elimination) without `--minify`?
https://esbuild.github.io/try/#dAAwLjIwLjIALS1kZWZpbmU6REVCVUc9dHJ1ZSAtLW1pbmlmeQBpZiAoREVCVUcpIHsKICBjb25zb2xlLmxvZygiZGVidWcgbWVzc2FnZSIpOwp9CmNvbnNvbGUubG9nKCJqdXN0IGEgbWVzc2FnZSIpOw
If you remove `--minify` `DEBUG` will be replaced with `true`

**Comment by evanw** [comment]
I assume that you are asking for a way to get esbuild to unwrap the `if` statement without inserting the comma operator. Enabling and disabling individual minification transforms like that not something that esbuild can do. There are only three separate flags for minification, which are already documented here: https://esbuild.github.io/api/#minify.

**Comment by commonuserlol** [comment]
I mean, can esbuild remove dead code (if loop with false statement) but don't minify script?

**Comment by evanw** [comment]
Not in this case. Without minification enabled, esbuild still does some expression-level simplifications but doesn't do statement-level simplifications. Here are two ways to do that without minification enabled: [option 1](https://esbuild.github.io/try/#dAAwLjIwLjIALS1kZWZpbmU6REVCVUc9ZmFsc2UAREVCVUcgJiYgY29uc29sZS5sb2coImRlYnVnIG1lc3NhZ2UiKTsKY29uc29sZS5sb2coImp1c3QgYSBtZXNzYWdlIik7) and [option 2](https://esbuild.github.io/try/#dAAwLjIwLjIALS1kcm9wLWxhYmVscz1ERUJVRwBERUJVRzogY29uc29sZS5sb2coImRlYnVnIG1lc3NhZ2UiKTsKY29uc29sZS5sb2coImp1c3QgYSBtZXNzYWdlIik7).

**Comment by commonuserlol** [comment]
Thanks!
