### ISSUE TITLE
Explanation of colors in Bundle Size Analyzer 

### ISSUE THREAD

**Issue by ChristopherPHolder** [evanw/esbuild#3707]
When using the [Esbuild - Bundle Size Analyzer](https://esbuild.github.io/analyze/) it does not provide any explanation about what the colors mean. 

![image](https://github.com/evanw/esbuild/assets/40126819/3414e94c-b56a-4a5d-84d3-02c7c6f14d11)

However they are definitely not random. 

In Another Bundle Analyzer called Bundle Wizard they provide this:

![image](https://github.com/evanw/esbuild/assets/40126819/8668a3a2-0ba2-4f4b-bd54-2fe784ed35e3)

In Esbuild - Bundle Size Analyzer:

What do the colors mean? 

Are there any docs?

Is the codebase for this tool open sources and on github ?

**Comment by evanw** [comment]
> What do the colors mean?

The colors don't mean too much. They are only intended to make things that are colocated in the directory tree look similar in the graph. The [specific algorithm](https://github.com/esbuild/esbuild.github.io/blob/10ead9bf986c3bd7b892253bf7d17a9b96bb7d9b/src/analyze/color.ts#L172-L193) is:

1. Set the size of each file in the directory tree to the number of bytes of output it produced
2. Sort the files such that larger directory children come before smaller directory children
3. Map the range [0°, 360°] to the ordered list of files, weighed by the size of each file
4. Set the color of each file using the angle at the file's midpoint as the hue for HSL

This is most obvious when you look at the sunburst chart as the colors form a rainbow hue wheel (note that the color of each wedge is sampled at the midpoint angle).

> Are there any docs?

Not for that, sorry.

> Is the codebase for this tool open sources and on github ?

Yes. On GitHub, you can always find the content for `<user>.github.io` at `github.com/<user>/<user>.github.io` for any `<user>`. So the source for https://esbuild.github.io is here: https://github.com/esbuild/esbuild.github.io.
