### ISSUE TITLE
some minification performed even though minify not enabled

### ISSUE THREAD

**Issue by kzc** [evanw/esbuild#371]
It doesn't appear to be possible to output code without at least some degree of minification - is this by design?

```
$ esbuild --version
0.6.31
```
Actual:
```
$ echo 'false, true, a = true && b, a = false || b, typeof !!7, typeof !!!x;' | esbuild
false, true, a = b, a = b, "boolean", typeof !x;

$ echo 'false, true, a = true && b, a = false || b, typeof !!7, typeof !!!x;' | esbuild --minify-whitespace
!1,!0,a=b,a=b,"boolean",typeof!x;
```
Expected:
```
$ echo 'false, true, a = true && b, a = false || b, typeof !!7, typeof !!!x;' | npx uglify-js
false,true,a=true&&b,a=false||b,typeof!!7,typeof!!!x;
```

Encountered when trying to verify non-minified whitespace-removed esbuild output of uglify tests against whitespace-removed input.

**Comment by evanw** [comment]
This is intentional. It's constant folding, not minification. This is useful when combined with `--define` for compile-time flags. Not doing so can make bundling slower. For example, React contains this code:

```js
if (process.env.NODE_ENV === 'production') {
  module.exports = require('./cjs/react-dom.production.min.js');
} else {
  module.exports = require('./cjs/react-dom.development.js');
}
```

Usually you use `--define:process.env.NODE_ENV="development"` in development. If constant folding is not done then the parser does not discover that the if statement condition is statically false, and the bundler ends up bundling both the production build and the development build.

**Comment by kzc** [comment]
It's not documented as such:
```
  --minify-whitespace   Remove whitespace
```
It breaks from convention for other minifiers like uglify and terser with `compress` disabled and Google Closure Compiler with [WHITESPACE_ONLY](https://closure-compiler.appspot.com/home#code%3D%252F%252F%2520%253D%253DClosureCompiler%253D%253D%250A%252F%252F%2520%2540compilation_level%2520WHITESPACE_ONLY%250A%252F%252F%2520%2540output_file_name%2520default.js%250A%252F%252F%2520%253D%253D%252FClosureCompiler%253D%253D%250A%250Afalse%252C%2520true%252C%2520a%2520%253D%2520true%2520%2526%2526%2520b%252C%2520a%2520%253D%2520false%2520%257C%257C%2520b%252C%2520typeof%2520!!7%252C%2520typeof%2520!!!x%253B). 

Minification of syntax is generally understood to be a collection of standard compiler optimizations of which constant folding is one. One would not expect to optimize code with just `--minify-whitespace` enabled. It'd be used for debugging generally, or to verify parsing fidelity.

There seems to be a consistency issue as well - if you look at the top post, notice that `true` and `false` are handled differently with no flags versus `--minify-whitespace`.

Closing issue since it's by design.

**Comment by evanw** [comment]
Oh I see, you were probably talking about the `true` to `!0` conversion. Yeah I could change that behavior I guess. The reason why that happens currently is that `--minify-syntax` rewrites the syntax in the parser while the printer currently only looks at `--minify-whitespace` but the `true` to `!0` conversion happens in the printer.

**Comment by kzc** [comment]
The true/!0 observation was just a tangent.

It would be useful for esbuild to have a new flag to not perform any optimizations or minification transforms of any kind to accurately output the code as parsed, providing functionality that other minifers presently support.
