### ISSUE TITLE
Import with wildcard

### ISSUE THREAD

**Issue by jbjanot** [evanw/esbuild#3711]
Hi everyone and thanks a lot for all the hard work on this tool!

I am trying to import modules from my entry point with wildcards, but I can't make it work.
It might just not be possible and I misunderstand it.

It looks like that:

```js
import 'files/*.js';
```

With a basic build like this:
```js
esbuild.build( {
	entryPoints: [ 'src/main.js' ],
	bundle: true,
	outfile: 'dist/script.js',
} );

```

[I did a quick test here that reproduces what I see.](https://esbuild.github.io/try/#YgAwLjIwLjIAe2J1bmRsZTogdHJ1ZX0AZQBlbnRyeS5qcwBpbXBvcnQgJyouanMnOwAAZmlsZTEuanMAZXhwb3J0IGRlZmF1bHQgbmV3IGNsYXNzIEZpbGUxIHsKY29uc3RydWN0b3IoKXsKY29uc29sZS5sb2coImZpbGUxIik7Cn0KfQAAZmlsZTIuanMAZXhwb3J0IGRlZmF1bHQgbmV3IGNsYXNzIEZpbGUyIHsKY29uc3RydWN0b3IoKXsKY29uc29sZS5sb2coImZpbGUyIik7Cn0KfQ)

Thank you for your help!

**Comment by evanw** [comment]
This is not something that esbuild has built-in behavior for. You are welcome to write an esbuild plugin to do this if you would like for it to work. Plugin API documentation is here: https://esbuild.github.io/plugins/. It looks like there might also be some existing plugins that do this (search for "glob"): https://github.com/esbuild/community-plugins/.

**Comment by jbjanot** [comment]
Thank you very much @evanw for taking the time to point me this. Indeed, I can see some tools that are not that far from what I need (might need some updates though).
Thanks!
