### ISSUE TITLE
Broken automatic JSX transform

### ISSUE THREAD

**Issue by fabiospampinato** [evanw/esbuild#3714]
As far as I can tell the automatic JSX transform is totally broken.

Given this following input file:

```ts
export function App() {
  return <h1>Hello World</h1>;
}
```

according to React's [documentation on this](https://legacy.reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html) I'd expect that to get compiled down to this:

```ts
import {jsx as _jsx} from 'react/jsx-runtime';

export function App() {
  return _jsx('h1', { children: 'Hello world' });
}
```

But on version v0.20.2 with the following command:

```sh
esbuild --bundle --jsx=automatic bug.jsx
```

I get this output:

```sh
"use strict";
(() => {
  // bug.jsx
  function App() {
    return /* @__PURE__ */ React.createElement("h1", null, "Hello World");
  }
})();
```

If I set also `--jsx-import-source=react` and/or `--jsx-dev`, or if I don't set the `--jsx=automatic` flag at all, I don't see any difference whatsoever in the output.

It looks like that's just broken I guess?

**Comment by evanw** [comment]
I can't reproduce this. [The output appears to be correct.](https://esbuild.github.io/try/#YgAwLjIwLjIALS1idW5kbGUgLS1qc3g9YXV0b21hdGljIC0tcGFja2FnZXM9ZXh0ZXJuYWwgLS1mb3JtYXQ9ZXNtAGUAYnVnLmpzeABleHBvcnQgZnVuY3Rpb24gQXBwKCkgewogIHJldHVybiA8aDE+SGVsbG8gV29ybGQ8L2gxPjsKfQ) Maybe you have a `tsconfig.json` file that's overriding your CLI JSX settings? [Here is an example.](https://esbuild.github.io/try/#YgAwLjIwLjIALS1idW5kbGUgLS1qc3g9YXV0b21hdGljIC0tcGFja2FnZXM9ZXh0ZXJuYWwgLS1mb3JtYXQ9ZXNtAGUAYnVnLmpzeABleHBvcnQgZnVuY3Rpb24gQXBwKCkgewogIHJldHVybiA8aDE+SGVsbG8gV29ybGQ8L2gxPjsKfQAAdHNjb25maWcuanNvbgB7CiAgImNvbXBpbGVyT3B0aW9ucyI6IHsKICAgICJqc3giOiAicmVhY3QiCiAgfQp9)

**Comment by fabiospampinato** [comment]
Ah, you're right, that's what's happening.

Shouldn't CLI flags have higher precedence though? Like if they had higher precedence this would just work, if they shouldn't have higher precedence I don't see why anybody would explicitly provide them, in any case some kind of warning if they get overridden by `tsconfig.json` or something else seems useful 🤔

**Comment by evanw** [comment]
The way it's designed is that the CLI flags provide the base level and then per-directory settings can override them. This is necessary for building larger projects where different directories might need to have different JSX settings. This is something esbuild supports by allowing there to be different `tsconfig.json` files for different subdirectory trees.

**Comment by fabiospampinato** [comment]
Ah, I see. Thanks for the explanation.

**Comment by fabiospampinato** [comment]
A `--no-tsconfig` flag seems useful 🤔

**Comment by evanw** [comment]
> A `--no-tsconfig` flag seems useful 🤔

This already exists: ` --tsconfig-raw={}`. [See an example.](https://esbuild.github.io/try/#YgAwLjIwLjIALS1idW5kbGUgLS1qc3g9YXV0b21hdGljIC0tcGFja2FnZXM9ZXh0ZXJuYWwgLS1mb3JtYXQ9ZXNtIC0tdHNjb25maWctcmF3PXt9AGUAYnVnLmpzeABleHBvcnQgZnVuY3Rpb24gQXBwKCkgewogIHJldHVybiA8aDE+SGVsbG8gV29ybGQ8L2gxPjsKfQAAdHNjb25maWcuanNvbgB7CiAgImNvbXBpbGVyT3B0aW9ucyI6IHsKICAgICJqc3giOiAicmVhY3QiCiAgfQp9)

**Comment by fabiospampinato** [comment]
That seems good enough 👍 It may be worth mentioning that in the `--help` page, I didn't know that option existed.
