### ISSUE TITLE
Expected ";" but found "const" - typescript transformer

### ISSUE THREAD

**Issue by bartlomiejzuber** [evanw/esbuild#3716]
Casting to 'const' should work as const assertions in TypeScript typically works. I.e. that code shouldn't fail.

Playground URL: https://esbuild.github.io/try/#dAAwLjIwLjIAAGV4cG9ydCBjb25zdCBwcmV2aWV3Q2FyZHMgPSBbCiAgewogICAgdGl0bGU6ICJBYm91dCB1cyIsCiAgICB0ZXh0OiAibG9yZW0gaXBzdW0iLAogICAgY3RhOiAic3VibWl0IiwKICAgIGFsdDogIlBlcnNvbiBzbWlsaW5nIGF3YXkgZnJvbSB0aGVpciBwaG9uZSIsCiAgfSwKICB7CiAgICB0aXRsZTogIkZvciBvdXIgY3VzdG9tZXJzIiwKICAgIHRleHQ6ICJsb3JlbSBpcHN1bSIsCiAgICBjdGE6ICJzdWJtaXQiLAogICAgYWx0OiAiUGVyc29uIHNtaWxpbmcgdGhyb3VnaCB3aW5kb3ciLAogIH1dIGFzIGNvbnN0Ow

Linked issue: https://github.com/withastro/astro/issues/10663

**Comment by hyrious** [comment]
You should enable [`--loader=ts`](https://esbuild.github.io/api/#loader) to tell esbuild the input is in TypeScript (default is JavaScript).

**Comment by evanw** [comment]
Yes, compiling TypeScript as JavaScript is expected to not work on TypeScript-only syntax. Compiling TypeScript as TypeScript [works as expected](https://esbuild.github.io/try/#dAAwLjIwLjIALS1sb2FkZXI9dHMAZXhwb3J0IGNvbnN0IHByZXZpZXdDYXJkcyA9IFsKICB7CiAgICB0aXRsZTogIkFib3V0IHVzIiwKICAgIHRleHQ6ICJsb3JlbSBpcHN1bSIsCiAgICBjdGE6ICJzdWJtaXQiLAogICAgYWx0OiAiUGVyc29uIHNtaWxpbmcgYXdheSBmcm9tIHRoZWlyIHBob25lIiwKICB9LAogIHsKICAgIHRpdGxlOiAiRm9yIG91ciBjdXN0b21lcnMiLAogICAgdGV4dDogImxvcmVtIGlwc3VtIiwKICAgIGN0YTogInN1Ym1pdCIsCiAgICBhbHQ6ICJQZXJzb24gc21pbGluZyB0aHJvdWdoIHdpbmRvdyIsCiAgfV0gYXMgY29uc3Q7).

I'm closing this issue as this is not a bug with esbuild.
