### ISSUE TITLE
Pass argument to IIFE

### ISSUE THREAD

**Issue by reesericci** [evanw/esbuild#3722]
I would like to be able to pass an object from the global scope to the IIFE via an argument. For example:

```js
(function (Scratch) {
	// do stuff
})(Scratch)
```

Is this possible to do with esbuild?

**Comment by evanw** [comment]
You can do that by constructing an IIFE yourself with [banner](https://esbuild.github.io/api/#banner) and [footer](https://esbuild.github.io/api/#footer).

**Comment by evanw** [comment]
I'm closing this issue because this question has been answered.
