### ISSUE TITLE
Get metafile info from a `watch()` rebuild

### ISSUE THREAD

**Issue by puleddu** [evanw/esbuild#3729]
I'm trying to write a build process that uses the built-in watch functionality of esbuild.
Something like:

```js
let ctx = await esbuild.context({
  entryPoints: ['app.js'],
  outfile: 'out.js',
  bundle: true,
})

await ctx.watch()
```

Is there any way to get the `metafile` information in such a config? I was hoping to have access to what iis available in a standard `.build()` script, such as `result.metafile` like in the example below:

```js
let result = await esbuild.build({
  entryPoints: ['app.js'],
  bundle: true,
  metafile: true,
  outfile: 'out.js',
})

fs.writeFileSync('meta.json', JSON.stringify(result.metafile))
```

**Comment by evanw** [comment]
You can use an [`onEnd` callback](https://esbuild.github.io/plugins/#on-end) to be notified of build results in watch mode, which you can then use to access the `metafile` property.

**Comment by puleddu** [comment]
Thank you, this was indeed what I needed.
