### ISSUE TITLE
removes the backslash "\" when minify option is false

### ISSUE THREAD

**Issue by noyobo** [evanw/esbuild#3730]
[esbuild](https://esbuild.github.io/try/#dAAwLjIwLjIAAHZhciBhID0gJzwvc2NyaXB0Pic7CnZhciBiID0gJzxcL3NjcmlwdD4nOwp2YXIgYyA9ICdceDVjZCsnOwp2YXIgZCA9ICdcZCsnOwp2YXIgZSA9ICdcdTAwNWMnOwp2YXIgZiA9ICdcXGQrJzs)

```js
var a = '</script>';
var b = '<\/script>';
var c = '\x5cd+';
var d = '\d+';
var e = '\u005c';
var f = '\\d+';
``` 
output 
```js
var a = "<\/script>";
var b = "<\/script>";
var c = "\\d+";
var d = "d+";
var e = "\\";
var f = "\\d+";
```

## Expected behavior 
Same as rollup, backslash and ascii code will not be deleted.

[Rollup](https://rollupjs.org/repl/?version=4.14.3&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMnZhciUyMGElMjAlM0QlMjAnJTNDJTJGc2NyaXB0JTNFJyUzQiU1Q252YXIlMjBiJTIwJTNEJTIwJyUzQyU1QyU1QyUyRnNjcmlwdCUzRSclM0IlNUNudmFyJTIwYyUyMCUzRCUyMCclNUMlNUN4NWNkJTJCJyUzQiU1Q252YXIlMjBkJTIwJTNEJTIwJyU1QyU1Q2QlMkInJTNCJTVDbnZhciUyMGUlMjAlM0QlMjAnJTVDJTVDdTAwNWMnJTNCJTVDbnZhciUyMGYlMjAlM0QlMjAnJTVDJTVDJTVDJTVDZCUyQiclM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiU3RCUyQyUyMnRyZWVzaGFrZSUyMiUzQWZhbHNlJTdEJTdE)

```js
var a = '</script>';
var b = '<\/script>';
var c = '\x5cd+';
var d = '\d+';
var e = '\u005c';
var f = '\\d+';
```
 output 

```js
var a = '</script>';
var b = '<\/script>';
var c = '\x5cd+';
var d = '\d+';
var e = '\u005c';
var f = '\\d+';
```

Although their syntax is equivalent in js, my running program relies on the ascii code of `\x5c`

When I used esbuild to replace the rollup project, the program ran unexpectedly.

## other repl

- [typescript-playground](https://www.typescriptlang.org/play/?target=1&module=5#code/G4QwTgBCELwQ5AHgPQGcDGYCWAHALgHzwDcAUKJAEawKIA6amuhJ54E6N8dAHgKzoAJgGpWFCIK50RY9gFMpAVwAMygbMgAzKdNHEgA)

**Comment by evanw** [comment]
Sorry, I’m confused. Like you said, `"\\"` and `"\x5c"` are equivalent strings in JavaScript, so this shouldn’t cause an observable difference in behavior. How is it then that these two escape sequences mean different things in your case? 

Are you perhaps using esbuild’s to process something that behaves differently than JavaScript? If so, then that’s outside of esbuild’s scope. JavaScript is deliberately the only scripting language that esbuild is designed to handle. 

Note that if you are interested in preserving the original value of a template literal in JavaScript, you can use a [tagged template literal](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals#tagged_templates) to do that. You may also find [`String.raw`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw) useful.

**Comment by noyobo** [comment]
This is due to the implementation of the .wxs getRegExp function in the WeChat Mini Program. The WeChat applet already has a large user base, so as developers we have to compromise on this writing method 😂

https://developers.weixin.qq.com/miniprogram/en/dev/reference/wxs/06datatype.html#regexp

<img width="252" alt="image" src="https://github.com/evanw/esbuild/assets/1292082/215c822a-7bce-4b22-b99b-ab583549a058">

When I used esbuild to build the executable code that produces the WeChat Mini Program, I found that `getRegExp("\d+")` was changed to `getRegExp("d+")`

I noticed that this phenomenon was also mentioned before https://github.com/evanw/esbuild/issues/3014


[repl](https://esbuild.github.io/try/#dAAwLjIwLjIAAG1vZHVsZS5leHBvcnRzID0gewogIGZuOiBmdW5jdGlvbiAoKSB7CiAgICB2YXIgcjEgPSBnZXRSZWdFeHAoIlx4NWNkKyIpOwogICAgY29uc29sZS5sb2cocjEudGVzdCgnMTIzJykpOyAvLyBmYWxzZQoKICAgIHZhciByMiA9IGdldFJlZ0V4cCgiXGQrIik7CiAgICBjb25zb2xlLmxvZyhyMi50ZXN0KCcxMjMnKSk7IC8vIHRydWUKCiAgICB2YXIgcjMgPSBnZXRSZWdFeHAoIlxcZCsiKTsKICAgIGNvbnNvbGUubG9nKHIzLnRlc3QoJzEyMycpKTsgLy8gZmFsc2UKICB9Cn0)  

There is nothing wrong with the esbuild method and it conforms to JavaScript syntax. But in the face of such a scenario, it is expected that the user's original writing method can be retained.

Can this conversion be selectively turned on as a compression option?

like：

- https://eslint.org/docs/latest/rules/no-useless-escape
- https://biomejs.dev/linter/rules/no-nonoctal-decimal-escape/

It can also be said that `.wxs` files are not JavaScript syntax to some extent.

I know the usage of `String.raw`, but in a case like this, it cannot be applied. Can the writing method of user source code be maintained during the construction process, and can it reduce consistency problems caused by conversion?

Whether the behavior of retaining the original string is beyond the scope of esbuild depends on how you define it. For example, rollup and webpack both process JavaScript, and they can retain the original code writing method.

`.wxs` uses JavaScript syntax, but has execution results that are inconsistent with JavaScript. This is a bit troubling. This behavior can be said to be beyond the scope of JavaScript.

**Comment by noyobo** [comment]
[esbuild repl](https://esbuild.github.io/try/#dAAwLjIwLjIALS1taW5pZnk9ZmFsc2UAdmFyIGEgPSAiPC9zY3JpcHQ+Igp2YXIgYiA9ICI8XC9zY3JpcHQ+IgoK)

I see that `"<\/script>"` is treated specially, keeping the backslashes. If imported using an external file, `<script src="file.js"></script>`. No reservations required. Just don't know how it loads and choose to keep it all the time. Even `"</script>"` will actively add backslashes.

Users know what they are writing and what it is for. They don't write backslashes for no reason. So there seems to be nothing wrong with always keeping the backslash, the syntax is equivalent.

If really need to remove the backslashes, using `eslint` or `biome`. Or minify option to remove it.

**Comment by evanw** [comment]
Sorry, I still don't understand the problem. Here's the code before processing it with esbuild:

```js
var getRegExp = x => new RegExp(x);

var r1 = getRegExp("\x5cd+");
console.log(r1.test('123')); // false

var r2 = getRegExp("\d+");
console.log(r2.test('123')); // true

var r3 = getRegExp("\\d+");
console.log(r3.test('123')); // false
```

That prints `true false true` in any specification-compliant JavaScript engine. Here's the code after processing it with esbuild:

```js
var getRegExp = (x) => new RegExp(x);
var r1 = getRegExp("\\d+");
console.log(r1.test("123"));
var r2 = getRegExp("d+");
console.log(r2.test("123"));
var r3 = getRegExp("\\d+");
console.log(r3.test("123"));
```

That also prints `true false true` in any specification-compliant JavaScript engine. So there doesn't appear to be a problem here. It makes sense that these behave the same because in JavaScript, the string `"\d+"` is the exact same value as `"d+"` (i.e. `"\d+" === "d+"` is true) and the string `"\x5cd+"` is the exact same value as `"\\d+"` (i.e. `"\x5cd+" === "\\d+"` is true).

I'm closing this issue as I do not consider it to be a bug. If you are using a JavaScript engine for which `"\d+" === "d+"` is false, then your JavaScript engine is broken, and you should be working with them to get it fixed. It's not esbuild's job to work around JavaScript engines that are broken like this. This also seems like a very trivial thing to fix in a JavaScript engine if this is indeed a JavaScript engine bug. You are welcome to point them to https://tc39.es/ecma262/#prod-EscapeSequence, specifically the following part of the JavaScript specification:

> * The SV of [_NonEscapeCharacter_](https://tc39.es/ecma262/#prod-NonEscapeCharacter) :: [_SourceCharacter_](https://tc39.es/ecma262/#prod-SourceCharacter) but not one of [_EscapeCharacter_](https://tc39.es/ecma262/#prod-EscapeCharacter) or [_LineTerminator_](https://tc39.es/ecma262/#prod-LineTerminator) is the result of performing [UTF16EncodeCodePoint](https://tc39.es/ecma262/#sec-utf16encodecodepoint) on the code point matched by [_SourceCharacter_](https://tc39.es/ecma262/#prod-SourceCharacter).

**Comment by noyobo** [comment]
My example seems a bit redundant, let's go back to the original question. Just expect esbuild not to remove the original characters. Unless the minify option is explicitly enabled.

**Comment by noyobo** [comment]
Sorry for the .wxs file example mentioned above. I clearly understand the difference between them and the javascript engine (just the syntax is the same). You don't need to understand this, but it has caused you trouble. This example seems inappropriate.

Tools such as webpack rollup babel typescript retain the output of `\d+` when converting the code. If esbuild can also maintain the output of `\d+`, it is enough. like [rollup repl](https://rollupjs.org/repl/?version=4.14.3&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQW51bGwlMkMlMjJtb2R1bGVzJTIyJTNBJTVCJTdCJTIyY29kZSUyMiUzQSUyMnZhciUyMGElMjAlM0QlMjAnJTNDJTJGc2NyaXB0JTNFJyUzQiU1Q252YXIlMjBiJTIwJTNEJTIwJyUzQyU1QyU1QyUyRnNjcmlwdCUzRSclM0IlNUNudmFyJTIwYyUyMCUzRCUyMCclNUMlNUN4NWNkJTJCJyUzQiU1Q252YXIlMjBkJTIwJTNEJTIwJyU1QyU1Q2QlMkInJTNCJTVDbnZhciUyMGUlMjAlM0QlMjAnJTVDJTVDdTAwNWMnJTNCJTVDbnZhciUyMGYlMjAlM0QlMjAnJTVDJTVDJTVDJTVDZCUyQiclM0IlMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTJDJTdCJTIyY29kZSUyMiUzQSUyMiUyMiUyQyUyMmlzRW50cnklMjIlM0FmYWxzZSUyQyUyMm5hbWUlMjIlM0ElMjJtYXRocy5qcyUyMiU3RCU1RCUyQyUyMm9wdGlvbnMlMjIlM0ElN0IlMjJvdXRwdXQlMjIlM0ElN0IlMjJmb3JtYXQlMjIlM0ElMjJlcyUyMiU3RCUyQyUyMnRyZWVzaGFrZSUyMiUzQWZhbHNlJTdEJTdE)

**Comment by noyobo** [comment]
Thanks for your reply.

Yes, esbuild is not a code formatter.

So how do define the behavior of changing `\d+` to `d+`? Compress or transform or format?  Should be the behavior when  `minify.minifySyntax` enabled ? or other options?

I just don't understand why removed backslash as default behavior. no options are provided. 

Is it necessary to remove it because of equivalence? This should be the responsibility of the formatting tool  like *eslint biome*
