### ISSUE TITLE
[Sourcemap] Private properties don't get sourcemapped correctly

### ISSUE THREAD

**Issue by WilliamABradley** [evanw/esbuild#3731]
It seems that JS private properties don't work with sourcemap names correctly, I'm assuming this is an esbuild limitation, instead of a Node limitation.

```
Node v20.11.1
Esbuild v0.20.2
```

Example:

```ts
export class MyAPI {
  #request() { ... }

  doAction() {
    return this.#request(...);
  }
}
```

If there is an error in `#request`, the sourcemapped stack trace looks like:
```
Error: My Error
   at fi.#e (*:*:*)
   at fi.doAction (*:*:*)
   ...
```

It would be nice to able for it to expand `#e` to `#request`.

**Comment by evanw** [comment]
I think this might be a node limitation. Here’s a live example of what esbuild does: [link](https://esbuild.github.io/try/#dAAwLjIwLjIALS1zb3VyY2VtYXAgLS1taW5pZnkAZXhwb3J0IGNsYXNzIE15QVBJIHsKICAjcmVxdWVzdCgpIHt9CgogIGRvQWN0aW9uKCkgewogICAgcmV0dXJuIHRoaXMuI3JlcXVlc3QoKTsKICB9Cn0). And here’s the source map that esbuild generates: [link](https://evanw.github.io/source-map-visualization/#NTUAZXhwb3J0IGNsYXNzIE15QVBJeyN0KCl7fWRvQWN0aW9uKCl7cmV0dXJuIHRoaXMuI3QoKX19CjI1NwB7InZlcnNpb24iOjMsInNvdXJjZXMiOlsiPHN0ZGluPiJdLCJzb3VyY2VzQ29udGVudCI6WyJleHBvcnQgY2xhc3MgTXlBUEkge1xuICAjcmVxdWVzdCgpIHt9XG5cbiAgZG9BY3Rpb24oKSB7XG4gICAgcmV0dXJuIHRoaXMuI3JlcXVlc3QoKTtcbiAgfVxufSJdLCJtYXBwaW5ncyI6IkFBQU8sYUFBTSxLQUFNLENBQ2pCQSxJQUFXLENBQUMsQ0FFWixVQUFXLENBQ1QsT0FBTyxLQUFLQSxHQUFTLENBQ3ZCLENBQ0YiLCJuYW1lcyI6WyIjcmVxdWVzdCJdfQ==). 

As you can see, the name `#request` is already in the source map and is already used in the right places. I’m not sure what else esbuild could do to make this work. It seems like node already has all of the information it needs to be able to do the right thing here.

**Comment by WilliamABradley** [comment]
Hmm, weird.

I guess I'll create a Nodejs issue and see what they think

**Comment by WilliamABradley** [comment]
Trying to do a basic reproduction seems to provide a correctly mapped stack trace which is weird, it must be something environment or runtime, so I'll have to dig deeper.

Closing this for now!
