### ISSUE TITLE
Line limit option (lineLimit) breaks code

### ISSUE THREAD

**Issue by Xerios** [evanw/esbuild#3735]
Unfortunately this is gonna be a very unhelpful bug report because the codebase on which this issue occurs is incredibly large and reproducing a minimal example is hard. Hopefully someone can contribute, or perhaps a warning message could be added in the docs.

Using low values for lineLimit such as 160 or 80 seems to break dynamic import from Vite, then again the generated code is quite different as seen in my results below:

Line limit 160:
```js
prop: ()=>Xn(()=>Promise.resolve().then(()=>BW), "\
__VITE_PRELOAD__"),
```

Line limit 500:
```js
prop: ()=>Xn(()=>Promise.resolve().then(()=>BW), void 0)
```

the actual code itself is a function that imports a svelte file:
```js
prop: () => import('./someSvelteFile.svelte'),
```

My guess is that Vite does a find and replace on `__VITE_PRELOAD__` which breaks when the slash newline is introduced, but I can't say for sure.

**Comment by evanw** [comment]
> My guess is that Vite does a find and replace on `__VITE_PRELOAD__` which breaks when the slash newline is introduced, but I can't say for sure.

That's my guess as well given your description, and given that I think I've read of Vite doing other things like that in the past. But that's not a problem with esbuild. If you need to post-process esbuild's output with such a tool, then perhaps you don't want to use the line limit setting? Either that or the other tool would have to be fixed.

**Comment by Xerios** [comment]
I was wondering if there wasn't already a way to preserve strings through either comment or some option in existing minifiers like terser, but I can't seem to find any. This is probably a very rare edge-case that I stumbled upon.

I'll make a cross-post to Vite to see if they can cover this edge-case.

**Comment by evanw** [comment]
I'm closing this issue because this is not a problem with esbuild. The strings that esbuild is generating are still valid JavaScript strings. It makes sense that tools using regexp-based post-processing don't automatically work with JavaScript like that, but in that case you should be able to disable the line limit setting until the other tools are fixed (or if they decide that it's not a problem worth fixing).

**Comment by thealjey** [comment]
> I'm closing this issue because this is not a problem with esbuild. The strings that esbuild is generating are still valid JavaScript strings. It makes sense that tools using regexp-based post-processing don't automatically work with JavaScript like that, but in that case you should be able to disable the line limit setting until the other tools are fixed (or if they decide that it's not a problem worth fixing).

I really wish esbuild didn't break strings like this at all, no matter the line length limit.
Would it be so bad to at least put it behind a flag and let the user choose if they want long strings broken or not?
