### ISSUE TITLE
`esnext` target doesn't transform using declarations but `es2022` does

### ISSUE THREAD

**Issue by dreamorosi** [evanw/esbuild#3736]
Given the following JavaScript file:

```js
import { fileURLToPath } from 'node:url';

class Test {
  [Symbol.dispose]() {
    console.log("Dispose called");
  }
}


const test = new Test();

const handler = () => {
  using inner = test;
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  handler();
}
```

bundled with this command:

```sh
npx esbuild --bundle src/test.js --platform=node --outdir=out --format=esm --target=esnext
```

according to the [target docs](https://esbuild.github.io/content-types/#javascript), using `esnext` as target should correctly transform the `using` keyword.

However running the bundled `out/test.js` file, results in a runtime `SyntaxError`:

```text
node out/test.js 
file:///Users/dreamorosi/Codes/test-esbuild/out/test.js:10
  using inner = test;
        ^^^^^

SyntaxError: Unexpected identifier 'inner'
    at ModuleLoader.moduleStrategy (node:internal/modules/esm/translators:118:18)
    at callTranslator (node:internal/modules/esm/loader:273:14)
    at ModuleLoader.moduleProvider (node:internal/modules/esm/loader:278:30)
    at async link (node:internal/modules/esm/module_job:76:21)

Node.js v20.9.0
```

looking at the bundled output, this is the content:

```js
// src/test.js
import { fileURLToPath } from "node:url";
var Test = class {
  [Symbol.dispose]() {
    console.log("Dispose called");
  }
};
var test = new Test();
var handler = () => {
  using inner = test;
};
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  handler();
}
```

conversely, using `es2022` as target, seem to produce the correctly downleveled output complete with a `__using` and `__callDispose` polyfill:

<details>

```js
var __knownSymbol = (name, symbol) => {
  return (symbol = Symbol[name]) ? symbol : Symbol.for("Symbol." + name);
};
var __using = (stack, value, async) => {
  if (value != null) {
    if (typeof value !== "object" && typeof value !== "function")
      throw TypeError("Object expected");
    var dispose;
    if (async)
      dispose = value[__knownSymbol("asyncDispose")];
    if (dispose === void 0)
      dispose = value[__knownSymbol("dispose")];
    if (typeof dispose !== "function")
      throw TypeError("Object not disposable");
    stack.push([async, dispose, value]);
  } else if (async) {
    stack.push([async]);
  }
  return value;
};
var __callDispose = (stack, error, hasError) => {
  var E = typeof SuppressedError === "function" ? SuppressedError : function(e, s, m, _) {
    return _ = Error(m), _.name = "SuppressedError", _.error = e, _.suppressed = s, _;
  };
  var fail = (e) => error = hasError ? new E(e, error, "An error was suppressed during disposal") : (hasError = true, e);
  var next = (it) => {
    while (it = stack.pop()) {
      try {
        var result = it[1] && it[1].call(it[2]);
        if (it[0])
          return Promise.resolve(result).then(next, (e) => (fail(e), next()));
      } catch (e) {
        fail(e);
      }
    }
    if (hasError)
      throw error;
  };
  return next();
};

// src/test.js
import { fileURLToPath } from "url";
var Test = class {
  [Symbol.dispose]() {
    console.log("Dispose called");
  }
};
var test = new Test();
var handler = () => {
  var _stack = [];
  try {
    const inner = __using(_stack, test);
  } catch (_) {
    var _error = _, _hasError = true;
  } finally {
    __callDispose(_stack, _error, _hasError);
  }
};
if (process.argv[1] === fileURLToPath(import.meta.url)) {
  handler();
}
```

</details>

The same happens when bundling a TypeScript file.

- `npx esbuild --version` = `0.20.2`
- `node --version` = `v20.9.0`

--

I am not sure if this behavior is intended and I am misunderstanding the docs.

**Comment by evanw** [comment]
You are misunderstanding the docs. This behavior is intended. Passing `esnext` means "preserve all upcoming JavaScript features without transformation" which is what esbuild is doing. This is also what other JavaScript transformers do, such as the TypeScript compiler (compare your code with [ES2022](https://www.typescriptlang.org/play/?target=9#code/JYWwDg9gTgLgBAbzgM2AGwKYFUBKAZAFQgAUBDGACzgF8UoIQ4ByAOwgBMMAuAVyjSYBuAFDCAxmlIBnKXAIYp8BMLhwA2gGUAniABGENADp2wKZCkYAugAoAlIhWq4YiCykGMhtBADm1gEQAIqbmGM6kaJjs-rYiqtTCCaIubvAwCvAAvHAsGADuchl2IuKuinAUpCzsmFBw2Xb1AHwOqjxSwCw+cJ25ddnpiiJJwMhw1mD0YgpShqRQPgBuagCMlvWZ2aiYuIQk5BTWoJCwhiAYMKSGfGi29sqqldW1xYlAA) vs. with [ESNext](https://www.typescriptlang.org/play/?target=99#code/JYWwDg9gTgLgBAbzgM2AGwKYFUBKAZAFQgAUBDGACzgF8UoIQ4ByAOwgBMMAuAVyjSYBuAFDCAxmlIBnKXAIYp8BMLhwA2gGUAniABGENADp2wKZCkYAugAoAlIhWq4YiCykGMhtBADm1gEQAIqbmGM6kaJjs-rYiqtTCCaIubvAwCvAAvHAsGADuchl2IuKuinAUpCzsmFBw2Xb1AHwOqjxSwCw+cJ25ddnpiiJJwMhw1mD0YgpShqRQPgBuagCMlvWZ2aiYuIQk5BTWoJCwhiAYMKSGfGi29sqqldW1xYlAA)).

Another way to think about it is that `esnext` means "I'm running my code in an environment that supports all upcoming JavaScript features, so no transformations are needed" whereas `es2022` means "I'm running my code in an environment that only supports JavaScript features up to the 2022 specification, so transform features newer than that".

> according to the [target docs](https://esbuild.github.io/content-types/#javascript), using `esnext` as target should correctly transform the `using` keyword.

The documentation you linked to is saying the opposite:

| Syntax transform | Transformed when `--target` is below | Example |
|---|---|---|
| [`using` declarations](https://github.com/tc39/proposal-explicit-resource-management) | `esnext` | `using x = y` |

"Transformed when `--target` is below" means that `using` is _not_ transformed when the target is equal to `esnext`, only when it is _below_ `esnext`. The target order is `es6`, `es2016`, `es2017`, `es2018`, ... `esnext` (you can think of "next" like "infinity" if that helps). So "below" means anything that comes before `esnext` in that order.

**Comment by dreamorosi** [comment]
Alright, my bad.

Thank you for explaining and for the patience.

I'll close the issue.
