### ISSUE TITLE
Output is incorrect when there is an import declaration with an import clause that has one type only import specifier

### ISSUE THREAD

**Issue by jordimarimon** [evanw/esbuild#3755]
Maybe there is already an issue about this, I have tried to search and haven't found anything. 

Feel free to close it if it's a duplicate.

The version of esbuild I'm using is `0.21.0`.

### How to reproduce it:

Create two TypeScript files:

**main.ts:**

```typescript
import { type Foo } from "./foo.js";

export class Bar {
   x: Foo | undefined = 3;
}
```

**foo.ts:**

```typescript
export type Foo = number;
```

This is the `tsconfig.json` I used to reproduce it:

```json
{
    "compilerOptions": {
        "baseUrl": "./",
        "target": "ES2022",
        "useDefineForClassFields": false,
        "module": "NodeNext",
        "moduleResolution": "NodeNext",
        "experimentalDecorators": true,
        "noEmitHelpers": false,
        "resolvePackageJsonExports": true,
        "resolveJsonModule": true,
        "removeComments": true,
        "isolatedModules": true,
        "downlevelIteration": true,
        "importHelpers": true,
        "verbatimModuleSyntax": true,
        "allowSyntheticDefaultImports": true,
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "strict": true,
        "declaration": true,
        "noImplicitAny": true,
        "strictNullChecks": true,
        "strictFunctionTypes": true,
        "strictBindCallApply": true,
        "strictPropertyInitialization": true,
        "noImplicitThis": true,
        "useUnknownInCatchVariables": true,
        "alwaysStrict": true,
        "noUnusedLocals": true,
        "noUnusedParameters": true,
        "exactOptionalPropertyTypes": true,
        "noImplicitReturns": true,
        "noFallthroughCasesInSwitch": true,
        "noUncheckedIndexedAccess": true,
        "noImplicitOverride": true,
        "noPropertyAccessFromIndexSignature": true,
        "allowUnusedLabels": true,
        "skipDefaultLibCheck": true,
        "skipLibCheck": true
    }
}
```

Now execute the following command:

```shell
esbuild main.ts --platform=browser --format=esm --target=es2022 --outfile=main.js
```

This is the output I get:

```javascript
import {} from "./foo.js";
class Bar {
  constructor() {
    this.x = 3;
  }
}
export {
  Bar
};
```

If I set the minify option to `true` in the previous command, I get the following:

```javascript
import"./foo.js";class r{constructor(){this.x=3}}export{r as Bar};
```

I would expect the correct output to not have the import declaration.

**Comment by hyrious** [comment]
This is because you have set [`verbatimModuleSyntax: true`](https://www.typescriptlang.org/tsconfig/#verbatimModuleSyntax:~:text=//%20Rewritten%20to%20%27import%20%7B%7D%20from%20%22xyz%22%3B%27). esbuild is generating the effectively same code as TypeScript compiler itself: [TypeScript Playground](https://www.typescriptlang.org/play/?target=99&verbatimModuleSyntax=true#code/JYWwDg9gTgLgBAbzjAnmApnAYhCcC+cAZlBCHAEQB0A9EblQFYDOFA3AFAfoAekscAMYAbAIbNmcAEKioiDnEU8AXNlxwAPnACuAOwAm6IsF3p9cALxwAzJ3xA)

**Comment by jordimarimon** [comment]
I wasn't aware of the fact that the TypeScript compiler also behaves like this. Thanks for pointing it out!

Having said that, is it correct to have an import declaration with an empty import clause? 

What side effects could cause if esbuild dropped entirely the import declaration if only types are being imported?

I can understand that esbuild may want to output similar code as the TypeScript compiler, but right now I don't see why it's important to keep the import declaration.

The reason I have enabled `verbatimModuleSyntax` is because I though that if I gave more information to the "compiler", by explicitly specifying if an import is type only or not, it would give me a more reasonable output but I can disable it if this is generating unused import declarations in the output. 

Feel free to close it if this is the expected behavior.

Thanks for the answer!

**Comment by hyrious** [comment]
> Is it correct to have an import declaration with an empty import clause?

Yes. It is different between importing a module or not importing it at all. The former means to keep any side effects in the dependency. 

For example, if `./foo.js` has code:

```js
// foo.js
console.log('side effect')
```

As a consequence the user ideally should see the log at runtime. That's why the import statement is kept.
