### ISSUE TITLE
Building on top of esbuild Analyze

### ISSUE THREAD

**Issue by jd-carroll** [evanw/esbuild#3757]
Wondering if you would be willing to share the code for https://esbuild.github.io/analyze/ ? Or is it already some place and I am not seeing it (again... 😊) ?

I have a couple of ideas for a new tool which is built on top of the analyzer, but would need to know a little more about how it works. Specifically, if it would be possible to base64 encode (or other means) a metafile as a query string param to have it automatically load.

**Comment by hyrious** [comment]
On GitHub, you can always find the content for `<user>.github.io` at `github.com/<user>/<user>.github.io` for any `<user>`. So the source for [esbuild.github.io](https://esbuild.github.io/) is here: [esbuild/esbuild.github.io](https://github.com/esbuild/esbuild.github.io/tree/main/src/analyze).

> Specifically, if it would be possible to base64 encode (or other means) a metafile as a query string param to have it automatically load.

This is supported. You can checkout its [implementation](https://github.com/esbuild/esbuild.github.io/blob/main/src/analyze/index.ts#L116) to understand the usage. A simple example:

```js
let analyze_url = new URL('https://esbuild.github.io/analyze/')
analyze_url.hash = btoa(JSON.stringify(metafile)).replace(/=+$/, '')
window.open(analyze_url, '_blank')
```

**Comment by jd-carroll** [comment]
@hyrious Thanks, I forgot to check for a separate `esbuild` user
