### ISSUE TITLE
react-compiler support

### ISSUE THREAD

**Issue by last-Programmer** [evanw/esbuild#3769]
Hi,

First of all thank you for this awesome build tool and it has saved us hundreds of hours in build time.

We are using react with typescript in our project. Today in react conf they have released react-compiler https://react.dev/learn/react-compiler#installation

Is there anyway we can use the react-compiler with esbuild in react typescript projects?

Thanks in advance.

**Comment by hyrious** [comment]
@last-Programmer
https://gist.github.com/hyrious/0ec637c7ec2214096cb591062ec73ee0

**Comment by last-Programmer** [comment]
@hyrious thank you very much. it works like a charm.
