### ISSUE TITLE
Import attributes should be enabled for `node18` and >= `node20` targets

### ISSUE THREAD

**Issue by silverwind** [evanw/esbuild#3778]
Import attributes were initially shipped in Node 21, but have recently been backported into 18 and 20 branches, specifically available in v21.0.0, v20.10.0, v18.20.0.

Ref: https://nodejs.org/api/esm.html#import-assertions

Current behaviour enables them only for node 21 and above:
```js
$ echo "import foo from 'foo.json' with {type: 'json'}" | esbuild --target="node20"
import foo from "foo.json";
$ echo "import foo from 'foo.json' with {type: 'json'}" | esbuild --target="node21"
import foo from "foo.json" with { type: "json" };
```

**Comment by evanw** [comment]
Thanks for the heads up! I'll add support for node v18.20+.

> Current behaviour enables them only for node 21 and above:

That's not exactly right. They're already enabled in v20.10+, just not v20+: [(example)](https://esbuild.github.io/try/#dAAwLjIxLjMALS10YXJnZXQ9bm9kZTIwLjEwAGltcG9ydCBmb28gZnJvbSAnZm9vLmpzb24nIHdpdGgge3R5cGU6ICdqc29uJ30)
