### ISSUE TITLE
Getting weird esbuild version when using 0.20.2

### ISSUE THREAD

**Issue by david10sing** [evanw/esbuild#3796]
I have a PNPM monorepo and I am getting the following interesting results...

esbuild is a transitive dependency but when I run the `--version` on the different bin files, I get the following

<img width="580" alt="image" src="https://github.com/evanw/esbuild/assets/6714127/1b19b9ee-8a14-4758-841c-b288c63a379e">

**Comment by evanw** [comment]
That sounds like a good bug report for pnpm.

**Comment by zkochan** [comment]
We cannot fix the issue without steps to reproduce. If you can provide steps to reproduce, we will check. And create a new issue instead of commenting under an issue that was already solved.
