### ISSUE TITLE
Feature request to allow aliases or resolution of modules in addition to node_modules.

### ISSUE THREAD

**Issue by richtera** [evanw/esbuild#380]
I am using esbuild within hugo to build my bundles. We're using my PR inside of hugo in order to add sourcemaps. One thing I am still struggling with might be a good addition into esbuild.
I would like to have an additional argument to specify a list of folders to lookup files similar to how NODE_PATH works.
I will use this to link together the various assets folders in the build. For example if you do `import "main"` it can then look for themes/assets/js/main in each module and then assets/js/main in the root.
Alternatively or in addition it would be great to be able to name this alias like "@assets" so one would do `import "@assets/main"` to do the lookup and `import "main"` would be reserved to node_modules.
Currently I do this by adding additional "mirror copies" called "_main" into each level and then I do `import "./_main"` instead of `import "./main"` to have it look for inherited modules.

**Comment by evanw** [comment]
This should be possible with a `tsconfig.json` or `jsconfig.json` file. This format is documented [in the TypeScript handbook](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping). Here's an example tsconfig.json file that might do what you're asking for:

```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@assets/*": ["themes/assets/js/*", "assets/js/*"]
    }
  }
}
```

**Comment by richtera** [comment]
This is kind of possible, but we have an additional requirement that we're running multiple hugo instances at the same time with different folder paths, and the current hugo version doesn't allow passing in the TSConfig file location.  The only workaround I found was to pass `@assets` as an external and to construct a fake node_modules folder inside of my root js folder inside of assets. Kind of cumbersome, but it will be immediately compatible with a tsconfig.json file as soon as I can use that.

Great idea, thank you. Using the tsconfig configuration will require no changes to ESBuild itself, but only implement the passing of the tsconfig filepath in the hugo pipeline opts.

**Comment by richtera** [comment]
I tried the tsconfig.json solution and in theory, it should actually work, but I am unable to get it to work for some strange reason. It works fine when I execute esbuild from the command line, but when executing it from within the hugo pipeline I don't get enough information as to why it's not working, but it's unable to resolve my modules. It's almost like it's ignoring the tsconfig.json files. I can't quite tell why the execution of esbuild on the command line and within hugo is acting so different; I am trying to match the exact arguments I am sending esbuild into the build options inside of hugo. Not sure, but I can't get it to work.

**Comment by richtera** [comment]
Yes it works. I had { "paths": { } } instead of { "compilerOptions": { "paths": { } }.
Unfortunately, I had to debug hugo to figure out where the resolver was not finding my path :).
But that's what debuggers are for!

**Comment by richtera** [comment]
There is a slight issue with "index.js" files.
If you declare
```json
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@assets/*": ["themes/assets/js/*", "assets/js/*"]
    }
  }
}
```
as above then
doing
`import "@assets"`
will always resolve to "themes/assets/js/index.js" as long as the `themes/assets/js` folder exists.
The resolve just checks for the existence and IsAbs of the path but not the existence of an index.js file within the path.
Removing `themes/assets/js` will then resolve to the next folder so the resolver is properly checking for the existence of the folder.

**Comment by richtera** [comment]
Added a workaround into the hugo PR to add full match names to search for index files.
For example
```javascript
      "@assets": [
        "./../../../../assets/js/index.tsx",
        "./../../../../assets/js/index.ts",
        "./../../../../assets/js/index.jsx",
        "./../../../../assets/js/index.mjs",
        "./../../../../assets/js/index.cjs",
        "./../../../../assets/js/index.js",
        "./../../../../assets/js/index.json",
        "./../js/index.tsx",
        "./../js/index.ts",
        "./../js/index.jsx",
        "./../js/index.mjs",
        "./../js/index.cjs",
        "./../js/index.js",
        "./../js/index.json",
        "./../../../module-student-template-combined@feature-data-builds/assets/js/index.tsx",
        "./../../../module-student-template-combined@feature-data-builds/assets/js/index.ts",
        "./../../../module-student-template-combined@feature-data-builds/assets/js/index.jsx",
        "./../../../module-student-template-combined@feature-data-builds/assets/js/index.mjs",
        "./../../../module-student-template-combined@feature-data-builds/assets/js/index.cjs",
        "./../../../module-student-template-combined@feature-data-builds/assets/js/index.js",
        "./../../../module-student-template-combined@feature-data-builds/assets/js/index.json"
      ],
```

**Comment by Maxattax97** [comment]
Looking for the same feature, but we're not using Typescript, so NODE_PATH or maybe CLI flag is the only way we can do it (other than butchering our file structure).

**Comment by richtera** [comment]
This actually works with jsconfig or tsconfig so it works with typescript or javascript. Are you expecting to see the jsconfig/tsconfig files during development or just during compile time?

**Comment by Maxattax97** [comment]
Took me a bit, but I got it working, thanks for pointing that out @richtera . This is my `jsconfig.json`:
```
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "*": [
        "Lib/*",
        "node_modules/*",
        "*"
      ]
    }
  }
}
```

**Comment by jellelicht** [comment]
Would it be possible to directly use the actual `NODE_PATH` environment variable? It would make esbuild very useful for distro packagers.

**Comment by evanw** [comment]
I'm going to close this because completely custom path resolution is now possible using a plugin: https://esbuild.github.io/plugins/#resolve-callbacks.

**Comment by evanw** [comment]
FWIW esbuild should now support `NODE_PATH`.
