### ISSUE TITLE
`entryPoints` does not support glob patterns

### ISSUE THREAD

**Issue by dwelle** [evanw/esbuild#381]
Glob patterns in `entryPoints` are not supported:

```
const { build } = require('esbuild');
build({
  entryPoints: './src/*.ts',
  /* ... */
});
```

throws:

```
error: Duplicate entry point "../../../../../.."
error: Duplicate entry point "."
error: Duplicate entry point "s"
```

When specified as an array (`entryPoints: ["./src/*.ts"]`), it throws:

```
error: Cannot read file "src/*.ts"
```

**Comment by rtsao** [comment]
You could always do something like this:

```js
const { build } = require("esbuild");
const glob = require("tiny-glob");

(async () => {
  let entryPoints = await glob("./src/*.ts");
  await build({
    entryPoints,
    /* ... */
  });
})();
```

**Comment by dwelle** [comment]
I know. I just thought it should either be 1) supported 2) handled (display user-friendly error) & documented.

**Comment by evanw** [comment]
The reason why this looks so weird here is that `entryPoints` is supposed to be an array of strings:

https://github.com/evanw/esbuild/blob/5e0dabffb29594acd7685981d1b1563aab1ea1bc/lib/types.ts#L44

Passing a string instead causes esbuild to iterate over the characters in the string and treat each character as an entry point path. I will add an error for this case if you pass invalid data for the `entryPoints` array.

**Comment by dwelle** [comment]
True (oh the joys of writing plain JS files instead of TS). I actually started with an array, and the error there is at least readable :).

**Comment by kuba-orlik** [comment]
> You could always do something like this:
> 
> ```js
> const { build } = require("esbuild");
> const glob = require("tiny-glob");
> 
> (async () => {
>   let entryPoints = await glob("./src/*.ts");
>   await build({
>     entryPoints,
>     /* ... */
>   });
> })();
> ```

This solution is far from perfect, as it doesn't require new files - that is, files created *after* watch has been started

**Comment by allomov** [comment]
Thank you! It was also acceptable to me to use `resolve-glob` with `glob.sync`, like this: 
```javascript
const glob = require('resolve-glob');

const options = {ignore: ["**/*.test.js", "**/*.spec.js", "**/*.stories.js"]};
const entryPoints = glob.sync(
  [
    "./app/javascript/**/*.ts",
    "./app/javascript/**/*.tsx",
    "./app/javascript/**/*.js",
    "./app/javascript/**/*.jsx"
  ],
  options)

build({
  entryPoints: entryPoints,
  // ...
}).catch(() => process.exit(1))
```

**Comment by ngdangtu-vn** [comment]
Do we have any solution for CLI version guys?
