### ISSUE TITLE
esbuild-wasm Unable to set globalName，error: -- window name=__dependency__

### ISSUE THREAD

**Issue by gitfei1231** [evanw/esbuild#3811]
tips:
It is normal to package the library into both ESM and CJS, and it can be used. However, it is not possible to package the iife now, as it is not possible to set the globalName

error:

After setting the `format: "iife"` and `globalName: '__dependency__'` in the esbuild wasm packaging library code, the package keeps showing an `index. ts:62 build dep err Error: Invalid build flag: "-- window name=__dependency__"`

<img src="https://github.com/evanw/esbuild/assets/5179891/d5bbf9b3-6694-49f0-bc03-19c20f2ab5db" />

code:
```js
async function buildBundle() {
    try {
        const result = await esbuild.build({
          entryPoints: ['/node_modules/echarts/echarts.all.js'],
          outdir: "/",
          bundle: true,
          minify: false,
          write: false,
          mainFields: ["browser", "module", "main"],
          logLevel: "silent",
          metafile: true,
          target: "esnext",
          jsxImportSource: "react",
          jsx: "automatic",
          sourcemap: false,
          supported: {
            "const-and-let": true
          },
          format: "iife",
          globalName:'__dependency__',
          plugins: [
             // A plugin written by oneself that can parse paths normally
          ]
        });
        
        console.log( result.outputFiles[0].text )
    } catch (o) {
      console.error("build dep err", o)
    }
  }
``

**Comment by gitfei1231** [comment]
@evanw help me

**Comment by hyrious** [comment]
[There's no `window-name` in the esbuild-wasm/lib/browser.js,](https://hyrious.me/npm-browser/?q=esbuild-wasm@0.21.5/package/lib/browser.js:351) only `global-name`. I guess that your bundler / config **replaces** `'global'` with `'window'` by doing a simple text search and replace.

**Comment by gitfei1231** [comment]
> [There's no `window-name` in the esbuild-wasm/lib/browser.js,](https://hyrious.me/npm-browser/?q=esbuild-wasm@0.21.5/package/lib/browser.js:351) only `global-name`. I guess that your bundler / config **replaces** `'global'` with `'window'` by doing a simple text search and replace.
> 
> To confirm what I said, you can click on the browser.js:633:9 in the error message from devtools console, and search for `globalName` and `window-name` in that file to see if it is the same as [the published one](https://hyrious.me/npm-browser/?q=esbuild-wasm). Note that you may need to see the final js file instead of the source-mapping-ed file.

Thank you so much. I never thought of this problem. It was indeed this problem

**Comment by gitfei1231** [comment]
@hyrious Thank you very much

**Comment by gitfei1231** [comment]
> > [There's no `window-name` in the esbuild-wasm/lib/browser.js,](https://hyrious.me/npm-browser/?q=esbuild-wasm@0.21.5/package/lib/browser.js:351) only `global-name`. I guess that your bundler / config **replaces** `'global'` with `'window'` by doing a simple text search and replace.
> > To confirm what I said, you can click on the browser.js:633:9 in the error message from devtools console, and search for `globalName` and `window-name` in that file to see if it is the same as [the published one](https://hyrious.me/npm-browser/?q=esbuild-wasm). Note that you may need to see the final js file instead of the source-mapping-ed file.
> 
> Thank you very much. I never thought of this problem. It was indeed this problem

**Comment by evanw** [comment]
That is a very strange problem. I wonder what is transforming esbuild's internals like this. In any case, it sounds like this question has been resolved, so I'm closing this issue.
