### ISSUE TITLE
feature request - annotate function code 

### ISSUE THREAD

**Issue by unilynx** [evanw/esbuild#3814]
(This may be out-of-scope for esbuild, and I accept immediate dismissal, but I'm going to try anyway as esbuild is already deeply integrated into our projects)

Would it be possible to add an option to have esbuild annotate (all/selectively) every line of code in a function with an external call describing file, location and the actual code? 

Eg

```
async function testCleanup() { //.. if this is line 1 of the source file..
  await beginWork();
  if(true)
    await runQuery();
  await commitWork();
}
```

would become with `esbuild --annotateCall __log --annotateFunctions '^test.*$'`:

```
async function testCleanup() { 
  __log('project/sub/dir/test-db.ts', 'testCleanup'); // signals start of function
  __log(2, '  await beginWork()'); // describes line 2
  await beginWork();
  __log(3, '  if (true)');
  if (true) { //insert block, esbuild should already know when it's needed
    __log(4, '    await runQuery();');
    await runQuery();
  }
  __log(5, '  await commitWork()');
  await commitWork();
  __log(null); //marks end of function
}
```

async context tracking should allow whoever implements __log to deal with interleaved function calls. with this, I'd be able to have test runners exactly pinpoint where all async contexts were at the moment an Error was thrown, do some adhoc profiling, generate line based profile information and I'm sure there's an AI startup in there somewhere. and it certainly beats manually adding console.log statements when pinning down the actual execution flow

I'm sure this can be sort of done outside esbuild or with some preprocessing, but esbuild sits at exactly the right spot to generate this code without too much overhead.

**Comment by evanw** [comment]
Yes this is outside of esbuild's scope. Sorry about that. You're probably looking for an AST-based JavaScript transformation tool that lets you do this type of custom stuff, which is not what esbuild is. For example, SWC exposes an [AST visitor API](https://swc.rs/docs/plugin/ecmascript/getting-started) that you might be able to use to do something like this (note that I have never used SWC myself, I'm just pretty sure it's intended for this stuff). It's implemented with native code so it probably qualifies as "without too much overhead" for you.

**Comment by evanw** [comment]
I'm closing this issue as I consider this to be out of scope.
