### ISSUE TITLE
 Dynamic require of "https" is not supported

### ISSUE THREAD

**Issue by bharathimarella** [evanw/esbuild#3815]
I'm getting  **Dynamic require of "https" is not supported** error when i try to turn a js file to generate cypress reports.I see this is related to esbuild .How to fix this issue ?

**Comment by evanw** [comment]
You will probably find your answer by reading the documentation:

* https://esbuild.github.io/api/#non-analyzable-imports
* https://esbuild.github.io/getting-started/#bundling-for-node

**Comment by evanw** [comment]
I'm closing this because it's not a bug with esbuild, and the ways to avoid this problem are already documented in the "getting started" instructions.
