### ISSUE TITLE
esbuild 0.22.0 not bundling node ESM modules correctly

### ISSUE THREAD

**Issue by benkaiser** [evanw/esbuild#3817]
This is likely user-error here, but with esbuild 0.21.5 I can run:

```
esbuild ./src/app.ts --format=cjs --bundle --outfile=dist/app.js --platform=node --target=node20.0
```
And I get:
```
  dist/app.js  4.7mb ⚠️

⚡ Done in 181ms
```

Where the entire contents of everything my app depends on in in the one file (as expected).

But under esbuild 0.22.0 I get a tiny file that is trying to do a bunch of ESM conversion. Same command results in:

```
  dist/app.js  2.9kb

⚡ Done in 23ms
```

And inspecting the file, the import lines just look like this, without pulling in the contents of those dependencies into the bundle.

```
var import_express = __toESM(require("express"));
var import_mongoose = __toESM(require("mongoose"));
```

This results in node not being able to run the file (which I'm sure is a configuration issue I can resolve, but it's just frustrating because esbuild isn't doing what I expect).

**Comment by hyrious** [comment]
This is probably because esbuild 0.22 makes `--packages=external` default when `--platform=node`. See [the changelog](https://github.com/evanw/esbuild/releases/tag/v0.22.0). You can revert to previous behavior with `--packages=bundle`.

**Comment by barendb** [comment]
This change should have been a major version bump... tsk tsk... imagine how many downstream systems just relied on the previous default

**Comment by evanw** [comment]
This is already explained in the release notes:

> **This release deliberately contains backwards-incompatible changes.** To avoid automatically picking up releases like this, you should either be pinning the exact version of esbuild in your package.json file (recommended) or be using a version range syntax that only accepts patch upgrades such as ^0.21.0 or ~0.21.0. See npm's documentation about [semver](https://docs.npmjs.com/cli/v6/using-npm/semver/) for more information.

The major version is 0 so the minor version is used for breaking changes.

**Comment by dreamorosi** [comment]
Hi @evanw - I'm ok with the change & how it was communicated, however I was wondering if you could clarify this statement from the release notes:

> This breaking change is an experiment.

What did you mean with this? Does this mean the change could be reverted?

Just trying to evaluate whether we should pin to older versions of `esbuild` or upgrade our CDK pipelines to set the `--packages=bundle` flag. I'm okay with the latter, but if there're plans of maybe reverting the change I'll wait it out and pin to `0.21.0` in the meanwhile.

---

Also, for anyone using CDK who stumbles into this issue, this is how you set the flag:

```ts
const fn = new NodejsFunction(this, 'MyFunction', {
  functionName: fnName,
  runtime: Runtime.NODEJS_20_X,
  entry: './src/index.ts',
  handler: 'handler',
  bundling: {
    minify: true,
    mainFields: ['module', 'main'],
    sourceMap: true,
    format: OutputFormat.ESM,
    platform: 'node',
    esbuildArgs: {
      '--packages': 'bundle' // <- behaves like before esbuild 0.22
    }
  },
});
```

**Comment by bergarces** [comment]
Just so you are aware, anyone building lambdas with `sam build` that installs esbuild globally on CI with `npm i -g esbuild` without any locked version (which admittedly they shouldn't do), is about to have a very bad day.

**Comment by benkaiser** [comment]
> This is probably because esbuild 0.22 makes `--packages=external` default when `--platform=node`. See [the changelog](https://github.com/evanw/esbuild/releases/tag/v0.22.0). You can revert to previous behavior with `--packages=bundle`.

Thanks for the info. Happy to close this then.

**Comment by KamaniBhavin** [comment]
I'm still encountering issues with AWS CDK, even after trying the following:

- Upgraded to **esbuild: 0.22.0** and used `--packages=bundle` instead of the default setting — still doesn't work.
- Pinned **esbuild to 0.21.5** and explicitly set `bundling.esbuildVersion` to `0.21.5`.

I've gone through all the suggestions provided here and on [this GitHub issue](https://github.com/aws/aws-cdk/issues/30717), but nothing seems to resolve the problem. 

Could anyone please help me figure out what's going wrong?

**Comment by KamaniBhavin** [comment]
Thanks, @WtfJoke, for taking the time to look into it and offer your feedback. I was able to pinpoint the cause of the issue and find a solution. For future reference, in my case, the problem was related to another package [Electro DB](https://github.com/tywalch/electrodb) that needed an update. While I'm still not entirely sure why this was causing the issue, updating the package resolved it for me.
