### ISSUE TITLE
JSX option "preserve" discards whitespace

### ISSUE THREAD

**Issue by bterlson** [evanw/esbuild#3818]
The JSX preserve transform discards leading whitespace within a JSXElement and prior to a child JSXElement, and discards trailing whitespace after a child JSXElement . See this [example here](https://esbuild.github.io/try/#dAAwLjIyLjAAewogIGxvYWRlcjogJ2pzeCcsCiAganN4OiAncHJlc2VydmUnLAp9ADxGb28+CgoKICA8QmFyIC8+CgogIGEKICBiCiAgYwoKCiAgPEJhciAvPgoKCgo8L0Zvbz4) where the output JSX for `Foo` 
should contain more whitespace at the start and end of the component.

**Comment by evanw** [comment]
I'm not sure why you're linking to version 0.19.11, which came out at the beginning of this year. In the very next version ([version 0.19.12](https://github.com/evanw/esbuild/releases/tag/v0.19.12)), this behavior was changed to [do exactly what you're suggesting](https://esbuild.github.io/try/#dAAwLjE5LjEyAHsKICBsb2FkZXI6ICdqc3gnLAogIGpzeDogJ3ByZXNlcnZlJywKfQA8Rm9vPgoKICB0ZXN0aW5nIDEgMiAzCgogIDxCYXIgLz4KCiAgYQogIGIKICBjCjwvRm9vPg). So esbuild already works the way you want. You just need to use a newer release of esbuild.

**Comment by bterlson** [comment]
My apologies! I will blame it on having 1000 tabs open late at night and will try not to think about this when I'm trying to fall asleep for years to come.

**Comment by bterlson** [comment]
Ahh sorry again, there is a case which does repro in [the latest version](https://esbuild.github.io/try/#dAAwLjIyLjAAewogIGxvYWRlcjogJ2pzeCcsCiAganN4OiAncHJlc2VydmUnLAp9ADxGb28+CgoKICA8QmFyIC8+CgogIGEKICBiCiAgYwo8L0Zvbz4) which explains how I noticed something wrong. I'll update the original issue text.
