### ISSUE TITLE
Doesn't preserve comments

### ISSUE THREAD

**Issue by ghost** [evanw/esbuild#3837]
If not minified I would expect my comments in original code to be printed. Instead they are not attached.

This is crucial when maintaining a bigger project or team members works together.

Typescript prints comments as one example

Multiline comments in a few places are preserved, but no single line.

```ts
"use strict"; /*--*/

"use strict"; //hello
```

Will not preserve the comments

**Comment by akellbl4** [comment]
Comments are preserved in resulting file when they have @preserve in them.
e.g. `/* my comment -- @preserve */`
[Docs](https://esbuild.github.io/api/#legal-comments)

**Comment by Tcjmd** [comment]
That means if I got 200k lines of code with comments etc, I first need to manually add  @preserve in all comments

Sounds complicated

**Comment by evanw** [comment]
I'm closing this issue as the user account that reported it has been deleted.
