### ISSUE TITLE
Comments are not preserved inside `switch...case`

### ISSUE THREAD

**Issue by akellbl4** [evanw/esbuild#3838]
When a comment is placed inside `switch` block above `case` or `default` it is not preserved in the transpiled code.

- [Build example](https://esbuild.egoist.dev/#W1siaW5kZXgudHMiLHsiY29udGVudCI6ImV4cG9ydCBlbnVtIE9wdGlvbnMge1xuICBGb28gPSAnZm9vJyxcbiAgQmFyID0gJ2JhcicsXG59XG5leHBvcnQgZnVuY3Rpb24gZXhhbXBsZShvcHRpb246IE9wdGlvbnMpIHtcbiAgc3dpdGNoIChvcHRpb24pIHtcbiAgICBjYXNlIE9wdGlvbnMuRm9vOiB7XG4gICAgICByZXR1cm4gJ0Zvb29vb28hJztcbiAgICB9XG4gICAgY2FzZSBPcHRpb25zLkJhcjoge1xuICAgICAgcmV0dXJuICdCYWFhYWFyISc7XG4gICAgfVxuICAgIC8qIFRoaXMgaXMgcmVtb3ZlZCAtLSBAcHJlc2VydmUgKi9cbiAgICAvKiBpc3RhbmJ1bCBpZ25vcmUgbmV4dCAtLSBAcHJlc2VydmUgKi9cbiAgICBkZWZhdWx0OiB7XG4gICAgICAvKiBUaGlzIGlzIHByZXNlcnZlZCAtLSBAcHJlc2VydmUgKi9cbiAgICAgIC8qIGlzdGFuYnVsIGlnbm9yZSBuZXh0IC0tIEBwcmVzZXJ2ZSAqL1xuICAgICAgcmV0dXJuICdOb3QgYSBmb28sIG5vdCBhIGJhcic7XG4gICAgfVxuICB9XG59XG4ifV0sWyJlc2J1aWxkLmNvbmZpZy5qc29uIix7ImNvbnRlbnQiOiJ7XG4gIFwiZm9ybWF0XCI6IFwiY2pzXCIsXG4gIFwiY2RuVXJsXCI6IFwiaHR0cHM6Ly9jZG4uc2t5cGFjay5kZXZcIixcbiAgXCJsZWdhbENvbW1lbnRzXCI6IFwiaW5saW5lXCJcbn0ifV0sWyJzdW0udHMiLHsiY29udGVudCI6ImV4cG9ydCBjb25zdCBzdW0gPSAoYTogbnVtYmVyLCBiOiBudW1iZXIpID0+IGEgKyBiIn1dXQ==)
- [Example with vitest](https://stackblitz.com/edit/github-rzcfqv?file=src%2Fbasic.ts)  where istanbul comment is stripped
- [Related issue](https://github.com/vitest-dev/vitest/issues/6153) in vitest repo

**Comment by Tcjmd** [comment]
@evanw any update on this issue?

**Comment by evanw** [comment]
The "legal comments" mechanism isn't designed for this use case. Legal comments are intended to be present but the specifics of where they are in the source code isn't supposed to matter. Legal comments are currently supported at the statement level but these things aren't statements (specifically a `CaseBlock` is a sequence of `CaseClauses` in JavaScript). I could "fix" what you're asking for by moving the comments into the case block so they are preserved (which is all the `@preserve` tag means), but that wouldn't achieve what you're trying to do.

What you're really asking for is for esbuild to support Istanbul's specific comment meta-language, which is not something that esbuild supports. You can read more about what supporting that would mean here: https://github.com/evanw/esbuild/issues/578#issuecomment-739787682. It's very non-trivial.

I can try treating these as expression-level comments for now (which they aren't), which will attempt to preserve them as long as minification is disabled. It still won't treat them as legal comments, but perhaps that is enough for this use case.
