### ISSUE TITLE
Doesn't fail on some cases

### ISSUE THREAD

**Issue by ghost** [evanw/esbuild#3846]
Esbuild doesn't seem to fail on a few edge cases.

@evanw seems to be an issue with the regEx validations? Many cases should fail

```ts

({a} += 0);

[(x = y)] = obj

[{x = y}.z] = obj



// RegEx cases

/(?<a\\\\uD801>.)/u

/(?<a\\\\uDCA4>.)/u

/(?<\\\\>.)/u


```

**Comment by Tcjmd** [comment]
@evanw  this cases are from Babel and should fail?  

```ts
for (var a = (b in c) in {});
for (var a = 1 || (b in c) in {});
for (var a = 1 + (2 || (b in c)) in {});
for (var a = (() => b in c) in {});
for (var a = 1 || (() => b in c) in {});
for (var a = (() => { b in c; }) in {});
for (var a = [b in c] in {});
for (var a = {b: b in c} in {});
for (var a = (x = b in c) => {} in {});
```

**Comment by Tcjmd** [comment]
edge case

```ts
switch (x) {case a: function f(){}; break; case b: function f(){}; break; }
```

**Comment by evanw** [comment]
> seems to be an issue with the regEx validations? Many cases should fail

Regular expression validation is not something that esbuild currently does. Garbage in, garbage out.

> this cases are from Babel and should fail?
> 
> ```ts
> for (var a = (b in c) in {});
> for (var a = 1 || (b in c) in {});
> for (var a = 1 + (2 || (b in c)) in {});
> for (var a = (() => b in c) in {});
> for (var a = 1 || (() => b in c) in {});
> for (var a = (() => { b in c; }) in {});
> for (var a = [b in c] in {});
> for (var a = {b: b in c} in {});
> for (var a = (x = b in c) => {} in {});
> ```

Sorry, I don't understand. Fail how? These are valid JavaScript. For example, `for (var a = 1 || (b in c) in {});` runs without problems in browsers and in node.

> edge case. This behavior and others depends on AnnexB is on / of.
> 
> Typescript handle AnnexB so worth mention. Maybe add an option for use of AnnexB

This is a very obscure edge case. Why is this important to you? What is your use case?

**Comment by Tcjmd** [comment]
`for cases` with `var` is edge cases when using `=` and toggling between AnnexB. If I remember correctly should only throw if AnnexB and / or strict mode. 

Bindings in `Try` and `Switch` statements behaves different too while toggling AnnexB.

For this case `({a} += 0);`; Only `=` are allowed here

**Comment by Tcjmd** [comment]
This
[test cases]( https://github.com/shapesecurity/shift-parser-js/blob/es2019/test/early-errors.js#L491 ) may be helpful. Points to the specs.

**Comment by evanw** [comment]
Realistically the vast majority of JavaScript runs under Annex B, so esbuild treats Annex B as a reality. I'm not convinced that the ability to toggle off Annex B in esbuild is worth supporting at all. It would add a lot of testing and maintenance overhead to support a rare type of environment in which almost no real JavaScript runs. That's why I'm asking you why the ability to toggle off Annex B is important to you.

**Comment by Tcjmd** [comment]
In my use case it's not important. I brought it up only because it's part of the specs. And Typescript seem to support it e.g in their regEx scanner

**Comment by evanw** [comment]
I'm closing this issue as the user account that reported it has been deleted.
