### ISSUE TITLE
minifyIdentifiers has undocumented behaviour

### ISSUE THREAD

**Issue by hesxenon** [evanw/esbuild#3847]
I noticed that when using react and react-dom I was unable to use the minified react-dom version unless I set `minifyIdentifiers: true` which I can't do because a library I depend on doesn't cope with that.

Maybe I missed something in the docs, but why or how does esbuild choose the version to include? The exports field of react-doms package.json also does not specify that, I'm really puzzled here.

EDIT: I found the switch in react-dom/index.js. The funny thing is, I do have `NODE_ENV=production` set, yet the `require('react-dom')` within react-dom/index.js does not seem to inherit this?

**Comment by evanw** [comment]
You didn't provide a way to reproduce your issue so I can't be sure, but I assume you're encountering the behavior that's documented here https://esbuild.github.io/api/#platform:

> When using the [build](https://esbuild.github.io/api/#build) API, all `process.env.NODE_ENV` expressions are automatically [defined](https://esbuild.github.io/api/#define) to `"production"` if all [minification](https://esbuild.github.io/api/#minify) options are enabled and `"development"` otherwise. This only happens if `process`, `process.env`, and `process.env.NODE_ENV` are not already defined. This substitution is necessary to avoid React-based code crashing instantly (since `process` is a node API, not a web API).

**Comment by hesxenon** [comment]
hmmm, I already have `NODE_ENV` set to "production" (as mentioned in #3848) but for some reason it doesn't seem to reach the react-dom/index.js in this case. I'll see if I can provide a minimal repro.

**Comment by hesxenon** [comment]
okay, so minimal repro is quite easy.
1. with pnpm (8.15.5 but shouldn't matter, same happens with 9x) install `react{,-dom}`
2. create an index.js demo file like this.
    ```ts
    import React from "react";
    import ReactDOM from "react-dom/client";
    
    const root = ReactDOM.createRoot(document.body);
    
    root.render(React.createElement("div", {}, "Hello World"));
    ```
    So this is just a tiny react demo app
3. run `NODE_ENV=production npx esbuild index.js --analyze --bundle --outfile=/dev/null`

My expectation would be that react-dom.production.min.js is included but apparently `NODE_ENV=production` does not "survive" until the switch statement for some reason?

`NODE_ENV=production npx esbuild index.js --analyze --bundle --minify --outfile=/dev/null` works however.

**Comment by hyrious** [comment]
esbuild does not read env variables, instead it will define `process.env.NODE_ENV` by whether `--minify` passed in. So if you want to define that manually you can do: `--define:process.env.NODE_ENV="production"`.

**Comment by hesxenon** [comment]
okay, that works as expected. Now the only question that remains is - which portion of the docs did I miss here? I've been using esbuild now for a few years and maybe I'm just getting confused from all the different build tools but I don't remember reading that :thinking: 

Though evans phrasing of the linked platform docs makes a lot more sense now...

In any case, thx for the help, closing
