### ISSUE TITLE
[lexical][prism] The code seems to have been incorrectly elevated while minimizing

### ISSUE THREAD

**Issue by wszgrcy** [evanw/esbuild#3850]
version: 0.21.5
I built it using Angular CLI
Import Lexical package
Everything is normal during development
But there were problems with the packaging during production
Finally, it was found that the position of the prism code introduced by Lexical was different from that during development
During development:

![image](https://github.com/user-attachments/assets/ab46e960-a3b2-44a4-a6eb-5dea3beda28e)

During production:
![image](https://github.com/user-attachments/assets/60343447-c387-40a7-b6c7-78bb05b312c7)
![image](https://github.com/user-attachments/assets/82bd2fb4-9d2b-493e-82b1-6eb236e84627)
![image](https://github.com/user-attachments/assets/6fda5854-9fb0-4d61-ae23-1a6a6ad91830)

**Comment by wszgrcy** [comment]
demo: https://github.com/wszgrcy/angular-lexical-build-error

**Comment by hyrious** [comment]
This minimal case to trigger this error is when esbuild bundles [`@lexical/code`](https://hyrious.me/npm-browser/?q=@lexical/code@0.16.1/package/LexicalCode.mjs) and hits its weird dual export entry with `--minify` (which means defining `process.env.NODE_ENV="production"`):

```js
// node_modules/@lexical/code/LexicalCode.mjs
import * as modDev from './LexicalCode.dev.mjs';
import * as modProd from './LexicalCode.prod.mjs';
const mod = process.env.NODE_ENV === 'development' ? modDev : modProd;
export const $createCodeHighlightNode = mod.$createCodeHighlightNode;
// ...
```

So the reprodcution without angular cli could be like this:

```js
// entry.js
import {CodeHighlightNode} '@lexical/code'
console.log(CodeHighlightNode)
```

```console
$ esbuild entry.js --bundle --outdir=dist --define:process.env.NODE_ENV=\"production\"
```

[Playground Link](https://esbuild.github.io/try/#YgAwLjIzLjAALS1idW5kbGUgLS1kZWZpbmU6UFJPRD10cnVlAGUAZW50cnkuanMAaW1wb3J0ICogYXMgZGV2IGZyb20gJy4vZGV2JwppbXBvcnQgKiBhcyBwcm9kIGZyb20gJy4vcHJvZCcKY29uc3QgbW9kID0gUFJPRCA/IHByb2QgOiBkZXYKZXhwb3J0IGNvbnN0IGZvbyA9IG1vZC5mb28AAGRldi5qcwBpbXBvcnQgJ3ByaXNtJwppbXBvcnQgJ3ByaXNtL3BsdWdpbicKZXhwb3J0IGNvbnN0IGZvbyA9ICdkZXYnAABwcm9kLmpzAGltcG9ydCAncHJpc20nCmltcG9ydCAncHJpc20vcGx1Z2luJwpleHBvcnQgY29uc3QgZm9vID0gJ3Byb2QnAABub2RlX21vZHVsZXMvcHJpc20vaW5kZXguanMAdmFyIFByaXNtID0ge30KaWYgKHR5cGVvZiBtb2R1bGUgPT09ICdvYmplY3QnKQogIG1vZHVsZS5leHBvcnRzID0gUHJpc20AAG5vZGVfbW9kdWxlcy9wcmlzbS9wbHVnaW4uanMAUHJpc20ucGx1Z2luID0ge30AAHBhY2thZ2UuanNvbgB7InNpZGVFZmZlY3RzIjpmYWxzZX0AAG5vZGVfbW9kdWxlcy9wcmlzbS9wYWNrYWdlLmpzb24AeyJuYW1lIjoicHJpc20ifQ)

I'm not quite sure what happened here, but here are some guesses:

- `import * as ns` in esbuild will make the depended module be wrapped with a namespace object, generating something like `__export(prod_exports, { foo: () => foo })` and `var import_prism = __toESM(require_prism())`.
- The `var import_prism = __toESM(require_prism())` statement is delayed to where it was actually depended, which is at the prod entry.
- `import 'prismjs/components/prism-javascript.js';`, does not say it is depending on the 'prism' module, and is occured both in the dev and prod entry. So it is lift up as a shared dependency. Although internally it is actually depending on the execution order of 'prism' to run first. So here 'prismjs/components/prism-javascript.js' is lift up before 'prism', causing the error.

To solve this error, at least as a workaround, is to set [`--conditions`](https://esbuild.github.io/api/#conditions) in esbuild options to select the prod entry file directly without touching the weird dual entry. I don't know if angular has the place to put this option but, here it is:

```js
esbuild.build({
  conditions: ['production']
})
```
