### ISSUE TITLE
Question about ShouldFoldBinaryOperatorWhenMinifying

### ISSUE THREAD

**Issue by hsiaosiyuan0** [evanw/esbuild#3854]
hi evanw, 

I'm learning esbuild's source code, I have a question about this function [ShouldFoldBinaryOperatorWhenMinifying](https://github.com/evanw/esbuild/blob/78f89e41d5e8a7088f4820351c6305cc339f8820/internal/js_ast/js_ast_helpers.go#L1184-L1190), the conditions in the switch-case stmt include `BinOpAdd`, `BinOpSub`, `BinOpDiv` but not `BinOpMul`, could you please tell me your considerations?

**Comment by hsiaosiyuan0** [comment]
```go
case BinOpAdd:
// Addition of small-ish integers can definitely be folded without issues
// "1 + 2" => "3"
if left, right, ok := extractNumericValues(binary.Left, binary.Right); ok &&
	left == math.Trunc(left) && math.Abs(left) <= 0xFFFF_FFFF &&
	right == math.Trunc(right) && math.Abs(right) <= 0xFFFF_FFFF {
	return true
}
```

follow the comment `// "1 + 2" => "3"` I have a guess that the const-folding in esbuild is preferred for minimizing source code rather than optimizeing the output code execution, and according to this guess, `BinOpMul` and `BinOpDiv` may cause the source code becomes large since the number precision `eg. 1/3 => 0.3333333333333333`

**Comment by evanw** [comment]
Yes, that's the general idea. It's a heuristic. This behavior may also change over time (and has already been changed in the past).
