### ISSUE TITLE
Drop console.assert() statements with always true assertion

### ISSUE THREAD

**Issue by ghost** [evanw/esbuild#3859]
see Terser issue 

https://github.com/terser/terser/issues/1545

**Comment by evanw** [comment]
I believe you can already trivially do this by changing this:

```js
console.assert(process.env.NODE_ENV === 'production' || !hasError, 'Oops');
```

to this:

```js
process.env.NODE_ENV === 'production' || console.assert(!hasError, 'Oops');
```

That's the same number of characters but it'll automatically work with all existing JavaScript tooling without needing any tooling modifications. You can also do this instead if you prefer:

```js
process.env.NODE_ENV !== 'production' && console.assert(!hasError, 'Oops');
```
