### ISSUE TITLE
Using esbuild for dependency analysis

### ISSUE THREAD

**Issue by prantlf** [evanw/esbuild#386]
I maintain a big project consisting of more than a thousand modules and using `RequireJS` for modularisation. Analysing module dependencies for documentation and refactoring purposes becomes painfully slow. I am thinking if `esbuild` could not help me just like it helps to speed up minification and concatenation or module bundles.

`esbuild` "almost" does what I would need by producing a metafile (in particular the `imports` property) together with the output bundle. But I do not need the bundle :-)

For example, the public `api` and `cli` packages could support _Analyse_ in addition to _Build_ and _Transform_. Analyse would traverse module dependencies like Build, but produce only the module metadata (`Metafile`). It would call only `bundler.ScanBundle`, but not `bundler.Compile`.

What do you think?

Being able to build a module dependency analyser using the `esbuild` API would be a half of the task. The second half would be making `esbuild` understand `AMD.JS` module syntax. It is an off-topic in this issue, but did you consider recognising the AMD.JS module syntax?

Thank you!

**Comment by evanw** [comment]
I understand the need for something like this, but this seems out of esbuild's scope to me.

I think it should be very possible to analyze the dependencies of an AMD code base extremely quickly, since they are all declared at the start of the file. Assuming each file is some form of `define([...deps], function() {})`, have you considered modifying whatever JavaScript parser you're using to stop parsing after the first `function` token and return an AST with an empty `FunctionExpression`? This should make whatever existing code you already have much faster. It seems to me like that would be an even easier solution than getting esbuild to do this, even if it was considered in scope for esbuild.

**Comment by dwelle** [comment]
I would like this as well.

We can always send the output to `/dev/null` but it keeps the unnecessary overhead of building the bundle in the first place. Still might be faster (haven't tested on large codebases) than using browserify ([substack/module-deps](https://github.com/substack/module-deps)) or similar, though.

**Comment by prantlf** [comment]
Thank you for your insight, @evanw!

Yes, I considered modifying a well-known parser like `acorn` or `esprima`, or even yours, which would be more complicated for me. I am reluctant to do it because of two reasons. Firstly, I would prefer a solution, which would not involve me maintaining a special JavaScript parser. Well, I still might end up with doing that, because as you wrote, parsing just the arguments of the `define` and `require` statements would not be a big deal. Secondly, I would like my fellow developers write the new code as ES modules. Our product consists of more than two thousands of AMD.JS modules and the scripts for bundling and loading them require this format now. I cannot afford to convert all modules and the build environment to ESM right away. I am looking for a compromise how to modernise the development step by step, which would mean a combination of AMD and ESM. The flexibility of the module format in the source code base makes me less keen on the special parser solution. For example:

AMD:

    define(
      ['core/libs/jquery', 'core/libs/backbone', ...],
      function ($, Backbone, ...) {
        ...
        return { MyView }
      })

ESM:

    import $ from 'core/libs/jquery'
    import Backbone from 'core/libs/backbone'
    ...
    export { MyView }

Theoretically, I might need to support the CommonJS syntax of the AMD.JS modules, but my colleagues have not used it, AFAIK:

    define(function (require, exports, module) {
      var $ = require('core/libs/jquery')
      var Backbone = require('core/libs/backbone')
      ...
      exports.MyView = MyView
    })

I tried `madge` for the dependency analysis and I wrote a script using `amodro-trace`, but analysing module dependencies for multiple entry modules gets noticeably slower. This lead me to the question, how much faster I would get with `esbuild`, without writing my own parser.

I prototyped an `analyse` mode in #392. You protect the internal interface pretty well ;-) so I dropped the idea of an external `esanalyse` tool. I tried to follow your approach of `build` and `transform` commands and added `analyse` command. It was straightforward and I did not look at the possibility of having `esanalyse` as an additional package in `cmd`.

I tried to test it with the project `three.js`, which you use for your benchmark. The dependency tree sprouting from the module `src/Three.js` includes 376 modules.

Printing module dependencies using `madge`:

    $ time madge --json src/Three.js >dependencies.json

    real	0m2.289s
    user	0m2.814s
    sys	  0m0.156s

Building a bundle and generating a metafile with module dependencies:

    $ time esbuild --bundle src/Three.js --outfile=bundle.js --metafile=bundle.json

    real	0m0.066s
    user	0m0.224s
    sys	  0m0.090s

Generating a metafile with module dependencies after `bundler.ScanBundle`:

    $ time esbuild --analyse src/Three.js --metafile=dependencies.json

    real	0m0.048s
    user	0m0.166s
    sys	  0m0.072s

The difference between `madge` and `esbuild` is abysmal. The difference between `--bundle` and `--analyse` is for the `three.js` project negligible.

I am looking for a way how to test it on my product. One way would be adding support for parsing AMD.JS modules to `esbuild`. I still have not overcome the fear from it ;-) I will maintain the `analyse` mode in my [analyse branch](https://github.com/prantlf/esbuild/commits/analyse), if you get interested and let you know about the progress of my prototyping.

**Comment by evanw** [comment]
Thank you for taking the time to prototype this out. However, I'm going to close this because I still consider it to be out of scope. And the increase in API surface for this isn't worth it IMO, especially since it's almost the same thing as the build API and the performance vs. the build API is similar enough.
