### ISSUE TITLE
enhance dead code elimination

### ISSUE THREAD

**Issue by ghost** [evanw/esbuild#3865]
```ts
let value = 0;
if (`${value++}hello` === `${value++}world`) {
	console.log(value)
}
```

Expected

```ts
let value=0;value+++"hello"==value+++"world"&&console.log(value);

// or

let value = 3; // or nothing if unused
```

**Comment by evanw** [comment]
I'm noticing that you have recently filed a lot of issues about minor things. I'm not sure why you're filing so many issues, but perhaps this means esbuild isn't the best tool for you and another tool would be a better fit for you?

**Comment by evanw** [comment]
I'm closing this issue as the user account that reported it has been deleted.
