### ISSUE TITLE
Target chrome53 does not cover Object.fromEntries

### ISSUE THREAD

**Issue by mitchellwarr** [evanw/esbuild#3869]
If you set your target to something lower than chrome73, such as **chrome53**, then it does not transform Object.fromEntries

**Comment by hyrious** [comment]
esbuild doesn't do polyfills, the [`target`](https://esbuild.github.io/api/#target) option is there for lowering language features like using generators instead of async-await. This behavior is also documented:

> Note that this is only concerned with syntax features, not APIs. It does not automatically add [polyfills](https://developer.mozilla.org/en-US/docs/Glossary/Polyfill) for new APIs that are not used by these environments. You will have to explicitly import polyfills for the APIs you need (e.g. by importing [`core-js`](https://www.npmjs.com/package/core-js)). Automatic polyfill injection is outside of esbuild's scope.

**Comment by mitchellwarr** [comment]
Huh, thats good to know. Makes sense. Ill add the core-js import for fromEntires specifically
