### ISSUE TITLE
Inconsistent minify output caused by type import

### ISSUE THREAD

**Issue by aleclarson** [evanw/esbuild#3881]
Even though importing a type won't affect the behavior of a bundle, it causes ESBuild to use a different identifier, resulting in inconsistent output.

## Reproduction

The reproduction steps are listed here: https://github.com/aleclarson/repro/tree/esbuild/consistent-minify#readme

```
git clone https://github.com/aleclarson/repro -b esbuild/consistent-minify
```

**Comment by aleclarson** [comment]
Just occurred to me that the Terser comparison is unnecessary. If I first compile the TypeScript to JavaScript, then minify after with a separate `esbuild --minify` command, the issue doesn't occur, of course, because there won't be a type import at the time of minification.

**Comment by evanw** [comment]
I can see the difference in output (e.g. [this](https://esbuild.github.io/try/#dAAwLjIzLjAALS1sb2FkZXI9dHMgLS1taW5pZnkAaW1wb3J0IHsKICBpc1BsYWluT2JqZWN0LAp9IGZyb20gJ3JhZGFzaGknCgpleHBvcnQgZnVuY3Rpb24gZm9vKGFyZzogb2JqZWN0IHwgTnVtYmVyIHwgU3RyaW5nKSB7CiAgcmV0dXJuIGlzUGxhaW5PYmplY3QoYXJnKSA/ICdvYmplY3QnIDogJ3ByaW1pdGl2ZScKfQ) vs. [this](https://esbuild.github.io/try/#dAAwLjIzLjAALS1sb2FkZXI9dHMgLS1taW5pZnkAaW1wb3J0IHsKICBpc1BsYWluT2JqZWN0LAogIHR5cGUgQm94ZWRQcmltaXRpdmUsCn0gZnJvbSAncmFkYXNoaScKCmV4cG9ydCBmdW5jdGlvbiBmb28oYXJnOiBvYmplY3QgfCBCb3hlZFByaW1pdGl2ZTxudW1iZXIgfCBzdHJpbmc+KSB7CiAgcmV0dXJuIGlzUGxhaW5PYmplY3QoYXJnKSA/ICdvYmplY3QnIDogJ3ByaW1pdGl2ZScKfQ)). But this doesn't seem to be a bug. The two results are functionally equivalent so this doesn't indicate a correctness issue.

**Comment by aleclarson** [comment]
It's only a bug if, like me, you're using the output to determine whether the implementation has actually changed (e.g. between a PR and its target branch). In my case, this is useful to bail out of a GitHub action early (e.g. avoid running benchmarks) if only the JSDoc was updated or whatever.

Anyway, fixing this issue is very low priority (on my end anyway), because the workaround of running `esbuild.build()` twice (once for bundling, then for minifying) works well enough.

**Comment by aleclarson** [comment]
Even after switching to a two-step process of "bundle then minify", identifiers were not always deterministic despite unchanged code (but only in CI for some reason; specifically `ubuntu-latest` in a GitHub action).

Therefore, I wrote a function for deterministic identifiers: https://github.com/radashi-org/radashi/blob/9aa272cd666b4278ca5df186aa5f8dbeca451bde/scripts/benchmarks/src/normalizeIdentifiers.ts

**Comment by evanw** [comment]
I'm closing this as I don't consider this to be a correctness issue. The minifier uses heuristics that attempt to generate minified names that compress better with gzip enabled by biasing the alphabet used for minified names toward characters that are present more often in the original source code (see [the implementation](https://github.com/evanw/esbuild/blob/6e049b81d2e080ccdf24db84a71934ea736879ce/internal/js_parser/js_parser.go#L17649-L17702) for details). That way characters used in strings can be reused for identifier names using a potentially smaller encoding in the gzip stream. It's a little more complicated than that (the contents of comments, import paths, and certain symbols are excluded) but it's a heuristic and is intentionally designed for speed, and not for the kind of precision you're asking for.

**Comment by skondrashov** [comment]
I ran into this same issue, so I'm leaving a comment though I agree that it's low priority at best. I was attempting to demonstrate that a PR introducing sweeping changes to the type system of a multi-bundle project does not change the output code, and therefore doesn't require testing, but found that certain bundles respond to certain type names (even if those types are unused) by changing the naming of variables in the minified code.
