### ISSUE TITLE
Unexpected output

### ISSUE THREAD

**Issue by luizbills** [evanw/esbuild#3884]
The bundler do not remove that "unused" AudioContext instance. Why?

https://esbuild.github.io/try/#YgAwLjIzLjEALS1idW5kbGUAZQBlbnRyeS5qcwBjb25zdCBhID0gbmV3IEF1ZGlvQ29udGV4dCgpCgpjb25zdCBiID0gKCkgPT4gYQoKZ2xvYmFsVGhpcy5jID0gKCkgPT4gImZvbyI

**Comment by evanw** [comment]
That’s likely because esbuild doesn’t know that `new AudioContext()` is side-effect free.

**Comment by luizbills** [comment]
> That’s likely because esbuild doesn’t know that `new AudioContext()` is side-effect free. 

make sense!

There are something I can do?

**Comment by hyrious** [comment]
You can mark your function-call (including `new XXX()`) as side-effect free with `/*@__PURE__*/`. [Playground Link](https://esbuild.github.io/try/#YgAwLjIzLjEALS1idW5kbGUAZQBlbnRyeS5qcwBjb25zdCBhID0gLypAX19QVVJFX18qLyBuZXcgQXVkaW9Db250ZXh0KCkKCmNvbnN0IGIgPSAoKSA9PiBhCgpnbG9iYWxUaGlzLmMgPSAoKSA9PiAiZm9vIg)

**Comment by luizbills** [comment]
> You can mark your function-call (including `new XXX()`) as side-effect free with `/*@__PURE__*/`.

thanks!
