### ISSUE TITLE
[question] Working directory CLI argument

### ISSUE THREAD

**Issue by nichoth** [evanw/esbuild#3901]
[The docs](https://esbuild.github.io/api/#working-directory) show for the CLI command,

```sh
cd "/var/tmp/custom/working/directory"
```

Is this a mistake? It has nothing to do with esbuild. I tried passing `--abs-working-dir` and `--working-dir`, but they do not work also.

How to set this via CLI?

Thanks.

**Comment by evanw** [comment]
The current working directory is an operating system concept, and is automatically passed to all commands that you run after running `cd`. For example, compare `bash -c '/bin/pwd'` with `bash -c 'cd Desktop && /bin/pwd'`. The `cd` command is how you change the current working directory when you are using the command line. This is not a mistake. Instead, this is a fundamental part of how all command line interfaces work.

**Comment by nichoth** [comment]
Thanks @evanw . So for posterity, the complete command would be something like

```sh
bash -c 'cd ./example-dir && esbuild ...'
```

The `bash -c` part was missing in my bash knowledge.
