### ISSUE TITLE
i have  a  question  ,   why  is vite not used  esbuild to bundle  ,however  select rollup to  build 

### ISSUE THREAD

**Issue by Super1Windcloud** [evanw/esbuild#3903]
i have  a  question  ,   why  is vite not used  esbuild to bundle  ,however  select rollup to  build

**Comment by Delapouite** [comment]
You'll find some info on the Rolldown about page: https://rolldown.rs/about

**Comment by Denis6902** [comment]
More info here https://vitejs.dev/guide/why.html#why-not-bundle-with-esbuild

**Comment by evanw** [comment]
That decision is made by the Vite project, which has nothing to do with this repo. Closing.
