### ISSUE TITLE
[BUG] Chunks loaded with () => import('..') are wrongly considered as initial

### ISSUE THREAD

**Issue by montella1507** [evanw/esbuild#3926]
[stats.json](https://github.com/user-attachments/files/17155953/stats.json)

Check this STATS.json please

This is wrong:
<img width="1095" alt="image" src="https://github.com/user-attachments/assets/25345793-c50c-42ed-8c18-a7cf71862775">

This component is loaded lazily:

```
 {
   path: 'edit/:id',
   loadComponent: () => import('./components/graphic-identity-edit/graphic-identity-edit.component').then((x) => x.GraphicIdentityEditComponent),
   canDeactivate: [UnsavedChangesGuard()],
 }
```

With this bug in the logic of "initial chunks", half of the chunks are considered as Initial wrongly, because of Angular lazyLoaded components.

**Comment by evanw** [comment]
Sorry, I don't understand. Both the code you describe and the screenshot you posted indicate that the files inside the `import()` are dynamically loaded (i.e. not initially loaded), so everything looks fine to me. What do you mean by "initial" then?

**Comment by montella1507** [comment]
Ah. So probably it is output from AngularCLI and not ESBUILD

<img width="725" alt="image" src="https://github.com/user-attachments/assets/240c17e6-8d18-4e2a-8563-a18a15617e1b">


Right. If yo, i will close the issue and sorry for wasting your time.
