### ISSUE TITLE
Feature Request: Support for registry Configuration

### ISSUE THREAD

**Issue by elrrrrrrr** [evanw/esbuild#3938]
I've noticed from the recent changes that esbuild has stopped supporting the registry configuration, which previously was able to recognize the `npm_config_registry` environment variable. This feature was quite useful for many users who work with private registries or need to specify a custom registry. 

I've seen the discussion in issue #291, and I understand that there might be concerns about the complexity it adds to the build process. However, I believe the benefits outweigh the potential drawbacks, and it would be a valuable addition to the tool.  🙏🏻

**Comment by evanw** [comment]
The way that this is supposed to work now is that [esbuild just invokes `npm` directly instead](https://github.com/evanw/esbuild/blob/d34e79e2a998c21bb71d57b92b0017ca11756912/lib/npm/node-install.ts#L118) of emulating it, and the `npm` command is supposed to handle everything including the `npm_config_registry` environment variable. This has been the case for quite some time now. You're linking to a very old issue from before esbuild started doing that (which was in [version 0.6.28](https://github.com/evanw/esbuild/blob/main/CHANGELOG-2020.md#0628), not long after the issue you're referencing was closed). So this should already be working.

If you have a bug report for esbuild, then please provide reproduction instructions.

**Comment by RopoMen** [comment]
I believe that here is still some issue.

Our setup uses Github Actions and set registry like this `npm config set registry https://<our artifactory/npm-mirror`

Yet, I see this error https://github.com/evanw/esbuild/blob/4475787eef4c4923b92b9fa37ebba1c88b9e1d9b/lib/npm/node-install.ts#L227 on our build logs. This means that esbuild has tried to download platform specific `@esbuild` package directly from registry.npmjs.org and I'm quite sure that that domain is restricted and thereof download fails.

My understanding is that `npm config set registry` is setting registry configuration globally, but this code dumps global config https://github.com/evanw/esbuild/blob/4475787eef4c4923b92b9fa37ebba1c88b9e1d9b/lib/npm/node-install.ts#L103

**Comment by JounQin** [comment]
@evanw 

According to https://docs.npmjs.com/cli/v8/configuring-npm/npmrc#files, it seems project level `.npmrc` will not be used with https://github.com/evanw/esbuild/blob/8c71947edbe5a158fec3a6d1cbfea1e8d5cdee70/lib/npm/node-install.ts#L118-L119

See also https://github.com/un-ts/napi-postinstall/issues/37
