### ISSUE TITLE
suppressing specific warnings

### ISSUE THREAD

**Issue by ojanvafai** [evanw/esbuild#395]
Is there a way to suppress specific warnings or classes of warnings?

I get a -0 comparison warning when compiling firestore. This warning seems reasonable and I've filed an issue with firestore. The -0 is unnecessary, but the code isn't technically incorrect in their case. Regardless, not getting my hopes up that they will fix it. https://github.com/firebase/firebase-js-sdk/issues/3814

```
node_modules/@firebase/firestore/dist/index.cjs.js:718:11: warning: Comparison with -0 using the === operator will also match 0
    return -0 === t && 1 / t == -1 / 0;
```

**Comment by iamakulov** [comment]
Adding my voice here. I’d love to be able to suppress warnings coming from `node_modules`. Warnings _are_ useful for first-party code, so I wouldn’t want to do `--log-level=error`. But for third-party code, they’re typically hard to fix (especially if it’s a transitive dependency) and result in noice.

**Comment by ojanvafai** [comment]
For what it's worth, I just filtered the warning out with an esbuild wrapper and it looks like firebase has fixed the issue (in 3 days!!). I'd consider this pretty low priority. But I can easily imagine having a lot of warnings and that being less tenable. Will leave open for you to decide what to do with @evanw. While this feels useful, I also wouldn't be offended at all if you just closed this. :)

**Comment by evanw** [comment]
I've decided to suppress warnings coming from `node_modules` by default.

**Comment by crondaemon** [comment]
Hi,
I'm observing the very same behavior before this change:

```
esbuild app/javascript/*.* --bundle --sourcemap --outdir=/tmp

▲ [WARNING] "types.d.ts" is not a valid value for the "type" field

    node_modules/datatables.net-select/package.json:9:12:
      9 │     "type": "types.d.ts",
        ╵             ~~~~~~~~~~~~

  The "type" field must be set to either "commonjs" or "module".

1 warning

  ../../../../tmp/application.js      3.1mb ⚠️
  ../../../../tmp/application.js.map  4.1mb

⚡ Done in 144ms
```

Is there something missing, or it's me missing something?
