### ISSUE TITLE
Statements generated from syntax lowering or keepNames block treeshaking

### ISSUE THREAD

**Issue by bluwy** [evanw/esbuild#3965]
When using the transform API with syntax lowering (e.g. for classes) or with keepNames (`--keep-names`), the code generated often look something like this:

```js
const _Foo = class _Foo {
};
__name(_Foo, "Foo");
__publicField(_Foo, "prop", "value");
export let Foo = _Foo;
```

[Playground link](https://esbuild.github.io/try/#dAAwLjI0LjAALS10YXJnZXQ9ZXMyMDE4IC0ta2VlcC1uYW1lcwBleHBvcnQgY2xhc3MgRm9vIHsKICBzdGF0aWMgcHJvcD0gInZhbHVlIjsKfQ)

~~Because the `__publicField` and `__name` aren't marked as pure (`/* @__PURE__ */`), even if `_Foo` is unused, bundlers are not able to assume it's safe to treeshake it. Should esbuild be prepending the `/* @__PURE__ */` comments to `__publicField` and `__name`?~~

The  `__publicField` and `__name` statements are holding a value on `_Foo`, which prevents it from being treeshaken if the exports are unused in bundlers.

---

I noticed for function expressions and keepNames, e.g. with `export const foo = () => {}`, esbuild is [already transforming it](https://github.com/evanw/esbuild/blob/9eca46464ed5615cb36a3beb3f7a7b9a8ffbe7cf/internal/js_parser/js_parser.go#L9987-L9995) to `export const _foo = /* @__PURE__ */ __name(() => {}, "foo")`. This has [allowed esbuild to treeshake it](https://esbuild.github.io/try/#YgAwLjI0LjAALS1idW5kbGUAZQBlbnRyeS5qcwBpbXBvcnQge3VzZWR9IGZyb20gJy4vbW9kdWxlXzEuanMnCgp1c2VkKCkAAG1vZHVsZV8xLmpzAHZhciBfX25hbWUgPSAodGFyZ2V0LCB2YWx1ZSkgPT4gT2JqZWN0LmRlZmluZVByb3BlcnR5KHRhcmdldCwgIm5hbWUiLCB7IHZhbHVlLCBjb25maWd1cmFibGU6IHRydWUgfSk7CgpleHBvcnQgY29uc3QgX2ZvbyA9IC8qIEBfX1BVUkVfXyAqLyBfX25hbWUoKCkgPT4gewogIGlmICh0cnVlKSByZXR1cm4KICBjb25zb2xlLmxvZygic2hvdWxkIGJlIHRyZWVzaGFrZW4iKTsKfSwgImZvbyIpOwoKZXhwb3J0IGNvbnN0IF9iYXIgPSAoKSA9PiB7CiAgaWYgKHRydWUpIHJldHVybgogIGNvbnNvbGUubG9nKCJzaG91bGQgYmUgdHJlZXNoYWtlbiIpOwp9Cl9fbmFtZShfYmFyLCAiYmFyIik7IC8vIHRyeSBwcmVwZW5kIGEgcHVyZSBjb21tZW50IGhlcmUKCmV4cG9ydCBjb25zdCB1c2VkID0gKCkgPT4gY29uc29sZS5sb2coJ3VzZWQnKQ) if unused.

~~Perhaps something similar can be done for [non-expressions](https://github.com/evanw/esbuild/blob/9eca46464ed5615cb36a3beb3f7a7b9a8ffbe7cf/internal/js_parser/js_parser.go#L9997-L10005) and for the lowering code.~~

**Comment by hyrious** [comment]
FYI, pure annotations don't work on statements. The only way to mark the `Foo` as pure in your case is:

```js
export let Foo = /* @__PURE__ */ (() => {
	const _Foo = class _Foo {
	};
	__name(_Foo, "Foo");
	__publicField(_Foo, "prop", "value");
	return _Foo;
})();
```

**Comment by bluwy** [comment]
Ah that pretty much makes this feature request moot then. I don't know if esbuild is up to transforming to that way to solve the treeshaking issue, or if there's some other solution to this.

**Comment by bluwy** [comment]
Going to close this for now as the issue is kinda broad and is probably worth as a better feature request to resolve the issue generically.
