### ISSUE TITLE
Default format for node platform with buildSync API

### ISSUE THREAD

**Issue by aleclarson** [evanw/esbuild#397]
The CLI docs state that the default format is `cjs` when the platform is `node`, while the `buildSync` API defaults to an `esm` format when `platform: 'node'` is passed.

**Comment by evanw** [comment]
Thanks for pointing this out. The documentation is incorrect. When bundling isn't enabled, the format option must be explicitly specified or no format change is performed. This is necessary to support "pass-through" behavior for people that aren't using esbuild as a bundler. The reason why there is no "pass-through" behavior when bundling is that the bundler has to pick a format to generate exports for.
