### ISSUE TITLE
esbuild (packages=external) does not add external packages (node_modules) from docker

### ISSUE THREAD

**Issue by Diboby** [evanw/esbuild#3970]
### The problem

On my machine (macOs 15), when packaging serverless using esbuild with the option `packages='external'`, a `node_modules` folder is added automacally to the build folder. With the same configuration, but run the command from any **nodejs docker image** (`alpine`, `bullseye` or `bookworm`) does not produce the same output, i-e the `node_modules` folder is not added.

### Config

My esbuild config file looks like

<details>
<summary>esbuild.config.mjs</summary>

```ts
export default (serverless) => {
  return {
    entryPoints: ['src/index.ts'],
    bundle: true,
    platform: 'node',
    minify: true,
    sourcemap: true,
    packages: 'external',
    target: 'node20.9',
    plugins: [],
    };
};
```
</details>

### Possible workarounds

1. Run `npm i --omit=dev` in the build folder: This approach is not possible with `serverless deploy` command without providing a package location option

## Other informations:
- esbuild: v0.24.0
- serverless: v4.4.7

**Comment by hyrious** [comment]
This seems a `serverless`'s intentional behavior: https://github.com/serverless/serverless/blob/main/lib%2Fplugins%2Fesbuild%2Findex.js#L873-L881.

**Comment by Diboby** [comment]
Thank you so much, @hyrious! 👍

The issue was related to npm authentication. From your comment, I understood that Serverless runs `npm install` in the background. So, when there is a private dependency, npm requires authentication against the private registry.

In my case, npm authentication was missing from within a Docker container, and unfortunately, I didn’t receive any error logs.

After fixing the authentication process, everything worked fine.

I'm really grateful for your help, @hyrious! 💯
