### ISSUE TITLE
validateBinaryVersion error

### ISSUE THREAD

**Issue by chenddcoder** [evanw/esbuild#3977]
<img width="1304" alt="image" src="https://github.com/user-attachments/assets/6bc49e42-3818-41a8-82e4-921f03a0c7a7">

**Comment by hyrious** [comment]
There [were](https://github.com/evanw/esbuild/issues/3800) reports before about pnpm not behaving well. You can try some of these steps:

- Upgrading your pnpm version and try again. You may need to delete the whole node_modules and pnpm-lock.yaml.
- Switching to npm and try again.
- Check your environment variables to see if there is a mis-configured `ESBUILD_BINARY_PATH`, which chould lead to the js module in esbuild to start a binary in different version. If so, delete that env and try again.

If it still occur when you're using pnpm, you can file an issue to pnpm.

**Comment by chenddcoder** [comment]
指定到最新版本0.24.0可以了
"esbuild": "^0.24.0"
pnpm似乎无法自动获取到最新版本
