### ISSUE TITLE
`esbuild` versus `vite`, specifically with TypeScript

### ISSUE THREAD

**Issue by hamirmahal** [evanw/esbuild#3984]
How does `esbuild` compare to `vite` in terms of build performance, simplicity, type safety, and ease of use?

**Comment by hamirmahal** [comment]
Specifically, which would you recommend for building a Chrome extension with TypeScript, and why?

**Comment by hamirmahal** [comment]
https://github.com/vitejs/vite/discussions/18732 is a sibling discussion.

**Comment by evanw** [comment]
I'm not sure, sorry. I haven't used Vite myself. It would be better to ask people who have used Vite instead. I'm closing this issue because I don't have an answer and it's not an issue with esbuild.
