### ISSUE TITLE
What is the proper way to have an `isBrowser`/`isNode` check that causes the code to only bundle one of two paths depending on platform target?

### ISSUE THREAD

**Issue by MicahZoltu** [evanw/esbuild#3992]
````
const inBrowser = (typeof window !== "undefined");
let NodeWorker;
let NodeCrypto;
if (!inBrowser) {
    NodeWorker = require("worker_threads").Worker;
    NodeCrypto = require("crypto");
}
````
This code will fail to bundle when `--platform=browser` is set because neither of those libraries are available in the browser.  How can I modify the `isBrowser` check such that esbuild will correctly skip those lines?

**Comment by hyrious** [comment]
You can add a try-catch around the requires so that esbuild won't check inside:

```js
const inBrowser = (typeof window !== "undefined");
let NodeWorker;
let NodeCrypto;
if (!inBrowser) {
	try {
		NodeWorker = require("worker_threads").Worker;
		NodeCrypto = require("crypto");
	} catch {}
}
```

**Comment by MicahZoltu** [comment]
If in node, you would want an error if either of those fails.  Adding a try with an empty catch would introduce a potential bug.

**Comment by MicahZoltu** [comment]
Hmm, this seems to do the trick.  Why is it that esbuild ignores the contents of try/catch blocks?
```js
const inBrowser = (typeof window !== "undefined");
let NodeWorker;
let NodeCrypto;
if (!inBrowser) {
    try {
        NodeWorker = require("worker_threads").Worker;
        NodeCrypto = require("crypto");
    } catch (error) {
        // necessary so esbuild ignores this
        throw error
    }
}
```

**Comment by hyrious** [comment]
esbuild reports that error because it can not bundle something not exist if that thing isn't externalized. But there's a common code pattern which gracefully handles "optional dependencies" (i.e. inside a try-catch block) so esbuild also allows that to swallow the error.

https://github.com/evanw/esbuild/blob/9eca46464ed5615cb36a3beb3f7a7b9a8ffbe7cf/internal/ast/ast.go#L115-L125

Other choices are that you can tell esbuild those node modules are externalized, or replaced with `undefined`:

- `--external:worker_threads --external:crypto` [(example)](https://esbuild.github.io/try/#YgAwLjI0LjAALS1idW5kbGUgLS1leHRlcm5hbDpmcwBlAGVudHJ5LmpzAHJlcXVpcmUoJ2ZzJyk)
- Put this in your pakcage.json:
  ```js
  "browser": { "crypto": false }
  ```
  [(example)](https://esbuild.github.io/try/#YgAwLjI0LjAALS1idW5kbGUAZQBlbnRyeS5qcwByZXF1aXJlKCdmcycpAABwYWNrYWdlLmpzb24AewogICJicm93c2VyIjogeyAiZnMiOiBmYWxzZSB9Cn0)

**Comment by MicahZoltu** [comment]
Is it possible to achieve the second solution (just put undefined) via CLI options, or do I have to modify the package.json to achieve that?

**Comment by evanw** [comment]
Documentation for what esbuild's `platform` setting does is here: https://esbuild.github.io/api/#platform. There are various ways to do this but `conditions` is probably the most straightforward. You can use `exports` in `package.json` to have different entry points (i.e. different files) for when the `browser` and `node` conditions are active. As usual when using `exports`, remember to also add a fallback `default` entry for when neither condition applies.

Closing as answered.

**Comment by MicahZoltu** [comment]
> You can use exports in package.json to have different entry points (i.e. different files) for when the browser and node conditions are active.

Unfortunately, platform differences are usually buried very deep in the project, as 99.9% of the project is the same for both.  There will often be one or two functions (in this case, it was a cryptographic function) that calls a different function on NodeJS vs Browser.  Moving that platform difference way up the stack to an index.js file requires either monkey patching something, making some global (probably the best option), or propagating the difference all over the application.

It would be nice if in the future there is a way for esbuild to be able to recognize conditions like `(typeof window !== "undefined")` (or something similar) and not follow into it if building for the other platform.

**Comment by evanw** [comment]
There are two mechanisms that use conditions: `exports` and `imports`, where `imports` is internal to a package and intended for use cases like that (node calls them "subpath imports"). I encourage you to read node's documentation about how packages work in node: https://nodejs.org/api/packages.html
