### ISSUE TITLE
NPM package missing?

### ISSUE THREAD

**Issue by IgorKrupenja** [evanw/esbuild#3999]
1. Open https://www.npmjs.com/package/esbuild
2. Or try running `npm i esbuild`

You will get 404 errors. This started happening around 30 min ago, 20:20 GMT.

**Comment by omtodkar** [comment]
There is some kind of incident on `npm registry` similar to `left-pad` incident.

**Comment by andrew-bierman** [comment]
+1 i noticed the same on my ci/cd pipeline

**Comment by omtodkar** [comment]
Try now they were upgrading infrastructure as per their [status](https://status.npmjs.org/).

**Comment by evanw** [comment]
https://status.npmjs.org/ says this:

> **Scheduled infrastructure upgrade**
>
> Update - Scheduled maintenance is still in progress. We will provide updates as necessary.
> Dec 08, 2024 - 18:57 UTC
>
> In progress - Scheduled maintenance is currently in progress. We will provide updates as necessary.
> Dec 08, 2024 - 18:00 UTC
>
> Scheduled - We will be conducting a scheduled infrastructure upgrade that may temporarily impact publishing and certain website functionalities. While some features will remain operational, like installations and search, minor inefficiencies may occur. Normal operations are expected to resume following the maintenance window.
> Dec 8, 2024 18:00-22:00 UTC

I assume this means npm screwed something up, but the screwup is temporary.

**Comment by evanw** [comment]
I'm closing this as npm has now posted this:

>  Completed - The scheduled maintenance has been completed. 
>  Dec 8, 22:00 UTC
