### ISSUE TITLE
[Feature] Exclude dependencies from bundle

### ISSUE THREAD

**Issue by renanbatel** [evanw/esbuild#40]
Webpack has a [externals](https://webpack.js.org/configuration/externals/#externals) option that provides a way of excluding dependencies from the bundle, it's useful when you use a library on development, but you don't want it on your bundle because it'll be available on the production environment.

There's this JQuery use case, but it'll be also useful if you plan to support Node, where some dependencies can be available in the runtime environment like we see on serverless platforms.

**Comment by evanw** [comment]
This is now possible with the `--external` flag. Pass `--external:foo` to exclude `foo` from the bundle.

**Comment by Yaroslavpnts** [comment]
But how we can achieve next case.
If we want to exclude some dependency form bundle, but still want ho have it in node_modules after compling?
So we need all dependencies from node_modules be in bundle and in node_modules we should have only 1 dependency.

**Comment by lazarljubenovic** [comment]
ESBuild doesn't control what's in your `node_modules` directory. It doesn't write into it, only reads from it.
