### ISSUE TITLE
Any Tutorials on how to use it?

### ISSUE THREAD

**Issue by navirick** [evanw/esbuild#400]
I might be missing something.. this project looks very cool.. but I can't seem to find anything like a tutorial on how to get started, how to use it, etc. The README seems to go in to various things that don't really explain how to use the tool, a road map, etc. Would be fantastic to have a lot more tutorials on the tool.

**Comment by evanw** [comment]
There aren't any step-by-step tutorials right now, sorry. I'm planning to put together a website after the plugin API is released with much more comprehensive documentation.

That said, the documentation and examples in the readme should be enough information to get up and running with esbuild. For example, there's a [Using with React](https://github.com/evanw/esbuild/blob/163e37da2ab8bef045907a13d5cf15882c92d22b/README.md#using-with-react) section that shows how to bundle React code. Is there something you're looking for from a tutorial in particular?

**Comment by evanw** [comment]
There is now a getting started guide here: https://esbuild.github.io/getting-started/.
