### ISSUE TITLE
Plugin API: built-in loaders are skipped

### ISSUE THREAD

**Issue by rtsao** [evanw/esbuild#401]
In my testing, it seems that if a file is handled by a plugin, it will not be transformed by any built-in loaders that have been configured, such as JSX.

This is most immediately an issue with the PnP plugin, but even in other cases, I think it would still make sense for esbuild to handle JSX or TS syntax emitted by plugins (assuming those loaders have been enabled).

**Comment by evanw** [comment]
Loader plugins can optionally return the loader to use for parsing the returned file contents. For example, a loader for TypeScript files could return `{ contents: typeScriptCode, loader: 'ts' }` to automatically convert the TypeScript code to JavaScript before bundling it. If the loader is not specified, it defaults to `js`.

There is also a way to automatically use the appropriate built-in configured loaders. This is code for the example PnP plugin:

```js
let { PosixFS, ZipOpenFS } = require(`@yarnpkg/fslib`)
let libzip = require(`@yarnpkg/libzip`).getLibzipSync()
let zipOpenFs = new ZipOpenFS({ libzip })
let crossFs = new PosixFS(zipOpenFs)
let pnpapi = require('pnpapi')

// More info: https://classic.yarnpkg.com/en/docs/pnp/
let pnpYarnPlugin = plugin => {
  plugin.setName('pnp')
  plugin.addResolver({ filter: /.*/ }, args => {
    return { path: pnpapi.resolveRequest(args.path, args.importDir + '/') }
  })
  plugin.addLoader({ filter: /.*/ }, args => {
    return { contents: crossFs.readFileSync(args.path), loader: 'default' }
  })
}
```

The `loader: 'default'` part tells esbuild to use the configured default loader for that file extension. So for example `.tsx` files will use the `tsx` loader. Here's a simple self-contained example to demonstrate this:

```js
let tsx = 'console.log(<div/> as any)'
require('esbuild').build({
  bundle: true,
  write: false,
  stdin: { contents: 'import "example"' },
  plugins: [
    plugin => {
      plugin.setName('test')
      plugin.addResolver({ filter: /.*/ }, () => ({ path: 'example.tsx' }))
      plugin.addLoader({ filter: /.*/ }, () => ({ contents: tsx, loader: 'default' }))
    },
  ],
}).then(({ outputFiles: [{ contents }] }) => {
  process.stdout.write(Buffer.from(contents).toString())
})
```

**Comment by rtsao** [comment]
Ah, thanks for the explanation! I hadn't noticed that in the loader return value.
