### ISSUE TITLE
vite6.0 error Cannot read directory "../..": Access is denied.

### ISSUE THREAD

**Issue by gongph** [evanw/esbuild#4017]
Env:

- win10 64
- vite@^6.0.5

npm run dev error:

```bash
Error: Build failed with 2 error:
error: Cannot read directory "../..": Access is denied.
error: Could not resolve "D:\\cz_workspace\\star-web-bui\\vite.config.js"
  at failureErrorWithLog (D:\cz_workspace\star-web-bui\node_modules\_esbuild@0.24.0@esbuild\lib\main.js:1476:15)
  ...
```

**Comment by evanw** [comment]
I'm closing this issue as the issue reporting instructions were not followed. Here are the instructions that you deleted when posting this issue:

> When reporting a bug or requesting a feature, please do the following:
>
> * Describe what esbuild is doing incorrectly and what it should be doing instead.
>
> * Provide a way to reproduce the issue. The best way to do this is to demonstrate the issue on the playground (https://esbuild.github.io/try/) and paste the URL here. A link to a minimal code sample with instructions for how to reproduce the issue may also work. Issues without a way to reproduce them may be closed.
