### ISSUE TITLE
Export from Does not have expected behaviour

### ISSUE THREAD

**Issue by WenheLI** [evanw/esbuild#403]
While trying to export the following `ts` code to `cjs`:
```ts
export { compile, PipelineGenContext, PipelineNode } from './compiler';
```
I got the following output:
```js
__export(exports, {
  PipelineGenContext: () => PipelineGenContext,
  PipelineNode: () => PipelineNode,
  compile: () => compile
});
const compiler = __toModule(require("./compiler"));
```

It seems that `esBuild` does not respect `export ... from '';`.
Any idea on how to add this support?

**Comment by evanw** [comment]
This looks like a duplicate of #393, which has already been fixed. What version of esbuild are you using? You can use `esbuild --version` to check. The latest version is 0.7.2.

**Comment by WenheLI** [comment]
> This looks like a duplicate of #393, which has already been fixed. What version of esbuild are you using? You can use `esbuild --version` to check. The latest version is 0.7.2.

Yep, this gets fixed in the latest version. Thanks!
