### ISSUE TITLE
allow wildcards for externals

### ISSUE THREAD

**Issue by Ventajou** [evanw/esbuild#406]
I use Webpack as a second pass to handle things such as turning SVGs into React components, importing AngularJS HTML templates and simply placing the assets exactly where I want them. In order to do that right now I have a script that builds a list of all the files that should be treated as external by esbuild because it seems to only accept absolute paths. This adds to the overhead of running Webpack...

Would it be possible to support wildcards (or even regular expressions) to specify externals?

**Comment by zmitry** [comment]
I did similar approach but I had to move all the svgs and css to specific folder which I could exclude.

**Comment by Ventajou** [comment]
I can't have everything in a single folder unfortunately.

My current approach is actually to run esbuild twice:
- the first time I parse all the errors for unsupported file extensions and unresolvable modules and add them to the list of externals. 
- the second time is the actual build, using the externals from the first run.

This is still way faster and more accurate than any npm library I tried to get hold of the file dependency tree of my project...

**Comment by heyheyhello** [comment]
Does a wildcard regex as done here https://github.com/evanw/esbuild/issues/420#issuecomment-717573508 resolve this? This is what I've been doing to have wildcard externals

**Comment by evanw** [comment]
FWIW you can do this as a plugin pretty easily. The plugin API is documented here: https://esbuild.github.io/plugins/.

**Comment by Ventajou** [comment]
Thanks, I'll close this. Been too busy to get into the plugins but now that they're there this will no longer be needed

**Comment by evanw** [comment]
The latest release allows you to use a single `*` wildcard for externals such as `--external:*.png` or `--external:/assets/*`. You can still write a quick plugin if you need something super custom but hopefully wildcards can solve for common cases without needing to write a plugin.
