### ISSUE TITLE
"require is not defined" error when bundling vfile for browser

### ISSUE THREAD

**Issue by cesutherland** [evanw/esbuild#414]
Hi folks, I'm working on some client-side text parsing tools utilizing unified and the https://github.com/vfile/vfile project.

Bundling the `vfile` module for browser, the `path` module is not present.  Adding `path` to `external` results in a build which throws `require is not defined` in the browser.  Here's the bundled lines which are throwing:

![image](https://user-images.githubusercontent.com/348406/94324264-165b0680-ff67-11ea-9243-f7df1009301c.png)

I have a minimal test-case here:
https://github.com/cesutherland/test-cases/tree/master/esbuild/browser-require-path

**Comment by cesutherland** [comment]
OK I found a solution for my test-case here: https://github.com/evanw/esbuild/issues/85#issuecomment-624346338  Adding the `browser` attribute to package.json solves it —

https://github.com/evanw/esbuild/issues/85#issuecomment-624346338

In my project, I've got a few packages in a yarn workspace and this is not working for me (yet).

**Comment by evanw** [comment]
Yes, using `browser` to provide a substitute is a good solution. Does that solution work for you? You said the problem is solved, but then you said it's not working for you. So I'm not sure if you consider this issue to be solved or not.

Also: if you just want to mark `path` as external instead, you are free to define your own version of `require` in the browser environment that does whatever you need it to. This should also be a sufficient primitive for you to build another solution to this problem.

**Comment by cesutherland** [comment]
@evanw thanks for the response!  I was able to fix this in my isolated test case with `browser`, but haven't been able to in my projects yarn workspace.  From a `scribe-worker` package which depends on `scribe-compiler` —

```
$ node scripts/build.js                                                                                                 
../scribe-compiler/node_modules/vfile/core.js:3:19: error: Could not resolve "path" (set platform to "node" when building for node)     
var path = require('path')                                                                                              
                   ~~~~~~                                                                                               
```

I've tried a couple things:

- disabling yarn's hoisting
- setting `browser` in the workspace, compiler & worker packages: `"path": "path-browserify"`
- adding the corresponding `path-browserify` package to the workspace, compiler & worker packages

So `path` isn't resolving across workspace package boundaries.  It does resolve for dependencies npm dependecies of `scribe-worker` itself.

If it's helpful I'm happy to put together a separate minimal test-case, but `external` ought to solve this for me — I can close this out!
