### ISSUE TITLE
[css] named exports instead of default for css modules

### ISSUE THREAD

**Issue by intrnl** [evanw/esbuild#418]
While CSS modules support isn't available yet, it would be nice to see the addition of named exports for it.
Camel case conversion is also be nice to see.

```
// main.js
import * as css from './style.module.css';

document.body.append(
  Object.assign(document.createElement('div'), {
    textContent: 'Hello world!',
    className: css.helloWorld,
  })
)

// style.module.css
.hello-world {
  color: red;
  font-weight: bold;
}

.foo-bar {
  color: blue;
}
```

**Comment by evanw** [comment]
I don't think this would be good to do at this stage because it would unnecessarily lock esbuild into a specific implementation. This seems like something that would be better done as a plugin. Closing.
