### ISSUE TITLE
Can't disable default loaders

### ISSUE THREAD

**Issue by Ventajou** [evanw/esbuild#420]
CSS support is great but I'd love to be able to disable it when using the JS API, however there's no documented way to clear a default loader right now...

**Comment by zmitry** [comment]
I guess you can set css extension loader to none

**Comment by evanw** [comment]
I'm not sure what you mean. You're saying what you want to not happen, but you aren't saying what you want to happen. Are you saying you want importing `.css` files to be a build error that fails the build?

**Comment by Ventajou** [comment]
Ah sorry I should provide better context! I use esbuild as a first build step which hands off the last bit of work to Webpack, so as I explained in #406 I want a number of files to be marked as external.

Ideally, I'll use esbuild plugins and get rid of webpack altogether, but for the time being I just want to easily mark files as external so that Webpack can take care of them. And surprisingly, the easiest way I've found to do that is to run esbuild once and parse the errors to determine which files should be external. It's faster and more accurate than anything else I've tried...

I've been using this setup for several weeks already that it's natural now, I didn't even think about how I was asking for builds to break :)

**Comment by heyheyhello** [comment]
@Ventajou Have you tried something like:

```js
const { build } = require('esbuild');
const skipCSSPlugin = plugin => {
  plugin.setName('skip-css');
  plugin.addResolver({ filter: /\.css$/ }, args => {
    // Optionally do path modifications here if you want like `/public/${args.path}`
    return { path: args.path, external: true, namespace: 'skip-css' };
  });
};
build({
  // ...
  plugins: [
    skipCSSPlugin,
  ],
})
```

My moving the resolution to a new namespace (any name is fine) and marking it as external then it won't use the default loader.

Does using the plugin API this way close the issue?

**Comment by Ventajou** [comment]
@heyheyhello I don't see plugins in the doc, has that been released? I thought it wasn't stable yet

**Comment by heyheyhello** [comment]
You can check the plugins branch, and it has been merged to master I believe. Docs are missing but see #111. Evan has said it's stable and nearly finalized

**Comment by evanw** [comment]
Plugins have been released and documentation is now up: https://esbuild.github.io/plugins/. Closing this since you should be able to do this yourself now.

**Comment by matthewmueller** [comment]
Found myself wanting to prevent JS files from importing CSS files and only allowing CSS files to import CSS files. Here's a plugin in case helpful:

```go
func DisableCSSImportsInJS() esbuild.Plugin {
	return esbuild.Plugin{
		Name: "disable-css-imports-in-js",
		Setup: func(build esbuild.PluginBuild) {
			build.OnResolve(esbuild.OnResolveOptions{Filter: `.css$`}, func(args esbuild.OnResolveArgs) (result esbuild.OnResolveResult, err error) {
				if filepath.Ext(args.Importer) != ".css" {
					return result, fmt.Errorf("esb: non-CSS file %q is not allowed to import CSS file %q", args.Importer, args.Path)
				}
				return result, nil
			})
		},
	}
}
```
