### ISSUE TITLE
error: Could not resolve "simple-exiftool"

### ISSUE THREAD

**Issue by alexkli** [evanw/esbuild#423]
(First of all, awesome tool, great speed!)

### Problem

I tried esbuild for our `node` applications, and it generally works. However, there seems to be an issue with [simple-exiftool](https://www.npmjs.com/package/simple-exiftool) - as soon as it is required, it fails with the error:

```
../../../../../../../nui/esbuild-test/project/index.js:1:8: error: Could not resolve "simple-exiftool" (mark it as external to exclude it from the bundle)
require("simple-exiftool");
        ~~~~~~~~~~~~~~~~~
1 error
```

### Steps to reproduce

Minimalist project to reproduce:

```bash
npm install -g esbuild

mkdir project
cd project

echo 'require("simple-exiftool");' > index.js
esbuild --bundle index.js 
```

Will throw the above error.

### Version

```
> esbuild --version
0.7.8
```

Same issue when using the Javascript API.

### Notes

One hunch: the package.json of simple-exiftool has its [`main` set to `./lib/exif`](https://github.com/ubaltaci/simple-exiftool/blob/master/package.json#L5). But it does not have that file, it only has a [lib/index.js](https://github.com/ubaltaci/simple-exiftool/blob/master/lib/index.js) and also a trivial [`index.js` in the root](https://github.com/ubaltaci/simple-exiftool/blob/master/index.js).

It works fine in our code, so maybe Nodejs' module loader is smart and falls back to `index.js` if the `main` from `package.json` can't be found. Possibly `esbuild` should do the same?

**Comment by alexkli** [comment]
Nodejs module loader seems to work as I assumed. From the [spec](https://nodejs.org/api/modules.html#modules_all_together):

```
LOAD_AS_DIRECTORY(X)
1. If X/package.json is a file,
   a. Parse X/package.json, and look for "main" field.
   b. If "main" is a falsy value, GOTO 2.
   c. let M = X + (json main field)
   d. LOAD_AS_FILE(M)
   e. LOAD_INDEX(M)
   f. LOAD_INDEX(X) DEPRECATED
   g. THROW "not found"
2. LOAD_INDEX(X)

...
LOAD_INDEX(X)
1. If X/index.js is a file, load X/index.js as JavaScript text. STOP
2. If X/index.json is a file, parse X/index.json to a JavaScript object. STOP
3. If X/index.node is a file, load X/index.node as binary addon. STOP

```

Note step 1b. which goes to loading `index.js`.

**Comment by evanw** [comment]
Thanks for reporting this. It does indeed look like esbuild is not following the spec correctly. This will be fixed in the next release.

**Comment by alexkli** [comment]
Thanks, I can confirm the fix!
