### ISSUE TITLE
Bundling fails with TypeScript 4 catch clause bindings

### ISSUE THREAD

**Issue by bkiac** [evanw/esbuild#435]
Build with `--bundle` fails if code has `unknown` on `catch` clause bindings.
I'm not sure if this is expected because the type system should be irrelevant for `esbuild`, but I can't get it to work.

Here is my error:
```bash
$ yarn esbuild --bundle src/index.ts --minify --sourcemap
src/hooks/useRequest.ts:160:18: error: Expected ")" but found ":"
        } catch (error: unknown) {
                      ^
1 error
error Command failed with exit code 1.
```

**Comment by evanw** [comment]
Thanks for the report. I didn't catch this in the recent TypeScript release notes. Just fixed it in version 0.7.10.
