### ISSUE TITLE
error: Invalid define: --define:process.env.NODE_ENV=development

### ISSUE THREAD

**Issue by kidandcat** [evanw/esbuild#44]
Getting error: 

`error: Invalid define: --define:process.env.NODE_ENV=development`

When executing the react example with:

`esbuild index.jsx --bundle '--define:process.env.NODE_ENV="development"' --outfile=out.js`

OS: Windows

**Comment by amursky** [comment]
When wrapping define in brackets as in the react example, the error is:
```npx esbuild index.jsx --bundle --minify --outfile=out.min.js '--define:process.env.NODE_ENV="production"'
error: Use --outdir instead of --outfile when there are multiple entry points```

And when not wrapping:
```npx esbuild index.jsx --bundle --minify --outfile=out.min.js --define:process.env.NODE_ENV="production"
error: Invalid define: --define:process.env.NODE_ENV=production```

**Comment by amursky** [comment]
Solved by wrapping `production` in single quotes:
`npx esbuild index.jsx --bundle --minify --outfile=out.min.js --define:process.env.NODE_ENV='production'`

**Comment by evanw** [comment]
What shell is this? cmd.exe? WSL? Cygwin? Something else?

**Comment by amursky** [comment]
I'm using cmder, it's using ConEmu under the hood.

**Comment by ivanjeremic** [comment]
How would this look like when using a JavaScript config file? ```
require("esbuild")
  .build({
    entryPoints: ["app.jsx"],
    bundle: true,
    inject: ["./react-shim.js"],
    outfile: "out.js",
    define: process.env.NODE_ENV = "production",
  })
  .catch(() => process.exit(1));

```

**Comment by gopal-virtual** [comment]
@ivanjeremic  Any argument in the command line is converted to a key-value pair. So it will look something like
```
{
    "process.env.NODE_ENV": `"production"`
}
```
If you are struggling to set this up, use a [starter-template](https://www.npmjs.com/package/@gvirtual/create-esbuild-starter) instead.

**Comment by ivanjeremic** [comment]
> @ivanjeremic Any argument in the command line is converted to a key-value pair. So it will look something like
> 
> ```
> {
>     "process.env.NODE_ENV": `"production"`
> }
> ```
> 
> If you are struggling to set this up, use a [starter-template](https://www.npmjs.com/package/@gvirtual/create-esbuild-starter) instead.

I try to setup esbuild for using a react component library, specifically there is one hook I want to make public on NPM and since rollup and webpack are not so my taste I wanted to learn esbuild and use it for that npm package(react hook), Can esbuild be used for this?
