### ISSUE TITLE
Benchmark comparison details

### ISSUE THREAD

**Issue by robpalme** [evanw/esbuild#443]
The TypeScript benchmark is unclear on whether the non-esbuild alternatives are including type-checking?  If possible type-checking should be disabled for it to be a legit comparison.

**Comment by evanw** [comment]
From the benchmark details in the readme:

> Webpack uses `ts-loader` with `transpileOnly: true`

The [documentation](https://github.com/TypeStrong/ts-loader/blob/cafc933deccd2ea816d41a8de0289d8a8ce36348/README.md#transpileonly) for `ts-loader` indicates that this option disables type checking. As far as I can tell, Parcel doesn't check for type errors in TypeScript code by default. I double-checked this by adding a type error and both Parcel and Webpack didn't report any type errors when building the benchmark.

**Comment by mischnic** [comment]
> Parcel doesn't check for type errors in TypeScript code by default

Correct

**Comment by evanw** [comment]
Closing since I think this question is sufficiently answered.
