### ISSUE TITLE
sourcemap path problem

### ISSUE THREAD

**Issue by yoyo930021** [evanw/esbuild#444]
Thanks to the author for amazing work.

I will try to use `esbuild` in [Vetur](https://github.com/vuejs/vetur) project https://github.com/vuejs/vetur/pull/2301.
This project have a lot of dependencies that make it hard to bundle and minify.
The `esbuild` is 128x faster than `rollup`. 
The cost time is from `6m 24.9s` to `3s`.

The VSCode debugger is broken with `esbuild` sourcemap.
I find two problems with sourcemap.
- The sourcemap `sources` path is base on esbuild execution path.
To be precise, it should be based on outFile path.
I need to hack `process.cwd()` for pin it.
https://github.com/vuejs/vetur/blob/2dd9fa83678a1f40cf78d4f1a13756eef78bd1e2/build/rollup-plugins.js#L30.
- The sourcemap don't have `sourceRoot`.
vscode debugger can't resolve path.
so I need to overrides to absoulte path.
https://github.com/vuejs/vetur/blob/2dd9fa83678a1f40cf78d4f1a13756eef78bd1e2/.vscode/launch.json#L32.

If we're fixing the first problem, it seems the second one isn't necessary.

**Comment by evanw** [comment]
The fix has now been published. Can you verify that source map paths are now working in VSCode?

**Comment by yoyo930021** [comment]
> The fix has now been published. Can you verify that source map paths are now working in VSCode?

The new version works well.
Thanks for help.
