### ISSUE TITLE
Option to mark all non-relative imports as external

### ISSUE THREAD

**Issue by intrnl** [evanw/esbuild#445]
This option could be handy for libraries where they'd only want to bundle their source code without also including whatever dependencies they might have. Manually managing a list of modules to exclude can be painful to keep in sync for larger libraries with tons of direct dependencies.

**Comment by chowey** [comment]
As a workaround, you could use your `package.json` file to keep track of your dependencies. This is usually a viable option, because you are probably already listing all of your direct dependencies in the `package.json` file.

**Comment by evanw** [comment]
FWIW this should be trivial to do with a plugin when the plugin API comes out.

**Comment by water-a** [comment]
Here's a simple plugin that accomplishes it!
```
const plugin: Plugin = {
  name: 'Set non-relative imports as externals',
  setup(build) {
    build.onResolve({ filter: /^[^\.]/ }, (args) => {
      return { path: args.path, external: true };
    });
  },
};
```
Basically it just checks it filters for imports without a dot at the beginning and sets it as an external module.

**Comment by evanw** [comment]
> Here's a simple plugin that accomplishes it!

Yes, this is exactly right. I'm closing this because this is now possible with a plugin.
