### ISSUE TITLE
[typescript] Option to remove only type imports

### ISSUE THREAD

**Issue by intrnl** [evanw/esbuild#448]
The option to remove only type imports that was introduced with TS 3.8 would be nice, that would remove the need to remove unused imports, which might be needed (if we're combining esbuild with some other transformations like svelte compiler)

```
// only remove this
import type { Type } from 'foo';
// don't remove this
import { unusedImport } from 'foo';
```

**Comment by evanw** [comment]
I just read up on this a bit. It looks like the matching config option from TypeScript is called `importsNotUsedAsValues` and was introduced by https://github.com/microsoft/TypeScript/pull/35200. Whatever solution that ends up being used here should be mindful of that precedent.

**Comment by intrnl** [comment]
Is this accessible via transforms API as well?

**Comment by intrnl** [comment]
@evanw Could this be accessible via transforms API as well?
Would be nice to have it as a way to preprocess TS inside Svelte components.
