### ISSUE TITLE
【npm-vue(vite)】After installing the esbuild package, an error is reported when using esbuild

### ISSUE THREAD

**Issue by idrnyu** [evanw/esbuild#452]
The error is as follows.
what should I do

`
yarn install v1.22.4

warning package.json: No license field
info No lockfile found.
warning competence-market-4@0.0.0: No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Rebuilding all packages...
error C:\Users\yy\Desktop\Competence-market\competence-market-4\node_modules\esbuild: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: C:\Users\yy\Desktop\Competence-market\competence-market-4\node_modules\esbuild
Output:
Trying to install "esbuild-windows-64" using npm
Failed to install "esbuild-windows-64" using npm: EBUSY: resource busy or locked, rmdir 'C:\Users\yy\Desktop\Competence-market\competence-market-4\node_modules\esbuild\.install'
Trying to download "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.6.34.tgz"
Failed to download "https://registry.npmjs.org/esbuild-windows-64/-/esbuild-windows-64-0.6.34.tgz": connect ETIMEDOUT 104.16.24.35:443
Install unsuccessful
`

**Comment by heyheyhello** [comment]
Are you able to download the tar.gz directly from the download link in the error?

**Comment by idrnyu** [comment]
> Are you able to download the tar.gz directly from the download link in the error?

The company's intranet was blocked.
But tar.gz can be downloaded on other computers.
How to add to the project after manual download? Copy to (node_modules)?
