### ISSUE TITLE
Minification error when bundling graphql (specifically minifyIdentifiers)

### ISSUE THREAD

**Issue by mhart** [evanw/esbuild#454]
Getting the following error thrown (I assume from `graphql`) when running a bundle, but *only* when `minifyIdentifiers` is `true`:

```
Error: Cannot use e "__Schema" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions

Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
```

I haven't narrowed down a small test case yet – will update when I do.

Running `terser` on the non-minified bundle produces a working bundle, so I suspect it's a bug specifically in esbuild's minification.

**Comment by mhart** [comment]
Have narrowed it down to `minifyIdentifiers` – the other minification options don't cause a problem

**Comment by mhart** [comment]
So the relevant check in `graphql` is here:

https://github.com/graphql/graphql-js/blob/bbd8429b85594d9ee8cc632436e2d0f900d703ef/src/jsutils/instanceOf.js#L19-L44

So adding the following to my esbuild options makes it work:
```
  define: {
    'process.env.NODE_ENV': '"production"',
  },
```

Gonna close this as that's the workaround – but still intriguing that it minifies ok with Terser without needing any changes.

**Comment by gjhommersom** [comment]
I found this issue after running into the same problem with graphql `14.7.0`. 

I managed to fix this by updating to the latest version of graphql `16.12.0`.
