### ISSUE TITLE
Option to specify import path for local externals

### ISSUE THREAD

**Issue by mhart** [evanw/esbuild#456]
Currently `esbuild` will modify any `require('./mydep')` calls to be a relative path from the resulting bundle if `./mydep` is marked as external.

This is a problem if you bundle into, say, a `dist` directory and the path is modified to `require('../some/original/path/mydep')` and points outside the build directory completely.

If there were a way to change this behavior (eg, by providing what it should map to), or even just an option to leave the original import path alone, that would be great! (obviously it requires the user moving the external file to the correct location in `dist` – but I assume that's true of any external module)

**Comment by evanw** [comment]
Note to self: I wonder if this could be handled using a resolver plugin once the plugin API comes out (issue #111).

**Comment by evanw** [comment]
I'm closing this because it's now possible to do this with a plugin. Here's an example:

```js
let importPathPlugin = {
  name: 'import-path',
  setup(build) {
    build.onResolve({ filter: /^\.\/mydep$/ }, args => {
      return { path: args.path, external: true }
    })
  },
}

require('esbuild').build({
  ...
  plugins: [importPathPlugin],
  ...
})
```

More documentation about the plugin API can be found here: https://esbuild.github.io/plugins/.

**Comment by bestickley** [comment]
The plugin is a fair workaround. Thank you. But why doesn't: `externals: ["./mydep"]` work? I know that doesn't allow for remapping the location, but I don't need to remap.

**Comment by speich** [comment]
> I'm closing this because it's now possible to do this with a plugin.

Unfortunately, if you are using the externals flag with the CLI, your out of luck, since plugins are not supported, right?
