### ISSUE TITLE
[0.7.15]: Sourcemap broken in Windows

### ISSUE THREAD

**Issue by darkdamp** [evanw/esbuild#463]
I just updated my site from "esbuild": "^0.6.27" to "esbuild": "^0.7.15"
This sort of broke my sourcemaps in Windows 10 chrome

Here's with 0.7.15
![1](https://user-images.githubusercontent.com/11677530/96257784-4b350900-0fbb-11eb-89a6-af71ab07acf2.PNG)
![2](https://user-images.githubusercontent.com/11677530/96257820-57b96180-0fbb-11eb-86de-65e9195e81bb.PNG)

The "fix" for it seem to be to put every path in the .js.map file into forward slashes
![3](https://user-images.githubusercontent.com/11677530/96257847-63a52380-0fbb-11eb-8db6-76ac795d12cb.PNG)
![4](https://user-images.githubusercontent.com/11677530/96257865-699b0480-0fbb-11eb-9126-859eff503a75.PNG)

However the chrome debugger also won't trigger on any breakpoints in 0.7.15 but I can't find out why.

**Comment by evanw** [comment]
Ah Windows, the source of the world's path separator problems. Sorry about this. It looks like I didn't catch this problem because my tests are converting `\` to `/`. Will fix.

I wonder why breakpoints are a problem. An initial local test on my end indicates that they still work.
