### ISSUE TITLE
Private props

### ISSUE THREAD

**Issue by dy** [evanw/esbuild#47]
Private fields are Stage3 proposal, supported by major browsers https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Class_fields. Any plans to support it?

**Comment by evanw** [comment]
Yes, definitely. I will support this at least as a pass-through transformation, and maybe also with a lowering pass (using `WeakMap` like TypeScript). Just haven't gotten to it yet.

**Comment by Sceat** [comment]
I'd too love this feature

**Comment by evanw** [comment]
Small update: the private name syntax can now be parsed in the latest release (version 0.4.9). I haven't implemented the transform for older browsers yet, however.

**Comment by evanw** [comment]
This should be working as of esbuild version 0.5.7. I have added support for all kinds of private names (fields, methods, and getters/setters both non-static and static). Please try it out and report bugs if you find any.

**Comment by toji** [comment]
Given that the readme goes out of it's way to point out how slow `WeakMap` can be I'm curious what other approaches were evaluated? One pattern that I've seen for private fields is to use `Symbol`, like so:

```js
const privateField = Symbol("MyClass/privateField");

class MyClass {
  constructor() {
    this.publicField = 0;
    this[privateField] = 1;
  }
}
```

Some quick benchmarking show that this performs closer to regular fields than the `WeakMap` approach. I know that it's observable via use of `Object.getOwnPropertySymbols()`, however, which may be the reason enough to avoid this approach if esbuild requires strict semantic equivalence.

**Comment by evanw** [comment]
> Some quick benchmarking show that this performs closer to regular fields than the `WeakMap` approach. I know that it's observable via use of `Object.getOwnPropertySymbols()`, however, which may be the reason enough to avoid this approach if esbuild requires strict semantic equivalence.

Yes, I have considered that too, but I avoided it for the reason you mentioned. Turning private fields into something that's not private seems like an invalid transformation to me. I could see it being an opt-in transform perhaps.

Part of my hesitation is I've never seen this feature actually used in real-world code. If this feature makes it into more real-world code and 99% of the uses out there don't actually have to do with privacy, then I could see changing the default transformation and have privacy be opt-in instead. But I think it remains to be seen how this feature will actually be used once it gets more wide-spread adoption.
