### ISSUE TITLE
Export ES6 module

### ISSUE THREAD

**Issue by dy** [evanw/esbuild#48]
Now created bundle has commonjs format.
Is there any way to set bundle format to `esm`?

**Comment by evanw** [comment]
No, there isn't yet. That's a good idea though. I'd like to add this feature at some point.

**Comment by arodic** [comment]
This is a must-have in my opinion. ES6 modules are the future. Awesome work Evan.

**Comment by looeee** [comment]
I thought `--target=esnext` would create an ES6 module. 

> This is a must-have in my opinion.

Completely agreed. This tool is blazing fast but no use to me unless it can output ES6 modules.

**Comment by lukejacksonn** [comment]
This would be incredible! Perhaps [`es-module-lexer`](https://github.com/guybedford/es-module-lexer) would make this easier to implement.

**Comment by evanw** [comment]
This is implemented in version 0.4.0 that was just released. Please try it out and let me know if you find any issues.
