### ISSUE TITLE
[typescript] expose importsNotUsedAsValues to transform API

### ISSUE THREAD

**Issue by intrnl** [evanw/esbuild#483]
This was probably already mentioned before, any thoughts on exposing `importsNotUsedAsValues` to the transform API?

This is plenty useful for preprocessing TypeScript within Svelte components, since it doesn't know what variables are being used in the markup (and thus requiring the need for disabling of import removal)

**Comment by evanw** [comment]
One thought is that it could be nice to be able to pass a raw `tsconfig.json` file to the transform API, which should take care of this case but also automatically be more forward-compatible with any additional `tsconfig.json`-specific stuff in the future. It would also keep the API surface of esbuild smaller.

Another thought is that this flag might not do what you want even if it worked. The flag's name is confusing but setting it to `preserve` doesn't actually preserve any of the imported names. The TypeScript compiler only preserves the import statement itself but strips off all of the imported names leaving a bare `import "path"` statement, and esbuild replicates this behavior to match the TypeScript compiler. Basically it only makes sure that the imported file is still imported. Does this flag's behavior work for what you are trying to do?

**Comment by intrnl** [comment]
Ah, that's unfortunate, I didn't realize that it would still remove all the imported names.
