### ISSUE TITLE
Is there a way to support multiple output formats?

### ISSUE THREAD

**Issue by ConsoleTVs** [evanw/esbuild#486]
eg. I would like to bundle using all formats available. I'm currently runing the esbuild 3 times with a single parameter (format) changed. Is it possible to output different files & formats or is it a consideration in the future?

**Comment by evanw** [comment]
This is not possible right now, and is also not something I'm considering. Various parts of the build process depend on the output format, so the simple way of implementing this would just be to run esbuild 3x internally anyway for no additional speed benefit.

I'd like to keep the API simple and adding API surface for running a build multiple times with different parameters seems more complex to me than just running esbuild multiple times.

Why are you looking for this? What about running esbuild three separate times isn't working for you?

**Comment by ConsoleTVs** [comment]
> What about running esbuild three separate times isn't working for you?

That's not a problem considering the speed of the build, but just thought some parts of the compiler can be re-used across calls and therefore make it easier and faster to output. Nevertheless, I was not aware it was so dependent on the single output format. I am currently using `tsup` that uses esbuild under the hood and lets you output multiple formats, considering your answer I assume it just calls the esbuild command for each format. I understand the simple API thing and I would also like to keep it that way, although sometimes it's convenient to have multiple outputs, even if esbuild does re-run everything internally.

Thank you for the answer.

**Comment by evanw** [comment]
No problem. Closing since it sounds like this question has been resolved.
