### ISSUE TITLE
[Feature] Add export information in the metafile

### ISSUE THREAD

**Issue by remorses** [evanw/esbuild#487]
I need to have access to export information, this could be done in the metafile output, something like this

```json
{
  "outputs": {
    "react/index.js": {
      "exports": ["default", "namedExport", "anotherNamedExport"],
      "imports": [
        ...
      ],
      "inputs": {
        ...
      },
      "bytes": 119
    }
}
```

My use case is detecting if a bundle is a commonjs module, i can know this checking if a module has only a default export

**Comment by evanw** [comment]
This sounds good. I will get this in sometime.

**Comment by remorses** [comment]
Thank you for your amazing work ❤️
