### ISSUE TITLE
How to using this with Vue project?

### ISSUE THREAD

**Issue by xuelabi123** [evanw/esbuild#488]

**Comment by evanw** [comment]
Closing as a duplicate of #113. From that thread:

> This is a duplicate of #75. Apparently you can use Vue with esbuild if you use JSX syntax. Otherwise, Vue syntax is not supported by esbuild itself. However, esbuild is being integrated into the Vue ecosystem as a library to transform TypeScript to JavaScript. See the thread for details.

**Comment by tnorthcutt** [comment]
FWIW, for anyone else googling Vue + esbuild things and ending up here, the above comment mentions #113, but I believe should actually mention [#133](https://github.com/evanw/esbuild/issues/133)
