### ISSUE TITLE
Mobile Safari: undefined is not an object (evaluating '__getOwnPropDesc(module, key).enumerable')

### ISSUE THREAD

**Issue by grantspeelman** [evanw/esbuild#489]
We starting receiving the following error only on mobile Safari:

```
undefined is not an object (evaluating '__getOwnPropDesc(module, key).enumerable')
```

Downgrading to 0.7.17 fixed the problem for us

**Comment by evanw** [comment]
Thanks for the report. After some research, I'm guessing this is due to a bug in Safari where `Object.getOwnPropertyDescriptor` is broken for numeric properties: https://github.com/zloirock/core-js/issues/495.
