### ISSUE TITLE
Feature to create a dedicated vendor bundle or chunk like in rollup.

### ISSUE THREAD

**Issue by lukasholzer** [evanw/esbuild#490]
First of all, it is extremely awesome what you are doing @evanw! 

The only thing I'm really missing is to extract some `node_modules` in a **vendor chunk**. As I can use immutable cache headers and they won't change that much in regards of the actual source code I'm producing.

I tried it by having to bundle tasks. One for my actual source code where I mark the dependencies as external and then a second one for the vendor. 
1. The first problem is then that the output in the `iife` format for the browser contains require statements which the browser cannot handle. 
2. The second problem would be on an optimization level as I don't know which parts of the dependency can be dropped and tree-shaked due to the missing references from the input file.

`esbuild ./node_modules/react/index.js --bundle --outfile=vendors.js  --format=iife --global-name=react`

`esbuild main.mjs --bundle --outfile=main.js  --format=iife --external:react`

In rollup there is the function called `manualChunks` where I can specify this very granual in which output chunk it will be bundled. https://rollupjs.org/guide/en/#outputmanualchunks

**Comment by lukasholzer** [comment]
I got it working for now with a very hacky workaround.

defining a vendor file:
```javascript
// vendor.mjs
import * as React from 'react';
import * as ReactDom from 'react-dom';

window.React = React;
window.ReactDom = ReactDom;
```
creating a require shim:
```javascript
// require-shim.js
window.require = (moduleName) => {
  switch (moduleName) {
    case 'react':
      return window['React'];
    case 'react-dom':
      return window['ReactDom'];
    default:
      throw new Error(`Could not resolve module: ${moduleName}`);
  }
};
```

and running:

```bash
esbuild main.mjs \
  --bundle \
  --inject:./require-shim.js \
  --outfile=main.js \
  --format=iife \
  --external:react \
  --external:react-dom \
```

**Comment by zaydek** [comment]
This is very cool. Thanks for sharing! The only problem your code snippet doesn’t solve for is tree-shaking, right? @lukasholzer

Do you have any of your repos that use this technique laying around that you can share?

**Comment by lukasholzer** [comment]
@zaydek yea sadly you cannot know how to tree-shake it but you can have an immutable cache header and have it cached properly. 

Sorry, the repo is sadly not open source :(
I have automated it in our build system to generate the bundle file depending on the imports you are doing. So the vendors file is auto-generated.

Furthermore, I'm using it only for a dev server to have faster recompiles as it does not need to bundle the vendors over and over again.

**Comment by zaydek** [comment]
Thanks for getting back to me @lukasholzer!

Would you be able to share what you mean here? _I have automated it in our build system to generate the bundle file depending on the imports you are doing. So the vendors file is auto-generated._ That is super interesting. Last night I was able to recreate the chunk technique with React but hadn’t imagined how to scale that to support arbitrary dependencies.

I’ve been experimenting here: https://github.com/zaydek/naive-page-based-router.

**Comment by evanw** [comment]
Closing this in favor of #207.
