### ISSUE TITLE
Question: can esbuild provide some api to check es version?

### ISSUE THREAD

**Issue by lcjnil** [evanw/esbuild#491]
Hi, I'd to use esbuild to check es version like [check-es-version-webpack-plugin](https://github.com/bitjourney/check-es-version-webpack-plugin), to ensure my code running on devices which doesn't support es5+.

Do you have any plan to provide API like that?

**Comment by evanw** [comment]
I have no plan to provide an API like that, sorry.

**Comment by evanw** [comment]
Closing because the question was answered.
