### ISSUE TITLE
GraphQL file loader

### ISSUE THREAD

**Issue by hmak-me** [evanw/esbuild#503]
I am migrating my framework from a webpack and babel combo to esbuild and tinkering with the API and the first thing that anybody might notice is the lack of built-in loaders. For example in my case I was using _graphql-tag/loader_ to transform .gql files into JS.

I've already read #111 issue. 
So, do you think it is a good choice to extend the built-in loaders or just wait for an stable version of the Plugin API?
I was wondering if you agree with starting a PR or not...

**Comment by remorses** [comment]
> So, do you think it is a good choice to extend the built-in loaders or just wait for an stable version of the Plugin API?

This would be a perfect case for a js plugin

> I was wondering if you agree with starting a PR or not...

A plugin to load graphql files would live in its own npm pakage, not in the esbuild repository itself

**Comment by Checksum** [comment]
I thought about this as well, but went ahead and built a loader for Elm anyway - https://github.com/Checksum/esbuild-elm-loader. Even if the plugin API changes considerably, the integration points should be conceptually the same (setup the plugin, transform the code, etc). So depending on your urgency, it may make sense to build and use it now, and keep it up-to date if the API changes.

**Comment by evanw** [comment]
> A plugin to load graphql files would live in its own npm pakage, not in the esbuild repository itself

Yes, that's correct. The intent of the plugin API is to make it possible to do things like this without needing to contribute to esbuild itself. Closing this issue since this isn't an issue with esbuild.

**Comment by louisscruz** [comment]
For those out there interested in this, there is now a plugin [`esbuild-graphql-loader`](https://github.com/luckycatfactory/esbuild-graphql-loader) to handle exactly this case.
