### ISSUE TITLE
Is it possible to suppress a warning via a comment?

### ISSUE THREAD

**Issue by LeeCheneler** [evanw/esbuild#512]
I'm getting this warning currently:
```sh
warning: This call to "require" will not be bundled because the argument is not a string literal
```

It's totally legitimate and is a useful warning, however its fine in this instance:
```ts
if (jestConfigExists) {
  try {
    jestConfig = require(jestConfigFilename);
  } catch (error) {
    console.error("Failed to load jest.config.js ->", error?.message ?? "");
    return process.exit(1);
  }
}
```

It would be nice to be able to disable the warning with an explanation like:
```ts
if (jestConfigExists) {
  try {
    // esbuild-disable-warning require-not-bundled - dynamic require is expected and safe here
    jestConfig = require(jestConfigFilename);
  } catch (error) {
    console.error("Failed to load jest.config.js ->", error.message);
    return process.exit(1);
  }
}
```

**Comment by evanw** [comment]
The escape hatch for this is currently to surround the `require()` call with a try/catch statement. However, it looks like it's not applying in this case. That's an oversight, sorry. Will fix.

**Comment by rw3iss** [comment]
Hi @evanw, What do you suggest we do if an imported module is using require() (within itself), and we want to suppress the warning?

**Comment by evanw** [comment]
Some options:

1. Disable warnings with `--log-level=warning`
2. Use esbuild's API instead of the CLI, disable all logging with `logLevel: 'silent'`, and print the data from the `.errors` and `.warnings` properties on the result yourself after filtering them

**Comment by rw3iss** [comment]
Thanks! Am using the API :-)
