### ISSUE TITLE
Can files be extracted from code?

### ISSUE THREAD

**Issue by ym-project** [evanw/esbuild#517]
Hi!

Can I extract files with any extension from code?
For example:
`file.js`
```js
import './style.styl'

function blaBlaBla() {....}
```
I expect what after bundling esbuild will generate:
- file.js
- style.styl

But `.styl` files are not created. I tried such loaders as: `file, binary` and others.
Expected behavior works only with css files.

**Comment by verydanny** [comment]
You have to essentially create a plugin for this Here's some resources:

Issues: #111, #503 

[Example loading `.elm` files:](https://github.com/Checksum/esbuild-elm-loader/blob/master/index.js)

You can technically process the `.styl` into CSS, here's a pseudo-code example:

```ts
import * as fs from 'fs'
import * as path from 'path'
import { BuildOptions, Plugin, OnLoadResult} from 'esbuild'
import stylus from 'stylus'

// Style Loader
export const StylusLoader = (options: BuildOptions = {}): Plugin => ({
  name: 'styl-loader',
  setup(build) {
    build.onResolve({ filter: /\.styl$/ }, (args) => {
      const resolvedPath = path.resolve(
        process.cwd(),
        path.relative(process.cwd(), args.resolveDir),
        args.path
      )

      return {
        path: resolvedPath,
        namespace: 'stylus',
      }
    })

    build.onLoad({ filter: /.*/, namespace: 'stylus' }, async (args) =>
      fs.promises
        .readFile(args.path, { encoding: 'utf-8' })
        .then((stylusString): Promise<OnLoadResult> => {
          return new Promise<OnLoadResult>((resolve, reject) => {
            return stylus(stylusString).render((err, contents) => {
              if (err) {
                return reject(err)
              }

              return resolve({
                contents,
                loader: 'css'
              })
            })
          })
        })
    )
  },
})
```

Then you'd just use the loader like so:

```ts
const code = await build({
  ...buildOptions,
  plugins: [
    StylusLoader()
  ]
})
```

Obviously, I haven't thought of concatenation, ordering, etc. I'm sure that's also in development by @evanw. Although, if you're using stylus, I assume everything is modular and this shouldn't be an issue.

**Comment by ym-project** [comment]
Oh @verydanny , it really works! Thank you!
But as I understand it seems like a hack. Because if we take not a style or not a js file we can not create file.
Am I right?

**Comment by verydanny** [comment]
Sure, you can just use fs to output that file wherever you want instead of resolving with `{contents, loader}`. You can just output undefined for that. I'm pretty sure this is to the API, not really "hacky". You could also do a `js` loader and write "style-loader" for the CSS too, so it injects it into the header or something.
