### ISSUE TITLE
Esbuild generates exports.default instead of module.exports

### ISSUE THREAD

**Issue by ym-project** [evanw/esbuild#529]
Hi!
Could you help me? I made stylus-loader for esbuild ([link](https://github.com/ym-project/esbuild-stylus-loader)). But I faced with problem when commonjs bundle doesn't work as expected.

Esbuild generates `exports.default = `, but I want `module.exports = `. Because of `exports.default` I can not require a package this way `const loader = require()`. Instead of wanted way I require like `const {default: loader} = require()`.

How can I fix it?

All files you can find in loader [repository](https://github.com/ym-project/esbuild-stylus-loader). But I duplicate several files below.

`esbuild config` `scripts/build.js`
```js
{
	entryPoints: [
		path.resolve(__dirname, '..', 'src', 'index.ts'),
	],
	bundle: true,
	// minify: true,
	platform: 'node',
	loader: {
		'.ts': 'ts',
	},
	external: [
		'stylus',
		'path',
		'fs',
	],
	outfile: path.resolve(__dirname, '..', 'npm', 'cjs.js'),
	format: 'cjs',
}
```

`source file` `src/index.ts`
```js
export default function esbuildStylusLoader() {.....}
```

**Comment by evanw** [comment]
I'm confused. If you want `module.exports = function() {}`, why did you not write `module.exports = function() {}`?

When a CJS module is bundled as ESM, esbuild will generate an export called `default` containing the exports of the CJS module. So if the entry point is CJS then I think both the CJS and ESM builds should behave the way you want.

**Comment by ym-project** [comment]
You are right!
I looked at the webpack. And he has the same behavior. For some reason it was logical for me when for `export default` should be generated `module.exports` in cjs format.
Ok, I'll use named export instead of default.

Thank you!
