### ISSUE TITLE
[Feature] Prefix and suffix files

### ISSUE THREAD

**Issue by evanw** [evanw/esbuild#53]
This is a feature request from a friend. Logging it here so I don't forget.

When bundling, have a way to add a prefix and/or suffix JavaScript file that is guaranteed to come before or after the bundle. These files would also generate source maps and would also interact with `--define`. This could be used to, for example, measure how long the execution time of the bundle took by saving `performance.now()` before and after the entry point executes.

**Comment by evanw** [comment]
I'm going to close this because I think the recently-released `--inject` feature essentially satisfies the original feature request. More information is available in [the release notes](https://github.com/evanw/esbuild/blob/03a33e6e007467d99989ecf82fad61bd928a71aa/CHANGELOG.md#0717).

**Comment by rsms** [comment]
Excellent. Thank you
