### ISSUE TITLE
Start using GitHub releases to notify about new releases

### ISSUE THREAD

**Issue by timocov** [evanw/esbuild#535]
This is not issue of the tool.

GitHub has nice option to subscribe on repo's releases (instead of subscribing on any activity in the repo to see what's going on) - it allows you do not track every single activity in the repo, but being notified about new releases. Currently, it seems that there is changelog file and git tags.

Do you have a plan to start to use GitHub releases?

**Comment by evanw** [comment]
It looks like there are already releases being generated, so I imagine you should already be able to subscribe to them: https://github.com/evanw/esbuild/releases. Are you just asking for the commit message to duplicate the information from the changelog for that release?

**Comment by timocov** [comment]
> It looks like there are already releases being generated, so I imagine you should already be able to subscribe to them: evanw/esbuild/releases

Actually it's not releases, it's just git tags on that page I guess. I'm already subscribed on releases and haven't been notified so far :)

(for example how releases page looks like when you create releases - https://github.com/webpack/webpack/releases)

> Are you just asking for the commit message to duplicate the information from the changelog for that release?

Not really. To create github's release you need to open releases page and then select already created tag or just draft new release (without tag at the moment), fill the information about the release (name, git tag to attached to and description - I guess it could be copy-paste from changelog file) and then "publish release". After that all subscribers will be notified about that release. More info on https://docs.github.com/en/free-pro-team@latest/github/administering-a-repository/managing-releases-in-a-repository#creating-a-release.

Yeah, it might be additional work while releasing the new version so I'm not pushing you to use them at all, but I believe it could be useful to people who wants to look at progress of the tool but not get all notifications about every single comment/issue.

Also, it seems that releases could be part of the automatization on GitHub actions - for example in https://github.com/TypeStrong/ts-loader/blob/master/.github/workflows/release.yml when a new release is created (it could be attached to a tag only, so it certainly exists), GA runs publishing the package to npm.

**Comment by rtsao** [comment]
You could probably do something much fancier with GitHub Actions and/or Releases, but https://github.com/evanw/esbuild/pull/539 should address this (and improve the releases page by displaying the relevant section of the changelog for each release) and doesn't alter your existing workflow in any way (you still commit locally, push the version tag, etc).

**Comment by evanw** [comment]
This latest release was published as a GitHub release: https://github.com/evanw/esbuild/releases/tag/v0.8.9. This should be the case from now on.

**Comment by timocov** [comment]
Yeah, it works perfectly now - just got an email with the new release. Thank you @rtsao!
