### ISSUE TITLE
Syntax error when using ternaries + async fat arrow + typecast

### ISSUE THREAD

**Issue by arcanis** [evanw/esbuild#541]
I admit the title is very specific 😄

The following structure doesn't parse with ESBuild, but seems fine per the TS playground:

```ts
_ as any ? async () => _ : _;
```

**Comment by rtsao** [comment]
It appears this is actually a broader issue with typecasted ternary conditions, it's just that this particular case results in a parse error.

For example, esbuild currently transformed `a as any ? b : c` to `a;`

**Comment by evanw** [comment]
The fix for this has been released. Thanks so much for reporting this.
