### ISSUE TITLE
Question about incremental builds behavior

### ISSUE THREAD

**Issue by henriquehbr** [evanw/esbuild#558]
I'm working on [`eswatch`](https://github.com/henriquehbr/eswatch), a file-watcher for esbuild, by default, if you don't specify a `--outdir` flag, the build output is stored on `node_modules/eswatch/lib/build/`

but there's a problem, between the builds, if a file is renamed or deleted, it's not removed from `node_modules/eswatch/lib/build/`, making the default output directory unnecessarily bloated, to fix this, i'm cleaning this folder before every build with [`rimraf`](https://github.com/isaacs/rimraf)

Can still benefit from the faster builds offered by the incremental mode even by removing the built files from the output? or they don't interfere with esbuild cache

**Comment by heyheyhello** [comment]
Do you need to be writing files to disk? With `--serve` available on esbuild storing files might be unnecessary, and then its esbuild's job to handle the in-memory cache of the build "files".

**Comment by henriquehbr** [comment]
Not really, i just need to be able to execute the transpiled javascript, i'll try with `--serve`, saw it on changelog on `0.8.12` release, but didn't realised how useful it could come to be, thank you!

**Comment by evanw** [comment]
> Can still benefit from the faster builds offered by the incremental mode even by removing the built files from the output? or they don't interfere with esbuild cache

The files are re-written on every incremental build so you can delete the build folder after every build if you'd like. This doesn't interfere with the cache.
