### ISSUE TITLE
Cannot invoke an object which is possibly 'undefined'

### ISSUE THREAD

**Issue by henriquehbr** [evanw/esbuild#559]
I'm not sure if this is intended, but the `.rebuild()` method from the `BuildResult` interface, accordingly to the snippet below, can also be undefined:

https://github.com/evanw/esbuild/blob/2fa473e4c2f5374e066353c9d37bdc8afa8da734/lib/types.ts#L88

Because of this, is necessary to adhere to some hacky solutions like this:

```typescript
const buildResult = await esbuildService.build({ ...esbuildConfig, incremental: true })
buildResult.rebuild!() // non-null assertions defeats the purpose of using "strict: true" on tsconfig.json
```

or also:

```typescript
const buildResult = await esbuildService.build({ ...esbuildConfig, incremental: true })
buildResult.rebuild && buildResult.rebuild()
```

or even this:

```typescript
const buildResult = await esbuildService.build({ ...esbuildConfig, incremental: true })
buildResult.rebuild?.call(this)
```

Is there anything that i'm missing? as shown in the example from [`0.8.12`](https://github.com/evanw/esbuild/blob/master/CHANGELOG.md#0812) release https://github.com/evanw/esbuild/blob/master/CHANGELOG.md), there were no need for any checking to use the `.rebuild()` method

```javascript
require('esbuild').build({
  entryPoints: ['app.js'],
  bundle: true,
  outfile: 'out.js',
  incremental: true,
}).then(result => {
  // The "rebuild" method is present if "incremental" is true. It returns a
  // promise that resolves to the same kind of object that "build" returns.
  // You can call "rebuild" as many times as you like.
  result.rebuild().then(result2 => {
    // Call "dispose" when you're done to free up resources.
    result.rebuild.dispose()
  })
})
```

**Comment by heyheyhello** [comment]
It says 

> "The rebuild method is present **if** "incremental" is true

So that's why it's undefined. You might be able to do some TypeScript hackery to return a version of BuildResult with that one property added as non-optional, but I don't know if it's worth it since `!` works
