### ISSUE TITLE
Using --format=esm and --external:package produces code containing require() calls for package

### ISSUE THREAD

**Issue by remorses** [evanw/esbuild#566]
Using `--format=esm` and `--external:package` produces code containing require() calls for `package`

I would like to have require calls on the external package to be converted to ES imports instead of require calls, to make the bundle valid ESM code 

Reproduction: https://github.com/remorses/reproduction-esbuild-require-in-esm-with-externals

**Comment by evanw** [comment]
This transformation isn't done automatically because it's impossible in the general case to preserve the semantics of the original code when you do this. It's a lossy transformation. Evaluation order would be changed and conditional imports would be changed into unconditional imports.

One way to fix this if you're running the code in node is to bring back the `require` function before your code is run. It's unfortunate that the `require` function is missing in node by default. You can get it back by using a stub file like this to load your code:

```js
import { createRequire } from 'module'
global.require = createRequire(import.meta.url)
import('./your-code.mjs')
```

If you are ok with changing the semantics of your code, another way to work around this is to use a plugin to convert `require` calls to `import` statements:

```js
const externalCjsToEsmPlugin = external => ({
  name: 'external',
  setup(build) {
    let escape = text => `^${text.replace(/[-\/\\^$*+?.()|[\]{}]/g, '\\$&')}$`
    let filter = new RegExp(external.map(escape).join('|'))
    build.onResolve({ filter: /.*/, namespace: 'external' }, args => ({
      path: args.path, external: true
    }))
    build.onResolve({ filter }, args => ({
      path: args.path, namespace: 'external'
    }))
    build.onLoad({ filter: /.*/, namespace: 'external' }, args => ({
      contents: `export * from ${JSON.stringify(args.path)}`
    }))
  },
})
```

You would use it like this:

```js
require('esbuild').build({
  bundle: true,
  outdir: 'bundle',
  format: 'esm',
  target: 'es2017',
  entryPoints: ['./src/index.ts'],
  plugins: [externalCjsToEsmPlugin(['react', 'react-dom'])],
})
```

**Comment by LXSMNSYC** [comment]
Interesting, although the package in the repro (`react-storage-hooks`) doesn't have an ESM bundle and so esbuild probably fallbacks to its only dist format which is the CJS format?

**Comment by remorses** [comment]
I tried the plugin solution [here](https://github.com/remorses/reproduction-esbuild-require-in-esm-with-externals/pull/1) and it works well

My use case was creating a bundle without any dependency apart from peer dependencies

**Comment by buronnie** [comment]
Hi @evanw , could you elaborate how this plugin can "convert require calls to import statements"? I thought it would change 
```
const URI = require('uri-js');
```
to 
```
import URI from 'uri-js';
```
but the plugin seems to only change the content of the dependency lib to export statement. I don't quite understand how this would help to solve the problem in this thread. Thanks!

**Comment by remorses** [comment]
@buronnie, basically esbuild replaces the lib contents with an esm export from the external package, this means that there won't be any require calls in the bundle

If you want to try this yourself i published a plugin to do this https://github.com/remorses/esbuild-plugins/tree/master/esm-externals

**Comment by buronnie** [comment]
Thank you @remorses. This works well for both "require cjs module" and "import es module". But it doesn't work for "import cjs module" (e.g. `import _ from lodash`). The reason i need to consider different cases is because i dynamically traverse the dep tree and whenever an external lib is found, i will bundle it separately. I wonder if `onResolve` callback can provide info about how module is imported (with `import` or `require`), so at least i can apply this solution to only `require` statement.

**Comment by buronnie** [comment]
I also notice that this plugin doesn't seem to work for `lodash`. 
```
const lodash = require('lodash');
console.log(lodash.upperCase('abc'));
``` 
will be transpiled to 
```
import * as default2 from "lodash";
import * as lodash_star from "lodash";
var require_lodash = __commonJS((exports) => {
  __markAsModule(exports);
  __export(exports, {
    default: () => default2
  });
  __exportStar(exports, lodash_star);
});

// src/index.js
var lodash = require_lodash();
console.log(lodash.upperCase("abc"));
```
instead `lodash.default.default.upperCase("abc")` will work.

**Comment by aral** [comment]
Just a note that this also affects requires of Node standard libraries in builds where `--platform=node --target=node`.

**Comment by forthealllight** [comment]
> upperCase

I have the same problem. Absolutely, it's " instead lodash.default.upperCase("abc") will work" ,but I want " "lodash.upperCase("abc") " . . how  to achieve it .

**Comment by forthealllight** [comment]
> I also notice that this plugin doesn't seem to work for `lodash`.
> 
> ```
> const lodash = require('lodash');
> console.log(lodash.upperCase('abc'));
> ```
> 
> will be transpiled to
> 
> ```
> import * as default2 from "lodash";
> import * as lodash_star from "lodash";
> var require_lodash = __commonJS((exports) => {
>   __markAsModule(exports);
>   __export(exports, {
>     default: () => default2
>   });
>   __exportStar(exports, lodash_star);
> });
> 
> // src/index.js
> var lodash = require_lodash();
> console.log(lodash.upperCase("abc"));
> ```
> 
> instead `lodash.default.default.upperCase("abc")` will work.

I have the same problem. Absolutely, it's " instead lodash.default.upperCase("abc") will work" ,but I want " "lodash.upperCase("abc") " . . how to achieve it .

**Comment by guest271314** [comment]
Still have to handle occurrences of `__dirname` in CommonJS source code using the `RegExp` approach.

I think I have a script that `deno` simply fails to produce the expected result unless CommonJS/`require()` is used.

**Comment by guest271314** [comment]
I'm using a modified version of the code here https://github.com/evanw/esbuild/issues/566#issuecomment-735551834, targeting `deno`, `bun`, and `node`, mainly to handle Node.js-specific built-in modules.


- Write all builtin `node:` modules to `imports` Import Map object `deno.json` in the form `"fs":"node:fs"`
- Convert `require()` in CommonJS source code to static ECMAScript `import` with `esbuild`
- `import` `process` for Deno
- Define `Buffer` globally for Deno
- Define `__dirname` as `import.meta-dirname` for Deno
- Define `__filename` as `import.meta-filename` for Deno

```
// bun build --target=node --packages=external esbuild.js --outfile=esbuild-esm.js
import { createRequire } from "node:module";
var __commonJS = (cb, mod) => () => (mod || cb((mod = { exports: {} }).exports, mod), mod.exports);
var __require = /* @__PURE__ */ createRequire(import.meta.url);

// esbuild.js
var require_esbuild = __commonJS(() => {
  // Write builtin node modules to deno.json
  // fs => node:fs ...
  var fs = __require("node:fs");
  var builtinModules = __require("node:module").builtinModules;
  var denoJSON = fs.readFileSync("deno.json", "utf8");
  var json = JSON.parse(denoJSON);
  var builtinImports = json.imports;
  for (const mod of builtinModules) {
    if (!/^node:/.test(mod)) {
      builtinImports[mod] = `node:${mod}`;
    } else {
      builtinImports[mod] = mod;
    }
  }
  fs.writeFileSync("deno.json", JSON.stringify(json, null, 2), "utf8");
  // Convert require() to static import with esbuild ECMAScript Modules
  var externalCjsToEsmPlugin = (external) => ({
    name: "node",
    setup(build) {
      try {
        let escape = (text) => `^${text.replace(/[-\/\\^$*+?.()|[\]{}]/g, "\\$&")}$`;
        let filter = new RegExp(external.map(escape).join("|"));
        build.onResolve({ filter: /.*/, namespace: "node" }, (args) => ({
          path: args.path,
          external: true
        }));
        build.onResolve({ filter }, (args) => ({
          path: args.path,
          namespace: "node"
        }));
        build.onLoad({ filter: /.*/, namespace: "node" }, (args) => ({
          contents: `export * from ${JSON.stringify(args.path)}`
        }));
      } catch (e) {
        console.warn("esbuild error:", e);
      }
    }
  });
  __require("esbuild").build({
    bundle: true,
    outfile: "fopen-wasm-esbuild.js",
    format: "esm",
    target: "esnext",
    entryPoints: ["./fopen-wasm.js"],
    plugins: [externalCjsToEsmPlugin(builtinModules)]
  }).then(() => {
    // Write to file generated by esbuild
    // import process from "node:process" for Deno
    // Define Buffer globally for Deno
    // Define __dirname as import.meta-dirname for Deno
    // Define __filename as import.meta-filename for Deno
    let file = fs.readFileSync("./fopen-wasm-esbuild.js", "utf-8");
    file = `
import process from "node:process";
globalThis.Buffer ??= (await import("node:buffer")).Buffer;
globalThis.__dirname = import.meta.dirname;
globalThis.__filename = import.meta.filename;

${file}`;
    fs.writeFileSync("./fopen-wasm-esbuild.js", file);
  }).catch(console.log);
});
export default require_esbuild();
```

Which produces code in `fopen-wasm-esbuild.js` that looks like this 

```
// node:fs
var fs_exports = {};
import * as fs_star from "fs";
var init_fs = __esm({
  "node:fs"() {
    __reExport(fs_exports, fs_star);
  }
});

// node:path
var path_exports = {};
import * as path_star from "path";
var init_path = __esm({
  "node:path"() {
    __reExport(path_exports, path_star);
  }
});

// node:crypto
var crypto_exports = {};
import * as crypto_star from "crypto";
var init_crypto = __esm({
  "node:crypto"() {
    __reExport(crypto_exports, crypto_star);
  }
});

```

**Comment by kettanaito** [comment]
I wonder how people managed to get this working in `esbuild` through `tsup` as the `onResolve` callback never fires for third-party modules there, only for relative modules you import in your code.
