### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by anand-sundaram-zocdoc** [evanw/esbuild#570]
I see that esbuild has both open and merged pull requests from several contributors, and also a very promising roadmap. However, there are no docs in the repo on contributing so I don't know what process to follow if I hope to:

1. Identify something useful that is not already being worked on that I can work on and open a PR for
2. If I have an idea, propose that in the way that is most useful to the maintainers (open an issue? open a PR? Some other preliminary process before either of those?)

**Comment by brandly** [comment]
i can't speak with any authority, but i'll share a couple links:
* month's ago, [Evan wasn't looking for contributions](https://github.com/evanw/esbuild/pull/9#issuecomment-587181024)
* [the roadmap](https://esbuild.github.io/faq/#upcoming-roadmap) seems well-defined, and as mentioned there, he doesn't plan on continuing to extend esbuild forever

so i don't think you'll get what you're looking for out of this repo. sorry!

**Comment by evanw** [comment]
Yes, that's correct. I'm not looking for contributions for contributions' sake. If you have a specific problem with esbuild or there is some change that you would like to see, it's best to file an issue so we can work through it together. I've been taking contributions for small bug fixes and for small features if they are in line with the vision.

**Comment by evanw** [comment]
Closing due to age.
