### ISSUE TITLE
Transform require/import syntax of "externals" to match output format?

### ISSUE THREAD

**Issue by popeindustries** [evanw/esbuild#572]
Presently (0.8.17), when marking a dependency as `external` (via `externals` argument or custom `onResolve` plugin), the original import syntax is preserved instead of being transformed to match that of the output `format`. 

For example, when bundling a cjs file to esm:

```js
const ms = require('ms');
module.exports = ms('10m');
```

...with `externals: ['ms']` and `format: 'esm'` results in:

```js
var __commonJS = (callback, module) => () => {
  if (!module) {
    module = {exports: {}};
    callback(module.exports, module);
  }
  return module.exports;
};

// input.js
var require_input = __commonJS((exports) => {
  var ms = require("ms");
  exports.dep = ms("10m");
});
export default require_input();
```

...which preserves the original `var ms = require("ms")` instead of transforming to `import ms from "ms"` to match the output format.

Perhaps it's out of scope, but fixing something like this in user space, without access to the AST, would be quite error prone.

**Comment by evanw** [comment]
This is a duplicate of #566.

> fixing something like this in user space, without access to the AST, would be quite error prone

It's actually easy to do this with a plugin: https://github.com/evanw/esbuild/issues/566#issuecomment-735551834.

**Comment by popeindustries** [comment]
Sorry for the duplicate! I'll take a look at the plugin solution.
