### ISSUE TITLE
Windows detected esbuild binary as  PUA:Win32/Puwaders.B!ml

### ISSUE THREAD

**Issue by rizkyramadhan** [evanw/esbuild#579]
![image](https://user-images.githubusercontent.com/126301/101268565-d4d0ae00-3796-11eb-8e82-87ee559dcfc4.png)

Windows annoyingly detected esbuild as a malware, and yarn/npm refused to install, here is [Learn More](https://go.microsoft.com/fwlink/?linkid=142185&name=PUA:Win32/Puwaders.B!ml&threatid=242877)  Link.

**Comment by evanw** [comment]
Ugh. That is unfortunate. I assume this isn't specific to version 0.8.17 since that version was about support for the M1 processor on macOS. It looks like Microsoft accepts false positive reports here: https://www.microsoft.com/en-us/wdsi/filesubmission?persona=SoftwareDeveloper. I can file it.

**Comment by rizkyramadhan** [comment]
Yup,

  "dependencies": {
    "esbuild": "^0.8.17",

previous version works fine, and no nagging received.

**Comment by evanw** [comment]
Ok I submitted this executable as a false positive to Microsoft. The submission ID is 74cb41d6-7806-4136-b340-900670d01cc7. I think that's all I can do on my end, so I'm going to close this issue. I'll let you know if I get any updates from Microsoft.

**Comment by evanw** [comment]
Here's what I got back from Microsoft:

> We have removed the detection. Please follow the steps below to clear cached detection and obtain the latest malware definitions.
> 
> 1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender
> 2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
> 3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
