### ISSUE TITLE
Dead code after return statment isn't removed during minification

### ISSUE THREAD

**Issue by fa93hws** [evanw/esbuild#580]
```
/* eslint-disable */
function spyReport(event) {
  if (true) return;
  if (!globalState.spyListeners.length) return;
  const listeners = globalState.spyListeners;
  for (let i = 0, l = listeners.length; i < l; i++) {
    listeners[i](event);
  }
}

spyReport(asdf);
```
is minified to
```
(()=>{function n(s){return;if(!globalState.spyListeners.length)return;for(let e=0,l=t.length;e<l;e++)t[e](s)}n(asdf);})();
```
while it should be 
```
(()=>{function n(s){return;}n(asdf);})();
```

## How to reproduce?
create `any.js` which have the following content
```
/* eslint-disable */
function spyReport(event) {
  if (true) return;
  if (!globalState.spyListeners.length) return;
  const listeners = globalState.spyListeners;
  for (let i = 0, l = listeners.length; i < l; i++) {
    listeners[i](event);
  }
}

spyReport(asdf);
```

build it with `esbuild any.js --bundle --minify --outfile=any.dist.js`

esbuild version: 0.8.7
node version: v12.16.1
OS: macOS Catalina 10.15.7

**Comment by fa93hws** [comment]
Ah actually it does remove the code after return..
The code is more complicated in my case and it doesn't do so in some cases, let me dive into it to investigate.

**Comment by evanw** [comment]
Thanks for the report. It looks like control flow liveness is not propagated to subsequent sibling statements. I'll fix this.
