### ISSUE TITLE
Title of the project

### ISSUE THREAD

**Issue by kripken** [evanw/esbuild#59]
The title says:

> An extremely fast JavaScript bundler and minifier

But it could be:

> Extremely Speedy Build tool for JavaScript 

Then it would be sort of a double meaning acronym... :wink: 

Thanks for this awesome project!

**Comment by evanw** [comment]
Haha, nice! I didn't pick up on that acronym possibility. I think I'll keep the title the way it is for now though.

> Thanks for this awesome project!

I could say the same to you: thanks so much for creating emscripten. What an incredible transformation of the ecosystem it has caused. And the ripples of it are still spreading. We at Figma are eternally grateful! 😁
