### ISSUE TITLE
How to use local esbuild binary in the npm package?

### ISSUE THREAD

**Issue by remorses** [evanw/esbuild#592]
I am trying to debug an error in esbuild golang code but i cannot find an easy way of using my local esbuild binary in the `esbuild` npm package

Maybe we can add an option `binaryPath` or use an environment variable `ESBUILD_BINAERY_PATH` as a solution, what do you think?

**Comment by evanw** [comment]
There is already a way to do this because esbuild has to do this during its tests. Look for the function `installForTests()` and its uses. Long story short if you install the `esbuild` package with the `ESBUILD_BIN_PATH_FOR_TESTS` environment variable configured, the install script will use that path instead of downloading the binary executable from the internet.

**Comment by prantlf** [comment]
If you need more than swapping testing `esbuild` binaries, if you need to step through the Go code in a debugger, you can make your IDE execute and debug a custom `esbuild` binary using the `esbuild` sources. It can help if looking for a problem by adding extra logging or other output and building test binaries is getting too long.

For example, you can clone this repository and open its folder in VS Code. Once you install the `golang.go` extension for VS Code, you will be able to create a launcher for `esbuild`. You would figure out the command line parameters that the `esbuild` executable needs to build your project (or a part of it) and use them together with the path to your project as the current directory. For example:

```json
{
  "name": "test build",
  "type": "go",
  "request": "launch",
  "mode": "auto",
  "program": "${workspaceFolder}/cmd/esbuild",
  "cwd": "/home/me/sources/myproject",
  "args": [
    "--bundle", "src/entry.js", "--outfile=out/bundle.js"
  ]
}
```

Then you can place breakpoints to `esbuild` source files, start a debugging session by hitting F5 and inspect what is happening during the build. Then check out a specific commit and debug again. Then make some changes and debug again, etc.

**Comment by remorses** [comment]
`ESBUILD_BIN_PATH_FOR_TESTS ` must be set during installation, i would like to change the used binary path at runtime, can i open a PR?
