### ISSUE TITLE
transformSync output regression in 0.8.22

### ISSUE THREAD

**Issue by eigilsagafos** [evanw/esbuild#596]
After the 0.8.22 release `transformSync` returns a stringified Uint8Array

**Comment by evanw** [comment]
I believe you but I am unable to reproduce this. It returns a string for me. [This test](https://github.com/evanw/esbuild/blob/d025ebd6688504495788ea2aa55a35b7e4f163fb/scripts/js-api-tests.js#L2127-L2130) is currently passing, for example.

Can you provide me with more information? Do you have a code sample that reproduces the problem? What platform is this on?

**Comment by eigilsagafos** [comment]
@evanw So, I did some more digging. So seems to me that passing a buffer to transformSync is the issue. This has worked before.

Does not work in 0.8.22
```
const code = readFileSync(filename)
const result = transformSync(code, {
    loader: "ts"
})
```

Works in 0.8.22
```
const code = readFileSync(filename)
const result = transformSync(code.toString(), {
    loader: "ts"
})
```

**Comment by evanw** [comment]
Ah, I see. That wasn't intentionally supported. This is the type definition for `transformSync`:

https://github.com/evanw/esbuild/blob/9db53e7b642d596fa6745f632850f146cb875e6c/lib/types.ts#L287

I can make sure this isn't silently allowed like it is now.

**Comment by eigilsagafos** [comment]
I see :) Thanks for pointing that out!
