### ISSUE TITLE
[CSS] Ignore css import

### ISSUE THREAD

**Issue by hiepsieunhan** [evanw/esbuild#599]
I am working on the project that use the library which having css import from javascript file. However, I don't want to load the css (to reduce the bundle time), as the css file is already extracted + minified using webpack.

Is it possible to ignore all the css import from javascript?

**Comment by jasbir91709** [comment]
you can use light weight web servers for faster loading
![light](https://user-images.githubusercontent.com/63893657/102175421-8d000400-3ec5-11eb-8a32-9b0b4cec1d5c.PNG)
![heavy](https://user-images.githubusercontent.com/63893657/102175423-8e313100-3ec5-11eb-886f-0231fc1dd24d.PNG)

Maintaining small, modular stylesheets can make development easier, and make it possible to deliver styles specifically to the pages that require them, reducing the total CSS served per page. But we are seeing now that there’s a price to pay in the HTTP overhead.

**Comment by evanw** [comment]
> Is it possible to ignore all the css import from javascript?

If you would like to exclude all CSS files from the bundle you could just do `--external:*.css`. That will turn these imports into `require()` calls or `import` statements though, which I'm guessing isn't what you want.

If you would like for importing `.css` files to behave as if they were an empty JavaScript file, you could do that with a plugin like this:

```js
let plugin = {
  name: 'empty-css-imports',
  setup(build) {
    build.onLoad({ filter: /\.css$/ }, () => ({ contents: '' }))
  },
}
```

That would basically erase all statements of the form `import './file.css'` when bundling. It's possible that might need some tweaks depending on the specifics of your situation.

**Comment by hiepsieunhan** [comment]
> If you would like for importing `.css` files to behave as if they were an empty JavaScript file, you could do that with a plugin like this:
> 
> ```js
> let plugin = {
>   name: 'empty-css-imports',
>   setup(build) {
>     build.onLoad({ filter: /\.css$/ }, () => ({ contents: '' }))
>   },
> }
> ```
> 
> That would basically erase all statements of the form `import './file.css'` when bundling. It's possible that might need some tweaks depending on the specifics of your situation.

Thanks for your reply @evanw , that is exactly what I am looking for.

**Comment by evanw** [comment]
Cool! I'm going to close this then since the question was answered.

**Comment by goulvench** [comment]
I was having the same issue, and passing ` --loader:.css=file` to the esbuild command in my `package.json` silently drops the css import.

I stumbled upon this problem after adding a library which contains an `import('main.css');` buried deep down somewhere. Since the `css` bundler is enabled by default, esbuild was overwriting my sass-generated files with only the contents of that js-imported file.

Anyway, problem solved, and esbuild is a LOT simpler to setup than webpack, and way faster too, so _bravo_ for that!

**Comment by rauschma** [comment]
What would the opposite functionality look like? That is, I’d like to:

* Only extract and bundle `.css` files that are imported from JavaScript.
* Not create a JavaScript bundle.

**Comment by evanw** [comment]
You can easily just discard the JavaScript bundle and not use it. The API has a `write: false` option that returns the generated files as objects without writing them as files.
