### ISSUE TITLE
Reproducible performance/correctness benchmark

### ISSUE THREAD

**Issue by evmar** [evanw/esbuild#6]
Hey, this project looks awesome!  I actually was tinkering in this same space with similar motivations and wrote my own lexer/parser/minifier.  I was more focused on minification than bundling (I only worked with single-file inputs) but it's still a lot of the same problems -- I even used "a popular library concatted with itself 10x" as my initial test just like you did!

What I discovered in my attempt is that it ends up being hard to
1. measure my thing's performance against others, because everybody always has idiosyncratic build processes with different flags etc
2. measure my things's correctness against others, because it's easy to do a very aggressive minifier that just generates invalid output

Because of those problems, I set my project aside and instead spent some time trying to come up with an approach to that problem.  I built a sort of mini-framework that lets you plug in multiple JS minifiers side by side and measure their performance across some apps.  And to deal with #2 it also tries to run end-to-end tests with the minifier's output as well (which is something I realized is necessary).

You can find it here:
https://github.com/evmar/js-min-bench
with some output here:
https://evmar.github.io/js-min-bench/

I think you might be able to drop your program in there into this list of tools:
https://github.com/evmar/js-min-bench/blob/master/src/metadata.ts#L103
and then either run the command in the readme (which runs everything) or run with some flags to just run the tools you care about:
https://github.com/evmar/js-min-bench/blob/master/src/run.ts#L98-L110

As the sort of value it brings, for example I patched out the minification from React (and [other libraries'](https://github.com/evmar/js-min-bench/blob/master/src/metadata.ts#L49)) build process to let you plug in yours:
https://github.com/evmar/js-min-bench/tree/master/third_party/react

Even if you don't find it useful, I'd love to get your thoughts on why not, or what would have been more useful.  I ended up a little bummed that I started with the fun thing (the fast lexer) and ended up mired in measurement and build processes, but I guess that is how this kind of project goes...

**Comment by evanw** [comment]
Cool! Thanks for posting about this. It looks really well-considered.

I took a brief stab at hooking up esbuild and it worked fine on the first try (including passing the todomvc tests). Here's how to invoke it:

```js
{
  id: 'esbuild',
  name: "esbuild",
  variants: [
    {
      command: 'esbuild %%in%% --minify-whitespace --outfile=%%out%%'
    },
    {
      id: 'minify',
      command: 'esbuild %%in%% --minify --outfile=%%out%%'
    }
  ]
},

```

Running the benchmark on my machine looks like this:

<img width="793" src="https://user-images.githubusercontent.com/406394/74600139-d1223e00-5041-11ea-880f-5e73d9e39f7a.png">

It's not surprising that the size of esbuild's minified output isn't completely as small as other minifiers that have been carefully tuned for years. I only did enough minification in esbuild to bring it within the same ballpark of other minifiers. Only the most significant minification transformations are implemented, and I haven't yet optimized specifically for small size under compression.

It's also not surprising that esbuild is the fastest, especially given the overhead of JIT warmup in node. Much of esbuild's performance comes from parsing multiple files in parallel, but esbuild also has fast single-threaded performance.

Some thoughts about performance/correctness tests:

* I've noticed that running a minifier is much slower the first time. I assume this has to do with the OS loading the files from disk into some cache. When benchmarking minifiers, make sure to run the multiple times and discard the first result, or the first minifier will be unfairly penalized.

* Even if a code base doesn't have tests, I've gotten some mileage out of just executing the code and making sure it doesn't crash on startup. Presumably this type of test only works for library code and not application code.

* JavaScript has a great test suite called [test262](https://github.com/tc39/test262). It's not specifically intended for minifiers but it has a ton of coverage for various strange language feature combinations and has helped me find a ton of bugs. For example, you can minify each valid syntax test case and re-parse it with another parser to check that it's valid syntax. You could also do a whitespace-only minification and then verify that the syntax tree is the same using another parser. If you're ambitious enough you could even try running the tests although you'll need to figure out a test harness.

I do think this project would be useful for me. The more tests the better! And it's great to have a nice visualization like this. I've been manually entering numbers into a Google spreadsheet.

**Comment by evanw** [comment]
I'm going to close this since it's a conversation and not an issue with esbuild. Please feel free to continue to discuss this here though!
