### ISSUE TITLE
esbuild potentially overrides default properties on window

### ISSUE THREAD

**Issue by lennyanders** [evanw/esbuild#603]
So I use esbuild to bundle my project which uses Vue 3 with a custom Plugin. Somewhere in Vue is a file with a default export named `addEventListener`. When I bundle my project to `esm` without minification the `addEventListener` from Vue gets defined globally via `var` and therefore replaces the default `addEventListener` function which breaks my code during development.

Previous versions of esbuild do not seem to have this issue because they did not transform `const` to `var` and Vue exports its own function via `const`.

Here Is a minimum example to replicate the problem:
```javascript
// main.js
import shared from './shared';

console.log(shared);

window.addEventListener('click', () => {
  console.log('clicked');
});
```

```javascript
// shared.js
export const addEventListener = () => {
  console.log(1);
};

export default () => {
  addEventListener();
};
```

When I bundle with this: `esbuild main.js --bundle --format=esm --outfile=dist/main.js` command, I get the following "broken" output file:

```javascript
// dist/main.js
// shared.js
var addEventListener = () => {
  console.log(1);
};
var shared_default = () => {
  addEventListener();
};

// main.js
console.log(shared_default);
window.addEventListener("click", () => {
  console.log("clicked");
});
```

**Comment by evanw** [comment]
If you use `--format=esm` then the output is in ESM format and must be loaded as such. In the browser this can be done with `<script type="module">` for example. Every ES module gets its own scope so `var addEventListener` will be local to the module instead of global. If you want to use the output without `type="module"` then you need to use `--format=iife` instead. That wraps the output in an immediately-invoked function expression which introduces a new scope.

**Comment by lennyanders** [comment]
I tested IIFE before and saw that it did work, I thought that the esm behavior is wrong, but you're clearly right. Thanks for clarifying!
Since I use the code in a content script of a chromium extension, I guess I need to use the IIFE format.

Sorry for this false bug and thanks for your response and this fantastic tool!

**Comment by terwer** [comment]
Thanks you very much.It works now.
