### ISSUE TITLE
Ramda bundling issue as of 0.8.19

### ISSUE THREAD

**Issue by rscharer** [evanw/esbuild#605]
I have an extremely basic use case of bundling a TS node project that makes use of Ramda's groupBy function to shape data coming back from Postgres:

```js
import * as R from 'ramda';
...
const rowsBySubType = R.groupBy((row) => row.subscriptionType, rxCategoryMedResult.rows);
```

When I bundle the file using esbuild 0.8.18, it correctly generates a module reference in the resulting js file:

```js
// node_modules/ramda/src/groupBy.js
var require_groupBy = __commonJS((exports2, module2) => ...etc
```

However when I bundle it using esbuild 0.8.19 or above, the require_groupBy section is missing entirely, leading to a reference error when groupBy is invoked. I honestly think it's odd that this hasn't been reported before given how common Ramda is, and maybe there's something weird in my setup that I'm not seeing, but I'm going to have to pin 0.8.18 until this is either addressed or somebody can explain what I'm doing wrong. Thanks!

**Comment by evanw** [comment]
I'm unable to reproduce the issue. Here's what I tried:

```js
// rambda-demo.mjs
import * as R from 'ramda';

const rows = [
  { subscriptionType: 'a', value: 1 },
  { subscriptionType: 'a', value: 2 },
  { subscriptionType: 'b', value: 3 },
  { subscriptionType: 'b', value: 4 },
];

const rowsBySubType = R.groupBy((row) => row.subscriptionType, rows);
console.log(rowsBySubType);
```

Both `node rambda-demo.mjs` and `esbuild --bundle rambda-demo.mjs | node` produce the same output and neither crashes. This is with esbuild version 0.8.23 (the latest version).

Since I can't reproduce it, it might be something more specific to your setup. Do you have a way for me to reproduce the issue? For example, are you able to share a code sample containing the issue?

**Comment by rscharer** [comment]
Oh, interesting. Thank you for taking the time to try to reproduce it. I'll
come up with the smallest reproducible test case I can find in the next day
or two and update the issue.
-R

**Comment by rscharer** [comment]
OK I can trivially reproduce this using your file if I include the --bundle
flag in the build command. Once you untar the attachment:
cd ramda-test
yarn install
npx esbuild src/ramda-test.ts --bundle --platform=node --outdir=dist

The resulting .js file will not actually include any code related to
groupBy.

Again I may be misunderstanding the intent of the --bundle flag, so tell me
if this not what I should actually be doing!

**Comment by rscharer** [comment]
Attaching test file:

[ramda-test.zip](https://github.com/evanw/esbuild/files/5710132/ramda-test.zip)

**Comment by rscharer** [comment]
Sorry, I just re-read your comment and realize you yourself are using --bundle — in my case it's the addition of --platform=node that's causing it to fail.

**Comment by evanw** [comment]
Thanks! I can reproduce the issue now. I’ll fix it in the next release.
