### ISSUE TITLE
`keepNames` and `execute` in WebdriverIO

### ISSUE THREAD

**Issue by flunderpero** [evanw/esbuild#607]
WebdriverIO lets you write regular functions that will then be executed in the browser's context. In the end the source of that function will simply be transferred to the browser and then fed to `eval()`.

This leads to problems, when I compile my test-code with `keepNames` and such functions define functions themselves, like this:
```
browser.execute(() => {
    function f() {
        return "test"
    }
    return f()
})
```

This will be transpiled to:
```
...
var __name = (target, value) => __defProp(target, "name", {value, configurable: true});
...
  browser.execute(() => {
    function f() {
      return "test";
    }
    // This is where it breaks ...
    __name(f, "f");
    return f();
  });
```

`__name` is not defined in the browser's context.

Is there any way to get around that?

**Comment by flunderpero** [comment]
I found a workaround for now. I simply assign all functions to a local object like this:
```
browser.execute(() => {
  const w = {}
  w.f = () => {
    return "test"
  }
  return w.f()
})
```

**Comment by evanw** [comment]
This approach is likely going to be brittle for other reasons too. The `__name` function is just one of many code transforms that esbuild can make that assume functions aren't arbitrarily recompiled by converting them to a string and feeding them to `eval`. Other examples include converting `a ** b` to `__pow(a, b)` and `{...a, ...b}` to `__assign({}, a), b)`.

Preserving the value of `toString()` on a function expression is not a design goal of esbuild. If that use case is important to you, it would be best to either arrange for the code to be passed as a string instead, or to use another tool that supports preserving the value of `toString()` on a function.

**Comment by flunderpero** [comment]
@evanw I fully understand and appreciate that you try to keep the right focus. For now I just see `__name` to be a problem, because it is unexpected at this point. The other examples do not apply if you choose a modern target (ES2017 in our case). But there might be others. With the workaround above and the fact, that we do not use nested functions that often in this context, I am fine for now.

I don't expect you to change anything to accommodate this use case, but perhaps the way `keepNames` is implemented could be improved. In our case, we do not use minification at all, so I would not expect that `__name` / `keepNames` would be necessary at all. But it is, otherwise our code does not run (here I don't mean the WebdriverIO-code but our business logic). The reason why is, that classes get renamed to `<class name>2` and that messes up our "reflection" code that uses the the classname (`class.constructor.name`).

**Comment by evanw** [comment]
I'm going to close this. This is not a supported use case. The way to do this robustly is to arrange for this code to be a string in the bundle.

**Comment by flunderpero** [comment]
I'm fine with the WebdriverIO use case. But now I stumbled upon the same error `__name is not defined` using the popular [canvas-confetti](https://github.com/catdad/canvas-confetti/blob/master/src/confetti.js) library. They try to dynamically create a worker from a blob and that fails, because the generated code looks like this:
```
var CONFETTI, SIZE = {}, module = {};
(function main(global2, module2, isWorker, workerSize) {
  var canUseWorker = !!(global2.Worker && global2.Blob && global2.Promise && global2.OffscreenCanvas && global2.OffscreenCanvasRenderingContext2D && global2.HTMLCanvasElement && global2.HTMLCanvasElement.prototype.transferControlToOffscreen && global2.URL && global2.URL.createObjectURL);
  function noop3() {
  }
  __name(noop3, "noop");
  function promise(func) {
    var ModulePromise = module2.exports.Promise;
    var Prom = ModulePromise !== void 0 ? ModulePromise : global2.Promise;
    if (typeof Prom === "function") {
      return new Prom(func);
    }
    func(noop3, noop3);
    return null;
  }
  __name(promise, "promise");

...
```

Do you have a workaround for that?
