### ISSUE TITLE
Loader strategy?

### ISSUE THREAD

**Issue by zaydek** [evanw/esbuild#609]
Thanks Evan, I really appreciate your work. Has been a while since I felt optimistic about web development. 😄

I was wondering for something like markdown files, where you want to parse files on import, if there’s any strategy or advice / plugin methodology for handling something like this?

I’m aware I can add `loader: { ".md": "text" }`, to the loader — is there a way to take this one step further and add a callback, like: `loader: { ".md": data => ... }` so I can process data when it loads?

I’m not sure this is actually a good idea, because this doesn’t necessarily solve for the .mdx case where you want to be able to tie in your own components. So I’m simply curious as to what you (or the community) has thought of.

Thanks!

**Comment by evanw** [comment]
Have you seen https://esbuild.github.io/plugins/#load-callbacks?

**Comment by zaydek** [comment]
Not yet — thank you! Will follow-up if need be.
