### ISSUE TITLE
[Thread] Logo

### ISSUE THREAD

**Issue by RayPS** [evanw/esbuild#61]
This project deserves a nice looking logo, so I am starting a thread to discuss it.
Let's contribute ideas on the comments, I'll be the first one.

**Comment by RayPS** [comment]
![Artboard](https://user-images.githubusercontent.com/1941540/79316346-c6e3c980-7f36-11ea-808c-a7c1b3732e42.png)

So starting from mine. My idea is pretty simple. There is a box symbolize 'bundle' like other bundlers do. The lightning bolt symbolize speedy. Turns out I was luckily getting an abstract 'E' and 'S' letter with it. The font I was randomly chosen 'Ubuntu Bold'. I am not sure how should I capitalize the name, but I am feeling satisfying with title-casing it.
Here we go!

**Comment by gocs** [comment]
ESBuild should be the way to go or else golint will warning :)

```
module name Esbuild should be ESBuild
```

https://github.com/golang/lint/issues/124

**Comment by kazzkiq** [comment]
@RayPS that's beautiful! Care to show us how would it look like in monochromatic version?

**Comment by amursky** [comment]
@gocs, I think ESBuild actually feels more intuitive similar to ESLint.
ESBuild sounds like a name of a new standard building tool for JS/TS ;)

@RayPS, could you try capital ESB? :)

**Comment by pi0** [comment]
Awesome @RayPS 👍 @evanw Is it okay to temporary use this logo for [modules.nuxtjs.org](https://modules.nuxtjs.org/) ?

**Comment by henriquehbr** [comment]
Great work @RayPS! am i allowed to use it on a subreddit avatar?

**Comment by RayPS** [comment]
The zip file includes: design source file, a transparent PNG, an editable SVG. Feel free to use it for any purpose.
[Archive.zip](https://github.com/evanw/esbuild/files/5821060/Archive.zip)
There is so much to learn, I design free logos/icons/webpages for open-source / non-profit projects.
If you are interested, hit me up.

**Comment by henriquehbr** [comment]
Many thanks for the assets, they're looking great, really useful for a provisional community icon

**Comment by osdevisnot** [comment]
hi @evanw I am wondering if community should explore more options for logo or if you have any specific design in mind. I am working on adding test cases for esbuild to [tooling.report](https://bundlers.tooling.report/) and I would love to use a logo that represents authors opinions/thoughts.

**Comment by evanw** [comment]
Thanks for reaching out. I haven't already gone with the logo earlier in this thread because it looks too much like a riff on Webpack to me. I guess maybe this means it's time for me to come up with a logo.

**Comment by evanw** [comment]
I'm currently thinking about going with this logo:

<img width="640" src="https://user-images.githubusercontent.com/406394/107381299-8ea00f80-6aa3-11eb-9389-aeec56e63df4.png">

Inspiration: fast forward (speed), right shift (shrink)

**Comment by henriquehbr** [comment]
This one express a pretty unique identity in contrast to other bundlers logos, i like it

**Comment by henriquehbr** [comment]
@evanw Sorry to reopen this, if not asking too much, can you provide a `.png` version please? containing only the logo, without background, i'm willing to replace the old [subreddit](https://reddit.com/r/esbuild) logo with this one

**Comment by evanw** [comment]
Sure: https://github.com/evanw/esbuild/blob/a846a60af6bf679e158e486b9da82dcf270fc613/images/logo.png

**Comment by henriquehbr** [comment]
Many thanks! 😄

**Comment by jacobp100** [comment]
@evanw Would you be willing to release the source files too?

**Comment by evanw** [comment]
The source is already checked in:

https://github.com/evanw/esbuild/blob/ac542f913908d7326b65eb2e01f0559ed135a40e/images/logo.svg#L1-L4
