### ISSUE TITLE
Wrongly source duplication in source map

### ISSUE THREAD

**Issue by lahmatiy** [evanw/esbuild#611]
The minimal code I found to reproduce the problem:
```js
// a.js
import * as t from './b';
export default t;

// b.js
export const x = 1;
```

Build config:
```js
require('esbuild').build({
    entryPoints: ['a.js'],
    bundle: true,
    sourcemap: true,
    outdir: 'out'
});
```

`esbuild` produces a source map:
```json
{
  "version": 3,
  "sources": ["../b.js", "../b.js", "../a.js"],
  "sourcesContent": ["export const x = 1;\n", "export const x = 1;\n", "import * as t from './b';\nexport default t;\n"],
  "mappings": ";;;;;;;;;;AAAA,MAAA;AAAA;AAAA;AAAA;ACAO,MAAM,IAAI;;;ACCjB,MAAO,YAAQ;",
  "names": []
}
```
The problem is that the source map contains source of `b.js` twice but should not.

**Comment by evanw** [comment]
Thanks for reporting this issue. I suspect this is a regression from [version 0.7.9](https://github.com/evanw/esbuild/blob/6589c0bca337123970a61c11412c04c7b314cc56/CHANGELOG.md#079) which allows a file to be split into discontiguous pieces (issue #421).
