### ISSUE TITLE
Is it possible to retain folder structure in outputdir?

### ISSUE THREAD

**Issue by oze4** [evanw/esbuild#618]
Per the title...I am trying to retain the same structure in my output (so I suppose I just want to transpile/minify but **not** bundle into a single file), is this possible?

**Comment by oze4** [comment]
Sorry to bother, I figured it out.

This was for a react project - I had to change `esbuild ./src` to `esbuild ./src/**/*`.

Full Command: `esbuild ./src/**/* --outdir=./dist --loader:.js=jsx`

**Comment by devklick** [comment]
Is this still valid? I get an error when I try this. 

Example structure:
```
src/
  lib/
    some-file.ts
  index.ts
```

Command:
```
esbuild ./src/** --outdir=./dist
```

Error:
>Could not resolve "./src/lib"

Using esbuild v0.17.18

**Comment by evanw** [comment]
I'm assuming your shell is expanding `./src/**` into `./src/lib` here. If that's the case, then that's a problem with your shell, not with esbuild. Shell expansion happens before esbuild runs so esbuild doesn't even see `./src/**` at all. You'll need to read your shell's documentation to figure out how to do glob expansion correctly. Either that or you can pass all of the files to esbuild manually.

**Comment by devklick** [comment]
Thanks @evanw, I realised it must be something like that after seeing an error:
>It looks like you are trying to use glob syntax (i.e. "*") with esbuild. This syntax is typically
  handled by your shell, and isn't handled by esbuild itself. You must expand glob syntax first
  before passing your paths to esbuild.

It appears to work if I specify file types, e.g.
```
esbuild ./src/**/*.ts --outdir=./dist
```

**Comment by rlindgren** [comment]
nice. but can we exclude some files by glob pattern that match the entry glob?

**Comment by funwithtriangles** [comment]
In case anyone is still having trouble: `outbase`was the setting I needed in order to prevent esbuild from collapsing the folder structure when I only had one folder in my input directory.

https://esbuild.github.io/api/#outbase

```ts
 const entryBase = 'my/base/path/'
 const ctx = await esbuild.context({
      entryPoints: [
        `${entryBase}/**/index.js`,
        `${entryBase}/**/config.js`,
        `${entryBase}/**/index.ts`,
        `${entryBase}/**/config.ts`,
      ],
      outbase: entryBase, // fixed the issue!
      ...
})
```
