### ISSUE TITLE
Add --nosources option for source maps

### ISSUE THREAD

**Issue by atombrenner** [evanw/esbuild#624]
## Context

I am using esbuild to bundle and minify Typescript functions for AWS lambda.

`esbuild --bundle --minify --keep-names --sourcemap --platform=node --target=node12`

To get meaningful stack traces for exceptions in production, I use the `--sourcemap` and `--keep-names` options.
I use `NODE_OPTIONS=--enable-source-maps` to get a stack trace that uses the source map.
One problem is, that I have to use the `--keep-names` option to see the original function names in the stack trace.
I guess that it could be related to the missing `names` field in the generated source map, but I'm not an expert on this topic.

## Issue

The `--sourcemap` option adds the original source to the `sourcesContent`field of the source map. This is not necessary for meaningful stack traces, it can be an empty array `"sourcesContent": []`.

Adding the complete source to the source map thwarts the goal of making the AWS Lamda artifact small
as it doubles the size of the zip package (index.js + index.js.map) I need to upload to AWS Lambda.

I would like an esbuild option `--nosources` that prevent sources from being included in the source map.
Something similiar to the [webpack devtool option `nosources-source-map`](https://webpack.js.org/configuration/devtool/#production)

My current workaround is to post process the generated source map from esbuild and remove the sourcesContent.

**Comment by evanw** [comment]
Thanks for the detail. Doing this makes sense. Injecting the original source code is by far the heaviest part of the source map, and is only useful in some scenarios.

I think `nosources` is not the right name because source maps have both a `sources` field and a `sourcesContent` field and the intent of the flag is to keep `sources` but discard `sourcesContent`. So I'll use a different name instead.

**Comment by evanw** [comment]
This has been fixed. Closing.

**Comment by p0wl** [comment]
wow, awesome, I just ran into exactly this (aws lambda with esbuild via [aws-lambda-nodejs](https://docs.aws.amazon.com/cdk/api/latest/docs/aws-lambda-nodejs-readme.html)), and so happy to found that you added an option for it. Thanks for your work!
