### ISSUE TITLE
How to make variables must be defined?

### ISSUE THREAD

**Issue by fy0** [evanw/esbuild#625]
Example:
```
echo "a+b; a()" | npx esbuild
```

tsc:
```
echo "a+b" > a.ts
tsc ./a.ts

a.ts(1,1): error TS2304: Cannot find name 'a'.
a.ts(1,3): error TS2304: Cannot find name 'b'.
```

**Comment by brandly** [comment]
in [the docs](https://esbuild.github.io/content-types/#typescript), it says

> However, esbuild _does not_ do any type checking so you will still need to run `tsc -noEmit` in parallel with esbuild to check types.

so, like you've done, you can use `tsc` to type check, including checking if variables are defined

**Comment by evanw** [comment]
The above post is correct. That's a task for a type checker, and esbuild is not a type checker. Closing.
