### ISSUE TITLE
target: node>12 supports import.meta.url but esbuild says is not available in the configured environment.

### ISSUE THREAD

**Issue by SalvatorePreviti** [evanw/esbuild#626]
NodeJS > 12 supports natively import.meta.url but setting it as a target generates an empty meta.url.

Warning is `"import.meta" is not available in the configured target environment and will be empty`

Forcefully setting the target to "es2020" causes instead other 2020 syntax to fail in node 12, 13, 14 like, for example, null coalescing operators.

Solution: esbuild with target node>12 should use the native import.meta.url

**Comment by evanw** [comment]
Thanks for the report. I think this is just due to a typo in esbuild's compatibility table:

https://github.com/evanw/esbuild/blob/150a01844d47127c007c2b1973158d69c560ca21/scripts/compat-table.js#L154

This should be `true`, not `false`. Will fix.
