### ISSUE TITLE
error in running make command

### ISSUE THREAD

**Issue by izayl** [evanw/esbuild#63]
example below

```
$ make bench-three                            
GOPATH=`pwd` go build -o esbuild esbuild/main
can't load package: package esbuild/main: malformed module path "esbuild/main": missing dot in first path element
make: *** [esbuild] Error 1
```

**Comment by tooolbox** [comment]
You probably have `GO111MODULE=on` in your environment.  Check it with `go env` and change it to `auto` or `off`.

**Comment by izayl** [comment]
> You probably have `GO111MODULE=on` in your environment. Check it with `go env` and change it to `auto` or `off`.

Thanks.

**Comment by evanw** [comment]
I could have fixed this by manually setting `GO111MODULE=off` in my build commands, but I thought I'd try fixing this by switching over to using Go modules. Building with `GO111MODULE=on` now seems to work for me. Please let me know if there are any other build issues as I'm not too familiar with Go modules.
