### ISSUE TITLE
Invalid define value

### ISSUE THREAD

**Issue by henriquehbr** [evanw/esbuild#630]
I'm trying to apply a temporary patch suggested in https://github.com/sveltejs/svelte/issues/3165#issuecomment-699985503 for a bug in svelte compilation output, the example uses rollup, i'm trying to reproduce the same behavior using esbuid `define`:

```js
await esbuild.build({
	entryPoints: ['./src/index.js'],
	bundle: true,
	platform: 'browser',
	define: {
		'outros.c.push': 'if (outros === undefined) { block.o(local); return }\noutros.c.push'
	},
	format: 'esm',
	splitting: true,
	outdir: 'public/build',
	plugins: [sveltePlugin()]
})
```

But, the following error is returned:

> `error: Invalid define value: "if (outros === undefined) { block.o(local); return }\noutros.c.push"`

Any clue of what could be happening?

**Comment by evanw** [comment]
This feature only takes JSON syntax. The docs are here: https://esbuild.github.io/api/#define.

**Comment by henriquehbr** [comment]
But, isn't the config above valid JSON syntax? or am i missing something?

**Comment by evanw** [comment]
That is an if statement and a return statement, not a JSON-compatable expression. Valid JSON syntax is limited to a null, boolean, number, string, array, or object literal expression.

The code in the define string must either be an identifier expression or must be parsable by `JSON.parse`.

**Comment by henriquehbr** [comment]
Indeed, sorry for the misunderstanding, do you think `define` is a good way to replace texts in the generated bundle? or there is another functionality more suitable for this task?

I'm thinking about writing a plugin to replace all the occurrences of the specified text in each of the imported chunks, but i'm not sure if it's actually a good idea

**Comment by evanw** [comment]
The `define` feature is not intended for this purpose. It looks to me like the right place to do this would be in the Svelte plugin itself, after the Svelte compiler runs but before the source code is returned to esbuild. Have you considered that solution? I'm imagining something like this (the code was copied from [this plugin](https://github.com/EMH333/esbuild-svelte/blob/daccc90c9ceda4610abd5281e8a27db3e5464641/index.ts#L46-L47)):

```diff
 let { js, css, warnings } = compile(source, { ...compileOptions, filename })
+js = js.replaceAll('outros.c.push', 'if (outros === undefined) { block.o(local); return }\noutros.c.push')
```

**Comment by henriquehbr** [comment]
Many thanks @evanw! this is a pretty solid solution and managed to solve my problem flawlessly, but i've choosen to do a simple file content replacement in the same node.js script i used to build the project, right after esbuild finishes it's job, making use exclusively of built-in modules, without the need of any third-party dependencies

Here's a gist of code as it might help someone in the future: https://gist.github.com/henriquehbr/093d6992b8259ebeed256719a1525c8a

**Comment by onzag** [comment]
I am having an issue here where I want bundled code to work with both worker context and user context, because I have two files with code in common, but it crashes because I cannot conditionally define the value for the global so that it works in both contexts, as some code tries to use the window object, I tried defining global as `global: '(typeof window !== "undefined" ? window : {})',` but this is not allowed, I will be forced to manually replace the content of the file with a content replace, which is dangerous, but I guess a UUID should do to ensure no collisions, but this could be easily resolved if it could just be an arbitrary string.

**Comment by onzag** [comment]
```const commonsJS = path.resolve(path.join('dist', 'data', 'commons.' + mode + '.js'));
    const commonsFile = fs.readFileSync(commonsJS, "utf-8");
    const fixedCommons = commonsFile
      .replace(/\$8a5c6e45304947ab980e35f38bfbb085/g, '(typeof window !== "undefined" ? window : {})');
    fs.writeFileSync(commonsJS, fixedCommons);
```

Not pretty but gets the job done, now I can have a commons file in the web and worker context.

**Comment by evanw** [comment]
I believe you are looking for the `inject` feature, not the `define` feature: https://esbuild.github.io/api/#inject
