### ISSUE TITLE
Question: Document Existing External Plugins?

### ISSUE THREAD

**Issue by louisscruz** [evanw/esbuild#632]
In getting started with ESBuild, I've found the need to lookup and write some plugins to get going. I had to do a bit of digging to see if what I was looking for existed at all (and I'm still not sure if it already existed somewhere out there).

Would you be open to adding a section to the plugins documentation with an index of known external plugins?

Possible upsides:

* should help people get started faster with common use cases
* might help prevent duplicate efforts to accomplish the same thing

Possible downsides:

* there might be some upkeep in maintaining these?
* quality control?
* maybe it's too early to do this right now if any API changes are anticipated?

If this happens to be something you'd consider adding to the documentation, I can carve out some time to try adding it.

**Comment by evanw** [comment]
Good idea. I think putting these in a GitHub repo will be easier to maintain for me over including them in the documentation itself. I put together a quick repo for this here (currently empty): https://github.com/esbuild/community-plugins. I'll link to it from the documentation once the repo gets going.

> there might be some upkeep in maintaining these? quality control?

I put a disclaimer in the readme to hopefully solve for the maintenance and quality control concerns.

> maybe it's too early to do this right now if any API changes are anticipated?

I'm not anticipating any major breaking plugin API changes at the moment, but the plugin API is still very young and has a lot of gaps so I'm reserving the right to potentially change it in a backwards-incompatible way in the future if necessary. There are likely to be at least minor breaking changes before esbuild hits 1.0.0 which may break backwards compatibility in certain edge cases without changing the overall API.

However, I still think it's useful to get this list going now. It's easy enough to move existing plugins to a "Works with version 0.8.x" section if there end up being breaking changes, and it will be helpful for me to have a list of existing plugins when thinking about potentially breaking changes in the future.

**Comment by evanw** [comment]
The list of existing plugins has been added to the documentation here: https://esbuild.github.io/plugins/#finding-plugins.
