### ISSUE TITLE
[Feature][Easy] --import-function="include"

### ISSUE THREAD

**Issue by dtruffaut** [evanw/esbuild#635]
# Context

In the context of code splitting
When developer is using a custom/generic importMap, it cannot statically use `import('./myfile.mjs')`.
Developer has to use a dedicated function, like `include('myfile')`, to infer path and hash :

```js
// index.html
// Current W3C importMap specification is limited to .mjs
// This custom/generic importMap infer hash for any file type, which is way better
globalThis.importMap = {
  "app.mjs":"42e13cac",
  "manifest.json":"b4eac61c",
  "sitemap.xml":"913485b5",
  "button.css":"81eded5e",
  "image.webp":"a831c2cc",
  "tensorflow.min.js":"6bd4cf05",
  "contacts.html":"9819814f"
});
globalThis.iMap = async (k) => `./${importMap[k]}-${k}`;
globalThis.include = async (k) => import(`${await iMap(`${k}.mjs`)}`);
await include('app')).start(); 
// Loads app.mjs-42e13cac.mjs
// In all subfiles, client cache is never broken because include('toto') stays include('toto')
// The only file that breaks client cache on subsequent builds is index.html. Great for users !
```

To make this code work, we have, for each build, in all files to replace the word 'import' by '_import', then replace the word 'include' by 'import' to make it work with esbuild, then replace the word 'import' by 'include' then replace the word '_import' by 'include'. This makes SSD suffer for nothing. We could just pass an option to esbuild to indicate what is the import function.

# Proposal

Provide a `--import-function` option to indicate the import fonction.

Something like :
```js
--bundle --splitting --import-function="include"
```

**Comment by evanw** [comment]
It's not clear to me if you're trying to resolve the import map at run-time or at compile-time. Regardless, the intended way to alter path resolution in esbuild during bundling is by writing an on-resolve plugin. The documentation for doing this is here: https://esbuild.github.io/plugins/#resolve-callbacks.

For the sake of example, assume there's some function called `pathForImport()` that does whatever path mapping you need. If you wanted to resolve the path mapping at compile-time, you could do something like this:

```js
let yourPlugin = {
  name: 'your-plugin',
  setup(build) {
    build.onResolve({ filter: /.*/ }, args => {
      return { path: pathForImport(args.path) }
    })
  },
}
```

If you wanted to resolve the path mapping at run-time, the exact details of that are probably more specific to your situation but you could try something like this:

```js
let yourPlugin = {
  name: 'your-plugin',
  setup(build) {
    build.onResolve({ filter: /.*/, namespace: 'your-plugin-shim' }, args => {
      // The import paths inside each "your-plugin-shim" file are external
      // (external means "resolved at run-time")
      return { path: args.path, external: true }
    })

    build.onResolve({ filter: /.*/ }, args => {
      // Map import paths into the "your-plugin-shim" namespace to reserve them
      return { path: args.path, namespace: 'your-plugin-shim' }
    })

    build.onLoad({ filter: /.*/, namespace: 'your-plugin-shim' }, args => {
      // Evaluate the path mapping at run-time instead of compile-time
      // (assuming you are importing the file using an "import()")
      return { contents: `exports.then = callback =>
        import(pathForImport(${JSON.stringify(args.path)})).then(callback)` }
    })
  },
},
```

You are also free to do whatever JavaScript code transforms you like on each input file before esbuild sees the code. That should let you do custom things such as replacing `import()` expressions with something else. This can be done with an on-load plugin: https://esbuild.github.io/plugins/#load-callbacks.

**Comment by dtruffaut** [comment]
Thks I'll try this.
