### ISSUE TITLE
Summary of the size of imported modules, like webpack-bundle-analyzer

### ISSUE THREAD

**Issue by joaopaulobdac** [evanw/esbuild#637]
[v0.8.28 just released the `--summary` flag which shows the size of the build](https://github.com/evanw/esbuild/releases/tag/v0.8.28). Could this flag show the size of imported modules similarly to what [webpack-bundle-analyzer](https://www.npmjs.com/package/webpack-bundle-analyzer) does, but simply in the terminal?

**Comment by evanw** [comment]
There are often hundreds of imported modules so this information isn't that straightforward to show in the terminal. You would necessarily have to omit information to make it fit, and I imagine people will end up wanting to show different things. It's not immediately clear to me what should be shown. All of the things I can think of wouldn't provide enough information to be useful to me.

This is the intent of esbuild's [`metafile` feature](https://esbuild.github.io/api/#metafile). It should provide enough information for you to implement something like `webpack-bundle-analyzer` yourself. It's what https://bundle-buddy.com/ uses for example, which is a similar tool to `webpack-bundle-analyzer`. You can just do a build with the `metafile` option set, then read that JSON file and print out whatever information you think is appropriate after the build is done. I think it'd be good for people to experiment with this for themselves first before considering including something like that in esbuild itself. I'd be interested to see what people come up with.

**Comment by joaopaulobdac** [comment]
I did not know about the metafile feature and bundle-buddy. Pretty cool.

> It's not immediately clear to me what should be shown. All of the things I can think of wouldn't provide enough information to be useful to me.

I would expect it to not show modules that are imported by the modules I'm importing. For example: If I import package A, and it imports package B, I'm only interested in the total cost of importing package A. This way, I don't think the summary output would be too much. And for projects that do import lots of packages, the list could be truncated.

**Comment by evanw** [comment]
> For example: If I import package A, and it imports package B, I'm only interested in the total cost of importing package A.

But many modules might import package B, which would potentially amortize the cost across many modules. This information would be hidden if the summary was collapsed like this so the output would potentially be misleading. Basically it feels to me like the output would raise questions that I'd immediately want more information to resolve. It seems like only showing the collapsed output could potentially result in people making misinformed decisions.

**Comment by joaopaulobdac** [comment]
Yeah that makes sense. Thanks. I'll close this issue since bundle-buddy already does what I want.

**Comment by dbousamra** [comment]
https://bundle-buddy.com/  is really useful thanks.

**Comment by Canuckaholic** [comment]
Does anyone know what the "All Imported Size" column represents in Bundle Buddy? Should I be concerned with large sizes there?

**Comment by dalcib** [comment]
`npx source-map-explorer bundle.js bundle.js.map --no-border-checks`
