### ISSUE TITLE
Zombie esbuild processes

### ISSUE THREAD

**Issue by mhanberg** [evanw/esbuild#643]
I can't seem to run the esbuild with the --serve functionality without leaving a zombie esbuild process when I stop it.

I have tried using the CLI and using the JS API, both seem to leave a zombie process.

This is what I've tried with the JS API so far.

```javascript
const baseConfig = {
  entryPoints: ['./js/app.js', './css/app.css'],
  target: "es2015",
  bundle: true,
  outdir: "../priv/static",
  plugins: [PostCSSPlugin] // plugin defined earlier in the script
};

function onRequest({ path }) {
  console.log(`building ${path}`);
}

esbuild.serve({ onRequest }, baseConfig)
  .then(server => {
    console.log("Server running for esbuild");

    process.on("exit", code => {
      console.log(`stopping the server with exit code ${code}`);

      server.stop();
    });
  })
  .catch(() => {
    console.log("Crashing esbuild");

    return process.exit(1)
  });
```

Any ideas?

**Comment by evanw** [comment]
I can't reproduce this. What platform are you on? And how are you stopping it? Does it happen without the plugin?

**Comment by mhanberg** [comment]
- This is on macOS.
- started as a "watcher" with the Phoenix web framework (elixir).
- I ctrl-c out of the phoenix dev server. it starts the esbuild process via an erlang port, not sure exactly how that get's shut down
- I do see it without the plugin

My priorities have shifted and I don't have the time to see this through. I'll close this and circle back if I find some time.

Thanks for your response 🙇.

**Comment by evanw** [comment]
Well I think I finally got it. I came across it due to some other work. It was a stray `!` of all things.

**Comment by mhanberg** [comment]
I'll update and see if it's fixed on my end. Thanks for your work on this!

**Comment by mhanberg** [comment]
Looks good 👍
