### ISSUE TITLE
Decorators tree shaking

### ISSUE THREAD

**Issue by Djaler** [evanw/esbuild#649]
When I have typescript decorators in code, the produced build doesn't allow treeshaking for classes with decorators.
For example, I have this source code:
```
@Component
export class Dialog<P> extends Vue {
    @Prop({ required: true })
    params!: P;
}
```
Compiled code:
```
let Dialog = class extends Vue {
};
__decorate([
  Prop({required: true})
], Dialog.prototype, "params", 2);
Dialog= __decorate([
  Component
], Dialog);
```

Because of `__decorate` calls treeshaking for Dialog doesn't work, even if this class not used in a client application.
I'm using `agadoo` utility to check treeshakeability

**Comment by evanw** [comment]
This is how TypeScript decorators work. The TypeScript-to-JavaScript transform in esbuild is designed to behave the same way that the official TypeScript compiler behaves. Here is [the output from the official TypeScript compiler](https://www.typescriptlang.org/play?emitDecoratorMetadata=false#code/AIYQ9gtgDmB2CmsAuAoeAPGAnJACAxgDYCGAzqbgCICWxhYA5gDwAKAfLhkogCYUBqAV3i4A3ilyTcwFljBQAFKNxZ4AR0HVVPAFy4kWYbgC+ASglSoxLMQikAhHpYBuFMZQ94RayMLw84NBwiEh6xLAAngA0uLLyYZExQvAJEShAA):

```js
let Dialog = class Dialog extends Vue {
};
__decorate([
    Prop({ required: true })
], Dialog.prototype, "params", void 0);
Dialog = __decorate([
    Component
], Dialog);
```

**Comment by Djaler** [comment]
So the whole world using typescript decorators is broken? That's sad

**Comment by folke** [comment]
Shouldn't these decorated classes be interpreted as if they had a PURE annotation?

Something like:

```js
let Dialog = /* @__PURE__ */ class Dialog extends Vue {
};
__decorate([
    Prop({ required: true })
], Dialog.prototype, "params", void 0);
Dialog = __decorate([
    Component
], Dialog);
```

**Comment by Djaler** [comment]
Yeah, but what about the first `__decorate` call? It only makes side effect, not assignment like the second call.

**Comment by evanw** [comment]
I'm closing this since I believe this question to be answered.

**Comment by Stnaire** [comment]
After many hours of trying, I think I've found a solution. Wrap all the decorators into a function that you then mark as pure:

```js
let Dialog =  class Dialog extends Vue {
};
Dialog = /* @__PURE__ */ ((_) => {
    __decorate([
        Prop({required: true})
    ], _.prototype, "params", void 0);
    return __decorate([
        Component
    ], _);
})(Dialog);
```
