### ISSUE TITLE
Feature request: Import type / types in Metadata.outputs[*].imports[*]

### ISSUE THREAD

**Issue by ggoodman** [evanw/esbuild#655]
## Use-case

Reading the build metadata of a code-split front-end and generating `<link rel="modulepreload" />` tags for synchronous imports (or at least prioritizing such over dynamic imports).

## Challenge

The challenge I've seen is understanding the type of imports surfaced in `Metadata`. I would like to be able to traverse the chunk dependency graph and generate appropriate preloads but would like to exclude dynamic imports from these. The metadata produced by `esbuild` doesn't include enough information to make the distinction between dynamic and synchronous imports.

**Comment by evanw** [comment]
Thanks for filing this. I've considered including this in the past. This is why the imports are objects instead of strings (so I can add additional properties). I was mainly just waiting for a use case. So I can add this.

**Comment by evanw** [comment]
Actually it looks like dynamic imports are already not included in the list of imports for an output chunk. This is a bug that should be fixed, but for now it should give you what you need. Can you confirm that dynamic imports in chunks are omitted for you too?

**Comment by ggoodman** [comment]
@evanw, you know what? You're probably right and I never even noticed. This actually suits my use-case quite well because I'm only interested in generating `<link rel="modulepreload" href="">` tags for synchronous imports. As a result, this doesn't impact me much.

I hope that if / when this 'bug' is fixed, we'll also have the ability to filter on sync vs async chunk dependencies.

**Comment by evanw** [comment]
That bug hasn't been fixed yet but in the next release you'll be able to filter by `obj.kind === 'import-statement'` (or by `obj.kind !== 'dynamic-import'`). I'll try to fix that during the upcoming code splitting rewrite.
