### ISSUE TITLE
`inject` has higher priority than `define`

### ISSUE THREAD

**Issue by remorses** [evanw/esbuild#660]
The identifiers for `options.define` should be replaced before injecting modules in `options.inject`

Another way to put this: `define` identifiers should have higher priority than exports in `inject`

This would prevent many injections from running, for example replacing occurrences of `process.env.VAR` with define could skip the injection of a `./process.js` module

Currently the injections are run first, which also means that the identifiers in `define` are never used if they are properties of an object exported from a module in `inject`

Reproduction: https://github.com/remorses/esbuild-inject-overrides-defines

**Comment by geoffharcourt** [comment]
The situation where this has been most relevant for us is that we need to define `process.cwd` as a function for some of our dependencies (just one that no-ops), so we have to pick a static set of `process.env` values from the injected `process` as a result.
