### ISSUE TITLE
Bug in path generation for code-split import paths

### ISSUE THREAD

**Issue by ggoodman** [evanw/esbuild#662]
## Description

`outputs[*].inputs[].path` values appear to include invalid directory segments when shared chunks are produced by nested paths.

## Reproduction

The following is a mini example that reproduces what I'm observing. It has a single entrypoint, with two chunks dynamically imported. The two lazy chunks and the main entrypoint all share a dependency on `./shared.js`.

**./index.js**

```js
import './shared';
import('./pages/about'), import('./pages/home');

React.createElement('div');
```

**./shared.js**:

```js
//Side-effect
console.log('Shared');
```

**./pages/about.js**:

```js
import '../shared';
```

**./pages/home.js**:

```js
import '../shared';
```

```sh
esbuild \
  --bundle \
  --format=esm \
  --define:process.env.NODE_ENV=\"production\" \
  --platform=browser \
  --outdir=build \
  --metafile=build/meta.json \
  --splitting \
  index.js
```

The issue can be observed in the following screenshot. Note that two output chunks refer to the same filename (`chunk.3D7RKSRB.js`), however at different locations. You can also see in the file tree that this chunk is only at the root of the `build` folder and is not duplicated in the `build/pages` folder.

![image](https://user-images.githubusercontent.com/50030/104268622-4ec51880-5462-11eb-8ddb-74126cd6347b.png)

**Comment by evanw** [comment]
Thanks for reporting this. The issue has been fixed and the fix will go out with the next release.
