### ISSUE TITLE
Importing default export and named exports in single import errors

### ISSUE THREAD

**Issue by jschaf** [evanw/esbuild#663]
Building this code: 

```
import React, { useState, useEffect } from 'react';
```

Errors with:

```
dist/app.js:1:7: error: No matching export for import "default"
```

I can work around the issue by splitting the import:

```ts
import React from 'react';
import { useState, useEffect } from 'react';
```

**Comment by evanw** [comment]
I tried to reproduce this by bundling this code with `react@17.0.1`:

```sh
echo "import React, { useState, useEffect } from 'react'" | esbuild --bundle
```

But I didn't get any errors. Are there more steps required to reproduce the error? Can you provide some sample code that would let me reproduce the problem?

**Comment by jschaf** [comment]
Hmmm... I can't reproduce either after updating Snowpack. Sorry for the noise, if it pops up again, I'll reopen with better steps.

Also, thank you for esbuild. I'm a huge fan of reframing the conversation around acceptable build times for large JS projects.
