### ISSUE TITLE
Capture output

### ISSUE THREAD

**Issue by arcanis** [evanw/esbuild#665]
It would be useful to have a way to catch the warnings and errors to operate on them. At the moment we can't pass a stdout stream to the `esbuild` function, so it's difficult to redirect it anywhere.

**Comment by evanw** [comment]
I'm assuming you are talking about the JavaScript API. This is possible by setting `logLevel: 'silent'` and then using the returned `warnings` and `errors` properties. If you're talking about the CLI instead, they are printed to `stderr` instead of `stdout`.

**Comment by arcanis** [comment]
Ahhh I completely missed that! Thanks 😃
