### ISSUE TITLE
Dead code elimination flag

### ISSUE THREAD

**Issue by Xiot** [evanw/esbuild#672]
This is probably a niche case, but it would be great to have a separate flag for dead code elimination.

My use case is as following:
The framework that I'm using builds up a single app that has both browser and node specific code, (wrapped with `__BROWSER__` and `__NODE__` flags, respectively, which are configured with --define).

Currently I'm experimenting with using esbuild inside of snowpack to handle the ad-hoc compilations.
Since the same source files are distributed to both browser and node, I'd like to remove the dead code before executing it, so that only the appropriate code (and imports) are evaluated.

As this is for development builds, I don't really want to enable too many minifications, but I would need the constant folding / dead code elimination.  I was trying `--minify-syntax` but I realized that it caused another plugin `react-refresh/babel` not to function, as it explicitly doesn't handle inlined `const` expressions.

~~Since I'm already relying on babel, and I don't need to do much processing in `esbuild` since I'm targeting es2020 (although I do still need to process jsx), I may just drop `esbuild` from that part of my pipeline.~~ (Actually its faster to create a simple babel plugin to undo the inline consts).  `esbuild` works so fast that I kinda wanna use it everywhere :P

**Comment by evanw** [comment]
Sorry, I don't understand what you mean. What is an inline `const` expression? Can you provide a code example that demonstrates what this means?

**Comment by Xiot** [comment]
Sorry,
By "inline const expression" I meant combining multiple `VariableDeclators` into a single `VariableDeclaration` (names of the nodes in the AST produced by babel).
```
const Foo = 1, Bar = 2;
```
vs
```
const Foo = 1;
const Bar = 2;
```
 

The actual reason for the code elimination flag looks something like this:
```
import {ServerPlugin} from './server';
import {BrowserPlugin} from './browser';

const app = new App();
if (__NODE__) {
  app.register(ServerPlugin);
}
if (__BROWSER__) {
  app.register(BrowserPlugin);
}
export default app;
```
The minification flags handle this nicely for me (slight side-tangent https://github.com/evanw/esbuild/issues/671) but where they run into issues with `react-refresh/babel` is that `--minify-syntax` rightfully merges consecutive `const` statements into a single one.  So
```
const ComponentOne = () => {...};
const ComponentTwo = () => {...};
```
becomes
```
const ComponentOne = () => {...}, ComponentTwo = () => {...};
```
which `react-refresh/babel`.  
I can work around the specific issue* of `react-refresh/babel`, however the larger topic of 'minification can affect other parts in the pipeline' is why I'm asking about the flag.

* In this case I wrote a simple babel plugin that runs before `react-refresh/babel` that expands the `VariableDeclarators` back into their own `VariableDeclarations`

**Comment by BRA1L0R** [comment]
This is not a niche case at all, i have the exact same issue that could be solved by your idea

**Comment by Xiot** [comment]
@BRA1L0R as a gotcha, after the constant folding, `imports` / `requires` are only removed when the `--bundle` flag is present, as without it, `esbuild` doesn't have enough context to determine if the `import`/`require` has side effects or not. (see #671 )
In my specific case I'm just removing all `import` calls that don't have a specifier. This works for me, but its definitely not a generic solution.

**Comment by evanw** [comment]
This was sort of added last September: https://esbuild.github.io/api/#tree-shaking. You can now do `--tree-shaking=true` to enable (top-level only) dead code elimination without needing to do `--bundle`, which may be what you're asking for. The `--minify-syntax` flag does more advanced dead code elimination during syntax compression but I don't think it makes sense to expose controls for disabling specific syntax transforms just to work around bugs in other code transformation libraries. Closing issue as resolved.
