### ISSUE TITLE
Relative source map file paths not found with vscode debugger

### ISSUE THREAD

**Issue by marvinhagemeister** [evanw/esbuild#675]
I'm currently debugging why breakpoints in vscode are not found with our testing setup over at [Preact](https://github.com/preactjs/preact). For that each test file is a fully self-contained bundle and our test runner serves those files relative to the server's process root:

```bash
# Folder structure
/my-project
  /src
    source.js
  /tests
    test1.js   # imports src/source.js
    /sub
      test2.js # imports src/source.js
```

How the files are served by the test runner:

```txt
/base/test1.js
/base/sub/test2.js
```

Now onto the source map resolution. The [spec](https://sourcemaps.info/spec.html#h.75yo6yoyk7x5) has this to say about resolution:

> If the sources are not absolute URLs after prepending of the “sourceRoot”, the sources are resolved relative to the SourceMap (like resolving script src in a html document).

The source maps generated by esbuild look like this for me:

```json
{
  "version": 3,
  "sources": ["src/source.js", "..."],
  "mappings": "...",
  "sourcesContent": [...]
} 
```

They don't have a `sourceRoot` property and therefore the source maps are resolved relative to the js file.

```txt
/base/test1.js -> /base/tests/test1.js
                  /base/src/source.js
/base/sub/test2.js -> /base/sub/tests/sub/test2.js
                      /base/sub/src/source.js
```

This leads to duplicate path segments as above. Here is a screenshot of what it looks like in Chrome's Devtools in Preact's suite:

![Screenshot 2021-01-14 at 17 08 47](https://user-images.githubusercontent.com/1062408/104617077-4ef42c80-568b-11eb-96f9-de3a7399095a.png)

In the screenshot `compat/test/browser` is repeated twice. So when a user creates a breakpoint in vscode the requested paths don't match and therefore the breakpoint is not found.

The way webpack handles this is by using a custom protocol `webpack://` to force the resolution logic to always be absolute. The vscode debugger plugin has some [built-in mappings](https://github.com/microsoft/vscode-chrome-debug/blob/c9bb7d2d793eeeefe06535baa39a4a4620a8ff91/src/chromeDebugAdapter.ts#L25-L31) that map this to the projects working directory.

I don't think using something like `esbuild://` would be a good fit, but some form of absolute resolution is needed for a consistent experience. Maybe this can be done via `sourceRoot` by setting it to a value which can be easily mapped by debuggers.

**Comment by evanw** [comment]
Can you try manually adding the appropriate `sourceRoot` value to the source map yourself and confirming that this fixes the issue for you locally? It would be good to know if that is a valid fix for this issue or not.
