### ISSUE TITLE
Can't run benchmarks

### ISSUE THREAD

**Issue by henriquehbr** [evanw/esbuild#676]
When i try to execute the benchmarks (both `make bench-three` or `make bench-three-esbuild`) i get the following error:

```
go build "-ldflags=-s -w" ./cmd/esbuild
rm -fr bench/three/esbuild
time -p ./esbuild --bundle --summary --global-name=THREE --sourcemap --minify bench/three/src/entry.js --outfile=bench/three/esbuild/entry.esbuild.js
process_begin: CreateProcess(NULL, time -p ./esbuild --bundle --summary --global-name=THREE --sourcemap --minify bench/three/src/entry.js --outfile=bench/three/esbuild/entry.esbuild.js, ...) failed.     
make (e=2): The system cannot find the file specified.
make: *** [Makefile:534: bench-three-esbuild] Error 2
```

## General details

**OS:** Windows 10 64-bits
**Editor:** VSCode 1.52.1
**Terminal:** Git Bash (On VSCode integrated terminal view)
**Go version**: `go1.15.6 windows/amd64`
**GNU Make version**: `GNU Make 4.3`
**esbuild version:** 0.8.32
**Latest commit from clone**: evanw/esbuild@57ac3ba

---

Immediately after cloning, i just ran the benchmarks without making any modifications to the project itself (as the [benchmark details](https://esbuild.github.io/faq/#benchmark-details) section on the docs don't specify any extra task that has to be performed before running the benchmarks), any clue of what could be happening?

Thanks in advance!

**Comment by evanw** [comment]
Sorry, my scripts are not cross-platform. I develop on macOS. I expect the scripts to work on most Unix systems but they will likely not work on Windows. Some options:

1. One option is to use WSL (Windows Subsystem for Linux). That should probably work, although then you will of course be benchmarking performance within the WSL environment.

2. Another option could be to debug what's happening on your end. For example, I'm not sure but that error message might be trying to say that the `time` command isn't installed? No guarantees on this option being easy to figure out though.

3. And another option could just be to follow what the benchmark commands do and translate them to Windows commands. To construct the three.js benchmark, you just need to a) clone three.js at version `r108`, b) make ten copies of the three.js `src` folder called `copy1` through `copy10`, and then c) create an `entry.js` file that looks like this:

    ```js
    import * as copy1 from './copy1/Three.js'; export {copy1}
    import * as copy2 from './copy2/Three.js'; export {copy2}
    import * as copy3 from './copy3/Three.js'; export {copy3}
    import * as copy4 from './copy4/Three.js'; export {copy4}
    import * as copy5 from './copy5/Three.js'; export {copy5}
    import * as copy6 from './copy6/Three.js'; export {copy6}
    import * as copy7 from './copy7/Three.js'; export {copy7}
    import * as copy8 from './copy8/Three.js'; export {copy8}
    import * as copy9 from './copy9/Three.js'; export {copy9}
    import * as copy10 from './copy10/Three.js'; export {copy10}
    ```

    From there you just tell each bundler to bundle the `entry.js` file. The commands are essentially as follows:

    * `esbuild --bundle --global-name=THREE --sourcemap --minify entry.js --outfile=entry.esbuild.js`

    * `webpack ./entry.js --devtool=source-map --mode=production --output-library THREE -o entry.webpack5.js`

    * `parcel build entry.js --global THREE --no-autoinstall --out-dir out --public-url ./ --out-file entry.parcel.js`

    * `rollup entry.js -o entry.rollup.js -c config.js` where `config.js` looks like this:

        ```js
        import { terser } from 'rollup-plugin-terser';
        export default {
          output: { format: 'iife', name: 'THREE', sourcemap: true },
          plugins: [terser()],
        }
        ```

    After that you'll need a way of timing the execution of each command. You don't want to rely on self-reported times for any of these tools because they will be wrong (too short). They won't include node's start-up time, for example. I'm not familiar with Windows so I can't help you with this part.

**Comment by henriquehbr** [comment]
Thanks for the clarifying answer! i think i'm going to stick with the third option, or maybe even running the benchmarks on a linux vm, the only reason i'm using windows at first is for gaming, because it really sucks so badly for coding
