### ISSUE TITLE
Error from bundled "google-protobuf" package: Cannot use 'in' operator to search for 'Array' in undefined

### ISSUE THREAD

**Issue by darioielardi** [evanw/esbuild#68]
Thanks for your great work with this package, that's what javascript web development needs right now.

I'm trying to migrate to esbuild a Typescript project ( currently bundled with Parcel ), which includes some code generated by the protocol buffers compiler which imports the [google-protobuf](https://www.npmjs.com/package/google-protobuf) library. 
When I run the bundled code in Chrome this error shows on console:
```
Uncaught TypeError: Cannot use 'in' operator to search for 'Array' in undefined
```
which is related to this piece of code in the bundled output:
```
// node_modules/google-protobuf/google-protobuf.js
    // ...
    $jscomp.polyfill = function(a, b, c, d) {
      if (b) {
        c = $jscomp.global;
        a = a.split(".");
        for (d = 0; d < a.length - 1; d++) {
          var e = a[d];
          e in c || (c[e] = {}); // <================ throws the error
          c = c[e];
        }
        a = a[a.length - 1];
        d = c[a];
        b = b(d);
        b != d && null != b && $jscomp.defineProperty(c, a, {
          configurable: true,
          writable: true,
          value: b
        });
      }
    };
```

I know this is not much, and I don't even know if this is a problem with the bundling, but I have no idea how to move.
Any help will be much appreciated, thank you.

**Comment by evanw** [comment]
Thank you for taking the time to report this issue. Unfortunately I'm having trouble reproducing this. Here's what I tried:

1. Create a simple protocol buffer message:

    ```proto
    syntax = "proto2";
    message Person { required string name = 1; }
    ```

2. Compile it as described in the `google-protobuf` readme:

        protoc --js_out=import_style=commonjs,binary:. messages.proto

    This generates `messages_pb.js` which depends on `require('google-protobuf')` as expected.

3. Create a simple JavaScript file `demo.js` to exercise the generated code:

    ```js
    const messages = require('./messages_pb.js');

    const person = new messages.Person();
    person.setName('Test name');

    const bytes = person.serializeBinary();
    const person2 = messages.Person.deserializeBinary(bytes);
    console.log('name:', JSON.stringify(person2.getName()));
    ```

4. Bundle it with esbuild:

        esbuild --bundle demo.js --outfile=out.js

5. Create a simple `index.html` file to get `out.js` to run:

    ```html
    <meta charset="utf-8">
    <script src="out.js"></script>
    ```

6. Serve `index.html` over localhost and view it in a browser.

When I try this, everything appears to run correctly. I see `name: "Test name"` in my console.

Are there a simple set of steps like these that I could take to reproduce this issue myself?

**Comment by darioielardi** [comment]
After hours of debugging I realized I was importing the bundled script as a ES Module.
Sorry for wasting your time and thank you for your help. closing.
