### ISSUE TITLE
[Feature] Add isCommonjs information in metafile

### ISSUE THREAD

**Issue by remorses** [evanw/esbuild#680]
I need to know when a bundle has been generated from a commonjs module, previously i was using the exports field and checking if there was only a default export but this would give too many false positives

```json
{
  "outputs": {
    "react/index.js": {
      "isCommonjs": true,
      "exports": ["default"],
      "imports": [
        ...
      ],
      "inputs": {
        ...
      },
      "bytes": 119
    }
}
```

**Comment by evanw** [comment]
It sounds like you are asking about if the input file is CommonJS or not, but the change you suggested appears to be indicating whether the output format was CommonJS or not. To clarify: you are interested in whether the input file is CommonJS not whether the output file is CommonJS, right? If so, I would expect this field to be in the `inputs` map not the `outputs` map.

**Comment by remorses** [comment]
Yes i think something like this should work
```json
{
  "outputs": {
    "react/index.js": {
      "isCommonjs": true,
      "exports": ["default"],
      "imports": [
        ...
      ],
      "inputs": {
        "node_modules/react/index.js": {
          "bytesInOutput": 0,
          "isCommonjs": true
        },
      },
      "bytes": 119
    }
}
```


My use case is rewriting imports to make them consumable by browser (for a tool called [bundless](https://github.com/remorses/bundless), very similar to vite but built around esbuild plugin system instead of rollup)

What i am doing is:
- bundle dependencies using esbuild
- rewrite imports to use the bundled ES module
- rewrite named imports to be properties of the default export if the bundle is using commonjs

**Comment by evanw** [comment]
Closing for the reason described in #810.
