### ISSUE TITLE
Incremental compilation doesn't seem to work properly

### ISSUE THREAD

**Issue by koluch** [evanw/esbuild#684]
Hi!

I am trying to use incremental build feature to implement custom development setup, but it doesn't seem to work properly. I am using example from [documentation](https://esbuild.github.io/api/#incremental):

```js
async function example() {
  console.log('start');

  let result = await require('esbuild').build({
    entryPoints: ['app.js'],
    bundle: true,
    outfile: 'out.js',
    incremental: true,
  });

  // Call "rebuild" as many times as you want
  for (let i = 0; i < 5; i++) {
    console.log('before rebuild');
    await result.rebuild();
    console.log('after rebuild'); // <- this would never print
  }

  // Call "dispose" when you're done to free up resources.
  result.rebuild.dispose();

  console.log('finish');
}

example();
```

When I call `await result.rebuild()`, node process exists. I tried this on node 10 and 14, same results. Oddly, when I add `setTimeout(() => {}, 5000);` at the top of the file, program works as expected

**Comment by evanw** [comment]
This was a regression that was introduced by a recent 3rd-party contribution: #656. I have already identified and fixed the issue: 0d50bbbe8dee843624fb2415a63aeb1ff903c4df. The fix hasn't been released yet but it will be in the next release.
