### ISSUE TITLE
Just wanted to say thanks

### ISSUE THREAD

**Issue by sirikon** [evanw/esbuild#685]
Doing any front-end related work recently has been a huge frustration. Dealing with all the nonsense, the bad tooling and the slow iterations was straight up depressing.

I'm working on a pet project that required some JS bundling with dependencies. Had to do many tricks and ugly workarounds to get my project working and building in a reasonable time so I could work on it without wanting to burn the computer and move to the mountains.

Couldn't find any sane approach for including type checking to the project. Including typescript on anything increased the build times immensely, and rewriting everything in something like Haxe resulted in too much work and complexity introduced in other ways.

And then, I found **esbuild**, which is freaking fast and it just works. It's been such a refreshing experience to use it so far. The build times are absurdly low even with minification and tree shaking of all the dependencies, creating a tidy 90kb bundle in no time. Now I'm including typescript in the project thanks to the built-in syntax removal/replacement for `.ts/.tsx` files, which keeps everything as fast as before and works like a charm.

So, just wanted to say a huge **thank you** for the amazing work being done here :heart:.

**Comment by zaydek** [comment]
I’m also incredibly grateful for this project. Thank you, sincerely. ❤️

**Comment by glromeo** [comment]
I am impressed by the quality and the speed of esbuild... a big thank you from me too!

**Comment by keelii** [comment]
感谢 esbuild，它让我们的开发环境1s内启动完成，这对我们来说非常重要 ❤️

**Comment by evanw** [comment]
Thanks everyone. It's heartwarming to hear how esbuild has helped improve your development experience. I'm going to close this issue now since it's not a problem with esbuild, but I really appreciate you sending your gratitude.
