### ISSUE TITLE
[Question] Go -> JS plugin interoperability

### ISSUE THREAD

**Issue by zaydek** [evanw/esbuild#688]
I’m wondering: Can tools written with esbuild in Go leverage esbuild/JS plugins?

On second thought, I suppose I could just pipe a process to Node from a Go plugin. 🤔 But is there a way to tap into the Node process that is already being orchestrated by esbuild? My solution would be targeted for one JS plugin, whereas I’m looking for an idiomatic way to resolve JS plugins generally.

Edit: I’ve read all of #111 to get up to speed. I know in your source you use this:

```go
		// We want to minimize the amount of IPC traffic. Instead of adding one Go
		// plugin for every JavaScript plugin, we just add a single Go plugin that
		// proxies the plugin queries to the list of JavaScript plugins in the host.
		options.Plugins = append(options.Plugins, api.Plugin{
			Name: "JavaScript plugins",
			Setup: func(build api.PluginBuild) {
				build.OnResolve(api.OnResolveOptions{Filter: ".*"}, func(args api.OnResolveArgs) (api.OnResolveResult, error) {
					var ids []interface{}
					applyPath := logger.Path{Text: args.Path, Namespace: args.Namespace}
					for _, item := range onResolveCallbacks {
						if config.PluginAppliesToPath(applyPath, item.filter, item.namespace) {
							ids = append(ids, item.id)
						}
					}
```

Is there a way I can tap into this so my tool written in esbuild / Go can tap into JS plugins as well?

This is the inverse of #515.

**Comment by zaydek** [comment]
On second thought, I suppose I could just pipe a process to node from a Go plugin. 🤔

**Comment by heyheyhello** [comment]
I don't think you can mix Node and Go plugins since esbuild isn't a "host" in and of itself - you have to write a Node or Go program that uses the API. You write a program that creates the esbuild process and defines plugins. If you need the inverse of the 115 comment you referenced then you can write a Go plugin that execs a child Node process to do work. As Evan said in that thread too, you can make it long lived and talk over stdin/sockets/etc, but you're responsible for creating that process.

**Comment by zaydek** [comment]
Hey @heyheyhello -- thanks for your reply. I don’t mind creating my own process, but wouldn’t this approach be somewhat incompatible with the _existing_ JS plugin ecosystem?

I’m trying to understand how esbuild does this internally. So if you use the Node API (like `require("esbuild").build`) then it creates a service and communicates with the esbuild executable over stdio (using a binary protocol).

I think what I’m trying to do is -- in order to leverage the existing ecosystem -- write a wrapper tool for esbuild that implements my core logic but still resolves community JS plugins.

**Comment by heyheyhello** [comment]
Hm so you want to write a JS script that basically imports a bunch of community plugins and sets them up in a plugin array but _doesn't_ import/call esbuild... and then have a Go program/plugin that uses esbuild and _somehow_ uses the JS plugins from that script?

So the question is how to load that JS plugin array into Go?

**Comment by zaydek** [comment]
> So the question is how to load that JS plugin array into Go?

I think we’re on the same page.

esbuild implements all of the internals to resolve JS plugins itself, and from looking at the source, when you call `build` from the NPM / JS API, you are kicking off a service that basically shunts build options to the esbuild binary (which presumingly is the compiled Go binary). Then Go uses a proxy plugin to talk to all JS plugins, which I think is how esbuild orchestrates resolving onResolve and onBuild plugins, by literally communicating over stdio to a child process in Node to resolve paths, contents, etc. At least this is what I’ve figured out so far.

**Comment by zaydek** [comment]
I’m gonna go ahead and close this for now so I don’t create unnecessary work for Evan. If I figure it out later I will follow-up here.
