### ISSUE TITLE
Set CWD programmatically

### ISSUE THREAD

**Issue by ggoodman** [evanw/esbuild#689]
## Description

Support passing in a `cwd` option to `Service#build()`.

## Use-case

Currently, much of `esbuild`'s path resolution and output path generation appears to depend on the working directory. Using `esbuild` as a component in a larger system means careful management of the working directory in order to prevent any conflicts with other components that also rely on `cwd`. I anecdotally observed that `cwd` also appears to be determined at the time the service is spawned and remains bound to that for its lifetime. That simplified working directory management, but I think `esbuild` could allow this to be explicit.

**Comment by zaydek** [comment]
For what it’s worth I’m currently doing something like this because esbuild requires absolute paths for custom resolvers:

```go
build.OnResolve(api.OnResolveOptions{Filter: "^%RETRO_STATIC_PATH%$"},
	func(args api.OnResolveArgs) (api.OnResolveResult, error) {
		cwd, err := os.Getwd()
		if err != nil {
			return api.OnResolveResult{}, fmt.Errorf("cannot cwd for plugin resolveRetroStaticPathPlugin; %w", err)
		}
		return api.OnResolveResult{Path: path.Join(cwd, filename)}, nil
	})
```

**Comment by evanw** [comment]
Yes I agree. I'm planning to do this in a breaking change. This will also help allow sharing the underlying service between builds with different working directories. Right now they spawn separate processes.
