### ISSUE TITLE
[Feature] read substitution variables from .env file

### ISSUE THREAD

**Issue by darioielardi** [evanw/esbuild#69]
It would be nice to have a flag `--env` to specify an .env file to read substitution variables from.

This way I wouldn't need to have multiple 'define:process.env.K=V' for multiple environment variables.

It could simply leverage the '--define' flag capabilities, prepending `process.env.` to each variable read from the specified file.

**Comment by evanw** [comment]
I recently added a JavaScript API that should make these kinds of things a lot nicer. This is pretty similar to "config files" in other bundlers.

For example, you can now write a build script like this:

```js
const { build } = require('esbuild')

const options = {
  stdio: 'inherit',
  entryPoints: ['./src/main.ts'],
  outfile: './dist/main.js',
  bundle: true,
  define: {
    'process.env.NODE_ENV': '"production"',
    'process.env.DEBUG': 'false',
  },
}

build(options).catch(() => process.exit(1))
```

You can even draw from the real environment at build time if you need to:

```js
const { build } = require('esbuild')
const define = {}

for (const k in process.env) {
  define[`process.env.${k}`] = JSON.stringify(process.env[k])
}

const options = {
  stdio: 'inherit',
  entryPoints: ['./src/main.ts'],
  outfile: './dist/main.js',
  bundle: true,
  define,
}

build(options).catch(() => process.exit(1))
```

I'm going to close this issue since I believe it's addressed by this new functionality.

**Comment by darioielardi** [comment]
That's awesome and it definitely addresses my issue, thanks!

**Comment by Speedy1991** [comment]
If you develop a react app and want the same behaviour as react-scripts you should only pass variables starting with `REACT_APP_`

```
for (const k in process.env) {
  if (k.startsWith('REACT_APP_')) {
    define[`process.env.${k}`] = JSON.stringify(process.env[k]);
  }
}
```

**Comment by iambumblehead** [comment]
Other toolchains support standard out-of-box env vars without requiring configuration scripts, eg [`VUE_APP_VAR,`][0] [`REACT_APP_VAR`][1] or [`S3_DIRECTORY_SYNC_VAR.`][2] Esbuild requires an extra config script to do this and, for people accustomed to using env vars with other tools, this situation makes esbuild incomplete and slightly annoying.

That said, esbuild is a terrific tool and I'm glad to be using it. I respect and appreciate this project. Esbuild would be even better if it supported env vars without requiring an extra config script.

[0]: https://cli.vuejs.org/guide/mode-and-env.html#using-env-variables-in-client-side-code
[1]: https://create-react-app.dev/docs/adding-custom-environment-variables/
[2]: https://github.com/foo-software/s3-directory-sync-cli/#usage

**Comment by iambumblehead** [comment]
@evanw is there any chance you might re-open this for everyone who thumbs-upped my last comment?

**Comment by NatoBoram** [comment]
How do we use it, though?

I have some environment variables in my `build.js`:
```javascript
const define = {
  'process.env.INLINE_BOLD': JSON.stringify(process.env['INLINE_BOLD']),
  'process.env.INLINE_COLOR': JSON.stringify(process.env['INLINE_COLOR']),
  'process.env.INLINE_ITALIC': JSON.stringify(process.env['INLINE_ITALIC']),
  'process.env.INLINE_LINK': JSON.stringify(process.env['INLINE_LINK']),
  'process.env.INLINE_MARKER': JSON.stringify(process.env['INLINE_MARKER']),
  'process.env.INLINE_STRIKETHROUGH': JSON.stringify(process.env['INLINE_STRIKETHROUGH']),
  'process.env.INLINE_UNDERLINE': JSON.stringify(process.env['INLINE_UNDERLINE']),
};

/** @type import('esbuild').BuildOptions */
let opts = {
  entryPoints: ['js/app.js'],
  bundle: true,
  target: 'es2016',
  outdir: '../priv/static/assets',
  logLevel: 'info',
  loader,
  plugins,
  external: ['/images/*'],
  define,
};
```

And some code that I want to be replaced:

```javascript
console.log('process.env.INLINE_BOLD');
console.log(process.env.INLINE_BOLD);
```
The compiled output:
```javascript
console.log("process.env.INLINE_BOLD");
console.log(process.env.INLINE_BOLD);
```
And the result in the console:
```log
process.env.INLINE_BOLD
Uncaught ReferenceError: process is not defined
```
Something isn't happening on my end...

**Comment by bluebrown** [comment]
Its not working for me either, it comes out as `void 0`, when I check the compiled script.

**Comment by marianneciara** [comment]
@NatoBoram I'm also having this issue – did you manage to resolve it in the end?

**Comment by NatoBoram** [comment]
Nope. Since we're doing back-end, we just injected these variables as a JSON string inside the HTML.

**Comment by marianneciara** [comment]
Thanks for your reply. I actually pieced together a solution that's working for me, posting my solution just in case it helps anyone.

Basically, I wasn't specifying the config file in my scripts – I wrongly assumed that the config file would be automatically picked up and would replace my inline `esbuild` command in `package.json`.

Currently I've got this setup that's working:

**.env**

`VARIABLE="Value"`

**package.json**

`"dev:js": "node esbuild.config.js --watch"`
`"build:js": "node esbuild.config.js"`

**esbuild.config.js**

```
const { build } = require('esbuild')
require('dotenv').config()
const args = process.argv.slice(2)

const options = {
  entryPoints: ['src/assets/js/_main.js'],
  outfile: 'dist/assets/js/main.bundle.js',
  bundle: true,
  minify: true,
  watch: args.includes('--watch'),
  define: {
    'VARIABLE': JSON.stringify(process.env.VARIABLE)
  },
}

build(options).catch(() => process.exit(1))
```

**Then in the front-end JS**

`console.log(VARIABLE)`

**Result**

`Value`


Feedback on this configuration more than welcome!

**Comment by mdtanrikulu** [comment]
one drawback is that any secret key will be visible in the debugger because the env variables given at build time are embedded in the bundled js.

**Comment by soeasyjx** [comment]
esbuild.config.js
```js
const { build } = require('esbuild')

const options = {
  stdio: 'inherit',
  entryPoints: ['./src/main.ts'],
  outfile: './dist/main.js',
  bundle: true,
  define: {
    'process.env.NODE_ENV': '"production"',
    'process.env.DEBUG': 'false',
  },
}
```

Use `import process,{pid} from "process"`;
process.env.DEBUG is not available

**Comment by SanariSan** [comment]
For those who are just looking for how to use env variables in a codebase, here is a link to the official docs. It shows a way to handle this using plugin resolution, no substitutions needed, which I think is a cleaner approach: https://esbuild.github.io/plugins/#using-plugins

**Comment by Nareshkumar-S-lap** [comment]
> one drawback is that any secret key will be visible in the debugger because the env variables given at build time are embedded in the bundled js.

then what we do for this any solution you got ?
