### ISSUE TITLE
Bug | Common chunks not working

### ISSUE THREAD

**Issue by PeteSolid** [evanw/esbuild#697]
esbuild version: 0.8.32
windows 10
node 15

Input:
```js
// a.ts
`export default function x() {
  return 1 + helper();
}
function helper() {
  return 4;
}
```
```js
// b.ts
export default function y() {
  return 1 + helper();
}
function helper() {
  return 4;
}
```
**Goal**: extract helper in a seperate file
`esbuild a.ts b.ts --format=esm --splitting  --minify --outdir=out`

Currently both output files contain the helper function

**Comment by evanw** [comment]
Code splitting doesn't work that way. The identity of these two functions are considered separate for the purposes of code splitting, so no code is considered to be shared. Code splitting works by making sure each given piece of code in each file ends up in at most one output file. It does not try to de-duplicate similar code from separate files. Instead, you would need to do something like this:

```ts
// a.ts
import { helper } from './c'
export default function x() {
  return 1 + helper();
}
```

```ts
// b.ts
import { helper } from './c'
export default function y() {
  return 1 + helper();
}
```

```ts
// c.ts
export function helper() {
  return 4;
}
```

**Comment by PeteSolid** [comment]
Ah, thank you for making this clear 👍
