### ISSUE TITLE
Svelte on m1 bug with precompiled svelte/internal sources.

### ISSUE THREAD

**Issue by Valexr** [evanw/esbuild#699]
Svelte on m1 bug with precompiled svelte/internal sources.
When component unmount from slot i have this error:

![image](https://user-images.githubusercontent.com/5656366/105285336-3f15a480-5bc5-11eb-8448-7f84098ea4ce.png)

When un/mount component in slot in localy imported module with this file structure:

- distImportedModule
- srcImportedModule
   - app
      - distApp
      - srcApp
 
 
![image](https://user-images.githubusercontent.com/5656366/105284722-18a33980-5bc4-11eb-9bf2-66d602c5e0fb.png)

### TESTED SOURCES ONLY FOR M1 arm64 architecture

[Source code](https://svelte.dev/repl/d6af19f0af41493f9f31e54cd75a96ea) for example. 
If you download it - remove rollup bundler.

Or [zip](https://github.com/Valexr/svelte-slidy/blob/master/tmp/svelte-slidy.zip) example.

**Comment by EMH333** [comment]
I would recommend closing this issue, as it doesn't seem to directly relate to esbuild. It can always be reopened if it is determined that is not the case.

Let's continue the conversation in EMH333/esbuild-svelte#23 and go from there?
