### ISSUE TITLE
invalid code is generated if a semicolon is omitted after setting a property on an object to an arrow function on the line before an iife

### ISSUE THREAD

**Issue by LinusCenterstrom** [evanw/esbuild#701]
The original code is generated by webpack (can provide if wanted).

But a minimal example is this.
source: 
```js
const a = {};
a.g = () => {}
(function(){
  console.log("test");
})();
```
output:
```js
const a = {};
(a.g = () => {
})(function() {
  console.log("test");
})();
```

From what I could gather defining an arrow function should cause automatic semicolon insertion which is why the source is even valid in the first place.

**Comment by evanw** [comment]
Thanks so much for reporting this. Will fix.
