### ISSUE TITLE
serve output

### ISSUE THREAD

**Issue by a-b-r-o-w-n** [evanw/esbuild#707]
Is there a reason that `esbuild.serve` does not expose the outfile and instead serves the entrypoints?

For example, the following configuration will serve `client.js` at `localhost:8000` but not `app.js`:

```js
esbuild.serve({}, {
  entryPoints: ['client.tsx'],
  bundle: true,
  outfile: 'app.js'
})
```

**Comment by evanw** [comment]
Thanks for reporting this issue. It looks like the serve API currently ignores the `outfile` setting. You're right that it shouldn't ignore it, so this is a bug that should be fixed.
