### ISSUE TITLE
Unexpected token "!" as line first character bundling scriptjs package

### ISSUE THREAD

**Issue by darioielardi** [evanw/esbuild#71]
I'm using an npm package which has [scriptjs](https://www.npmjs.com/package/scriptjs) as a dependency.
When I try to build with esbuild it fails with this error:
```
node_modules/scriptjs/dist/script.js:95:6: error: Unexpected "!"
       !scripts.length ? $script(s, id, done) : $script(s, callback)
       ^

``` 
Adding a semicolon to the end of the previous line fixes the error.

**Comment by evanw** [comment]
Thanks for the report. It looks like this regressed when I added TypeScript parsing (TypeScript uses a postfix `!` as a non-null assertion operator).
