### ISSUE TITLE
[Question] How do you all handle the change-log entries?

### ISSUE THREAD

**Issue by gagoar** [evanw/esbuild#713]
👋🏻  @evanw! thanks for this amazing tool.

This question might be off-topic, but I wanted to know how you guys generate the changelog? I have some OSS projects and I would like to take the same approach. 

The summary in the automatic dependency updates is quite useful to understand what happened. 

Thanks

**Comment by evanw** [comment]
I manually add an entry to CHANGELOG.md for each user-facing change under an "Unreleased" heading. Then, when I do a release, I change the heading to the newly-released version number. The script that publishes the release pushes a git tag for the newly-released version starting with `v`, which triggers a GitHub action to publish a new GitHub release. The last part (automating GitHub releases) was a contribution from here: #539.

**Comment by gagoar** [comment]
Oh I see. that's helpful.  I was guessing you had something around reading the PR comment so that could be included in the CHANGELOG. 

Thanks for answering!
