### ISSUE TITLE
Support logical assignment operator

### ISSUE THREAD

**Issue by schickling** [evanw/esbuild#715]
It seems like [logical assignment operators](https://github.com/tc39/proposal-logical-assignment/) (TC39 stage 4) are currently not yet supported. As they are supported in TypeScript since version 4 (see [PR](https://github.com/microsoft/TypeScript/pull/37727)), this means esbuild can't compile applications using this feature resulting in errors like this:

![image](https://user-images.githubusercontent.com/1567498/105966059-703e1b00-6084-11eb-9bfd-9746d7fef003.png)

Would be great if support could be added for this feature :)

**Comment by evanw** [comment]
I'm confused since support for this was added to esbuild a long time ago:

```sh
> echo "a ??= b" | esbuild
a ??= b;

> echo "a ??= b" | esbuild --target=es6
a != null ? a : a = b;
```

Your screenshot looks like an error from the TypeScript compiler, not from esbuild. Maybe you have an old version of the TypeScript compiler installed?

**Comment by schickling** [comment]
Funnily enough I'm currently toying with a Figma plugin and have been using `figplug` by @rsms which uses TS 3.9.6. Upgrading did the tricky indeed. Thanks!

**Comment by rsms** [comment]
Thanks for the ping @schickling — I've published a new version of `figplug` with typescript 3.9.7 (and fresh Figma API type definitions)

**Comment by schickling** [comment]
FWIW @rsms In this particular case you'd probably need to upgrade TS to 4.0+ otherwise the new logical assignment operators won't yet be supported (to my knowledge).
