### ISSUE TITLE
Import all files in folder

### ISSUE THREAD

**Issue by thomaschaaf** [evanw/esbuild#722]
I have a folder containing database migrations. I would like to include all files in a directory so that I can pass them to the database migration executor. As I understand something like `require.context` from webpack is not supported or desired in esbuild. What would your suggestion be on how I could import all files in a folder?

**Comment by evanw** [comment]
I would make a plugin that uses `fs.readdir` to read all of the files in the directory and then generates a virtual module with an import statement for each one. You don't need a plugin for this (you could just have a script generate that module before the build starts) but your workflow may be cleaner with a plugin.

**Comment by evanw** [comment]
Closing this because I believe the above solution is sufficient.

**Comment by thomaschaaf** [comment]
@evanw I am currently trying to write a drop-in replacement for `require.context` from webpack. The problem is that I need to get the parameters passed in to the function e.g. `require.context('./migrations')`. For this I think I need the AST. I am currently thinking of using ts-morph for this (after checking if `require.context` is in the file at all).

With the onResolve Plugin hook I could create something like https://www.npmjs.com/package/import-glob fairly easily (like the wasm plugin example).

What do you think is the better option? I would think the drop-in would benefit more but getting the AST from ts-morph seems like overkill.

**Comment by evanw** [comment]
I think the import-glob approach would be the best for now. It already works with the existing plugin API and it seems pretty ergonomic to me. It's also likely to be maximally efficient vs. AST manipulation plugins.

Doing ts-morph if `require.context` is in the file could be fine if there are only a few files containing `require.context`, especially if compatibility with existing code without modifying the code is critical. In that case it sounds reasonable to do something like this.

Long term I could imagine allowing `require.context()` to be implemented via plugins along with #700.

**Comment by thomaschaaf** [comment]
I ended up writing this plugin: https://github.com/thomaschaaf/esbuild-plugin-import-glob
