### ISSUE TITLE
Process will exit when watch mode is on

### ISSUE THREAD

**Issue by susiwen8** [evanw/esbuild#730]
Hi, amazing work on `watch mode`, but I have encounter under `watch mode`, after first build, process will exit, which I think it shouldn't happen.

Here is the script I use
```js
build({
    // stdio: 'inherit',
    entryPoints: [path.resolve(__dirname, '../src/echarts.all.ts')],
    outfile: outFilePath,
    format: 'cjs',
    sourcemap: true,
    bundle: true,
    watch: {
       onRebuild(error, result) {
            if (error) {
                console.error('watch build failed:', error)
            } else {
                console.error('watch build succeeded:', result)
            }
        },
    }
})
```

pretty much the same code with [doc](https://esbuild.github.io/api/#watch).

I try to debug myself, found out [this line](https://github.com/evanw/esbuild/blob/master/lib/node.ts#L73) would cause this issue. So what I propose as follow
```js
      if (result.rebuild) {
        let old = result.rebuild.dispose;
        result.rebuild.dispose = () => {
          old();
          service.stop();
        };
      }
      else if (!options.watch) {
        service.stop();
      }
```

However I don't have faith on this, so would you confirm it? If I were right, I could make a PR for it.

**Comment by fernandopasik** [comment]
I have detected the same problem.

```
node .esbuild.cjs
watch build failed: Error: The service was stopped
    at Socket.afterClose (/myproject/node_modules/esbuild/lib/main.js:526:18)
    at Socket.emit (events.js:327:22)
    at endReadableNT (internal/streams/readable.js:1327:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

**Comment by fernandopasik** [comment]
I tried your proposal @susiwen8 and I got an error on rebuild

```
watch build failed: Error: Build failed with 4 errors:
../../node_modules/esbuild/lib/main.js:550:33: error: [JavaScript plugins] callback is not a function
../../node_modules/esbuild/lib/main.js:550:33: error: [JavaScript plugins] callback is not a function
../../node_modules/esbuild/lib/main.js:550:33: error: [JavaScript plugins] callback is not a function
../../node_modules/esbuild/lib/main.js:550:33: error: [JavaScript plugins] callback is not a function
    at failureErrorWithLog (myproject/node_modules/esbuild/lib/main.js:1076:15)
    at myproject/node_modules/esbuild/lib/main.js:892:46
    at myproject/node_modules/esbuild/lib/main.js:576:15
    at Generator.next (<anonymous>)
    at myproject/node_modules/esbuild/lib/main.js:28:61
    at new Promise (<anonymous>)
    at __async (myproject/node_modules/esbuild/lib/main.js:10:10)
    at handleRequest (myproject/node_modules/esbuild/lib/main.js:545:40)
    at handleIncomingPacket (myproject/node_modules/esbuild/lib/main.js:602:7)
    at Socket.readFromStdout (myproject/node_modules/esbuild/lib/main.js:506:7) {
```

**Comment by evanw** [comment]
Thanks for the report. Clearly I was rushing when I got this out last night. The tests for this (which are working correctly) all use the `startService` API, not the `build` API. So that should be a good workaround for now.

Instead of doing this:

```js
esbuild.build({...})
```

Do this for now:

```js
esbuild.startService().then(service => service.build({...}))
```

I'll get this fixed today. Thanks again for the report, and sorry about the trouble.

**Comment by fernandopasik** [comment]
Thank you @evanw for taking this one quickly and for all the hard work!

**Comment by camsloanftc** [comment]
Hey @evanw, It looks like this is still an issue when attempting to use `esbuild.serve`. It immediately throws if I add `watch.onRebuild` to the buildConfig object. 

I am on `0.8.44` and can confirm it has no issues with just using the build command directly.

Would you like me to open a new issue for this?

**Comment by evanw** [comment]
Is the error message `Cannot use "watch" with "serve"`? It is an intentional limitation that you can't use both watch and serve at the same time. They are both two different ways of doing incremental builds.

**Comment by camsloanftc** [comment]
Ah yes sorry - you're right. Is there a similar callback to `onRebuild` using serve? The use case being to run an action anytime the files have changed.

**Comment by evanw** [comment]
The local server doesn't monitor for file changes at all. It only rebuilds when new HTTP requests come in. If you want to detect file changes too I suppose you could run esbuild twice, once for the local web server and once for the file watcher.
