### ISSUE TITLE
Decorator set to a constructor parameter

### ISSUE THREAD

**Issue by m-doi2** [evanw/esbuild#734]
The code when transpiling the decorator set in the constructor parameter seems to differ in processing from the code output from tsc.

As an effect of this, I have found that when I transpile and run code that uses the Inversify.js decorator, I get an error.

I have prepared this repository as a sample of what happens.
https://github.com/m-doi2/esbuild-ctor-param-decorator-bug-sample

In summary, there are the following differences between esbuild and tsc.

```ts
// tsc
Ninja = __decorate([
    inversify_1.injectable(),
    __param(0, inversify_1.inject(exports.Symbols.Katana)),
    __param(1, inversify_1.inject(exports.Symbols.Shuriken))
], Ninja);
```

```ts
// esbuild
__decorate([
  __param(0, import_inversify.inject(Symbols.Katana)),
  __param(1, import_inversify.inject(Symbols.Shuriken))
], Ninja.prototype, "constructor", 1);
Ninja = __decorate([
  import_inversify.injectable()
], Ninja);
```

It seems that tsc sets the parameter decorator directly to the class, while esbuild sets the parameter decorator to the prototype constructor.

Therefore, the following modification will work correctly.

```ts
// esbuild (fixed)
Ninja = __decorate([
  import_inversify.injectable(),
  __param(0, import_inversify.inject(Symbols.Katana)),
  __param(1, import_inversify.inject(Symbols.Shuriken))
], Ninja);
```

If this helps with this project, I'd be happy.

**Comment by evanw** [comment]
Ah, I wasn't aware of `constructor` behaving this way. Thanks for the report. This is indeed a bug. I can fix this.
