### ISSUE TITLE
 "jsx": "preserve" seems not working

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#735]

**Comment by hardfist** [comment]
I try to use esbuild to transform my `.tsx`files to `.jsx`(just to strip type annotation), but it seems even though I pass {jsx:preseerve} to tsconfigRaw, it still transform jsx to createElement
```
    plugins: [
      {
        name: 'esbuild',
        setup(build) {
          build.onLoad({ filter: /\.tsx$/ }, async (args) => {
            const result = (await fs.readFile(args.path)).toString();
            const contents = await esbuild.transform(result, {
              loader: 'tsx',
              tsconfigRaw: `{
  "compilerOptions": {
    "jsx": "preserve"
  }
}`,
            });
            console.log('result:', result, contents);
            return {
              contents: contents.code,
              loader: 'jsx',
            };
          });
        },
      },
    ],
```

**Comment by evanw** [comment]
Only a few `tsconfig.json` parameters are loaded at the moment, and `jsx` is not one of them. There is no code in esbuild that is capable of generating JSX syntax so this is expected behavior.

Can you say more about your use case? What tool(s) are you using on your code after stripping types with esbuild?

**Comment by hardfist** [comment]
we use `@babel/traverse` to transform `jsx` to `miniapp`(something like vue), which  relys on jsx ast type

**Comment by Dkendal** [comment]
Just ran into this as well. At https://github.com/BuilderIO we have a project https://github.com/BuilderIO/jsx-lite that converts JSX to equivalently code for multiple front-end frameworks. I was hoping to use esbuild as a drop in replacement for `tsc` but to do that it has to output JSX as out tool chain currently relies on Babel transforms to arrive at the final output.

I'd be happy to assist with this if you can point me in the right direction.

**Comment by whaaaley** [comment]
> Only a few `tsconfig.json` parameters are loaded at the moment, and `jsx` is not one of them. There is no code in esbuild that is capable of generating JSX syntax so this is expected behavior.
> 
> Can you say more about your use case? What tool(s) are you using on your code after stripping types with esbuild?

My use case for this is that I want to run JSX transformations all at once _after_ esbuild ouputs a bundle. Ignoring JSX would be very nice to have. I'm using official TSC to take care of JSX.

**Comment by DominicTobias** [comment]
JSX for React Native also needs to be on "preserve"/"react-native" AKA "don't do anything with it"
