### ISSUE TITLE
Watch mode not working on Ubuntu

### ISSUE THREAD

**Issue by laurentpayot** [evanw/esbuild#737]
Watch mode issue #21 was closed but using the following example from the docs

```js
require('esbuild').build({
  entryPoints: ['app.js'],
  outfile: 'out.js',
  bundle: true,
  watch: {
    onRebuild(error, result) {
      if (error) console.error('watch build failed:', error)
      else console.error('watch build succeeded:', result)
    },
  },
})
```
with
```js
// app.js
console.log("Hello!")
```
I get the following error:
```
watch build failed: Error: The service was stopped
    at Socket.afterClose (/home/laurent/projects/myproject/node_modules/esbuild/lib/main.js:526:18)
    at Socket.emit (node:events:388:22)
    at endReadableNT (node:internal/streams/readable:1294:12)
    at processTicksAndRejections (node:internal/process/task_queues:80:21)
```

Without the watch option the output is generated without problem.

I'm using **node 15.3.0** on my **Ubuntu 20.10** PC.

**Comment by evanw** [comment]
I'm guessing this is a duplicate of #730. Hopefully the problem is already fixed in the latest version that was just released. What version of esbuild are you using? The latest version is 0.8.39.

**Comment by laurentpayot** [comment]
Oops yes looks like it's a duplicate of #730. I was using version 0.8.38. Just installed esbuild@0.8.39 and it worked like a charm. Thanks a lot!
