### ISSUE TITLE
Option to disable spinner in watch mode

### ISSUE THREAD

**Issue by mhanberg** [evanw/esbuild#742]
The watch mode is very nice, but the spinner disrupts the console during my development, so it would be nice to be able to turn it off.

Here is an example: Running a [Phoenix](https://github.com/phoenixframework/phoenix) server with the console enabled. (I have phoenix configured to run esbuild when the dev server boots up)

You can see that the esbuild spinner eats the characters as I try to type, not allowing me to easily use the REPL console.

![esbuild-spinner](https://user-images.githubusercontent.com/5523984/106550917-1dc88880-64e2-11eb-86f4-0b11296738d1.gif)

Thanks!

**Comment by evanw** [comment]
The log level API option is documented here: https://esbuild.github.io/api/#log-level. Setting `--log-level=warning` only shows warnings and errors, setting `--log-level=error` only shows errors, and setting `--log-level=silent` only shows nothing.

**Comment by mhanberg** [comment]
That works, thanks 👍.
