### ISSUE TITLE
[Feature] Dead Code Elimination with dynamic import() statements.

### ISSUE THREAD

**Issue by osdevisnot** [evanw/esbuild#747]
hi @evanw, I know this has been brought up before in #16 and various other threads (#661, #453, #322, #56), but I wanted to ensure the dead code elimination is covered when using dynamic imports.

More precisely, I want to ensure below test case from [tooling.report](https://bundlers.tooling.report/) is covered.

This test bundles two modules - an entry module, and a `utils.js` module it dynamically imports to create a split point. The dynamically imported module has two exports, but only the `logCaps` export is used.

**index.js**

```js
(async function() {
  const { logCaps } = await import('./utils.js');
  logCaps('This is index');
})();
```

**utils.js**

```js
export function logCaps(msg) {
  console.log(msg.toUpperCase());
}

export function thisIsNeverCalled(msg) {
  return msg + '!';
}
```

Expected Output:

Once built for _production_, the `thisIsNeverCalled` function from `utils.js` should not be present in the resulting bundle(s).

Output as of `v0.8.39` of esbuild:
```js
// ...cjs interop code removed to reduce noise.

// src/utils.js
var require_utils = __commonJS((exports) => {
  __export(exports, {
    logCaps: () => logCaps,
    thisIsNeverCalledEither: () => thisIsNeverCalledEither
  });
  function logCaps(msg) {
    console.log(msg.toUpperCase());
  }
  function thisIsNeverCalledEither(msg) {
    return msg + "!";
  }
});

// src/index.js
(function() {
  return __async(this, null, function* () {
    const {logCaps} = yield Promise.resolve().then(() => __toModule(require_utils()));
    logCaps("This is index");
  });
})();

```

**Comment by evanw** [comment]
Sure, sounds good. I can keep this issue open to track this feature.
