### ISSUE TITLE
esbuild watch caused high disk i/o

### ISSUE THREAD

**Issue by connor4312** [evanw/esbuild#750]
I have happily adopted esbuild and started using it for new projects. A couple days after I first tried it and complained there was no watch mode, watch mode was released -- thank you! ❤️ 

This morning I had watch mode running on a project and noticed my computer slowed down a good deal. I opened task manager and saw the esbuild was thrashing the disk pretty hard.

![image](https://user-images.githubusercontent.com/2230985/106826152-2ed8dd00-663b-11eb-9c85-fd6411970b80.png)

The command was:

```
esbuild web/src/index.tsx --bundle --tsconfig=tsconfig.json --outfile=web/public/index.js --format=iife --sourcemap --watch  --define:process.env.NODE_ENV=\"production\"
```

It had been running fine for several hours previously, and after restarting it it went back to normal; unfortunately I don't have a reproduction. And didn't have the wherewithal at the time to try to collect any sort of traces before killing it, but I wanted to let you know regardless.

This was running inside an Ubuntu Docker container using Docker's WSL2 backend.

**Comment by evanw** [comment]
Thanks for the report. Watch mode uses polling so it relies on your operating system to keep file metadata in RAM. I have no idea what the Docker <-> WSL2 <-> Windows file system driver setup is like but I could imagine it not caching stuff effectively.

FWIW you don't need to use esbuild's built-in watch mode if you don't want to or if it's not working for you. Feel free to use esbuild's build API with any of the many other file watching libraries out there. Some other well-known ones are [watchexec](https://github.com/watchexec/watchexec) and [chokidar](https://github.com/paulmillr/chokidar).

**Comment by connor4312** [comment]
Except for this one moment, esbuild's watch has been working beautifully (in containers and windows itself)

**Comment by mitschabaude** [comment]
I want to report what I assume is a related problem:

After starting esbuild in watch mode, it continually keeps increasing RAM usage by about 1-2 MB per second (!).

My OS is Ubuntu, but this was also experienced by a co-worker with another Linux distro. We noticed it when his laptop was brought to its knees, with 4 GB RAM usage by esbuild alone ;)

**Comment by evanw** [comment]
Ah wow ok that's terrible. I haven't experienced that myself but I'll try to reproduce it.

**Comment by connor4312** [comment]
Good find! Though I don't think that's my issue. I'll make a fork of esbuild that runs a pprof server so that I can get more information for you if I'm un/lucky enough to hit this again.
