### ISSUE TITLE
root dir of build and  custom metafile

### ISSUE THREAD

**Issue by sessionboy** [evanw/esbuild#753]
@evanw Hi, guy!
1，provide root dir configuration
I didn’t find root dir configuration, 
My esbuild build script is in a separate library, which is referenced by other projects, so they are not in the same root directory.

```js
// esbuild script lib dir
/Volumes/work/mylib/packages/esbuild/...

// another project dir
/Volumes/work/myproject

service.build({
    rootDir:  "/Volumes/work/myproject",   // This is exactly what i need
    target: 'esnext',
    format: 'esm',
    entryPoints:[ "react", "react-dom" ],
    ....
})
```
Now I don't know how to deal with it, please give me some help.

2，I want to customize the output structure of the `metafile`, for example:
```js
{
  "imports": {
    "react": "./react.js",
    "react-dom": "./react-dom.js"
  }
}
```
Therefore, I suggest allowing `metafile` as a function, giving the metafile to the user to control, so as to customize the output content of the `metafile`.

**Comment by evanw** [comment]
1. I'm not sure what you mean by root dir but you may find these API options helpful:

    * https://esbuild.github.io/api/#working-directory
    * https://esbuild.github.io/api/#outbase

2. You can easily do this yourself by writing code that reads the metafile after the build is done and overwrites it with different contents. If you don't want the metafile to be written to the file system first, you can use the [write](https://esbuild.github.io/api/#write) API option to have the API return the output files as in-memory buffers.

**Comment by sessionboy** [comment]
>    * https://esbuild.github.io/api/#working-directory   

This is what i want, thanks.

> You can easily do this yourself by writing code that reads the metafile after the build is done and overwrites it with different contents. If you don't want the metafile to be written to the file system first, you can use the write API option to have the API return the output files as in-memory buffers.   

I tried, but this will affect the speed of the build, which is more than 1 times the original speed.

**Comment by sessionboy** [comment]
Thanks. 🍻
