### ISSUE TITLE
var(--tw-empty,/*!*/ /*!*/) wrongly processed

### ISSUE THREAD

**Issue by monken** [evanw/esbuild#760]
TailwindCSS uses this workaround to set the value of a CSS variable to a single empty space:

```css
--tw-ring-inset: var(--tw-empty,/*!*/ /*!*/);
```

which is translated by esbuild into (`minify: false`)

```css
--tw-ring-inset: var(--tw-empty,);
```

which is not valid and should instead be left untouched.

There are more details around this in the following ticket:

https://github.com/tailwindlabs/tailwindcss/issues/2889

**Comment by evanw** [comment]
Wow what a crazy edge case. Thanks for the heads up. I’ll make sure this is fixed in one of the upcoming releases.

**Comment by monken** [comment]
Wow, thanks for fixing this so fast!

**Comment by sebastienbarre** [comment]
Thanks @evanw for putting this in 0.8.43; coincidentally I *just* noticed this very issue today while using Tailwind's ring utilities. Snowpack still uses esbuild 0.8.7, but nothing `resolution` can't fix temporarily in my `package.json`...
