### ISSUE TITLE
Is it possible to get the requires of a JS file from go?

### ISSUE THREAD

**Issue by joneshf** [evanw/esbuild#761]
I'm working on a project where I need to parse JS files to know what each one requires. I'm doing this from go. I figure the easiest thing here is to use a go package that is already parsing JS, and I know esbuild parses JS.

I know there's a public API for building and transforming JS, and I see that there's an internal package for parsing JavaScript, but I can't really access that from go easily. Is there any way to use esbuild from go to get the requires of a JS file? I didn't really see anything in the API for either build or transform which would help here, but I might have missed something.

Note: I'm not specifically asking you to open up your go API to allow this. More asking if it's already possible and I'm missing how to do it. If you want to open up the API, it would probably solve my problem and I would be grateful, but that's not the ask.

**Comment by evanw** [comment]
Couldn't you bundle the file with a plugin that marks every import as external to the bundle, but that accumulates the imports in a list?

```js
async function getImports(path) {
  const imports = [];
  await require('esbuild').build({
    entryPoints: [path],
    bundle: true,
    write: false,
    plugins: [{
      name: 'get-imports',
      setup(build) {
        build.onResolve({ filter: /.*/ }, args => {
          if (args.importer) {
            imports.push(args.path);
            return { path: args.path, external: true };
          }
        });
      },
    }],
  })
  return imports;
}
```

**Comment by joneshf** [comment]
Oh, interesting! It looks like the go API supports all that stuff as well through the `api.BuildOptions`: https://pkg.go.dev/github.com/evanw/esbuild/pkg/api#BuildOptions, and the documentation provides examples for how to write a plugin in go: https://esbuild.github.io/plugins/ ! That seems like it might work.

My only question is whether it's possible to only look at a single file without traversing down further into the transitive dependencies? Is that what `api.OnResolveResult.External` signifies? I kind of assume that from the explanation of `external` in the other part of the documentation: https://esbuild.github.io/api/#external, but not entirely sure.

**Comment by evanw** [comment]
Yes, that’s correct. That’s what external means.

**Comment by joneshf** [comment]
Great! This all works and solves my problem. Thanks so much for the help!
