### ISSUE TITLE
Dead code not eliminated

### ISSUE THREAD

**Issue by jaydenseric** [evanw/esbuild#765]
With this code in `in.js`:

```js
if (0 && false) console.error('abcde');
```

And this use of the CLI:

```
esbuild in.js --bundle --minify --outfile=out.js
```

`abcde` correctly does not appear in the `out.js` bundle.

But, unexpectedly, it does with this:

```js
if ((0 + 0) && false) console.error('abcde');
```

In real world modules, I have code like this:

```js
if (typeof process === 'object' && process.env.NODE_ENV !== 'production') {
  Foo.displayName = 'Foo';
  Foo.propTypes = {
    className: PropTypes.string,
    children: PropTypes.node.isRequired,
  };
}
```

The idea is, when `process.env.NODE_ENV` is `'production'`, the React component `displayName` and `propTypes` should be dead-code eliminated from the bundle. This works with webpack but not esbuild.

With this CLI usage:

```
esbuild in.js --bundle --minify define:process.env.NODE_ENV=\"production\" --outfile=out.js
```

The `process.env.NODE_ENV !== 'production'` is swapped with `false` in the `out.js` bundle, but the dead code is not eliminated.

**Comment by evanw** [comment]
Thanks for the report. I have a substitution rule for `false && anything` → `false` but it looks like I also need a rule for `noSideEffects && false` → `false`.

**Comment by jaydenseric** [comment]
Great, thanks for the speedy response :)

Even if the left side of the if condition has side effects, the if block could be eliminated.

For example this:

```js
if (foo() && false) {
  console.log('abcde');
}
```

Could become:

```js
foo();
```
