### ISSUE TITLE
support rootdir to control  load node_modules path

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#767]
It seems that esbuild load third party package from esbuild entryPoint path, which sometimes doesn't meets our needs, since we need to control esbuild can only load module from our custom project root, something like `rootdir` in rollup-plugin-node-resolve would be helpful.

**Comment by evanw** [comment]
You should be able to use an on-resolve plugin to control everything about esbuild's path resolution: https://esbuild.github.io/plugins/#resolve-callbacks. This should let you implement something like rollup-plugin-node-resolve yourself.

**Comment by hardfist** [comment]
yes, I currently use resolve callback to solve the problem, but it would be much slower than do that in esbuild self。

**Comment by evanw** [comment]
Some other alternatives:

* Use a plugin written in Go (no performance penalty vs. esbuild itself)
* Use symlinks for custom `node_modules` aliases (not sure how well this works on Windows)
* Use the newly-released `NODE_PATH` feature (documented in [the release notes](https://github.com/evanw/esbuild/blob/5b7b7e717f424b31149be8851f4d847016c18775/CHANGELOG.md#0843))

**Comment by hardfist** [comment]
it seems that NODE_PATH more like alias support, which doesn't support node resolution on NODE_PATH,
the following code will not load react from node_modules in app (app and tools are packages in a monorepo)
// mono/tools/build.js
```js
// mono/tools/build.js
const { build, buildSync } = require('esbuild');
const path = require('path');
buildSync({
  stdin: {
    contents: `import React from 'react'`,
    // resolveDir: path.resolve(__dirname, '../app'),
  },
  nodePaths: [path.resolve(__dirname, '../app')], // mono/app/index.js
  bundle: true,
  write: true,
  outfile: 'bundle.js',
});

```

**Comment by evanw** [comment]
Is this what you're looking for?

```js
  nodePaths: [
    path.resolve(__dirname, '../app'),
    path.resolve(__dirname, '../app', 'node_modules'),
  ],
```

**Comment by hardfist** [comment]
no, even node_modules is listed here, the recursive parent node_modules stills not listed here, which will not work in monorepo project.
```
node_modules
packages/
  app1
     node_modules
     src/
  app2
    node_modules
    src/
  appX
    node_modules
    src/
  shared-build-tools
package.json
```

all the app project are build using shared-build-tools(which wrap esbuild), but it seems that using resolveDir in stdin works for my scenario

**Comment by evanw** [comment]
> it seems that using resolveDir in stdin works for my scenario

Glad that works for you! I think that means this issue is resolved. Closing.
