### ISSUE TITLE
JavaScript doesn't have multidimensional arrays

### ISSUE THREAD

**Issue by piotrromanowski** [evanw/esbuild#78]
typescript compiles the following code
```
const value = values[item.index ?? -1] || 0;
```
into
```
var value = values[_e = item.index, (_e !== null && _e !== void 0 ? _e : -1)] || 0
```
which, when ran through esbuild spits out the following error

```
app.js:1:34: warning: Use of "," inside a property access is misleading because JavaScript doesn't have multidimensional arrays
var value = values[_e = item.index, (_e !== null && _e !== void 0 ? _e : -1)] || 0
                                  ^
```

but is bundled correctly with browserify

**Comment by evanw** [comment]
Thanks for calling this out. This was left over from some static analysis experiments. Like you pointed out, this can incorrectly be triggered by transpiled code. I should just remove this.

**Comment by piotrromanowski** [comment]
Wow that was fast! Thanks for the help!
