### ISSUE TITLE
carry hook info to plugin error message

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#780]
currently esbuild will carry plugin name to plugin error which is very helpful , but doesn't carry hook info with error
![image](https://user-images.githubusercontent.com/8898718/107472235-8d590a80-6ba9-11eb-9f60-da791ff762cc.png)

something like following would be more helpful for debugging plugin problem
```
 error: [memfs-plugin:onLoad] ENOENT: no such file or directory, open '/Users/admin/github/neo/packages/bundler/__tests__/fixtures/memfs/src/index.js'
```

**Comment by evanw** [comment]
The error message should now look like this:

<img width="608" src="https://user-images.githubusercontent.com/406394/107597757-71b52a80-6bd0-11eb-87a6-bf8c39d47a15.png">
