### ISSUE TITLE
--watch mode interacts poorly when stdout is not a TTY

### ISSUE THREAD

**Issue by kevinburkemeter** [evanw/esbuild#793]
I use a process manager to start both esbuild in --watch mode and nginx (which we use to terminate TLS for local development)

```
watch:
	goreman --set-ports=false --exit-on-error start
```

This reads the instructions out of a Procfile

```
alb: nginx -p ./fs -c etc/nginx/nginx.conf
watcher: ./node_modules/.bin/esbuild --watch --color=false src/index.jsx
```

Each time the three dots change, a new line is drawn to the output:

```
$ make watch
envdir envs/localdev goreman --set-ports=false --exit-on-error start
15:23:38     alb | nginx: [alert] could not open error log file: open() "/usr/local/var/log/nginx/error.log" failed (13: Permission denied)
15:23:38 watcher | ~/src/github.com/meterup/dashboard ~/src/github.com/meterup/dashboard
15:23:38 watcher | + ./node_modules/.bin/esbuild ./src/index.jsx --watch --color=false
▫▫▫ 3:39 watcher |
▪▫▫ 3:39 watcher |
▪▪▫ 3:40 watcher |
▪▪▪ 3:40 watcher |
▫▪▪ 3:41 watcher |
▫▫▪ 3:41 watcher |
```

It would be nice if the --watch tool could detect a TTY and avoid printing the bubbles if so, since they just clutter the screen.

Further, echoing the request in #751 it would be nice if it was possible to see somehow that esbuild was detecting changes and doing _something_, especially since the rebuild process is polling-driven and not file-event driven.

**Comment by evanw** [comment]
See also #742. You can use the [log level](https://esbuild.github.io/api/#log-level) option to disable this in the meantime.
