### ISSUE TITLE
Add multiple loaders example to docs

### ISSUE THREAD

**Issue by mwanji** [evanw/esbuild#809]
The loader documentation states:

> The transform API call just takes a single loader since it doesn't involve interacting with the file system

However, I can't find an example of passing several loaders on the CLI.

My apologies if this is explained somewhere else or if it's obvious to everyone, but it took me a long time and multiple attempts to figure out how to do it. 

Could an example such as the following be added?

`esbuild app.js --bundle --loader:.png=dataurl --loader:.svg=text`

(I'm also not sure where the docs are, but I'm happy to open a PR for this, if you want)

**Comment by evanw** [comment]
Sure. It has been added to the example: https://esbuild.github.io/api/#loader. The repo is here by the way: https://github.com/esbuild/esbuild.github.io.

**Comment by mwanji** [comment]
Thanks!
