### ISSUE TITLE
Can't import a stylesheet in plain TS

### ISSUE THREAD

**Issue by dragonDScript** [evanw/esbuild#815]
In a typescript file, when I try to import a stylesheet, it doesn't get applied.

**Comment by adamhp** [comment]
If you'd like assistance with that, you may want to provide more information. Some common pieces of information that are helpful:
1. Command you actually ran
2. Operation system
3. `esbuild` version
4. Contents of the TypeScript file and stylesheet

Or the gold standard: a GitHub repo with a reproducible example. At a minimum, the files and the steps you took to create the behavior.

**Comment by dragonDScript** [comment]
> If you'd like assistance with that, you may want to provide more information. Some common pieces of information that are helpful:
> 
> 1. Command you actually ran
> 2. Operating system
> 3. `esbuild` version
> 4. Contents of the TypeScript file and stylesheet
> 
> Or the gold standard: a GitHub repo with a reproducible example. At a minimum, the files and the steps you took to create the behavior.

Excuse me, I was busy at that time. While making a repro, I noticed all styles copied to a `main.css` file. Thank you!

P.d. this should be clarified in the css loader docs?

**Comment by adamhp** [comment]
It seems pretty clear already: https://esbuild.github.io/content-types/#css
>You can also import CSS from JavaScript. When you do this, esbuild will gather all CSS files referenced from a given entry point and bundle it into a sibling CSS output file next to the JavaScript output file for that JavaScript entry point. 

Also, the usage indicates:
```
esbuild --bundle app.css --outfile=out.css
```
