### ISSUE TITLE
Question: How to preserve some identifiers after minify

### ISSUE THREAD

**Issue by emrul** [evanw/esbuild#818]
Hi, I'd like to bundle a library for external use.  I have a bunch of methods and properties that should be public and should be preserved during minification.  Is there a way to achieve this (exclude some identifiers/symbols from being minified)?

**Comment by heyheyhello** [comment]
When you export an identifier it will preserve its name. Properties on objects also keep their names/keys. Should work as expected.

Or are you talking about saving the chosen minified variables (A,e,$,...etc) so they're consistent across rebuilds?

**Comment by evanw** [comment]
In addition to the above exceptions, there is also [the `--keep-names` option](https://esbuild.github.io/api/#keep-names) for the `.name` property on functions and classes. It's hard to answer this question without more information about your use case, and perhaps a code snippet.

**Comment by emrul** [comment]
Hi, thanks for the fast response, let me provide an example:
```js
export class SomeClass {
    publicMethod() {
        // ...
    }
    _internalMethod() {
        /// ...
    }
}

```

In this case, how can I mark `publicMethod()` to be preserved after minification?

**Comment by heyheyhello** [comment]
Have you tried? It should always be preserved :)
![Peek 2021-02-17 14-07](https://user-images.githubusercontent.com/44614862/108274372-a7569800-7129-11eb-8e79-7a22c30a73d4.gif)

**Comment by evanw** [comment]
> I have a bunch of methods and properties that should be public and should be preserved during minification.

I think this issue can be closed then. Minification always preserves the names of all methods and properties. No additional configuration is necessary.

**Comment by emrul** [comment]
Closing for now - I will put together a worked example.  My example was poor

**Comment by JoseLuis11** [comment]
> In addition to the above exceptions, there is also [the `--keep-names` option](https://esbuild.github.io/api/#keep-names) for the `.name` property on functions and classes. It's hard to answer this question without more information about your use case, and perhaps a code snippet.

Thanks! this helped me a lot
