### ISSUE TITLE
Preserve public names

### ISSUE THREAD

**Issue by scorredoira** [evanw/esbuild#82]
Is it possible to prevent renaming exported variables? 

I am not using modules, just regular javascript and I just need to minify a file and be able to call it from the outside. For example:

```
var S;
(function (S) {
	function foo() {
	}
	S.foo = foo;

})(S || (S = {}));
```

**Comment by evanw** [comment]
Did you mean to close this? I thought it was a good idea. This would make esbuild match the behavior of other minifiers such as terser. If people want the current behavior, they could either opt into it (like the `--toplevel` flag that terser has) or wrap everything in a closure.

**Comment by scorredoira** [comment]
Hi, I have been looking at the code and got to renamer.go -> minifyAllSymbols but couldn't find how to determine if a Symbol is public to skip it.

I thought that maybe the whole project is meant to be used with modules and so I closed this, but if it is possible then it would be great!

**Comment by scorredoira** [comment]
Tested with a large application (~200k lines) and worked fine.

Also generates smaller files than Google Closure Compiler:

```
source                    613.1 kB
esbuild                   259.4 kb     29 ms
Google Closure Compiler   285.8 kB   3728 ms
```

**Comment by mustafa0x** [comment]
Any chance we could get `--toplevel` to avoid wrapping everything in an iife?
