### ISSUE TITLE
[Question] Can esbuild / Go use esbuild / JS plugins?

### ISSUE THREAD

**Issue by zaydek** [evanw/esbuild#821]
If I write a program in esbuild / Go is there a way I can interop with the existing esbuild / JS plugin ecosystem?

Right now I’m concerned that I’d need to write esbuild / JS if I want to leverage esbuild / JS plugins. I know that esbuild / Go actually uses a `/.*/` regex (or something like that) to talk to Node plugins, so is there a way I -- a consumer of esbuild -- can do the same (or something to the same effect) to leverage esbuild / JS plugins in my esbuild / Go program?

If not I can always use esbuild / JS but I’d prefer to write as much Go as possible and only tap into Node when I absolutely need to.

(Tagging @heyheyhello because this is the same question as #688, just revisited.)

**Comment by evanw** [comment]
It's not a supported workflow. I have primarily designed esbuild to be used with JavaScript. Go was originally an implementation detail but was exposed as an API at the request of the community. However, I think the JavaScript APIs are most natural to use when JavaScript is the host and since that is the primary use case, I plan to keep the JavaScript API the way it currently is.

It's still possible to do this, but it's very manual. You can write a Go plugin that creates a node child process and then communicates with it. This is all esbuild is doing. I may at some point standardize a communication protocol for this (see https://github.com/evanw/esbuild/issues/111#issuecomment-720053290), but for now the communication protocol is up to you.

**Comment by zaydek** [comment]
Thank you. This is reasonable. What I’ll probably end up doing is serializing my Go state to disk and then have Node deserialize the state at startup and call esbuild. So a) Go is the parent process and and b) I can leverage JS / esbuild plugins in a supported workflow. Sort of like what you described but now esbuild is managed by Node.

> It's still possible to do this, but it's very manual. You can write a Go plugin that creates a node child process and then communicates with it. This is all esbuild is doing.

This is interesting. If I do this, do I need to create two plugins? One for `onResolve` and one for `onBuild`? I’d actually really like to try making a MVP with stdio / plaintext as the protocol. This would provide so much more flexibility for me.

**Comment by zaydek** [comment]
Oh wow. You create one plugin with both an onBuild and onLoad resolver:

```go
build.OnResolve(api.OnResolveOptions{Filter: ".*"}, func(args api.OnResolveArgs) (api.OnResolveResult, error) {
build.OnLoad(api.OnLoadOptions{Filter: ".*"}, func(args api.OnLoadArgs) (api.OnLoadResult, error) {
```

Very cool. OK I’ll review your source and see what I can figure out.

If you don’t mind don’t close this just yet. I want to see if I can make a MVP with stdio / plaintext as the protocol, and then will report my findings back here.

**Comment by zaydek** [comment]
@evanw I’m sorry to re-open this, but after experimenting for weeks of building on top of esbuild with Go vs. Node.js + TypeScript, Node.js is becoming too painful for me for what I’m trying to build.

So that brings me back to this question: Is there a minimal viable example for esbuild Go / esbuild JS plugin interop?

I know you’ve pointed me to [this comment](https://github.com/evanw/esbuild/issues/111#issuecomment-720053290) previously, and I’m aware that esbuild uses a simple enough binary protocol for stdin / stdout, but where I get lost in the implementation details because esbuild JS plugins have their own API / lifecycle functions such as `onLoad`, `onResolve`, etc. and I’m not sure if I’m supposed to manually manage those or not.

Given this isn’t a supported workflow, I totally get that you may not want to get into the details. But as someone who has heavily worked on esbuild, this is my biggest pain point. I absolutely love esbuild and what it enables developers, but I’m worried about the user story that esbuild tooling should be built exclusively on top of the Node.js ecosystem if such tooling needs to be able to leverage the JS plugin API.

**Comment by evanw** [comment]
I don't have the time to build a sample right now, but you could do this with a Go plugin that launches a node process and communicates with it. You don't need to use the same binary protocol that esbuild uses. You can use any protocol you want (e.g. stdin/stdout with protocol buffers, stdin/stdout with JSON, or some form of RPC over HTTP).

It would look something like this:

```go
var jsPlugin api.Plugin = api.Plugin{
  Name: "js-plugins",
  Setup: func(build api.PluginBuild) {
    // Setup:
    // - Create a node process
    // - In the node process, run "setup" on all desired plugins
    //   - Use a stub API that just records the API calls and their arguments
    // - This could potentially be done in parallel without blocking here

    build.OnResolve(api.OnResolveOptions{Filter: ".*"},
      func(ora api.OnResolveArgs) (api.OnResolveResult, error) {
        // Run resolvers:
        // - Unconditionally send this request over to node
        //   - Go though the recorded "onResolve" callbacks in the order they were registered
        //   - Run any plugins that match the filter regular expression and namespace
        //   - Skip plugins that return undefined, stop if a plugin reports an error
        // - Otherwise send the resolve result back and return it here if there was one
        // - You should forward the plugin's name to "PluginName" to proxy it
        return api.OnResolveResult{}, nil
      })

    build.OnLoad(api.OnLoadOptions{Filter: ".*"},
      func(ora api.OnLoadArgs) (api.OnLoadResult, error) {
        // Run loaders:
        // - Unconditionally send this request over to node
        //   - Go though the recorded "onLoad" callbacks in the order they were registered
        //   - Run any plugins that match the filter regular expression and namespace
        //   - Skip plugins that return undefined, stop if a plugin reports an error
        // - Otherwise send the load result back and return it here if there was one
        // - You should forward the plugin's name to "PluginName" to proxy it
        return api.OnLoadResult{}, nil
      })
  },
}
```

This is probably going to be a bit rough because it hasn't been done exactly like this before (node is the host process instead of the child process with esbuild's JavaScript API) but I don't see any reason why this wouldn't work. This is essentially what esbuild itself does in the JavaScript API implementation. There are additional smaller details to consider such as what to do about `pluginData` (esbuild keeps it in a JavaScript map and sends the keys of the map over to Go) but I think this should be enough to get something working.

**Comment by zaydek** [comment]
Thank you so much. I’ll study this closely and continue to parse your original source code.

If I can get a functioning demo to work, I’ll be sure to report back w/ a MVP repo you can point to and or others can leverage. And if I can’t figure this out, my fallback will be to use esbuild / node as a child process and communicate with Go over HTTP. Similar architectures but I really want to maintain Go code at the end of the day.

On another note, I wanted to say thank you, like really thank you. I’ve spent probably 1000+ hours in Figma and now 100+ hours w/ esbuild, and both have been life-changing technologies for me.

**Comment by zaydek** [comment]
Just wanted to quickly follow-up: I learned how to communicate over stdio (Go <-> node) using JSON using a long-lived child process. So Go is the parent process and node is the child process. Previously this didn’t work for me because I only knew how to one-shot run shell commands from Go, but yesterday, after you commented, I learned how to use `cmd.StdoutPipe()` so I can stream data from node.

I also started learning about binary protocols and I definitely would like to see your implementation standardized in the future. It’s very simple and obsoletes the need for most users to reach for GRPC, etc. first (which is even more daunting to me). JSON is fine for my use-case, but I like the idea of using a binary protocol like yours because it seems so elegant for IPC.

Btw I discovered how you implement plugins here: https://github.com/evanw/esbuild/blob/master/pkg/api/api_impl.go#L1248. I know this is only the overhead for Go but I hadn’t seen this previously, so it helps to understand how you’re actually orchestrating plugins.

I’m going to try to not reinvent the wheel here and instead stream node from Go. There’s still a few unanswered questions like:

- Can I use stdin as a pipe to node? Right now I only have one-way communication from node, but if I can pipe stdin to node then I have two-way.
- If I defer warnings and error-messages to esbuild (I like this because then I can use all of your current and future logging UI), will the logs still be in color? I don’t yet know if `isTTY` logic works for me in this way.
- Besides try-catch, if I use `process.on("uncaughtException", ...)` can I safely handle all runtime failures in node so Go knows what’s going on.

Anyway, I think I have enough of an idea how to defer to esbuild rather than reinvent plugin logic since I think there are going to be more subtleties than I can anticipate and the API will naturally change / improve over time. Sorry I had to bother you with this but hopefully you can point to https://github.com/evanw/esbuild/issues/821#issuecomment-797784638 in the future if someone finds themselves in the same circumstance.

Thank you for your work and time. Closing.
