### ISSUE TITLE
Site search?

### ISSUE THREAD

**Issue by Pomax** [evanw/esbuild#824]
There's a ton of information on the ESBuild site, but it's all hidden under "I hope you can guess where it lives" - would it be possible to add a search? (bonus points for just making that a search that, on first focus, Fetch()es a search index data and then doesn't actually do any active searching but consults the search tree to match n-grams to the page/section those occur in. That approach can be made a build step for the site CD, so the site can stay a normal static site)

**Comment by zaydek** [comment]
@Pomax Just a heads up the website source is here: https://github.com/esbuild/esbuild.github.io. Content is stored in a YAML / markdown hybrid format which he parses at build-time.

**Comment by evanw** [comment]
What were you searching for that you couldn't find? The site deliberately uses very few pages so that you can just use your browser's built-in search feature. The API documentation is all on one page: https://esbuild.github.io/api/.

**Comment by Pomax** [comment]
The detailed list of supported CLI options. There's nothing in the sidebar atm that is the obvious jumping-in point for them. (It's something quite distinct from an API, and is too detailed to expect under a Getting Started section)

**Comment by Haroenv** [comment]
If you're interested, we can definitely set up DocSearch on esbuild!

**Comment by evanw** [comment]
Closing because I don't think the documentation needs search for this. With #1002, all supported CLI options are now always expanded in the sidebar when you visit https://esbuild.github.io/api/.
