### ISSUE TITLE
Trouble loading fonts from Semantic UI

### ISSUE THREAD

**Issue by sholladay** [evanw/esbuild#826]
I use [Semantic UI React](https://react.semantic-ui.com/) as my component library. It's generally combined with `semantic-ui-css` to provide CSS styles. Unfortunately, something about the `@font-face` rules in `semantic-ui-css` trips up esbuild.

With an `index.jsx` entry point file of simply:

```js
import 'semantic-ui-css/semantic.css';
```

... I get errors when I run esbuild, such as:

```sh
❯ npx esbuild index.jsx --bundle --sourcemap --outdir=build
 > node_modules/semantic-ui-css/semantic.css: error: Could not resolve "./themes/default/assets/fonts/icons.eot?#iefix"
    7672 │   src: url("./themes/default/assets/fonts/icons.eot?#iefix") format('embedded-opentype'), url("./themes/default/assets/...
         ╵            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 > node_modules/semantic-ui-css/semantic.css: error: Could not resolve "./themes/default/assets/fonts/icons.svg#icons"
    7672 │ ...efault/assets/fonts/icons.ttf") format('truetype'), url("./themes/default/assets/fonts/icons.svg#icons") format('svg');
         ╵                                                            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 > node_modules/semantic-ui-css/semantic.css: error: Could not resolve "./themes/default/assets/fonts/outline-icons.eot?#iefix"
    12951 │   src: url("./themes/default/assets/fonts/outline-icons.eot?#iefix") format('embedded-opentype'), url("./themes/defaul...
          ╵            ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I'm not sure what the best approach is for dealing with these assets, but the paths are correct and the files do exist on disk. It works with my current Rollup setup. Do I need to specify some kind of loader? It would be nice if esbuild could give a more actinable error message.

esbuild v0.8.46
Node v15.7.0
semantic-ui-css v2.4.1

**Comment by evanw** [comment]
This happens because the file does not have the `.eot?#iefix` extension. This has come up once before too: #743. I suppose it's worth adding the workaround into esbuild itself since it looks like both Parcel and Webpack special-case these kinds of paths.

**Comment by sholladay** [comment]
@evanw Many thanks for the fast response and fix. I've confirmed that the fix works. I also love the way you solved it. I haven't quite gotten my build working yet, but feeling really good about esbuild. :)

Is there a succinct way to configure a loader for multiple file types? If I understand correctly, I think I need to use the `dataurl` loader on all of these images, fonts, and SVGs that are being loaded by `url()` in Semantic's CSS file. That's making my bundle command pretty unwieldy.

```sh
npx esbuild lib/index.jsx --bundle --sourcemap \
  --outdir=build \
  --define:process.env.NODE_ENV=\"production\" \
  --loader:.png=dataurl \
  --loader:.woff=dataurl \
  --loader:.woff2=dataurl \
  --loader:.eot=dataurl \
  --loader:.ttf=dataurl \
  --loader:.svg=dataurl
```

**Comment by evanw** [comment]
> Is there a succinct way to configure a loader for multiple file types? 

No, there isn't really. Each file type is explicit. You could write a plugin I suppose but the plugin code would be bigger than just using the loader commands.

> That's making my bundle command pretty unwieldy.

The CLI is only really intended for simple uses of esbuild. More complex uses should probably use the API instead:

```js
require('esbuild').build({
  entryPoints: ['lib/index.jsx'],
  bundle: true,
  sourcemap: true,
  outdir: 'build',
  define: {
    'process.env.NODE_ENV': '"production"',
  },
  loader: {
    '.png': 'dataurl',
    '.woff': 'dataurl',
    '.woff2': 'dataurl',
    '.eot': 'dataurl',
    '.ttf': 'dataurl',
    '.svg': 'dataurl',
  },
})
```

This is about equivalent verbosity of course, but having it in a separate file and being able to use real programming language syntax makes it less unwieldy IMO. You could also then use code to construct the `loader` object from an array of file extensions, for example.

**Comment by sholladay** [comment]
For me, the main selling point of esbuild is the simple DX and good defaults (as opposed to performance). I haven't needed any plugins yet and for the most part everything "just works". The CLI is an important part of the simple DX because it makes it easy to switch between modes (e.g. turn `watch` or `minify` mode on/off) during development.

I wonder if you would be willing to support a config file so that we could put some options in a file but still use the CLI?

Rollup supports this via the `--config` flag, which enables loading a config file (`rollup.config.js` by default).

For example, my Rollup config file looks like this:

```js
import babel from '@rollup/plugin-babel';
import commonjs from '@rollup/plugin-commonjs';
import resolve from '@rollup/plugin-node-resolve';
import replace from '@rollup/plugin-replace';
import { terser } from 'rollup-plugin-terser';
import postcss from 'rollup-plugin-postcss';
import json from '@rollup/plugin-json';

// `npm run build` -> `isDev` is false
// `npm run dev` -> `isDev` is true
const isDev = Boolean(process.env.ROLLUP_WATCH);

export default {
    input  : 'lib/index.jsx',
    output : {
        file      : 'build/app.js',
        format    : 'esm',
        sourcemap : true
    },
    plugins : [
        resolve({
            extensions : ['.js', '.json', '.jsx'],
            browser    : true
        }),
        commonjs({ include : 'node_modules/**' }),
        postcss({
            modules : {
                globalModulePaths : [
                    /node_modules\/react-credit-cards\/es\/styles-compiled.css/u,
                    /node_modules\/react-image-crop\/dist\/ReactCrop.css/u,
                    /node_modules\/semantic-ui-css\/components\/.*\.css/u
                ]
            }
        }),
        // This is needed to fix React assuming the browser has `process`
        replace({ 'process.env.NODE_ENV' : JSON.stringify(isDev ? 'development' : 'production') }),
        json({ preferConst : true }),
        babel({
            babelHelpers : 'bundled',
            exclude      : 'node_modules/**'
        }),
        !isDev && terser()
    ]
};
```

The beauty of this is that it is dynamic like the API but it preserves the convenience of the CLI. It also simplifies npm scripts, mine are just:

```json
"scripts": {
    "build": "rollup --config",
    "dev": "rollup --config --watch"
},
```

If it weren't for the lack of a default loader for some of those file types, I wouldn't even feel the need for a config file, I'd probably just keep everything in npm scripts, which would be even more awesome.

**Comment by evanw** [comment]
> I wonder if you would be willing to support a config file so that we could put some options in a file but still use the CLI?

No, I am not willing to do this. I think the API is a better design than a config file. Using the API is about the same amount of code as using a config file but it's much more flexible because it doesn't take away your abstraction capabilities. I went into this in more detail in #536 if you're interested.

> The CLI is an important part of the simple DX because it makes it easy to switch between modes (e.g. turn `watch` or `minify` mode on/off) during development.

The nice thing about the API vs. a config file is _you_ are in control, not esbuild. Doing something like that is trivial with `minify: process.argv.includes('--minify')` if that's what you want.

**Comment by sholladay** [comment]
Alright, well thank you for considering. I'll make a wrapper CLI and publish it to npm in case others find it useful. FWIW, I don't see these things as mutually exclusive. An API is great for complex use cases, but it's never going to compete with a CLI in terms of ergonomics, which I'm sure is why esbuild has a CLI to begin with.

**Comment by izatop** [comment]
@evanw what's about the package resolution hack like this `~@fortawesome/fontawesome-free/...`? This method uses in webpack font loaders (and maybe in some other build tools). I use this hack too in my build system on top of esbuld.
I want to preserve hashes and queries in the css url function when my plugin resolves package resources in `node_modules`.

**Comment by AStoker** [comment]
@izatop , you ever figure that one out? Just started an Angular 16 upgrade with experimental ESBuild support, and it's failing on font files from fortawesome.

**Comment by izatop** [comment]
@AStoker I solve that case by plugin which resolves paths starting at `~@` in sass files.

**Comment by AStoker** [comment]
Hmmm, yeah, I don't think that's the case that's going on with me (the tilde is actually deprecated with latest sass). I'll keep digging, but thanks for the reply!
