### ISSUE TITLE
React Project With Custom JSX Factory

### ISSUE THREAD

**Issue by n1xx1** [evanw/esbuild#832]
I'm trying to get the css prop of emotion to work correctly, so as far I understood I can use the `inject` option and then specify the `jsxFactory` and `jsxFragment`. 

My config looks like this:

```js
require("esbuild")
  .build({
    // ...
    jsxFactory: "__jsx",
    jsxFragment: "__Fragment",
    inject: [path.join(__dirname, "./react-shim.js")],
    // ...
  )}
```

And the react-shim.js is this:
```js
const {
  jsx: __jsx,
  Fragment: __Fragment,
} = require("@emotion/react/jsx-runtime");
```
However the in generated code the import names get renamed:
```js
  // scripts/react-shim.js
  var {
    jsx: __jsx2,
    Fragment: __Fragment
  } = require_emotion_react_jsx_runtime_browser_cjs();
  // ....
  var MotionCard = import_react12.memo(import_react12.forwardRef(function MotionCard2({card, onDragEnd}, ref) {
    return /* @__PURE__ */ __jsx(motion.div, {
      css: {width: "10%"},
      ref,
  // ...
```

Why are the names changed? How can I make it work?

Thank you and great work with the project!

**Comment by evanw** [comment]
The inject feature is just a way to automatically generate an import. When you say `inject: "./react-shim.js"` you are telling esbuild to generate an import that looks like this in every file:

```js
import {/* ...all exports of react-shim.js... */} from "./react-shim.js"
```

However, this file doesn't have any exports, only local variables:

```js
const {
  jsx: __jsx,
  Fragment: __Fragment,
} = require("@emotion/react/jsx-runtime");
```

You can't import anything from a file that doesn't have any exports. Instead you need to do something like this:

```js
export {
  jsx as __jsx,
  Fragment as __Fragment,
} from "@emotion/react/jsx-runtime";
```

The names of your local variables are being changed to avoid name collisions with references to globals in another file. Unexported local variables are not supposed to be accessible outside of that file.

**Comment by hardfist** [comment]
@n1xx1  I build site with emotion using esbuild, you can reference it here, https://github.com/hardfist/neo-tools/blob/main/packages/playground/scripts/build.ts#L25

**Comment by cosmith** [comment]
Thanks @hardfist, for those looking to get emotion working with esbuild, the relevant config is this:
```js
jsxFactory: "jsx",
inject: [path.join(__dirname, "react-shim.js")],
```
and in `react-shim.js`
```js
import {jsx} from "@emotion/react";
export {jsx};
```

And thanks @evanw ! Build time went from 2 minutes to 1.9s 😅

**Comment by zaydek** [comment]
@hardfist Can I use something like your technique to transform React files so I don’t need to do `import React from "react"`? I think React uses a Babel transform API to do this.

**Comment by evanw** [comment]
> Can I use something like your technique to transform React files so I don’t need to do `import React from "react"`?

This might be relevant: https://esbuild.github.io/content-types/#auto-import-for-jsx

**Comment by zaydek** [comment]
@evanw You’re the best. Thank you so much.

**Comment by hardfist** [comment]
> @hardfist Can I use something like your technique to transform React files so I don’t need to do `import React from "react"`? I think React uses a Babel transform API to do this.

it already does

**Comment by evanw** [comment]
I'm going to close this because I believe that the original question has been answered.

**Comment by n1xx1** [comment]
Sorry about this issue. For some reason I thought I closed it when I figured it out. I don't think it's even necessary to change the documentation, it was my mistake to completely miss the fact you have to export stuff in the injected shim to make them available. Thanks!

**Comment by kelly-tock** [comment]
> Thanks @hardfist, for those looking to get emotion working with esbuild, the relevant config is this:
> 
> ```js
> jsxFactory: "jsx",
> inject: [path.join(__dirname, "react-shim.js")],
> ```
> 
> and in `react-shim.js`
> 
> ```js
> import {jsx} from "@emotion/react";
> export {jsx};
> ```
> 
> And thanks @evanw ! Build time went from 2 minutes to 1.9s 😅

i'm trying to get esbuild-jest working, and will also ask on that repo as well. 

with this setup still getting:

```js
Test suite failed to run

    ReferenceError: jsx is not defined
```

jest config:
```json
transform: {
    '^.+\\.(js|jsx|ts|tsx)$': [
      'esbuild-jest',
      {
        jsxFactory: 'jsx',
        jsxFragment: 'Fragment',
        inject: [path.join(__dirname, 'react-shim.js')],
      },
    ],
  },
```


```js
import { Fragment } from 'react';
import { jsx } from '@emotion/react';

export { jsx, Fragment };
```

any ideas?
