### ISSUE TITLE
Add option to disable `.min.js` suffix for minified files, using `outdir`

### ISSUE THREAD

**Issue by fnky** [evanw/esbuild#84]
The current behavior when using `outdir` with `minify` is to add a `.min.js` extension to the output file name for each entrypoint. This is inconvenient in cases where you want to point to a specific file (e.g. from a HTML file), depending on the environment that you build for (production/development).

One workaround is to add multiple build configs for each entry point, with different `outfile` so that each entry point is built independently. Another way would be to rename the file after compilation. While both of these workarounds works in theory, it makes configuring builds more complicated.

#### Proposal

A possible solution could be to add a flag (e.g. `minifySuffix`) that allows you to toggle this behavior. For example:

```js
{
  entryPoints: ['./src/a.ts', './src/b.ts']
  outdir: './dist',
  minify: true,
  // Disable .min.js suffix in file name for minified files.
  minifySuffix: false
}
```

Would output the following:

```
root/
  dist/
    a.js
    b.js
  src/
    a.ts
    b.ts
```

#### Default behavior

In order for it to consistent with other `minify*` flags, passed through the command line, it would likely need to be `false` by default so that you can enable it by passing `--minifySuffix`.

The downside is that it would be a breaking change to the current default behavior.

**Comment by evanw** [comment]
Yeah I don't like this behavior either. I did this because it lets you do `esbuild --minify foo.js` to write to `foo.min.js` without needing to add `--outfile=foo.min.js` but you're right that it doesn't make sense in this case. I think it's fine to do a breaking change given that this project is still early, so I think I'll just do a breaking change for this.

**Comment by alex-drocks** [comment]
How do you re-enable this option? I actually would like to output .min.js on my files and .min.css

**Comment by geoffharcourt** [comment]
@alex-drocks right now we do this with `entryNames`, but it requires the config file instead of a CLI option.

**Comment by alex-drocks** [comment]
> @alex-drocks right now we do this with `entryNames`, but it requires the config file instead of a CLI option.

Thank you very much I'll read more on that option!

**Comment by evanw** [comment]
> I actually would like to output .min.js on my files

Have you tried `--out-extension:.js=.min.js`? Docs are here: https://esbuild.github.io/api/#out-extension

**Comment by alex-drocks** [comment]
> > I actually would like to output .min.js on my files
> 
> Have you tried `--out-extension:.js=.min.js`? Docs are here: https://esbuild.github.io/api/#out-extension

Not yet, I'll do that. Thank you so much guys. I was lost in docs. (not very used to handle build tools without a higher level tool) ESBuild is awesome.

**Comment by alex-drocks** [comment]
it worked like this: 

```Javascript
//currently unused

const {build} = require('esbuild');
const postCssPlugin = require("esbuild-plugin-postcss2").default;
const autoprefixer = require("autoprefixer");


build({
  entryPoints: ['src/produits/produits.js', 'src/comptoirs/comptoirs.js'],
  outExtension: {'.js': '.min.js', '.css': '.min.css'},
  outdir: 'build',
  target: "es6",
  format: "iife",
  bundle: true,
  minify: true,
  plugins: [
    postCssPlugin({
      plugins: [autoprefixer()]
    })
  ],
})
  .catch(() => process.exit(1));
```
