### ISSUE TITLE
esbuild does not tree shake known globals

### ISSUE THREAD

**Issue by moos** [evanw/esbuild#842]
esbuild: 
```
$ echo "class A extends HTMLElement {}" | npx esbuild --bundle --format=esm
// <stdin>
var A = class extends HTMLElement {
};
```
Rollup:
```
$ echo "class A extends HTMLElement {}" | npx rollup
- → stdout...
(!) Generated an empty chunk
-
```
For unknown globals (e.g., "class A extends Foo {}"), both esbuild and rollup keep the definition.
 
It would be great if esbuild could also filter for [known globals](https://github.com/rollup/rollup/blob/master/src/ast/nodes/shared/knownGlobals.ts).   

Related: 
- #756 (issue is with HTMLElement and not with `lit-element`)
- [rollup/#3115](https://github.com/rollup/rollup/issues/3115)
- [shoelace-style/#180](https://github.com/shoelace-style/shoelace/issues/180#issuecomment-781680509)

**Comment by evanw** [comment]
There is limited support for this already in esbuild here:

https://github.com/evanw/esbuild/blob/f50aa9a1a71a7db80adb6ec34896a98e32ed927a/internal/config/globals.go#L15-L24

This does not yet encode DOM globals, however.

**Comment by moos** [comment]
Ah good to know.  I'm not a Go programmer but willing to give it a "go" if you want some help.  Let me know.

**Comment by evanw** [comment]
It's ok, this is easy for me. I've got this one.
