### ISSUE TITLE
[Bug] Unreachable code not removed after If/Else

### ISSUE THREAD

**Issue by tobymao** [evanw/esbuild#844]
```js
var test = function(x) { if (x == 1 ) {
    return "a"
  } else {
    return "b"
  }

  return null;
}

test(1)
```

esbuild a.js --minify
```js
var test=function(r){if(r==1)return"a";return"b";return null};test(1);
```

esbuild a.js --minify --bundle
```js
(()=>{var e=function(r){if(r==1)return"a";return"b";return null};e(1);})();
```

In both cases, --minify should remove the final return null because it is unreachable.

**Comment by evanw** [comment]
Huh, yeah that looks like a bug. Seems like it'll be easy to fix.

**Comment by evanw** [comment]
The next release will generate this code:

```js
var test=function(r){return r==1?"a":"b"};test(1);
```

**Comment by tobymao** [comment]
Wow amazingly quick fix. Will this work without bundle as well? I don't use --bundle in my app.

**Comment by evanw** [comment]
Yeah this shouldn’t depend on the bundle setting.
