### ISSUE TITLE
Unexpected "(" before object pattern (introduced in v0.8.48)

### ISSUE THREAD

**Issue by ebeloded** [evanw/esbuild#846]
The recent version of esbuild (v0.8.48) started to fail when bundling TS code containing this function:

```ts
export function mapDoc<T>(doc: firebase.firestore.DocumentSnapshot): T | null {
  return doc.exists ? (({ id: doc.id, ...doc.data() } as unknown) as T) : null
} 
```

Here is the message returned by esbuild
```
errors: [
    {
      detail: undefined,
      location: {
        ...
        lineText: '  return doc.exists ? (({ id: doc.id, ...doc.data() } as unknown) as T) : null',
        ...
      },
      notes: [],
      text: 'Unexpected "(" before object pattern'
    }
  ],
```

This is recent - v0.8.47 works as expected

**Comment by evanw** [comment]
Sorry about that. These are errors from speculative parsing that shouldn't be leaking into the final log when speculative parsing fails. Will fix.
