### ISSUE TITLE
[Question] About Loaders [ js vs jsx, ts vs tsx ]

### ISSUE THREAD

**Issue by aelbore** [evanw/esbuild#848]
if i have javascript ".js" file and set the loader to ".jsx" is there any difference? 
some other other code with react has ".js" extensions which contains jsx, and some ".js" files has no jsx code

**Comment by heyheyhello** [comment]
If you have any JSX in any files, regardless of the file extension, you'll need to use the JSX loader (or TSX if you have TypeScript that has JSX)

**Comment by evanw** [comment]
From [the documentation](https://esbuild.github.io/content-types/#typescript):

> The `tsx` loader is _not_ a superset of the `ts` loader. They are two different partially-incompatible syntaxes. For example, the character sequence `<a>1</a>/g` parses as `<a>(1 < (/a>/g))` with the `ts` loader and `(<a>1</a>) / g` with the `tsx` loader.
>
> The most common issue this causes is not being able to use generic type parameters on arrow function expressions such as `<T>() => {}` with the `tsx` loader. This is intentional, and matches the behavior of the official TypeScript compiler. That space in the `tsx` grammar is reserved for JSX elements.

**Comment by aelbore** [comment]
@evanw @heyheyhello thanks for the info 👍
