### ISSUE TITLE
[best practice] workbox integration

### ISSUE THREAD

**Issue by Stanzilla** [evanw/esbuild#849]
Hey there, I'm currently looking for some advice or maybe a snippet for a best practice integration or Google's workbox and esbuild. I found a few examples that involve running the workbox cli via npx but I'm wondering if there is something better.

Thanks!

**Comment by evanw** [comment]
I don't know what workbox is so I probably can't be of much help, sorry. I'm not aware of anything like this.

**Comment by Stanzilla** [comment]
Workbox is Google's service worker framework: https://developers.google.com/web/tools/workbox |https://github.com/GoogleChrome/workbox they offer plugins for Rollup and Webpack

**Comment by evanw** [comment]
I think this sounds like a question for the Google workbox then. I did a search for you and found this: https://github.com/GoogleChrome/workbox/issues/2588. Hope that's helpful.

I'm going to close this issue because it's not an issue with esbuild.
