### ISSUE TITLE
Parser bug: top-level async and generator functions conflict with nested `var` declarations

### ISSUE THREAD

**Issue by bakkot** [evanw/esbuild#857]
Another bug from fuzzing:
```js
async function x() {}
{
  var x;
}
```
is improperly rejected. The same happens for `function*` and `async function*`, but not a plain `function(){}`, and not if the `var x` is at the top level of the program or function rather than nested inside of a block or loop header.

This also applies inside functions, as in

```js
function outer() {
  async function x() {}
  {
    var x;
  }
}
```

Note that this would be the correct behavior at a higher level of nesting. It's only at the top level of programs and functions where function declarations are treated like `var` declarations for the purposes of determining conflicts.

The relevant part of the spec is [TopLevelLexicallyDeclaredNames](https://tc39.es/ecma262/#sec-static-semantics-toplevellexicallydeclarednames), which has a special case for [HoistableDeclaration](https://tc39.es/ecma262/#prod-HoistableDeclaration), which includes all four kinds of function declaration, not just non-async non-generator functions.

**Comment by evanw** [comment]
Thanks for the report!
