### ISSUE TITLE
[Question] Customize serverdir request path?

### ISSUE THREAD

**Issue by zaydek** [evanw/esbuild#858]
_I know this is something you likely don’t want to support but I want to ask still. Thank you in advance._

For static web servers, files generally require an `.html` suffix. But is there a way I can map `/` maps to `/index.html` and `/page` to `/page.html` myself? For example, is there a way I can alter the incoming request to make the web server handle more like Netlify and other common providers?

I know this is likely not something you want to support because of existing constraints like mirroring source files for features like ES Modules, but it would be a very useful feature still.

My use case is like this:

```js
const esbuild = require("esbuild")
const p = require("path")

// convertToFilesystemPath converts a browser path to a filesystem path.
function convertToFilesystemPath(path) {
  // "/" -> "/index"
  let path2 = path
  if (path2.endsWith("/")) {
    path2 += "index"
  }
  // "/index" -> "/index.html"
  if (p.extname(path2) === "") {
    path2 += ".html"
  }
  return path2
}

async function run() {
  await esbuild.serve({
    servedir: "www",
    onRequest: args => {
      args.path = convertToFilesystemPath(args.path) // Here
      // ...
    },
  })
}

run()
```

(Tried this, doesn’t work)

If this is not something you want to support, is there a way I can still leverage esbuild to manage the web server but I proxy it somehow? Nothing complicated, just from the same machine for local development.

**Comment by evanw** [comment]
> I know this is something you likely don’t want to support but I want to ask still. Thank you in advance.

You're right, this is something that I don't think esbuild should have built in :)

> If this is not something you want to support, is there a way I can still leverage esbuild to manage the web server but I proxy it somehow? Nothing complicated, just from the same machine for local development.

I think this should be pretty trivial. I wrote up some code for someone else with a similar request here: https://github.com/evanw/esbuild/pull/843#issuecomment-781908280. If you try it out and it works for you, I can put something like that in the docs.

**Comment by zaydek** [comment]
Thanks Evan. I didn’t see that PR but I agree that it does feel too specific. :)

> This doesn't work because the callback is run after the request has been served. It's only intended for logging purposes.

Yeah, I figured anything I do with the args is idempotent. That being said, it is so valuable to have quick access to that metadata. I was able to very quickly create this CLI thanks to your work:

<img width="876" alt="Screen Shot 2021-02-21 at 12 37 05 PM" src="https://user-images.githubusercontent.com/58870766/108614861-94053e80-7441-11eb-8f7d-b0664bb4d058.png">

> I think this should be pretty trivial. I wrote up some code for someone else with a similar request here: #843 (comment). That should be a good starting point. If a proxy approach like this works for you, I can put something like that in the docs.

I had something like this in mind but I didn’t know how to articulate it. This looks like it could work! I’ll have to play with it in the context of an esbuild setup, but I can’t imagine why it wouldn’t work (I just have to pick an unused port for esbuild servedir or pick one at random?).

I’d love to see an example detailing this in the docs. This is a really helpful quality of life example because it helps demonstrate how esbuild is not just a linker for the web but can also help you faithfully simulate a deployed HTTP server / hosting provider. I could always ship my own naive node HTTP server (for the project I’m working on) but then it probably wouldn’t address caching / cache eviction, and if I include a Go HTTP server than I have to worry about cross-platform binaries + the caching problem.

**Comment by zaydek** [comment]
Free free to close this at your disclosure, before or after your example is documented in the docs. Thank you again.

**Comment by evanw** [comment]
The documentation is now live: https://esbuild.github.io/api/#customizing-server-behavior. Closing.

**Comment by zaydek** [comment]
Hahaha I think were both typing at the same time. I just finished this. Feel free to use it or not at all. Your documentation is great but it would be nice to demonstrate a MVP SPA / SSG.

---

I wanted to follow-up with a repro to help you articulate proxying in the docs. I took it as an opportunity to more deeply understand how your code works and demonstrate MVP SPA and SSG implementations so users can leverage this in any direction they need without putting further constraints on esbuild.

Repro repo here: https://github.com/zaydek/esbuild-proxy-serve.

Here’s the important file. There’s also `www` to demonstrate `spaify` and `ssgify` respectively work.

```js
const esbuild = require("esbuild")
const http = require("http")
const path = require("path")

// The port the user sees and the port esbuild uses.
const userPort = 3000
const esbuildPort = userPort + 10

// spaify converts a URL for SPA-mode.
function spaify(url) {
  const parts = url.split(url, ":" + userPort)
  return parts[0]
}

// ssgify converts a URL for SSG-mode.
function ssgify(url) {
  if (url.endsWith("/")) return url + "index.html"
  if (path.extname(url) === "") return url + ".html"
  return url
}

// The proxy server.
const proxySrv = http.createServer((req, res) => {
  // The proxy request.
  const proxyReq = http.request({ ...req, path: spaify(req.url), port: esbuildPort }, proxyRes => {
    // The proxy response.
    if (proxyRes.statusCode === 404) {
      res.writeHead(200, { "Content-Type": "text/html" })
      res.end("<h1>404 Page Not Found</h1>")
    } else {
      res.writeHead(proxyRes.statusCode, proxyRes.headers)
      proxyRes.pipe(res, { end: true })
    }
  })
  req.pipe(proxyReq, { end: true })
})
proxySrv.listen(userPort)

esbuild.serve({
  port: esbuildPort,
  servedir: "www",
  onRequest: args => {
    console.log({ args })
  },
})
```

I think the key aspects to touch are this:

- SPA mode generally means route paths to `/` (which esbuild handles (or Go indirectly?) handles as `/index.html`
- SSG mode generally means means map browser paths to filesystem paths (usually just means `/` -> `/index.html` and `/hello` -> `/hello.html`)

Proxying requests is a simple idea; there are two ports, one the user sees and one esbuild uses internally for `servedir`. When the user creates a request in the browser, the server fires a proxied request which hits the esbuild server. The proxy step allows esbuild consumers to transform `req.url` based on their needs. All custom logic / middleware can be implemented in the proxying step; SPA-mode, SSG-mode, and or custom error handling / forwarding to /404.html.
