### ISSUE TITLE
Support entry similar to "react-dom/server"

### ISSUE THREAD

**Issue by pandagood** [evanw/esbuild#860]
I tried the following build, but it threw an error:
```js
const buildResult = await service.build({
  target: 'esnext',
  format: 'esm',
  entryPoints:[
    "react-dom/server",
    "@material-ui/core/Button"
  ],
  ...
})
```
The error:
```js
Cannot find module '/Volumes/book/esbuild-react/node_modules/react-dom/server'
```

**Comment by evanw** [comment]
Doing that is supported:

```sh
$ echo '{}' > package.json
$ npm i esbuild react-dom
$ node_modules/.bin/esbuild --bundle react-dom/server
```

It's possible you have the wrong working directory. You could try the https://esbuild.github.io/api/#working-directory setting, which is what esbuild uses to resolve entry point paths against.

> The error:
> ```js
> Cannot find module '/Volumes/book/esbuild-react/node_modules/react-dom/server'
> ```

An error with this text is not ever thrown with esbuild. I assume this means you have some other wrapper in your code around esbuild that is throwing this error. You will have to debug this yourself.

**Comment by pandagood** [comment]
> It's possible you have the wrong working directory.      

Thanks, It worked.
