### ISSUE TITLE
Can not erasure types

### ISSUE THREAD

**Issue by CHOYSEN** [evanw/esbuild#863]
## Reproduction
https://github.com/CHOYSEN/esbuild-types-issue

`b.ts` export interface `Car`
`a.ts` import `Car` then export it, should it be erasure?
It works as my expect when `a.ts` doesn't export `Car`

**Comment by CHOYSEN** [comment]
The original issue https://github.com/vitejs/vite/issues/2117

**Comment by evanw** [comment]
From [the documentation](https://esbuild.github.io/content-types/#typescript):

> You should probably enable the [`isolatedModules`](https://www.typescriptlang.org/tsconfig#isolatedModules) TypeScript configuration option if you use TypeScript with esbuild. This prevents you from using features which could cause mis-compilation in environments like esbuild where each file is compiled independently without tracing type references across files. For example, it prevents you from re-exporting types from another module using <code>export <wbr>{T} <wbr>from <wbr>'./types'</code> (you need to use <code>export <wbr>type <wbr>{T} <wbr>from <wbr>'./types'</code> instead).

**Comment by CHOYSEN** [comment]
Thanks, get it!
