### ISSUE TITLE
A way to serve to 0.0.0.0?

### ISSUE THREAD

**Issue by romanoff** [evanw/esbuild#866]
It could be useful during development together with using Tailscale for example. Otherwise static resources are returned from localhost, but are not returned from public ip address

**Comment by evanw** [comment]
From [the documentation](https://esbuild.github.io/api/#serve-arguments):

> * `host`
>
>     The web server is only available on the internal loopback address by default. This is deliberate behavior for security reasons, since the local network environment may not be trusted. However, it can be useful to run the web server on a different address when developing with esbuild inside of a virtual machine/docker container, or to request development assets from a remote testing device on the same network at a different IP address. To do that you need to specify the host here. You can set the host on the command line by using `--serve=192.168.0.1:8000` instead of just `--serve`.
