### ISSUE TITLE
Esbuild fails to build TypeScript code for a VSCode extension

### ISSUE THREAD

**Issue by ashleydavis** [evanw/esbuild#867]
Esbuild looks awesome, thanks so much for your work on it.

I was hoping to use it to bundle my VSCode extension which is built on TypeScript.

I've installed the latest version:  0.8.50

This is my project: https://github.com/ashleydavis/taskboard-vscode-extension

I run esbuild lkes this:

```bash
npx esbuild src\extension.ts --bundle --platform=node --outfile=out\extension.js
````

Here is the output:

```bash
 > src/extension.ts: warning: Calling "unified" will crash at run-time because it's an import namespace object, not a function (make sure to enable TypeScript's "esModuleInterop" setting)
    14 │ const fromMarkdownProcessor = unified().use(markdown);
       ╵                               ~~~~~~~
   src/extension.ts: note: Consider changing "unified" to a default import instead
     8 │ import * as unified from "unified";
       │        ~~~~~~~~~~~~
       ╵        unified

 > src/extension.ts: warning: Calling "unified" will crash at run-time because it's an import namespace object, not a function (make sure to enable TypeScript's "esModuleInterop" setting)
    28 │ const toMarkdownProcessor = unified().use(stringify, markdownOptions);
       ╵                             ~~~~~~~
   src/extension.ts: note: Consider changing "unified" to a default import instead
     8 │ import * as unified from "unified";
       │        ~~~~~~~~~~~~
       ╵        unified

 > src/extension.ts: error: Could not resolve "vscode" (mark it as external to exclude it from the bundle)
    1 │ import * as vscode from 'vscode';
      ╵                         ~~~~~~~~
```

There are a couple of warnings and an error.

I can build using the TypeScript compiler and there are no errors:
```bash
npx  tsc
```

Is there something I should configure to make esbuild work or is this a genuine problem bundling VSCode extensions?

**Comment by heyheyhello** [comment]
If you check the typings for that package you'll see it's a namespace _and_ and function, which is interesting. Not sure if that requires `esModuleInterop`, worth a shot.

Otherwise, try `import unified = require (...)` as shown here:
https://www.github.com/unifiedjs/unified/tree/main/types%2Fts4.0%2Funified-tests.ts

**Comment by ashleydavis** [comment]
Thanks for your quick response.

The main problem is trying to import "vscode".

I've just implemented my bundle with webpack using the instructions here: https://code.visualstudio.com/api/working-with-extensions/bundling-extension

It says that the "vscode" module must be excluded:

![image](https://user-images.githubusercontent.com/625126/108641284-97a4ce00-74f2-11eb-8971-9fa0138c1f3c.png)

It looks like you can do this in esbuild as well. So I'm going to try that now.

**Comment by ashleydavis** [comment]
Ok I have the answer.

The key to making this work with esbuild is to use the --external argument like this:

```bash
npx esbuild src\extension.ts --bundle --platform=node --external:vscode --outfile=out\extension.js
```

That excludes the vscode import from esbuild and it bundles my extension code!

I still get the warnings, but that isn't stopping the bundle from being generated.

Hopefully, my findings will help the next person who tries to build a VSCode extension with esbuild.
