### ISSUE TITLE
Export with globalName return wrong global object

### ISSUE THREAD

**Issue by sondh0127** [evanw/esbuild#869]
Here is my config build.
![image](https://user-images.githubusercontent.com/62163604/108692886-c55c3800-752f-11eb-9cf3-e7137c35a348.png)

with entryPoint is the `main.js` with `export default app`
![image](https://user-images.githubusercontent.com/62163604/108692919-d016cd00-752f-11eb-9391-c61a04322e98.png)

I expected a global variable `app` will point to `mySvelte` app. 
but instead the app = {default: `mySvelte` }

So, Is there any option for my case?

**Comment by evanw** [comment]
This is deliberate behavior. When you do `export default` in ESM that means you are creating an export called `default`.

If you want to export the object itself you could try using a CommonJS export instead such as `module.exports = app` or `return app`.

**Comment by evanw** [comment]
Closing because I got a 👍 from the author of this issue. I tested `module.exports = app` myself and it works for me, so it should be a valid solution for this issue.
