### ISSUE TITLE
Support glob inside npm scripts

### ISSUE THREAD

**Issue by brunoluiz** [evanw/esbuild#875]
Currently, the following command produces what is expected, with the correct structure:

```
esbuild ./src/**/*.ts --outdir=dist
```

But, running the same command as an `npm-script` will not work, as npm itself seems to have a different way to do glob matching

```
{
  ...
  "scripts": { "build": "esbuild ./src/**/*.ts --outdir=dist" }
  ...
}
```

**Comment by brunoluiz** [comment]
To be fair, it is probably because I use zsh, but internally npm uses sh or bash iirc. There are some projects (`eslint`, `mocha`) which bypass this by parsing globs when the input is specified inside single quote marks. In this case, `esbuild` with glob parsing would look like `esbuild './src/**/*.ts' --outdir=dist`

**Comment by evanw** [comment]
I'm not going to encode zsh-specific features into esbuild. There are many different shells and I think it's best if esbuild remains shell-agnostic. There are also features specific to Windows Command Prompt that esbuild doesn't emulate, for example.

If you would like for this to work you are welcome to write a small script to do this yourself. I assume the most straightforward way to do this would be to use the [`glob`](https://www.npmjs.com/package/glob) package with [esbuild's JavaScript API](https://esbuild.github.io/api/#build-api).

**Comment by brunoluiz** [comment]
Makes sense. As it is a personal one-man project, I just ended up doing `zsh -c 'esbuild ./src/**/*.ts --outdir=dist'`. Would be nice to have this glob syntax as other projects do though (as `mocha`, `eslint` etc).

Anyways, closing it for now.
