### ISSUE TITLE
Is there anyway to disable error reporting or pipe stdout to a file.

### ISSUE THREAD

**Issue by jctaoo** [evanw/esbuild#877]
Using Nodejs api `esbuild.build`

**Comment by evanw** [comment]
The documentation is available here: https://esbuild.github.io/api/

> Is there anyway to disable error reporting

https://esbuild.github.io/api/#log-level

> or pipe stdout to a file

https://esbuild.github.io/api/#outfile

**Comment by jctaoo** [comment]
Sorry, I have read the document, but did not notice the `silent` option in log-level. 😂
