### ISSUE TITLE
Bundle not-minified 

### ISSUE THREAD

**Issue by baumannalexj** [evanw/esbuild#887]
Would like to use with AWS lambda, so we'd like to leave source code to view in Lambda UI.

* esbuild uses package.json "main" field to source index.js location
* esbuild has a flag to choose to not-minify
* esbuild provides a flag to exclude dependency from bundledDependencies (e.g. Dynamoose has aws-sdk as a transient dep, but we do not want to bundle since AWS provides this)
* bonus: also zips as reponame.zip

**Comment by evanw** [comment]
Sorry, I'm pretty confused. I don't understand what you're saying. There is no flag to disable minification. Minification is disabled by default. There is only a flag to enable minification: https://esbuild.github.io/api/#minify.

There is nothing specific to AWS about esbuild. If you want to change something about AWS's use of esbuild, you'll have to ask them.

**Comment by baumannalexj** [comment]
Thank you @evanw, that makes sense.

I'll close and open another: aws-sdk was an example,  the ability to exclude a node_module would be helpful.
