### ISSUE TITLE
How can I turn off 'Cannot assign to import" If libs contain it?

### ISSUE THREAD

**Issue by mvolkov-prog** [evanw/esbuild#891]
![image](https://user-images.githubusercontent.com/55079059/109275513-6e17d980-7847-11eb-886b-b6e271240cd4.png)

**Comment by zeallot** [comment]
Subscribe, have a same problem.

**Comment by vkaboskin** [comment]
OH, i have a same problem too. Will watch what to do. 

I wanna write my webpack project to esbuild.

**Comment by cojukesy** [comment]
This problem was blocking me, I had to go back to webpack

**Comment by evanw** [comment]
It is not possible to turn this off. This is not valid ECMAScript module code. Properties of an imported module namespace object [cannot be assigned to](https://tc39.es/ecma262/#sec-module-namespace-exotic-objects-set-p-v-receiver) in ECMAScript. Here's an example of trying to do this in node:

```
$ cat ./example.mjs
import * as vec2 from './example.mjs'
vec2.angle = function (v1, v2) {
};
```

```
$ node ./example.mjs
vec2.angle = function (v1, v2) {
           ^

TypeError: Cannot add property angle, object is not extensible
```

This bundler follows ECMAScript semantics just like node, so if your code uses ECMAScript module syntax and doesn't run in node, then it likely won't run in esbuild either. I think you will likely have to go back to Webpack to be able to use this library.

**Comment by Jarred-Sumner** [comment]
You could work around it by importing the non-ESM version of the library doing this, or transform it to CJS and then import the CJS version and esbuild will transform it back

**Comment by evanw** [comment]
Yes, that's a good point. This module ships with broken ESM code but esbuild is only loading it because it's respecting the `module` field instead of the `main` field in `package.json`. You can tell esbuild to not respect the `module` field using `--main-fields=browser,main`. More documentation about this API option is here: https://esbuild.github.io/api/#main-fields.

**Comment by evanw** [comment]
I'm going to close this because I think the above answers should be sufficient. Feel free to add additional comments if you have additional thoughts.
