### ISSUE TITLE
How solve problem, when libs contains node libs like a 'domain'

### ISSUE THREAD

**Issue by mvolkov-prog** [evanw/esbuild#892]
![image](https://user-images.githubusercontent.com/55079059/109279386-437c4f80-784c-11eb-8505-d4b0c5ecc6bb.png)

**Comment by evanw** [comment]
The error message you copied already says what to do: `set platform to "node" when bundling for node`. Documentation for the platform option is here: https://esbuild.github.io/api/#platform.

**Comment by evanw** [comment]
Closing this because the way to resolve this issue was mentioned in the issue itself and there has been no response. Feel free to add additional information if there is any.
