### ISSUE TITLE
provide some hooks for watch

### ISSUE THREAD

**Issue by hardfist** [evanw/esbuild#895]
it would be very helpful if esbuild could export some watch events to userland ,which user can do some custom things such as analyze rebuild performance.

**Comment by zaydek** [comment]
@hardfist I’m a little confused. Are you proposing something different from `onRebuild`?

https://esbuild.github.io/api/#watch:

```js
require('esbuild').build({
  entryPoints: ['app.js'],
  outfile: 'out.js',
  bundle: true,
  watch: {
    onRebuild(error, result) {
      if (error) console.error('watch build failed:', error)
      else console.error('watch build succeeded:', result)
    },
  },
}).then(result => {
  // Call "stop" on the result when you're done
  result.stop()
})
```

`args` includes `timeInMs`, which provides some performance insights.

Could you be more specific what you are interested in?

**Comment by hardfist** [comment]
whoop, I didn't realize esbuild already supports onRebuild hooks.

**Comment by hardfist** [comment]
It seems like args doesn't contains `timeInMs` now? @zaydek

**Comment by zaydek** [comment]
Oops. Try `timeInMs` (capital 'S').

```ts
export interface ServeOnRequestArgs {
  remoteAddress: string;
  method: string;
  path: string;
  status: number;
  timeInMS: number; // The time to generate the response, not to send it
}
```
