### ISSUE TITLE
Private methods in class fields

### ISSUE THREAD

**Issue by morten-krogh** [evanw/esbuild#901]
This class illustrates the issue

```js
class A {
    pub = this.#priv;

    #priv() {
        console.log('Inside #priv');
    }
}
```

There is  a private method #priv which is being referenced in the class field initializer for pub.

Transpiling with esbuild from ESNEXT to ES6 gives the following

```js
var _priv, priv_fn;
var A = class {
  constructor() {
    __publicField(this, "pub", __privateMethod(this, _priv, priv_fn));
    _priv.add(this);
  }
};
_priv = new WeakSet();
priv_fn = function() {
  console.log("Inside #priv");
};
```

The transpiled code gives an error.

The problem is the order of the two lines in the constructor. 
The class field initializer

```js
  __publicField(this, "pub", __privateMethod(this, _priv, priv_fn));
```

runs before the private method is defined

```js
  _priv.add(this);
```

I would guess the solution is just to make sure all private methods are defined first in the constructor (right after super).
The class fields can then be defined after that.

**Comment by evanw** [comment]
Thanks for the report. This will be fixed in the next release.
