### ISSUE TITLE
How to support this.constructor.name when building? 

### ISSUE THREAD

**Issue by topoge** [evanw/esbuild#908]
```
class A{
 constructor(){ 
      console.log(this.constructor.name)
    }
}
````
After build, this feature cannot be used

**Comment by evanw** [comment]
Have you tried https://esbuild.github.io/api/#keep-names?

**Comment by topoge** [comment]
> 
> 
> Have you tried https://esbuild.github.io/api/#keep-names?

Thank you very much, it is very helpful to me
