### ISSUE TITLE
Add option to not automatically include licenses in footer

### ISSUE THREAD

**Issue by eligrey** [evanw/esbuild#919]
I already embed different, more-concise licenses in a banner and want to opt-out of license inclusion in the footers.

Judging from [this code in linker.go](https://github.com/evanw/esbuild/blob/b72805747e10f4072de9defc851543727d2d8ef5/internal/bundler/linker.go#L3972-L3975), it appears that there is no way to opt-out of automatic license inclusion as footers are added are from an append-only list.

This could be implemented by special-casing `footer: false` in the build API to remove *every* footer.

**Comment by jaydenseric** [comment]
Sometimes ESBuild is used within test scripts for published packages, to assert the bundle size is within an acceptable limit. Here is an example:

https://github.com/jaydenseric/extract-files/blob/ba4c930e63e540987f682434a9621747dbe78495/test/bundle.test.js#L9-L24

Unfortunately, sometimes dependencies have large license comments that end up in the bundle, and cause the bundle size to increase a lot and exceed the asserted limit. These bundles are really to test the size of the actual code, not comments, and are never distributed anywhere (or even written to the filesystem) so excluding license comments in this context is legally fine. We need to be able to configure ESBuild to exclude _all_ comments from the bundle.
