### ISSUE TITLE
Can i use the AST parser of Esbuild?

### ISSUE THREAD

**Issue by zbysir** [evanw/esbuild#92]
Can you move out `parse` and `ast` from `internal` to export they?

Thx, I want to use Golang to render Jsx.

**Comment by evanw** [comment]
See the disclaimer in the readme:

> The Go code in this repo isn't intended to be built upon. Go is just an implementation detail of how I built this tool. The stable interfaces for this project are the command-line API and the JavaScript API, not the internal Go code. I'm may change the internals in a backwards-incompatible way at any time to improve performance or introduce new features.

The AST structure and the parser are potentially going to change quite a bit in the next month or two to accommodate new features.

**Comment by zbysir** [comment]
Thx for your reply, I'm not in a hurry, so I may decide in a month or two.
