### ISSUE TITLE
Sometimes can't install esbuild with 3rd-party registry

### ISSUE THREAD

**Issue by TuiMao233** [evanw/esbuild#921]
~~~
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn F:\projects\test\my-vue-app\node_modules\esbuild\esbuild.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'spawn F:\\projects\\test\\my-vue-app\\node_modules\\esbuild\\esbuild.exe',
  path: 'F:\\projects\\test\\my-vue-app\\node_modules\\esbuild\\esbuild.exe',
  spawnargs: [ '--service=0.8.55', '--ping' ]
}
~~~

The problem was solved after I rolled back esbuild to 0.8.54

**Comment by evanw** [comment]
I assume this means esbuild failed to install correctly. The clues for why that happened are in npm's install messages, not in this error message.

**Comment by TuiMao233** [comment]
No, npm did not report an error, the installation is normal, but I found no esbuild.exe exists in node_modules/esbuild

**Comment by cnscoo** [comment]
你是不是使用了镜像来获取npm包？如果是的话，以下步骤可能对你有帮助。

- 清理npm缓存 `npm cache clean -f`
- 删除项目中的 node_modules 文件夹
- 删除 ~/.npmrc 文件中配置的所有镜像
- 重新打开一个终端执行依赖安装 `npm install`.

如果是相同原因，执行完以上步骤应该就可以了。
不过对此我还是不解，我比较过 registry.npm.taobao.org 与 registry.npmjs.org 的文件，发现并没有什么不一样，暂时不清楚产生问题的原因是什么。

**Comment by yilihjy** [comment]
I met the same problem.

**Comment by TuiMao233** [comment]
> 你是不是使用了一部分来来获取npm包？如果是的话，以下步骤可能对你有帮助。
> 
> * 清理npm缓存 `npm cache clean -f`
> * 删除项目中的node_modules文件夹
> * 删除〜/ .npmrc文件中配置的所有副本
> * 重新打开一个终端执行依赖安装`npm install`。
> 
> 如果是相同原因，执行完以上步骤应该就可以了。
> 不过对此我还是不解，我比较过registry.npm.taobao.org与registry.npmjs.org的文件，发现并没有什么不一样，暂时不清楚产生问题的原因是什么。

我使用了你的方法，成功运行了。但有时候还是会有这种情况出现，具体出现的时机我不是很清楚。

**Comment by evanw** [comment]
Closing since this is unactionable, and also because 3rd-party registries aren't officially supported. If npm works but a mirror of npm doesn't, then that's a problem with the mirror, not with esbuild.

**Comment by appbest** [comment]
npm v7 以上有个 Bug,需要执行以下安装

`node node_modules/esbuild/install.js`
