### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by sergey-morenets** [evanw/esbuild#923]
Hi

I tried to integrate esbuild into our project instead of Webpack but had a couple of questions. Unfortunately I couldn't find answers in the documentation.
First of all, we use TypeScript, so does esbuild use tsconfig.json during conversion to JS? Here's our tsconfig.json:

```
{
  "compilerOptions": {
    "module": "esnext",
    "target":  "esnext",
    "sourceMap": false
  },
  "exclude": [
    "node_modules"
  ]
}
```

If we run tsc it will convert our code it using latest ES version but with esbuild we get the same output for different target/module values. 
I found flag --target, but if we add it to the esbuild command: --target=esnext it seems to not affect output JS file.
Another question - is it good idea to compile TypeScript files using tsc and then bundle it using es-bundle?

**Comment by evanw** [comment]
These are good questions.

> does esbuild use tsconfig.json during conversion to JS?

It currently only uses a few fields:

* `jsxFactory`
* `jsxFragmentFactory`
* `useDefineForClassFields`
* `importsNotUsedAsValues`
* `paths`
* `baseUrl`
* `extends`

All other fields are ignored.

> If we run tsc it will convert our code it using latest ES version but with esbuild we get the same output for different target/module values.

The `target` and `module` fields are ignored. The `--target=` flag in esbuild has a slightly different format and can represent values like `node15` or `chrome80`. Another issue is that esbuild currently respects multiple `tsconfig.json` files as input but must have a single target value. This is tracked by #277.

> Another question - is it good idea to compile TypeScript files using tsc and then bundle it using es-bundle?

For many cases you can let esbuild convert TypeScript to JavaScript and not use tsc. This will be much faster than using tsc. However, you may want to use tsc first (or equivalently an esbuild plugin that calls `ts.transpileModule`) if any of esbuild's TypeScript compilation caveats don't work for you: https://esbuild.github.io/content-types/#typescript-caveats.

**Comment by sergey-morenets** [comment]
@evanw Thank you for the quick response.

Can you please mention list of supported fields (from tsconfig.json) in the corresponding section? https://esbuild.github.io/content-types/#typescript

And my main question is still open. What is the ES version used by default during TS compilation to JS? And can adjust this version somehow?

**Comment by evanw** [comment]
> Can you please mention list of supported fields (from tsconfig.json) in the corresponding section?

👍 

> What is the ES version used by default during TS compilation to JS? And can adjust this version somehow?

The `--target=` flag defaults to `esnext` but you can set it to values such as `--target=es2018`, `--target=chrome80`, `--target=node15`, or even a comma-separated list of targets such as `--target=es2020,chrome58,firefox57,safari11,edge16`. The full documentation is here: https://esbuild.github.io/api/#target.

**Comment by sergey-morenets** [comment]
> 
> 
> > Can you please mention list of supported fields (from tsconfig.json) in the corresponding section?
> 
> 👍
> 
> > What is the ES version used by default during TS compilation to JS? And can adjust this version somehow?
> 
> The `--target=` flag defaults to `esnext` but you can set it to values such as `--target=es2018`, `--target=chrome80`, `--target=node15`, or even a comma-separated list of targets such as `--target=es2020,chrome58,firefox57,safari11,edge16`. The full documentation is here: https://esbuild.github.io/api/#target.

Thank you. Do I understand correctly that esbuild contains its own (custom) compiler/transpiler from Typescript to ES?

**Comment by evanw** [comment]
Yes, that's correct. It doesn't use Microsoft's implementation at all although I did reference it heavily when I made it. There are other similar efforts that do this too (reimplement TypeScript-to-JavaScript conversion from scratch) such as [Babel](https://babeljs.io/docs/en/babel-plugin-transform-typescript), [Sucrase](https://github.com/alangpierce/sucrase#transforms), and [SWC](https://swc.rs/docs/configuring-swc#jscparser). I know at least Babel and Sucrase have similar limitations to esbuild around `isolatedModules`.

**Comment by evanw** [comment]
The set of supported `tsconfig.json` fields is now documented here: https://esbuild.github.io/content-types/#tsconfig-json. Closing.

**Comment by jasonwilliams** [comment]
Hey @evanw 
I’m a bit confused about target, it’s mentioned in the documentation about being respected, but from what I understand in this thread it’s never used, you need to provide it or it uses esnext.
Why is it in the list?

**Comment by evanw** [comment]
If you don’t pass `--target=` to esbuild directly, then esbuild will use `target` from `tsconfig.json` instead if it exists, and will only fall back to `esnext` if neither of those settings are provided.
