### ISSUE TITLE
Make esbuild options available to plugins

### ISSUE THREAD

**Issue by thomaschaaf** [evanw/esbuild#927]
It would be good if the plugins could access the esbuild options. E.g. I would like to access the tsconfig passed in.

Currently they are not available see: https://esbuild.github.io/plugins/#load-arguments

**Comment by evanw** [comment]
Yes, I agree. I plan to do this but still haven't done it yet. Closing as a duplicate of #373.

**Comment by evanw** [comment]
Support for this is in the latest release. Documentation is here: https://esbuild.github.io/plugins/#build-options.
