### ISSUE TITLE
Chunk name collisions if 2 chunks' content is identical

### ISSUE THREAD

**Issue by overlookmotel** [evanw/esbuild#928]
When splitting, chunk filenames are based on a content hash. If the content of 2 files is identical, they will have identical hashes and therefore ESBuild only outputs 1 shared chunk when it should output 2.

Here is a (rather artificial) case to demonstrate:

```js
// src/index.js
import {x, y} from './shared.js';
console.log(x === y);

// src/other1.js
import {x} from './shared.js';
x();

// src/other2.js
import {y} from './shared.js';
y();

// src/shared.js
const x = () => 123;
const y = () => 123;
export {x, y};
```

```js
esbuild.buildSync({
  entryPoints: ['src/index.js', 'src/other1.js', 'src/other2.js'],
  bundle: true,
  splitting: true,
  format: 'esm',
  minify: true,
  outdir: 'build'
});
```

Output is as follows:

```js
// index.js
import{a as o}from"./chunk.IW3PO35Y.js";import{a as m}from"./chunk.IW3PO35Y.js";console.log(o===m);

// other1.js
import{a as m}from"./chunk.IW3PO35Y.js";m();

// other2.js
import{a as m}from"./chunk.IW3PO35Y.js";m();

// chunk.IW3PO35Y.js
var t=()=>123;export{t as a};
```

Running `src/index.js` logs `false`, whereas running `build/index.js` logs `true`.

This example is contrived, but given how many chunks ESBuild can create, and how small they can be, I think collisions like this are quite possible in the real world.

I'm not sure what best solution is, but ESBuild should probably throw an error rather than creating incorrect output at least.

**Comment by evanw** [comment]
Thanks for calling this out! I did not anticipate this issue. I will need to mix input file names into the file name hash to avoid this.

**Comment by overlookmotel** [comment]
That was quick! Thanks for fixing.

When you say "input file names", do you mean the files that the code originated in? Or the entry points that import the chunk? i.e. in my example above is it `src/shared.js`? Or `src/index.js` + `src/other1.js` + `src/other2.js`?

Neither would be ideal because in first case there could still be collisions if all the code originates in same file (as in my example), and in 2nd case the hash would change if a further entry point also imports the same statements, despite the content of the shared chunk remaining the same.

I *think* what you're doing in c05c489 is the former, and then mixing in the "part range" which I assume refers to the line/column numbers of the source - which would solve all cases I can envisage. But I don't "speak" Go, so I'm not 100% sure I've understood the change you've made. Could you possibly confirm?

**Comment by evanw** [comment]
The input file names are names of all the original source code files that ended up in the chunk, so just `src/shared.js` in this example. This would completely the solve the issue if a given file could only end up in a single chunk. However, esbuild currently has a file splitting optimization that can redirect content from a single file into separate chunks.

This is why the part range is also necessary. The indices of the part range are top-level statement indices instead of line/column numbers but it's the same idea. Top-level statement indices are the used because this is the granularity of the file splitting optimization.

But I'm considering removing the file splitting optimization somewhat soon to make it possible to implement support for top-level await, which has file-level evaluation order semantics. Then the hash algorithm wouldn't need the part range data anymore. It would then only need the input file names.

**Comment by overlookmotel** [comment]
Thanks for your explanation. Yes, that's what I'd guessed the fix you made was doing (bar statement indices instead of lines/columns).

I just made a [comment](https://github.com/evanw/esbuild/pull/924#issuecomment-792172575) on the 0.9.0 roadmap PR saying how valuable the statement-level splitting is. But hey, if it's infeasible to make it top-level await work with it, I can see TLA would be higher priority.

**Comment by overlookmotel** [comment]
Actually, I have another solution which I think is slightly better.

The intent of the hashes in chunk filenames is to facilitate caching. As much as possible, if the content of the file doesn't change, it's filename shouldn't change either.

Mixing metadata into the hash produces another source of change which is not related to the actual contents of the chunk file.

For example, in my case above, if `src/shared.js` is moved to `src/shared/index.js`, the content of all the chunks would remain unchanged. But, since c05c489 also uses the source filename in calculating the hashes, both the shared chunks' hashes would change, invalidating the cache.

Until statement-level code-splitting is removed, reversing the order of the statements in `src/shared.js`, or adding further statements at the top of the file, would also cause the same effect.

A simpler method to ensure unique hashes without this side effect would be to use a simple counter. In JS:

```js
const usedHashes = Object.create(null);

function hashForFileName( contents ) {
  const hash = sha1( contents );
  const numUses = usedHashes[hash] || 0;
  usedHashes[hash] = numUses + 1;

  // If not used this hash before, return it
  if (numUses === 0) return hash;

  // Hash already used - mix in counter and hash again
  return sha1( `${hash}${numUses}` );
}
```

I guess this has the downside of being less parallelisable - the check for whether a hash has been used before would need to be in main thread - but I can't imagine it'll be a big hit.
