### ISSUE TITLE
Avoid Class renaming in .ts !?

### ISSUE THREAD

**Issue by djmisterjon** [evanw/esbuild#931]
Hi , when convert my file `.js` to `.ts` , my class are renamed !
```js
export class Foo {
	static Hello = 'Hello';
	constructor() {
		const test = Foo.Hello; // hey dont rename me !
	}
}
```
produce:
```js
const _Foo = class {
  constructor() {
    const test = _Foo.Hello;
  }
};
export let Foo = _Foo;
Foo.Hello = "Hello";
```
![image](https://user-images.githubusercontent.com/24865815/110253912-b24b5e00-7f5a-11eb-983d-e36da6ef41be.png)

is there a option to disable this behavior with `.ts` , `.tsx` ?
I have no issue if i use `.js or .jsx` extensions ! 
i know snowpack using `esbuild` , but am not sure if this issu came from `snowpack` or `esbuild` .!
https://github.com/snowpackjs/snowpack/issues/2804

I see a fix for `.js` only here !, but what about `.ts` ?
https://github.com/evanw/esbuild/blob/2001dff446c016612f4043c8ff8b7cb1bf69ed5e/CHANGELOG.md#unreleased
https://github.com/evanw/esbuild/issues/510

---
![image](https://user-images.githubusercontent.com/24865815/110253621-487e8480-7f59-11eb-9582-e537d17fcb47.png)
---
thanks

edit: TS compiler and babel show me good code, so it may related to esbuild or snowpack ?!
![image](https://user-images.githubusercontent.com/24865815/110254027-5208ec00-7f5b-11eb-8cd0-ceff6ea51f61.png)
and same for babel ! 
![image](https://user-images.githubusercontent.com/24865815/110254079-93010080-7f5b-11eb-98dc-5374e83b1ce1.png)

**Comment by evanw** [comment]
If you rely on the value of the `.name` property on the class, you should enable the [keep names](https://esbuild.github.io/api/#keep-names) setting.

**Comment by djmisterjon** [comment]
> If you rely on the value of the `.name` property on the class, you should enable the [keep names](https://esbuild.github.io/api/#keep-names) setting.

Thank you for you time , so if i understand , i should add  `keepNames: true,` there ?
https://github.com/snowpackjs/snowpack/blob/a8e97be06373aade636b9b40b312bc7ca2943bd6/snowpack/src/plugins/plugin-esbuild.ts#L36
or do you know if snowpack allow a way to setting this ? 
https://www.snowpack.dev/guides/optimize-and-bundle#nav-primary

So if i want fix this i need a way to customize `esbuild` in `snowPack` right ?

**Comment by evanw** [comment]
It looks like they don't currently expose that setting. You'll have to ask them to expose it.

**Comment by djmisterjon** [comment]
oki, thanks for your time and help
