### ISSUE TITLE
addNewBundledCss doesn't work with code-splitting

### ISSUE THREAD

**Issue by lauri865** [evanw/esbuild#932]
For dynamic imports, the check of `hasScriptImportAlready` always fails. Also, the CSS chunks get exported to `[chunk].[hash].css`, while the JS chunk is imported through the main source file name, so `if (!manifest.outputs[scriptKey]) {` will always result true for these cases as well.

**Comment by evanw** [comment]
> For dynamic imports, the check of `hasScriptImportAlready` always fails.

There is no code in this repository with that name: https://github.com/evanw/esbuild/search?q=hasScriptImportAlready. I don't understand what you're talking about.

**Comment by lauri865** [comment]
apologies, wrong repo 🤦‍♂️
