### ISSUE TITLE
TypeScript Generic Arrow function raises error

### ISSUE THREAD

**Issue by n1ru4l** [evanw/esbuild#934]
```tsx
export const useDebounce = <T,>(value: T, delay: number): T => {
  // State and setters for debounced value
  const [debouncedValue, setDebouncedValue] = React.useState(value);

  React.useEffect(
    () => {
      // Update debounced value after delay
      const handler = setTimeout(() => {
        setDebouncedValue(value);
      }, delay);

      // Cancel the timeout if value changes (also on delay change or unmount)
      // This is how we prevent debounced value from updating if value is changed ...
      // .. within the delay period. Timeout gets cleared and restarted.
      return () => {
        clearTimeout(handler);
      };
    },
    [value, delay] // Only re-call effect if value or delay changes
  );

  return debouncedValue;
};

```

Raises the following error:

```
  
  Unexpected "const"
  7  |  export const useDebounce = <T>(value: T, delay: number): T => {
  8  |    // State and setters for debounced value
  9  |    const [debouncedValue, setDebouncedValue] = React.useState(value);
     |    ^
  10 |    React.useEffect(() => {
  11 |      // Update debounced value after delay
```

After I changed it to

```diff
- export const useDebounce = <T,>(value: T, delay: number): T => {
+ export const useDebounce = (value: any, delay: number): any => {
```

or 

```diff
- export const useDebounce = <T,>(value: T, delay: number): T => {
+ export function useDebounce<T>(value: T, delay: number): T {
```

Everything works just fine

**Comment by evanw** [comment]
> ```tsx
> export const useDebounce = <T,>(value: T, delay: number): T => {
>   // State and setters for debounced value
>   const [debouncedValue, setDebouncedValue] = React.useState(value);
> 
>   React.useEffect(
>     () => {
>       // Update debounced value after delay
>       const handler = setTimeout(() => {
>         setDebouncedValue(value);
>       }, delay);
> 
>       // Cancel the timeout if value changes (also on delay change or unmount)
>       // This is how we prevent debounced value from updating if value is changed ...
>       // .. within the delay period. Timeout gets cleared and restarted.
>       return () => {
>         clearTimeout(handler);
>       };
>     },
>     [value, delay] // Only re-call effect if value or delay changes
>   );
> 
>   return debouncedValue;
> };
> ```

This TypeScript code appears to parse fine with esbuild when I try it.

> Raises the following error:
>
> ```
>   Unexpected "const"
>   7  |  export const useDebounce = <T>(value: T, delay: number): T => {
>   8  |    // State and setters for debounced value
>   9  |    const [debouncedValue, setDebouncedValue] = React.useState(value);
>      |    ^
>   10 |    React.useEffect(() => {
>   11 |      // Update debounced value after delay
> ```

This doesn't look like an error produced by esbuild since it has multiple line numbers. It looks like an error produced by some other tool. I'm guessing that your problem is being caused by another tool, not with esbuild. If you double-check and you still believe that it's a problem with esbuild, please provide the esbuild command-line parameters you used that can demonstrate the problem.

**Comment by n1ru4l** [comment]
Yeah, you are right, I am indeed using esbuild wrapped by vite and it complains that it is an error caused by esbuild. I will double check!
