### ISSUE TITLE
Talk at JavaScript Israel

### ISSUE THREAD

**Issue by benjamingr** [evanw/esbuild#937]
Hey Evan,

(Not sure if you remember me, we talked a bit on the Node.js issue tracker and a few other places)

I'm going to give a talk on modern build infrastructure and I want to mention and talk about ESBuild. The audience is usually ±100-200 people and there are ±500-1000 more views later on. The talks are mostly in Hebrew.

It's an online event:

I was wondering if (in order of priority):
 - You'd be willing to record 2-3 minutes describing the main selling points of esbuild (it's fast, it's reliable, it does from-scratch builds faster than webpack incremental builds) and ideally why it's fast. This can also include a call to action / call for contributors.
 - If not - if you'd be willing to review 2-3 minutes of me talking about it.
 - If not - if you'd be willing to review a bit of text I'll write about it.

If any of this is interesting or relevant to you - I'm available at benjamingr@gmail.com (I couldn't find your email publicly easily and didn't want to contact you privately by scraping git or similarly).

**Comment by evanw** [comment]
Thank you for reaching out. However, this is not something I'm interested in. Closing.
