### ISSUE TITLE
Expose parse/generate API

### ISSUE THREAD

**Issue by Djaler** [evanw/esbuild#950]
This can be used as a replacement for @babel/parser and @babel/generator and improve performance

**Comment by evanw** [comment]
This is out of scope for esbuild. It's listed as a non-goal [in the documentation](https://esbuild.github.io/faq/#upcoming-roadmap):

> * An API for custom AST manipulation

I haven't used [swc](https://swc.rs/) myself but I've heard that it's designed to be a Babel replacement and has an [AST API](https://swc.rs/rustdoc/swc_ecma_ast/index.html) that can be used to write plugins. I suggest checking out swc instead.

**Comment by Djaler** [comment]
Ok, thanks for the link
