### ISSUE TITLE
CSS Page Margin Rules

### ISSUE THREAD

**Issue by martinring** [evanw/esbuild#955]
I don't know exactly what your policy is about including css features but your css parser accepts `@page` rules from the [paged media working draft](https://www.w3.org/TR/css-page-3/) which is great. However, it complains about unknown rules when using [margin rules](https://www.w3.org/TR/css-page-3/#at-page-rule) from the same working draft (same section):

````css
@page {
  @bottom-center { content: counter(page) }
}
````

gives me:

````
> src/style/print.css:2:4: warning: "@bottom-center" is not a known rule name
    20 │   @bottom-center {
       ╵   ~~~~~~~~~~~~~~
````

I know that this is currently not supported by browsers but it is by e-publishing tools like [prince](https://www.princexml.com/) ([feature doc](https://www.princexml.com/doc/paged/#page-regions)) and [weasyprint](https://weasyprint.org/start/) ([feature doc](https://weasyprint.readthedocs.io/en/latest/features.html#css-paged-media-module-level-3))

**Comment by evanw** [comment]
Thanks very much for linking to the documentation of existing user agents that support this feature. Supporting these rules sounds reasonable. I'll remove the warning in the next release (it should already work, warning aside, since esbuild preserves unknown CSS syntax).
