### ISSUE TITLE
esbuild throws fault error within TUP build system

### ISSUE THREAD

**Issue by mikehaverstock** [evanw/esbuild#957]
TUP is a very opinionated build system that proxies all file access through a virtual file system so that it can record all reads / writes as part of your build. This allows it to automatically track your dependencies and knows the optimal steps to re-run whenever a subset of files change.  http://gittup.org/tup/

Within our build system I tried to replace our `./node_modules/.bin/uglify` call with `./node_modules/.bin/esbuild` and got a runtime error from esbuild. I tried simplifying the command down to `./node_modules/.bin/esbuild --version` to make sure that esbuild was doing the bare minimum and still got the following error.

```
unexpected fault address 0x10084a0
fatal error: fault
[signal SIGBUS: bus error code=0x2 addr=0x10084a0 pc=0x10084a0]

goroutine 1 [running, locked to thread]:
runtime.throw(0x149f0a2, 0x5)
	/usr/local/go/src/runtime/panic.go:1117 +0x72 fp=0xc0000485f8 sp=0xc0000485c8 pc=0x1037eb2
runtime.sigpanic()
	/usr/local/go/src/runtime/signal_unix.go:731 +0x2d6 fp=0xc000048630 sp=0xc0000485f8 pc=0x104f2d6
runtime.init.0()
	/usr/local/go/src/runtime/cpuflags_amd64.go:15 fp=0xc000048638 sp=0xc000048630 pc=0x10084a0
runtime.doInit(0x16e03e0)
	/usr/local/go/src/runtime/proc.go:6265 +0xec fp=0xc000048788 sp=0xc000048638 pc=0x104808c
runtime.main()
	/usr/local/go/src/runtime/proc.go:174 +0x130 fp=0xc0000487e0 sp=0xc000048788 pc=0x103a5b0
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc0000487e8 sp=0xc0000487e0 pc=0x10705c1
```

I'm curious if this rings any bells and if there's anything else for me to try to help diagnose what's going on. If it'd be helpful I could put together a minimal repo to reproduce the issue.

Thanks for all your work!

**Comment by evanw** [comment]
This doesn't ring any bells (haven't seen this particular failure before) but my gut is that this isn't going to work. It looks like the problem is in the Go runtime when it's setting up the process. So I'm guessing there's nothing specific to esbuild about this issue. Do you know if this is an issue for all Go programs? If so, this could potentially be something the Go compiler team could fix.

**Comment by mikehaverstock** [comment]
Even a hello-world go binary fails to run. So, this isn't esbuild specific. Thanks!
