### ISSUE TITLE
Can't understand the purpose of __toModule.

### ISSUE THREAD

**Issue by sbfkcel** [evanw/esbuild#961]
![image](https://user-images.githubusercontent.com/5469785/110973171-dca47d80-8397-11eb-8a6d-3475fd60ea3c.png)

The returned object will cause the program to run abnormally. The results generated by native TypeScript compilation will not. The return result encapsulated by __toModule seems abnormal.

---

My input file

```typescript
import {UnityEngine} from 'csharp'
UnityEngine.Debug.Log('hello world5');
let obj:UnityEngine.GameObject = new UnityEngine.GameObject("testobject");

obj.transform.position = new UnityEngine.Vector3(1, 2, 3);
```
---
TypeScript output results（Operating normally）

```javascript
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const csharp_1 = require("csharp");
csharp_1.UnityEngine.Debug.Log('hello world5');
let obj = new csharp_1.UnityEngine.GameObject("testobject");
obj.transform.position = new csharp_1.UnityEngine.Vector3(1, 2, 3);
```

**Comment by evanw** [comment]
Transforming `import {UnityEngine} from 'csharp'` to `const csharp_1 = require("csharp")` is a legacy TypeScript behavior that esbuild does not implement. You should enable TypeScript's `esModuleInterop` setting. Documentation about this is here: https://esbuild.github.io/content-types/#es-module-interop.

**Comment by evanw** [comment]
Closing since I believe this question has been answered. Feel free to continue to comment here with further questions relevant to this topic if you have any.

**Comment by sbfkcel** [comment]
I enabled tsconfig.json and added esModuleInterop, but it was not resolved. When format is cjs, no extra work is required. Hope to change to swc first
