### ISSUE TITLE
Filenames with spaces can not be bundled

### ISSUE THREAD

**Issue by retorquere** [evanw/esbuild#965]
When I run `npx esbuild 'translators/Better BibTeX.ts' --bundle --outdir=build/dist/` I get

```
 > error: Could not resolve "translators/Better"

 > error: Could not resolve "BibTeX.ts"
```

**Comment by evanw** [comment]
When I try that I get this (I did not create the file):

```
 > error: Could not resolve "translators/Better BibTeX.ts"
```

What operating system are you using? And which shell are you using to run the command?

**Comment by retorquere** [comment]
bash/MacOS big sur

**Comment by retorquere** [comment]
Huh -- it seems like it's `npx`. When I run 

```
./node_modules/.bin/esbuild 'translators/Better BibTeX.ts' --bundle --outdir=build/dist
```

it does work

**Comment by evanw** [comment]
Which version of npx? For me, `npx --version` says 7.6.1.

**Comment by retorquere** [comment]
7.3.0

**Comment by evanw** [comment]
Thanks for following up. I can confirm that this version of npx is broken. How unfortunate.

**Comment by retorquere** [comment]
No problem -- I've just installed esbuild globally.
