### ISSUE TITLE
Webpack benchmarks are with ts-loader

### ISSUE THREAD

**Issue by desmap** [evanw/esbuild#973]
A minor nitpick: I've seen that the Webpack benchmarks were done with `ts-loader` in the respective `package.json`s. I did some intense [benchmarks against babel a while ago](https://github.com/TypeStrong/ts-loader/issues/1174) and babel was faster. I think that esbuild should be still faster than that but just want to mention it and I'm curious how your benchmark would change with babel.

**Comment by evanw** [comment]
Unfortunately `@babel/plugin-transform-typescript` has some limitations and only works for some TypeScript code. These limitations mean that it's not able to successfully build the TypeScript benchmark. I just tried using Babel now and Webpack gives me lots of errors of the form `Identifier '___' has already been declared` and warnings of the form `export '___' (reexported as '___') was not found in '___'`.

**Comment by evanw** [comment]
Closing this for the reason above. Babel doesn't work with the TypeScript code in the benchmark.
