### ISSUE TITLE
Typescript: optional chaining is not being transpiled

### ISSUE THREAD

**Issue by retorquere** [evanw/esbuild#974]
build script:

```
const path = require('path')
const fs = require('fs')
const esbuild = require('esbuild')

async function rebuild() {
  for (const translator of process.argv.slice(2)) {
    console.log(path.parse(translator).base)

    const globalName = 'BBTTranslator' + path.parse(translator).name.replace(/ /g, '')
    const outfile = path.join('build/dist', path.parse(translator).name + '.js')

    await esbuild.build({
      entryPoints: [translator],
      format: 'iife',
      globalName,
      bundle: true,
      outfile,
    })
  }
}

rebuild().catch(err => console.log(err))
```

source being transpiled:

```
if (mode === "export" && this.header.configOptions?.getCollections && Zotero.nextCollection) {
  // pass
}
```

transpilation result:

```
var BBTTranslatortt = (() => {
  var __commonJS = (callback, module) => () => {
    if (!module) {
      module = {exports: {}};
      callback(module.exports, module);
    }
    return module.exports;
  };

  // tt.ts
  var require_tt = __commonJS((exports) => {
    if (mode === "export" && exports.header.configOptions?.getCollections && Zotero.nextCollection) {
    }
  });
  return require_tt();
})();
```

**Comment by evanw** [comment]
Syntax transforms for JavaScript are documented here: https://esbuild.github.io/content-types/#javascript. Specifically:

> All modern JavaScript syntax is supported by esbuild. Newer syntax may not be supported by older browsers, however, so you may want to configure the [target](https://esbuild.github.io/api/#target) option to tell esbuild to convert newer syntax to older syntax as appropriate.

**Comment by retorquere** [comment]
Sorry I didn't find that myself -- this is great, I can just set support to `firefox60` and get exactly what I need with minimal transpilation.

**Comment by evanw** [comment]
Ok. Closing as it sounds like this issue has been resolved.

**Comment by retorquere** [comment]
Yes, can be closed -- what's the norm here, contributors close the issue or submitters close the issue?

**Comment by evanw** [comment]
I'm not sure there is a norm. Both things happen fairly often. Issues can easily be reopened if needed, so I don't think it's too important to be rigorous about it.

**Comment by retorquere** [comment]
I have a bot on some of my repos that enforces that only I can close issues of a certain kind. I usually leave issues open until the repo owner concludes they've been handled, but I take it it's OK to submitter-close if the submitter deems it handled. I'll do that from now on here.
