### ISSUE TITLE
Bare unicode characters after bundle of json

### ISSUE THREAD

**Issue by retorquere** [evanw/esbuild#977]
bundle script:

```
const esbuild = require('esbuild')

async function rebuild() {
  await esbuild.build({
    entryPoints: ['tt.ts'],
    format: 'iife',
    bundle: true,
    outfile: 'tt.js',
    target: ['firefox60'],
  })
}

rebuild().catch(err => console.log(err))
```

tt.ts:

```
import x from './ascii.json'
console.log(x)
```

ascii.json:
```
{
  "\ud835\udfce": {"math": "\\mathbf{0}"}
}
```

output:
```
(() => {
  // ascii.json
  var _ = {math: "\\mathbf{0}"};
  var ascii_default = {
    \u{1D7CE}: _
  };

  // tt.ts
  console.log(ascii_default);
})();
```

I'm trying to run the results through jscodeshift and it doesn't like that bare `\u{1D7CE}` (I didn't know this was valid javascript)

**Comment by retorquere** [comment]
FF60 says `SyntaxError: invalid escape sequence` when I try to run this.

**Comment by evanw** [comment]
Huh. My compatibility table data says that this is supported since Firefox 53: https://github.com/kangax/compat-table/blob/c06fcd3387a5770708a452fb90dbc4e99bb37e4f/data-es6.js#L18988. If you want to use UTF-8 instead you can enable this: https://esbuild.github.io/api/#charset.

**Comment by retorquere** [comment]
Maybe Zotero has done something that caused a regression, but I have to say it is not very likely. But thanks, this will fix it for me.

**Comment by retorquere** [comment]
Setting the charset to utf-8 causes dict literals with unicode keys to be output unescaped, which also gives me errors in Zotero. Is there a target that is close to `firefox60` but which will not produce bare unicode escapes?

**Comment by retorquere** [comment]
What is the current target list? [This](https://esbuild.github.io/api/#target) doesn't list `firefox60` but that does work, where `firefox52` does not.

**Comment by retorquere** [comment]
(alternately, can I just convince esbuild not to use bare unicode escapes?)

**Comment by retorquere** [comment]
Or if I could replace the json loader, that would also work; I'd just use jsesc to output it in a way that works in Zotero, as the problem is limited to JSON files for me.

**Comment by retorquere** [comment]
If I delete `versions.UnicodeEscapes.firefox` in `scripts/compat-table.js`, my code mostly works after bundling -- it's just the bare unicode that blocks a transition to esbuild for me.

**Comment by evanw** [comment]
It turns out this doesn't have to do with Firefox at all. The bug is that when validating whether esbuild can print an identifier without quotes, non-BMP characters always being treated as `ID_Continue` because they extend past the first code unit. This is incorrect because the first character should be treated as `ID_Start` instead. I'll fix this.

**Comment by retorquere** [comment]
Sweet!

**Comment by retorquere** [comment]
This does fix it for me.

**Comment by retorquere** [comment]
If you don't mind me asking -- do you have a release planned that would include this? I understand no hard ETAs in open source work.

**Comment by evanw** [comment]
No worries. I generally release changes within a day or two.

**Comment by retorquere** [comment]
I've migrated my project, and builds are not only amazingly fast (including type-checking using tsc), my bundler code is now *significantly* simpler because an increasing part of my bundler setup consisted of workarounds for webpack.

Thank you!
