### ISSUE TITLE
[Suggestion] Support esbuild.initialize for ‘warming up‘ esbuild

### ISSUE THREAD

**Issue by zaydek** [evanw/esbuild#979]
Now that the service API has been deprecated, is there a recommended way to ‘warm up’ esbuild if you plan on running it many times? I’d be passing in different entry points / outfile params, but because esbuild needs to start a process in the background (Node -> Go), I was wondering if there’s an idiomatic way to ‘boot’ esbuild?

Previously I was using `esbuild.startService` and I found that:

```go
esbuild.build({})
```

probably achieves the same goal. I also noticed there is `initialize` but that seems to be a browser-only API.

```ts
// This configures the browser-based version of esbuild. It is necessary to
// call this first and wait for the returned promise to be resolved before
// making other API calls when using esbuild in the browser.
//
// Works in node: yes
// Works in browser: yes ("options" is required)
export declare function initialize(options: InitializeOptions): Promise<void>;
```

Would one of these be recommended over the other? Thanks in advance.

**Comment by evanw** [comment]
I'd be open to allowing a no-op call to `initialize` in node for this. But `esbuild.build({})` should work fine for now.

**Comment by zaydek** [comment]
You have my vote for `esbuild.initialize()`.

**Comment by zaydek** [comment]
I updated the title to help reflect this suggestion. Feel free to close this at your discretion. Thanks Evan!
