### ISSUE TITLE
TypeScript enums error.

### ISSUE THREAD

**Issue by keelii** [evanw/esbuild#98]
ESBuild seems transform TS enum with unexpected result. But TS playground looks OK.

![correct](https://user-images.githubusercontent.com/458894/81472873-2fb81c00-922d-11ea-9fea-800af0b37319.png)

```ts
//  esbuild test.tsx
enum FlexParentDisplay {
    Flex = 'flex',
    InlineFlex = 'inline-flex',
    Block = 'block',
}
```

esbuild output this:

![esbuild-error](https://user-images.githubusercontent.com/458894/81472886-4cecea80-922d-11ea-9550-076e58b88dcb.png)

![esbuild-error-res](https://user-images.githubusercontent.com/458894/81472912-86bdf100-922d-11ea-8de4-63ed6aa065b7.png)

**Comment by evanw** [comment]
Thanks for the report. I wasn't aware of this difference in behavior in the TypeScript compiler. It looks like this applies only when you use a string or a no-substitution template literal. Will fix.
