### ISSUE TITLE
Log the API provided by `esbuild.initialize()`

### ISSUE THREAD

**Issue by masterchief01** [evanw/esbuild#981]
Before deprecation of the method `startService`, following code would return the options provided by esbuild `const x = await esbuild.startService(options)`. 

Since the release of `esbuild.initialize`, the return type of the same is `Promise<void>` and naturally a log of this would return `undefined`.

Is there some way to log the API provided by `esbuild` upon starting the service?

**Comment by evanw** [comment]
I don't really understand what you're saying, but there is no more service. You now just do this to use esbuild:

```js
const esbuild = require('esbuild')
const result = await esbuild.build(options)`
```

The API object is `esbuild` in this example (the return value of `require('esbuild')`). If you want to log it, you can do `console.log(esbuild)`. There is no longer a need to call something to get the API object.

**Comment by masterchief01** [comment]
This helps, thank you!
