### ISSUE TITLE
Could not resolve "..." (mark it as external to exclude it from the bundle)

### ISSUE THREAD

**Issue by Brian-McBride** [evanw/esbuild#993]
Is there a way to handle this in a plugin? 

This is from a library our team is using:
`Could not resolve "@nestjs/microservices" (mark it as external to exclude it from the bundle)`

Their codebase has entries like this:
```javascript
const { MicroservicesModule, } = optional_require_1.optionalRequire('@nestjs/microservices/microservices-module', () => require('@nestjs/microservices/microservices-module'));
```
```javascript
loadValidator() {
     return load_package_util_1.loadPackage('class-validator', 'ValidationPipe', () => require('class-validator'));
}
```

It would be great if I could handle this error. In all these cases it looks like a conditional function. 
I was thinking as a plugin I could run a check on the package tree to see if that package is even installed. If it isn't, then I can move this error into a warning. If it is in the package tree, then I would allow it to error out as it should be resolving.

**Comment by evanw** [comment]
Yes that should be possible. You could create an [`onResolve` plugin](https://esbuild.github.io/plugins/#resolve-callbacks) matching `^@nestjs/microservices.*` and then check whether the package is installed. If so, you could return `undefined` to allow esbuild to do its thing. If not, you could return `{ path, external: true }` to tell esbuild to not include that path in the bundle.

**Comment by Brian-McBride** [comment]
What I am more looking for is running a plugin where I check for the error. 

I won't know what package is being required conditionally. This was an example. I suppose I could fail the compile, then collect all the errors, see if I can auto-resolve them by adding those libs into the exclude array, and run esbuild again. 

Maybe that is just the best way.

**Comment by evanw** [comment]
Can't you call `require.resolve` or something equivalent from within the plugin to check for yourself whether the package is installed without needing to rely on an error from esbuild?

**Comment by evanw** [comment]
Closing due to lack of a reply, and since this is a question and not an issue with esbuild.
